### ISSUE TITLE
About Installing & Usage

### ISSUE THREAD

**Issue by mlhkr** [danielkrupinski/Osiris#1]
Hi,
I'm asking from here one more time in case someone needs it.
After compiling .dll file how to inject it / into which executable to inject it?
Any key combinations to use the .dll?

Thanks

**Comment by Hongarc** [comment]
You closed it but you should edit your issue your way.

You can check [Loading / Injecting into game process](https://github.com/danielkrupinski/Osiris#loading--injecting-into-game-process)
