### ISSUE TITLE
[suggestion] aimbot nearest

### ISSUE THREAD

**Issue by tacticalNukes** [danielkrupinski/Osiris#100]
The "nearest" bone if it's possible to make it for example if head is seen then shoot at the head but prioritise the bone that takes most damage

**Comment by effexcs** [comment]
That isn't impossible but it might be hard to achieve in a legit bot

**Comment by effexcs** [comment]
I've seen many rage cheats which have this

**Comment by Shaxzy** [comment]
You mean hitscan right? Why would you want this in a legitbot, it would look blatant tbh

**Comment by effexcs** [comment]
Yeah it's fine as it is

**Comment by Shaxzy** [comment]
This is a rage aimbot feature for a reason I think. Never seen it in any legitbot

**Comment by t9z** [comment]
> This is a rage aimbot feature for a reason I think. Never seen it in any legitbot

Works in a legitbot too. It only looks blatant if you are not so good with legit aim. If the cheat doesn't have weapon groups in aimbot, it's better to use nearest bone option instead of Head bone. Depending on your settings, you most likely don't want to hit headshots with an AWP of course.
