### ISSUE TITLE
Please add Bullet Tracer and Hitsounds !!

### ISSUE THREAD

**Issue by dispacc436** [danielkrupinski/Osiris#1000]
please !

**Comment by effex1337** [comment]
NO

**Comment by ZPDMiller** [comment]
Hitsounds are already in it

**Comment by Straightplus** [comment]
lel no

**Comment by dispacc436** [comment]
> Hitsounds are already in it

nope

**Comment by dispacc436** [comment]
> lel no

lel yes

**Comment by VuBrian22** [comment]
@dispacc436 Or learn to add it yourself. Don't be so rude and demanding you are turning into an Entitled Brat. Please stop.

**Comment by VuBrian22** [comment]
@effex1337 @Straightplus @ZPDMiller You guys are doing great!

**Comment by dispacc436** [comment]
@VuBrian22 ok  i will paste it my self thanks for replying .

**Comment by VuBrian22** [comment]
@dispacc436 Glad to see the better you. And no problem!

**Comment by woah1337** [comment]
> @effex1337 @Straightplus @ZPDMiller You guys are doing great!

autism spotted

**Comment by Straightplus** [comment]
lel

**Comment by Oly-UK** [comment]
#1434
