### ISSUE TITLE
Jackal inspired legit csgo esp

### ISSUE THREAD

**Issue by Chopard** [danielkrupinski/Osiris#1002]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/372302-jackal-inspired-legit-csgo-esp.html

https://www.youtube.com/watch?v=5EERwu3dQx8&feature=youtu.be

Please add!

**Comment by tirziz** [comment]
Meme feature but epic :)

**Comment by anonymouschicken1111** [comment]
This is fucking amazing
