### ISSUE TITLE
Delete this, nevermind

### ISSUE THREAD

**Issue by Slyember** [danielkrupinski/Osiris#1008]
Silent aim shoots at the floor with AA on

**Comment by num3rical** [comment]
This problem has been happening with me. How did you fix it?

**Comment by xAkiraMiura** [comment]
smoothing may be the problem.

**Comment by num3rical** [comment]
> 
> 
> smoothing may be the problem.

What do you mean by this? If you're talking about the smooth setting in the aimbot tab, I have that set to 1 for everything.

**Comment by xAkiraMiura** [comment]
smoothing requires a delay but if you are smoothing for 1 tick it only can go half way (you are shooting on the first tick)
2 ticks: 1/3rd way
3 ticks: 1/4th way

**Comment by num3rical** [comment]
> 
> 
> smoothing requires a delay but if you are smoothing for 1 tick it only can go half way (you are shooting on the first tick)
> 2 ticks: 1/3rd way
> 3 ticks: 1/4th way

I'm not sure how I would apply this knowledge to actually fixing the problem. It also doesn't explain how I have this problem but other people don't, since I would assume it would work the same for everyone.

**Comment by xAkiraMiura** [comment]
either disable smoothing or unbind your `+attack` key (or just dont use it) and use the aimbot's auto shot on key instead.

**Comment by num3rical** [comment]
> either disable smoothing or unbind your `+attack` key (or just dont use it) and use the aimbot's auto shot on key instead.

I already use auto shot on key, which is one of the side buttons of my mouse.
