### ISSUE TITLE
Edge Jump + Prediction System

### ISSUE THREAD

**Issue by xXTOO-HARDXx** [danielkrupinski/Osiris#1009]
Love what's been done with this project so far.

Although there's a problem with the Edge Jump feature; It uses a ray tracing method instead of an Engine Prediction System, which would work much much better, with 100% accuracy all of the time.

The Ray Tracing System is too inconsistent, especially in this situation. 

I consider this an issue because it is near impossible to make skill jumps like from Window to Cat on Mirage with such inconsistency.

All that needs to be done is to expand the SDK a bit, implement those newly added expansions to be updated during the PredictionSystem::Start function and whatnot, and then change the EdgeJump function to use the PredictionSystem::Start and PredictionSystem::Stop methods instead of Ray Tracing. Pseudocode:

int originalFlags = localplayer->getflags();

if (originalFlags & FL_ONGROUND && !(localplayer->GetFlags() & FL_ONGROUND))
{
      cmd->buttons |= IN_JUMP;
}

**Comment by notgoodusename** [comment]
if you want engine prediction just check this
https://github.com/danielkrupinski/Osiris/pull/832/commits/d8793720ffca94254c2aedc1c463d3c6ecffa3b1

**Comment by notgoodusename** [comment]
so i added the engine prediction and edgejump and works almost the same

**Comment by woah1337** [comment]
https://github.com/danielkrupinski/Osiris/issues/954 i literally said it sucks and someone c+ped it and made a pr and it got accepted LOL

**Comment by danielkrupinski** [comment]
Updated now.
