### ISSUE TITLE
[Surgestion] Team sided skinchanger

### ISSUE THREAD

**Issue by Straightplus** [danielkrupinski/Osiris#1014]
As title says^^ (So you would be able to toggle 1 skin for both teams or for one of the other, i just want some thoughts about it, personally i would love to see it be added :))

**Comment by ZPDMiller** [comment]
+1, Sensum has it and it uses nSkinz like Osiris, just saying if you'd like to try and copy it

**Comment by Abonilla17** [comment]
The newer version of sensum is no longer on github can do upload the source if you have it?

**Comment by ZPDMiller** [comment]
https://anonfile.com/x0WcY1Pen2/Sensum-master_zip

**Comment by xpossed-you** [comment]
why teamsided when you can go server-sided :)

**Comment by Straightplus** [comment]
lol not what i meant but ok
