### ISSUE TITLE
[QUESTION]Is it good for legit?

### ISSUE THREAD

**Issue by Entryon** [danielkrupinski/Osiris#1018]
is it enough if I add some junk code to use it for legit?

**Comment by tirziz** [comment]
Dont use on your main , this is open source after all.

**Comment by Straightplus** [comment]
1+ its p100 (xd)

**Comment by Entryon** [comment]
i've deleted some parts of the code that i didn't needed and added junk code and now it seems preety safe to use even on my main. I hope I won't get banned.

**Comment by xAkiraMiura** [comment]
junk code does nothing and removing the code means nothing if something downstream is sigged.
can we get an F for your main?

**Comment by notgoodusename** [comment]
> junk code does nothing and removing the code means nothing if something upstream is sigged.
> can we get an F for your main?

i mean, i have an acc with 120+ hours and i didnt get banned

**Comment by xAkiraMiura** [comment]
it may not be detected right now but if any valve employee decides to a critical part could get sigged that isn't that easy to just remove.

**Comment by MinecraftGoodGame** [comment]
Yeah I'm playing for over 3 months and 300 hours and I'm good, without junkcode or any major changes.

**Comment by xAkiraMiura** [comment]
i wasn't saying it was detected, i was just saying junkcode does nothing.
^ its very clearly not detected. as long as you don't rage you won't get banned.

the compiler will optimize out whatever junk code you put in it. also signatures check the assembly so unless you are breaking instructions up like ADD 5 to ADD 3 and ADD 2 or adding random NOPs then the signature doesnt change.

**Comment by MinecraftGoodGame** [comment]
Yeah, so no point of doing that

**Comment by streamshark** [comment]
> i wasn't saying it was detected, i was just saying junkcode does nothing.
> ^ its very clearly not detected. as long as you don't rage you won't get banned.
> 
> the compiler will optimize out whatever junk code you put in it. also signatures check the assembly so unless you are breaking instructions up like ADD 5 to ADD 3 and ADD 2 or adding random NOPs then the signature doesnt change.

overall I agree with you that junkcode isn't a good strategy, but a typical step when adding it is to disable optimizations in compiler settings. still, you can get detected with it easily

**Comment by craxking** [comment]
i have been using it on my main for 500 hours now.. no ban..
but yeah there is always a risk... so dont use it on account with expensive inventory.. also try not to rage in game

**Comment by craxking** [comment]
> > i wasn't saying it was detected, i was just saying junkcode does nothing.
> > ^ its very clearly not detected. as long as you don't rage you won't get banned.
> > the compiler will optimize out whatever junk code you put in it. also signatures check the assembly so unless you are breaking instructions up like ADD 5 to ADD 3 and ADD 2 or adding random NOPs then the signature doesnt change.
> 
> overall I agree with you that junkcode isn't a good strategy, but a typical step when adding it is to disable optimizations in compiler settings. still, you can get detected with it easily

disable optimization and then good luck with performance issue with your game

**Comment by anarbmw** [comment]
@notgoodusename @xAkiraMiura @Straightplus @tirziz 
100% safe to use, just download VAC Bypass Loader and update Osiris 2-3 time a week.
My main is nova 2 and supreme, 2 medals and bunch of skins.

**Comment by notgoodusename** [comment]
but with a press of a button valve could do a vac wave, i mean vac on 2017 detected vmt hooks after that there were undetected again and every time of some there will be a vac wave

**Comment by Straightplus** [comment]
yeah just dont cheat during the summer lol

**Comment by Straightplus** [comment]
btw y did you ping us?

**Comment by Straightplus** [comment]
@anarbmw

**Comment by anarbmw** [comment]
@Straightplus just like that xd

**Comment by Straightplus** [comment]
wat?
