### ISSUE TITLE
[Issue] Opening csgo process while cheat menu is open.

### ISSUE THREAD

**Issue by rosesware** [danielkrupinski/Osiris#1020]
- Basically, when I minimize CS:GO while cheat's menu is open, when I try to enter in CS:GO, game just don't enter (game in full-screen).

**I think It's a `ImGui` issue, but not sure.**
****
A while ago had one update in `ImGui` (I think It was), that allow us to minimize CS:GO while cheat's menu is open, but I don't really remember where is the code and I think that code isn't completed and makes this issue possible.

**Comment by danielkrupinski** [comment]
It was supposed to be fixed in 612d1c94ec53196e368ca924a6ae53ff3da1345c but it isn't fully.
