### ISSUE TITLE
help with skeleton esp 

### ISSUE THREAD

**Issue by WolfOGG** [danielkrupinski/Osiris#1021]
I have completely pasted in a skeleton esp and I got it to work but somehow i messed it up, must be something small, what am I missing? https://imgur.com/a/eMczYfE

p.s. ignore the fact that its taking the head dots place, im just testing it using that toggle.

**Comment by ZerGo0** [comment]
Well there is no functions 

> I have completely pasted in a skeleton esp and I got it to work but somehow i messed it up, must be something small, what am I missing? https://imgur.com/a/eMczYfE
> 
> p.s. ignore the fact that its taking the head dots place, im just testing it using that toggle.

darwLine only takes 4 vectors as argument, you set the color before you draw it with `interfaces.surface->setDrawColor(255, 255, 255, 255)`

**Comment by xAkiraMiura** [comment]
drawLine takes `int, int, int, int`, not vectors. try doing `sParent.x, sParent.y, sChild.x, sChild.y`

**Comment by WolfOGG** [comment]
I fixed it, thanks anyways!
