### ISSUE TITLE
Menu Customization Help!

### ISSUE THREAD

**Issue by contentshark** [danielkrupinski/Osiris#1022]
I want to change the opacity of the menu, how do I get away with doing this, also I want to make the edges of the menu not round. Is there anyway to do this maybe in imgui?

**Comment by effex1337** [comment]
style.alpha = 0.5f;
Or
ImGui::SetNextWindowBgAlpha(0.5f);

**Comment by fangshang132** [comment]
> style.alpha = 0.5f;
> Or
> ImGui::SetNextWindowBgAlpha(0.5f);

@effex1337 what is the difference of these two methods

**Comment by MinecraftGoodGame** [comment]
1 method changes alpha of entire menu while other change only a certain window

**Comment by fangshang132** [comment]
> 1 method changes alpha of entire menu while other change only a certain window

@MinecraftGoodGame @effex1337 where do i put it because when i do a search for it i cant find anything that already has that in it

**Comment by Straightplus** [comment]
omfg

**Comment by anonymouschicken1111** [comment]
> > 1 method changes alpha of entire menu while other change only a certain window
> 
> @MinecraftGoodGame @effex1337 where do i put it because when i do a search for it i cant find anything that already has that in it

We're not here to spoonfeed
