### ISSUE TITLE
How to modify default colors Allies/Enemies (Glow and ESP)

### ISSUE THREAD

**Issue by asmouman** [danielkrupinski/Osiris#1024]
Good Morning,

I need to know how to modify the default colors of Glow and ESP for the Allies and the Enemies

Regards

@danielkrupinski

**Comment by asmouman** [comment]
@danielkrupinski

**Comment by MinecraftGoodGame** [comment]
What do you mean?

**Comment by asmouman** [comment]
I would like to modify the default configuration of esp and glow, now I can modify elements in Config.h but this applies the same modifications for all Category, (Allies \ Enemies \ Planting \ Defusing \ Local player \ Weapons \ C4 \ Planted C4 \ Chickens \ Defuse kits \ Projectiles \ Hostages \ Ragdolls \). For example, I would select only Alliers and apply the color blue and red for Enemies.

Sorry my english is bad

**Comment by asmouman** [comment]
struct Glow {
        bool enabled{ true };
        bool healthBased{ false };
        float thickness{ 1.0f };
        float alpha{ 1.0f };
        int style{ 0 };
        Color color{ 255,0,0 };

    };

**Comment by MinecraftGoodGame** [comment]
You can still have different colors for allies and enemies, I don't get you

**Comment by asmouman** [comment]
I would like to apply my own default colors after injection. In my hack I would not like to give access to the color adjustment. You understand ?

**Comment by MinecraftGoodGame** [comment]
A solution might be to make a config with your desired colors and load it on inject

**Comment by asmouman** [comment]
please tell me how to do it ?

**Comment by xAkiraMiura** [comment]
find the function that runs when you click load and call it with your desired default config in Osiris.cpp at the bottom, in theory everything should initialize and then it will load the config.
^ or you could modify the options file but that doesn't let you easily modify the default without recompiling.

**Comment by MinecraftGoodGame** [comment]
Not on my computer so I can't test but I thibk config.load() is what you're looking for

**Comment by asmouman** [comment]
Tell me what to modify exactly. I'm a beginner. And It is possible to put my config file in the dll ? @xAkiraMiura @MinecraftGoodGame Many thanks for your answers

**Comment by MinecraftGoodGame** [comment]
Are you gonna share the dll? If not you can just create a normal config and just load it on inject

**Comment by asmouman** [comment]
I really want to automatically activate a default config after injection without accessing the settings. I will lock the settings to users in my hack. I would like to impose my own settings, my own colors.

**Comment by xAkiraMiura** [comment]
if you're a beginner then game hacking is not the place for you. [learncpp.com](https://www.learncpp.com/)

**Comment by anonymouschicken1111** [comment]
> if you're a beginner then game hacking is not the place for you. [learncpp.com](https://www.learncpp.com/)

I think u meant game hack programming

**Comment by asmouman** [comment]
I don't want cpp training, i just need help to make my own default configuration. Tell me what to change and where.

**Comment by danielkrupinski** [comment]
You have to add appriopriate constructors, example for glow:
```cpp
struct Glow {
    Glow(float r, float g, float b) : color{ r, g, b } { }
    Glow() = default;

    bool enabled{ false };
    bool healthBased{ false };
    float thickness{ 1.0f };
    float alpha{ 1.0f };
    int style{ 0 };
    Color color;
};

std::array<Glow, 21> glow{ {
    { 0.003f, 1.0f, 0.439f }, // Allies All
    {}, // Allies Visible - default
    {}, // Allies Occluded - default
    {}, // Enemies All - default
    { 0.94f, 0.07f, 0.745f } // Enemies Visible
    // rest - default
} };
```

**Comment by asmouman** [comment]
> You have to add appropriate constructors, example for glow:
> 
> ```c++
> struct Glow {
>     Glow(float r, float g, float b) : color{ r, g, b } { }
>     Glow() = default;
> 
>     bool enabled{ false };
>     bool healthBased{ false };
>     float thickness{ 1.0f };
>     float alpha{ 1.0f };
>     int style{ 0 };
>     Color color;
> };
> 
> std::array<Glow, 21> glow{ {
>     { 0.003f, 1.0f, 0.439f }, // Allies All
>     {}, // Allies Visible - default
>     {}, // Allies Occluded - default
>     {}, // Enemies All - default
>     { 0.94f, 0.07f, 0.745f } // Enemies Visible
>     // rest - default
> } };
> ```

Nice thank you i love u @danielkrupinski  it's perfect

**Comment by asmouman** [comment]
Just last question @danielkrupinski how to enable esp name ?


struct Esp {
        struct Shared {
            bool enabled{ true };
            int font{ 0x1d };
            ColorToggle snaplines;
            ColorToggle box;
            int boxType{ 0 };
            ColorToggle name;
            ColorToggle outline{ 0.0f, 0.0f, 0.0f };
            ColorToggle distance;
            float maxDistance{ 0.0f };
        };
       
        struct Player : public Shared {
            ColorToggle eyeTraces;
            ColorToggle health;
            ColorToggle healthBar;
            ColorToggle armor;
            ColorToggle armorBar;
            ColorToggle money;
            ColorToggle headDot;
            ColorToggle activeWeapon;
            bool deadesp { false };
        };

**Comment by danielkrupinski** [comment]
```cpp
struct ColorToggle : public Color {
    ColorToggle() = default;
    ColorToggle(bool enabled) : enabled{ enabled } { }
    ColorToggle(float r, float g, float b) : Color{ r, g, b } { }

    bool enabled{ false };
};

// inside esp struct
ColorToggle name{ true };
```

**Comment by asmouman** [comment]
it works but i can't combine :

ColorToggle name{ true };
**and**
ColorToggle name{ 0.003f, 1.0f, 0.439f };

How to enable esp name and select the color of esp name

**Comment by danielkrupinski** [comment]
Define appropriate constructor for that, I'm not gonna do everything for you.

**Comment by thomas0aotian** [comment]
I think he defined it already

**Comment by xAkiraMiura** [comment]
> 
> 
> > if you're a beginner then game hacking is not the place for you. [learncpp.com](https://www.learncpp.com/)
> 
> I think u meant game hack programming

we are on a programming platform so its implied.

@thomas0aotian explain why you disliked my comment? would you say that game hacking is a beginner friendly safe space where absolutely nobody gets flamed for pasting or not knowing basic programming things?
^ stop being spiteful that you're on the wrong side.

**Comment by asmouman** [comment]
> Define appropriate constructor for that, I'm not gonna do everything for you.

@danielkrupinski I really tried for hours I can't do it I only have errors.

**Comment by xAkiraMiura** [comment]
# stop trying to reap the benefits without working for it.
learn c++ half of us here did and maybe you can do it.
**if you're not going to learn to code then just go buy a p2c like aimware**

**Comment by asmouman** [comment]
> # stop trying to reap the benefits without working for it.
> learn c++ half of us here did and maybe you can do it.
> **if you're not going to learn to code then just go buy a p2c like aimware**

**I learn by practicing leave me alone, do you have a problem with me ?**

**Comment by asmouman** [comment]
I will propose an improved code to create default configurations. I work on it

**Comment by xAkiraMiura** [comment]
> I need to know how to modify the default colors of Glow and ESP for the Allies and the Enemies

> I would like to apply my own default colors after injection. In my hack I would not like to give access to the color adjustment. You understand ?

> please tell me how to do it ?

> Just last question @danielkrupinski how to enable esp name ?

> Joined 2 days ago

thats a whole lot of learning i see there. you are not practicing, you are pasting. **you cannot learn programming by pasting**

as i said before, go learn general programming before you try to do game hacking, 
if you cannot understand basic c++ then you definitely won't be able to reverse engineer an entire game.

for instance, whats the difference between stdcall, thiscall, and fastcall? you will crash if you use the wrong one on a function hook.
additionally, how can we use a pointer to an object to call a member function?

If you really want to step into hacking before general programming then I recommend you try externals first, you will actually be able to learn off of that unlike internals where you probably won't understand whats going on for the first few **months**.

I do not have a problem with you, I just don't like it when people leech off others without giving any real effort to improve themselves.
