### ISSUE TITLE
Material group; how to get them?

### ISSUE THREAD

**Issue by MinecraftGoodGame** [danielkrupinski/Osiris#1025]
I am trying to make a proper nightmode, but despite colormodulating World and StaticProp there are still some unmodulated textures, and my question is - how can I get the name of the group? Example:
https://imgur.com/a/YlZDseT

**Comment by xAkiraMiura** [comment]
best bet would to be to decompile the .BSP and open it in hammer, if you open the object properties it will tell you its type (e.g. func_detail, prop_dynamic, prop_static)

**Comment by danielkrupinski** [comment]
Those boxes are rendering by engine using fastpath, that's why they can't be color modulated.
It looks like the boxes are **brushes** so fastpath can be turned off by setting `cl_brushfastpath` cvar to **0**.
