### ISSUE TITLE
how to change key open menu?

### ISSUE THREAD

**Issue by advancedz** [danielkrupinski/Osiris#1026]
I would like to change key open menu (insert key ) to anything I want? what source i should to change?

**Comment by MinecraftGoodGame** [comment]
You don't have to, you can change it in the menu

**Comment by dctrlight** [comment]
You can change it within the cheat itself

**Comment by advancedz** [comment]
oh! thank  . i found it   . open menu  ---> misc menu --> menu key   and change key
