### ISSUE TITLE
FPS issues.

### ISSUE THREAD

**Issue by SapphireCodenz** [danielkrupinski/Osiris#1027]
So I downloaded the new osiris update and compiled it 2 days ago, and my CPU usage is going for like 70%-80%, my specs are:
8 GB RAM
IGD Core i5-3330 @ 3.00 GHz
64 bit OS.

**Comment by xAkiraMiura** [comment]
Try enabling the AVX/AVX2 instruction set in build settings if you have them on your CPU.
Are you GPU limited or CPU limited?
If you're GPU limited then disable things like disable model occlusion and set it to lowest everything.
If you're CPU limited then you can try disable multi core rendering.
^ bit dangerous but if you can overclock it will help you a bit. (my CPU goes up to 120%)

**Comment by NexSqaud** [comment]
1. Compile cheat with AVX support (not sure your CPU support AVX2)
2. Buy new CPU
3. Buy new PC

**Comment by talk2g** [comment]
@NexSqaud  can u helpme find the avx option in build/project settings.
i cant seem to find it.
