### ISSUE TITLE
[QUESTION] One Windows Style - Default

### ISSUE THREAD

**Issue by itchy2019** [danielkrupinski/Osiris#1030]
Question: 
What part of the code should I change so the cheat starts in one window style by default?

thank you!

**Comment by WolfOGG** [comment]
Go to your config.h file and change this `int menuStyle{ 0 };` to `int menuStyle{ 1 };` 0 by default means that you get the window bar, 1 makes the one window style to your default.

**Comment by itchy2019** [comment]
Thank you very much!

**Comment by xAkiraMiura** [comment]
better method: edit Osiris.cpp to run config.load after everything is loaded, at injection time it will auto load.
you can modify the default config without having to recompile the entire project.
