### ISSUE TITLE
Drawing aimbot FOV circle

### ISSUE THREAD

**Issue by Nexo848** [danielkrupinski/Osiris#1032]
So i wanted to draw aimbot fov circle, i made this in Aimbot::run function:
![Screenshot_3](https://user-images.githubusercontent.com/54820747/73247505-4623f580-41b1-11ea-9f4f-a61dc5f687a2.png)
DEG2RAD is:
![Screenshot_4](https://user-images.githubusercontent.com/54820747/73247518-4d4b0380-41b1-11ea-88a7-84523d74a2d5.png)
playerFov is hooked here:
![Screenshot_5](https://user-images.githubusercontent.com/54820747/73247574-779cc100-41b1-11ea-869f-9d0f1eeafe8c.png)
I tried many other things, but now i dont know whats wrong, maybe you can help.

**Comment by MinecraftGoodGame** [comment]
Try to move it into a new function and call it in painttraverse if you didn't

**Comment by Nexo848** [comment]
I tried this already, effect was same: nothing shows up

**Comment by xAkiraMiura** [comment]
instead of using override view couldn't you just use ISurface?
also what editor/theme are you using

**Comment by Nexo848** [comment]
What do u mean by ISurface, is there any functon to get player fov? Also i moved it to other function:
![Screenshot_3](https://user-images.githubusercontent.com/54820747/73304229-270c7e80-4218-11ea-8169-07dae9c0bac6.png)
My theme is:
[PaleNight.zip](https://github.com/danielkrupinski/Osiris/files/4124530/PaleNight.zip)

**Comment by xAkiraMiura** [comment]
oh sorry, i thought that was trying to do the rendering, didn't see it was getting the FOV.
the entity class has a netvar `m_iFov`. `localPlayer->fov`?
does it not work when getting the fov or when trying to render?

**Comment by Nexo848** [comment]
okay, i changed it to the entity class netvar, but it still not working. i dont know on which point it fails, but i think it is getting fov or calculating radius.

**Comment by ZerGo0** [comment]
I'm not 100% sure if I'm getting you are trying to achieve, but I'm going to post this regardless. There have been multiple attempts on drawing the aimbot fov, here is an example: https://github.com/danielkrupinski/Osiris/pull/827/files

**Comment by xAkiraMiura** [comment]
attach a debugger, drop a breakpoint on your fov grabbing line, go into the autos tab, single step over, and you should be able to see its value.

**Comment by xAkiraMiura** [comment]
if you got it to work accurately could you make a pull request if you are okay with it being public?
