### ISSUE TITLE
../Osiris.dll is not a valid win32 application

### ISSUE THREAD

**Issue by Cicker21** [danielkrupinski/Osiris#1033]
All .cpp were successfully compiled, but when **Visual Studio 2019** finish the compilation i got this error:
(It's setted as `Release | x86`, my OS is W10 x64)

![image](https://user-images.githubusercontent.com/60420691/73332821-d456b500-425f-11ea-8cb6-74ca038a65c5.png)

**Comment by MinecraftGoodGame** [comment]
This means that you compiled succesfully, but Windows cannot open standalone dll files, you will need to use an injector to inject it into the game.

**Comment by Cicker21** [comment]
Do you recommend any?

**Comment by MinecraftGoodGame** [comment]
Just use any to be honest, it shouldn't matter unless you use a public, popular and a bit old injector, or you can make one yourself, pretty sure there are tutorials for that.

**Comment by Cicker21** [comment]
One by myself? looks hard haha, thanks for all guy
