### ISSUE TITLE
How to make real angle thirdperson?

### ISSUE THREAD

**Issue by paddy41601** [danielkrupinski/Osiris#1034]
How to make real angle thirdperson?
I want to show anti-aim angle with thirdperson.
I try setviewangle ,but it will change both camera angle and animation.
Is there any good way or source to achieve that?
Sorry for my bad English.

**Comment by xAkiraMiura** [comment]
# duplicate issue, please search next time.
https://github.com/danielkrupinski/Osiris/issues <-- there exists a search box 

i wrote instructions in #1010. we gave enough information that you can create it.

**Comment by notgoodusename** [comment]
> # duplicate issue, please search next time.
> https://github.com/danielkrupinski/Osiris/issues <-- there exists a search box
> 
> i wrote instructions in #1010. we gave enough information that you can create it.

did you make it?

**Comment by paddy41601** [comment]
> # duplicate issue, please search next time.
> https://github.com/danielkrupinski/Osiris/issues <-- there exists a search box
> 
> i wrote instructions in #1010. we gave enough information that you can create it.

I think this is kind of difference.
I want to set local view angle to my real angle in third person instead of chams it.
but I didn't find the proper function to call.(as i mentioned,call setviewangle will change both camera and animation angle)

**Comment by xAkiraMiura** [comment]
the instructions change the local player, not creating new chams.
modify `info.angles` in the DrawModelExecute hook to your real angles ([obtained from before the end of CreateMove](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hooks.cpp#L166))

**Comment by notgoodusename** [comment]
i personally do changes on viewangles on frame render start and change my foot to lby(with another animstate)

**Comment by DoomFishWasTaken** [comment]
made a pull, close this #1546
