### ISSUE TITLE
How to get if player is in fov

### ISSUE THREAD

**Issue by notgoodusename** [danielkrupinski/Osiris#1035]
so i wrote a knifebot, the problem is when someone is behind me it tries to stab him like he is infront of me, so a good option would be to get in fov, i tried triggerbotting but it works only when i am aiming directly at them which sucks, i could use this method but with a bigger hitbox(how to do that?)

**Comment by xAkiraMiura** [comment]
What does world 2 screen return if someone is off screen? does it max out at your resolution or does it continue?
if it does continue and its larger than your screen size they are probably out of view.

**Comment by notgoodusename** [comment]
> What does world 2 screen return if someone is off screen? does it max out at your resolution or does it continue?
> if it does continue and its larger than your screen size they are probably out of view.

that only returns 204(true), i debbug it

**Comment by ruffi123456789** [comment]
Calculate Angle to look at player, if (CalculatedAngle - CurrentAngle).Distance2D() > fov player is not in fov then. (I'm not exactly sure if you need to use Distance2D, just google it)

Btw. World2Screen should only return true when the converted position is visible on screen.
