### ISSUE TITLE
game update

### ISSUE THREAD

**Issue by Bywnb** [danielkrupinski/Osiris#1036]
i know GetCSWeaponData is 459
has any other index changed?

**Comment by CerberusGame** [comment]
GetInaccuracy() 481
GetSpread() 451
UpdateAccuracyPenalty() 482
GetCSWpnData() 459
GetName() 385

**Comment by Bywnb** [comment]
> GetInaccuracy() 481
> GetSpread() 451
> UpdateAccuracyPenalty() 482
> GetCSWpnData() 459
> GetName() 385

i update osiris including GetInaccuracy and GetCSWpnData , but still crush.Can u help me plz.

**Comment by EurobeatClub** [comment]
Update isn't crashing me but aimbot did stop working.

**Comment by Bywnb** [comment]
> Update isn't crashing me but aimbot did stop working.

yep, aimbot not works

**Comment by ZerGo0** [comment]
Just attach a debugger and see which value doesn't update/return anything. Waiting for someone to fix it would probably also work.

**Comment by ifoverload** [comment]
> GetInaccuracy() 481
> GetSpread() 451
> UpdateAccuracyPenalty() 482
> GetCSWpnData() 459
> GetName() 385

to me it does crashing

**Comment by simonsmh** [comment]
```
struct WeaponData {
    std::byte pad1[4];   //0x0000
    char *name;          //0x0004
    std::byte pad1_[12]; //0x0008
    int maxClip;         //0x0014
    std::byte pad2[180]; //0x0018
    int type;            //0x00CC
    std::byte pad2_[28]; //0x00D0
    bool fullAuto;       //0x00EC
    std::byte pad3[3];   //0x00ED
    int damage;          //0x00F0
    float armorRatio;    //0x00F4
    int bullets;         //0x00F8
    float penetration;   //0x00FC
    std::byte pad4[8];   //0x0100
    float range;         //0x0108
    float rangeModifier; //0x010C
    std::byte pad5[16];  //0x0110
    bool silencer;       //0x0120
    std::byte pad6[15];  //0x0121
    float maxSpeed;      //0x0130
    float maxSpeedAlt;   //0x0134
};
```
https://github.com/simonsmh/Osiris/commit/9d730c5fa956b4f7bc84e25fa3e23ebeaa622efb

**Comment by h4x0reL** [comment]
Just change this two bad boys and work good.
GetInaccuracy() 481
GetWeaponData() 459

**Comment by Asviix** [comment]
I'm compiling it with new indexes, I be right be to you if it works

**Comment by Bywnb** [comment]
> Just change this two bad boys and work good.
> GetInaccuracy() 481
> GetWeaponData() 459

not really, i changed both and it works well , but it crashed in my friend's computer

**Comment by h4x0reL** [comment]
For me works fine ;)

**Comment by Asviix** [comment]
Works perfectly with the two indexes changed

> Just change this two bad boys and work good.
> GetInaccuracy() 481
> GetWeaponData() 459

Good job @h4x0reL !

**Comment by 4rist0** [comment]
> For me works fine ;)

Hey, I don't know anything about coding, could you upload your dll to mediafire or something and share it to here please? Thank you!

**Comment by simonsmh** [comment]
getWeaponSubType() 281

**Comment by 4rist0** [comment]
> getWeaponSubType() 281
> > For me works fine ;)
> 
> Hey, I don't know anything about coding, could you upload your dll to mediafire or something and share it here please? Thank you!

please :/

**Comment by Asviix** [comment]
@4rist0 

If you have any problem just ask me
[Osiris.zip](https://github.com/danielkrupinski/Osiris/files/4133822/Osiris.zip)

**Comment by 4rist0** [comment]
> @4rist0
> 
> If you have any problem just ask me
> [Osiris.zip](https://github.com/danielkrupinski/Osiris/files/4133822/Osiris.zip)

Hello, that's not a sln file how can make it a dll?

**Comment by Asviix** [comment]
It's already compiled, just inject it and you're done.

**Comment by 4rist0** [comment]
> It's already compiled, just inject it and you're done.

Hmm, Are you sure? Because i only see a file but it's not dll :/ could you check it again please?

**Comment by Asviix** [comment]
> > It's already compiled, just inject it and you're done.
> 
> Hmm, Are you sure? Because i only see a file but it's not dll :/ could you check it again please?

I accidentally removed the file extension while renaming it, just add ".dll" at the end of the file and it should work just fine :)

**Comment by ifoverload** [comment]
> getWeaponSubType() 281

thanks

**Comment by 4rist0** [comment]
> > > It's already compiled, just inject it and you're done.
> > 
> > 
> > Hmm, Are you sure? Because i only see a file but it's not dll :/ could you check it again please?
> 
> I accidentally removed the file extension while renaming it, just add ".dll" at the end of the file and it should work just fine :)

Yea, I just did that :p but didnt try to inject yet, also don't get me wrong but normally the dll size is 600kb but your is 2.5mb, why is that?

**Comment by Asviix** [comment]
That's weird I actually didn't noticed that, it works fine for me but if you don't want to inject it (which is totally fine) I can explain to you step by step how to modify the files and compile it :p

**Comment by 4rist0** [comment]
> That's weird I actually didn't noticed that, it works fine for me but if you don't want to inject it (which is totally fine) I can explain to you step by step how to modify the files and compile it :p

Ah, but that would be a big effort for you and i am not sure it's worth for you? :D

**Comment by Asviix** [comment]
> > That's weird I actually didn't noticed that, it works fine for me but if you don't want to inject it (which is totally fine) I can explain to you step by step how to modify the files and compile it :p
> 
> Ah, but that would be a big effort for you and i am not sure it's worth for you? :D

Don't worry it's not very hard to do :D
Just add me on Discord (Asviix#1934)

**Comment by 4rist0** [comment]
> > > That's weird I actually didn't noticed that, it works fine for me but if you don't want to inject it (which is totally fine) I can explain to you step by step how to modify the files and compile it :p
> > 
> > 
> > Ah, but that would be a big effort for you and i am not sure it's worth for you? :D
> 
> Don't worry it's not very hard to do :D
> Just add me on Discord (Asviix#1934)
Thanks for your help, buddy!

**Comment by Kodikusik** [comment]
Great! It works now. ur great :)

**Comment by Havoccboi** [comment]
> > Just change this two bad boys and work good.
> > GetInaccuracy() 481
> > GetWeaponData() 459
> 
> not really, i changed both and it works well , but it crashed in my friend's computer

where do I find these two?

**Comment by NexSqaud** [comment]
@Havoccboi Entity.h

**Comment by asmouman** [comment]
> > > That's weird I actually didn't noticed that, it works fine for me but if you don't want to inject it (which is totally fine) I can explain to you step by step how to modify the files and compile it :p
> > 
> > 
> > Ah, but that would be a big effort for you and i am not sure it's worth for you? :D
> 
> Don't worry it's not very hard to do :D
> Just add me on Discord (Asviix#1934)

J’ai vu que tes Français je t’ai add sur Discode poto
