### ISSUE TITLE
new chams(real/fake)

### ISSUE THREAD

**Issue by aFakeCmd** [danielkrupinski/Osiris#1039]
after watching how chams are created, I don’t understand how to create real / fake AA chams, please help

**Comment by NekoRem** [comment]
I just recalculate matrix and call dme twice with original angles (real) and new angles (fake)

**Comment by xAkiraMiura** [comment]
1. override your material for your fake chams
2. set the info.angles to your fake
3. call the original draw model execute
4. override your material for your real chams
5. set the info.angles to your real 
6. call the original draw model execute

all of this should occur in 1 function call.

**Comment by aFakeCmd** [comment]
> 1. override your material for your fake chams
> 2. set the info.angles to your fake
> 3. call the original draw model execute
> 4. override your material for your real chams
> 5. set the info.angles to your real
> 6. call the original draw model execute
> 
> all of this should occur in 1 function call.

I do not quite understand how to implement 2,3, can you give an example?
