### ISSUE TITLE
Prime issues

### ISSUE THREAD

**Issue by Cicker21** [danielkrupinski/Osiris#1043]
I dont know why but i tried the "Fake Prime" option and when i found a match all my other functions stop working, included the overlay to set/unset this option. By the moment i wont use it again...

**Comment by MinecraftGoodGame** [comment]
Are you sure you didn't missclick the "Unhook" button?

**Comment by Cicker21** [comment]
I feel stupid ... 
Thx for solving my issues +rep bro
