### ISSUE TITLE
Custom Clantag doesn't work

### ISSUE THREAD

**Issue by spy12085621** [danielkrupinski/Osiris#1044]
At this current source build, typing anything on custom clantag and enabling it won't do a thing.

**Comment by NekoRem** [comment]
Enable the checkbox then modify the text in the inputbox

**Comment by anarbmw** [comment]
clock tag doesnt work tho
@NekoRem

**Comment by ZerGo0** [comment]
> clock tag doesnt work tho
> @NekoRem

Enable Custom Clantag and ClockTag: https://github.com/danielkrupinski/Osiris/blob/1100fa092b363ed7d139d2d75c4a10c2faa40922/Osiris/Hacks/Misc.cpp#L77
