### ISSUE TITLE
Blockbot... Help. :(

### ISSUE THREAD

**Issue by Evilhelder** [danielkrupinski/Osiris#1045]
Does anyone have the osiris version code with "blockbot"?

I lost the project when I formatted the computer, and now I only have the DLL that stopped working after the last update ...

I just want the blockbot code, so I can add it to the osiris update...

**Comment by NekoRem** [comment]
Yes i might make a pull request with it later

**Comment by AbdallahMehiz** [comment]
Check this out #739

**Comment by Evilhelder** [comment]
> 
> 
> Check this out #739

The blockbot was removed from the code for that version, and the code that I found from the old version doesn't match the new one anymore, it doesn't have the variable "calcangle" and "distance" ....

I tried to make it work, but to no avail.

**Comment by NekoRem** [comment]
#1048
