### ISSUE TITLE
Enable esp name and choose a default color for the different players

### ISSUE THREAD

**Issue by asmouman** [danielkrupinski/Osiris#1047]
Hi guys,

I know I'm annoying but please I haven't found any solutions

following my post #1024 where @danielkrupinski  helped me well

I want enable esp name/esp box and choose a default color for the different players

//1 Allies All
//2 Allies Visible - default
//3 Allies Occluded - default
//4 Enemies All - default
//5 Enemies Visible
//6 Enemies Occluded

This is my code now : 

**My problem is that i can't combine :**

**ColorToggle name{ true };
**and**
ColorToggle name{ 0.003f, 1.0f, 0.439f };**

```
struct ColorToggle : public Color {
ColorToggle() = default;
ColorToggle(bool enabled) : enabled{ enabled } { }
ColorToggle(float r, float g, float b) : Color{ r, g, b } { }

struct Esp {
        struct Shared {
            bool enabled{ true };
            int font{ 22 };
            ColorToggle snaplines;
            ColorToggle box{ true };
            int boxType{ 0 };
            ColorToggle name{ true };
            ColorToggle outline{ true };
            ColorToggle distance;
            float maxDistance{ 0.0f };
        };


        struct Player : public Shared {
            ColorToggle eyeTraces;
            ColorToggle health{ true };
            ColorToggle healthBar;
            ColorToggle armor;
            ColorToggle armorBar;
            ColorToggle money;
            ColorToggle headDot;
            ColorToggle activeWeapon{ true };
            bool deadesp{ false };
        };

        struct Weapon : public Shared { 
            
            ColorToggle box{ false };
            ColorToggle name{ false };
            ColorToggle outline{ false };

        
        }
        
        weapon{ {
        { false }//1 Weapon - default

    } };

        struct Projectile : public Shared {};
        std::array<Projectile, 9> projectiles{ {
        { false }, //1 Flashbang - default
        { false }, //2 HE Grenade - default
        { false }, //3 Breach Charge - default
        { false }, //4 Bump Mine - default
        { false }, //5 Decoy Grenade - default
        { false },//6 Molotov - default
        { false }, //7 TA Grenade - default
        { false }, //8 Smoke Grenade - default
        { false } //9 Snowball - default

    } };

        struct DangerZone : public Shared { };
        std::array<DangerZone, 18> dangerZone{ {
        { false }, //1 Sentries - default
        { false }, //2 Drones - default
        { false }, //3 Cash - default
        { false }, //4 Cash Dufflebag - default
        { false }, //5 Pistol Case - default
        { false },//6 Light Case - default
        { false }, //7 Heavy Case - default
        { false }, //8 Explosive Case - default
        { false }, //9 Tools Case - default
        { false }, //10 Full Armor - default
        { false }, //11 Armor - default
        { false },//12 Helmet - default
        { false }, //13 Parachute - default
        { false }, //14 Briefcase - default
        { false }, //15 Tablet Upgrade - default
        { false }, //16 Exojump - default
        { false }, //17 Ammobox - default
        { false }//18 Radar Jammer - default

    } };

        std::array<Player, 6> players{ {
        { true }, //1 Allies All
        { false }, //2 Allies Visible - default
        { false }, //3 Allies Occluded - default
        { true }, //4 Enemies All - default
        { false }, //5 Enemies Visible
        { false }//6 Enemies Occluded

    } };





    } esp;
```

THANKS for ur help!

**Comment by xAkiraMiura** [comment]
# [learncpp.com](https://learncpp.com)
you can't make them have the same variable name ffs.

just do:
`ColorToggle name{ true };`
`ColorToggle color{ 0.003f, 1.0f, 0.439f };`
or something like that.

**Comment by asmouman** [comment]
**LOL, I listened to your advice I regularly look at this site**



> # [learncpp.com](https://learncpp.com)
> you can't make them have the same variable name ffs.
> 
> just do:
> `ColorToggle name{ true };`
> `ColorToggle color{ 0.003f, 1.0f, 0.439f };`
> or something like that.

Nop it's not correct in this situation and I would like to apply different colors depending on the players

//1 Allies All
//2 Allies Visible - default
//3 Allies Occluded - default
//4 Enemies All - default
//5 Enemies Visible
//6 Enemies Occluded

**Comment by notgoodusename** [comment]
Just go to config.h or config.cpp and search for glow and mess around with it

**Comment by asmouman** [comment]
> Just go to config.h or config.cpp and search for glow and mess around with it

I think you did not understand my request

**Comment by notgoodusename** [comment]
> > Just go to config.h or config.cpp and search for glow and mess around with it
> 
> I think you did not understand my request

oh sorry i think you are right anyways a good way of doing this is by forcing a color every time you inject it(once)
so you do
static bool random = true;
if(random)
{
//set your color here
random = false;
}

**Comment by asmouman** [comment]
I would like this by default when the cheat is injected without configuration

[https://serving.photos.photobox.com/2558424217f94e79df7336603c2ac7d1ef66fdae6de884085746882a05fd461de01c9d3d.jpg](url)

**Comment by notgoodusename** [comment]
> I would like this by default when the cheat is injected without configuration
> 
> [https://serving.photos.photobox.com/2558424217f94e79df7336603c2ac7d1ef66fdae6de884085746882a05fd461de01c9d3d.jpg](url)

that url doesnt exist

**Comment by asmouman** [comment]
https://serving.photos.photobox.com/2558424217f94e79df7336603c2ac7d1ef66fdae6de884085746882a05fd461de01c9d3d.jpg

**Comment by notgoodusename** [comment]
you can go to esp search for all those things do what i said and for red you do (255,0,0) and for green you do (0,255,0)

**Comment by asmouman** [comment]
lol it's not that easy bro

**Comment by notgoodusename** [comment]
example 
if (config.snaplines.enable)
static bool random = true;
if(random){
float color[3] =(255,0,0);
                interfaces.surface->setDrawColor(color);
}

**Comment by notgoodusename** [comment]
you cant do colortoggle something{color}
because is a toggle

**Comment by asmouman** [comment]
> example
> if (config.snaplines.enable)
> static bool random = true;
> if(random){
> float color[3] =(255,0,0);
> config.esp.snaplines.color = color;
> interfaces.surface->setDrawColor(config.esp.snaplines.color);
> }

where should i put this code

**Comment by asmouman** [comment]
> you cant do colortoggle something{color}
> because is a toggle

do you have discord

**Comment by notgoodusename** [comment]
> > you cant do colortoggle something{color}
> > because is a toggle
> 
> do you have discord

send yours and ill acept it

**Comment by asmouman** [comment]
> > > you cant do colortoggle something{color}
> > > because is a toggle
> > 
> > 
> > do you have discord
> 
> send yours and i will add you

speedycratos#0686

**Comment by xAkiraMiura** [comment]
> **My problem is that i can't combine :**
>
> **ColorToggle name{ true };**
> **and**
> **ColorToggle name{ 0.003f, 1.0f, 0.439f };**

> Nop it's not correct in this situation and I would like to apply different colors depending on the players

???

is the problem you can't combine variables or you need to apply different colors?

**Comment by asmouman** [comment]
both

**Comment by asmouman** [comment]
@danielkrupinski can u help me pls ?
