### ISSUE TITLE
Anti-aim problem

### ISSUE THREAD

**Issue by Nexo848** [danielkrupinski/Osiris#1049]
Hi, so i wanted to expand antiaim someway, i added some yaws:
![Screenshot_4](https://user-images.githubusercontent.com/54820747/73575993-b19fe880-4479-11ea-87d8-8cf05457f4cb.png)
Unfortunally its not working, any ideas what gone wrong?

**Comment by notgoodusename** [comment]
use switch instead of if, if you refer to not seeing your angles then there is nothing wrong, also i see that you did cmd->tickcount & 1 which will always be true because any int can be divided by 1 an return itself use 2 for it to work

**Comment by notgoodusename** [comment]
Also i see you did SIDEMOVE which is totally diferent from VIEWANGLES do cmd->viewangles instead and should ready to go

**Comment by Nexo848** [comment]
should it be visible to other players? because im testing it with my friend, and he is saying if it works of not.

**Comment by Nexo848** [comment]
he only see pitch down/up

**Comment by Nexo848** [comment]
i tested it, and it not works like that, still something not works
![Screenshot_5](https://user-images.githubusercontent.com/54820747/73577316-d5186280-447c-11ea-93f6-7535689591a6.png)

**Comment by notgoodusename** [comment]
because chocked packets cant be seen by other player you have to do if(!sendpacket) (not visible angle)
if(sendpacket) (visible angle)

**Comment by Nexo848** [comment]
okay, thank u, it working now
