### ISSUE TITLE
AA nadefix & AA method crash

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#1050]
I try to add both of this and i got randomly crash . 

More AA methods. #989
AA on nade fix #432

Anyone know how to fix this crash?

Here is my AntiAim.cpp 

I only change this part 

 	static bool bFlip = false;

        const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());

        const auto activeWeapon = localPlayer->getActiveWeapon();

        auto itemindex = getWeaponIndex(activeWeapon->itemDefinitionIndex2());

        if (config.antiAim.enabled && !activeWeapon->isInThrow())

... etc etc }

Edit: when i debug it say the problem come from this line 

        if (config.antiAim.enabled && !activeWeapon->isInThrow())

**Comment by xAkiraMiura** [comment]
i would just add a check `if (cmd->buttons & IN_ATTACK)` or similar.
i think isInThrow() fails because you are holding something that isn't a grenade.

**Comment by notgoodusename** [comment]
> i would just add a check `if (cmd->buttons & IN_ATTACK)` or similar.
> i think `isInThrow()` fails because you are holding something that isn't a grenade.

i made mine aa nade fix with including grenades in it

**Comment by danielkrupinski** [comment]
Add null pointer checks.

**Comment by dapaster** [comment]
> 
> 
> Add null pointer checks.

Thanks Daniel
