### ISSUE TITLE
movement recorder

### ISSUE THREAD

**Issue by crtezgod** [danielkrupinski/Osiris#1051]
i saw this thing in some other cheats and i think its very useful
so it would be good to see it in Osiris
any opinions?

**Comment by xAkiraMiura** [comment]
how is this useful? we aren't doing any machine learning.
if you say it's for when they run away ESP is much more effective.

**Comment by crtezgod** [comment]
> 
> 
> how is this useful? we aren't doing any machine learning.
> if you say it's for when they run away ESP is much more effective.

nah its not that
u record some hops like window to catwalk and you can play it back with 100% accuracy
here's a video about it: https://www.youtube.com/watch?v=4rU54zKoPxE&t=115s

**Comment by xAkiraMiura** [comment]
oh, that's actually pretty cool, it would take a lot of work to implement, however.

**Comment by effex1337** [comment]
https://cdn.otaku.ooo/d39qi.mp4
My Attempt to Implement this(watch full)
;)

**Comment by WolfOGG** [comment]
I had this on an old old OLD version of Osiris but for nades throws. BTW thanks @effex1337 for the menu you made, I now use a heavily modified version of it as my main and only menu :wink: https://imgur.com/a/yYknX2M
