### ISSUE TITLE
[Question] Is it possible to add another layer for the chams?

### ISSUE THREAD

**Issue by OOF-RIF** [danielkrupinski/Osiris#1052]
Title

**Comment by danielkrupinski** [comment]
Yes

**Comment by OOF-RIF** [comment]
how would i go about doing this? When i alter the std::clamp value it gives me an error

**Comment by OOF-RIF** [comment]
http://prntscr.com/qw6xa5

**Comment by danielkrupinski** [comment]
Expand this array https://github.com/danielkrupinski/Osiris/blob/31df728c2b21e1f478211fb2e428c832e1f0c65a/Osiris/Config.h#L112 and adjust the clamp you posted.

**Comment by OOF-RIF** [comment]
thanks!

**Comment by OOF-RIF** [comment]
I've been messing around with it but i keep getting the "term does not evaluate to a function taking 2 arguments"  link to the errors http://prntscr.com/qwa6ur

the errors go to http://prntscr.com/qwa6yo

**Comment by EurobeatClub** [comment]
Hi, don't do this:

    ImGui::InputInt("##mat", &material, 1, 2, 3);
    material = std::clamp(material, 1, 2, 3);

But instead do this, it works:

    ImGui::InputInt("##mat", &material, 1, 3);
    material = std::clamp(material, 1, 3);

**Comment by OOF-RIF** [comment]
thanks!
