### ISSUE TITLE
fireEventClientSide doesn't register all events

### ISSUE THREAD

**Issue by JDeu** [danielkrupinski/Osiris#1053]
As stated in [#639](https://github.com/danielkrupinski/Osiris/issues/639)

**Comment by NexSqaud** [comment]
1. Create a event listener class and handleGameEvent function
```c++
class MyEventlistener{
public:
    constexpr auto handleGameEvent(GameEvent* event) noexcept
    {
        switch(fnv::hashRuntime(event->getName()){
            // there check for all events from step 2
        }
    }
}
```
2. Register listener in game
At Hooks::Hooks()
```c++
MyEventListener listener{};
// here hooking code
interfaces.gameEventManager->addListener(listener, "EVENT NAME");
// copy for all events you need
```
3. Done

**Comment by effex1337** [comment]
Was a new class rly needed tho i just do
GameEvent* listener;
interfaces.gameEventManager->addListener(listener, "player_impact", false);
I modified add listener so i could listen for serversided evsnts as well.

**Comment by xAkiraMiura** [comment]
wym serversided events? events that are networked but the client ignores?

**Comment by notgoodusename** [comment]
> wym serversided events? events that are networked but the client ignores?

there are 2 hooks fireeventclientside and fireevent as the name suggests one is clientside and the other isnt(correct me if iam wrong)

**Comment by JDeu** [comment]
Taking @effex1337 's solution of using `GameEvent` as the listener.

`interfaces.gameEventManager->addListener(new GameEvent, "player_footstep");`

Then in `fireEventClientSide` just listen for the event.

`case fnv::hash("player_footstep"):`

Thanks!

**Comment by JDeu** [comment]
Re-opening the issue due to crashing when returning original function in `fireEventClientSide` after registering the listeners.

**Comment by xAkiraMiura** [comment]
[AddListener](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/public/igameevents.h#L110) (IGameEventListener2*);

[IGameEventListener2](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/public/igameevents.h#L88-L96)

I think trying to redirect a server side event into fireEventClientSide crashes because it isn't expecting non-client events. Are you able to not run the original function if the event is server side or does it still crash?

**Comment by NexSqaud** [comment]
@JDeu just create class for listening events. https://github.com/danielkrupinski/Osiris/issues/1053#issuecomment-582980289

**Comment by JDeu** [comment]
Adding a new listener using `GameEvent` or `GameEventListner` still gives me a read access violation...

EventListenerClass

`class GameEventListener
{
public:

	constexpr auto fireGameEvent(GameEvent* event) noexcept
	{
		return callVirtualMethod<void, GameEvent*>(this, 1, event);
	}
};`

In `Hooks:Hooks`

`interfaces.gameEventManager->addListener(new GameEventListener, "player_footstep");`

In `fireEventClientSide` hook

`case fnv::hash("player_footstep"):`

If I always return `fireEventClientSide` true then it doesn't throw a violation

**Comment by notgoodusename** [comment]
>addListener(new GameEventListener, "player_footstep");


shouldnt GameEventListener be a pointer?

**Comment by JDeu** [comment]
> > addListener(new GameEventListener, "player_footstep");
> 
> shouldnt GameEventListener be a pointer?

Same thing?

**Comment by NexSqaud** [comment]
GameEventListener is interface! In fireGameEvent you recived a event! Don't call virtual methods!
Make this in fireGameEvent in GameEventListener:
```c++
switch(fnv::hashRuntime(event->getName()){
    case fnv::hash("player_footstep"):
    //HERE CALL HACK METHODS!!!
    break;
}
```

**Comment by danielkrupinski** [comment]
You should now be able to capture all events.

**Comment by JDeu** [comment]
Great. Thanks @danielkrupinski!

For anyone who wants to use more events, Alien Mods has a [page](https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events) with all the events.
