### ISSUE TITLE
Huge FPS loss with ColorWorld

### ISSUE THREAD

**Issue by ZerGo0** [danielkrupinski/Osiris#1054]
https://github.com/danielkrupinski/Osiris/blob/31df728c2b21e1f478211fb2e428c832e1f0c65a/Osiris/Hacks/Visuals.cpp#L77

@danielkrupinski I just did a benchmark and I lose 130+ FPS when I have it enabled, a way to fix that is by just enabling it when I join the game and then disable it. To me, this sounds like it is constantly scanning the same objects and set's the colour for each object. Looking at the code it clearly shows that it exactly what it is doing.

Is there any particular reason why it rescans each tick?

**Comment by danielkrupinski** [comment]
I have never experienced FPS loss because of this function.

**Comment by danielkrupinski** [comment]
How many FPS do you have normally? What CPU & GPU you have?

**Comment by ZerGo0** [comment]
> How many FPS do you have normally? What CPU & GPU you have?

https://i.imgur.com/5wUKnd6.gifv

AMD Ryzen 7 3800X @4.4GHz OC
Nvidia 1080TI

**Comment by danielkrupinski** [comment]
Try calling Visuals::colorWorld() from CreateMove hook instead of FrameStageNotify.

**Comment by ZerGo0** [comment]
> Try calling Visuals::colorWorld() from CreateMove hook instead of FrameStageNotify.

Doesn't really seems to affect it, to be honest, BombTimer also seems to drop like 30-40 FPS.

**Comment by danielkrupinski** [comment]
Try limiting your fps to a stable amount.

**Comment by NexSqaud** [comment]
Try enable AVX2 instruction set

**Comment by ZerGo0** [comment]
> Try limiting your fps to a stable amount.

I will benchmark it later with the actual benchmark and report the results back.

> Try enable AVX2 instruction set

I'm already doing that.

**Comment by ZerGo0** [comment]
> Try limiting your fps to a stable amount.

Actually, this is only an issue when you are CPU limited (I use a smaller resolution on my test account which results in a CPU Limit), in an actual match it doesn't really matter. Issue closed, not worth the effort.
