### ISSUE TITLE
{Question} Repo with All the Pull Requests

### ISSUE THREAD

**Issue by VuBrian22** [danielkrupinski/Osiris#1055]
Is there a repo with all the pull requests in them? I could do it myself I just forgot the commands to do so. I remember that ZPD Miller had an updated fork of his own however suddenly his whole profile was off the radar.

**Comment by xAkiraMiura** [comment]
You can see closed pulls as well, do you mean branches?

**Comment by VuBrian22** [comment]
@xAkiraMiura Well not quite. It was a fork of this original repo with all of the pull requests merged into the fork.

**Comment by tirziz** [comment]
Merge all of them make your fork unstable but well it can be some useful features.

**Comment by VuBrian22** [comment]
@tirziz yeah oh well...but that's the least of my worries. lol

**Comment by RyDeem** [comment]
i have some of the main features in my repo, take a look maybe usefull idk
https://github.com/RyDeem/Osiris

**Comment by VuBrian22** [comment]
@RyDeem That will do thank you! hey do you remember the commands to merge the pull requests to your own fork?

**Comment by xAkiraMiura** [comment]
either `git rebase` to replay commits or `git merge`.
I couldn't get merge to work however rebasing definitely does work, if you modified the branch at all then it will probably say "x and (you) Authored commit", unfortunately.
