### ISSUE TITLE
How to use listbox func?

### ISSUE THREAD

**Issue by notgoodusename** [danielkrupinski/Osiris#1057]
so i saw gui.cpp a func call listbox which is exactly what im looking for the problem is that i dont know how to use it, anyone knows? if so can you tell me how to use it?

**Comment by effex1337** [comment]
Read the arguments
Its the same for both 
ImGui::Combo and Imgui::Listbox
Which is:
("title", the int for selecting values, the character array, array size, how large should the listbox be or how many items to display at once)
Example:
ImGui::Listbox("test", &config.menu.style, "variable one\0variable 2\0", 2)
In this case i defined my array midline so i dont need to define the arraysize.

**Comment by notgoodusename** [comment]
> Read the arguments
> Its the same for both
> ImGui::Combo and Imgui::Listbox
> Which is:
> ("title", the int for selecting values, the character array, array size, how large should the listbox be or how many items to display at once)
> Example:
> ImGui::Listbox("test", &config.menu.style, "variable one\0variable 2\0", 2)
> In this case i defined my array midline so i dont need to define the arraysize.

i read the arguments but what do i have to put in the {}
