### ISSUE TITLE
How to declare getViewAngles() ?

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#1058]
So if i want to declare the localplayer i need to do this 

          const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());

 When I try this it gives me error
       
           const auto GetvAngle = interfaces.engine->getViewAngles();

how to declare getViewAngles() ?

**Comment by ClaudiuHKS** [comment]
``static Vector Angles { }; interfaces.engine->getViewAngles(Angles);``

**Comment by dapaster** [comment]
Thank you ClaudiuHKS
