### ISSUE TITLE
[Update] CSGO Updated

### ISSUE THREAD

**Issue by cheatscsgocom** [danielkrupinski/Osiris#1060]
CSGO has just been updated. No information appears on the blog of updates with today's ( https://blog.counter-strike.net/index.php/category/updates/ ) and they have not announced anything on twitter. Anyone know what the update is and if it is safe to continue using the Osiris?
Thanks

**Comment by Akianzax** [comment]
I think it's a normal update of the vac. You should be fine. I just inject after the update and nothing bad happens.

**Comment by itchy2019** [comment]
> I think it's a normal update of the vac. You should be fine. I just inject after the update and nothing bad happens.

Generally the bank falls into the account 72 to 96 hours after being detected. It is not immediate. be careful with that

**Comment by cheatscsgocom** [comment]
According to a Reddit user, the update is about this:
https://www.reddit.com/r/csgo/comments/eyh0lz/counterstrike_global_offensive_update_for_2320/
