### ISSUE TITLE
[translate issus]

### ISSUE THREAD

**Issue by H3artdown** [danielkrupinski/Osiris#1061]
i change string to chinese but when the menu show , that string become ???????
using utf-8 btw
![1580804905](https://user-images.githubusercontent.com/60644404/73726917-63396500-476b-11ea-9420-34e204f713e3.png)

**Comment by ClaudiuHKS** [comment]
It works for me if I add the following font file and the following ranges.

``static const ImWchar Ranges [ 3 ] { NULL + 1, USHRT_MAX, NULL, }; io.Fonts->AddFontFromFileTTF ( "MingLiU.TTF" , 12.F , NULL , & Ranges [ NULL ] );``

Yes, **UTF-8** works but **UTF-8-BOM** works too.

However, **C:/Windows/Fonts/ArialUni.TTF** seems NOT to work even if it says that it's **Unicode**.

[mingliu.zip](https://github.com/danielkrupinski/Osiris/files/4152380/mingliu.zip)

**Comment by H3artdown** [comment]
> It works for me if I add the following font file and the following ranges.
> 
> `static const ImWchar Ranges [ 3 ] { NULL + 1 , USHRT_MAX , NULL , }; io.Fonts->AddFontFromFileTTF ( "MingLiU.TTF" , 12.F , NULL , & Ranges [ NULL ] );`
> 
> Note, **USHRT_MAX** expands to **0xFFFF** or **65535**.
> 
> Yes, **UTF-8** works but **UTF-8-BOM** works too.
> 
> However, **C:/Windows/Fonts/ArialUni.TTF** seems NOT to work even if it says that it's **Unicode**.
> 
> [mingliu.zip](https://github.com/danielkrupinski/Osiris/files/4152380/mingliu.zip)

thank for your reply first , but maybe not working for me
![U N07HSV%EHFEA{$G)%C00](https://user-images.githubusercontent.com/60644404/73738292-33945800-477f-11ea-9bd3-cd1917de25be.png)

**Comment by ClaudiuHKS** [comment]
Line [1667](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/imgui/imgui_draw.cpp#L1667) → Unable To Load The TTF Font File (TTF Font File Was NOT Found)

``static const ImWchar myRanges [ 3 ] { NULL + 1 , USHRT_MAX , NULL , };``
``const auto myFont { io.Fonts->AddFontFromFileTTF ( "MingLiU.TTF" , 12.F , nullptr , & myRanges [ NULL ] ) };``
``if ( !myFont )``
``{``
``MessageBoxW ( { } , L"Unable To Load The TTF Font File" , L"ImGui Error" , MB_ICONERROR | MB_OK );``
``exit ( EXIT_FAILURE );``
``};``

1. If **MingLiU.TTF**'s location is the same with the location of **csgo.exe**, you need to call

``const auto myFont { io.Fonts->AddFontFromFileTTF ( "MingLiU.TTF" , 12.F , nullptr , & myRanges [ NULL ] ) };``

2. If **MingLiU.TTF**'s location is **C:/Windows/Fonts**, you need to call

``const auto myFont { io.Fonts->AddFontFromFileTTF ( "C:/Windows/Fonts/MingLiU.TTF" , 12.F , nullptr , & myRanges [ NULL ] ) };``

Replace [THIS](https://pastebin.com/bG46NPVs) with [THIS](https://pastebin.com/m1DDccZd).

**Comment by H3artdown** [comment]
i use the same code in my friends pc and its working , but not fine for me , maybe my vs broken or lack some model ， thanks for your help anyway

**Comment by xAkiraMiura** [comment]
If it works on your friend's PC but not yours then try building in `Release x86` mode and installing the newest VC++ runtime.
