### ISSUE TITLE
How to hook inside a hook?

### ISSUE THREAD

**Issue by notgoodusename** [danielkrupinski/Osiris#1064]
so i made a fake latency func made all the classes and stuff, the problem comes when trying to hook it, since hooking it before the game starts results in a crash or not even injecting, hooking it inside createmove and making nullptrs checks is the right solution but it always crashes at hookat func.

 Is there a way to hook after joining the game?

**Comment by woah1337** [comment]
pseudocode for u

ur createmove func(){
static bool doonce= true;
if(doonce && is in a game){
hook ur function here();
doonce = false;
}

**Comment by notgoodusename** [comment]
i have already made that pseudo code checking if oldnetchan != netchan, yet the problem comes when making the hook to be hooks.network = netchan;

**Comment by woah1337** [comment]
> i have already made that pseudo code checking if oldnetchan != netchan, yet the problem comes when making the hook to be hooks.network = netchan;

can you post some code? and also the exception/error?

**Comment by notgoodusename** [comment]
` if (interfaces.engine->isConnected())
    {
        FakeLatency::UpdateIncomingSequences();

       // auto Clientstate = *reinterpret_cast<CClientState***>(callVirtualMethod<uintptr_t>(interfaces.engine , 12) + 0x10);
       // auto Clientstate = *reinterpret_cast<uintptr_t*>(uintptr_t(GetModuleHandle("engine.dll")) + 0x57E854);
       // DWORD Clientstate = (DWORD) * (DWORD*)memory.clientState;
        if (!memory.clientState->m_NetChannel)
            return;
        void* last_ptr = nullptr;
            //auto intnetchan = *reinterpret_cast<uintptr_t*>(Clientstate + 0x9C);
            //NetworkChannel* netchan = reinterpret_cast<NetworkChannel*>(intnetchan);
            if (!last_ptr || last_ptr != memory.clientState->m_NetChannel)
            {
                last_ptr = memory.clientState->m_NetChannel;
                hooks.network = memory.clientState->m_NetChannel; //crashes here
            }
    }`   
how i get cclientstate
`clientState = **reinterpret_cast<CClientState***>((*reinterpret_cast<uintptr_t**>(interfaces.engine))[12] + 16);`

**Comment by notgoodusename** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/57305491/73837072-6b3ae880-47ef-11ea-99f0-573c3daf8ece.png)

**Comment by ZerGo0** [comment]
Might help you: https://github.com/DankPaster/MutinyFixed/blob/f15d87ef03028fcdc9edc0c3c156e00305cc4fba/MutinyFixed/CSGOFullv2/CreateMove.cpp#L820

**Comment by notgoodusename** [comment]
> Might help you: https://github.com/DankPaster/MutinyFixed/blob/f15d87ef03028fcdc9edc0c3c156e00305cc4fba/MutinyFixed/CSGOFullv2/CreateMove.cpp#L820

i will try it later
