### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by InSovietCS** [danielkrupinski/Osiris#1065]
Suggestion: when the "No Aim Punch" and "No View Punch" options are active, the bullets are significantly harder to track (becuase of the effect, they go much higher)

My suggestion: making a function to draw scan lines for bullets (like line tracers, similar to what BRUTALE has) to track the bullets easier.

Just a QoL suggestion...

**Comment by MinecraftGoodGame** [comment]
Or use recoil crosshair

**Comment by InSovietCS** [comment]
> Or use recoil crosshair

Some people (like me) hate the recoil crosshair as it gets confusing for someone who has been orienting movement around a static one for so long (700ish hours)

**Comment by WolfOGG** [comment]
I coded in a recoil circle like an fov circle but to see where recoil goes.
