### ISSUE TITLE
C++ no suitable constructor exists to convert from double to Vector

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#1066]
this is the code

     float speed = localPlayer->velocity().length2D();

     Vector forward;
     Vector right = (forward + 0.217812) * -speed;
     Vector left = (forward + -0.217812) * -speed;

the error is from this line 

     Vector right = (forward + 0.217812) * -speed;
     Vector left = (forward + -0.217812) * -speed;

**Comment by Laxybaxy** [comment]
you could do this
```
        Vector forward{ 0.217812f,0.217812f,0.217812f };

        Vector right = forward * -speed;
        Vector left = forward*-1.f * -speed;
```

**Comment by dapaster** [comment]
Thanks :) @Laxybaxy
