### ISSUE TITLE
Is this cheat detected?

### ISSUE THREAD

**Issue by VoltexYT** [danielkrupinski/Osiris#1068]
Hello, i want to know if the cheat is detected?

With best regards!

**Comment by AbdallahMehiz** [comment]
with an undetected injecting method/injector. it still not detected :D

**Comment by Asviix** [comment]
There's always a risk, but if you have a good injector you should be fine, but do not use Osiris after a big CSGO update and wait for an Osiris Update.

**Comment by littlehurensohn** [comment]
Simply you can make cheat undetected, theres are too many ways. 

Use randoinjector, add some asm__ bytes, junkcodes, off optimalization. 
rand() can be tho useful, for little change signature (after start), tho can add it into cheat. 
Like that my paste is undetected more then 8 months, gl.

**Comment by VoltexYT** [comment]
Ok thank you for your answer

Herr Littlehurensohn and Mr.Asviix

**Comment by xAkiraMiura** [comment]
adding random assembly does nothing but break up signatures to be smaller.
adding junkcode does literally nothing
turning off optimization has downstream affects and eventually the changes from it will also get sigged
the cheat isn't even detected right now, not many people use it compared to AW or OT so it's not a big priority for valve.
adding more features makes more signatures possible
removing features doesn't do much when the hook or an important feature gets sigged

recode hooking would actually work but have fun using any other hooking method, most are slower and the equal/faster are probably detected.

**Comment by littlehurensohn** [comment]
@danielkrupinski close it :heart:

**Comment by bogdancstrike** [comment]
> Simply you can make cheat undetected, theres are too many ways.
> 
> Use randoinjector, add some asm__ bytes, junkcodes, off optimalization.
> rand() can be tho useful, for little change signature (after start), tho can add it into cheat.
> Like that my paste is undetected more then 8 months, gl.
> BTW: Add more features from other sources, remove some useless features, recode hooking.

Hi! I'd like to recode the cheat a bit (remove some functions). Can you help me do it?
