### ISSUE TITLE
[QUESTION] autopistol delay

### ISSUE THREAD

**Issue by xpossed-you** [danielkrupinski/Osiris#1070]
is there any way we can add delay to autopistol?

**Comment by hyperxpro** [comment]
> is there any way we can add delay to autopistol?

Delay in an auto pistol mode is useless. You're better off using an auto clicker.

**Comment by notgoodusename** [comment]
> is there any way we can add delay to autopistol?

yep
if(memory.globalVars->serverTime() - lastTime >= config.misc.delay){
//shoot
lastTime = memory.globalVars->serverTime();
}

**Comment by xpossed-you** [comment]
> 
> 
> > is there any way we can add delay to autopistol?
> 
> yep
> if(memory.globalVars->serverTime() - lastTime >= config.misc.delay / 1000.f){
> //shoot
> lastTime = memory.globalVars->serverTime();
> }
> //1000.f for miliseconds

thanks notgoodusename
