### ISSUE TITLE
[Help] Fast Stop 

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#1071]
I'm try to make Fast Stop feature like in this video
https://www.youtube.com/watch?v=3QihqT1GkH8

this is my code

      void Misc::fastStop(UserCmd* cmd) noexcept 

    {

        const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
        Vector velocity = localPlayer->velocity();
        Vector direction;
    
        float speed = velocity.length2D();

        direction.y = cmd->viewangles.y - direction.y;

        Vector forward{ 0.217812f,0.217812f,0.217812f };
    

        Vector right = forward * -speed;
        Vector left = forward * -1.f * -speed;

        Vector move_forward = forward * -speed;
        Vector move_backward = forward * -1.f * -speed;

       {
          if (!(cmd->buttons |= UserCmd::IN_MOVELEFT))
              cmd->sidemove += +left.y;

          if (!(cmd->buttons |= UserCmd::IN_MOVERIGHT))
              cmd->sidemove -= -right.y;
       }

       {
          if (!(cmd->buttons |= UserCmd::IN_FORWARD))
              cmd->forwardmove += +move_forward.x;

          if (!(cmd->buttons |= UserCmd::IN_BACK))
              cmd->forwardmove -= -move_backward.x;
       }

    }

 But still not working

**Comment by notgoodusename** [comment]
direction isnt used and make static vectors

**Comment by notgoodusename** [comment]
do = instead of -= or +=

**Comment by dapaster** [comment]
Thanks i will do this later
