### ISSUE TITLE
How to create server time method? (context; for clantag)

### ISSUE THREAD

**Issue by 8cy** [danielkrupinski/Osiris#1072]
I'm trying to make a tick based animated clantag and..

This is the code I have so far:
```
if (config.misc.switchTag) {
        static int counter = 0;
        static int motion = 0;
        if (counter % 48 == 0)
             motion++;
        ServerTime = // WHAT DO I PUT HERE???
        int value = ServerTime % 25;
        switch (value) {
                case 0: memory.setClanTag(XorStr("   "), "tag"); break;
                case 1: memory.setClanTag(XorStr("  t"), "tag"); break;
                case 2: memory.setClanTag(XorStr(" ta"), "tag"); break;
                case 3: memory.setClanTag(XorStr("tag"), "tag"); break;
                case 4: memory.setClanTag(XorStr("ag "), "tag"); break;
                case 5: memory.setClanTag(XorStr("g  "), "tag"); break;

        }
}
```
However, I need to get the ServerTime working but nothing actually works. I've tried;

**Method 1**
```
int ServerTime = ((float)Interfaces::GlobalVars->interval_per_tick * LocalPlayer->GetTickBase());
// This one was a recomended method that I don't think even works with the Osiris SDK lol
```
**Method 2**
```
int ServerTime = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer())->tickBase();
```
**Method 3**
```
int ServerTime = memory.globalVars->serverTime();```

How do I get it working???

**Comment by psycho147** [comment]
int ServerTime = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer())->tickBase() * config.misc.animationSpeed * memory.globalVars->intervalPerTick;

**Comment by notgoodusename** [comment]
memory.globalVars->realtime or currentime

**Comment by 8cy** [comment]
@psycho147 animationSpeed errors out, where is it defined lol

**Comment by 8cy** [comment]
Update; I managed to get @psycho147's suggestion working with some tweaks. I removed `config.mic.animationSpeed *` and it ended up working but about at the same level it was at before. Here is a video of how it works, currentaly I'm trying to get rid of the cutting out which is present; [Video Example](https://streamable.com/bjjha). Help would be appreciated as I still can't find a way to have a consistant stacking clantag method.

**Comment by effex1337** [comment]
Just steal it from fatality leaked source's clantag, some headstarts there are like 34 cases for tags on it and theres a number divided by 34+-1 do that and your should be fine.

**Comment by 8cy** [comment]
@effex1337 looking at the fatal src and if I were to do the 100% port then there would be a lot of reverse engineering I'd have to do. I'm like 3 hours in and shits still fucked lol. I'm going to try to use Osiris SDK functions to replace the fatal ones for now.

**Comment by littlehurensohn** [comment]
I have this in my source like 3 months, i make the code in 5 mins, its fucking basic and easy, + its ez how to make synced clantag.

**Comment by 8cy** [comment]
> I have this in my source like 3 months, i make the code in 5 mins, its fucking basic and easy, + its ez how to make synced clantag.

@littlehurensohn thats cool and all but literally no one asked or cares unless you post it.

**Comment by xAkiraMiura** [comment]
http://www.cplusplus.com/reference/string/string/substr/
or
http://www.cplusplus.com/reference/algorithm/rotate/
^ do that, your current method is a huge anti-pattern

"lot of reverse engineering" my ass; you already have all the code, it's not even reverse engineering at this point just throwing code together until it works.

sig is literally just pattern scanning code, given a module an a IDA-style signature it returns an address, you then apply this address to a function and we can call this function as we would normally (virtual function)
^ effective declaration: `__fastcall set_clantag_fn (const char* tag, const char* tag);`
^ calling: `set_clantag_fn("Example", "Example");`
[heres another example of the clantag function](https://github.com/spirthack/CSGOSimple/blob/master/CSGOSimple/helpers/utils.cpp#L278)

[...and what if i told you osiris already has a clantag function?](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Memory.h#L36) you seem to already know this but why are you saying you don't have it in the picture?

> I'm like 3 hours in and shits still fucked

[learncpp.com](https://www.learncpp.com/)

p.s. you don't even need to have all of those variables wasting memory, literally just switch off of `currTime % len`
p.p.s you don't even need xorstr; Valve isn't going to check the strings for your paste's name.

**Comment by notgoodusename** [comment]
in memory.cpp there is a setclantag func so idk

**Comment by littlehurensohn** [comment]
> > I have this in my source like 3 months, i make the code in 5 mins, its fucking basic and easy, + its ez how to make synced clantag.
> 
> @littlehurensohn thats cool and all but literally no one asked or cares unless you post it.

Ur fun, no one cares? 
Bruh, U actually post some shitty c+p code, and dont know how to make it works, dont be dummy and go on learncpp.com .. U missing some basic skills.

**Comment by 8cy** [comment]
> > > I have this in my source like 3 months, i make the code in 5 mins, its fucking basic and easy, + its ez how to make synced clantag.
> > 
> > 
> > @littlehurensohn thats cool and all but literally no one asked or cares unless you post it.
> 
> Ur fun, no one cares?
> Bruh, U actually post some shitty c+p code, and dont know how to make it works, dont be dummy and go on learncpp.com .. U missing some basic skills.

Chill I fixed it because some people are actually helpful, unlike yo ass just spitting straight bullshit that no one cares about that just boost yo shitty ass ego(.)

**Comment by littlehurensohn** [comment]
> > > > I have this in my source like 3 months, i make the code in 5 mins, its fucking basic and easy, + its ez how to make synced clantag.
> > > 
> > > 
> > > @littlehurensohn thats cool and all but literally no one asked or cares unless you post it.
> > 
> > 
> > Ur fun, no one cares?
> > Bruh, U actually post some shitty c+p code, and dont know how to make it works, dont be dummy and go on learncpp.com .. U missing some basic skills.
> 
> Chill I fixed it because some people are actually helpful, unlike yo ass just spitting straight bullshit that no one cares about that just boost yo shitty ass ego(.)

:1st_place_medal:

**Comment by xAkiraMiura** [comment]
both of you, stop flaming. you contributed nothing to the conversation so why did you post in the first place? think before you post.

did you end up resolving the issue? if so please close the issue.

p.s. your grammer reflects your immaturity

**Comment by littlehurensohn** [comment]
@notgoodusename close it :heart:
