### ISSUE TITLE
[Issues] Failed to build Osiris

### ISSUE THREAD

**Issue by xpossed-you** [danielkrupinski/Osiris#1075]
`1>  link!RaiseException()+0x48
1>  link!CxxThrowException()+0x66
1>  link!std::_Xout_of_range()+0x1f
1>  link!InvokeCompilerPass()+0x31dd0
1>  link!InvokeCompilerPass()+0x22ab4
1>  link!InvokeCompilerPass()+0x229e5
1>  link!InvokeCompilerPass()+0x22d43
1>  link!InvokeCompilerPass()+0x229e5
1>  link!InvokeCompilerPass()+0x22f02
1>  link!InvokeCompilerPass()+0x22e34
1>  link!InvokeCompilerPass()+0x2681e
1>  link!InvokeCompilerPass()+0x262d7
1>  link!CloseTypeServerPDB()+0xa771b
1>
1>LINK : fatal error LNK1257: code generation failed
1>Done building project "Osiris.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

**Comment by danielkrupinski** [comment]
That's linker error.
