### ISSUE TITLE
Show Fake

### ISSUE THREAD

**Issue by VoltexYT** [danielkrupinski/Osiris#1076]
The game crashes after activate this

static void __stdcall drawModelExecute :
```
static void __stdcall drawModelExecute(void* ctx, void* state, const ModelRenderInfo& info, matrix3x4* customBoneToWorld) noexcept
{

    hooks.modelRender.callOriginal<void, 21>(ctx, state, std::cref(info), customBoneToWorld);

    auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());

    interfaces.modelRender->forceMaterialOverride(nullptr);
    auto fake = localPlayer->eyeAngles();
    localPlayer->viewPunchAngle() = fake;
    localPlayer->drawModel(0x1, 255);
    interfaces.modelRender->forceMaterialOverride(nullptr);
}

DRAW MODEL : 

    void drawModel(int flags, char alpha)
    {
        return callVirtualMethod<void(__thiscall*)(void*, int, unsigned char)>(this + 4, 9)(this + 4, flags, alpha);
    }
```

**Comment by notgoodusename** [comment]
yeah i have the same problem i think there is no solution

**Comment by notgoodusename** [comment]
dont use char  for alpha use int

**Comment by notgoodusename** [comment]
if you do that maybe it wont crash, but maybe it wont show the chams but show the shadows(happend to me if i remember)

**Comment by VoltexYT** [comment]
Without the drawmodel function it shows the shadows and with the client crashes

**Comment by notgoodusename** [comment]
> dont use char for alpha use int

try this and tell me how it goes

**Comment by Straightplus** [comment]
`i think hes pc exploded lol`

**Comment by VoltexYT** [comment]
int = crash!

**Comment by notgoodusename** [comment]
check this post maybe it can help you, he refers that he called original sceneend, i dont understand him, but maybe you do
https://www.unknowncheats.me/forum/counterstrike-global-offensive/322882-crashing-calling-function-drawmodel-chams.html

**Comment by VoltexYT** [comment]
sorry dude i dont get anything.

**Comment by notgoodusename** [comment]
try replacing drawmodrl with hooks.modelRender.calloriginal blahblah

**Comment by effex1337** [comment]
Bruh u cslling endscene chams stuff in dme
Great job :facepalm:

**Comment by VoltexYT** [comment]
wtf osiris calling chams in drawModelExecute too

**Comment by notgoodusename** [comment]
> wtf osiris calling chams in drawModelExecute too

what do u mean?

**Comment by xAkiraMiura** [comment]
could you tell us where it crashes?

also osiris does use DME for chams, not EndScene.
[bool Chams::render(void* ctx, void* state, const ModelRenderInfo& info, matrix3x4* customBoneToWorld) const noexcept](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hacks/Chams.cpp#L45)
^ DME calling convention

*also Entity doesn't have a method called drawModel?*

**Comment by notgoodusename** [comment]
> _also Entity doesn't have a method called drawModel?_

no it doesnt, you have to do this + 4 to get clientrenderable, just like getmodel

**Comment by VoltexYT** [comment]
Have anyone a smart idea to show fake antiaim?

**Comment by notgoodusename** [comment]
> Have anyone a smart idea to show fake antiaim?

do getoriginal idk if it changes anything but i think it does, since drawmodelexecute is a void func it will work perfectly(correct me if i am wrong)
