### ISSUE TITLE
Silent Aim Question

### ISSUE THREAD

**Issue by ZerGo0** [danielkrupinski/Osiris#1077]
https://github.com/danielkrupinski/Osiris/blob/385dcf22efba4c219009ffe8dba417921a8613af/Osiris/Hacks/Aimbot.cpp#L177

Hey, I have noticed that the silent aim looks quite obvious even on low FOV and I was wondering what could cause this? I know that Perfect Silent Aim is patched and that it will show it no matter what, but I was wondering with the code above it applies the angle and it gets proceded by the server which is expected and it looks kind of like this:
(1/4 demo speed, 64 tick demo)
![Silent](https://i.imgur.com/9klZRcf.gif)

I'm playing with low sensitivity and idk if that affects it or not, but to me, it seems like it keeps that angle for more than 1 tick which it shouldn't and only updates it when I move my mouse? I'm not exactly sure what the server allows in MM, but would it help if you set the angle back to the original one the next tick and is that undetected by the anti-cheat?

@danielkrupinski 
Also is there any other way to contact you, I have a few questions sometimes and I don't want to open an issue each time...

**Comment by danielkrupinski** [comment]
Silent aim is client-sided. It flicks back because when aimbot become inactive game sends your local angles (different from server) to the server.

**Comment by ZerGo0** [comment]
> Silent aim is client-sided. It flicks back because when aimbot become inactive game sends your local angles (different from server) to the server.

I know why it flickers, it just takes quite a long time to reset the aim back to the local aim, serval ticks. It's quite noticable when you spectate someone using Osiris and Silent Aim.
