### ISSUE TITLE
Failed to find VClient018 interface!

### ISSUE THREAD

**Issue by mrb0098** [danielkrupinski/Osiris#1078]
Hi
i am trying to use osiris.dll file on a win form project to build my own dll injector but when i try to add that file as a reference i got[ this error 
](https://i.imgur.com/pgkSlhv.png)

---------------------------
Osiris
---------------------------
Failed to find VClient018 interface!
---------------------------
OK   
---------------------------

**Comment by ZerGo0** [comment]
You can't load it as a reference, you can just locally find it and load it that way.

**Comment by effex1337** [comment]
U don't inject as soon as you open the game. 
Wait for serverbrowser.dll to load in csgo i posted the code for it somewhere in here.

**Comment by mrb0098** [comment]
i need to put it on my own dll injector and build my injector as single .exe file
how can i do that ?

**Comment by danielkrupinski** [comment]
Convert dll to byte array or store it as resource.
