### ISSUE TITLE
[SUGGESTION] Flick for aimbot

### ISSUE THREAD

**Issue by Vonr** [danielkrupinski/Osiris#1079]
right now aimbot has an option for silent aim but i think it would be nice to have an option to flick to the target when firing (basically aimlock but when mouse is clicked, not held or togged) would make sniper plays more believable as currently it flicks to the target then back which doesnt look very legit.

**Comment by notgoodusename** [comment]
use aimlock instead of silent or both

**Comment by NexSqaud** [comment]
just turn off silent and set smooth to 0

**Comment by xAkiraMiura** [comment]
aimlock + silent should cause it to only lock on when you shoot and not return, just make sure autoshoot is off.
^ i recommend an fov limit.

alternatively you could unbind your attack button and bind the aimbot to it with autoshoot enabled, that way smoothing would work.
