### ISSUE TITLE
Something actually useful

### ISSUE THREAD

**Issue by TrackyBunny** [danielkrupinski/Osiris#108]
A simple unhook/unload button.

I really want you to add an unload button, just because I really don't want to restart the game every time I change my source code just so I can test the changes.

Thanks anyways!

**Comment by t9z** [comment]
Have you tried "Edit and Continue"?

**Comment by danielkrupinski** [comment]
Implemented. Thanks!

**Comment by effexcs** [comment]
Umm does it really unhook? 
I can't compile again when i unhook and edit the source

**Comment by danielkrupinski** [comment]
@effexcs You need to manually map dll. If you use LoadLibrary injection you need to unload it from process using some external tool.
