### ISSUE TITLE
[SUGGESTION] Chams based on visibility

### ISSUE THREAD

**Issue by Vonr** [danielkrupinski/Osiris#1080]
2 configurable colors/hues. 1 for when that part is visible and the other when it isnt. i know its possible to make it so that it cant only do parts of the body instead of the whole body but im not sure how complicated that is. Even if the whole body becomes the visible color when part of it is visible, it would still be useful.

**Comment by notgoodusename** [comment]
bro, there are already in the cheat
just instead of All do visible or occluded

**Comment by RyDeem** [comment]
lol wtf have you even poked around in the cheat?
Did you not know there are aimbots for each weapon individually as well?

check the dropdown menus fam in the window your in, explore

**Comment by Vonr** [comment]
didnt see an option for that in the chams window will check again
