### ISSUE TITLE
Cursor flicking bug

### ISSUE THREAD

**Issue by barbadully** [danielkrupinski/Osiris#1082]
Basically I updated the cheat with everything you did, and now all of a sudden when I inject and join a game I can see my cursor flickering ingame, I am playing fullscreen. Not sure what I did but I fucked something up for sure, because that didn't happen before. Any help on how I would fix this without needing to go for a clean start ?

**Comment by danielkrupinski** [comment]
Maybe you forgot this
https://github.com/danielkrupinski/Osiris/blob/e75ffbbf6d37b2c49135119cafec2c3a1b00162f/Osiris/GUI.cpp#L38

**Comment by barbadully** [comment]
thank you btw
