### ISSUE TITLE
Possible to fix No Recoil, No Spread ???

### ISSUE THREAD

**Issue by asmouman** [danielkrupinski/Osiris#1083]
Possible to add functional No Recoil and No Spread in this hack?  It's the only thing missing in this Royal hack

**Comment by notgoodusename** [comment]
> Possible to add functional No Recoil and No Spread in this hack? It's the only thing missing in this Royal hack

what do u mean?like for hvh nospread?

**Comment by Vonr** [comment]
probably either a old vulnerability with the spread cl command or some rng prediction

**Comment by rosesware** [comment]
You can do it already with Engine Prediction and removing recoil to your "Aimbot" settings (in-game cheat, course).
