### ISSUE TITLE
How to filter activeWeapon names in ESP

### ISSUE THREAD

**Issue by Megalounge** [danielkrupinski/Osiris#1085]
This is how it goes, I enter a community server and every round start you are equipped with Bare hands and a hammer (or an axe), so when I turned on active Weapon in ESP, it would be very hard to tell who is carrying deadly weapons for example an AWP or AK-47 since there are so many boxes and names and weapons on the screen. 
I was thinking if there's any way to filter the default weapons and even filter certain weapons, I tried to but failed. Any suggestions or thoughts?

**Comment by WolfOGG** [comment]
@danielkrupinski Make boxes static and add skeletons. I have made my own skeleton esp but it is a paste and it is just a bunch of crappy coding since it is completely pasted.

**Comment by xAkiraMiura** [comment]
> @danielkrupinski Make boxes static and add skeletons. I have made my own skeleton esp but it is a paste and it is just a bunch of crappy coding since it is completely pasted.

how is that on topic and why are you pinging daniel? you could have made a seperate issue and someone could have decided to work on it.

**Comment by mercyples** [comment]
> @danielkrupinski Make boxes static and add skeletons. I have made my own skeleton esp but it is a paste and it is just a bunch of crappy coding since it is completely pasted.

can u give me source for your skeleton esp please 
thanks!
