### ISSUE TITLE
When i crouch and look down enough the bullets goes WAYYY down...

### ISSUE THREAD

**Issue by Straightplus** [danielkrupinski/Osiris#1086]
more than they should and heres some video of it.
I can recreate it everytime doesent matter about server nor tick count.

Here is some footage of the issue: https://anonfile.com/t4caE4X8n7/Counter-strike_Global_Offensive_2020.02.10_-_19.15.47.01_mp4

Things ive done so far to try and catch the error: resetting the aimbot in my config and deleting some code in aimbot (like pr's)

**Comment by Laxybaxy** [comment]
upload the footage to yt, takes hours to download..

**Comment by Straightplus** [comment]
okay

**Comment by Straightplus** [comment]
there :)

**Comment by Straightplus** [comment]
dont mind the audio

**Comment by Laxybaxy** [comment]
Guessing its caused by antiaim or silent aimbot?

**Comment by Straightplus** [comment]
both is disabled? i explained it here: 

> Things ive done so far to try and catch the error: resetting the aimbot in my config and deleting some code in aimbot (like pr's)

**Comment by Straightplus** [comment]
well i didnt say it was off but i thought it was self explained

**Comment by ZerGo0** [comment]
Post the code of your aimbot, you probably messed something up when you edited it.

**Comment by Straightplus** [comment]
It is the same as daniels

**Comment by Straightplus** [comment]
I reversed it after trying to remove it

**Comment by xAkiraMiura** [comment]
is that a server specific thing or does it still break in a self-hosted match?

**Comment by Straightplus** [comment]
havent tested in self hosted but breaks on both valve servers and community

**Comment by Straightplus** [comment]
okay iam le confusion it doesent break in self hosted maps but does in custom servers???

**Comment by notgoodusename** [comment]
servers works with angles differently, try playing without osiris

**Comment by Straightplus** [comment]
only happens when iam injected
UPDATE: idfky but now it doesent break in valve servers??

**Comment by xAkiraMiura** [comment]
does it still happen if you don't have any configs loaded? (default state)

could be a desync between where networked viewangles is and engine angles are, maybe something is dividing them by 2 before they get sent?

**Comment by Straightplus** [comment]
it doesent.
just tested it? WTF

**Comment by Laxybaxy** [comment]
It could be literally annything since you are working with a paste/forked version of osiris, there is no problem in the original(?) so the error must be somewhere else
