### ISSUE TITLE
Game updated and cheat error

### ISSUE THREAD

**Issue by CSGOCheatsArg** [danielkrupinski/Osiris#1087]
Game updated and cheat error

Capture: https://gyazo.com/9ebc2726d88f12ceb13f89db76b9b56e

Release Notes for 2/11/2020
2020.02.11 - 

[ COMMUNICATIONS ]
– Players who receive significantly more communication abuse reports than others will receive a warning. If they continue to receive significantly more reports they will be muted by default. Other players can unmute them through the scoreboard as usual.
– Muting a player will now also hide their name and avatar.
– Reporting a player for abusive communications will now automatically mute them.

[ MISC ]
– Ballistic Shield will now block all melee attacks (knife, axe, fists, etc.)
– Texture and normal updates to the MAC-10 | Classic Crate to match new MAC-10 UV from Kai123

**Comment by Davidjarrieta** [comment]
yeah same here, got it fixed?

**Comment by eschram** [comment]
@Davidjarrieta not fixed

**Comment by effex1337** [comment]
https://www.youtube.com/watch?v=JD4rmt7Ym1A
this video explains why its crasing

    submitReport = findPattern<decltype(submitReport)>(L"client_panorama", "\x55\x8B\xEC\x83\xE4\xF8\x83\xEC\x20\x8B\x4D\x08\x56\x57\xE8????\x8B\xF8\x8D\x4C\x24\x0C");

is outdated

**Comment by effex1337** [comment]
if u want to just play the game and not use the reportbot then just remove this line(temporary fix).

**Comment by Cicker21** [comment]
i can't find this line

**Comment by Bywnb** [comment]
now who can fix it?

**Comment by streamshark** [comment]
in visual studio go to source files -> memory.cpp, then comment out line 40 (submitreport line)

**Comment by Cicker21** [comment]
thx, i was searching on reportbot.cpp

**Comment by streamshark** [comment]
you know you can search in github/visual studio too right

**Comment by ZerGo0** [comment]
@danielkrupinski Report Bot signature needs to be updated it seems like

**Comment by blissau** [comment]
how tf do i fix this

**Comment by unniggable** [comment]
by removing reportbot or getting the new sig

**Comment by Matt-cloud** [comment]
anyone know what the new signature is

**Comment by blissau** [comment]
can someone link the updated file

**Comment by Vonr** [comment]
https://github.com/Akandesh/blazedumper

**Comment by Vonr** [comment]
check that repo for updated sigs

**Comment by Bywnb** [comment]
> check that repo for updated sigs

we need Report Bot signature not offsets

**Comment by danielkrupinski** [comment]
Updated. They added **hidden** cvar `cl_mute_player_after_reporting_abuse`, on by default. Also it seems you don't receive confirmation when reporting more than once per 10 seconds.
