### ISSUE TITLE
Failed to find pattern?!

### ISSUE THREAD

**Issue by jh-elec** [danielkrupinski/Osiris#1088]
As of today, I have had the following problem.
My Cnfg.: Windows 10, X64

![grafik](https://user-images.githubusercontent.com/40752237/74330369-d9ece880-4d91-11ea-93a0-87a1d4c5b497.png)

**Comment by woah1337** [comment]
epic 👏

**Comment by jh-elec** [comment]
> epic 👏

?

**Comment by unniggable** [comment]
wait until someone updates the sigs on the cheat. CSGO had an update and some sigs have changed

**Comment by 0x1Eren** [comment]
Same here.

**Comment by CSGOCheatsArg** [comment]
#1087

**Comment by thvozdovic** [comment]
Commit 41362d9 fixed it.
