### ISSUE TITLE
Font Change

### ISSUE THREAD

**Issue by ddjem87** [danielkrupinski/Osiris#109]
Hello i wanted to modify the cheat a little and make it undetected (if it is idk just for security)
i wanted to modify the aimbot menu so it wont say rifles or heavy i wanted them to be icons so i made a custom font with better readability and added the icons i already changed the names of rifles, heavy ,smg, pistols but the font seems to not load and the old font is there.
I tried to change the font with

io.Fonts->AddFontFromFileTTF(strcat(buffer, "\\Fonts\\CherryMonospace-Light.ttf"), 16.0f);

I tried with the default input of the font 
\\Fonts\\tahoma.ttf     (or whatever was i don't remember)

I tried with  (there are 2 backslashes but does not appear for some reason)
C:\\Users\\UserX\\AppData\\Local\\Microsoft\\Windows\\Fonts\\CherryMonospace-Light.ttf
But still no result.
That's the directory of the font if anyone can help me please(Thanks in advanced)

**Comment by TheNotoriousAWP** [comment]
because there is already an iofonts pointer elsewhere in the code. I think it's in hooks.cpp or something. I changed mine to roboto regular.

**Comment by ddjem87** [comment]
this particular line that i wrote
io.Fonts->AddFontFromFileTTF(strcat(buffer, "\Fonts\CherryMonospace-Light.ttf"), 16.0f);

is from hooks.cpp but i does not change the actual font

**Comment by danielkrupinski** [comment]
You need to use double backslashes or single forward slashes.

**Comment by ddjem87** [comment]
They are in two backslashes I putted In () that they are they just don't appear here for some reason

**Comment by ddjem87** [comment]
Well i guess no one will help..
