### ISSUE TITLE
Chams issue

### ISSUE THREAD

**Issue by j13li78** [danielkrupinski/Osiris#1091]
Decals render above chams and they disappear after a specific distance even though the player isn't dormant.

**Comment by danielkrupinski** [comment]
Post screenshot please.

**Comment by j13li78** [comment]
![Counter-strike  Global Offensive Screenshot 2020 02 12 - 16 03 04 75](https://user-images.githubusercontent.com/40141174/74347321-37446200-4db1-11ea-9990-c3990ca4abc8.png)

**Comment by danielkrupinski** [comment]
Enable "Disable model occlusion" in "Misc".

**Comment by j13li78** [comment]
That worked thanks.
Also is it possible to get those glow chams?
![9p7p](https://user-images.githubusercontent.com/40141174/74347827-f8fb7280-4db1-11ea-8fce-d5c195c5443a.PNG)

**Comment by notgoodusename** [comment]
> That worked thanks.
> Also is it possible to get those glow chams?
> ![9p7p](https://user-images.githubusercontent.com/40141174/74347827-f8fb7280-4db1-11ea-8fce-d5c195c5443a.PNG)

yeah it is go to chams.cpp and vertixgeneric or something like that and change it

**Comment by j13li78** [comment]
also i noticed when you enable disable model occlusion you have to rejoin the game because it won't work otherwise.

**Comment by KarimFPS** [comment]
One more thing, Daniel can you make the occluded charm render in front smoke grenade.

**Comment by ZerGo0** [comment]
> That worked thanks.
> Also is it possible to get those glow chams?
> ![9p7p](https://user-images.githubusercontent.com/40141174/74347827-f8fb7280-4db1-11ea-8fce-d5c195c5443a.PNG)

Go into the Glow tab and set the glow style to 1, it will pulsate tho.

**Comment by j13li78** [comment]
> 
> 
> > That worked thanks.
> > Also is it possible to get those glow chams?
> > ![9p7p](https://user-images.githubusercontent.com/40141174/74347827-f8fb7280-4db1-11ea-8fce-d5c195c5443a.PNG)
> 
> Go into the Glow tab and set the glow style to 1, it will pulsate tho.

Yeah, I've already found that, but I don't want it to pulsate.
