### ISSUE TITLE
Cant build after update

### ISSUE THREAD

**Issue by d3faultdea7h** [danielkrupinski/Osiris#1093]
![image](https://user-images.githubusercontent.com/40793039/74361462-dd4a9900-4dbe-11ea-9117-db4e38cc46c1.png)

**Comment by playday3008** [comment]
https://github.com/playday3008/Osiris/actions/runs/38204239 All compiled successfully

**Comment by d3faultdea7h** [comment]
Thanks for the fast replied but i wanna know how can i fix this on the source so i can learn something with it

**Comment by IonutMindrescu** [comment]
> https://github.com/playday3008/Osiris/actions/runs/38204239 All compiled successfully

Thanks m8 :D

**Comment by notgoodusename** [comment]
> Thanks for the fast replied but i wanna know how can i fix this on the source so i can learn something with it

probably a {

**Comment by danielkrupinski** [comment]
Update your Visual Studio installation.
