### ISSUE TITLE
why the anti aim not working? 

### ISSUE THREAD

**Issue by smartxd3** [danielkrupinski/Osiris#1095]
i test tge anti aim alot of time and its diden't work
its need a update?
if some has fixed it, can tell me how please?

**Comment by CantRememberMyself** [comment]
choke some packets

**Comment by xAkiraMiura** [comment]
> choke some packets

doesnt help.

make your own AA if it doesn't work. 
[i recommend installing this](https://app.grammarly.com/)

**Comment by smartxd3** [comment]
i don't know how to make it.. is there any source working for osiris..

**Comment by xAkiraMiura** [comment]
i *had* made a better anti-aim, ive since deleted the repo but if you can somehow download it from the pull requests on this repo then you can try it.

**Comment by smartxd3** [comment]
i did see it but u tell us its not working and u will fix it

**Comment by xAkiraMiura** [comment]
nothing about it was broken.
I said I failed to sync the branch with master, you will be on an older version of Osiris if you choose to clone it so it's up to you to resync it.
