### ISSUE TITLE
[BUG] occluded charm

### ISSUE THREAD

**Issue by KarimFPS** [danielkrupinski/Osiris#1096]
Occluded charm does not render the model if player behide smoke, is this a bug or intended?

**Comment by ReconTheCat** [comment]
search up the definition of occluded

**Comment by xAkiraMiura** [comment]
> search up the definition of occluded

 search up the definition of occluded. your vision can be occluded. it's not limited to physically being unable to get through something.

**Comment by ReconTheCat** [comment]
> > search up the definition of occluded
> 
> search up the definition of occluded. your vision can be occluded. it's not limited to physically being unable to get through something.

your point? he's behind the smoke, occluded also means your vision can be obstructed yes, he's occluded therefore the function is doing it's job it's just a stupid question

**Comment by MinecraftGoodGame** [comment]
"occluded" is similar to "hidden", so if an enemy is hidden behind a smoke it should be considered "occluded"

**Comment by Cicker21** [comment]
the point is, there is a way to see the enemy through the smoke?
Also you can activate "Wireframe Smoke" at Visuals menu. But when you have this option sometimes Aimbot option "Only Visible" fails and hit hidden enemies...

**Comment by KarimFPS** [comment]
> the point is, there is a way to see the enemy through the smoke?
> Also you can activate "Wireframe Smoke" at Visuals menu. But when you have this option sometimes Aimbot option "Only Visible" fails and hit hidden enemies...

just use occluded for defusing and planting player. If you use wireframe smoke then its no legit anymore.
