### ISSUE TITLE
[Issue] Loading the cheat increases my input lag. 

### ISSUE THREAD

**Issue by SmakHvh-MadLad** [danielkrupinski/Osiris#1097]
I tested injecting the cheat and not injecting an it increases my input lag by alot is there a way to fix this

**Comment by KarimFPS** [comment]
How to check input lag ?

**Comment by SmakHvh-MadLad** [comment]
dunno but i dont need something to tell me that theres input lag i can feel it when im playing

**Comment by DasX** [comment]
autism is strong in you
