### ISSUE TITLE
Find a global team list

### ISSUE THREAD

**Issue by NexSqaud** [danielkrupinski/Osiris#1098]
Can you find and hook a global teams UtlVector (g_Teams)? I found that class in client.dll

https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/client/c_team.h

**Comment by danielkrupinski** [comment]
Loop through entity list and find `CTeam` entities.

**Comment by NexSqaud** [comment]
I have exception [here](https://imgur.com/a/hnMhBs9). What could it be?

**Comment by NexSqaud** [comment]
Uh i forgot check for null 🤦‍♂

**Comment by NexSqaud** [comment]
I checked entity list, there no CTeam entities
