### ISSUE TITLE
Detected

### ISSUE THREAD

**Issue by NexSqaud** [danielkrupinski/Osiris#110]
I was vac banned after use this cheat. I think your cheat is detected.

https://steamcommunity.com/id/zuhan1337

P.S. I was use new account and didn't use another cheat
P.P.S Injector: Process hacker

**Comment by effexcs** [comment]
Process hacker 
Are you serious?

**Comment by NexSqaud** [comment]
And something is wrong to use process hacker as injector?

**Comment by NexSqaud** [comment]
I also inject a cheat on this https://steamcommunity.com/id/gospodin_podmishkin account using process hacker, but it's not VAC banned

**Comment by sollywelch** [comment]
Man, being using this cheat for a few months, added junk code (lots of it) modified features / removed features and also used vm protect on the whole .dll had no problems with vac bans, also done the same to my injector! To be extra cautious I injector the cheat of an encrypted USB drive and remove it afterwards to make sure the injector is closed. This method works for me and I have had 0 problems just a few overwatch bans here and their!

**Comment by Shaxzy** [comment]
It is not detected, and even if it was it’s open source, make it undetected yourself.
