### ISSUE TITLE
Looking for a way to draw text on the screen

### ISSUE THREAD

**Issue by elgato69** [danielkrupinski/Osiris#1100]
Trying to add some features and so far have been able to find how to define the missing identifiers but i'm stuck on drawing some text on the screen, the source code i'm using uses something called g_Render->Text.
Just looking for an alternate in osiris, sorry if the answer is obvious, im new to all this stuff

**Comment by MinecraftGoodGame** [comment]
interfaces.surface->drawText(x1,x2,y1,y2)
but first u need to set color and font using interfaces.surface's other stuffs

**Comment by elgato69** [comment]
Thanks a million man

**Comment by littlehurensohn** [comment]
what a question :DDDDDDDDD

**Comment by elgato69** [comment]
no bully me i'm still new xD
