### ISSUE TITLE
[BUG] In Cyrillic version CS GO, I have question marks in skinchanger

### ISSUE THREAD

**Issue by playday3008** [danielkrupinski/Osiris#1101]
![unknown](https://user-images.githubusercontent.com/18056374/74538376-6509e200-4f3c-11ea-9ddf-c47a91d6e63e.png)
E.g.

**Comment by danielkrupinski** [comment]
You have to adjust Unicode ranges for GUI fonts to cover Cyrillic characters.

**Comment by playday3008** [comment]
![image](https://user-images.githubusercontent.com/18056374/74547261-1ebc7f00-4f4c-11ea-98aa-67e18970550b.png)
fixed, thx

**Comment by MinecraftGoodGame** [comment]
Input doesn't work anyway at least for me
