### ISSUE TITLE
Custom Hitmarker Sounds

### ISSUE THREAD

**Issue by CerberusGame** [danielkrupinski/Osiris#1102]
https://gyazo.com/f223951bbde62d02ff5f4361664a95ca

How do I add sounds to the hitmarker?

**Comment by NexSqaud** [comment]
Find sound in CS:GO files, add (here)[https://imgur.com/a/ZEUbhFt] "play SOUNDNAME", and add (here)[https://imgur.com/a/7QPNkPY] sound name for gui.

**Comment by Straightplus** [comment]
i think he wants to implement custom hitsounds...

**Comment by CerberusGame** [comment]
> i think he wants to implement custom hitsounds...

Exactly

**Comment by Straightplus** [comment]
Maybe add "custom" to your title?

**Comment by Oly-UK** [comment]
#1434
