### ISSUE TITLE
Mem pattern scan issue

### ISSUE THREAD

**Issue by sik0o** [danielkrupinski/Osiris#1104]
When i load the cheat i got a Scan pattern error, how can i fix this? Older versions always worked....

**Comment by danielkrupinski** [comment]
What error do you get?

**Comment by sik0o** [comment]
The addresses are always diff.... 

![pattern](https://user-images.githubusercontent.com/41169634/74568254-db780580-4f77-11ea-875d-a54bb1946fd9.png)

**Comment by sik0o** [comment]
One thing I did, deleted all "(const char8_t*)" because I had compile errors.
I'm a paster so don't know if this caused the issue...

**Comment by danielkrupinski** [comment]
You are using older version of the source code.

**Comment by sik0o** [comment]
Gonna try again... Ty for reply tho!
