### ISSUE TITLE
failed to find pattern

### ISSUE THREAD

**Issue by rafalohaki** [danielkrupinski/Osiris#1105]
commit dd74ac3d3aa2b52c938afeb5e4a399a80687dfde

![image](https://user-images.githubusercontent.com/20607107/74595186-d8941800-503e-11ea-9971-6dfc406f472e.png)

**Comment by danielkrupinski** [comment]
Nope, now we don't have that error message. Also error icon has been replaced with a warning. Update your source code.

**Comment by rafalohaki** [comment]
ok.ty
