### ISSUE TITLE
[Code issue] Making game crash.

### ISSUE THREAD

**Issue by rosesware** [danielkrupinski/Osiris#1106]
I recently added a "_Left hand knife_" and "_Right hand knife_" to Osiris, but in-game crash when I play on **community servers (surf combat)**, here the code:
```
void Misc::handKnife() noexcept
{
	const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
	if (!localPlayer)
		return;
	if (!localPlayer->isAlive())
		return;

	if (config.misc.leftHandKnife)
	{
		static auto leftHandKnife = interfaces.cvar->findVar("cl_righthand");
		const auto activeWeapon = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer())->getActiveWeapon();
		if (activeWeapon->isKnife())
		{
			leftHandKnife->setValue(0);
		}
		else
		{
			leftHandKnife->setValue(1);
		}
	}
	else
	if (config.misc.rightHandKnife)
	{
		static auto rightHandKnife = interfaces.cvar->findVar("cl_righthand");
		const auto activeWeapon = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer())->getActiveWeapon();
		if (activeWeapon->isKnife())
		{
			rightHandKnife->setValue(1);
		}
		else
		{
			rightHandKnife->setValue(0);
		}
	}
}
```
I already know the code can be more simplified and maybe wrong but it's working (I mean, I think so).
**The issue is, when I fall in void and "_respawn_"/"_appears_" in surf named jail it crash the game without any reason.**

Code seems the same: https://github.com/danielkrupinski/Osiris/pull/993

**Comment by woah1337** [comment]
`const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
const auto activeWeapon = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer())->getActiveWeapon();`

da fuk

**Comment by NexSqaud** [comment]
Build in debug mode, attach debugger to game, inject cheat with loadlibrary method. When it crash check where issue.

**Comment by tirziz** [comment]
pretry sure there is a pull request has this feature, try to search it maybe

**Comment by rosesware** [comment]
> btw if(!activeweapon) return but ur code looks pretty bad rn

I literally just copy-pasted, and change some thinks that I needed, I know it's pasted and it's wrong, maybe a "Swap knife" would be better, but I'm completely newbie with this.

**Comment by woah1337** [comment]
> > btw if(!activeweapon) return but ur code looks pretty bad rn
> 
> I literally just copy-pasted, and change some thinks that I needed, I know it's pasted and it's wrong, maybe a "Swap knife" would be better, but I'm completely newbie with this.

made a simple left hand knife as an example
``
void leftHandKnife() noexcept
{
	static auto knifeVar = interfaces.cvar->findVar("cl_righthand");
	const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
	if (!localPlayer || !localPlayer->isAlive) return;
	const auto activeWeapon = localPlayer->getActiveWeapon();
	if (!activeWeapon) return;
	activeWeapon->isKnife() ? knifeVar->setValue(0) : knifeVar->setValue(1);
}``

**Comment by rosesware** [comment]
> > > btw if(!activeweapon) return but ur code looks pretty bad rn
> > 
> > 
> > I literally just copy-pasted, and change some thinks that I needed, I know it's pasted and it's wrong, maybe a "Swap knife" would be better, but I'm completely newbie with this.
> 
> made a simple left hand knife as an example
> 
> ```c++
> void leftHandKnife() noexcept
> {
> 	static auto knifeVar = interfaces.cvar->findVar("cl_righthand");
> 	const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
> 	if (!localPlayer || !localPlayer->isAlive) return;
> 	const auto activeWeapon = localPlayer->getActiveWeapon();
> 	if (!activeWeapon) return;
> 	activeWeapon->isKnife() ? knifeVar->setValue(0) : knifeVar->setValue(1);
> }
> ```

Thanks I will test and say something.

**Comment by rosesware** [comment]
_@woah1337_ 

It's working fine, just needed to add `()` next to `isAlive`.
