### ISSUE TITLE
Radio , Player List and lua execution

### ISSUE THREAD

**Issue by giangero1** [danielkrupinski/Osiris#1107]
![image](https://user-images.githubusercontent.com/56077913/74603240-2dc13f80-50ba-11ea-99df-4b148649adc1.png)
First two features i think daniel can add them really easily idk about lua execution that would be hard.
if anyone can add the first two features that would be awesome in pull requests .

**Comment by 0x1Eren** [comment]
Radio? Your actually going to listen to a fucking radio? Just open up your web brower and search it through that. Or add it yourself. I think it would be a waste of time to add a radio into some cheat. About the LUA, Great idea but where are you thinking to get them?

**Comment by giangero1** [comment]
https://github.com/es3n1n/boynexthook_lua

**Comment by giangero1** [comment]
they have a really good dubstep radio i can't find it on the internet :P

**Comment by giangero1** [comment]
Player list is also very important to know Live hp money weapon and ammo

**Comment by giangero1** [comment]
whatever i'm just using both cheats at the same time to have those extra features :D

**Comment by giangero1** [comment]
https://media.discordapp.net/attachments/678576592636739591/678578516970962964/IMG_20200216_142808.jpg?width=1142&height=643

**Comment by effex1337** [comment]
> ![image](https://user-images.githubusercontent.com/56077913/74603240-2dc13f80-50ba-11ea-99df-4b148649adc1.png)

got the src for this?

**Comment by woah1337** [comment]
why do you want lua execution in an open source cheat? 🤔 🤔 🤔

**Comment by dctrlight** [comment]
player list could be helpful radio and luas are just really dumb

**Comment by xAkiraMiura** [comment]
> 
> 
> whatever i'm just using both cheats at the same time to have those extra features :D

nobody explain to them how foolish this is, lets just let them see how it backfires

**Comment by CantRememberMyself** [comment]
playerlist is easy

**Comment by giangero1** [comment]
> > whatever i'm just using both cheats at the same time to have those extra features :D
> 
> nobody explain to them how foolish this is, lets just let them see how it backfires

it's epic an epic result actually https://youtu.be/mPwvaHi2B8Y and i didn't get copyright striked from the radio cause it was playing so low, you just have to disable some features(third person and knife skinchanger had an issue) from osiris that interfere with boysnexthook and boom works like a charm.

**Comment by GoGixdd** [comment]
wtf ahahaa, 
We are have bugged lua, but at hte moment i'm fixed trash code and lua works fine without crashes.
