### ISSUE TITLE
[Question] Auto load CFG

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#1108]
I have a question.
I have created a cfg called: LIGIT_1
How should I do or what part of the code should I change , so that every time I load the cheat, LEGIT_1 is automatically loaded without having to go to the CONFIG / LOAD tab ?

Thank you

(Sorry for my english)

**Comment by xAkiraMiura** [comment]
Osiris.cpp

do `Config.Load('LIGIT_1')` at the end of the file.
^ probably the wrong calling convention so go into menu.cpp and see how its called.

**Comment by NexSqaud** [comment]
do `config.load(0);` at the end of Hooks::Hooks() method in Hooks.cpp file

**Comment by ifoverload** [comment]
i'd rather using "last loaded config" system for this...

**Comment by CSGOCheatsArg** [comment]
> i'd rather making/using "last loaded config" system for this...

Good idea
