### ISSUE TITLE
VAC Error

### ISSUE THREAD

**Issue by eschram** [danielkrupinski/Osiris#1109]
Cheat is blocking vac systems and randomly disconnects me from games.

**Comment by danielkrupinski** [comment]
Nope, it's not.

**Comment by eschram** [comment]
it is... cus its been doing it for me.

**Comment by xAkiraMiura** [comment]
you account may be subject to vac deep scans or you're just being VAC Authed.

**Comment by NexSqaud** [comment]
Check game cache, change your injector, use manual map injector
