### ISSUE TITLE
[Question] Recommended Injector

### ISSUE THREAD

**Issue by eschram** [danielkrupinski/Osiris#1110]
Is there any good undetected injector I should be using? I am currently using Lit Injector 1.6.1 and it seems to be fine but idk.

**Comment by Laxybaxy** [comment]
i used rando as a base for mine

**Comment by CSGOCheatsArg** [comment]
https://github.com/danielkrupinski/curiuminjector-csgo

**Comment by NexSqaud** [comment]
https://github.com/danielkrupinski/Inflame

**Comment by tirziz** [comment]
https://github.com/bananasss00/Rando-Injector
