### ISSUE TITLE
[SUGGESTION] Please add fov drawing

### ISSUE THREAD

**Issue by playday3008** [danielkrupinski/Osiris#1111]
Add fov drawing please
Like this https://i.gyazo.com/dc92fb2f3660bea6da9e79332a65c84d.png

**Comment by playday3008** [comment]
![20200217_161911](https://user-images.githubusercontent.com/18056374/74666244-756ec680-51a1-11ea-8d72-fcf5a29be370.png)
Lol

**Comment by tirziz** [comment]
#827 use search function plz

**Comment by NexSqaud** [comment]
#310

**Comment by Evilhelder** [comment]
#1114  Easy

**Comment by playday3008** [comment]
> #1114 Easy

Ok, working https://github.com/playday3008/Osiris/actions/runs/42075307
