### ISSUE TITLE
[NOT AN ISSUE] I need some suggestions for AIM settings

### ISSUE THREAD

**Issue by Vaadaaa** [danielkrupinski/Osiris#1116]
Hello, guys!

I am really a new Player at this game i am also suck at spray so, the only reason I use this is, spray control/aimasist(more like hitting the enemy)
So I am looking for some suggestions to make my config legit and useful for me, here are my settings for AK47, Is it so obv? Or legit? I don't want to get reported because of this it looks fine in game but As I said i am really new at this game i don't know the things well, I also don't use wallhack or ESP, I am suck at spray so, that's why  I use it, Anyway I am asking you guys are these settings good enough(legit)?
 If not can you tell me what should i change? Thanks!
My config:
![YOPbgcE](https://user-images.githubusercontent.com/60470027/74761938-f6a38780-528d-11ea-82d0-1a690a74aa4a.png)

**Comment by tirziz** [comment]
try #769 and Recoil crosshair, its legit enough

**Comment by Vaadaaa** [comment]
> try #769 and Recoil crosshair, its legit enough
Hey, thanks for the answer and what do you mean by 769? Is there a config in that topic? Can you link me that pls?

**Comment by tirziz** [comment]
It is a pull request of Standalone RCS

**Comment by Zadeys** [comment]
you should practice and get used to the aimbot

**Comment by Vaadaaa** [comment]
> you should practice and get used to the aimbot

Are these settings legit? Or should i change something?
