### ISSUE TITLE
How to add junkcode

### ISSUE THREAD

**Issue by Zadeys** [danielkrupinski/Osiris#1117]
Hi i am new to this and i really want to know how to add junkcode to help to make the cheat undetectable.

**Comment by CSGOCheatsArg** [comment]
The cheat is undetectable
You can add more security with VMProtect

**Comment by VuBrian22** [comment]
There is no need to add junkcode to this cheat.

**Comment by kekikcilerakin** [comment]
I don't understand how an open source cheat doesn't detected, can someone explain to me?

**Comment by NexSqaud** [comment]
That not popular free cheat, like CSGOSimple or Eternity

**Comment by NexSqaud** [comment]
@Zadeys You can use VAC Bypass Loader to disable VAC

**Comment by VuBrian22** [comment]
> I don't understand how an open source cheat doesn't detected, can someone explain to me?

This cheat uses signatures fro detection. Currently VAC doesn't seem to detect those signatures that match the database of detected ones. However not all cheats are undetectable. Osiris can be detected at anytime if VAC has hold of the cheat's signature.

**Comment by kekikcilerakin** [comment]
@NexSqaud @VuBrian22 thank you guys.

**Comment by VuBrian22** [comment]
@kekikcilerakin np

**Comment by littlehurensohn** [comment]
> > I don't understand how an open source cheat doesn't detected, can someone explain to me?
> 
> This cheat uses signatures for detection. Currently VAC doesn't seem to detect those signatures that match the database of detected ones. However not all cheats are undetectable. Osiris can be detected at anytime if VAC has hold of the cheat's signature.

There is PEB, thats why cheat is undetected, next what can be good is ErasePE.

**Comment by dctrlight** [comment]
Please dont rely on junk code to make it undetected. You can just use the cheat as it is undetected for now.

**Comment by xAkiraMiura** [comment]
> 
> 
> The cheat is undetectable

texas, is that you?

> You can add more security with VMProtect

or you can write your own polymorphic injector

> @kekikcilerakin That not popular free cheat, like CSGOSimple or Eternity

CSGOSimple isn't a popular free cheat? it's a base.

> > > snip~
> > >
> > snip~
> 
> There is PEB, thats why cheat is undetected, next what can be good is ErasePE.

i don't think thats how it works.


there is a paster by the name of Zadey on YouTube that has made pasting tutorials that show you how to make junk code @Zadeys 

make sure you spoof `cl_junkcode` to 1 😉

**Comment by NexSqaud** [comment]
> CSGOSimple isn't a popular free cheat? it's a base.
English not my native language, i wanted to say "not as popular as"

**Comment by littlehurensohn** [comment]
> > The cheat is undetectable
> 
> texas, is that you?
> 
> > You can add more security with VMProtect
> 
> or you can write your own polymorphic injector
> 
> > @kekikcilerakin That not popular free cheat, like CSGOSimple or Eternity
> 
> CSGOSimple isn't a popular free cheat? it's a base.
> 
> > > > snip~
> > > 
> > > 
> > > snip~
> > 
> > 
> > There is PEB, thats why cheat is undetected, next what can be good is ErasePE.
> 
> i don't think thats how it works.
> 
> there is a paster by the name of Zadey on YouTube that has made pasting tutorials that show you how to make junk code @Zadeys
> 
> make sure you spoof `cl_junkcode` to 1

junkcode in 2k20 what a dawg

**Comment by ADGAYMILK** [comment]
> > I don't understand how an open source cheat doesn't detected, can someone explain to me?
> 
> This cheat uses signatures for detection. Currently VAC doesn't seem to detect those signatures that match the database of detected ones. However not all cheats are undetectable. Osiris can be detected at anytime if VAC has hold of the cheat's signature.

I think VAC will detect file hash
So I often change that text like"That's a triumph." to "Ojbk,Loaded"
then hash changed

**Comment by xAkiraMiura** [comment]
if you are paranoid about your strings getting sigged then just use a compile time string encoder... like `xorstring`.

also why would Valve sig "That's a triumph." over "Aimbot" or even "ESP"? 1 targets a single cheat while the others target almost all cheats in existence.
