### ISSUE TITLE
General & Visuals

### ISSUE THREAD

**Issue by matoqueimado** [danielkrupinski/Osiris#1118]
When you plant the C4 the selfchams stop working please fix and clantag changer
(Sugestion: Add chams for ragdolls improve the grenade trajetory and improve the one window menu add a legit resolver and a legit aa (i know this is retard for a free cheat but you make a really very good work))

**Comment by dctrlight** [comment]
Try and set 'Planting' chams for the local chams problem

**Comment by danielkrupinski** [comment]
Should be fixed now.
