### ISSUE TITLE
[Question] How to center text

### ISSUE THREAD

**Issue by sweetymaya** [danielkrupinski/Osiris#1119]
So was wondering how could i center the text i have ontop that has aimbot, esp etc
https://i.imgur.com/1UlCtgq.jpg

**Comment by NexSqaud** [comment]
auto screenSize = interfaces.surface->getScreenSize();
float screenCenterX = screenSize.first / 2;
float screenCenterY = screenSize.second / 2;

**Comment by 3Ld4D** [comment]
`
auto text = "Aimbot";
auto windowCenter = ImGui::GetWindowSize().x / 2;
auto textCenterX = ImGui::CalcTextSize(text).x / 2;
ImGui::SetCursorPosX(windowCenter - textCenterX);
`
