### ISSUE TITLE
i can see people in smokes?

### ISSUE THREAD

**Issue by xdd929292** [danielkrupinski/Osiris#1120]
Have no idea what i did but why is this happening https://i.imgur.com/G7McGgb.jpg

**Comment by hyperxpro** [comment]
> Have no idea what i did but why is this happening https://i.imgur.com/G7McGgb.jpg

LMAO

**Comment by rosesware** [comment]
Normally or some feature or glitch? 'Cause if it's a glitch we can make this being a feature.

**Comment by danielkrupinski** [comment]
It's the same problem as https://youtu.be/yZxI4qdyVXM. I've reverted recent changes, so this bug won't occur unless you check "Disable model occlusion" option.
