### ISSUE TITLE
How to get da osiris.dll?

### ISSUE THREAD

**Issue by TomVonNebenan** [danielkrupinski/Osiris#1121]
Having issues getting the osiris.dll.
Using the old dll, i now get a crash of CS:GO.
Please give me a full description.
I just downloaded old versions of Osiris, there the .dll was given. 
In the newest one theres just a description how to get it. 
Please help me and give me a better description or send me the right .dll

**Comment by NexSqaud** [comment]
download new version, replace old files, recompile

**Comment by KuteKetX** [comment]
just pull the most recent source code from the repo then compile

**Comment by TomVonNebenan** [comment]
@NexSqaud 
Bro, its not working any more. Im getting a fucking crash

**Comment by NexSqaud** [comment]
just download new version from repo and compile
![Screenshot_110](https://user-images.githubusercontent.com/27753846/74864417-1e741780-5382-11ea-8b89-29e770980546.png)

**Comment by rosesware** [comment]
Dyslexia is actually a problem.

**Comment by xAkiraMiura** [comment]
Run this in cmd.exe
`cd %appdata%/../../Desktop & git clone https://github.com/danielkrupinski/Osiris.git & cd Osiris & Osiris.sln`
You will need git for windows and visual studio installed.
then at the top click `Debug` and select `Release`.
next use `Ctrl + B`
a DLL will be dropped into the Osiris folder on your desktop somewhere.
