### ISSUE TITLE
SetToolTip

### ISSUE THREAD

**Issue by CerberusGame** [danielkrupinski/Osiris#1122]
How can I use SetToolTip in the menu ?

**Comment by littlehurensohn** [comment]
SetToolTip("blah blah");

Dont forget to add IsItemHovered

**Comment by xAkiraMiura** [comment]
# congratulations, your pseudo code is wrong.

SetTooltip definition: `void ImGui::SetTooltip(const char*);`
IsItemHovered definition: `bool ImGui::IsItemHovered();`

Example:

    if (ImGui::IsItemHovered()) {
        ImGui::SetTooltip("Example Tooltip");
    }

If you're doing `using namespace ImGui;` then your making a big mistake.

**Comment by littlehurensohn** [comment]
> # congratulations, your pseudo code is wrong.
> SetTooltip definition: `void ImGui::SetTooltip(const char*);`
> IsItemHovered definition: `bool ImGui::IsItemHovered();`
> 
> Example:
> 
> ```
> if (ImGui::IsItemHovered()) {
>     ImGui::SetTooltip("Example Tooltip");
> }
> ```
> 
> If you're doing `using namespace ImGui;` then your making a big mistake.

yo, i forgot to ImGui:: but who cares, still i hope too many of you have brain and dont forget to add it lmfao fagg

**Comment by xAkiraMiura** [comment]
# toxic

also make sure to do `using namespace std;` 😉
