### ISSUE TITLE
bunnyhop legit ?

### ISSUE THREAD

**Issue by naomi721** [danielkrupinski/Osiris#1123]
I wonder if you have how to put bunnyhop legit with hitchance

**Comment by dctrlight** [comment]
#389

**Comment by KernCS** [comment]
I personally use "human bhop" taken from another cheat, but I fixed it to work in osiris

`
void Misc::human_bhop(UserCmd* cmd) noexcept
{
    static int hops_restricted = 0;
    static int hops_hit = 0;

    if (auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer()); config.misc.human_bhop

        && localPlayer->moveType() != MoveType::LADDER) {
        if (cmd->buttons & UserCmd::IN_JUMP && !(localPlayer->flags() & 1)) {
            cmd->buttons &= ~UserCmd::IN_JUMP;
            hops_restricted = 0;
        }
        else if ((rand() % 100 > config.misc.bhop_hit_chance			//chance of hitting first hop is always the same, the 2nd part is that so it always doesn't rape your speed
            && hops_restricted < config.misc.hops_restricted_limit)	//the same amount, it can be made a constant if you want to or can be removed, up to you
            || (config.misc.max_hops_hit > 0							//force fuck up after certain amount of hops to look more legit, you could add variance to this and
                && hops_hit > config.misc.max_hops_hit))				//everything but fuck off that's too much customisation in my opinion, i only added this one because prof told me to
        {
            cmd->buttons &= ~UserCmd::IN_JUMP;
            hops_restricted++;
            hops_hit = 0;
        }
        else
            hops_hit++;
    }
}
`

**Comment by naomi721** [comment]
> Eu pessoalmente uso o "bhop humano" retirado de outra fraude, mas eu o consertei para trabalhar em osíris
> 
> void Misc :: human_bhop (UserCmd * cmd) noexcept
> {
> static int hops_restricted = 0;
> static int hops_hit = 0;
> 
> ```
> if (auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer()); config.misc.human_bhop
> 
>     && localPlayer->moveType() != MoveType::LADDER) {
>     if (cmd->buttons & UserCmd::IN_JUMP && !(localPlayer->flags() & 1)) {
>         cmd->buttons &= ~UserCmd::IN_JUMP;
>         hops_restricted = 0;
>     }
>     else if ((rand() % 100 > config.misc.bhop_hit_chance			//chance of hitting first hop is always the same, the 2nd part is that so it always doesn't rape your speed
>         && hops_restricted < config.misc.hops_restricted_limit)	//the same amount, it can be made a constant if you want to or can be removed, up to you
>         || (config.misc.max_hops_hit > 0							//force fuck up after certain amount of hops to look more legit, you could add variance to this and
>             && hops_hit > config.misc.max_hops_hit))				//everything but fuck off that's too much customisation in my opinion, i only added this one because prof told me to
>     {
>         cmd->buttons &= ~UserCmd::IN_JUMP;
>         hops_restricted++;
>         hops_hit = 0;
>     }
>     else
>         hops_hit++;
> }
> ```
> 
> }

poderia colacar o codigo direto no misc ? ou teria que add alguma coisa em outro arquivo ?

**Comment by KernCS** [comment]
> > Eu pessoalmente uso o "bhop humano" retirado de outra fraude, mas eu o consertei para trabalhar em osíris
> > void Misc :: human_bhop (UserCmd * cmd) noexcept
> > {
> > static int hops_restricted = 0;
> > static int hops_hit = 0;
> > ```
> > if (auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer()); config.misc.human_bhop
> > 
> >     && localPlayer->moveType() != MoveType::LADDER) {
> >     if (cmd->buttons & UserCmd::IN_JUMP && !(localPlayer->flags() & 1)) {
> >         cmd->buttons &= ~UserCmd::IN_JUMP;
> >         hops_restricted = 0;
> >     }
> >     else if ((rand() % 100 > config.misc.bhop_hit_chance			//chance of hitting first hop is always the same, the 2nd part is that so it always doesn't rape your speed
> >         && hops_restricted < config.misc.hops_restricted_limit)	//the same amount, it can be made a constant if you want to or can be removed, up to you
> >         || (config.misc.max_hops_hit > 0							//force fuck up after certain amount of hops to look more legit, you could add variance to this and
> >             && hops_hit > config.misc.max_hops_hit))				//everything but fuck off that's too much customisation in my opinion, i only added this one because prof told me to
> >     {
> >         cmd->buttons &= ~UserCmd::IN_JUMP;
> >         hops_restricted++;
> >         hops_hit = 0;
> >     }
> >     else
> >         hops_hit++;
> > }
> > ```
> > 
> > 
> > }
> 
> poderia colacar o codigo direto no misc ? ou teria que add alguma coisa em outro arquivo ?

Read the code and you can see what you need to do "&& hops_hit > config.misc.max_hops_hit))" aka				config.misc.max_hops_hit <--- legit tells you were to put it
