### ISSUE TITLE
How to Chinese it

### ISSUE THREAD

**Issue by hackmln** [danielkrupinski/Osiris#1125]
How to Chinese it

**Comment by zHElEARN** [comment]
Add a macro definition
```c++
#define U8(S) reinterpret_cast<const char *>(u8##S)
```
Then ```U8("中文")```

**Comment by hackmln** [comment]
老哥留个联系方式 或者加我QQ1940135998 学习一下

**Comment by hackmln** [comment]
> Add a macro definition
> 
> ```c++
> #define U8(S) reinterpret_cast<const char *>(u8##S)
> ```
> 
> Then `U8("中文")`

老哥留个联系方式 或者加我QQ1940135998 学习一下

**Comment by thomas0aotian** [comment]
作于汉化倒卖的话不教

**Comment by zHElEARN** [comment]
> 
> 
> 作于汉化倒卖的话不教

OK

**Comment by zHElEARN** [comment]
> 
> 
> 作于汉化倒卖的话不教

But this project is the MIT open source license, he can close the source again

**Comment by Mankvis** [comment]
> Add a macro definition
> 
> ```c++
> #define U8(S) reinterpret_cast<const char *>(u8##S)
> ```
> 
> Then `U8("中文")`

你好，请问这个具体在哪个文件呢
