### ISSUE TITLE
Hack Updates

### ISSUE THREAD

**Issue by Cicker21** [danielkrupinski/Osiris#1131]
It's Reportbot updated and working?
AntiAim doesn't work since a while...

Thank you developer for updating this software from time to time, my best wishes.

**Comment by ZerGo0** [comment]
The Reportbot has been updated the same day it got updated by Valve.

AntiAim works as well just increase the choke packets amount in the misc menu.

**Comment by smartxd3** [comment]
where is this choke packets?

**Comment by xAkiraMiura** [comment]
misc
