### ISSUE TITLE
[Suggestion] Team Damage Counter

### ISSUE THREAD

**Issue by Evilhelder** [danielkrupinski/Osiris#1134]
This function would be nice, showing the total damage you did to your team (thus preventing you from taking a suspension for TK), and showing the damage your allies did to each other (Also giving information in case you are trolling, being able to ban allies.)

It's a pretty stupid function, but it's cool.

Discuss:  https://www.unknowncheats.me/forum/counterstrike-global-offensive/307950-team-damage-counter.html

SC:
![image](https://user-images.githubusercontent.com/33970481/75085420-ccf59500-5507-11ea-9566-6f411237bf37.png)

**Comment by xAkiraMiura** [comment]
[player_hurt ](https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events#player_hurt) event in [fireEventClientSide](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hooks.cpp#L325)

if playerID == localplayerID then increment a variable by the damage

logging it to the in-game console would require an external function i don't think is currently in Osiris.

**Comment by danielkrupinski** [comment]
@xAkiraMiura We have memory.debugMsg function.
