### ISSUE TITLE
NO LONGER UNDETECTED

### ISSUE THREAD

**Issue by Aidan7831** [danielkrupinski/Osiris#1139]
this cheat is no longer undetected, i tried installing it but not using any cheats on a seperate account (not activating any settings) and within a day my account got vacd

**Comment by AlexanderQueen** [comment]
Detected injector.

**Comment by AbdallahMehiz** [comment]
it is undetected, might be your injector

**Comment by rosesware** [comment]
Why you open an issue saying the cheat is "NO LONGER UNDETECTED"?

**Comment by xAkiraMiura** [comment]
put the dll on a non-system partition 4head.
VAC checks the USN journels for your C: partition. (not the physical drive, just the mount)

if you don't have a second drive you can make a seperate partition and then mount it.

**Comment by VuBrian22** [comment]
VAC is supposed to be non-intrusive anyway.

**Comment by tirziz** [comment]
Its undetected at the moment . Try a different injector maybe

**Comment by yEsPaP** [comment]
use VAC Bypass loader lmao

**Comment by ClaudiuHKS** [comment]
Just inject **Osiris** into **csgo.exe** by using a simple injector that only needs **VirtualAllocEx**, **WriteProcessMemory** and **CreateRemoteThread**. It will be completely undetected. Or you can use any other injector that people say about it that it's undetected. Don't use random injectors. Some manual map injectors cause vac detections even on undetected cheats such **Osiris**.

**Comment by vsnrytune** [comment]
> Just inject **Osiris** into **csgo.exe** by using a simple injector that only needs **VirtualAllocEx**, **WriteProcessMemory** and **CreateRemoteThread**. It will be completely undetected. Or you can use any other injector that people say about it that it's undetected. Don't use random injectors. Some manual map injectors cause **VAC** detections even on undetected cheats such **Osiris**.

What injectors do you recommend? Is RandoInjector good enough?

**Comment by xAkiraMiura** [comment]
RandoInjector is too popular so a core function of it is probably sigged. (I don't know exactly how VAC works on injectors.)
You can try [Inflame](https://github.com/danielkrupinski/inflame), an injector made by daniel. It has both LoadLibrary and ManualMap injection methods.
