### ISSUE TITLE
player shadows

### ISSUE THREAD

**Issue by AndreasYNY** [danielkrupinski/Osiris#1140]
Hello, i notice this thing where player shadows will not displayed.....well i use this to live/recording so it's obv that i'm cheating if the shadows is gone....
![20200223010812_1](https://user-images.githubusercontent.com/46004308/75097145-039be000-55da-11ea-9301-9e714a562b69.jpg)

**Comment by HeadlessCpp** [comment]
visuals -> no shadows?

**Comment by xAkiraMiura** [comment]
make sure shadows are set to high in game settings, they don't have much of a performance impact.
if they were disabled in visuals then when re-enabling them will cause the game to freeze for 30s-2m.
if the game never resumes try pressing the menu key to close the menu, ImGui seems to freeze d3d.

**Comment by danielkrupinski** [comment]
Turn off "Disable model occlusion".
