### ISSUE TITLE
Auto Jumpbug

### ISSUE THREAD

**Issue by Vonr** [danielkrupinski/Osiris#1142]
Crouch when jumping and uncrouch when 4 units away from the ground.

(Prevents fall damage and allows for longer jumps but longer jumps probably requires different code)

**Comment by streamshark** [comment]
There's been a ton of requests for this, just search "jumpbug" in issues. I tried making it myself but only got it to work for jumps on flat ground with no height difference, my prediction was off, and the method I was attempting to use was a lot more primitive than some commonly used jumpbug sources ( https://www.unknowncheats.me/forum/cs-go-releases/365274-jumpbug-source.html . The link I posted is criticized for being crappy code, but the concept for doing it is there, and with engine prediction in Osiris now, it may be more feasible.

**Comment by Vonr** [comment]
https://pastebin.com/jQz1Y6xV
https://pastebin.com/qwMUfUBJ
https://pastebin.com/fbS8tBeZ

some sources i found with a quick google search

**Comment by Vonr** [comment]
and as for engine prediction, i have no clue what it does or how to use it. im also bad at c++ and i hate the language which is why i didnt even try to do it myself

**Comment by Vonr** [comment]
closed because duplicate of like 7 issues

**Comment by effex1337** [comment]
Finally a smart man!

**Comment by Vonr** [comment]
i regret to inform you that opening a duplicate issue is in itself dumb. therefore i am dumb. speaking of which i need help with getting the shiz done. its like 90% complete but i have no idea what MASK_SOLID_BRUSHONLY is

**Comment by Vonr** [comment]
found it in gmod docs

**Comment by Vonr** [comment]
https://wiki.facepunch.com/gmod/Enums/MASK for anyone who needs it
