### ISSUE TITLE
Fakeban

### ISSUE THREAD

**Issue by SAmme064** [danielkrupinski/Osiris#1144]
The fake ban does not change color just text...

**Comment by xAkiraMiura** [comment]
either use a clantag or disconnect from the game.
you can use a zero width space so it appears like you don't have a clantag
^ copy and paste here: `​`

**Comment by SAmme064** [comment]
what do you mean?

**Comment by SAmme064** [comment]
nwm but how do i change back my name????

**Comment by danielkrupinski** [comment]
You have to attack your teammate then your colored name will appear in chat. To change your name back use `name` console command or reconnect to the server.

**Comment by SAmme064** [comment]
so the easiest way is to just disconnect after attacked teammate and then rejoin?

**Comment by SAmme064** [comment]
and also the anti aim. how can you see it?
