### ISSUE TITLE
csgo closes after injecting and loading the map

### ISSUE THREAD

**Issue by CSGOCheatsArg** [danielkrupinski/Osiris#1145]
csgo closes after injecting and loading the map
I am using the curiuminjector-csgo-master as usual. this started happening today after the last update

**Comment by danielkrupinski** [comment]
Compile in debug mode, attach debugger to csgo process, inject dll and when it crashes make screenshot of what debugger says and post it here.

**Comment by yEsPaP** [comment]
> csgo closes after injecting and loading the map
> I am using the curiuminjector-csgo-master as usual. this started happening today after the last update

strang works fine here

**Comment by CSGOCheatsArg** [comment]
Now Works! It was a strange thing, I haven't touched anything. It must have been something random. Thanks
