### ISSUE TITLE
My shetty pickup line

### ISSUE THREAD

**Issue by anonymouschicken1111** [danielkrupinski/Osiris#1146]
`Are you a github repository, because I want to commit to you.`

If your girlfriend is a programmer and uses GitHub try this on her. 

I guarantee that she'll love you for it.

**Comment by effex1337** [comment]
Um WHAT THE FUCK!!! 
😂😂😂😂😂😂😂😂

**Comment by anonymouschicken1111** [comment]
This issue section is plagued so why no spread some love

**Comment by barbadully** [comment]
cringe

**Comment by tirziz** [comment]
Its doesn't matter whatever you do when your crush doesn’t like you back

**Comment by RyDeem** [comment]
Are you a videogame software? 
Because i would like to reverse engineer your interiour with my dongle.
