### ISSUE TITLE
CUtlBTree overfloow (Problem)(SOLVED)

### ISSUE THREAD

**Issue by gaston010** [danielkrupinski/Osiris#1148]
I get this error after playing 10-30 minutes. It only happens with osiris. Anyone know what problem? (compile the .dll)

![error  cs go](https://user-images.githubusercontent.com/18094984/75179803-a73fda00-5719-11ea-93ac-3a1f29e78f46.png)

I'm sorry if it's not the place to ask,

**Comment by gaston010** [comment]
Solved , don't use a hold cfg , need create a new .

**Comment by xAkiraMiura** [comment]
close the issue, dont edit the title to just say solved.
