### ISSUE TITLE
Shaking aimbot

### ISSUE THREAD

**Issue by catahustle** [danielkrupinski/Osiris#115]
Smooth aimbot became not smooth, it shakes a lot

**Comment by danielkrupinski** [comment]
Increasing smooth factor should help you.

**Comment by catahustle** [comment]
https://www.youtube.com/watch?v=Yb7bEjw3bQ0 it is still shaking

**Comment by DaemonGFX** [comment]
the rcs only works on target

**Comment by danielkrupinski** [comment]
Updated aimbot, please check again.

**Comment by catahustle** [comment]
now aimbot is working fine
thx
