### ISSUE TITLE
Stream Proof

### ISSUE THREAD

**Issue by MrDioogo** [danielkrupinski/Osiris#1150]
add stream proof feature

**Comment by KibbeWater** [comment]
??

**Comment by dapaster** [comment]
https://github.com/danielkrupinski/GOESP

**Comment by MrDioogo** [comment]
@dapaster GOSESP does not have as many features as Osiris

**Comment by rosesware** [comment]
If @danielkrupinski start a project with "Stream Proof" is because he won't add "Stream Proof" for Osiris.

**Comment by playday3008** [comment]
You can inject GOESP and Osiris in one process
Ex. Osiris with aim, GOESP with WH

**Comment by xAkiraMiura** [comment]
bad idea, couldn't recommend.

**Comment by playday3008** [comment]
Maybe bad idea, but i try to inject GOESP and Osiris, and working

**Comment by MrDioogo** [comment]
thx, i'ill use GOESP and Osiris

**Comment by playday3008** [comment]
But don't enable conflict functions. Maybe crash, or something else.

**Comment by KibbeWater** [comment]
Expect more frequent crashes and laggy gameplay
