### ISSUE TITLE
Resolver

### ISSUE THREAD

**Issue by dctrlight** [danielkrupinski/Osiris#1152]
a simple resolver would be cool

**Comment by yEsPaP** [comment]
It's a legit cheat

**Comment by xAkiraMiura** [comment]
not a valid reason to be missing an entire feature.

**Comment by streamshark** [comment]
probably will need to implement spread/occlusion miss logging first, if you miss when you should have hit then mark them as desyncing and do some bruteforce

**Comment by 3bood0o0** [comment]
adding resolver will b good idea but i think it will b buged with the legit bot

**Comment by dctrlight** [comment]
The "it's a legit cheat" argument doesn't explain there being features like auto revovler or auto wall

**Comment by dctrlight** [comment]
plus many legit cheats have resolvers

**Comment by crtezgod** [comment]
maybe u got into a legit hvh so you need at least a resolver that can resolve legit desync

**Comment by notgoodusename** [comment]
u need another animstate and simple logic and you can make a resolver
