### ISSUE TITLE
 How to update Osiris.dll myself if CSGO is updated

### ISSUE THREAD

**Issue by AlisaCiya** [danielkrupinski/Osiris#1155]
If CSGO is updated, how should I update it to adapt to the new version。

**Comment by ClaudiuHKS** [comment]
If Osiris is not working anymore due to a CS:GO update, stop using it and constantly check the latest Osiris updates, here: https://github.com/danielkrupinski/Osiris/commits/master

When you see that Osiris has been updated (this usually takes a few hours), you download it again and rebuild it.
