### ISSUE TITLE
Invisible hands, weapon and models

### ISSUE THREAD

**Issue by gothdemon666** [danielkrupinski/Osiris#1156]
I have this problem. Can anyone help me?

When I load map i cant see my hands, weapons and models :/

**Comment by HeadlessCpp** [comment]
Do you have no hands, weapon ect on in visuals?

**Comment by gothdemon666** [comment]
**i have everything off and i cant see hands weapons or models " CT or T "**

**Comment by littlehurensohn** [comment]
Reset config.
