### ISSUE TITLE
UTF-8 WITH ROM BUG

### ISSUE THREAD

**Issue by jackieyiwu** [danielkrupinski/Osiris#1157]
UTF-8 WITH ROM BUG. The outher fonts The font is displayed as ???
When i change to UTF-8 WITHOUT ROM , it displayed correct .But the codes error.

**Comment by danielkrupinski** [comment]
> UTF-8 WITH ROM

Do you mean Romanian characters not being displayed?

**Comment by jackieyiwu** [comment]
> 
> 
> > UTF-8 WITH ROM
> 
> Do you mean Romanian characters not being displayed?

No. I mean the UTF-8 with signature cant displayed some characters,not the language, and if save as UTF without signature, some characters codes running erros.

**Comment by jackieyiwu** [comment]
> 
> 
> > UTF-8 WITH ROM
> 
> Do you mean Romanian characters not being displayed?

I think it's influenced by ImWchar ranges.The same translation in a character code becomes correct.

**Comment by jackieyiwu** [comment]
> 
> 
> > UTF-8 WITH ROM
> 
> Do you mean Romanian characters not being displayed?

I think it's influenced by ImWchar ranges.Sometimes it will be ok that translate with another agreed word.

**Comment by danielkrupinski** [comment]
Okay, should be fixed in f12c106daa4f380e2630846ca70d1bc6260632d4

**Comment by jackieyiwu** [comment]
> 
> 
> Okay, should be fixed in [f12c106](https://github.com/danielkrupinski/Osiris/commit/f12c106daa4f380e2630846ca70d1bc6260632d4)

TKS A LOT i WILLTRY
