### ISSUE TITLE
Adding a new hook

### ISSUE THREAD

**Issue by KibbeWater** [danielkrupinski/Osiris#1159]
Sorry, I'm very new at cpp but how would I go about adding a new hook like [this one](https://www.unknowncheats.me/forum/counterstrike-global-offensive/316562-earrape-custom-coloured-messages-pretending-ban-people.html)?

**Comment by unniggable** [comment]
i am not sure if that works anymore anyway

**Comment by KibbeWater** [comment]
> i am not sure if that works anymore anyway

worth a shot atleast

**Comment by Straightplus** [comment]
"15th January 2019, 05:47 AM"

**Comment by KibbeWater** [comment]
I really don't see the problem is trying. Valve is clearly very retarded and has left other retarded shit for a long time

**Comment by Scui1** [comment]
> 
> 
> I really don't see the problem is trying. Valve is clearly very retarded and has left other retarded shit for a long time

so are you...

**Comment by xAkiraMiura** [comment]
ive done testing. sending colored messages no longer works (at least with my implementation) but queue bombing still works and my friends might be deaf now (and spoofing player names).

**Comment by KibbeWater** [comment]
> ive done testing. sending colored messages no longer works (at least with my implementation) but queue bombing still works and my friends might be deaf now (and spoofing player names still works).

Oh great! they left the best part xP
Could you show how you implemented hook for it or send a sample so I can try implement it myself?

**Comment by Scui1** [comment]
Do you mean spoofing a players name when inviting still works, or does it work for any message?

**Comment by Scui1** [comment]
> 
> 
> ive done testing. sending colored messages no longer works (at least with my implementation) but queue bombing still works and my friends might be deaf now (and spoofing player names still works).

Do you mean spoofing a players name when inviting still works, or does it work for any message?

**Comment by xAkiraMiura** [comment]
when inviting.
oh and i forgot to mention that you can spoof player ranks (doesn't show up locally).
^ invited a gn with s1 spoofer and confused them.

on the original post there was a link to [another post](https://www.unknowncheats.me/forum/cs-go-releases/325060-lobby-chat-message-modifier.html) by the same OP.
in that he has a link to [a github repo](https://github.com/TrevenT/TrenenLobbyEngine).

[this appears to be the hook.](https://github.com/TrevenT/TrenenLobbyEngine/blob/master/TrenenLobbyEngine/cheat/hooking/Hooks.cpp#L5-L14)
...[and this appears to be the nuke.](https://github.com/TrevenT/TrenenLobbyEngine/blob/master/TrenenLobbyEngine/cheat/lobby/LobbyMod.cpp#L201-L215)
