### ISSUE TITLE
[Feature] Delay between target change

### ISSUE THREAD

**Issue by Sawuus** [danielkrupinski/Osiris#1160]
For now "legit" aimbotting at high ranks is almost impossible.
I use on key aimlock, and when I kill an enemy with a smooth ~ 4.5, the crosshair immediately begins to move to another enemy and I don't have enough time to release aimlock key.

There should be an option to set a delay (in milliseconds) between target changes.
When the aimbot wants to change the target it will wait for a certain amount of time.

**Comment by KibbeWater** [comment]
just set it to the shoot key?

**Comment by Sawuus** [comment]
> just set the bind to your shoot button

In many situations it is too slow and there is still a problem with full-auto, which kills all enemies at the same time

**Comment by KibbeWater** [comment]
> > just set the bind to your shoot button
> 
> In many situations it is too slow and there is still a problem with full-auto, which kills all enemies at the same time

Auto shoot in "high ranks" is just stupid. If you don't want to rage hack then legit hack, put on some smoothing, onkey to fire and so on. I haven't had any issues with it

**Comment by Sawuus** [comment]
> > > just set the bind to your shoot button
> > 
> > 
> > In many situations it is too slow and there is still a problem with full-auto, which kills all enemies at the same time
> 
> Auto shoot in "high ranks" is just stupid. If you don't want to rage hack then legit hack, put on some smoothing, onkey to fire and so on. I haven't had any issues with it

I have no idea what you're talking about. Like I said, I'm using aimlock with smooth 4.5, without auto-shooting oro anything like that.

**Comment by KibbeWater** [comment]
use manual not auto shoot. not shit it looks obvious

**Comment by KibbeWater** [comment]
it's not that hard to use it to confirm a deagle kill
