### ISSUE TITLE
Random crashes?

### ISSUE THREAD

**Issue by JaySlappin** [danielkrupinski/Osiris#1163]
Just wondering, is anyone else experiencing crashes after the recent updates? I'll crash around every 5 mins. Im only using radar and vis chams. Thanks all!

**Comment by xAkiraMiura** [comment]
are you using the most recent build?
are you running any other cheats with Osiris?

**Comment by NekoRem** [comment]
i was having the same problem but im pretty sure it was from my lua system

**Comment by JaySlappin** [comment]
honestly I thought it was one of the PR's i C+P'd but i guess not if someone else if having an issue @danielkrupinski

**Comment by JaySlappin** [comment]
> are you using the most recent build?
> are you running any other cheats with Osiris?

Yes, no. Only using osiris with some added PR's

**Comment by AbdallahMehiz** [comment]
yea the cheat crashes for me everytime i plant the bomb

**Comment by littlehurensohn** [comment]
i fx it

**Comment by JaySlappin** [comment]
> i fx it

Care to share?

**Comment by JaySlappin** [comment]
> yea the cheat crashes for me everytime i plant the bomb

Not having that problem, just tryed it

**Comment by steel4me** [comment]
Nothing is crashing when you take original repo with latest commits...maybe you integrated something what causes the crash. Some of the pull requests for example?

**Comment by dctrlight** [comment]
debugggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg

**Comment by JaySlappin** [comment]
> Nothing is crashing when you take original repo with latest commits...maybe you integrated something what causes the crash. Some of the pull requests for example?

Just confirmed this, my bad all, i dont know why that didnt occur to me anyway

**Comment by xAkiraMiura** [comment]
the pull you were cloning was probably behind on a patch
