### ISSUE TITLE
Anti-Aim

### ISSUE THREAD

**Issue by SAmme064** [danielkrupinski/Osiris#1164]
Is it possible to see the anti-aim? and change player direction??

**Comment by JaySlappin** [comment]
Only way to see your AA with base osiris is to go into a bot match and type "bot_mimic 1" into console. Bots will replicate the AA. I dont think you can change direction without C+Ping a pull request for AA but i might be wrong.

**Comment by JDeu** [comment]
What I use 

`void setDeadFlag(Vector angle) noexcept{ *reinterpret_cast<Vector*>((DWORD)this + 0x31D4 + 0x4) = angle; }` 

Place in entity then set when in thirdperson 😄

**Comment by notgoodusename** [comment]
> What I use
> 
> `void setDeadFlag(Vector angle) noexcept{ *reinterpret_cast<Vector*>((DWORD)this + 0x31D4 + 0x4) = angle; }`
> 
> Place in entity then set when in thirdperson

b1g fix

**Comment by DoomFishWasTaken** [comment]
made a pull close this #1546
