### ISSUE TITLE
Changing font?

### ISSUE THREAD

**Issue by unniggable** [danielkrupinski/Osiris#1166]
I am looking at the code but it says the font is 0x1d but what is this font and how would i go about changing it to another one?

**Comment by jimbob88** [comment]
# The Approach and Findings
The font `0x1d` is used for things such as the ESP text, and is defined for use in the ESP here:
```cpp
struct Esp {
        struct Shared {
            bool enabled{ false };
            int font{ 0x1d }; // the font used by the ESP
            ColorToggle snaplines;
            ColorToggle box;
            int boxType{ 0 };
            ColorToggle name;
            ColorToggle outline{ 0.0f, 0.0f, 0.0f };
            ColorToggle distance;
            float maxDistance{ 0.0f };
        };
```
This is actually a hexadecimal number, from the csgo console command: `vgui_spew_fonts`, I have placed the output of this command [here](https://pastebin.com/L2XdUzCU). 
The code `0x1d` comes from the line:
```
28: HFont:0x0000001d, MainMenuFont, MainMenuFontTracker-no, font:verdana bold, tall:16
```
As you can see it is simply `0x0000001d` with the middle 0s cut out. Theoretically one can change this value to any of the other hexadecimal numbers, just remove the middle 0s, you can find these numbers [here](https://pastebin.com/zxzkFTam).

For example, if one changes the text `0x1d`, to `0xbe`, in the afforementioned line of code:
```
  79: HFont:0xbe, Trebuchet18, Trebuchet18ClientScheme-p, font:Trebuchet MS, tall:40
```
Then the esp will now look like this:
![Example 0xbe](https://user-images.githubusercontent.com/9913366/76143982-b278fb00-6073-11ea-8e12-b9296ef8f89e.png)
Obviously this kind of font isn't exactly desireable, as it is absolutely massive. 

The issue with this is the fact, one's old configs save the current font so on loading a config the current font will reset to the font stored within that config.

# How to change your font easily ;)

If one wants to simply change the font in their existing config they should:

 * Download and install [notepad++](https://notepad-plus-plus.org/downloads/)
 * Go to your Documents folder, then the folder named Osiris
 * In here one should see your config files, if you don't have any you can [download this](https://drive.google.com/file/d/1rKu-bGzP7GAKFtJ5S1d5-egCgCANmcP5/view?usp=sharing), it is the default config of Osiris (so no hacks enabled), and place that file into your Documents -> Osiris folder
 * Right click the config file you wish to change the font of, and click `Edit with Notepad++`, notepad++ should open up with your config file.
 * Press Ctrl+F (Find), and type "Font" than hit the enter key, then the escape key.
 * You should see, around about line 1879, a line that says: `"Font" : 29,`
 * Change the number 29, to the [number at the start of the line + 1](https://pastebin.com/zxzkFTam), for example if I want to change my font to:
```
  56: HFont:0xa7, ClientTitleFont, ClientTitleFontClientScheme-no, font:Counter-Strike Logo, tall:59
```
I would replace `29` with `57` (which is 56+1)
 * Press Ctrl+S to save your changes and close notepad++
 * When you load Osiris on csgo your config should now have the changed font :)

Hope this helped,
Jim

**Comment by xAkiraMiura** [comment]
im pretty sure VGUI fonts are based on your installed Windows fonts, if you install the font to windows it might show up in the options.

**Comment by jimbob88** [comment]
> 
> 
> im pretty sure VGUI fonts are based on your installed Windows fonts (i've used this to put my menu in the Ubuntu font), if you install the font to windows it might show up in the options.

If one wants to load a VGUI font for IMGUI (the GUI software for Osiris) one could overwrite the lines ([45](https://github.com/danielkrupinski/Osiris/blob/04364371a5162e47461a6f50c5b920da71fd6b15/Osiris/GUI.cpp#L45)-[46](https://github.com/danielkrupinski/Osiris/blob/04364371a5162e47461a6f50c5b920da71fd6b15/Osiris/GUI.cpp#L46)) in GUI.cpp
```cpp
        fonts.tahoma = io.Fonts->AddFontFromFileTTF((path / "tahoma.ttf").string().c_str(), 15.0f, nullptr, ranges);
        fonts.segoeui = io.Fonts->AddFontFromFileTTF((path / "segoeui.ttf").string().c_str(), 15.0f, nullptr, ranges);
```

And change the strings `"tahoma.ttf"` and `"segoeui.ttf"` to the font one wanted to use for their ImGUI, my prior message focuses on the `0x1d` value which is what the question originally mentioned.

**Comment by unniggable** [comment]
Thanks for the detailed response. Answered my question and helped me understand how to change fonts.
