### ISSUE TITLE
How To Bypass VAC kick without changing Max Angle Delta?  

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#1167]
Is there any way to bypass VAC kick on casual or deathmatch without changing the Max Angle Delta to 30 while using AA? 

I tried using 

https://github.com/danielkrupinski/VAC-Bypass-Loader

But still getting VAC kick

**Comment by NexSqaud** [comment]
This a server-side checks, no way to bypass

**Comment by dapaster** [comment]
But p2c like onetap can rage without any prob . What method did they use?

**Comment by AbdallahMehiz** [comment]
> But p2c like onetap can rage without any prob . What method did they use?

lol, they actually get kicked. haven't you tested?

**Comment by dapaster** [comment]
Yes i try using otc on casual and not getting vac auth error

**Comment by AbdallahMehiz** [comment]
you get the auth error with any cheat you use if you went full rage.
i tried it with multiple cheats like otc, fatality(cracked), and aimware
