### ISSUE TITLE
skin changer bug?

### ISSUE THREAD

**Issue by JustinLatiao** [danielkrupinski/Osiris#1170]
When I used the default knife and gloves, the skin changer worked without any issues. But when I have my own knife and glove skin, even without using a skin changer. The animation of switching between weapons is abnormal and stuttered, and my own glove skin sometimes does not display

**Comment by danielkrupinski** [comment]
Please provide short video or gif demonstrating the issue.

**Comment by Bywnb** [comment]
> Please provide short video or gif demonstrating the issue.

OK, my friend's account has gloves, he raised the issue with me, but he's sleeping now. I will let him wake up and record a video showing the problem. According to his response, his glove skin became the default skin after he died once.

**Comment by lordeternity000** [comment]
It happens with me too but when i have default knife and use skinchanger for other knives like survival knife. Normal draw animation works fine but the " tossing in air and catching one" gets messed up in animation.
