### ISSUE TITLE
Micro laggs / freezes, angles broken? Since update 25.02.20

### ISSUE THREAD

**Issue by steel4me** [danielkrupinski/Osiris#1171]
Okay, it is hard to explain, thats why i made a video. But please read first. 

After last update from 25.02.20 i got strange micro laggs / freezes. Frames are constant, when i switch to desktop on second monitor, i see that my mouse movement stucks at the same time while i got this micro laggs / freezes. 

Anyway. I think my viewangles got fucked up at the same time i got those laggs/freezes i got a headshot in the video. Slowmotion begins at 0:11 and ends at 0:35. If you look exactly. My complete view was rotatet to the left with 10 degrees or something the complete slowmo time till end. I showed this video to some mates. They didnt understand what i mean. It is like a "crooked view" when you are on a "ship" xD

I had something similar 5 years ago, i forgot to clamp / normalize angles on silent aim in my code and got instant untrusted ban. I didnt closed csgo. After i was dead and respawned, view was normal. No ban till now. @ZerGo0 @danielkrupinski what do you think when you watch the video?

https://streamable.com/pv2pa

**Comment by steel4me** [comment]
Btw. i can make a video with micro laggs/freezes too if you like. Before Update i played long time without any problems.

**Comment by xAkiraMiura** [comment]
that looks like the view punch is double what it should be. it appears to be over correcting.

**Comment by littlehurensohn** [comment]
ill sometimes get random crash idk why

**Comment by steel4me** [comment]
> that looks like the view punch is double what it should be. it appears to be over correcting.

true, found the problem i think. didn't realized that getaimpunch was nativly added, so i did getaimpunch + weaponrecoilscale.  scary, but no untrust or ban till know.

**Comment by steel4me** [comment]
btw micro laggs / freezes are still there
