### ISSUE TITLE
GameEvent missing getFloat and getBool

### ISSUE THREAD

**Issue by 3Ld4D** [danielkrupinski/Osiris#1173]
This cheat is missing event->getFloat() and event->getBool().
i tried to do it but it didn't work out.

**Comment by effex1337** [comment]
constexpr auto getBool(const char* keyName) noexcept
    {
        return callVirtualMethod<bool, const char*, bool>(this, 5, keyName, 0);
    }

    constexpr auto getInt(const char* keyName) noexcept
    {
        return callVirtualMethod<int, const char*, int>(this, 6, keyName, 0);
    }
	
    constexpr auto getFloat(const char* keyName) noexcept
    {
        return callVirtualMethod<float, const char*, float>(this, 8, keyName, 0);
    }

**Comment by 3Ld4D** [comment]
thanks.
