### ISSUE TITLE
expected either a definition or tag name

### ISSUE THREAD

**Issue by aljawary** [danielkrupinski/Osiris#1177]
as u can see i got error like this. so how to fix ?
https://prnt.sc/r9tled

**Comment by 3Ld4D** [comment]
did you set the latest version of windows sdk?

**Comment by xAkiraMiura** [comment]
im assuming you modified the source. if this is correct then is the wrong place to ask. char8_t is a general c++ thing, not related to game hacking.

for a fresh copy: `git clone https://github.com/danielkrupinski/Osiris.git`

**Comment by danielkrupinski** [comment]
#1158
