### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by JohnRich1372** [danielkrupinski/Osiris#118]
Can you make the aimbot wallbang please?

**Comment by Havoccboi** [comment]
turn Visible Only to off and it will

**Comment by JohnRich1372** [comment]
Yeah but if you turn on autoshoot it just shoots through walls

**Comment by effexcs** [comment]
That is a rage feature you're asking for
It's called autowall damage and hitchance
It's better off not being here for now

**Comment by JohnRich1372** [comment]
Hm, okay. I won't use autoshoot then since it just shoots through walls.
