### ISSUE TITLE
[Suggestion] Skin search?

### ISSUE THREAD

**Issue by gucciMatix** [danielkrupinski/Osiris#1180]
hello friends, maybe add skin search or skin filtering in skinchanger?

**Comment by AbdallahMehiz** [comment]
maybe an option to filter skins by weapon like skeet has will be good but its kinda hard to do :"(

**Comment by xAkiraMiura** [comment]
i think daniel has said he does not want to do this.

**Comment by gucciMatix** [comment]
its not hard to but, requires a lot of time

**Comment by DoctorYasin** [comment]
:/

**Comment by Cyk-Fad** [comment]
I think it's easy

**Comment by Cyk-Fad** [comment]
Becaues my osiris has one skinsearch

**Comment by gucciMatix** [comment]
skin search it's easy, but skin filtering a little bit harder

**Comment by danielkrupinski** [comment]
Now you can search skins for certain weapon.
