### ISSUE TITLE
Can you add compiled dll ?

### ISSUE THREAD

**Issue by ttsmiyc** [danielkrupinski/Osiris#1182]
Is it possible to have compiled osiris.dll ?

**Comment by AbdallahMehiz** [comment]
read the instructions on the code's README pleaseee
![image](https://user-images.githubusercontent.com/59295266/75632672-c13c5980-5bfe-11ea-9a03-bccc1fc38d8c.png)

**Comment by ttsmiyc** [comment]
i can't download visual studio , i have internet with limited GB and actually can't that's why i asked , i know how to compile but can't
