### ISSUE TITLE
[Suggestion] Sound/footstep ESP

### ISSUE THREAD

**Issue by Exonip** [danielkrupinski/Osiris#1183]
Displays players only when they are hearable.

**Comment by gucciMatix** [comment]
bump

**Comment by xAkiraMiura** [comment]
> 
> 
> bump

anyone who has notifications enabled (beta, i think) for the repo gets a notification whenever anyone  reacts with an emote. posting "bump" has no more of an impact than just doing a thumbs up.

**Comment by gucciMatix** [comment]
oh ok, sorry i didnt know how it works here.
