### ISSUE TITLE
i can't download visual studio , i have internet with limited GB and actually can't that's why i asked , i know how to compile but can't

### ISSUE THREAD

**Issue by ttsmiyc** [danielkrupinski/Osiris#1184]
i can't download visual studio , i have internet with limited GB and actually can't that's why i asked , i know how to compile but can't

_Originally posted by @ttsmiyc in https://github.com/danielkrupinski/Osiris/issues/1182#issuecomment-593146915_

**Comment by Radient-Sfere** [comment]
just get vis stopdi

**Comment by streamshark** [comment]
you will probably have to find someone to add on discord or something to give it to you, I wouldn't suggest anyone post binaries here because there's malicious potential there

**Comment by Exonip** [comment]
Add me on Discord: Exonip#3641. I can compile it while we screen share.

**Comment by ttsmiyc** [comment]
Sent request Exonip

**Comment by littlehurensohn** [comment]
@Exonip Wow, guy what want to help someone, cool! :hand:

**Comment by xAkiraMiura** [comment]
i know gitlab supports but is it possible to add pipelines to the repo so github automatically builds the project whenever it updates? we wouldn't have to recompile it ourselves and threads like this would cease.
