### ISSUE TITLE
Osiris is b1g cheats now!!

### ISSUE THREAD

**Issue by xpossed-you** [danielkrupinski/Osiris#1186]
big bruh moment

**Comment by barbadully** [comment]
why would he do that if it's a free project, he doesn't earn any money off of it, and wasting money on a domain is just fucking retarded. Please use your brain next time

**Comment by Evilhelder** [comment]
> 
> 
> Osiris is bigger than it seems, are you gonna add domain name in osiris (idk what its called)
> example : (skeet.**cc** | onetap.**com** | aimware.**net**)

Are you blind?

![image](https://user-images.githubusercontent.com/33970481/75733752-d5eb2100-5cd4-11ea-9e42-009d0a900df7.png)

**Comment by H3artdown** [comment]
rofl B1g ISSUE

**Comment by hyperxpro** [comment]
As mentioned above, Osiris is free so spending money doesn't make sense. But hey, contributions are welcome. Go ahead and donate domain and server hosting for us and we'll appreciate it.
