### ISSUE TITLE
Stream proof??

### ISSUE THREAD

**Issue by SAmme064** [danielkrupinski/Osiris#1189]
is it possible to make the chams and esp and everything else who shows up on the screen stream proof?

**Comment by AbdallahMehiz** [comment]
try [Daniel's obs proof Cheat "GOESP"](https://github.com/danielkrupinski/GOESP)

**Comment by xAkiraMiura** [comment]
chams are inherently impossible to make stream proof, they rely on the game's DrawModelExecute function. (you could recreate it with dx9 but with severe performance implications.)

**Comment by xpossed-you** [comment]
i will not use cheat in my stream, or else i will get clara-fied.

**Comment by danielkrupinski** [comment]
Stream Proof ESP has been added.
