### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by kasem123** [danielkrupinski/Osiris#119]
I've tried this for about an hour by now, really impressive.
One suggestions that i have would be Autoshoot Damage calculation:
I've seen a few cheats have this. Basically when autoshoot "visible only" is disabled, make sure that you're at least causing damage to the target and not just attempting to shoot through all walls

and the only issue i've had so far is that triggerbot seems to be broken in arms race mode, but it was working in aim training map

**Comment by danielkrupinski** [comment]
Added wall penetration system.
