### ISSUE TITLE
antikick

### ISSUE THREAD

**Issue by ADGAYMILK** [danielkrupinski/Osiris#1192]
Does we can make a antikick like
someone votes you , and we call a vote to disable this?

**Comment by EurobeatClub** [comment]
That method was patched ages ago.

**Comment by ADGAYMILK** [comment]
oh no
but we can trigger it manually

**Comment by xAkiraMiura** [comment]
you can't trigger it manually.
the old method was that a server wide vote could override a team vote. this has been patched.
^ same reason you cant anti-vote in competitive. (no server wide votes)
