### ISSUE TITLE
Inverted Aim

### ISSUE THREAD

**Issue by vsnrytune** [danielkrupinski/Osiris#1193]
Would love to use this cheat, but I'm one of those rare people who use inverted mouse in CS:GO and the aim in this cheat fucks up when that setting is on. How to fix?

**Comment by xAkiraMiura** [comment]
keep the issue open, most of us are busy and can't immediately respond.

something you could probably try is finding all references to the mouse delta and inverting them (multiply by -1)

**Comment by vsnrytune** [comment]
> keep the issue open, most of us are busy and can't immediately respond.
> ^ unless you solved it, if you did please comment what you did to help people in the future.
> 
> something you could probably try is finding all references to the mouse delta and inverting them (multiply by -1)

Sorry, this was meant to be posted on another github, somehow I ended up here when osiris already works with inverted mouse. Thank you though, your advice might work on the other cheat
