### ISSUE TITLE
The Cheat is not working after csgo update

### ISSUE THREAD

**Issue by Exonip** [danielkrupinski/Osiris#1194]
Many features like triggerbot crash

**Comment by xAkiraMiura** [comment]
recompile.
if that doesn't work try re-downloading the source.

**Comment by xBaTm4n** [comment]
Same for me, esp and chams. crash

**Comment by You02** [comment]
GetInaccuracy - 482
GetSpread - 452
AccuracyPenalty - 483
IsPlayer - 158
GetCSWpnData - 460
IsWeapon - 166

Update these values,
 https://www.unknowncheats.me/forum/counterstrike-global-offensive/103220-counterstrike-global-offensive-reversal-structs-offsets-640.html

**Comment by JHompesc-dev** [comment]
isPlayer() is still at index 157 tho

**Comment by ClaudiuHKS** [comment]
Can you see the list of stickers from the skin changer?

**Comment by JHompesc-dev** [comment]
Well if you insist [heres your pasta](https://pastebin.com/zbCXmvG5)

**Comment by H3artdown** [comment]
i fixed them and the only thing not working is chams

**Comment by xAkiraMiura** [comment]
> 
> 
> i fixed them and the only thing not working is chams
> ——
> nvm i type wrong number xD fixed now

and this is why we make pulls rather than having to do everything by hand.

**Comment by H3artdown** [comment]
> > i fixed them and the only thing not working is chams
> > ——
> > nvm i type wrong number xD fixed now
> 
> and this is why we make pulls rather than having to do everything by hand.

true
