### ISSUE TITLE
How You Update Osiris I Wanna Know , Thank's :P .

### ISSUE THREAD

**Issue by novaxawp** [danielkrupinski/Osiris#1195]
### hello daniel 

_i wanna know how u update this cheat u can DM me in discord thank u so much for ur great cheat and 
i will be happy if u awnser me :D here or discord  ._

Discord : - 𝐂𝐢𝐥𝐥𝐢𝐚𝐧 𝐌𝐮𝐫𝐩𝐡𝐲 -#0753

**Much Love .**

**Comment by H3artdown** [comment]
wrong discord

**Comment by ClaudiuHKS** [comment]
> wrong discord

99% the name is fake

**Comment by KernCS** [comment]
> > wrong discord
> 
> 99% the name is fake
> 
> Anyways, are Skin Changer's stickers available for you ? Like can you choose them from that list ? My list seems empty.

https://i.imgur.com/JmYk9Cf.jpg Mine looks fine?

**Comment by H3artdown** [comment]
> > wrong discord
> 
> 99% the name is fake
> 
> Anyways, are Skin Changer's stickers available for you ? Like can you choose them from that list ? My list seems empty.

yes i can use it without problem , maybe you can change character and try it

**Comment by H3artdown** [comment]
> > > wrong discord
> > 
> > 
> > 99% the name is fake
> > Anyways, are Skin Changer's stickers available for you ? Like can you choose them from that list ? My list seems empty.
> 
> https://i.imgur.com/JmYk9Cf.jpg Mine looks fine?

this is your own cheat ? i found your discord and join in xD

**Comment by novaxawp** [comment]
my new discord [old sucks] : - Cilian Murphy -#0753

**Comment by novaxawp** [comment]
> > > wrong discord
> > 
> > 
> > 99% the name is fake
> > Anyways, are Skin Changer's stickers available for you ? Like can you choose them from that list ? My list seems empty.
> 
> https://i.imgur.com/JmYk9Cf.jpg Mine looks fine?

what is ur discord i have some questions :) ?

**Comment by KernCS** [comment]
> > > > wrong discord
> > > 
> > > 
> > > 99% the name is fake
> > > Anyways, are Skin Changer's stickers available for you ? Like can you choose them from that list ? My list seems empty.
> > 
> > 
> > https://i.imgur.com/JmYk9Cf.jpg Mine looks fine?
> 
> this is your own cheat ? i found your discord and join in xD

it's just a modified version of Osiris, do you like my discord? xD

**Comment by H3artdown** [comment]
> > > > > wrong discord
> > > > 
> > > > 
> > > > 99% the name is fake
> > > > Anyways, are Skin Changer's stickers available for you ? Like can you choose them from that list ? My list seems empty.
> > > 
> > > 
> > > https://i.imgur.com/JmYk9Cf.jpg Mine looks fine?
> > 
> > 
> > this is your own cheat ? i found your discord and join in xD
> 
> it's just a modified version of Osiris, do you like my discord? xD

no cuz the link for buy invite is a music video lmao

**Comment by KernCS** [comment]
> > > > wrong discord
> > > 
> > > 
> > > 99% the name is fake
> > > Anyways, are Skin Changer's stickers available for you ? Like can you choose them from that list ? My list seems empty.
> > 
> > 
> > https://i.imgur.com/JmYk9Cf.jpg Mine looks fine?
> 
> what is ur discord i have some questions :) ?

Kern#4080

**Comment by novaxawp** [comment]
> > > > > wrong discord
> > > > 
> > > > 
> > > > 99% the name is fake
> > > > Anyways, are Skin Changer's stickers available for you ? Like can you choose them from that list ? My list seems empty.
> > > 
> > > 
> > > https://i.imgur.com/JmYk9Cf.jpg Mine looks fine?
> > 
> > 
> > this is your own cheat ? i found your discord and join in xD
> 
> it's just a modified version of Osiris, do you like my discord? xD

i

**Comment by xAkiraMiura** [comment]
how is any of this on topic to Osiris?

**Comment by H3artdown** [comment]
> Kern#4080

added

> > > > > wrong discord
> > > > 
> > > > 
> > > > 99% the name is fake
> > > > Anyways, are Skin Changer's stickers available for you ? Like can you choose them from that list ? My list seems empty.
> > > 
> > > 
> > > https://i.imgur.com/JmYk9Cf.jpg Mine looks fine?
> > 
> > 
> > what is ur discord i have some questions :) ?
> 
> Kern#4080

added
