### ISSUE TITLE
[NOT ISSUE] Killshot, Between Shots Question?

### ISSUE THREAD

**Issue by vsnrytune** [danielkrupinski/Osiris#1198]
Killshot and between shots in aimbot tab, what do they do?

**Comment by ADGAYMILK** [comment]
Killshot is "When we can 1shot 1kill , then fire guns"

**Comment by ADGAYMILK** [comment]
Killshot is good with Zeus X27

**Comment by playday3008** [comment]
And between shots?

**Comment by AbdallahMehiz** [comment]
Between shots is "Aimbot will continue to lock on to other targets after kills"
useful with assault rifles and smgs and pistols

**Comment by effex1337** [comment]
Dont think thats how it works.
Theres a certain time needed for the gun to shoot its next bullet, hence betn shots means its gonna use the aimbot when the gun is waiting for its next bullet to get in the magazine
Imo useful for not so legit configs/very useful for semi rage configs.

**Comment by xAkiraMiura** [comment]
nor would it be for hvh because your head will be visible while you can't shoot

**Comment by DoomFishWasTaken** [comment]
Killshot = shoot any bone if lethal even if you have a different bone selected
Between shots = continue to aimbot even if you cannot shoot
