### ISSUE TITLE
are the indexes for entity.h fixed?

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1199]
extremely sorry, but, I don't know if I'm using the right words to describe my problem, I'm extremely new to coding and only know up to chapter 2.1 of learncpp.com. so yeah, that new. the aimbot wasn't working anymore, I was pretty sure it had something to do with fiding players, is the problem with the aimbot fixed?

**Comment by dapaster** [comment]
#1197

**Comment by DoctorYasin** [comment]
Go to Entity.h and change indexes of two functions:
getInaccuracy() : 482
getWeaponData() : 460
