### ISSUE TITLE
[not cheat related]

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1200]
Hello, I'm curious about where should I start in-game hacking? I'm interested in the subject so I have started learning a tiny bit of c++, I BARELY know anything like the bare hello world program minimum.
what should I learn? And when should I learn it? Thank you for your time!

**Comment by tirziz** [comment]
after learning C++ try basic Cheat engine , then maybe reserve engineer.

**Comment by HowToMakeFaceitAB** [comment]
> after learning C++ try basic Cheat engine , then maybe reserve engineer.

ok thank you sir.
