### ISSUE TITLE
Crashing game

### ISSUE THREAD

**Issue by DoubleG123** [danielkrupinski/Osiris#1201]
[ENG] when i open cheat (osiris) my csgo crash within 5 minutes (csgo files work good) no reason why csgo crash

[PL] kiedy odpalam cheat (osiris) po +/- 5 minutach gra mi crashuje tak bez powodu sprawdzalem spojnosci plikow i nic zadnego komunikatu dlaczego mi scrashowalo.. po prostu to wyglada jak bym sam sb wylaczyl csa a tak nie robie

**Comment by DoctorYasin** [comment]
Automatic game closes when aimbot kills 1 man while on.

**Comment by DoubleG123** [comment]
oh ok ill try to play without it

**Comment by DoctorYasin** [comment]
I think the problem is caused by memory or hook or entity.

**Comment by DoubleG123** [comment]
still crashing

**Comment by DoubleG123** [comment]
yesterday this cheat worked good with aimbot today it crash game wtf

**Comment by DoubleG123** [comment]
thats not problem with config lol cheat broke

**Comment by DoubleG123** [comment]
theres video how it looks
https://youtu.be/wtbi8uVgCBI

**Comment by xAkiraMiura** [comment]
are you on the most recent commit? you may need to recompile.
`git clone https://github.com/danielkrupinski/Osiris.git`

**Comment by DoubleG123** [comment]
now, when i download this i cant even join any map..

**Comment by DoubleG123** [comment]
but i can play on bots normally

**Comment by DoubleG123** [comment]
and still game crashes

**Comment by DoubleG123** [comment]
i reinstall csgo and still crashes

**Comment by mileshatz** [comment]
@DoubleG123 Game update. dude just wait danielkrupinski update...

**Comment by DoubleG123** [comment]
i joined on my other account, where i open this cheat first time and its working no problem wtf

**Comment by DoubleG123** [comment]
oh, still not working nvm

**Comment by mileshatz** [comment]
just close issue and wait new update danielkrupinski..
