### ISSUE TITLE
[Question] Is this undected ?

### ISSUE THREAD

**Issue by Nyazuma** [danielkrupinski/Osiris#1202]
Do I need any kind of VAC bypass before using it or this can be run undected ? 
If needed, please link me any VAC bypass.

Thank's

**Comment by dapaster** [comment]
https://github.com/danielkrupinski/VAC-Bypass-Loader

**Comment by xAkiraMiura** [comment]
the VAC bypass may cause VAC Auths

the cheat is not detected, I have had accounts for weeks at a time while running Osiris.

**Comment by mileshatz** [comment]
Close issue cheat undetected.. wait update

**Comment by JaySlappin** [comment]
Been using for a month+ and havent got banned on like 3 accounts, id say so
