### ISSUE TITLE
the game crashed after loading a map

### ISSUE THREAD

**Issue by smartxd3** [danielkrupinski/Osiris#1203]
the game crashed every time i load a map even if i diden't use any config..
please fix it

**Comment by xAkiraMiura** [comment]
have you updated to the most recent commit and recompiled?

**Comment by AlexanderQueen** [comment]
Or crashes on press TriggerBot!!!

**Comment by smartxd3** [comment]
i did update it byt still get crashed

**Comment by Nexo848** [comment]
Go to Entity.h and change indexes of two functions:
getInaccuracy() : 482
getWeaponData() : 460
