### ISSUE TITLE
Game crashes after i activate chams!

### ISSUE THREAD

**Issue by zico50050** [danielkrupinski/Osiris#1205]
i tweaked the aimbot numbers but still when i Apply my config with chams the game crashes

Any idea why? and when it's going to be fixed? ^_^

**Comment by mileshatz** [comment]
just wait danielkrupinski update..

**Comment by zico50050** [comment]
> just wait danielkrupinski update..

Okay thanks

**Comment by zico50050** [comment]
> Go to Entity.h and change indexes of two functions:
> getInaccuracy() : 482
> getWeaponData() : 460

I will try it thanks :D
