### ISSUE TITLE
Do not open Issues for crash or someting 

### ISSUE THREAD

**Issue by mileshatz** [danielkrupinski/Osiris#1206]
Just wait a update danielkrupinski

**Comment by DoubleG123** [comment]
uhh but my csgo crash without cheat no reason

**Comment by JaySlappin** [comment]
> uhh but my csgo crash without cheat no reason

then thats your problem, nothing to do with Osiris. Try verifying your Game files on steam...

**Comment by DoctorYasin** [comment]
Go to Entity.h and change indexes of two functions:
getInaccuracy() : 482
getWeaponData() : 460
