### ISSUE TITLE
FIX AIMBOT IM SILVER 4 AND NEED AIMBOT  

### ISSUE THREAD

**Issue by VICTOR-HOOK** [danielkrupinski/Osiris#1208]
Hello pls someone fix the aimbot it doesnt work PLS FIX i need fast i need aimbot i cant shoot pls fix aimbot im silver 4 pls fix aimbot i cant aim healp. TY for fixing aimbot

**Comment by DoctorYasin** [comment]
Go to Entity.h and change indexes of two functions:
getInaccuracy() : 482
getWeaponData() : 460
