### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by JohnRich1372** [danielkrupinski/Osiris#121]
How do I change a menuitem's text font?

**Comment by Tetrisz** [comment]
Just look in the source

**Comment by JohnRich1372** [comment]
Does PushFont(); work?

**Comment by danielkrupinski** [comment]
Use below code to change menu font:
```cpp
ImGuiIO& io = ImGui::GetIO();
io.Fonts->AddFontFromFileTTF(/* arg1 - path to font */, /* arg2 - font size */);
```
To change font of menu element use PushFont() function.

**Comment by NexSqaud** [comment]
How to change font for Surface::printText ? or font size ?
