### ISSUE TITLE
still crashes

### ISSUE THREAD

**Issue by DoubleG123** [danielkrupinski/Osiris#1211]
my game still crashes after update!
when i load map my csgo crash
i updated cheat and still not working

**Comment by DoubleG123** [comment]
i reinstalled csgo and still 
crashing

**Comment by ZerGo0** [comment]
Reinstalling the game literally doesn't do anything. Download a fresh version of Osiris and it will work, you must#ve messed something up.

**Comment by DoubleG123** [comment]
i launch csgo without cheat and it dont even want load map

**Comment by DoubleG123** [comment]
changed some settings to low and it can load but crashes after 2 minutes

**Comment by ZerGo0** [comment]
Well then it's not an issue from the cheat, I'm not going to explain to you how to fix you shit. Google is powerful and easy to use.

**Comment by DoubleG123** [comment]
i used  google methods, but its 1-4 years old videos and it doesnt work

**Comment by DoubleG123** [comment]
and this issue happend when i downloaded osiris so thats osiris issue cuz without it my csgo worked great

**Comment by xAkiraMiura** [comment]
# Osiris did not break your game.

your injector may have been malicious, which injector did you use?

**Comment by DoubleG123** [comment]
cmrinjector

**Comment by craxking** [comment]
also avoid using old configs

**Comment by DoubleG123** [comment]
yeah ik 
but what injector i should use uh...?

**Comment by xpossed-you** [comment]
you should use process hacker 2 instead
because Valve will not detect a task manager right?

**Comment by AMATEURZ1337** [comment]
you're propably using shit methods with depots that will "fix" onetap Crack

**Comment by xAkiraMiura** [comment]
> 
> 
> you're propably using shit methods with depots that will "fix" onetap Crack

how is that relevent? are you trying to start a flame ware?

**Comment by rosesware** [comment]
Game still crashing, yes, 10 minutes and game get down with simple game events like, start another round, buy something, things like that.

**Comment by effex1337** [comment]
That would be relevant only if he said i crash after i inject.
"i launch csgo without cheat and it dont even want load map"

**Comment by DoubleG123** [comment]
i did low graphic sethings and game load but crashes after round or something like rosesware said

**Comment by DoubleG123** [comment]
sorry for not responding i wasnt at home

**Comment by DoubleG123** [comment]
idk i close this issue cuz nobody know how to fix it.. lol
