### ISSUE TITLE
Random crashes only on dust2 comp

### ISSUE THREAD

**Issue by unniggable** [danielkrupinski/Osiris#1213]
Tried debugging but it only shows me "Exception thrown at 0x6CE536B4 (cheat.dll) in csgo.exe: 0xC0000005: Access violation reading location 0x000000F4." this only happens when ive injected and in a comp game on dust2

**Comment by xAkiraMiura** [comment]
0xC0000005 means bad pointer
0x000000F4 looks like an offset added to nullptr

attach a debugger and tell us at what line it crashes.

**Comment by ClaudiuHKS** [comment]
Like @xAkiraMiura said, you need to debug it, so compile it in Debug x86 mode and put the following files in the same folder with csgo.exe and inject from that location as well:

Debug\Osiris.dll
Debug\Osiris.ilk (if exists)
Debug\Osiris.pdb
Debug\vc142.idb (if exists)
Debug\vc142.pdb (if exists)

It should show you the line like in the picture.
![debug](https://user-images.githubusercontent.com/9334579/76002991-17b3db80-5f10-11ea-917a-9788b3c55dad.png)

**Comment by unniggable** [comment]
ok i have tried with the debug .dll and i cant even open the menu without it throwing me loads of imgui errors in imgui.cpp and i havent even touched that file.

**Comment by unniggable** [comment]
IM_ASSERT(g.CurrentWindowStack.Size > 1 && "Calling End() too many times!"); in imgui.cpp line 5805

**Comment by danielkrupinski** [comment]
0x000000F4 indicates you're trying to read team netvar of a nullptr entity. This error is not possible in the unmodified version of the source code as we're using team netvar only in one place which has null pointer check. Call stack in debugger window will reveal you were you forgot to check entity pointer.
