### ISSUE TITLE
[Suggestion] Stream-Proof

### ISSUE THREAD

**Issue by AndreasYNY** [danielkrupinski/Osiris#1214]
Since Osiris using GOESP's base, can it be stream-proofed just like GOESP? 
will this making osiris more detectable tho??? 🤔

**Comment by xAkiraMiura** [comment]
i don't think osiris uses goesp as a base.

Osiris.cpp does not use a DllMain function and relys on object constructors to do stuff.
GOESP uses DllMain. this is the reason you are able to reinject after an uninject. DllMain is required to fully unload.

**Comment by NexSqaud** [comment]
GOESP use DirectX present and reset and game window wndproc to draw. Osiris use in-game functions to draw ESP.

**Comment by danielkrupinski** [comment]
Stream Proof ESP has been added.
