### ISSUE TITLE
Aimbot not Working

### ISSUE THREAD

**Issue by kschou95** [danielkrupinski/Osiris#1215]

**Comment by HowToMakeFaceitAB** [comment]
update it
big brain

**Comment by kschou95** [comment]
nope, genius, i cleaned everything and pulled again, still not working

**Comment by xAkiraMiura** [comment]
describe the issue more. does it not fire at all (you need to enable auto shot) or just not snap on? if you have silent checked the it may be snapping but not firing.

if you do have auto shot i would recommend an on key. osiris doesn't have auto stop so you will be inaccurate if you're maxes aren't set up perfectly.

**Comment by rosesware** [comment]
> osiris doesn't have auto stop so you will be inaccurate if you're maxes aren't set up perfectly.

"Aim accuracy" and "Shot accuracy", also "Slowwalk" helps.
