### ISSUE TITLE
Aimbot Smoothing Broken

### ISSUE THREAD

**Issue by Slyember** [danielkrupinski/Osiris#1217]
When Aimbot Weapon smoothness isn't "1.0" or 1, the aimbot doesnt fire at a target or fires not near them at all!

NOTE: Both my max shot inaccuracy & max aim inaccuracy are "0.1", Both RCS options are at 0 also

**Comment by AbdallahMehiz** [comment]
the aim and shot inaccuracy should be 1-1...

**Comment by HowToMakeFaceitAB** [comment]
it's not broken, sorry but your brain is the one that's actually broken...

**Comment by HowToMakeFaceitAB** [comment]
my way of talking is too sinister, I'm afraid I'm watching too much anime .

**Comment by AbdallahMehiz** [comment]
> my way of talking is too sinister, I'm afraid I'm watching too much anime .

yea u r

**Comment by HowToMakeFaceitAB** [comment]
Or I just play too much half-life and have become a human vortigaunt
