### ISSUE TITLE
Menu and Visuals font

### ISSUE THREAD

**Issue by PatrixCheats** [danielkrupinski/Osiris#1221]
Is there a way i can change visuals/esp font

**Comment by xAkiraMiura** [comment]
yes, just click the font button. i think it shows up as a number rather than the font name however.
if you want something custom you have to implement it yourself, there is no custom font option as of now.

**Comment by PatrixCheats** [comment]
Ok thx

**Comment by PatrixCheats** [comment]
I tried to implement it but i just couldn't figure ot how also (menu related) when i go and change font in gui.cpp. The menu changes font but to some other font not the one i wanted

**Comment by PatrixCheats** [comment]
Please can someone help me

**Comment by rosesware** [comment]
[GOESP](https://github.com/danielkrupinski/GOESP) have it, **I think** you just need to change to Osiris SDK.

**Comment by xAkiraMiura** [comment]
as the ESP uses VGui and VGui fonts are based on the installed WIndows fonts, if you install the font to windows it might show up in the font selection.

**Comment by techprimedev** [comment]
theres away to change the menu of Osiris? use another menu?
