### ISSUE TITLE
Backtrack records broken sometimes

### ISSUE THREAD

**Issue by ZerGo0** [danielkrupinski/Osiris#1222]
I have noticed that I haven't been able to backtrack enemies like I used to so I decided to look into it a bit. After testing I found out that it seems to store the origins wrong sometimes.

Preview of the issue (ignore the first shot, the breakpoint go hit):
![preview](https://i.imgur.com/OROAPp0.gif)

I was clearly on it and I had norecoil and nospread on, it should've definitely hit the enemy, but it didn't. You can also see that there are a few records that are in front of the bot. If they are in the front I can't backtrack the bot. When there is no record in front of the bot which only happens sometimes then I can hit the backtrack tick that I'm aiming at.

I have no idea how this even happens to be honest, looking at the code it literally saves the origin and simtime of the player to a deque and that's it.

Mind looking at it? @danielkrupinski

**Comment by xAkiraMiura** [comment]
i've also noticed that i can't hit moving targets. i attributed this to being 150 ping on a EU Spain server but it could be due to this.
i know the map you are on has an issue with animations but i don't think it would cause 3 records to show ahead.

**Comment by ZerGo0** [comment]
> i've also noticed that i can't hit moving targets. i attributed this to being 150 ping on a EU Spain server but it could be due to this.
> i know the map you are on has an issue with animations but i don't think it would cause 3 records to show ahead.

Appreciate the input, pretty sure that the map doesn't matter, the same issue on another map. However, looking at the values in a debugger shows that everything is actually fine. Might be just a visual thing, but 
![Preview2](https://i.imgur.com/44nRcdN.png)

Here is another gif showing the actual issue:
![Preview3](https://i.imgur.com/G19r2Tl.gif)

**Comment by effex1337** [comment]
1. The bt sucks 
2. The size shouldn't be 13
The first record is incorrect(looks like forward tracking)

**Comment by ZerGo0** [comment]
> 1. The bt sucks
> 2. The size shouldn't be 13
>    The first record is incorrect(looks like forward tracking)

Yup surely helps solving the issue. 

It is 13 ticks because 200÷(1000÷64) = 12,8 which gets rounded up.

**Comment by effex1337** [comment]
Then if size=13 invalidate 1st record?

**Comment by ZerGo0** [comment]
I did some more testing and I found out that the DME drawing stuff seems to be a bit behind `stage == FrameStage::RENDER_START` which is the update condition for the backtrack records:
![Pre](https://i.imgur.com/wn51r8c.png)

Changing it to `stage == FrameStage::NET_UPDATE_POSTDATAUPDATE_START` or `stage == FrameStage::NET_UPDATE_START` fixes the displaying issue, but results in even worse results when it comes to hitting the actual backtrack ticks.

**Comment by xAkiraMiura** [comment]
maybe use CreateMove with NetVars instead of FrameStageNotify?
all other backtrack implementations ive seen have used CreateMove.

**Comment by ZerGo0** [comment]
> maybe use CreateMove with NetVars instead of FrameStageNotify?
> all other backtrack implementations ive seen have used CreateMove.

Tested that, doesn't really change anything sadly.
