### ISSUE TITLE
sorry for bad english. recomend any dll injectors?

### ISSUE THREAD

**Issue by Jaglii** [danielkrupinski/Osiris#1223]
i am in need of a undetected dll injector for this cheat

**Comment by xAkiraMiura** [comment]
try [inflame](https://github.com/danielkrupinski/inflame) by daniel as well.

**Comment by craxking** [comment]
Daniel's inflame is the best free injector

**Comment by playday3008** [comment]
Try Xenos on Github

**Comment by xAkiraMiura** [comment]
Xenos has been out for many years and in my testing is VAC detected.

**Comment by playday3008** [comment]
IDK, I don't have VAC, and Xenos updated 7 months ago

**Comment by Aidan7831** [comment]
i dont understand the compile tutorial on Inflame. i get to number 5 but there is no inflame.sln only mla oir whatever

**Comment by TauCSGO** [comment]
> i am in need of a undetected dll injector for this cheat

https://github.com/danielkrupinski/curiuminjector-csgo
Undetected
Change [asm], change dll name, compile, and done

**Comment by xAkiraMiura** [comment]
> 
> 
> > i am in need of a undetected dll injector for this cheat
> 
> https://github.com/danielkrupinski/curiuminjector-csgo
> Undetected
> Change [asm], change dll name, compile, and done

injectors that load hard coded names are general bad, im pretty sure inflame supports any dll name.



> 
> 
> i dont understand the compile tutorial on Inflame. i get to number 5 but there is no inflame.sln only mla oir whatever

only follow steps 1 to 4, manual map injectors may lead to vac auths.
if you did 1 to 4 correctly an EXE should have been made.

**Comment by jimbob88** [comment]
Personally I have been using Sazinjector and it has worked perfectly, as it is still updated repeatedly, you need an account to download it but it is really good and has a simple interface. 
There is a [forum post](https://infocheats.net/threads/sazinjector-v2-6-free-07-03-2020.248/) with the download link; however, as you need to register and some people don't really want to do that. The link for version 2.6 is [here](https://mega.nz/#!xthChS6Q!P3AtUbGcY31Tn9cy2EZhvdqKkK4B8l-H3_KCaLQtAwc), and the password is `SazZ` (I used 7z to unzip it as I couldn't work out how to do it with file explorer.

The only issue I have encountered with it is that windows defender detects it as trying to use a UAC bypass so I had to press the allow button on it..
Hope this helps,
Jim.

**Comment by xAkiraMiura** [comment]
ideally if you make your own injector you can double click on the dll and automatically inject it, much faster than using a gui.
^ my custom injector does this (but i prefer drag and drop to not inject system DLLs into the gane)

**Comment by BitesizedLion** [comment]
> 
> 
> try [inflame](https://github.com/danielkrupinski/inflame) by daniel as well.

Hi, I tried using Inflame with Osiris and for some odd reason it does nothing when injected? Tried loadlibrary and manual-map.

**Comment by jimbob88** [comment]
Although I currently use Saz, anyone know if there is an injector that can work on Faceit AC, because things like aimware ultra do...
