### ISSUE TITLE
Glow applied on hands

### ISSUE THREAD

**Issue by darkisgod444** [danielkrupinski/Osiris#1225]
Can i somehow apply glow in osiris like this:
![PicsArt_03-07-02 00 27](https://user-images.githubusercontent.com/61908493/76143988-1c959e00-607c-11ea-9c44-a5d5b5538cba.png)

**Comment by danielkrupinski** [comment]
I think it's a special chams material.

**Comment by darkisgod444** [comment]
Oh ok so you cant apply glow on hands like you do on enemy models??
![Capture 2020-02-10 12 18 37](https://user-images.githubusercontent.com/61908493/76144235-80b96180-607e-11ea-9991-20efa3f7a6e4.jpg)

**Comment by darkisgod444** [comment]
Ok so you cant apply glow on hands like you do on enemies??
![PicsArt_03-07-02 22 09](https://user-images.githubusercontent.com/61908493/76144293-0b9a5c00-607f-11ea-801c-a696fb81b658.jpg)
??

**Comment by darkisgod444** [comment]
It doesn't seem like chams material to me because the blue glow on his hands changes if you look at them from different angle don't know chams can do that. Feel free to correct me

**Comment by effex1337** [comment]
Yeah they totally don't say it's a material in aimware.

**Comment by effex1337** [comment]
The material is dev/glow_armsrace btw.
Now do your research and find a way to modulate it.
@danielkrupinski Will it be accepted if i make a pr for this?

**Comment by darkisgod444** [comment]
Thx should i close issue now??

**Comment by rosesware** [comment]
> Thx should i close issue now??

Don't, wait for more answers.

**Comment by darkisgod444** [comment]
I tried to do this and i ended up with this:
![PicsArt_03-07-05 30 42](https://user-images.githubusercontent.com/61908493/76147135-68a30b80-6099-11ea-954e-60ab8ba39a9f.png)
How can i make it show real hands under the glowing texture ?

**Comment by darkisgod444** [comment]
Someone please help me

**Comment by effex1337** [comment]
> Someone please help me

Wait for my pr!

**Comment by darkisgod444** [comment]
Ok i hope it comes soon :D

**Comment by nullang** [comment]
#1260

**Comment by effex1337** [comment]
https://github.com/danielkrupinski/Osiris/pull/1262
There you go!

**Comment by darkisgod444** [comment]
Thx mate
