### ISSUE TITLE
Fake Vote

### ISSUE THREAD

**Issue by tamas0313** [danielkrupinski/Osiris#1227]
Fake vote is not working gray panel is not pop up!

**Comment by danielkrupinski** [comment]
You have to call vote yourself.

**Comment by tamas0313** [comment]
yes i know, but after the update i think not working

**Comment by xAkiraMiura** [comment]
name appears invisible and shows the original vote.
happened to me a few days ago after the 3/2/20 update.

**Comment by tamas0313** [comment]
yes same problem, somebody know what is wrong?

**Comment by danielkrupinski** [comment]
Looks like it was patched.

**Comment by thvozdovic** [comment]
Remove it from the cheat then ?

**Comment by xAkiraMiura** [comment]
he did, check the commits.
