### ISSUE TITLE
How to use anti aim.

### ISSUE THREAD

**Issue by smurfsmfc** [danielkrupinski/Osiris#1228]
Please reply @danielkrupinski 
How to use anti aim

**Comment by xAkiraMiura** [comment]
You won't be able to see it on your end. Either use `bot_mimic 1` or get a friend to verify your settings.
In Misc enable `fix movement` if you have a problem with wierd movement.
*currently at anti aim only does a few hammer units of desync, hard to notice.* 

Please don't ping people in specific unless you're replying to them. Most of us have notifications enabled for the repo and will respond when we get the time to.
