### ISSUE TITLE
ReportBot

### ISSUE THREAD

**Issue by AlexanderQueen** [danielkrupinski/Osiris#1229]
Is it possible to make to select unit(player) who will be reported not whole team?

**Comment by xAkiraMiura** [comment]
just report them normally. the bot only sends 1 report to each player.

**Comment by AlexanderQueen** [comment]
> just report them normally. the bot only sends 1 report to each player.

So that's the idea. To select 1 unit not whole team. I want to report him 50x times,i'm tired to do that manually.

**Comment by xAkiraMiura** [comment]
more than 1 report do nothing.

**Comment by AlexanderQueen** [comment]
I don't agree with you. Yesterday gave 1 started then with auto-report and he got untrusted? Coincidence? I think not.

**Comment by xAkiraMiura** [comment]
alright so im going to blatantly spinbot in **1** competitive, lets say everyone reported me, that would make 9 reports.
then i have my friend continuously report me, thats over 11.
the estimated amount of reports required to get into overwatch is 11
if i don't get into to overwatch then multiple reports do nothing.
if i do get overwatched then either the auto-leveling service i used got a report on it or VACnet automatically put me into overwatch.

**Comment by anonymouschicken1111** [comment]
> I don't agree with you. Yesterday gave 1 started then with auto-report and he got untrusted? Coincidence? I think not.

Just think about it
Counting multiple reports by a single player would be op and dumb on valve's end
Valve's vacnet would be overwhelmed

**Comment by xAkiraMiura** [comment]
vacnet doesn't review reports. vacnet reviews gameplay and sends it to overwatch if it it suspecious.
