### ISSUE TITLE
sound Esp Needed 

### ISSUE THREAD

**Issue by madhatterxk** [danielkrupinski/Osiris#1231]
im sorry idk where to put this but can you add sound Esp for example if someone is walking i can detect where the enemy is in a legit way if he makes any sound it will be also very good for def people and legit people

**Comment by xAkiraMiura** [comment]
duplicate: #337 #766 #1183
better title: `[Request] Sound ESP`
also lots of grammar mistakes.

how you can do this (we probably don't want to):
either hook the sound function or use the sound event. grab the origin of it, world to screen the coordinates, then draw it with ISurface.

**Comment by CerberusGame** [comment]
+1

**Comment by xAkiraMiura** [comment]
there is a way to turn footstep sounds up to 200%.
considering we have 4+ issues on sound ESP, oldest i know from july 2019, i don't think anybody wants to work on it.

**maybe you could do it?**
