### ISSUE TITLE
Crash when loading config

### ISSUE THREAD

**Issue by num3rical** [danielkrupinski/Osiris#1232]
Seemingly out of the blue, my game has begun crashing anytime I try to load a config. I attached a debugger and got this:
`Exception thrown at 0x373C2BD3 (Osiris.dll) in csgo.exe: 0xC0000005: Access violation reading location 0x00000000.`

**Comment by xAkiraMiura** [comment]
error      0xC0000005 = reading bad memory
memory 0x00000000 = nullptr 

what line of which file did the debugger stop on? you need to check for nullptr before there.

**Comment by num3rical** [comment]
Nevermind, turns out I accidentally broke something. I redownloaded and recompiled and it worked.
