### ISSUE TITLE
How to make "further-optimizations"?

### ISSUE THREAD

**Issue by JustKraskata** [danielkrupinski/Osiris#1233]
https://github.com/danielkrupinski/Osiris#further-optimizations I compiled w/o any problems but how to make that step and how can it help me?

**Comment by xAkiraMiura** [comment]
(menu bar) > Project > Properties > Configuration Properties > Linker > Code Generation > Enable Enchanced Instruction Set > Advanced Vector Extensions 2

screen shot: https://i.imgur.com/wfMoiLp.png

**Comment by danielkrupinski** [comment]
It enables compiler to generate more performant code when dealing with floating-point numbers and matrices (mainly ESP code is affected).
