### ISSUE TITLE
Multiple keys to aim

### ISSUE THREAD

**Issue by Asviix** [danielkrupinski/Osiris#1234]
Any idea on how to do that ?

**Comment by xAkiraMiura** [comment]
what do you mean? multiply `*` key to aim or multiple keys `a OR b` to enable aim?

**Comment by Asviix** [comment]
a OR b
Already tried some things in the Aimbot.cpp by trying mouse1 and mouse5 but didn't quite work out

**Comment by Asviix** [comment]
Edit: I just noticed I had typo in the title

**Comment by Asviix** [comment]
Closed, got it working for what I wanted to do
Might add a GUI option and add it as a pull request
