### ISSUE TITLE
please add bypass sv_pure

### ISSUE THREAD

**Issue by alessio-png** [danielkrupinski/Osiris#1235]
it would be great if bypass sv_pure was in this cheat

**Comment by xBaTm4n** [comment]
+1

**Comment by dapaster** [comment]
what does it do?

**Comment by tirziz** [comment]
> what does it do?

Remove files integrity so you can use custom models, custom sounds

**Comment by yEsPaP** [comment]
```
void Visuals::svpureshit() noexcept {

    const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
    if (!localPlayer)
        return;
    interfaces.cvar->findVar("sv_pure")->setValue(config.visuals.fullBright ? 0 : 1);
};
```

Pasted code here u go uWu

**Comment by CantRememberMyself** [comment]
> ```
> void Visuals::svpureshit() noexcept {
> 
>     const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
>     if (!localPlayer)
>         return;
>     interfaces.cvar->findVar("sv_pure")->setValue(config.visuals.fullBright ? 0 : 1);
> };
> ```
> 
> Pasted code here u go uWu

that wouldnt work lmao, you need to hook SendMessageNetwork, refer to this post https://www.unknowncheats.me/forum/counterstrike-global-offensive/279394-dumb-sv_pure-bypass.html

**Comment by xAkiraMiura** [comment]
you cant just force a convar when file integrity is checked

**Comment by rosesware** [comment]
> `interfaces.cvar->findVar("sv_pure")->setValue(config.visuals.fullBright ? 0 : 1);`

?

**Comment by yEsPaP** [comment]
> you cant just force a convar when file integrity is checked

ok whatever im a noob i dont even know c++ that well.

**Comment by xAkiraMiura** [comment]
file integrity isn't even a c++ thing?
