### ISSUE TITLE
deteceted

### ISSUE THREAD

**Issue by datwayx420** [danielkrupinski/Osiris#1238]
was qued with homie and he got vaced mid gamefirst game using it / anything in genral

**Comment by streamshark** [comment]
if anything he uses gets him banned, probably using a detected injector

**Comment by tirziz** [comment]
What features did your friend use?

**Comment by datwayx420** [comment]
not sure but he wasnt raging on a brand new acount got banned in causle

**Comment by AbdallahMehiz** [comment]
his injector is detected.

**Comment by datwayx420** [comment]
no its not cuz i use the same one cheatz app

**Comment by AbdallahMehiz** [comment]
just use daniel's vac bypass loader to avoid vac bans

**Comment by xAkiraMiura** [comment]
> 
> no its not cuz i use the same one cheatz app

ruh roh thats not how it works at all.

VAC intentionally has delayed bans and occasionally just won't check your system unless you get reported. learn about the detection vector VAC uses.

**Comment by xBaTm4n** [comment]
i played over 50 matches. legit. no ban yet. from s2 to mg2

**Comment by steel4me** [comment]
just for info. i use my own manual map injector with erase pe header and highly modificated osiris over 12 months on 10 diffrent accounts now. 

2 confirmed VAC bans till now. Never used VAC-bypass. Signature based ban is not possible cause modification. Loader based ban is not possible cause it is my own and every account would be "banned".

Mostly i play legit and use the same standard settings like...: aimer, esp, chams, glow.
Sometimes i activate backtrack and choked packets. Max angle delta is 30.

Till now i can't explain what happened ;)
