### ISSUE TITLE
Glow RGB/ RBG bug?

### ISSUE THREAD

**Issue by ClaudiuHKS** [danielkrupinski/Osiris#1240]
https://github.com/danielkrupinski/Osiris/blob/139d410366a8e96652ac46384b8b309faeb6f544/Osiris/Hacks/Glow.cpp#L67

Should this be RGB instead?

**Comment by NexSqaud** [comment]
if you didn't see any problems at glow color dont touch this

**Comment by ClaudiuHKS** [comment]
Well, of course you can't see any _big_ problems because it's **Rainbow**. So it has all the colors. I still think it should be ``{ r, g, b }`` instead.

``                else if (glow.color.rainbow) {``
``                    const auto [r, g, b] { rainbowColor(memory.globalVars->realtime, glow.color.rainbowSpeed) };``
``                    glowobject.glowColor = { r, b, g };``
``                }``

**Comment by KuteKetX** [comment]
this mainly depends on how that variable is being used.

**Comment by xAkiraMiura** [comment]
i haven't seen how rainbow works but if it is an HSV -> RGB function then it might need to be RBG.

**Comment by ClaudiuHKS** [comment]
Everything in **Osiris** is RGB but this, I have deeply checked. You can't find one more RBG thing.
**Glow.cpp** file is the only one that has this RBG thing so I think it's just a spelling mistake of the author.

**Comment by danielkrupinski** [comment]
Fixed
