### ISSUE TITLE
Skeleton ESP

### ISSUE THREAD

**Issue by PUREHAX** [danielkrupinski/Osiris#1242]
Would like to have a skeleton Esp :)

**Comment by xAkiraMiura** [comment]
congradulations, we do.

**Comment by PUREHAX** [comment]
sounds good :)

**Comment by Trigmam** [comment]
> congratulations, we do.

can you tell me where skeleton Esp is located under?

**Comment by PUREHAX** [comment]
So, whats with the skeleton esp ? can someone tell me how to implement it ?

**Comment by xAkiraMiura** [comment]
> So, whats with the skeleton esp ? can someone tell me how to implement it ?

read next time. i said it is already in the cheat.

> can you tell me where skeleton Esp is located under?

its under the ESP tab somewhere.
