### ISSUE TITLE
Crashing along and AimBot not working at all

### ISSUE THREAD

**Issue by Scifi9902** [danielkrupinski/Osiris#1244]
Basically Aim Bot does not work at all no matter the settings enabled or disabled, I've tried with lock and without lock and if you enable trigger bot and join a game you will crash or if your in a game and you go to enable trigger bot you will crash.

**Comment by xBaTm4n** [comment]
u have the latest update for entity?

**Comment by saaiz** [comment]
> u have the latest update for entity?

how to update? im new here;/

**Comment by xAkiraMiura** [comment]
download [git for windows](https://gitforwindows.org/) if you do not have it already
run `git clone https://danielkrupinski/Osiris.git`
a folder named Osiris will be created where ever you ran it.

**Comment by Scifi9902** [comment]
I'm using the latest version and these errors still occur.

**Comment by xAkiraMiura** [comment]
attach a debugger and tell us where it crashes.

**Comment by Scifi9902** [comment]
> attach a debugger and tell us where it crashes.

I dont really code c / c++ so how would I add a debug for a module

**Comment by xAkiraMiura** [comment]
congratulations. debugging isn't a c++ thing, its a VS2019 thing.
Menu bar > Debug > Attack debugger to process > select `csgo.exe`
when it crashes vs2019 will pop up and say where it crashed.
**you will need to inject a debug build**

**Comment by danielkrupinski** [comment]
It works fine, make sure you're using the latest version.
