### ISSUE TITLE
Auto Counter-Strafe [Enhancement]

### ISSUE THREAD

**Issue by Deagle2k** [danielkrupinski/Osiris#1245]
Add a function/option to turn on auto counter strafe. Where you press a at the same time as d and you stop fast. But Can you add something so it does it for you? THX!

**Comment by dctrlight** [comment]
so basically autostop?

**Comment by dapaster** [comment]
> 
> 
> so basically autostop?

https://www.youtube.com/watch?v=3QihqT1GkH8

**Comment by SunzBody** [comment]
#2039
