### ISSUE TITLE
Apparently detected

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#1246]
Many people on cheater.fun are commenting their accounts were detected (no overwatch, vac ban). Yesterday, I have been particularly banned an account (also direct vac). I am using my own injector that I am sure is not detected. Please, you should check what's happening. It cannot be coincidence.
There is also an Issue # 1238 that comments the same.

Mar 10-2020: https://gyazo.com/fceb534df2c8a50fcf53c02e03e61f9a

**Comment by Asviix** [comment]
There was indeed a vac wave recently, using an undetected injector so I didn't get banned by VAC, otherwise OW bans were not related to this Wave.

**Comment by TauCSGO** [comment]
> There was indeed a vac wave recently, using an undetected injector so I didn't get banned by VAC, otherwise OW bans were not related to this Wave.

So you tell me that Osiris was not detected in this vac wave?
Only the injectors detected?
There is an injector that is used a lot, by @danielkrupinski which he should also check
https://github.com/danielkrupinski/curiuminjector-csgo

**Comment by RyDeem** [comment]
I've NOT gotten banned, and im using a random injector from unknowncheats so i think osiris is not detected.

**Comment by num3rical** [comment]
The two accounts I use Osiris on haven't been banned. I use randoinjector as well, so it's probably the injector you use OP.

**Comment by steel4me** [comment]
There is a wave and something is detected, maybe not osiris itself. Watch back some years, many internals that used VMT hooking got detected. The problems we have now: The bans are delayed. Some account get banned now, some later. I know this from last years, it can take up to 1,2,3 or 4 weeks. Dont know what they do ;)

**Comment by TauCSGO** [comment]
> The two accounts I use Osiris on haven't been banned. I use randoinjector as well, so it's probably the injector you use OP.

I use the curiuminjector-csgo, it's the same as the random-injector
I will continue to investigate. Maybe Daniel can clear our doubts

**Comment by steel4me** [comment]
https://github.com/danielkrupinski/Osiris/issues/1238#issuecomment-597041210

**Comment by tirziz** [comment]
Just a thought, maybe the aimbot pattern got detected by vacnet. I have an account only charm and esp and never get ban. Other with legit aimbot and rcs got ban in this vac wave.

**Comment by NexSqaud** [comment]
Imflame injector (manual map) + added some features + semi-rage config. no vac

**Comment by xAkiraMiura** [comment]
pretty sure curiuminjector is detected, just use inflame or make your own.
also daniel made a VAC disabler.

as Osiris is a Windows only cheat you are certainly on windows. on windows you can press the print screen (often prt sc) button to take a screenshot. if you do not have a print screen button then it may be FN (function) + INS (insert).

**Comment by xBaTm4n** [comment]
so, it's detected or?

**Comment by Matt-cloud** [comment]
> so, it's detected or?

it's not

**Comment by Havoccboi** [comment]
Not detected for me yet!

**Comment by steel4me** [comment]
> so, it's detected or?

at the moment you can't say yes or no. if a VAC detection happened, the accounts will be flagged as detectet. that means. If osiris was detectet on 30 accounts, then the first 10 accounts will be banned immediantly, the next 10 get delay for +14 days, the next 10 accounts get delayed ban +31 days.

VAC Detection != VAC Ban

The longest delayed ban that i was able to confirm was 4 weeks. I read about 6 month but i can't confirm that.

**Comment by num3rical** [comment]
> EDIT / Update: I can now confirm the 3. banned account.

What injector did you use?

**Comment by xBaTm4n** [comment]
played over 50 matches, last one on 9 march. no ban yet. used gh injector + junk | vac bypass + junk and some junks in osiris.

**Comment by xAkiraMiura** [comment]
> **Cause:**
> If a VAC detection happened, the accounts will be flagged as detected. that means. If osiris was detected on 30 accounts, then the first 10 accounts will be banned immediantly, the next 10 get delay for +14 days, the next 10 accounts get delayed ban +31 days. i have some accounts, i guess they are flagged and will be banned soon. the next weeks, they have all red TF and i was not able to get green anymore **;)**
> 

VAC is handled on valve's servers. we do not know how the delayed banning mechanism works (if we did they would change it).

> **Last time played csgo on that account: 20.02.20**

VACnet could have re-reviewed the match and then flagged it? I have seen untrusted bans getting promoted to VAC bans, with untrusted bans being removed (i think, been forever since ive gotten untrusted) VACnet may have been the reason.

**Comment by steel4me** [comment]
> VAC is handled on valve's servers. we do not know how the delayed banning mechanism works (if we did they would change it).

> VACnet could have re-reviewed the match and then flagged it? I have seen untrusted bans getting promoted to VAC bans, with untrusted bans being removed (i think, been forever since ive gotten untrusted) VACnet may have been the reason.

yes sir, just examples how delayed bans **could** work. Some people here think, when one guy got a ban, all others that use osiris, should get banned too at the same time, this is just wrong. cause they use delayed bans.

> played over 50 matches, last one on 9 march. no ban yet. used gh injector + junk | vac bypass + junk and some junks in osiris.

yes sir, that's what i try to explain, i do this since 03/19 but without vac-bypass, that means 9 months without problems  ;)

**Comment by TauCSGO** [comment]
> played over 50 matches, last one on 9 march. no ban yet. used gh injector + junk | vac bypass + junk and some junks in osiris.

The bypass problem (and I think it's already proven by various experiences from different players) is that it drops the factor to red immediately, the reason is unknown.

https://github.com/danielkrupinski/VAC-Bypass-Loader/issues/12#issuecomment-561997753

**Comment by furioushell98** [comment]
These last 3 days i used vac bypass loader, modified osiris with junkcode and an injector from mpgh, also i legit cheated on MM, raged on DZ and casual. And i'm not banned yet.

**Comment by xAkiraMiura** [comment]
junk code not needed. (does nothing)

also if you rage on casual remember that reports carry over so you still can get overwatched but without all 11 or 9 reports.

**Comment by Matt-cloud** [comment]
> > Just a thought, maybe the aimbot pattern got detected by vacnet. I have an account only charm and esp and never get ban. Other with legit aimbot and rcs got ban in this vac wave.
> 
> maybe, hard to guess. i know that other internals got hit. only few bans till now like 2017 with VMT hooks as i already told.
> 
> > > so, it's detected or?
> > 
> > 
> > it's not
> 
> At the moment you can't say yes or no. it's more of an assessment, i tend to yes.
> 
> **Cause:**
> If a VAC detection happened, the accounts will be flagged as detected. that means. If osiris was detected on 30 accounts, then the first 10 accounts will be banned immediantly, the next 10 get delay for +14 days, the next 10 accounts get delayed ban +31 days. i have some accounts, i guess they are flagged and will be banned soon. the next weeks, they have all red TF and i was not able to get green anymore **;)**
> 
> VAC Detection != VAC Ban
> 
> The longest delayed ban that i was able to confirm was 4 weeks. I read about 6 month but i can't confirm that.
> 
> EDIT / Update: I can now confirm the 3. banned account.
> **Last time played csgo on that account: 20.02.20**

Thanks for the info

**Comment by MasterChief220** [comment]
> > Just a thought, maybe the aimbot pattern got detected by vacnet. I have an account only charm and esp and never get ban. Other with legit aimbot and rcs got ban in this vac wave.
> 
> maybe, hard to guess. i know that other internals got hit. only few bans till now like 2017 with VMT hooks as i already told.
> 
> > > so, it's detected or?
> > 
> > 
> > it's not
> 
> At the moment you can't say yes or no. it's more of an assessment, i tend to yes.
> 
> **Cause:**
> If a VAC detection happened, the accounts will be flagged as detected. that means. If osiris was detected on 30 accounts, then the first 10 accounts will be banned immediantly, the next 10 get delay for +14 days, the next 10 accounts get delayed ban +31 days. i have some accounts, i guess they are flagged and will be banned soon. the next weeks, they have all red TF and i was not able to get green anymore **;)**
> 
> VAC Detection != VAC Ban
> 
> The longest delayed ban that i was able to confirm was 4 weeks. I read about 6 month but i can't confirm that.
> 
> EDIT / Update: I can now confirm the 3. banned account.
> **Last time played csgo on that account: 20.02.20**

if the other accounts stop using the cheat they wont be hit by the wave
