### ISSUE TITLE
Watermark font

### ISSUE THREAD

**Issue by darkisgod444** [danielkrupinski/Osiris#1247]
How to change watermark font??

**Comment by bekocango** [comment]
I need to change menu font. Do you know how can i do?

**Comment by darkisgod444** [comment]
I think just replace font path in gui.cpp

**Comment by darkisgod444** [comment]
Please someone help

**Comment by littlehurensohn** [comment]
create font

**Comment by darkisgod444** [comment]
What do you mean create font

**Comment by NexSqaud** [comment]
use vgui_spew_fonts to look for a builtin font. when you choose one go to SDK/Surface.h and replace font value.

**Comment by xAkiraMiura** [comment]
ISurface has a virtual function called `CreateFont`, returning an unsigned int as an id.
ISurface then uses this ID in another vfunc called `SetFontGlyphSet`, assigning it to a windows font.
find where the equivilent of `SetFontGlyphSet` is getting called and change the font name to what you want.
