### ISSUE TITLE
Menu Change Font (ı,ü,ö,ğ...)

### ISSUE THREAD

**Issue by bekocango** [danielkrupinski/Osiris#1248]
Hello i need (ı,ü,ö,ğ...) font characters. How can i change? Please help.

**Comment by ClaudiuHKS** [comment]
Hi, can you post a screenshot?
I think **Osiris** already support such characters, see [master → GUI.cpp, Line # 44](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/GUI.cpp#L44).

Just use ı, ü, ö, ğ in Visual Studio. It should be working.

**Comment by bekocango** [comment]
![Ekran Görüntüsü (42)](https://user-images.githubusercontent.com/62030537/76447204-53034e00-63d9-11ea-93b2-426a7d2ff5a6.jpg)
Here! Please Help.

**Comment by ClaudiuHKS** [comment]
It works. I tested with both **ArialUni.TTF** and **SegoeUI.TTF** (font that **Osiris** is using).
Are you sure **GUI.cpp** file has UTF-8 encoding?

![Example](https://user-images.githubusercontent.com/9334579/76455406-5fd67080-63de-11ea-95ca-159f94cfdd5d.png)

**Comment by bekocango** [comment]
I tried  `setlocale(LC_ALL, "Turkish");`
But nothing :(

**Comment by danielkrupinski** [comment]
Please paste the problematic string
(s) here, so we can test them ourselves.

**Comment by bekocango** [comment]
Hello. I'am trying change this "GUI.cpp": `ImGui::MenuItem("Aim ğüıö", nullptr, &window.aimbot);`
But this characters not showing.

Full Code Part:
`void GUI::renderMenuBar() noexcept
{
    if (ImGui::BeginMainMenuBar()) {
        ImGui::MenuItem("Aim  ğüıö", nullptr, &window.aimbot);
        ImGui::MenuItem("Anti Aim", nullptr, &window.antiAim);
        ImGui::MenuItem("Trigger Hilesi", nullptr, &window.triggerbot);
        ImGui::MenuItem("Backtrack", nullptr, &window.backtrack);
        ImGui::MenuItem("Parlama", nullptr, &window.glow);
        ImGui::MenuItem("Chamlar", nullptr, &window.chams);
        ImGui::MenuItem("Etiket", nullptr, &window.esp);
        ImGui::MenuItem("Gorunum", nullptr, &window.visuals);
        ImGui::MenuItem("Skin Degistirici", nullptr, &window.skinChanger);
        ImGui::MenuItem("Ses", nullptr, &window.sound);
        ImGui::MenuItem("Stil", nullptr, &window.style);
        ImGui::MenuItem("Cesitli", nullptr, &window.misc);
        //ImGui::MenuItem("Rapor Botu", nullptr, &window.reportbot);
        ImGui::MenuItem("Ayarlar", nullptr, &window.config);
        ImGui::EndMainMenuBar();
    }`

**Comment by bekocango** [comment]
> Please paste the problematic string
> (s) here, so we can test them ourselves.

Hello. I'am trying change this "GUI.cpp": ImGui::MenuItem("Aim ğüıö", nullptr, &window.aimbot);
But this characters not showing.

**Comment by danielkrupinski** [comment]
[Save file as UTF-8](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-save-and-open-files-with-encoding?view=vs-2019#to-save-a-file-with-encoding)
