### ISSUE TITLE
Legit anti-aim?

### ISSUE THREAD

**Issue by Nojus0** [danielkrupinski/Osiris#1249]
title says all

**Comment by notgoodusename** [comment]
pretty simple there is a lot of public info, i think you can do it yourself

**Comment by xAkiraMiura** [comment]
the current anti-aim is a legit anti aim.
doesn't work well but thats beside the point.

**Comment by streamshark** [comment]
why is the desync delta so shitty? does breaking lby method increase max desync compared to micromovement method? browsing unknowncheats but I can't find info on that specifically

**Comment by notgoodusename** [comment]
> why is the desync delta so shitty? does breaking lby method increase max desync compared to micromovement method? browsing unknowncheats but I can't find info on that specifically

lby breakering doubles the desync delta

**Comment by streamshark** [comment]
![csgo_BcPVMtZeEN](https://user-images.githubusercontent.com/43255752/76476135-50dfc600-63be-11ea-85d8-e6320080f607.png)
pasted in an LBY breaker from Fuzion and got this. hard to test if it works on multiplayer well, and got kicked for untrusted after awhile for having my angles out of clamp range

**Comment by notgoodusename** [comment]
> ![csgo_BcPVMtZeEN](https://user-images.githubusercontent.com/43255752/76476135-50dfc600-63be-11ea-85d8-e6320080f607.png)
> pasted in an LBY breaker from Fuzion and got this. hard to test if it works on multiplayer well, and got kicked for untrusted after awhile for having my angles out of clamp range

that doesnt show anything

**Comment by streamshark** [comment]
huh? blue hitbox = real, look at the feet. also had pitch on in this screenshot

**Comment by xAkiraMiura** [comment]
you could probably test it with `bot_mimic 1`
clamp the angles and it would be good, too bad its pasted. at least it uses the same approach as current so can still improve.

**Comment by designer1337** [comment]
that's how proper deync should look like:

![proper desync](https://i.imgur.com/0UQeYnC.png)

3 lines proper desync with lby breaker and without triggering balance adjust anim.

**Comment by streamshark** [comment]
are you using animstate based lby update prediction?

**Comment by notgoodusename** [comment]
> are you using animstate based lby update prediction?

just use a timer

**Comment by 3L337-n2** [comment]
@notgoodusename But when i use your lby antiaim is will rotate to the real hitbox , this is because i'm not breaking the lby?

**Comment by notgoodusename** [comment]
> @notgoodusename But when i use your lby antiaim is will rotate to the real hitbox , this is because i'm not breaking the lby?

yes and because my old antiaim pull request is wrong, i have made it now and made sure it works so i might release it

**Comment by 3L337-n2** [comment]
Wow, i'm too impatient to wait for it.

**Comment by notgoodusename** [comment]
> Wow, i'm too impatient to wait for it.

done. #1257

**Comment by 3L337-n2** [comment]
Thx :P
