### ISSUE TITLE
Osiris got detected...

### ISSUE THREAD

**Issue by AbdallahMehiz** [danielkrupinski/Osiris#1251]
some of my friends (alot) happened to get vac banned using osiris
i didn't get it cause of vac bypass loader
we can clearly see the vac wave and the comments on cheater.fun of people getting vac banned
![image](https://user-images.githubusercontent.com/59295266/76529668-e177de00-6472-11ea-9464-be7f3631b1d6.png)

**Comment by streamshark** [comment]
lots of p2cs got "semi-detected", seems more likely vac is detecting a specific feature than any. though, Osiris is open source so it's always a possibility. use VAC bypass by Daniel when you play for best safety

**Comment by yEsPaP** [comment]
Compile vac bypass loader, remove steam from startup on pc and add the compile vac bypass loader to startup.

**Comment by craxking** [comment]
> Compile vac bypass loader, remove steam from startup on pc and add the compile vac bypass loader to startup.

you know he is talking about his friends right?

**Comment by tirziz** [comment]
No idea, what is detected. Just be safe and dont use one your main

**Comment by djsall** [comment]
https://i.imgur.com/tOHqIkz.png
I got hit by it too, been using osiris with some changed function names, deleted comments, etc. Probablyx a feature, not the entire source is detected.

**Comment by xAkiraMiura** [comment]
cheater.fun is most certainly not a reliable source. the people on there probably have detected injectors or paste siged features.
i doubt Osiris is detected, if it were then **my** accounts would be VAC banned.

*hint: VAC checks your system USN journels for the system partition.* ***this means dont put anything on your C:/ drive.*** *either make a different partition or use a different drive.*

> I got hit by it too, been using osiris with some changed function names, deleted comments, etc.

changing function names does literally nothing. it doesn't even change the hash like junk code does (which is also useless).
deleting comments also does literally nothing. they are removed by the compiler
**please learn what a compiler does and what machine code is**

> Probably a feature, not the entire source is detected.

or the hooking method. or the hooks. or the use of interfacs.

**Comment by littlehurensohn** [comment]
lmao, my paste is UD more then 1 year

**Comment by ripkyo** [comment]
I've been using Osiris with [MemJect](https://github.com/danielkrupinski/MemJect) for 1 year and never got banned.

**Comment by ClaudiuHKS** [comment]
Osiris is undetected.

I and five of my friends share the same injector and never got banned.
I've changed a few text lines inside our copy of Osiris and added some small fixes or edits, nothing more.

If you get banned, the first thing you should do is to check whether the injector you've ran is detected or not.

Note that if you ran multiple injectors, in the last 30 or even 90 days, no idea, you probably don't know which one caused the ban.

**Comment by djsall** [comment]
> changing function names does literally nothing. it doesn't even change the hash like junk code does (which is also useless).
I have a basic understanding of the compiler, I just didn't think it through. Thanks for pointing it out!
Also, thanks for the tip with the C drive.

**Comment by djsall** [comment]
>If you get banned, the first thing you should do is to check whether the injector you've ran is detected or not.

[This](https://github.com/h4zey/Dll-Injector) is the injector I use.

**Comment by VuBrian22** [comment]
> > If you get banned, the first thing you should do is to check whether the injector you've ran is detected or not.
> 
> [This](https://github.com/h4zey/Dll-Injector) is the injector I use.

That injector hasn't been updated in 2 years. I wouldn't trust it in your situation. It is probably detected. In addition, since it seems like you have very little knowledge and only "have a basic understanding of the compiler" then I don't think you updated it either.

**Comment by xBaTm4n** [comment]
I use GH injector (open spurce) no ban yet. With vac bypass

**Comment by steel4me** [comment]
> lots of p2cs got "semi-detected", seems more likely vac is detecting a specific feature than any. though, Osiris is open source so it's always a possibility. use VAC bypass by Daniel when you play for best safety, as you already do

this is a good and helpful assumption, there are many indications, even if nobody wants to admit it

I know this issue is closed. But i want to share this with you mates:
https://github.com/danielkrupinski/Osiris/issues/1268#issuecomment-601613898

**Comment by vsnrytune** [comment]
I feel like it's been detected, but not insta ban, they're just flagging accounts and putting them in low trust for delayed ban. For the past week I've been in red trust factor even tho I do everything I can not to be and rarely get called out as I play very legit. Nothing I do is getting me out of red trust

**Comment by steel4me** [comment]
> I feel like it's been detected, but not insta ban, they're just flagging accounts and putting them in low trust for delayed ban. For the past week I've been in red trust factor even tho I do everything I can not to be and rarely get called out as I play very legit. Nothing I do is getting me out of red trust

At least one person who understood what I wanted to tell everyone here, thank you!

I have some accounts that do exactly the same and I know when the ban will happen. i hope i am wrong with my guesses. trade everything away from these accounts, the delay is 2-8 weeks.
