### ISSUE TITLE
自定义字体

### ISSUE THREAD

**Issue by 18339256125** [danielkrupinski/Osiris#1252]
When I customize the font, he appears ?? But my query font contains this font

**Comment by zHElEARN** [comment]
老哥你这个标题用中文，内容又用英文是啥操作啊（笑

更改字体之后 使用中文要用“u8”

在Visual Studio 2017中
直接在字符串前加`u8`即可
例如
```c++
ImGui::Begin(u8"自瞄", &window.aimbot, windowFlags);
```

如果是在Visual Studio 2019中
添加一个宏
```c++
#define U8(S) reinterpret_cast<const char *>(u8##S)
```
然后
```c++
ImGui::Begin(U8("自瞄"), &window.aimbot, windowFlags);
```
即可

**Comment by 18339256125** [comment]
舒服了

**Comment by 18339256125** [comment]
> 老哥你这个标题用中文，内容又用英文是啥操作啊（笑
> 
> 更改字体之后使用中文要用“ u8”
> 
> 在Visual Studio 2017中直接
> 在字符串前加`u8`即可
> 例如
> 
> ```c++
> ImGui :: Begin（u8“自瞄”，＆window.aimbot，windowFlags）;
> ```
> 
> 如果是在Visual Studio 2019中
> 添加一个宏
> 
> ```c++
> ＃定义 U8（S）reinterpret_cast < const  char *>（u8 ## S）
> ```
> 
> 然后
> 
> ```c++
> ImGui :: Begin（U8（“自瞄”），＆window.aimbot，windowFlags）;
> ```
> 
> 即可

不行啊,我定义宏之后用U8.还是?? 这怎么办,tahoma字体中有中文啊

**Comment by zHElEARN** [comment]
> > 老哥你这个标题用中文，内容又用英文是啥操作啊（笑
> > 更改字体之后使用中文要用“ u8”
> > 在Visual Studio 2017中直接
> > 在字符串前加`u8`即可
> > 例如
> > ```c++
> > ImGui :: Begin（u8“自瞄”，＆window.aimbot，windowFlags）;
> > ```
> > 
> > 
> > 如果是在Visual Studio 2019中
> > 添加一个宏
> > ```c++
> > ＃定义 U8（S）reinterpret_cast < const  char *>（u8 ## S）
> > ```
> > 
> > 
> > 然后
> > ```c++
> > ImGui :: Begin（U8（“自瞄”），＆window.aimbot，windowFlags）;
> > ```
> > 
> > 
> > 即可
> 
> 不行啊,我定义宏之后用U8.还是?? 这怎么办,tahoma字体中有中文啊

你可以试试msyh.ttc

**Comment by 18339256125** [comment]
> > > 老哥你这个标题用中文，内容又用英文是啥操作啊（笑
> > > 更改字体之后使用中文要用“ u8” 
> > > 在Visual Studio 2017中直接
> > > 在字符串前加`u8`可用
> > > 例如
> > > ```c++
> > > ImGui ::开始（u8“自瞄”，＆window.aimbot，windowFlags）；
> > > ```
> > > 
> > > 
> > > 如果是在Visual Studio 2019中
> > > 添加一个宏
> > > ```c++
> > > ＃定义U8（S）reinterpret_cast < const   char *>（u8 ## S）
> > > ```
> > > 
> > > 
> > > 然后
> > > ```c++
> > > ImGui :: Begin（U8（“自瞄”），＆window.aimbot，windowFlags）；
> > > ```
> > > 
> > > 
> > > 即可
> > 
> > 
> > 不行啊，我定义宏之后用U8。还是？这怎么办，tahoma字体中有中文啊
> 
> 你可以试试msyh.ttc
这次真的舒服了 感谢

**Comment by FiYHer** [comment]
A method that doesn't use u8
`std::string string_to_utf8(const std::string& str)
{
    int nwLen = MultiByteToWideChar(CP_ACP, 0, str.c_str(), -1, NULL, 0);
    wchar_t* pwBuf = new wchar_t[nwLen + 1];
    memset(pwBuf, 0, nwLen * 2 + 2);
    MultiByteToWideChar(CP_ACP, 0, str.c_str(), str.length(), pwBuf, nwLen);
	
    int nLen = ::WideCharToMultiByte(CP_UTF8, 0, pwBuf, -1, NULL, NULL, NULL, NULL);
    char* pBuf = new char[nLen + 1];
    memset(pBuf, 0, nLen + 1);
    WideCharToMultiByte(CP_UTF8, 0, pwBuf, nwLen, pBuf, nLen, NULL, NULL);

    delete[]pwBuf;
    delete[]pBuf;

    return std::string(pBuf);
}

void show_chinese()
{
	ImGui::Text(string_to_utf8("显示中文"));
}`

**Comment by FiYHer** [comment]
//A method that doesn't use u8

std::string string_to_utf8(const std::string& str)
{
    int nwLen = MultiByteToWideChar(CP_ACP, 0, str.c_str(), -1, NULL, 0);
    wchar_t* pwBuf = new wchar_t[nwLen + 1];
    memset(pwBuf, 0, nwLen * 2 + 2);
    MultiByteToWideChar(CP_ACP, 0, str.c_str(), str.length(), pwBuf, nwLen);
	
    int nLen = ::WideCharToMultiByte(CP_UTF8, 0, pwBuf, -1, NULL, NULL, NULL, NULL);
    char* pBuf = new char[nLen + 1];
    memset(pBuf, 0, nLen + 1);
    WideCharToMultiByte(CP_UTF8, 0, pwBuf, nwLen, pBuf, nLen, NULL, NULL);

    delete[]pwBuf;
    delete[]pBuf;

    return std::string(pBuf);
}

void show_chinese()
{
	ImGui::Text(string_to_utf8("显示中文"));
}

**Comment by FiYHer** [comment]
//A method that doesn't use u8
std::string string_to_utf8(const std::string& str)
{
    int nwLen = MultiByteToWideChar(CP_ACP, 0, str.c_str(), -1, NULL, 0);
    wchar_t* pwBuf = new wchar_t[nwLen + 1];
    memset(pwBuf, 0, nwLen * 2 + 2);
    MultiByteToWideChar(CP_ACP, 0, str.c_str(), str.length(), pwBuf, nwLen);
    int nLen = WideCharToMultiByte(CP_UTF8, 0, pwBuf, -1, NULL, NULL, NULL, NULL);
    char* pBuf = new char[nLen + 1];
    memset(pBuf, 0, nLen + 1);
    WideCharToMultiByte(CP_UTF8, 0, pwBuf, nwLen, pBuf, nLen, NULL, NULL)'
    delete[]pwBuf;
    delete[]pBuf;
    return std::string(pBuf);
}
void show_chinese()
{
	ImGui::Text(string_to_utf8("显示中文"));
}

**Comment by FiYHer** [comment]
//A method that doesn't use u8
std::string string_to_utf8(const std::string& str)
{
	int nwLen = MultiByteToWideChar(CP_ACP, 0, str.c_str(), -1, NULL, 0);
	wchar_t* pwBuf = new wchar_t[nwLen + 1];
	memset(pwBuf, 0, nwLen * 2 + 2);
	MultiByteToWideChar(CP_ACP, 0, str.c_str(), str.length(), pwBuf, nwLen);

	int nLen = WideCharToMultiByte(CP_UTF8, 0, pwBuf, -1, NULL, NULL, NULL, NULL);
	char* pBuf = new char[nLen + 1];
	memset(pBuf, 0, nLen + 1);
	WideCharToMultiByte(CP_UTF8, 0, pwBuf, nwLen, pBuf, nLen, NULL, NULL);

	std::string ret = pBuf;
	delete[]pwBuf;
	delete[]pBuf;

	return ret;
}
void show_chinese()
{
ImGui ::Text(string_to_utf8("显示中文").c_str());
}

**Comment by jackieyiwu** [comment]
作者不是已经修正过UTF-8支持了吗？ 改下字体和字库就可以直接输出了
