### ISSUE TITLE
Prime Hack VAC Detected or No?

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#1256]
So i just inject the cheat, turn on prime and unhook it, can i get banned?

**Comment by darkisgod444** [comment]
I don't know why would you do that because fake prime in osiris is visual change only as i know.

**Comment by num3rical** [comment]
> 
> 
> I don't know why would you do that because fake prime in osiris is visual change only as i know.

This is correct, all the fake prime function does is show to you and other people in your lobby that you have a prime-enabled account. You will still be put in a non-prime game.

**Comment by xAkiraMiura** [comment]
Osiris doesn't unload correctly. this is evident by the fact you can't reinject with LoadLibrary
although unhooking decreases your chance of being detected greatly, osiris is memory resident to some capacity so it's not perfectly safe.
