### ISSUE TITLE
StudioRender.h Error

### ISSUE THREAD

**Issue by CerberusGame** [danielkrupinski/Osiris#1258]
return std::string_view{ materialOverride->getName() }.starts_with("dev/glow");
starts_with error in StudioRender.h

**Comment by xAkiraMiura** [comment]
you modified the source incorrectly. either clone from this repo or clone from the pull you tried to use.
*please stop trying to manually paste over code, it never works and this is evidence for that*

syntax: `git clone github.com/user/repo.git`
example: `git clone github.com/danielkrupinski/Osiris.git`

**Comment by CerberusGame** [comment]
Change code to:
`return std::strstr(materialOverride->getName(), "dev/glow") != nullptr;`

**Comment by CerberusGame** [comment]
Change code to :
`return std::strstr(materialOverride->getName(), "dev/glow") != nullptr;`
