### ISSUE TITLE
[Question] backtrack/snipers aim

### ISSUE THREAD

**Issue by furioushell98** [danielkrupinski/Osiris#1259]
Hello. I'd like to know what does "recoil based backtrack" mean in Osiris. I tried it on and off and i couldn't tell the difference, and there's no explanation for it in the github Readme. I'd like to know what makes backtrack stronger, having it on or off? 
And one more thing, in Aimbot menu i can find smg/heavy/rifle/pistol tabs but no tab for Awp, scout, autos. I guess their settings are included in "All" tab?

**Comment by xAkiraMiura** [comment]
snipe (rifles) are apart of the rifles tab iirc.
recoil based backtrack has something to do with the aimpunch but i haven't done enough testing to see if its benefitial.

**Comment by furioushell98** [comment]
Thanks.
