### ISSUE TITLE
Banned while using Osiris

### ISSUE THREAD

**Issue by num3rical** [danielkrupinski/Osiris#1261]
Just got an untrusted ban on the account that I only use Osiris, so either the cheat is detected or a feature is detected, since I doubt it's the injector (randoinjector). I'm not going to use Osiris for a while, and I suggest everyone else do the same until what exactly is detected can be determined.

As a reference to Daniel or anyone else trying to figure this out, I used Osiris with these pull requests added to it:

#989 
#1257 

I also had nearly every feature enabled, so if it truly is a detected feature it would be hard to determine from me which one it is. However, if others that were banned can share what features they had enabled, it could help.

**Comment by xAkiraMiura** [comment]
i know that my pull doesn't use untrusted angles but i haven't tested notgoodusernames's pull.
in misc i think there is a setting to max the delta or something, make sure that was enabled.

in a normal use case untrusted bans never occur because VACnet stopped banning on its own and relys on OW instead.

my theory is that ngu's pull is going outside the max delta and doing untrusted angles that are never caught because they are properly clamped (just too much of a difference).

*also how did you use my pull with theirs? was my code modular enough to integrate it?*

**Comment by num3rical** [comment]
> also how did you use my pull with theirs? was my code modular enough to integrate it?
Sorry, I was a bit confusing in my post. I meant that I had used both of those at one point on the cheat, but not at the same time. I'm going to make a new account and play without ngu's pull and see if I get banned anytime soon.

**Comment by xAkiraMiura** [comment]
my pull uses a constant value for spin speed which might be outside of the max angle delta, thats the only way i think mine could cause a ban.

**Comment by furioushell98** [comment]
Bruh. Since 10 march till today i've been using daily vac bypass loader, compiled dll of osiris from corsair.wtf (compiled on 10 march) and an undetected injector from mpgh, i use almost all misc features, backtrack rcs fov glow chams etc. I rage on casual and Dz to finish operation missions, and on my main btw lmao, no bans yet. ¯\_(ツ)_/¯

**Comment by dapaster** [comment]
My acc is almost lvl 19 already . And many pull request ive been added/used except raging on Competitive. Still no ban yet . 

I use Daniel Vac Disabler and using random free injector . Still no ban .

**Comment by notgoodusename** [comment]
> Just got an untrusted ban on the account that I only use Osiris, so either the cheat is detected or a feature is detected, since I doubt it's the injector (randoinjector). I'm not going to use Osiris for a while, and I suggest everyone else do the same until what exactly is detected can be determined.
> 
> As a reference to Daniel or anyone else trying to figure this out, I used Osiris with these pull requests added to it:
> 
> #989
> #1257
> 
> I also had nearly every feature enabled, so if it truly is a detected feature it would be hard to determine from me which one it is. However, if others that were banned can share what features they had enabled, it could help.

DUDE DONT USE AA ON DEATHMATCH THAT GIVES YOU UNTRUSTED EASY IN 2 SECONDS NO FEATURE IS DETECTED

**Comment by xAkiraMiura** [comment]
alright so it seems your's is detected not mine.

> 
> 
> Bruh. Since 10 march till today i've been using daily vac bypass loader, compiled dll of osiris from corsair.wtf (compiled on 10 march) and an undetected injector from mpgh, i use almost all misc features, backtrack rcs fov glow chams etc. I rage on casual and Dz to finish operation missions, and play MM too, on my main btw lmao, no bans yet. ¯_(ツ)_/¯

this issue relates to our specific pulls. not base osiris.
also why are you using braindead forums, its super easy to compile, takes less than 10 seconds, and injectors are easy to make (or compile daniel's Inflame injector).

**Comment by furioushell98** [comment]
> also why are you using braindead forums, its super easy to compile, takes less than 10 seconds, and injectors are easy to make (or compile daniel's Inflame injector).
I don't have ms visuals installed yet ( limited net ) so that might take a while. I took a look at Inflame injector and it seems interesting. Btw what is safer? Manual map or loadlibrary?

**Comment by xAkiraMiura** [comment]
loadlibrary is much more common but manual map occassionally triggers VAC.
MM also allows re-injection with osiris.
