### ISSUE TITLE
I'am using on Prime! 

### ISSUE THREAD

**Issue by bekocango** [danielkrupinski/Osiris#1263]
Hello, I'am using this chat on my prime account. I'am using aim bot with silent Fov 20. And just chams. No wall hack. Without i use vac bypass. Can i get ban? Pleas give me info. Thanks...

**Comment by CerberusGame** [comment]
Don't be banned if you play legit ( Sorry my english is bad)

**Comment by furioushell98** [comment]
You should definitely use vac bypass just in case, cuz people say osiris is detected

**Comment by bekocango** [comment]
> Don't be banned if you play legit ( Sorry my english is bad)

Yes i plays really legit. Thanks.

**Comment by bekocango** [comment]
> You should definitely use vac bypass just in case, cuz people say osiris is detected

I am using. But i have lots of junk code. Is this detected ?

**Comment by xAkiraMiura** [comment]
as low as 2 FOV has gotten me called out by teammates.
not using wallhack doesn't make you any more legit?
vac bypass may get you a VAC Auth.
**junk code does** ***nothing***

*idk how fov is calculated but i think 20 fov is around a 3rd of your screen size. (not at all legit)*

please only use osiris on non-prime accounts, it's a medium sized public cheat and could be sigged at any moment.
