### ISSUE TITLE
Osiris is detected

### ISSUE THREAD

**Issue by Wincheat** [danielkrupinski/Osiris#1264]
Well i was using only chams, and rank revealer. 

The first day was fine, next day i got vac ban. 

I recommend all people to stop using osiris until they find a fix. I even added 100 + junkcodes, ran i through vm protect, so something must be wrong :)

**Comment by CerberusGame** [comment]
vmprotect detected and injector :) 
Use [https://github.com/danielkrupinski/VAC-Bypass-Loader](url)

**Comment by notgoodusename** [comment]
> Well i was using only chams, and rank revealer.
> 
> The first day was fine, next day i got vac ban.
> 
> I recommend all people to stop using osiris until they find a fix. I even added 100 + junkcodes, ran i through vm protect, so something must be wrong :)

your injector is detected and junk code and vm protect doesnt make the dll undetected

**Comment by JohnnyBoyXd** [comment]
> vmprotect detected and injector :)
> Use [https://github.com/danielkrupinski/VAC-Bypass-Loader](url)

When i use "VAC-Bypass-Loader" i can't inject Osiris, i get the error "access is denied", i tried injecting with the Project-Infinity Injector and Process hacker 2, if you know why and know how to fix it please let me know. :)

**Comment by xAkiraMiura** [comment]
junkcode does nothing

also run your injector as admin.
vac bypass runs steam as admin which runs CSGO as admin and so your injector needs to be admin

> I recommend all people to stop using osiris until they find a fix.

we have a fix, its called understanding how VAC works.

**Comment by whiteworthy** [comment]
@xAkiraMiura are you using vac bypass or just the raw dll?

**Comment by xAkiraMiura** [comment]
i dont use vac bypass at all because i made my own steam management software that is incompatible with it. 
when i encounter a vac auth i discard the account either way so i would rather get a full ban infrequently than a soft ban frequently.

i know how vac bypass works because a cancerous memory resident p2c uses it and its a pain to inject anything else.

**Comment by xBaTm4n** [comment]
Guys, in last 3 days i played with vac bypass + gh injector with junks and hash changed every time. No ban yet. I played over 65 matches for now

**Comment by xAkiraMiura** [comment]
# junk code does nothing

learn how assembly signatures work.
changing the hash also does nothing.

**Comment by Zhxcky** [comment]
when i use vac bypass, i cannot open Osiris menu, any help?

**Comment by Zhxcky** [comment]
> Guys, in last 3 days i played with vac bypass + gh injector with junks and hash changed every time. No ban yet. I played over 65 matches for now

still no ban?
