### ISSUE TITLE
 Hello, I would have a Question.

### ISSUE THREAD

**Issue by DoctorYasin** [danielkrupinski/Osiris#1265]
I am modifying ImGui by myself. How much chance does this lower my risk of getting caught?

For example ;
ImGui::Checkbox | ImGui::Chi
ImGui::Button | ImGui::But

Would It Benefit Me?
I am waiting for your ideas.

**Comment by designer1337** [comment]
It won't.

**Comment by DoctorYasin** [comment]
I used to use it like this. I have now updated the imgui version.
https://cdn.discordapp.com/attachments/616700990556733461/688327054877262038/Ekran_Alnts.PNG

**Comment by xAkiraMiura** [comment]
because imgui is not exclusive to hacking it will probably not get detected (ever).
learn how the compiler works, changing function names won't do anything. the assembly output will be exactly the same.

**Comment by littlehurensohn** [comment]
> I used to use it like this. I have now updated the imgui version.
> https://cdn.discordapp.com/attachments/616700990556733461/688327054877262038/Ekran_Alnts.PNG

honestly, looks as trash.

**Comment by xAkiraMiura** [comment]
1. the padding is inconsistent
2. the text is very close to clipping outside the bubble boxes (text needs to be verically centered)
3. the icons are of different sizes.

i do like the color scheme though, if you somehow centered the text verically and maybe horizontally then it could work.

**Comment by DoctorYasin** [comment]
Actually I Designed This Menu According To Customers' Desires But Your Ideas Satisfied Me.

**Comment by danielkrupinski** [comment]
I assume your question has been answered.
