### ISSUE TITLE
Custom hitsound 

### ISSUE THREAD

**Issue by darkisgod444** [danielkrupinski/Osiris#1267]
Can i use my custom hitsound??? i have the .wav file but i think osiris plays the sounds from memory

**Comment by bytixo** [comment]
Osiris play the sound from the files actually so i think you can't load custom sound https://imgur.com/a/jDLP0Ht

**Comment by RyDeem** [comment]
put the file in the csgo files and change the code to mirror that?

**Comment by xAkiraMiura** [comment]
`./csgo/sounds` gets dynamically loaded at run time. its probably `EngineClient::PlaySound`

**Comment by EurobeatClub** [comment]
Make a folder in here:
C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\sound\(new folder)
Then add the .wav file into that folder and add hitsound to misc.h like this:
"play (new folder)/(sound)",
Works for me.

**Comment by Oly-UK** [comment]
#1434
