### ISSUE TITLE
How to trace rays?

### ISSUE THREAD

**Issue by notgoodusename** [danielkrupinski/Osiris#1269]
i want to trace 4 rays from a person, i dont know how.
what does the mask is? how can i trace a ray 90 degrees apart? and how can i get if it is visible?

**Comment by streamshark** [comment]
if you can find the original edgejump pull request it used rays (enginetrace), masks are primarily used to filter the localplayer out of the trace so it doesn't just immediately hit the player if started at eyepoint etc.. but masks can be used to filter whatever you don't want to hit out of the trace

**Comment by notgoodusename** [comment]
ok but how can i know what mask to use?

**Comment by streamshark** [comment]
oops, I confused masks with filters. I THINK masks are what you want to hit with the ray (ex map terrain), filters are what you don't want to include in the trace. not sure how you find masks. looking at the old edgejump 0x1400B is the mask for hitting map terrain but i'm not sure where that was derived from

**Comment by danielkrupinski** [comment]
[There you have masks](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/public/bspflags.h)

**Comment by ClaudiuHKS** [comment]
[This is how to trace from origin, with no limits, using angles.](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hacks/Triggerbot.cpp#L49)
[This is how to trace from an origin to another origin.](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hacks/Aimbot.cpp#L71)

**Comment by notgoodusename** [comment]
> [This is how to trace from origin, with no limits, using angles. Well there is a limit, of course, in this example, the maximum weapon range but you can use 8192.0f as the maximum value.](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hacks/Triggerbot.cpp#L49)
> [This is how to trace from an origin to another origin.](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hacks/Aimbot.cpp#L71)

ok thanks, now how can i like make bool that detects if it is visible

**Comment by ClaudiuHKS** [comment]
[I don't know exactly what you mean, this is a clean example of use though.](https://pastebin.com/42i4hHrF)

[If you need to check the visibility maybe you wanna take a look here.](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/SDK/Entity.h#L109)

**Comment by notgoodusename** [comment]
> [I don't know exactly what you mean, this is a clean example of use though.](https://pastebin.com/42i4hHrF)
> 
> [If you need to check the visibility maybe you wanna take a look here.](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/SDK/Entity.h#L109)
> 
> You always have to use MASK_SHOT in a CS:GO cheat.

thats for seeing a player not a ray, what i mean is a check for ray visibility
