### ISSUE TITLE
[SUGGESTION] Maybe Lua

### ISSUE THREAD

**Issue by playday3008** [danielkrupinski/Osiris#1270]
Maybe someone want to add Lua in Osiris
I find Osiris repo with integrated Lua, but without functional
Maybe Daniel can migrate Lua from this [repo](https://github.com/TXIuTnVsbA/Osiris_Edit) to original Osiris repo

**Comment by num3rical** [comment]
Lua isn't needed in an open source cheat, everything you need can just be added directly to the code.

**Comment by playday3008** [comment]
Yea, but for example anybody wants to add rainbow border to code? No.
But maybe, someone wants rainbow border or someone (bad English) else in Osiris, but majority doesn't want this shit

**Comment by HowToMakeFaceitAB** [comment]
well it's a good idea luas , since some ppl like me don't know how to code . luas are a pretty good idea
we can use other ppls code without adding them into the cheat

**Comment by xAkiraMiura** [comment]
interpreted code like python, c#, java, or lua will never run as fast as compiled C/C++. implementing LUA would have performance implications, also c++ is super easy to use, why not just program in it in the first place. 

most LUAs implmentations don't have a standard, a fatality LUA won't work with onetap and a skeet lua wont work with aimware. all LUAs would have to be rewritten for Osiris.



> well it's a good idea luas , since some ppl like me don't know how to code . luas are a pretty good idea

it's still programming?
> we can use other ppls code without adding them into the cheat

literally just clone another person's code. `git merge` if you want multiple people's code.
`git clone https://github.com/USER/REPO.git`

LUAs add another detection vector. also you could probably make a malicious LUA that would give arbituary code execution on a machine.

> Yea, but for example anybody wants to add rainbow border to code? No.
> But maybe, someone wants rainbow border or someone (bad English) else in Osiris, but majority doesn't want this shit

you can make the changes without commiting them and making a pull, you know?
also there is a helper function that literally manages rainbow for you, just add it to the style selector.

**Comment by playday3008** [comment]
> you can make the changes without commiting them and making a pull, you know?
I know, but i am stupid for c++))

**Comment by HowToMakeFaceitAB** [comment]
> interpreted code like python, c#, java, or lua will never run as fast as compiled C/C++. implementing LUA would have performance implications, also c++ is super easy to use, why not just program in it in the first place.
> 
> most LUAs implmentations don't have a standard, a fatality LUA won't work with onetap and a skeet lua wont work with aimware. all LUAs would have to be rewritten for Osiris.
> 
> > well it's a good idea luas , since some ppl like me don't know how to code . luas are a pretty good idea
> 
> it's still programming?
> 
> > we can use other ppls code without adding them into the cheat
> 
> literally just clone another person's code. `git merge` if you want multiple people's code.
> `git clone https://github.com/USER/REPO.git`
> 
> LUAs add another detection vector. also you could probably make a malicious LUA that would give arbituary code execution on a machine.
> 
> > Yea, but for example anybody wants to add rainbow border to code? No.
> > But maybe, someone wants rainbow border or someone (bad English) else in Osiris, but majority doesn't want this shit
> 
> you can make the changes without commiting them and making a pull, you know?
> also there is a helper function that literally manages rainbow for you, just add it to the style selector.

hey how do you merge pull requests?

**Comment by HowToMakeFaceitAB** [comment]
> REPO

pls reply

**Comment by hyperxpro** [comment]
> interpreted code like python, c#, java, or lua will never run as fast as compiled C/C++. implementing LUA would have performance implications, also c++ is super easy to use, why not just program in it in the first place.
> 
> most LUAs implmentations don't have a standard, a fatality LUA won't work with onetap and a skeet lua wont work with aimware. all LUAs would have to be rewritten for Osiris.
> 
> > well it's a good idea luas , since some ppl like me don't know how to code . luas are a pretty good idea
> 
> it's still programming?
> 
> > we can use other ppls code without adding them into the cheat
> 
> literally just clone another person's code. `git merge` if you want multiple people's code.
> `git clone https://github.com/USER/REPO.git`
> 
> LUAs add another detection vector. also you could probably make a malicious LUA that would give arbituary code execution on a machine.
> 
> > Yea, but for example anybody wants to add rainbow border to code? No.
> > But maybe, someone wants rainbow border or someone (bad English) else in Osiris, but majority doesn't want this shit
> 
> you can make the changes without commiting them and making a pull, you know?
> also there is a helper function that literally manages rainbow for you, just add it to the style selector.

Java is not interpreted. Go learn some basics kid.

**Comment by xAkiraMiura** [comment]
> 
> 
> > ~
> 
> Java is not interpreted. Go learn some basics kid.

are you not going to point out how C# isn't interpreted then?

https://en.wikipedia.org/wiki/Bytecode
>  Bytecode may often be either directly executed on a virtual machine (a p-code machine i.e., **interpreter**), or it may be further compiled into machine code for better performance.
