### ISSUE TITLE
Cant compile the cheat

### ISSUE THREAD

**Issue by sorrowvibez** [danielkrupinski/Osiris#1271]
the config code has too many errors and i cant built it

**Comment by m0nsterJ** [comment]
Did you change your setting from Debug to Release?

**Comment by sorrowvibez** [comment]
> Did you change your setting from Debug to Release?

yes i did

**Comment by xAkiraMiura** [comment]
what visual studio version are you using? i think 2019 is required for the v142 toolkit.
try using `git clone https://github.com/danielkrupinski/Osiris.git` and see if a fresh copy will build.

**Comment by danielkrupinski** [comment]
#1158
