### ISSUE TITLE
[SUGGESTION] Rank/Medal/Level changer 

### ISSUE THREAD

**Issue by whirlpool2** [danielkrupinski/Osiris#1272]
Fake Prime is a pretty nice addition, but it left me wondering if fake rank and level can work. There's been cheats that can do that. This is only a suggestion, it's only up to Daniel if he wants to implement it.

**Comment by xAkiraMiura** [comment]
there does exist a working method related to lobby messages, the implementation ive seen doesn't show up locally, however.
every time ive seen the level changer it always shows a variable name rather than "Level x"
