### ISSUE TITLE
[REQUEST] Extended Backtracking

### ISSUE THREAD

**Issue by m0nsterJ** [danielkrupinski/Osiris#1273]
~

**Comment by RyDeem** [comment]
YES THIS WOULD BE AMAZING
/caps

**Comment by Shaxzy** [comment]
Wasn't this patched ages ago? I might be wrong, but I remember doing this back in 2018 and it got patched. 🤔

**Comment by m0nsterJ** [comment]
The 1000ms Backtrack was Patched,indeed, but you can still extend the backtrack from ~200ms to about 400ms with Fake Latency (around 250ms is enough)

**Comment by xAkiraMiura** [comment]
explanation: you are converting the 200ms forward tracking window into a backtrack window as well by fake lagging.
if you have real lag it will subtract from the forward tracking window.

**Comment by notgoodusename** [comment]
> Wasn't this patched ages ago? I might be wrong, but I remember doing this back in 2018 and it got patched. 🤔

no.
i tried doing this the problem comes when trying to hook it #1064
