### ISSUE TITLE
Crashing on memory.isOtherEnemy

### ISSUE THREAD

**Issue by LeYesnt** [danielkrupinski/Osiris#1274]
I have been getting a weird crash after the latest update, when i try to debug it i get this?
Can some pro please help me:
![image](https://user-images.githubusercontent.com/39915461/76954639-f50ec300-6910-11ea-8c46-e253bf0bcf6a.png)

**Comment by xAkiraMiura** [comment]
are you checking if localPlayer is valid?
are you checking if the entity is valid?

0xC0000005 means a bad pointer in either localPlayer or entity.

**Comment by Straightplus** [comment]
![error](https://user-images.githubusercontent.com/39915461/77010471-1fd93580-696a-11ea-87b6-5f70783d54e0.jpg)
also getting this

**Comment by Straightplus** [comment]
![image](https://user-images.githubusercontent.com/39915461/77010649-7777a100-696a-11ea-9556-bc3ed1642d4d.png)

**Comment by Straightplus** [comment]
can i find out where 0x78AA2B66 is?

**Comment by xAkiraMiura** [comment]
the game moves stuff around so you won't be able to find the assembly of it.
check the stack call, it will give you a hint to what crashed it.

**Comment by ClaudiuHKS** [comment]
You are not allowed to add changes here: https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hacks/Aimbot.cpp#L23

Anyways, if you did not touch that function, I suggest you to check if the player is valid before calling **isEnemy**. For example:

``ClientClass * pClClass { };``
``if ( pEntity && ( pClClass = pEntity->getClientClass ( ) ) && pClClass->classId == ClassId::CSPlayer && pEntity->isEnemy ( ) ) { /* your code */ };``
