### ISSUE TITLE
Command Delay

### ISSUE THREAD

**Issue by bekocango** [danielkrupinski/Osiris#1278]
How can i delay any script? I want to make this:
/// In Triggerbot.cpp

 if (damage >= (config.triggerbot[weaponIndex].killshot ? trace.entity->health() : config.triggerbot[weaponIndex].minDamage)) {
                cmd->buttons |= UserCmd::IN_ATTACK; //THIS IS DEFAULT
                std::string cmd = "use weapon_knife"; //I ADDED THIS
                interfaces.engine->clientCmdUnrestricted(cmd.c_str()); //I ADDED THIS
                             ///****/// I WANT DELAY HERE  ////****///
                std::string cmd = "slot1"; //I ADDED THIS
                interfaces.engine->clientCmdUnrestricted(cmd.c_str()); //I ADDED THIS
                lastTime = 0.0f;

This is basic switch command. But i want to make delay this.

**Comment by ClaudiuHKS** [comment]
``static float fActionExecutionTime = 0.0f;``

``... some code here ...``

``if ( memory.globalVars->currenttime - fActionExecutionTime > 0.25f )``
``{``
``  // 0.25 seconds (1/4 seconds) have passed, let's execute this stuff again``
``  ... your stuff here ...``
``  fActionExecutionTime = memory.globalVars->currenttime;``
``};``

``... some other code here ...``

**Comment by ClaudiuHKS** [comment]
I've no idea exactly what you want, maybe you need delayed tasks. Take a look here:

Put the following function, below **#include** stuff inside your **cpp** file:

``DWORD myTask(HANDLE pParameter)``
``{``
``Sleep(320 /* milliseconds delay */);``
``interfaces.engine->clientCmdUnrestricted("slot1"); /* not sure if it works called from a thread, you can test */``
``return EXIT_SUCCESS;``
``};``

Replace this block:

``////// I WANT DELAY HERE ///////``
``std::string cmd = "slot1"; //I ADDED THIS``
``interfaces.engine->clientCmdUnrestricted(cmd.c_str()); //I ADDED THIS``

With the following line of code:

``CreateThread({ }, { }, ((PTHREAD_START_ROUTINE) (myTask)), { }, { }, { });``

**Comment by bekocango** [comment]
> I've no idea exactly what you want, maybe you need delayed tasks. Take a look here:
> 
> Put the following function, below **#include** stuff inside your **cpp** file:
> 
> `DWORD myTask(HANDLE pParameter)`
> `{`
> `::Sleep(((DWORD) (320)) /* milliseconds delay */);`
> `if (interfaces.engine && interfaces.engine->isInGame() && interfaces.engine->isConnected())`
> `interfaces.engine->clientCmdUnrestricted("slot1"); /* not sure if it works called from a thread, you can test */`
> `return ((DWORD) (EXIT_SUCCESS));`
> `};`
> 
> Replace this block:
> 
> `////// I WANT DELAY HERE ///////`
> `std::string cmd = "slot1"; //I ADDED THIS`
> `interfaces.engine->clientCmdUnrestricted(cmd.c_str()); //I ADDED THIS`
> 
> With the following line of code:
> 
> `::CreateThread({ }, { }, ((PTHREAD_START_ROUTINE) (myTask)), { }, { }, { });`

You are the BEST. Thank you, it's worked. Thank you soo much.
