### ISSUE TITLE
A friendly fire check is missing @ Hacks/Aimbot.cpp

### ISSUE THREAD

**Issue by ClaudiuHKS** [danielkrupinski/Osiris#1279]
https://github.com/danielkrupinski/Osiris/blob/721061144446efe0a846162fadd2e31aab8a6fa2/Osiris/Hacks/Aimbot.cpp#L76

This can cause team damage.

**Comment by AbdallahMehiz** [comment]
happened to me once, if you were trying to shoot an enemy who is behind your friend the aimbot will just shoot through your friend causing team damage

**Comment by ClaudiuHKS** [comment]
I already have an undecided PR and I can't start another one, because I didn't create a separate branch for it. So here is the fix:

**1 Line Change**
---

``static bool canScan(Entity* localPlayer, Entity* entity, const Vector& destination, const WeaponData* weaponData, int minDamage) noexcept``

→

``static bool canScan(bool friendlyFire, Entity* localPlayer, Entity* entity, const Vector& destination, const WeaponData* weaponData, int minDamage) noexcept``

**1 Block Add** → _Above_ ``if (trace.fraction == 1.0f)``
---

``ClientClass* pHisClClass{ };``
``if (!friendlyFire && trace.entity && (pHisClClass = trace.entity->getClientClass()) && pHisClClass->classId == ClassId::CSPlayer && !trace.entity->isEnemy())``
``return false;``

**1 Line Change**
---

``if (!entity->isVisible(bonePosition) && (config.aimbot[weaponIndex].visibleOnly || !canScan(localPlayer, entity, bonePosition, activeWeapon->getWeaponData(), config.aimbot[weaponIndex].killshot ? entity->health() : config.aimbot[weaponIndex].minDamage)))``

→

``if (!entity->isVisible(bonePosition) && (config.aimbot[weaponIndex].visibleOnly || !canScan(config.aimbot[weaponIndex].friendlyFire, localPlayer, entity, bonePosition, activeWeapon->getWeaponData(), config.aimbot[weaponIndex].killshot ? entity->health() : config.aimbot[weaponIndex].minDamage)))``
