### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#1280]
It will make a circle or other shape whenever the enemies create a footstep sound

**Comment by littlehurensohn** [comment]
ez to paste, look at some source at github.

 ctrl+c - ctr+v != profit

**Comment by Zhxcky** [comment]
> ez to paste, look at some source at github.
> 
> ctrl+c - ctr+v != profit

unfortunately, got no basic coding skill.

**Comment by xAkiraMiura** [comment]
#1231 #1183 #766 #337
