### ISSUE TITLE
Question about misc settings

### ISSUE THREAD

**Issue by vsnrytune** [danielkrupinski/Osiris#1281]
What does fix movement, bone matrix, animation lod and tablet signal do?

**Comment by xAkiraMiura** [comment]
fix movement: makes the movement follow engine angles (what you see) rather than networked angles (what the server sees)

bone matrix: i think it makes skeleton ESP draw a bit cleaner

animation LOD: sets level of detail for animations

tablet signal: makes the tablet in dangerzone work even when underground (normally goes to static)

**Comment by vsnrytune** [comment]
> fix movement: makes the movement follow engine angles (what you see) rather than networked angles (what the server sees)
> 
> bone matrix: i think it makes skeleton ESP draw a bit cleaner
> 
> animation LOD: sets level of detail for animations
> 
> tablet signal: makes the tablet in dangerzone work even when underground (normally goes to static)

Any use for fix movement and animation lod in a legit config? And what max angle delta should I use if I'm not raging at all? Just wondering if it being set to max affects my legit config

**Comment by xAkiraMiura** [comment]
fix movement if you are using a silent aimbot
i haven't noticed animation LOD at all, might just be a performance thing.

if your not raging then the max angle delta shouldn't matter.

**Comment by streamshark** [comment]
check out the readme for information about most of the features, 
![image](https://user-images.githubusercontent.com/43255752/77162574-85f8b200-6a69-11ea-81f7-738c803fcaca.png)

**Comment by ClaudiuHKS** [comment]
@xAkiraMiura, I really took a deep look into the **Fix Movement** feature and I'm pretty sure it's only **Anti Aim** related.

``constexpr void fixMovement(UserCmd* cmd, float yaw) noexcept``

**cmd** is the actual (updated) **cmd** pointer, after all sub-hacks were executed (aim, trigger, .. edge jump ..) and **yaw** is the original **cmd->viewangles.y** value, before all sub-hacks are executed.

So, maybe it's **AimBOT** related as well, if the **FoV** value is like 30.0+, 60.0+, .. I don't know.

Anyways, in my opinion, you should only use **Fix Movement** if you have troubles throwing grenades or while moving [W A S D].
