### ISSUE TITLE
[REQUEST] Trigger Fake Shoots

### ISSUE THREAD

**Issue by bekocango** [danielkrupinski/Osiris#1282]
This triggerbot need fake shoots. Because it's not legit for me. Can you add?

**Comment by m0nsterJ** [comment]
What do you mean with "fake shoots" can you explain in detail please?

**Comment by CantRememberMyself** [comment]
i think he means overburst.

**Comment by bekocango** [comment]
> What do you mean with "fake shoots" can you explain in detail please?

When enemy dead. Trigger bot shoot one or two fake shoots.

**Comment by HowToMakeFaceitAB** [comment]
smart idea

**Comment by danielkrupinski** [comment]
Added in bd71054014f890d3c7c221c2d44e547f910a2fb0.
