### ISSUE TITLE
Random crashes on inject

### ISSUE THREAD

**Issue by effex1337** [danielkrupinski/Osiris#129]
I don't know to what extent this is true but osiris randomly crashes on inject on nvidia gpus.
The reason I'm saying it is i never crashed on My Home laptop. But it randomly crashes on some of my friends' pc with nvidia gpus. P.S. i don't have any gpu.
This is just my guess but i don't think cfg is the issue.

**Comment by danielkrupinski** [comment]
Do your friends' CPUs support AVX 2 instruction set?

**Comment by NexSqaud** [comment]
I have a nvidia video card and the game does not crash. CPU supports AVX (not AVX2)

**Comment by NexSqaud** [comment]
ok, new version is crashing on nvidia gpus

**Comment by NexSqaud** [comment]
access violation when reading at 0x00002FAA

**Comment by NexSqaud** [comment]
Exception thrown at 0x762A0C35 (ucrtbase.dll) in csgo.exe:
0xC0000005: Access violation reading location 0x00000018

EAX = 00000000
EDX = 00000018
EBX = 00000400
ESI = 00000000

**Comment by danielkrupinski** [comment]
@NexSqaud Exception is thrown in C RunTime library, it is not caused by Osiris, probably your injector's fault. Closing.

**Comment by NexSqaud** [comment]
But i tried inflame injector now,
