### ISSUE TITLE
getting errors

### ISSUE THREAD

**Issue by gamemaster32** [danielkrupinski/Osiris#1290]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2146	syntax error : missing ')' before identifier 'char8_t'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	31
Error	C2039	'starts_with': is not a member of 'std::basic_string_view<char,std::char_traits<char>>' (compiling source file Hacks\Backtrack.cpp)	Osiris	C : \Users\\Desktop\osiris\Osiris\SDK\StudioRender.h	32
Error	C4430	missing type specifier - int assumed.Note: C++ does not support default - int	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	31
Error	C2065	'char8_t': undeclared identifier	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	31
Error	C2059	syntax error : ')'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	31
Error	C3927	'->': trailing return type is not allowed after a non - function declarator	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	31
Error	C3484	syntax error : expected '->' before the return type	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	31
Error	C3613	missing return type after '->' ('int' assumed)	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	31
Error	C2146	syntax error : missing ';' before identifier 'good'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	31
Error	C2059	syntax error : 'else'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	33
Error	C2059	syntax error : 'for'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	36
Error	C2143	syntax error : missing ')' before ';'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	36
Error	C2143	syntax error : missing ';' before '<'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	36
Error	C4430	missing type specifier - int assumed.Note: C++ does not support default - int	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	36
Error	C2143	syntax error : missing ';' before '++'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	36
Error	C2086	'int i': redefinition	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	36
Error	C2059	syntax error : ')'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	36
Error	C2143	syntax error : missing ';' before '{'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	36
Error	C2447	'{': missing function header(old - style formal list ? )	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	36
Error	C2059	syntax error : 'for'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	63
Error	C2143	syntax error : missing ')' before ';'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	63
Error	C2143	syntax error : missing ';' before '<'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	63
Error	C4430	missing type specifier - int assumed.Note: C++ does not support default - int	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	63
Error	C2086	'int i': redefinition	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	63
Error	C2143	syntax error : missing ';' before '++'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	63
Error	C2059	syntax error : ')'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	63
Error	C2143	syntax error : missing ';' before '{'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	63
Error	C2447	'{': missing function header(old - style formal list ? )	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	63
Error	C2447	'{': missing function header(old - style formal list ? )	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	80
Error	C2447	'{': missing function header(old - style formal list ? )	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	88
Error	C2059	syntax error : 'for'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	96
Error	C2143	syntax error : missing ')' before ';'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	96
Error	C2143	syntax error : missing ';' before '<'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	96
Error	C4430	missing type specifier - int assumed.Note: C++ does not support default - int	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	96
Error	C2086	'int i': redefinition	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	96
Error	C2143	syntax error : missing ';' before '++'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	96
Error	C2059	syntax error : ')'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	96
Error	C2143	syntax error : missing ';' before '{'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	96
Error	C2447	'{': missing function header(old - style formal list ? )	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	96
Error	C2059	syntax error : 'for'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	120
Error	C2143	syntax error : missing ')' before ';'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	120
Error	C2143	syntax error : missing ';' before '<'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	120
Error	C4430	missing type specifier - int assumed.Note: C++ does not support default - int	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	120
Error	C2086	'int i': redefinition	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	120
Error	C2143	syntax error : missing ';' before '++'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	120
Error	C2059	syntax error : ')'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	120
Error	C2143	syntax error : missing ';' before '{'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	120
Error	C2447	'{': missing function header(old - style formal list ? )	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	120
Error	C2059	syntax error : 'for'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	150
Error	C2143	syntax error : missing ')' before ';'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	150
Error	C2143	syntax error : missing ';' before '<'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	150
Error	C4430	missing type specifier - int assumed.Note: C++ does not support default - int	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	150
Error	C2086	'int i': redefinition	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	150
Error	C2143	syntax error : missing ';' before '++'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	150
Error	C2059	syntax error : ')'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	150
Error	C2143	syntax error : missing ';' before '{'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	150
Error	C2447	'{': missing function header(old - style formal list ? )	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	150
Error	C2447	'{': missing function header(old - style formal list ? )	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	371
Error	C2059	syntax error : 'for'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	462
Error	C2143	syntax error : missing ')' before ';'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	462
Error	C2143	syntax error : missing ';' before '<'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	462
Error	C4430	missing type specifier - int assumed.Note: C++ does not support default - int	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	462
Error	C2086	'int i': redefinition	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	462
Error	C2143	syntax error : missing ';' before '++'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	462
Error	C2059	syntax error : ')'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	462
Error	C2143	syntax error : missing ';' before '{'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	462
Error	C2447	'{': missing function header(old - style formal list ? )	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	462
Error	C2059	syntax error : 'for'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	553
Error	C2143	syntax error : missing ')' before ';'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	553
Error	C2143	syntax error : missing ';' before '<'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	553
Error	C4430	missing type specifier - int assumed.Note: C++ does not support default - int	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	553
Error	C2086	'int i': redefinition	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	553
Error	C2143	syntax error : missing ';' before '++'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	553
Error	C2059	syntax error : ')'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	553
Error	C2143	syntax error : missing ';' before '{'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	553
Error	C2447	'{': missing function header(old - style formal list ? )	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	553
Error	C2447	'{': missing function header(old - style formal list ? )	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	643
Error	C2059	syntax error : 'for'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	720
Error	C2143	syntax error : missing ')' before ';'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	720
Error	C2143	syntax error : missing ';' before '<'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	720
Error	C4430	missing type specifier - int assumed.Note: C++ does not support default - int	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	720
Error	C2086	'int i': redefinition	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	720
Error	C2143	syntax error : missing ';' before '++'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	720
Error	C2059	syntax error : ')'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	720
Error	C2143	syntax error : missing ';' before '{'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	720
Error	C2447	'{': missing function header(old - style formal list ? )	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	720
Error	C2447	'{': missing function header(old - style formal list ? )	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	752
Error	C2447	'{': missing function header(old - style formal list ? )	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	771
Error	C2447	'{': missing function header(old - style formal list ? )	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	794
Error	C2447	'{': missing function header(old - style formal list ? )	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	895
Error	C2059	syntax error : '}'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	908
Error	C2143	syntax error : missing ';' before '}'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	908
Error	C2143	syntax error : missing ';' before '{'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	911
Error	C2447	'{': missing function header(old - style formal list ? )	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	911
Error	C4430	missing type specifier - int assumed.Note: C++ does not support default - int	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	1659
Error	C2146	syntax error : missing ')' before identifier 'char8_t'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	1659
Error	C2065	'char8_t': undeclared identifier	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	1659
Error	C2059	syntax error : ')'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	1659
Error	C4430	missing type specifier - int assumed.Note: C++ does not support default - int	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	1665
Error	C2146	syntax error : missing ')' before identifier 'char8_t'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	1665
Error	C2065	'char8_t': undeclared identifier	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	1665
Error	C2059	syntax error : ')'	Osiris	C : \Users\\Desktop\osiris\Osiris\Config.cpp	1665
Error	C2039	'starts_with': is not a member of 'std::basic_string_view<char,std::char_traits<char>>' (compiling source file Hacks\Chams.cpp)	Osiris	C : \Users\\Desktop\osiris\Osiris\SDK\StudioRender.h	32
Error	C2039	'starts_with': is not a member of 'std::basic_string_view<char,std::char_traits<char>>' (compiling source file Hooks.cpp)	Osiris	C : \Users\\Desktop\osiris\Osiris\SDK\StudioRender.h	32

----

please help

**Comment by xAkiraMiura** [comment]
you need build tools v142. download Visual Studio 2019.
if you modified the source then try a fresh clone with `git clone https://github.com/danielkrupinski/Osiris.git`

*i can see you obfuscated the logs.*

**Comment by RyDeem** [comment]
missing ')' before identifier 'char8_t' Osiris C : \Users\Desktop\osiris\Osiris\Config.cpp 31

**Comment by gamemaster32** [comment]
> you need build tools v142. download Visual Studio 2019.
> if you modified the source then try a fresh clone with `git clone https://github.com/danielkrupinski/Osiris.git`
> 
> _i can see you obfuscated the logs._

i used v142 and 10  sdk.  I just removed my name cuz it was my real name

**Comment by gamemaster32** [comment]
i also did not modify the source

**Comment by CerberusGame** [comment]
try v141

**Comment by danielkrupinski** [comment]
#1158
