### ISSUE TITLE
Getting errors please help

### ISSUE THREAD

**Issue by Bafmaaan** [danielkrupinski/Osiris#1291]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	 'char8_t': undeclared identifier	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	1659	
Warning	C28182	Dereferencing NULL pointer. 'window->RootWindowForNav' contains the same NULL value as 'parent_window' did. 	Osiris	C:\USERS\HONZA\DESKTOP\OSIRIS-MASTER\OSIRIS\IMGUI\IMGUI.CPP	5292	
Warning	C28182	Dereferencing NULL pointer. 'window' contains the same NULL value as 'g.NavWindow' did. 	Osiris	C:\USERS\HONZA\DESKTOP\OSIRIS-MASTER\OSIRIS\IMGUI\IMGUI.CPP	8498	
Warning	C26451	Arithmetic overflow: Using operator '-' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '-' to avoid overflow (io.2).	Osiris	C:\USERS\HONZA\DESKTOP\OSIRIS-MASTER\OSIRIS\IMGUI\IMGUI.CPP	9966	
Warning	C26495	Variable 'ImGuiSizeCallbackData::UserData' is uninitialized. Always initialize a member variable (type.6).	Osiris	C:\USERS\HONZA\DESKTOP\OSIRIS-MASTER\OSIRIS\IMGUI\imgui.h	1553	
Warning	C26495	Variable 'ImGuiColorMod::Col' is uninitialized. Always initialize a member variable (type.6).	Osiris	C:\USERS\HONZA\DESKTOP\OSIRIS-MASTER\OSIRIS\IMGUI\imgui_internal.h	708	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	31	
Error	C2146	 syntax error: missing ')' before identifier 'char8_t'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	31	
Error	C2065	 'char8_t': undeclared identifier	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	31	
Error	C2059	 syntax error: ')'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	31	
Error	C3927	 '->': trailing return type is not allowed after a non-function declarator	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	31	
Error	C3484	 syntax error: expected '->' before the return type	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	31	
Error	C3613	 missing return type after '->' ('int' assumed)	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	31	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	31	
Error	C2146	 syntax error: missing ';' before identifier 'good'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	31	
Error	C2059	 syntax error: ')'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	31	
Error	C2059	 syntax error: 'else'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	33	
Error	C2059	 syntax error: 'for'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	36	
Error	C2143	 syntax error: missing ')' before ';'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	36	
Error	C2065	 'aimbot': undeclared identifier	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	36	
Error	C2143	 syntax error: missing '>' before ';'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	36	
Error	C2909	 'i': explicit instantiation of function template requires return type	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	36	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	36	
Error	C7538	 'i' is not a variable template	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	36	
Error	C2143	 syntax error: missing ';' before '++'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	36	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	36	
Error	C2086	 'int i': redefinition	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	36	
Error	C2059	 syntax error: ')'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	36	
Error	C2143	 syntax error: missing ';' before '{'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	36	
Error	C2447	 '{': missing function header (old-style formal list?)	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	36	
Error	C2059	 syntax error: 'for'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	63	
Error	C2143	 syntax error: missing ')' before ';'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	63	
Error	C2143	 syntax error: missing ';' before '<'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	63	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	63	
Error	C2086	 'int i': redefinition	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	63	
Error	C2143	 syntax error: missing ';' before '++'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	63	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	63	
Error	C2086	 'int i': redefinition	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	63	
Error	C2059	 syntax error: ')'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	63	
Error	C2143	 syntax error: missing ';' before '{'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	63	
Error	C2447	 '{': missing function header (old-style formal list?)	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	63	
Error	C2447	 '{': missing function header (old-style formal list?)	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	80	
Error	C2447	 '{': missing function header (old-style formal list?)	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	88	
Error	C2059	 syntax error: 'for'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	96	
Error	C2143	 syntax error: missing ')' before ';'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	96	
Error	C2143	 syntax error: missing ';' before '<'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	96	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	96	
Error	C2086	 'int i': redefinition	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	96	
Error	C2143	 syntax error: missing ';' before '++'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	96	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	96	
Error	C2086	 'int i': redefinition	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	96	
Error	C2059	 syntax error: ')'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	96	
Error	C2143	 syntax error: missing ';' before '{'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	96	
Error	C2447	 '{': missing function header (old-style formal list?)	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	96	
Error	C2059	 syntax error: 'for'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	120	
Error	C2143	 syntax error: missing ')' before ';'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	120	
Error	C2143	 syntax error: missing ';' before '<'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	120	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	120	
Error	C2086	 'int i': redefinition	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	120	
Error	C2143	 syntax error: missing ';' before '++'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	120	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	120	
Error	C2086	 'int i': redefinition	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	120	
Error	C2059	 syntax error: ')'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	120	
Error	C2143	 syntax error: missing ';' before '{'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	120	
Error	C2447	 '{': missing function header (old-style formal list?)	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	120	
Error	C2059	 syntax error: 'for'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	150	
Error	C2143	 syntax error: missing ')' before ';'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	150	
Error	C2143	 syntax error: missing ';' before '<'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	150	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	150	
Error	C2086	 'int i': redefinition	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	150	
Error	C2143	 syntax error: missing ';' before '++'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	150	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	150	
Error	C2086	 'int i': redefinition	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	150	
Error	C2059	 syntax error: ')'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	150	
Error	C2143	 syntax error: missing ';' before '{'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	150	
Error	C2447	 '{': missing function header (old-style formal list?)	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	150	
Error	C2447	 '{': missing function header (old-style formal list?)	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	371	
Error	C2059	 syntax error: 'for'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	462	
Error	C2143	 syntax error: missing ')' before ';'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	462	
Error	C2143	 syntax error: missing ';' before '<'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	462	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	462	
Error	C2086	 'int i': redefinition	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	462	
Error	C2143	 syntax error: missing ';' before '++'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	462	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	462	
Error	C2086	 'int i': redefinition	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	462	
Error	C2059	 syntax error: ')'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	462	
Error	C2143	 syntax error: missing ';' before '{'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	462	
Error	C2447	 '{': missing function header (old-style formal list?)	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	462	
Error	C2059	 syntax error: 'for'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	553	
Error	C2143	 syntax error: missing ')' before ';'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	553	
Error	C2143	 syntax error: missing ';' before '<'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	553	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	553	
Error	C2086	 'int i': redefinition	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	553	
Error	C2143	 syntax error: missing ';' before '++'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	553	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	553	
Error	C2086	 'int i': redefinition	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	553	
Error	C2059	 syntax error: ')'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	553	
Error	C2143	 syntax error: missing ';' before '{'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	553	
Error	C2447	 '{': missing function header (old-style formal list?)	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	553	
Error	C2447	 '{': missing function header (old-style formal list?)	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	643	
Error	C2059	 syntax error: 'for'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	720	
Error	C2143	 syntax error: missing ')' before ';'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	720	
Error	C2143	 syntax error: missing ';' before '<'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	720	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	720	
Error	C2086	 'int i': redefinition	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	720	
Error	C2143	 syntax error: missing ';' before '++'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	720	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	720	
Error	C2086	 'int i': redefinition	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	720	
Error	C2059	 syntax error: ')'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	720	
Error	C2143	 syntax error: missing ';' before '{'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	720	
Error	C2447	 '{': missing function header (old-style formal list?)	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	720	
Error	C2447	 '{': missing function header (old-style formal list?)	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	752	
Error	C2447	 '{': missing function header (old-style formal list?)	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	771	
Error	C2447	 '{': missing function header (old-style formal list?)	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	794	
Error	C2447	 '{': missing function header (old-style formal list?)	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	895	
Error	C2059	 syntax error: '}'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	908	
Error	C2143	 syntax error: missing ';' before '}'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	908	
Error	C2143	 syntax error: missing ';' before '{'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	911	
Error	C2447	 '{': missing function header (old-style formal list?)	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	911	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	1659	
Error	C2146	 syntax error: missing ')' before identifier 'char8_t'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	1659	
Error	C2059	 syntax error: ')'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	1659	
Error	C2059	 syntax error: ')'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	1659	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	1665	
Error	C2146	 syntax error: missing ')' before identifier 'char8_t'	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	1665	
Error	C2065	 'char8_t': undeclared identifier	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	1665	
Error	C1003	 error count exceeds 100; stopping compilation	Osiris	C:\Users\Honza\Desktop\Osiris-master\Osiris\Config.cpp	1665

**Comment by danielkrupinski** [comment]
#1158
