### ISSUE TITLE
[REQUEST & QUESTION] pSilent Aimbot & VAC Bypass

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#1293]
Request : pSilent Aimbot
Question : Can't open the menu while using VAC Bypass (https://github.com/danielkrupinski/VAC-Bypass)

**Comment by AbdallahMehiz** [comment]
Use the [vac bypass loader ](https://github.com/danielkrupinski/VAC-Bypass-Loader) here.

**Comment by m0nsterJ** [comment]
You have to execute your Injector as Administrator, otherwise it won't work.

**Comment by ClaudiuHKS** [comment]
pSilent is RIP since 2015, LOL.

**Comment by Zhxcky** [comment]
> Use the [vac bypass loader ](https://github.com/danielkrupinski/VAC-Bypass-Loader) here.

yes i am using that bypass but still it wont load Osiris, i use As0nar Injector

**Comment by rosesware** [comment]
> yes i am using that bypass but still it wont load Osiris, i use As0nar Injector

Use a injector not this.
