### ISSUE TITLE
Wall Hack With Key Holding 

### ISSUE THREAD

**Issue by bekocango** [danielkrupinski/Osiris#1294]
How can i open wall hack while holding any key? Just holding, not press active or press deactive. Thanks...

**Comment by jimbob88** [comment]
Hey there @bekocango, if you want to make any function bound to a key press, it is pretty simple, if you are okay with editing the source code!
At the start of the method that would be called you put this:
```cpp
if (!GetAsyncKeyState(keyCode))
            return;
```
Substitute the key code with any of the codes from [here](https://docs.microsoft.com/en-gb/windows/win32/inputdev/virtual-key-codes), and replace the variable `keyCode` with the hexadecimal value! For example, if you want to bind to the ALT key, search for it on the table, and you'll see this:
![Screenshot of VK_MENU](https://user-images.githubusercontent.com/9913366/77539492-5eef1580-6e99-11ea-83b8-f84077d4fa60.png)
Then put `0x12` into the code:
```cpp
if (!GetAsyncKeyState(0x12))
            return;
```

## How does this work?
Simply using the `win32` module, it checks to see if that key is pressed, if it isn't it exits the method by returning a blank value!
I got it from line 40 of `Triggerbot.cpp`:
```cpp
if (config.triggerbot[weaponIndex].onKey && !GetAsyncKeyState(config.triggerbot[weaponIndex].key))
        return;
```

## For WallHacks
With wallhacks it very much depends which function you are using for it (i.e. chams or esp)! 

If you are confused as to how to get it to work, reply with your config so I can show which function needs to be changed!

Hope this helps,
Jim

**Comment by bekocango** [comment]
> Hey there @bekocango, if you want to make any function bound to a key press, it is pretty simple, if you are okay with editing the source code!
> At the start of the method that would be called you put this:
> 
> ```c++
> if (!GetAsyncKeyState(keyCode))
>             return;
> ```
> 
> Substitute the key code with any of the codes from [here](https://docs.microsoft.com/en-gb/windows/win32/inputdev/virtual-key-codes), and replace the variable `keyCode` with the hexadecimal value! For example, if you want to bind to the ALT key, search for it on the table, and you'll see this:
> ![Screenshot of VK_MENU](https://user-images.githubusercontent.com/9913366/77539492-5eef1580-6e99-11ea-83b8-f84077d4fa60.png)
> Then put `0x12` into the code:
> 
> ```c++
> if (!GetAsyncKeyState(0x12))
>             return;
> ```
> 
> ## How does this work?
> Simply using the `win32` module, it checks to see if that key is pressed, if it isn't it exits the method by returning a blank value!
> I got it from line 40 of `Triggerbot.cpp`:
> 
> ```c++
> if (config.triggerbot[weaponIndex].onKey && !GetAsyncKeyState(config.triggerbot[weaponIndex].key))
>         return;
> ```
> 
> ## For WallHacks
> With wallhacks it very much depends which function you are using for it (i.e. chams or esp)!
> 
> If you are confused as to how to get it to work, reply with your config so I can show which function needs to be changed!
> 
> Hope this helps,
> Jim

Wow man. Thank you very much. I will try this. ☺

**Comment by danielkrupinski** [comment]
Added
