### ISSUE TITLE
[Discussion] The ability to know what other team is voting

### ISSUE THREAD

**Issue by AbdallahMehiz** [danielkrupinski/Osiris#1295]
Last day i was in a comp game and found this guy, he typed in chat that the enemy team is calling a timeout and voting YES after a few seconds we recieved a timeout.
can this feature be implemented in osiris?
![20200321155329_1](https://user-images.githubusercontent.com/59295266/77245738-26dd9d80-6c21-11ea-996d-dc442ff40593.jpg)

**Comment by hyperxpro** [comment]
See #590
