### ISSUE TITLE
[Not an issue] Skeet chams in Osiris 

### ISSUE THREAD

**Issue by furioushell98** [danielkrupinski/Osiris#1296]
Hello. Is it possible to make Chams look like the blue one in the screenshot? If so what are the material/alpha settings that i should use to make it look like that? It's a bit confusing.. Or if someone could share a cfg with these chams i'd really appreciate it.
![bDK9aiu](https://user-images.githubusercontent.com/51128106/77246784-d1a68980-6c2a-11ea-83d1-a16469541aa6.png)

**Comment by effex1337** [comment]
Material one - normal, full black
Material two - glow, mess around with the color(hint : don't make it full blue)

**Comment by furioushell98** [comment]
> Material one - normal, full black
> Material two - glow, mess around with the color(hint : don't make it full blue)

Ty so much
