### ISSUE TITLE
[Issue] VS Not Creating Solution

### ISSUE THREAD

**Issue by DontEvenKnowk** [danielkrupinski/Osiris#1297]
I've been trying to create the solution for the dll, yet nothing works, I've installed all versions of SDK Toolset, the third time around and even gave VS adminstrator but I'll always get an Error D8027, Cannot Execute C:\....c1xx.dll
Any help?

**Comment by streamshark** [comment]
The source comes with a solution, Osiris.sln
![image](https://user-images.githubusercontent.com/43255752/77247347-70ac9080-6bed-11ea-970b-0c451c168282.png)

**Comment by DontEvenKnowk** [comment]
> When you have equiped a copy of source code, next step is opening Osiris.sln in Microsoft Visual Studio 2019.
> 
> Then change build configuration to Release | x86 and simply press Build solution.
> 
> If everything went right you should receive Osiris.dll binary file.

I've been following those instructions.

**Comment by SleekZ** [comment]
You can used my repo, I post Osiris's Dlls there.

**Comment by SleekZ** [comment]
https://github.com/SleekZ/Osiris-DLLs

**Comment by azzlak** [comment]
> https://github.com/SleekZ/Osiris-DLLs

Can you please send me a dll?

**Comment by SleekZ** [comment]
> > https://github.com/SleekZ/Osiris-DLLs
> 
> Can you please send me a dll?

I’m not going to keep updating it because he updates it pretty much every day.
