### ISSUE TITLE
[Request] Add a way to change the calling convention

### ISSUE THREAD

**Issue by GottaGetThat** [danielkrupinski/Osiris#1298]
https://github.com/danielkrupinski/Osiris/blob/0d20404fa77441377224824848fba412104846f3/Osiris/SDK/Utils.h#L9

Why is __thiscall forced here? This isn't ideal for people who want to expand the SDK and add more methods (Ex: ICvar->ConsoleColorPrintf, which uses __cdecl instead)

**Comment by xAkiraMiura** [comment]
ConColorMessage (what you referenced) is already in the cheat through the memory object.

also i dont think osiris really cares about calling conventions because all of the hooks are __stdcall.

**Comment by danielkrupinski** [comment]
Vast majority of virtual methods use __thiscall convention. Function you mentioned prolly uses __thiscall and __cdecl fused together, so it's tricky to call it. Currently there's no need for that, and I believe that the source shouldn't contain any superfluous code.
