### ISSUE TITLE
Rq:Change ESP Color while IsDefusing;isPlanting on active PlayerModel

### ISSUE THREAD

**Issue by DotNetFritz** [danielkrupinski/Osiris#13]
I will check if I can implement the IsDefsuing;IsPlanting Event on PlayerModel for you. So if the PlayerModel is doing one of this two Actions it changes the PlayerModel Cham to different color to check if someone fake the defuse or not.

**Comment by danielkrupinski** [comment]
Thanks for giving this idea. Feel free to open PR if you implemented these features.

**Comment by LuanDevecchi** [comment]
![image](https://user-images.githubusercontent.com/27377250/50447898-72fa3f00-0905-11e9-9088-84438330eb01.png)

Currently working on that, if you don't mind.
also, can't find isPlanting offset, glad if anyone can help.

**Comment by t9z** [comment]
> also, can't find isPlanting offset, glad if anyone can help.
Hey, there is an event called "bomb_beginplant" which will tell you when the bomb is being planted but you need to implement event logging in the cheat in order to use this event. There is also a netvar called "m_bStartedArming".

**Comment by 0xE232FE** [comment]
For the function is Planting you need to get the Active Weopon and if it is CC4 active then Player isPlantingC4.

**Comment by danielkrupinski** [comment]
Implemented.
