### ISSUE TITLE
Aimbot not working

### ISSUE THREAD

**Issue by ThiccTomato** [danielkrupinski/Osiris#1300]
Everything is working fine except the aimbot, which doesnt work at all.
Idk if im missing something but yeah. please help.

**Comment by danielkrupinski** [comment]
Enable and set fov > 0

**Comment by HowToMakeFaceitAB** [comment]
update your dll or just as daniel said set fov >0 otherwise it won't work

**Comment by ZiloGG** [comment]
> update your dll or just as daniel said set fov >0 otherwise it won't work

Hello, just a short question where do i update my dll?

**Comment by lnrsazscye** [comment]
me too, the aimbot doesnt work for me, where do i get a new version ?

**Comment by xAkiraMiura** [comment]
[rtfm](https://github.com/danielkrupinski/Osiris/blob/master/README.md)
