### ISSUE TITLE
Failed to find pattern

### ISSUE THREAD

**Issue by AmonKing** [danielkrupinski/Osiris#1301]
https://imgur.com/a/arTd9Il

**Comment by HowToMakeFaceitAB** [comment]
try googling the issue or recompiling the source

**Comment by danielkrupinski** [comment]
Verify that your GameOverlayRender.dll file in Steam directory isn't corrupted.

**Comment by Termisher** [comment]
i have same problem

**Comment by Termisher** [comment]
crash after fiew seconds of playing
