### ISSUE TITLE
Material

### ISSUE THREAD

**Issue by darkisgod444** [danielkrupinski/Osiris#1303]
![Screenshot_2020-03-23-12-46-11-882_com google android youtube](https://user-images.githubusercontent.com/61908493/77313563-65985400-6d04-11ea-9ff4-35f125b97291.png)
What is the enemy chams material??? It looks similar to the glow chams material in osiris but this one is much more glowing and looks cooler in my opinion

**Comment by whirlpool2** [comment]
the video is edited with a glow filter, you can see it on the scoreboard up top, it also glows

**Comment by PatrixCheats** [comment]
ok thx

**Comment by xAkiraMiura** [comment]
post processing affect, could possibly be applied real time but would hurt fps.

**Comment by xpossed-you** [comment]
.K.A.R.M.A. the worst clan ever
