### ISSUE TITLE
[Request] Sound ESP

### ISSUE THREAD

**Issue by Vakium** [danielkrupinski/Osiris#1305]
i loveeee sound ESP

**Comment by xAkiraMiura** [comment]
#1231 #1183 #766 #337

**Comment by HowToMakeFaceitAB** [comment]
wouldn't be better to just add it into the cheat? some people like to use wh but are too blatant with it. 
So it would be very smart to add sound esp as a way to use wh without knowing the enemys postion

**Comment by xAkiraMiura** [comment]
> without knowing the enemys postion

so subtitles?

the standard implementation is to make an expanding circle around where they steped. (which gives you their position)

**Comment by HowToMakeFaceitAB** [comment]
>  (which gives you their position)

**Comment by danielkrupinski** [comment]
I've added audibility checks to [my other project](https://github.com/danielkrupinski/GOESP/blob/4f310d66cbf47427e54c996229dac12cbe6bee70/GOESP/Hacks/ESP.cpp#L81-L87), maybe you'd like to check it out.
