### ISSUE TITLE
Osiris probably detected

### ISSUE THREAD

**Issue by vsnrytune** [danielkrupinski/Osiris#1306]
Haven't been vaced yet but I've been put into the lowest trust factor ever and it hasn't increased at all for two weeks. Nothing to do with my playstyle as I play very legit, rarely get called out or top frag and definitely don't grief with enemy team on auto-mute, so yeah. Probably got flagged for delayed vac ban.

**Comment by vsnrytune** [comment]
Every single match I get put against hvh and I just take the loss, surrender or leave so can't be because I play hvh myself. I even spent some money on the account which didn't help improve my trust at all either.

**Comment by hyperxpro** [comment]
Close the issue and delete the Steam account and get yourself infected with COVID-19 because your IQ level is just way too much to live on Earth.

**Comment by vsnrytune** [comment]
> Close the issue and delete the Steam account and get yourself infected with COVID-19 because your IQ level is just way too much to live on Earth.

Explain why am I put in low trust then along with other Osiris users when I don't do anything to be put into low trust? Einstein

**Comment by HugeSwantz** [comment]
> 
> 
> > Close the issue and delete the Steam account and get yourself infected with COVID-19 because your IQ level is just way too much to live on Earth.
> 
> Explain why am I put in low trust then along with other Osiris users when I don't do anything to be put into low trust? Einstein

just dont cheat simple

**Comment by notgoodusename** [comment]
the ammount of issues about this is, is impresive but people be like "omg i raged hack got ban no way osiris is detected", and low trustfactor doesnt mean anything with vac you get reported often then you will have a low trustfactor close this issue pls.
other issues like this:
#1264 #1261 #1251 #1246 #1238 #1139

**Comment by xAkiraMiura** [comment]
accounts are not as isolated as you think, getting banned on one will lower the trust of the others.
making or using alt accounts drops the trust factor of your network.

**Comment by steel4me** [comment]
even if he talks nonsense at some parts ... geez I'm bored with all this comments. delayed bans are nothing new. why should you please give some accounts that will be banned soon green trust factor again? 

would be more funny to put all cheating idiots in red trust factor till they get banned ;) it is nothing new that it was already possible to see the ban flag of accounts a few years ago, but I hope you are right akira. really. i hope im completly wrong.  too bad that you don't accept my $ 10 bet, come on, it's just fun...

so, i have nothing to loose, see if im hopefully wrong. this account should get banned near 14.04:
https://steamcommunity.com/profiles/76561198089658239

**Comment by HugeSwantz** [comment]
> 
> 
> accounts are not as isolated as you think, getting banned on one will lower the trust of the others.
> making or using alt accounts drops the trust factor of your network.

akira wdym i have more than 30 bant non prime accs yet my main remains untouched

**Comment by hyperxpro** [comment]
> accounts are not as isolated as you think, getting banned on one will lower the trust of the others.
> making or using alt accounts drops the trust factor of your network.

Nope, never. That's not how it works.

**Comment by ThAsviix24** [comment]
The **Injector** you use can be detected yes, only use trusted injector or even make one yourself

**Comment by vsnrytune** [comment]
> even if he talks nonsense at some parts ... geez I'm bored with all this comments. delayed bans are nothing new. why should you please give some accounts that will be banned soon green trust factor again?
> 
> would be more funny to put all cheating idiots in red trust factor till they get banned ;) it is nothing new that it was already possible to see the ban flag of accounts a few years ago, but I hope you are right akira. really. i hope im completly wrong. too bad that you don't accept my $ 10 bet, come on, it's just fun...
> 
> so, i have nothing to loose, see if im hopefully wrong. this account should get banned near 14.04.2020:
> https://steamcommunity.com/profiles/76561198089658239
> 
> > accounts are not as isolated as you think, getting banned on one will lower the trust of the others.
> > making or using alt accounts drops the trust factor of your network.
> 
> just deleting some reg keys, steam subfolders and cache fix this, after that just loose some MM's on that accounts and you are fine. you did it correct if steam asks for auth code for this accounts, like you got a new machine.

What nonsense did I talk about?

**Comment by vsnrytune** [comment]
> The **Injector** you use can be detected yes, only use trusted injector or even make one yourself

I use inflame with manual map injection

**Comment by steel4me** [comment]
> What nonsense did I talk about?

>Explain why am I put in low trust then along with other Osiris users when I don't do anything to be >put into low trust? Einstein

You are put along with other Cheaters, maybe not cheaters. **Bot surely not only Osiris ;)**

**Comment by vsnrytune** [comment]
> > What nonsense did I talk about?
> 
> > Explain why am I put in low trust then along with other Osiris users when I don't do anything to be >put into low trust? Einstein
> 
> You are put along with other cheaters, maybe not cheaters but other players with red trust. **But surely not only Osiris ;)**

That's not what I meant, I meant other Osiris users (specifically you) are also stuck in low trust

**Comment by steel4me** [comment]
Just give up, dont warn or inform others.
Close issue and dont use osiris. Wait till end of april.
I think we have other problems out there then red tf and vac.
Until then, some things will change and everyone will be more experienced than now.

**Comment by m0nsterJ** [comment]
@steel4me And, did it get banned? No, it didnt like we said lol.

**Comment by steel4me** [comment]
At least wait till tomorrow in cause of diffrent time zones. It is not GMT +1.
I can confirm 5 other accounts that was last played in jan / feb that stucked in red trust factor and got banned last days ;)

**Comment by m0nsterJ** [comment]
well all of my non primes are not banned with only Osiris injected.

**Comment by steel4me** [comment]
Can't remeber what you wrote. Maybe you are save in cause of VAC bypass. As i already told. It is strange. I injected on 10 accounts. It seems that not every account have this banflag, some of this account got green trust again where i played not much with osiris.
Other accounts with which I played a lot with osiris, for example 3 days in a row. 5 MMs per day, are flagged for ban. Maybe there is a VAC module that is not loaded / streamed every match. I can't explain what they do exactly but this ban flags exists and they hold you on red trust factor.
I already lost rank after 4 weeks. Lost 20 matches. Red TF still exist ;)

Wait till tomorrow and watch again.

**Comment by vsnrytune** [comment]
> Can't remeber what you wrote. Maybe you are save in cause of VAC bypass. As i already told. It is strange. I injected on 10 accounts or even more!? Maybe 15. It seems that not every account have this banflag, some of this accounts got green trust again, where i played not much with osiris.
> Other accounts where played a lot with osiris, for example 3 days in a row. 5 MMs per day, are flagged for ban. Maybe there is a VAC module that is not loaded / streamed every match. I can't explain what they do exactly but this ban flag exist and they hold you on red trust factor.
> I already lost rank after 4 weeks. Lost 20 matches. Red TF still exist ;)
> 
> Wait till tomorrow and watch again. I only played on prime accounts. Wasted a lot of money.
> At the moment im save cause i dont use osiris and i stay green. Playstyle and settings are the same, only other dll ;)

Since I posted this, I kept playing with Osiris perfectly fine and been getting green trust many times, except the problem is that it takes me like 5 wins to get green trust, but then it goes straight back to red within literally a single match, not even yellow, but eventually builds back up again

**Comment by steel4me** [comment]
nothing to say anymore. VAC happened like i said, i was never able to get green trust again with this account ;)

**Comment by notgoodusename** [comment]
> nothing to say anymore. VAC happened like i said, i was never able to get green trust again with this account ;)

idk bro, i always had green trust factor, what injector were you using?

**Comment by steel4me** [comment]
my own! the same that i use since over 10 years .... with my other dll i have no problems...some feature triggers detection, nevermind, i dont use osiris...believe me or not, something weird is going on

**Comment by notgoodusename** [comment]
> my own! the same that i use since over 10 years .... with my other dll i have no problems...some feature triggers detection, nevermind, i dont use osiris anymore...believe me or not, something weird is going on

from which base?

**Comment by steel4me** [comment]
lets see what happens, i release my base when i get vac again on my other accounts! just be careful please, the longest delay ban i can confirm was 16 weeks. really crazy. i know, it sounds weird

**Comment by pedermark** [comment]
> Haven't been vaced yet but I've been put into the lowest trust factor ever and it hasn't increased at all for two weeks. Nothing to do with my playstyle as I play very legit, rarely get called out or top frag and definitely don't grief with enemy team on auto-mute, so yeah. Probably got flagged for delayed vac ban.

You can get low trust favtor if you get many reports, play with friends that get many reports or if you played with people that got banned.

**Comment by pedermark** [comment]
> Haven't been vaced yet but I've been put into the lowest trust factor ever and it hasn't increased at all for two weeks. Nothing to do with my playstyle as I play very legit, rarely get called out or top frag and definitely don't grief with enemy team on auto-mute, so yeah. Probably got flagged for delayed vac ban.

It can also be that your injector is detected.

**Comment by m0nsterJ** [comment]
@steel4me Yes indeed it sounds weird that you get hit by the ban hammer. I didn't get banned while using a public injector and my custom version of Osiris. All of my steam accounts have never gotten vac banned while using Osiris.
