### ISSUE TITLE
Get closest entity to crosshair

### ISSUE THREAD

**Issue by notgoodusename** [danielkrupinski/Osiris#1307]
The title says it all, i thought about making it like the aimbot but i want to return the userid instead of the vector of the position of the bone

**Comment by xAkiraMiura** [comment]
pseudo code

    float delta = FLOAT_MAX;
    int best = 0;
    for i in 1 to 64 {
      ent e = GetEnt(i)
      float dist = abs(local->angle - e->angle)
      if (dist < delta) {
        delta = dist
        best = i;
      }
    }

then you can do anything with the best index.
add the usual checks like if they are invalid, the localplayer, dead, or dormant.

**Comment by notgoodusename** [comment]
that is for the distance from the localplayer pos, i need from the localplayer crosshair instead

**Comment by danielkrupinski** [comment]
At first you have to decide which point of player's body you want to calculate fov to. Then just modify aimbot code to fit your expectations.
