### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by darkisgod444** [danielkrupinski/Osiris#1308]
![PicsArt_03-23-09 02 03](https://user-images.githubusercontent.com/61908493/77358122-92bb2580-6d49-11ea-878b-2e869677dc59.jpg)
Can someone explain this error?? Also I have my own menu on osiris and added a lot of pull requests

**Comment by darkisgod444** [comment]
I just dont know how to fix, any help appreciated:)

**Comment by danielkrupinski** [comment]
Press "Opakovat" and it will show you that line in the source code. Probably you're calling ImVector::pop_back() on an empty vector.

**Comment by darkisgod444** [comment]
Ok thx

**Comment by xAkiraMiura** [comment]
on every windows machine since Vista there is a tool called "Snipping tool". it allows you to take screenshots instead of taking a picture of your monitor.

**Comment by RyDeem** [comment]
windows key > type "sni" > press enter

**Comment by darkisgod444** [comment]
I don't see huge issue that I didn't use the snipping tool. But you guys are cool trying to act smart
