### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by OliK69** [danielkrupinski/Osiris#131]
I was using it for some time, but after latest update after compiling and injecting to csgo, my game is not responding for ~30s and then after pressing insert nothing happens. Before I used vs 2017 to compile, now I'm using vs 2019, saying just for sure.

**Comment by danielkrupinski** [comment]
Does your CPU support AVX 2 instruction set?

**Comment by OliK69** [comment]
How I can check it?

**Comment by danielkrupinski** [comment]
Use [CPU-Z](https://www.cpuid.com/softwares/cpu-z.html)

**Comment by OliK69** [comment]
So thats the problem?
![image](https://user-images.githubusercontent.com/49819490/56461136-0cb29400-63ae-11e9-9f4a-3a9849f9dbdf.png)

**Comment by danielkrupinski** [comment]
Yes, go to `Properties -> C/C++ -> Code Generation -> Enable Enhanced Instruction Set` and set this to AVX or SSE2.

**Comment by OliK69** [comment]
Thank you so much! Everything is fine now
