### ISSUE TITLE
I need help with adding new stuff

### ISSUE THREAD

**Issue by unnamed01X** [danielkrupinski/Osiris#1310]
Hey, i would like to include the "**fake unbox**" into my osiris source.
Yeah, i know that there's the same issue there: https://github.com/danielkrupinski/Osiris/issues/512 ,
but i have a problem with adding that. i tried it meny times to make it working.
Still doesnt works. could someone help me or make a tutorial?
thank you in advance.

I also want to include some stuff from "**lua script**" into my osiris source. I got some but the lua is new for me, and also i don't know how to code the same thing into **c ++**, but it's not importent for now, i mean if someone would like to help me out, pls give me your Discord contact below. 
But at first, i would like to make my "**fake unbox**" working.
**Thanks**

**Comment by unnamed01X** [comment]
bump

**Comment by unnamed01X** [comment]
bump

**Comment by DoomFishWasTaken** [comment]
#1483 close this issue I made a pull
