### ISSUE TITLE
Add nade helper

### ISSUE THREAD

**Issue by sammy6369** [danielkrupinski/Osiris#1311]
I suggest adding nade helper, just like ratpoison.
It'd be so much better, thank you!

**Comment by xAkiraMiura** [comment]
osiris already has grenade prediction.
if you ment hard coded locations rather than grenade prediction it's not going to happen.

**Comment by HowToMakeFaceitAB** [comment]
> osiris already has grenade prediction.
> if you ment hard coded locations rather than grenade prediction it's not going to happen.

isn't it hard to add hard coded locations?

**Comment by sammy6369** [comment]
Well, I don't mean hard-coded locations. The locations can be managed by users/cfg.
I just thought Ratpoison is open source so it could cope. Nevermind.
