### ISSUE TITLE
willing to pay for someone to add skeet menu for me

### ISSUE THREAD

**Issue by zc-xc** [danielkrupinski/Osiris#1314]
Hello Github, i have been using osiris for a bit now and found this cool skeet menu on unknowncheats for imgui, but idk how to use it tbh :( so i made account here to ask if anyone would be willing to add it for me, it doesn't have to be perfect or even have to have the features on it, just aslong as it works and does not crash!!!

edit: all i ask is for menu to work and not crash, dont add features.

will pay $10 - $15 paypal, but you must do it for me first, then show that u have done it, then i'll pay, then you send 😄 
edit #2: discord: zcxc#2772

**Comment by whirlpool2** [comment]
same
