### ISSUE TITLE
Jumpbug (again!)

### ISSUE THREAD

**Issue by streamshark** [danielkrupinski/Osiris#1318]
Was working on trying to finally get jumpbug working in Osiris last night, unsuccessfully, but came up with this:
```C++
void Misc::jumpbug(UserCmd* cmd) noexcept
{
    if (!config.misc.jumpbug || !GetAsyncKeyState(config.misc.jumpbugkey))
        return;

    const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());

    if (!localPlayer || !localPlayer->isAlive())
        return;


    auto start = localPlayer->origin();
    auto end = start;
    end.z -= config.misc.jumpBugHeight; //should be 4 ?? ??

    Trace trace;
    interfaces.engineTrace->traceRay({start, end }, 0x1400B, localPlayer, trace);

    if (trace.fraction != 1.0f || (localPlayer->flags() & 1)) {

        if (EnginePrediction::getFlags() & 1) //bhop on land, not sure if needed
        {
            cmd->buttons |= UserCmd::IN_JUMP;
        }
        cmd->buttons &= ~UserCmd::IN_DUCK; 
        cmd->buttons |= UserCmd::IN_ATTACK; //debug to know when triggered
    }
    else
    {
        cmd->buttons |= UserCmd::IN_DUCK;
    }

}
```

In all my testing I don't think I got a single jumpbug to occur....
I was running this after engine prediction like edgejump, and jumpBugHeight was bound to an integer slider I used to play around with different heights. I'm sure what I have could be simplified a lot once I know what I'm doing wrong but I modified it a million times trying to fix it. Anyone know why this might not work?

**Comment by Vonr** [comment]
you a tracing a single ray to the ground instead of the player's hitbox

**Comment by Vonr** [comment]
you can check what i did [here](https://github.com/danielkrupinski/Osiris/pull/1178) but it only works once in a while

**Comment by streamshark** [comment]
tracing hitbox (hull trace) is an improvement for uneven ground, single ray should at least work on flat areas

**Comment by notgoodusename** [comment]
try getabsorigin instead of origin

**Comment by xAkiraMiura** [comment]
you do realize you can attach a debugger, right? breaks points are indeed a thing to see if code ran.
even if you didn't have vs2019's debugger there is a function in memory called DebugMsg to log to the ingame console.

**Comment by streamshark** [comment]
yeah I could have but I threw it in just to see quickly if I was hitting ground properly and not local player etc as a sanity check

**Comment by streamshark** [comment]
> try getabsorigin instead of origin

I'll try this next, I was using origin because it goes to vecOrigin in Osiris which is what the jumpbug source I was basing mine off of used

**Comment by littlehurensohn** [comment]
if (trace.fraction != 1.0f || (localPlayer->flags() & 1)) {

This is absolutely bad, i actually got works jumpbug, try to learn how it must works.

**Comment by littlehurensohn** [comment]
useless 

if (EnginePrediction::getFlags() & 1) //bhop on land, not sure if needed
        {
            cmd->buttons |= UserCmd::IN_JUMP;
        }

**Comment by littlehurensohn** [comment]
else
    {
        cmd->buttons |= UserCmd::IN_DUCK;
    }

doesnt give sense

**Comment by streamshark** [comment]
> if (trace.fraction != 1.0f || (localPlayer->flags() & 1)) {
> 
> This is absolutely bad, i actually got works jumpbug, try to learn how it must works.

hmm, I know the onground flag check could probably be removed but I didn't want to remain crouched after jumpbugging. guessing you don't mean the trace because all that is is checking if we hit the ground



> useless
> 
> if (EnginePrediction::getFlags() & 1) //bhop on land, not sure if needed
> {
> cmd->buttons |= UserCmd::IN_JUMP;
> }

yeah, I left a comment here because all the vids of jumpbug I found showed a bhop on landing so I threw it in to check if that was my mistake when it wasn't working



> else
> {
> cmd->buttons |= UserCmd::IN_DUCK;
> }
> 
> doesnt give sense

added to automatically crouch if holding the key midair so you dont have to hit crouch + JB key at same time for convenience, not necessary but nice I think

**Comment by streamshark** [comment]
if you could be more specific about what is wrong or post what your code that would be helpful. also today I tried running outside of engine prediction with the ghetto start += vel*ticks extrapolation meme thing and actually got successful jumpbugs on flat ground with 6 unit trace, was inconsistent when dropping from a height. I don't understand why engine prediction isn't cooperating

**Comment by Vonr** [comment]
isnt engine prediction predicting one tick ahead? in which case you would want to execute jump bug when fraction is 1.0f?

**Comment by Vonr** [comment]
or maybe `fraction != 0.0f` but not `fraction != 1.0f`

**Comment by Vonr** [comment]
also @littlehurensohn if you got it to work why not share?

**Comment by streamshark** [comment]
I was basing the fraction thing off of https://developer.valvesoftware.com/wiki/UTIL_TraceLine

"fraction: How far the trace went before hitting something. 0-1, 1.0 means it didn't hit anything."
so checking != 1.0 means we did hit something. not sure about engine pred being 1 tick ahead

**Comment by Vonr** [comment]
thanks for that link. id assume that you'd keep crouched when frac == 1 then uncrouch when frac != 1 but keep in mind the hitbox change when crouching and uncrouching

**Comment by daisuki333** [comment]
any luck with this working, or any other updated code perhaps?
