### ISSUE TITLE
Error trying to build

### ISSUE THREAD

**Issue by tacticalNukes** [danielkrupinski/Osiris#1319]
I get a 600+ errors  in the project, I am using Visual studio 2019 I have done everything said like release and x86 but still don't understand why I am getting a bunch of errors?

I get a bunch of errors like cannot open source file, cannot include file, expected a ''. etc...

**Comment by KernCS** [comment]
give a ss of your errors

**Comment by tacticalNukes** [comment]
I managed to remove a bunch but still get these:
![image](https://user-images.githubusercontent.com/49035285/77570862-b5c21280-6ecc-11ea-9be6-2feae72b1810.png)

**Comment by danielkrupinski** [comment]
Your Visual Studio or Windows SDK installation is broken.

**Comment by tacticalNukes** [comment]
I just updated Visual studio and my SDK 10.0

**Comment by danielkrupinski** [comment]
Maybe select "Repair" in your Visual Studio Installer app.

**Comment by danielkrupinski** [comment]
Or maybe this can help you https://stackoverflow.com/questions/42777424/visual-studio-2017-errors-on-standard-headers

**Comment by tacticalNukes** [comment]
I tried all of that and nothing worked idk my exact SDK is just 10.0 and I notice a lot of people have 10.0.17134.0 or something like that is that something I need or?

**Comment by tacticalNukes** [comment]
okay now it's fine.
I downloaded version: SDK 10.0.17134.12
https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/
If someone else needs it
