### ISSUE TITLE
Drag menu when open again gui

### ISSUE THREAD

**Issue by Hongarc** [danielkrupinski/Osiris#132]
- Open menu
- Drag one menu (without  release left mouse)
- Press insert
- Press insert again, and it will drag my menu (same that I hold left mouse)

I think it should send event release left mouse when I turn off gui.

**Comment by danielkrupinski** [comment]
Should be fixed now -  36285da7e286d639eadbc21eea9eb77a72aabf50

**Comment by Hongarc** [comment]
@danielkrupinski Thank you for the quick fix
