### ISSUE TITLE
Make thirdperson display cmd->viewangles

### ISSUE THREAD

**Issue by DoomFishWasTaken** [danielkrupinski/Osiris#1322]
Make thirdperson display cmd->viewangles, instead of local eye angle

**Comment by xAkiraMiura** [comment]
when the local player is called in DME just override pInfo. ModelRenderInfo_t (using Source SDK's naming) contains the viewangle.

**Comment by notgoodusename** [comment]
> when the local player is called in DME just override pInfo. ModelRenderInfo_t (using Source SDK's naming) contains the viewangle.

did it work?

**Comment by DoomFishWasTaken** [comment]
nope got no idea how to implement the ModelRenderInfo_t, tried to implement this to DME but no luck
`*(Vector*)((uintptr_t)localPlayer + 0x31D8) = cmd->viewangles;`
^^^^ code that works in other sources

**Comment by notgoodusename** [comment]
> nope got no idea how to implement the ModelRenderInfo_t, tried to implement this to DME but no luck
> `*(Vector*)((uintptr_t)localPlayer + 0x31D8) = cmd->viewangles;`
> ^^^^ code that works in other sources

i do that but on thirdperson and on fra render start with the angles i sent on sendpacket

**Comment by DoomFishWasTaken** [comment]
> > nope got no idea how to implement the ModelRenderInfo_t, tried to implement this to DME but no luck
> > `*(Vector*)((uintptr_t)localPlayer + 0x31D8) = cmd->viewangles;`
> > ^^^^ code that works in other sources
> 
> i do that but on thirdperson and on fra render start with the angles i sent on sendpacket

are you willing to share code?

**Comment by notgoodusename** [comment]
> > > nope got no idea how to implement the ModelRenderInfo_t, tried to implement this to DME but no luck
> > > `*(Vector*)((uintptr_t)localPlayer + 0x31D8) = cmd->viewangles;`
> > > ^^^^ code that works in other sources
> > 
> > 
> > i do that but on thirdperson and on fra render start with the angles i sent on sendpacket
> 
> are you willing to share code? as mine just crashes my game immediately when joining a match

is literally the same code

**Comment by DoomFishWasTaken** [comment]
i mean where do i put it ive tried both thirdperson() and drawModelExecute()

**Comment by xAkiraMiura** [comment]
why are you guys doing that ugly offset pointer stuff when we [literally have structs](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/SDK/ModelRender.h#L13-L24)?

    info.angles = cmd->viewangles;

In [DrawModelExecute](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hooks.cpp#L202-L214)

info is a reference to ModelRenderInfo so you may need to use the override operator `->` (i haven't checked in VS)

**Comment by notgoodusename** [comment]
> why are you guys doing that ugly offset pointer stuff when we [literally have structs](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/SDK/ModelRender.h#L13-L24)?
> 
> ```
> info.angles = cmd->viewangles;
> ```
> 
> In [DrawModelExecute](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hooks.cpp#L202-L214)
> 
> info is a reference to ModelRenderInfo so you may need to use the override operator `->` (i haven't checked in VS)

ModelRenderInfo is constant meaning everything inside the class is constant, so u cant change the angle due to cmd->viewangle being not constant and info.angles being constant

**Comment by xAkiraMiura** [comment]
make a non-const copy of it and pass it into the original function?

**Comment by DoomFishWasTaken** [comment]
@xAkiraMiura tried to change 
`static void __stdcall drawModelExecute(void* ctx, void* state, const ModelRenderInfo& info, matrix3x4* customBoneToWorld) noexcept`
to 
`static void __stdcall drawModelExecute(void* ctx, void* state, ModelRenderInfo& info, matrix3x4* customBoneToWorld) noexcept` and adding
`    const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());

    if (memory->input->isCameraInThirdPerson == true && localPlayer && localPlayer->isAlive())
        info.angles = cmd->viewangles;`
crashes game when going into thirdperson

**Comment by xAkiraMiura** [comment]
changing function definitions is not what i ment.
also doing `== true` is redundant.
you never checked if the player was ingame before checking the camera position or if alive. (although DME doesn't seem to be called when not ingame)
`cmd->viewangles` is only available inside of CreateMove, how did you get it from inside of DrawModelExecute.

i ment make a copy of info to a non const copy and then modifying the copy and passing it to ofunc.

**Comment by DoomFishWasTaken** [comment]
@xAkiraMiura defining it by adding `UserCmd* cmd` at the start of Hooks.cpp

**Comment by DoomFishWasTaken** [comment]
got it to work #1546
