### ISSUE TITLE
Osiris Manualmapping Crashing CSGO

### ISSUE THREAD

**Issue by DoctorYasin** [danielkrupinski/Osiris#1324]
Osiris Manualmapping Crashing CSGO,
LoadLibrary Working.
ManualMapping Crash CSGO.

Can You Help ?

**Comment by danielkrupinski** [comment]
Maybe your injector is doing something wrong or you're manual mapping debug dll.

**Comment by DoctorYasin** [comment]
ManualMap
>Types
>>ManagedPtr.cs =  https://hastebin.com/axeripubip.cpp
>Win32
>>Definitions.cs =  https://hastebin.com/busotawete.cs
>>Imports.cs =  https://hastebin.com/upedisoxux.cs
>> pDefinitions.cs =  https://hastebin.com/zepesalegi.nginx
>Helpers.cs =  https://hastebin.com/ehuvibipom.cs
>ManualmapInjector.cs =  https://hastebin.com/ubodopezag.cs

Bro Other Cheats No Problem Only Osiris Injecting After CSGO Closing.
Osiris Not Supporting ManualMap Please Fix.

**Comment by DoctorYasin** [comment]
i need help.

**Comment by AMATEURZ1337** [comment]
I reported this problem long time ago. but, it's closed with reason "there's nothing to fix"

**Comment by DoctorYasin** [comment]
may not have seen. @AMATEURZ1337

**Comment by DoctorYasin** [comment]
I asked my friends osiris does not support. they said use another source. but I think this problem can be easily overcome.

**Comment by danielkrupinski** [comment]
Strangle enough I use manual mapping injector all time without any problem.

**Comment by DoctorYasin** [comment]
Why does it cause problems when injecting manualmap?
@danielkrupinski Can you share the manualmap file you use?

**Comment by danielkrupinski** [comment]
https://github.com/danielkrupinski/Inflame

**Comment by DoctorYasin** [comment]
what could be the problem in my loader?

**Comment by DoctorYasin** [comment]
The game closes when osiris converts bytes. Can't find a solution to this? @danielkrupinski
