### ISSUE TITLE
Custom model

### ISSUE THREAD

**Issue by xpossed-you** [danielkrupinski/Osiris#1328]
is there anyway to add Community server custom models to Osiris so we can use it on CSGO MM?

**Comment by effex1337** [comment]
Nice add +rep

**Comment by xpossed-you** [comment]
> 
> 
> Nice add +rep

sorry, im just asking if thats possible,

**Comment by effex1337** [comment]
It's pretty much already there,  you just need to modify stuff a bit and use some brain juice. There are tons of atuff on uc.
(it's just around 20 lines to add if you actually read whats goin on and shit)
Good luck!

**Comment by xAkiraMiura** [comment]
if you decide to implement it yourself use PrecacheModel instead of FindMDL. FindMDL requires you to reload the map.

**Comment by xpossed-you** [comment]
thanks guys for responding
