### ISSUE TITLE
[QUESTION] how to change healthesp position ingame

### ISSUE THREAD

**Issue by mattys0229** [danielkrupinski/Osiris#1329]
Hello,

I'm asking if it's possible to change the healthesp position both in the X axis and the Y axis.
I was able to change the X axis in game by typing this

renderPositionedText(209, (std::to_wstring(entity->health()) + L" HP").c_str(), { bbox.x1 + config.hpposx , drawPositionY });

in Misc.cpp, you can find it by searching "config.health.enabled"

I tried doing the same by writing drawPositionY + config.hpposy but it gave me errors.

More info:
            float hpposx{ 0.0f };
            float hpposy{ 0.0f };
in Config.h under "float maxDistance"

and
            ImGui::SliderFloat("hp esp pos x", &config.esp.players[selected].hpposx, -100.0f, 100.0f, "%.2f Hp pos X");
            ImGui::SliderFloat("hp esp pos y", &config.esp.players[selected].hpposy, -100.0, 100.0f, "%.2f Hp pos Y");
in GUI.cpp, you can find it by searching "void GUI::renderEspWindow"

if anyone finds the solution, thanks a lot!

**Comment by BloodXPride** [comment]
Inside renderPlayerBox in ESP.cpp:

replace this:

renderPositionedText(config.font, (std::to_wstring(entity->health()) + L" HP").c_str(), { bbox.x1 + 5, drawPositionY });


with this:

 const auto [width, height] { interfaces->surface->getTextSize(config.font, (std::to_wstring(entity->health()) + L" HP").c_str()) };
            float drawPositionYy = bbox.y1 - 5 + height;
            renderPositionedText(config.font, (std::to_wstring(entity->health()) + L" HP").c_str(), { (bbox.x0 + bbox.x1 - width) / 2, drawPositionYy });


health value is now below the character

**Comment by mattys0229** [comment]
thanks
