### ISSUE TITLE
I can't inject dll

### ISSUE THREAD

**Issue by ek4yle** [danielkrupinski/Osiris#133]
Using GH injector with default setting i cant inject, using xenos with default setting i cant inject too
but using GH injector with manual map csgo crashes

**Comment by Hongarc** [comment]
Are you try using [`Simple dll Injector`](https://sourceforge.net/projects/simple-dll-injector/)?

**Comment by bastquu** [comment]
it doesn't work for me either:( I've tried all the injectors

**Comment by NexSqaud** [comment]
i use [Extreme Injector v3.7.3](https://www.unknowncheats.me/forum/general-programming-and-reversing/213038-extreme-injector-v3-7-a.html) with [this](http://prntscr.com/nf3x6c) settings. 
Try to delete old config file > Documents/Osiris

**Comment by Hongarc** [comment]
Are you turn on FaceIt AC or others AC?

**Comment by danielkrupinski** [comment]
Try solution posted in #131

**Comment by bastquu** [comment]
it doesn't work :(

**Comment by ek4yle** [comment]
![image](https://user-images.githubusercontent.com/49836082/56495541-857d3180-650f-11e9-97f8-28936a46ba6f.png)


> Try solution posted in #131

nothing changer

**Comment by ek4yle** [comment]
it's not osiris' problem, cuz i cant inject any dll

**Comment by bastquu** [comment]
I'm sorry, it's all working out, thank you.
