### ISSUE TITLE
Look at this INSANE DOUBLETAP!11!!

### ISSUE THREAD

**Issue by notgoodusename** [danielkrupinski/Osiris#1330]
i am in the current process of making a doubletap but look what i got is hilarious and the title is sarcasm
https://streamable.com/byjob

**Comment by xAkiraMiura** [comment]
client side desync, i haven't looked into doubletap nor tick shifting so i don't know whats going on exactly. are you replaying ticks?

**Comment by notgoodusename** [comment]
> client side desync, i haven't looked into doubletap nor tick shifting so i don't know whats going on exactly. are you replaying ticks?

no, im adding fake user cmds and i did something out of curiosity and this happend

**Comment by CantRememberMyself** [comment]
you do be hittin p doe

**Comment by rosesware** [comment]
Sick, I mean do you can do that on servers? Weird.

**Comment by xpossed-you** [comment]
rapid fire?

**Comment by xAkiraMiura** [comment]
> 
> 
> Sick, I mean, you can do that on servers? Weird.

no. most of that is client side only. when his viewangle suffers recoil/his ammo goes down is when the server actually shots.
