### ISSUE TITLE
Walkbot 

### ISSUE THREAD

**Issue by crocogab** [danielkrupinski/Osiris#1331]
Would it be possible to create a walk bot?
Thank you for your response

**Comment by xAkiraMiura** [comment]
+forward; +right; </s>

make a NAV parser and then just use a pathfinding algorithm.

**Comment by crocogab** [comment]
With what tool would it be possible to do this ?
Sorry i'm a n00b in programming

**Comment by xAkiraMiura** [comment]
there exists a NAV parser on UC that you can paste or try reversing the Source SDK from 2013.

**Comment by crocogab** [comment]
Thanks bro
