### ISSUE TITLE
How to check inScoped 1  2 ?

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#1332]
im trying to make noZoom
#866 

but i want to make it like onetap 

i mean when

if (1st scoped)
FOV=90

if(2nd scoped)
FOV=40

**Comment by effex1337** [comment]
Active weapon -> m_zoomLevel

**Comment by dapaster** [comment]
i add this

        NETVAR(zoomLevel, "CBaseCombatWeapon", "m_zoomLevel", int)

and this

          if (activeWeapon->zoomLevel() == 1)
           {
           localPlayer->fov() = 90 + config->visuals.fov;
           localPlayer->fovStart() = 90 + config->visuals.fov;
           }
    
          else if (activeWeapon->zoomLevel() == 2)
           {
           localPlayer->fov() = 40 + config->visuals.fov;
           localPlayer->fovStart() = 40 + config->visuals.fov;
           }

but nothing happen @effex1337

**Comment by effex1337** [comment]
I think it's just cbase weapon

**Comment by dapaster** [comment]
still not working

**Comment by effex1337** [comment]
Then just use a hardcoded offset from an offset dump.

**Comment by xAkiraMiura** [comment]
DT_WeaponCSBaseGun
        m_zoomLevel                                   : 0x000033C0
        m_iBurstShotsRemaining                        : 0x000033C4

all netvar tables start with DT? why are you putting a classname into it?

**Comment by dapaster** [comment]
> 
> 
> ```
> DT_WeaponCSBaseGun
>     m_zoomLevel                                   : 0x000033C0
>     m_iBurstShotsRemaining                        : 0x000033C4
> ```
> 
> all netvar tables start with DT? why are you putting a classname into it?

what do you mean?

**Comment by xAkiraMiura** [comment]
> > ~
>
> what do you mean?

nvm, osiris uses a custom netvar manager.

**Comment by effex1337** [comment]
NETVAR(zoomLevel, "CWeaponCSBaseGun", "m_zoomLevel", int)
Try this and print the output

**Comment by dapaster** [comment]
Thanks! its working! @effex1337

**Comment by dapaster** [comment]
one problem.

when i load the cfg with this setting turn on the game will crash.

but the feature is working perfectly .

    NETVAR(zoomLevel, "CWeaponCSBaseGun", "m_zoomLevel", int)

___
    void Visuals::noZoom() noexcept
    {
        if (config->visuals.noZoom) 
        {
            auto localPlayer = interfaces->entityList->getEntity(interfaces->engine->getLocalPlayer());
            auto activeWeapon = localPlayer->getActiveWeapon();

            if (activeWeapon->zoomLevel() == 1)
            {
                localPlayer->fov() = 90 + config->visuals.fov;
                localPlayer->fovStart() = 90 + config->visuals.fov;
            }
            else if (activeWeapon->zoomLevel() == 2)
            {
                localPlayer->fov() = 40 + config->visuals.fov;
                localPlayer->fovStart() = 40 + config->visuals.fov;
            }

        }

    }

**Comment by dapaster** [comment]
Debug

![image](https://user-images.githubusercontent.com/60472098/77864370-ba831f80-725a-11ea-90da-6f28b6749fb4.png)

**Comment by dapaster** [comment]
Problem solved. 

the problem is Hooks.cpp
