### ISSUE TITLE
Config not working?

### ISSUE THREAD

**Issue by tacticalNukes** [danielkrupinski/Osiris#1334]
How do I add no recoil to my config? I can't find or get it to work

**Comment by danielkrupinski** [comment]
If you use high aimbot fov and no smoothing, it will act like "no recoil".

**Comment by CKH0** [comment]
no recoil work with aimbot only

**Comment by tacticalNukes** [comment]
oh alright thanks, btw my config isn't working. when I load my new config it's saved like the last one I had on
