### ISSUE TITLE
When I Enable Gloves...

### ISSUE THREAD

**Issue by bekocango** [danielkrupinski/Osiris#1336]
Is This Bug??
![Ekran Görüntüsü (51)](https://user-images.githubusercontent.com/62030537/77824532-7ab22000-7114-11ea-8206-954bb3574a80.png)

**Comment by designer1337** [comment]
shiny boi

**Comment by effex1337** [comment]
Looks like saitama ngl

**Comment by danielkrupinski** [comment]
I think CS:GO devs broke something in the latest shader update.

**Comment by Zhxcky** [comment]
solar power

**Comment by xpossed-you** [comment]
bald too smooth the sun light start focusing into his head

**Comment by rosesware** [comment]
A brilliant bald.

**Comment by danielkrupinski** [comment]
Should be fixed now.

**Comment by yxb6846928** [comment]
How to solve this problem？
@danielkrupinski
