### ISSUE TITLE
Cheat Protection

### ISSUE THREAD

**Issue by bootkitt** [danielkrupinski/Osiris#1337]
We Inject the hack into the Game. I need a code to delete a dll after exiting the game.
I want to do this inside the hack. is there any way to do this?

**Comment by littlehurensohn** [comment]
You can't delete the .dll, only when u be using manualmap.
Simply make some "Loader" in c++, what be streaming dll bytes from website.

(U dont must download .dll in 2k20) lmaoo

**Comment by xAkiraMiura** [comment]
> (U dont must download .dll in 2k20) lmaoo

learn english please.

if you put the DLL onto a USB drive you can just unplug it. also VAC doesn't appear to scan drives other than C:/ so you could probably put it there and be safe.

**Comment by DoctorYasin** [comment]
Osiris closes the game when I use manualmap.  I researched a little osiris not every manualmap is compatible.

**Comment by DoctorYasin** [comment]
How can I make the osiris manualmap compatible?

**Comment by AbdallahMehiz** [comment]
why don't use a usb stick, just inject the cheat and eject the usb from your system, easy and simple as i mostly do

**Comment by DoctorYasin** [comment]
I passed Manual Map. Cheating CSGO is Injected.  Game Freezes And Closes Immediately

**Comment by DoctorYasin** [comment]
```
        void Inject()
        {
            try
            {
                var target = Process.GetProcessesByName("csgo").FirstOrDefault();
                if (target == null) return;

                //////////////////// INJECTION HERE ////////////////////
                ///
                using(WebClient wc = new WebClient())
                {
                    wc.Proxy = null;
                    //wc.Headers.Add("User-Agent", "custom user agent here");//If have .htaccess
                    var response = wc.DownloadData("");//Link of your DLL
                    var injector = new ManualMapInjector(target) { AsyncInjection = true }; 
                    var module = $"hmodule = 0x{injector.Inject(response).ToInt64():x8}";
                    MessageBox.Show("Injected !");
                    Environment.Exit(0);
                }
                ///
                ///////////////////////////////////////////////////////
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }
```

**Comment by DoctorYasin** [comment]
@danielkrupinski

**Comment by bytixo** [comment]
try using is memject injector you don't even need to keep the .dll on your computer

**Comment by DoctorYasin** [comment]
@bytixo 
bro i have private loader.
`        void Inject()
        {
            try
            {
                var name = "csgo";
                var target = Process.GetProcessesByName(name).FirstOrDefault();
                if (target == null) return;

                //////////////////// iDLL Download Data ////////////////////
                ///
                using (WebClient wc = new WebClient())
                {
                    wc.Proxy = null; //
                    wc.Headers.Add("User-Agent", "7ab567e5ec9f24a980edfa60b2bb23df");//.htaccess user-agent 
                    var response = wc.DownloadData("http://link/custom.dll");//
                    var injector = new ManualMapInjector(target) { AsyncInjection = true };
                    var module = $"hmodule = 0x{injector.Inject(response).ToInt64():x8}";
                    MessageBox.Show("Injected !");
                    Environment.Exit(0);
                }
                ///
                ///////////////////////////////////////////////////////
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
           `

**Comment by DoctorYasin** [comment]
the game closes directly.

**Comment by danielkrupinski** [comment]
I think the problem lies in your private loader.

**Comment by DoctorYasin** [comment]
loadlibrary problem does not occur. but how do I program the dll to delete itself after closing?
@danielkrupinski

**Comment by Sapphire1337420** [comment]
lmao nice "#1337"

**Comment by streamshark** [comment]
why do you want to delete dll after injection?
