### ISSUE TITLE
Material help

### ISSUE THREAD

**Issue by darkisgod444** [danielkrupinski/Osiris#1338]
Does anyone know this material??
![PicsArt_03-29-08 13 19](https://user-images.githubusercontent.com/61908493/77842696-a9bca600-7195-11ea-87b0-dc9bdff01a78.png)

**Comment by effex1337** [comment]
Eyesore

**Comment by darkisgod444** [comment]
Can you tell me me the whole material name for example dev/glowoverlay.vmt i couldnt find it anywhere

**Comment by xAkiraMiura** [comment]
material is probably custom as it is an IgnoreZ (as you can see from the knife).
you can go to the valve developer docs for materials (VMT) and try to replicate it.
