### ISSUE TITLE
hello it shows this error.

### ISSUE THREAD

**Issue by CaptainBoi** [danielkrupinski/Osiris#1339]
please look at it i tried to fix it the problem is caused becoz of worldtoscreen in esp.cpp.
![image](https://user-images.githubusercontent.com/33902342/77843668-03849680-71bd-11ea-8ffa-d86a2e4197ce.png)

**Comment by xAkiraMiura** [comment]
update/reinstall visual studio 2019. you need build kit v142
get a fresh download of the repo.

can't help you too much if you don't show us the error.

**Comment by CaptainBoi** [comment]
updated look at it now.

**Comment by xAkiraMiura** [comment]
attach a debugger and see at which line it crashes. 
it appears you modified something or the game just updated and i haven't seen it.

**Comment by CaptainBoi** [comment]
well before the updates in march it worked with pphud at same time but now after the update it gives me this error. although  i didnt edit anything in the code yet this is the latest dll so far gives me a error after injecting.

**Comment by CaptainBoi** [comment]
its real size is 4.0mb but when i compile it , that gives me a dll of 852kb size file.

**Comment by xAkiraMiura** [comment]
debug DLLs are always large, compiling as Release x86 will shrink the file size.
