### ISSUE TITLE
How I can update Osris/offsets?

### ISSUE THREAD

**Issue by j0k3rh4u5** [danielkrupinski/Osiris#134]
How I can update offsets of Osris Hack?

**Comment by danielkrupinski** [comment]
There are no offsets.

**Comment by j0k3rh4u5** [comment]
How I can update the cheat? (on my own) Or it is automatically updated?

**Comment by HeadlessCpp** [comment]
You can come back every update and change what he changed or re-download it?

**Comment by Fry2412** [comment]
Just clone/pull and recompile.

**Comment by danielkrupinski** [comment]
Things that may require updating after game update are:
- [memory patterns](Osiris/Memory.cpp)
- [interfaces versions](Osiris/Interfaces.cpp)
- [game structs and classes](Osiris/SDK)
