### ISSUE TITLE
How to add RageBot

### ISSUE THREAD

**Issue by Cyk-Fad** [danielkrupinski/Osiris#1342]
How to add RageBot, or Lua?

**Comment by effex1337** [comment]
You need to add more ram for ragebot and lua.
https://downloadmoreram.com/
This might help you!

**Comment by xpossed-you** [comment]
omg haha

**Comment by Cyk-Fad** [comment]
Thank you~ Mua~

**Comment by xpossed-you** [comment]
his joking bro

**Comment by Cyk-Fad** [comment]
haha

**Comment by Cyk-Fad** [comment]
I know

**Comment by xpossed-you** [comment]
you really want to know how to add Ragebot?

**Comment by Cyk-Fad** [comment]
Yes

**Comment by xpossed-you** [comment]
https://www.youtube.com/watch?v=dQw4w9WgXcQ
here it is my tutorial coding, on how to add features like autoshoot

**Comment by Cyk-Fad** [comment]
ok thank you very much

**Comment by xpossed-you** [comment]
i gotchu bro

**Comment by Cyk-Fad** [comment]
haha

**Comment by hyperxpro** [comment]
@xpossed-you 12y/old?

**Comment by Cyk-Fad** [comment]
haha

**Comment by effex1337** [comment]
at least hes not 9 yo

**Comment by Cyk-Fad** [comment]
hahahah yes

**Comment by DoomFishWasTaken** [comment]
> You need to add more ram for ragebot and lua.
> https://downloadmoreram.com/
> This might help you!

thanks this helped me paste skeet.cc and now im tapping 4 yo nns in hvh

**Comment by xpossed-you** [comment]
> 
> 
> @xpossed-you 12y/old?

bruh, what?

**Comment by notgoodusename** [comment]
#1218 use this

**Comment by nealvos1353** [comment]
> https://www.youtube.com/watch?v=dQw4w9WgXcQ
> here it is my tutorial coding, on how to add features like autoshoot

--
XcQ, leave it blue
