### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by HypeLevels** [danielkrupinski/Osiris#1343]
I'm using randominjector, when I change maps the game crash example I'm In casual then changes map when casual finishes and I crash :/

**Comment by Faysal1969** [comment]
thats not happening to me

**Comment by HypeLevels** [comment]
that is really weird, can it be only me ? build in release Win32 everything works fine (i think lol) maybe there is a way to see what can be going on ? ill wait for someone that can help me more 🤔

**Comment by streamshark** [comment]
be sure you have the latest version of Osiris, verify the crash isn't there when not using Osiris, try a different injector like Xenos or one of the ones daniel has on his github

**Comment by HypeLevels** [comment]
Im using the latest version, game runs fine without it, different injector does the same

**Comment by danielkrupinski** [comment]
Compile in debug mode, attach debugger to the game process and inject dll using loadlibrary injector. When it crashes make a screenshot and post here.

**Comment by HypeLevels** [comment]
Stupid question, how do i attach the debugger to the game process? i inject the debug dll on the game is that it ? also when it crashes it doesnt show anything th game just closes like if the process was killed

**Comment by HypeLevels** [comment]
ok found how to attach the debugger, using https://github.com/KcYoung1997/LoadLibrary compilled dll in debug x86, going to test in a second

**Comment by HypeLevels** [comment]
https://hypelevels.is-ne.at/9NtkfK this is what shows up on vs after game crash

**Comment by danielkrupinski** [comment]
How much RAM CS:GO uses without cheats?

**Comment by HypeLevels** [comment]
Idk I was only testing Osiris to get better at cpp maybe arround 4gb ram

A terça, 31 de mar de 2020, 01:01, Daniel Krupiński <
notifications@github.com> escreveu:
