### ISSUE TITLE
[Enhancement] dynamic smooth

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1345]
Dynamic smooth is a pretty decent idea.

Correct me if i'm wrong : dynamic smooth generates a random value each time aimbot is activated 
Then assigns that value to be used as aimbot smooth, very simple i think

**Comment by rosesware** [comment]
Dynamic smooth don't "generates", it count who many FOV you need to hit the enemy and automatically resolve it to aimbot work depending on your crosshair longitude to the enemy.

**Comment by xAkiraMiura** [comment]
did you have a stroke writing that comment?

by dynamic smoothing do you mean curved or just variable in speed.
if you mean variable in speed then you can just use `rand` after doing `srand` once to get a number from 0 to 1 inclusive and then dividing the distance by it.
