### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by Zhxcky** [danielkrupinski/Osiris#1348]
Cancel

**Comment by effex1337** [comment]
It's already patched dumbo.

**Comment by HowToMakeFaceitAB** [comment]
Patched close this

**Comment by Faysal1969** [comment]
Patched

**Comment by rosesware** [comment]
It wasn't, got patched and someone revive the feature already, not much than 2 weeks before.

**Comment by RyDeem** [comment]
and it gat patched AGAIN
