### ISSUE TITLE
A warning in VS2019

### ISSUE THREAD

**Issue by Cyk-Fad** [danielkrupinski/Osiris#1349]
warning MSB8028: The intermediate directory (Release\) contains files shared from another project (Osiris.vcxproj).  This can lead to incorrect clean and rebuild behavior.

**Comment by Cyk-Fad** [comment]
Then and I can't use AimBot

**Comment by xAkiraMiura** [comment]
[first result on google.](https://stackoverflow.com/a/33641740/9281083)
also warnings shouldn't prevent you from using features

*how did you even encounter this problem?*

**Comment by Cyk-Fad** [comment]
I don't know
