### ISSUE TITLE
Triggerbot + Visible only

### ISSUE THREAD

**Issue by tamas0313** [danielkrupinski/Osiris#1350]
I tried to paste from aimbot.cpp only visible but failed. Maybe somebody can help me?

**Comment by Finndramere** [comment]
theres visible only option for triggerbot. you just have to uncheck ignore smoke and ignore flash. am I missing something or are you trying to add autowall triggerbot?

**Comment by 0xE232FE** [comment]
I think he means Autowall Triggerbot ;-)

**Comment by tamas0313** [comment]
yapp Autowall
