### ISSUE TITLE
Errors while trying to build

### ISSUE THREAD

**Issue by random4321** [danielkrupinski/Osiris#1351]
Over 700 errors, is it just me?

**Comment by xpossed-you** [comment]
re-download again?

**Comment by random4321** [comment]
> re-download again?

tried that, same errors

**Comment by HowToMakeFaceitAB** [comment]
Set release

**Comment by HowToMakeFaceitAB** [comment]
Or redownload vs2019 with 142 kit

**Comment by random4321** [comment]
> Set release

did, i used visual studio 2017, now i'll try with 2019
