### ISSUE TITLE
READ ME I WANT TO MAKE SURE YOUR FINE

### ISSUE THREAD

**Issue by NameNotTakenYAY** [danielkrupinski/Osiris#1352]
yo g I see you havent updated in a while and I know theres a epidemic. Your all good right?

**Comment by streamshark** [comment]
yeah 3 days hes prob dead :(((((

**Comment by hyperxpro** [comment]
This is Github, not Facebook.

Close this off-topic issue.

**Comment by whirlpool2** [comment]
he's updating GOESP, latest commit was 1 hour ago dude
