### ISSUE TITLE
Double tap implementation help (tick base manipulaition)

### ISSUE THREAD

**Issue by DahKiwiDude** [danielkrupinski/Osiris#1353]
Ive been doing research into double tap but alot of the articles i see on UC are highly outdated and not detailed

So anyone on here whos created a dt for osiris if you could either share and or explain the concept and infomation required to dt in csgo i would be really grateful 

And also with the framework/sdk osiris has built in would i be able to dt with the correct code?
Btw i do have a long history of modifying osiris as ive added lby breaking aa and a bunch of other stuff so when you explain you dont have to keep it very simple as i would like to understand tick base manipulaition more than i do witch isnt alot

**Comment by DahKiwiDude** [comment]
Yes this is a new github acc i dont use my main for these types of projects for obvs reasons

**Comment by notgoodusename** [comment]
@agshaidun made a doubletap but he is gone the videos are still there but unlisted

**Comment by DahKiwiDude** [comment]
Ae there any record of his work?

**Comment by notgoodusename** [comment]
yep but they are unlisted

**Comment by DahKiwiDude** [comment]
Do you have any screenshots or if they are videos do you have any links..

**Comment by DahKiwiDude** [comment]
@notgoodusename 
I notice you posted about your double tap recently
Cant you share the source behind that or at least the hooks for WritingCmds etc and the required hooks so i can build off that

If you want to keep it private you can send me a dm on discord if you would prefer

**Comment by notgoodusename** [comment]
i like public stuff so here
hook itself
bool __fastcall WriteUsercmdDeltaToBuffer(void* ECX, void* EDX, int nSlot, void* buf, int from, int to, bool isNewCmd)
{
    static DWORD WriteUsercmdDeltaToBufferReturn = (DWORD)pat::FindPattern("engine.dll", "84 C0 74 04 B0 01 EB 02 32 C0 8B FE 46 3B F3 7E C9 84 C0 0F 84");
    //static auto sendmovecall = pat::FindPattern("engine.dll", "84 C0 74 04 B0 01 EB 02 32 C0 8B FE 46 3B F3 7E C9 84 C0 0F 84 ? ? ? ?");
    static auto ofunct = hooks.client.getOriginal2<bool, void*, int, void*, int, int, bool >(24, ECX, nSlot, buf, from, to, isNewCmd);

    if ((DWORD)_ReturnAddress() != WriteUsercmdDeltaToBufferReturn || tickbaseShift <= 0 || !memory.clientState || !memory.clientState->m_NetChannel)
    {
        tickbaseShift = 0;
        return ofunct(ECX, nSlot, buf, from, to, isNewCmd);
    }
    if (from != -1)
        return true;

    auto CL_SendMove = []() {
        using CL_SendMove_t = void(__fastcall*)(void);
        static CL_SendMove_t CL_SendMoveF = (CL_SendMove_t)pat::FindPattern("engine.dll", "55 8B EC A1 ? ? ? ? 81 EC ? ? ? ? B9 ? ? ? ? 53 8B 98");

        CL_SendMoveF();
    };

    auto WriteUsercmd = [](void* buf, UserCmd* in, UserCmd* out) {
        using WriteUsercmd_t = void(__fastcall*)(void*, UserCmd*, UserCmd*);
        static WriteUsercmd_t WriteUsercmdF = (WriteUsercmd_t)pat::FindPattern("client_panorama.dll", "55 8B EC 83 E4 F8 51 53 56 8B D9 8B 0D");
        WriteUsercmdF(buf, in, out);

    };
    // number of backup and new commands
    int* pNumBackupCommands = (int*)((std::uintptr_t) buf - 0x30);
    int* pNumNewCommands = (int*)((std::uintptr_t)buf - 0x2C);
    auto net_channel = *reinterpret_cast<INetChannel**>(reinterpret_cast<uintptr_t>(memory.clientState) + 0x9C);
    int32_t new_commands = *pNumNewCommands;
    // Manipulate CLC_Move
    auto nextcmdnumber = memory.clientState->lastoutgoingcommand + memory.clientState->chokedcommands + 1;
    auto totalnewcommands = std::min(tickbaseShift, 16);
    tickbaseShift -= totalnewcommands;
    from = -1;
    *pNumNewCommands = totalnewcommands;
    *pNumBackupCommands = 0;
    //generate real cmd's
    for (to = nextcmdnumber - new_commands + 1; to <= nextcmdnumber; to++)
    {
        if (!ofunct(ECX, nSlot, buf, from, to, true))
            return false;

        from = to;
    }
    UserCmd* lastrealcmd = memory.cinput->GetUserCmd(nSlot, from);
    UserCmd fromcmd;
    if (lastrealcmd)
        fromcmd = *lastrealcmd;
    UserCmd tocmd = fromcmd;
    tocmd.commandNumber++;
    tocmd.tickCount += (timeToTicks(0.5f) + nextcmdnumber);
    //generate fake cmd's
    for (int i = new_commands; i <= totalnewcommands; i++)
    {
        WriteUsercmd(buf, &tocmd, &fromcmd);
        fromcmd = tocmd;
        tocmd.commandNumber++;
        tocmd.tickCount++;
    }
    //send them in all together
    CL_SendMove();
    return true;
}
getoriginal2
        template<typename T, typename ...Args>
        constexpr auto getOriginal2(size_t index, Args... args) const noexcept
        {
            return reinterpret_cast<T(__thiscall*)(Args...)>(oldVmt[index]);
        }

can use memory for this one
unsigned int pat::FindPattern(std::string moduleName, std::string pattern, bool relativeOffset) noexcept
{
	const char* pat = pattern.c_str();
	uintptr_t firstMatch = 0;
	uintptr_t rangeStart = (uintptr_t)GetModuleHandleA(moduleName.c_str());
	MODULEINFO miModInfo; GetModuleInformation(GetCurrentProcess(), (HMODULE)rangeStart, &miModInfo, sizeof(MODULEINFO));
	uintptr_t rangeEnd = rangeStart + miModInfo.SizeOfImage;

	for (uintptr_t pCur = rangeStart; pCur < rangeEnd; pCur++) {
		if (!*pat)
			break;

		if (*(PBYTE)pat == '\?' || *(BYTE*)pCur == getByte(pat)) {
			if (!firstMatch)
				firstMatch = pCur;

			if (!pat[2])
				break;

			if (*(PWORD)pat == '\?\?' || *(PBYTE)pat != '\?')
				pat += 3;

			else
				pat += 2;
		}
		else {
			pat = pattern.c_str();
			firstMatch = 0;
		}
	}

	if (relativeOffset)
		firstMatch = firstMatch + 0x5 + *(DWORD*)(firstMatch + 0x1);
	return firstMatch;
}


createmove
    if (config.misc.Doubletap)
    {
        if ((cmd->buttons & (UserCmd::IN_ATTACK)))
        {

            int doubletapTickcountDelta = memory.globalVars->tickCount - lastDoubleTapInTickcount;

            if (doubletapTickcountDelta >= timeToTicks(2.0f)) {
                lastDoubleTapInTickcount = memory.globalVars->tickCount;
                cmd->tickCount = INT_MAX;
                tickbaseShift = 16;
            }
        }
        else {
            cmd->tickCount = memory.globalVars->tickCount;
        }
    }
    else
    {
        tickbaseShift = 0;
    }

**Comment by notgoodusename** [comment]
memory.cpp  
  clientState = **reinterpret_cast<CClientState***>((*reinterpret_cast<uintptr_t**>(interfaces.engine))[12] + 16);
cclientstate class
struct Vector;
struct CClockDriftMgr
{
	float m_ClockDriftMgr;
};
struct CClientState
{
public:

	void ForceFullUpdate()
	{
		m_nDeltaTick = -1;
	}

	std::byte pad_0000[156];             //0x0000
	INetChannel* m_NetChannel;          //0x009C //Netchan
	uint32_t m_nChallengeNr;        //0x00A0
	std::byte pad_00A4[100];             //0x00A4
	uint32_t m_nSignonState;        //0x0108
	std::byte pad_010C[8];               //0x010C
	float m_flNextCmdTime;          //0x0114
	uint32_t m_nServerCount;        //0x0118
	uint32_t m_nCurrentSequence;    //0x011C
	std::byte pad_0120[8];               //0x0120
	CClockDriftMgr m_ClockDriftMgr; //0x0128
	uint32_t m_nDeltaTick;          //0x0178
	bool m_bPaused;                 //0x017C
	std::byte pad_017D[3];               //0x017D
	uint32_t m_nViewEntity;         //0x0180
	uint32_t m_nPlayerSlot;         //0x0184
	std::byte m_szLevelName[260];        //0x0188
	std::byte m_szLevelNameShort[40];    //0x028C
	std::byte m_szGroupName[40];         //0x02B4
	std::byte pad_02DC[52];              //0x02DC
	uint32_t m_nMaxClients;         //0x0310
	std::byte pad_0314[18820];           //0x0314
	float m_flLastServerTickTime;   //0x4C98
	bool insimulation;              //0x4C9C
	std::byte pad_4C9D[3];               //0x4C9D
	uint32_t oldtickcount;          //0x4CA0
	float m_tickRemainder;          //0x4CA4
	float m_frameTime;              //0x4CA8
	uint32_t lastoutgoingcommand;   //0x4CAC
	uint32_t chokedcommands;        //0x4CB0
	uint32_t last_command_ack;      //0x4CB4
	uint32_t command_ack;           //0x4CB8
	uint32_t m_nSoundSequence;      //0x4CBC
	std::byte pad_4CC0[80];              //0x4CC0
	Vector viewangles;              //0x4D10
}; //Size: 0x4E1C
netchan class
class INetChannel
{
public:
	
    bool transmit(bool onlyReliable = false)
    {
        return callVirtualMethod<bool>(this, 47, onlyReliable);
    }
}

**Comment by DahKiwiDude** [comment]
Could you share your INetChannel
From for example
` auto net_channel = *reinterpret_cast<INetChannel**>(reinterpret_cast<uintptr_t>(memory.clientState) + 0x9C);`

**Comment by DahKiwiDude** [comment]
Also have you missed out a class called "pat" in "pat::FindPattern"

`    static DWORD WriteUsercmdDeltaToBufferReturn = (DWORD)pat::FindPattern("engine.dll", "84 C0 74 04 B0 01 EB 02 32 C0 8B FE 46 3B F3 7E C9 84 C0 0F 84");
`

**Comment by notgoodusename** [comment]
#include <array>
#include <string>
#include <type_traits>
#include <Windows.h>
#include <Psapi.h>

**Comment by notgoodusename** [comment]
#define INRANGE(x,a,b)    (x >= a && x <= b) 
#define getBits( x )    (INRANGE((x&(~0x20)),'A','F') ? ((x&(~0x20)) - 'A' + 0xa) : (INRANGE(x,'0','9') ? x - '0' : 0))
#define getByte( x )    (getBits(x[0]) << 4 | getBits(x[1]))

**Comment by DahKiwiDude** [comment]
`memory.cinput->GetUserCmd(nSlot, from);`

Also i believe cinput is missing from memory

Unles sim being a bit dumb again

Also thanks for all this
i will be looking through how it all works later

**Comment by notgoodusename** [comment]
UserCmd* GetUserCmd(int nSlot, int sequence_number)
	{
		//typedef UserCmd* (__thiscall* GetUserCmd_t)(void*, int, int);
		return callVirtualMethod<UserCmd*, int, int>(this, 8,nSlot, sequence_number);
	}

**Comment by notgoodusename** [comment]
memory.input->GetUserCmd(nSlot, from);

**Comment by DahKiwiDude** [comment]
I get pointer to known type is not allowed :/

**Comment by DahKiwiDude** [comment]
Dont we need a line of code to hook the function such as 
"clientState.hookAt(24, WriteUsercmdDeltaToBuffer);"
24 is the index for create move how do i hook it for write cmd

Im going ot test without the hook but i dont believe it will work

**Comment by notgoodusename** [comment]
client.hookAt(24, WriteUsercmdDeltaToBuffer);

**Comment by DahKiwiDude** [comment]
For the life of me i cant get your source to work,
`clientState = reinterpret_cast<CClientState*>((reinterpret_cast<uintptr_t*>(interfaces.engine))[12] + 16);`
This gets flagged "clientState" for not existing in memory so i define it with its class "CClientState* clientState;"
Then i compile and get hit with lots of errors
Ive made it work by defining it within bool __fastcall WriteUsercmdDeltaToBuffer function but
when testing nothing happened and i suspect thats because of the fact its not hooked using hookAt(24, WriteUsercmdDeltaToBuffer);
so im going to try work out the index

**Comment by DahKiwiDude** [comment]
Using
`clientMode.hookAt(25, WriteUsercmdDeltaToBuffer);`

Has got the function to be hooked correctly
But clientState doesnt seem to have any data causing it to crash so now im super stumped

**Comment by DahKiwiDude** [comment]
Whats annoying is i have this so close to working :(

**Comment by xAkiraMiura** [comment]
if your message is too long to fit in a single comment then maybe it shouldn't be sent as a comment.
pastebin and hastebin exist. (or you could make a fork and link that)

**Comment by notgoodusename** [comment]
index is 24
memory.cpp
    clientState = **reinterpret_cast<CClientState***>((*reinterpret_cast<uintptr_t**>(interfaces.engine))[12] + 16);
memory.h
    CClientState* clientState;

**Comment by DahKiwiDude** [comment]
I got an error saying un able t find pattern :( it hooks fine i believe its just an issue with pattern scanning within the hook
`    static CL_SendMove_t CL_SendMoveF = (CL_SendMove_t)findPattern(L"engine.dll", "55 8B EC A1 ? ? ? ? 81 EC ? ? ? ? B9 ? ? ? ? 53 8B 98");

    static WriteUsercmd_t WriteUsercmdF = (WriteUsercmd_t)findPattern(L"client_panorama.dll", "55 8B EC 83 E4 F8 51 53 56 8B D9 8B 0D");
`
So i assume i just need to find correct patterns

**Comment by DahKiwiDude** [comment]
`Vmt clientState{ memory.clientState };
clientState.hookAt(24, WriteUsercmdDeltaToBuffer);`

or do i have to link it to client vmt

`client.hookAt(24, WriteUsercmdDeltaToBuffer);`

**Comment by DahKiwiDude** [comment]
At this point ive tried so much to get this to work there are still many situations i have to guess what to do, can you just share some sort of solution or something as this isnt working at all

**Comment by notgoodusename** [comment]
client no clientstate, create a new file and put 
#include "SDK/Pattern.h"


unsigned int pat::FindPattern(std::string moduleName, std::string pattern, bool relativeOffset) noexcept
{
	const char* pat = pattern.c_str();
	uintptr_t firstMatch = 0;
	uintptr_t rangeStart = (uintptr_t)GetModuleHandleA(moduleName.c_str());
	MODULEINFO miModInfo; GetModuleInformation(GetCurrentProcess(), (HMODULE)rangeStart, &miModInfo, sizeof(MODULEINFO));
	uintptr_t rangeEnd = rangeStart + miModInfo.SizeOfImage;

	for (uintptr_t pCur = rangeStart; pCur < rangeEnd; pCur++) {
		if (!*pat)
			break;

		if (*(PBYTE)pat == '\?' || *(BYTE*)pCur == getByte(pat)) {
			if (!firstMatch)
				firstMatch = pCur;

			if (!pat[2])
				break;

			if (*(PWORD)pat == '\?\?' || *(PBYTE)pat != '\?')
				pat += 3;

			else
				pat += 2;
		}
		else {
			pat = pattern.c_str();
			firstMatch = 0;
		}
	}

	if (relativeOffset)
		firstMatch = firstMatch + 0x5 + *(DWORD*)(firstMatch + 0x1);
	return firstMatch;
}
and on the header file put
#pragma once
#include <array>
#include <string>
#include <type_traits>
#include <Windows.h>
#include <Psapi.h>


#define INRANGE(x,a,b)    (x >= a && x <= b) 
#define getBits( x )    (INRANGE((x&(~0x20)),'A','F') ? ((x&(~0x20)) - 'A' + 0xa) : (INRANGE(x,'0','9') ? x - '0' : 0))
#define getByte( x )    (getBits(x[0]) << 4 | getBits(x[1]))
namespace pat
{
	unsigned int FindPattern(std::string, std::string, bool relativeOffset = false) noexcept;
}

**Comment by notgoodusename** [comment]
> i just want myself some double tap

this doubletap doesnt work so you can try to fix it the basic stuff is on this post
