### ISSUE TITLE
How to make ImGuiwindow look like skeet or aimware?

### ISSUE THREAD

**Issue by Cyk-Fad** [danielkrupinski/Osiris#1354]
I think we need to update window.

**Comment by hyperxpro** [comment]
Selling paste? xD

**Comment by rosesware** [comment]
> Selling paste? xD

I think he's asking who to make Osiris looks like a Skeet or Aimware in terms of menu.

**Comment by KernCS** [comment]
https://i.imgur.com/YhQhRA8.jpg Not hard:) just go to uc and find a paste with skeet menu ?

**Comment by Mistrz1337** [comment]
> Not hard:) just go to uc and find a paste with skeet menu ?
> ![YhQhRA8](https://user-images.githubusercontent.com/31683300/78142598-61b7b080-742d-11ea-941b-823cb1db2e90.jpg)

Can you send src with done it ?

**Comment by KernCS** [comment]
> > Not hard:) just go to uc and find a paste with skeet menu ?
> > ![YhQhRA8](https://user-images.githubusercontent.com/31683300/78142598-61b7b080-742d-11ea-941b-823cb1db2e90.jpg)
> 
> Can you send src with done it ?


Go to uc find skeet paste and start c+p

**Comment by Mistrz1337** [comment]
> > > Not hard:) just go to uc and find a paste with skeet menu ?
> > > ![YhQhRA8](https://user-images.githubusercontent.com/31683300/78142598-61b7b080-742d-11ea-941b-823cb1db2e90.jpg)
> > 
> > 
> > Can you send src with done it ?
> 
> Go to uc find skeet paste and start c+p

can't you just upload it ?

**Comment by KernCS** [comment]
> > > > Not hard:) just go to uc and find a paste with skeet menu ?
> > > > ![YhQhRA8](https://user-images.githubusercontent.com/31683300/78142598-61b7b080-742d-11ea-941b-823cb1db2e90.jpg)
> > > 
> > > 
> > > Can you send src with done it ?
> > 
> > 
> > Go to uc find skeet paste and start c+p
> 
> can't you just upload it ?

i guy said he would pay me for implementing the menu to osiris so it would not be fair for him if i just upload it now, (he knew it came from uc)

**Comment by asntoxic** [comment]
@KernCS  can you give me only skeet imgui? :P

**Comment by whirlpool2** [comment]
what should i be pasting over?

**Comment by KernCS** [comment]
> what should i be pasting over?

https://www.unknowncheats.me/forum/cs-go-releases/346798-internal-censored-clone-menu.html
https://void.to/t/Release-nanosense-gamesense-dump-v5-source
pick one:)

**Comment by Cyk-Fad** [comment]
thanks! :D

**Comment by Cyk-Fad** [comment]
A lot of erro is show..............

**Comment by KernCS** [comment]
> A lot of erro is show..............

ik u have to fix them:D

**Comment by DevSerpent** [comment]
> > A lot of erro is show..............
> 
> ik u have to fix them:D

Can you add me on discord? its important: ᴊ ɪ ɪ ɴ ɢ ᴢ 吉恩茲#5006

**Comment by N8TH1N6** [comment]
> Not hard:) just go to uc and find a paste with skeet menu ? ![YhQhRA8](https://user-images.githubusercontent.com/31683300/78142598-61b7b080-742d-11ea-941b-823cb1db2e90.jpg)

can I buy that from u xD?
