### ISSUE TITLE
Movement recorder (is everyone ignoring this?)

### ISSUE THREAD

**Issue by ChromMob** [danielkrupinski/Osiris#1355]
I found this code on the web. I tried to implement it to Osiris but I wasn't successful can u import it for me, please. Code: [Code](https://www.unknowncheats.me/forum/counterstrike-global-offensive/362788-movement-recording.html) If this can not be implemented there are also other codes to try. [Code 1](https://www.unknowncheats.me/forum/counterstrike-global-offensive/175479-movement-recorder.html) [Code 2](https://www.unknowncheats.me/forum/counterstrike-source/102831-movement-record.html) [Here](https://aixxe.net/2017/04/source-input-recorder) is even a tutorial how to make it.

**Comment by modern158** [comment]
If this can not be implemented there are also other codes to try. [Code1](https://www.unknowncheats.me/forum/counterstrike-source/102831-movement-record.html) [Code2](https://www.unknowncheats.me/forum/counterstrike-global-offensive/175479-movement-recorder.html)

**Comment by xAkiraMiura** [comment]
all the code needed is right there on the post, learn what you're doing and don't beg.

**Comment by HowToMakeFaceitAB** [comment]
yes, yes they are
