### ISSUE TITLE
Location Spammer?

### ISSUE THREAD

**Issue by CantRememberMyself** [danielkrupinski/Osiris#1356]
Any ideas how to go about this?

**Comment by KernCS** [comment]
https://github.com/AimTuxOfficial/AimTux/blob/9aa85f904dd465523296ae08437001bf4a3a150a/src/Hacks/spammer.cpp#L116 Aimtux got it c+p

**Comment by CantRememberMyself** [comment]
oh sweet tysm

**Comment by CantRememberMyself** [comment]
> https://github.com/AimTuxOfficial/AimTux/blob/9aa85f904dd465523296ae08437001bf4a3a150a/src/Hacks/spammer.cpp#L116 Aimtux got it c+p

**Comment by CantRememberMyself** [comment]
> https://github.com/AimTuxOfficial/AimTux/blob/9aa85f904dd465523296ae08437001bf4a3a150a/src/Hacks/spammer.cpp#L116 Aimtux got it c+p

could you help me with this part
" return (const char*)((uintptr_t)this + offsets.DT_BasePlayer.m_szLastPlaceName);"
what do i do to replace the "offsets.DT_BasePlayer.m_szLastPlaceName"

**Comment by Kron1Q** [comment]
NETVAR(idk, "CBasePlayer", "szLastPlaceName", char);

**Comment by xAkiraMiura** [comment]
please learn what you are doing. with vs2019 you can literally hover over a variable and it will give you its value.

the offsets are **certainly** wrong anyway considering aimtux old and **literally linux based**


> ```
> NETVAR(idk, "CBasePlayer", "szLastPlaceName", char);
> ```

looks correct, offset should be `0x000035B4` but may be outdated.

**Comment by CantRememberMyself** [comment]
`   if (!config.misc.locationz)
        return;

    const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());

    for (int i = 1; i <= interfaces.engine->getMaxClients(); ++i) {
        const auto entity = interfaces.entityList->getEntity(i);
        std::string str = "say_team \"";
        str += entity->Location();
        str += "\"";

        interfaces.engine->clientCmdUnrestricted(str.c_str());


    }`

crashing with this code

Location = NETVAR(Location, "CBasePlayer", "szLastPlaceName", char);

Any ideas? @xAkiraMiura @Kron1Q

**Comment by CantRememberMyself** [comment]
void Misc::locationspam() noexcept
{   
    if (config.misc.locationz)
    {
        for (int i = 1; i <= interfaces.engine->getMaxClients(); ++i) {
                const auto pentity = interfaces.entityList->getEntity(i);
                const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
                if (!pentity || !pentity->isAlive())
                    return;
             interfaces.engine->clientCmdUnrestricted(std::string{ "say_team " }.append(pentity->GetLastPlaceName()).c_str());
        }
    }
}

ok so this works but it only prints my location??

**Comment by CantRememberMyself** [comment]
have it working now, thanks guys
