### ISSUE TITLE
How i implimented correct Third person AA.

### ISSUE THREAD

**Issue by Marlborow** [danielkrupinski/Osiris#1357]
All instructions on all issues were so unclear.
I've found out in the end how to achieve this and i don't wan't any one else to spend a day or two
In a constant mood to take a shower with a toaster.

Keep in mind my osiris is a little out of date, you might have to change some likes 
(like for instance config.something now is config->something) *bruh*

1. I set a public vectors in config.h named "GlobalThirdpersonAngle" and "GlobalIsThirdPerson"

2. in AntiAim.cpp i do
		`if (sendPacket == false) config.GlobalThirdpersonAngle = cmd->viewangles;`
at the end

3. in Entity.h, in class Entity i do
`void setDeadFlag(Vector angle) noexcept { const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
		*reinterpret_cast<Vector*>((DWORD)localPlayer + 0x31D4 + 0x4) = angle; 
	}`  

4. in Visuals.cpp in thirdperson right under "if (config.visuals.thirdperson)" i do

`if (memory.input->isCameraInThirdPerson = (!config.visuals.thirdpersonKey || isInThirdperson) && interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer())->isAlive()) 
		{
			config.GlobalIsThirdPerson = 1;
			memory.input->cameraOffset.z = static_cast<float>(config.visuals.thirdpersonDistance);
		}
		else config.GlobalIsThirdPerson = 0;` 

5. in Hooks.cpp in FrameStageNotify at "if (stage == FrameStage::RENDER_START) {"
i put this right under
`if (config.antiAim.enabled) {
                if (config.GlobalIsThirdPerson == 1)
		{
			Entity entity;
			entity.setDeadFlag(config.GlobalThirdpersonAngle);
		}
}`

**Comment by Marlborow** [comment]
Side note, just tried fireing manually instead of aimbot, seems like my bullets shoot a little to the left of the crosshair. Hope that's just my anti-aim.

**Comment by xAkiraMiura** [comment]
next time please make a pull, copy pasting code manually is bad practice.

**Comment by notgoodusename** [comment]
bruh this will show your chocked angles dont u wanna see your real instead lf something they cant see?(to fix this do if sendpacket ==true) and i think i already made this

**Comment by Marlborow** [comment]
I've added a toggle button to check both sendpacksts and not sending packets. Only the above show's my actual angle displayed by bot_mimic

**Comment by Marlborow** [comment]
> 
> 
> next time please make a pull, copy pasting code manually is bad practice.

My appologies and noted, was my first post on Github.
