### ISSUE TITLE
Can you add C4 explosion damage

### ISSUE THREAD

**Issue by lss961638214** [danielkrupinski/Osiris#1358]
Can give us better dodge when C4 explodes

**Comment by Or3nges** [comment]
#1016

**Comment by RyDeem** [comment]
not on all maps, but its a guide atleast, as the bomb damage is not a 3d circle around the bomb , but has predifined damage zones as far as im aware

**Comment by xAkiraMiura** [comment]
it is a sphere around the bomb. it is inaccurate on maps like nuke because the damages is set to be either 50 to 100 lower than all other maps.
also predefined spots is bad practice.
