### ISSUE TITLE
hy can't my awp and ssg 08 automatically target others

### ISSUE THREAD

**Issue by lss961638214** [danielkrupinski/Osiris#1359]
I adjusted Fov to 100 and Smooth to 1, but my awp (ssg 08) was not near the head of the bot, but it was still there after I shot it. How can I solve this problem?

**Comment by tirziz** [comment]
change max inaccuracy

**Comment by lss961638214** [comment]
I found that this is not the problem of the maximum error. This problem is caused by the recoil control. When I did not set it, awp and ssg will not work, but thank you for your reminder.

**Comment by rosesware** [comment]
> but thank you for your reminder.
### ?
I don't know what you talking to, and I don't understand what you want to tells us, put more commas correctly and your english... but, what you "did not set it" ("Recoil"?) if "Recoil" is now automatically?

**Comment by lss961638214** [comment]
![4T7 0T~PZOU`_`GB8KZ{6MM](https://user-images.githubusercontent.com/61107038/78313765-75c4f480-758a-11ea-9aa1-0072357e29d5.png)
![FR3OX5Y%Q8 YEIQC6S$R$MF](https://user-images.githubusercontent.com/61107038/78313772-7eb5c600-758a-11ea-81ff-019f0257aa90.png)
The first image has no aiming effect, the second image has an aiming effect
My english is really bad, excuse me

**Comment by RyDeem** [comment]
That is not recoil control, that is inaccuracy ( Aimbot waits for the weapon to steady itself (on 0.07) or does not ( 1.00 ).
Thats is bassicaly what thast feature does in simple terms.
Please, take some time and experiment with the features to learn what they do to the aimbot :)

**Comment by xAkiraMiura** [comment]
max aim inaccuracy = forced time between shots (to reduce spread)
max shot inaccuracy = maximum speed (which also increases spread)

> 
> 
> > ~
> 
> ### ?
> 
> I don't think I know what you talking to, and I don't understand what you want to tells us, put more commas correctly and your english... but, what you "did not set it" ("Recoil"?) if "Recoil" is now automatically?

i think you should learn english too <3
