### ISSUE TITLE
Glow issue

### ISSUE THREAD

**Issue by Erwan420G** [danielkrupinski/Osiris#136]
Since the last update (about a day ago),on the glow, the occluded and visible functions are not working well. I'm trying to fix it I'll update if I succeed.

**Comment by HeadlessCpp** [comment]
What do you mean not working well?

**Comment by Erwan420G** [comment]
When I check visible with a color, it displays another color and same for occluded... I can't figure out why.

**Comment by HeadlessCpp** [comment]
Did you modify anything?

**Comment by Erwan420G** [comment]
Nevermind... I'm so dumb because I checked health based glow and of course the health colors override the basic glow colors. Thanks for the replies anyway!
