### ISSUE TITLE
Occasional Crash in Osiris

### ISSUE THREAD

**Issue by dev-nocap** [danielkrupinski/Osiris#1361]
There seems to be a small issue where Osiris will crash upon starting to throw a grenade. I don't notice any specific behavior that could cause the problem nor can I find something in the source that would cause this.

**Comment by dev-nocap** [comment]
Note that it most often happens with CT Incendiary Grenades and Flashbangs on either side.

**Comment by HowToMakeFaceitAB** [comment]
are you using grenade prediction

**Comment by dev-nocap** [comment]
Nope it's off
