### ISSUE TITLE
Errors while build

### ISSUE THREAD

**Issue by TwitchDash** [danielkrupinski/Osiris#1362]
bruh?
![image](https://user-images.githubusercontent.com/57836484/78366033-1eef0780-75ea-11ea-9b8c-6eed25485d9a.png)

![image](https://user-images.githubusercontent.com/57836484/78366092-37f7b880-75ea-11ea-9b1e-9e97bbaf6360.png)

**Comment by TwitchDash** [comment]
![image](https://user-images.githubusercontent.com/57836484/78366420-ab012f00-75ea-11ea-8c4c-b01813af9ad2.png)

**Comment by dev-nocap** [comment]
Are you using the most recent version of Osiris source?
Have you tried updating your Visual Studio?
Mine definitely doesn't have this many errors.

**Comment by TwitchDash** [comment]
yes

**Comment by Faysal1969** [comment]
you can fix the char8_t errors with changing them to char

**Comment by xAkiraMiura** [comment]
> 
> 
> you can fix the char8_t errors with changing them to char

or you can just fix the underlying problem. thats a bandage solution.

**Comment by danielkrupinski** [comment]
#1186

**Comment by danielkrupinski** [comment]
#1158
