### ISSUE TITLE
[REQUEST] Penetration Crosshair

### ISSUE THREAD

**Issue by dev-nocap** [danielkrupinski/Osiris#1363]
Has anyone made or thought about making a penetration crosshair? It's as simple as drawing a little box that turns green when you can wallbang but I can't seem to get one working.

**Comment by Zhxcky** [comment]
so for example, when you aim at wall that can be wallbanged, the crosshair turns green?

**Comment by HowToMakeFaceitAB** [comment]
> so for example, when you aim at wall that can be wallbanged, the crosshair turns green?

correct

**Comment by HowToMakeFaceitAB** [comment]
but maybe also adding a min dmg indicator for the penetration crosshair(say you set the min dmg for the penetration crosshair to 20 your penetration crosshair doesn't turn green unless you can do at least 20 dmg with your shot ,as an example)

**Comment by dev-nocap** [comment]
@danielkrupinski Is there any way you know how to implement this?
