### ISSUE TITLE
[REQUEST] Update Skinchanger

### ISSUE THREAD

**Issue by Zhxcky** [danielkrupinski/Osiris#1364]

**Comment by danielkrupinski** [comment]
Why?

**Comment by RyDeem** [comment]
i think there were new skins added in the latest update?
source: https://blog.counter-strike.net/index.php/category/updates/

**Comment by Zhxcky** [comment]
> Why?

new skin update?

**Comment by danielkrupinski** [comment]
List of skins is retrieved dynamically from game memory, it's always up-to-date.
