### ISSUE TITLE
Killshot and Burst Time Explanation?

### ISSUE THREAD

**Issue by Zhxcky** [danielkrupinski/Osiris#1365]
just noticed the new features on triggerbot menu, can someone tell me what are those?

**Comment by AbdallahMehiz** [comment]
Killshot: The triggerbot will only shoots if it is 100% certain that the shot will kill the target
-same goes for the aimbot killshot
Burst time(overbust): The triggerbot will continue to shoot the weapon(fully automatic weapons) for a certain ammount of time after the target is out of range or killed
