### ISSUE TITLE
Why use relative and abusing masm?

### ISSUE THREAD

**Issue by d4rkd3n1337** [danielkrupinski/Osiris#1366]
https://github.com/danielkrupinski/Osiris/blob/9db3e26fe30f99d52d53b6958742a7b216637e3b/Osiris/Hacks/Visuals.cpp#L221

`void DrawScreenEffectMaterial(IMaterial *pMaterial, int x, int y, int w, int h)
			{
				using Fn = void(__stdcall*)(IMaterial*, int, int, int, int);

				static Fn DrawScreenEffectMaterialFn = nullptr;

				if (!DrawScreenEffectMaterialFn)
					DrawScreenEffectMaterialFn = MemoryAPI::FindPattern(Images::ClientPanorama, "55 8B EC 83 E4 F8 83 EC 1C 53 56 57 8D 44 24 18").cast<Fn>();

				DrawScreenEffectMaterialFn(pMaterial, x, y, w, h);
			}`

**Comment by danielkrupinski** [comment]
Your signature leads to the same function, which obviously isn't __stdcall or any other defined calling convention (first two arguments are passed in registers and stack is managed as in __cdecl).
