### ISSUE TITLE
Message box?

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#1367]
Hi, where is now the code for Welcome "message box" ?

interfaces.gameUI->messageBox("This was a triumph!", "Osiris has been successfully loaded.");

Before it was inside hook.cpp, but now when putting that line, the compilation fails

**Comment by Mistrz1337** [comment]
you need to change interfaces.gameUI to interfaces->gameUI

**Comment by TauCSGO** [comment]
> you need to change interfaces.gameUI to interfaces->gameUI

Like this?
`interfaces.gameUI->messageBox("This was a triumph!", "Osiris has been successfully loaded.");`

it does not work

**Comment by Zhxcky** [comment]
ye i want to change that to using my own text but couldn't findout how

**Comment by Kron1Q** [comment]
> > you need to change interfaces.gameUI to interfaces->gameUI
> 
> Like this?
> `interfaces->gameUI->messageBox("This was a triumph!", "Osiris has been successfully loaded.");`
> 
> it does not work

It does, just tested.

**Comment by TauCSGO** [comment]
> It does, just tested.

it does not work
when load the cheat, csgo crash

**Comment by Kron1Q** [comment]
You are right. Just checked on newest Osiris and i am crashing. I am using older version and it works.

https://i.imgur.com/IZL4BJm.png

**Comment by mrb0098** [comment]
same problem
when i use ` interfaces->gameUI->messageBox` **csgo crash**
