### ISSUE TITLE
Trying to paste offscreen esp

### ISSUE THREAD

**Issue by jalopino** [danielkrupinski/Osiris#1368]
![image](https://user-images.githubusercontent.com/50796215/78503577-22c18c00-779a-11ea-8cd5-ae51efa73f00.png) I don't know how to fix the Vector part. Can someone help?

**Comment by dev-nocap** [comment]
Are any of those functions defined in config? Also many of your errors are springing from syntax that doesn't work with the current version of Osiris, use arrow operators instead.
