### ISSUE TITLE
Triggerbot -> possibility to select multiple hitspots??? 

### ISSUE THREAD

**Issue by BloodXPride** [danielkrupinski/Osiris#1369]
Hey, i want to know if its possible to select multiple hitspots at once.
I only can select "All" or single spots.
I want that Triggerbot will only hit "Head","Chest" and "Stomach".

Thx in advance.

**Comment by linuxer9** [comment]
I guess this feature will be redundant, for now you can use minimum damage
for example, AWP deals 85 damage to legs
If you se triggerbot minimum damage to a value more than 85 it will exclude legs if you set it to "all"
but yes multiple hitbox/bone option would be awesome
