### ISSUE TITLE
[Request] Config Saving and Deleteing Confirmation Window

### ISSUE THREAD

**Issue by Vadenez** [danielkrupinski/Osiris#1371]
(Idea) 
A "Confirmation Window" for deleting or saving Configs, as I keep on acedentally deleting and over-righting my configs with another config. I have now just resorted to being more cautious, but when It does happen, I have to completely recreate my config, which takes a lot of time.

**Comment by KernCS** [comment]
My delete confirm `                if (ImGui::Button("Delete Config", { 100.0f, 25.0f }))
                    ImGui::OpenPopup("Config to delete");
                if (ImGui::BeginPopup("Config to delete")) {
                    static constexpr const char* names[]{ "Yes", "No" }; 
                    for (int i = 0; i < IM_ARRAYSIZE(names); i++) {
                        if (i == 1) ImGui::Separator();
                
                        if (ImGui::Selectable(names[i])) {
                            switch (i) {
                            case 0: config->remove(currentConfig); break;
                            case 1:  break;
                            }
                        }
                    }
                    ImGui::EndPopup();`

**Comment by Vadenez** [comment]
wow, thx

**Comment by TauCSGO** [comment]
> My delete confirm
> 
> ```c++
> if (ImGui::Button("Delete Config", { 100.0f, 25.0f }))
>                     ImGui::OpenPopup("Config to delete");
>                 if (ImGui::BeginPopup("Config to delete")) {
>                     static constexpr const char* names[]{ "Yes", "No" }; 
>                     for (int i = 0; i < IM_ARRAYSIZE(names); i++) {
>                         if (i == 1) ImGui::Separator();
>                 
>                         if (ImGui::Selectable(names[i])) {
>                             switch (i) {
>                             case 0: config->remove(currentConfig); break;
>                             case 1:  break;
>                             }
>                         }
>                     }
>                     ImGui::EndPopup();
> ```

Maybe the next update @danielkrupinski ?
