### ISSUE TITLE
[Request] Recoil Crosshair sepreate from CSGO Crosshair

### ISSUE THREAD

**Issue by Vadenez** [danielkrupinski/Osiris#1372]
(Idea)
    Would there be any way to have the Recoil Crosshair sepreate from the Crosshair in the middle of your screen? to make it visable it would also need some customiztion features, like being able to change its color. and either make it invisable until you start shooting, or somehow make it underlap the Csgo Crosshair, so that your csgo crosshair doesnt change color as you start to sprey.

**Comment by tirziz** [comment]
Csgosimple base have that, you can try to cp from it.

**Comment by dev-nocap** [comment]
Daniel's GOESP has that in it and I would assume it would be a near copy/paste from that to Osiris.
