### ISSUE TITLE
My resolver

### ISSUE THREAD

**Issue by notgoodusename** [danielkrupinski/Osiris#1373]
This was done with a bot.
Basically it traces 4 rays at 45 ,135,-45 and -135 grades apart from the current viewangle and sets pitch to 0 otherwise it would be looking at the ground and gets the distance from the head to the wall and set the yaw feet depending on that info.
Also i need some help detecting if a player is chocking packets currently it does it with every player.
Video:
https://streamable.com/czalvl

**Comment by HowToMakeFaceitAB** [comment]
> This was done with a bot.
> Basically it traces 4 rays at 45 ,135,-45 and -135 grades apart from the current viewangle and sets pitch to 0 otherwise it would be looking at the ground and gets the distance from the head to the wall and set the yaw feet depending on that info.
> Also i need some help detecting if a player is chocking packets currently it does it with every player.
> Video:
> https://streamable.com/czalvl

Hey, can you please help me merge your legit aa pull request with the cheat.
 : https://github.com/danielkrupinski/Osiris.git
 https://github.com/notgoodusename/Osiris-1.git
how do i do it

**Comment by HowToMakeFaceitAB** [comment]
im trying to git cloned both on my desktop and I can't git merge them, help?

**Comment by Scui1** [comment]
Detecting how many packets a player is choking can be done by doing simtime - oldsimtime - 1.  But that's not a reliable way to detect desync if you're trying to do that. Could you anyway share the code how you rotated the players in osiris?

**Comment by notgoodusename** [comment]
> Detecting how many packets a player is choking can be done by doing simtime - oldsimtime - 1. But that's not a reliable way to detect desync if you're trying to do that. Could you anyway share the code how you rotated the players in osiris?

cant right now, i just add the desync delta to their goalfeetyaw on frame_postdataupdate_start

**Comment by Cyk-Fad** [comment]
can you share it for free?

**Comment by notgoodusename** [comment]
> can you share it for free?

i will, when i finish the resolver
