### ISSUE TITLE
[error ?]

### ISSUE THREAD

**Issue by phoemeister** [danielkrupinski/Osiris#1375]
skin changer in 3734 commit didn't work?

**Comment by xAkiraMiura** [comment]
please refer to commits by their hash rather than their number. 
im assuming you ment 81702b9a9742fa21355699c44db9cd3686587745 (because that is commit 3734) and that had nothing to do with the skin changer

**Comment by phoemeister** [comment]
i know, but after update from latest commit skin changer doesn't work.
