### ISSUE TITLE
I want to know which function is to reduce recoil

### ISSUE THREAD

**Issue by 18339256125** [danielkrupinski/Osiris#1378]
reduce recoil

**Comment by xAkiraMiura** [comment]
its a single line of code that uses a netvar, doubles it, and adds it to the viewangle.

**Comment by 18339256125** [comment]
> 它是使用netvar的单行代码，将其加倍，然后将其添加到viewangle中。
I want to know how to do it, because I do n’t know much about it .plz

**Comment by HowToMakeFaceitAB** [comment]
it does it for you , well it's just recoil compensation so

**Comment by 18339256125** [comment]
> it does it for you , well it's just recoil compensation so

How to add it, can you write this code for me?plz

**Comment by xAkiraMiura** [comment]
https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hacks/Aimbot.cpp#L177
removing `+ aimPunch` would cause no recoil correction.
