### ISSUE TITLE
[idea] inventory changer

### ISSUE THREAD

**Issue by ToxicMods** [danielkrupinski/Osiris#1379]
i've seen most csgo cheats nowadays have a inventory changer and idk how to do it myself so i would like this to happen

**Comment by m0nsterJ** [comment]
that would be awesome

**Comment by xpossed-you** [comment]
there are skinchanger already in cheat, why need inventory changer?

**Comment by Zhxcky** [comment]
> there are skinchanger already in cheat, why need inventory changer?

to make it more legit? like legit we have these skins

**Comment by xAkiraMiura** [comment]
inventory changers are local only. they will not show up for anyone else.
how does that make it more legit.

**Comment by Zhxcky** [comment]
> inventory changers are local only. they will not show up for anyone else.
> how does that make it more legit.

when you streaming or recording, it will looks more legit.

**Comment by HowToMakeFaceitAB** [comment]
> inventory changers are local only. they will not show up for anyone else.
> how does that make it more legit.

while streaming or faking vids like bhop lol

**Comment by m0nsterJ** [comment]
@HowToMakeFaceitAB Bhop is not faking his videos, because in the videos,where he is cheating with a knife, he is using skeet and skeet has no inventory changer nor can you inject multiple cheats while having skeet injected.

**Comment by rosesware** [comment]
The only thing would be interesting if the inventory changer was added, was the fact that we can see the skins we want in our inventory, and we can have a skin for each side (CT & T). 

> and we can have a skin for each side (CT & T)

Updating the skin changer we can do that.

**Comment by rosesware** [comment]
> @HowToMakeFaceitAB Bhop is not faking his videos, because in the videos,where he is cheating with a knife, he is using skeet and skeet has no inventory changer nor can you inject multiple cheats while having skeet injected.

External one.

**Comment by xAkiraMiura** [comment]
pretty sure you have to do stuff with protobufs to fake the inventory, its different from the skin changer.
*P.S. which autist invited bhop to skeet*

**Comment by KernCS** [comment]
> pretty sure you have to do stuff with protobufs to fake the inventory, its different from the skin changer.
> _P.S. which autist invited bhop to skeet_

 [https://www.unknowncheats.me/forum/counterstrike-global-offensive/271136-inventory-changer-protobuf.html](you can do it without protobufs)

**Comment by HowToMakeFaceitAB** [comment]
> @HowToMakeFaceitAB Bhop is not faking his videos, because in the videos,where he is cheating with a knife, he is using skeet and skeet has no inventory changer nor can you inject multiple cheats while having skeet injected.

i was joking bro
