### ISSUE TITLE
FLASH Reduction still not implemented ?

### ISSUE THREAD

**Issue by Asado-san** [danielkrupinski/Osiris#138]
Where's the Flash reduction feature ?
[https://snag.gy/pjA4La.jpg](url)

but it was written in ReadMe ? that flash reduction was added ?
[https://snag.gy/KwDrpa.jpg](url)

**Comment by NexSqaud** [comment]
are you serious?
http://prntscr.com/ngl6aa

**Comment by effexcs** [comment]
Time for an epic/r/chosingbeggars
