### ISSUE TITLE
[idea] sound beam

### ISSUE THREAD

**Issue by Luzzik** [danielkrupinski/Osiris#1380]
Maybe add sound beam ?

**Comment by xpossed-you** [comment]
can you tell me what sound beam is?

**Comment by RyDeem** [comment]
yes please explain asntoxic, i am one for beams i love em, all long and beamyy but aint never heard one tho

**Comment by DoomFishWasTaken** [comment]
@asntoxic if you need it, DIY, I've already done the work for beams (#1546) and events are listed here: https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events
