### ISSUE TITLE
how to use a custom esp font?

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#1381]

**Comment by xAkiraMiura** [comment]
use ISurface::SetFontGlyphSet. it will be renamed to something else in Osiris but thats the original name. the second argument should be a `const char*` to an installed Windows font. put ttf file in `C:/Windows/Fonts` or run the font installer (from double clicking a ttf file and clicking install).

**Comment by Zhxcky** [comment]
> use ISurface::SetFontGlyphSet. it will be renamed to something else in Osiris but thats the original name. the second argument should be a `const char*` to an installed Windows font. put ttf file in `C:/Windows/Fonts` or run the font installer (from double clicking a ttf file and clicking install).
> the first argument is a font ID that you pass into font rendering functions.

where do i place that?

**Comment by xAkiraMiura** [comment]
im not helping you paste. read the instructions i gave and read up on ISurface (VGui).

**Comment by moonm00n** [comment]
learncpp.com

**Comment by moonm00n** [comment]
![image](https://user-images.githubusercontent.com/45876341/79226739-29699680-7e5f-11ea-9f89-149d2af931a9.png)
thanks

**Comment by moonm00n** [comment]
![image](https://user-images.githubusercontent.com/45876341/79239052-6a1ddb80-7e70-11ea-93fd-0d60c8c5b026.png)
