### ISSUE TITLE
How to change radar radius?

### ISSUE THREAD

**Issue by rein-C0** [danielkrupinski/Osiris#1385]
Hi,
I want to ask how to change radar radius? It is so small, I want it to be a little bigger.
Also I want to ask what is the best dll injector for csgo? 
Thank You

**Comment by Vadenez** [comment]
Personally I use "Xenos" as a dll injector:
Github page: https://github.com/DarthTon/Xenos
An exe Version, so you dont have to compile: https://www.unknowncheats.me/forum/general-programming-and-reversing/124013-xenos-injector-v2-0-a.html

As for changing the radar, if you mean changing itz size on your screen, that can be done through csgo commands or through the settings in csgo (size of radar is not related to Osiris).

But if you mean people showing up on the radar hack farther away, thats phisically imposible to do, as csgo loads only players othat are in the reletive same area of the map as you.

**Comment by Vadenez** [comment]
settings for the map in Csgo would be under the 'Game" Tab, just above where the crosshair settings are, alteritivly you can use a map to change your radar settings:
I use "Config Generator ✮ crashz & Misterio"
https://steamcommunity.com/sharedfiles/filedetails/?id=1325659427
