### ISSUE TITLE
Auto Accept doesn't work

### ISSUE THREAD

**Issue by vsnrytune** [danielkrupinski/Osiris#1387]
Pls fix

**Comment by toster234** [comment]
I think it's working properly. This function does not cause the "accept match" button to disappear.

**Comment by Vadenez** [comment]
I used it yesterday, it did work but my game didnt load into the map, though just restarting CSGO fixed it, and brought my into the game i had already accepted.

Also next time you post an issue describe what didnt work about it, as without that info helping you becomes harder.

**Comment by danielkrupinski** [comment]
Now "Auto accept" also updates the UI.
