### ISSUE TITLE
New Materials

### ISSUE THREAD

**Issue by OOF-RIF** [danielkrupinski/Osiris#1388]
The new materials im adding just show up as normal, what am I doing wrong. I have a suspicion that the materials im entering are not supported but I don't know.
http://prntscr.com/rv031p
http://prntscr.com/rv03cd
http://prntscr.com/rv03ji

**Comment by OOF-RIF** [comment]
yep all those materials are not from csgo, sorry for bothering

**Comment by xAkiraMiura** [comment]
if you have another cheat that uses the `ofstream` method of chams, you can terminate the game and the cheat will fail to delete the material files, using that you can get the material.
