### ISSUE TITLE
[suggestion]

### ISSUE THREAD

**Issue by bruteforcehacker** [danielkrupinski/Osiris#139]
I think you should add a name stealer
[https://github.com/AimTuxOfficial/AimTux/blob/master/src/Hacks/namestealer.h](url)

[https://github.com/AimTuxOfficial/AimTux/blob/master/src/Hacks/namestealer.cpp](url)

**Comment by NexSqaud** [comment]
https://github.com/danielkrupinski/Osiris/issues/135#issuecomment-486093257

**Comment by danielkrupinski** [comment]
Added.
