### ISSUE TITLE
[Question for community] What do ya'll use for a DLL Injector?

### ISSUE THREAD

**Issue by Vadenez** [danielkrupinski/Osiris#1390]
I've been having some problems witch CSGO prompting "VAC was unable to verify game session", seeing that I only use Osiris and I've when through other ways of getting rid of this message, I was thinking that it could be my injector (Xenos, https://github.com/DarthTon/Xenos) as its old and possible detected in some way.
even if Xenos is not the reason for CSGO's VAC prompt, I'd still like to know that ya'll use, so that I can change my injector.

Any suggestions for an injector?

**Comment by KernCS** [comment]
i have been using a modified version of randoinjector since november:)

**Comment by TauCSGO** [comment]
https://github.com/danielkrupinski/curiuminjector-csgo

**Comment by Vadenez** [comment]
@TauCSGO, I didnt know Daniel had a DLL injector, thx.

Also ill close this issue on the 10th, the more replies the better :)

**Comment by rosesware** [comment]
> https://github.com/danielkrupinski/curiuminjector-csgo

It's random injector but with `JunkCode.h`.

**Comment by Faysal1969** [comment]
im using RandoInjector

**Comment by xpossed-you** [comment]
using Process Hacker 2 in a long time, never get VAC.
if CSGO keep showing "VAC was unable to verify your game"
open Steam > Library | right click CSGO and go to properties > Local Files | click "Verify integrity pf game files" wait till its done

**Comment by Vadenez** [comment]
@xpossed-you, I've tryed that fix. I was using [freehourboost.com](url) for CSGO hours on the account so I think that had something to do with it. Hopfully it wont happen again anyways, as the Account i was using literally just got banned 2 hours ago, and I don't intend to use [freehourboost.com](url) again on another account...

**Comment by rosesware** [comment]
@Vadenez use [VAC Bypass Loader](https://github.com/danielkrupinski/VAC-Bypass-Loader).

**Comment by Vadenez** [comment]
I heard someone say that It currently doesnt work, do you use it? and does it work?
Also what exactly does it do? does it stop this message or somthing else?

**Comment by xpossed-you** [comment]
> 
> 
> @xpossed-you, I've tryed that fix. I was using [freehourboost.com](url) for CSGO hours on the account so I think that had something to do with it. Hopfully it wont happen again anyways, as the Account i was using literally just got banned 2 hours ago, and I don't intend to use [freehourboost.com](url) again on another account...

i use freehourboost.com for making my CSGO gameplay hours in my alt account, not banned and the account information never changed, freehourboost just joining a deathmatch (official MM) and then just spin in the same place, its not spinbot.... its just spinning at a normal speed.
