### ISSUE TITLE
[Request] Forward tracking 

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1391]
like backtracking but reversed, predicts player location. ex: https://www.youtube.com/watch?v=0nwifqSeJpU

**Comment by rosesware** [comment]
I never seen this before. It's pretty obvious, seems like perfect silent, weird.

**Comment by HowToMakeFaceitAB** [comment]
> I never seen this before. It's pretty obvious, seems like perfect silent, weird.

Well it's like psilent but i won't appear like that to demos

**Comment by CallieOwO** [comment]
https://www.youtube.com/watch?v=066rFX2cibM
