### ISSUE TITLE
[Request] Multiple hitboxes for aimbot and triggerbot 

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1392]
the option to select hitboxes and not just a single hitbox or all hitboxes / nearest. i.e: Head, chest, stomach. real simple You let players choose what hitboxes to aimbot on( you don't use the hitboxes just exclude the ones that aren't selected from the aimbot)

**Comment by RyDeem** [comment]
yes this would be awesome, like checkmarks on the hitbox you want

id like to add that selecting arms/legs should be enabled too

**Comment by HowToMakeFaceitAB** [comment]
> yes this would be awesome, like checkmarks on the hitbox you want
> 
> id like to add that selecting arms/legs should be enabled too

Yeah i hope you can add that

**Comment by HowToMakeFaceitAB** [comment]
Can you make a pull request?

**Comment by thisisprettyepic** [comment]
crazy to me that this hasn’t been made yet
