### ISSUE TITLE
[Request] Server Selector/Changer

### ISSUE THREAD

**Issue by helpmewithcodingcplusplus** [danielkrupinski/Osiris#1395]
Every 1-2 matches, always mm with russian or eu player with 130 - 180 latency.
Or maybe, is there any solution to "always" join below 100~ latency server?

Thanks

**Comment by m0nsterJ** [comment]
Go into your console and type this command : mm_dedicater_search_maxping 50. That should fix it

**Comment by helpmewithcodingcplusplus** [comment]
> Go into your console and type this command : mm_dedicater_search_maxping 50. That should fix it

Thank you!!
