### ISSUE TITLE
How do i merge this 

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1396]
as an example, I'm trying to merge: https://github.com/danielkrupinski/Osiris.git
with: https://github.com/notgoodusename/Osiris-1.git
how do I do it?(please explain with detail since I'm really new to github)

**Comment by notgoodusename** [comment]
i didnt update that repository with my resolver

**Comment by HowToMakeFaceitAB** [comment]
> i didnt update that repository with my resolver

I know but I don't really care, please tell me how to merge

**Comment by xAkiraMiura** [comment]
not a github thing, its a git thing.
with the command line you can type `git help merge`. it will open a web page in your browser.
also have fun resolving merge conflicts.

**Comment by HowToMakeFaceitAB** [comment]
> not a github thing, its a git thing.
> with the command line you can type `git help merge`. it will open a web page in your browser.
> also have fun resolving merge conflicts.

Merge confpict?

**Comment by mdilai** [comment]
GIT is a great tool for source managing. To do what you want just need to do one time

`git remote add notgoodusename https://github.com/notgoodusename/Osiris-1.git`
and then
```
git fetch --all
git merge notgoodusename/master
```
each time you want to merge updates from other remote branch.
I also recommend to enable "reuse recorded resolution” function of git repo using
`git config --global rerere.enabled true`
so git will teach itself how you deal with merge conflicts and will be able to reproduce it automatically during next merges.
