### ISSUE TITLE
Is it possible to add a skin search system

### ISSUE THREAD

**Issue by AlisaCiya** [danielkrupinski/Osiris#1397]
Skin searcher

**Comment by Vadenez** [comment]
So many people have asked for this its not even funny. and while its mostlikly possible It won't be coming out until year 2098, so its not happening.

**Comment by Cyk-Fad** [comment]
I made a skin search that can search Chinese and English, but I do n’t want to share it for free, if you are Chinese, you can add my QQ2476159893

**Comment by danielkrupinski** [comment]
Now you can search skins for certain weapon.
