### ISSUE TITLE
How could i get ragdoll chams

### ISSUE THREAD

**Issue by OOF-RIF** [danielkrupinski/Osiris#1398]
I dont just want the glow, I also want chams on them.

**Comment by Vadenez** [comment]
There isnt a current option for this in Osiris, even though its been wanted for a while.
If you what more info on why not, there are these Issues that got posted about it: #426, #944, #1187, #1299

**Comment by OOF-RIF** [comment]
> There isnt a current option for this in Osiris, even though its been wanted for a while.
> If you what more info on why not, there are these Issues that got posted about it: #426, #944, #1187, #1299
> Hopefully this helps you on your quest for a "ragdoll chams" or "dead chams"

I know it does not pass through dme, I was just wondering if it was possible for Daniel to add it as it looks epic
