### ISSUE TITLE
Are you planning to add an aim assist?

### ISSUE THREAD

**Issue by CSkya32** [danielkrupinski/Osiris#14]
First, you have a great project and I am using it for days without an vac ban :)!

I do not see code for an aim assist in osiris (but an aimbot which hopefully comes soon(?)), and would like to know if you are planning to add an aim assist with custom settings for humanization?
Even if not I will keep using your project and I am learning c++ atm so I can modify the cheat for myself too :+1:

**Comment by t9z** [comment]
Aimbot is going to be added soon like he said earlier. You can always implement it yourself and make a PR.
