### ISSUE TITLE
Aimbot Improvement Suggestion

### ISSUE THREAD

**Issue by TrackyBunny** [danielkrupinski/Osiris#140]
Hey. I hope y'all having fun with your projects :D

Alright, I think everybody here knows what they need. Smart Aimbot.

Now by me saying smart aimbot, all I'm saying is that... For example:
There are 2 enemies in a far distance. You start spraying one enemy with an ak-47 (for example) and the aimbot does its thing but doesn't really know on which entity it should lock so it picks the closest to the crosshair. 

You know what I'm saying?

You should make like, **if entity found and cmd->buttons in attack at do not let go of that current entity until he's dead, and if dead do not lock/search for other players until mouse1/attack key has let go**.

I think everybody will love that improvement. 

Thanks in advance.

**Comment by designer1337** [comment]
kill delay is way better than this
