### ISSUE TITLE
[Request] aa indicator + aa inverter

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1401]

**Comment by AbdallahMehiz** [comment]
#1257

**Comment by HowToMakeFaceitAB** [comment]
> #1257

Too many merge conflicts, why not add it into the cheat?

**Comment by HowToMakeFaceitAB** [comment]
> #1257

no thanks

**Comment by xAkiraMiura** [comment]
> 
> 
> > #1257
> 
> Too many merge conflicts, why not add it into the cheat?

???

**Comment by DoctorYasin** [comment]
@xAkiraMiura #1257 
fixed by cs:go. can you repair it for me

**Comment by HowToMakeFaceitAB** [comment]
> @xAkiraMiura #1257
> 
> not working

thanks for passing the message
