### ISSUE TITLE
#1391

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1403]
#1391 
good posts never get enough attention

**Comment by m0nsterJ** [comment]
That's pretty fucking true.

**Comment by designer1337** [comment]
It's not even good post, forwardtracking is useless

**Comment by HowToMakeFaceitAB** [comment]
> It's not even good post, forwardtracking is useless

what do you mean it's useless? if you are legit hacking it's useful, please if you want to say something explain it

**Comment by coron3hotdog** [comment]
forward tracking predicts player's movements, if the player moves in a different direction or change the velocity, you will overshoot

**Comment by HowToMakeFaceitAB** [comment]
> forward tracking predicts player's movements, if the player moves in a different direction or change the velocity, you will overshoot

Forgot about peeking?

**Comment by xpossed-you** [comment]
why you crying when your posts doesnt get enough attention? it took a time to make new features in a cheat

**Comment by xAkiraMiura** [comment]
ive seen better issues. you know, ones made by people that have tried doing something and not just begging?
please refer to [this page on stackoverflow](https://stackoverflow.com/help/how-to-ask)
