### ISSUE TITLE
daniel hasn't made any updates in 2 days?

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1404]
I am just wondering if you are working on a new feature that's it, I don't care if you release updates regularly or not 
ps: quality over quantity

**Comment by streamshark** [comment]
if he is you will see it in commits when it's done

**Comment by xAkiraMiura** [comment]
> if he is you will see it in commits when it's done

commas are important. i read it as "if he is you" initially. ~~pls fix~~

Daniel mades very little profit off of Osiris. it is free and all money recieved is from donations. He probably has a job and can't dedicate all his time on the project.
^ he also has to update GOESP, another project he is working on.

**Comment by HowToMakeFaceitAB** [comment]
> > if he is you will see it in commits when it's done
> 
> commas are important. i read it as "if he is you" initially. ~pls fix~
> 
> Daniel mades very little profit off of Osiris. it is free and all money recieved is from donations. He probably has a job and can't dedicate all his time on the project.
> ^ he also has to update GOESP, another project he is working on.

I didn't know

**Comment by streamshark** [comment]
> > if he is you will see it in commits when it's done
> 
> commas are important. i read it as "if he is you" initially. ~pls fix~
> 
> Daniel mades very little profit off of Osiris. it is free and all money recieved is from donations. He probably has a job and can't dedicate all his time on the project.
> ^ he also has to update GOESP, another project he is working on.

added a comma, also according to daniel's github profile he works for epic games (or is at least in their org on github)
