### ISSUE TITLE
skeleton esp + ragdoll chams

### ISSUE THREAD

**Issue by CantRememberMyself** [danielkrupinski/Osiris#1405]
over requested feature i am aware but i would really love to see skeleton esp in osiris
also ragdoll chams

**Comment by mattys0229** [comment]
for the skeleton do world to screen for example:
    Vector head;
    if (!worldToScreen(entity->getBonePosition(8), head))
        return;
will give you the head position (head.x, head.y)
and then do 
    interfaces->surface->drawLine(head.x, head.y, body.x, body.y)

im not so good at cpp but this should work.
