### ISSUE TITLE
[Request] Head Level Indicator

### ISSUE THREAD

**Issue by Araptois** [danielkrupinski/Osiris#1407]
Hi, Daniel.

I was thinking of a feature that could be interesting and which is for example on the Letalithy cheat, the fact of having a Head Level Indicator, which indicates our crosshair placement.
As on these pictures below, it could be very interesting as legit features

[https://prnt.sc/rww0x0](https://prnt.sc/rww0x0)
[https://prnt.sc/rww1f6](https://prnt.sc/rww1f6)

**Comment by rosesware** [comment]
I think its very unnecessary, there are many features that would be much more relevant, as the skeleton in Esp.

**Comment by Vadenez** [comment]
theres a head esp aswell, but I would still love this feature.

**Comment by Araptois** [comment]
> 
> 
> I think its very unnecessary, there are many features that would be much more relevant, as the skeleton in Esp.

I think that adding this feature would be very useful for those who simply don't use ESP, to avoid having the human reflex to look through walls for example and get banned by Overwatch. Whereas if we use the Head Level Indicator, we just know where to place our viewfinder, which can drastically increase our head count while remaining legit!

**Comment by Araptois** [comment]
> 
> 
> theres a head esp aswell, but I would still love this feature.

Yes, but the head esp gives at the same time the position of the players, and that's where the HLI could be interesting ! :p

**Comment by rosesware** [comment]
What I'm trying to say is, would be a completely unusable feature because anyone with 2 brain cells knows where to place the crosshair and I also don't think that will change anything because this feature would be useful for people who don't use aimbot and we both know that all people uses aimbot even if it's minimal.

**Comment by Araptois** [comment]
> 
> 
> What I'm trying to say is, would be a completely unusable feature because anyone with 2 brain cells knows where to place the crosshair and I also don't think that will change anything because this feature would be useful for people who don't use aimbot and we both know that all people uses aimbot even if it's minimal.

Oh, okay, I see what you mean. After all, it might not be necessary for everyone, but it's a feature that can be used, and it's still a plus. With an aimbot it could be even more efficient than the aimbot alone, but I understand your point of view.

**Comment by Vadenez** [comment]
@rosesware, personally I don't use aimbot, not even a little, so in mysituation this feature is so useful. As I personally don't have good crosshair placement when watching corners.

**Comment by xpossed-you** [comment]
i do what i can, but i think its pretty useless, even a person with no experience of this game know where to put his crosshair to a head level

**Comment by xpossed-you** [comment]
> 
> 
> @rosesware, personally I don't use aimbot, not even a little, so in my situation this feature is so useful. As I personally don't have good crosshair placement when watching corners.

bruh

**Comment by dctrlight** [comment]
If you can't figure out head level without cheats you shouldn't be cheating

**Comment by Araptois** [comment]
> 
> 
> If you can't figure out head level without cheats you shouldn't be cheating

If we're gonna follow your reasoning, then we might as well not cheat, man, if there's no point.

**Comment by xpossed-you** [comment]
Lethality is shit btw

**Comment by m0nsterJ** [comment]
@xpossed-you This issue is about a head level indicator, not about shit-talking other cheats.
