### ISSUE TITLE
Wireframe Smoke not working

### ISSUE THREAD

**Issue by AnimeniacSimey** [danielkrupinski/Osiris#1408]
Title. I have the box checked but I can't see smokes!

**Comment by RyDeem** [comment]
but do you see the smoke wireframe?
Please provide a screenshot if possible.

**Comment by Cyk-Fad** [comment]
My Osiris Is working.
Is your code changed ?

**Comment by AnimeniacSimey** [comment]
> but do you see the smoke wireframe?
> Please provide a screenshot if possible.
No, I do not see the wireframe. Here is a video: [Google Drive](https://drive.google.com/file/d/1LYn-863GwaVNpi0wYDtP8NuVMoi9cg86/view?usp=sharing)

**Comment by AnimeniacSimey** [comment]
> My Osiris Is working.
> Is your code changed ?

@Cyk-Fad The cheat itself is working, just not the wireframe smoke. The code is slightly changed, I injected junk code.

**Comment by danielkrupinski** [comment]
You have "No smoke" checked also.

**Comment by xpossed-you** [comment]
hahahahhah

**Comment by AnimeniacSimey** [comment]
> You have "No smoke" checked also.

🤦‍♂️🤦‍♂️🤦‍♂️
