### ISSUE TITLE
Crash if select sticker on AK-47

### ISSUE THREAD

**Issue by playday3008** [danielkrupinski/Osiris#1410]
https://www.youtube.com/watch?v=9jw11VhyDRA
don't look on OsirisBETA, in my code SkinChanger untouched.

**Comment by playday3008** [comment]
1,3 sticker slot

**Comment by playday3008** [comment]
https://youtu.be/lsSUovk4bOw?t=60

**Comment by danielkrupinski** [comment]
The problem doesn't seem to exist in unmodified source code.

**Comment by danielkrupinski** [comment]
The issue existed only in certain locales, fixed in cdfd00750fc67c52afbbf2cf54c33bfef09dac16

**Comment by playday3008** [comment]
https://youtu.be/ZMptQ1YZhns unmodified source code.

**Comment by playday3008** [comment]
Working, thanks
