### ISSUE TITLE
Seeking info on localplayer current weapon equiped

### ISSUE THREAD

**Issue by RyDeem** [danielkrupinski/Osiris#1417]
I am trying to make a call of duty-esq mod for csgo inside osiris, with the goal of right click to look down sights. (That changes the viewmodel if crouched/standing acordingly for each weapon diferently)

I need help, i cant find a good way to get the current weapon.

Currently i am using some code like

```
const auto viewmodel_offset_x = interfaces->cvar->findVar("viewmodel_offset_x");
const auto viewmodel_offset_y = interfaces->cvar->findVar("viewmodel_offset_y");
const auto viewmodel_offset_z = interfaces->cvar->findVar("viewmodel_offset_z");

const auto activeWeaponClassId = localPlayer->getActiveWeapon()->getClientClass()->classId;

        if (activeWeaponClassId == ClassId::C4) {
            if (viewmodel_offset_x != 0) { viewmodel_offset_x->setValue(0); };
            if (viewmodel_offset_y != 0) { viewmodel_offset_y->setValue(0); };
            if (viewmodel_offset_z != 0) { viewmodel_offset_z->setValue(0); };
        };
```

The problem is that in osiris the classID list is not complete, there are not all weapons/equiped grenades in ClassId.h

```
BaseCSGrenadeProjectile = 9,
    BreachChargeProjectile = 29,
    BumpMineProjectile = 33,
    C4,
    Chicken = 36,
    CSPlayer = 40,
    CSRagdoll = 42,
    Deagle = 46,
    DecoyProjectile = 48,
    Drone,
    Dronegun,
    EconEntity = 53,
    EconWearable,
    Hostage = 97,
    Healthshot  = 104,
    Cash,
    Knife = 107,
    KnifeGG,
    MolotovProjectile = 113,
    AmmoBox = 124,
    LootCrate,
    RadarJammer,
    WeaponUpgrade,
    PlantedC4,
    PropDoorRotating = 142,
    SensorGrenadeProjectile = 152,
    SmokeGrenadeProjectile = 156,
    SnowballProjectile = 160,
    Tablet = 171,
    Aug = 231,
    Awp,
    Elite = 238,
    FiveSeven = 240,
    G3sg1,
    Glock = 244,
    P2000,
    P250 = 257,
    Scar20 = 260,
    Sg553 = 264,
    Ssg08 = 266,
    Tec9 = 268
```

So i am looking for a better way to get the weapon currently equipped for local player

OR

A way to add more weapons to ClassID, if that would even work.

Thank you in advance :)

**Comment by danielkrupinski** [comment]
For precise weapon identification use `WeaponId`.

**Comment by danielkrupinski** [comment]
Also don't forget to check if local player and active weapon is valid to prevent crashes.

**Comment by RyDeem** [comment]
Thank you for WeaponId, did not know that yet. 🗡️ 

If you can help with one more thing, why am i getting an error here, and how would i go about using the ConVars with Int?

For this code for example i am getting an error on " != "
Convar and int incompatible
```
const auto sv_minSpecCvar = interfaces->cvar->findVar("sv_competitive_minspec");
if (sv_minSpecCvar != 1) { sv_minSpecCvar->setValue(1); };
```
But code that checks against 0 works tho - like

`if (sv_minSpecCvar != 0) { sv_minSpecCvar->setValue(0); };`

**Comment by RyDeem** [comment]
== 0 
not 
!= 1 
i found out.

**Comment by xAkiraMiura** [comment]
in your case `!= 0` is acting as a null check. 
you need to use `CVar::getInt()`

    if (sv_minSpecCvar->getInt() != 1) {
        sv_minSpecCvar->setValue(1);
    };
