### ISSUE TITLE
getInt/getFloat Syntax help

### ISSUE THREAD

**Issue by RyDeem** [danielkrupinski/Osiris#1418]
i cant get convars working in my code, is there something i have to do with it else?

`int crosshairR = interfaces->cvar->findVar("cl_crosshaircolor_r");`

error on text "interfaces" = 
a value of type "ConVar *" cannot be used to initialize an entity of type "int"

so im looking for how to initialize it.
Is " static_cast " helpful here? if so how do i use it? 

Thank you in advance anyone :)

//
(even if i use " auto " on crosshairR not int i will get the same error down the line later in code that tries to int it like here 

`interfaces->surface->setDrawColor(crosshairR, crosshairG, crosshairB, 255);`

 it wants int but gets ConVar and freaks out.

//
I can change the value directly with ->setValue but im having trouble when trying to read it, and set a int/bool/whatever with a ConVar.

**Comment by danielkrupinski** [comment]
https://github.com/danielkrupinski/Osiris/blob/master/Osiris/SDK/ConVar.h

**Comment by xAkiraMiura** [comment]
[ftfy](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/SDK/ConVar.h#L8)

**Comment by RyDeem** [comment]
I saw that get func, but i must be missing something simple then aswell, because this code for example does not work, maybe my syntax is wrong?

```
                                                                                    ////////
const float viewmodel_offset_x   = interfaces->cvar->findVar("viewmodel_offset_x")->getFloat;
                                               //// error here //////
if (viewmodel_x_default != viewmodel_offset_x) { viewmodel_x_default->setValue(viewmodel_offset_x); };
```

expression must have a pointer type


Prob im just doing something simple wrong as always, but this is how i learn xd


/////////
I have made stuff with the limited knowledge i have, check it out if you want to :)
https://gist.github.com/RyDeem/3c77986be70802742b02d9e51b0537d1
(its a Viewmodel changer XYZ GUI interface with cl_righthand integration as well)

**Comment by effex1337** [comment]
interfaces.cvar->findVar();

**Comment by RyDeem** [comment]
> interfaces.cvar->findVar();

Yes but that just returns the ConVar raw, its is still 
" ConVar .function name. value " 
not 
" float/int/bool/ .function name. value "

Or maybe you are commenting on ConVar in general.

**Comment by effex1337** [comment]
interfaces.cvar->findVar()->getValue();

**Comment by RyDeem** [comment]
interfaces.cvar->findVar()->getValue(); = Convar has no member getValue();

and

interfaces.cvar->findVar()->getfloat();   = expression must have a pointer type error

there also is an arrow between interfaces->cvar as well?

**Comment by effex1337** [comment]
https://github.com/danielkrupinski/Osiris/blob/00b4a657d547e6a3df2734bd2107c1297ed4db8f/Osiris/Hacks/Esp.cpp#L195

**Comment by effex1337** [comment]
static auto gameType{ interfaces->cvar->findVar("game_type") };
            static auto survivalMaxHealth{ interfaces->cvar->findVar("sv_dz_player_max_health") };

            const auto maxHealth{ (std::max)((gameType->getInt() == 6 ? survivalMaxHealth->getInt() : 100), entity->health()) };

More than enough info

**Comment by RyDeem** [comment]
i seem 2 have found the issue.

I thought i can add the getInt() to the 
static auto survivalMaxHealth{ interfaces->cvar->findVar("sv_dz_player_max_health") };

like 
static auto survivalMaxHealth{ interfaces->cvar->findVar("sv_dz_player_max_health")->getInt };

but i gotta do it next step down the line.

Thank you for your input kind sirs.
