### ISSUE TITLE
no recoil

### ISSUE THREAD

**Issue by yanghoxom** [danielkrupinski/Osiris#1419]
Anyone can tell me about it ?
i see features include it but dont found after inject

**Comment by RyDeem** [comment]
Do you mean this? -> No visual recoil - remove visual recoil punch effect

That is visual recoil, not the spray pattern.

**Comment by memsenpai** [comment]
@RyDeem I tried `no aimpunch` in visual
Seems like it's not what I expected
What I expected was that when I dried with the gun, there was no recoil.
I hold the mouse and all the bullets will fall to one point at crosshair
i think it mean "norecoil"

**Comment by VuBrian22** [comment]
What your looking for from your descriptions is Standalone RCS. As mentioned before by @RyDeem the no recoil that you tried out is only eliminating the "Visual Recoil" and "not the spray pattern". Under the Main Aim Tab though, there is Aim RCS. It might not satisfy your needs but it still is slightly leaning towards "controlling your recoil"and not fully eliminating it.

**Comment by memsenpai** [comment]
@VuBrian22 BUt i don't use Aimbot. i think it is risk. I'm just use trigger and want trigger also have recoil control
and about recoil control in Aimbot tab, it not exists in code and view. `README.md` write about it but i can not found it in code or UI
```
Recoil control x - horizontal recoil control factor
Recoil control y - vertical recoil control factor
```

**Comment by xAkiraMiura** [comment]
recoil control scripts are very noticeable.
if you have **any** trained muscle memory then even a weak RCS will mess with your recoil control.

**Comment by memsenpai** [comment]
@xAkiraMiura it mean use recoil control make hight chance detect ?

**Comment by steel4me** [comment]
I don't get it. This fucking nonsense. The missing "Standalone Recoil Control System" in Osiris. It is like the missing penis in the osiris myth. Isis had to rebuild osiris penis with magic, cause it was eaten by a fish!

**Comment by xAkiraMiura** [comment]
> 
> 
> @xAkiraMiura it mean use recoil control make hight chance detect ?

if you've ever watched someone use a RCS it is very blatant. (overwatch)
it probably doesn't have a chance of getting VAC detected.

**Comment by steel4me** [comment]
> > @xAkiraMiura it mean use recoil control make hight chance detect ?
> 
> if you've ever watched someone use a RCS it is very blatant. (overwatch)
> it probably doesn't have a chance of getting VAC detected.

Can't confirm this. Standalone RCS is standard, everyone who is able to use Standalone RCS will do this. You will not get OW with RCS. It looks much much much more unlegit when you use osiris with rcs while aimbot is active with spraydown, cause when you enemy is dead RCS turns off and your shots will go up to the sky. **This looks super ultra unlegit and blatant**.

**Comment by vsnrytune** [comment]
> > @xAkiraMiura it mean use recoil control make hight chance detect ?
> 
> if you've ever watched someone use a RCS it is very blatant. (overwatch)
> it probably doesn't have a chance of getting VAC detected.

yeah, no, rcs is definitey not very blatant. I use steel4me's RCS code at like 0.35 and I'm doing perfectly fine, have been using it in every other legit cheat and never got overwatch banned
