### ISSUE TITLE
Night mode 

### ISSUE THREAD

**Issue by skiterr** [danielkrupinski/Osiris#142]
hi , I noticed a slight underdevelopment in brightness, so as to reduce the value so to 0.08 0.06 everything is darkened, it would be nice if the weapon looks normal champses and also a skybox, and there would be useful skyboxes such as galaxy it would be nice. Slightly not worked out in the glow visible type 1 , e. g. you can't see the highlighted hand only when you notice the whole body will start to illuminate. Several types of glows in visible cool heads would notice.

**Comment by Shuvi-Moro** [comment]
@danielkrupinski close this
