### ISSUE TITLE
Can anyone tell me why it's not working ?

### ISSUE THREAD

**Issue by Mistrz1337** [danielkrupinski/Osiris#1420]
void Misc::LeftHandKnife() noexcept 
{
    static ConVar* cl_righthand = interfaces->cvar->findVar("cl_righthand");
        const auto activeWeapon = localPlayer->getActiveWeapon();
        bool Knife = 0;
        if (const auto activeWeapon = localPlayer->getActiveWeapon(); activeWeapon && activeWeapon->getClientClass()->classId == ClassId::Knife)
            Knife = 1;
        else
            Knife = 0;
        if (!Knife) 
        {
            if (!config->misc.lefthandknife) 
            {
                cl_righthand->setValue(1);
            }
            else {
                cl_righthand->setValue(0);
            };
        };
}
![image](https://user-images.githubusercontent.com/46001149/79147994-1c986480-7dc5-11ea-88fc-efc6f429d212.png)

**Comment by RyDeem** [comment]
Please, when using the code function select drag mouse your text and then click the code button.
It makes it all in the code box.

and i think you just need 2 change one ! on 
```
if (!Knife)
{
if (!config->misc.lefthandknife)
```
to 
```
if (Knife)
{
if (!config->misc.lefthandknife)
```

I may be wrong tho

**Comment by rosesware** [comment]
```
void Misc::leftHandKnife() noexcept
{
	if (config->misc.leftHandKnife) {
		static auto knifeVar = interfaces->cvar->findVar("cl_righthand");

		if (!localPlayer || !localPlayer->isAlive()) return;

		const auto activeWeapon = localPlayer->getActiveWeapon();
		if (!activeWeapon) return;

		activeWeapon->isKnife() ? knifeVar->setValue(0) : knifeVar->setValue(1);
	}
}
```
This should work.

**Comment by Mistrz1337** [comment]
> ```
> void Misc::leftHandKnife() noexcept
> {
> 	if (config->misc.leftHandKnife) {
> 		static auto knifeVar = interfaces->cvar->findVar("cl_righthand");
> 
> 		if (!localPlayer || !localPlayer->isAlive()) return;
> 
> 		const auto activeWeapon = localPlayer->getActiveWeapon();
> 		if (!activeWeapon) return;
> 
> 		activeWeapon->isKnife() ? knifeVar->setValue(0) : knifeVar->setValue(1);
> 	}
> }
> ```
> 
> This should work.

nope ;( but ty for try

**Comment by rosesware** [comment]
> > ```
> > void Misc::leftHandKnife() noexcept
> > {
> > 	if (config->misc.leftHandKnife) {
> > 		static auto knifeVar = interfaces->cvar->findVar("cl_righthand");
> > 
> > 		if (!localPlayer || !localPlayer->isAlive()) return;
> > 
> > 		const auto activeWeapon = localPlayer->getActiveWeapon();
> > 		if (!activeWeapon) return;
> > 
> > 		activeWeapon->isKnife() ? knifeVar->setValue(0) : knifeVar->setValue(1);
> > 	}
> > }
> > ```
> > 
> > 
> > This should work.
> 
> nope ;( but ty for try

What is getting error?

**Comment by Mistrz1337** [comment]
> > > ```
> > > void Misc::leftHandKnife() noexcept
> > > {
> > > 	if (config->misc.leftHandKnife) {
> > > 		static auto knifeVar = interfaces->cvar->findVar("cl_righthand");
> > > 
> > > 		if (!localPlayer || !localPlayer->isAlive()) return;
> > > 
> > > 		const auto activeWeapon = localPlayer->getActiveWeapon();
> > > 		if (!activeWeapon) return;
> > > 
> > > 		activeWeapon->isKnife() ? knifeVar->setValue(0) : knifeVar->setValue(1);
> > > 	}
> > > }
> > > ```
> > > 
> > > 
> > > This should work.
> > 
> > 
> > nope ;( but ty for try
> 
> What is getting error?

its not working in game

**Comment by xpossed-you** [comment]
> 
> 
> > > > ```
> > > > void Misc::leftHandKnife() noexcept
> > > > {
> > > > 	if (config->misc.leftHandKnife) {
> > > > 		static auto knifeVar = interfaces->cvar->findVar("cl_righthand");
> > > > 
> > > > 		if (!localPlayer || !localPlayer->isAlive()) return;
> > > > 
> > > > 		const auto activeWeapon = localPlayer->getActiveWeapon();
> > > > 		if (!activeWeapon) return;
> > > > 
> > > > 		activeWeapon->isKnife() ? knifeVar->setValue(0) : knifeVar->setValue(1);
> > > > 	}
> > > > }
> > > > ```
> > > > 
> > > > 
> > > > This should work.
> > > 
> > > 
> > > nope ;( but ty for try
> > 
> > 
> > What is getting error?
> 
> its not working in game

success in compiling the dll but not working in game?

**Comment by xAkiraMiura** [comment]
> 
> 
> Please, when using the code function select drag mouse your text and then click the code button.
> It makes it all in the code box.
> 
> and i think you just need 2 change one ! on
> 
> ```
> if (!Knife)
> {
> if (!config->misc.lefthandknife)
> ```
> 
> to
> 
> ```
> if (Knife)
> {
> if (!config->misc.lefthandknife)
> ```
> 
> I may be wrong tho

the point of !Knife it checking if it is nullptr. i don't think doing the opposite would work.

> > ~
>
> success in compiling the dll but not working in game?

you should attach a debugger and go to the locals tab to see what the value of everything is.

**Comment by CerberusGame** [comment]
> ```
> void Misc::leftHandKnife() noexcept
> {
> 	if (config->misc.leftHandKnife) {
> 		static auto knifeVar = interfaces->cvar->findVar("cl_righthand");
> 
> 		if (!localPlayer || !localPlayer->isAlive()) return;
> 
> 		const auto activeWeapon = localPlayer->getActiveWeapon();
> 		if (!activeWeapon) return;
> 
> 		activeWeapon->isKnife() ? knifeVar->setValue(0) : knifeVar->setValue(1);
> 	}
> }
> ```
> 
> This should work.

give your Entity isKnife code ..

**Comment by rosesware** [comment]
> > ```
> > void Misc::leftHandKnife() noexcept
> > {
> > 	if (config->misc.leftHandKnife) {
> > 		static auto knifeVar = interfaces->cvar->findVar("cl_righthand");
> > 
> > 		if (!localPlayer || !localPlayer->isAlive()) return;
> > 
> > 		const auto activeWeapon = localPlayer->getActiveWeapon();
> > 		if (!activeWeapon) return;
> > 
> > 		activeWeapon->isKnife() ? knifeVar->setValue(0) : knifeVar->setValue(1);
> > 	}
> > }
> > ```
> > 
> > 
> > This should work.
> 
> give your Entity isKnife code ..

```
	constexpr auto isKnife() noexcept
	{
		return getWeaponType() == WeaponType::Knife;
	}
```

**Comment by CerberusGame** [comment]
> > > ```
> > > void Misc::leftHandKnife() noexcept
> > > {
> > > 	if (config->misc.leftHandKnife) {
> > > 		static auto knifeVar = interfaces->cvar->findVar("cl_righthand");
> > > 
> > > 		if (!localPlayer || !localPlayer->isAlive()) return;
> > > 
> > > 		const auto activeWeapon = localPlayer->getActiveWeapon();
> > > 		if (!activeWeapon) return;
> > > 
> > > 		activeWeapon->isKnife() ? knifeVar->setValue(0) : knifeVar->setValue(1);
> > > 	}
> > > }
> > > ```
> > > 
> > > 
> > > This should work.
> > 
> > 
> > give your Entity isKnife code ..
> 
> ```
> 	constexpr auto isKnife() noexcept
> 	{
> 		return getWeaponType() == WeaponType::Knife;
> 	}
> ```

not working

**Comment by xAkiraMiura** [comment]
attach a debugger. go to the locals tab and you will see the values.
