### ISSUE TITLE
What part of hooks.cpp initializes only once, not in a loop?

### ISSUE THREAD

**Issue by RyDeem** [danielkrupinski/Osiris#1421]
I need to know this to make a defaults grabbing thing that reads your cl_righthand on menu screen right after inject (among other things)

Is it createMove ?

to add some relevant code to this issue = 

```
    const auto cl_righthand_default = config->visuals.viewmodel_xyz_clright_default;
    const auto cl_righthandCvar     = interfaces->cvar->findVar("cl_righthand");

    if (cl_righthandCvar->getInt() == 0) { cl_righthand_default == 0; } else { cl_righthand_default == 1; };
```

Code should be good, i just want 2 know where 2 hook this correctly.

(and i know i could use ? and : for else like x ? y : z, i just dont feel comfortable with that just yet xd)

**Comment by notgoodusename** [comment]
> I need to know this to make a defaults grabbing thing that reads your cl_righthand on menu screen right after inject (among other things)
> 
> Is it createMove ?
> 
> to add some relevant code to this issue =
> 
> ```
>     const auto cl_righthand_default = config->visuals.viewmodel_xyz_clright_default;
>     const auto cl_righthandCvar     = interfaces->cvar->findVar("cl_righthand");
> 
>     if (cl_righthandCvar->getInt() == 0) { cl_righthand_default == 0; } else { cl_righthand_default == 1; };
> ```
> 
> Code should be good, i just want 2 know where 2 hook this correctly.
> 
> (and i know i could use ? and : for else like x ? y : z, i just dont feel comfortable with that just yet xd)

use framestagenotify on framerenderstart

**Comment by xAkiraMiura** [comment]
hooks is an object so it most certainly has a constructor.
If we check in Osiris.cpp we see that hooks gets initialized last so the convar system is always available.
^ just put it in the initializer rather than waiting for the game to call a hook.

**Comment by RyDeem** [comment]
yeah for some reason i thouth that hooks is the first thing to initialize in the cheat, but now i know better.

Kinda made sense to me to Hook things first, 

Thank you for your feedback guys.
