### ISSUE TITLE
Weapon Chams

### ISSUE THREAD

**Issue by Rrhyast** [danielkrupinski/Osiris#1422]
Weapon chams only work on local player please fix.

**Comment by Vadenez** [comment]
Do you mean that they only work when in your hand?

**Comment by m0nsterJ** [comment]
@Vadenez  A quick google research about CS:GO game hacking will give you the answer.

**Comment by xAkiraMiura** [comment]
> 
> 
> Do you mean that they only work when in your hand?

doesn't apply when spectating other players. this doesn't work on the hands and sleves either iirc.

**Comment by effex1337** [comment]
Remove the is localplayer alive check

**Comment by effex1337** [comment]
if (!localPlayer || !localPlayer->isAlive() || localPlayer->isScoped())
        return;
Remove these in renderweapon,sleeve,weapon

**Comment by Vadenez** [comment]
@m0nsterJ, I know, I just wanted clarification from Rrhyast, that its what he was talking bout..
