### ISSUE TITLE
[Help]Legti AA  Chams

### ISSUE THREAD

**Issue by Cyk-Fad** [danielkrupinski/Osiris#1423]
#1257  How add Legit AA chams? I think we need it to ues legit AA

**Comment by moonm00n** [comment]
no, we dont

**Comment by Cyk-Fad** [comment]
emmmmmmmmmmmmmmm

**Comment by Cyk-Fad** [comment]
Why we don't ?

**Comment by moonm00n** [comment]
the antiaim isnt working very good, and the only thing people want are desync chams

**Comment by Cyk-Fad** [comment]
emmmmm

**Comment by Cyk-Fad** [comment]
My means #1257

**Comment by moonm00n** [comment]
what do you mean?

**Comment by Cyk-Fad** [comment]
#1257  I think we need a Legit AA chams

**Comment by Vadenez** [comment]
reading this gave me AIDS

**Comment by m0nsterJ** [comment]
@Vadenez Be fucking mature, AIDS is a serious disease so don't make jokes about it.

**Comment by xAkiraMiura** [comment]
no need to spam the issue with comments.
if you press `enter` it makes a newline so you can put lots of stuff in 1 comment.

> 
> 
> @Vadenez Be fucking mature, AIDS is a serious disease so don't make jokes about it.

aids lol

**Comment by DahKiwiDude** [comment]
being honest here if you struggle and fail to add desync chams to a cheat then you honestly need to do a lot more research into antiaims and how they work and why ther work as adding dysync chams is probably one of the easiest things to add to a cheat

**Comment by xpossed-you** [comment]
pls stop, im losing 79% of my braincells reading this

**Comment by Kron1Q** [comment]
> pls stop, im losing 79% of my braincells reading this

how u calculated that number? pls share <3

> I think we need it to ues legit AA
No, you dont need chams to use Anti Aim.
