### ISSUE TITLE
Color Picker issue

### ISSUE THREAD

**Issue by igothxps** [danielkrupinski/Osiris#1425]
So i added eso chams and i color modulated both the glow around the chams and the material its self my problem is the fact the pickers are flipped (i added an extra one bc you need two) 
![image](https://user-images.githubusercontent.com/51724664/79204789-1927cc00-7e0b-11ea-8714-5ad13dc15292.png)
my code 
        if (material == glow || material == chrome || material == plastic || material == glass || material == crystal || material == skeet) {
            auto material = dispatchMaterial(chams.material);
            if (material == skeet) {
                material->colorModulate(chams.color.color);
                material->colorModulate(chams.color.Glowoverlaycolor);

**Comment by xAkiraMiura** [comment]
general programming error, not specific to osiris.
[learncpp.com](https://learncpp.com)
*we literally have 2 chams per type so you can do overlays. there is no need for 2 color pickers at all when you change the material into an overlay.*

**Comment by igothxps** [comment]
Ok well for one ive tried it with the 2 chams per type thing didnt work for me 2 the color pickers are needed as you need to modulate that glow and the cham material. the glow comes on the material and isnt able to be changed without what i have done

**Comment by moonm00n** [comment]
u press that little arrow so you can use 2 chams types at the same time, now u can overlay your eso glow on top of normal chams

**Comment by igothxps** [comment]
@moonm00n as much as i appreciate you trying to help it doesnt work that way for me the eso glow still remains blue which was its default color before i added the second picker i did the 2 cham types and it still didnt do anything

**Comment by moonm00n** [comment]
1. eso glow chams are already in the cheat 2. you dont need to do the thing that youre doing in this cheat

**Comment by moonm00n** [comment]
u got it working?
