### ISSUE TITLE
Add Stream-proof pls <3

### ISSUE THREAD

**Issue by KikoCS** [danielkrupinski/Osiris#1427]
Hello, can u add stream-proof into Osiris? I will be very happy. Thanks <3

**Comment by effex1337** [comment]
just multi inject it with 
https://github.com/danielkrupinski/GOESP

**Comment by KikoCS** [comment]
Oh ok ill try it <3 Thank u.

**Comment by KikoCS** [comment]
So, im back. It works but i like to use chams and there is the problem. Its still visible in video. If you can do it so please add Stream-proof to Osiris <3 Thanks

**Comment by effex1337** [comment]
Chams weren't supposed to be steam proof. 
Even gamesense doesn't have stream proof chams.

**Comment by KikoCS** [comment]
Oh, ok thank you
