### ISSUE TITLE
Add features list

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#1428]
-better visuals (The text on the current visuals doesn't get smaller as you walk away and it just looks bad)
-legit aa
-block bot and run boost bot

**Comment by notmugi** [comment]
what do you mean by the visuals not getting smaller? they're not supposed to for visibility reasons.
legit aa would be nice, block bot is aight but i really would like the runboost bot

**Comment by kermacide** [comment]
> what do you mean by the visuals not getting smaller? they're not supposed to for visibility reasons.
> legit aa would be nice, block bot is aight but i really would like the runboost bot

it's like the visuals, more specifically the name/text is massive when close, and far away and it has really ugly fonts.
GOESP has a feature to choose the font and I'd like to see that implemented, plus it would basically be a copypaste to add it

**Comment by notmugi** [comment]
> > what do you mean by the visuals not getting smaller? they're not supposed to for visibility reasons.
> > legit aa would be nice, block bot is aight but i really would like the runboost bot
> 
> it's like the visuals, more specifically the name/text is massive when close, and far away and it has really ugly fonts.
> GOESP has a feature to choose the font and I'd like to see that implemented, plus it would basically be a copypaste to add it

You can actually change the font. Just pick something small. I use 145 which for me is an outlined font that looks really small and pixely. It's clean and rly nice. Might not be the same for you though, idk if it'll be the same based on your installed fonts

**Comment by kermacide** [comment]
> You can actually change the font. Just pick something small. I use 145 which for me is an outlined font that looks really small and pixely. It's clean and rly nice. Might not be the same for you though, idk if it'll be the same based on your installed fonts

Change the font in the code?

**Comment by notmugi** [comment]
> > You can actually change the font. Just pick something small. I use 145 which for me is an outlined font that looks really small and pixely. It's clean and rly nice. Might not be the same for you though, idk if it'll be the same based on your installed fonts
> 
> Change the font in the code?

No there is literally a font option in the ESP tab

**Comment by kermacide** [comment]
> > > You can actually change the font. Just pick something small. I use 145 which for me is an outlined font that looks really small and pixely. It's clean and rly nice. Might not be the same for you though, idk if it'll be the same based on your installed fonts
> > 
> > 
> > Change the font in the code?
> 
> No there is literally a font option in the ESP tab

i know theres one in goesp, im talking about osiris

**Comment by notmugi** [comment]
> > > > You can actually change the font. Just pick something small. I use 145 which for me is an outlined font that looks really small and pixely. It's clean and rly nice. Might not be the same for you though, idk if it'll be the same based on your installed fonts
> > > 
> > > 
> > > Change the font in the code?
> > 
> > 
> > No there is literally a font option in the ESP tab
> 
> i know theres one in goesp, im talking about osiris

YES. ITS IN OSIRIS TOO

**Comment by kermacide** [comment]
> > > > > You can actually change the font. Just pick something small. I use 145 which for me is an outlined font that looks really small and pixely. It's clean and rly nice. Might not be the same for you though, idk if it'll be the same based on your installed fonts
> > > > 
> > > > 
> > > > Change the font in the code?
> > > 
> > > 
> > > No there is literally a font option in the ESP tab
> > 
> > 
> > i know theres one in goesp, im talking about osiris
> 
> YES. ITS IN OSIRIS TOO

where?

**Comment by notmugi** [comment]
> > > > > > You can actually change the font. Just pick something small. I use 145 which for me is an outlined font that looks really small and pixely. It's clean and rly nice. Might not be the same for you though, idk if it'll be the same based on your installed fonts
> > > > > 
> > > > > 
> > > > > Change the font in the code?
> > > > 
> > > > 
> > > > No there is literally a font option in the ESP tab
> > > 
> > > 
> > > i know theres one in goesp, im talking about osiris
> > 
> > 
> > YES. ITS IN OSIRIS TOO
> 
> where?

I can't take a screenshot right now. But it's directly in the ESP tab. You need to update your cheat if it's not there. 
![unknown-3](https://user-images.githubusercontent.com/12789510/79310985-c3b2f400-7eca-11ea-942c-d29bbb8e583d.png)

**Comment by kermacide** [comment]
> > > > > > > You can actually change the font. Just pick something small. I use 145 which for me is an outlined font that looks really small and pixely. It's clean and rly nice. Might not be the same for you though, idk if it'll be the same based on your installed fonts
> > > > > > 
> > > > > > 
> > > > > > Change the font in the code?
> > > > > 
> > > > > 
> > > > > No there is literally a font option in the ESP tab
> > > > 
> > > > 
> > > > i know theres one in goesp, im talking about osiris
> > > 
> > > 
> > > YES. ITS IN OSIRIS TOO
> > 
> > 
> > where?
> 
> I can't take a screenshot right now. But it's directly in the ESP tab. You need to update your cheat if it's not there.
> ![unknown-3](https://user-images.githubusercontent.com/12789510/79310985-c3b2f400-7eca-11ea-942c-d29bbb8e583d.png)

do you mean the thing with arrows and the number?

**Comment by notmugi** [comment]
> > > > > > > > You can actually change the font. Just pick something small. I use 145 which for me is an outlined font that looks really small and pixely. It's clean and rly nice. Might not be the same for you though, idk if it'll be the same based on your installed fonts
> > > > > > > 
> > > > > > > 
> > > > > > > Change the font in the code?
> > > > > > 
> > > > > > 
> > > > > > No there is literally a font option in the ESP tab
> > > > > 
> > > > > 
> > > > > i know theres one in goesp, im talking about osiris
> > > > 
> > > > 
> > > > YES. ITS IN OSIRIS TOO
> > > 
> > > 
> > > where?
> > 
> > 
> > I can't take a screenshot right now. But it's directly in the ESP tab. You need to update your cheat if it's not there.
> > ![unknown-3](https://user-images.githubusercontent.com/12789510/79310985-c3b2f400-7eca-11ea-942c-d29bbb8e583d.png)
> 
> do you mean the thing with arrows and the number?

Yep, that's the font

**Comment by kermacide** [comment]
> > > > > > > > > You can actually change the font. Just pick something small. I use 145 which for me is an outlined font that looks really small and pixely. It's clean and rly nice. Might not be the same for you though, idk if it'll be the same based on your installed fonts
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Change the font in the code?
> > > > > > > 
> > > > > > > 
> > > > > > > No there is literally a font option in the ESP tab
> > > > > > 
> > > > > > 
> > > > > > i know theres one in goesp, im talking about osiris
> > > > > 
> > > > > 
> > > > > YES. ITS IN OSIRIS TOO
> > > > 
> > > > 
> > > > where?
> > > 
> > > 
> > > I can't take a screenshot right now. But it's directly in the ESP tab. You need to update your cheat if it's not there.
> > > ![unknown-3](https://user-images.githubusercontent.com/12789510/79310985-c3b2f400-7eca-11ea-942c-d29bbb8e583d.png)
> > 
> > 
> > do you mean the thing with arrows and the number?
> 
> Yep, that's the font

does it have fonts that are "baked" into the cheat like only 10 fonts or all installed fonts on pc?

**Comment by notmugi** [comment]
> > > > > > > > > You can actually change the font. Just pick something small. I use 145 which for me is an outlined font that looks really small and pixely. It's clean and rly nice. Might not be the same for you though, idk if it'll be the same based on your installed fonts
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Change the font in the code?
> > > > > > > 
> > > > > > > 
> > > > > > > No there is literally a font option in the ESP tab
> > > > > > 
> > > > > > 
> > > > > > i know theres one in goesp, im talking about osiris
> > > > > 
> > > > > 
> > > > > YES. ITS IN OSIRIS TOO
> > > > 
> > > > 
> > > > where?
> > > 
> > > 
> > > I can't take a screenshot right now. But it's directly in the ESP tab. You need to update your cheat if it's not there.
> > > ![unknown-3](https://user-images.githubusercontent.com/12789510/79310985-c3b2f400-7eca-11ea-942c-d29bbb8e583d.png)
> > 
> > 
> > do you mean the thing with arrows and the number?
> 
> Yep, that's the font

Alright, can we delete this? It is pretty unnecessary

**Comment by notmugi** [comment]
> > > > > > > > > > You can actually change the font. Just pick something small. I use 145 which for me is an outlined font that looks really small and pixely. It's clean and rly nice. Might not be the same for you though, idk if it'll be the same based on your installed fonts
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Change the font in the code?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > No there is literally a font option in the ESP tab
> > > > > > > 
> > > > > > > 
> > > > > > > i know theres one in goesp, im talking about osiris
> > > > > > 
> > > > > > 
> > > > > > YES. ITS IN OSIRIS TOO
> > > > > 
> > > > > 
> > > > > where?
> > > > 
> > > > 
> > > > I can't take a screenshot right now. But it's directly in the ESP tab. You need to update your cheat if it's not there.
> > > > ![unknown-3](https://user-images.githubusercontent.com/12789510/79310985-c3b2f400-7eca-11ea-942c-d29bbb8e583d.png)
> > > 
> > > 
> > > do you mean the thing with arrows and the number?
> > 
> > 
> > Yep, that's the font
> 
> does it have fonts that are "baked" into the cheat like only 10 fonts or all installed fonts on pc?

It's whatever's installed on your PC

**Comment by kermacide** [comment]
> > > > > > > > > > > You can actually change the font. Just pick something small. I use 145 which for me is an outlined font that looks really small and pixely. It's clean and rly nice. Might not be the same for you though, idk if it'll be the same based on your installed fonts
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Change the font in the code?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > No there is literally a font option in the ESP tab
> > > > > > > > 
> > > > > > > > 
> > > > > > > > i know theres one in goesp, im talking about osiris
> > > > > > > 
> > > > > > > 
> > > > > > > YES. ITS IN OSIRIS TOO
> > > > > > 
> > > > > > 
> > > > > > where?
> > > > > 
> > > > > 
> > > > > I can't take a screenshot right now. But it's directly in the ESP tab. You need to update your cheat if it's not there.
> > > > > ![unknown-3](https://user-images.githubusercontent.com/12789510/79310985-c3b2f400-7eca-11ea-942c-d29bbb8e583d.png)
> > > > 
> > > > 
> > > > do you mean the thing with arrows and the number?
> > > 
> > > 
> > > Yep, that's the font
> > 
> > 
> > does it have fonts that are "baked" into the cheat like only 10 fonts or all installed fonts on pc?
> 
> It's whatever's installed on your PC

ill check

**Comment by notmugi** [comment]
> > > > > > > > > > > > You can actually change the font. Just pick something small. I use 145 which for me is an outlined font that looks really small and pixely. It's clean and rly nice. Might not be the same for you though, idk if it'll be the same based on your installed fonts
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > Change the font in the code?
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > No there is literally a font option in the ESP tab
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > i know theres one in goesp, im talking about osiris
> > > > > > > > 
> > > > > > > > 
> > > > > > > > YES. ITS IN OSIRIS TOO
> > > > > > > 
> > > > > > > 
> > > > > > > where?
> > > > > > 
> > > > > > 
> > > > > > I can't take a screenshot right now. But it's directly in the ESP tab. You need to update your cheat if it's not there.
> > > > > > ![unknown-3](https://user-images.githubusercontent.com/12789510/79310985-c3b2f400-7eca-11ea-942c-d29bbb8e583d.png)
> > > > > 
> > > > > 
> > > > > do you mean the thing with arrows and the number?
> > > > 
> > > > 
> > > > Yep, that's the font
> > > 
> > > 
> > > does it have fonts that are "baked" into the cheat like only 10 fonts or all installed fonts on pc?
> > 
> > 
> > It's whatever's installed on your PC
> 
> ill check

Can we delete this wall of text please?

**Comment by notmugi** [comment]
@kermacide dude please, can we delete the massive replies and leave it to your original question?

**Comment by Shaxzy** [comment]
Osiris have the option to change the ESP font. It's the number in the ESP tab I believe.
>Font - esp text font number (from vgui_spew_fonts command)

**Comment by Vadenez** [comment]
@Shaxzy  that's font size. And you can change the font aswell, aslong as you have a tiny bit of c++ code knowledge, and the font installed on your computer. also dont ask me how to do this, but I have seen a post on the subject at one time, in the issues tab...

**Comment by notmugi** [comment]
@Vadenez it literally is not. you can go test that for yourself. scroll through the numbers. you'll get completely different fonts entirely. it's the EXACT same thing as GOESP, except it doesnt name them, they're just numbers

**Comment by notmugi** [comment]
![image](https://user-images.githubusercontent.com/12789510/79432041-43a78f80-7f99-11ea-9bf7-65cfae63614d.png)
take a look at this font. it's #145 for me, i'm not sure what it will be for you, but this is the one i typically use. and i set it through the esp menu

**Comment by Oly-UK** [comment]
#1257 #1048

**Comment by moonm00n** [comment]
![image](https://user-images.githubusercontent.com/45876341/79469171-1fcb6480-8000-11ea-85a5-a78dd42f41af.png)
ISurface setFontGlyphSet

**Comment by Cryforus** [comment]
Inventory Changer Would Be Cool
