### ISSUE TITLE
Hacks Tab list too big for small resolutions

### ISSUE THREAD

**Issue by big-lip-bob** [danielkrupinski/Osiris#1429]
![image](https://user-images.githubusercontent.com/41026257/79336097-6bf4a700-7f23-11ea-8f95-b0f5327e4290.png)
Self explanatory, make at least so the Config tab is frist so we can load them

**Comment by streamshark** [comment]
are you playing CSGO on a gameboy?

**Comment by danielkrupinski** [comment]
Sorry, currently I'm not planning a scalable menu implementation. You can autoload your config in one line of C++ code.
