### ISSUE TITLE
quick question about the color picker

### ISSUE THREAD

**Issue by notmugi** [danielkrupinski/Osiris#1432]
Hey, I'm looking to modify the appearance of the color picker. I've already done so to my liking with the check boxes, but can't seem to find where to modify the rendering of the color pickers. 

Any help would be greatly appreciated. i checked imguicustom but that doesnt seem to be quite what i'm looking for.
![image](https://user-images.githubusercontent.com/12789510/79424654-7ac47380-7f8e-11ea-9752-25164c312fe0.png) 
i'm looking to achieve a similar look to the checkboxes i created here, but obviously with the dynamic coloring of the color picker.

**Comment by Oly-UK** [comment]
look in imguiCustom.cpp :)

**Comment by Oly-UK** [comment]
wait nevermind

**Comment by notmugi** [comment]
@Oly-UK yeah that draws a checkbox, but my checkboxes are customized so that can't be right. It still looks different

**Comment by notmugi** [comment]
i'm also very confused because if it's drawing a checkbox just like the normal checkboxes in the GUI, it should be drawing them in a similar style, if i'm not mistaken. sorry if these are dumb questions. i just wanna figure this out and also understand why it's not doing what i expect it to do

**Comment by notmugi** [comment]
nevermind i figured it out! 
![image](https://user-images.githubusercontent.com/12789510/79626328-5c30ba80-80fd-11ea-91d3-7ee00c791a15.png)
