### ISSUE TITLE
aimbot problem

### ISSUE THREAD

**Issue by xSTN666** [danielkrupinski/Osiris#1433]
aimbot doesnt always pick the target closest to crosshair, how would i fix that?

**Comment by xAkiraMiura** [comment]
create a variable float with a value very high.
get the distance from the engine angles to the target angles
if the distance is lower than the variable then set the variable to the distance and store the entity index.
once the entity loop is completely finished grab the player at the stored index and then do the rest of the aimbot calculations with them.
