### ISSUE TITLE
horizontal ESP

### ISSUE THREAD

**Issue by Oly-UK** [danielkrupinski/Osiris#1438]
hey can someone help me make horizontal ESP, i don't really understand it and i would like to have armor bar at the bottom

**Comment by Oly-UK** [comment]
basically i want to achieve an ESP like this 
![image](https://user-images.githubusercontent.com/55945421/79478347-34f5c280-8003-11ea-882b-2ed6ca8322df.png)
the purple bar being the ammo bar i added in #1437 ;)

**Comment by notgoodusename** [comment]
and the blue one?

**Comment by Oly-UK** [comment]
> and the blue one?

armor

**Comment by notgoodusename** [comment]
ok use
interfaces->surface->drawOutlinedRect();
x is for horizontal and y for height

**Comment by Oly-UK** [comment]
yeah im aware of that i just dont really know what to do with it if i'm honest lmao

**Comment by Oly-UK** [comment]
> ok use
> interfaces->surface->drawOutlinedRect();
> x is for horizontal and y for height

i've been trying all day, it seemed so simple but apparently i don't have the brain capacity to do it, do you know how to do this?

**Comment by Oly-UK** [comment]
https://i.gyazo.com/045f754210114c13a62e51073aa164a8.mp4
            float offset = abs(bbox.y1 - bbox.y0) * (100.0f - entity->armor()) / 100.0f;
            interfaces->surface->drawFilledRect(bbox.x0 + offset, bbox.y0 + 3.f + drawPositionX, bbox.x1, bbox.y0 + 7.f + drawPositionX);

this is my best attempt yet, but still extremely off lmao

**Comment by Oly-UK** [comment]
@danielkrupinski could i get a hand please?

**Comment by Oly-UK** [comment]
![image](https://user-images.githubusercontent.com/55945421/79640144-d574ef80-8187-11ea-9cd0-657f517b3bfd.png)
@notgoodusename pog

**Comment by notgoodusename** [comment]
pog
