### ISSUE TITLE
what is the best fov for silent? 

### ISSUE THREAD

**Issue by smartxd3** [danielkrupinski/Osiris#1440]
what is the best legit fov for silent aim using ak or m4 without getting ow ban

**Comment by danielkrupinski** [comment]
Don't use silent at all, it's client-sided only.

**Comment by m0nsterJ** [comment]
I am usually using silent aim on scout and awp with a low fov like 1-2. Sometimes even on the deagle with like 0.5-1 fov (all weapons with no aimlock enabled)

**Comment by smartxd3** [comment]
> Don't use silent at all, it's client-sided only.

what is the best legit aimbot? using aimlock? but aimlock is so obv..

**Comment by smartxd3** [comment]
> I am usually using silent aim on scout and awp with a low fov like 1-2. Sometimes even on the deagle with like 0.5-1 fov (all weapons with no aimlock enabled)

so we can use silent with low fov without getting ow ban?

**Comment by RyDeem** [comment]
> Don't use silent at all, it's client-sided only.

well there is a difference, no silent = 
goes from what you are aiming at this moment to the aim target
Silent = 
Goes to the target AND comes back, like a fast flick.
and yes it can be seen, but with some ping wizardry can be hidden quite well.

**Comment by RyDeem** [comment]
> > I am usually using silent aim on scout and awp with a low fov like 1-2. Sometimes even on the deagle with like 0.5-1 fov (all weapons with no aimlock enabled)
> 
> so we can use silent with low fov without getting ow ban?

id say dont use silent if you dont want overwatch, actually dont use aim, walls at all xd //butThatsJustMy2c

**Comment by Zhxcky** [comment]
> > Don't use silent at all, it's client-sided only.
> 
> what is the best legit aimbot? using aimlock? but aimlock is so obv..

There's no different between silent aim and aimlock on server side, try to record demo w/silent aimbot and see the demo clip, it's flicks through your enemy body and comeback into your default views / current views, it just make it silent on client side not server side or other guy view.

**Comment by xAkiraMiura** [comment]
there is a difference from silent and aimlock: aimlock will follow the target after it initially locks on (if they are still in FOV range). silent *should* only lock on when shooting.

**Comment by Natural-Selection09** [comment]
Why does people still use aimbot? i mean seriously.. The backtrack is WAY enough. Maybe you guys should learn how to play the game before cheating on it. As long as your aim is okay' and that you have a good crosshair placement you just need backtrack and then you become an absolute monster. And people won't see anything in OW.
