### ISSUE TITLE
new update breaks aimbot

### ISSUE THREAD

**Issue by AustScar5** [danielkrupinski/Osiris#1441]
title, the aimbot sometimes misfires and shoots into the air while spraying, and its impossible to control recoil,, pulling down does nothing

maybe offset update?

**Comment by lss961638214** [comment]
The reason may be that this update cancels the "Recoil-based fov"

**Comment by lss961638214** [comment]
And I don't know when "Recoil control x (y)" is gone

**Comment by danielkrupinski** [comment]
Should be fixed (73b88bcd10baac299666ed18c1609d62cb02b6c4)
