### ISSUE TITLE
[Question] Fix bone matrix

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#1444]
Does `Fix bone matrix` affect the aimbot?

Can someone explain how does it work?

**Comment by Zhxcky** [comment]
It basicly correct client bone matrix to be closer to server one, that's mean you can "hide" your aimbot / make silent aimbot more "silent"

**Comment by dapaster** [comment]
Thank you @Zhxcky

**Comment by notgoodusename** [comment]
> It basicly correct client bone matrix to be closer to server one, that's mean you can "hide" your aimbot / make silent aimbot more "silent"

what?? no, it doesnt make it more "silent", what it does is sets absorigin(interpolated) to origin(uninterpolated) and calls setupbones and restores the origin, so the model will be always to the most recent uninterpolated data
