### ISSUE TITLE
Strange visual bug

### ISSUE THREAD

**Issue by 17sergiom2000** [danielkrupinski/Osiris#1445]
This happens with some player models heads even when everything is off.
SS:
https://i.imgur.com/4Ratztj.jpg

**Comment by dapaster** [comment]
#1336

**Comment by xpossed-you** [comment]
"I think CS:GO devs broke something in the latest shader update"
- Daniel Krupinski

**Comment by Oly-UK** [comment]
nothing daniel can do about it

**Comment by danielkrupinski** [comment]
Should be fixed now.
