### ISSUE TITLE
How can i make the chams override otc's chams

### ISSUE THREAD

**Issue by OOF-RIF** [danielkrupinski/Osiris#1446]
title. It just does not want to work on allies, enemies or local player. works on everything else. Any fix?

**Comment by danielkrupinski** [comment]
> otc's chams

What's that?

**Comment by playday3008** [comment]
Hah, onetap crack

**Comment by xpossed-you** [comment]
turn off otc chams

**Comment by xpossed-you** [comment]
please close this issue, this has nothing to do in Osiris development

**Comment by wirebruh** [comment]
> > otc's chams
> 
> What's that?

he is double injecting onetap crack and osiris
