### ISSUE TITLE
VAC Protection?

### ISSUE THREAD

**Issue by bilalreader** [danielkrupinski/Osiris#1448]
Does the cheat have VAC protection? Or how to do it?

**Comment by Faysal1969** [comment]
you can add junkcode

**Comment by xAkiraMiura** [comment]
junkcode does nothing. use [daniel's VAC Bypass](https://github.com/danielkrupinski/VAC-Bypass-Loader/)

**Comment by xpossed-you** [comment]
> 
> 
> you can add junkcode

junkcode is useless at this time, maybe forever

**Comment by bilalreader** [comment]
> junkcode does nothing. use [daniel's VAC Bypass](https://github.com/danielkrupinski/VAC-Bypass-Loader/)


where exactly will i add it?

**Comment by xpossed-you** [comment]
> 
> 
> > junkcode does nothing. use [daniel's VAC Bypass](https://github.com/danielkrupinski/VAC-Bypass-Loader/)
> 
> where exactly will i add it?

you dont have to add it to Osiris solution just do this
    Compile VAC-Bypass-Loader
    Close Steam client if running.
    Run VAC-Bypass-Loader.exe as Adminitrator. Steam will be opened automatically.

**Comment by bilalreader** [comment]
> > > junkcode does nothing. use [daniel's VAC Bypass](https://github.com/danielkrupinski/VAC-Bypass-Loader/)
> > 
> > 
> > where exactly will i add it?
> 
> you dont have to add it to Osiris solution just do this
> Compile VAC-Bypass-Loader
> Close Steam client if running.
> Run VAC-Bypass-Loader.exe as Adminitrator. Steam will be opened automatically.


then I will open the cheat. Is that all?

**Comment by xpossed-you** [comment]
> 
> 
> > > > junkcode does nothing. use [daniel's VAC Bypass](https://github.com/danielkrupinski/VAC-Bypass-Loader/)
> > > 
> > > 
> > > where exactly will i add it?
> > 
> > 
> > you dont have to add it to Osiris solution just do this
> > Compile VAC-Bypass-Loader
> > Close Steam client if running.
> > Run VAC-Bypass-Loader.exe as Adminitrator. Steam will be opened automatically.
> 
> then I will open the cheat. Is that all?

yes

**Comment by bilalreader** [comment]
> > > > > junkcode does nothing. use [daniel's VAC Bypass](https://github.com/danielkrupinski/VAC-Bypass-Loader/)
> > > > 
> > > > 
> > > > where exactly will i add it?
> > > 
> > > 
> > > you dont have to add it to Osiris solution just do this
> > > Compile VAC-Bypass-Loader
> > > Close Steam client if running.
> > > Run VAC-Bypass-Loader.exe as Adminitrator. Steam will be opened automatically.
> > 
> > 
> > then I will open the cheat. Is that all?
> 
> yes


Will I do this every time? automatic is not possible?

**Comment by xpossed-you** [comment]
> 
> 
> > > > > > junkcode does nothing. use [daniel's VAC Bypass](https://github.com/danielkrupinski/VAC-Bypass-Loader/)
> > > > > 
> > > > > 
> > > > > where exactly will i add it?
> > > > 
> > > > 
> > > > you dont have to add it to Osiris solution just do this
> > > > Compile VAC-Bypass-Loader
> > > > Close Steam client if running.
> > > > Run VAC-Bypass-Loader.exe as Adminitrator. Steam will be opened automatically.
> > > 
> > > 
> > > then I will open the cheat. Is that all?
> > 
> > 
> > yes
> 
> Will I do this every time? automatic is not possible?

everytime you want to play CSGO just open the bypass loader

**Comment by RyDeem** [comment]
i mean vac bypass is cool and all but i have not gotten any VAC on any of my accounts playing with this cheat and some rando source of a injector i found on UC for over a year, is it really needed?

**Comment by Vadenez** [comment]
@RyDeem Vac Bypass it not needed to run and use Osiris. Also you can still get Vac banned using Vac Bypass if you are being blatant, as I've been banned while using it and being blatant.

**Comment by Zhxcky** [comment]
> @RyDeem Vac Bypass it not needed to run and use Osiris. Also you can still get Vac banned using Vac Bypass if you are being blatant, as I've been banned while using it and being blatant.

Funny, i never got vac banned even if i was rage hacking, been using for 7 month no vac ban at all.

**Comment by m0nsterJ** [comment]
@Vadenez The VAC-bypass loader only protects you from getting VAC banned (from the anti-cheat itself). It does not protect you from getting Overwatch banned (from players who are watching the demo and determine if you guilty of cheating or not), since there is no working Overwatch bypass anymore. I assume that you got Overwatch banned first (for cheating too blatant) and that turned into a VAC ban. (there is a chance that the Overwatch ban (game ban) can turn into a VAC ban,even though the cheat you were using is not detected)

**Comment by HowToMakeFaceitAB** [comment]
> junkcode does nothing. use [daniel's VAC Bypass](https://github.com/danielkrupinski/VAC-Bypass-Loader/)

#1466

**Comment by techprimedev** [comment]
I Open Daniel`s VAC Bypass, but steam open and close in instants

**Comment by hkmodd** [comment]
> junkcode does nothing. use [daniel's VAC Bypass](https://github.com/danielkrupinski/VAC-Bypass-Loader/)

Yo Bro junkcode works immaculately, what are u talking about
You just have to put the JunkCode in every .cpp, not just at the end of the source haha

**Comment by effex1337** [comment]
> > junkcode does nothing. use [daniel's VAC Bypass](https://github.com/danielkrupinski/VAC-Bypass-Loader/)
> 
> Yo Bro junkcode works immaculately, what are u talking about
> You just have to put the JunkCode in every .cpp, not just at the end of the source haha

OK big brain then explain how and why ain't adding junk code makes it ud.
Also what tf is end of source???

**Comment by hkmodd** [comment]
Bruh I don't know sorry, I just see that adding junkcode to Injector and Cheat makes it undetected for the poor VAC
I'm not a programmer
I've not commented to be a big brain :(
I've seen also that adding junkcode to every .cpp file makes undetected cheats that without that Junkcode are not ud, so I came just to an obvious conclusion

If you please could share with me your infos I'd be glad to learn new things, thanks

**Comment by xAkiraMiura** [comment]
> I'm not a programmer

then why are you acting like know what you are talking about.

> I've seen also that adding junkcode to every .cpp file makes undetected cheats that without that 

VAC delays bans for a reason. seems you got tricked.

> Btw I used VAC-bypass-Loader and it made me kick out of a Competitive and even autoabandon it 

make a bug report there.

> If you please could share with me your infos I'd be glad to learn new things, thanks

polymorphic injectors work well. kernal mode injectors also work if your injectors keep getting your trust low.

**Comment by olanelson85** [comment]
I've been using this on my main and test account with [randoinjector](https://github.com/bananasss00/Rando-Injector) and **no** [VAC Bypass](https://github.com/danielkrupinski/VAC-Bypass-Loader/) for a couple months, so far not a single vac ban.
I use [this](https://steamcommunity.com/profiles/76561199037722500) account to test configs.

> @RyDeem Vac Bypass it not needed to run and use Osiris. Also you can still get Vac banned using Vac Bypass if you are being blatant, as I've been banned while using it and being blatant.

VAC ban != Overwatch ban; As in it doesn't matter if you're being blatant or **"legit"**, if VAC catches you, you're done.

**Comment by xAkiraMiura** [comment]
> 
> 
> I've been using this on my main and test account with [randoinjector](https://github.com/bananasss00/Rando-Injector) and **no** [VAC Bypass](https://github.com/danielkrupinski/VAC-Bypass-Loader/) for a couple months, so far not a single vac ban.
> I use [this](https://steamcommunity.com/profiles/76561199037722500) account to test configs.
> 
> > @RyDeem Vac Bypass it not needed to run and use Osiris. Also you can still get Vac banned using Vac Bypass if you are being blatant, as I've been banned while using it and being blatant.
> 
> VAC ban != Overwatch ban; As in it doesn't matter if you're being blatant or **"legit"**, if VAC catches you, you're done.

VACnet can catch you if you are blatant. i don't know if VACnet's specifics have been changed but it used to be able to elevate untrusted bans into vac bans.
