### ISSUE TITLE
[Request] Seperate Section for snipers in Triggerbot and Aimbot

### ISSUE THREAD

**Issue by Kuritsu243** [danielkrupinski/Osiris#1453]
Is there anyway you could add a seperate section for sniper rifles in the aimbot and triggerbot sections? Could help a lot of people out with their Legit configs

**Comment by Vadenez** [comment]
There in the rifes tab, so IDK what doing that would acomplish. just config the sniper rifes sepreatly...

**Comment by xpossed-you** [comment]
its already separated.

open the Rifles tab to see more info
