### ISSUE TITLE
Game crash upon injecting osiris.dll (Non steam cs version)

### ISSUE THREAD

**Issue by GenTapDude** [danielkrupinski/Osiris#1455]
I compiled the newest version of the cheat and when I inject it with (in my case) bonskoinjector it just crashes my game. I'm using Counter Strike Warzone which is a non steam version basically but other cheats designed for cs:go work great for CS warzone so I dont think that's the cause.
Has anyone experienced this? I think I have all the runtimes needed because I do a lot and everything have worked great so far but I might be wrong.

**Comment by m0nsterJ** [comment]
@GenTapDude Osiris is a CSGO cheat and not a CS Warzone cheat. There might be cheats that work for CSGO and CS Warzone additionally, but thats not the case with Osiris.

**Comment by GenTapDude** [comment]
@m0nsterJ is there anything that I can do to make it work? @danielkrupinski da rade coś tu wykminić?
What is a good alternative to Osiris?

**Comment by bruhmoment21** [comment]
in your case the game is outdated. the cheat indexes/offsets/signatures are updated to the current game not non steam version(warzone) which may not be updated. i hope you know that csgo is free.

**Comment by GenTapDude** [comment]
@bruhmoment21 the cs warzone is autoupdating so it is updated (I can join to cs:go community servers so it must be the newest version)
![cswarzone](https://user-images.githubusercontent.com/63969229/79694923-f0bd2900-8273-11ea-8bf3-8c0066241fea.JPG)

**Comment by rosesware** [comment]
CS:GO is free, you have skin changer on Osiris, why do you want CS Warzone?

**Comment by GenTapDude** [comment]
Because if I get a vac banned on several fresh accounts I will get banned on my main eventually. I just dont feel safe, its same with EAC - if you get 3 bans, Your HWID will be banned and any account you have ever logged to on that PC will get a ban too.
Unless I'm wrong.

**Comment by bruhmoment21** [comment]
> @rosesware Because if I get a vac banned on several fresh accounts I will get banned on my main eventually. I just dont feel safe, its same with EAC - if you get 3 bans, Your HWID will be banned and any account you have ever logged to on that PC will get a ban too.
> Unless I'm wrong.

If you have n accounts, where n is number of accounts, linked to same phone number, if you get banned on one of those accounts (with the same phone number), you ll get banned on all of them. If it s just the email you are good and hwid bans is just a meme, only accounts can get banned not hwids (by vac)

**Comment by danielkrupinski** [comment]
We use Steam's game overlay for rendering GUI, that may be the problem. You can try to get DirectX device from the game but you have to do it on your own.
