### ISSUE TITLE
How to slow the aimbot flick without miss ?

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#1456]
When i use AWP and set `smooth` to 1 the aimbot will hit the enemy . But if i set more than 1 the aimbot gonna miss.  

I want to make the aimbot still hit even when the `smooth` value is more than 1.

Is this possible?

Any idea how to do this?

**Comment by dctrlight** [comment]
thats what `smooth` is

**Comment by dapaster** [comment]
what i mean is how to make the aimbot less flick / make it look more legit @dctrlight

**Comment by Shaxzy** [comment]
Why would you use smooth aimbot with AWP in the first place?
You could alternatively bind the aimbot and triggerbot to the same key (magnet trigger), so when you hold that key it will start aiming towards the target and shoot once the target is in your crosshair.

**Comment by dapaster** [comment]
thanks @Shaxzy

**Comment by dapaster** [comment]
Thanks @Shaxzy
