### ISSUE TITLE
How to get bullet impact position?

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#1460]
Trying to make hitmarker dmg indicator . 

Can someone tell me how to get the bullet impact position.

I'm using the enemy bone 

    Vector bone {Enemy bone (head)}
    Vector w2screen

    World2Screen(bone,w2screen)

    SetTextPosition 

But when in game

The hitmarker only appear on the floor where the localplayer spawn.

And then crash a few min later

**Comment by Oly-UK** [comment]
#835

**Comment by dapaster** [comment]
> #835

I want to make it like this

https://www.youtube.com/watch?v=Rpsnnp3qeeI

**Comment by 3Ld4D** [comment]
https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events#bullet_impact

**Comment by dapaster** [comment]
Thanks @3Ld4D
