### ISSUE TITLE
When I use Aim bot, the recoil is very strong and I can't hit

### ISSUE THREAD

**Issue by AlisaCiya** [danielkrupinski/Osiris#1462]

**Comment by 18339256125** [comment]
how can i fix it

**Comment by Araptois** [comment]
Dont use aimbot ¯\_(ツ)_/¯

**Comment by HowToMakeFaceitAB** [comment]
> Dont use aimbot ¯_(ツ)_/¯
> 
> Or disabled recoil control

You can't disable it

**Comment by HowToMakeFaceitAB** [comment]
> What do you mean by saying
> 
> > the recoil is very strong

Maybe he's using 1 smooth lmao

**Comment by 18339256125** [comment]
> What do you mean by saying
> 
> > the recoil is very strong

Bullets float to the sky

**Comment by HowToMakeFaceitAB** [comment]
> > What do you mean by saying
> > > the recoil is very strong
> 
> Bullets float to the sky

You have latest osiris?

**Comment by 18339256125** [comment]
> > > What do you mean by saying
> > > > the recoil is very strong
> > 
> > 
> > Bullets float to the sky
> 
> You have latest osiris? And try using different config

Always follow fashion

**Comment by danielkrupinski** [comment]
Last week's game update broke recoil control but it's been fixed - 73b88bcd10baac299666ed18c1609d62cb02b6c4
