### ISSUE TITLE
Hitsound pack 1-7

### ISSUE THREAD

**Issue by xpossed-you** [danielkrupinski/Osiris#1463]
just write the file name in custom hitsound string
extrack at csgo/sound

[sound.zip](https://github.com/danielkrupinski/Osiris/files/4511290/sound.zip)

**Comment by Araptois** [comment]
The last sound... 

👌

**Comment by xpossed-you** [comment]
> 
> 
> The last sound...
> 
> ok_hand

LETS GET ITTTTTTT

**Comment by xpossed-you** [comment]
> 
> 
> @xpossed-you I've updated your comment to with an attachment. Next time please upload files to Github instead of third-party file hostings.

IM SORRY, next time i will upload my attachment to Github
