### ISSUE TITLE
Question about github

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1466]
So, i'm kinda still trying to figure this out, how do i use pull requests into the cheat, do i do it manually or do i just clone it, but most pull requests use outdated versions so how do i use latest osiris version with pull requests without re adding changes manually

**Comment by xAkiraMiura** [comment]
your question is about git, not github.
you can run `git help command` to open a page about the command.
the command you want is `git merge`

if you only want to update an older branch then you can do `git fetch` and `git rebase` to update it to latest.

**Comment by HowToMakeFaceitAB** [comment]
> your question is about git, not github.
> you can run `git help command` to open a page about the command.
> the command you want is `git merge`
> 
> if you only want to update an older branch then you can do `git fetch` and `git rebase` to update it to latest.

Ok, so how do i merge a pull request with cheat? I know it's git merge, and i tried searching it up, didn't understand very well. Could you please give me a guide, or justs steps to merge?
