### ISSUE TITLE
Open case [Source]

### ISSUE THREAD

**Issue by randybail** [danielkrupinski/Osiris#1467]
I am going to share my code with you guys next week i just wanna finish this code (i have added latest protobuf to make it work with the inventory)

![ez](https://user-images.githubusercontent.com/64097042/79896350-8be70780-8408-11ea-8ca5-4ea114321c50.png)

smash a like if you like it.

If you let me some more days after release i will try my best to make it savable with config.

**Comment by unnamed01X** [comment]
maybe do the same thing with "fake unbox" option? like searching for the knifes/skins, automatic *nick* in game switching or something (sorry for trash eng)

**Comment by techprimedev** [comment]
Nice

**Comment by smartxd3** [comment]
waw is that inventory change?? the equip from inventory is an inventory changer?
and good luck bro :)

**Comment by xpossed-you** [comment]
+rep
how you add an image to imgui?

**Comment by effex1337** [comment]
> +rep
> how you add an image to imgui?

ImGui::Image(texture_id, size);
Ez as that

**Comment by xpossed-you** [comment]
oh thx men

**Comment by jdbjdb2** [comment]
Did you implement the full protobuf? I've been struggling to implement myself. I am trying to make a translator for ingame chat as outlined [here](https://pastebin.com/sUcpup5B). I do this since lots of players I encounter are russian so it would be good to understand the chat and this will help but I am struggling to correctly link protobufs and then use them for the translation

**Comment by Oly-UK** [comment]
yo wtf that's insane, good fucking shit my man

**Comment by m0nsterJ** [comment]
Dude that's insane, nice one dude!

**Comment by GenTapDude** [comment]
how is that gonna work? Add real items to my inventory? naaah

**Comment by Oly-UK** [comment]
@GenTapDude it's gonna be an inventory changer but with a case opener that's awesome asf

**Comment by Or3nges** [comment]
any progress? I just can't wait :D 👯‍♂️  ⚰️ 👯‍♂️
                                                           👯‍♂️

**Comment by Tanishq999** [comment]
Wow .. thats nice!! :)

**Comment by Oly-UK** [comment]
whens the relase comin fam

**Comment by Straightplus** [comment]
Next week* xd

**Comment by xtyspengu** [comment]
must've been fake or my dude just died

**Comment by Straightplus** [comment]
lol

**Comment by Oly-UK** [comment]
yh this was probably fake thinking about it lol

**Comment by 1lexysexy** [comment]
woah man thats cool

**Comment by 1lexysexy** [comment]
kinda lookin like painted :D

**Comment by Oly-UK** [comment]
oh yeah we got fooled. The button text aint even alligned the same

**Comment by Oly-UK** [comment]
yh this is fake 100%
