### ISSUE TITLE
Fix fakeban./Add Fake Vote.

### ISSUE THREAD

**Issue by Allerek** [danielkrupinski/Osiris#1468]
Fakeban nie działa prawidłowo,  po kliknięciu 'Setup Fake Ban' i wpisaniu disconect(gdyż tak to powinno działać). Wiadomość nie jest wyświetlana prawidłowo.

Proszę o dodanie Fake Vote(zmienianie nicku na poprzedni powinno odbyć się automatycznie po stworzeniu głosowania lub 1 minucie).

**Comment by m0nsterJ** [comment]
@Allerek Fake Vote has been patched since 4 months and the fake ban is working properly.

**Comment by xAkiraMiura** [comment]
you need to have a clantag if you want it to show up when you shoot a teammate. I use a zero-width space character as my clantag. (or you can reconnect (i think the retry command will dc and rc?))

**Comment by Allerek** [comment]
> you need to have a clantag if you want it to show up when you shoot a teammate. I use a zero-width space character as my clantag. (or you can reconnect (i think the retry command will dc and rc?))
As i know 'retry' doesnt work on official valve servers

**Comment by Allerek** [comment]
> you need to have a clantag if you want it to show up when you shoot a teammate. I use a zero-width space character as my clantag. (or you can reconnect (i think the retry command will dc and rc?))

As i know 'retry' doesnt work on official valve servers
