### ISSUE TITLE
Add RCS (Recoil Control System)

### ISSUE THREAD

**Issue by techzin** [danielkrupinski/Osiris#1470]
I was testing Osiris and realized that when I tried to make a spray with an AK-47, my aim went up a lot, making it impossible to kill the enemy, but I tried to lower it, but it was very difficult to control as if the aimbot does not let up.

I think adding an RCS would be a big step forward in the project.

**Comment by xpossed-you** [comment]
there are RCS in the older version of Osiris (2019) but i think it not working properly, so they removed it.

maybe they will added RCS but not now, be passion ok?

**Comment by dapaster** [comment]
> I was testing Osiris and realized that when I tried to make a spray with an AK-47, my aim went up a lot, making it impossible to kill the enemy, but I tried to lower it, but it was very difficult to control as if the aimbot does not let up.
> 
> I think adding an RCS would be a big step forward in the project.

Did you use silent aim?

**Comment by Spache123** [comment]
UP @danielkrupinski (please add)

**Comment by xAkiraMiura** [comment]
to make an RCS just modify the engine angles rather than the networked angles with the delta change of a netvar. it only requires 2 variables and 2 checks.

**Comment by Oly-UK** [comment]
@xpossed-you there was nothing wrong with it, daneil just removed it as he preferred automated recoil compensation. Here is a random commit so you can take a look at the old RCS https://github.com/danielkrupinski/Osiris/blob/efecdbf75b7a9472066b8909fb412ea71f03df46/Osiris/Hacks/Aimbot.cpp#L144-L146 and here is a pull request with standalone RCS which is stronger imo https://github.com/danielkrupinski/Osiris/pull/1277

**Comment by techprimedev** [comment]
@danielkrupinski You have plans to re add RCS on Osiris?
