### ISSUE TITLE
how to add a new font in Osiris?

### ISSUE THREAD

**Issue by xpossed-you** [danielkrupinski/Osiris#1471]

**Comment by 3Ld4D** [comment]
Surface or Imgui?

**Comment by xpossed-you** [comment]
Surface

**Comment by 3Ld4D** [comment]
try `setFontGlyphSet()`

**Comment by xpossed-you** [comment]
ok

**Comment by littlehurensohn** [comment]
PushFont 
PopFont

Find on google how to load (font) bytes from memory.

**Comment by xAkiraMiura** [comment]
> 
> 
> PushFont
> PopFont
> 
> Find on google how to load (font) bytes from memory.

that is not how you create a font with ISurface. that is how to do ImGui fonts.
