### ISSUE TITLE
[Code Sample] csgo source

### ISSUE THREAD

**Issue by tirziz** [danielkrupinski/Osiris#1476]
Apparently CS:GO source from 2017 has been leak (but no depot yet). Maybe valve will change to source 2 sooner than we though,
more info can be found here
https://github.com/perilouswithadollarsign/cstrike15_src

**Comment by vsnrytune** [comment]
Does this mean we will be able to get more juicy cheat features? ;)

**Comment by tirziz** [comment]
> Does this mean we will be able to get more juicy cheat features? ;)

Dont think so, still a good reference.
