### ISSUE TITLE
[Feature Request] Kill Sounds?

### ISSUE THREAD

**Issue by Adim2P** [danielkrupinski/Osiris#1477]
It's a simple feature, just plays a sound after you killed someone

**Comment by Oly-UK** [comment]
it's easy to add mate, look at how hitsounds work and then look at the kill message feature put the two together and boom.

**Comment by streamshark** [comment]
not sure if you mean through the mic like P2Cs

**Comment by xpossed-you** [comment]
> 
> 
> it's easy to add mate, look at how hitsounds work and then look at the kill message feature put the two together and boom.

big brain, if this was reddit... i would give you a gold medals

**Comment by Oly-UK** [comment]
> > it's easy to add mate, look at how hitsounds work and then look at the kill message feature put the two together and boom.
> 
> big brain, if this was reddit... i would give you a gold medals

ikr

**Comment by xAkiraMiura** [comment]
https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events
`player_death` is the event you want.
`player_hurt` already contains hitsound code.

**Comment by xpossed-you** [comment]
this feature is added to Osiris, please close this issue
