### ISSUE TITLE
Glow enabled by key? 

### ISSUE THREAD

**Issue by GenTapDude** [danielkrupinski/Osiris#1478]
Could someone make a simple code to make GLOW enable or disable with a f7 key or something?

**Comment by mattys0229** [comment]
probably just if key is pressed toggle the glow enable bool. i dont really know cpp but i think it would work this way.

**Comment by xAkiraMiura** [comment]
use `GetAsyncKeyState` every frame. 
argument 1 is the button code (either a character literal (e.g. `'a'`) or a `Windows.h` [virtual key code](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes) (e.g. VK_INSERT or VK_END)).

by default `GetAsyncKeyState` will repeat if you hold down the button for a while, like when typing, to prevent this do logical AND with `1<<15` and then store the value and compare it to see if it changed.

then just set the variable to be its negated self (e.g. `x = !x` or `x ^= 1`).

**Comment by danielkrupinski** [comment]
Added
