### ISSUE TITLE
(Maybe)Closest thing to desync chams

### ISSUE THREAD

**Issue by notgoodusename** [danielkrupinski/Osiris#1479]
White fake
Yellow real
https://streamable.com/88gwru
now i need to fix the material cuz it doesnt work unless you toggle local player chams.
Should i publish this?

**Comment by designer1337** [comment]
holy shit nice legs from scene end

and no, it's not even close

**Comment by notgoodusename** [comment]
> holy shit nice legs from scene end
> 
> and no, it's not even close

i know

**Comment by designer1337** [comment]
> > holy shit nice legs from scene end
> > and no, it's not even close
> 
> i know

first of all u should manage localplayer real and fake animation and then render it using DrawModelExexute or DrawModel

**Comment by notgoodusename** [comment]
yeah, i know that but i havent tried yet
the idea would be to
backup layers
create an animstate
feed incorrect data or feed correct data
setupbones
restore layers

**Comment by unnamed01X** [comment]
yeah, share the code please!

**Comment by m0nsterJ** [comment]
@unnamed01X these desync chams are not working properly, so just wait until @notgoodusename fixed them and made a pull-request

**Comment by unnamed01X** [comment]
yeah, but i would like to look at the localhost chams (fake) etc :D 
but if he fix it and publish it, it would be very niceeee

**Comment by 3Ld4D** [comment]
i managed to make it and it was using glow
