### ISSUE TITLE
Get offset on netvar

### ISSUE THREAD

**Issue by notgoodusename** [danielkrupinski/Osiris#1481]
As the title says, i need m_flPoseParameter from DT_BaseAnimating and it returns and std::array<float,24>, i dont know much about how netvars work, so if someone could help me, i would be grateful

**Comment by notgoodusename** [comment]
i fixed it!
    std::array<float, 24> & pos_par()
    {
        constexpr auto hash{ fnv::hash("DT_BaseAnimating->m_flPoseParameter") };
        return *reinterpret_cast<std::array< float, 24 >*> ((uintptr_t)this + netvars->operator[](hash));
    }

**Comment by 3Ld4D** [comment]
@notgoodusename thanks i needed that for local fix

**Comment by notgoodusename** [comment]
you are welcome! trying the same right now, got some kind of results, i may post a vid showing the fix i did so far

**Comment by notgoodusename** [comment]
also dont use "DT_BaseAnimating" use "CBaseAnimating" otherwise it wont work

**Comment by gtdani51** [comment]
@notgoodusename thanks for that, now i need SetAbsAngle for local fix
i use this on memory.cpp
`setAbsAngle = relativeToAbsolute<decltype(setAbsAngle)>(FIND_PATTERN(int*, L"client_panorama", "\x55\x8B\xEC\x83\xE4\xF8\x83\xEC\x64\x53\x56\x57\x8B\xF1\xE8");`
is this correct?

**Comment by 3Ld4D** [comment]
@gtdani51 
```cpp
in Memory.h under `class ViewRender;`:
typedef void(__thiscall* SetAngleFn)(void*, const Vector&);
under `uintptr_t reset;`:
SetAngleFn setAngles;
in Memory.cpp
setAngles = FIND_PATTERN(SetAngleFn, L"client_panorama", "\x55\x8B\xEC\x83\xE4\xF8\x83\xEC\x64\x53\x56\x57\x8B\xF1");
in Entity.h
void setAngles2(const Vector angles)
{
    memory->setAngles(this, angles);
}

**Comment by gtdani51** [comment]
> ```c++
> void setAngles2(const Vector angles)
> {
>     memory->setAngles(this, angles);
> }
> ```
still need constructor to convert int to vector

**Comment by 3Ld4D** [comment]
```cpp
local->setAbsAngle(Vector{0, abs, 0});```
