### ISSUE TITLE
Backtrack Issues

### ISSUE THREAD

**Issue by sundafused** [danielkrupinski/Osiris#1485]
I've noticed my backtracking isn't working at all. Even when I choke different numbers of packets, or none at all. Turning aimbot off doesn't work. I don't know what it could be.

**Comment by wirebruh** [comment]
can you show a video? are you on the latest version of the cheat?

**Comment by sundafused** [comment]
I don't have a video, but every version of the cheat I use has this problem. I've tried recompiling, but this has been a persistent problem for months now.
