### ISSUE TITLE
Custom smooth for rcs

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1486]
Rcs uses smoothness of aimbot, and that makes it harder to control recoil i.e: when you're using 15+smooth on aimbot, the rcs just doesn't do anything and just ruins the aimbot, allowing us to use a custom smooth for rcs is much better or as i have been begging for the last 2 months(XD) can you add standalone rcs
Or just give link me some pasted code?

**Comment by 3Ld4D** [comment]
why are you using 15+ smooth at the first place

**Comment by xpossed-you** [comment]
15+ smoothing in Aimbot? thats just like you dont have to use aimbot.
RCS Source : https://www.unknowncheats.me/forum/counterstrike-global-offensive/135848-recoil-control-without-fixed-point.html

**Comment by HowToMakeFaceitAB** [comment]
> 15+ smoothing in Aimbot? thats just like you dont have to use aimbot.
> RCS Source : https://www.unknowncheats.me/forum/counterstrike-global-offensive/135848-recoil-control-without-fixed-point.html

Thank you, and is 15 too much? What do you recommend?

**Comment by 3Ld4D** [comment]
1 smooth with 2-3fov

**Comment by xpossed-you** [comment]
> 
> 
> > 15+ smoothing in Aimbot? thats just like you dont have to use aimbot.
> > RCS Source : https://www.unknowncheats.me/forum/counterstrike-global-offensive/135848-recoil-control-without-fixed-point.html
> 
> Thank you, and is 15 too much? What do you recommend?

1-2 is too blatant
3-5 is likely humanized aim

**Comment by 3Ld4D** [comment]
well it all depends on your skill

**Comment by 3Ld4D** [comment]
if you are on LE+ you are good with 1-2 with low fov

**Comment by vsnrytune** [comment]
1-2 seems blatant af, I'm using 1.5-2 fov with 12 smooth on rifles and 2.5 fov with 8 smooth on pistols and it's perfect

**Comment by HowToMakeFaceitAB** [comment]
> 1-2 smooth sounds blatant af, I'm using 1.5-2 fov with 12 smooth on rifles and 2.5 fov with 8 smooth on pistols and it's perfect

try using an aimlock with 12 smooth and 1.4 fov on rifles, it works really well ngl
and for pistols 2.5 with 8 is good

**Comment by HowToMakeFaceitAB** [comment]
Just started using 8 smooth with 1
4 fov on rifles, destroys
