### ISSUE TITLE
walkbot

### ISSUE THREAD

**Issue by gznster** [danielkrupinski/Osiris#1487]
I saw someone on unkonwncheats able to merge osiris with a walkbot function, anybody care sharing some resources on how to do so?

**Comment by HowToMakeFaceitAB** [comment]
what is the point, it's a pointless function, if you want a pointless function like that, try searching it up yourself, not many people are really gonna help you, if the function is useful, they might link you the source of the function

**Comment by Finndramere** [comment]
I've been digging around on how to add nav mesh walkbot but I can't seem to understand how it works and how to implement it. I know you need A* path algorithm and navmesh parser but I can't understand it.
