### ISSUE TITLE
106 Errors when Building Solution

### ISSUE THREAD

**Issue by xanaxw** [danielkrupinski/Osiris#1488]
Hi, as I have 0 coding knowledge, I would kindly like to ask how I can fix this so that I can build the solution.

Output log: https://pastebin.com/phWTF7NF
Thanks in advance.

**Comment by HowToMakeFaceitAB** [comment]
what the hell?

**Comment by rafalohaki** [comment]
XD
u need to install depended tools

**Comment by xanaxw** [comment]
> XD
> u need to install depended tools

Can I have a link to that please?

**Comment by danielkrupinski** [comment]
#1158
