### ISSUE TITLE
Add No Flash feature

### ISSUE THREAD

**Issue by real-Shigure** [danielkrupinski/Osiris#1489]
No flash was added in old version, but in this latest version I can't find this features. (No flash is very useful! )🏃‍♂️😊Thanks!

**Comment by HowToMakeFaceitAB** [comment]
> No flash was added in the old version, but in this latest version, I can't find these features. (No flash is very useful! )🏃‍♂️😊Thanks!

there aren't any no flash features but there is a flash reducer, set it to 100% for no flash, in the  visual tab

**Comment by real-Shigure** [comment]
> No flash was added in the old version, but in this latest version, I can't find these features. (No flash is very useful! )🏃‍♂️😊Thanks!
> 
> there aren't any noflash features but there is a flash reducer, set it to 100% for no flash, in the visual tab, and also, if your issue is fixed, please close the issue.

Thanks! I find it.
