### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by EGTLoneWolf** [danielkrupinski/Osiris#149]
Can this cheat be used in Danger Zone mode?  
I am asking this as i am crashing in DangerZone with this cheat

**Comment by NexSqaud** [comment]
http://prntscr.com/njcxl5 This cheat works in danger zone correctly.

**Comment by Havoccboi** [comment]
is this working now?

**Comment by EGTLoneWolf** [comment]
Well i mean like it works , but it will crash later on in the game for me
