### ISSUE TITLE
Pls help with git merge

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1491]
i am retarded and can't figure out how to merge pull request with cheat, tried searching it up, i didn't understand anything, pls explain

**Comment by xAkiraMiura** [comment]
[here you go](https://lmgtfy.com/?q=git+merge)

**Comment by HowToMakeFaceitAB** [comment]
> [here you go](https://lmgtfy.com/?q=git+merge)

still dont understand lMFAOOO
