### ISSUE TITLE
add if player = friendly do this in static void renderBox

### ISSUE THREAD

**Issue by mattys0229** [danielkrupinski/Osiris#1492]
Is there a way to add functions if a player is friendly or its a weapon in static void renderBox in esp.cpp ?

edit: i just want to give enemies and teammates a different color without using config.box.color

**Comment by xAkiraMiura** [comment]
ofc, just open vs2019, add an if check to see if the player team is the same as the local player. if so they are friendly and you can run a function. i believe there is a helper function that checks if an entity is a weapon as well.

hard coding is a bad idea, why not just use the config system?

**Comment by mattys0229** [comment]
because the config files dont support alpha colors and i dont really want to use them in the first place..

**Comment by danielkrupinski** [comment]
If I understood right, #1024 may help you.

**Comment by mattys0229** [comment]
Thanks!
