### ISSUE TITLE
Style Window

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#1494]
i just want the onewindow style
i want to remove the classic style permanently what codes should i remove 
Thank You

**Comment by xpossed-you** [comment]
> Thank You

 no problem

**Comment by tirziz** [comment]
Checkout gui.cpp. Remove what you dont need.

**Comment by xpossed-you** [comment]
> 
> 
> Checkout gui.cpp. Remove what you dont need.

 not just gui.cpp, 
you have to :
remove it from gui.h
change code from config.cpp and config.h
