### ISSUE TITLE
Add functions

### ISSUE THREAD

**Issue by MatthewzCode** [danielkrupinski/Osiris#1496]
I'm really sorry for being such a NN but I don't know how to paste the tutorials on youtube are all with a different source if I'm right. I already have the code for what I'm trying to add could someone link me a tutorial or something please. Any help is welcome thank you! <3

**Comment by dapaster** [comment]
What do you want to add?

**Comment by KernCS** [comment]
1, Do you know what nn mean?
2, What is it you wanna add?

**Comment by olanelson85** [comment]
I wouldn't suggest even trying to paste new features into osiris, for even if you have prior programming knowledge, **pasting** is still a bit of work. 
For instance if you want to paste, say, a different anti-aim from a different source, then you'd have to adjust the names of the functions inside that bit of code to the ones existing in osiris; and well, if osiris doesn't have the functions needed for it, you're either gonna have to paste them too or make them yourself. 
If you dont know what you're doing, you're not gonna get anywhere trying to paste.

**Comment by xAkiraMiura** [comment]
pasting takes no effort other than searching inside your base. everything is already there and you aren't reversing things in IDA.
the code is already there so you don't even need to think of the flow or variable management.

**Comment by joshcancode** [comment]
This isn't really the place for asking for someone to help you paste someone else's work into your source. If you aren't entirely sure on how to get the code you have into this source, I would recommend watching some C++ tutorials and familiarizing yourself with the Osiris framework before continuing. I can say this is one of the nicest frameworks I've seen on Github, so it shouldn't be too difficult to learn your way around the source.

**Comment by xpossed-you** [comment]
learncpp.com

**Comment by MatthewzCode** [comment]
Okay thank y'all for the "support", I'll just look for some c++ tutorials as joshcancode mentioned and look on the website posted by xpossed-you. Thanks!

**Comment by joshcancode** [comment]
> Okay thank y'all for the "support", I'll just look for some c++ tutorials as joshcancode mentioned and look on the website posted by xpossed-you. Thanks!

Good! You're already doing better than 99% of the pasting community. Dedicating to learning C++ before hopping into this is a huge step to making better software. I wasn't trying to sound rude earlier, I'm just very stern with people who want to paste without any knowledge. Glad you're putting in some effort before starting.

**Comment by xpossed-you** [comment]
> 
> 
> Okay thank y'all for the "support", I'll just look for some c++ tutorials as joshcancode mentioned and look on the website posted by xpossed-you. Thanks!

see learning is better than pasting. thank you back
