### ISSUE TITLE
help with custom animations

### ISSUE THREAD

**Issue by AustScar5** [danielkrupinski/Osiris#1498]
trying to code a custom animation, but it completely removes the clantag when activated, ideas would be appreciated  

    if (config->misc.customClanTag) {
        static std::string clanTag;
        size_t clantagSize = clanTag.size();
        std::string spacesText(clantagSize, ' ');

        if (config->misc.animatedClanTag) {
            clanTag = spacesText + clanTag + spacesText;
            for (int i = 0; i < clantagSize * 2; i++)
                std::cout << clanTag.substr(i, clantagSize) << std::endl;

            memory->setClanTag(clanTag.c_str(), clanTag.c_str());
        }

**Comment by effex1337** [comment]
Do you even know what you're doing?

**Comment by AustScar5** [comment]
why else do you think i'm asking for help?

**Comment by joshcancode** [comment]
This is extremely incorrect. You are running a for statement with the clantagSize * 2, which makes no sense. You're also printing to console for no reason. Your `clanTag` variable is never assigned, you're doing `clanTag = spacesText + clanTag + spacesText;` which just makes the clantag 2 spaces...
