### ISSUE TITLE
Junk Code

### ISSUE THREAD

**Issue by lordeternity000** [danielkrupinski/Osiris#1501]
For undetected dll do i have to add junk code or vmprotecting is enough?

**Comment by xpossed-you** [comment]
i never put a junkcode or vmprotect'd my dll
never get VAC. but lets see what others opinion is

**Comment by bootfast** [comment]
Yep u can use junk code+vm protect for extra protection...

**Comment by HowToMakeFaceitAB** [comment]
> Yep u can use junk code+vm protect for extra protection...

No, he can't, osiris uses code optimization, junk code is useless with code optimization

**Comment by vsnrytune** [comment]
> > Yep u can use junk code+vm protect for extra protection...
> 
> No, he can't, osiris uses code optimization, junk code is useless with code optimization

So is this why all of my junk code gets deleted even when I disable code optimisation in VS? But I don't understand how it would still be getting deleted

**Comment by lordeternity000** [comment]
> None of those options work. Junkcode does nothing and vmprotect also. Use Daniel's VAC-Bypass Loader

Doesn't that give vac error or low trust?

**Comment by bootfast** [comment]
> > Yep u can use junk code+vm protect for extra protection...
> 
> No, he can't, osiris uses code optim

> > Yep u can use junk code+vm protect for extra protection...
> 
> No, he can't, osiris uses code optimization, junk code is useless with code optimization

Disable optimization solve the issue...
I built it without optimization and its running well. And Dll size is large too ( i checked the size of osiris.dll with both optimization and without optimization)

**Comment by vsnrytune** [comment]
> > > Yep u can use junk code+vm protect for extra protection...
> > 
> > 
> > No, he can't, osiris uses code optim
> 
> > > Yep u can use junk code+vm protect for extra protection...
> > 
> > 
> > No, he can't, osiris uses code optimization, junk code is useless with code optimization
> 
> Disable optimization solve the issue...
> I built it without optimization and its running well. And Dll size is large too ( i checked the size of osiris.dll with both optimization and without optimization)

Disabling optimization does absolutely nothing for me with Osiris, works fine with other pastes. No matter how much junk I add the file size doesn't change

**Comment by m0nsterJ** [comment]
@everyone take your normal compiled osiris dll (without junkcode) and the other dll (with junkcode) and compare those in SIGBENCH. You will see that the signature matches to 99%. Just use Daniel's VAC-Bypass loader and you are safe.

**Comment by lordeternity000** [comment]
But vac bypass gives red trust factor in prime lobby.

**Comment by xXTOO-HARDXx** [comment]
what da hellll are you guys on about?

ok, the VAC Bypass **does not** work anymore, obviously, so regardless of whether it gives red trust don't bother to use it lol.

if you are trying to add junk code to the source; disable all of the optimization settings in C/C++ -> Optimization, if the junk code is still being cut out then make sure you're on the correct build configuration and try disabling the optimization settings in Linker -> Optimization

**Comment by lordeternity000** [comment]
Is the vac bypass detected? Does it ban accounts now?

**Comment by m0nsterJ** [comment]
@xXTOO-HARDXx The VAC-Bypass works, I am using the VAC-Bypass with an Indigo paste which uses vmt hooking (detected hooking method) and I have not been banned by VAC, so we can safely assume that it works. Also to my other comment is it too much effort to test it out with SIGBENCH, or do you just want to believe that junkcode does something?

**Comment by xXTOO-HARDXx** [comment]
@lordeternity000 you can use it fine without getting banned for using the VAC Bypass, but I dont believe it works properly anymore, read below..

@m0nsterJ well, I have used it for about a year and I was banned on my main yesterday :)

it's safe to say that it may work, but it isn't reliable. I know Valve is slow with patching very obvious shit sometimes but do you really think that the VAC Bypass, after 7 MONTHS, would still work that easily? just by what is essentially a simple byte patch? I doubt it.

**Comment by m0nsterJ** [comment]
@xXTOO-HARDXx All I can say is that I am using it with my Indigo paste which uses vmt hooking (detected since 2017) and I haven't gotten banned.

**Comment by lordeternity000** [comment]
@m0nsterJ , @xXTOO-HARDXx.   I had a prime account with green trust factor. I used an undetected injector with latest vmprotected osiris dll. It was still green. And then i used vac-bypass(the .exe version) with the same injector and dll, i got red trust factor the 1st time I searched for mm, even before getting into the match. I know that the injector is undetected because I use it for another prime account and it's not vac banned and has a green trust factor. So it has to be vac-bypass that caused immediate red trust factor. But my trust factor was still higher than another guy who I met in my 1st match after using the said vac-bypass.

**Comment by xXTOO-HARDXx** [comment]
@m0nsterJ @lordeternity000 well, it's quite strange then. Maybe Valve has decided to incorporate a different play on cheaters :thinking: ... Maybe they are using a method similar to shadow banning, where essentially anyone that tried to bypass vac is put into red trust with other cheaters, rather than just getting banned, and also makes them think that the VAC Bypass isn't working by not issuing VAC bans. This is the only conclusion I can seem to come to.

**Comment by lordeternity000** [comment]
Or maybe valve is marking these accounts for a delayed vac ban or ban wave

**Comment by xXTOO-HARDXx** [comment]
> Or maybe valve is marking these accounts for a delayed vac ban or ban wave

also a possible situation, yes. but that would defeat the purpose of the concept I explained because everyone would just get new accounts, not use the VAC Bypass, and then wont be flagged.

**Comment by lordeternity000** [comment]
That

> > Or maybe valve is marking these accounts for a delayed vac ban or ban wave
> 
> also a possible situation, yes. but that would defeat the purpose of the concept I explained because everyone would just get new accounts, not use the VAC Bypass, and then wont be flagged.
> 
> That is, if people figured out the reason behind the VAC Wave.

That is true. But i am gonna keep using vac-bypass on that account (untill it gets banned maybe) caused that account is already f'ed might as well get it to some good use to see if vac-bypass still works.

**Comment by vsnrytune** [comment]
> @m0nsterJ @lordeternity000 well, it's quite strange then. Maybe Valve has decided to incorporate a different play on cheaters  ... Maybe they are using a method similar to shadow banning, where essentially anyone that tried to bypass vac is put into red trust with other cheaters, rather than just getting banned, and also makes them think that the VAC Bypass IS actually working by not issuing VAC bans to people who are shadow banned, per se. This is the only conclusion I can seem to come to.

This is false, I've been using vac bypass and osiris for ages and I'm still playing in green trust, although sometimes it can drop to red in literally one game, but goes back up again.

**Comment by lordeternity000** [comment]
> > @m0nsterJ @lordeternity000 well, it's quite strange then. Maybe Valve has decided to incorporate a different play on cheaters  ... Maybe they are using a method similar to shadow banning, where essentially anyone that tried to bypass vac is put into red trust with other cheaters, rather than just getting banned, and also makes them think that the VAC Bypass IS actually working by not issuing VAC bans to people who are shadow banned, per se. This is the only conclusion I can seem to come to.
> 
> This is false, I've been using vac bypass and osiris for ages and I'm still playing in green trust, although sometimes it can drop to red in literally one game, but goes back up again.

How long does it take in your case for the trust factor to go up again?

**Comment by vsnrytune** [comment]
> > > @m0nsterJ @lordeternity000 well, it's quite strange then. Maybe Valve has decided to incorporate a different play on cheaters  ... Maybe they are using a method similar to shadow banning, where essentially anyone that tried to bypass vac is put into red trust with other cheaters, rather than just getting banned, and also makes them think that the VAC Bypass IS actually working by not issuing VAC bans to people who are shadow banned, per se. This is the only conclusion I can seem to come to.
> > 
> > 
> > This is false, I've been using vac bypass and osiris for ages and I'm still playing in green trust, although sometimes it can drop to red in literally one game, but goes back up again.
> 
> How long does it take in your case for the trust factor to go up again?

1-5 games maybe, it stays at green for a while, but sometimes randomly drops to red in just a single match and then goes back up again, I get matched with few other cheaters, even at red trust

**Comment by xXTOO-HARDXx** [comment]
@vsnrytune why did I get banned while using it lol

**Comment by lordeternity000** [comment]
> > > > @m0nsterJ @lordeternity000 well, it's quite strange then. Maybe Valve has decided to incorporate a different play on cheaters  ... Maybe they are using a method similar to shadow banning, where essentially anyone that tried to bypass vac is put into red trust with other cheaters, rather than just getting banned, and also makes them think that the VAC Bypass IS actually working by not issuing VAC bans to people who are shadow banned, per se. This is the only conclusion I can seem to come to.
> > > 
> > > 
> > > This is false, I've been using vac bypass and osiris for ages and I'm still playing in green trust, although sometimes it can drop to red in literally one game, but goes back up again.
> > 
> > 
> > How long does it take in your case for the trust factor to go up again?
> 
> 1-5 games maybe, it stays at green for a while, but sometimes randomly drops to red in just a single match and then goes back up again, I get matched with few other cheaters, even at red trust

Maybe it doesn't turn green but your lobby members' trust factor is low so they don't see your red tf.

**Comment by lordeternity000** [comment]
> @vsnrytune why did I get banned while using it lol

You sure it was vac ban? Coz game bans also turn to vac-ban after 1 day or so.

**Comment by vsnrytune** [comment]
> > Maybe it doesn't turn green but your lobby members' trust factor is low so they don't see your red tf.

I'm not that stupid lol, it's obviously more likely that it's my trust going up to green and then back down to red, than my 4 teammates who are all legit and don't cheat, with really good old accounts

**Comment by xXTOO-HARDXx** [comment]
> > @vsnrytune why did I get banned while using it lol
> 
> You sure it was vac ban? Coz game bans also turn to vac-ban after 1 day or so.

It was indeed a VAC ban, I wouldn't of been game banned, I don't do anything suss. I only use bhop and edge jump in game lol.

**Comment by bootfast** [comment]
Vac bypass loader give me red tf too...
i dont think its safe anymore

**Comment by lordeternity000** [comment]
> > > @vsnrytune why did I get banned while using it lol
> > 
> > 
> > You sure it was vac ban? Coz game bans also turn to vac-ban after 1 day or so.
> 
> It was indeed a VAC ban, I wouldn't of been game banned, I don't do anything suss. I only use bhop and edge jump in game lol.

Dude you can learn that with practice. You don't have to use osiris just for that.

**Comment by xAkiraMiura** [comment]
> > I only use bhop and edge jump in game lol.
> 
> Dude you can learn that with practice. You don't have to use osiris just for that.

no. whenever you bhop you have less than or equal to a 50% chance of hitting a hop. bhopping legit is completely luck based, not skill.
also VMProtect is VAC detected.

**Comment by xXTOO-HARDXx** [comment]
> > > > @vsnrytune why did I get banned while using it lol
> > > 
> > > 
> > > You sure it was vac ban? Coz game bans also turn to vac-ban after 1 day or so.
> > 
> > 
> > It was indeed a VAC ban, I wouldn't of been game banned, I don't do anything suss. I only use bhop and edge jump in game lol.
> 
> Dude you can learn that with practice. You don't have to use osiris just for that.



> > > I only use bhop and edge jump in game lol.
> > 
> > 
> > Dude you can learn that with practice. You don't have to use osiris just for that.
> 
> no. whenever you bhop you have less than or equal to a 50% chance of hitting a hop. bhopping legit is completely luck based, not skill.
> also VMProtect is VAC detected.

@xAkiraMiura is right. 

@lordeternity000 

I don't use Osiris anymore anyway, I was just talking about VAC Bypass loader combined with something I made. I have stopped using VAC Bypass now because of red trust lmao. And yeahhh, I know, I can do most skill jumps I do without Edge Jump (engPred) but, it's just so much nicer hitting the jumps 100% of the time rather than like 60-75% of the time :)

**Comment by younasiqw** [comment]
No 100% Anti-Detection, Unless U Have VAC Bypass
