### ISSUE TITLE
Faceit Undetected!

### ISSUE THREAD

**Issue by bootfast** [danielkrupinski/Osiris#1504]
Can i get ban in faceit by using osiris??

**Comment by xpossed-you** [comment]
You cant get banned in faceit using osiris because you cant inject a dll to CSGO after opening FaceIt anticheat

**Comment by bootfast** [comment]
Any way to bypass faceit AC??

**Comment by xpossed-you** [comment]
its not impossible, but its pretty hard.
even if you manage to bypass it, faceit anticheat will take a screenshot from your screen to check if you use hack or not

**Comment by Oly-UK** [comment]
short answer: no

**Comment by younasiqw** [comment]
Faceit anti-cheat will rape u
