### ISSUE TITLE
Welcome Message Box

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#1506]
Hello
I would like to place again the welcome popup message that previously had the cheat.
Does anyone know how to do it and in which line would I go from hooks.cpp?

I have tried with
`interfaces.gameUI->messageBox("This was a triumph!", "Osiris has been successfully loaded.");`
and
`interfaces->gameUI->messageBox("This was a triumph!", "Osiris has been successfully loaded.");`

In neither case does it work
@danielkrupinski 

(Sorry for my english)

**Comment by danielkrupinski** [comment]
It's been renamed to createCommandMsgBox.

**Comment by TauCSGO** [comment]
> It's been renamed to createCommandMsgBox.

And what would the code line look like and what line would I put it on?
Sorry for the inconvenience

**Comment by danielkrupinski** [comment]
Put it anywhere after `interfaces` object initialization.

**Comment by TauCSGO** [comment]
> Put it anywhere after `interfaces` object initialization.

It doesn't work for me, I must be doing something wrong

**Comment by NekoRem** [comment]
> > Put it anywhere after `interfaces` object initialization.
> 
> It doesn't work for me, I must be doing something wrong

interfaces->gameUI->createCommandMsgBox("This was a triumph!", "Osiris has been successfully loaded.");

put this at the bottom of void Hooks::install() noexcept

**Comment by TauCSGO** [comment]
> > > Put it anywhere after `interfaces` object initialization.
> > 
> > 
> > It doesn't work for me, I must be doing something wrong
> 
> interfaces->gameUI->createCommandMsgBox("This was a triumph!", "Osiris has been successfully loaded.");
> 
> put this at the bottom of void Hooks::install() noexcept

Now Works!
Thank you very much ♥

**Comment by toprak1224** [comment]
where should i paste

**Comment by NekoRem** [comment]
i said where you should put it....

**Comment by toprak1224** [comment]
plss send me picture ım noob
