### ISSUE TITLE
Max angle delta

### ISSUE THREAD

**Issue by lordeternity000** [danielkrupinski/Osiris#1507]
What does max angle delta do and how much should it be set for legit?

**Comment by furioushell98** [comment]
If you set max angle delta to 30 or less you won't get vac auth error when using 255 fov in casual/deathmatch, this is the benefit i see from this option. You can still legit cheat fine with max angle delta (255) as long as you're using low fov

**Comment by lordeternity000** [comment]
Thanks. But do you know what it actually does?

**Comment by designer1337** [comment]
> Thanks. But do you know what it actually does?

He literally explained u

**Comment by FrontStreet** [comment]
> 
> 
> Thanks. But do you know what it actually does?

It basically controls how much the aimbot can move per shot. i.e low delta will force the aimbot to move slowly, max delta means it snaps instantly (if you're not using smoothness)

**Comment by lordeternity000** [comment]
> > Thanks. But do you know what it actually does?
> 
> It basically controls how much the aimbot can move per shot. i.e low delta will force the aimbot to move slowly, max delta means it snaps instantly (if you're not using smoothness)

Thanks
