### ISSUE TITLE
Dll not working

### ISSUE THREAD

**Issue by Bigbyk** [danielkrupinski/Osiris#151]
Hey 
I've done everything  as it is  written in instructions, i got a dll file but when I  inject it to csgo using HEX-EN it does not open with 'insert' key. I don't know why does this happen.

**Comment by Havoccboi** [comment]
Same here, dll not working for me atm

**Comment by danielkrupinski** [comment]
Please describe issue more closely.

**Comment by Havoccboi** [comment]
game is crashing when I try to inject , My processor supports AVX2 Im using it. i tried it with randolinjector(i used to do it) and also extreme injector game crashes for both the cases. another dll can be injected in the same process(i build solution with vs19 , sdk 10 and v142)

**Comment by strme** [comment]
Same problem, menu not work
The game crash only when i try inject with mmp

**Comment by strme** [comment]
I fixed it: Eanable Enhanced Istruction Set = Not Set

**Comment by Bigbyk** [comment]
My game is not crashing but the menu is  not opening in game ://

**Comment by Bigbyk** [comment]
Other cheats are working properly when injected, only this does not

**Comment by danielkrupinski** [comment]
It looks like a problem with your injector. I have no problems using [my own injector]( https://github.com/danielkrupinski/Inflame).

**Comment by Bigbyk** [comment]
Just one more question:
Why can't  I just download the dll file from here but I have to do it myself? No offense, I'm just curious

**Comment by effex1337** [comment]
Because it's open source and constantly updating

**Comment by Bigbyk** [comment]
I don't need 5 updates  a day to not get banned  tbh

**Comment by Bigbyk** [comment]
Or what kind of updates are theese
