### ISSUE TITLE
Can't find the "Osiris" folder to put a config.

### ISSUE THREAD

**Issue by Rezvann** [danielkrupinski/Osiris#1510]
Hello, i want to put a config and i can't find the "Osiris" folder in This PC/Documents

Can someone help me?

**Comment by dapaster** [comment]
just create the folder manually

**Comment by Rezvann** [comment]
Ok but nothing happens

**Comment by BoyWonder01** [comment]
Create the folder in Documents and then go ahead and create the config in Osiris.

**Comment by Rezvann** [comment]
> Create the folder in Documents and then go ahead and create the config in Osiris.

I want to put any config.

**Comment by Rezvann** [comment]
if I create a config in osiris the next time I enter it no longer appears to me

**Comment by Rezvann** [comment]
Nvm, I solved, ty

**Comment by xXTOO-HARDXx** [comment]
please close
