### ISSUE TITLE
Updating Imgui library causes an error with "Color"

### ISSUE THREAD

**Issue by greevak** [danielkrupinski/Osiris#1511]
That error been here right after i updated imgui.
Files i have updated right off imgui's github page were: 
![11](https://user-images.githubusercontent.com/38337258/80804321-75397100-8bbd-11ea-9ec6-2c162135fa46.png)

Except for imgui_draw.cpp, as i have copy pasted that right from the newest osiris' update to my modified version folder. ( Note that i have added custom themes to it).

As seen in this error, I have tried to look it up but seem to have no answers.
![Err](https://user-images.githubusercontent.com/38337258/80804206-212e8c80-8bbd-11ea-8a9f-e8fdbe22dc8f.png)
That seems to appear as well:
![Err2](https://user-images.githubusercontent.com/38337258/80809207-debf7c80-8bc9-11ea-8c0a-aa7e54c5ec3f.png)

Would appreciate any help, and if you can add me on discord (GREEV#3535) would be better.

**Comment by danielkrupinski** [comment]
Be careful when updating **imconfig.h** - it contains custom ImVec4 constructors.
