### ISSUE TITLE
[Help]How to simulate console command '+attack'

### ISSUE THREAD

**Issue by coron3hotdog** [danielkrupinski/Osiris#1514]
I encountered a anti-cheat using .smx plugins to detect one-tick perfect shoot, which is extactly what Osiris been using. Tested on local server and discovered that if you use 'mouse_event' to do the triggerbot trick you can bypass the Triggerbot detection, I'm just wondering if it's possible to triggerbot by inputting console command, feel free to leave your suggestion, appreciated!

**Comment by xXTOO-HARDXx** [comment]
This is possible, yes. Although I haven't done it myself before.

From what's been found before, look into integrating:
```
ClientCmd()
ExecuteClientCmd()
ClientCmd_Unrestricted ()
```

Their respective Virtual Functions:
```
virtual void ClientCmd (const char *szCmdString ) = 0;
virtual void ExecuteClientCmd (const char *szCmdString ) = 0;
virtual void ClientCmd_Unrestricted (const char *szCmdString ) = 0;
```

And their expanded, defined functions:

```
void CEngineClient::ClientCmd( const char *szCmdString )
{
    if (cl.m_bRestrictClientCommands)
    {
        Cbuf_AddExecutionMarker (eCmdExecutionMarker_Enable_FCVAR_CLIENTCMD_CAN_EXECUTE);
    }

    Cbuf_AddText( szCmdString );
    Cbuf_AddText("\n");
 
    if (cl.m_bRestrictClientCommands)
    {
        Cbuf_AddExecutionMarker (eCmdExecutionMarker_Disable_FCVAR_CLIENTCMD_CAN_EXECUTE);
    }
}

void CEngineClient::ExecuteClientCmd( const char *szCmdString )
{
    Cbuf_AddText( szCmdString );
    Cbuf_AddText("\n");
    Cbuf_Execute();
}

void CEngineClient::ClientCmd_Unrestricted( const char *szCmdString )
{
    Cbuf_AddText( szCmdString );
    Cbuf_AddText("\n");
}
```

**Comment by xXTOO-HARDXx** [comment]
So, theoretically, including these functions into the SDK, you'd be able to call something like:

`client->ClientCmd_Unrestricted ("+attack");`

might work, someone would have to test though.

**Comment by coron3hotdog** [comment]
> So, theoretically, including these functions into the SDK, you'd be able to call something like:
> 
> `client->ClientCmd_Unrestricted ("+attack");`
> 
> might work, someone would have to test though.

thx for the reply, i've been digging in the source and found there's already a function very similar to what you've mentioned above in SDK/Engine.h

`VIRTUAL_METHOD(void, clientCmdUnrestricted, 114, (const char* cmd), (this, cmd, false))`

so I tried to implement the original triggerbot from
`cmd->buttons |= UserCmd::IN_ATTACK;` to this `interfaces->engine->clientCmdUnrestricted("+attack;-attack");`

however in game, when I hold the triggerbot button, it didn't shoot. and when I mannually killed a bot by pressing left mouse button while holding the triggerbot key, it detects triggerbot. very strange to me.

**Comment by coron3hotdog** [comment]
btw, this is how this anti cheat detects triggerbot
[https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/1f5e77cc57a25772760d637f718f77d1dd6b095a/lilac.sp#L1239](url)

**Comment by xXTOO-HARDXx** [comment]
@coron3hotdog hmm, I see. Is the SDK you are using somewhere in Repo where I can view it? may make things easier if I can see exactly what's going on

**Comment by coron3hotdog** [comment]
> @coron3hotdog hmm, I see. Is the SDK you are using somewhere in Repo where I can view it? may make things easier if I can see exactly what's going on

here [https://github.com/danielkrupinski/Osiris/blob/master/Osiris/SDK/Engine.h#L44](url)

**Comment by xXTOO-HARDXx** [comment]
@coron3hotdog I did some testing and it seems and this worked:

```
std::string cmd1 = "+attack";
interfaces->engine->clientCmdUnrestricted ("cmd1");
std::string cmd2 = "-attack";
interfaces->engine->clientCmdUnrestricted ("cmd2");
```

i.e. you must call commands in separate function calls because when entering commands through console, each semicolon defines a new ExecuteClientCmd, e.g:

```
+attack; -attack would execute as:

ExecuteClientCmd ("+attack");
ExecuteClientCmd ("-attack");
```

**Comment by coron3hotdog** [comment]
@xXTOO-HARDXx tested but not working, maybe im doing something wrong, could you please add me on discord for further discussion?
coron3#6322

**Comment by xXTOO-HARDXx** [comment]
@coron3hotdog sure.
