### ISSUE TITLE
cant inject osiris into csgo

### ISSUE THREAD

**Issue by seabass23522** [danielkrupinski/Osiris#1515]
When I inject Osiris to csgo it says access is denied

**Comment by m0nsterJ** [comment]
@seabass23522 Could you please give more information?

**Comment by seabass23522** [comment]
what information do you need @m0nsterJ

**Comment by Zhxcky** [comment]
Run as administrator

**Comment by seabass23522** [comment]
When I do this pops up I don't know what it means      
![f](https://user-images.githubusercontent.com/54745955/80857050-0855c380-8c1d-11ea-94a1-288123f5e8bd.PNG)

**Comment by seabass23522** [comment]
I ran it as administrator nothing changed

**Comment by seabass23522** [comment]
this is what it says
![d](https://user-images.githubusercontent.com/54745955/80857152-da24b380-8c1d-11ea-8559-cba3578506f8.PNG)

**Comment by dctrlight** [comment]
go to Hacker->Show details for all processes

**Comment by seabass23522** [comment]
thank you @dctrlight
