### ISSUE TITLE
how can i add weapon icons?

### ISSUE THREAD

**Issue by shakeit1337** [danielkrupinski/Osiris#1517]
how can i add weapon icons? 
how can i add a background by spec list ?

sorry for bad english. ^^

**Comment by xXTOO-HARDXx** [comment]
I am not going to answer that second question lol, but for weapon icons, what I did once is make a custom font with the weapons icons as letters (A=AK47 icon, a=Glock18 Icon, etcetc) and then store the font in a byte array (unsigned char rather) and then the byte array will be loaded into memory and you can access the font like any other font and then use something along the lines of:

interfaces->surface->setTextFont (yourFontID);
interfaces->surface->setTextPosition (box2dx0 + box2dx1 - width) / 2, bbox.y0 - 5 - height);
interfaces->surface->printText ("A"); //for said AK47

**Comment by Kron1Q** [comment]
@xXTOO-HARDXx correct me if i am wrong but you cant do that with surface (font in byte array).

**Comment by xXTOO-HARDXx** [comment]
> @xXTOO-HARDXx correct me if i am wrong but i am pretty sure you cant do that with surface (font in byte array).

you know what, you might be right actually, I mean I don't see why you wouldn't be able to, maybe even if it required you to modify some things a bit... but it has been a long while since I did it, that was just how I remember doing it. :thinking:
