### ISSUE TITLE
How can I add Pull requests to my version of the cheat?

### ISSUE THREAD

**Issue by GreenNightfall** [danielkrupinski/Osiris#1519]
How can I add Pull requests to my version of the cheat?
When i add the code manually to every file it causes a lot of errors...

**Comment by Cyk-Fad** [comment]
I just paste it. You have to fix it.

**Comment by Cyk-Fad** [comment]
Most of them are old codes

**Comment by GreenNightfall** [comment]
Ok thx

**Comment by xAkiraMiura** [comment]
[git merge](https://lmgtfy.com/?q=git+merge)
pasting is error prone so its better to just let git try to solve diffs.
