### ISSUE TITLE
dll crashing game

### ISSUE THREAD

**Issue by hitlerjesus** [danielkrupinski/Osiris#152]
when injecting using extreme-injector, the game crashes. i have tried using sse, avx and no instructions and all lead to crashing. An older version of this cheat still injects but aimbot, knife changer and recoil crosshair dont work, esp still works. I am compiling with vs 2019.

**Comment by A-003** [comment]
Everything works for me

**Comment by hitlerjesus** [comment]
Changing these values on the latest version and then compiling also causes my game to crash when injecting. Not sure why this is happening because before the update everything was working was fine, if i use the old version some things dont work and a loud noise starts playing when i fire with anygun.
