### ISSUE TITLE
update

### ISSUE THREAD

**Issue by toprak1224** [danielkrupinski/Osiris#1520]
How can I update the files without editing them every time

**Comment by bekocango** [comment]
> How can I update the files without editing them every time

Nice question. +1

**Comment by rafalohaki** [comment]
merge them

**Comment by toprak1224** [comment]
@rafalohaki how ?

**Comment by rafalohaki** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork

**Comment by rafalohaki** [comment]
close it, i have spam on home page....

**Comment by rafalohaki** [comment]
@toprak1224
