### ISSUE TITLE
DONATE

### ISSUE THREAD

**Issue by toprak1224** [danielkrupinski/Osiris#1521]
I want to donate you, Daniel, but PayPal is not available in my country. Please add another payment option.

**Comment by dapaster** [comment]
@danielkrupinski

**Comment by TheFlyingGamer7** [comment]
@danielkrupinski

**Comment by toprak1224** [comment]
@danielkrupinski

**Comment by Oly-UK** [comment]
you could send the money to someone you really trust via bank transfer and then they send via paypal and shout you out in the comment or smth
