### ISSUE TITLE
Suggestions for functions u could add ✔

### ISSUE THREAD

**Issue by GreenNightfall** [danielkrupinski/Osiris#1522]
### More Improtant Features

• No Recoil / RCS Control
• Inventory Changer
• Legit Flickshot (More legit functions for aimbot⚠)
• Legit Bhop / Human Bhop
• Bomb Damage Indicator
• Grenade Predction saver (Save the spots where u can throw your grenades)
• Fake Medal (Part of Inventory Changer)
• OBS Proof
• FakeLag

### Less Important Features

• Live Radio / Music Feature
• Soundboard
• BlockBot
• Idk more features so if you guys have some ideas commend them

**Comment by m0nsterJ** [comment]
• Better Legit Desync / AA
• Legit Desync / AA resolver

**Comment by 3Ld4D** [comment]
pretty sure fake medal is fixed.
also for obs proof you have:
 https://github.com/danielkrupinski/GOESP

**Comment by Or3nges** [comment]
• Smoke timer
• Incendiary Timer
• Killsound via voice chat
• Choose how much zoom u want using 'Zoom' in the Visuals tab
• Legit fakeduck

**Comment by HackerGeo-sp1ne** [comment]
+1

**Comment by dapaster** [comment]
+1

**Comment by dapaster** [comment]
Here from pull request

`RCS`#1277 

`BlockBot` #1048 

`Legit Bhop` #1162 

`Bomb Dmg Indicator` #1016 

and fakelag is already in osiris . It was `Choked Packet` on the Misc tab.

**Comment by dapaster** [comment]
legit flickshot +1

**Comment by Evilhelder** [comment]
add this too: 

Grief box / Damage Team counter: #1149

**Comment by toprak1224** [comment]
rank cahnger +1

**Comment by GreenNightfall** [comment]
> Here from pull request
> 
> `RCS`#1277
> 
> `BlockBot` #1048
> 
> `Legit Bhop` #1162
> 
> `Bomb Dmg Indicator` #1016
> 
> and fakelag is already in osiris . It was `Choked Packet` on the Misc tab.

Is there a tutorial how to add pull requests into the cheat code?

**Comment by Zhxcky** [comment]
• Limit remover for viewmodels X, Y, Z (Unnecessary)
• Freecam
• Legit AA
• Better Skinchanger menu (The Skin will load based on the weapons, example when you choose AK-47 it will only show a skin that exist for AK-47, not putting all the Skin into 1 place)
• Working StatTrak

**Comment by notgoodusename** [comment]
no spread??????

**Comment by Zhxcky** [comment]
> no spread??????

It was exist 7 months ago on  Gamesense, i don't know if it still possible or nah

**Comment by 3Ld4D** [comment]
it's for no spread hvh

**Comment by OBO-1** [comment]
• Aimbot threshold/deadzone.
• Fast Stop.
• Run boost bot.

**Comment by ConniKiwi** [comment]
God you guys are ever so needy XD

**Comment by notgoodusename** [comment]
there is nospread for hvh already, bruh

**Comment by ConniKiwi** [comment]
Imagine trying to predict spread on a hvh server that disabled spread bitch youd miss every shot

**Comment by notgoodusename** [comment]
osiris doesnt compensate for spread.

**Comment by ConniKiwi** [comment]
Its pretty simple to add

**Comment by 3Ld4D** [comment]
i actually did nospread hvh with my version of osiris and it was bad.
you wouldn't even shoot at ppl with untrusted pitches and things u use in nospread.

**Comment by ConniKiwi** [comment]
rly, did you implement it correctly?

**Comment by 3Ld4D** [comment]
> rly, did you implement it correctly?

i didn't implement anything to aimbot.
it just wouldn't shoot at him, while it was fine on my friend which was using regular down pitch (89).

**Comment by ConniKiwi** [comment]
Oh on no spread hvh with osiris you have to check the the no spread cvar and if its true i believe you can disable any anti spread and possibly recoil to

**Comment by 3Ld4D** [comment]
> Oh on no spread hvh with osiris you have to check the the no spread cvar and if its true i believe you can disable any anti spread and possibly recoil to

i've made hitchance for aimbot so that wasn't an issue it's just invalid pitches

**Comment by ConniKiwi** [comment]
Alright, id patch the spread issue though if i was you allows you to have higher hitchance values

**Comment by zxsleebu** [comment]
Really working resolver. Resolver in current version of Osiris does not work properly. i can't hit nobody with min damage 0 and other hvh settings. It really miss so much

**Comment by notgoodusename** [comment]
> Really working resolver. Resolver in current version of Osiris does not work properly. i can't hit nobody with min damage 0 and other hvh settings. It really miss so much

there isnt a resolver

**Comment by zxsleebu** [comment]
> and fakelag is already in osiris . It was `Choked Packet` on the Misc tab.

it works on key lol. i think peek on lag will be better

**Comment by zxsleebu** [comment]
> there isnt a resolver

but why it miss so many times even when enemy and me aren't moving ◘_◘

**Comment by ConniKiwi** [comment]
If you want fake lag all you have to do is choke packets count how many are choked and make sure to not choke more than aprox 14 packets and youll be good

**Comment by OBO-1** [comment]
> Really working resolver. Resolver in current version of Osiris does not work properly. i can't hit nobody with min damage 0 and other hvh settings. It really miss so much

what resolver?

**Comment by zxsleebu** [comment]
> If you want fake lag all you have to do is choke packets count how many are choked and make sure to not choke more than aprox 14 packets and youll be good

so it will work even if i will not press the key?

**Comment by notgoodusename** [comment]
> > If you want fake lag all you have to do is choke packets count how many are choked and make sure to not choke more than aprox 14 packets and youll be good
> 
> so it will work even if i will not press the key?

yes

**Comment by zxsleebu** [comment]
AntiAim stopping on throwing a grenade. It throwes grenades right where you are :(

**Comment by ConniKiwi** [comment]
To go a step further you could cast rays to add on peak

**Comment by notgoodusename** [comment]
or just use the canscan func from aimbot and fakelag

**Comment by ConniKiwi** [comment]
> 
> 
> Add please AntiAim stopping on throwing a grenade. It throwes grenades right where you are :(

`    if (cmd->buttons & UserCmd::IN_ATTACK) {
        return;
    }
    if (cmd->buttons & UserCmd::IN_USE) {
        return;
    }`

I think this will work

**Comment by notgoodusename** [comment]
> > Add please AntiAim stopping on throwing a grenade. It throwes grenades right where you are :(
> 
> ` if (cmd->buttons & UserCmd::IN_ATTACK) { return; } if (cmd->buttons & UserCmd::IN_USE) { return; }`
> 
> I think this will work

if (cmd->buttons & (UserCmd::IN_ATTACK | UserCmd::IN_USE)) 
{
do stuff
}

**Comment by zxsleebu** [comment]
> `if (cmd->buttons & UserCmd::IN_ATTACK) { return; } if (cmd->buttons & UserCmd::IN_USE) { return; }`
> 
> I think this will work

thanks man. i'll edit this comment if it will work

**Comment by ConniKiwi** [comment]
> 
> 
> > > Add please AntiAim stopping on throwing a grenade. It throwes grenades right where you are :(
> > 
> > 
> > ` if (cmd->buttons & UserCmd::IN_ATTACK) { return; } if (cmd->buttons & UserCmd::IN_USE) { return; }`
> > I think this will work
> 
> if (cmd->buttons & (UserCmd::IN_ATTACK | UserCmd::IN_USE))
> {
> do stuff
> }

Use this its alot more tidy

**Comment by zxsleebu** [comment]
> Use this its alot more tidy

i'll try both

**Comment by ConniKiwi** [comment]
They are both the same pieces of code written differently

**Comment by zxsleebu** [comment]
> They are both the same pieces of code written differently

ik. but i think that @notgoodusename 's option looks simplier xdd

**Comment by ConniKiwi** [comment]
Yeh it does lol

**Comment by king1919djdj** [comment]
how about a bullet trace ?

**Comment by aljawary** [comment]
add desync chams pls i cant see my fake body :(
