### ISSUE TITLE
Butterfly knife animation issues

### ISSUE THREAD

**Issue by mm0ji** [danielkrupinski/Osiris#1523]

**Comment by CerberusGame** [comment]
+1

**Comment by Cyk-Fad** [comment]
+1

**Comment by bekocango** [comment]
> * The butterfly knife will rubberband on the animation where the player's fingers move to slide across the bottom of the blade.
> * The randomization for the pullouts seem to be inaccurate with the second pullout occurring around 50% of the time instead of 10-15% of the time.

Same on shadow daggers. When i press left mouse button.

**Comment by Cyk-Fad** [comment]
> > * 蝴蝶刀将在动画上橡皮筋缠住，玩家的手指在该动画上移动以滑过刀片的底部。
> > * 提取的随机性似乎不准确，因为第二次提取的发生时间约为50％，而不是10-15％。
> 
> 暗影匕首也一样。当我按下鼠标左键时。

+1
