### ISSUE TITLE
AntiAim on grenade

### ISSUE THREAD

**Issue by egssy0** [danielkrupinski/Osiris#1524]
AntiAim on grenade

**Comment by xpossed-you** [comment]
you gonna tell us the problem or what?

**Comment by 3Ld4D** [comment]
> you gonna tell us the problem or what?

anti aim doesn't get disabled when u throw.
i might make a pull for that if needed.

**Comment by egssy0** [comment]
Y please, I tried somethin but so much errors etc

**Comment by 3Ld4D** [comment]
@egssy0
https://github.com/danielkrupinski/Osiris/pull/1525
