### ISSUE TITLE
Cheat ready

### ISSUE THREAD

**Issue by egssy0** [danielkrupinski/Osiris#1528]
how can i notification cheat ready this is old ready message but doesnt works anymore pls help
interfaces.gameUI->messageBox("title", "Osiris ready");

**Comment by KernCS** [comment]
Under " Hooks::Hooks(HMODULE cheatModule) : module{ cheatModule } " paste this
" interfaces->gameUI->messageBox("title", "Osiris ready");   "

**Comment by egssy0** [comment]
Class gameui doesnt includes messageBox

**Comment by NekoRem** [comment]
#1506

**Comment by toprak1224** [comment]
https://hizliresim.com/7SMEAG   plss help me I can not

**Comment by egssy0** [comment]
@toprak1224 maybe too late answer but u forgot ending your command.
