### ISSUE TITLE
Signature

### ISSUE THREAD

**Issue by bogdancstrike** [danielkrupinski/Osiris#1529]
Hi everyone.
I know that's not an issue, i just was wondering how can i change the cheat signature? Like, what to modify and which files? I'm new to hacking and I'd like to learn on a real project like this.
Also, I'd like to modify the code a bit. I'd like to remove all functions except aimbot, rank revealer and radar hack. Is it possible, if yes, how?

**Comment by NekoRem** [comment]
Remove the code for all the cheat functions you're not using but make sure not to remove anything vital.

**Comment by bogdancstrike** [comment]
And for the signature changing, what should i remove? As I know, renaming variables/functions won't change anything. Junk code is still junk, not working as I know.

**Comment by NekoRem** [comment]
I'm not spoon feeding you. Research it.

**Comment by danielkrupinski** [comment]
Hook compiler function responsible for code generation and alter machine code it produces.
