### ISSUE TITLE
cheat crashes when i die

### ISSUE THREAD

**Issue by egssy0** [danielkrupinski/Osiris#1531]
cheat crashes when i die

**Comment by 3Ld4D** [comment]
u probably forgot to add localplayer or weapon check

**Comment by Oly-UK** [comment]
did you add any features yourself or from a pull request? if so which ones
attach visual studio debugger to see what line you crash at

**Comment by egssy0** [comment]
Y, I got it
Causes my new antiaim #1525 
Idk but it crashes when I throw flashbang too
But I removed them works normal now
