### ISSUE TITLE
Hooking - SendNetMsg

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#1532]
Im trying to hook the sendnetmsg for sv_pure bypass but i cant seem to find out the correct index for the v function

**Comment by ConniKiwi** [comment]
nope its this thats my issue (uc paste for sv_pure)

return hooks.engine.callOriginal<bool, 42(pNetChan, msg, bForceReliable, bVoice);
https://imgur.com/a/MjjukMz

bool __fastcall SendNetMsg(INetChannel* pNetChan, void* edx, INetMessage& msg, bool bForceReliable, bool bVoice)
{
    if (msg.GetType() == 14) // Return and don't send messsage if its FileCRCCheck
        return false;

    if (msg.GetGroup() == 9) // Fix lag when transmitting voice and fakelagging
        bVoice = true;

    return hooks.engine.callOriginal<bool, 42(pNetChan, msg, bForceReliable, bVoice);
}

**Comment by 3Ld4D** [comment]
try
```cpp
hooks.engine.callOriginal<bool, 42, INetChannel*,void*, bool, bool>(pNetChan, msg, bForceReliable, bVoice);

**Comment by Oly-UK** [comment]
i havent tried it but this gives no errors
`return hooks->engine.callOriginal<INetChannel*, 42, void*, INetMessage&, bool, bool>(pNetChan, msg, bForceReliable, bVoice);`

**Comment by Oly-UK** [comment]
could you send me your INetChannel and Message classes please

**Comment by Oly-UK** [comment]
nevermind i got it. i will test it in a min

**Comment by Oly-UK** [comment]
just tried it, getting kicked using old sounds :/

**Comment by ConniKiwi** [comment]
any results as im now about to test

**Comment by ConniKiwi** [comment]
https://imgur.com/a/fPg4b0o

I got this during testing

` engine.hookAt(42, SendNetMsg);`

This is the code i used to hook it not sure if its correct?

**Comment by notgoodusename** [comment]
index is 40

**Comment by notgoodusename** [comment]
also you have to hook netchannel

**Comment by ConniKiwi** [comment]
ok i can hook netchannel but how do i hook SendNetMsg in terms of netchannel

**Comment by ConniKiwi** [comment]
well i dont have a hook setup but i can get the netchannel using sig
