### ISSUE TITLE
Backtrack Issues

### ISSUE THREAD

**Issue by sundafused** [danielkrupinski/Osiris#1534]
Alright, I've tried different combinations of settings, configs, versions of the cheat, but I cannot for the life of me get backtrack to work. I have no clue why. I have packets choked, always, or on key, and even try to shoot the backtrack chams, but I'm not getting results. Anyone know what might be goin on?

**Comment by xXTOO-HARDXx** [comment]
Choked packets aren't needed for backtrack. Maybe you just have very inconsistent internet

**Comment by sundafused** [comment]
> Choked packets aren't needed for backtrack. Maybe you just have very inconsistent internet

That could definitely be it, I appreciate it.
