### ISSUE TITLE
static constexpr const char* Language coding problem .

### ISSUE THREAD

**Issue by cha222554** [danielkrupinski/Osiris#1537]
![QQ截图20200505181537](https://user-images.githubusercontent.com/12673397/81056058-768bd600-8efc-11ea-814a-0b32cad4c575.jpg)
![QQ截图20200505181528](https://user-images.githubusercontent.com/12673397/81056061-78559980-8efc-11ea-8f61-c24842995c9e.jpg)
![QQ截图20200505181453](https://user-images.githubusercontent.com/12673397/81056065-78ee3000-8efc-11ea-82f5-c4824fe716fb.jpg)
![Screen1](https://user-images.githubusercontent.com/12673397/81056066-78ee3000-8efc-11ea-843c-d33f8cabd204.jpg)

whats the problem ?
static constexpr const char* cant Compile with U8 so i didnt add that .
and it cant display in ESP option(shows ???) but can display in aimbot option .

**Comment by wirebruh** [comment]
is it the same font?

**Comment by younasiqw** [comment]
Once you successfully use Chinese, it is estimated that it will be sold. hhhh

**Comment by cha222554** [comment]
> Once you successfully use Chinese, it is estimated that it will be sold. hhhh

dont be a idiot jerk here.

**Comment by cha222554** [comment]
> is it the same font?

the font he push didnt the same (but add utf8) , i try push same font and got crash .

**Comment by younasiqw** [comment]
> > Once you successfully use Chinese, it is estimated that it will be sold. hhhh
> 
> dont be a idiot jerk here.

As far as I know, there are many people who use this source to sell in China, just simply added Chinese, and did not even change the UI :))
If you are not such a person, why do you need to change the characters to Chinese? Just for learning the code will not need to change at all, ridiculous
Your UTF-8 wording is even wrong, please learn the basics

**Comment by cha222554** [comment]
> > > 一旦您成功使用了中文，估计它将被出售。h
> > 
> > 
> > 不要在这里成为白痴。
> 
> 据我所知，有很多人使用此资源在中国销售，只是添加了中文，甚至没有更改用户界面:)）
> 如果您不是这样的人，为什么需要更改字符对中文？仅仅为了学习代码根本就不需要更改，荒谬
> 您的UTF-8措辞甚至是错误的，请学习基础知识

as far as i know , many people in china is not like you always say hate speech in many website , almost all time is you guys started it and upgrade a simple QA learning quesiton to racial discrimination . i dont care u say im a noob or something else . but please dont make you self like a fool by saying racial hate speech in GITHUB .

all ethnic groups in all regions have villains to transform open source programs to sell, which has nothing to do with the chinese or a single race. I suggest you broaden your horizons and dont make racial discrimination in open source forums its shame .

**Comment by cha222554** [comment]
> > > Once you successfully use Chinese, it is estimated that it will be sold. hhhh
> > 
> > 
> > dont be a idiot jerk here.
> 
> As far as I know, there are many people who use this source to sell in China, just simply added Chinese, and did not even change the UI :))
> If you are not such a person, why do you need to change the characters to Chinese? Just for learning the code will not need to change at all, ridiculous
> Your UTF-8 wording is even wrong, please learn the basics

as far as i know , many people in china is not like you always say hate speech in many website , almost all time is you guys started it and upgrade a simple QA learning quesiton to racial discrimination . i dont care u say im a noob or something else . but please dont make you self like a fool by saying racial hate speech in GITHUB .

all ethnic groups in all regions have villains to transform open source programs to sell, which has nothing to do with the chinese or a single race. I suggest you broaden your horizons and dont make racial discrimination speech in open source forums its shame .

**Comment by younasiqw** [comment]
I have no racial discrimination, only u think others are discriminating against u :))

**Comment by cha222554** [comment]
i can accept 

> I have no racial discrimination, only u think others are discriminating against u :))

im sorry , but if i say something about hongkong or taiwan , u guys will say many bad word to me .
so i never talk about politics and race .
like "many people in hongkong balabla " i will never use the word like that .
and im not hate you region people , i dont know why u against me .
i love china , im chinese , but it doesnt mean i must love our goverment , and i didnt do badthing to you or you region . i love hongkong too.
and i cant accept cuz some idiot sell free things , so all race is *** the word like that .
i just being reason about what you're talking about.
all u words shows how u hate to a chinese race . and will all know .

but I don't want to have this meaningless debate any more. u shouldnt come to this technical forum to discuss how a race are bad . u should go tweet .

**Comment by Cyk-Fad** [comment]
你是哪个组的？
你想翻译加我QQ 2476159893

**Comment by Cyk-Fad** [comment]
我是专业魔改os与翻译的 我是发呆

**Comment by Cyk-Fad** [comment]
我是DLL研究所的

**Comment by Mankvis** [comment]
> ![QQ截图20200505181537](https://user-images.githubusercontent.com/12673397/81056058-768bd600-8efc-11ea-814a-0b32cad4c575.jpg)
> ![QQ截图20200505181528](https://user-images.githubusercontent.com/12673397/81056061-78559980-8efc-11ea-8f61-c24842995c9e.jpg)
> ![QQ截图20200505181453](https://user-images.githubusercontent.com/12673397/81056065-78ee3000-8efc-11ea-82f5-c4824fe716fb.jpg)
> ![屏幕1](https://user-images.githubusercontent.com/12673397/81056066-78ee3000-8efc-11ea-843c-d33f8cabd204.jpg)
> 
> 有什么问题 ？
> 静态constexpr const char *无法使用U8进行编译，所以我没有添加它。
> 并且它不能显示在ESP选项中（显示???），但是可以显示在aimbot选项中。

你翻译好了吗？我这边使用U8显示的都是???

**Comment by Cyk-Fad** [comment]
我明天回家 到时候找你 不用加U8

**Comment by Cyk-Fad** [comment]
加我QQ 2476159893
