### ISSUE TITLE
[standalone rcs request]

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1538]
hey, can anyone link me a standalone rcs , or give me code to paste?

**Comment by HowToMakeFaceitAB** [comment]
I would code it myself if I wasn't just learning arrays, I'm new to c++ but I intend on improving

**Comment by Kron1Q** [comment]
https://github.com/danielkrupinski/Osiris/pull/1277
https://github.com/danielkrupinski/Osiris/pull/769

**Comment by HowToMakeFaceitAB** [comment]
> #1277
> #769

doesn't work sadly, how can i get it to work

**Comment by Hunterswat** [comment]
> > [# 1277 ](https://github.com/danielkrupinski/Osiris/pull/1277)
> > [# 769](https://github.com/danielkrupinski/Osiris/pull/769)
> 
> infelizmente não funciona, como posso fazê-lo funcionar?

I can add, discord: MunhoZ # 4150
