### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by HackerGeo-sp1ne** [danielkrupinski/Osiris#1539]
![Untitled](https://user-images.githubusercontent.com/42976769/81089527-26654180-8f05-11ea-94c1-cbf98d1fb8ec.png)

**Comment by 3Ld4D** [comment]
don't modify the code when u don't know how to...

**Comment by notgoodusename** [comment]
stop saying the same thing over and over... the problem comes from the config and this only happens when debugging, to fix the issue just put a bigger number on the array
    struct Aimbot {
//variables
    };
    std::array<Aimbot, 40> aimbot;
change that to something higher like 70
and do the same with triggerbot

**Comment by wirebruh** [comment]
> don't modify the code when u don't know how to...

its not that website with unknown cheats, its github

**Comment by bambusboy** [comment]
std::array<Aimbot, 40> aimbot;
int index = (some value);
int ci = std::clamp(index, 0, (int)aimbot.size());
works for me

**Comment by NekoRem** [comment]
It's the chams material. I believe Daniel fixed it in the latest commits.
