### ISSUE TITLE
interfaces->engine->getPlayerInfo())->getMaxDesyncAngle();

### ISSUE THREAD

**Issue by egssy0** [danielkrupinski/Osiris#1540]
interfaces->engine->getPlayerInfo())->getMaxDesyncAngle();

**Comment by egssy0** [comment]
this doesnt works what i must do

**Comment by egssy0** [comment]
it gives E0165 code im using TR version of VS

**Comment by notgoodusename** [comment]
localPlayer.get()->getMaxDesyncAngle();

**Comment by egssy0** [comment]
cmd->viewangles.y += interfaces->entityList->getEntity(localPlayer.get()->getMaxDesyncAngle());

now E2138

i trying do this
https://github.com/danielkrupinski/Osiris/pull/989

**Comment by 3Ld4D** [comment]
```cpp
cmd->viewangles.y += localPlayer->getMaxDesyncAngle();

**Comment by egssy0** [comment]
thanks dude it works now!
