### ISSUE TITLE
question about GUI

### ISSUE THREAD

**Issue by notmugi** [danielkrupinski/Osiris#1541]
does anyone know how easy/hard it would be to port Osiris over to zgui? I'm not a fan of imgui and i want to try zgui but i dont really know how i'd go about doing it. I know imgui is extremely customizable but i like the way zgui looks out of the box. Any help is super appreciated.

**Comment by notgoodusename** [comment]
welp you would have to
-delete imgui folder
-import zgui into a folder
-redo gui.cpp

**Comment by notmugi** [comment]
is that really it lol? That's not too bad. I assumed you'd have to do alot more, or redo a ton of stuff

**Comment by notgoodusename** [comment]
AND maybe redoing some other stuff

**Comment by NekoRem** [comment]
you would also need to make the rendering functions

**Comment by notmugi** [comment]
Yeah I looked more into this, pulled a fresh copy of Osiris and tried it. I'll work more on it but idk if it's something I'm willing to put as much work as it would require into it. the more I did stuff the more I realized there was more I needed to change and fix/add. I'll close this for now. If I figure anything out I'll reopen incase anyone else is curious how it's done or smth

**Comment by NekoRem** [comment]
If you're curious how zgui is implemented check an old repository of mine out. This was the first time i started using zgui. Tbh i believe imgui is better and easier to use.
https://github.com/NekoRem/alphauc-sdk-zgui
