### ISSUE TITLE
AntiAim

### ISSUE THREAD

**Issue by egssy0** [danielkrupinski/Osiris#1542]
how can i see my antiaim?

**Comment by notgoodusename** [comment]
*reinterpret_cast<Vector*>(reinterpret_cast<uintptr_t>(localPlayer.get()) + 0x31D8) = sent;

**Comment by egssy0** [comment]
emmm, im not really experinced what i must do this?

**Comment by bambusboy** [comment]
bot_mimic 1

**Comment by DoomFishWasTaken** [comment]
made a pull, close this #1546

**Comment by egssy0** [comment]
Thanks!
