### ISSUE TITLE
custom skybox

### ISSUE THREAD

**Issue by jestemgosciem** [danielkrupinski/Osiris#1544]
I would like a custom skybox to type the name like hitsound.

**Comment by NekoRem** [comment]
Add the material file into the skybox material folder and then add an option to change to that material. I believe it's located in "Counter-Strike Global Offensive\csgo\materials\skybox\"

**Comment by jestemgosciem** [comment]
i know but I mean to enter the name skybox

**Comment by NekoRem** [comment]
I cannot help you when I don’t understand you

**Comment by jestemgosciem** [comment]
click custom and put the name of the skybox in there.
