### ISSUE TITLE
Eventlistener?

### ISSUE THREAD

**Issue by egssy0** [danielkrupinski/Osiris#1545]
how can i add event listener window

**Comment by egssy0** [comment]
and how can i draw background of watermark?

**Comment by OBO-1** [comment]
noob dog fan?

**Comment by egssy0** [comment]
shut up ** 

> dog shit

**

**Comment by bambusboy** [comment]
https://www.learncpp.com

**Comment by egssy0** [comment]
I have books for learning thanks 3 iq dog

**Comment by 3Ld4D** [comment]
> I have books for learning thanks 3 iq dog

then why u didn't read it fully

**Comment by egssy0** [comment]
started 1m ago / i trying learn php too

**Comment by 3Ld4D** [comment]
so u could make a loader as well as website and sell osiris for 20$ per month?

**Comment by egssy0** [comment]
nop

**Comment by bambusboy** [comment]
bro u dont have basic understanding of coding hacks and ur calling ppl 3 iq dogs while u have one on pfp smfh

**Comment by egssy0** [comment]
@bambusboy @3Ld4D @IsaacPV @mdilai , I'm ok about that, I was a newcomer c++.
