### ISSUE TITLE
Silent Aimbot

### ISSUE THREAD

**Issue by TheFlyingGamer7** [danielkrupinski/Osiris#1548]
I have some quick questions about the silent feature of the aimbot:

Is it perfect silent - as in do spectators / over watchers see the snap to the enemy?

Thanks

**Comment by TheFlyingGamer7** [comment]
After running a couple tests I have come to believe it is perfect silent but would like to know what anyone else thinks

**Comment by sundafused** [comment]
There is no such thing as pSilent anymore, silent aim is completely clientside.

**Comment by TheFlyingGamer7** [comment]
> There is no such thing as pSilent anymore, silent aim is completely clientside.

Ah OK, so to check if it looks legit can you watch replays / demos? Or will that still not show what it looks like on OW / to spectators

**Comment by Zhxcky** [comment]
> > There is no such thing as pSilent anymore, silent aim is completely clientside.
> 
> Ah OK, so to check if it looks legit can you watch replays / demos? Or will that still not show what it looks like on OW / to spectators

watch the demo whilst using silent aimbot, it will snap ur aim

**Comment by xpossed-you** [comment]
> 
> 
> > > There is no such thing as pSilent anymore, silent aim is completely clientside.
> > 
> > 
> > Ah OK, so to check if it looks legit can you watch replays / demos? Or will that still not show what it looks like on OW / to spectators
> 
> watch the demo whilst using silent aimbot, it will snap ur aim

i watch demo, and it looks completely silent for me. my friend using Osiris, and when he shoot the enemy the bullet hit the nearest target but i dont see any snap back to crosshair.

**Comment by TheFlyingGamer7** [comment]
> > > There is no such thing as pSilent anymore, silent aim is completely clientside.
> > 
> > 
> > Ah OK, so to check if it looks legit can you watch replays / demos? Or will that still not show what it looks like on OW / to spectators
> 
> watch the demo whilst using silent aimbot, it will snap ur aim

I've only tried it at like 1 fov or so, and that seems fine so will test at a higher amount some time

**Comment by TheFlyingGamer7** [comment]
> > > > There is no such thing as pSilent anymore, silent aim is completely clientside.
> > > 
> > > 
> > > Ah OK, so to check if it looks legit can you watch replays / demos? Or will that still not show what it looks like on OW / to spectators
> > 
> > 
> > watch the demo whilst using silent aimbot, it will snap ur aim
> 
> i watch demo, and it looks completely silent for me. my friend using Osiris, and when he shoot the enemy the bullet hit the nearest target but i dont see any snap back to crosshair.

Yeah same, but I use 0.5 to 1.2 fov max with it as I only really need a very slight assit

**Comment by Finndramere** [comment]
0.5 fov is the minimum i go for. Anything above 1 fov is blatant and too consistent. if you want to go for 1 fov and above go for silent aim = disabled, bone = nearest, smooth = 2, and between shots = disabled. Snappy sometimes so I don't recommend.

**Comment by Shuvi-Moro** [comment]
[Osiris.zip](https://github.com/danielkrupinski/Osiris/files/4594550/Osiris.zip)

**Comment by Shuvi-Moro** [comment]
my configs

**Comment by xpossed-you** [comment]
> 
> 
> [Osiris.zip](https://github.com/danielkrupinski/Osiris/files/4594550/Osiris.zip)

no one asking for your config, but ok
