### ISSUE TITLE
Change ImGui Style

### ISSUE THREAD

**Issue by icantfindausernamelol** [danielkrupinski/Osiris#1549]
Hello everyone. I am new to programming and I don't a lot about c. I want to change the style of my Osiris cheat but wherever I found a style online I didn't knew where to paste it or what I had to do. Please don't start harassing me and sorry for the bad English.

**Comment by egssy0** [comment]
If you want paste themes edit **imgui_draw.cpp**
If you want paste checkboxes etc. edit **imgui_widgets.cpp**

**Comment by egssy0** [comment]
If you want add new style you must edit **imgui.h** // **GUI.cpp** too

**Comment by icantfindausernamelol** [comment]
> If you want paste themes edit **imgui_draw.cpp**
> If you want paste checkboxes etc. edit **imgui_widgets.cpp**

Thank you so much! I am just new and I don't know a lot.

**Comment by xpossed-you** [comment]
> 
> 
> If you want add new style you must edit **imgui.h** // **GUI.cpp** too

you dont need to edit imgui.h imo

**Comment by egssy0** [comment]
if he want make it selectable he must do it

**Comment by 3Ld4D** [comment]
just don't touch ImConfig cuz it can fuck up calculations like ImVec2 + ImVec2

**Comment by icantfindausernamelol** [comment]
> just don't touch ImConfig cuz it can fuck up calculations like ImVec2 + ImVec2

Thanks for the answers but I still can't understand how to add or edit the theme of imgui cuz I ain't no worked with it before.

**Comment by 3Ld4D** [comment]
```cpp
ImGui::PushStyleColor(ImGuiCol_ChildBg,ImVec4(0,0,0,0)); //changes background color of childs to black

ImGui::PopStyleColor(); //don't forget this otherwise it will crash ur game

**Comment by icantfindausernamelol** [comment]
> ```c++
> ImGui::PushStyleColor(ImGuiCol_ChildBg,ImVec4(0,0,0,0)); //changes background color of childs to black
> 
> ImGui::PopStyleColor(); //don't forget this otherwise it will crash ur game
> ```

Alright I start to understand how this works cuz I am now watching some online tutorials about imgui. One last question, pushstylecolor is the only thing I can change?
