### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by effex1337** [danielkrupinski/Osiris#155]
Does this cheat have backtrack? 
I kinda feel like it has it. :thinking:

**Comment by PAWX4321** [comment]
NOŁ
this heat noł have baktrak
sry for my bad englishj

**Comment by effex1337** [comment]
Like i feel the enemy getting backtracked

**Comment by Tetrisz** [comment]
There's no backtracking, most likely actual lag compensation from high ping or just the aimbot killing people.

**Comment by Shaxzy** [comment]
As stated above, no backtrack

**Comment by 0xAB51NTH** [comment]
Sadly no bacctrack
