### ISSUE TITLE
These 2 features don't work for me

### ISSUE THREAD

**Issue by Uronic** [danielkrupinski/Osiris#1552]
Autostrafe and Viewmodel Z adjustment do not work for me. I tried looking in issues for these and did not find a fix, for autostrafe I only found that it works when it clearly does not for me. Please fix.

**Comment by 3Ld4D** [comment]
> Autostrafe and Viewmodel Z adjustment do not work for me. I tried looking in issues for these and did not find a fix, for autostrafe I only found that it works when it clearly does not for me. Please fix.

autostrafe works you just don't see the movement of it.

**Comment by xpossed-you** [comment]
autostrafe activated whenever you jump, so if you want to bunnyhop dont press W

**Comment by Uronic** [comment]
still doesnt work

**Comment by 3Ld4D** [comment]
like i said you can't see the movement of auto strafe

**Comment by Uronic** [comment]
yea but i dont see any sort of speed increase at all in cl_showpos, autostrafe is either supposed to turn for u when u move ur mouse or give u speed with wigglehack, i dont see any of these two occuring, it doesnt work.

**Comment by 3Ld4D** [comment]
wigglehack 😂
it works when u move your mouse, if you looked at the code you would see that.
```cpp
        if (cmd->mousedx < 0)
            cmd->sidemove = -450.0f;
        else if (cmd->mousedx > 0)
            cmd->sidemove = 450.0f;

**Comment by Uronic** [comment]
I have seen the code months before and have already seen this, I feel like I need to show how the autostrafe looks and how it does not work at all on my side. Here is some proof. https://streamable.com/16t0dy

**Comment by 3Ld4D** [comment]
you are not supposed to spin with it.
you get speed when u go around the corner or something.
mousedx isn't the best way to do auto strafe but it does the job.
