### ISSUE TITLE
sv_pure bypass? 

### ISSUE THREAD

**Issue by icantfindausernamelol** [danielkrupinski/Osiris#1553]
Is there a way to implement a sv_pure bypass feature in Osiris. If yes how?

**Comment by xpossed-you** [comment]
yes

**Comment by littlehurensohn** [comment]
Like that: https://www.unknowncheats.me/forum/counterstrike-global-offensive/279394-dumb-sv_pure-bypass.html

**Comment by Cyk-Fad** [comment]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/392489-fixing-sv_pure-kicks.html

**Comment by hyperxpro** [comment]
Duplicate of #1235, #1138. #687, #569, #442 and #416
