### ISSUE TITLE
IMGUI Checkboxes style

### ISSUE THREAD

**Issue by greevak** [danielkrupinski/Osiris#1554]
I want to change the checkboxes style to this style, but it seem to not be working.

Any idea on how to implement it to osiris? It gives a bunch of errors for whatever reason.
Tried to fixed them but it seems that its related to some specific callouts that am not aware of.

Looking:
![0](https://i.imgur.com/hrizPas.png)

style:
https://pastebin.com/skJPXcNh

**Comment by xXTOO-HARDXx** [comment]
well maybe if you showed us some of the errors we'd be able to help :)

**Comment by wheremyfiji** [comment]
it works for me
https://pastebin.com/VTU2eavh

**Comment by greevak** [comment]
> it works for me
> https://pastebin.com/VTU2eavh

Thanks, working!
