### ISSUE TITLE
Is Osiris detected somehow or not.

### ISSUE THREAD

**Issue by xXTOO-HARDXx** [danielkrupinski/Osiris#1555]
I usually download the release version of the .dll from cheater.fun and protect it myself as it *usually* gets updated each and every day, how ever it hasnt been updated in like three days... is it detected or is someone on holidays? much thanks

**Comment by 17sergiom2000** [comment]
the last update was 1 hour ago... bruh. And just because daniel updates a few things doesn't mean it becomes undetected, since the signature of the cheat is still basically the same

**Comment by xXTOO-HARDXx** [comment]
> the last update was 1 hour ago... bruh. And just because daniel updates a few things doesn't mean it becomes undetected, since the signature of the cheat is still basically the same

what? yes, i know this. i can add junk code, vmprotect, run it through obsidium, etc.

I mean is some part of Osiris detected, NOT the signature, I am talking internally; vmt, etc.

it was just weird it not being updated lol, so... I am guessing not? or...

**Comment by icantfindausernamelol** [comment]
> > the last update was 1 hour ago... bruh. And just because daniel updates a few things doesn't mean it becomes undetected, since the signature of the cheat is still basically the same
> 
> what? yes, i know this. i can add junk code, vmprotect, run it through obsidium, etc.
> 
> I mean is some part of Osiris detected, NOT the signature, I am talking internally; vmt, etc.
> 
> it was just weird it not being updated lol, so... I am guessing not? or...

What is obsidium? lol

**Comment by tirziz** [comment]
Dont use aimbot or aimtiaim then.

**Comment by xXTOO-HARDXx** [comment]
> > > the last update was 1 hour ago... bruh. And just because daniel updates a few things doesn't mean it becomes undetected, since the signature of the cheat is still basically the same
> > 
> > 
> > what? yes, i know this. i can add junk code, vmprotect, run it through obsidium, etc.
> > I mean is some part of Osiris detected, NOT the signature, I am talking internally; vmt, etc.
> > it was just weird it not being updated lol, so... I am guessing not? or...
> 
> What is obsidium? lol

look it up :)

**Comment by xXTOO-HARDXx** [comment]
> Dont use aimbot or aimtiaim then.

ig

**Comment by 17sergiom2000** [comment]
U can't be 100% sure everything is undetected bcs valve can just stream a new module to vac and detected some internal part of osiris. Right now, I'm pretty sure everything internally is ud but that may change in the future.

**Comment by xXTOO-HARDXx** [comment]
> U can't be 100% sure everything is undetected bcs valve can just stream a new module to vac and detected some internal part of osiris. Right now, I'm pretty sure everything internally is ud but that may change in the future.

alright, that's what I was looking for, thanks alot <3. closed
