### ISSUE TITLE
Recoil Control

### ISSUE THREAD

**Issue by Slacky145** [danielkrupinski/Osiris#1560]
Was RCS removed? Because I am unable to find the RCS Option in the aimbot tab or any other tabs

**Comment by Shuvi-Moro** [comment]
Plus, i think this is not a good idea!!!

**Comment by Shuvi-Moro** [comment]
I use the old version of osiris due to the fact that in the new one the recoil control was removed I have a very powerful and legit configuration, but I can not use it on the new version due to the lack of control of the return

**Comment by HowToMakeFaceitAB** [comment]
> I use the old version of osiris due to the fact that in the new one the recoil control was removed I have a very powerful and legit configuration, but I can not use it on the new version due to the lack of control of the return

instead of recoil control you have recoil compensation, recoil control is basically always on

**Comment by Slacky145** [comment]
> I use the old version of osiris due to the fact that in the new one the recoil control was removed I have a very powerful and legit configuration, but I can not use it on the new version due to the lack of control of the return

How can I find the old version and I thought that you had to update with the csgo updates? and also auto strafe does not work how can i fix that.

**Comment by Shuvi-Moro** [comment]
[Osiris.zip](https://github.com/danielkrupinski/Osiris/files/4603329/Osiris.zip)
I don’t know what version it is, but it suits me best because there I can set up my recoil control for each weapon

**Comment by Asviix** [comment]
You can add it back with this pull, I got it working on the latest version.

[https://github.com/danielkrupinski/Osiris/pull/1277](url)
