### ISSUE TITLE
Not able to Inject the DLL

### ISSUE THREAD

**Issue by VuBrian22** [danielkrupinski/Osiris#1566]
About 2 days ago was when the DLL just stopped injecting properly after the Osiris Source update. I made sure that everything was updated and re-compiled the source multiple times even going as far as to verify the game files and reinstalling it. But to no avail, the dll still wouldn't inject and the cheat menu doesn't show up. I'm currently using SazZ's injector which doesn't hold any logs or messages when you inject something. However I've tried Corsair's Injector and a message has popped up showing 0 out of 1 dlls injected successfully. I have also tried other dlls such as Daniel's GOESP Cheat however that didn't inject as well.

**Comment by xpossed-you** [comment]
if you injecting something else and still not working, i think the problem here is not Osiris, maybe use different injector like Process Hacker 2, i use that and got no problem injecting

**Comment by VuBrian22** [comment]
> if you injecting something else and still not working, i think the problem here is not Osiris, maybe use different injector like Process Hacker 2, i use that and got no problem injecting

Yeah i would understand that it's not a problem with Osiris itself as I have tried injecting other cheats as well. I am very hesitant in using Process Hacker. I'm not quite sure if it's undetected. Could you please reassure me if I am wrong?

**Comment by hurdofdaniels** [comment]
> I am very hesitant in using Process Hacker. I'm not quite sure if it's undetected. Could you please reassure me if I am wrong?
I don't recommend using other peoples injectors, make your own, or modify a pre-existing one like add random lines of code here's one that I made that you might want to use. [https://github.com/hurdofdaniels/Dll-Injector](https://github.com/hurdofdaniels/Dll-Injector)

**Comment by VuBrian22** [comment]
Also I don't know if Valorant's Anti-Cheat has anything to do with this because every time that I log on my computer, a notification pops up saying that Vanguard has blocked something. And it shows the message again every time I insert and mount an SD Card in which holds the cheat, injector, and Daniel's VAC-Bypass. I may be wrong but this is just all speculation. I don't have anything to prove it. I was just wondering.

**Comment by hurdofdaniels** [comment]
> Also I don't know if Valorant's Anti-Cheat has anything to do with this because every time that I log on my computer, a notification pops up saying that Vanguard (Anti-Cheat) has blocked something. And it shows the message again every time I insert and mount an SD Card in which holds the cheat, injector, and Daniel's VAC-Bypass. I may be wrong but this is just all speculation. I don't have anything to prove it. I was just wondering.   

The reason for this is your anti virus, It thinks the injector and dll are malicious, to avoid it whitelist the files in your anti virus.

**Comment by VuBrian22** [comment]
> > Also I don't know if Valorant's Anti-Cheat has anything to do with this because every time that I log on my computer, a notification pops up saying that Vanguard (Anti-Cheat) has blocked something. And it shows the message again every time I insert and mount an SD Card in which holds the cheat, injector, and Daniel's VAC-Bypass. I may be wrong but this is just all speculation. I don't have anything to prove it. I was just wondering.
> 
> The reason for this is your anti virus, It thinks the injector and dll are malicious, to avoid it whitelist the files in your anti virus.

I don't have an AV installed. And Windows Defender has already been disabled through the Windows Registry and via the Local Group Policy.

**Comment by hurdofdaniels** [comment]
> I don't have an AV installed. And Windows Defender has already been disabled through the Windows Registry and via the Local Group Policy.

That is strange, I'm not sure how to help.

**Comment by VuBrian22** [comment]
> > I don't have an AV installed. And Windows Defender has already been disabled through the Windows Registry and via the Local Group Policy.
> 
> That is strange, I'm not sure how to help.

Well thanks for trying. I'm just as stumped as you are. ^^

**Comment by xpossed-you** [comment]
> 
> 
> > > I don't have an AV installed. And Windows Defender has already been disabled through the Windows Registry and via the Local Group Policy.
> > 
> > 
> > That is strange, I'm not sure how to help.
> 
> Well thanks for trying. I'm just as stumped as you are. ^^

well. Process Hacker 2 is not just an injector, it is a Task manager/Process Explorer too... so Valve will not detect PH2, because PH2 is quite a legal software too. also Valorant Anti-Cheat is gay, it install on Kernel and have access to all your data. its not a fake information, here's the video about Valorant anticheat : https://www.youtube.com/watch?v=_dOCtaBObg4

**Comment by VuBrian22** [comment]
> > > > I don't have an AV installed. And Windows Defender has already been disabled through the Windows Registry and via the Local Group Policy.
> > > 
> > > 
> > > That is strange, I'm not sure how to help.
> > 
> > 
> > Well thanks for trying. I'm just as stumped as you are. ^^
> 
> well. Process Hacker 2 is not just an injector, it is a Task manager/Process Explorer too... so Valve will not detect PH2, because PH2 is quite a legal software too. also Valorant Anti-Cheat is gay, it install on Kernel and have access to all your data. its not a fake information, here's the video about Valorant anticheat : https://www.youtube.com/watch?v=_dOCtaBObg4

Oh ok. Yeah I do understand that the anti-cheat runs that way and I have watched that video before. I am fully aware of its shady business behind closed-doors on my PC .
