### ISSUE TITLE
中国人请看这里

### ISSUE THREAD

**Issue by Cyk-Fad** [danielkrupinski/Osiris#1567]
中国人请看这里，如果你是拿来翻译倒卖的，那么恭喜，你妈死了！
这是拿来学习的版本，并不是拿来倒卖的！

**Comment by zHElEARN** [comment]
虽然倒卖不太好
不过这是MIT协议啊。。。

**Comment by zHElEARN** [comment]
而且有一说一 你看一下MIT许可证的Permissions

> - Permissions
>   - Commercial use
>   - Modification
>   - Distribution
>   - Private use
>- Limitations
>   - Liability
>   - Warranty

第一个Commercial use就说明了可以商业使用啊

**Comment by zHElEARN** [comment]
根本就谈不上**倒卖**

**这是一个开源软件**

**Comment by Cyk-Fad** [comment]
人家拿这个卖了几百万 淘宝的那几个

**Comment by Cyk-Fad** [comment]
免费东西倒卖 怎么说？

**Comment by zHElEARN** [comment]
_Commercial use_ 允许商业使用
_Private use_ 允许私人使用

**Comment by real-Shigure** [comment]
倒卖确实不好，但其MIT协议中允许了商业使用。对于倒卖行为，你可以在淘宝上对他们进行举报，这是最有效的办法。或者联系完美世界、淘宝客服，对这些倒卖店铺进行举报、封禁。

- 如果此回复解决了问题，你可以关闭此issue。

**Comment by Cyk-Fad** [comment]
的确

**Comment by zHElEARN** [comment]
确实
