### ISSUE TITLE
Crashing when trying to inject.

### ISSUE THREAD

**Issue by hakuna0** [danielkrupinski/Osiris#157]
So, let me explain. I have my own injector and i tried to inject the dll into the game. The game just crashed, and nothing happend. First yeah, i didn't builded the osiris, first i made it undetected so i won't get vac. And then trying to inject it, my game crashesh
Also i get warnings, which i can't fix or just understand 
![image](https://user-images.githubusercontent.com/50289375/57191332-ffa8af80-6f2c-11e9-9d1c-88dc882bbd27.png)
And it should look like that when i try to build it?
![image](https://user-images.githubusercontent.com/50289375/57191360-48f8ff00-6f2d-11e9-92f4-bd6256dc667d.png)
Btw, i'm using the same sdk version, and etc. I don't know where is the problem. Thanks!

**Comment by effex1337** [comment]
maybe its the old config?
delete osiris files in my documents

**Comment by danielkrupinski** [comment]
Build unmodified source and check if it crashes.

**Comment by effex1337** [comment]
by own injector u mean rando injector?

**Comment by hakuna0** [comment]
@effex1337 Already did that, still doesn't work. Also, my own injector coded.
@danielkrupinski - How the fuck is supposed to do that, i mean i can't find this setting sorry but i'm new to this shit.

**Comment by danielkrupinski** [comment]
Sorry, can't help you then.
