### ISSUE TITLE
How to change to Chinese

### ISSUE THREAD

**Issue by Mankvis** [danielkrupinski/Osiris#1571]
How to change to Chinese

Because English is not very good, can we add Chinese directly?

I will not sell it, but use it myself

**Comment by fwb5** [comment]
毛子不会给你汉化的

**Comment by bambusboy** [comment]
just translate menu

**Comment by Asviix** [comment]
translate the file gui.cpp

**Comment by Mankvis** [comment]
> just translate menu (gui.cpp)

thank you,

**Comment by Mankvis** [comment]
> translate the file gui.cpp

thank you,

**Comment by Mankvis** [comment]
> translate the file gui.cpp

![image](https://user-images.githubusercontent.com/49258868/81519472-f1794480-9373-11ea-91f6-f4c32c61d752.png)

Is it like this? If I'm wrong, can you point me to a place

**Comment by Mankvis** [comment]
> > just translate menu (gui.cpp)
> 
> thank you,

![image](https://user-images.githubusercontent.com/49258868/81519526-29808780-9374-11ea-8199-ba3b96f3a1a0.png)


Is it like this? If I'm wrong, can you point me to a place
