### ISSUE TITLE
Vac kick

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#1573]
kicks me with a cop and says like "your pc blocks the vac system"
and throws this link https://support.steampowered.com/kb_article.php?ref=2117-ILZV-2837

**Comment by Shuvi-Moro** [comment]
i use anti-vak

**Comment by 3Ld4D** [comment]
i don't see osiris having to do anything with this, try using different injector or vac bypass.

**Comment by hyperxpro** [comment]
@3Ld4D It's Orisis bug. I used the same injector to inject Onetap and Osiris, when I use Onetap and everything works perfectly even if I go full rage in DM/Casual or War games but even in normal Aimbot, Osiris sucks and I get kicked. I tried infinite settings on Osiris but still the same.

**Comment by dapaster** [comment]
> @3Ld4D It's Orisis bug. I used the same injector to inject Onetap and Osiris, when I use Onetap and everything works perfectly even if I go full rage in DM/Casual or War games but even in normal Aimbot, Osiris sucks and I get kicked. I tried infinite settings on Osiris but still the same.

Onetap have aimstep to prevent vac kick

**Comment by dapaster** [comment]
> i use anti-vak

Go to Misc Tab

Find `Max Angle Delta`

Change from 255 to below 40

You can use this to prevent vac kick. 

But this only work while Anti Aim off

**Comment by 3Ld4D** [comment]
that's what aimstep does,it sets ur max angle delta to 30.

**Comment by hyperxpro** [comment]
@3Ld4D Doesn't work

**Comment by 3Ld4D** [comment]
> @3Ld4D Doesn't work

it's simple u just set it to 30 or less
