### ISSUE TITLE
activeWeapon->isInReload()

### ISSUE THREAD

**Issue by iniw** [danielkrupinski/Osiris#1574]
i'm trying to make a Reloading flag and this is my current code:

```cpp
        if (const auto activeWeapon{ entity->getActiveWeapon() };  config.reloading.enabled && activeWeapon && activeWeapon->isInReload()) {

            if (config.reloading.rainbow)
                interfaces->surface->setTextColor(rainbowColor(memory->globalVars->realtime, config.reloading.rainbowSpeed));
            else
                interfaces->surface->setTextColor(config.reloading.color);

            renderPositionedText(config.font, L"Reloading", { bbox.x1 + 5, drawPositionY });
            }
        }
```` 

it doesn't work.
i did some testing and apparently the isInReload() function only works on the localPlayer's active weapon. for example, if i do this:
```cpp
if (const auto activeWeapon{ localPlayer->getActiveWeapon() };  config.reloading.enabled && activeWeapon && activeWeapon->isInReload()) {

            const auto [width, height] = interfaces->surface->getScreenSize();
            auto textPositionY = static_cast<int>(0.25f * height);
            auto [textWidth, textHeight] = interfaces->surface->getTextSize(Surface::font, L"reloading");

            if (config.reloading.rainbow)
                interfaces->surface->setTextColor(rainbowColor(memory->globalVars->realtime, config.reloading.rainbowSpeed));
            else
                interfaces->surface->setTextColor(config.reloading.color);

            //renderPositionedText(config.font, L"Reloading", { bbox.x1 + 5, drawPositionY });
            interfaces->surface->setTextPosition(width - textWidth - 5, textPositionY);
            interfaces->surface->printText(L"reloading");
            }
        }
```

it prints reloading on the top right of my screen. does anyone know of a way to make isInReload() work with other entities apart from localPlayer?

**Comment by ConniKiwi** [comment]
im pretty sure the is in reloading flag only returns a value for localplayer as the reloading state isnt networked for other players

**Comment by ConniKiwi** [comment]
you can use their bullet count and if it changes by a large value they must have reloaded but im not sure about while they are reloading

**Comment by ConniKiwi** [comment]
With a little bit of googling you might be abe to use this netvar "m_bReloadVisuallyComplete"
else you will have to look into checking animstates

**Comment by Kron1Q** [comment]
You can't do it like that for other players. You need to use animation sequences.

	auto animLayer = ESP_ctx.player->GetAnimOverlay(1);
	auto reloadlayer = ESP_ctx.player->GetSequenceActivity(animLayer->m_nSequence) == 967 && animLayer->m_flWeight != 0.f;

thats from my old paste, should work :)
