### ISSUE TITLE
[Suggestion] Realtime Bomb Status

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#1575]
To check if the bomb "Can Defuse" or "Cannot Defuse" you need to go to the bomb first. So instead of that maybe change the bomb status to realtime ? 

So you don't need to go to the bomb when it cannot defuse

**Comment by hyperxpro** [comment]
LMAO

**Comment by dapaster** [comment]
> 
> 
> LMAO

wdym

**Comment by orzobinbo** [comment]
5 secs with defuse kit,
10 without
i dont think you need anything else really....

**Comment by Shuvi-Moro** [comment]
Lol nice info)))

**Comment by lordeternity000** [comment]
You know there is a bomb timer feature right? Which shows exactly the thing you are suggesting for.
