### ISSUE TITLE
I cannot change the font

### ISSUE THREAD

**Issue by djkcyl** [danielkrupinski/Osiris#1576]
If the font is changed, it will not be displayed

![image](https://user-images.githubusercontent.com/59153990/81569251-9e35df00-93d1-11ea-8d4f-41abc3a9cb65.png)
![image](https://user-images.githubusercontent.com/59153990/81569351-bdcd0780-93d1-11ea-8494-88d91f8a4447.png)

**Comment by danielkrupinski** [comment]
What font ranges you use?

**Comment by djkcyl** [comment]
> What font ranges you use?

simhei.ttf or STXIHEI.TTF

**Comment by danielkrupinski** [comment]
https://github.com/ocornut/imgui/blob/master/docs/FONTS.txt#L96-L112
