### ISSUE TITLE
I can not compile the source in a dll file

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#1579]
I have a problem, maybe I'm just dumb and I don’t understand a damn thing, but still I ask for help
[Skrin shot](https://i.imgur.com/CFP7sgn.png)
[Skrin shot 2](https://i.imgur.com/Vl4CfJf.png)

**Comment by bloater-floater** [comment]
Don't use russian in the path to anything

**Comment by rosesware** [comment]
Screen shot*

You probably renamed a file, or removed it, download the latest version of Osiris again and paste the files in the source folder of the current Osiris folder that you have.

**Comment by xpossed-you** [comment]
something is missing, delete the older osiris-master and download a new one. just delete the older version, and extract a new one
