### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by effex1337** [danielkrupinski/Osiris#158]
is remove scoped overlay supposed to be like this?
![image](https://user-images.githubusercontent.com/48663440/57191367-7604dc00-6f44-11e9-8c33-cb54be408297.png)
I tried to do some stuff and my result was what i needed except for the no scope lines staying on every time.
Tried even more modding then i again got what i need to be but this time the old issue was fixed and the new issue was the console and crosshair and net_graph doesn't work.

**Comment by danielkrupinski** [comment]
Try disabling blur.

**Comment by effex1337** [comment]
No blur doesn't do anything for me though
![image](https://user-images.githubusercontent.com/48663440/57191697-17d9f800-6f48-11e9-87bf-c1bb8dd48b2d.png)
this is what i get(not zoomed in)
![image](https://user-images.githubusercontent.com/48663440/57191702-29bb9b00-6f48-11e9-87a4-095e1475891e.png)
and this when zoomed in

**Comment by effex1337** [comment]
1more thing
![image](https://user-images.githubusercontent.com/48663440/57191759-c120ee00-6f48-11e9-98f0-76793568f4eb.png)
this is how the console looks

**Comment by ultramemer** [comment]
![image](https://user-images.githubusercontent.com/31269663/57192727-36d28d00-6f3c-11e9-8597-2db07971197c.png)
enable this

**Comment by danielkrupinski** [comment]
Then that's probably post-processing. Try disabling it.

**Comment by effex1337** [comment]
Thanks for suggesting that but nah i wanted to disable the lines when not scoped. 
In other words no scope lines like all other cheats that just removes the black part.

Since i can't actually code but do stuff to some extent by looking at the examples.
I got no clue how to do that, i had a vague idea/algorithm but that didn't work.

**Comment by danielkrupinski** [comment]
Ok, you should check "m_bIsScoped" netvar like in https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hacks/Chams.h#L25

**Comment by effex1337** [comment]
Didn't work : (
I insta crashed

```    if (!config.visuals.noScopeOverlay || interfaces.panel->getName(panel) != "HudZoom")
	{
		hooks.panel.callOriginal<void, unsigned int, bool, bool>(41, panel, forceRepaint, allowForce);
	}

	const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
	if (localPlayer->isAlive())
	{
		if (localPlayer->getProperty<bool>("m_bIsScoped"))
		{
			const auto[screen_x, screen_y] = interfaces.surface->getScreenSize();
			auto[center_x, center_y] = interfaces.surface->getScreenSize();
			center_x /= 2; center_y /= 2;
		    interfaces.surface->drawLine(0, center_y, screen_x, center_y);
		    interfaces.surface->drawLine(center_x, 0, center_x, screen_y);
		}
	}```
the code i used

**Comment by danielkrupinski** [comment]
Check if is in game `interfaces.engine->isInGame()`.

**Comment by effex1337** [comment]
Thanks, it's working like a charm now.
1 more thing can i get an example of localPlayer->getInaccuracy();
to get inaccuracy of the current weapon

**Comment by danielkrupinski** [comment]
```
const auto activeWeapon = interfaces.entityList->getEntityFromHandle(localPlayer->getProperty<int>("m_hActiveWeapon"));

if (activeWeapon) {
    float inaccuracy = activeWeapon->getInaccuracy();
}
```
