### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lockxd159** [danielkrupinski/Osiris#1580]
I pasted an autoblocker into osiris
and i get this error 
![erreee](https://user-images.githubusercontent.com/65194937/81666080-d6750600-9441-11ea-8423-c2680a36e648.JPG)
I tried with localplayer.get but still didn't work.
If someone can help because im not an expert , thanks

**Comment by xpossed-you** [comment]
can you provide a full image? if you just put one line of code, it wont help you.

**Comment by xpossed-you** [comment]
> 
> 
> I pasted an autoblocker into osiris
> and i get this error
> ![erreee](https://user-images.githubusercontent.com/65194937/81666080-d6750600-9441-11ea-8423-c2680a36e648.JPG)
> I tried with localplayer.get but still didn't work.
> If someone can help because im not an expert , thanks

i think its not `getLocalPlayer());` it is `localPlayer.get());`

**Comment by lockxd159** [comment]
yeah i said i already test but that doesn't work

**Comment by notgoodusename** [comment]
auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
to 
auto localPlayer = localPlayer.get()

**Comment by lockxd159** [comment]
> auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
> to
> auto localPlayer = localPlayer.get()

that makes more errors :/

![image](https://user-images.githubusercontent.com/65194937/81722195-4fe01900-9481-11ea-991d-2a6257fd9f50.png)

**Comment by Cyk-Fad** [comment]
... Please learn C++

**Comment by 3Ld4D** [comment]
you don't need that since localPlayer is already defined.

**Comment by dapaster** [comment]
> 
> 
> > auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
> > to
> > auto localPlayer = localPlayer.get()
> 
> that makes more errors :/
> 
> ![image](https://user-images.githubusercontent.com/65194937/81722195-4fe01900-9481-11ea-991d-2a6257fd9f50.png)

you forgot this " **;** "
