### ISSUE TITLE
standalone rcs

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1582]
how to make #1277 work with current build?

**Comment by Kron1Q** [comment]
I don't understand your problem. It works perfectly with newest Osiris. Re-add slider for recoilControlY/X or replace it with "1" instead for full control.

**Comment by steel4me** [comment]
> I don't understand your problem. It works perfectly with newest Osiris. Re-add slider for recoilControlY/X or replace it with "1" instead for full control.

True ;)

**Comment by HowToMakeFaceitAB** [comment]
> I don't understand your problem. It works perfectly with newest Osiris. Re-add slider for recoilControlY/X or replace it with "1" instead for full control.

Don't wanna readd the sliders cuz they succ
