### ISSUE TITLE
Add Scroll Bar

### ISSUE THREAD

**Issue by techprimedev** [danielkrupinski/Osiris#1585]
Hello, I would like to know how to add a scroll bar, for example.

I reduced the SetNextWindowSize, and that hid some options.

**Comment by xpossed-you** [comment]
its not Osiris problem, its imgui problem

**Comment by SleekZ** [comment]
Still should be able to do it. You can edit ImGUI.

**Comment by techprimedev** [comment]
> Still should be able to do it. You can edit ImGUI.

:(
