### ISSUE TITLE
Update pls

### ISSUE THREAD

**Issue by 0lsi** [danielkrupinski/Osiris#1586]
Perhaps you are working on, but there is an update on csgo and many player got a vac ban, plz update your cheat it is very nice !

**Comment by VuBrian22** [comment]
As far as I'm concerned, it's working fine and is still undetected. Those bans are probably the delayed bans kicking in from maybe a month or so ago. It happens a lot after an update.

**Comment by 0lsi** [comment]
So for you the cheat is still undetectable ? Did you play with it since the new update ? And which injector do you use ? (personnaly i use process hacker 2) and last question do you use vmprotect ? thx

**Comment by VuBrian22** [comment]
> So for you the cheat is still undetectable ? Did you play with it since the new update ? And which injector do you use ? (personnaly i use process hacker 2) and last question do you use vmprotect ? thx

For me I played it last night right after the update. I haven't had a VAC ban ever since then. I also use Process Hacker 2. I don't VMProtect it because I already used Daniel's VAC Bypass.

**Comment by 0lsi** [comment]
Ok thx for the informations, and you cheat on prime or no ?

**Comment by VuBrian22** [comment]
> Ok thx for the informations, and you cheat on prime or no ?

I do have an account with prime and one with non-prime and I tested the cheat with both and so far nothing has happened to them.

**Comment by 0lsi** [comment]
Do you use Vac-bypass or Vac-bypass loader ?

**Comment by VuBrian22** [comment]
> Do you use Vac-bypass or Vac-bypass loader ?

I used the Loader.

**Comment by 0lsi** [comment]
Thx i will do the same ;)

**Comment by VuBrian22** [comment]
> Thx i will do the same ;)

Yeah np. Feel free to close this issue so it cleans things up a bit in the Issues Tab. It's a mess there rn.
