### ISSUE TITLE
Rank Revealer causing issues

### ISSUE THREAD

**Issue by hindia420** [danielkrupinski/Osiris#1589]
When enabled, viewing +scoreboard drops the game fps a lot.

**Comment by littlehurensohn** [comment]
csgo>panorama> delete videos. <-- Fixed.

**Comment by xpossed-you** [comment]
how rank revealer make CSGO lag? can someone explain to me?

**Comment by 3Ld4D** [comment]
> how rank revealer make CSGO lag? can someone explain to me?

no clue, i had an issue where i had 20 fps in menu and the fix was to simply delete all videos in panorama.So that's probably his issue which has nothing to do with osiris or any cheat.

**Comment by bruhmoment21** [comment]
try this since u can't hide ranks when disabling rank revealer
```
void Misc::revealRanks(UserCmd* cmd) noexcept
{
    static bool onlyOnce;
    if (config->misc.revealRanks && cmd->buttons & UserCmd::IN_SCORE && !onlyOnce)
    {
        onlyOnce = true;
        interfaces->client->dispatchUserMessage(50, 0, 0, nullptr);
    }
}
```

**Comment by bruhmoment21** [comment]
> try this since u can't hide ranks when disabling rank revealer
> 
> ```
> void Misc::revealRanks(UserCmd* cmd) noexcept
> {
>     static bool onlyOnce;
>     if (config->misc.revealRanks && cmd->buttons & UserCmd::IN_SCORE && !onlyOnce)
>     {
>         onlyOnce = true;
>         interfaces->client->dispatchUserMessage(50, 0, 0, nullptr);
>     }
> }
> ```

try creating a global bool only_once and set it to false again when autoaccept code gets run or creating ur own button that sets it to false
