### ISSUE TITLE
[Petition] Inventory Changer

### ISSUE THREAD

**Issue by bpekalp** [danielkrupinski/Osiris#1590]
What if you replaced skin changer with an inventory changer? That would be better (and pretty sick) in my opinion. If possible can you do it please?

**Comment by techprimedev** [comment]
I don't see any point in this, since skin changer and inventory changer work the same way.
But if anyone can, I wouldn't be angry in any way :)

**Comment by Cryforus** [comment]
techprimedev for me the main point of adding a inventory changer to the cheat is that it add's the functionality of having native ct or t sided weapons and allowing the weapons to show up in the buy menu. But you are right its not necessary.

**Comment by bpekalp** [comment]
Inventory Changer is way better than casual skin changer unless you want to use custom skins. For example Bayonet | Whiteout. You can fake open cases, add music kits, badges, etc. with Inventory changer

**Comment by techprimedev** [comment]
> techprimedev para mim, o ponto principal de adicionar um trocador de inventário ao truque é que ele adiciona a funcionalidade de ter armas nativas de ct ou t e permitir que as armas apareçam no menu de compra. Mas você está certo, não é necessário.

if you see a skin in the inventory and purchase menu for you it is important, who am I to prevent this.
If anyone can do that, I would be grateful to see the code :)

**Comment by Zhxcky** [comment]
Item Changer will make Skin Changer looks more legit so +1

**Comment by techprimedev** [comment]
> Item Changer will make Skin Changer looks more legit so +1

legit? lmao
