### ISSUE TITLE
Add Recoil Control System (RCS)

### ISSUE THREAD

**Issue by techzin** [danielkrupinski/Osiris#1591]
I was testing Osiris using the aimbot, and I realized that the aim ends up going way beyond normal.
a good method of correcting this is by adding a Recoil Control System or RCS Stand Alone.

**Comment by bpekalp** [comment]
Osiris has RCS. Its always on.

**Comment by techprimedev** [comment]
> Osiris has RCS. Its always on.

but, there is no customization button. + _ +

**Comment by bpekalp** [comment]
Yeah, you're right. That would be good, but still, it exists.

**Comment by HowToMakeFaceitAB** [comment]
my recommendation is to only use backtrack with visuals and stuff like that, the aimbot in this cheat needs some work
