### ISSUE TITLE
perfect word color

### ISSUE THREAD

**Issue by jestemgosciem** [danielkrupinski/Osiris#1595]
add this to hooks to color the orange elements

GetColorModulation:
        find_signature("materialsystem.dll", "55 8B EC 83 EC ? 56 8B F1 8A 46")
IsUsingStaticPropDebugModes:
        find_signature("engine.dll", "8B 0D ? ? ? ? 81 F9 ? ? ? ? 75 ? A1 ? ? ? ? 35 ? ? ? ? EB ? 8B 01 FF 50 ? 83 F8 ? 0F 85 ? ? ? ? 8B 0D")

**Comment by Cyk-Fad** [comment]
???
