### ISSUE TITLE
How to simply inject os, just like VAC-Bypass-Loader

### ISSUE THREAD

**Issue by djkcyl** [danielkrupinski/Osiris#1597]
I want to get a simple Loader, turn on automatic injection like [VAC-Bypass-Loader](https://github.com/danielkrupinski/VAC-Bypass-Loader)

**Comment by littlehurensohn** [comment]
I can sell you the Loader with that for 10$

**Comment by rosesware** [comment]
> I can sell you the Loader with that for 10$

Do you think? Why he should pay 10$ to have a loader who inject a open source cheat?

**Comment by egssy0** [comment]
> I can sell you the Loader with that for 10$

Dumb hunt :D

**Comment by Zhxcky** [comment]
> I can sell you the Loader with that for 10$

lol

**Comment by littlehurensohn** [comment]
just if aint want to pay me, do it urself. lmao

**Comment by djkcyl** [comment]
> just if aint want to pay me, do it urself. lmao
No, I did it myself
