### ISSUE TITLE
Chams broken

### ISSUE THREAD

**Issue by lizei** [danielkrupinski/Osiris#1598]
How would I update the chams myself? offsets are broken for it since of last update I just keep crashing when I turn on chams. Any help would be appreciated :)

**Comment by xpossed-you** [comment]
I dont have any problem with chams, can you show some screenshot?

**Comment by lizei** [comment]
I have problems because I'm using an older build, I wanted to update it myself, I prefer using older versions since I think it was better back a while. I have updated everything such as ESP, Glow, Aimbot throughout the times when they got outdated. But I really can't seem to find where I should begin when updating the chams...

**Comment by egssy0** [comment]
No one can help you for older builds

**Comment by lizei** [comment]
I don't need help coding the chams, what I need help with is to update the chams to work for the latest cs:go patch. Enabling chams as of now just crashes my game.

**Comment by lizei** [comment]
Solved it by rewriting the chams.
