### ISSUE TITLE
[feature]

### ISSUE THREAD

**Issue by rafalohaki** [danielkrupinski/Osiris#1599]
Recommend to close old issues,
ppl are helping and when issue is fixed it still is seen on my home page as unresolved.

**Comment by rafalohaki** [comment]
https://pasty.eu/i/NRJl.png

**Comment by rafalohaki** [comment]
![image](https://user-images.githubusercontent.com/20607107/82093720-ef104500-96fb-11ea-826d-c08ead4542e1.png)

**Comment by bpekalp** [comment]
How is that a feature?

**Comment by rafalohaki** [comment]
> How is that a feature?

cuz its not a bug?
