### ISSUE TITLE
How to get UserCMD?

### ISSUE THREAD

**Issue by CovERUshKA** [danielkrupinski/Osiris#160]
I don't know how to get UserCMD

**Comment by danielkrupinski** [comment]
Grab it in hookedCreateMove() function https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hooks.cpp#L78

**Comment by CovERUshKA** [comment]
Very hard. Can you tell where UserCMD address https://github.com/frk1/hazedumper/blob/master/csgo.hpp here? If there is, say the name of the address.

**Comment by CovERUshKA** [comment]
Скажи пожалуйста. Какую программу ты используешь для поиска оффсетов, адресов, функций?

**Comment by CovERUshKA** [comment]
Tell me please. What program do you use to search for offsets, addresses, functions?
