### ISSUE TITLE
[Crash] Disabling Visible Only crashes game

### ISSUE THREAD

**Issue by ChickenNerd** [danielkrupinski/Osiris#1602]
Hi!
When i disable "Visible Only" my game crashes.
My Aimbot code is the same as in the repo.
Without disabling it, it works normally.

**Comment by danielkrupinski** [comment]
Can anyone else confirm this issue?

**Comment by psycho147** [comment]
Works fine for me

**Comment by ChickenNerd** [comment]
Fixed by re-downloading source., don't really know why it broke
