### ISSUE TITLE
Osiris after Source 2 arrives.

### ISSUE THREAD

**Issue by techzin** [danielkrupinski/Osiris#1603]
What will happen to Osiris after Source 2 arrives?
Does anyone have any idea what will stop working?
how long can it take to fix?

**Comment by techprimedev** [comment]
I imagine that most functions will stop as client_panorama.dll will be modified or renamed.

**Comment by pkienhai** [comment]
nah i think daniel will fix it anyway

**Comment by xXTOO-HARDXx** [comment]
well, it really depends how things change. Source 2 is a near to a complete overhaul of the Source Engine. To make matters worse, there's no public SDK for Source 2, so... big sad.
And because Source 2 is so much more up to date with things, many hacks that were possible due to the Source Engine's vulnerabilities, will not be possible any more.

**Comment by 0xMDIV** [comment]
> well, it really depends how things change. Source 2 is near to a complete overhaul of the Source Engine. To make matters worse, there's no public SDK for Source 2, so... big sad.
> And because Source 2 is so much more up to date with things, many hacks that were possible due to the Source Engine's vulnerabilities, will not be possible any more.

When im not wrong informed, then valve decided to release the source 2 SDK on the same time as csgo will come to source 2

**Comment by xXTOO-HARDXx** [comment]
> > well, it really depends how things change. Source 2 is near to a complete overhaul of the Source Engine. To make matters worse, there's no public SDK for Source 2, so... big sad.
> > And because Source 2 is so much more up to date with things, many hacks that were possible due to the Source Engine's vulnerabilities, will not be possible any more.
> 
> When im not wrong informed, then valve decided to release the source 2 SDK on the same time as csgo will come to source 2

Haha, if they do then I give up.
Part of me just wants CSGO to be cheater free, let it flourish again and then people will actually come back to play it. Smh Valve. Pay EasyAntiCheat ffs
