### ISSUE TITLE
[Feature] Sv_pure bypassing (release code) **ENJOY**

### ISSUE THREAD

**Issue by jimmienea** [danielkrupinski/Osiris#1604]
**Hooks.cpp** (include "INetMessage.h")

bool __fastcall SendNetMsg(INetChannel* pNetChan, void* edx, INetMessage& msg, bool bForceReliable, bool bVoice) noexcept
{
	if (msg.GetType() == 14) // Return and don't send messsage if its FileCRCCheck
		return false;

	if (msg.GetGroup() == 9) // Fix lag when transmitting voice and fakelagging
		bVoice = true;

	return hooks->engine.callOriginal<INetChannel*, 42, void*, INetMessage&, bool, bool>(pNetChan, msg, bForceReliable, bVoice);
}

Put this on "void Hooks::install() noexcept"  (to call and run it automatically when you join the game )

`engine.hookAt(42, SendNetMsg);`

**Engine.h**

class INetChannel;

class Engine {
public:
    VIRTUAL_METHOD(INetChannel*, getNetworkChannel, 42, (), (this))

};

**INetMessage.h**

#ifndef INETMESSAGE_H
#define INETMESSAGE_H

class INetMsgHandler;
class INetMessage;
class INetChannel;

// typedef bool (INetMsgHandler::*PROCESSFUNCPTR)(INetMessage*);
// #define CASTPROCPTR( fn ) static_cast <bool (INetMsgHandler::*)(INetMessage*)> (fn)

class INetMessage
{
public:
	virtual	~INetMessage() {};

	// Use these to setup who can hear whose voice.
	// Pass in client indices (which are their ent indices - 1).
	
	virtual void	SetNetChannel(INetChannel * netchan) = 0; // netchannel this message is from/for
	virtual void	SetReliable( bool state ) = 0;	// set to true if it's a reliable message
	
	virtual bool	Process( void ) = 0; // calls the recently set handler to process this message
	
	virtual	bool	ReadFromBuffer( bf_read &buffer ) = 0; // returns true if parsing was OK
	virtual	bool	WriteToBuffer( bf_write &buffer ) = 0;	// returns true if writing was OK
		
	virtual bool	IsReliable( void ) const = 0;  // true, if message needs reliable handling
	
	virtual int				GetType( void ) const = 0; // returns module specific header tag eg svc_serverinfo
	virtual int				GetGroup( void ) const = 0;	// returns net message group of this message
	virtual const char		*GetName( void ) const = 0;	// returns network message name, eg "svc_serverinfo"
	virtual INetChannel		*GetNetChannel( void ) const = 0;
	virtual const char		*ToString( void ) const = 0; // returns a human readable string about message content
	virtual size_t			GetSize() const = 0;
};

#endif

If i forgot something then please let me know or someone gonna help you.

**Comment by VuBrian22** [comment]
Hey! Thanks for your contribution to the repository, however would you mind putting this as a pull request? It just makes things a lot simpler and cleaner to go ahead and implement if it works well.

**Comment by notgoodusename** [comment]
im pretty sure you didnt test this, you have to hook netchannel not engine

**Comment by littlehurensohn** [comment]
Honestly, when u not adding other features mean "change CT model" etc.. like.. u want anime char, u dont need that. 
Cause chams are "created" not "findMaterial".

**Comment by littlehurensohn** [comment]
> im pretty sure you didnt test this, you have to hook netchannel not engine

it can works normally, cause still its be hooked.

**Comment by littlehurensohn** [comment]
> > im pretty sure you didnt test this, you have to hook netchannel not engine
> 
> it can works normally, cause still its be hooked.

I have this code few months, cause it was on uc, and it works fine.

**Comment by Cyk-Fad** [comment]
virtual	bool	ReadFromBuffer(bf_read& buffer) = 0; // returns true if parsing was OK
	virtual	bool	WriteToBuffer(bf_write& buffer) = 0;	// returns true if writing was OK
bf_read & bf_write 
you forget this

**Comment by Cyk-Fad** [comment]
bf_read & bf_write
you aren't finish them

**Comment by notgoodusename** [comment]
> bf_read & bf_write
> you aren't finish them

you dont need that

**Comment by Cyk-Fad** [comment]
ok

**Comment by CantRememberMyself** [comment]
i don't understand the engine.h part, i can't put that in there because it collides with "    VIRTUAL_METHOD(NetworkChannel*, getNetworkChannel, 78, (), (this))"

**Comment by CantRememberMyself** [comment]
could you make a pull request, i pasted it in as is and i'm crashing :/

**Comment by xAkiraMiura** [comment]
> 
> 
> could you make a pull request, i pasted it in as is and i'm crashing :/

...and this is why we use git. doing things by hand is error prone.
use git as it was intended and submit a pull request, even if it's going to get declined it can still be pulled from.
^ also saves a lot of work from anyone wanting to try out your code.

**Comment by toxicfunky** [comment]
Who can i use this code do i need a programm or what can someone explain please?
