### ISSUE TITLE
[REQUEST] sound esp

### ISSUE THREAD

**Issue by sorrowvibez** [danielkrupinski/Osiris#1605]
if theres sound esp in osiris that would help alot

**Comment by egssy0** [comment]
What is sound ESP?

**Comment by BachaBajceps** [comment]
up, Sound ESP is showing players only when they make sound, like step jump shoot. Simpler implementations of Sound ESP just check for entity speed.

**Comment by Zhxcky** [comment]
#1305 #1231 #1183 #766 #337

**Comment by littlehurensohn** [comment]
Do BulletBeams Ring.
