### ISSUE TITLE
fast stop

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1607]

**Comment by xpossed-you** [comment]
which Fast stop? the "when you stop pressing movement keys "W,A,S,D" it will be fully stopped" or the "you will stopped when you shooting someone" ?

**Comment by HowToMakeFaceitAB** [comment]
W a s d fast stop

**Comment by HowToMakeFaceitAB** [comment]
> which Fast stop? the "when you stop pressing movement keys "W,A,S,D" it will be fully stopped" or the "you will stopped when you shooting someone" ?

First one

**Comment by SunzBody** [comment]
#2039
