### ISSUE TITLE
message box

### ISSUE THREAD

**Issue by toprak1224** [danielkrupinski/Osiris#1609]
I would like to place again the welcome popup message ı need picture plss someone help me

**Comment by egssy0** [comment]
Dani renamed it to `createCommandMsgBox`


`interfaces->gameUI->createCommandMsgBox("Don't paste", "This is an test.");`

**Comment by egssy0** [comment]
Add it to
`void Hooks::install() noexcept`

**Comment by egssy0** [comment]
Please close this issue

**Comment by toprak1224** [comment]
plss send me picture ım noob

**Comment by egssy0** [comment]
Mate it's so basic.
You don't want picture 
I can say you steps

Open Hooks.cpp
Click CTRL+F
Type this to box `void Hooks::install() noexcept`
Click Enter
And write bellow this `void Hooks::install() noexcept
interfaces->gameUI->createCommandMsgBox("Don't paste", "This is an test.");`


> I'm beginner too

**Comment by zSniiKeR** [comment]
It's work here, thank you so much bro ! :D @egssy0

**Comment by TauCSGO** [comment]
#1506
