### ISSUE TITLE
Injector & HWID

### ISSUE THREAD

**Issue by cojo1989** [danielkrupinski/Osiris#161]
Hello Daniel, i really love your hack <3. I have a question do you have a simple injector UD? And can you tell me how to put a HWID Lock on my source? I tryed some tutorials but unsuccesfully.

Thank you very much buddy !

**Comment by danielkrupinski** [comment]
My injectors: https://github.com/danielkrupinski/Inflame and newer one but not yet documented https://github.com/danielkrupinski/Jector. I am sorry, can't help you with HWID lock.

**Comment by ptzer** [comment]
If your thinking of making a "private cheat" out of this please don't.

**Comment by cojo1989** [comment]
LoL, no thank you. Im good just for me and 2-3 friends. I just want to make a protection for my friends. Im not interested to make money from this buddy. I am playing csgo just for fun... i got 29 years old, im waiting a baby i don`t even have time to play so much. Thank you anyway buddy.
