### ISSUE TITLE
help my with gui

### ISSUE THREAD

**Issue by jestemgosciem** [danielkrupinski/Osiris#1615]
I would like it to be an input animation e.g. from alpha 0.1 to 1
https://youtu.be/POk80-4zM2g?t=43

**Comment by DahKiwiDude** [comment]
do research into how imgui set colors
youll figure it out quickly

**Comment by techprimedev** [comment]
Wouldn't it be easier to break into Steam's database and give yourself the Desired Skin?
Close this issue soon.

**Comment by bruhmoment21** [comment]
```
const int fade_factor = static_cast<int>(1.0f / 0.15f * functions.get_frametime() * 255);
alpha = std::clamp(alpha + (menu_opened ? fade_factor : -fade_factor), 0, 255);
```
credits: zxvnme
