### ISSUE TITLE
i keep sliding whenever i inject plz help

### ISSUE THREAD

**Issue by jayedm420** [danielkrupinski/Osiris#1619]
it seems like the walking animation does not load please help

**Comment by m0nsterJ** [comment]
Is Moonwalk turned off in the Misc section?

**Comment by jayedm420** [comment]
yes sir moonwalk is unchecked ive tried ticking fix movement,fix bone matrix and fix animation LOD  but that does not seem to help

**Comment by jayedm420** [comment]
ive uploaded a video too 
https://youtu.be/6pnv40lUntM
 other players can also see me sliding and call me out plz help

**Comment by zajkos** [comment]
Turn off Moonwalk, go enable fix movment or go restart game?

**Comment by notgoodusename** [comment]
thats a visual bug

**Comment by jayedm420** [comment]
moonwalk is disabled fix movement is enabled still im sliding ?
so no solution?

**Comment by HowToMakeFaceitAB** [comment]
> moonwalk is disabled fix movement is enabled still im sliding ?
> so no solution?

you're not sliding bruh, visual glitch

**Comment by jayedm420** [comment]
thanks!
