### ISSUE TITLE
Autowall & Hit Chance/Damage

### ISSUE THREAD

**Issue by IKodHak** [danielkrupinski/Osiris#162]
Would that be something you'd add in the future

Also anything about the skin changer?

**Comment by edgarbarney** [comment]
I'm working on a nSkinz integration.Idk what will daniel say but i can send a pull request if he allow me so.

**Comment by IKodHak** [comment]
@edgarbarney looks like he's already working on it!

**Comment by cojo1989** [comment]
Up for skin on weapons but preset ones from CSGO ❤️❤️❤️

**Comment by diekunstderfuge** [comment]
Will it be added?
