### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by farisuqail** [danielkrupinski/Osiris#1621]
i didnt modify anything and csgo occasionally  crashes , freezes and i have to force close it , i also use vac bypass loader , any help ?

**Comment by zajkos** [comment]
u off antivirus?
open injector with administrator privileges

**Comment by zSniiKeR** [comment]
Crash here too, i'm using Saz Injector. before source updates the cheat work's for me. Now, i'm using an old version of Osiris that i have downloaded here.

**Comment by farisuqail** [comment]
> u off antivirus?
> open injector with administrator privileges

yep ive done both

**Comment by dapaster** [comment]
![image](https://user-images.githubusercontent.com/60472098/82560234-9df0cd00-9ba3-11ea-84be-e1fba38b91be.png)
 i got this too . i use latest unmodify osiris . 
i try to verify game and also reinstall csgo but the error still exist .

but mine only appear when i exit the game
