### ISSUE TITLE
[Suggestion] standalone rcs

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1624]
the recoil compensation is pretty decent with low smooth but looks unlegit although maybe FINALLY making a standalone RCS would fix it, I know there is a pull request for it but it would be much better if it was official because the RCS in the pull request needs the recoil control x and y sliders to work whereas @danielkrupinski adding it would require it

**Comment by HowToMakeFaceitAB** [comment]
(enableRCS)
{
	static Vec2f unresolvedDeltaAimPunch{ 0.f,0.f };				// accumulated delta aimPunch over time
	static Vec2f lastAimPunch{0.f,0.f};
	
	Vec2f  newAimPunch = game.m_localPlayer.m_aimPunch;				//this is where you RPM player aimPunch
	Vec2f  deltaAimPunch = newAimPunch - lastAimPunch;
	lastAimPunch = newAimPunch;
	
	if (getAsyncKeyState(VK_LBUTTON))
	{
		unresolvedDeltaAimPunch += deltaAimPunch;
		
		Vec2f deltaAngles = unresolvedDeltaAimPunch*(rcsAimSpeed*deltaTime);
			
		unresolvedDeltaAimPunch -= deltaAngles;
		
		Vec2f  deltaPixels = deltaAngles * (-2.f * cursorPixelPerDegree);	//cursorPixelPerDegree is calculated from sensitivity
 
		moveCursor(-deltaPixels.x, deltaPixels.y);							//you should use SendInput for this, mouse_event(MOUSEEVENTF_MOVE,-deltaPixels.x,deltaPixels.y,0,0);// not sure if this will work, never tried mouse_event before
	}
	else
		unresolvedDeltaAimPunch.set(0.f, 0.f);								// if not pressing left mouse button, then reset accumulated delta aimPunch
}

**Comment by HowToMakeFaceitAB** [comment]
class Movement
{
public:
	Vec2f m_position;
	Vec2f  m_velocity;
	Vec2f  m_acceleration;
	Vec2f  m_jerk;
	Movement() = default;
	~Movement() = default;
	Movement(const Vec2f & pos, const Vec2f & vel, const Vec2f & acc, const Vec2f & jerk) :m_position{ pos }, m_velocity{ vel }, m_acceleration{ acc }, m_jerk{ jerk } {}
	void reset()
	{
		m_position = { 0.f,0.f };
		m_velocity = { 0.f,0.f };
		m_acceleration = { 0.f,0.f };
		m_jerk = { 0.f,0.f };
	}
	void update(double dt)
	{
		m_acceleration += m_jerk * dt;
		m_velocity += m_acceleration * dt;
		m_position += m_velocity * dt;
	}
}

**Comment by notgoodusename** [comment]
this can be done easier

**Comment by HowToMakeFaceitAB** [comment]
> this can be done easier

and how so? if you can make a pull request that doesn't have any problems with the cheat it would be greatly apreciated

**Comment by notgoodusename** [comment]
ok

**Comment by notgoodusename** [comment]
old code i have that works as intended
`        static Vector StaticAimPunchAngle;
        if (cmd->buttons & UserCmd::IN_ATTACK)
        {
            const auto currentaimPunch = activeWeapon->requiresRecoilControl() ? localPlayer->getAimPunch() : Vector{ };

            cmd->viewangles += StaticAimPunchAngle - currentaimPunch;
            StaticAimPunchAngle = currentaimPunch;
            if (!config->aimbot[weaponIndex].silent)
            {
                interfaces->engine->setViewAngles(cmd->viewangles);
            }
        }
        else {
            StaticAimPunchAngle.y = 0.f;
            StaticAimPunchAngle.x = 0.f;
        }`

**Comment by cailloubr** [comment]
I was trying to pull this out, but my code is not worthy :/
