### ISSUE TITLE
how to see real/fake angle

### ISSUE THREAD

**Issue by jestemgosciem** [danielkrupinski/Osiris#1626]
this metod in pr dosent work for me, everyone have this code?

**Comment by dapaster** [comment]
#1546 `made thirdperson show cmd->viewangles`

**Comment by jestemgosciem** [comment]
i dont know to paste this code, can you help me?

**Comment by dapaster** [comment]
> 
> 
> i dont know to paste this code, can you help me?

how about this one ? 
#739

**Comment by jestemgosciem** [comment]
@dapaster only change offset and work?

**Comment by jestemgosciem** [comment]
i have problem with "reinterpret_cast" reason: "invalid type conversion"

**Comment by dapaster** [comment]
*reinterpret_cast<Vector*>(reinterpret_cast<uintptr_t>(localPlayer.get()) + 0x31D8) = angle;

change localPlayer to localPlayer.get()

**Comment by jestemgosciem** [comment]
i have got this"thirdperson unable to match function definition to an existong declaration" and "syntax error: idefiter "Vector"", I don't know what's wrong

**Comment by jestemgosciem** [comment]
okey, this code work for me, thanks you

**Comment by jestemgosciem** [comment]
when i go to team crash csgo

**Comment by jestemgosciem** [comment]
![20200522091643_1](https://user-images.githubusercontent.com/64129769/82642232-e5ac3e80-9c0d-11ea-8648-6450d8bc9fea.jpg) , okey work but that's not it, it doesn't show pitch and yaw doesn't change

**Comment by notgoodusename** [comment]
set it to your viewangles

**Comment by designer1337** [comment]
Sync your animations with server.

**Comment by jestemgosciem** [comment]
how to sync animations?

**Comment by DoomFishWasTaken** [comment]
#1626 made a standalone pull now get to doing some c+p

**Comment by jestemgosciem** [comment]
work, ty guys
