### ISSUE TITLE
[REQUEST] Auto edge bug

### ISSUE THREAD

**Issue by M70000** [danielkrupinski/Osiris#1630]
Well, i didn't found this feature in any public forum, it would be amazing if someone can add it to Osiris, if u don't know what is edge bug, u should see this video: https://www.youtube.com/watch?v=7jV-HBEi5wM

**Comment by iniw** [comment]
```cpp
if (config->misc.edgeBug && GetAsyncKeyState(config->misc.edgeBugKey) && localPlayer->flags() & 1)
        cmd->buttons |= UserCmd::IN_DUCK;
```
thats probably the easiest (and worst) way to do it,

**Comment by Finndramere** [comment]
> ```c++
> if (config->misc.edgeBug && GetAsyncKeyState(config->misc.edgeBugKey) && localPlayer->flags() & 1)
>         cmd->buttons |= UserCmd::IN_DUCK;
> ```
> 
> thats probably the easiest (and worst) way to do it,

wtf is that? isn't that crouch in air?

**Comment by littlehurensohn** [comment]
WHEN UR ON GROUND -> localPlayer->flags() & 1
WHEN UR IN AIR -> !localPlayer->flags() & 1

**Comment by littlehurensohn** [comment]
@ApolloXXX I can sell you my code, from my private hakenzz.

JumpBug & EdgeBug.

**Comment by gabesmithdev** [comment]
leak.codes posted proper edgebug source this week. I cant unlock it tho. U will have to go there to get it.
