### ISSUE TITLE
[suggestion] Change crosshair color on sight.

### ISSUE THREAD

**Issue by vzmuric** [danielkrupinski/Osiris#1635]
What i mean by this is your crosshair changes color when enemy lands on it, like in Max Payne 3.
Example: https://youtu.be/XxrQe6La5oY?t=240

**Comment by 3Ld4D** [comment]
u can use cl_crosshairstyle 1 and change it's size using cl_fixedcrosshairgap

**Comment by CantRememberMyself** [comment]
im pretty sure there are crosshairs that do that anyway, look on crashz config generator v3

**Comment by micwoj92** [comment]
> im pretty sure there are crosshairs that do that anyway, look on crashz config generator v3

How can crosshair get input to change color then? Is there like something that tells gameclient 'hey, enemy is under your crosshair'?

**Comment by CantRememberMyself** [comment]
> > im pretty sure there are crosshairs that do that anyway, look on crashz config generator v3
> 
> How can crosshair get input to change color then? Is there like something that tells gameclient 'hey, enemy is under your crosshair'?

yes? lol

**Comment by cailloubr** [comment]
> > im pretty sure there are crosshairs that do that anyway, look on crashz config generator v3
> 
> How can crosshair get input to change color then? Is there like something that tells gameclient 'hey, enemy is under your crosshair'?

Ehhh?? 
![Screenshot_3](https://user-images.githubusercontent.com/60858720/82850357-731fb500-9ed2-11ea-9af2-4f45eccdf9f4.png)
