### ISSUE TITLE
[REQUEST] Fake item unbox(chat) and trade massage?

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#1636]
Does anyone have Fake item unbox and trade massage for that is working as dll?

i tried @DoomFishWasTaken Pull req but ain't working..

I can give a one skin for this!

**Comment by ADGAYMILK** [comment]
I've think that problem is to change colour of guns...

**Comment by cailloubr** [comment]
I've tried #1483 , works perfectly but you need attack your teammates (like Fake Ban).

**Comment by RichhieCheaterfun** [comment]
Hi @cailloubr, can you drop me .dll file of that? If you still have that mate

**Comment by cailloubr** [comment]
My project has external dependencies (user activity on my forum), so it won't load :(

**Comment by DoomFishWasTaken** [comment]
> My project has external dependencies (user activity on my forum), so it won't load :(
> 
> He is avaliable on cheaters.pro (in portuguese)

@cailloubr who is?

**Comment by DoomFishWasTaken** [comment]
@ghost fixed the pull :)

**Comment by DoomFishWasTaken** [comment]
@danielkrupinski close this, the guy deleted his github acc
