### ISSUE TITLE
problem with shooting(anti aim)

### ISSUE THREAD

**Issue by jestemgosciem** [danielkrupinski/Osiris#1638]
https://youtu.be/7phBs6fOu8Y

**Comment by Kron1Q** [comment]
Dont AA when IN_ATTACK

**Comment by jestemgosciem** [comment]
if (!(cmd->buttons & (UserCmd::IN_ATTACK | UserCmd::IN_ATTACK2))) {
        AntiAim::run(cmd, previousViewAngles, currentViewAngles, sendPacket);
    }

**Comment by 3Ld4D** [comment]
increase MaxAngleDelta

**Comment by jestemgosciem** [comment]
work, thanks

**Comment by xAkiraMiura** [comment]
> 
> 
> if (!(cmd->buttons & (UserCmd::IN_ATTACK | UserCmd::IN_ATTACK2))) {
> AntiAim::run(cmd, previousViewAngles, currentViewAngles, sendPacket);
> }

for future reference its better to do invert this and use a return instead, it prevents your indentation from getting crazy large and unreadable.
the compiler makes them output the same code.

**Comment by notgoodusename** [comment]
> > if (!(cmd->buttons & (UserCmd::IN_ATTACK | UserCmd::IN_ATTACK2))) {
> > AntiAim::run(cmd, previousViewAngles, currentViewAngles, sendPacket);
> > }
> 
> for future reference its better to invert this and use a return instead, it prevents your indentation from getting crazy large and unreadable.
> the compiler makes them output the same code.

yeah but you dont want to return in createmove, better do it inside the func
