### ISSUE TITLE
drawOutlinedCircle (draw Aimbot FOV)

### ISSUE THREAD

**Issue by cailloubr** [danielkrupinski/Osiris#1639]
I've updated Draw Aimbot FOV from #1114

I tried to skip the checks by assigning static values, but the circle is not drawn.

I tried #1551 but have the same problem, in all resolutions or aspect ratio.

This makes me think it is a problem with the drawOutlinedCircle function, since in no scenario did it work.

![Screenshot_4](https://user-images.githubusercontent.com/60858720/82852496-871ae500-9ed9-11ea-8c78-20f4d10ab563.png)

**Comment by zSniiKeR** [comment]
Try this #310, work's fine here

**Comment by cailloubr** [comment]
Worked, ty!

**Comment by cailloubr** [comment]
Worked, ty!
