### ISSUE TITLE
Theres a Simple way to make a csgo cheat Menu?

### ISSUE THREAD

**Issue by techprimedev** [danielkrupinski/Osiris#1640]

**Comment by Cyk-Fad** [comment]
? Use IMGUI to do that

**Comment by xAkiraMiura** [comment]
Please provide a description on what you are doing, also why is the title in random caps?

Osiris comes with a menu, if you want to change it you can edit `gui.cpp`.
If you want to make a UI from scratch you would either have to use `ISurface` (less performant, easier) or learn `DirectX` (more preformant, harder)
