### ISSUE TITLE
How make config can't read ？

### ISSUE THREAD

**Issue by Cyk-Fad** [danielkrupinski/Osiris#1641]
Can we use Json to do this?

**Comment by sorrowvibez** [comment]
nah

**Comment by Cyk-Fad** [comment]
... How to do that dude ? Pls help me

**Comment by xAkiraMiura** [comment]
what is your goal?

**Comment by Cyk-Fad** [comment]
People can't read config after save that. like  misc.antiAFK = 010000010111010

**Comment by xAkiraMiura** [comment]
JSON (JavaScript Object Notation) is based on JavaScript and you can't do binary in JavaScript so JSON doesn't support it.

JSON does support strings so you could put that into a string but you would then have to parse it to an integer somehow.

also there is a unicode character than breaks UTF-8 editors on windows but that would cause the JSON to be invalid unless you spliced it off.

**Comment by Cyk-Fad** [comment]
emmmmmmmmm, So I can't use Json to do this
