### ISSUE TITLE
Can't save or load configs

### ISSUE THREAD

**Issue by subessencial** [danielkrupinski/Osiris#1644]
Title.

Seems like the dll isn't creating the folder, for some reason, some help would be appreciated!

**Comment by rosesware** [comment]
> Title.
> 
> Seems like the dll isn't creating the folder, for some reason, some help would be appreciated!

Create yourself.

**Comment by subessencial** [comment]
Created, still doesn't save.

**Comment by danielkrupinski** [comment]
Record the video or gif of how you're creating & saving config.
