### ISSUE TITLE
INJECT

### ISSUE THREAD

**Issue by zajkos** [danielkrupinski/Osiris#1645]
When I inject with many injectors and process hacker I don't see a menu of cheat
How can I fix that

**Comment by notgoodusename** [comment]
press insert and on top should appear

**Comment by zajkos** [comment]
when I press ins I don't see that problem !!! When I inject its injected and i can click anything on cs (the cheat menu is but not visible)

**Comment by cailloubr** [comment]
Your dependencies have problems.

Try install C++ 2015 Runtime (x86) manually:
https://www.microsoft.com/pt-br/download/details.aspx?id=48145

**Comment by xAkiraMiura** [comment]
the project is reliant on C++17? how would the VC++ 2015 runtime be able to support something from the future.

**Comment by zajkos** [comment]
I have VC++ 2008, 2010, 2012, 2013 ,2015, 2017, 2019  Runtime mby i go to reinstall

**Comment by techprimedev** [comment]
make sure you use the 2015 c ++ runtime.

**Comment by zajkos** [comment]
ImGui dependencies --> how can I fix that?

> make sure you use the 2015 c ++ runtime.
I use 100%

![Zrzut ekranu (186)](https://user-images.githubusercontent.com/65664846/83233739-78f5ee80-a18f-11ea-876e-a36b7575c333.png)

**Comment by cailloubr** [comment]
> ![Zrzut ekranu (187)](https://user-images.githubusercontent.com/65664846/83234101-0df8e780-a190-11ea-9aad-e27e93c9c13e.png)
Uninstall and try these package:
https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by zajkos** [comment]
or by accident, if it was on the VC ++ Runtime side, could I not use other cheats?


> > ![Zrzut ekranu (187)](https://user-images.githubusercontent.com/65664846/83234101-0df8e780-a190-11ea-9aad-e27e93c9c13e.png)
> 
> Uninstall and try these package:
> https://aka.ms/vs/16/release/vc_redist.x86.exe
> 
> But I recommend that you review your build settings or download the solution files again.

ok i can try
