### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Heapy1337** [danielkrupinski/Osiris#1646]

**Comment by toprak1224** [comment]
+1

**Comment by egssy0** [comment]
**_Impossible_**

**Comment by egssy0** [comment]
do u think inventory changer real?

**Comment by egssy0** [comment]
Maybe possible but this makes **EZ VAC**

**Comment by techprimedev** [comment]
Wouldn't it be easier to break into Steam's database and give yourself the Desired Skin?
Close this issue soon.

**Comment by Zhxcky** [comment]
> Wouldn't it be easier to break into Steam's database and give yourself the Desired Skin?
> Close this issue soon.

LOL, it was Client-side no need to access the Database, how funny.

**Comment by xAkiraMiura** [comment]
> 
> 
> > Wouldn't it be easier to break into Steam's database and give yourself the Desired Skin?
> > Close this issue soon.
> 
> LOL, it was Client-side no need to access the Database, how funny.

> **and make it like its showing to everybody**

OP wants it server-sided. i dont think "learnread.com" exists though so i can't help you with reading.

**Comment by Heapy1337** [comment]
ok im actually retarded... i edited the description now :)

**Comment by Zhxcky** [comment]
> > > Wouldn't it be easier to break into Steam's database and give yourself the Desired Skin?
> > > Close this issue soon.
> > 
> > 
> > LOL, it was Client-side no need to access the Database, how funny.
> 
> > **and make it like its showing to everybody**
> 
> OP wants it server-sided. i dont think "learnread.com" exists though so i can't help you with reading.

I might be high but don't remember typing this
