### ISSUE TITLE
Font Memory

### ISSUE THREAD

**Issue by egssy0** [danielkrupinski/Osiris#1648]
How can i get memory of the font? 
For Ex: [Balsamiq Sans](https://fonts.google.com/specimen/Balsamiq+Sans?category=Display)

**Comment by xAkiraMiura** [comment]
For ESP: 
install it on Windows. `void ISurface::SetFontGlyphSet(HFont, const char*, ...);` takes 7-9 parameters, the first two being an ID which you plug into the font rendering function (you can create a new font ID with the `HFontISurface::CreateFont();` function) and the name in the `C:/Windows/Fonts` directory (not the file name, just what it displays (`explorer.exe` replaces that directory with a special page))
^ `typedef unsigned long HFont`

For ImGUI:
convert the font into a byte array and then plug it into the imgui renderer function.
