### ISSUE TITLE
a

### ISSUE THREAD

**Issue by CleverSource** [danielkrupinski/Osiris#165]
a

**Comment by HeadlessCpp** [comment]
What do you mean by crosshair

**Comment by CleverSource** [comment]
Crosshair lock on* 
Different from aimbot, all it does is lockon (decide if visible or not) and just has a smoothness option.

**Comment by CleverSource** [comment]
Also a triggerbot for visible and non-visible people would be cool. Just suggestions that my friend asked me to post.

**Comment by HeadlessCpp** [comment]
I'm a little confused what you mean by that, sounds like a aimbot.

**Comment by effex1337** [comment]
Why delete?  :thinking:
