### ISSUE TITLE
CSGO NEW UPDATE and Osiris Crash

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#1650]
FYI: CSGO NEW UPDATE and Osiris Crash when you enter the map
Regards

**Comment by real-Shigure** [comment]
me too, even if i use the clean copy of Osiris.

**Comment by AllyQTs** [comment]
It crashes so I have to inject while im in the match, and opening consle just straight up crashes the game

**Comment by real-Shigure** [comment]
> It crashes so I have to inject while im in the match, and opening consle just straight up crashes the game

Thx, it s seems to be a temporary solution. I think we can inject when player in the match and don not open the consle.

**Comment by danielkrupinski** [comment]
Should be "fixed".
