### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by lizei** [danielkrupinski/Osiris#1656]
How would I start updating the cheat to work for the latest game patch? I've had the source code for some time and I don't feel like scratching it now would be a good idea.. I'd like to continue where I left it.

**Comment by xAkiraMiura** [comment]
`git pull` from within a local git repository to update to remote.
then just rebuild the solution with vs2019.

if you copied and pasted all the code then you won't have your remote set.
at that point just use `del ../Osiris & git clone https://github.com/danielkrupinski/Osiris.git`
(delete and redownload)

**Comment by lizei** [comment]
What would I need to update in the source code? Entity.h? Engine.h? or what?
I really appreciate any answer that could help :)

**Comment by xAkiraMiura** [comment]
use git as it was intended. **git is version control software. you shouldn't need to do anything by hand**. 
[heres an answer that could help.](https://lmgtfy.com/?q=git+pull)

**Comment by lizei** [comment]
Thanks for giving me the answers I looked for. I really appreciate it 👍

**Comment by lizei** [comment]
I just can't figure out how to use this "git pull" and I haven't found any good answer on google either..

**Comment by 4risto** [comment]
> I just can't figure out how to use this "git pull" and I haven't found any good answer on google either..
Or just download the files by using the "Clone or download" button then open the file with visual studio

**Comment by lizei** [comment]
> > I just can't figure out how to use this "git pull" and I haven't found any good answer on google either..
> > Or just download the files by using the "Clone or download" button then open the file with visual studio

I need help to update an older version of osiris not downloading a new one.

**Comment by 4risto** [comment]
> > > I just can't figure out how to use this "git pull" and I haven't found any good answer on google either..
> > > Or just download the files by using the "Clone or download" button then open the file with visual studio
> 
> I need help to update an older version of osiris not downloading a new one.

Ah my bad i didnt actually read all the messages, just tried to help quickly sorry.

**Comment by lizei** [comment]
> > > > I just can't figure out how to use this "git pull" and I haven't found any good answer on google either..
> > > > Or just download the files by using the "Clone or download" button then open the file with visual studio
> > 
> > 
> > I need help to update an older version of osiris not downloading a new one.
> 
> Ah my bad i didnt actually read all the messages, just tried to help quickly sorry.

No problem dude, You was only trying to be helpful :)
