### ISSUE TITLE
minor code fixes

### ISSUE THREAD

**Issue by boris768** [danielkrupinski/Osiris#1657]
https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Netvars.cpp#L152

better to add default: return sequence in this switch, if u add here new knifes, it can cause bugs. also same for line 159

**Comment by cailloubr** [comment]
Make a pull request.

**Comment by xAkiraMiura** [comment]
there is no need for a default case because the default case is the exact same as what the outer block returns. (it would be easier to read but the compiler would get rid of it anyway)
