### ISSUE TITLE
So how to make a desync chams?

### ISSUE THREAD

**Issue by hopelessFantast** [danielkrupinski/Osiris#1658]

**Comment by M3351AN** [comment]
Imagine the desync inside your eye.

**Comment by xAkiraMiura** [comment]
as i wrote on #1039,

> override your material for your **fake** chams
> set the info.angles to your **fake**
> call the original draw model execute
> override your material for your **real** chams
> set the info.angles to your **real**
> call the original draw model execute
>
> all of this should occur in 1 function call.

info is const so you will have to make a non-const copy so you can modify it but thats not hard to figure out.

**Comment by m0rethan3** [comment]
> as i wrote on #1039,
> 
> > override your material for your **fake** chams
> > set the info.angles to your **fake**
> > call the original draw model execute
> > override your material for your **real** chams
> > set the info.angles to your **real**
> > call the original draw model execute
> > all of this should occur in 1 function call.
> 
> info is const so you will have to make a non-const copy so you can modify it but thats not hard to figure out.

thats not how things work after fake angle patch
