### ISSUE TITLE
[REQUEST] - jump check 

### ISSUE THREAD

**Issue by zajkos** [danielkrupinski/Osiris#1659]
Can u add JUMP CHECK on AIMBOT options?

**Comment by Kron1Q** [comment]
just check if you are IN_JUMP and return

**Comment by zajkos** [comment]
Like this?

Aimbot.cpp     --->
if (!(localPlayer->GetFlags() & FL_ONGROUND) && Settings::Aimbot::aim_JumpCheck)
		return;

Config.cpp        --->
ImGui::Checkbox("In Air", &Settings::Aimbot::aim_JumpCheck);

**Comment by zajkos** [comment]
good or bad?

**Comment by Kron1Q** [comment]
Like this, just convert it to fit osiris. Add jumpcheck in config.h and checkbox in gui.

**Comment by zajkos** [comment]
like this in GUI?
ImGui::Checkbox("Jump Check", &Settings::Aimbot::aim_JumpCheck);

and in config.h?
bool JumpCheck{ false };

**Comment by zajkos** [comment]
I know I must change aimbot.cpp ( and GUI) because I write this modeling on GODWARE and INDIGO
and in particular, I have to change it --> & FL_ONGROUND) && Settings::Aimbot::aim_JumpCheck

**Comment by zajkos** [comment]
sorry I'm so weak in c ++ but I'm just starting to learn it and I thought it would be a good way to write simple functions

**Comment by zajkos** [comment]
on GUI cpp?
ImGui::Checkbox("Jump Check", &config->aimbot[currentWeapon].JumpCheck);

**Comment by zajkos** [comment]
aimbot.cpp
if (config->aimbot[weaponIndex].JumpCheck
		return;

**Comment by zajkos** [comment]
or like this?
if (bestTarget->GetFlags() & FL_ONGROUND) & (config->aimbot[weaponIndex].JumpCheck{
            return;
              }

**Comment by zajkos** [comment]
who can help me XD

**Comment by xAkiraMiura** [comment]
use git as it was intended. make a fork and commit your changes. (you can fork without making a pull request)

**Comment by zajkos** [comment]
@Kron1Q Thanks i love u 💙 but here is one problem -->
"jump check" is not a component of "Config :: Aimbot"
did I do something wrong?

**Comment by zajkos** [comment]
ok i fix  -->

aimbot.cpp
`if (!(localPlayer->flags() & FL_ONGROUND) && config->aimbot[weaponIndex].jumpCheck)
return;`

entity.h
`#define FL_ONGROUND (1<<0)`

config.h / in aimbot struct
`bool jumpCheck{ false };`

gui.cpp / in aimbot
`ImGui::Checkbox("jump check", &config->aimbot[currentWeapon].jumpCheck);`

config.cpp
`if (aimbotJson.isMember("jumpcheck")) aimbotConfig.jumpCheck= aimbotJson["jump check"].asBool();`
(change jumpcheck --> jumpCheck)

and lower in cfg load
`aimbotJson["jump check"] = aimbotConfig.jumpCheck;`
(change jumpcheck --> jumpCheck)
