### ISSUE TITLE
Issues compiling

### ISSUE THREAD

**Issue by lizei** [danielkrupinski/Osiris#1663]
Okey so when I'm trying to build the solution I get errors like these. If anyone knows how to solve it It'd be much appreciated :)
![devenv_N4FqMTVNuQ](https://user-images.githubusercontent.com/61404620/83333007-b2694f80-a29e-11ea-84bc-fbfbf7c8b63d.png)

**Comment by techprimedev** [comment]
you are using #include <string> ?

**Comment by lizei** [comment]
Yeah, I get 34 of those errors and all are coming from the same file "Memory.h"

**Comment by danielkrupinski** [comment]
What version of Visual Studio you're using?

**Comment by lizei** [comment]
Visual Studio 2019 version: 16.6.0

**Comment by danielkrupinski** [comment]
Make sure you're using the latest copy of the source code - there is no way for that error to occur in Hooks.cpp as stringstreams are used only in Esp.cpp and Misc.cpp. Also Memory.h doesn't use  stringstreams anymore.

**Comment by lizei** [comment]
I'm using an older version of the source code which I wanted to update after the latest csgo update broke it.

**Comment by danielkrupinski** [comment]
Then you can try to cast it to `const std::ostringstream&` like
```cpp
static_cast<const std::ostringstream&>(std::ostringstream{ } << "Failed to find pattern in " << module << '!').str()
```

**Comment by lizei** [comment]
It seemed to solve all problems but I'll still have to update the cheat in order for it to work with latest csgo patch, what broke in the latest update? Anything to update in "Entity.h"?
