### ISSUE TITLE
[Request] Add Stream Proof

### ISSUE THREAD

**Issue by techprimedev** [danielkrupinski/Osiris#1664]
Is it very difficult to add a Stream proof / OBS Spoofer?

**Comment by TauCSGO** [comment]
duplicate ... multiple times...
https://github.com/danielkrupinski/Osiris/issues?q=is%3Aissue+obs

**Comment by pkienhai** [comment]
use GOESP
https://github.com/danielkrupinski/GOESP

**Comment by techprimedev** [comment]
> use GOESP
> https://github.com/danielkrupinski/GOESP

But, i want to use other functions  aimbot, skinchanger and misc.

Is possible copy code from GOESP to Osíris?

**Comment by cailloubr** [comment]
> > use GOESP
> > https://github.com/danielkrupinski/GOESP
> 
> But, i want to use other functions aimbot, skinchanger and misc.
> 
> Is possible copy code from GOESP to Osíris?

Inject Osiris and GOESP together. 

Use Osiris for Aimbot/Misc/etc and GOESP for ESPs.

**Comment by toprak1224** [comment]
@cailloubr ıllısson%100

**Comment by hyperxpro** [comment]
Funny to see kids requesting features again and again without checking backlog for it. Why not add the feature yourself?

**Comment by rafalohaki** [comment]
we need a moderator

**Comment by hyperxpro** [comment]
> we need a moderator

+1

**Comment by techprimedev** [comment]
Sorry for this issue, i will try to add the stream mode and send to Pulls.
