### ISSUE TITLE
 FPS will decrease,

### ISSUE THREAD

**Issue by AlisaCiya** [danielkrupinski/Osiris#1665]
how to fix it

**Comment by cailloubr** [comment]
https://www.ebay.com/itm/AMD-RYZEN-5-3600-6-Core-3-6-GHz-4-2-GHz-Max-Boost-Socket-AM4-65W-100-100000031/293145457304

**Comment by 18339256125** [comment]
If I don't inject, then FPS300 +, but if I inject, FPS100 ~ 150, when I see the enemy, it drops to double digits

**Comment by VuBrian22** [comment]
Did you compile with AVX2 or AVX512 optimizations depending on your CPU?

**Comment by Cyk-Fad** [comment]
打钱 QQ 2476159893

**Comment by Cyk-Fad** [comment]
手机号当GIT名字 牛大了
