### ISSUE TITLE
explanation of what each option does on all the cheats(aimbot, anti aim, etc..)

### ISSUE THREAD

**Issue by amirgambit** [danielkrupinski/Osiris#1666]
Is there some kind of faq or readme that explains all this. For now, ive only been using glow cause i dont know how to use others.

**Comment by KernCS** [comment]
https://github.com/danielkrupinski/Osiris/blob/master/README.md  ??

![OjMBVLj](https://user-images.githubusercontent.com/31683300/83354440-eb65fa80-a358-11ea-9a5b-a99095207667.png)

**Comment by amirgambit** [comment]
my bad. didnt realize it. thanks
