### ISSUE TITLE
CS:GO crashes when injecting an AVX-512 or AVX2 compiled build.

### ISSUE THREAD

**Issue by ryseDMT** [danielkrupinski/Osiris#1668]
My CPU is a Ryzen 5 2600 and ,according to several websites, supports AVX2 and AVX-512. I know this isn't an issue with the source itself, but I am still curious as to why that happens. As for now, I'm going to fall back to compiling with SSE2.

**Comment by g42ftw** [comment]
AVX-512 is not supported by Ryzen 5 2600, that's why your game crashes with your own Osiris build.
