### ISSUE TITLE
if inject csgo crashing

### ISSUE THREAD

**Issue by ahmet1231** [danielkrupinski/Osiris#1670]
if i inject with ayyhook loader osiris its crashing

**Comment by littlehurensohn** [comment]
Try another injector.

**Comment by techprimedev** [comment]
hey man, ayyhook use ManualMap Method, but not updated, use Rando-Injector or Extreme Injetor.

**Comment by ahmet1231** [comment]
> hey man, ayyhook use ManualMap Method, but not updated, use Rando-Injector or Extreme Injetor.

how to change method ?

**Comment by DoomFishWasTaken** [comment]
not trying to sell osiris, are you now? because last time i checked ayyhook was a p2c loader? if you are trying to sell someone else's work don't go ask for help doing it.

**Comment by ahmet1231** [comment]
> not trying to sell osiris, are you now? because last time i checked ayyhook was a p2c loader? if you are trying to sell someone else's work don't go ask for help doing it.

no im not trying to sell

**Comment by danielkrupinski** [comment]
Debug it then.

**Comment by ahmet1231** [comment]
> Debug it then.

what ?

**Comment by techzin** [comment]
> > hey man, ayyhook use ManualMap Method, but not updated, use Rando-Injector or Extreme Injetor.
> 
> how to change method ?
Use LoadLibrary to Inject.
