### ISSUE TITLE
Skinchanger OW Ban

### ISSUE THREAD

**Issue by AlisaCiya** [danielkrupinski/Osiris#1671]
I only used the skinchanger, other functions are not used, but I was OWBan

**Comment by TauCSGO** [comment]
Many people have received OW ban between yesterday and today. I don't know what the reason is, maybe osiris was detected somehow. At cheater.fun people also complain

**Comment by xAkiraMiura** [comment]
this was closed because skinchanger is purely local. there is no way for OW to see it.
you had ESP or something enabled and your behaviour gave it away.

**Comment by TauCSGO** [comment]
I did not say that the skins are seen in the game, but rather that the function was detected

**Comment by xAkiraMiura** [comment]
how would a function being detected lead to OW? only VAC does things to the client, VACnet and OW are completely server sided and behaviour based.

**Comment by AlisaCiya** [comment]
I just used the skinchanger, the other functions were not used, but I was VACBAN, and I swear that what I said is true

**Comment by xAkiraMiura** [comment]
> I only used the skinchanger, other functions are not used, but I was OWBan

> but I was VACBAN

OW != VAC

**Comment by AlisaCiya** [comment]
I know, but I have already been VACBan, they came out together,
I also know that OWBan is reported to be cheated by others.

**Comment by TauCSGO** [comment]
Maybe
#1681
