### ISSUE TITLE
Custom hitsound made me unable to enter Official Matchmaking.

### ISSUE THREAD

**Issue by nucreac** [danielkrupinski/Osiris#1672]
The instructions were clear, "Put sound on csgo/sound/". So, I put a .wav file inside "sound" folder, I tried it on Aimbotz or any other custom maps, it worked. But, as soon as I tried to enter Official Matchmaking, it said something about me modifying the game files and prevents me from playing Competitive Mode. Help, please?

**Comment by xAkiraMiura** [comment]
verify integrity of game files from inside steam. sounds shouldn't be protected like materials are.
