### ISSUE TITLE
[REQUEST] color

### ISSUE THREAD

**Issue by JacksonDon** [danielkrupinski/Osiris#1673]
Yo kinda stoopid but is there someone who can make "rainbowColor" time, speed, only on these colors? 

30, 255, 109 / 255 = 0.11f, 1.0f, 0.42f
235, 64, 52 / 255 = 0.92f, 0.25f, 0.20f

Thanks.

**Comment by littlehurensohn** [comment]
@DoomFishWasTaken
@effex1337 

please.

**Comment by littlehurensohn** [comment]
@danielkrupinski is it possible please?

**Comment by cailloubr** [comment]
Use Glow rainbow as example.

**Comment by DoomFishWasTaken** [comment]
> 30, 255, 109 / 255 = 0.11f, 1.0f, 0.42f
> 235, 64, 52 / 255 = 0.92f, 0.25f, 0.20f

@littlehurensohn do you want the rainbowColor to fade between these colors?

**Comment by littlehurensohn** [comment]
> > 30, 255, 109 / 255 = 0.11f, 1.0f, 0.42f
> > 235, 64, 52 / 255 = 0.92f, 0.25f, 0.20f
> 
> @littlehurensohn do you want the rainbowColor to fade between these colors?

Yeah..

**Comment by littlehurensohn** [comment]
@DoomFishWasTaken Is it possible?

**Comment by xAkiraMiura** [comment]
just calculate a gradient and use the engine currtime modulused by the duration to index it.
as you have said yourself, "Code it your self, its easy."
