### ISSUE TITLE
Add Image to Cheat.

### ISSUE THREAD

**Issue by techprimedev** [danielkrupinski/Osiris#1674]
Uhh yeah im trying to draw a image but i have no idea

ImTextureID my_tex_id = io.Fonts->TexID;

float my_tex_w = (float)io.Fonts->TexWidth;

float my_tex_h = (float)io.Fonts->TexHeight;

ImGui::Image(my_tex_id, ImVec2(my_tex_w, my_tex_h), ImVec2(0, 0), ImVec2(1, 1), ImColor(255, 255, 255, 255), ImColor(255, 255, 255, 128));

Just copy and pasted the example from imgui_demo but how can i change the ImTextureId to a png?

ImTextureID my_tex_id = "D:\DL\_SHIT\xd.JPG";

doesnt work

**Comment by 3Ld4D** [comment]
https://github.com/ocornut/imgui

**Comment by techprimedev** [comment]
> https://github.com/ocornut/imgui

i tryed, but don`t work.

**Comment by cailloubr** [comment]
https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples

This is the unique method to use.

**Comment by littlehurensohn** [comment]
IDirect3DTexture9
