### ISSUE TITLE
My Animation Fix so far (aka AnimFix)

### ISSUE THREAD

**Issue by notgoodusename** [danielkrupinski/Osiris#1675]
Right now hooking DoExtraBoneProcessing and StandardBlendingRules,
 looks good 
except when knifing which fucks up duck amount but apart from that pretty gucci
https://streamable.com/6oxuyy

**Comment by exDot-programmer** [comment]
hey share this code please i need this

**Comment by notgoodusename** [comment]
This is old af, i have a better animfix on my repo (OsirisAndExtra)
