### ISSUE TITLE
Get Ping value in int

### ISSUE THREAD

**Issue by techzin** [danielkrupinski/Osiris#1676]
i'm particularly new to c ++, i'm trying to get the fps value in const char, to use in ImGui :: Text ("");

But I had several problems, could someone reveal the exact code to me?

i would like the watermark fps

code ()

std :: wstring fps {L "FPS:" + std :: to_wstring (static_cast <int> (1 / frameRate))};

**Comment by xAkiraMiura** [comment]
> Get **Ping** value in int

> i'm trying to get the **fps** value in const char

which one are you actually trying to get.

also your static_cast has a syntax error and isn't even needed.

**Comment by techprimedev** [comment]
> > Get **Ping** value in int
> 
> > i'm trying to get the **fps** value in const char
> 
> which one are you actually trying to get.
> 
> also your static_cast has a syntax error and isn't even needed.

this is the code of Osiris Watermark
