### ISSUE TITLE
[request] config auto save

### ISSUE THREAD

**Issue by janbonk** [danielkrupinski/Osiris#1677]
automatically saves config after changing features

**Comment by cailloubr** [comment]
Wouldn't it be more secure and stable if the configuration was saved when closing the menu? Since technically it won't make a difference if you activate and deactivate the function without closing the menu?

**Comment by xAkiraMiura** [comment]
i use configs as templates and modify them slightly to adapt to the current situation, this would break that.

> Wouldn't it be more secure and stable if the configuration was saved when closing the menu? Since technically it won't make a difference if you activate and deactivate the function without closing the menu?

it is more stable in the case that something toggling causes a crash while it is writing to disk, but secure != stable, this has nothing to do with security.

also if you hold down the menu key then you get a load of writes to the disk which is always great for performance.

**Comment by cailloubr** [comment]
> it is more stable in the case that something toggling causes a crash while it is writing to disk, but secure != stable, this has nothing to do with security.
> 

Safe when accidentally modifying settings.

> also if you hold down the menu key then you get a load of writes to the disk which is always great for performance.

I think there must be some problem in my build then, because when I hold the button, it is only computed once (the menu opens / closes, but does not repeat the action)
