### ISSUE TITLE
A help?

### ISSUE THREAD

**Issue by RichhieCheaterfun** [danielkrupinski/Osiris#1679]
Can someone explain which program i should use if i wanna to add for example Fake items unbox & chat #1483 to osiris? Or how i can do this?

I tried with visual studio copy - paste codes and i got around 40 errors

I know this is stupid but i am new into this..

**Comment by KernCS** [comment]
learn basic c++ then it should be pretty straightforward copy - paste

**Comment by xAkiraMiura** [comment]
you want to use `git merge` because that is why we are using git in the first place.
pasting doesn't require any understanding of basic c++

**Comment by cailloubr** [comment]
> you want to use `git merge` because that is why we are using git in the first place.
> pasting doesn't require any understanding of basic c++

If you don't have programming skills it becomes difficult, especially since these people don't even know how to use git/github.

Basically is CHEATER.FUN member trying make your own build.
