### ISSUE TITLE
Watermark

### ISSUE THREAD

**Issue by cojo1989** [danielkrupinski/Osiris#168]
Any posibility to add when you activate the watermark to apear the FPS and to be the name Osiris rainbow mode or something? Thank you :D

**Comment by cojo1989** [comment]
It would be great to add FPS and PING ❤️❤️

**Comment by danielkrupinski** [comment]
Added. Thanks!

**Comment by cojo1989** [comment]
Daniel thank you buddy. Im not gone be able to test it today. But when i will be able im gone leave you a review. Very good job buddy. I love your work, appreciate. 😂😂😂
