### ISSUE TITLE
Csgo crashing

### ISSUE THREAD

**Issue by ShortLatino** [danielkrupinski/Osiris#1680]
Everytime I inject osiris csgo it gets injected in the main menu but once I go into a game it crashes and if I try and inject in a game I crash too

**Comment by cailloubr** [comment]
Which injector are you using?

**Comment by ShortLatino** [comment]
a custom one but I get this now when I try to inject:
![image](https://user-images.githubusercontent.com/65367131/83780735-d6a5a180-a68d-11ea-9975-e60ee3d749f4.png)

**Comment by cailloubr** [comment]
Update your project to the lastest build.

**Comment by ShortLatino** [comment]
I have I just downloaded thhe newest version

**Comment by ShortLatino** [comment]
I fixed it but now when I join a game with it injected or inject in a game I crash

**Comment by DoomFishWasTaken** [comment]
download a clean version of repo, its probably something that you did wrong.

**Comment by littlehurensohn** [comment]
#1701
