### ISSUE TITLE
FYI: Maybe Detected

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#1681]
Since two days ago, many people I know have received BAN (Overwartch).
It was not worrying, because OW is the responsibility of each one.
But today VAC BAN started to fall
I don't know if it's a new VAC WAVE or any changes that made Osiris detectable.
It would be nice if you could review it earlier or what change valve made before being sure and continuing.

Personally I think the OW BAN message is showing because of some kind of error, but it is actually a VAC BAN
There are many accounts of many people I know who have had BAN in these two days

I particularly use the Injector: https://github.com/danielkrupinski/curiuminjector-csgo
@danielkrupinski 
It was never detected, in addition to changing the junk code every week.
But other well-known people don't use that injector, so I don't know the reason for so many BAN

**Comment by toprak1224** [comment]
banned on 3 accounts today  ı use only osiris

**Comment by danielkrupinski** [comment]
It may be because of commit abd14654ef993b96ce832f17261fe7dcd6a00fb1 making vmt hooks detection-prone.

**Comment by techprimedev** [comment]
@danielkrupinski what can you do to solve this problem?

**Comment by LOG1CC** [comment]
Idk I used it with your bypass + VM and didn't get banned.

**Comment by techprimedev** [comment]
Yes, I'm using danielkrupinski's Bypass Loader, and so far I haven't received a vac ban, but I was a little afraid now.

> Idk eu usei com seu desvio + VM e não fui banido.

Yes, I'm using danielkrupinski's Bypass Loader, and so far I haven't received a vac ban, but I was a little afraid now.

**Comment by danielkrupinski** [comment]
You can change hooking method or use [Vac-Bypass](https://github.com/danielkrupinski/Vac-Bypass) (if it still works).

**Comment by LOG1CC** [comment]
I'm not the one pro in coding in this thread xd

**Comment by LOG1CC** [comment]
Some people were trying your bypass, they hook cheat engine and it still works.

**Comment by techprimedev** [comment]
> Você pode alterar o método de conexão ou usar o [Vac-Bypass](https://github.com/danielkrupinski/Vac-Bypass) (se ainda funcionar).

could you commit to solve this problem? who knows how to use the old hook method.

**Comment by TheNulledJester** [comment]
Would love to see a commit to solve this issue. If not, thank you either way for updating the solution constantly.

**Comment by TauCSGO** [comment]
> You can change hooking method or use [Vac-Bypass](https://github.com/danielkrupinski/Vac-Bypass) (if it still works).
this is the same?
https://github.com/danielkrupinski/VAC-Bypass-Loader

**Comment by TauCSGO** [comment]
> You can change hooking method or use [Vac-Bypass](https://github.com/danielkrupinski/Vac-Bypass) (if it still works).

this is the same?
https://github.com/danielkrupinski/VAC-Bypass-Loader

**Comment by 3Ld4D** [comment]
> It may be because of commit [abd1465](https://github.com/danielkrupinski/Osiris/commit/abd14654ef993b96ce832f17261fe7dcd6a00fb1) making vmt hooks detection-prone.

i didn't get banned so it probably isn't.

**Comment by Vadenez** [comment]
@danielkrupinski, Yes the VAC-Bypass-Loader still works, from my experiences...

**Comment by techprimedev** [comment]
my friends got banned 1 hour ago, they said they always used VAC Bypass (2 friends.), But i`m not banned at this moment.

**Comment by techprimedev** [comment]
@danielkrupinski will you update the VM?

**Comment by Lazaggna** [comment]
Still not vac banned, seems fine.

**Comment by Asviix** [comment]
I've been using it a lot after this commit even dropping 40 frags as "legit"
no ban at all

**Comment by notgoodusename** [comment]
JUNK CODE DOES NOTHING! ITS A GIGANTIC MEME

**Comment by 3Ld4D** [comment]
> JUNK CODE DOES NOTHING! ITS A GIGANTIC MEME

only changes hashing not signature so it's useless

**Comment by Th3nd** [comment]
i got ow banned yesterday :( could be detected, or i could be an idiot.

**Comment by cailloubr** [comment]
I've some pulls in my code, works perfectly, no one have receive VAC (i update to a forum, ~100 daily users, manual map injection)

**Comment by techprimedev** [comment]
all my friends are being banned hahahahaha.
so far i'm safe.

**Comment by notgoodusename** [comment]
> all my friends are being banned hahahahaha.
> so far i'm safe.

same as me.

**Comment by tirziz** [comment]
> all my friends are being banned hahahahaha.
> so far i'm safe.

Are you using aimbot ?

**Comment by toxic-bhaiya** [comment]
i got vacced low fov aim and visible chams is all I use is it the cheat or the project infinity loader ??

**Comment by ocewot** [comment]
i also got vacced havent used it in 3 days as well and the vac ban just appeared today

**Comment by Asviix** [comment]
Been OW banned on a dummy account too, might want to wait if you use it on an account you care about

**Comment by techprimedev** [comment]
> > all my friends are being banned hahahahaha.
> > so far i'm safe.
> 
> Are you using aimbot ?

Using Fov 0.86 with Silent

**Comment by Zhxcky** [comment]
> i got ow banned yesterday :( could be detected, or i could be an idiot.

OW are different from VAC, Probably bcuz you're too obvious, try to be more legit.

**Comment by AlisaCiya** [comment]
I just used the skinchanger and it will also be VAC, OW

**Comment by TheFantasticLoki** [comment]
1 Vac as of today. no ow ban. tho I have only been OW banned twice in 2 years.

**Comment by BloodXPride** [comment]
2 accs VAC ban, 2 accs OW ban. Strange. Injected via manual mapping with thread hijacking. My friend used loadlibrary bytecode based injection. That makes no difference. Nevertheless banned. Its for sure detected in my opinion. Can be the hookingmethod, i dont know.

**Comment by Sadlysius** [comment]
I haven't been banned; used it for 250 hours in the last month with some minor modifications to the source and Daniel's VAC bypass.
I will avoid using it during this time till this issue gets resolved tho.

**Comment by rosesware** [comment]
> Since two days ago, many people I know have received BAN (Overwartch).

If your friends got overwatch ban, it was not by detection, it's simple, your friends who perceive 0 of everything that encompasses CS, who played blatant and were overwatched, VAC! Simple as that.

**Comment by notgoodusename** [comment]
Got VAC Banned, doesnt matter it was a smurf anyways

**Comment by techprimedev** [comment]
The VAC Bypass no longer protects you.

I've been using Bypass with Osiris for 2 weeks and today I received a VAC ban. you will only be able to search for a few and then receive the vac, even when using the Bypass.

Osiris has Detected.

**Comment by jwao** [comment]
@techprimedev Kinda funny I found you here...You are the developer of "Scorpion cheats" that's a p2c Osiris paste.
What a meme.

**Comment by tirziz** [comment]
I can confirm multiple of my non prime account getting ban. Reason: unknow. Functions used: visible charm, bhop and skin changer.

**Comment by techzin** [comment]
> I can confirm multiple of my non prime account getting ban. Reason: unknown. Functions used: visible charm, bhop and skin changer.

Try to Use Vac Bypass, and say the results.

**Comment by jwao** [comment]
Funny how you changed your name 

> > I can confirm multiple of my non prime account getting ban. Reason: unknown. Functions used: visible charm, bhop and skin changer.
> 
> Try to Use Vac Bypass, and say the results.

**Comment by techzin** [comment]
> Funny how you changed your name
> 
> > > I can confirm multiple of my non prime account getting ban. Reason: unknown. Functions used: visible charm, bhop and skin changer.
> > 
> > 
> > Try to Use Vac Bypass, and say the results.

what do you want here?

**Comment by notgoodusename** [comment]
> > Funny how you changed your name
> > > > I can confirm multiple of my non prime account getting ban. Reason: unknown. Functions used: visible charm, bhop and skin changer.
> > > 
> > > 
> > > Try to Use Vac Bypass, and say the results.
> 
> what do you want here?

LMAO, imagine selling osiris as a p2c

**Comment by techzin** [comment]
> > > Funny how you changed your name
> > > > > I can confirm multiple of my non prime account getting ban. Reason: unknown. Functions used: visible charm, bhop and skin changer.
> > > > 
> > > > 
> > > > Try to Use Vac Bypass, and say the results.
> > 
> > 
> > what do you want here?
> 
> LMAO, imagine selling osiris as a p2c

I am not selling Osiris.

**Comment by notgoodusename** [comment]
> I am not selling Osiris.


You have a fucking website by your name and inside you say you sell "Best cheats of brazil" LMAO, clown
also here is a screenshot of the menu you sell as a p2c
http://prntscr.com/sv1t0h
vid:
https://www.youtube.com/watch?v=uYNxjjo1AdU

**Comment by techzin** [comment]
I do not control ScorpionCheats.

I only sell the Loader for them.

With the My forum API.

**Comment by notgoodusename** [comment]
Your website
https://www.techprimedev.tech/
insecure btw, had to open in incognito

**Comment by notgoodusename** [comment]
> I do not control ScorpionCheats.
> 
> I only sell the Loader for them.
> 
> With the My forum API.

Then who does? And why is there an option to pay?

**Comment by techzin** [comment]
> > I do not control ScorpionCheats.
> > I only sell the Loader for them.
> > With the My forum API.
> 
> Then who does? And why is there an option to pay?

I don't know if you noticed, but my forum is a cheat forum. Anyone can hire me to make a loader for their cheat.

**Comment by notgoodusename** [comment]
> I don't know if you noticed, but my forum is a cheat forum. Anyone can hire me to make a loader for their cheat.


Do you know the coders?

**Comment by techzin** [comment]
> > I do not control ScorpionCheats.
> > I only sell the Loader for them.
> > With the My forum API.
> 
> Then who does? And why is there an option to pay?

I have a partnership with ScorpionCheats, I only take care of the Loader.

**Comment by techzin** [comment]
> Your website
> https://www.techprimedev.tech/
> insecure btw, had to open in incognito

How they do their cheats I shouldn't worry.

**Comment by notgoodusename** [comment]
> How they do their cheats I shouldn't worry.

ok
