### ISSUE TITLE
Crash when injected

### ISSUE THREAD

**Issue by infinity1211** [danielkrupinski/Osiris#1682]
![Untitled](https://user-images.githubusercontent.com/65710399/83719798-7bf05380-a655-11ea-8b36-53cf971aad2a.png)

It shows this error

**Comment by VuBrian22** [comment]
Yeah it happens after the new update to CS. @danielkrupinski

**Comment by infinity1211** [comment]
Thanks @VuBrian22

**Comment by xAkiraMiura** [comment]
interfaces are a system that valve implements into every single DLL they make, by specifying a DLL and a string it will return a pointer to the beginning of the class. 
apparently client_panorama was renamed to client and so its not going to find something inside of nothing. (that or VClient changed from 018 to (probably) 019)
(hooking is downstream of interfaces so you are not completely wrong)
