### ISSUE TITLE
[Error] Failed to find VClient018 interface.

### ISSUE THREAD

**Issue by real-Shigure** [danielkrupinski/Osiris#1683]
CSGO updated 10 min ago, and Osiris told me the error message when i inject the dll. I m not sure if the update cause this error.

**Comment by real-Shigure** [comment]
i have verified the integrity of CSGO files, but the error still occur.

**Comment by Amedin21** [comment]
yes,fix this problem

**Comment by infinity1211** [comment]
It happens when the game updates wait for @danielkrupinski to fix this

**Comment by real-Shigure** [comment]
same error on onetap dll, this is error info:

----------- INFO ----------
Layer: 1.
Caused: Can't find offset. Signature: 55 8B EC 83 E4 F8 83 EC 70 6A 58.
----------------------------

so i think the reason is the change ofsignature when CSGO updates (maybe).

**Comment by DoomFishWasTaken** [comment]
found the problem making a pull request now @danielkrupinski

**Comment by yaelahrip** [comment]
its been changed back to client.dll

**Comment by DoomFishWasTaken** [comment]
@yaelahrip im making a pull rn

**Comment by yaelahrip** [comment]
@DoomFishWasTaken ah yu did it alr. thx.

**Comment by danielkrupinski** [comment]
Fixed

**Comment by aloraini1419** [comment]
> Fixed

can you give the fixed one?
