### ISSUE TITLE
Chams don't work after updating to latest

### ISSUE THREAD

**Issue by TheLuaDawge** [danielkrupinski/Osiris#1686]

**Comment by cailloubr** [comment]
Check your code, working perfectly on original build.

**Comment by TheLuaDawge** [comment]
Checked everything, did it correctly.

**Comment by TheLuaDawge** [comment]
![image](https://user-images.githubusercontent.com/22395774/83748919-35095a80-a663-11ea-8cd6-9e902867c38b.png)
I have Allies on all and the enemy is affected.
My enemy chams are off and if I turn it on it doesn't work.

**Comment by TheLuaDawge** [comment]
just realized, autoshot broke too for some reason

**Comment by cailloubr** [comment]
Download the lastest build.

**Comment by hastydev** [comment]
[ALTERNATE ACCOUNT] I think this error was because of my isOtherEnemy function.
please close this some1
