### ISSUE TITLE
[REQUEST]Knifebot

### ISSUE THREAD

**Issue by N0x0PE** [danielkrupinski/Osiris#1687]
A knifebot (a trigger bot that stabs someone if he can) with the option to do only back stabs / only slashes / only stabs.

**Comment by 6ick** [comment]
Knife bot is part of cheats with a ragebot..
I dont think it will be added in the near future to osirs, because it is a legit cheat-

**Comment by stacyonthatbeat** [comment]
> Knife bot is part of cheats with a ragebot..
> I dont think it will be added in the near future to osirs, because it is a legit cheat-

A knifebot can be used legitimately? It's just automatically knifing depending on the enemy's health

**Comment by M3351AN** [comment]
Just like a trigger not with knifes

**Comment by stacyonthatbeat** [comment]
> Just like a trigger not with knifes

It's just like a trigger but with knives*
