### ISSUE TITLE
[REQUEST] Standalone RCS

### ISSUE THREAD

**Issue by aljawary** [danielkrupinski/Osiris#1691]
how to make or add standaone RCS?
example: https://www.youtube.com/watch?v=mw7o6pJRmik

**Comment by Asviix** [comment]
#1277

**Comment by aljawary** [comment]
thx dude

**Comment by mazmamad** [comment]
awokokawokwaokaw tolol

**Comment by aljawary** [comment]
> awokokawokwaokawoh no, i got spotted
