### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#1692]
https://i.imgur.com/Fshlhdm.png

**Comment by Shuvi-Moro** [comment]
https://i.imgur.com/8J89vw4.png

**Comment by Shuvi-Moro** [comment]
https://i.imgur.com/6h5Hu24.png

**Comment by yaelahrip** [comment]
@Shuvi-Moro Retarget your project. and make sure all lib&inc are loaded.

**Comment by Shuvi-Moro** [comment]
@yaelahrip And where can I download them?

**Comment by danielkrupinski** [comment]
In Visual Studio Installer select and install package for C++ development.
