### ISSUE TITLE
Aimbot Hitchance?

### ISSUE THREAD

**Issue by Cyk-Fad** [danielkrupinski/Osiris#1694]
like tittle, how to do this. 
I don't know

**Comment by notgoodusename** [comment]
https://github.com/mdilai/JweegaCSGO/blob/master/Jweega/Hacks/Aimbot.cpp#L98

**Comment by Cyk-Fad** [comment]
It's not working......
The game will stop working...

**Comment by hastydev** [comment]
please tell me you didn't paste the entire code

**Comment by aljawary** [comment]
i got error in this line, help!
https://prnt.sc/svexsm

**Comment by hastydev** [comment]
try localPlayer.get

**Comment by aljawary** [comment]
thx solved

**Comment by aljawary** [comment]
thx but my game crash after it

**Comment by dapaster** [comment]
@Cyk-Fad 
#1716

**Comment by Cyk-Fad** [comment]
> @Cyk-Fad
> 
> Here you go
> #1716

Thanks
