### ISSUE TITLE
CS:GO Crashes on injection. No errors.

### ISSUE THREAD

**Issue by ryseDMT** [danielkrupinski/Osiris#1695]
After merging your fixes for recent Counter-Strike updates, my build of the cheat causes csgo.exe to crash when injected via LoadLibrary. No errors appear.

**Comment by ryseDMT** [comment]
Even cloning this repo and compiling this without making any changes, the issue persists.

**Comment by hastydev** [comment]
Mine keeps crashing sometimes on menu.

**Comment by ryseDMT** [comment]
Problem was on my end. For some reason, VMProtect does not function anymore FYI.  I know it's not a good way of protecting an internal CS:GO cheat, but (I think) it's better than nothing. Now it just crashes the game on injection.
