### ISSUE TITLE
Menu Design

### ISSUE THREAD

**Issue by CerberusGame** [danielkrupinski/Osiris#1696]
I just want renderGuiStyle2 to appear. How can I do it ?

**Comment by xtyspengu** [comment]
This is C+P. Delete void GUI::render() noexcept and replace it with the below



void GUI::render() noexcept
{
    if (!config->style.menuStyle) {
        renderGuiStyle2();
    }
}

**Comment by hastydev** [comment]
modify the code in gui.cpp

**Comment by CerberusGame** [comment]
> This is C+P. Delete void GUI::render() noexcept and replace it with the below
> 
> void GUI::render() noexcept
> {
> if (!config->style.menuStyle) {
> renderGuiStyle2();
> }
> }

I did, but the menu opens automatically.

**Comment by CerberusGame** [comment]
I changed open = true in GUI.h, but it didn't work.

**Comment by techprimedev** [comment]
> I changed open = true in GUI.h, but it didn't work.

no, change the GUI::render()

and set renderGuiStyle2();

**Comment by DoomFishWasTaken** [comment]
better way of doing this: 
replace (in Config.h)
`    struct {
        int menuStyle{ 0 };
        int menuColors{ 0 };
    } style;`
with
`    struct {
        int menuStyle{ 1 };
        int menuColors{ 0 };
    } style;`

**Comment by CerberusGame** [comment]
> better way of doing this:
> replace (in Config.h)
> 
> ```
>    struct {
>         int menuStyle{ 0 };
>         int menuColors{ 0 };
>     } style;
> ```
> 
> with
> 
> ```
>     struct {
>         int menuStyle{ 1 };
>         int menuColors{ 0 };
>     } style;
> ```

nothing has changed

**Comment by CerberusGame** [comment]
@danielkrupinski Help me pls

**Comment by CerberusGame** [comment]
If the menu does not open automatically, it can work. How can I turn off the automatically opening of the menu ?

**Comment by CerberusGame** [comment]
Bool open = true in GUI.h I tried to change it but it didn't

**Comment by DoomFishWasTaken** [comment]
@CerberusGame 
`        int menuStyle{ 0 };`
to
`        int menuStyle{ 1 };`
?

**Comment by CerberusGame** [comment]
> @CerberusGame
> ` int menuStyle{ 0 };`
> to
> ` int menuStyle{ 1 };`
> ?

I tried but it didn't work
