### ISSUE TITLE
Errors on Add imgui/imgui_impl_dx9.cpp

### ISSUE THREAD

**Issue by techprimedev** [danielkrupinski/Osiris#1698]
when i try to add #include "imgui/imgui_impl_dx9.cpp" in Gui.cpp i get several errors in my project, how do i solve?

**Comment by KernCS** [comment]
include imgui_impl_dx9.h insted

**Comment by techprimedev** [comment]
> include imgui_impl_dx9.h insted

imgui_impl_dx9.h don`t have g_pd3dDevice

**Comment by techprimedev** [comment]
g_pd3dDevice not defined, i need imgui_impl_dx9.cpp

**Comment by littlehurensohn** [comment]
dont use g_pd3dDevice **BUT** device

**Comment by techprimedev** [comment]
> dont use g_pd3dDevice **BUT** device

device is not defined

**Comment by littlehurensohn** [comment]
> > dont use g_pd3dDevice **BUT** device
> 
> device is not defined

weird
