### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by alpine971** [danielkrupinski/Osiris#170]
Hello, why was kittenzok’s pr denied and closed?, then you deleted his pr.

**Comment by danielkrupinski** [comment]
1. Rude PR title.
2. Vulgar commit description.

User proved via further errant commentary he didn't fully understand the code he was referring to. The PR is closed but not deleted.

**Comment by alpine971** [comment]
“Remove sus ass check for a site that causes you to BSOD” is a rude title?, ok, how about the actual code he posted, you did have malicious code running that checks the dns cache for cshacked.pl, i’m pretty sure participant knows what he’s talking about, if he didn’t he wouldn’t have found what you were doing in the first place.

**Comment by danielkrupinski** [comment]
> “Remove sus ass check for a site that causes you to BSOD” is a rude title?

Yes, it is.
For future bear in mind license notice:
```
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS ORIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THEAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHERLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THESOFTWARE.
```

**Comment by MrBisKit** [comment]
It looks like you just dodge the questions
