### ISSUE TITLE
skin changer doesn't work

### ISSUE THREAD

**Issue by mazmamad** [danielkrupinski/Osiris#1700]
skin changer its broken now... but only osiris source .. the other free cheat its fine

**Comment by littlehurensohn** [comment]
#1701

**Comment by psycho147** [comment]
Enabling cz75 or choosing karambit as a knife after last csgo update breaks the skin changer, aimware also has this issue so it's not an "only osiris" problem.

**Comment by aljawary** [comment]
wait till daniel update it kontol

**Comment by danielkrupinski** [comment]
Nope, it's working fine all the time.
