### ISSUE TITLE
[Request] Adding script support

### ISSUE THREAD

**Issue by abeznoskov** [danielkrupinski/Osiris#1702]
I use Osiris is my main cheat for 10 months and I really like it, but something is missing.
I think script support would make the cheat much better and the people who use the cheat, can code thier own scripts and publish them for everyone to use.

Sorry for my bad english.

**Comment by Consele64** [comment]
Osiris is open-source, people would add something they want anyway. Script would be useful if it wasn't open source tbh.

**Comment by DoomFishWasTaken** [comment]
Three reasons why this is not a good idea:
1. Osiris is open source anyone can download a version of the source and edit it, then publish it to Pull Requests.
2. Lua/JS degrades performance.
3. Annoying ass hell to implement, yes I have done it partially but it was so shitty that I didn't want to finish it.

**Comment by littlehurensohn** [comment]
Its easy to implement Lua. 

lua = thats what you need

**Comment by DoomFishWasTaken** [comment]
except why do people want lua, its literally open source?

**Comment by littlehurensohn** [comment]
> except why do people want lua, its literally open source?

Lua is open source, you can find on github osiris with lua implemented. 

@DoomFishWasTaken 

Btw: can u make the rainbow color on 2 colors? Like i previous wanted..

**Comment by TheFantasticLoki** [comment]
I think the main benefit is an easier learning curve to coding in LUA vs osiris.

**Comment by hastydev** [comment]
lua is easier to learn than c++ and it's easier to use

**Comment by 6ick** [comment]
I totaly agree that it is not that important to have lua support, but I do not know how to code cheats and dont know c++. And I want to add my own things learn how to code. I think many people can agree with me that scripting for a cheat is easier than modifing a cheat. And scripters can always use the latest version of osiris. (sry for bad english)

**Comment by 6ick** [comment]
And I think it would make it more comunnity driven and people could learn something than rather always asking to implement something.

**Comment by hyperxpro** [comment]
-1

**Comment by DoomFishWasTaken** [comment]
@AntonDoil
```
float fade(float step, float globaltime, float min, float max) 
{
    float colorVar = std::sin(globaltime * step);
    return std::clamp(colorVar, min, min);    
}
```
this should do :)
