### ISSUE TITLE
edge bug?

### ISSUE THREAD

**Issue by Zvondaaa** [danielkrupinski/Osiris#1705]

**Comment by littlehurensohn** [comment]
Code it your self, its easy.

**Comment by aljawary** [comment]
> Code it your self, its easy.

damn if i good at coding ill do my self man

**Comment by littlehurensohn** [comment]
![image](https://user-images.githubusercontent.com/44606865/83964235-d4209300-a8ab-11ea-996b-2006a1d9750a.png)

@aljawary

**Comment by littlehurensohn** [comment]
Tho is useful velocity indicator :)

**Comment by notgoodusename** [comment]
thats from another cheat

**Comment by KernCS** [comment]
> thats from another cheat

How do you know its not just Osiris?

**Comment by DoomFishWasTaken** [comment]
@KernCS checkboxes dont need XorStr() in osiris, binds are hotkey() or something like that not bind()

**Comment by KernCS** [comment]
> @KernCS checkboxes dont need XorStr() in osiris, binds are hotkey() or something like that not bind()

Maybe a remake of the keybinds? i did the same since i did not like the one that's in the source rn.
XorStr is simple to add so i don't really see a reason not just to add it, again i did exactly the same
