### ISSUE TITLE
quickstop?

### ISSUE THREAD

**Issue by jestemgosciem** [danielkrupinski/Osiris#1710]
someone has a quickstop code for osiris?

**Comment by dapaster** [comment]
use this #1587

**Comment by 3Ld4D** [comment]
```cpp
void Aimbot::autoStop(UserCmd* cmd) noexcept
{
    if (!localPlayer || !localPlayer->isAlive())
        return;

    if (!(localPlayer->flags() & FL_ONGROUND))
        return;

    Vector Velocity = localPlayer->velocity();

    if (Velocity.length2D() == 0)
        return;

    static float Speed = 450.f;

    Vector Direction;
    Vector RealView;
    math.VectorAngles(Velocity, Direction);
    g->engine->getViewAngles(RealView);
    Direction.y = RealView.y - Direction.y;

    Vector Forward;

    math.AngleVectors(Direction, &Forward);
    Vector NegativeDirection = Forward * -Speed;

    if (cmd->buttons & IN_FORWARD || cmd->buttons & IN_BACK)
        cmd->forwardmove = NegativeDirection.x;
    if (cmd->buttons & IN_MOVELEFT || cmd->buttons & IN_MOVERIGHT)
        cmd->sidemove = NegativeDirection.y;
}

**Comment by aljawary** [comment]
> ```c++
> void Aimbot::autoStop(UserCmd* cmd) noexcept
> {
>     if (!localPlayer || !localPlayer->isAlive())
>         return;
> 
>     if (!(localPlayer->flags() & FL_ONGROUND))
>         return;
> 
>     Vector Velocity = localPlayer->velocity();
> 
>     if (Velocity.length2D() == 0)
>         return;
> 
>     static float Speed = 450.f;
> 
>     Vector Direction;
>     Vector RealView;
>     math.VectorAngles(Velocity, Direction);
>     g->engine->getViewAngles(RealView);
>     Direction.y = RealView.y - Direction.y;
> 
>     Vector Forward;
> 
>     math.AngleVectors(Direction, &Forward);
>     Vector NegativeDirection = Forward * -Speed;
> 
>     if (cmd->buttons & IN_FORWARD || cmd->buttons & IN_BACK)
>         cmd->forwardmove = NegativeDirection.x;
>     if (cmd->buttons & IN_MOVELEFT || cmd->buttons & IN_MOVERIGHT)
>         cmd->sidemove = NegativeDirection.y;
> }
> ```

make a pull pls
