### ISSUE TITLE
Autostrafe move check

### ISSUE THREAD

**Issue by bruhmoment21** [danielkrupinski/Osiris#1711]
`if (cmd->buttons & (IN_FORWARD | IN_BACK | IN_MOVELEFT | IN_MOVERIGHT)) return;`

why not? checks if you are moving when autostrafing

**Comment by yaelahrip** [comment]
**yea simple check but dope**

**Comment by aljawary** [comment]
dont know man where should i paste this?

**Comment by bruhmoment21** [comment]
> dont know man where should i paste this?

```
void Misc::autoStrafe(UserCmd* cmd) noexcept
{
    if (cmd->buttons & (IN_FORWARD | IN_BACK | IN_MOVELEFT | IN_MOVERIGHT)) return;
    if (localPlayer
        && config->misc.autoStrafe
        && !(localPlayer->flags() & 1)
        && localPlayer->moveType() != MoveType::NOCLIP) {
        if (cmd->mousedx < 0)
            cmd->sidemove = -450.0f;
        else if (cmd->mousedx > 0)
            cmd->sidemove = 450.0f;
    }
}
```

**Comment by aljawary** [comment]
nice thx man

**Comment by cailloubr** [comment]
Make a pull, please!

**Comment by bruhmoment21** [comment]
> Make a pull, please!

hard. i don t know how

**Comment by cailloubr** [comment]
Allow me?

**Comment by bruhmoment21** [comment]
> Allow me?

sure create one

**Comment by littlehurensohn** [comment]
Still not good autostrafer, this is useless and u dont get 300 velocity on first jump. 

What i recommend is viewangles autostrafer.

**Comment by cailloubr** [comment]
This is a legit Autostafe.

Em seg., 8 de jun. de 2020 às 13:33, littlehurensohn <
notifications@github.com> escreveu:

**Comment by notgoodusename** [comment]
> Still not good autostrafer, this is useless and u dont get 300 velocity on first jump.
> 
> What i recommend is multidirectional viewangles autostrafer.

i have one is really fun.

**Comment by RealSmecks** [comment]
> > Still not good autostrafer, this is useless and u dont get 300 velocity on first jump.
> > What i recommend is multidirectional viewangles autostrafer.
> 
> i have one, is really fun.

Hey. I've been trying to make a multidirectional autostrafer for Osiris but can't seem to make one. If possible, could you give your autostrafe function code?
