### ISSUE TITLE
Player models from other maps

### ISSUE THREAD

**Issue by ocewot** [danielkrupinski/Osiris#1713]
is it possible to add the old terrorist playermodel from the map Cruise? I believe they are called pirate https://counterstrike.fandom.com/wiki/Pirate I like this playermodel because it has the gold watch also, is it possible to add the t side model for office? im suggesting this because there is the model changer for the new buyable models but i didnt see the old models and think it would be cool to have

**Comment by dapaster** [comment]
+1

**Comment by danielkrupinski** [comment]
Cool idea!

**Comment by danielkrupinski** [comment]
I've added one pirate model for testing (c68dfe3feb6bf116d7b2885bfa313265fa1a8101 & f48c764c6a8f745f3524111bf2fe8d511431603b).
