### ISSUE TITLE
Is it Redundant to VMProtect the VAC Bypass Loader? 

### ISSUE THREAD

**Issue by VuBrian22** [danielkrupinski/Osiris#1715]
I currently VMProtect the .dll itself. I'm just wondering if it's necessary to do the same with the loader. I also use Process Hacker 2 as an injector. I ask of this because of the recent VAC Bans many have been receiving. I'm a little hesitant to inject anything into the game and use the loader to launch Steam as of last week as well as this week. (FYI: None of my accounts have been banned yet.)

**Comment by Floraly** [comment]
Stop bullshitting around... VM Protect does nothing against signature scans! It just add an signature which is easier to detect for VAC and don't come up with junk code it does nothing against VAC!

**Comment by xXTOO-HARDXx** [comment]
Ok, well Floraly is very wrong, so don't mind him/her.

To answer OP's question(s), no, there isn't any point in VMProtecting VAC Bypass Loader. Yes, VMProtecting can *help* against signature scans in terms of a cheat itself, however, Steam itself isn't protected by any VAC Modules or anything similar, obviously; so the VAC Bypass is fine left alone.

It's probably worth mentioning; VAC Bypass is kind of redundant in of itself now a days, my PC has been flagged thanks to it and there is really no need to use it anyways so as long as you are taking the necessary precautions. Although, who gets flagged seems to be very... selective at times, and I am yet to figure out why.

gl, Jimmy.

**Comment by Consele64** [comment]
Well, don't cheat on accounts you don't want to get banned. (Like mains and such.)
Second of all, no need to VMP a dll or the bypass itself, you can just give it a go by itself.

**Comment by VuBrian22** [comment]
Alrighty, thanks for the Information!

**Comment by infinity1211** [comment]
> Ok, well Floraly is very wrong, so don't mind him/her.
> 
> To answer OP's question(s), no, there isn't any point in VMProtecting VAC Bypass Loader. Yes, VMProtecting can _help_ against signature scans in terms of a cheat itself, however, Steam itself isn't protected by any VAC Modules or anything similar, obviously; so the VAC Bypass is fine left alone.
> 
> It's probably worth mentioning; VAC Bypass is kind of redundant in of itself now a days, my PC has been flagged thanks to it and there is really no need to use it anyways so as long as you are taking the necessary precautions. Although, who gets flagged seems to be very... selective at times, and I am yet to figure out why.
> 
> gl, Jimmy.

what to do u mean by flagged?

**Comment by xXTOO-HARDXx** [comment]
> > Ok, well Floraly is very wrong, so don't mind him/her.
> > To answer OP's question(s), no, there isn't any point in VMProtecting VAC Bypass Loader. Yes, VMProtecting can _help_ against signature scans in terms of a cheat itself, however, Steam itself isn't protected by any VAC Modules or anything similar, obviously; so the VAC Bypass is fine left alone.
> > It's probably worth mentioning; VAC Bypass is kind of redundant in of itself now a days, my PC has been flagged thanks to it and there is really no need to use it anyways so as long as you are taking the necessary precautions. Although, who gets flagged seems to be very... selective at times, and I am yet to figure out why.
> > gl, Jimmy.
> 
> what to do u mean by flagged?

That's just what I was referencing as VAC flagging your PC as a 'cheater pc', once this happens, supposedly every account you use on that computer is put straight into red trust so that you verse other cheaters... However, this methodology isn't confirmed, but it isn't pure speculation either, it seems to be the case for some people. Valve works in strange ways . x(

**Comment by infinity1211** [comment]
> > > Ok, well Floraly is very wrong, so don't mind him/her.
> > > To answer OP's question(s), no, there isn't any point in VMProtecting VAC Bypass Loader. Yes, VMProtecting can _help_ against signature scans in terms of a cheat itself, however, Steam itself isn't protected by any VAC Modules or anything similar, obviously; so the VAC Bypass is fine left alone.
> > > It's probably worth mentioning; VAC Bypass is kind of redundant in of itself now a days, my PC has been flagged thanks to it and there is really no need to use it anyways so as long as you are taking the necessary precautions. Although, who gets flagged seems to be very... selective at times, and I am yet to figure out why.
> > > gl, Jimmy.
> > 
> > 
> > what to do u mean by flagged?
> 
> That's just what I was referencing as VAC flagging your PC as a 'cheater pc', once this happens, supposedly every account you use on that computer is put straight into red trust so that you verse other cheaters... However, this methodology isn't confirmed, but it isn't pure speculation either, it seems to be the case for some people. Valve works in strange ways . x(

i read about this unknowncheats forum...it tells that vac only affects the account you are getting detected with, but still no one knows how it works..
1.https://www.unknowncheats.me/forum/counterstrike-global-offensive/143570-vac-flagging.html
2.https://www.unknowncheats.me/forum/counterstrike-global-offensive/139652-vac-flagged.html

**Comment by xXTOO-HARDXx** [comment]
> > > > Ok, well Floraly is very wrong, so don't mind him/her.
> > > > To answer OP's question(s), no, there isn't any point in VMProtecting VAC Bypass Loader. Yes, VMProtecting can _help_ against signature scans in terms of a cheat itself, however, Steam itself isn't protected by any VAC Modules or anything similar, obviously; so the VAC Bypass is fine left alone.
> > > > It's probably worth mentioning; VAC Bypass is kind of redundant in of itself now a days, my PC has been flagged thanks to it and there is really no need to use it anyways so as long as you are taking the necessary precautions. Although, who gets flagged seems to be very... selective at times, and I am yet to figure out why.
> > > > gl, Jimmy.
> > > 
> > > 
> > > what to do u mean by flagged?
> > 
> > 
> > That's just what I was referencing as VAC flagging your PC as a 'cheater pc', once this happens, supposedly every account you use on that computer is put straight into red trust so that you verse other cheaters... However, this methodology isn't confirmed, but it isn't pure speculation either, it seems to be the case for some people. Valve works in strange ways . x(
> 
> i read about this unknowncheats forum...it tells that vac only affects the account you are getting detected with, but still no one knows how it works..
> 1.https://www.unknowncheats.me/forum/counterstrike-global-offensive/143570-vac-flagging.html
> 2.https://www.unknowncheats.me/forum/counterstrike-global-offensive/139652-vac-flagged.html

Yes, this is good insight, we don't know how it works, but from what I've seen I've made up a likely scenario and stuck to it because it's safer to than not to. :)

**Comment by 0xE232FE** [comment]
Okay believe what you want. ;-) I just say what I know and he says what he googled on Unknowncheats...

**Comment by xXTOO-HARDXx** [comment]
> Okay believe what you want. ;-) I just say what I know and he says what he googled on Unknowncheats...

This is fair enough. :)
