### ISSUE TITLE
Question: Autoload saved custom CFG

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#1717]
Question
I have a CFG called **LEGIT**
I would like that every time I load osiris, avoid the step of going to the config tab, select the CFG LEGIT and press LOAD

Is there a line of code to add that can simplify this action?

Thanks

**Comment by KernCS** [comment]
#1616

**Comment by TauCSGO** [comment]
> #1616

I don't understand exactly how to write the line

**Comment by KernCS** [comment]
> > #1616
> 
> I don't understand exactly how to write the line

My bad under
 `void Hooks::install() noexcept`
paste in the buttom
`config->load(0);`

**Comment by TauCSGO** [comment]
> > > #1616
> > 
> > 
> > I don't understand exactly how to write the line
> 
> My bad under
> `void Hooks::install() noexcept`
> paste in the buttom
> `config->load(0);`

Thanks, it worked well for me
That option makes it load the CFG first, in alphabetical order

I'm going to bother you with one more question
In case of having several CFGs, example

AIM
LEGIT
WALL

With that line the CFG called AIM would load
If I wanted the CFG called LEGIT to load, can you add any lines?

**Comment by KernCS** [comment]
> > > > #1616
> > > 
> > > 
> > > I don't understand exactly how to write the line
> > 
> > 
> > My bad under
> > `void Hooks::install() noexcept`
> > paste in the buttom
> > `config->load(0);`
> 
> Thanks, it worked well for me
> That option makes it load the CFG first, in alphabetical order
> 
> I'm going to bother you with one more question
> In case of having several CFGs, example
> 
> AIM
> LEGIT
> WALL
> 
> With that line the CFG called AIM would load
> If I wanted the CFG called LEGIT to load, can you add any lines?

my best suggestion would be just to rename your "legit" to "1 legit"

**Comment by TauCSGO** [comment]
> > > > > #1616
> > > > 
> > > > 
> > > > I don't understand exactly how to write the line
> > > 
> > > 
> > > My bad under
> > > `void Hooks::install() noexcept`
> > > paste in the buttom
> > > `config->load(0);`
> > 
> > 
> > Thanks, it worked well for me
> > That option makes it load the CFG first, in alphabetical order
> > I'm going to bother you with one more question
> > In case of having several CFGs, example
> > AIM
> > LEGIT
> > WALL
> > With that line the CFG called AIM would load
> > If I wanted the CFG called LEGIT to load, can you add any lines?
> 
> my best suggestion would be just to rename your "legit" to "1 legit"

Thank you!

**Comment by TauCSGO** [comment]
This stopped working after today's Osiris update.

( Severity Code Description Project File Line Suppression State
Error C2660 'Config::load': function does not take 1 arguments Osiris Hooks.cpp 579

**Comment by TauCSGO** [comment]
Hi @KernCS 
This stopped working after today's Osiris update.

( Severity Code Description Project File Line Suppression State
Error C2660 'Config::load': function does not take 1 arguments Osiris Hooks.cpp 579

you know how to fix it?
