### ISSUE TITLE
[Bug] cheat tries to rcs with usp

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1718]
Cheat tries to rcs with usp and it messes up my aimbot

**Comment by xXTOO-HARDXx** [comment]
Add a check for the ID of the weapon you're holding in the RCS code, duhhh.

And USP does have recoil? so how is it messing up your aimbot? That doesn't make any sense lol

**Comment by HowToMakeFaceitAB** [comment]
> Add a check for the ID of the weapon you're holding in the RCS code, duhhh.
> 
> And USP does have recoil? so how is it messing up your aimbot? That doesn't make any sense lol

It does make sense but you don't have a brain, the usp has recoil when its fired automatically, Nobody fires the usp automatically, first shot always misses

**Comment by xXTOO-HARDXx** [comment]
> > Add a check for the ID of the weapon you're holding in the RCS code, duhhh.
> > And USP does have recoil? so how is it messing up your aimbot? That doesn't make any sense lol
> 
> It does make sense but you don't have a brain, the usp has recoil when its fired automatically, Nobody fires the usp automatically, first shot always misses

what are you trying here?.. you ask for help that I'm willing to give, and then you attempt to correct me? Which you didn't by the way.. hmm. I know the answer to your issue. But don't be an asshole about it. Thanks X)

**Comment by HowToMakeFaceitAB** [comment]
Mmh
