### ISSUE TITLE
After using osiris I can no longer shutdown my pc 

### ISSUE THREAD

**Issue by Robby-Sodhi** [danielkrupinski/Osiris#1720]
it always happens after using osiris for a while locking shutting down etc break on my pc

**Comment by mazmamad** [comment]
well force shutdown lmao , or just close all running program before shutdown

**Comment by aljawary** [comment]
u have potato pc, should buy a new good one

**Comment by adampala123** [comment]
This actually happens to me too. Not like I have a potato PC. It's not a big deal tho.

**Comment by Robstersgaming** [comment]
> This actually happens to me too. Not like I have a potato PC. It's not a big deal tho.

Do you use process hacker to inject? I believe that is the issue not 100% sure

**Comment by cailloubr** [comment]
> > This actually happens to me too. Not like I have a potato PC. It's not a big deal tho.
> 
> Do you use process hacker to inject? I believe that is the issue not 100% sure

i've tested, process hacker not cause this.
