### ISSUE TITLE
Detected

### ISSUE THREAD

**Issue by xavier124** [danielkrupinski/Osiris#1721]
I pasted osiris, removed tons of features and vmprotected with virtualization+mutation, and I got overwatched on the 7th of june and vac'd on the 9th. Is osiris detected or is valve tricking us and masking overwatches as vac? (edit: injector used was randoinjector with asm emit bytes)

**Comment by infinity1211** [comment]
no, you are just blatant hacking. i ve been using it for 2 months... still no vac or ow ban, i am using vac bypass loader and xenos injector

**Comment by infinity1211** [comment]
and ya overwatch ban turns into vac ban in a fewday because of vacnet

**Comment by xavier124** [comment]
vac bypass still works?

**Comment by infinity1211** [comment]
i guess it does...have to test it with detected cheat

**Comment by Btibor12** [comment]
Yea, I got banned too today. No notification about overwatch, just vac. I didn't use vac-bypass or anything like that so I think that's the case. My friend's account suprisingly hasn't got banned, but we used the same settings. I only used skinchanger.

**Comment by aljawary** [comment]
yesterday i try to test this cheat, play blatant, after 4 match i got ow ban but on the next day it turn to vac ban

**Comment by infinity1211** [comment]
@Btibor12  you probably used a detected injector and he didnt
@aljawary ow bans turns into vac ban in a few minutes/hours/days. if it gives only vac either ur dll is detected or ur injector is

**Comment by Btibor12** [comment]
@infinity1211 We used the same injector (Process Hacker)

**Comment by realstyla23** [comment]
> yesterday i try to test this cheat, play blatant, after 4 match i got ow ban but on the next day it turn to vac ban

OW ban turns into VAC most of the time

**Comment by steel4me** [comment]
Really funny, 3 month later and see what happened, nobody believed me, even now, everyone deny it. Anyone who is interested should read these closed issues below.

It is really simple, stop using osiris till it get fixed.
I wasted over 5 accounts with osisris and got vac, my osiris clone was highly modificated.
I use my own injector over 15 years now, never got vac.

Im still using my injector over 3 month now. No vac, no ban, nothing. Just other dll, no osiris anymore ;)

#1246
#1238
#1251
#1268
#1306

**Comment by techzin** [comment]
Close this issue, hook is not detected.
