### ISSUE TITLE
[SUGGESTION] SIR, CAN YOU PLEASE ADD BULLET TRACE ?

### ISSUE THREAD

**Issue by king1919djdj** [danielkrupinski/Osiris#1723]
I have a suggestion
sir , can you add bullet traces to the software ?
if there already are bullet traces please tell me how to enable them ?

**Comment by AntonDoil** [comment]
Find some source what actually have bullet beams. 
Paste it into osiris.

Its easy, dont need event listener, what you need (if you dont have event lister) 

if (!strcmp(event->getName(), "bullet_impact")) 
{
//Draw bullet
}

Profitable!

**Comment by AntonDoil** [comment]
Tho like that can make derank bot, and more useful features. 
I have base what is old (6 months old osiris) 
And it works perfect till now.

**Comment by king1919djdj** [comment]
THANKS m8 
i really wanted this feature
i will try it out

**Comment by king1919djdj** [comment]
I had a doubt will it draw the whole trace or impacts ?

**Comment by king1919djdj** [comment]
> Find some source what actually have bullet beams.
> Paste it into osiris.
> 
> Its easy, dont need event listener, what you need (if you dont have event lister)
> 
> if (!strcmp(event->getName(), "bullet_impact"))
> {
> //Draw bullet
> }
> 
> Profitable!

can u suggest some source with bullet beams ?
I am unable to locate even a single one ?

**Comment by AntonDoil** [comment]
> > Find some source what actually have bullet beams.
> > Paste it into osiris.
> > Its easy, dont need event listener, what you need (if you dont have event lister)
> > if (!strcmp(event->getName(), "bullet_impact"))
> > {
> > //Draw bullet
> > }
> > Profitable!
> 
> can u suggest some source with bullet beams ?
> I am unable to locate even a single one ?

I can link some source. 

https://github.com/ben93riggs/CSGO_Internal/blob/719b94b7eba6bb38d06eff85d5295cb462dec23f/CSGO_Internal/BulletTracer.cpp

There u go buddy

**Comment by king1919djdj** [comment]
THANK YOU SO MUCH
