### ISSUE TITLE
custom skybox

### ISSUE THREAD

**Issue by jestemgosciem** [danielkrupinski/Osiris#1724]
![skyboxx](https://user-images.githubusercontent.com/64129769/84183609-75663f80-aa8c-11ea-9700-22897e0118fc.png)
can someone send me a code for this?

**Comment by cailloubr** [comment]
https://github.com/danielkrupinski/Osiris/blob/f48c764c6a8f745f3524111bf2fe8d511431603b/Osiris/Hacks/Visuals.cpp#L368

**Comment by aljawary** [comment]
its already there

**Comment by xXTOO-HARDXx** [comment]
@cailloubr @aljawary ...
The OP clearly wants to add their own 'Custom Skybox' addition, which is NOT in Osiris.

And, to @jestemgosciem that's not a hard task. But I think it might leave you untrusted, I am not sure.

All you have to do is put your Skybox materials in the CSGO skybox folder (should already exist, if Valve still use it) and then add the name and ID of your custom Skybox file into the Osiris Skybox arrays, and lastly, add the item(s) into the GUI Combo for Skyboxes :)

**Comment by cailloubr** [comment]
#1731

**Comment by xXTOO-HARDXx** [comment]
Cailloubr has basically done what I suggested and done the work for you, @jestemgosciem 

Please close this thread, thanks.
