### ISSUE TITLE
[Question] Addressing the "Hooking Issue"

### ISSUE THREAD

**Issue by xXTOO-HARDXx** [danielkrupinski/Osiris#1726]
### Hi,

For Daniel personally, I was curious; are you going to address the supposed "detected hooking" and recode the hooking class? 

Or, because the cheat is still deemed 'operable', will you just continue to stick with optimising and adding features over time, letting others figure out their own way of making it undetected.. you know.. considering it's an open source project, and your intentions might not be to provide an undetected public cheat to everyone, of course.

Thanks, Jimmy.

**P.S. if you aren't Daniel, _and_ aren't willing to actually contribute to this 'issue', do yourself a favour and kindly fuck off, there's too many people in this repository making false claims all the time, does my head in... x(**

**Comment by barbadully** [comment]
just some more info on this, first account got game banned, a day or two later it turned into a vac. I had my doubts because the last game I played on that account I held spacebar the entire match but didn't kill anyone. now I woke up and saw that my new account got game banned aswell, will update if it turns into vac aswell... not sure what's causing it too but people automatically go for the hooks

**Comment by xXTOO-HARDXx** [comment]
> just some more info on this, first account got game banned, a day or two later it turned into a vac. I had my doubts because the last game I played on that account I held spacebar the entire match but didn't kill anyone. now I woke up and saw that my new account got game banned aswell, will update if it turns into vac aswell... not sure what's causing it too but people automatically go for the hooks

yeahhhhhhhhhhh, I don't understand people's automatic assumption that it 'must be the hooks', when there's no evidence of it, lolol

also, thanks for the input.

**Comment by realstyla23** [comment]
It is 100% not the hooking...

I've been using Osiris since 2 months on 3 accounts.. 
1 non prime for rage 
1 smurf legit 
1 main account legit

I dont even have low trust factor or anything.. 

Used daniels injector and only did some tweaks to Osiris and Injector..


No OW, no VAC or anything..

**Comment by xXTOO-HARDXx** [comment]
> It is 100% not the hooking...
> 
> I've been using Osiris since 2 months on 3 accounts..
> 1 non prime for rage
> 1 smurf legit
> 1 main account legit
> 
> I dont even have low trust factor or anything..
> 
> Used daniels injector and only did some tweaks to Osiris and Injector..
> 
> No OW, no VAC or anything..

Well, this throws a spanner in the works... xD

Keep in mind VAC Bans can be delayed for weeks at a time, rarely of course.

**Comment by realstyla23** [comment]
i think it has smth to do with some features or the bypass loader. or maybe some old version ppl used.. tho someone posted that he used the newest version and got vacced.. trying that now too

**Comment by AntonDoil** [comment]
> > i'll try to make a pull request with minhook this month or july can't do right now because of exams.
> 
> This is an interesting idea.. and would be much appreciated of course. 
> 
> Implementing Minhook to replace VMT Hooking could 100% confirm whether it is the hooking that is in fact, detected.

Dont know if is it true, but i heard minhook is detected. 
I can share source for minhook if you want.

**Comment by xXTOO-HARDXx** [comment]
> > > i'll try to make a pull request with minhook this month or july can't do right now because of exams.
> > 
> > 
> > This is an interesting idea.. and would be much appreciated of course.
> > Implementing Minhook to replace VMT Hooking could 100% confirm whether it is the hooking that is in fact, detected.
> 
> Dont know if is it true, but i heard minhook is detected.
> I can share source for minhook if you want.

Well, not necessarily.. I always veered away from Minhook because it can be sigged, unlike VMT Hooking, but I don't think it'll be detected so as long as you change the signature a bit. I'm not sure, I've never used it.

**Comment by AntonDoil** [comment]
> > > > i'll try to make a pull request with minhook this month or july can't do right now because of exams.
> > > 
> > > 
> > > This is an interesting idea.. and would be much appreciated of course.
> > > Implementing Minhook to replace VMT Hooking could 100% confirm whether it is the hooking that is in fact, detected.
> > 
> > 
> > Dont know if is it true, but i heard minhook is detected.
> > I can share source for minhook if you want.
> 
> Well, not necessarily.. I always veered away from Minhook because it can be sigged, unlike VMT Hooking, but I don't think it'll be detected so as long as you change the signature a bit. I'm not sure, I've never used it.

Honestly, i tried to change the signature and i still get vacced. 
Thats mean, there can be detected hooking or smth other.

**Comment by xXTOO-HARDXx** [comment]
> > > > > i'll try to make a pull request with minhook this month or july can't do right now because of exams.
> > > > 
> > > > 
> > > > This is an interesting idea.. and would be much appreciated of course.
> > > > Implementing Minhook to replace VMT Hooking could 100% confirm whether it is the hooking that is in fact, detected.
> > > 
> > > 
> > > Dont know if is it true, but i heard minhook is detected.
> > > I can share source for minhook if you want.
> > 
> > 
> > Well, not necessarily.. I always veered away from Minhook because it can be sigged, unlike VMT Hooking, but I don't think it'll be detected so as long as you change the signature a bit. I'm not sure, I've never used it.
> 
> Honestly, i tried to change the signature and i still get vacced.
> Thats mean, there can be detected hooking or smth other.

Well that's the problem, we don't know what is xd.

If Daniel finished the reversed VAC modules then we could know what's causing the detections by maybe hooking some stuff, monitoring some return addresses, something of the sort.

**Comment by steel4me** [comment]
hello @xXTOO-HARDXx  i think you should know me from other issues now ;)

i told my story and i hope you remeber. i used highly modificated osiris since 04/2019 so i played over 8 month's without vac bypass and my own injector. please stop claiming that my injector is shit. when i read this one more time i will kill someone. 

first detections happened to me in 02/2020, delayed bans of 5 accounts happened differntly. some account one week later, some accounts +12 weeks later.

Maybe it is or was the VMT hooking, i see in commit history that daniel implemented minhook. but there is something I doubt. VMT hooking was detected somewhere in 2017 / 2018. cant remember exactly. many internals got detected. so if it was the hooking method, why should someone be able to use osiris without ban and without vac bypass? it should instantly ban everyone. so. how the hack i was able to play 8 month without any detection, low trust or banflag? 

somewhere in mid of feb 02, daniel added enginge prediction, maybe that's a trace

**Comment by danielkrupinski** [comment]
Now we have 3 hooking methods so you can easily switch from one to another if you have any detection doubts.
