### ISSUE TITLE
skinchenger not working

### ISSUE THREAD

**Issue by naphz4** [danielkrupinski/Osiris#1728]
skinchanger not working only knife changer works

**Comment by mazmamad** [comment]
bro i got some fix after disable cz and not use karambit... but.... when i use another cheat boom! karambit and cz its 100% fine :)

**Comment by TheNulledJester** [comment]
> bro i got some fix after disable cz and not use karambit... but.... when i use another cheat boom! karambit and cz its 100% fine :)

Did you delete cz skin from the cheat or just swap the cz with the five-seven/tec9?
