### ISSUE TITLE
W,A,S,D Autostrafe

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#1730]
anyone have this ?

**Comment by notgoodusename** [comment]
pasta for u :3
static float AutoStrafeAngle = 0.f;
void Misc::autoStrafe(UserCmd* cmd, const Vector& currentViewAngles) noexcept
{
    static float ang = 0.f;
    static float direction = 0.f;
    if (!config->misc.autoStrafe)
    {
        ang = 0.f;
        direction = 0.f;
        AutoStrafeAngle = 0.f;
        return;
    }
    if (!localPlayer || !localPlayer->isAlive())
        return;
    if (localPlayer->velocity().length2D() < 10.f)
    {
        ang = 0.f;
        direction = 0.f;
        AutoStrafeAngle = 0.f;
        return;
    }
    const auto activeWeapon = localPlayer->getActiveWeapon();
    if (localPlayer->throwing(cmd))
        return;
    if (!activeWeapon)
        return;
    if (cmd->buttons & (UserCmd::IN_USE))
        return;
    if ((cmd->buttons & (UserCmd::IN_ATTACK) || (activeWeapon->isKnife() && cmd->buttons & (UserCmd::IN_ATTACK2))) && activeWeapon->nextPrimaryAttack() <= memory->globalVars->serverTime())
        return;
    if (localPlayer->moveType() == MoveType::NOCLIP || localPlayer->moveType() == MoveType::LADDER || (!(cmd->buttons & UserCmd::IN_JUMP)))
    {
        if (cmd->buttons & UserCmd::IN_FORWARD)
        {
            ang = 0.f;
        }
        if (cmd->buttons & UserCmd::IN_MOVELEFT)
        {
            ang = 90.f;
        }
        if (cmd->buttons & UserCmd::IN_MOVERIGHT)
        {
            ang = -90.f;
        }
        if (cmd->buttons & UserCmd::IN_BACK)
        {
            ang = 180.f;
        }
        direction = ang;
        AutoStrafeAngle = 0.f;
        return;
    }
    if (cmd->buttons & (UserCmd::IN_ATTACK | UserCmd::IN_USE))
        return;
    Vector base;
    interfaces->engine->getViewAngles(base);


    float delta = min(radiansToDegrees(std::asinf(30.f / localPlayer->velocity().length2D())) * 0.5f, 45.f);

    static bool flip = true;
    if (cmd->buttons & (UserCmd::IN_FORWARD | UserCmd::IN_MOVELEFT | UserCmd::IN_MOVERIGHT | UserCmd::IN_BACK))
    {
        cmd->forwardmove = 0;
        cmd->sidemove = 0;
        cmd->upmove = 0;
    }
    ang = 0.f;
    if (cmd->buttons & UserCmd::IN_FORWARD)
    {
        ang = 0.f;
        if (cmd->buttons & UserCmd::IN_MOVELEFT)
        {
            ang = 45.f;
        }
        else if (cmd->buttons & UserCmd::IN_MOVERIGHT)
        {
            ang = -45.f;
        }
    }
    if (!(cmd->buttons & (UserCmd::IN_FORWARD | UserCmd::IN_BACK)))
    {
        if (cmd->buttons & UserCmd::IN_MOVELEFT)
        {
            ang = 90.f;
        }
        if (cmd->buttons & UserCmd::IN_MOVERIGHT)
        {
            ang = -90.f;
        }
    }
    if (cmd->buttons & UserCmd::IN_BACK)
    {
        ang = 180.f;
        if (cmd->buttons & UserCmd::IN_MOVELEFT)
        {
            ang = 135.f;
        }
        else if (cmd->buttons & UserCmd::IN_MOVERIGHT)
        {
            ang = -135.f;
        }
    }
    if (std::abs(direction - ang) < 180)
    {
        if (direction < ang)
        {
            direction += delta;
        }
        else
        {
            direction -= delta;
        }
    }
    else {
        if (direction < ang)
        {
            direction -= delta;
        }
        else
        {
            direction += delta;
        }
    }
    direction = std::isfinite(direction) ? std::remainder(direction, 360.0f) : 0.0f;
    if (cmd->mousedx < 0)
    {
        cmd->sidemove = -450.0f;
    }
    else if (cmd->mousedx > 0)
    {
        cmd->sidemove = 450.0f;
    }
    flip ? base.y += direction + delta : base.y += direction - delta;
    flip ? AutoStrafeAngle = direction + delta : AutoStrafeAngle = direction - delta;
    if (cmd->viewangles.y == currentViewAngles.y)
    {
        cmd->viewangles.y = base.y;
    }
    flip ? cmd->sidemove = 450.f : cmd->sidemove = -450.f;
    flip = !flip;
}

float Misc::getAutostrafeAngle() noexcept
{
    return AutoStrafeAngle;
}

**Comment by notgoodusename** [comment]
on antiaim do cmd->viewangles.y -=  Misc::getAutostrafeAngle();

**Comment by dapaster** [comment]
Thank you!
