### ISSUE TITLE
directonal bhop ?

### ISSUE THREAD

**Issue by king1919djdj** [danielkrupinski/Osiris#1734]
is directional bhop present in the cheat ?
+(i am a noob at bhopping)
sorry for asking a noobish question

**Comment by adampala123** [comment]
If you mean autostrafer, then yes.

**Comment by notgoodusename** [comment]
> is directional bhop present in the cheat ?
> +(i am a noob at bhopping)
> sorry for asking a noobish question

no there isnt, there is only a legit one

**Comment by king1919djdj** [comment]
ok,
thanks  
any non colliding source code for directonal bhop ?
[if present]
