### ISSUE TITLE
Today I woke up and I can't compile the cheat anymore...

### ISSUE THREAD

**Issue by barbadully** [danielkrupinski/Osiris#1735]
I even tried to download the fresh source and compile it and it just doesn't let me...
![image](https://user-images.githubusercontent.com/60882933/84381733-c0499980-abe9-11ea-86d6-1c40f1b7abf0.png)

**Comment by barbadully** [comment]
I have like a billion errors and it only said that it failed to locate CL.exe

**Comment by dapaster** [comment]
Try reinstall Visual Studio

**Comment by barbadully** [comment]
> Try reinstall Visual Studio

I did and it still doesn't work x)

**Comment by Floraly** [comment]
When I wake up the first thing is to make me a pot of coffee... And then start to code ;-)

**Comment by hyperxpro** [comment]
Go to sleep again.

**Comment by cailloubr** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/60858720/84604852-53dfcc00-ae6f-11ea-9689-1a3a9393205d.png)
