### ISSUE TITLE
FYI: CSGO new UPDATE and CRASH

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#1738]
CSGO new UPDATE and CRASH when it is injected

Release Notes for 6/11/2020
2020.06.11 - 

[MISC]
– Added a new game communication setting “Text Filtering” which is enabled by default and blocks profane words used in text chat.
– Fixed a trigger_bomb_reset regression.

**Comment by techzin** [comment]
Same, Crash when game start

**Comment by techzin** [comment]
Failed to Find VClient018 Interface.

**Comment by techzin** [comment]
Remove Misc::purchaseList from Hook and EventListener to solve temporary.

**Comment by TauCSGO** [comment]
> Remove Misc::purchaseList from Hook and EventListener to solve temporary.

it has not worked for me :(

**Comment by real-Shigure** [comment]
Same, the game crashed when i choose CT/T.

**Comment by techzin** [comment]
> > Remove Misc::purchaseList from Hook and EventListener to solve temporary.
> 
> it has not worked for me :(

Go to Entity.h in IsOtherEnemy contente, remove actual Returno and add return false;

**Comment by likeman66** [comment]
> > > Remove Misc::purchaseList from Hook and EventListener to solve temporary.
> > 
> > 
> > it has not worked for me :(
> 
> Go to Entity.h in IsOtherEnemy content, remove actual return and add return false;

hi, I'm completely a noob which I can't actually understand about ur solution. but is it possible for u to upload a fixed dll？Appriciate it

**Comment by techzin** [comment]
> > > > Remove Misc::purchaseList from Hook and EventListener to solve temporary.
> > > 
> > > 
> > > it has not worked for me :(
> > 
> > 
> > Go to Entity.h in IsOtherEnemy content, remove actual return and add return false;
> 
> hi, I'm completely a noob which I can't actually understand about ur solution. but is it possible for u to upload a fixed dll？Appriciate it

I'm now Using Mobile +-+

This Modification Only Solve Crashs, The Aimbot and Wallhack don't work because Local player not defined.

**Comment by real-Shigure** [comment]
I removed all calls related to "isOtherEnemy", Osiris can inject and run successfully, but the functions related to this are not working properly. (So this is just a temporary solution)

**Comment by techzin** [comment]
> I removed all calls related to "isOtherEnemy", Osiris can inject and run successfully, but the functions related to this are not working properly. (So this is just a temporary solution)

Yes, Temporary Solution, Tou need to Update Índex and Signatures, @danielkrupinski will update soon.

**Comment by danielkrupinski** [comment]
Should be fixed.
