### ISSUE TITLE
I tried removing reportbot and got these errors

### ISSUE THREAD

**Issue by cryptdrive** [danielkrupinski/Osiris#1739]
So i removed reportbot and got these errors . I can't fix it , i got the same errors when i removed triggerbot .

![vserror](https://user-images.githubusercontent.com/66123787/84480097-a5daf300-acb1-11ea-9601-04334a35070f.png)

I'm using the latest vs studio with latest windows sdk .

**Comment by 0xE232FE** [comment]
Things are dependable from each other. So you need to remove all dependencies too.

**Comment by cryptdrive** [comment]
> Things are dependable from each other. So you need to remove all dependencies too.

I did remove everything related to reportbot and didnt touch anything else . I don't know why am i getting this same error for every feature i remove . Is everything connected to aimbot ?

**Comment by danielkrupinski** [comment]
The error says precisely: **lines 288 and 61 in Config.h**.

**Comment by cryptdrive** [comment]
![61](https://user-images.githubusercontent.com/66123787/84483191-9c07be80-acb6-11ea-9e05-f4301ea5e387.png)
![288](https://user-images.githubusercontent.com/66123787/84483196-9dd18200-acb6-11ea-8ad0-1536725d0eb2.png)
whats wrong :o ?

**Comment by cryptdrive** [comment]
Nvm , i had to remove 283-293 and it got fixed .
