### ISSUE TITLE
New menu style?

### ISSUE THREAD

**Issue by cojo1989** [danielkrupinski/Osiris#174]
Hello Daniel, **just a suggestion**. 
You should do menu on left side of the screen, change that gray to black, make text color red, if you put it on left side make it bigger, make 
**-RCS only 1 bar not X and Y**
**-Add RCS Standalone** 
-Make the buttons when you click them to change only 1 window not to appear other one over and over. 

Dont understand me wrong i fucking appreciate your work, i love the cheat but i would like to see something new. I got enough designs about Aimtux and stuff like that. I would love to help you with some good ideeas.

**Comment by HighPolyLuna** [comment]
You can easily do this yourself. ImGui is very easy to learn.

**Comment by effex1337** [comment]
If you want you could steal my menu it's on my github got an older version. 
100--not-osiris i think

**Comment by cojo1989** [comment]
@effex1337 do you have any screenshots? Thank you buddy.

**Comment by effex1337** [comment]
A Bit smater's(mutiny) menu with a different color scheme

**Comment by cojo1989** [comment]
@effex1337 can you make a tutorial how to make it? If i don’t ask to much buddy. Thank you very much.

**Comment by effex1337** [comment]
Umm you just gotta compile and the dll is there with the menu
I'll update it later when i have the mood for it

**Comment by effex1337** [comment]
Would take around 5-10 mins to update it
