### ISSUE TITLE
wallhack key

### ISSUE THREAD

**Issue by HackerGeo-sp1ne** [danielkrupinski/Osiris#1740]
add wallhack on key

**Comment by zajkos** [comment]
esp.cpp 
`if (config->espJson.onKey) {
    if (!config->espJson.keyMode) {
        if (!GetAsyncKeyState(config->espJson.key))
            return;
    }
    else {
        static bool toggle = true;
        if (GetAsyncKeyState(config->espJson.key) & 1)
            toggle = !toggle;
        if (!toggle)
            return;
    }
}`

**Comment by zajkos** [comment]
Config.cpp
if (espJson.isMember("On key")) espConfig.onKey = espJson["On key"].asBool();
if (espJson.isMember("Key")) espConfig.key = espJson["Key"].asInt();
espJson["Key"] = espConfig.key;

**Comment by zajkos** [comment]
Config.h
int key{ 0 };

**Comment by zajkos** [comment]
GUI.cpp
hotkey(config.espJson.key);

ImGui::Combo("Mode :", &config.espJson.keyMode, "Hold\0Toggle\0");

**Comment by zajkos** [comment]
I do not know much about c ++ so do not judge this code too critically, in addition, I wrote it spontaneously and in less than 5 minutes something to fix will definitely be found but I think I more or less did what it should look like

**Comment by zajkos** [comment]
of course, everything should be in the right places and not just anywhere

**Comment by zajkos** [comment]
and of course this is only for esp not for chams and glow, but more or less it should look like in esp

Sorry for my English

**Comment by HackerGeo-sp1ne** [comment]
you have discord? i need you, i pay you, how to contact you?

**Comment by zajkos** [comment]
zajkos#1320

**Comment by danielkrupinski** [comment]
Added
