### ISSUE TITLE
anti aim

### ISSUE THREAD

**Issue by jestemgosciem** [danielkrupinski/Osiris#1743]
when my revolver loads my anti aim does not work, I want my anti aim to work when the revolver loads, help

**Comment by dapaster** [comment]
**Hooks.cpp**

https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hooks.cpp#L132

Remove the `Misc::prepareRevolver(cmd);`

And move to here

    if (!(cmd->buttons & (UserCmd::IN_ATTACK | UserCmd::IN_ATTACK2))) {
        Misc::chokePackets(sendPacket);
        AntiAim::run(cmd, previousViewAngles, currentViewAngles, sendPacket);
        Misc::prepareRevolver(cmd);
    }

**Comment by 3Ld4D** [comment]
> **Hooks.cpp**
> 
> https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hooks.cpp#L132
> 
> Remove the `Misc::prepareRevolver(cmd);`
> 
> And move to here
> 
> ```
> if (!(cmd->buttons & (UserCmd::IN_ATTACK | UserCmd::IN_ATTACK2))) {
>     Misc::chokePackets(sendPacket);
>     AntiAim::run(cmd, previousViewAngles, currentViewAngles, sendPacket);
>     Misc::prepareRevolver(cmd);
> }
> ```

that won't work, u need revolver fix.
```cpp
if (weapon->IsRevolver())
{
    if (cmd->buttons & IN_ATTACK2)
        return;

    if (weapon->CanFirePostpone() && (cmd->buttons & IN_ATTACK))
	return;
}

**Comment by jestemgosciem** [comment]
where put this code?
