### ISSUE TITLE
[Help] Crash after "merging" two pull requests

### ISSUE THREAD

**Issue by ekstazas** [danielkrupinski/Osiris#1744]
Okay, so I downloaded @DoomFishWasTaken 's #1546 reworked anti-aim and etc. pull request and tried adding in @dapaster 's #1716 aimbot hitchance.

Everything compiled, injected into the game normally, menu opens, but after loading into a match/workshop map/server/against bots, CSGO just crashes without any error or pop-up.

Any help is appreciated.

**Comment by jannikahoi** [comment]
https://github.com/danielkrupinski/Osiris/commit/a0e90938c10ddd32723def1566d204ecda6fb084
