### ISSUE TITLE
My game has been crashing when joining a map after the newest update of csgo

### ISSUE THREAD

**Issue by SakariTaanila** [danielkrupinski/Osiris#1746]
Immediately when i join a map my game crashes.

**Comment by gustavogino** [comment]
New pattern in IsOtherEnemy

**Comment by SakariTaanila** [comment]
> New pattern in IsOtherEnemy

Okay, how should I go about fixing this? Thanks!

**Comment by gustavogino** [comment]
Change old pattern to new pattern
https://github.com/danielkrupinski/Osiris/commit/a0e90938c10ddd32723def1566d204ecda6fb084

**Comment by SakariTaanila** [comment]
> Change old pattern to new pattern
> [a0e9093](https://github.com/danielkrupinski/Osiris/commit/a0e90938c10ddd32723def1566d204ecda6fb084)

Thanks sir, I highly appreciate your help :)
