### ISSUE TITLE
ACTUALLY detected

### ISSUE THREAD

**Issue by xavier124** [danielkrupinski/Osiris#1749]
Removed like half the features and vmp'd with virtualization+mutation and injected with randoinjector with asm emit junk. Got vac ban. NO OVERWATCH. Just vac.
![image](https://user-images.githubusercontent.com/40267566/84565953-db491480-ad75-11ea-899b-c234cc0211f6.png)

**Comment by hyperxpro** [comment]
Close the issue. We already have a lot of these.

**Comment by kschou95** [comment]
pls check other issues, this is your own problem

**Comment by Megalounge** [comment]
We know about it already.

**Comment by aljawary** [comment]
close this, theres so many multiple issues like this

**Comment by VuBrian22** [comment]
OML Your INJECTOR is detected!! Please close this issue and use Process Hacker 2 as it uses a Kernel Driver for process management and most importantly injection.

**Comment by xavier124** [comment]
> 
> 
> OML Your INJECTOR is detected!! Please close this issue and use Process Hacker 2 as it uses a Kernel Driver for process management and most importantly PE injection.

isn't process hacker 2 detected? If it isn't then why doesn't anyone recommend PH2 and they recommend rando-injector?

**Comment by ocewot** [comment]
idk i honestly think it is detected i used two different injectors i even continued to use my rando injector paste with other cheats and not get banned. then after getting banned using osiris i used a c# injector that is is barely known i added junk code still got banned

**Comment by VuBrian22** [comment]
> > OML Your INJECTOR is detected!! Please close this issue and use Process Hacker 2 as it uses a Kernel Driver for process management and most importantly PE injection.
> 
> isn't process hacker 2 detected? If it isn't then why doesn't anyone recommend PH2 and they recommend rando-injector?

I've actually switched to PH2 many months ago from my own modified version of RandoInjector and I have received no bans at all on 6 accounts so far.

**Comment by cryptdrive** [comment]
Why would you use rando injector ? people have been using that injector since 2017 without any changes .

**Comment by TheNulledJester** [comment]
Can vouch. I have done the exact same thing as stated above and got vac'd on 4 accounts.

**Comment by FL1ks** [comment]
i've been using this cheat for like 3 months it didn't get detacted once

**Comment by 0xE232FE** [comment]
Consider the Injector causing the detection.
As I have done some misstakes in my injector I received gamban -> VAC Ban
https://steamcommunity.com/id/imguiX64/
https://steamcommunity.com/id/SorenBecker/
Both Accounts detected same day the VAC Ban issue was different. Look at the days!

**Comment by xavier124** [comment]
> 
> 
> Consider the Injector causing the detection.
> As I have done some misstakes in my injector I received gamban -> VAC Ban
> https://steamcommunity.com/id/imguiX64/
> https://steamcommunity.com/id/SorenBecker/
> Both Accounts detected same day the VAC Ban issue was different. Look at the days differense nearly 40 days!!! So the VAC Ban could lay quiet a while in the past. I used the injecotr only once on both accounts same day for testing. And then don't play this Accounts anymore. After sometime one Account got Game Ban issued and 24 hrs later VAC Ban same for the Account that was banned later on.

Gameban then vac is vacnet, nothing is detected, ur just too blatant

**Comment by 0xE232FE** [comment]
@xavier124 It was 100% injector, I know what I am doing. ;-)

**Comment by ruminyan** [comment]
Just make your own injector, there should be enough tutorials online to make one yourself.

**Comment by VuBrian22** [comment]
@ruminyan If you go back to the old hooking methods, you'll also get banned as now it's the hooking methods that are detected and not your injector.

**Comment by erikKeresztes** [comment]
Of course it's detectable, if you don't want to get VAC banned, play legit, make your own cheat, or buy a private cheat

**Comment by xXTOO-HARDXx** [comment]
Osiris isn't ACTUALLY detected, so please close this issue thread thanks.
