### ISSUE TITLE
1> Hooks.obj: error LNK2001: Unrecognized external symbol "void __cdecl Aimbot :: run (struct UserCmd *)" (? Run @ Aimbot @@ YAXPAUUserCmd @@@ Z) some help?

### ISSUE THREAD

**Issue by Zvonda1337** [danielkrupinski/Osiris#1752]

**Comment by Cyk-Fad** [comment]
delete your source and use git clone new source

**Comment by anony123456** [comment]
is this related to cheat detection

**Comment by Zvonda1337** [comment]
@Cyk-Fad I dont want delete my source because i have lot of features in it

**Comment by Megalounge** [comment]
change x64 to x32

**Comment by aljawary** [comment]
This errors happen cuz daniel update the imgui version, i got the same issues
