### ISSUE TITLE
How to Get Pattern Index?

### ISSUE THREAD

**Issue by techzin** [danielkrupinski/Osiris#1754]
I would like to understand what the osiris standards are (findpattern)
I'm trying to learn how to update this myself, I already downloaded IDA Pro and installed the Sigmaker plugin, to generate patterns, however I don't know which option to use.

![image](https://user-images.githubusercontent.com/61809691/84581096-c4c1ae00-adb3-11ea-8b12-cc17ab0f1fe2.png)

**Comment by xAkiraMiura** [comment]
the first option is what you want as that is what the pattern scan function takes.

ida style sigs use either the hex of an assembly instruction or a question mark for any instruction. (whereas code style uses a mask, requiring 2 strings)

**Comment by 0xE232FE** [comment]
First you need to know that the Mac OS Version includes Function Names. From here you can start to find things in the Windows Binary.
