### ISSUE TITLE
[VAC BYPASS METHOD] 

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1755]
create a fake csgo.exe process and attach vac to it, no vac bans anymore, tested it without vac bypass loader, 2 weeks and still no ban (not vm protected, cuz its useless as vm protection just doesn't work)

**Comment by Megalounge** [comment]
What do you mean by creating a fake csgo.exe instance?

**Comment by 0xE232FE** [comment]
Its another injection method. You spawn 3rd Party Process inject the dll into it and wait for csgo process to apear and look for the panorama dll loaded. Then the 3rd Party Process will inject the osiris dll into the csgo process. This is how I inject without any detection atm.

**Comment by HowToMakeFaceitAB** [comment]
Yeah and it's good

**Comment by Megalounge** [comment]
Sounds complicated, do you have any tutorial on doing that method? Thanks for your kindness.

**Comment by 0xE232FE** [comment]
You just build an cascaded injector and first inject into a 3rd Party Process and the 2nd injector in the 3rd Party process wait for the csgo process and attach to it and look for the loaded panorma environemnt. If it has been loaded the 2nd injector in the 3rd Party Process can inject into csgo process. That is what most p2c Developers do with their injectors. VAC can not scan the 3rd Party harmless application because it is out of scope. I have already successfully injected with Nvidia Stuff which injects into nearly any 3D Application.

**Comment by Megalounge** [comment]
> You just build an cascaded injector and first inject into a 3rd Party Process and the 2nd injector in the 3rd Party process wait for the csgo process and attach to it and look for the loaded panorma environemnt. If it has been loaded the 2nd injector in the 3rd Party Process can inject into csgo process. That is what most p2c Developers do with their injectors. VAC can not scan the 3rd Party harmless application because it is out of scope. I have already successfully injected with Nvidia Stuff which attach/inject into nearly any 3D Application.

so that's kinda like Internal/External like what most ppl are talking about.

**Comment by realstyla23** [comment]
> You just build an cascaded injector and first inject into a 3rd Party Process and the 2nd injector in the 3rd Party process wait for the csgo process and attach to it and look for the loaded panorma environemnt. If it has been loaded the 2nd injector in the 3rd Party Process can inject into csgo process. That is what most p2c Developers do with their injectors. VAC can not scan the 3rd Party harmless application because it is out of scope. I have already successfully injected with Nvidia Stuff which attach/inject into nearly any 3D Application.

nah i dont get it. what u mean by 3rd party process

**Comment by jBZ8hwBS1QS** [comment]
> Its another injection method. You spawn 3rd Party Process inject the dll into it and wait for csgo process to apear and look for the panorama dll loaded. Then the 3rd Party Process with a armed injector will be able to load/inject the osiris dll into the csgo process. This is how I inject without any detection atm.

So. Do you have any loader or injector publicly available?

**Comment by sorrowvibez** [comment]
can you make a video tutorial on how you do it?

**Comment by newcommerdontblame** [comment]
Can u make a vid pls

**Comment by 0xE232FE** [comment]
https://www.youtube.com/watch?v=H0FEr_-udj8

**Comment by Malilor** [comment]
> create a fake csgo.exe process and attach vac to it, no vac bans anymore, tested it without vac bypass loader, 2 weeks and still no ban (not vm protected, cuz its useless as vm protection just doesn't work)

can i add you on discord, i could really use this method

**Comment by xXTOO-HARDXx** [comment]
Please close this issue.

**Comment by HowToMakeFaceitAB** [comment]
It does work, ive tested it, don't tell me what works and what doesn't, i know it does, imma close issue cuz idc about osiris anymore

**Comment by xXTOO-HARDXx** [comment]
> It does work, ive tested it, don't tell me what works and what doesn't, i know it does, imma close issue cuz idc about osiris anymore

If whatever you are doing works then have done a very terrible job of explaining what you are doing lmao

**Comment by HowToMakeFaceitAB** [comment]
I suck at explaining

**Comment by xXTOO-HARDXx** [comment]
> I suck at explaining

Well, then, that's fair enough. The concept of attaching VAC and tricking csgo.exe is possible, but it's not as simple as injecting VAC into a random csgo.exe that is third party and it magically working.
