### ISSUE TITLE
Can't use custom clantag with cyrillic letters

### ISSUE THREAD

**Issue by playday3008** [danielkrupinski/Osiris#1758]
I wrote for example: осирисosiris
![image](https://user-images.githubusercontent.com/18056374/84593788-51b94580-ae4e-11ea-8f61-65ad20750785.png)
![image](https://user-images.githubusercontent.com/18056374/84593801-61d12500-ae4e-11ea-890f-a56d289feaf7.png)

**Comment by playday3008** [comment]
Maybe this is ImGui bug, but in [Sensum](https://github.com/playday3008/Sensum) cheat that's working, and Sensum GUI based on ImGui

**Comment by AntonDoil** [comment]
u8
