### ISSUE TITLE
vclient018 error

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#1760]
![Untitled](https://user-images.githubusercontent.com/65455170/84594375-816e4a80-ae5a-11ea-940c-7fff9bc77008.jpg)
 how can i fix i dont wanna lose my version

**Comment by overthrown-by-society** [comment]
Maybe you're still using the old client_panorama.dll?
https://github.com/danielkrupinski/Osiris/commit/efe8d16d0ea5d6e5cd45208a7f3d6ef2ff5526e6

**Comment by playday3008** [comment]
or trying inject using crashhandler method

**Comment by newcommerdontblame** [comment]
İt doesnt work now game crashing

> Maybe you're still using the old client_panorama.dll?
> [efe8d16](https://github.com/danielkrupinski/Osiris/commit/efe8d16d0ea5d6e5cd45208a7f3d6ef2ff5526e6)

**Comment by newcommerdontblame** [comment]
> or trying inject using crashhandler method

What is this

**Comment by playday3008** [comment]
> What is this
Renaming `Osiris.dll` to `crashhandler.dll` and replacing it in Steam folder

**Comment by overthrown-by-society** [comment]
> İt doesnt work now game crashing
> 
> > Maybe you're still using the old client_panorama.dll?
> > [efe8d16](https://github.com/danielkrupinski/Osiris/commit/efe8d16d0ea5d6e5cd45208a7f3d6ef2ff5526e6)

Debug it, then.
