### ISSUE TITLE
(Question) Easy download for Osiris?

### ISSUE THREAD

**Issue by Deciy** [danielkrupinski/Osiris#1764]
I've been trying to use Osiris but everything has been holding me back. I tried to do it via Osiris.sln however, Visual Studio had trouble downloading things that were needed at I can't fix it. My friend sent me download files that worked for a little, however then I got an error that reads, "Failed to find VClient018 interface!" and my game crashes. I looked for fixes and found one for the VClient018 issue but the problem is that I don't understand code, also the fix the I found for VClient018 didn't explain how to fix it it just showed code. Can anybody send me updated Osiris files or maybe explain how to fix 'em? Or even can someone help me find a fix for Visual Studio?

**Comment by infinity1211** [comment]
Reinstall Visual studio with Desktop Development with C++ and download latest files by danielkrupinski and then compile. Or just download from cheater.fun

**Comment by barbadully** [comment]
https://pastebin.com/ApbquT8U

**Comment by newcommerdontblame** [comment]
> Reinstall Visual studio with Desktop Development with C++ and download latest files by danielkrupinski and then compile. Or just download from cheater.fun

Just reinstall vs with tools and when u setup login with your acc dont dowload from cheaterfun or some shitty cheatforums

**Comment by Deciy** [comment]
> > Reinstall Visual studio with Desktop Development with C++ and download latest files by danielkrupinski and then compile. Or just download from cheater.fun
> 
> Just reinstall vs with tools and when u setup login with your acc dont dowload from cheaterfun or some shitty cheatforums

Thank you I’ll give it a shot later (I don’t have access to my pc rn) and let you know how it went.

**Comment by 0xE232FE** [comment]
#1 install git
#2 run command `git clone https://github.com/danielkrupinski/Osiris`

There is no more easier way to download Osiris!

**Comment by Deciy** [comment]
> #1 install git
> #2 run command `git clone https://github.com/danielkrupinski/Osiris`
> 
> There is no more easier way to download Osiris!

Ok. I have access to my computer again (don't ask why I didn't) and I'll make sure to try out these suggestions asap.
