### ISSUE TITLE
They are selling osiris as their own cheat

### ISSUE THREAD

**Issue by Kingsman-cmd** [danielkrupinski/Osiris#1765]
I know a cheat distributor that slightly changed the osiris menu and is selling it as its own cheat.
Their YouTube channel: https://www.youtube.com/channel/UCp0UM3c1ZzwpLBjdiOmIANQ/videos
They call it "Premium X"

**Comment by newcommerdontblame** [comment]
osiris is open source cheat isnt it?

**Comment by notgoodusename** [comment]
nothing daniel can do.

**Comment by TauCSGO** [comment]
Permissions:  Commercial use

https://github.com/danielkrupinski/Osiris/blob/master/LICENSE
