### ISSUE TITLE
(Release) New MENU 

### ISSUE THREAD

**Issue by techzin** [danielkrupinski/Osiris#1766]
I was studying ImGui and found a source containing Osiris and with a very attractive menu.
this on void.to follows the link for anyone interested.
https://void.to/t/OSIRIS-WITh-evolve-menu

Screenshot:
![thread_3057c4a7f8f35cb6b7cb8f8fccd3b24c (1)](https://user-images.githubusercontent.com/61809691/84691822-2c463d80-af1b-11ea-9a37-a8a2182748b2.png)

**Comment by newcommerdontblame** [comment]
Do you have discord can i ask you something?

**Comment by techzin** [comment]
Just to clarify, I didn't make this menu.

my discord: TechZiN#4087

**Comment by Zurek0x** [comment]
> Just to clarify, I didn't make this menu.
> 
> my discord: TechZiN#4087

Send me your new discord, I'm working on a patcher for this and im gonna add it to the new versions of Osiris
