### ISSUE TITLE
(QUESTION) Best Injector to use?

### ISSUE THREAD

**Issue by samplics** [danielkrupinski/Osiris#1767]
I was using Lit Injector for the past 2 years on alts and I think that it is detected now :(

**Comment by DoritoKing94** [comment]
Guided Hacking has a good injector to use that's safe and so far i think undetected too as well as being simple

**Comment by techzin** [comment]
You can use my injection (Opensource) Developed in C#
Github: https://github.com/techzin/Tech-CSGO-Injector

**Comment by xXTOO-HARDXx** [comment]
Process Hacker 2 is probably your best bet, it uses a Kernel Driver for process management, including injecting DLLs. 

Please close this issue if you found what you need, thanks.

**Comment by samplics** [comment]
> Process Hacker 2 is probably your best bet, it uses a Kernel Driver for process management, including injecting DLLs.
> 
> Please close this issue if you found what you need, thanks.

Where can I download Process Hacker 2? is it: https://processhacker.sourceforge.io

**Comment by realstyla23** [comment]
> > Process Hacker 2 is probably your best bet, it uses a Kernel Driver for process management, including injecting DLLs.
> > Please close this issue if you found what you need, thanks.
> 
> Where can I download Process Hacker 2? is it: https://processhacker.sourceforge.io

is it safe to use? cuz i have my own injector but ph2 would be better at the end..

**Comment by xXTOO-HARDXx** [comment]
> > > Process Hacker 2 is probably your best bet, it uses a Kernel Driver for process management, including injecting DLLs.
> > > Please close this issue if you found what you need, thanks.
> > 
> > 
> > Where can I download Process Hacker 2? is it: https://processhacker.sourceforge.io
> 
> is it safe to use? cuz i have my own injector but ph2 would be better at the end..

As I said, PH2 is very Kernel reliant, so you should be able inject just fine because there's nothing much VAC can do from UserMode when you're using a KernelMode injector, to scan anything, etc
