### ISSUE TITLE
(QUESTION) how do I put getLocalPlayer on osiris?

### ISSUE THREAD

**Issue by koon666** [danielkrupinski/Osiris#1769]
how do i add getlocalplayer to osiris? because I was putting a jump bug that uses getlocalplayer, but this is not in osiris source. (source) const auto localPlayer = interfaces.entityList->getEntity(interfaces->engine->getLocalPlayer());

**Comment by cailloubr** [comment]
#include (SDK/LocalPlayer.h)
localPlayer.get()

**Comment by aljawary** [comment]
localPLayer.get()

**Comment by koon666** [comment]
not yet ;-;
https://prnt.sc/t0srvm

**Comment by cailloubr** [comment]
Bom, cê é BR, daí facilita um pouco.

O LocalPlayer saiu do Engine a um tempo atrás, agora você só usa "localPlayer.get()" e nada mais, como pode ver na linha abaixo:
https://github.com/danielkrupinski/Osiris/blob/6760072bda00174d46f251281fd940b7e75c7b57/Osiris/Hacks/Misc.cpp#L321

Se você ficar com dúvida, é mais fácil dar um "CTRL + F" no VStudio e pesquisar.

**Comment by koon666** [comment]
ola cailloubr, ent, eu troquei aquele codigo por esse que vc mandou e msm assim deu erro: https://prnt.sc/t0yet6

me desculpe, pois eu sou iniciante nessas coisas ;-;

**Comment by cailloubr** [comment]
Faltou o ".get()"

**Comment by koon666** [comment]
também não foi: https://prnt.sc/t0zv1h

se quiser conversa melhor, me adicione no discord: koon3123#4879

**Comment by cailloubr** [comment]
O nome da variável é o mesmo nome da função, troca pra "local".

**Comment by koon666** [comment]
tambem não foi so com o local

**Comment by cailloubr** [comment]
> tambem não foi so com o local

Eu te adicionei em um repositório com minha versão do Osiris, dá uma olhada lá, ela é bem diferente da original, com diversas funções extras, você vai conseguir tirar suas dúvidas.

**Comment by koon666** [comment]
obrigado :)

**Comment by cailloubr** [comment]
De nada, o nome é "BRCheats-CSGO".

Fecha o issue aí por favor.

**Comment by koon666** [comment]
ok

**Comment by twangsriprasoet** [comment]
> not yet ;-;
> https://prnt.sc/t0srvm
> 
> void Misc::jumpBug(UserCmd* cmd) noexcept
> {
> 
> ```
> if (!config->misc.jumpbug) return;
> 
> const auto localPlayer = interfaces->entityList->getEntity(localPlayer.get();
> 
> float max_radias = M_PI * 2;
> float step = max_radias / 128;
> float xThick = 23;
> 
> if (GetAsyncKeyState(config->misc.jumpbugkey) && (localPlayer->flags() & (1 << 0))) {
>     if (config->misc.bunnyHop) {
>         config->misc.bunnyHop = false;
>         bhopWasEnabled = true;
>     }
> 
>     const auto [width, height] = interfaces->surface->getScreenSize();
>     if (unduck) {
>         bDidJump = false;
>         cmd->buttons |= UserCmd::IN_DUCK; // duck
>         cmd->buttons |= UserCmd::IN_JUMP; // jump
>         unduck = false;
>     }
>     Vector pos = localPlayer->origin();
>     for (float a = 0.f; a < max_radias; a += step) {
>         Vector pt;
>         pt.x = (xThick * cos(a)) + pos.x;
>         pt.y = (xThick * sin(a)) + pos.y;
>         pt.z = pos.z;
> 
> 
>         Vector pt2 = pt;
>         pt2.z -= 6;
> 
>         Trace fag;
> 
>         TraceFilter flt = localPlayer;
> 
>         interfaces->engineTrace->traceRay({ pt, pt2 }, 0x1400B, flt, fag);
> 
>         if (fag.fraction != 1.f && fag.fraction != 0.f) {
>             bDidJump = true;
>             cmd->buttons |= UserCmd::IN_DUCK; // duck
>             cmd->buttons |= UserCmd::IN_JUMP; // jump
>             unduck = true;
>         }
>     }
>     for (float a = 0.f; a < max_radias; a += step) {
>         Vector pt;
>         pt.x = ((xThick - 2.f) * cos(a)) + pos.x;
>         pt.y = ((xThick - 2.f) * sin(a)) + pos.y;
>         pt.z = pos.z;
> 
>         Vector pt2 = pt;
>         pt2.z -= 6;
> 
>         Trace fag;
> 
>         TraceFilter flt = localPlayer;
>         interfaces->engineTrace->traceRay({ pt, pt2 }, 0x1400B, flt, fag);
> 
>         if (fag.fraction != 1.f && fag.fraction != 0.f) {
>             bDidJump = true;
>             cmd->buttons |= UserCmd::IN_DUCK;; // duck
>             cmd->buttons |= UserCmd::IN_JUMP; // jump
>             unduck = true;
>         }
>     }
>     for (float a = 0.f; a < max_radias; a += step) {
>         Vector pt;
>         pt.x = ((xThick - 20.f) * cos(a)) + pos.x;
>         pt.y = ((xThick - 20.f) * sin(a)) + pos.y;
>         pt.z = pos.z;
> 
>         Vector pt2 = pt;
>         pt2.z -= 6;
> 
>         Trace fag;
> 
>         TraceFilter flt = localPlayer;
>         interfaces->engineTrace->traceRay({ pt, pt2 }, 0x1400B, flt, fag);
> 
>         if (fag.fraction != 1.f && fag.fraction != 0.f) {
>             bDidJump = true;
>             cmd->buttons |= UserCmd::IN_DUCK; // duck
>             cmd->buttons |= UserCmd::IN_JUMP; // jump
>             unduck = true;
>         }
>     }
> }
> 
> 
> 
> else if (bhopWasEnabled) {
>     config->misc.bunnyHop = true;
>     bhopWasEnabled = false;
> }
> ```
> 
> }

Ty for the code, i tried and it's working. 😄

**Comment by unnamed01X** [comment]
how to do "localplayer", i got errors when im trying to add something
