### ISSUE TITLE
(Question) How to change the menu

### ISSUE THREAD

**Issue by ajblackwood** [danielkrupinski/Osiris#1772]
How would i go about changing the menu

**Comment by AlisaCiya** [comment]
gui.cpp

**Comment by cailloubr** [comment]
https://github.com/danielkrupinski/Osiris/blob/master/Osiris/GUI.cpp
+
https://github.com/ocornut/imgui/wiki

**Comment by ajblackwood** [comment]
Like if i found a second source that uses im gui and i like the gui would i just copy and pate it over and then call it again in all the places where the gui is called

**Comment by xXTOO-HARDXx** [comment]
> Like if i found a second source that uses im gui and i like the gui would i just copy and pate it over and then call it again in all the places where the gui is called

No, this would take a lot of manual tinkering. You would have to copy the code over and change all of the references. 

Close this issue if you have figured it out, and don't need any more help.

**Comment by ajblackwood** [comment]
> > Like if i found a second source that uses im gui and i like the gui would i just copy and pate it over and then call it again in all the places where the gui is called
> 
> No, this would take a lot of manual tinkering. You would have to copy the code over and change all of the references.
> 
> Close this issue if you have figured it out, and don't need any more help.

Im gonna be trying this out when i can but thanks for the help

**Comment by xXTOO-HARDXx** [comment]
> > > Like if i found a second source that uses im gui and i like the gui would i just copy and pate it over and then call it again in all the places where the gui is called
> > 
> > 
> > No, this would take a lot of manual tinkering. You would have to copy the code over and change all of the references.
> > Close this issue if you have figured it out, and don't need any more help.
> 
> Im gonna be trying this out when i can but thanks for the help

Glad to hear it.
Feel free to close this when you can, good luck with the menu!
