### ISSUE TITLE
anti aim future

### ISSUE THREAD

**Issue by jestemgosciem** [danielkrupinski/Osiris#1773]
how to create antiaim at target?

**Comment by techzin** [comment]
there is an anti-yea pull request, you can see it here -> https://github.com/danielkrupinski/Osiris/pull/1546
I think you can use it to develop yours.
:)

**Comment by xXTOO-HARDXx** [comment]
Refer to the pull that techzin provided, if you have fixed your issue, please close this issue, thanks.

**Comment by jestemgosciem** [comment]
i didint saw that future

**Comment by DoomFishWasTaken** [comment]
get list of all enemies, get nearest to crosshair (or use some other target selection), get bones and look at head/torso/etc, set cmd->viewangles.y
