### ISSUE TITLE
Help with SkinChangers Image files

### ISSUE THREAD

**Issue by techzin** [danielkrupinski/Osiris#1775]
People, I'm building a function to display the skins images on the skinchanger.
ex: you selected the Dragon Lore, it will be displayed in the preview.
A problem I found and having images of skins, it seems to me that the valve stores a link in the csgo folder (\ csgo \ scripts \ items)
but I have no idea of converting the values inside those files into a variable, if someone can help me with that I will be happy, I intend to make everything available through a pull request.

**Comment by cailloubr** [comment]
https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples

**Comment by newcommerdontblame** [comment]
Its pretty useless i think also accept my friend request in discord

**Comment by techzin** [comment]
> https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples

so, i already understood how the image system works, i already managed to use images in the menu.

**Comment by techzin** [comment]
> Its pretty useless i think also accept my friend request in discord

already accepted.

**Comment by KernCS** [comment]
https://yougame.biz/threads/42556/

**Comment by xXTOO-HARDXx** [comment]
Use ItemDefinitionIndex() functions to find the current weaponID, and beforehand, use AddFontFromMemoryTTF() (ImGUI) to load an icon base Font; which is a true font file with all of the weapon icons saved inside.

You can find one on UC I think, take a look.

**Comment by techzin** [comment]
> Use ItemDefinitionIndex() functions to find the current weaponID, and beforehand, use AddFontFromMemoryTTF() (ImGUI) to load an 'icon base' font, that's what I call them at least; which is a true font file with all of the weapon icons saved inside.
> 
> You can find one on UC I think, take a look.

Thanks
