### ISSUE TITLE
Can Cvars cause Vac Bans?

### ISSUE THREAD

**Issue by techzin** [danielkrupinski/Osiris#1776]
I was studying the way cheats work and realized that some functions are done using Cvars (internal csgo commands) an example of this is the crosshair sniper available on Osiris.
My question is, I found a command that removes the recoil (weapon_recoil_scale 0)
I did some tests and I didn't get a ban (until now.)
is there a problem using these types of commands? will it cause problems with detection?

**Comment by xAkiraMiura** [comment]
`weapon_recoil_scale` is **server sided** and requires `sv_cheats`.

**Comment by techzin** [comment]
I managed to use it in an official Valve killer, modifying the Osiris Misc, I took the function that added the Sniper Crosshair and put weapon_recoil_scale, and it worked I got a perfect recoil.

**Comment by AlisaCiya** [comment]
I have tried adding weapon recoil scale before, but it seems to have no effect

**Comment by AlisaCiya** [comment]
If the CSGO internal command can be passed, then if the noclip command is feasible, we can fly

**Comment by techzin** [comment]
> If the CSGO internal command can be passed, then if the noclip command is feasible, we can fly

Noclip is a Server Si de Var

**Comment by AlisaCiya** [comment]
Okay, I think too much.hah

**Comment by AlisaCiya** [comment]
When I'm in the official match, the weapon recoil scale command does not make the weapon have no recoil. If all hit the wall, the bullets are very dense, but if it hits a person, there is no recoilless effect.

**Comment by 0xE232FE** [comment]
You can modify the 3rd Party View and you can spectator fly with it. ;-)

**Comment by AlisaCiya** [comment]
Yes, although the recoil is reduced visually, there is actually recoil

**Comment by xXTOO-HARDXx** [comment]
If you consider your question(s) answered, please close this issue. Thanks.

**Comment by techzin** [comment]
Weapon_recoil_scale don't work correctly on Match Making because is only clientes si de recoil, you need to use a RCS to reduce recoil
