### ISSUE TITLE
FAKE PING AKA EXTENDED BACKTRACK

### ISSUE THREAD

**Issue by notgoodusename** [danielkrupinski/Osiris#1777]
GUYS, not only is this for fake ping, it can be also be used to a sv pure bypass because im hooking netchannel
https://www.unknowncheats.me/forum/counterstrike-global-offensive/279394-dumb-sv_pure-bypass.html

proof of my fake ping: https://streamable.com/upy0ul

im going to release this, of course, so everyone can enjoy 400 ms backtrack and maybe someone will do a sv pure bypass

**Comment by VuBrian22** [comment]
I'm interested to see what you did. Can't wait for the release!

**Comment by koon666** [comment]
can you send me the osiris source with sv pure bypass? I wish I had a source to use old gloves -__-

**Comment by notgoodusename** [comment]
i may be posting the pr tomorrow, because i have homework

**Comment by koon666** [comment]
I didn't understand, will you post the source or the dll? and where will you post? I don't know what it is. sry bro ;-;

**Comment by techzin** [comment]
> Eu não entendi, você vai postar a fonte ou a dll? e onde você vai postar? Não sei o que é isso sry bro; -;

pull requests.

**Comment by AntonDoil** [comment]
> i may be posting the pr tomorrow, because i have homework

Do you have discord?

**Comment by aljawary** [comment]
sorry what is netchannel ?

**Comment by notgoodusename** [comment]
> > i may be posting the pr tomorrow, because i have homework
> 
> Do you have discord?

yes, send yours and i will add you

**Comment by AntonDoil** [comment]
> > > i may be posting the pr tomorrow, because i have homework
> > 
> > 
> > Do you have discord?
> 
> yes, send yours and i will add you

Meinkhampf#2444

**Comment by notgoodusename** [comment]
done

**Comment by notgoodusename** [comment]
Found a way to do a sv pure bypass, releasing it now
