### ISSUE TITLE
[NOT AN ISSUE] but something is wrong.. (banned)

### ISSUE THREAD

**Issue by realstyla23** [danielkrupinski/Osiris#1778]
I know there are 100000 of threads like this already.. but something like that never happened to me.

just played a game on a new account with the latest osiris build, did my usual modifications on it.

got banned midgame.. Overwatch ban.. not sure how that is even possible. 

my other three accounts who I didnt inject since almost two weeks now are still without a ban, though I used a different version of Osiris back then

**Comment by xAkiraMiura** [comment]
if you got banned mid-game with no previous matches then you got banned by VACnet.

**Comment by 0xE232FE** [comment]
@xAkiraMiura this is not true. If his Account got Flagged there is also a possibility to get banned in mid match. This happens to me in 2017 as a public Hook Method I used got flagged. The bans are issued while playing in Game. If I don't join a VAC Server all Accounts are still not banned! I tested all Accounts that used the Hook in June 2017 are flagged. I have over 70 Accounts that has been flagged and I reproduced the Bans even this days. I played one of the 70 Accounts last week which is never been playing CSGO since 2017 and the VAC Ban gets fired during the first match I play, even if I do not inject anything!

**Comment by steel4me** [comment]
> @xAkiraMiura this is not true. If his Account got Flagged there is also a possibility to get banned in mid match. This happens to me in 2017 as a public Hook Method I used got flagged. The bans are issued while playing in Game. If I don't join a VAC Server all Accounts are still not banned! I tested all Accounts that used the Hook in June 2017 are flagged. I have over 70 Accounts that has been flagged and I reproduced the Bans even this days. I played one of the 70 Accounts last week which is never been playing CSGO since 2017 and the VAC Ban gets fired during the first match I play, even if I do not inject anything!

True!

**Comment by realstyla23** [comment]
but how can a new account be flagged without any games played not even injected... the other three accounts are clean, just played on all of them one game.. just to be sure.. but thx for the info

**Comment by steel4me** [comment]
nobody can say exactly what steam is doing and most people here speak from their experiences. you cannot always share every opinion. The following is important for multiaccounting:

Never use the same email address for all your accounts.
Each account must have its own email address.

Disable family sharing on all accounts.

Never use the same cell phone number on multiple accounts.

otherwise it can lead to a ban on several accounts at the same time if the accounts have been linked as described above. not everyone will share this opinion. but it happened to me. and you learn from mistakes

**Comment by Scui1** [comment]
> 
> 
> if you got banned mid-game with no previous matches then you got banned by VACnet.

Why do you even open your mouth when you don't know what VACnet does? There was never any talk about VACnet handling out VAC bans wtf

**Comment by xXTOO-HARDXx** [comment]
> > if you got banned mid-game with no previous matches then you got banned by VACnet.
> 
> Why do you even open your mouth when you don't know what VACnet does? There was never any talk about VACnet handling out VAC bans wtf. This guy probably just got banned because of his detected hooking method.

I'll +1 that. Akira says some silly things sometimes 🥴

**Comment by m0nsterJ** [comment]
@steel4me Having the same e-mail address connected to a banned and connect to a not banned account won't lead to a ban. You don't need a new e-mail for each account lol. I use one e-mail for 5 non primes and like 10 banned non primes and the 5 who are connected to the same e-mail as the 10 banned ones didn't get banned. I am using the same cellphone number on my main account and my VAC banned account and I didn't get banned on my not banned main account. You will only receive a ban at the time one of the two accounts with the same phone number gets banned, then both of the accounts have a ban. But if you received let's say a VAC ban 500 days ago on your phone number and you connect this exact phone number on a new account, the new account won't get banned. Stop spreading fake information, do your research.

**Comment by xXTOO-HARDXx** [comment]
> @steel4me Having the same e-mail address connected to a banned account and connect to a not banned account won't lead to a ban. You don't need a new e-mail for each account lol. I use one e-mail for 5 non primes and like 10 banned non primes and the 5 who are connected to the same e-mail as the 10 banned ones didn't get banned. I am using the same cellphone number on my main account and my VAC banned account and I didn't get banned on my not banned main account. You will only receive a ban at the time one of the two accounts with the same phone number gets banned. But if you received let's say a VAC ban 500 days ago on your phone number and you connect this exact phone number on a new account, the new account won't get banned. Stop spreading fake information, do your research.

Steel isnt entirely incorrect, however you won't get banned if you used the same e-mail, in any situation. what he said about using the same e-mail is correct, sort of; your account will likely be flagged and there will be a strong correlation between your "new account" having bad trust factor if you had another account banned on the same e-mail, but you won't get "banflagged", per se.

**Comment by steel4me** [comment]
> @steel4me Having the same e-mail address connected to a banned account and connect to a not banned account won't lead to a ban. You don't need a new e-mail for each account lol. I use one e-mail for 5 non primes and like 10 banned non primes and the 5 who are connected to the same e-mail as the 10 banned ones didn't get banned. I am using the same cellphone number on my main account and my VAC banned account and I didn't get banned on my not banned main account. You will only receive a ban at the time one of the two accounts with the same phone number gets banned. But if you received let's say a VAC ban 500 days ago on your phone number and you connect this exact phone number on a new account, the new account won't get banned. Stop spreading fake information, do your research.

@m0nsterJ 
**First Fact** -> you are one of those guys that are fully unable to proofread and interpret texts.
I don't spread fake information when i write **it can lead to a ban**, i didnt wrote "**it will lead to a ban**" also i wrote that i made this experience but not everyone has to share this experience with me or believe me. so your answer is absolutely nonsense

**Second Fact** -> you are one of those guys that say osiris didn't triggered any sort of ban. Not in february when i reported it, not even now, although more and more people are reporting it.
some of them don't have much clue and use public injectors, ok, but a lot of other peoples like @xXTOO-HARDXx that experienced a random ban out of nowhere like me are facing the possibility that the hooking method maybe triggeres a sort of ban. And again, i wrote **maybe**. I wil get it to the point now. You are othe chosen one that passes fake information to users by saying osiris is safe and dont trigger any ban, a public cheat which sourcecode is fully available fo all. ok that makes sense. cmon...really?

**Third Fact** -> everything you wrote is always 100% true, you never use "maybe" or "possible" in your sentence construction. Let's pray for you omniscient god who knows everything

**Fourth Fact** -> you are just retarted, I no longer read a single sentence from you, you are the scum of the community that literally annihilates the basic idea of github. together find errors, optimize code

**Comment by xXTOO-HARDXx** [comment]
Yadi yadi yah. The point is your two;

1. If you want your best bet at being in good trust, use a different email.
2. Using the same email WON'T get you banned but will LIKELY have a negative EFFECT on any future accounts you make.
3. You WILL get banned in CSGO if you're banned on another account linked the same MOBILE NUMBER.
4. Public injectors and generally bad without heavy modification or randomisation in the codes flow control. LVLL technique's, etc.

Have a nice day, close the thread sometime, I'm trying to contribute to cleaning up the issues section... 600 open issues? What the actual heck. Lol.

**Comment by steel4me** [comment]
> Yadi yadi yah. The point is you two;
> 
> 1. If you want your best bet at being in good trust, use a different email.
> 2. Using the same email WON'T get you banned but will LIKELY have a negative EFFECT on any future accounts you make.
> 3. You WILL get banned in CSGO if you're banned on another account linked the same MOBILE NUMBER.
> 4. Public injectors are generally bad without heavy modification or randomisation in the codes flow control. LVLL technique's, etc.
> 
> Have a nice day, close the thread sometime, I'm trying to contribute to cleaning up the issues section... 600 open issues? What the actual heck. Lol.

Even if I no longer use osiris i would be interested in what ultimately triggered the random bans ... which supposedly never existed. haha, nice joke

**Comment by Scui1** [comment]
Vmt is detected, just use something different and you‘ll be fine. For me playing with vmt (not osiris) leads to an ow ban after some hours and then transforms into a vac ban.

**Comment by realstyla23** [comment]
so i changed the hookin method minhook and now its good.. we'll see in the future but so far no ban..

**Comment by xXTOO-HARDXx** [comment]
> so i changed the hookin method minhook and now its good.. we'll see in the future but so far no ban..

would be so kind to create a fork or your own repo with the modified hooking? It's up to you of course.

**Comment by realstyla23** [comment]
i rather not... maybe in the future since I dont even know  if its safe or not.. but if you are into hooking look for  "MinHook - The Minimalistic API Hooking Library"

what u could do is remove all features and just leave the aimbot for example then try with the new hooking method. not much work

**Comment by steel4me** [comment]
Finally Daniel seems to implement MinHook.

https://github.com/danielkrupinski/Osiris/commit/e7732dcd32f277593f5780a2f38898c9081fa64a
