### ISSUE TITLE
Feature suggestion (resolver)

### ISSUE THREAD

**Issue by pr0f35510n4l** [danielkrupinski/Osiris#1779]
Hello, this is a really great cheat, but I am missing 1 thing here and I do not have enough knowledge to do it myself. Could you please add AA Resolver to the cheat. 
Thank you.

**Comment by xXTOO-HARDXx** [comment]
I'll make a pull.

**Comment by aljawary** [comment]
> I'll make a pull.

quick bro we need this feature to beat spinner

**Comment by hastydev** [comment]
yes

**Comment by hastydev** [comment]
I mean there's an alternative, just spam body

**Comment by hastydev** [comment]
bro its been 2 hours

**Comment by 4u7157** [comment]
> I'll make a pull.

when pull sar

**Comment by hastydev** [comment]
bro please pull

**Comment by xXTOO-HARDXx** [comment]
Sorry, I got school. I'll make the pull later on when I have time. And when I say "I'll make a pull"... I mean a LegitAA Resolver. Why the heck would you put a full AA resolver in a full legit cheat smh

**Comment by hastydev** [comment]
the cheat isn't full legit cheat lmao
Osiris could be actually good for HVH if there was a resolver. The cheat can tap bad configs if you set bodyaim

**Comment by cailloubr** [comment]
É cada coisa que eu leio, não vou nem gastar meu inglês ruim com isso

**Comment by newcommerdontblame** [comment]
> Sorry, I got school. I'll make the pull later on when I have time. And when I say "I'll make a pull"... I mean a LegitAA Resolver. Why the heck would you put a full AA resolver in a full legit cheat smh
> 
> A full resolver would be a lot of code, that I don't have time to write.
> 
> EDIT: there's no point having a rage AntiAim resolver because you're still gonna get tapped first; either their ragebot will shoot quicker, the resolver won't work the first time (and then ya fucked) or you'll miss their fakelag

Can u make it with player options like dont resolve everyplayer we can choose the player
 cuz it make legit players unhittable

**Comment by xXTOO-HARDXx** [comment]
> > Sorry, I got school. I'll make the pull later on when I have time. And when I say "I'll make a pull"... I mean a LegitAA Resolver. Why the heck would you put a full AA resolver in a full legit cheat smh
> > A full resolver would be a lot of code, that I don't have time to write.
> > EDIT: there's no point having a rage AntiAim resolver because you're still gonna get tapped first; either their ragebot will shoot quicker, the resolver won't work the first time (and then ya fucked) or you'll miss their fakelag
> 
> Can u make it with player options like dont resolve everyplayer we can choose the player
> cuz it make legit players unhittable

I can try, might take a bit cause I have to find time.

**Comment by newcommerdontblame** [comment]
> > > Sorry, I got school. I'll make the pull later on when I have time. And when I say "I'll make a pull"... I mean a LegitAA Resolver. Why the heck would you put a full AA resolver in a full legit cheat smh
> > > A full resolver would be a lot of code, that I don't have time to write.
> > > EDIT: there's no point having a rage AntiAim resolver because you're still gonna get tapped first; either their ragebot will shoot quicker, the resolver won't work the first time (and then ya fucked) or you'll miss their fakelag
> > 
> > 
> > Can u make it with player options like dont resolve everyplayer we can choose the player
> > cuz it make legit players unhittable
> 
> I can try, might take a bit cause I have to find time.

So when?

**Comment by xXTOO-HARDXx** [comment]
> > Sorry, I got school. I'll make the pull later on when I have time. And when I say "I'll make a pull"... I mean a LegitAA Resolver. Why the heck would you put a full AA resolver in a full legit cheat smh
> > A full resolver would be a lot of code, that I don't have time to write.
> > EDIT: there's no point having a rage AntiAim resolver because you're still gonna get tapped first; either their ragebot will shoot quicker, the resolver won't work the first time (and then ya fucked) or you'll miss their fakelag
> 
> Can u make it with player options like dont resolve everyplayer we can choose the player
> cuz it make legit players unhittable

Only just read this, but, no that isn't right. Resolving players that don't have anti-aim will just make them stay the same.

**Comment by avidretard** [comment]
> > > Sorry, I got school. I'll make the pull later on when I have time. And when I say "I'll make a pull"... I mean a LegitAA Resolver. Why the heck would you put a full AA resolver in a full legit cheat smh
> > > A full resolver would be a lot of code, that I don't have time to write.
> > > EDIT: there's no point having a rage AntiAim resolver because you're still gonna get tapped first; either their ragebot will shoot quicker, the resolver won't work the first time (and then ya fucked) or you'll miss their fakelag
> > 
> > 
> > Can u make it with player options like dont resolve everyplayer we can choose the player
> > cuz it make legit players unhittable
> 
> Only just read this, but, no that isn't right. Resolving players that don't have anti-aim will just make them stay the same.

find a way to check for the enemies eye angles to see if theyre pointing down or not or check if youre on a vac secured server could be a way to chose whether or not to resolve someone
