### ISSUE TITLE
ANTI AIM DOUBTS 

### ISSUE THREAD

**Issue by king1919djdj** [danielkrupinski/Osiris#1780]
I'll keep it short
how does the anti aim work ?
is it the fake body type or the looking down and back type ?

**Comment by newcommerdontblame** [comment]
https://youtu.be/CWdRwG63c3c

**Comment by king1919djdj** [comment]
so it creates a fake angle of my player model ?
i used it in matchmaking, my teammates said that i was looking backwards while moving (and they kicked me, yeah they did)

**Comment by notgoodusename** [comment]
Valve patched fake angles, 
Before
The first command of a batch was used for the server while the sent ones where used to the client
basically
if(!sendpacket && firstcommand)
server
else if(sendpacket)
client
Now 
Every command is used for the server while the client only uses the sent ones
basically
if(!sendpacket || sendpacket)
server
else if(sendpacket)
client
