### ISSUE TITLE
[Question] Best practices to make it undetected?

### ISSUE THREAD

**Issue by pabisovskyooo** [danielkrupinski/Osiris#1782]
Hello! I have now added 32 long lines of junk code to my cheat. (Auto Junkcode.exe). What else could I do to make sure it won't be detected by VAC? How often should I change my junk code if only me and a few friends using my cheat?

**Comment by aljawary** [comment]
Juno code is useless

**Comment by 4u7157** [comment]
vac-bypass-loader ig

**Comment by pabisovskyooo** [comment]
> vac-bypass-loader ig

Could you tell me more? How long are you playing using a vac-bypass-loader? of course without VAC.

**Comment by hyperxpro** [comment]
Junk codes are useless. When you load the cheat, it'll be the same for all Osiris users out there. There are better ways to detect a cheat other than just signature matching.

**Comment by aljawary** [comment]
junk code are useless, u can add or remove some features to make it little undetected and protect with vmprotect

**Comment by cailloubr** [comment]
Code your own cheat.

**Comment by xXTOO-HARDXx** [comment]
Something about Osiris is detected, or Valve have changed how VAC detects some cheats, namely Osiris. Also, junk code is not useless. That's a fact, anyone that disagrees is spreading misinformation.

**Comment by hyperxpro** [comment]
> Something about Osiris is detected, or Valve have changed how VAC detects some cheats, namely Osiris. Also, junk code is not useless. That's a fact, anyone that disagrees is spreading misinformation.

Sorry if you hurt but your confidence level shows either you're Valve employee working on VAC or just another silver retard.

**Comment by xXTOO-HARDXx** [comment]
> > Something about Osiris is detected, or Valve have changed how VAC detects some cheats, namely Osiris. Also, junk code is not useless. That's a fact, anyone that disagrees is spreading misinformation.
> 
> Sorry if you hurt but your confidence level shows either you're Valve employee working on VAC or just another silver retard.

I'm neither of the sort... I have seen literally SO many people saying that Junk Code is useless that now I am just getting pissed off, because it just isn't true.

**Comment by xAkiraMiura** [comment]
> 
> 
> > >~
> > 
> > 
> > ~
> 
> ~
> 
> I have seen A LOT of people saying that Junk Code is useless, and at this point I don't even know what to say.. I know it isn't true, but people are obviously too stuck to their ignorant demeanours.

try adding junk code and then seeing if my pattern scanning function fails. it wont. sigs are small enough that it can still be grabbed between your junk code blocks.
(also the compiler will remove the junk code unless you disable optimization. this is a bad idea because most of the time the compiler is smarter than you (certainly **you**) and unoptimized code can become very unoptimized).

**Comment by xXTOO-HARDXx** [comment]
> > > > ~
> > > 
> > > 
> > > ~
> > 
> > 
> > ~
> > I have seen A LOT of people saying that Junk Code is useless, and at this point I don't even know what to say.. I know it isn't true, but people are obviously too stuck to their ignorant demeanours.
> 
> try adding junk code and then seeing if my pattern scanning function fails. it wont. sigs are small enough that it can still be grabbed between your junk code blocks.
> (also the compiler will remove the junk code unless you disable optimization. this is a bad idea because most of the time the compiler is smarter than you (certainly **you**) and unoptimized code can become very unoptimized).

you don't understand my point, I've made it many times before. It really depends on where and how you use junk code that makes the difference. If you use it in-line in your feature functions correctly along with other things it does indeed change the signature, I've done it for years,

Also, there's no reason to bring hostility into conversation ("certainly you"). Sorry if me being right pissed you off. ;)

**Comment by xXTOO-HARDXx** [comment]
> Hello! I have now added 32 long lines of junk code to my cheat. (Auto Junkcode.exe). What else could I do to make sure it won't be detected by VAC? How often should I change my junk code if only me and a few friends using my cheat?

Ok OP, in essence, it isn't very useful at all to add large blocks of junk code anywhere, especially at the end of .cpp files. it's just increasing the file size, really.

Consider implementing junk code into already existing functions, make 'Junk Functions', and make them return a random number or long and do a relative constant return check when calling them, before continuing with your cheat code.

Also, something very useful... use a custom obfuscation algorithm! they can be very extensive in their usability.

An example, using **Control Flow Flattening**, allows you to turn something such as:

```
void main()
{
  int a = sin (v69lol) / tan (69lmao);
  if(a <= 0)
    return 1;
  else
    return 10;
  return 0;
}
```

into something like:

```
void main ()
{
  int a = atoi(argv[1]);
  int b = 0;
  while(1) 
  {
    switch(b) 
    {
      case 0:
        if(a <= 0)
          b = 1;
        else
          b = 2;
        break;
      case 1:
        return 1;
      case 2:
        return 10;
      default:
        break;
    }
  }
  return 0;
}
```

search up on it, it's a very useful technique, much more useful than 'Junk Code'.

**Comment by hyperxpro** [comment]
ROFL SILVER KID TRYING TO HIDE CHEATS TO RANK UP TO GN1 TO GET OVERWATCH SO THAT HE CAN BAN CHEATER. HAHAHAHAHAHAHA. GOOD LUCK JUNK.

**Comment by xXTOO-HARDXx** [comment]
> ROFL SILVER KID TRYING TO HIDE CHEATS TO RANK UP TO GN1 TO GET OVERWATCH SO THAT HE CAN BAN CHEATER. HAHAHAHAHAHAHA. GOOD LUCK JUNK.

what in the world are you talking about.

**Comment by barbadully** [comment]
> ROFL SILVER KID TRYING TO HIDE CHEATS TO RANK UP TO GN1 TO GET OVERWATCH SO THAT HE CAN BAN CHEATER. HAHAHAHAHAHAHA. GOOD LUCK JUNK.

are you fucking retarded?

**Comment by cailloubr** [comment]
> ROFL SILVER KID TRYING TO HIDE CHEATS TO RANK UP TO GN1 TO GET OVERWATCH SO THAT HE CAN BAN CHEATER. HAHAHAHAHAHAHA. GOOD LUCK JUNK.

I think you must have a problem. Nobody goes to GitHub to look for cheats, the real people (with issues and pulls) visualize this project to learn how the reverse engineering and modification of a game works. If people compile this and use it, it is not our fault, as nowhere is it encouraged or supported to use it in official matches. Draw your own conclusions from this.
