### ISSUE TITLE
Backtrack Not Working

### ISSUE THREAD

**Issue by sundafused** [danielkrupinski/Osiris#1783]
Hey everyone, backtracking is not working at all for me. [Here's a video of it](https://youtu.be/s5hGWnRyiak) Anybody have any suggestions to help? It's been like this for a while, no matter how many times i recompile the cheat.

**Comment by cailloubr** [comment]
Try recent pull request.

**Comment by sundafused** [comment]
> Try recent pull request.

As shown in the video, I have actually already tried that. I appreciate the input though.

**Comment by notgoodusename** [comment]
try the lastest change, idk why it doesnt work for you

**Comment by xXTOO-HARDXx** [comment]
Osiris' backtrack can be inconsistent sometimes, from my experience at least.

Also, I am pretty sure Osiris doesn't check for valid ticks, which doesn't help. Correct me if I am wrong.

**Comment by notgoodusename** [comment]
> Osiris' backtrack can be inconsistent sometimes, from my experience at least.
> 
> Also, I am pretty sure Osiris doesn't check for valid ticks, which doesn't help. Correct me if I am wrong.

it does check if the ticks are valid also removing getlerp from cmd tickcount makes it more consistent

**Comment by AntonDoil** [comment]
Bruh, dont aim at last model of the player, try to hit the middle.

**Comment by sundafused** [comment]
> Bruh, dont aim at last model of the player, try to hit the middle.
I've tried hitting every single part of the backtrack model I can.
