### ISSUE TITLE
(Request) simple legit aa resolver

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#1786]
Can u make legit aa resolver with player options like dont resolve everyplayer we can choose

**Comment by xXTOO-HARDXx** [comment]
there's already an active issue for this that was literally just opened, please close this. Too much bloat

**Comment by newcommerdontblame** [comment]
So you guys should make if people want that much

**Comment by newcommerdontblame** [comment]
Nvm
