### ISSUE TITLE
(Question) Easy download for Osiris? Part 2

### ISSUE THREAD

**Issue by Deciy** [danielkrupinski/Osiris#1787]
I have tried to hack in Csgo via Visual Studio, however, my current computer does not meet the requirements for Visual Studio. Are there any other ways to download Osiris? It worked before when my friend sent files through discord. The file names were Osiris.dll and osiris_2_mpgh.net.rar. But recently these files stopped working thanks to the Failed to find VClient018 interface! error. All I need are just some easy to download files or some other way to use these hacks.

**Comment by king1919djdj** [comment]
[Osiris.zip](https://github.com/danielkrupinski/Osiris/files/4802851/Osiris.zip)
try this

**Comment by xXTOO-HARDXx** [comment]
Use the link that @king1919djdj provided. If it works for you, please close this issue, thanks @OP

**Comment by Deciy** [comment]
> [Osiris.zip](https://github.com/danielkrupinski/Osiris/files/4802851/Osiris.zip)
> try this
> compiled it myself so it should work

Thank you. I'll try it asap.

**Comment by Deciy** [comment]
Sorry for being a waste of time but do any of you have working injectors?

**Comment by xXTOO-HARDXx** [comment]
> Sorry for being a waste of time but do any of you have working injectors?

Try getting yourself a copy of Process Hacker 2. Undetected afaik

**Comment by Deciy** [comment]
> > Sorry for being a waste of time but do any of you have working injectors?
> 
> Try getting yourself a copy of Process Hacker 2. Undetected afaik

OK one last thing. Is it on github? Also if you have used it, can you explain how to use it as an injector. I am asking these because I want to make sure I got the right download and also it just looked like taskmanager

**Comment by xXTOO-HARDXx** [comment]
> > > Sorry for being a waste of time but do any of you have working injectors?
> > 
> > 
> > Try getting yourself a copy of Process Hacker 2. Undetected afaik
> 
> OK one last thing. Is it on github? Also if you have used it, can you explain how to use it as an injector. I am asking these because I want to make sure I got the right download and also it just looked like taskmanager

https://github.com/processhacker/processhacker/releases/download/v2.39/processhacker-2.39-setup.exe

Get the installer here.
When installed, just open it, find csgo.exe in the process list, right click csgo.exe, and find the "inject DLL" option. Works a charm. GL.

Close issue if this works for you 👍

**Comment by Deciy** [comment]
Thank both of you so much! It worked!
