### ISSUE TITLE
Vac auth error

### ISSUE THREAD

**Issue by Nesc4uu** [danielkrupinski/Osiris#1789]
I'm getting vac auth error in matchmaking everytime, why ?

**Comment by aljawary** [comment]
- Verify ur game files.
- Relog ur Steam Account
- Done

**Comment by Nesc4uu** [comment]
i know that, but in competitive you cant reconnect after a vac auth error...
I think that the reason of this error is the recoil based fov... Can someone fix it?

**Comment by zxsleebu** [comment]
bro lol just use vac bypass loader. it fixed all errors for me

**Comment by Nesc4uu** [comment]
i'm being game banned in all of my accounts without use aimbot or wallhacks... :/

**Comment by Nesc4uu** [comment]
i got banned in my first match using osiris

**Comment by zxsleebu** [comment]
use sazinjector, vac bypass, and protect your dll with vmprotect. it shouldn't be happened

**Comment by Nesc4uu** [comment]
i used my own injector, all vmprotected
i was getting game banned cuz of my phone number, sorry for my mistake
