### ISSUE TITLE
Not Working on faceit????

### ISSUE THREAD

**Issue by xmine7890** [danielkrupinski/Osiris#1790]
Is there anyway it work on faceit???

**Comment by xmine7890** [comment]
@danielkrupinski

**Comment by AntonDoil** [comment]
No.
If you want add me on the discord and i can sell you version for faceit what spoofin client side anticheat, tho serverside **BUT** have only bhop.

**Comment by m0nsterJ** [comment]
@AntonDoil Why are you trying to scam people lmao

**Comment by AntonDoil** [comment]
> @AntonDoil Why are you trying to scam people lmao

Scam? Add me onto discord and i can give u free subscription to prove you, im not scamming. Retard. 

Meinkhampf#2444

**Comment by m0nsterJ** [comment]
Nah dude I'm good I don't need your "free sub" prob some keylogger or trojan or something smh.

**Comment by yaelahrip** [comment]
@m0nsterJ idk what was wrong  with you haha funny

**Comment by AntonDoil** [comment]
> Nah dude I'm good I don't need your "free sub" prob some keylogger or trojan or something smh.

Honestly, you must be retarded. 
Like first you call me "scammer", and then when i offer u free subscription, you call me "ratter". 
Get some brain buddy.

**Comment by m0nsterJ** [comment]
@AntonDoil I highly doubt that you have your own cheat with a good "sub" system. Who would advertise their cheat on Github to a guy asking if Osiris works on faceit + selling your stuff via discord is kinda odd aswell. If you have such a big p2c for faceit and stuff then why are you selling your shit via discord,hm? Also, how would you give me a free sub without sending me a loader or anything, in the loader could be some virus or smth. Get some brain buddy.

**Comment by AntonDoil** [comment]
> @AntonDoil I highly doubt that you have your own cheat with a good "sub" system. Who would advertise their cheat on Github to a guy asking if Osiris works on faceit + selling your stuff via discord is kinda odd aswell. If you have such a big p2c for faceit and stuff then why are you selling your shit via discord,hm? Also, how would you give me a free sub without sending me a loader or anything, in the loader could be some virus or smth. Get some brain buddy.

tf u talkin' about? I dont must sell it there, it was only offer th.  
"free sub without sending me a loader or anything"
Thats why i asked you for Discord, dumb ass.

**Comment by cailloubr** [comment]
This is a issue, not a trade.

**Comment by xXTOO-HARDXx** [comment]
This doesn't support faceit and likely never will. 

Please close this issue, thanks.

**Comment by xmine7890** [comment]
Okay Thanks
