### ISSUE TITLE
hit marker

### ISSUE THREAD

**Issue by jestemgosciem** [danielkrupinski/Osiris#1791]
i try to decrease alpha after shoot, but dosent work, code: if (config->visuals.hitMarkerTime > 0) {
            float alpha = config->visuals.hitMarkerTime;

            interfaces->surface->setDrawColor(255, 255, 255, alpha);
            interfaces->surface->drawLine(width_mid + 10, height_mid + 10, width_mid + 4, height_mid + 4);
            interfaces->surface->drawLine(width_mid - 10, height_mid + 10, width_mid - 4, height_mid + 4);
            interfaces->surface->drawLine(width_mid + 10, height_mid - 10, width_mid + 4, height_mid - 4);
            interfaces->surface->drawLine(width_mid - 10, height_mid - 10, width_mid - 4, height_mid - 4);

            config->visuals.hitMarkerTime -= 2;

            break;
        }

**Comment by xXTOO-HARDXx** [comment]
First of all, don't use operator signs with different variable types:
`if (config->visuals.hitMarkerTime > 0) {`
instead, don't be an entire noob, and use the same types:
`if (config->visuals.hitMarkerTime > 0.0f) {`


Also, 'alpha' in the Color struct is an integer that ranges from 1-255, so setting it to 0.6f (the default value for **hitMarkerTime**) won't do anything. If you are trying to set it to a float (**hitmarkerTime**), you are losing data, so you're probably having the issue there.
