### ISSUE TITLE
(Help)making ur own source

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#1793]
Is there a easy way to mix 2 pull
For example i wanna add this (https://github.com/danielkrupinski/Osiris/pull/1483) feature to (https://github.com/danielkrupinski/Osiris/pull/1781) this 
how can i do that? Is there any tutorial video to understand?

**Comment by RyDeem** [comment]
1 Download Github Desktop.
2 download master branch of osiris (clone on main page/open in desktop x-github-client://openRepo/https://github.com/danielkrupinski/Osiris)
3 click "current branch" on top of the github desktop app
4 click "New branch" button on top next to search box
5 use upstream/master
6 then when its created go into "current branch" again but this time click on the bottom most button choose a branch to merge in to branch.
7 then select the pull request you want to merge.

I hope some of this helps, but as a coder you should do poking around, and start using google for problems. Not always people are helpful, some might just drop a www.google.com and leave.

Peace and have fun.

**Comment by RyDeem** [comment]
And you are not going to make your own source by adding pulls to osiris, thats not how it works, id say you just want to dabble in coding, and see how things work now, dont say you are making your own source, Osiris IS your source at the moment. :)

**Comment by cailloubr** [comment]
> 1 Download Github Desktop.
> 2 download master branch of osiris (clone on main page/open in desktop x-github-client://openRepo/https://github.com/danielkrupinski/Osiris)
> 3 click "current branch" on top of the github desktop app
> 4 click "New branch" button on top next to search box
> 5 use upstream/master
> 6 then when its created go into "current branch" again but this time click on the bottom most button choose a branch to merge in to branch.
> 7 then select the pull request you want to merge.
> 
> I hope some of this helps, but as a coder you should do poking around, and start using google for problems. Not always people are helpful, some might just drop a [www.google.com](http://www.google.com) and leave.
> 
> Peace and have fun.

The pulls that he quoted are outdated, he will need some changes/fixes.

**Comment by RyDeem** [comment]
yes that is true cail.

Is there a easy way to mix 2 pull-basically no is the answer,
 but poke around and try stuff, you allways can wipe and start from fresh source not modded (upstream/master)

**Comment by notgoodusename** [comment]
> The pulls that he quoted are outdated, he will need some changes/fixes.


mine isnt tho.

**Comment by cailloubr** [comment]
You understood what I meant.
