### ISSUE TITLE
Manualmap Crash

### ISSUE THREAD

**Issue by psxsahan** [danielkrupinski/Osiris#1794]
All manualmap methods crashes.

**Comment by notgoodusename** [comment]
what do you mean?

**Comment by xXTOO-HARDXx** [comment]
> All manualmap methods crashes.

What injector are you using, and do you have the latest source?

**Comment by psxsahan** [comment]
> > All manualmap methods crashes.
> 
> What injector are you using, and do you have the latest source?

i'm using lastest source. ManualMap injectors crashing when i try to inject in game

**Comment by xXTOO-HARDXx** [comment]
> > > All manualmap methods crashes.
> > 
> > 
> > What injector are you using, and do you have the latest source?
> 
> i'm using lastest source. ManualMap injectors crashing when i try to inject in game

You still didn't say **which** injector you are using.

Just for the sake of it, download the newest source again since the hooking recode, compile and test it out.

**Comment by ahmet1231** [comment]
yes manualmap crashing how to fix :/

**Comment by psxsahan** [comment]
> > > > All manualmap methods crashes.
> > > 
> > > 
> > > What injector are you using, and do you have the latest source?
> > 
> > 
> > i'm using lastest source. ManualMap injectors crashing when i try to inject in game
> 
> You still didn't say **which** injector you are using.
> 
> Just for the sake of it, download the newest source again since the hooking recode, compile and test it out.
> 
> If you stop experiencing the issue, please close the issue. Thanks.

i'm trying ayyware loader's manualmapping. not for sale cheat, for manualmap method. but it's crashing.

**Comment by notgoodusename** [comment]
just use csgosimple injector

**Comment by xXTOO-HARDXx** [comment]
> > > > > All manualmap methods crashes.
> > > > 
> > > > 
> > > > What injector are you using, and do you have the latest source?
> > > 
> > > 
> > > i'm using lastest source. ManualMap injectors crashing when i try to inject in game
> > 
> > 
> > You still didn't say **which** injector you are using.
> > Just for the sake of it, download the newest source again since the hooking recode, compile and test it out.
> > If you stop experiencing the issue, please close the issue. Thanks.
> 
> i'm trying ayyware loader's manualmapping. not for sale cheat, for manualmap method. but it's crashing.

If you download the fresh source code, compile it and inject it with process hacker 2, then all should work fine.

That's all the help I can give, I have no idea what Ayyware Loader is or how it works, you need to give more detail.

**Comment by psxsahan** [comment]
[https://github.com/WilsonPublic/SimpleLoader/blob/master/GitHub%20SimpleLoader/Injection/ManualMapInjector.cs](url) MMapinjector

https://github.com/WilsonPublic/SimpleLoader/blob/master/GitHub%20SimpleLoader/Injection/ManualMapInjector.cs

like this.

**Comment by xXTOO-HARDXx** [comment]
> [https://github.com/WilsonPublic/SimpleLoader/blob/master/GitHub%20SimpleLoader/Injection/ManualMapInjector.cs](url) MMapinjector
> 
> like this.

Just use process hacker 2 lol.

It uses a Kernel Driver for LoadLibrary meaning it's very unlikely for VAC to detect it.
