### ISSUE TITLE
after update metode hooking my csgo crash after inject

### ISSUE THREAD

**Issue by jestemgosciem** [danielkrupinski/Osiris#1797]
and i have question, how can i debug my project to find an error?

**Comment by danielkrupinski** [comment]
Have you modified the source code?

**Comment by wirebruh** [comment]
Do you use the extended backtrack pull request? It has to be updated.

**Comment by aljawary** [comment]
> Do you use the extended backtrack pull request? It has to be updated.

yeah i did, but aint crash just doesnt work

**Comment by jestemgosciem** [comment]
Yes, i edit source. Add simple antiaim, thirdperson fix etc. But i edit only hooks.cpp and hooks.h and add this new files

**Comment by jestemgosciem** [comment]
i got error with interfaces but i can complicate

**Comment by xXTOO-HARDXx** [comment]
> and i have question, how can i debug my project to find an error?

build the .dll in Debug, start CS:GO, attach Visual Studio to csgo.exe (**DON'T JOIN VALVE SERVERS**), and then inject Osiris and debug :)

**Comment by xXTOO-HARDXx** [comment]
> i got error with interfaces but i can complicate

show a screenshot or something. don't be vague.

**Comment by aljawary** [comment]
> i got error with interfaces but i can complicate

yea its becuz daniel delete these class in interfaces.h
`class Client;
class Cvar;
class Engine;
class EngineTrace;
class EntityList;
class GameEventManager;
class GameMovement;
class GameUI;
class InputSystem;
class Localize;
class MaterialSystem;
class ModelInfo;
class ModelRender;
class NetworkStringTableContainer;
class Panel;
class PhysicsSurfaceProps;
class Prediction;
class RenderView;
class Surface;
class Sound;
class SoundEmitter;
class StudioRender;`

**Comment by xXTOO-HARDXx** [comment]
If you aren't going to continue the conversation then please close this issue, it's not worth having open.

**Comment by jestemgosciem** [comment]
can you upload video, i understand what u said

**Comment by xXTOO-HARDXx** [comment]
> can you upload video, i understand what u said

I also received the issues with the interfaces... as if they were not being defined. This happens in certain scopes, and seemingly disappears for no reason, when I make a change.
