### ISSUE TITLE
Change Font: Tahoma

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#1799]
I saw several topics about it but I did not understand very well
If I want to change the font for the menu, for example, for the tahoma font, how should I do?
Thank you

**Comment by xXTOO-HARDXx** [comment]
`fonts.tahoma = io.Fonts->AddFontFromFileTTF((path / "tahoma.ttf").string().c_str(), 15.0f, &cfg, ranges);`

this is already called inside of GUI init. so you should be able to just remove:

`fonts.segoeui = io.Fonts->AddFontFromFileTTF((path / "segoeui.ttf").string().c_str(), 15.0f, &cfg, ranges);`

but it might not work, ImGui is gay like that sometimes; finicky.

Report back :p

**Comment by TauCSGO** [comment]
Thanks, works

I changed for ARIAL.ttf
and in the gui.h add the line

    struct {
        ImFont* arial = nullptr;
        ImFont* segoeui = nullptr;
    } fonts;

**Comment by xXTOO-HARDXx** [comment]
> Thanks, works
> 
> I changed for ARIAL.ttf
> and in the gui.h add the line
> 
> ```
> struct {
>     ImFont* arial = nullptr;
>     ImFont* segoeui = nullptr;
> } fonts;
> ```

ah, glad to hear it. GJ.
