### ISSUE TITLE
Crashing & Backtrack not working with chams

### ISSUE THREAD

**Issue by CleverSource** [danielkrupinski/Osiris#180]
I tested backtrack and it doesn't work how backtrack is meant to and CSGO randomly crashed.

Examples of backtracking:
https://www.youtube.com/watch?v=ceaqz66WRBc&t=29s
https://www.youtube.com/watch?v=Nrot2tbLN68&t=1s

**Comment by CleverSource** [comment]
To note: It only crashed while using backtrack.

**Comment by HeadlessCpp** [comment]
What do you think the backtracking is doing then...

**Comment by CleverSource** [comment]
Look at the videos I provided, they show exactly what backtrack is. I'm mainly stating it will crash when used and that chams don't work with it.

**Comment by ultramemer** [comment]
did you use backtrack after [this](https://github.com/danielkrupinski/Osiris/commit/a7d982f78667e9e72b81875ab2596a7494a752fb) commit?

**Comment by CleverSource** [comment]
Yes, I used it on commit 2430.

**Comment by ultramemer** [comment]
uncomment what was done in that commit and try to use backtrack again
the chams i did show the last available record, not all available
about the crashes: i didnt experience them when i was playing around with backtrack, attach the debugger and show what it will show you when you crash

**Comment by CleverSource** [comment]
I uncommented that commit, no noticeable changes but I did notice backtrack works. I still experience a random crash throughout playing though.

**Comment by ultramemer** [comment]
did you attach the debugger?

**Comment by CleverSource** [comment]
The visual studio debugger?

**Comment by ultramemer** [comment]
yep

**Comment by CleverSource** [comment]
How would I attach that? I've never used it on an external application only projects in vs2019

**Comment by CleverSource** [comment]
Is it remote windows debugger?

**Comment by ultramemer** [comment]
open csgo
press ctrl+alt+p in visual studio
attach to csgo and inject osiris

**Comment by CleverSource** [comment]
![image](https://user-images.githubusercontent.com/21996470/57587040-b2988080-74cc-11e9-8364-1b05324a60d4.png)
Crash error!

**Comment by ultramemer** [comment]
well, this means that backtrack is trying access something which is literally nowhere
did it show where it crashed?

**Comment by CleverSource** [comment]
It crashed in my folder that has Osiris.dll is located.

**Comment by CleverSource** [comment]
The only files in there is the amazing dll injector called Inflame made by Daniel and Osiris.dll

**Comment by CleverSource** [comment]
Did not mean to close it, sorry.

**Comment by ultramemer** [comment]
i mean did it show the code which caused the crash
did you compile in debug mode?
![image](https://user-images.githubusercontent.com/31269663/57587116-5fdcba00-7508-11e9-97cb-238be0516481.png)

**Comment by CleverSource** [comment]
No it didn't show the code, I believe it was in Debug let me check.

**Comment by CleverSource** [comment]
Turns out I was using the Release DLL, I'll rerun my tests and get it to crash while on the Debug DLL

**Comment by danielkrupinski** [comment]
@CleverSource Remember to inject using LoadLibrary method.

**Comment by CleverSource** [comment]
![image](https://user-images.githubusercontent.com/21996470/57587224-a2ce6b80-74cf-11e9-969e-3c0300c3ef77.png)
Happens in Utils.h

**Comment by CleverSource** [comment]
@danielkrupinski I always use LoadLibrary.

**Comment by ultramemer** [comment]
show the call stack

**Comment by CleverSource** [comment]
It is happening here: https://github.com/danielkrupinski/Osiris/blob/master/Osiris/SDK/Utils.h
I'm on the latest commit and I reversed the changes on commit 2430 like @ultramemer said.

**Comment by CleverSource** [comment]
![image](https://user-images.githubusercontent.com/21996470/57587231-cbeefc00-74cf-11e9-9e70-99a9dcf6e57d.png)
Call stack

**Comment by CleverSource** [comment]
@ultramemer Any extra information you need?

**Comment by ultramemer** [comment]
try to revert [this](https://github.com/danielkrupinski/Osiris/commit/2412e7fc2c94e10a62aed16bdea5380c50395c6e) change

**Comment by CleverSource** [comment]
@ultramemer Will do.

**Comment by CleverSource** [comment]
@ultramemer I reverted it and I haven't experienced a crash. Seems to have fixed things.

**Comment by CleverSource** [comment]
@ultramemer You may want to pull request it or I can.

**Comment by ultramemer** [comment]
well, im sure Daniel will revert the second commit
only the second one because the first one worsens the aimbot

**Comment by CleverSource** [comment]
@danielkrupinski When you can make sure to do that.

**Comment by danielkrupinski** [comment]
Just pushed fix.

**Comment by CleverSource** [comment]
@danielkrupinski Awesome!
