### ISSUE TITLE
-FPS

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#1801]
My osiris kills ~ 50-60% FPS. Is there any way to optimize it because if I choose to play according to Legit at 25-35 FPS or play without cheat but with stable 62 (fps_max 63) I would choose the second !!!

**Comment by danielkrupinski** [comment]
What options are you using?

**Comment by aljawary** [comment]
> My osiris kills ~ 50-60% FPS. Is there any way to optimize it because if I choose to play according to Legit at 25-35 FPS or play without cheat but with stable 62 (fps_max 63) I would choose the second !!!

did u use fix bone matrix in misctab?

**Comment by Shuvi-Moro** [comment]
clear osiris

**Comment by Shuvi-Moro** [comment]
I just inject not including any functions and I’m eating a bunch of FPS

**Comment by Colten3Gamer** [comment]
To me happens the same but i have 300 fps when i inject stay with 20/30 fps and i have only activate skins and bomb time, If someone can help i will be grateful.

**Comment by Shuvi-Moro** [comment]
I no longer have this problem after updating the hook component

**Comment by Shuvi-Moro** [comment]
Thanks

**Comment by Colten3Gamer** [comment]
Shuvi-moro what did you made get the error out?
