### ISSUE TITLE
[Question] Instant Notifications

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#1805]
Is there any way to be notified by email when @danielkrupinski  uploads a new update? 
For example, being notified of new commits
In the notifications area, only find options to receive emails from conversations in which I participate, but I would like to be updated with the changes in Osiris

Thanks

**Comment by xXTOO-HARDXx** [comment]
![VnYse](https://user-images.githubusercontent.com/19278924/85343626-ac2e6200-b530-11ea-9516-2ecf7f84c930.JPG)

**Comment by xXTOO-HARDXx** [comment]
I've never used 'Watch' before in Github, but I am pretty sure it should do what you are asking about.

Close this issue if it helps. Thanks.

**Comment by TauCSGO** [comment]
> I've never used 'Watch' before in Github, but I am pretty sure it should do what you are asking about.
> 
> Close this issue if it helps. Thanks.

Thanks, but the **WATCH** option is for new **ISSUES** and **CONVERSATIONS**
I need notification when a new **commit** is uploaded

**Comment by xXTOO-HARDXx** [comment]
Well, you can try to download git and use that for notifcations, maybe there's something in there.

Why do you need INSTANT notifcations? I really don't see why you'd need them.

**Comment by TauCSGO** [comment]
> Why do you need INSTANT notifcations? I really don't see why you'd need them.

Because some hook updates are important and you shouldn't use an outdated dll

**Comment by xXTOO-HARDXx** [comment]
> > Why do you need INSTANT notifcations? I really don't see why you'd need them.
> 
> Because some hook updates are important and you shouldn't use an outdated dll

Just make sure to frequently check yourself. The worst that can happen is your game crashes.

**Comment by TauCSGO** [comment]
> Just make sure to frequently check yourself. The worst that can happen is your game crashes.

If you don't have the solution, please don't answer.

**Comment by xXTOO-HARDXx** [comment]
> > Just make sure to frequently check yourself. The worst that can happen is your game crashes.
> 
> If you don't have the solution, please don't answer.

There is no solution, you can try webhooks, but there's no in-house solution so this issue would be better off closed. Unless there's something I'm unaware of, that is.

Also, you do not govern this issue section, so please don't tell me to not answer, **especially** when all I'm doing is trying to help, thanks.

**Comment by TauCSGO** [comment]
> > > Just make sure to frequently check yourself. The worst that can happen is your game crashes.
> > 
> > 
> > If you don't have the solution, please don't answer.
> 
> You can try webhooks, but otherwise, there's no in-house solution; this issue would be better off closed. Unless there's something I'm unaware of, that is.
> 
> Also, you do not govern this issue section, so please don't tell me to not answer, **especially** when all I'm doing is trying to help, thanks.

If you don't have the solution, please don't answer.

**Comment by xXTOO-HARDXx** [comment]
> > > > Just make sure to frequently check yourself. The worst that can happen is your game crashes.
> > > 
> > > 
> > > If you don't have the solution, please don't answer.
> > 
> > 
> > You can try webhooks, but otherwise, there's no in-house solution; this issue would be better off closed. Unless there's something I'm unaware of, that is.
> > Also, you do not govern this issue section, so please don't tell me to not answer, **especially** when all I'm doing is trying to help, thanks.
> 
> If you don't have the solution, please don't answer.

Are you incompetent in a literal sense? Seriously, fuck off. You don't deserve any help.

Close this issue, I've already given you your answer.

**Comment by xXTOO-HARDXx** [comment]
> > > > > > Just make sure to frequently check yourself. The worst that can happen is your game crashes.
> > > > > 
> > > > > 
> > > > > If you don't have the solution, please don't answer.
> > > > 
> > > > 
> > > > You can try webhooks, but otherwise, there's no in-house solution; this issue would be better off closed. Unless there's something I'm unaware of, that is.
> > > > Also, you do not govern this issue section, so please don't tell me to not answer, **especially** when all I'm doing is trying to help, thanks.
> > > 
> > > 
> > > If you don't have the solution, please don't answer.
> > 
> > 
> > Are you incompetent in a literal sense? Seriously, fuck off. You don't deserve any help.
> > Close this issue, I've already given you your answer.
> 
> Your language shows who you are, and it is not in the first post that I read it

What are you talking about? I'd be disappointed if you told me English was your first language, because you're clearly having trouble with common sense.

**Comment by emphatically** [comment]
I dont think you can do this, like @xXTOO-HARDXx said, you can try `webhooks`. But I am not used with that stuff so I cant help.

also, why you have todo him like that? the guy was just trying to help. 

he has helped more than anyone else I've seen in the issue section, apart from Daniel and Akira.

**Comment by TauCSGO** [comment]
> I dont think you can do this, like @xXTOO-HARDXx said, you can try `webhooks`. But I am not used with that stuff so I cant help.
> 
> also, why you have todo him like that? the guy was just trying to help.
> 
> he has helped more than anyone else I've seen in the issue section, apart from Daniel and Akira.

he says "fuck off" in all the posts, when he doesn't like what they answer, it's not helpful
Thanks for your answer

**Comment by emphatically** [comment]
> I dont think you can do this, like @xXTOO-HARDXx said, you can try webhooks. But I am not used with that stuff so I cant help.
> also, why you have todo him like that? the guy was just trying to help.
> he has helped more than anyone else I've seen in the issue section, apart from Daniel and Akira.
> 
> he says "fuck off" in all the posts, when he doesn't like what they answer, it's not helpful
> Thanks for your answer

I don't agree. He was trying to offer help and encouraging you to close the issue because there is already way too many of them open (600+), but you kept pushing him back. I sorta know him and I know he deals with a lot of people who aren't experienced with coding and stuff, so of course he's going to be frustrated easily.

I don't know why I said this, but, I'm backing him up I guess. Glad I could be of assistance.
