### ISSUE TITLE
RCS?

### ISSUE THREAD

**Issue by YameKukuri** [danielkrupinski/Osiris#1807]
ik this isn't a issue but how can i add RCS or enable RCS to my osiris? Is there anyone who have the c++ code to RCS that i can add to osiris?

**Comment by RyDeem** [comment]
The RCS in my knowledge is enabled by default based on equiped gun.
No customization anymore though, just smooth and hitchance/aimbot activate chance settingsleft.

**Comment by aljawary** [comment]
u can check on #1277
