### ISSUE TITLE
Change Menu and tab fonts.

### ISSUE THREAD

**Issue by Adi2071** [danielkrupinski/Osiris#1808]
Hi,

How to change menu and tab fonts? I tried everything. Unfortunately I fail. Please help. Instead of the name Aimbot, I'd like an icon like in GameSense.

**Comment by newcommerdontblame** [comment]
https://github.com/danielkrupinski/Osiris/issues/1772

**Comment by Adi2071** [comment]
> #1772

not work. I tried everything I could think of and could find in other source codes.

**Comment by TauCSGO** [comment]
#1799

**Comment by xXTOO-HARDXx** [comment]
Refer to TauCSGO's comment for changing the fonts.

If you'd like icons, you can either read about the ImGui API and try to incorporate ImGui::Image();

**OR**

You can use a Memory Font, in a char/byte array, and use something like this to create a reference as well as load the font in mem:

`ImFont* gamesenseFont = io.Fonts->**AddFontFromMemoryTTF**(&fontArray, sizeof(fontArray), 16.0f);`

`fontArray` should be an `unsigned char*` full of bytes. (the font)

Good luck.
