### ISSUE TITLE
Change Path = My Documents

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#1809]
CFGs are saved in "My Documents\Osiris"
How can I save them to D: \CFG
for example? For Read and Save CFGs in D:

I found the line at hooks.cpp

config = std :: make_unique <Config> ("Osiris");

There I can change the name of the folder, but I cannot change the path

Thanks

**Comment by emphatically** [comment]
This is pretty self explanatory.

Read the GUI::config function at the top of config.cpp

Modify the path variable to a directory, e.g. D:\\saves\\Osiris

Make sure you use double backslashes.
