### ISSUE TITLE
how to add new chams models.

### ISSUE THREAD

**Issue by DoctorYasin** [danielkrupinski/Osiris#1812]
![image](https://user-images.githubusercontent.com/49906809/85566341-a15ef480-b638-11ea-8e26-eb0ca9bf1fb3.png)
![image](https://user-images.githubusercontent.com/49906809/85566678-ed119e00-b638-11ea-9647-f9d9016f735c.png)

**Comment by newcommerdontblame** [comment]
That would be super cool

**Comment by dapaster** [comment]
+1

**Comment by notgoodusename** [comment]
on the chams tab you can change that and have 2 renders at the same time just click the arrow and change 1 and 2 however you like

**Comment by DoomFishWasTaken** [comment]
Like @notgoodusename said this is literally already in the cheat. Upper hands and gun is just Glow with changed alpha :)

**Comment by DoomFishWasTaken** [comment]
Also if you want to add new read this ;)
https://developer.valvesoftware.com/wiki/Material
