### ISSUE TITLE
Desync Chams once for all DONE!

### ISSUE THREAD

**Issue by notgoodusename** [danielkrupinski/Osiris#1813]
i got them working, yey
proof:
https://streamable.com/nbrl48

**Comment by newcommerdontblame** [comment]
nice work man are u gonna make pull for this?
can we get ur source?

**Comment by notgoodusename** [comment]
> nice work man are u gonna make pull for this?
> can we get ur source?

im going to make a pr, i dont know when since i need to fix a few things

**Comment by newcommerdontblame** [comment]
osiris going to be private cheat level lmao

**Comment by aljawary** [comment]
wow Osiris on the next level

**Comment by mazmamad** [comment]
wow goodjob man

**Comment by aljawary** [comment]
> wow goodjob man

lmao gayfriend why are u here?

**Comment by DoomFishWasTaken** [comment]
Gj my src still has some problems, so imma just use urs ;)

**Comment by Scui1** [comment]
The pose doesn't seem correct to me. Are you just rotating the matrix?

**Comment by notgoodusename** [comment]
> The pose doesn't seem correct to me. Are you just rotating the matrix?

no, im creating a new one apart from my real

**Comment by nosexynomoney** [comment]
good job man

**Comment by mazmamad** [comment]
> i got them working, yey
> proof:
> https://streamable.com/nbrl48

release the beta source bro...  :<
