### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by kaylenbro** [danielkrupinski/Osiris#1815]
Could someone tell me how you could optimize this cheat because it is pretty unoptimized

**Comment by MiniPEACECloset** [comment]
Unfortunately, you can't because it's already feature-packed.

**Comment by cailloubr** [comment]
> Could someone tell me how you could optimize this cheat because it is pretty unoptimized

Buy another CPU, 5% FPS loss is very good.

**Comment by xXTOO-HARDXx** [comment]
Yes, .text patching has bad performance compared to VMT.

But, what can you do.

Close this, no one gonna optimise Osiris at this point.
