### ISSUE TITLE
Non Legit Bhop Source Code Needed

### ISSUE THREAD

**Issue by king1919djdj** [danielkrupinski/Osiris#1817]
I need a non legit bhop source code 
if anybody can help me that will be deeply appreciated 
 if directional bhop that will be great

**Comment by king1919djdj** [comment]
OK.............
i'll try to get it to work 
thanks

**Comment by king1919djdj** [comment]
can anybody make this code compatible with osiris ?
idk c++

**Comment by RealSmecks** [comment]
https://github.com/RealSmecks/Osiris/commit/23e4cc456acf355037c277d14e24fef290b2bb87

i pasted this from another fork. cant remember who's it was. lets u switch between legit, normal and rage. from me using it, rage and normal work the same, just rage is a little better. the directional on this is broken tho.

**Comment by xXTOO-HARDXx** [comment]
Multiple possible solutions posted now, please close this issue. Thanks.
