### ISSUE TITLE
(Request)movement features

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#1818]
Can someone make movement stuff like optimizable autostrafer for kz long jumps and movement recorder

**Comment by DoomFishWasTaken** [comment]
Autostrafer is already does have 100% sync in strafes

**Comment by newcommerdontblame** [comment]
> Autostrafer is already does have 100% sync in strafes

its legit strafer bro i mean hardstrafes like 6 per second for long jumps 

actually i think u can add ur pull this feature 
For hvh u need rage bhops tho

**Comment by newcommerdontblame** [comment]
Optimizable autostrafer would be cool in ur pull 
i think u can do this :))

**Comment by newcommerdontblame** [comment]
@danielkrupinski bruh what u thing about this cant u paste or write?
