### ISSUE TITLE
cant use interfaces

### ISSUE THREAD

**Issue by effex1337** [danielkrupinski/Osiris#182]
i get "pointer to incomplete class type is not allowed"
it used to work before

**Comment by effex1337** [comment]
in gui.cpp

**Comment by danielkrupinski** [comment]
What does it say? What class?

**Comment by effex1337** [comment]
![image](https://user-images.githubusercontent.com/48663440/57597836-af56d080-7570-11e9-86ca-928ba243ad47.png)

**Comment by danielkrupinski** [comment]
`#include SDK/Surface.h`

**Comment by effex1337** [comment]
fixed thanks
idk why but including this wasn't needed in the older versions|
https://github.com/effex1337/100--not-osiris/blob/master/Osiris/GUI.cpp
