### ISSUE TITLE
Menu Style2 and colors

### ISSUE THREAD

**Issue by codsec** [danielkrupinski/Osiris#1820]
I'm kind of new to this, so any forgiveness for being "noob", but someone takes a question from me, I want to know how I change the default colors and where they are and, if possible, I would like to know how I define the style2 the menu as default and I also wanted to increase it so that almost all tabs would appear

**Comment by xXTOO-HARDXx** [comment]
Go into the style tab in Osiris. And change the colour scheme to custom. All of the colours are changeable from there.

**Comment by codsec** [comment]
> Go into the style tab in Osiris. And change the colour scheme to custom. All of the colours are changeable from there.

I don't want to change it that way, I want to change it within the script in a standard way, you know?

**Comment by xXTOO-HARDXx** [comment]
> > Go into the style tab in Osiris. And change the colour scheme to custom. All of the colours are changeable from there.
> 
> I don't want to change it that way, I want to change it within the script in a standard way, you know?

right. well, that takes a bit of explaining. which I am not willing to do, sorry.

But, you can read the ImGui documentation. it will tell you exactly how to do it :)

GL

**Comment by codsec** [comment]
> > > Go into the style tab in Osiris. And change the colour scheme to custom. All of the colours are changeable from there.
> > 
> > 
> > I don't want to change it that way, I want to change it within the script in a standard way, you know?
> 
> right. well, that takes a bit of explaining. which I am not willing to do, sorry.
> 
> But, you can read the ImGui documentation. it will tell you exactly how to do it :)
> 
> GL

okok thx anyway
