### ISSUE TITLE
FPS dropped badly

### ISSUE THREAD

**Issue by fenggege953** [danielkrupinski/Osiris#1821]
When I use the generated DLL file and inject it into csgo, I find that the frame number of my csgo has dropped from more than 360 at the beginning to 80. How to solve this problem

**Comment by fenggege953** [comment]
I hope someone with ability can help me solve this problem. Please

**Comment by newcommerdontblame** [comment]
Same. This hook changes killed my fps tho

**Comment by fenggege953** [comment]
No, no, no, man, I've solved the problem

**Comment by fenggege953** [comment]
The reason is that I didn't use release to generate DLL. At the beginning, I used debug. Now the problem is solved after I change it

**Comment by fenggege953** [comment]
I hope all the brothers who have this kind of problem will try to do it again to see if the problem can be solved

**Comment by fenggege953** [comment]
When you have equiped a copy of source code, next step is opening Osiris.sln in Microsoft Visual Studio 2019.

Then change build configuration to Release | x86 and simply press Build solution.

If everything went right you should receive Osiris.dll binary file.

**Comment by fenggege953** [comment]
![image](https://user-images.githubusercontent.com/66827864/85823162-47346f80-b7af-11ea-898a-9a91b747727b.png)

**Comment by fenggege953** [comment]
just like this

**Comment by JustinLatiao** [comment]
nice to see u've solved bro :)

**Comment by Cyk-Fad** [comment]
if  problem has been solve
please close this Question
