### ISSUE TITLE
how to change key open menu?

### ISSUE THREAD

**Issue by koon666** [danielkrupinski/Osiris#1823]
Hello, I wanted to change the key to open the menu, without having to go to the misc and then to the "Menu Key". I wanted to change the font, but I couldn't find anything to change the key. NOTE: I want to change the insert key to delete :)))

**Comment by codsec** [comment]
https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Config.h
![image](https://user-images.githubusercontent.com/44205014/85913468-97411f80-b80b-11ea-83a3-2e5348c74bf9.png)

**Comment by xXTOO-HARDXx** [comment]
> https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Config.h
> ![image](https://user-images.githubusercontent.com/44205014/85913468-97411f80-b80b-11ea-83a3-2e5348c74bf9.png)

Adding into what was posted above me, the 'delete' key code is just after the 'insert' keycode, so you can just change 0x2D to 0x2E. And delete will be default. Close this issue when you get it. Thanks.

**Comment by koon666** [comment]
thanks bro :))
