### ISSUE TITLE
Osiris is ready for rage

### ISSUE THREAD

**Issue by Deciy** [danielkrupinski/Osiris#1824]
In my eyes I think Osiris is ready for some rage hacks. For example one I would love to see is Osiris spinbot. It would also be great to have a working min damage. These are just literally two examples but before I make suggestions I would like to know if anyone else agrees (Or disagrees) that Osiris is ready for rage.

**Comment by aljawary** [comment]
Even with spinbot osiris still not good

**Comment by tirziz** [comment]
It not mean to be a rage hack

**Comment by xXTOO-HARDXx** [comment]
I simply don't agree with this. Osiris is not a HvH/rage cheat, it IS NOT "ready for rage" in any sense. The base was built with Legit cheating in mind, so to turn it into a rage cheat would take a lot of effort. Close this, \\pointless thread.

**Comment by Deciy** [comment]
> I simply don't agree with this. Osiris is not a HvH/rage cheat, it IS NOT "ready for rage" in any sense. The base was built with Legit cheating in mind, so to turn it into a rage cheat would take a lot of effort. Close this, \pointless thread.

If it was built for legit hacking why does it have so many rage options? Auto shot, (not working) min damage,moonwalk,kill message, name stealer, setup fake ban. Even though these might not be lethal they aren’t legit whatsoever. You guys can post opinions don’t attack me because of a suggestion. I didn’t say anything offensive or controversial. You don’t need to attack me because I have a different opinion

**Comment by Deciy** [comment]
> Even with spinbot osiris still not good

If you don’t like Osiris...why are you here?

**Comment by xXTOO-HARDXx** [comment]
What...

I didn't mean to attack you at all lol, wasnt my intention <3

> moonwalk,kill message, name stealer, setup fake ban
^ these are all fun/trolling features

autoshot is a bit of a random thing, I don't know why it is in Osiris.



> > Even with spinbot osiris still not good
> 
> If you don’t like Osiris...why are you here?

I think he just means, "even with a spinbot, Osiris wouldnt be good for raging"

**Comment by Deciy** [comment]
Ok I am sorry for seeming to have attitude I’m not in a good mood. I’m also sorry for saying you attacked me that’s just how it felt on my side of the screen. I hope you understand all I want is rage hacks I think it would be fun on Osiris 😁. I’m going to leave this thread open for a short while to see if I can get some more opinions. Have a nice day.

**Comment by xXTOO-HARDXx** [comment]
> Ok I am sorry for seeming to have attitude I’m not in a good mood. I’m also sorry for saying you attacked me that’s just how it felt on my side of the screen. I hope you understand all I want is rage hacks I think it would be fun on Osiris 😁. I’m going to leave this thread open for a short while to see if I can get some more opinions. Have a nice day.

This is fine. 👍

**Comment by mazmamad** [comment]
trust me its not ready ,need to fix aimbot first :<

**Comment by Deciy** [comment]
> trust me its not ready ,need to fix aimbot first :<

What’s wrong with it?

**Comment by newcommerdontblame** [comment]
> What’s wrong with it?

Bipolar shit

**Comment by hyperxpro** [comment]
Fatality.win
Aimware.net
Gamesense.pub
Onetap.com
orange.fanta.club

Why you want Spin in Orisis when so many better options available?

**Comment by aljawary** [comment]
> > trust me its not ready ,need to fix aimbot first :<
> 
> What’s wrong with it?

The aimbot in this chit is so bad

**Comment by hyperxpro** [comment]
> > > trust me its not ready ,need to fix aimbot first :<
> > 
> > 
> > What’s wrong with it?
> 
> The aimbot in this chit is so bad

Looks like you new. Spin = Aimbot + Anti Aim. Osiris aimbot is trash, it sucks when killing enemy with Aimbot (no AA), forgot it can kill enemy with AA Aimbot. Osiris don't have hit change, fake duck, minimum direct damage, minimum wall bang damage, multipoint, multiple hit box, etc etc.

**Comment by xXTOO-HARDXx** [comment]
The aimbot in Osiris is by no means bad. It just wasn't written with rage hacking in mind.

Spinbot = aim and spinning antiaim.

**Comment by Deciy** [comment]
Fine how about we just get more anti aim options and a working min damage

**Comment by Deciy** [comment]
> Fatality.win
> Aimware.net
> Gamesense.pub
> Onetap.com
> orange.fanta.club
> 
> Why you want Spin in Orisis when so many better options available?

If we have one tap why do we have any of those other options? Your point doesn’t make sense

**Comment by Deciy** [comment]
> Fatality.win
> Aimware.net
> Gamesense.pub
> Onetap.com
> orange.fanta.club
> 
> Why you want Spin in Orisis when so many better options available?

The reason I want spin in Osiris is because it has a good silent aim. Also why not?

**Comment by Deciy** [comment]
I’m going to close this but I still would love rage on Osiris
