### ISSUE TITLE
csgo anticheat update

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#1825]
![Screenshot_2020-06-27-14-03-33-1](https://user-images.githubusercontent.com/65455170/85920762-25a2b900-b87f-11ea-8e7b-a5638fe59b04.png)

Have u guys tried this update
how we gonna inject osiris

**Comment by hyperxpro** [comment]
Duplicate of #1822

**Comment by newcommerdontblame** [comment]
Oh didint see

**Comment by king1919djdj** [comment]
so we don't have to worry about it ?
i use process hacker for injection
