### ISSUE TITLE
(REQUEST) Auto Jump Bug

### ISSUE THREAD

**Issue by koon666** [danielkrupinski/Osiris#1826]
someone give me the jump bug code for osiris source pls

**Comment by twangsriprasoet** [comment]
#1769 here's the working code. but you need to fix something to make it works. 😃

**Comment by twangsriprasoet** [comment]
fix with this. you'll see the difference.
[https://www.unknowncheats.me/forum/cs-go-releases/365274-jumpbug-source.html](url)

**Comment by koon666** [comment]
hi twangsriprasoet, can you give me your osiris source with jumpbug? I can't fix my srry

**Comment by twangsriprasoet** [comment]
Here's the code. [https://hatebin.com/enoqegfiwm](url)
Just put it into Misc.cpp and do the things to make it works.
but in `Hooks.cpp` need to call createmove after EnginePrediction.
// `pt2.z` can be custom value.

**Comment by newcommerdontblame** [comment]
https://github.com/danielkrupinski/Osiris/pull/1829
