### ISSUE TITLE
[REQUEST] Respect "Clean Player Names" game option

### ISSUE THREAD

**Issue by cookiedragon234** [danielkrupinski/Osiris#1827]
Would be nice if esp etc respected the Clean Player Names game option

**Comment by Floraly** [comment]
Set Chams to by player color would also be nice to distinguish the players by their team color :-)

**Comment by newcommerdontblame** [comment]
> Set Chams to by player color would also be nice to distinguish the players by their color :-)

it would be nice with player selectable legit aa resolver
