### ISSUE TITLE
[Bug report] Head dot attached to left-shoulder bone

### ISSUE THREAD

**Issue by xRevan116x** [danielkrupinski/Osiris#183]
This also affects aimbot. Even with 100% RCS on both axes, aimbot locks onto the shoulder instead of the head. My guess is entity bone placement is fucked.

See attached screens for more info.
Cheers :)

![20190513205330_1](https://user-images.githubusercontent.com/49450202/57609177-75161f00-75c2-11e9-98b7-ea418adddeaa.jpg)
![20190513210026_1](https://user-images.githubusercontent.com/49450202/57609178-75161f00-75c2-11e9-82a9-bc1122e5a7fb.jpg)

**Comment by xRevan116x** [comment]
I have not touched the source. 
I recompiled a few times to test it.

I did overwrite my existing outdated Profile each time. Could be that being fucked, but unlikely.

**Comment by Shaxzy** [comment]
Hmm.. I don’t know. For me the dot is perfectly on the head

**Comment by cojo1989** [comment]
For me also, but the dot is so big :)) bigger then the head xD
i don`t know why.

**Comment by xRevan116x** [comment]
Found the problem.
The workshop maps I was using were fucking up the models I guess. 

Vanilla maps work fine.
