### ISSUE TITLE
I think this cheat has been detected as my and one of friends account were VAC banned.

### ISSUE THREAD

**Issue by f-lat** [danielkrupinski/Osiris#1830]

**Comment by qQh3Tz** [comment]
Osiris is not detected, more likely your injector is.
Inject Osiris using [MemJect](https://github.com/danielkrupinski/MemJect) and use [VAC-Bypass](https://github.com/danielkrupinski/VAC-Bypass-Loader) for extra precaution so you'll be fine.

**Comment by f-lat** [comment]
Ok, thank you so much.

**Comment by Jujudo** [comment]
Osiris is detected!
