### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by OhMekzz** [danielkrupinski/Osiris#1831]
How do i add new features to osiris

**Comment by hyperxpro** [comment]
Using Brain and Visual Studio IDE.

**Comment by aljawary** [comment]
Require updated brain

**Comment by mazmamad** [comment]
lmao joke

**Comment by newcommerdontblame** [comment]
Why u guys so toxic lmao 

1 Download Github Desktop.
2 download master branch of osiris (clone on main page/open in desktop x-github-client://openRepo/https://github.com/danielkrupinski/Osiris)
3 click "current branch" on top of the github desktop app
4 click "New branch" button on top next to search box
5 use upstream/master
6 then when its created go into "current branch" again but this time click on the bottom most button choose a branch to merge in to branch.
7 then select the pull request you want to merge. 

or

https://www.learncpp.com/

**Comment by tirziz** [comment]
> Why u guys so toxic lmao
Because you can't learn how to code just by reading some random comments.

**Comment by tirziz** [comment]
> Why u guys so toxic lmao.

Because you can't learn how to code just by reading some random comments.
