### ISSUE TITLE
Crashing with Discord.. Maybe?

### ISSUE THREAD

**Issue by sserve-kr** [danielkrupinski/Osiris#1833]
I played csgo using Osiris, and working discord.
when i changed window to send message to my friend, game still working fine, but crashed while playing competitive match.

I don't know why, and I'm not sure if it's a crash with Discord, but it's probably because of Discord because it was fine when I played the first two competitive match.

\+ Discord window crashed too. Discord still working, but only window crashed

**Comment by xXTOO-HARDXx** [comment]
Discord may not of updated their hooks for CSGO, to compensate for the LoadLibrary update.

This is hard to diagnose.

**Comment by RyDeem** [comment]
disable discord overlay in discord settings

**Comment by sserve-kr** [comment]
crashing solved.. discord overlay caused csgo crash
thanks for help
