### ISSUE TITLE
Injectors for the new update?

### ISSUE THREAD

**Issue by Adim2P** [danielkrupinski/Osiris#1834]
Any new injectors I can use to bypass the new anti cheat method CSGO implemented?

**Comment by aljawary** [comment]
U can use this
`#define WIN_LEAN_AND_MEAN
#include <iostream>
#include <Windows.h>
#include <TlHelp32.h>
 
DWORD get_proc_id(const char* proc_name)
{
	DWORD proc_id = 0;
	auto* const h_snap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
 
	if (h_snap != INVALID_HANDLE_VALUE)
	{
		PROCESSENTRY32 proc_entry;
		proc_entry.dwSize = sizeof(proc_entry);
 
		if (Process32First(h_snap, &proc_entry))
		{
			do
			{
				if (!_stricmp(proc_entry.szExeFile, proc_name))
				{
					proc_id = proc_entry.th32ProcessID;
					break;
				}
			} while (Process32Next(h_snap, &proc_entry));
		}
	}
 
	CloseHandle(h_snap);
	return proc_id;
}
 
int main()
{
	const char* dll_path = R"(C:\Cheat\your guci cheat.dll)";
	const char* proc_name = "csgo.exe";
	DWORD proc_id = 0;
 
	while (!proc_id)
	{
		proc_id = get_proc_id(proc_name);
		Sleep(30);
	}
 
	auto* const h_proc = OpenProcess(PROCESS_ALL_ACCESS, 0, proc_id);
 
	if (h_proc && h_proc != INVALID_HANDLE_VALUE)
	{
		const LPVOID nt_open_file = GetProcAddress(LoadLibraryW(L"ntdll"), "NtOpenFile");
		if (nt_open_file)
		{
			char original_bytes[5];
			memcpy(original_bytes, nt_open_file, 5);
			WriteProcessMemory(h_proc, nt_open_file, original_bytes, 5, nullptr);
		}
		
		auto* loc = VirtualAllocEx(h_proc, nullptr, MAX_PATH, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
		WriteProcessMemory(h_proc, loc, dll_path, strlen(dll_path) + 1, nullptr);
		auto* const h_thread = CreateRemoteThread(h_proc, nullptr, 0, reinterpret_cast<LPTHREAD_START_ROUTINE>(LoadLibraryA), loc, 0, nullptr);
	
		if (h_thread) CloseHandle(h_thread);
	}
 
	if (h_proc) CloseHandle(h_proc);
	return 0;
}`

**Comment by aljawary** [comment]
#define WIN_LEAN_AND_MEAN
#include <iostream>
#include <Windows.h>
#include <TlHelp32.h>
 
DWORD get_proc_id(const char* proc_name)
{
	DWORD proc_id = 0;
	auto* const h_snap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
 
	if (h_snap != INVALID_HANDLE_VALUE)
	{
		PROCESSENTRY32 proc_entry;
		proc_entry.dwSize = sizeof(proc_entry);
 
		if (Process32First(h_snap, &proc_entry))
		{
			do
			{
				if (!_stricmp(proc_entry.szExeFile, proc_name))
				{
					proc_id = proc_entry.th32ProcessID;
					break;
				}
			} while (Process32Next(h_snap, &proc_entry));
		}
	}
 
	CloseHandle(h_snap);
	return proc_id;
}
 
int main()
{
	const char* dll_path = R"(C:\Cheat\your guci cheat.dll)";
	const char* proc_name = "csgo.exe";
	DWORD proc_id = 0;
 
	while (!proc_id)
	{
		proc_id = get_proc_id(proc_name);
		Sleep(30);
	}
 
	auto* const h_proc = OpenProcess(PROCESS_ALL_ACCESS, 0, proc_id);
 
	if (h_proc && h_proc != INVALID_HANDLE_VALUE)
	{
		const LPVOID nt_open_file = GetProcAddress(LoadLibraryW(L"ntdll"), "NtOpenFile");
		if (nt_open_file)
		{
			char original_bytes[5];
			memcpy(original_bytes, nt_open_file, 5);
			WriteProcessMemory(h_proc, nt_open_file, original_bytes, 5, nullptr);
		}
		
		auto* loc = VirtualAllocEx(h_proc, nullptr, MAX_PATH, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
		WriteProcessMemory(h_proc, loc, dll_path, strlen(dll_path) + 1, nullptr);
		auto* const h_thread = CreateRemoteThread(h_proc, nullptr, 0, reinterpret_cast<LPTHREAD_START_ROUTINE>(LoadLibraryA), loc, 0, nullptr);
	
		if (h_thread) CloseHandle(h_thread);
	}
 
	if (h_proc) CloseHandle(h_proc);
	return 0;
}

**Comment by VuBrian22** [comment]
Use Daniel's new [patch loader](https://github.com/danielkrupinski/OneByteLdr) for manual mapping injection and inject the cheat using an undetected injector using manual map. I personally use Process Hacker 2 as it uses a kernel driver for process management and I haven't ran into any detection issues ever since the beginning of 2020.

**Comment by aljawary** [comment]
u can use this

> #define WIN_LEAN_AND_MEAN
#include <iostream>
#include <Windows.h>
#include <TlHelp32.h>
 
DWORD get_proc_id(const char* proc_name)
{
	DWORD proc_id = 0;
	auto* const h_snap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
 
	if (h_snap != INVALID_HANDLE_VALUE)
	{
		PROCESSENTRY32 proc_entry;
		proc_entry.dwSize = sizeof(proc_entry);
 
		if (Process32First(h_snap, &proc_entry))
		{
			do
			{
				if (!_stricmp(proc_entry.szExeFile, proc_name))
				{
					proc_id = proc_entry.th32ProcessID;
					break;
				}
			} while (Process32Next(h_snap, &proc_entry));
		}
	}
 
	CloseHandle(h_snap);
	return proc_id;
}
 
int main()
{
	const char* dll_path = R"(C:\Cheat\your guci cheat.dll)";
	const char* proc_name = "csgo.exe";
	DWORD proc_id = 0;
 
	while (!proc_id)
	{
		proc_id = get_proc_id(proc_name);
		Sleep(30);
	}
 
	auto* const h_proc = OpenProcess(PROCESS_ALL_ACCESS, 0, proc_id);
 
	if (h_proc && h_proc != INVALID_HANDLE_VALUE)
	{
		const LPVOID nt_open_file = GetProcAddress(LoadLibraryW(L"ntdll"), "NtOpenFile");
		if (nt_open_file)
		{
			char original_bytes[5];
			memcpy(original_bytes, nt_open_file, 5);
			WriteProcessMemory(h_proc, nt_open_file, original_bytes, 5, nullptr);
		}
		
		auto* loc = VirtualAllocEx(h_proc, nullptr, MAX_PATH, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
		WriteProcessMemory(h_proc, loc, dll_path, strlen(dll_path) + 1, nullptr);
		auto* const h_thread = CreateRemoteThread(h_proc, nullptr, 0, reinterpret_cast<LPTHREAD_START_ROUTINE>(LoadLibraryA), loc, 0, nullptr);
	
		if (h_thread) CloseHandle(h_thread);
	}
 
	if (h_proc) CloseHandle(h_proc);
	return 0;
}

**Comment by VuBrian22** [comment]
> u can use this
> 
> > 
> 
> #define WIN_LEAN_AND_MEAN
> #include
> #include <Windows.h>
> #include <TlHelp32.h>
> 
> DWORD get_proc_id(const char* proc_name)
> {
> DWORD proc_id = 0;
> auto* const h_snap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
> 
> ```
> if (h_snap != INVALID_HANDLE_VALUE)
> {
> 	PROCESSENTRY32 proc_entry;
> 	proc_entry.dwSize = sizeof(proc_entry);
> 
> 	if (Process32First(h_snap, &proc_entry))
> 	{
> 		do
> 		{
> 			if (!_stricmp(proc_entry.szExeFile, proc_name))
> 			{
> 				proc_id = proc_entry.th32ProcessID;
> 				break;
> 			}
> 		} while (Process32Next(h_snap, &proc_entry));
> 	}
> }
> 
> CloseHandle(h_snap);
> return proc_id;
> ```
> 
> }
> 
> int main()
> {
> const char* dll_path = R"(C:\Cheat\your guci cheat.dll)";
> const char* proc_name = "csgo.exe";
> DWORD proc_id = 0;
> 
> ```
> while (!proc_id)
> {
> 	proc_id = get_proc_id(proc_name);
> 	Sleep(30);
> }
> 
> auto* const h_proc = OpenProcess(PROCESS_ALL_ACCESS, 0, proc_id);
> 
> if (h_proc && h_proc != INVALID_HANDLE_VALUE)
> {
> 	const LPVOID nt_open_file = GetProcAddress(LoadLibraryW(L"ntdll"), "NtOpenFile");
> 	if (nt_open_file)
> 	{
> 		char original_bytes[5];
> 		memcpy(original_bytes, nt_open_file, 5);
> 		WriteProcessMemory(h_proc, nt_open_file, original_bytes, 5, nullptr);
> 	}
> 	
> 	auto* loc = VirtualAllocEx(h_proc, nullptr, MAX_PATH, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
> 	WriteProcessMemory(h_proc, loc, dll_path, strlen(dll_path) + 1, nullptr);
> 	auto* const h_thread = CreateRemoteThread(h_proc, nullptr, 0, reinterpret_cast<LPTHREAD_START_ROUTINE>(LoadLibraryA), loc, 0, nullptr);
> 
> 	if (h_thread) CloseHandle(h_thread);
> }
> 
> if (h_proc) CloseHandle(h_proc);
> return 0;
> ```
> 
> }
> <

That would be creating extra work that not needed. On UC, where you got the code from it states that Daniel's new patch loader serves the same purpose but it's just simpler to use.

![image](https://user-images.githubusercontent.com/25190751/85979037-a99a9500-b994-11ea-911f-a1335dc1fb51.png)

**Comment by VuBrian22** [comment]
Just compile the [patch loader](https://github.com/danielkrupinski/OneByteLdr) and run it after you run the game but before you inject the cheat.

**Comment by craxking** [comment]
> Just compile the [patch loader](https://github.com/danielkrupinski/OneByteLdr) and execute it after you run the game but before you inject the cheat.

I might be wrong but i think this patch is for only bypassing load library injection
or do i have to use it for bypassing manual map injection as well?.. i am confused

**Comment by xXTOO-HARDXx** [comment]
@craxking Yes, you're right, it is. Because the new CSGO update only hooks `LoadLibraryW` and essentially replaces it. Daniel's byte patch writes the code for the original function back, so that it is no longer hooked.

Manual Mapping still works just as it did before.

**Comment by VuBrian22** [comment]
@craxking Yeah whoops my bad. It is actually for load library injection, sorry.

**Comment by Adim2P** [comment]
> @craxking Yeah whoops my bad. It is actually for load library injection, sorry.

Alright so, I can just compile the Patch Loader and run it when the game starts before I inject the cheat? Then I can use any previous injectors that I use to inject the cheat am I correct?

**Comment by TauCSGO** [comment]
> #define WIN_LEAN_AND_MEAN
> #include
> #include <Windows.h>
> #include <TlHelp32.h>
> 
> DWORD get_proc_id(const char* proc_name)
> {
> DWORD proc_id = 0;
> auto* const h_snap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
> 
> ```
> if (h_snap != INVALID_HANDLE_VALUE)
> {
> 	PROCESSENTRY32 proc_entry;
> 	proc_entry.dwSize = sizeof(proc_entry);
> 
> 	if (Process32First(h_snap, &proc_entry))
> 	{
> 		do
> 		{
> 			if (!_stricmp(proc_entry.szExeFile, proc_name))
> 			{
> 				proc_id = proc_entry.th32ProcessID;
> 				break;
> 			}
> 		} while (Process32Next(h_snap, &proc_entry));
> 	}
> }
> 
> CloseHandle(h_snap);
> return proc_id;
> ```
> 
> }
> 
> int main()
> {
> const char* dll_path = R"(C:\Cheat\your guci cheat.dll)";
> const char* proc_name = "csgo.exe";
> DWORD proc_id = 0;
> 
> ```
> while (!proc_id)
> {
> 	proc_id = get_proc_id(proc_name);
> 	Sleep(30);
> }
> 
> auto* const h_proc = OpenProcess(PROCESS_ALL_ACCESS, 0, proc_id);
> 
> if (h_proc && h_proc != INVALID_HANDLE_VALUE)
> {
> 	const LPVOID nt_open_file = GetProcAddress(LoadLibraryW(L"ntdll"), "NtOpenFile");
> 	if (nt_open_file)
> 	{
> 		char original_bytes[5];
> 		memcpy(original_bytes, nt_open_file, 5);
> 		WriteProcessMemory(h_proc, nt_open_file, original_bytes, 5, nullptr);
> 	}
> 	
> 	auto* loc = VirtualAllocEx(h_proc, nullptr, MAX_PATH, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
> 	WriteProcessMemory(h_proc, loc, dll_path, strlen(dll_path) + 1, nullptr);
> 	auto* const h_thread = CreateRemoteThread(h_proc, nullptr, 0, reinterpret_cast<LPTHREAD_START_ROUTINE>(LoadLibraryA), loc, 0, nullptr);
> 
> 	if (h_thread) CloseHandle(h_thread);
> }
> 
> if (h_proc) CloseHandle(h_proc);
> return 0;
> ```
> 
> }
> <

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0167	argument of type "WCHAR *" is incompatible with parameter of type "const char *"	
line	21	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'int _stricmp(const char *,const char *)': cannot convert argument 1 from 'WCHAR [260]' to 'const char *'	 
line 21

**Comment by VuBrian22** [comment]
> > #define WIN_LEAN_AND_MEAN
> > #include
> > #include <Windows.h>
> > #include <TlHelp32.h>
> > DWORD get_proc_id(const char* proc_name)
> > {
> > DWORD proc_id = 0;
> > auto* const h_snap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
> > ```
> > if (h_snap != INVALID_HANDLE_VALUE)
> > {
> > 	PROCESSENTRY32 proc_entry;
> > 	proc_entry.dwSize = sizeof(proc_entry);
> > 
> > 	if (Process32First(h_snap, &proc_entry))
> > 	{
> > 		do
> > 		{
> > 			if (!_stricmp(proc_entry.szExeFile, proc_name))
> > 			{
> > 				proc_id = proc_entry.th32ProcessID;
> > 				break;
> > 			}
> > 		} while (Process32Next(h_snap, &proc_entry));
> > 	}
> > }
> > 
> > CloseHandle(h_snap);
> > return proc_id;
> > ```
> > 
> > 
> > }
> > int main()
> > {
> > const char* dll_path = R"(C:\Cheat\your guci cheat.dll)";
> > const char* proc_name = "csgo.exe";
> > DWORD proc_id = 0;
> > ```
> > while (!proc_id)
> > {
> > 	proc_id = get_proc_id(proc_name);
> > 	Sleep(30);
> > }
> > 
> > auto* const h_proc = OpenProcess(PROCESS_ALL_ACCESS, 0, proc_id);
> > 
> > if (h_proc && h_proc != INVALID_HANDLE_VALUE)
> > {
> > 	const LPVOID nt_open_file = GetProcAddress(LoadLibraryW(L"ntdll"), "NtOpenFile");
> > 	if (nt_open_file)
> > 	{
> > 		char original_bytes[5];
> > 		memcpy(original_bytes, nt_open_file, 5);
> > 		WriteProcessMemory(h_proc, nt_open_file, original_bytes, 5, nullptr);
> > 	}
> > 	
> > 	auto* loc = VirtualAllocEx(h_proc, nullptr, MAX_PATH, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
> > 	WriteProcessMemory(h_proc, loc, dll_path, strlen(dll_path) + 1, nullptr);
> > 	auto* const h_thread = CreateRemoteThread(h_proc, nullptr, 0, reinterpret_cast<LPTHREAD_START_ROUTINE>(LoadLibraryA), loc, 0, nullptr);
> > 
> > 	if (h_thread) CloseHandle(h_thread);
> > }
> > 
> > if (h_proc) CloseHandle(h_proc);
> > return 0;
> > ```
> > 
> > 
> > }
> > <
> 
> Severity Code Description Project File Line Suppression State
> Error (active) E0167 argument of type "WCHAR *" is incompatible with parameter of type "const char *"
> line 21
> 
> Severity Code Description Project File Line Suppression State
> Error C2664 'int _stricmp(const char *,const char *)': cannot convert argument 1 from 'WCHAR [260]' to 'const char *'
> line 21

Don't use that code. Use the loader for load library injection that Daniel made instead.
