### ISSUE TITLE
Crash csgo after inject

### ISSUE THREAD

**Issue by unnamed01X** [danielkrupinski/Osiris#1835]
i got a problem, after inject the game is crashing instantlly, im using rando injector. Any ideas?

**Comment by newcommerdontblame** [comment]
Change ur injector nothin wrong with cheat

**Comment by unnamed01X** [comment]
that's not true. I downloaded the osiris again, compiled and inject it by Randoinjector, everything was fine.
But my version of Osiris is new as well, yesterday it worked. What happend? I didnt change anything there, and there's dll from 27.07.2020, was working yesterday, since today it's getting crashed
(sorry for trash english)

**Comment by unnamed01X** [comment]
never mind xD
