### ISSUE TITLE
How to make ESP disappear for overwolf

### ISSUE THREAD

**Issue by Yodawg-Osirisuser** [danielkrupinski/Osiris#1838]
If you don't know what Overwolf is it basically is a recording platform that records your highlights however when recording it shows Esp and I don't know why but that's annoying too me. Is there any way to make it not record the esp?

**Comment by AlisaCiya** [comment]
Use GOESP

**Comment by Yodawg-Osirisuser** [comment]
> Use GOESP

I wish I could but Visual Studio doesn't work for me.

**Comment by RyDeem** [comment]
Then make visual studio work for you?

**Comment by caiocinel** [comment]
> > Use GOESP
> 
> I wish I could but Visual Studio doesn't work for me. It would work if I had an easy Winrar download that works with process hacker, however I don't know how to make one. It would be nice if someone could explain how to make a Winrar file like that or if someone could just do it for me.

 Have a infinite of cheating forums with GOESP and Osiris files, just download and inject.

**Comment by Yodawg-Osirisuser** [comment]
> > > Use GOESP
> > 
> > 
> > I wish I could but Visual Studio doesn't work for me. It would work if I had an easy Winrar download that works with process hacker, however I don't know how to make one. It would be nice if someone could explain how to make a Winrar file like that or if someone could just do it for me.
> 
> There a lot of infinite of cheating forums with GOESP and Osiris files, just download and inject.

I am dumb why didn't I think of that?
