### ISSUE TITLE
canScan function doesnt have a working min damage

### ISSUE THREAD

**Issue by notgoodusename** [danielkrupinski/Osiris#1839]
You can test this by putting 250 as min damage and aimlock on, bone nearest, it should target the head or just dont target anything

**Comment by xXTOO-HARDXx** [comment]
You didnt even say what **does** happen... so?

**Comment by notgoodusename** [comment]
> You didnt even say what **does** happen... so?

it targest the nearest bone and stays there, when it should target the bone head

**Comment by xXTOO-HARDXx** [comment]
> > You didnt even say what **does** happen... so?
> 
> it targest the nearest bone and stays there, when it should target the head

Ah, I see what you mean. But, then again, why would you ever use a value of 250 for min damage? Min damage is meant to be used in values up to 100. Because otherwise it isn't practical.

**Comment by notgoodusename** [comment]
> > > You didnt even say what **does** happen... so?
> > 
> > 
> > it targest the nearest bone and stays there, when it should target the head
> 
> Ah, I see what you mean. But, then again, why would you ever use a value of 250 for min damage? Min damage is meant to be used in values up to 100. Because otherwise it isn't practical.

its just an example that mindamage isnt working as it should

**Comment by xXTOO-HARDXx** [comment]
> > > > You didnt even say what **does** happen... so?
> > > 
> > > 
> > > it targest the nearest bone and stays there, when it should target the head
> > 
> > 
> > Ah, I see what you mean. But, then again, why would you ever use a value of 250 for min damage? Min damage is meant to be used in values up to 100. Because otherwise it isn't practical.
> 
> its just an example that mindamage isnt working as it should

but, by design, MinDamage is for determining whether you will do a certain amount of damage or similar. Buttttt, since players cannot take any more than 100 damage without dying, MinDamage DOES work as it's meant to. Because 250 is simply out of the bounds of the application at hand; killing someone.

**Comment by MiniPEACECloset** [comment]
if you put the min dmg on 70 and bone nearest it will still snap on nearest that will not be head. and when the head is visible it will just stay at the previous hitbox it

**Comment by notgoodusename** [comment]
i think u dont understand what the canScan function does
On the aimbot before checking if it is closer to the crosshair, it checks the damage it can do to that bone position, it returns damage >= mindamage, meaning that if the damage it can do is below min damage it wont target that, and the mindamage is only clamped on gui to 250 and 0
