### ISSUE TITLE
Imgui Menu issue

### ISSUE THREAD

**Issue by Lemzer** [danielkrupinski/Osiris#1841]
Hello!

I am currently trying to implement the `Gamesense ImGui` menu, found on a different online forum. (Not sure if I can link it).

So far everything compiles but after I try to inject, I get the following error after attaching the debugger: `No current context. Did you call ImGui::CreateContext() and ImGui::SetCurrentContext() ?`.

I assume it is because I have replaced some ImGui files with the new version.

I am wondering if someone could help me with this, since it should not be really hard since the whole Gamesense menu (the ImGui version) is already downloadable from the forums. But implementing it, is for me, the hardest part.

I am not active on Github so if someone could help me, please leave your Discord and I'll add you. Afterwards I will post my solution here, so this is not an useless issue.

Thanks a lot.

**Comment by xXTOO-HARDXx** [comment]
> Hello!
> 
> I am currently trying to implement the `Gamesense ImGui` menu, found on a different online forum. (Not sure if I can link it).
> 
> So far everything compiles but after I try to inject, I get the following error after attaching the debugger: `No current context. Did you call ImGui::CreateContext() and ImGui::SetCurrentContext() ?`.
> 
> I assume it is because I have replaced some ImGui files with the new version.
> 
> I am wondering if someone could help me with this, since it should not be really hard since the whole Gamesense menu (the ImGui version) is already downloadable from the forums. But implementing it, is for me, the hardest part.
> 
> I am not active on Github so if someone could help me, please leave your Discord and I'll add you. Afterwards I will post my solution here, so this is not an useless issue.
> 
> Thanks a lot.

VS Debugger **literally** told you what you need to do.

When you get the error, it will also show you what line in your code is causing the issue. Call `ImGui::CreateContext()` before the line you get.

Also, yes, of course you can post links. This is GitHub, not UC.

**Comment by RyDeem** [comment]
lol, thease people.. "what do i do with this error? (ERROR: Do this) ???????"
id understand if it was like ERROR 1038: Discombobulating the secular tree failed at orange moon 2

**Comment by Lemzer** [comment]
> > Hello!
> > I am currently trying to implement the `Gamesense ImGui` menu, found on a different online forum. (Not sure if I can link it).
> > So far everything compiles but after I try to inject, I get the following error after attaching the debugger: `No current context. Did you call ImGui::CreateContext() and ImGui::SetCurrentContext() ?`.
> > I assume it is because I have replaced some ImGui files with the new version.
> > I am wondering if someone could help me with this, since it should not be really hard since the whole Gamesense menu (the ImGui version) is already downloadable from the forums. But implementing it, is for me, the hardest part.
> > I am not active on Github so if someone could help me, please leave your Discord and I'll add you. Afterwards I will post my solution here, so this is not an useless issue.
> > Thanks a lot.
> 
> VS Debugger **literally** told you what you need to do.
> 
> When you get the error, it will also show you what line in your code is causing the issue. Call `ImGui::CreateContext()` before the line you get.
> 
> Also, yes, of course you can post links. This is GitHub, not UC.
> 
> EDIT: I encourage you to post the link, because that would make things so much easier for anyone willing to answer.

https://corsair.wtf/topic/1429-every-gamesense-menu-clone-ever/ Number 1.

> lol, thease people.. "what do i do with this error? (ERROR: Do this) ???????"
> id understand if it was like ERROR 1038: Discombobulating the secular tree failed at orange moon 2, now thats a doozy.


I have obviously already tried to do what the error gives me. Sad that @RyDeem knows everything better, so how about you tell me what's wrong?

I have tried to create a context and also tried to set a context but it does not work since it gave the same error :')
I have also compared my GUI version with the original and the only difference is, some imgui files got replaced so there might be an issue internally.

**Comment by xXTOO-HARDXx** [comment]
> > > Hello!
> > > I am currently trying to implement the `Gamesense ImGui` menu, found on a different online forum. (Not sure if I can link it).
> > > So far everything compiles but after I try to inject, I get the following error after attaching the debugger: `No current context. Did you call ImGui::CreateContext() and ImGui::SetCurrentContext() ?`.
> > > I assume it is because I have replaced some ImGui files with the new version.
> > > I am wondering if someone could help me with this, since it should not be really hard since the whole Gamesense menu (the ImGui version) is already downloadable from the forums. But implementing it, is for me, the hardest part.
> > > I am not active on Github so if someone could help me, please leave your Discord and I'll add you. Afterwards I will post my solution here, so this is not an useless issue.
> > > Thanks a lot.
> > 
> > 
> > VS Debugger **literally** told you what you need to do.
> > When you get the error, it will also show you what line in your code is causing the issue. Call `ImGui::CreateContext()` before the line you get.
> > Also, yes, of course you can post links. This is GitHub, not UC.
> > EDIT: I encourage you to post the link, because that would make things so much easier for anyone willing to answer.
> 
> https://corsair.wtf/topic/1429-every-gamesense-menu-clone-ever/ Number 1.
> 
> > lol, thease people.. "what do i do with this error? (ERROR: Do this) ???????"
> > id understand if it was like ERROR 1038: Discombobulating the secular tree failed at orange moon 2, now thats a doozy.
> 
> I have obviously already tried to do what the error gives me. Sad that @RyDeem knows everything better, so how about you tell me what's wrong?
> 
> I have tried to create a context and also tried to set a context but it does not work since it gave the same error :')
> I have also compared my GUI version with the original and the only difference is, some imgui files got replaced so there might be an issue internally.

I am downloading it and checking it out now.

**Comment by Lemzer** [comment]
@xXTOO-HARDXx Really strange, glad it is working for you. Could I add you on Discord?

**Comment by RyDeem** [comment]
When you get the error, it will also show you what line in your code is causing the issue. Call ImGui::CreateContext() before the line you get.

**Comment by Lemzer** [comment]
> When you get the error, it will also show you what line in your code is causing the issue. Call ImGui::CreateContext() before the line you get.
> 
> I might have came on a bit hard before, but srs, this error explains itself, most dont.

My man, I know. I have added the `ImGui::CreateContext()` to all places where I possibly could. In the main GUI function where the menu gets initialized and also one line before the error even happens. I am glad that @xXTOO-HARDXx doesn't have this issue but I still get the same issue so I am not sure what happened. But I would like to see the source where @xXTOO-HARDXx is working in, since that one works.

**Comment by xXTOO-HARDXx** [comment]
> > When you get the error, it will also show you what line in your code is causing the issue. Call ImGui::CreateContext() before the line you get.
> > I might have came on a bit hard before, but srs, this error explains itself, most dont.
> 
> My man, I know. I have added the `ImGui::CreateContext()` to all places where I possibly could. In the main GUI function where the menu gets initialized and also one line before the error even happens. I am glad that @xXTOO-HARDXx doesn't have this issue but I still get the same issue so I am not sure what happened. But I would like to see the source where @xXTOO-HARDXx is working in, since that one works.

Sure. Comment your Discord here if you'd like to show me your code or something, I'll add you.

I never post my Discord anywhere publicly. Sorry.

**Comment by Lemzer** [comment]
> > > When you get the error, it will also show you what line in your code is causing the issue. Call ImGui::CreateContext() before the line you get.
> > > I might have came on a bit hard before, but srs, this error explains itself, most dont.
> > 
> > 
> > My man, I know. I have added the `ImGui::CreateContext()` to all places where I possibly could. In the main GUI function where the menu gets initialized and also one line before the error even happens. I am glad that @xXTOO-HARDXx doesn't have this issue but I still get the same issue so I am not sure what happened. But I would like to see the source where @xXTOO-HARDXx is working in, since that one works.
> 
> Sure. Comment your Discord here if you'd like to show me your code or something, I'll add you.
> 
> I never post my Discord anywhere publicly. Sorry.

https://discord.gg/D3PPVF Me neither actually so just join the server, it's just me.

**Comment by Shaxzy** [comment]
@Lemzer were you able to solve it?

**Comment by Lemzer** [comment]
> @Lemzer were you able to solve it?

Yes, the menu got implemented from scratch again by @xXTOO-HARDXx and all the errors were fixed.

I do experience a couple of weird issues but will try to fix those.

**Comment by koahook** [comment]
Would you like to help me add this menu into osiris Lemzer or send me the gui?
