### ISSUE TITLE
help me, what should i do? (engine)

### ISSUE THREAD

**Issue by unnamed01X** [danielkrupinski/Osiris#1843]
http://prntscr.com/tajtup

what's going on? with what should i replace localplayer?

**Comment by aljawary** [comment]
Try localPlayer.get()

**Comment by unnamed01X** [comment]
http://prntscr.com/talnt7
still doesnt work

**Comment by NekoRem** [comment]
> http://prntscr.com/talnt7
> still doesnt work

![Capture](https://user-images.githubusercontent.com/31341992/86401316-eec70b80-bca1-11ea-86a7-58b1917c0118.PNG)

remove that and make it only localPlayer.get()

**Comment by unnamed01X** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/62210471/86402972-0d7ecf80-bcad-11ea-8cc3-e094306ccc03.png)
something is wrong, i remove that thing @NekoRem 
the error is in polish but google translate gives that: "cannot be used before it is initialized"

**Comment by NekoRem** [comment]
> ![Screenshot_3](https://user-images.githubusercontent.com/62210471/86402972-0d7ecf80-bcad-11ea-8cc3-e094306ccc03.png)
> something is wrong, i remove that thing @NekoRem
> the error is in polish but google translate gives that: "cannot be used before it is initialized"
do you have localPlayer.h?

**Comment by unnamed01X** [comment]
yes, it's the newest osiris source code

**Comment by NekoRem** [comment]
get rid of the `auto localPlayer  = interfaces->entitylist->getentity` definition and just use localPlayer instead

**Comment by unnamed01X** [comment]
> get rid of the `auto localPlayer = interfaces->entitylist->getentity` definition and just use localPlayer instead

i do not understand that, idk what's going on, i cannot add anything with localplayer, even if i use the newest Osiris version with localplayer.h and tryting to implement that by localPlayer.get()

**Comment by NekoRem** [comment]
send the code and i will correct it to show you what i mean

**Comment by unnamed01X** [comment]
just tell me where could i find that and then i will send you that

**Comment by NekoRem** [comment]
> just tell me where could i find that and then i will send you that

i don't understand what you just said...

**Comment by NekoRem** [comment]
just add me on discord ReaSanka 散華 礼弥#7074
