### ISSUE TITLE
FPS issue.

### ISSUE THREAD

**Issue by AbhinayNegi** [danielkrupinski/Osiris#1845]
Osiris is the best hack but for the past 1 month updates, it is causing a huge fps drop issue. Without hack, my FPS is 60 but after hack is injected my fps drops and stays between 20 and 15. Please fix this issue.

**Comment by notgoodusename** [comment]
I think is posible that the new hooks may be dropping fps

**Comment by newcommerdontblame** [comment]
Same. it was boosting my fps.. nowadays it fucked up

**Comment by AbhinayNegi** [comment]
> I think is possible that the new hooks may be dropping fps

There was an update came I think 1 or 2 weeks ago that was working perfectly without any issue. But again new update came which is again causing fps drop.

**Comment by xXTOO-HARDXx** [comment]
Yes, it is because of MinHook. MinHook is more performance costly.

**VMT** is the most performance efficient.
**.text** patching is in the middle generally **(MinHook)**.
**Detours** are the slowest of the three.

**Comment by AbhinayNegi** [comment]
> Yes, it is because of MinHook. MinHook is more performance costly.
> 
> **VMT** is the most performance efficient.
> **.text** patching is in the middle generally (MinHook).
> **Detours** are the slowest of the three.

So it means MinHook is very important.

**Comment by xXTOO-HARDXx** [comment]
> > Yes, it is because of MinHook. MinHook is more performance costly.
> > **VMT** is the most performance efficient.
> > **.text** patching is in the middle generally (MinHook).
> > **Detours** are the slowest of the three.
> 
> So it means MinHook is very important.

Sort of... MinHook is the reason for the crap FPS and there's not much you can do about it.

**Comment by notgoodusename** [comment]
You can change from minhook to the old method of hooking (Vmt)
Its a 1 line change 
1. Go to Hooks.h
2. Look for the line `using HookType = MinHook;`
3. Change MinHook to VmtSwap

**Comment by 4u7157** [comment]
also if your cpu support's AVX2 you could try to enable that in visualstudio settings. will help aswell

**Comment by lerrific** [comment]
What was the reason to change the hooking to a slower method anyway?

**Comment by xXTOO-HARDXx** [comment]
> What was the reason to change the hooking to a slower method anyway?

The VMT hooking in the previous versions was detected by VAC.
