### ISSUE TITLE
Help !

### ISSUE THREAD

**Issue by ProJay210** [danielkrupinski/Osiris#1848]
OK i cannot compile this on vs 2017 v141, is there any workaround since the requirement suggests v142 and i do not want to upgrade it to v142.

**Comment by Floraly** [comment]
Retargef your project to toolset v141 should work. But I recommend you to use always latest toolset to keep up with Microsoft development.

**Comment by ProJay210** [comment]
I did change it to v141 but i get bunch of error. The source was completely pure. I downloaded it, changed properties and build the solution.
![image](https://user-images.githubusercontent.com/49186177/86535926-5929b700-bf01-11ea-86eb-165ab3a9111a.png)


![image](https://user-images.githubusercontent.com/49186177/86535969-b58cd680-bf01-11ea-9891-e0cafc36214b.png)

**Comment by Shuvi-Moro** [comment]
![Screenshot_20200705-195800-1](https://user-images.githubusercontent.com/63977167/86537743-10223480-befa-11ea-8715-9291f987b786.jpg)
You can search these error codes in Google and solve the problem yourself. Why contact us?

**Comment by techzin** [comment]
Use Visual Studio 2019 with toolset v142

**Comment by techzin** [comment]
Use last SDK Version
