### ISSUE TITLE
ManualMap Not workingt

### ISSUE THREAD

**Issue by techzin** [danielkrupinski/Osiris#1849]
I was trying to test some injectors, and I realized that ManualMap doesn’t work with Osiris, maybe the reason for this is osiris’s EntryPoint method, which only seems compatible with LoadLibrary, this is complicated with the new CS: GO BETA, it detects the DLL, so ManualMap, remove the traces of the DLL so that anticheat does not detect it

**Comment by NekoRem** [comment]
> I was trying to test some injectors, and I realized that ManualMap doesn’t work with Osiris, maybe the reason for this is osiris’s EntryPoint method, which only seems compatible with LoadLibrary, this is complicated with the new CS: GO BETA, it detects the DLL, so ManualMap, remove the traces of the DLL so that anticheat does not detect it

Its the injector... manual mapping works fine for me

**Comment by techzin** [comment]
> > I was trying to test some injectors, and I realized that ManualMap doesn’t work with Osiris, maybe the reason for this is osiris’s EntryPoint method, which only seems compatible with LoadLibrary, this is complicated with the new CS: GO BETA, it detects the DLL, so ManualMap, remove the traces of the DLL so that anticheat does not detect it
> 
> Its the injector... manual mapping works fine for me
I tested with Ayyhook Manualmap, Xenos Injector, Extreme Injector and C# OpenSource ManualMap

**Comment by techzin** [comment]
Only Osíris Crash, another cheat works fine.

**Comment by mazmamad** [comment]
close this

**Comment by danielkrupinski** [comment]
It's your injector's fault, you can try debugging to see why it crashes.

**Comment by techzin** [comment]
> > Eu estava tentando testar alguns injetores e percebi que o ManualMap não funciona com Osiris, talvez o motivo seja o método EntryPoint da osiris, que apenas parece compatível com o LoadLibrary, isso é complicado com o novo CS: GO BETA, ele detecta a DLL, portanto ManualMap, remova os rastreamentos da DLL para que o anticheat não a detecte
> 
> É o injetor ... o mapeamento manual funciona bem para mim

whats injector you use?

**Comment by NekoRem** [comment]
> > > Eu estava tentando testar alguns injetores e percebi que o ManualMap não funciona com Osiris, talvez o motivo seja o método EntryPoint da osiris, que apenas parece compatível com o LoadLibrary, isso é complicado com o novo CS: GO BETA, ele detecta a DLL, portanto ManualMap, remova os rastreamentos da DLL para que o anticheat não a detecte
> > 
> > 
> > It's the injector ... manual mapping works well for me
> 
> whats injector you use?

My own since they’re easy to make
