### ISSUE TITLE
Takes longer to join games 

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1850]
Takes longer to join a map with osiris

**Comment by HowToMakeFaceitAB** [comment]
I use other cheats and it only happens with osiris

**Comment by danielkrupinski** [comment]
Have you measured the time? Bear in mind that first map loading takes more time because assets haven't been cached yet.

**Comment by HowToMakeFaceitAB** [comment]
> Have you measured the time? Bear in mind that first map loading takes more time because assets haven't been cached yet.

Yes, i've found it only happens on local game servers and not on community / valve server, as for the time, it's usually 3-4m( takes 2 - 2:30 without osiris) sometimes it crashes if i try to go into a local game server again, i'll attach a debugger if u want?

**Comment by danielkrupinski** [comment]
That would be helpful.

**Comment by HowToMakeFaceitAB** [comment]
> That would be helpful.

Okay, will do! Sorry for super late reply, i wasn't home, right now its night, i will give you info tmr

**Comment by HowToMakeFaceitAB** [comment]
> That would be helpful.

Sorry, due to unfortunate circumstances i can't attach a debugger
