### ISSUE TITLE
fix drawAimbotFov & Time watermark

### ISSUE THREAD

**Issue by sserve-kr** [danielkrupinski/Osiris#1852]
I found local player..
no error, successfully built.
![image](https://user-images.githubusercontent.com/61446372/86581382-ff85c300-bfba-11ea-9cfb-6a8562f7453d.png)

but not working.
is there a problem with my code?

**Comment by sserve-kr** [comment]
I found it... But is this right code?
no error found.
![image](https://user-images.githubusercontent.com/61446372/86581382-ff85c300-bfba-11ea-9cfb-6a8562f7453d.png)

**Comment by Kron1Q** [comment]
Maybe you are not calling that func?

**Comment by sserve-kr** [comment]
![image](https://user-images.githubusercontent.com/61446372/86723002-76c26200-c062-11ea-8bce-6ac7139dc40d.png)
on hooks.cpp.
is this  right code?

and, i want to create time  watermark.
but this code gave me error.
i am new to C++, sorry for stupid question,
but how to fix it?
```C++
const auto time = std::time(nullptr);
const auto localTime = std::localtime(&time);
char s[11];
sprintf_s(s, "[%02d:%02d:%02d]", localTime->tm_hour, localTime->tm_min, localTime->tm_sec);
interfaces->surface->setTextPosition(25, 0);
const auto nowtime{ L"T: " + s };
interfaces->surface->printText(nowtime.c_str());
```

**Comment by sserve-kr** [comment]
Fixed.
