### ISSUE TITLE
Make valorant hack like this one 

### ISSUE THREAD

**Issue by xmine7890** [danielkrupinski/Osiris#1854]

**Comment by aljawary** [comment]
close this

**Comment by xmine7890** [comment]
> close this

do you have valorant hack??

**Comment by m0nsterJ** [comment]
do you have brain???

**Comment by Shuvi-Moro** [comment]
> do you have brain???

He don't have brain

**Comment by barbadully** [comment]
fucking kill urself lmao

**Comment by kermacide** [comment]
> > close this
> 
> do you have valorant hack??

i have valorant hack you want man?

**Comment by kvetinkavole** [comment]
no. Close.
