### ISSUE TITLE
Tabbar column

### ISSUE THREAD

**Issue by kvetinkavole** [danielkrupinski/Osiris#1856]
when i use ImGui::NextColumn(); in the tabbar it hide/move (idk) other tabs
With ImGui::NextColumn(); :
https://gyazo.com/53a5ac2c56707880cae8b056c685768e
Withount:
https://gyazo.com/652c5dac66190f0f28d8bb4c3bef4971
Someone help me with fix? Thanks. / how to use column in tabbar

**Comment by icantfindausernamelol** [comment]
Buttons

**Comment by kvetinkavole** [comment]
> 
> 
> Buttons

 What you mean ?

**Comment by xXTOO-HARDXx** [comment]
Why are you trying to change column anyway?

And it's probably helpful if you show where in the code you use NextColumn so I can see the context

**Comment by kvetinkavole** [comment]
> 
> 
> Why are you trying to change column anyway?
> 
> And it's probably helpful if you show where in the code you use NextColumn so I can see the context

im fix it by myself. Bcs im remaking the menu, adding some features...

**Comment by xXTOO-HARDXx** [comment]
> > Why are you trying to change column anyway?
> > And it's probably helpful if you show where in the code you use NextColumn so I can see the context
> 
> im fix it by myself. Bcs i remaking the menu, adding some features...

Well that makes matters worse, because that means I don't even know you're doing at all. Cause your code won't match anything I can read myself.

Show code or no one can help.
