### ISSUE TITLE
Osiris Update

### ISSUE THREAD

**Issue by DaghanKurt** [danielkrupinski/Osiris#1857]
hi guys i needed to ask this question everytime when osiris updates should i need to download again like with new files osiris.sln ?

**Comment by kvetinkavole** [comment]
just change the code in specify files

**Comment by DaghanKurt** [comment]
like changing the new files to the old files

**Comment by newcommerdontblame** [comment]
> like changing the new files to the old files

just download githubdesktop then u can easily update ur cheat when daniel updated

**Comment by DaghanKurt** [comment]
yea i downloaded the new version bıt everyday its updated 😔
