### ISSUE TITLE
Osiris Config

### ISSUE THREAD

**Issue by DaghanKurt** [danielkrupinski/Osiris#1858]
hi the osiris works fine 👏 but i want to save the config but when i go to documents the osiris file was gone this story happend a week ago i droped a little my laptop and like the E driver broke down and it didnt work E driver was gone the documents was in the E drive but now i transferd the documents to Program Files 86 idk why i did that but now how can i save my config ![image](https://user-images.githubusercontent.com/68009235/86962633-ea9c6180-c16b-11ea-8c82-eb86da966da1.jpeg)

this is the document file now

**Comment by xXTOO-HARDXx** [comment]
> hi the osiris works fine  but i want to save the config but when i go to documents the osiris file was gone this story happend a week ago i droped a little my laptop and like the E driver broke down and it didnt work E driver was gone the documents was in the E drive but now i transferd the documents to Program Files 86 idk why i did that but now how can i save my config ![image](https://user-images.githubusercontent.com/68009235/86962633-ea9c6180-c16b-11ea-8c82-eb86da966da1.jpeg)
> 
> this is the document file now

Osiris uses a path reference to get the path to your current Users' documents (e.g. `C:\\Users\\xxx\\Documents`) and then points to the Osiris directory inside. If the directory doesn't exist it will create a new Osiris folder.

Try putting your old Osiris folder from your old documents folder into your standard documents folder. Found at `C:\Users\xxx\Documents`

Good luck.

**Comment by kvetinkavole** [comment]
specify full link in Osiris.cpp
