### ISSUE TITLE
After the last CSGO update, I cant Inyect Osiris... Any Idea?

### ISSUE THREAD

**Issue by SuperK2-OS** [danielkrupinski/Osiris#1860]
Next Steps ?

Im a osiris Junk ! hehehhe

**Comment by xXTOO-HARDXx** [comment]
do you receive a message on the main menu when you inject saying that it was blocked?

**Comment by SuperK2-OS** [comment]
Simply I cant inject any DLL ... no messages ... my firends has "Pay" Cheats and works fine.

I´m Sad

xDD

**Comment by xXTOO-HARDXx** [comment]
> Simply I cant inject any DLL ... no messages ... my firends has "Pay" Cheats and works fine.
> 
> I´m Sad
> 
> xDD

Two things you can do:
1. Try launching CSGO with -insecure to see if that helps.
2. Try using a different injector; process hacker 2 for example.

**Comment by kermacide** [comment]
https://github.com/AMATEURZ1337/load-lib-injector

**Comment by afulsamet** [comment]
VAC doesn't just allow you to inject(LoadLibrary) unsigned DLL's after the last update.
Use a ManualMap or KernelManualMap injectors.

**Comment by SuperK2-OS** [comment]
I wil try Thank you so much !!!

**Comment by YanderewareDev** [comment]
Just use injector that bypasses new DLL protection. Or use Daniel's OneByteLdr

**Comment by AbhinayNegi** [comment]
> Just use injector that bypasses new DLL protection. Or use Daniel's OneByteLdr.

How to use this injector.

**Comment by AbhinayNegi** [comment]
> VAC doesn't just allow you to inject(LoadLibrary) unsigned DLL's after the last update.
> Use a ManualMap or KernelManualMap injectors.

I have use 3 injector 2 of them has ManualMap feature but every time I inject dll the csgo crashes. If I am not using manualmap then there is no effect in-game.

**Comment by Guanzhe** [comment]
> I wil try Thank you so much !!! And I will give you Feedback !!

and then??how about??
