### ISSUE TITLE
New CS:GO anti-cheat update prevents from injection

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#1861]
Currently using Process Hacker 2 and it doesn't inject at all. Looks like a good anticheat update at last

**Comment by kermacide** [comment]
https://github.com/AMATEURZ1337/load-lib-injector

**Comment by samplics** [comment]
> https://github.com/AMATEURZ1337/load-lib-injector

Fails when I try to build it :|

**Comment by samplics** [comment]
https://gyazo.com/43ae9988e98102a9be949123965c687e

**Comment by VuBrian22** [comment]
@samplics There's a release tab for that: https://github.com/AMATEURZ1337/load-lib-injector/releases/tag/1.0

**Comment by DaghanKurt** [comment]
yo i build it and it has not prob but u need to build it with release 86 and make osiris cheat.dll rename it

**Comment by Shuvi-Moro** [comment]
https://vk.com/video268543085_456239717
ez))) thanks

**Comment by BohanRen** [comment]
try this [https://github.com/BohanRen/BobHCSGOInjector](https://github.com/BohanRen/BobHCSGOInjector)

**Comment by Guanzhe** [comment]
it is a good issue
