### ISSUE TITLE
THIS INJECTOR IS WORKING

### ISSUE THREAD

**Issue by DaghanKurt** [danielkrupinski/Osiris#1862]
guys this injector is working https://github.com/AMATEURZ1337/load-lib-injector  

when u setup the sln file do relase 86 and rename osiris cheat.dll when the setup is done just open cs and drag the "cheat.dll" with the injector and its done ![Uploading 87003542...]()

**Comment by Kraken69** [comment]
Im playing csgo after 6 months. Can u confirm that this cheat and injector is still safe?

**Comment by DaghanKurt** [comment]
yes the injector is safe the same producer made it

**Comment by Kraken69** [comment]
Does this cheat still work? I heard csgo made anticheat update where third party programs cant run csgo

**Comment by DaghanKurt** [comment]
yeah this cheat still works with this injector

**Comment by Kraken69** [comment]
Do u know anyone who gives compiled version of osiris on yt?

**Comment by DemonOfSelzar** [comment]
I used to use this and its fine. How exactly do I drag the dll and the injector into cs and where should i put the cheat.dll?

**Comment by DaghanKurt** [comment]
like open the injector with cheat dll

**Comment by Kraken69** [comment]
Does anyone know a youtuber who makes osiris cheats which are not fake?

**Comment by DemonOfSelzar** [comment]
I loaded the game and ran the cheat.dll with the injector and the injector says that it cannot find the cheat.dll and closes

**Comment by DemonOfSelzar** [comment]
@Kraken69 bhop made a video of it a few days ago. https://www.youtube.com/watch?v=YsxZHhdO5Q0.
Just compile the cheat with visual studio. Its not that hard.

**Comment by DaghanKurt** [comment]
> I loaded the game and ran the cheat.dll with the injector and the injector says that it cannot find the cheat.dll and closes
> 
> 

no no u need to like drag the cheat dll to the injector like open toghether at the same time

**Comment by DemonOfSelzar** [comment]
Yeah I did it nvm

**Comment by Kraken69** [comment]
It says cannot find proccessIDinjection failed

**Comment by king1919djdj** [comment]
u keep the cheat.dll in the same folder as the release 
do rename whichever dll u are u sing to cheat.dll
