### ISSUE TITLE
OSIRIS LEGIT CONFIG

### ISSUE THREAD

**Issue by DaghanKurt** [danielkrupinski/Osiris#1863]
yeah i need one can i get one

**Comment by DemonOfSelzar** [comment]
I can make one once I get it running.

**Comment by xXTOO-HARDXx** [comment]
Bruh. I'm sorry, but this is a fucking issue section. Not a config section on a forum.

There's plenty of sites you can find that have Osiris Configs. Namely, https://corsair.wtf/
