### ISSUE TITLE
I need an undetected injector for osiris

### ISSUE THREAD

**Issue by Kraken69** [danielkrupinski/Osiris#1864]
Title

**Comment by iAlpha0Detrix** [comment]
use this injector https://github.com/danielkrupinski/curiuminjector-csgo
and add this line of code after line 178 in Main.cpp

LPVOID ntOpenFile = GetProcAddress(LoadLibraryW(L"ntdll"), "NtOpenFile");
	if (ntOpenFile) {
		char originalBytes[5];
		memcpy(originalBytes, ntOpenFile, 5);
		WriteProcessMemory(hProcess, ntOpenFile, originalBytes, 5, NULL);
	}

tested it and worked perfectly fine

**Comment by Shuvi-Moro** [comment]
![image](https://user-images.githubusercontent.com/63977167/87025787-81f0cb80-c1e3-11ea-90c5-71a4515c4873.png)
So?

**Comment by kvetinkavole** [comment]
https://github.com/AMATEURZ1337/load-lib-injector
