### ISSUE TITLE
osiris fps drop

### ISSUE THREAD

**Issue by avangersKinkyClient** [danielkrupinski/Osiris#1866]
dear mister Daniel ,
i did use your cheat and it is great but i did test lot of cheats and they not give fps drops by your new updates i did use osiris back and i did normally play around 120 fps in game now i only got around 40 / 20 even 10 fps please if you can update osiris and fix it if you can and got time

regards avangers

ps : your doing very but very good work

**Comment by NekoRem** [comment]
People have been over this its MinHook that causes the fps drop you can change it back by reverting the commits

**Comment by kvetinkavole** [comment]
MinHook droping framerate sometimes, use vmt method (old method before minhook update)

**Comment by xXTOO-HARDXx** [comment]
People have been saying you can switch back to VMT by changing all of the hook types back `vmtswap`

**Comment by NekoRem** [comment]
> dear mister Daniel ,
> i did use your cheat and it is great but i did test lot of cheats and they not give fps drops by your new updates i did use osiris back and i did normally play around 120 fps in game now i only got around 40 / 20 even 10 fps please if you can update osiris and fix it if you can and got time
> 
> regards avangers
> 
> ps : your doing very but very good work

You can close this issue now

**Comment by MasterChief220** [comment]
> People have been over this its MinHook that causes the fps drop you can change it back by reverting the commits

how do u do that . And whats minhook?

**Comment by NekoRem** [comment]
> > People have been over this its MinHook that causes the fps drop you can change it back by reverting the commits
> 
> how do u do that . And whats minhook?

CLOSE THIS

**Comment by emphatically** [comment]
> > > People have been over this its MinHook that causes the fps drop you can change it back by reverting the commits
> > 
> > how do u do that . And whats minhook?
> 
> CLOSE THIS

xD

**Comment by NekoRem** [comment]
> > > > People have been over this its MinHook that causes the fps drop you can change it back by reverting the commits
> > > 
> > > 
> > > how do u do that . And whats minhook?
> > 
> > 
> > CLOSE THIS
> 
> xD

Im sorry its just you made me very angry

**Comment by Shuvi-Moro** [comment]
> > > > > People have been over this its MinHook that causes the fps drop you can change it back by reverting the commits
> > > > 
> > > > 
> > > > how do u do that . And whats minhook?
> > > 
> > > 
> > > CLOSE THIS
> > 
> > 
> > xD
> 
> Im sorry its just you made me very angry

I'm for fun just to continue it

**Comment by MasterChief220** [comment]
> > > People have been over this its MinHook that causes the fps drop you can change it back by reverting the commits
> > 
> > 
> > how do u do that . And whats minhook?
> 
> CLOSE THIS

how do you fix it though????
