### ISSUE TITLE
Mouse side buttons make my menu unfocus

### ISSUE THREAD

**Issue by skuut-coppy-666** [danielkrupinski/Osiris#1867]
Hello kind people,

So I started off as Osiris as a base and then implemented [this](https://corsair.wtf/topic/1429-every-gamesense-menu-clone-ever/) menu (number 1 on that thread) into Osiris. Everything works fine so far and I haven't changed anything in the `Hooks`. But unfortunately whenever I press the `mouse4` or `mouse5` button (the side buttons on my mouse), the menu becomes unclickable. I have no idea why this happens and it looks like the menu just unfocusses and I got no clue why this is happening. As I said before, this only happens when I press the side buttons of my mouse.

The menu does not freeze or anything, since the "tab icons" still change from color (to the hover color) if I double click on one of them. It just doesn't do anything on click.

I do not have the source public but the only stuff that has been changed is the `GUI.cpp` and the `imgui` files. Nothing in Hooks, regarding input management has been changed. However, this issue does not happen in Osiris itself. I am wondering if someone might have an idea why this is happening since I got a bind on my mouse that I use as a primary action but unfortunately this does not work in combation with the menu.

I've also attached the debugger and tried to debug it multiple times but unfortunately nothing is giving me errors so it is hard to debug.

**Edit:** If I bind something in the menu (for example edge jump) to `mouse4`, then `mouse4` doesn't make the menu 'unclickable' anymore, so then it works fine. But obviously, `mouse5` is still an issue then. And this is not normal ofcourse.

**Comment by danielkrupinski** [comment]
Does this issue occur in the clean Osiris source?

**Comment by skuut-coppy-666** [comment]
> Does this issue occur in the clean Osiris source?

Nope I tried to reproduce this issue in the original Osiris source but it does not seem to happen.

That is why I am really confused. Since I have not replace any of the standard input management. I've only replaced a couple of `imgui` files (that came with the menu) and of course the `GUI.cpp` stuff, the regular stuff to replace the menu.

**Comment by skuut-coppy-666** [comment]
Anyone? 😕
