### ISSUE TITLE
[SUGGESTION] molotov mesh

### ISSUE THREAD

**Issue by 0suddenly0** [danielkrupinski/Osiris#1871]
In aimwar there is a function (I don’t know what it is exactly called) that displays the radius of molotov in the form of polygons.
I found several netvars which are most likely used in it. I tried to make this function myself, but could not make the logic for rendering polygons. Here is a list of netvars:
vec3, vec_origin, "DT_BaseEntity", "m_vecOrigin"
int, fire_count, "DT_Inferno", "m_fireCount"
int[64], fire_x, "DT_Inferno", "m_fireXDelta"
int[64], fire_y, "DT_Inferno", "m_fireYDelta"
int[64], fire_z, "DT_Inferno", "m_fireZDelta"
Here's what it looks like in aimwar:https://prnt.sc/tfn2g3

**Comment by caiocinel** [comment]
I think it would look better in the style of OTC, where it is integrated with the grenade prediction and informs the area that it will act beyond the damage that HE is supposed to cause.

**Comment by danielkrupinski** [comment]
Added (0357fba56c0383802e021a4794a67388090d1cf4).
