### ISSUE TITLE
My custom osiris randomly crashing

### ISSUE THREAD

**Issue by sserve-kr** [danielkrupinski/Osiris#1872]
my custom version of osiris randomly crashing my game
but i dont know why.

I'm using Win10, 720x480 res (because my computer is super potato)
[and my source code is here](https://github.com/sserve-kr/MyOsirisWork)

What i changed on original osiris:
+ Add no zoom [Khajiitos's work](https://github.com/danielkrupinski/Osiris/pull/866)
+ Add [this](https://github.com/danielkrupinski/Osiris/pull/1546), but only bullet tracer beam & draw multipoints
+ some crashing bug fix & remove anti-aim & rename some features but only gui showing (not function name)

is there incorrect code?

**Comment by caiocinel** [comment]
> my custom version of osiris randomly crashing my game
> but i dont know why.
> 
> I'm using Win10, 720x480 res (because my computer is super potato)
> [and my source code is here](https://github.com/sserve-kr/MyOsirisWork)
> 
> What i changed on original osiris:
> 
> * Add no zoom [Khajiitos's work](https://github.com/danielkrupinski/Osiris/pull/866)
> * Add [this](https://github.com/danielkrupinski/Osiris/pull/1546), but only bullet tracer beam & draw multipoints
> * some crashing bug fix & remove anti-aim & rename some features but only gui showing (not function name)
> 
> is there incorrect code?

Some peoples have problems with bullet tracer, idk why.

**Comment by sserve-kr** [comment]
lol i just changed my game resolution, and it fixed. XDD
