### ISSUE TITLE
[SUGGESTION] Fake Kick 

### ISSUE THREAD

**Issue by king1919djdj** [danielkrupinski/Osiris#1874]
It would be nice to have a independent recoil control system
plus is it still possible to make a fake kick in which u make your name like "/n /n /n /n jack /n /n /n /n" or something like that

**Comment by xXTOO-HARDXx** [comment]
fake kick is easy to make yourself, the code is already there.

There is already a pull request for stand alone RCS.

**Comment by sserve-kr** [comment]
Where is that code? I can't find that.. fake kick

**Comment by xXTOO-HARDXx** [comment]
Search for fake kick on UnknownCheats, ez code

**Comment by king1919djdj** [comment]
didn't Osiris already had fake kick ?
cause I saw the option in some screen shots of the older version I think

**Comment by sserve-kr** [comment]
I saw that too, in unknowncheats version

**Comment by xXTOO-HARDXx** [comment]
> didn't Osiris already had fake kick ?
> cause I saw the option in some screen shots of the older version I think

It might of, yeah.

**Comment by king1919djdj** [comment]
plus I cant find any fake kick thread or post in unknowncheats
if somebody finds it please do share a link

**Comment by xXTOO-HARDXx** [comment]
> plus I cant find any fake kick thread or post in unknowncheats
> if somebody finds it please do share a link

https://www.unknowncheats.me/forum/counterstrike-global-offensive/352403-trying-fake-vote.html

https://www.unknowncheats.me/forum/counterstrike-global-offensive/332665-troll-kick-lines.html

**Comment by king1919djdj** [comment]
> > plus I cant find any fake kick thread or post in unknowncheats
> > if somebody finds it please do share a link
> 
> https://www.unknowncheats.me/forum/counterstrike-global-offensive/352403-trying-fake-vote.html
> 
> https://www.unknowncheats.me/forum/counterstrike-global-offensive/332665-troll-kick-lines.html

ahh thanks m8

**Comment by king1919djdj** [comment]
Is it possible for someone to create a pull for this
[ I know I am asking for too much so forgive me ]

**Comment by king1919djdj** [comment]
@danielkrupinski Sir if u have time to spare, do consider on working on adding this to the software

**Comment by danielkrupinski** [comment]
It was patched few months ago.

**Comment by king1919djdj** [comment]
ohh that's why
thanks
