### ISSUE TITLE
[HELP] How to fix my source with new anti-cheat update 

### ISSUE THREAD

**Issue by novaxawp** [danielkrupinski/Osiris#1875]
### hi , my source after update is crashing , idk how danielkrupinski update osiris that is not cause crash and i hope i can fix my source with u guys 

**i inject osiris and my source with Xenos  ,  osiris is not crashing but my cheat is crashing afrer 1 sec , and i use manual maping injector and i minhook my source but still crash , i wanna know how to fix it and wanna know how danielkrupinski fix/update osiris** 

**_tnx , great community !_**

**Comment by NekoRem** [comment]
not to be a meanie or anything but i think you need a better translator

**Comment by notgoodusename** [comment]
Debug

**Comment by ldealism** [comment]
cs:go crashes once I try to inject it, is there a fix for this?

**Comment by NekoRem** [comment]
> cs:go crashes once I try to inject it, is there a fix for this?

Yes, there is.

**Comment by ldealism** [comment]
> > cs:go crashes once I try to inject it, is there a fix for this?
> 
> Yes, there is.

Can I know how?

**Comment by NekoRem** [comment]
> > > cs:go crashes once I try to inject it, is there a fix for this?
> > 
> > 
> > Yes, there is.
> 
> Can I know how?

It involves using your brain ready?

**Comment by ldealism** [comment]
> > > > cs:go crashes once I try to inject it, is there a fix for this?
> > > 
> > > 
> > > Yes, there is.
> > 
> > 
> > Can I know how?
> 
> It involves using your brain ready?

Yes

**Comment by NekoRem** [comment]
open github desktop and click fetch origin

**Comment by ldealism** [comment]
> open github desktop and click fetch origin

And?

**Comment by NekoRem** [comment]
thats it.

**Comment by ldealism** [comment]
> thats it.

So now it won't crash?

**Comment by NekoRem** [comment]
it shouldn't unless you mess with stuff

**Comment by ldealism** [comment]
> it shouldn't unless you mess with stuff

I don't really know how to "fetch origin" and I don't know what that does.

**Comment by NekoRem** [comment]
make sure you have merged the upstream with your master

**Comment by ldealism** [comment]
I only have the .dll and nothing else

**Comment by NekoRem** [comment]
then i cannot help you

**Comment by xXTOO-HARDXx** [comment]
Ffs. You shouldn't be cheating with an open source cheat if you don't know how to code or use visual studio.

Butt, what you have to do is just download the latest source and compile it inside of visual studio community.

It isn't hard, and very self explanatory. Use Google, not the issue section.

**Comment by Frouk3** [comment]
use csh injector
https://cheater.fun/injectors/1245-csh-injector-works-on-the-new-version-of-csgo-free-download.html
read description before injecting
