### ISSUE TITLE
I got VAC banned

### ISSUE THREAD

**Issue by ldealism** [danielkrupinski/Osiris#1877]
Title says it all, use this at your own risk. Was only using WH & ESP.

**Comment by Felxe007** [comment]
you need to make it undetectable your self. this is an open-source cheat for the public. watch this https://www.youtube.com/watch?v=BI6U0MHUfXQ to make it undetectable. the video is quite old and he's not using the same cheat, but informative.

**Comment by bruhmoment21** [comment]
![image](https://user-images.githubusercontent.com/53657322/87240000-03cc3900-c41e-11ea-8259-0daa9c7cae4b.png)
don't add junk code lol its meme

**Comment by Felxe007** [comment]
> ![image](https://user-images.githubusercontent.com/53657322/87240000-03cc3900-c41e-11ea-8259-0daa9c7cae4b.png)
> don't add junk code lol its meme

Ofcourse but still informative 👌. Still haven't been vac tho

**Comment by Floraly** [comment]
Did you play casual matches?

**Comment by MasterChief220** [comment]
> Did you play casual matches?
> And Bans are delayed and the detection can be weeks or months ago.

not really . If you use a detected cheat you'll get banned in a day or two by VAC. Undetected cheats dont get banned by VAC . You may be banned by overwatch though .

**Comment by mapleint** [comment]
Junk code doesn't work
If you think pasting with junk code at the end of bin works, you don't know how sigs or vac works.

**Comment by Shuvi-Moro** [comment]
in order to get around this problem, disable vac.  And for this there is anti-vac ... More on your own. & Close this is shit.

**Comment by m0nsterJ** [comment]
Junk Code does nothing since it will get detected by VAC as DATA and not as actual code so stop spreading this shit.
