### ISSUE TITLE
How to use fake ban?

### ISSUE THREAD

**Issue by sserve-kr** [danielkrupinski/Osiris#1878]
idk how to use fake ban, so i just changed name to fake name..

Or it's really fake name??

**Comment by ldealism** [comment]
> idk how to use fake ban, so i just changed name to fake name..
> 
> Or it's really fake name??

I'm not sure it actually works, haven't tried it since I got banned in like 5 minutes while only using walls and esp.

**Comment by xXTOO-HARDXx** [comment]
I am pretty sure you just press setup ban and then leave the match. and in chat instead of saying "xxx has disconnected" it will say "xxx has been permanently banned from Official CSGO Servers" or something like that. And it will also be red text, just like an actual perm ban.

**Comment by sserve-kr** [comment]
i'll test it tomorrow, with my friend.
thx for help :)

**Comment by xXTOO-HARDXx** [comment]
> i'll test it tomorrow, with my friend.
> thx for help :)

Best of luck. 👍

**Comment by sserve-kr** [comment]
How to restore my changed nickname?
my nickname is blank in game chat and it easily get overwatch ban, i think.

**Comment by xXTOO-HARDXx** [comment]
> How to restore my changed nickname?
> my nickname is blank in game chat and it easily get overwatch ban, i think.
> 
> Automatically restore after disconnected? or can I use some code?

I think it should change back when you join back to the game.

And no, I have completed over 400 overwatch cases and there's no indication of what anyone's name is. In overwatch we don't get any information about the suspect. So you're fine.

**Comment by sserve-kr** [comment]
again, thanks for help.

**Comment by Frouk3** [comment]
When you disconnect writes Player xxx [fake ban] [reason of disconnecting]
