### ISSUE TITLE
Lagging

### ISSUE THREAD

**Issue by MasterChief220** [danielkrupinski/Osiris#1880]
With osiris my game lags alot and fps drops to 40-20 from 180 . Can anyone tell me whats the issue?

**Comment by newcommerdontblame** [comment]
new hook method

**Comment by MasterChief220** [comment]
> new hook method

how do i fix it mate?

**Comment by kvetinkavole** [comment]
for fix use old hook vmt method

**Comment by MasterChief220** [comment]
> for fix use old hook vmt method

thats exactly what im asking!!!how?? I dont know coding mate....

**Comment by MasterChief220** [comment]
You can change from minhook to the old method of hooking (Vmt)
Its a 1 line change

Go to Hooks.h
Look for the line using HookType = MinHook;
Change MinHook to VmtSwap
