### ISSUE TITLE
Multipoint, autowall and autostop

### ISSUE THREAD

**Issue by avidretard** [danielkrupinski/Osiris#1881]
osiris is actually suprisingly good for hvh but its lacking these features. I know its a legit cheat but i think this could genuinely compete with some cheats in hvh.

**Comment by king1919djdj** [comment]
have u ever actually used osiris for hvh on hvh servers ?
u literally get raped out there

**Comment by king1919djdj** [comment]
plus osiris is not meant for hvh
idk how many times people have been told that OSIRIS IS A "LEGIT" CHEAT, NOT A "HVH" CHEAT

**Comment by avidretard** [comment]
> have u ever actually used osiris for hvh on hvh servers ?
> u get raped out there

i actually have and i pissed off a v3 user so much that he went full baim

**Comment by sserve-kr** [comment]
i'm using my custom osiris, and it's good at hvh. I got many aimware, some onetap users. without antiaim.

I removed anti-aim, and there's pull request for draw multipoint.
(But not applied for aimbot yet 😂) 

so I want to use real anti-aim, multipoints, autowall etc.
that will be great.

**Comment by newcommerdontblame** [comment]
https://streamable.com/luqpde
https://streamable.com/d871dv
someone tryna make osiris for hvh lmao

**Comment by notgoodusename** [comment]
autowall is already on the cheat, the rest of the stuff is up to you to make and figure out

**Comment by king1919djdj** [comment]
> > have u ever actually used osiris for hvh on hvh servers ?
> > u get raped out there
> 
> i actually have and i pissed off a v3 user so much that he went full baim

and then u lost the match, right ?

**Comment by avidretard** [comment]
> > > have u ever actually used osiris for hvh on hvh servers ?
> > > u get raped out there
> > 
> > 
> > i actually have and i pissed off a v3 user so much that he went full baim
> 
> and then u lost the match, right ?

yeah lol but still i was positive kd with no multipoint, resolver or autowall

**Comment by avidretard** [comment]
> autowall is already on the cheat, the rest of the stuff is up to you to code and figure out

there is no autowall it wont shoot thru thin walls

**Comment by king1919djdj** [comment]
it does 
i have tried it 
i was shooting a guy automatically through wall adjacent to the ladder in palace for a damage for 15 to head on mirage

**Comment by avidretard** [comment]
> it does
> i have tried it
> i was shooting a guy automatically through wall adjacent to the ladder in palace for a damage for 15 to head on mirage
> disable visible only and set the minimum damage to 1

shit then idk
