### ISSUE TITLE
Three question about osiris fake vote

### ISSUE THREAD

**Issue by sserve-kr** [danielkrupinski/Osiris#1885]
1. [this](https://www.unknowncheats.me/forum/counterstrike-global-offensive/352403-trying-fake-vote.html) or [this](https://www.unknowncheats.me/forum/counterstrike-global-offensive/332665-troll-kick-lines.html),
Still working?

2. Why patched?

3. fake vote code in link above, detected? or not detected?

**Comment by notgoodusename** [comment]
1. changing names is possible however the "fake vote" thing was patched a few months ago
2. because players were confused when people called a fake vote
3. it isnt detected

**Comment by sserve-kr** [comment]
then i can use fake vote?

**Comment by notgoodusename** [comment]
you can but it wont work

**Comment by king1919djdj** [comment]
close this now

**Comment by AbhinayNegi** [comment]
> 1. changing names is possible however the "fake vote" thing was patched a few months ago
> 2. because players were confused when people called a fake vote
> 3. it isnt detected

What is the fake vote? How does it work?
