### ISSUE TITLE
(REQUEST) units (pre) for velocity indicator

### ISSUE THREAD

**Issue by koon666** [danielkrupinski/Osiris#1886]
if anyone knows this code for the units or (pre) of the velocity indicator, please send me. I'm looking and trying to do and I never can :(

Example: https://prnt.sc/tgir6s

**Comment by sserve-kr** [comment]
there's a pull request about velocity indicator. go to pull request

**Comment by NekoRem** [comment]
> if anyone knows this code for the units or (pre) of the velocity indicator, please send me. I'm looking and trying to do and I never can :(
> 
> Example: https://prnt.sc/tgir6s

i have made a pull request for this feature

**Comment by NekoRem** [comment]
> if anyone knows this code for the units or (pre) of the velocity indicator, please send me. I'm looking and trying to do and I never can :(
> 
> Example: https://prnt.sc/tgir6s

If you would be so kind to close this issue thanks

**Comment by max000555** [comment]
> > if anyone knows this code for the units or (pre) of the velocity indicator, please send me. I'm looking and trying to do and I never can :(
> > Example: https://prnt.sc/tgir6s
> 
> If you would be so kind to close this issue thanks

he is talking about last velocity on ground not about current local player velocity.

**Comment by koon666** [comment]
> > > if anyone knows this code for the units or (pre) of the velocity indicator, please send me. I'm looking and trying to do and I never can :(
> > > Example: https://prnt.sc/tgir6s
> > 
> > 
> > If you would be so kind to close this issue thanks
> 
> he is talking about last velocity on ground not about current local player velocity.

yes, I've been looking for this code for a long time, but I don't think
