### ISSUE TITLE
Best Injector With Hide Modules and PE Eraser

### ISSUE THREAD

**Issue by techzin** [danielkrupinski/Osiris#1887]
i am using this injector created by daniel a while ago, it is working very well.

make it work and simple, compile your Osiris project in Release | x86, use a tool to convert the DLL to Hex, and simply put the data in the injector's arrary and you're done.
testing on Windows 10.
https://github.com/danielkrupinski/MemJect

credtis to [Daniel](https://github.com/danielkrupinski)

**Comment by NekoRem** [comment]
> i am using this injector created by daniel a while ago, it is working very well.
> 
> make it work and simple, compile your Osiris project in Release | x86, use a tool to convert the DLL to Hex, and simply put the data in the injector's arrary and you're done.
> testing on Windows 10.
> https://github.com/danielkrupinski/MemJect
> 
> credtis to [Daniel](https://github.com/danielkrupinski)

I don't understand what this is.. How is this an issue?

**Comment by techzin** [comment]
the Issues tab, it was the best way I found to share this with the community.
