### ISSUE TITLE
Movesiris source?

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#1888]
i cant find this source anyone can send github link or direct source files pls

**Comment by sserve-kr** [comment]
What is movesiris

**Comment by newcommerdontblame** [comment]
> What is movesiris

Osiris source with so many movement features

**Comment by notgoodusename** [comment]
u understand the fact that a person that isnt daniel code it around osiris
meaning that there is no way we get the source if the person doesnt share it

**Comment by notgoodusename** [comment]
no

**Comment by NekoRem** [comment]
My mind is blown
