### ISSUE TITLE
[Config]  Configs do not work after Update

### ISSUE THREAD

**Issue by memeToasty** [danielkrupinski/Osiris#189]
The configs that are created in an older version will not work, as if new variables are declared the size of the struct elements in the Config change and thus creating an offset, which ruins the whole settings. I've made a version control in my fork to prevent old configs being applied to a new version

**Comment by memeToasty** [comment]
nevermind my version control is not working, as the storage of the config is quite weird xD

**Comment by danielkrupinski** [comment]
I know that.
