### ISSUE TITLE
CSGO crashing after injecting dll.

### ISSUE THREAD

**Issue by AbhinayNegi** [danielkrupinski/Osiris#1894]
After the update, I cant use this hack anymore. I searched on the internet people recommending using manualmap injector. I tried 3 different injectors to inject dll via manual map but every time I inject csgo is crashing. If I am not using manual map and just using a standard method then there is no effect in-game.

**Comment by Shuvi-Moro** [comment]
Без названия
https://vk.com/video268543085_456239717

**Comment by Shuvi-Moro** [comment]
https://github.com/AMATEURZ1337/load-lib-injector/releases/tag/1.0

**Comment by AbhinayNegi** [comment]
> After the update, I cant use this hack anymore. I searched on the internet people recommending using manualmap injector. I tried 3 different injectors to inject dll via manual map but every time I inject csgo is crashing. If I am not using manual map and just using a standard method then there is no effect in-game.
