### ISSUE TITLE
[REQUEST] BlockBot?

### ISSUE THREAD

**Issue by aljawary** [danielkrupinski/Osiris#1895]
Can u add back blockbot into osiris?

**Comment by notgoodusename** [comment]
#1048

**Comment by aljawary** [comment]
> #1048

Does it still working?

**Comment by notgoodusename** [comment]
> > #1048
> 
> Does it still working?

idk

**Comment by caiocinel** [comment]
> > #1048
> 
> Does it still working?

You will need fix a lot of things.

**Comment by aljawary** [comment]
> > > #1048
> > 
> > 
> > Does it still working?
> 
> You will need fix a lot of things.

Thats a problem for me, i still noob in c++ and gamehacking

**Comment by caiocinel** [comment]
You just need programming logic to identify what needs to change.

If you don't know how to program, you have nothing to do.

>
