### ISSUE TITLE
(REQUEST)smooth bomb planting side and and bomb timer

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#1896]
As title says 
example:
![Screenshot_2020-07-13-23-48-01-1](https://user-images.githubusercontent.com/65455170/87352551-e4d7bf00-c563-11ea-897c-2c922049bcf1.png)
![Screenshot_2020-07-13-23-47-23-1-1-1](https://user-images.githubusercontent.com/65455170/87352559-e99c7300-c563-11ea-8f53-3288286a6fae.png)

**Comment by NekoRem** [comment]
This can be done easily if you have the brains

**Comment by danielkrupinski** [comment]
We already have bomb timer.

**Comment by Cyk-Fad** [comment]
Try it by your self.
Just learn C++

**Comment by newcommerdontblame** [comment]
> We already have bomb timer.

Lol it takes up half of the screen

**Comment by newcommerdontblame** [comment]
> This can be done easily if you have the brains

i didint say easy or something like that  

> Try it by your self.
> Just learn C++

K

**Comment by newcommerdontblame** [comment]
> This can be done easily if you have the brains

Then do it if u can

**Comment by NekoRem** [comment]
> > This can be done easily if you have the brains
> 
> Then do it if u can

I have done something similar to this already but i shall leave it to your capable hands to type your own code
