### ISSUE TITLE
Not injecting?

### ISSUE THREAD

**Issue by Yodawg-Osirisuser** [danielkrupinski/Osiris#1897]
The injector at #1862 isn't working anymore (at least for me). Does anyone have any other working injectors?

**Comment by newcommerdontblame** [comment]
Did u change ur dll name to cheat.dll ?

**Comment by VuBrian22** [comment]
It still works. I've just recompiled it and ran it again and it injects just as well.

**Comment by Yodawg-Osirisuser** [comment]
Why didn't I think of that?? Thanks though it fixed it for me too.
