### ISSUE TITLE
CFGs problems

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#1898]
Hi @danielkrupinski 
 After updating the code today, there are problems saving the cfg
I have deleted all the cfg and created new ones, but when saving the changes, some changes are not saved
when the game starts again, no changes appear
the same goes for other options, for example glow and esp

for example: in misc, if I select "bomb timer" and save, when I load again, bomb timer is not selected

**Comment by sserve-kr** [comment]
me too.
I'm using my custom version, After update, Config.cpp is entirely changed.
I'm tried to fix source code, but  i think my source code doesn't have any problem.
idk how to fix this.

**Comment by danielkrupinski** [comment]
Old Esp is no longer saved to config, new Stream Proof ESP is going to replace it. I'm aware some variables are not saved.

**Comment by williamzerner** [comment]
the same problem occurred for skin changer

**Comment by TauCSGO** [comment]
> I'm aware some variables are not saved.

Thank you
