### ISSUE TITLE
Cannot display after modifying font

### ISSUE THREAD

**Issue by djkcyl** [danielkrupinski/Osiris#1901]
![image](https://user-images.githubusercontent.com/59153990/87398316-4c375280-c5e8-11ea-9425-ca671460a921.png)

**Comment by danielkrupinski** [comment]
That means that font atlas texture failed to load into GPU. Which font you used? And what's your GPU?

**Comment by djkcyl** [comment]
Chinese font, GTX1660

**Comment by djkcyl** [comment]
simhei.ttf

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/87399908-ab966200-c5ea-11ea-9aad-54b06eda577e.png)

[simhei.zip](https://github.com/danielkrupinski/Osiris/files/4917342/simhei.zip)
this

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/87400069-e7312c00-c5ea-11ea-8c28-b61dff1229e5.png)

**Comment by danielkrupinski** [comment]
I will test it. Try to use font with less glyphs like Tahoma.

**Comment by danielkrupinski** [comment]
If you're using this font for GUI, you can try reducing oversampling and using smaller font size.

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/87400811-e0ef7f80-c5eb-11ea-88ae-1ff50316958e.png)
It cannot be displayed here. If I change the font here, it cannot be displayed.

**Comment by danielkrupinski** [comment]
That's strange because characters that can't be displayed should appear as `?`. If you know which characters should be displayed there, you can paste them here, so I can test them.

**Comment by danielkrupinski** [comment]
Should be fixed 8f2f2cbd2c0c589d80d4a93bd666ffc07df66b9f
