### ISSUE TITLE
Sliding

### ISSUE THREAD

**Issue by 1-Xycro** [danielkrupinski/Osiris#1902]
In the killcam replay, im always sliding, how do i remove it?

**Comment by danielkrupinski** [comment]
Record a GOTV demo on local server and check if the issue exists on it.

**Comment by Deciy** [comment]
@Kraken69 I downloaded a competitive match replay and I wasn't sliding during the game. Also no one on my team said anything about my character sliding so I think its just a killcam glitch.

**Comment by DoctorYasin** [comment]
Since Osiris is a legit cheat, it will not appear that you are slipping on the opposite side.
To cancel this, you need to turn off everything related to pattern fix. If still continues, I think the problem is in the source you are using.
