### ISSUE TITLE
(REQUEST) spectator list imGui

### ISSUE THREAD

**Issue by koon666** [danielkrupinski/Osiris#1912]
someone has a code for spectator list in gui?

Example: https://prnt.sc/tie9z6

**Comment by RyDeem** [comment]
Look at the GUI.cpp // Study it
Look at the purchaselist function, its drawing a GUI window too? wow nice.
Make your own spectator list gui taking the purchaselist as a base...

Its not alot...

**Comment by koon666** [comment]
> Look at the GUI.cpp // Study it
> Look at the purchaselist function, its drawing a GUI window too? wow nice.
> Make your own spectator list gui taking the purchaselist as a base...
> 
> Its not alot to be fair, and should be fun practise of coding...

THANKS BRO :)

**Comment by danielkrupinski** [comment]
@RyDeem Your code will randomly crash when "Multicore rendering" enabled because it isn't safe to access entity list from DirectX hook.
