### ISSUE TITLE
I want to add  special character like ★

### ISSUE THREAD

**Issue by sserve-kr** [danielkrupinski/Osiris#1913]
But it show ? instead ★
is it possible?

**Comment by rosesware** [comment]
### ★ = \u2605
Yes, it is.
[fileformat](http://www.fileformat.info) - use this site to search the symbol, and when you see "C/C++/Java source code" text, just copy the encoding and paste in your source.

**Comment by sserve-kr** [comment]
Sorry, but can you give me source code? because  i'm not good at C++..

**Comment by RyDeem** [comment]
good info roses, thank you. :)
Was usefull for me
