### ISSUE TITLE
Crash when loading cfg

### ISSUE THREAD

**Issue by Frouk3** [danielkrupinski/Osiris#1914]
I can inject, but when i try to load a .cfg the game crashes, and appear this window:

Debug Assertion failed !

Program: d:\**********\Osiris.dll
File: minkernel\crts\ucrt\src\appcrt\convert\isctype.cpp
Line: 42

Expression: c >= -1 && c <= 255

For information on how your program can cause an assertion failure , see the Visual C++ documentation on asserts.

(Press retry to debug the application)

And 3 buttons  "cancel"  "retry" "skip"

**Comment by danielkrupinski** [comment]
Could you post your config file?

**Comment by Frouk3** [comment]
yes take
[Legit.zip](https://github.com/danielkrupinski/Osiris/files/4930641/Legit.zip)

**Comment by Kaves999** [comment]
LOL , thank you frouk3 thats my original post in cheater.fun .

Hi Daniel, this is the original cfg that causes that crash

[trank.zip](https://github.com/danielkrupinski/Osiris/files/4933200/trank.zip)

**Comment by Kaves999** [comment]
too many people having the same problem

**Comment by Frouk3** [comment]
I installed Visual Studio. I don't know if that working correct

**Comment by Frouk3** [comment]
Kaves999 if you think that I downloaded configurations, I did not download other configurations i just create them

**Comment by danielkrupinski** [comment]
Should be fixed now.
