### ISSUE TITLE
configs not loading all settings

### ISSUE THREAD

**Issue by Saje6** [danielkrupinski/Osiris#1918]
I deleted my configs and created new ones, and the bomb timer, health based checkbox in glow and the Chams section is not loading/saving

**Comment by Saje6** [comment]
With the latest commit dce0137, the entries in the config are functional, except for the bomb timer

**Comment by 0xE232FE** [comment]
I think Daniel is working on a Switch for Stream Safe Settings and non Stream Safe settings construct. So you have a StreamSafe switch. ;-) Otherwise StreamSafe ESP is useless if you use features that are not stream safe ;-)

**Comment by danielkrupinski** [comment]
Fixed
