### ISSUE TITLE
App crash while saving/loading configs

### ISSUE THREAD

**Issue by PriyanshuXavie** [danielkrupinski/Osiris#1921]
![Desktop Screenshot 2020 07 17 - 18 45 17 32](https://user-images.githubusercontent.com/68430893/87791071-4d25e980-c85f-11ea-8f54-5259183dd287.png)

**Comment by PriyanshuXavie** [comment]
this, and few types of other errors, are causing app crashes. skin changer is one of the problem.

**Comment by danielkrupinski** [comment]
Are you using the latest version? This was supposed to be fixed in a6e9d084c5eae3b8430f72050e3b2c92b9e8c254

**Comment by PriyanshuXavie** [comment]
@danielkrupinski yes i am using the latest version.

**Comment by danielkrupinski** [comment]
Press "Retry" and show callstack.

**Comment by danielkrupinski** [comment]
With the Steam version only.

**Comment by PriyanshuXavie** [comment]
@danielkrupinski  do we need to use vac by pass with osiris as well?
