### ISSUE TITLE
(request) offscreen esp

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#1923]
basicly shows players behind you 
![faf](https://user-images.githubusercontent.com/65455170/87810814-3df66a00-c866-11ea-9305-315ec7dda99d.jpg)

**Comment by newcommerdontblame** [comment]
i couldnt find better screenshot but its very usefull i think 
hope someone can make pr for this

**Comment by NekoRem** [comment]
Ive made this but with 3d triangles

**Comment by newcommerdontblame** [comment]
> Ive made this but with 3d triangles

ss?

**Comment by newcommerdontblame** [comment]
> Ive made this but with 3d triangles

Hey are u gonna share with us ??

**Comment by aljawary** [comment]
This must be useful

**Comment by newcommerdontblame** [comment]
> No im not going to share it yet

sad(

> This must be useful

yess sir

**Comment by newcommerdontblame** [comment]
Are u gonna take a look @danielkrupinski

**Comment by aljawary** [comment]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/282111-offscreen-esp.html
Here the example source, how to impelement it onto osiris

**Comment by newcommerdontblame** [comment]
> https://www.unknowncheats.me/forum/counterstrike-global-offensive/282111-offscreen-esp.html
> Here the example source, how to impelement it onto osiris

That shit has 29389272 lines dude holyf

**Comment by NekoRem** [comment]
> > https://www.unknowncheats.me/forum/counterstrike-global-offensive/282111-offscreen-esp.html
> 
> > Here the example source, how to impelement it onto osiris
> 
> 
> 
> That shit has 29389272 lines dude holyf

It would take very little to implement this...

**Comment by newcommerdontblame** [comment]
@NekoRem dude why u dont share urs lmao its public cheat anyways

**Comment by NekoRem** [comment]
> @NekoRem dude why u dont share urs lmao its public cheat anyways

I would but I think I deleted the source because I've made my own cheat that's not based on Osiris. either way it would take like 20 mins to make and you even have a source you can copy from.

**Comment by danielkrupinski** [comment]
Added in fe654e9118dbb65775655a16a41fb7633833dbbc
