### ISSUE TITLE
Head level indicator?

### ISSUE THREAD

**Issue by Deciy** [danielkrupinski/Osiris#1924]
We need head level indicator.

**Comment by SDE1x** [comment]
Figuring out crosshair placement is a much more efficient solution to this problem - and also to enjoying counterstrike more. It doesn't take as long as you might think.

**Comment by Deciy** [comment]
I just think it would be nice. Also, it could help users learn crosshair placement too.

**Comment by king1919djdj** [comment]
why not use head dots in esp ?

**Comment by barbadully** [comment]
> I just think it would be nice. Also, it could help users learn crosshair placement too.

maybe learn the fucking game without cheating then u fucking retard? lmao

**Comment by Deciy** [comment]
> > I just think it would be nice. Also, it could help users learn crosshair placement too.
> 
> maybe learn the fucking game without cheating then u fucking retard? lmao

Lol why are you here? This thread is for cheaters not for you to come in and be an asshole. Also I already know the game? I already have crosshair placement down? Don't come in here assuming you know shit. gtfo this place isn't for you dumbass

**Comment by Deciy** [comment]
> why not use head dots in esp ?

I don't use esp cause well I might accidentally look at someone through a wall then I can get easily overwatched.

**Comment by deboogergithub** [comment]
> We need head level indicator.

imo its useless, because it only works when the enemy is at the same height on the level as you. masterlooser15 did a great job on head level indicators tho

**Comment by caiocinel** [comment]
> > > I just think it would be nice. Also, it could help users learn crosshair placement too.
> > 
> > 
> > maybe learn the fucking game without cheating then u fucking retard? lmao
> 
> Lol why are you here? This thread is for cheaters not for you to come in and be an asshole. Also I already know the game? I already have crosshair placement down? Don't come in here assuming you know shit. gtfo this place isn't for you dumbass

Ehh, no?
We are on GitHub, here is a place to develop the source code, implementations are important, but it is worth mentioning that the focus is on DEVELOPMENT. 

In the last few months this repository has become chaos, it's very silly talk, if you want to suggest something, do your best and make a pull request.

If you want to talk about cheating, try Corsair.wtf or Cheaterfun.

**Comment by Deciy** [comment]
> > > > I just think it would be nice. Also, it could help users learn crosshair placement too.
> > > 
> > > 
> > > maybe learn the fucking game without cheating then u fucking retard? lmao
> > 
> > 
> > Lol why are you here? This thread is for cheaters not for you to come in and be an asshole. Also I already know the game? I already have crosshair placement down? Don't come in here assuming you know shit. gtfo this place isn't for you dumbass
> 
> Ehh, no?
> We are on GitHub, here is a place to develop the source code, implementations are important, but it is worth mentioning that the focus is on DEVELOPMENT.
> 
> In the last few months this repository has become chaos, it's very silly talk, if you want to suggest something, do your best and make a pull request.
> 
> If you want to talk about cheating, try Corsair.wtf or Cheaterfun.

Bruh but why would he be on this issue? This particular issue is for cheaters? I never once said that github is for cheating I’m video games lol.
