### ISSUE TITLE
How Anti-afk works?

### ISSUE THREAD

**Issue by nikita-tarasov3** [danielkrupinski/Osiris#1929]
How Anti-afk works?

**Comment by MasterChief220** [comment]
I think it makes use of the command +right which means that you cant be kicked by the server for being afk as it doesnt classify you as afk . However you can still be kicked if your teammates vote to kick you.

**Comment by danielkrupinski** [comment]
It sends different UserCmd::buttons every other tick, so the server thinks we aren't afk.
