### ISSUE TITLE
Explit - Menu GUI

### ISSUE THREAD

**Issue by cojo1989** [danielkrupinski/Osiris#193]
Daniel, its any way posible to implement Explit menu into yours? I tryed but i dont have so many experience with coding and it would be easier if you can make a tutorial or something with it. Or even to make other reposition with it integrated. Thank you very much.

**Comment by effex1337** [comment]
Explit?

**Comment by cojo1989** [comment]
Search on reposition from Daniel, you will find it there. :)

**Comment by effex1337** [comment]
reposition?

**Comment by cojo1989** [comment]
https://github.com/danielkrupinski/Explit Sorry for that, im just rushing when i write and english is not my native language. Here you have the link for that GUI.

**Comment by effex1337** [comment]
You just need to unhook imgui then hook zgui and design the menu.

**Comment by cojo1989** [comment]
Probably, i really dont know. Im really a newbie. If i would have a tutorial how to do it it would be appreciated. Anyway its just for fun and i like to help with some ideas.

**Comment by effex1337** [comment]
Or you could just learn how to use ImGui
https://github.com/IcePixelx/Menu-Creator-CSGO/
Use this to practice, it's really helpful.

**Comment by patrykkolodziej** [comment]
Explits uses edited zgui, everything about implementing it to your source you can find on zgui's repo.
https://github.com/zxvnme/zgui
