### ISSUE TITLE
AutoStop or NoSpread(legit)?

### ISSUE THREAD

**Issue by sserve-kr** [danielkrupinski/Osiris#1930]
I hope there is nospread or autostop option to shot perfectly while running
(but legit)

can anyone help me?

**Comment by senisditron** [comment]
you must set this option in aimbot

Max aim inaccuracy - maximum weapon inaccuracy allowing aimbot to run, lowering this value will e.g. disable aimbot while jumping or running

**Comment by newcommerdontblame** [comment]
youtubers spend hours going for clips and it's completely luck so no.

**Comment by newcommerdontblame** [comment]
youtubers spend hours going for clips and it's completely luck so no.
u cant do nospread thing
