### ISSUE TITLE
How do I use stream proof esp?

### ISSUE THREAD

**Issue by TheSmartOne1O** [danielkrupinski/Osiris#1932]
I was streaming with Nvidia ShadowPlay and the ESP still showed up. Do I need to use OBS, if so what settings?

**Comment by TheSmartOne1O** [comment]
I Tried it with OBS and the game is black on OBS game capture. Window Capture shows ESP.

**Comment by danielkrupinski** [comment]
You should use game capture, but since Trusted Launch update you have to use **-untrusted** launch option to allow OBS.

**Comment by RyDeem** [comment]
or disable the dll protection with one byte and inject any game capture you want from any software... as far as i know.

**Comment by TheSmartOne1O** [comment]
Thank you, guys.

**Comment by TheSmartOne1O** [comment]
Or is there a better game capture software, that can stream & record?

**Comment by free0ne87** [comment]
Try this!
https://github.com/danielkrupinski/OneByteLdr/issues/17

**Comment by TheSmartOne1O** [comment]
Thank you, I will try that.

**Comment by TheSmartOne1O** [comment]
It works. Thank you Guys.
