### ISSUE TITLE
Music changer

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#1933]
that about making not only a skin changer but also a music changer, I think it would be pretty good, since not everyone wants to pay for music and music in cs is in any case more atmospheric than outside.

**Comment by MasterChief220** [comment]
> that about making not only a skin changer but also a music changer, I think it would be pretty good, since not everyone wants to pay for music and music in cs is in any case more atmospheric than outside.

I found out another hack for it that allows u to listen to music kits.

**Comment by nikita-tarasov3** [comment]
+1 great idea

**Comment by wemanzoz** [comment]
when?
