### ISSUE TITLE
HP/Armor ESP

### ISSUE THREAD

**Issue by hyperxpro** [danielkrupinski/Osiris#1936]
Can't find HP/Armor ESP after recent updates. Any clue on this?

**Comment by 0xE232FE** [comment]
Will come back I guess.

**Comment by hyperxpro** [comment]
@danielkrupinski Updates?

**Comment by danielkrupinski** [comment]
"Health Bar" has been added.

**Comment by hyperxpro** [comment]
Thanks :)
