### ISSUE TITLE
new osiris is not cool some functions does not work

### ISSUE THREAD

**Issue by madhatterxk** [danielkrupinski/Osiris#1937]
-1 FONT SIZE*  we need font size back i can't even read the enemy name with these fonts it doesn't work with my resolution i use 800-600 i have low fps

-2 * I CANT USE CHAMS  anymore?* and if i use " ignore-z" feature in chams
 the enemy appears with the same visible color so i cant tell if he's behind wall or not 

3.*GLOW CONTROL*since i cant i cant control the glow it reduced my fps i used to keep glow at 50% as same as the visible color 

4. ENEMY HEAD DOT*if i play legit i don't get the Enemy head mark its not available anymore 

5. GRENADE PREDICTION doesn't work

**Comment by danielkrupinski** [comment]
Was there ever a font size option?

**Comment by Deciy** [comment]
I’ve been having similar issues recoil crosshair and sniper crosshair haven’t been working for me. However grenade prediction worked just fine for me. Also yeah I don’t remember a font size thing

**Comment by HowToMakeFaceitAB** [comment]
> Was there ever a font size option?

no, but can you please improve the grenade prediction as it looks really bad, thanks 👍 <3

**Comment by madhatterxk** [comment]
> Was there ever a font size option?

yes before in the esp section there was Font size

**Comment by Official-Kinja** [comment]
"-1 FONT SIZE* we need font size back i can't even read the enemy name with these fonts it doesn't work with my resolution i use 800-600 i have low fps"

Stop using a Potato pc Khaled

**Comment by caiocinel** [comment]
> Stop using a Potato pc Khaled
If you are not going to contribute positively to the discussion, please do not disturb.

**Comment by danielkrupinski** [comment]
You can change font sizes here: https://github.com/danielkrupinski/Osiris/blob/d27388bf2a75f6b526f51627407ffa055b5dd8d1/Osiris/Config.cpp#L1184-L1186

**Comment by madhatterxk** [comment]
> "-1 FONT SIZE* we need font size back i can't even read the enemy name with these fonts it doesn't work with my resolution i use 800-600 i have low fps"
> 
> Stop using a Potato pc Khaled

BAHHAHAHAHAHHAHAAHA I thought you're dead man

**Comment by Official-Kinja** [comment]
Nahh i'm still alive tapping these mofos 24/7

**Comment by danielkrupinski** [comment]
I've added "Head Box" as "Head dot" replacement.

**Comment by madhatterxk** [comment]
> "-1 FONT SIZE* we need font size back i can't even read the enemy name with these fonts it doesn't work with my resolution i use 800-600 i have low fps"
> 
> Stop using a Potato pc Khaled

my discord is madhatterxk#4218

**Comment by madhatterxk** [comment]
> I've added "Head Box" as "Head dot" replacement.

Love from the land of Osiris daniel love from Egypt <3
