### ISSUE TITLE
Safe to use with Faceit?

### ISSUE THREAD

**Issue by PriyanshuXavie** [danielkrupinski/Osiris#1939]

**Comment by jalopino** [comment]
no

**Comment by stacylol** [comment]
depends if you can bypass the ac somehow, it never asked me to download/use the client ac for some reason. it might be something about my acc idk (steam lvl 70, 3k hours, prime, skins(?)).
the aimbot is probably detected by serverside ac I guess, could randomize the smoothness but whatever

**Comment by newcommerdontblame** [comment]
it never asked me to download/use the client ac for some reason. it might be something about my acc idk (steam lvl 70, 3k hours, prime, skins(?)).

how da fuck??????????

**Comment by newcommerdontblame** [comment]
>it never asked me to download/use the client ac for some reason. it might be something about my acc idk (steam lvl 70, 3k hours, prime, skins(?)).

how da fuck??????????
