### ISSUE TITLE
drawfov doesnt working 

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#1940]
everything is done with misc.h,config,gui but it isnt showing up i mean circle is not drawn.

code: 
void Misc::drawFov() noexcept
{
    if (config->misc.drawFOV && interfaces->engine->isInGame()) {
        if (!localPlayer || !localPlayer->isAlive())
            return;

        const auto activeWeapon{ localPlayer->getActiveWeapon() };
        if (!activeWeapon)
            return;

        auto weaponIndex{ getWeaponIndex(activeWeapon->itemDefinitionIndex2()) };
        if (!weaponIndex)
            return;

        auto weaponClass = getWeaponClass(activeWeapon->itemDefinitionIndex2());
        if (!config->aimbot[weaponIndex].enabled)
            weaponIndex = weaponClass;

        if (!config->aimbot[weaponIndex].enabled)
            weaponIndex = 0;

        if (config->aimbot[weaponIndex].enabled) {

            const auto [width, height] { interfaces->surface->getScreenSize() };

            const auto actualFov{ std::atanf((static_cast<float>(width) / static_cast<float>(height)) * 0.75f * std::tanf(degreesToRadians(fov / 2.f))) };

            if (config->aimbot[weaponIndex].silent)
                interfaces->surface->setDrawColor(255, 10, 10, 255);
            else
                interfaces->surface->setDrawColor(10, 255, 10, 255);

            auto radius{ static_cast<int>(std::tanf(degreesToRadians(config->aimbot[weaponIndex].fov) / 2.f) / std::tanf(actualFov) * width) };

            interfaces->surface->drawCircle(width / 2, height / 2, radius, ++radius);
        }
    }
}

**Comment by mazmamad** [comment]
dont use all on aimbot use selected aimbot weapon and get ur fov

**Comment by newcommerdontblame** [comment]
> dont use all on aimbot use selected aimbot weapon and get ur fov

still same(((

**Comment by caiocinel** [comment]
> still same(((

Try the version available in "BRCheats-CS" repository.

**Comment by newcommerdontblame** [comment]
> > still same(((
> 
> Try the version available in "BRCheats-CS" repository.

I'll be try thanks

**Comment by newcommerdontblame** [comment]
One more question @caiocinel is fake items workin?

**Comment by caiocinel** [comment]
> One more question @caiocinel is fake items workin?

Yes

**Comment by Cyk-Fad** [comment]
drawFov is working for me ....

**Comment by Cyk-Fad** [comment]
void Misc::drawAimbotFov() noexcept 
{
    if (config->misc.drawAimbotFov && interfaces->engine->isInGame()) 
    {
        if (!localPlayer || !localPlayer->isAlive() || !localPlayer->getActiveWeapon()) 
            return;
        int weaponId = getWeaponIndex(localPlayer->getActiveWeapon()->itemDefinitionIndex2());
        if (!config->aimbot[weaponId].enabled) weaponId = 0;
        if (!config->aimbot[weaponId].enabled) return;
        auto [width, heigth] = interfaces->surface->getScreenSize();
        if (config->aimbot[weaponId].silent)
            interfaces->surface->setDrawColor(255, 10, 10, 255);
        else 
            interfaces->surface->setDrawColor(10, 255, 10, 255);
        float radius = std::tan(degreesToRadians(config->aimbot[weaponId].fov / 2.f)) / std::tan(degreesToRadians(config->misc.actualFov / 2.f)) * width;
        interfaces->surface->drawOutlinedCircle(width / 2, heigth / 2, radius, 100);
    }
}

**Comment by newcommerdontblame** [comment]
>Yes

everything on spanish bro lmao btw drawfov worked thanks for this

**Comment by caiocinel** [comment]
*Portuguese, just read the code.
