### ISSUE TITLE
FPS Drops and Config Tab gets a Error Message

### ISSUE THREAD

**Issue by namekh** [danielkrupinski/Osiris#1942]
everything important says the title. still dont know how to fix it

**Comment by PriyanshuXavie** [comment]
@danielkrupinski .

**Comment by MasterChief220** [comment]
yeah i got fps drops too. The only fix i found out that reduces the drops in fps is to use the old hook method . Can u elaborate on the config tab error message thougH?


> everything important says the title. still dont know how to fix it

**Comment by danielkrupinski** [comment]
FPS problem should be gone since 1afa0671fc6eed3baa1a18c9f97be3f395f1fa60. It turns out that sv_cheats hook was a hot spot, being called ~200 times a frame.

**Comment by PriyanshuXavie** [comment]
@danielkrupinski so new update will fix this fps problem?
