### ISSUE TITLE
Osiris wont load.

### ISSUE THREAD

**Issue by Straightplus** [danielkrupinski/Osiris#1943]
It just wont load, i have tried compiling myself, and using websites.
I have used, xenos injector and process hacker.

**Comment by RyDeem** [comment]
did you see OneByteLdr ?

**Comment by TheSmartOne1O** [comment]
Use Manual Map in Xenos. These settings work for me. 
![image](https://user-images.githubusercontent.com/52098823/88164899-aa0c0180-cbc9-11ea-9ba2-83f3c6cca01f.png)

**Comment by Straightplus** [comment]
Aight will try

**Comment by Straightplus** [comment]
Ayyy it worked cheers mate, have a good one!
