### ISSUE TITLE
fast question about osiris.vcxproj

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#1944]
how to edit this file when im tryna open osiris.sln opens
![Untitled](https://user-images.githubusercontent.com/65455170/88188022-f6922400-cc3f-11ea-81ac-e85e7e74c199.jpg)

**Comment by deboogergithub** [comment]
wdym by that

**Comment by newcommerdontblame** [comment]
this is what i mean i cant find these lines (sorry for song)
https://streamable.com/603vcw

**Comment by newcommerdontblame** [comment]
nvm i got it
