### ISSUE TITLE
Why do we use new config-save-way ?

### ISSUE THREAD

**Issue by Cyk-Fad** [danielkrupinski/Osiris#1945]
It can't save as Bomb Timer (Waiting For Danie Fix)
I don't want to fix because I don't like new way
why we use that?

**Comment by AbhinayNegi** [comment]
What is new way

**Comment by newcommerdontblame** [comment]
Can you give me ur discord please i wanna ask u something

**Comment by Cyk-Fad** [comment]
> Can you give me ur discord please i wanna ask u something

Right My discrod is Cyk-Fad#8394

**Comment by newcommerdontblame** [comment]
> > Can you give me ur discord please i wanna ask u something
> 
> Right My discrod is Cyk-Fad#8394

i added u my discord is 23223axd#4752 ( i forgot my accs password so dont mind my nickname:D )

**Comment by PriyanshuXavie** [comment]
@Cyk-Fad added you on discord wanna ask you something

**Comment by danielkrupinski** [comment]
Missing objects are fixed now. New config approach is to save only those settings which differ from default ones - this reduces config file size drastically. Moreover it allows you to load numerous configs without collisions (e.g. one config containing skin changer settings,  another with aimbot settings etc.)
