### ISSUE TITLE
Distorted Sound

### ISSUE THREAD

**Issue by anthonyyjoo** [danielkrupinski/Osiris#1946]
Whenever I leave a match and go back to the menu, there's a heavy, distorted sound playing.

My menu music is off

**Comment by caiocinel** [comment]
Try change game priority in Task Manager, this is a problem with heavy CPU usage.

**Comment by anthonyyjoo** [comment]
should i lower the game priority?

**Comment by caiocinel** [comment]
> should i lower the game priority?

Try both, does this only happen with the injected Osiris?

**Comment by anthonyyjoo** [comment]
yeaaa it only happens when its injected with Osiris

ive tried changing the priority to every setting but theres still distorted sound coming out

**Comment by caiocinel** [comment]
Are you using cl_forcepreload?

**Comment by anthonyyjoo** [comment]
ohhhhh is that the problem?

**Comment by caiocinel** [comment]
It costs nothing to test

**Comment by anthonyyjoo** [comment]
Error: Total static audio channels have been used: 160 96, +ui\panorama\bg_dust2_01.wav 97, +ui\panorama\bg_dust2_01.wav 98, +ui\panorama\bg_dust2_01.wav 99, +ui\panorama\bg_dust2_01.wav 100, +ui\panorama\bg_dust2_01.wav 101, +ui\panorama\bg_dust2_01.wav 102, +ui\panorama\bg_dust2_01.wav 103, +ui\panorama\bg_dust2_01.wav 104, +ui\panorama\bg_dust2_01.wav 105, +ui\panorama\bg_dust2_01.wav 106, +ui\panorama\bg_dust2_01.wav 107, +ui\panorama\bg_dust2_01.wav 108, +ui\panorama\bg_dust2_01.wav 109, +ui\panorama\bg_dust2_01.wav 110, +ui\panorama\bg_dust2_01.wav 111, +ui\panorama\bg_dust2_01.wav 112, +ui\panorama\bg_dust2_01.wav 113, +ui\panorama\bg_dust2_01.wav 114, +ui\panorama\bg_dust2_01.wav 115, +ui\panorama\bg_dust2_01.wav 116, +ui\panorama\bg_dust2_01.wav 117, +ui\panorama\bg_dust2_01.wav 118, +ui\panorama\bg_dust2_01.wav 119, +ui\panorama\bg_dust2_01.wav 120, +ui\panorama\bg_dust2_01.wav 121, +ui\panorama\bg_dust2_01.wav 122, +ui\panorama\bg_dust2_01.wav 123, +ui\panorama\bg_dust2_01.wav 124, +ui\panorama\bg_dust2_01.wav 125, +ui\panorama\bg_dust2_01.wav 126, +ui\panorama\bg_dust2_01.wav 127, +ui\panorama\bg_dust2_01.wav 128, +ui\panorama\bg_dust2_01.wav 129, +ui\panorama\bg_dust2_01.wav

this is what comes up in my console after leaving a match

**Comment by caiocinel** [comment]
https://steamcommunity.com/app/730/discussions/0/617329920702527101/?l=portuguese
