### ISSUE TITLE
Aimbot doubt.

### ISSUE THREAD

**Issue by markito12** [danielkrupinski/Osiris#1947]
Is there any option to avoid locking to another target after a kill?

**Comment by stacylol** [comment]
Disable "Between shots" and set Max Inaccuracy to very low, play around with the settings.
If that doesn't help try to decrease the FOV.

**Comment by sserve-kr** [comment]
What "Between shots" do?

**Comment by Finndramere** [comment]
> What "Between shots" do?

if disabled(between shots) aimbot does not activate until a bullet is ready. So basically if you one deag someone with high fov low smooth it will not snap to another target until you can shoot again.
