### ISSUE TITLE
fov (xyz) Changer

### ISSUE THREAD

**Issue by SMACheats** [danielkrupinski/Osiris#1948]
how can you add fov xyz at osiris?

viewmodel_offset_x
viewmodel_offset_y
viewmodel_offset_z
![Unbenannt](https://user-images.githubusercontent.com/25822003/88241042-42b58680-cc89-11ea-8823-82735c89d990.PNG)

is this possible to add? (on osiris)

**Comment by Cyk-Fad** [comment]
sure

**Comment by Cyk-Fad** [comment]
void Misc::customViewmodel() noexcept 
{

    if (config->misc.CustomViewModel) {
        if (!localPlayer)
            return;

        static ConVar* view_x = interfaces->cvar->findVar("viewmodel_offset_x");
        static ConVar* view_y = interfaces->cvar->findVar("viewmodel_offset_y");
        static ConVar* view_z = interfaces->cvar->findVar("viewmodel_offset_z");
        static ConVar* sv_minspec = interfaces->cvar->findVar("sv_competitive_minspec");

        *(int*)((DWORD)&sv_minspec->onChangeCallbacks + 0xC) = 0;

        sv_minspec->setValue(0);
        view_x->setValue(config->misc.viewmodel_x);
        view_y->setValue(config->misc.viewmodel_y);
        view_z->setValue(config->misc.viewmodel_z);
    }
}

**Comment by senisditron** [comment]
@Cyk-Fad 
> void Misc::customViewmodel() noexcept

and it shouldn't be like that?

`void Misc::CustomViewmodel(UserCmd* cmd) noexcept`

**Comment by Florian9900** [comment]
and how i add this (this change ingame not)
![Unbenan2nt](https://user-images.githubusercontent.com/25822003/88310447-f82b1d00-cd0f-11ea-8074-d5681d133fc1.PNG)
![Unben3annt](https://user-images.githubusercontent.com/25822003/88310448-f82b1d00-cd0f-11ea-82f8-baf13a8de772.PNG)
![Unbe1nannt](https://user-images.githubusercontent.com/25822003/88310449-f8c3b380-cd0f-11ea-8bd4-0f004bc9102e.PNG)
![Unbenannt](https://user-images.githubusercontent.com/25822003/88310450-f95c4a00-cd0f-11ea-9b8f-14f73353d7ec.PNG)

**Comment by senisditron** [comment]
@Florian9900 

Look Hooks.cpp and paste this

`Misc::CustomViewmodel(cmd);`

**Comment by newcommerdontblame** [comment]
> and how i add this (this change ingame not)
> ![Unbenan2nt](https://user-images.githubusercontent.com/25822003/88310447-f82b1d00-cd0f-11ea-8074-d5681d133fc1.PNG)
> ![Unben3annt](https://user-images.githubusercontent.com/25822003/88310448-f82b1d00-cd0f-11ea-82f8-baf13a8de772.PNG)
> ![Unbe1nannt](https://user-images.githubusercontent.com/25822003/88310449-f8c3b380-cd0f-11ea-8bd4-0f004bc9102e.PNG)
> ![Unbenannt](https://user-images.githubusercontent.com/25822003/88310450-f95c4a00-cd0f-11ea-9b8f-14f73353d7ec.PNG)

it could be better in visual tab)

**Comment by barbadully** [comment]
![image](https://user-images.githubusercontent.com/60882933/88390905-72fc4280-cdb9-11ea-99ec-316503f909b2.png)
![image](https://user-images.githubusercontent.com/60882933/88391012-9cb56980-cdb9-11ea-84d9-3ae4587ef85a.png)
what in the hell did I do wrong here, won't save at all

**Comment by notgoodusename** [comment]
> ![image](https://user-images.githubusercontent.com/60882933/88390905-72fc4280-cdb9-11ea-99ec-316503f909b2.png)
> ![image](https://user-images.githubusercontent.com/60882933/88391012-9cb56980-cdb9-11ea-84d9-3ae4587ef85a.png)
> what in the hell did I do wrong here, won't save at all

they have to be the same
"viewmodel_x", "Custom Viewmodel X"
those arent the same so the cheat doesnt read it

**Comment by aljawary** [comment]
pls someone make pr of this

**Comment by barbadully** [comment]
> > ![image](https://user-images.githubusercontent.com/60882933/88390905-72fc4280-cdb9-11ea-99ec-316503f909b2.png)
> > ![image](https://user-images.githubusercontent.com/60882933/88391012-9cb56980-cdb9-11ea-84d9-3ae4587ef85a.png)
> > what in the hell did I do wrong here, won't save at all
> 
> they have to be the same
> "viewmodel_x", "Custom Viewmodel X"
> those arent the same so the cheat doesnt read it

I am actually fucking blind, thank u
