### ISSUE TITLE
 particular request

### ISSUE THREAD

**Issue by mabite44** [danielkrupinski/Osiris#1950]
if i cheat on my second account and go back to my main account which has the prime and play without cheating do i have a VAC BAN risk

**Comment by mabite44** [comment]
I'm afraid that the cheat leaves files / traces in my game

**Comment by newcommerdontblame** [comment]
Just duplicate pak001,materials and models files 
when u play without cheat use clear one if u feel uncomfortable

**Comment by danielkrupinski** [comment]
It doesn't change the game files.

**Comment by mabite44** [comment]
> Just duplicate pak001,materials and models files
> when u play without cheat use clear one if u feel uncomfortable
> 
> But u cant get vac for osiris if u asked for this

osiris and really undetectable
it really leaves no trace

**Comment by notgoodusename** [comment]
> osiris and really undetectable ?
> it really leaves no trace ?

the only trace it leaves is on your documents folder, not in your game
