### ISSUE TITLE
NEW UPDATE CSGO (not beta .5.9 launch anymore)

### ISSUE THREAD

**Issue by Kaves89** [danielkrupinski/Osiris#1953]
Hello, since the new update I can no longer play in beta.5.9.

Is there any other way to inject Osiris and play in trusted mode?

**Comment by 0xE232FE** [comment]
Yes and there are already solved issues about this. Just read ;-)

**Comment by Kaves89** [comment]
I was using Corsair injector, already solved whith another injector.

**Comment by jakubiakdev** [comment]
I'm being able to inject just by placing the injector in C:/windows/cheat_folder

**Comment by Heapy1337** [comment]
> I'm being able to inject just by placing the injector in C:/windows/cheat_folder

worked for me with csh injector :D

simply make a folder in C:/Windows
and then give a csh injector and a cheat.dll
rename cheat.dll to cshacked.pl.dll and simply run
csh injector as an admin!
WORKS FOR ME
