### ISSUE TITLE
fake prime effective???

### ISSUE THREAD

**Issue by sserve-kr** [danielkrupinski/Osiris#1955]
I know it's "fake", but after use this, my alternative account don't get banned!
I used rage config on competitive and wingman match, and reported by many people,
but my account still alive.

So... is it real prime???
or just my luck??

**Comment by KernCS** [comment]
What does prime and not getting ban have to do with each other?

**Comment by sserve-kr** [comment]
> What does prime and not getting ban have to do with each other?

prime is increase player's trust factor, so harder to getting ban i think...

**Comment by king1919djdj** [comment]
> > What does prime and not getting ban have to do with each other?
> 
> prime is increase player's trust factor, so harder to getting ban i think...

lol

**Comment by rosesware** [comment]
Fake prime is just a visual lobby thing, don't affect anything in your trust factor.

**Comment by barbadully** [comment]
> > What does prime and not getting ban have to do with each other?
> 
> prime is increase player's trust factor, so harder to getting ban i think...

fucking retards on the internet I swear to fucking God

**Comment by HowToMakeFaceitAB** [comment]
> > > What does prime and not getting ban have to do with each other?
> > 
> > 
> > prime is increase player's trust factor, so harder to getting ban i think...
> 
> fucking retards on the internet I swear to fucking God

hes dumb , yes, but no need to be a complete dick about it, asshole
