### ISSUE TITLE
Turkish characters ranges

### ISSUE THREAD

**Issue by CerberusGame** [danielkrupinski/Osiris#1956]
@danielkrupinski please add Turkish characters ranges.

**Comment by toprak1224** [comment]
googldan imgui türkçe karakter ekleme diye arat çıkar

**Comment by danielkrupinski** [comment]
Already supported:
![image](https://user-images.githubusercontent.com/34515229/88564804-f923bd80-d033-11ea-930f-9c4035e46d60.png)
