### ISSUE TITLE
Config issue

### ISSUE THREAD

**Issue by sugaiYT** [danielkrupinski/Osiris#1957]
So,
I searched for some configs to use and found a config. So far so good.
Then I tried to use it in-game but it just changed the menu nothing more.
I opened the config and then opened my normal config and saw that they were built differently.

new config:
{
	"Aimbot" : 
	[
		{
			"Aimlock" : false,
			"Auto scope" : false,
			"Auto shot" : false,
			"Between shots" : true,
			"Bone" : 2,
			"Enabled" : false,
			"Fov" : 0.0,
			"Friendly fire" : false,
			"Ignore flash" : false,
			"Ignore smoke" : false,
			"Key" : 18,
			"Key mode" : 0,
			"Killshot" : false,
			"Max aim inaccuracy" : 1.0,
			"Max shot inaccuracy" : 1.0,
			"Min damage" : 1,
			"On key" : false,
			"Recoil control X" : 1.0,
			"Recoil control Y" : 1.0,
			"Recoil-based fov" : false,
			"Scoped only" : false,
			"Silent" : true,
			"Smooth" : 1.0,
			"Visible only" : true
		},
		{
			"Aimlock" : false,

My normal one:
{
  "Aimbot": [
    {
      "Between shots": false,
      "Enabled": true,
      "Fov": 3.15,
      "Scoped only": false,
      "Silent": true,
      "Visible only": false
    },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,

I know this is hard to understand but english isnt my first language so I can't really help it.

**Comment by newcommerdontblame** [comment]
can u screenshot ur sources aimbot tab?

**Comment by sugaiYT** [comment]
https://user-images.githubusercontent.com/68751469/88457554-d9e82d00-ce87-11ea-9b46-46723138bd2b.PNG)
https://user-images.githubusercontent.com/68751469/88457559-dc4a8700-ce87-11ea-9eb5-a32be3abe82e.PNG)
https://user-images.githubusercontent.com/68751469/88457562-e076a480-ce87-11ea-891c-262481afa62c.PNG)
https://user-images.githubusercontent.com/68751469/88457565-e3719500-ce87-11ea-8f56-414e74e96574.PNG)
https://user-images.githubusercontent.com/68751469/88457577-f6846500-ce87-11ea-90b0-c7163f8446bb.PNG)

like this?
