### ISSUE TITLE
(REQUEST)velocity line

### ISSUE THREAD

**Issue by koon666** [danielkrupinski/Osiris#1959]
I'm looking for a code for the player's speed lines, whoever, please send me :(

Example: https://prnt.sc/to6lty

**Comment by koahook** [comment]
look at the showVelocity pull, then render that as a line, clamp the line and position it

**Comment by koon666** [comment]
can you help me with this?

**Comment by danielkrupinski** [comment]
Could you explain in detail how it works?

**Comment by koon666** [comment]
> Could you explain in detail how it works?

this works like the velocity with numbers, with each units with the line, the line goes up more. as you can see in the video -> 
 https://youtu.be/7eYDKL2QP_M - https://prnt.sc/tpgm66

**Comment by newcommerdontblame** [comment]
@danielkrupinski check this vid lmao didnt u see movesiris? https://www.youtube.com/watch?v=7bpd4x-loZY
