### ISSUE TITLE
RCS &Aimbot

### ISSUE THREAD

**Issue by cojo1989** [danielkrupinski/Osiris#196]
Hello Daniel, i want to ask if is possible to add RCS standalone (no target) and to make it one slide and for aimbot when you click to lock on near bone to make it to not jump if you have RCS activated. Sorry for my explain but english is not my native language but i hope you understand. Thank you buddy ❤️

**Comment by cojo1989** [comment]
Aaa, and this thing should really add (version check of csgo) for example if an update its made to cs go the hack would not work until you update it and in return to give you a msg like “cs go updated!”

**Comment by Shaxzy** [comment]
@cojo1989 why would you need an update check? The cheat usually works after csgo updates.
