### ISSUE TITLE
Injection Issue

### ISSUE THREAD

**Issue by Cicker21** [danielkrupinski/Osiris#1960]
I downloaded this injector: https://github.com/AMATEURZ1337/load-lib-injector
but still not working, my old injector is not working too. I got message of "module injected!" so teorically is injected, but in game the INSERT key doesnt works. what can i do??. thx in advance

**Comment by Cicker21** [comment]
i tried using xenos injector but when i inject the file csgo closes

**Comment by PriyanshuXavie** [comment]
@Cicker21 
use csh injector

**Comment by Heapy1337** [comment]
same here :P

**Comment by creapygames** [comment]
use this injector work for me youtu.be/ykPv6Ll-gd4

if you wanna use this injector to other cheat just rename it to OTC.dll

**Comment by VuBrian22** [comment]
You didn't run the injector as an administrator. Try going into the properties menu and compatibility tab to change it to run as an admin. I've ran into this problem before. 
![image](https://user-images.githubusercontent.com/25190751/88463881-02156300-ce6b-11ea-88f5-20a973574d2e.png)

**Comment by Cicker21** [comment]
i had to run as admin .....

**Comment by Cicker21** [comment]
thx for all the answers!! <3
