### ISSUE TITLE
Can't save nor load any configs.

### ISSUE THREAD

**Issue by ChrisTooFair** [danielkrupinski/Osiris#1961]
I couldn't load or save any configs i make it says "Debug Error", i tried installing all Visual C++ Runtime Library it still doesn't fix the problem, any fix? It would be helpful.

**Comment by danielkrupinski** [comment]
Could you post here the config file you're trying to load?

**Comment by demonboii** [comment]
[legit_config.zip](https://github.com/danielkrupinski/Osiris/files/4975095/legit_config.zip)
I have to convert it into a ZIP file because GitHub doesn't support the file extension.

**Comment by danielkrupinski** [comment]
This is an empty file and therefore not a valid JSON.

**Comment by demonboii** [comment]
Oh yeah, it can't save any config, that's why its empty, but i fixed the problem rn, the problem is i save configs in-match not on the CS:GO menu, Thank you for responding.
