### ISSUE TITLE
Improve the grenade prediction because it causes fps drops when you're moving

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1964]
title explains it all : )

**Comment by danielkrupinski** [comment]
Osiris uses game's built-in grenade prediction so it can't be optimized unless we implement it ourselves.

**Comment by HowToMakeFaceitAB** [comment]
> Osiris uses game's built-in grenade prediction so it can't be optimized unless we implement it ourselves.

oh, i didn't know, sorry.
