### ISSUE TITLE
f

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#1965]
I made a steam account , I used extreme injector with manual map, I was using osiris and got banned mid match, whole thing took about 1-2 hours, has anyone else gotten banned? btw to note if you guys use Daniel's vac bypass it works wonderfully, Never ever got banned with it :0 , i would recommend it to everyone using any cheat

**Comment by danielkrupinski** [comment]
Extreme injector is known to be detected.

**Comment by HowToMakeFaceitAB** [comment]
> Extreme injector is known to be detected.

Oh, do you recommend any injectors?
