### ISSUE TITLE
[Question] VAC Banned after 5 months

### ISSUE THREAD

**Issue by markito12** [danielkrupinski/Osiris#1966]
Got vac banned after 5 months of legit hacking, what is interesting and wonders me is that last 2 days i started using reportbot, dont know if that has anything to do with the ban.

**Comment by HowToMakeFaceitAB** [comment]
What Injector?

**Comment by Jimmy-Baby** [comment]
I am not sure if or why reportbot would cause a ban. But, it is fairly useless anyways, so you can just avoid it.

Sorry about your ban.

**Comment by SwenzyS** [comment]
What is your injector?

**Comment by markito12** [comment]
> Sorry about your ban.

Thanks, im using NewGaming Injector, [VAC Bypass](https://github.com/danielkrupinski/VAC-Bypass), [CSGO Library Injection Bypass](https://github.com/danielkrupinski/OneByteLdr) and obviously Osiris

**Comment by newcommerdontblame** [comment]
Just because ur INJETCtor:)

**Comment by markito12** [comment]
What injector do you recomend?

**Comment by Jimmy-Baby** [comment]
> > Sorry about your ban.
> 
> Thanks, im using NewGaming Injector, [VAC Bypass](https://github.com/danielkrupinski/VAC-Bypass), [CSGO Library Injection Bypass](https://github.com/danielkrupinski/OneByteLdr) and obviously Osiris
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/31602075/88484806-e207a180-cf47-11ea-8abc-ceed26b80fb4.png)

Well. The best injector you could use is your own kernel byte injector.

Osiris.dll -> binary in byte[] form -> use kernel driver to allocate and write the bytes of Osiris.dll into CSGO :)

I don't know what to recommend because I only use my own injectors. I used to use process hacker 2, I don't know if it works since the new Trusted Mode update though. Give it a shot :)

**Comment by markito12** [comment]
> > > Sorry about your ban.
> > 
> > 
> > Thanks, im using NewGaming Injector, [VAC Bypass](https://github.com/danielkrupinski/VAC-Bypass), [CSGO Library Injection Bypass](https://github.com/danielkrupinski/OneByteLdr) and obviously Osiris
> > ![Screenshot_1](https://user-images.githubusercontent.com/31602075/88484806-e207a180-cf47-11ea-8abc-ceed26b80fb4.png)
> 
> Well. The best injector you could use is your own kernel byte injector.
> 
> Osiris.dll -> binary in byte[] form -> use kernel driver to allocate and write the bytes of Osiris.dll into CSGO :)
> 
> I don't know what to recommend because I only use my own injectors. I used to use process hacker 2, I don't know if it works since the new Trusted Mode update though. Give it a shot :)

Thanks! ill try
