### ISSUE TITLE
What is the best legit setting for flickshots ? (AWP and Scout)

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#1967]
this is my setting

FOV = 1.00
Smooth = 1.00
No Silent
No Aimlock
No Between shots
Ignore Flash
Visible Only
Bone = Nearest

Is this good?

How about you guys?

**Comment by A1gaoshanlaiyige** [comment]
Fov=3.15
Smooth-1.44
Yes Silent
No Aimlock
No Between shots
Ignore Flash
Visible Only
Bone = Nearest
