### ISSUE TITLE
Skin changer is not working after saving config with set of skins.

### ISSUE THREAD

**Issue by PriyanshuXavie** [danielkrupinski/Osiris#1970]
the csgo stops with an abort error once i load after saving config with set of skins applied.

**Comment by danielkrupinski** [comment]
Post your config here, please.

**Comment by PriyanshuXavie** [comment]
[lel.zip](https://github.com/danielkrupinski/Osiris/files/4980675/lel.zip)

**Comment by PriyanshuXavie** [comment]
> [lel.zip](https://github.com/danielkrupinski/Osiris/files/4980675/lel.zip)

@danielkrupinski

**Comment by danielkrupinski** [comment]
It works just fine for me. Make sure you're not manual-mapping a dll compiled in debug configuration.

**Comment by PriyanshuXavie** [comment]
@danielkrupinski can i talk to personally anywhere? any social platform, even discord?
