### ISSUE TITLE
How to get Player Clantag?

### ISSUE THREAD

**Issue by userplayer77** [danielkrupinski/Osiris#1973]
Hey, i got an idea with clantags, but i need to get a player clantag, and i dont know how to do that.
The idea: when i click 'Check' button, change my clantag to 'user_check' to a second, if another user using my version of osiris, always checking players clantag, if anyone clantag changed to 'user_check', change his clantag 'user_imchecked', and my cheat do checking always clantags, and when anyone clantag is 'user_imchecked', set a int, to +1, or get player name. (to show users in menu)
I know everything how to do, except, to every get players clantag on the server.
Can you help me? :D
Sorry for bad eng :c

**Comment by danielkrupinski** [comment]
You can get clan tag from CCSPlayerResource->m_szClan.

**Comment by userplayer77** [comment]
i tried to get in this way, but didnt work. i got a random number on map change or idk.

'Misc.cpp'

	//Testing self clantag detect first
	const auto locId = localPlayer->getUserId();

	auto clant = interfaces->entityList->getEntity(locId)->GetClanTag();

	std::string cmd = "echo clantag: " + std::to_string(clant);

	interfaces->engine->clientCmdUnrestricted(cmd.c_str());

'Entity.h'

	NETVAR(GetClanTag, "CCSPlayerResource", "m_szClan", char)

From Console:

"clantag: 0"
"clantag: 0"
...
"i not edited anything, but random change"
"clantag: 58"
"clantag: 58"
...

What is the problem?

![issue](https://user-images.githubusercontent.com/61803005/88531219-cad9ba00-d002-11ea-8c29-986bf577aba3.png)

**Comment by danielkrupinski** [comment]
Try defining it as **char[16]**.

**Comment by danielkrupinski** [comment]
Also CCSPlayerResource is a separate entity, not a player subclass.

**Comment by userplayer77** [comment]
I changed 'Misc.cpp'

	const auto locIndex = localPlayer->index();

	char clant[16];

	sprintf_s(clant, interfaces->entityList->getEntity(locIndex)->GetClanTag());

	std::string clanstring = clant;
	std::string cmd = "echo clantag: " + clanstring;

	interfaces->engine->clientCmdUnrestricted(cmd.c_str());

and 'Entity.h'

	NETVAR(GetClanTag, "CCSPlayerResource", "m_szClan", char[16])

I tried with real clantag, and fake clantag, but 'clant' is always nothing, and console only show up:
'clantag: '
'clantag: '
...

**Comment by userplayer77** [comment]
i tried many to make that, but didn't work :C
Please can you give me an example how to get a Player Clantag? I have many ideas with it :(

**Comment by danielkrupinski** [comment]
```cpp
NETVAR(clanTag, "CCSPlayerResource", "m_szClan", char[65][16])
```

and

```cpp
for (int i = interfaces->engine->getMaxClients() + 1; i <= interfaces->entityList->getHighestEntityIndex(); ++i) {
    const auto playerResource = interfaces->entityList->getEntity(i);
    if (!playerResource || playerResource->getClientClass()->classId != ClassId::CSPlayerResource)
        continue;

    if (localPlayer)
        memory->debugMsg("LOCAL CLAN: %s\n", playerResource->clanTag()[localPlayer->index()]);

    break;
}
```

**Comment by sheavyq** [comment]
Hey daniel, what is the CSPlayerResource ClassId?

**Comment by sheavyq** [comment]
Hey, can you help me what is the problem? I tried to get player clantag in your way, and ClassId::CSPlayerResource is didn't definied for me, i changed it to ClassId::CSPlayer, but i got nothing from console, when i delete '|| playerResource->getClientClass()->classId != ClassId::CSPlayerResource' from the if, i got random characters/game like this: ��.
Can you help me? >.<
