### ISSUE TITLE
Suggestion Thread

### ISSUE THREAD

**Issue by TheFantasticLoki** [danielkrupinski/Osiris#1974]
**Hiya!!!** This is a suggestion thread ig cause I have a couple.
 Add the esp from aw where it shows where the molly actually is based on where it spreads.  ex.
![image](https://user-images.githubusercontent.com/26889568/88538632-ed50e080-cfcc-11ea-81fa-febfc849dc08.png)

Skin search #1963 This would make the skin changer alot more usable. nskinz just hasn't been updated in a while.

Option for disabling the recoil crosshair on pistols should be a top priority cause trying to aim with pistols and accurately tap with a moving crosshair is aids.

Please bring the ping based backtrack from PR #960 to the cheat. it's a lot easier to just use that then manually set the backtrack every game and makes it more legit. I got called out much less using it vs manual.

Aimbot hasn't been touched in a while so why not shot delay for auto shot for flickshots. Using the triggerbot and aimbot with the same keys doesn't work half the time.
Also I think scoped only option is bugged. and also shouldn't be on by default. I think ignore flash and smoke should be on by default so your not locking on through smoke or blind by accident. Also possibly add an option for aimbot to switch to chest hitbox if target is beyond say 10-15 meters.

#1016 Should be implemented.

Steps visuals shouldn't be gone I loved those.

I had made my own branch with several more PRs but it was too much to keep updating and I stopped playing for a while.
 Anyways that's all for now. Love ya @danielkrupinski keep up the wonderful work.

**Comment by newcommerdontblame** [comment]
he doesn't even check suggestion posts i think xd

**Comment by TheFantasticLoki** [comment]
Hmm maybe he does maybe he doesn't.

**Comment by barbadully** [comment]
> he doesn't even check suggestion posts i think xd

he does but doesn't care about them that much because all people do here are beg for dumb shit that they can do themselves like 80% of this issue

**Comment by PriyanshuXavie** [comment]
@barbadully  not everyone is a coder.

**Comment by PriyanshuXavie** [comment]
> > he doesn't even check suggestion posts i think xd
> 
> he does but doesn't care about them that much because all people do here are beg for dumb shit that they can do themselves like 80% of this issue

@barbadully Not everyone is a good coder.

**Comment by TheFantasticLoki** [comment]
it's not that we can't do it it's that it's hard to keep our own forks with additional changes up to date with the base. Plus having him add these in gives me more confidence that it'll be coded right.

**Comment by notgoodusename** [comment]
ping based backtrack is on by default and it shouldnt, by any means, not be, ping based backtrack disabled will only fuck up backtracking in general
also you understood ignore flash and smoke wrong, when toggled it will ignore flash/smoke
