### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by SapphireCodenz** [danielkrupinski/Osiris#1978]
Hi daniel, just a quick question, is there anyway we can talk? do you use discord? if not, make a discord account and a discord server for osiris!

**Comment by Jimmy-Baby** [comment]
he's probably seen this question a lot and will likely not answer.
Why do you need to talk to him? Is there anything I can help with? I am sup4 1337 haxor coder ;)

**Comment by danielkrupinski** [comment]
The Lepus#5583

**Comment by Jimmy-Baby** [comment]
rest in peace to that discord account x)
