### ISSUE TITLE
Crash on config load after skin search update.

### ISSUE THREAD

**Issue by TheFantasticLoki** [danielkrupinski/Osiris#1980]
Currently looking into what option is causeing this will update thread when I do.

Edit: Think it's probably something with my skins cause other configs load fine. Broken Config for testing purposes.
[config.zip](https://github.com/danielkrupinski/Osiris/files/4984502/config.zip)

**Comment by Jimmy-Baby** [comment]
Build as debug, attach to process, wait for the breakpoint by repeating what makes it crash 😁

**Comment by TheFantasticLoki** [comment]
`Exception thrown at 0x761343D2 in csgo.exe: Microsoft C++ exception: std::out_of_range at memory location 0x0097A044.
The thread 0x759c has exited with code 100 (0x64).
The thread 0x5844 has exited with code 100 (0x64).
The thread 0x7940 has exited with code 100 (0x64).
The thread 0x4900 has exited with code 100 (0x64).
The thread 0x6500 has exited with code 100 (0x64).
The thread 0x46e0 has exited with code 100 (0x64).
The thread 0x13b8 has exited with code 100 (0x64).
The thread 0x7954 has exited with code 100 (0x64).
The thread 0x7518 has exited with code 100 (0x64).
The thread 0x3b20 has exited with code 100 (0x64).
The thread 0x74a4 has exited with code 100 (0x64).
The thread 0x74ac has exited with code 100 (0x64).
The thread 0x7564 has exited with code 100 (0x64).
The thread 0x7560 has exited with code 100 (0x64).
The thread 0x2868 has exited with code 100 (0x64).
The thread 0x7558 has exited with code 100 (0x64).
The thread 0x6abc has exited with code 100 (0x64).
The thread 0x76c8 has exited with code 100 (0x64).
The thread 0x75c4 has exited with code 100 (0x64).
The thread 0x6ef8 has exited with code 100 (0x64).
The thread 0x77f0 has exited with code 100 (0x64).
The thread 0x74b0 has exited with code 100 (0x64).
The thread 0x74c8 has exited with code 100 (0x64).
The thread 0x74c4 has exited with code 100 (0x64).
The thread 0x7594 has exited with code 100 (0x64).
The thread 0x75c8 has exited with code 100 (0x64).
The thread 0x5f70 has exited with code 100 (0x64).
The thread 0x7818 has exited with code 100 (0x64).
The thread 0x781c has exited with code 100 (0x64).
The thread 0x2ba0 has exited with code 100 (0x64).
The thread 0x7bd0 has exited with code 100 (0x64).
The thread 0x2338 has exited with code 100 (0x64).
The thread 0x7890 has exited with code 100 (0x64).
The thread 0x4658 has exited with code 100 (0x64).
The thread 0x7654 has exited with code 100 (0x64).
The thread 0x7b70 has exited with code 100 (0x64).
The thread 0x7928 has exited with code 100 (0x64).
The thread 0x6a28 has exited with code 100 (0x64).
The thread 0x7a2c has exited with code 100 (0x64).
The thread 0x764c has exited with code 100 (0x64).
The thread 0x253c has exited with code 100 (0x64).
The thread 0x66f4 has exited with code 100 (0x64).
The thread 0x75d0 has exited with code 100 (0x64).
The thread 0x2c4c has exited with code 100 (0x64).
The thread 0x73f8 has exited with code 100 (0x64).
The thread 0x6008 has exited with code 100 (0x64).
The thread 0x6404 has exited with code 100 (0x64).
The thread 0x4814 has exited with code 100 (0x64).
The thread 0x27c0 has exited with code 100 (0x64).
The thread 0x42d4 has exited with code 100 (0x64).
The thread 0x1930 has exited with code 100 (0x64).
The thread 0x159c has exited with code 100 (0x64).
The thread 0x1658 has exited with code 100 (0x64).
The thread 0x29a4 has exited with code 100 (0x64).
The thread 0x5b54 has exited with code 100 (0x64).
The thread 0x3868 has exited with code 100 (0x64).
The thread 0x1af4 has exited with code 100 (0x64).
The thread 0x56d8 has exited with code 100 (0x64).
The thread 0x4040 has exited with code 100 (0x64).
The thread 0x4ac0 has exited with code 100 (0x64).
The thread 0x6720 has exited with code 100 (0x64).
The thread 0x6e68 has exited with code 100 (0x64).
The thread 0x634 has exited with code 100 (0x64).
The thread 0x1f18 has exited with code 100 (0x64).
The thread 0x406c has exited with code 100 (0x64).
The thread 0xd94 has exited with code 100 (0x64).
The thread 0x5708 has exited with code 100 (0x64).
The thread 0x6a80 has exited with code 100 (0x64).
The thread 0x1a38 has exited with code 100 (0x64).
The thread 0x3f40 has exited with code 100 (0x64).
The thread 0x36f0 has exited with code 100 (0x64).
The thread 0x2498 has exited with code 100 (0x64).
The thread 0x3184 has exited with code 100 (0x64).
The thread 0x6940 has exited with code 100 (0x64).
The thread 0x313c has exited with code 100 (0x64).
The thread 0x75b8 has exited with code 100 (0x64).
The thread 0x76c0 has exited with code 100 (0x64).
The program '[26828] csgo.exe' has exited with code 100 (0x64).`

**Comment by TheFantasticLoki** [comment]
seems to be something with my chams in my config. That cause a new config to start crashing when I transfered chams settings

**Comment by Jimmy-Baby** [comment]
> seems to be something with my chams in my config. That cause a new config to start crashing when I transfered chams settings
>

It's probably best you screenshot where in your code the crash happens if you want help :) 

not the debug log, that doesn't really tell me anything.

**Comment by danielkrupinski** [comment]
Thanks for reporting the issue, it's fixed now.
