### ISSUE TITLE
localPlayerEyePosition is not used

### ISSUE THREAD

**Issue by chrisp132** [danielkrupinski/Osiris#1981]
https://github.com/danielkrupinski/Osiris/blob/5c639663cf15f1632a0b0c490b3ea5f29e1c388c/Osiris/Hacks/Aimbot.cpp#L175

https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hacks/Aimbot.cpp#L182

**Comment by Jimmy-Baby** [comment]
Wot. You say it's not used but also link to the line exactly where it IS used.. ???

And even if it wasn't used, it's just a pointer; the value would still be used by the game in memory so there's no performance impact by just creating a reference to it. 

there's no real reason to create a new issue for this.

**Comment by chrisp132** [comment]
Apologise, I should have described the issue (more of a minor annoyance) better.

localPlayerEyePosition is declared as a variable on line 146 but only used on line 163.
localPlayer->getEyePosition() is later called on line 175 and 182 instead of using localPlayerEyePosition.

**Comment by Jimmy-Baby** [comment]
> Apologise, I should have described the issue (more of a minor annoyance) better.
> 
> localPlayerEyePosition is declared as a variable on line 146 but only used on line 163.
> localPlayer->getEyePosition() is later called on line 175 and 182 instead of using localPlayerEyePosition.

Right, I see.

It might be better off just removing the variable and using `getEyePosition()` in both calculations, as it takes my machine around 10ms (when debugging at the same time) to iterate the bones list meaning the second time `calculateRelativeAngle()` is used, the eye position is out of date, which you may not want with an aimbot especially. But overall, yes, a very minor issue hehe
