### ISSUE TITLE
ImGui killfeed crashing game

### ISSUE THREAD

**Issue by sheavyq** [danielkrupinski/Osiris#1984]
Hey, I created a imgui killfeed, for servers, where killfeed is blocked, and to sort player kills, and deaths.
I included DirectX in Misc:

player_hurt Event (in misc.cpp):

```
std::string cmda;
std::string cmdv;
std::string cmdw;
int cmddh;

bool player_killed = false;
bool player_damaged = false;

	void Misc::PlayerHurt(GameEvent& event) noexcept
	{
		for (int i = 1; i <= interfaces->engine->getMaxClients(); ++i) {
			PlayerInfo playerInfo;

			if (!interfaces->engine->getPlayerInfo(i, playerInfo))
				continue;

			if (!localPlayer || !localPlayer->isAlive())
				return;

			const auto ent = interfaces->entityList->getEntity(i);
			const auto entId = ent->getUserId();

			if (event.getString("weapon") == "taser")
			{
				return;
			}

			if (event.getInt("attacker") == entId)
			{
				cmda = playerInfo.name;
			}

			if (event.getInt("userid") == entId)
			{
				cmdv = playerInfo.name;
			}


		}

		if (cmda == "" || cmdv == "")
		{
			return;
		}
		else
		{

			if (event.getInt("health") < 1)
			{
				cmdw = event.getString("weapon");
				player_killed = true;
			}
			else
			{
				cmdw = event.getString("weapon");
				cmddh = event.getInt("dmg_health");
				player_damaged = true;
			}
		}
	}
```

And the ImGui List (in misc.cpp, and hooked in Hooks.cpp line 256: Misc::KillList();):

```
ImGui::SetNextWindowSize({ 300.0f, 200.0f }, ImGuiCond_Once);
	ImGuiWindowFlags windowFlags = ImGuiWindowFlags_NoCollapse;
	if (!gui->open) windowFlags |= ImGuiWindowFlags_NoInputs;
	ImGui::PushStyleVar(ImGuiStyleVar_WindowTitleAlign, { 0.5f, 0.5f });
	ImGui::Begin("Killfeed", nullptr, windowFlags);
	ImGui::PopStyleVar();

	if (player_killed == true)
	{
		listfull = listfull + cmda + " killed " + cmdv + " with " + cmdw + "\n";
		cmda = "";
		cmdv = "";
		player_killed = false;
	}

	ImGui::TextWrapped("%s", listfull);

	ImGui::End();

	//std::sort(clientlist.begin(), clientlist.end());
	//for (std::string& s : clientlist)

	ImGui::SetNextWindowSize({ 300.0f, 200.0f }, ImGuiCond_Once);
	if (!gui->open) windowFlags |= ImGuiWindowFlags_NoInputs;
	ImGui::PushStyleVar(ImGuiStyleVar_WindowTitleAlign, { 0.5f, 0.5f });
	ImGui::Begin("Damagefeed", nullptr, windowFlags);
	ImGui::PopStyleVar();


	if (player_damaged == true)
	{
		listfulldamaged = listfulldamaged + cmda + " damaged " + cmdv + " with " + cmdw + " -" + std::to_string(cmddh) + "\n";
		cmda = "";
		cmdv = "";
		player_damaged = false;
	}

	ImGui::TextWrapped("%s", listfulldamaged);

	ImGui::End();
```

![killdamagefeed](https://user-images.githubusercontent.com/68903936/88658615-00020d00-d0d4-11ea-921d-f8d7fae30661.png)

And the List always set to "", on round end, to clear the list.

**Everything works fine with this,** but my game crash randomly (i think only in community servers), and i think, crashing by the directx hook accessing to entitylist or i dont know.
Can you help me how to fix that?

**Comment by caiocinel** [comment]
Text encoding problem? Test without displaying the names of the players to see

**Comment by notgoodusename** [comment]
check for entity before using it, and check for event too, localPlayer check should be at the start,

**Comment by sheavyq** [comment]
> Text encoding problem? Test without displaying the names of the players to see

Thanks for commenting, but the problem is not with the encoding, i created a for, what erease all characters except abc characters, and i disabled menu's and i write it on the console only, and i crashing again. the problem is, what @notgoodusename commented.

> check for entity before using it, and check for event too, localPlayer check should be at the start.

Thanks a lot, i checked ent at start and didn't crash :D
