### ISSUE TITLE
Insert does not work !

### ISSUE THREAD

**Issue by cojo1989** [danielkrupinski/Osiris#199]
Hello guys, when i load the config the insert it`s not working anymore i don`t know why... i even create new configs any ideea why? On my laptop it`s working but on my pc it`s not... save version of Osiris.

**Comment by memeToasty** [comment]
Look at the menu button its changeable

**Comment by cojo1989** [comment]
I don`t understand what do you say buddy sorry.

**Comment by Shaxzy** [comment]
Maybe you accidently changed the menu key in your cfg.

**Comment by effex1337** [comment]
Yeah you probably did that.
Try pressing alt that happened to me once as well.

**Comment by NexSqaud** [comment]
```c++
int menuKey{ 0x2D }; // VK_INSERT
```
Config.h, line 168
[Virtual-key codes](https://docs.microsoft.com/en-us/windows/desktop/inputdev/virtual-key-codes)

**Comment by pisklakboo** [comment]
its still not working

**Comment by cojo1989** [comment]
It was not change anything... i just resave it and everything work now... i don`t know why happen that. All happen when i change the CFG from Laptop to PC i don`t know why... it was opening the cheat ->load config and i could not close it.

**Comment by pisklakboo** [comment]
im using DLL Injector v2 i think this program doesnt work, any help?

**Comment by NexSqaud** [comment]
@cojo1989 when you load config, menu key changes too. Check Misc after config load

**Comment by cojo1989** [comment]
The problem is after i load it nothing work. Its freezing. I dont know why... i try with some friends for some of them work for others the same

**Comment by memeToasty** [comment]
maybe the config you are using is from an earlier version of Osiris, thus not working on new versions at the moment.
