### ISSUE TITLE
Get Player Clantag didn't working

### ISSUE THREAD

**Issue by sheavyq** [danielkrupinski/Osiris#1991]
Hey, i found this issue, #1973 you show an example how to do this, but i got problem: when i trying to get player clantag in your way, ClassId::CSPlayerResource is didn't definied for me, i changed it to ClassId::CSPlayer, but i got nothing from console. When i delete '|| playerResource->getClientClass()->classId != ClassId::CSPlayerResource' from the if, i got random characters/game like this: ����.
Can you help me, what is the problem? >.<

**Comment by danielkrupinski** [comment]
17eb96966108ee82cd94406f43df4fcc4bd32344?

**Comment by sheavyq** [comment]
> [17eb969](https://github.com/danielkrupinski/Osiris/commit/17eb96966108ee82cd94406f43df4fcc4bd32344)?

It didn't working in my version, but i downloaded the new version and working, thanks a lot :D
