### ISSUE TITLE
ImGui::Combo bug

### ISSUE THREAD

**Issue by avidretard** [danielkrupinski/Osiris#1992]
Cant open the bottom two combos and the 3 combos are sort of "merged together" as i can only open the top one but it shows the options from the other two.
![help](https://user-images.githubusercontent.com/68190750/88917427-a29ac700-d25f-11ea-8da5-d4597f3f540d.png)

![image](https://user-images.githubusercontent.com/68190750/88917469-b6462d80-d25f-11ea-9a80-1b0b61d0a9a5.png)

**Comment by dapaster** [comment]
ImGui::PushID;
    ImGui::PopID;

**Comment by avidretard** [comment]
> you forgot
> 
> ```
> ImGui::PushID;
> ImGui::PopID;
> ```

thanks alot
