### ISSUE TITLE
center tabs

### ISSUE THREAD

**Issue by braken1** [danielkrupinski/Osiris#1996]
hello ive been trying to put all the tabs in the centre so it will look better but i cant really do it any help pls?[
![osiris](https://user-images.githubusercontent.com/68773970/88985722-5a1bf180-d2d1-11ea-8e6f-d307a1d075b7.png)
](url)

**Comment by KernCS** [comment]
ImGui::SetCursorPosX((ImGui::GetWindowWidth() - 150 + ImGui::GetStyle().ItemSpacing.x) / 2);
ImGui::Button("aimbot", ImVec2(75, 20));
ImGui::SameLine();
ImGui::Button("idk", ImVec2(75, 20));

^Don't remember if osiris use buttons in the menu? but that should work

**Comment by braken1** [comment]
it works with these tabs i tried to put your code there in many ways but i cant get i to work

**Comment by koon666** [comment]
can you give me the code to put the osiris name at the top of the menu? pls :(

**Comment by braken1** [comment]
void GUI::renderGuiStyle2() noexcept
{
    ImGui::SetNextWindowSize({ 600.0f, 420.0f });
    ImGui::Begin("Osiris", nullptr, windowFlags | ImGuiWindowFlags_NoTitleBar);
    ImGui::BeginTabBar;
    ImGui::SetCursorPosX((ImGui::GetWindowWidth() - 150 + ImGui::GetStyle().ItemSpacing.x) / 1.62);
    ImGui::Text("osiris");

**Comment by koon666** [comment]
can you give me the code that you left the ends of the square menu too? srry :(

**Comment by braken1** [comment]
just go to imgui.cpp and edit everything what says rounding at 0

**Comment by koon666** [comment]
ty :)

**Comment by koon666** [comment]
do you know how to do it every time you inject, does it open in the "One Window" style?

**Comment by braken1** [comment]
yes renderGuistyle2 is one windowed mode so try launching it before norman menu bar
