### ISSUE TITLE
is anti aim even working

### ISSUE THREAD

**Issue by sheeshbrobro** [danielkrupinski/Osiris#1997]
how do i know if its working is there any desync visual?

**Comment by A1gaoshanlaiyige** [comment]
Call your friend

**Comment by sserve-kr** [comment]
anti aim working, but it's sucks.
I don't use that on my rage cfg, and it's better than use anti aim.

**Comment by newcommerdontblame** [comment]
> anti aim working, but it's sucks.
> I don't use that on my rage cfg, and it's better than use anti aim.

Lol 

>Rage
>Osiris

**Comment by rubieowo** [comment]
Yaw (Desync) doesn't work afaik
