### ISSUE TITLE
Error: Bone access not allowed

### ISSUE THREAD

**Issue by infinity1211** [danielkrupinski/Osiris#1998]
![boneacess](https://user-images.githubusercontent.com/65710399/88998058-cff27e00-d30e-11ea-97ed-3e357c8299e6.png)

**Comment by danielkrupinski** [comment]
Probably an issue with your code. Don't call setupBones from DirectX thread.

**Comment by notgoodusename** [comment]
its completly normal to get that error message just ignore it
