### ISSUE TITLE
random seed button for pattern skins?

### ISSUE THREAD

**Issue by TheFantasticLoki** [danielkrupinski/Osiris#1999]
Think about it. Would be nice to have

**Comment by danielkrupinski** [comment]
But can't you just enter "random" number as a seed?

**Comment by TheFantasticLoki** [comment]
I wanted this so the seed would be random every time you bought the weapon without going into the menu every time

**Comment by rosesware** [comment]
I'm shocked.

**Comment by TheFantasticLoki** [comment]
no you can't as far as latest build is concerned.
