### ISSUE TITLE
Half Glow

### ISSUE THREAD

**Issue by mlhkr** [danielkrupinski/Osiris#2]
Hi,
Enemies are painted half just under their bellies (belts) are painted.

**Comment by mlhkr** [comment]
I'm gonna do that but today I got the fresh copy from git to compile but as far as I can see the last commit broke the code. please check the attachment.
[errors.txt](https://github.com/danielkrupinski/Osiris/files/2522000/errors.txt)

**Comment by danielkrupinski** [comment]
I see, will fix tomorrow. You can reset your local repo to state at commit 5657c20a585f975537228d6850bc9893f8666e1a which should compile.

**Comment by danielkrupinski** [comment]
Compilation errors should now be fixed. Please test again.

**Comment by mlhkr** [comment]
I've compiled the latest version and now seems like it's working.
The glows are OK.
