### ISSUE TITLE
Insert not working, im using DLL Injector v2

### ISSUE THREAD

**Issue by pisklakboo** [danielkrupinski/Osiris#200]
when i injected it, i pressed insert in cs go and didnt work

**Comment by astron-dev** [comment]
The issue is on your site the cheat works fine

**Comment by Asado-san** [comment]
> when i injected it, i pressed insert in cs go and didn't work

Q. did the Dll worked on your PC previously ?
Q did you have proper vs redist installed ? 
Q. is your IDE compiler set to your version of tool set &  OS version.

A. Probably your injector is not working. Try extreme injector to check if it injects
A. no point opening 2 threads.
A. the issue section is for debugging purposes as far i know if it doesn't work or inject theirs no wrong with the code. it's just in your PC, cause if it's a bug it should inject & make CS crash. not being injected is a error on the injector not on the dll

**Comment by NexSqaud** [comment]
Compile with VS2019? Inject method? run injector as admin?

**Comment by danielkrupinski** [comment]
Sorry, can't help you.
