### ISSUE TITLE
Osiris still work ?

### ISSUE THREAD

**Issue by yezz123** [danielkrupinski/Osiris#2000]
I inject DLL file on the game for the third time and nothing work what i can do 😅
this is my laptop performance :
HP OMEN 15.6" Gaming Laptop 144Hz i7-8750H 16GB RAM 1TB HDD 128GB SSD RTX 2070 8GB Max-Q

**Comment by braken1** [comment]
try another injector it worked for me i use rando now

**Comment by yezz123** [comment]
give me the injector ?
i use this one https://www.dllinjector.com/

**Comment by braken1** [comment]
braken #0133 ill send you

**Comment by toprak1224** [comment]
try this https://github.com/BohanRen/BobHCSGOInjector   work for trusted mod

**Comment by aljawary** [comment]
Its working fine

**Comment by yezz123** [comment]
give me the injector please?

**Comment by toprak1224** [comment]
> give me the injector please?

 https://github.com/BohanRen/BobHCSGOInjector work for trusted mod
