### ISSUE TITLE
Question or Issue regarding Use of Silent aim .

### ISSUE THREAD

**Issue by AbhinayNegi** [danielkrupinski/Osiris#2001]
I was trying silent aim and I know what it does, then I came to know that it is the only client-sided only so what is the reason for this option in aimbot when it is not server-sided. I know making the server-side is challenging but what is the point for client-side only, because in the demo it is visible.

**Comment by braken1** [comment]
its for rage so you dont get seizure from aim shaking i guess

**Comment by DoomFishWasTaken** [comment]
_server side silent aim (aka psilent) was patched years ago_

**Comment by AbhinayNegi** [comment]
ok thanks
