### ISSUE TITLE
[Help] How to add custom weapon models? or custom Player models into enemy?

### ISSUE THREAD

**Issue by sheavyq** [danielkrupinski/Osiris#2005]
I think use FindMDL, but i dont know how to include that in osiris. Can you help me? :D

**Comment by NekoRem** [comment]
I'd recommend using Precache models since its better and applies the model instantly instead of needing to change map
Relevant documentation: https://www.unknowncheats.me/forum/counterstrike-global-offensive/214919-precache-models.html

**Comment by sheavyq** [comment]
> I'd recommend using Precache models since its better and applies the model instantly instead of needing to change map
> Relevant documentation: [https://www.unknowncheats.me/forum/counterstrike-global-offensive/214919-precache-models.html](url)

i try to use Visuals::playerModel() base to make that, but i didnt know how to set my local weapon model, i tried this way, but didnt work:
`if (const auto model = "models/weapons/awp/freedom.mdl") {
		if (auto activeWeapon{ localPlayer->getActiveWeapon() }; activeWeapon)
			{
				if (activeWeapon && activeWeapon->itemDefinitionIndex2() == WeaponId::Awp)
				{
					if (const auto modelprecache = interfaces->networkStringTableContainer->findTable("modelprecache")) {
						modelprecache->addString(false, model);
					}
				}
			}

		const auto cwid = interfaces->entityList->getEntityFromHandle(localPlayer->getActiveWeapon()->handle());

		cwid->setModelIndex(interfaces->modelInfo->getModelIndex(model));
    }`

Can you help me how to make that? :D

**Comment by sheavyq** [comment]
> I'd recommend using Precache models since its better and applies the model instantly instead of needing to change map
> Relevant documentation: [https://www.unknowncheats.me/forum/counterstrike-global-offensive/214919-precache-models.html](url)

I precached my model in Visuals.cpp at Visuals::playerModel(): 
	modelprecache->addString(false, "models/weapons/awp/freedom.mdl");

and change weapon model(at Visuals::playerModel())
	const auto cwid = interfaces->entityList->getEntityFromHandle(localPlayer->getActiveWeapon()->handle());
	cwid->setModelIndex(interfaces->modelInfo->getModelIndex("models/weapons/awp/freedom.mdl"));

this didnt change anything, can you help me what is wrong with this code? :d
