### ISSUE TITLE
Randomly lost connection/Disconnected when in MM [Old Osiris Version]

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#2006]
I don't want to use the latest osiris because my osiris have many features inside and I don't want to start from the beginning again.

Is there anything that i forgot to update?

Can someone tell me what cause this ?

**Comment by dapaster** [comment]
No my internet connection is perfectly fine

**Comment by newcommerdontblame** [comment]
Same issue with my source when i join mm it disconnects me and say timed out

**Comment by RyDeem** [comment]
Well if it is an old osiris version there is not really much help that can be provided.

**Comment by caiocinel** [comment]
I haven't updated my source since adding the new json library and it is 100%, update your code manually following each commit, with that you continue with your functions and stay updated.

**Comment by dapaster** [comment]
Everytime getting disconnected, this error appear

![image](https://user-images.githubusercontent.com/60472098/89216288-b39b5d80-d5fc-11ea-977c-edde7a5d712a.png)
![image](https://user-images.githubusercontent.com/60472098/89216314-c1e97980-d5fc-11ea-818d-e673bba74a34.png)

**Comment by NekoRem** [comment]
> Everytime getting disconnected, this error appear
> 
> ![image](https://user-images.githubusercontent.com/60472098/89216288-b39b5d80-d5fc-11ea-977c-edde7a5d712a.png)
> ![image](https://user-images.githubusercontent.com/60472098/89216314-c1e97980-d5fc-11ea-818d-e673bba74a34.png)

This error can be caused my a multitude of things but most of the time its caused by your antivirus. You can try `netsh winsock reset` in an administrator command prompt. Although its most likely not the problem it might possibly be it.
