### ISSUE TITLE
(REQUEST) Add bloom remover

### ISSUE THREAD

**Issue by Frouk3** [danielkrupinski/Osiris#2007]
I played in my server with sv_cheats 1 and with disabling bloom i get some fps

**Comment by notgoodusename** [comment]
how do you remove bloom?

**Comment by Frouk3** [comment]
> how do you remove bloom? (what convar)

mat_disable_bloom

**Comment by RyDeem** [comment]
here you go @Frouk3 #2010

**Comment by danielkrupinski** [comment]
Disabling postprocessing also disables bloom, doesn't it?

**Comment by RyDeem** [comment]
I do think so dan heh. But i made it standalone if he wants it.

**Comment by Frouk3** [comment]
mat_disable_bloom gives 5-10 fps but i don`t know how many fps gives in other pc
