### ISSUE TITLE
Fix Stream Proof Esp

### ISSUE THREAD

**Issue by Frouk3** [danielkrupinski/Osiris#2008]
so when i moving mouse box and other esp got delay of follow player its looks like esp doesn't hook to player

**Comment by tirziz** [comment]
since it using overlay hook. that issue cant be help

**Comment by danielkrupinski** [comment]
Show video

**Comment by RyDeem** [comment]
I just tested it seems spot on.
do you have low fps? (idk if that would even influence a delay )

**Comment by Frouk3** [comment]
> Show video

With new update this delay is disappeared
