### ISSUE TITLE
Aimbot shoot delay between shoots

### ISSUE THREAD

**Issue by Frouk3** [danielkrupinski/Osiris#2009]
When i toogle on autoshoot aimbot spent all ammo

**Comment by RyDeem** [comment]
Use "max aim inaccuracy" and "max shot inaccuracy", they work kind of like a timer but based on the current recoil.
try a value of 0.02000 in both fields to see what im talking about.
(you can hold Control Key and press mouse1 on a field with a numeric value to edit it by text not slider)

**Comment by notgoodusename** [comment]
> When i toogle on autoshoot aimbot spent all ammo

this is because autoshoot doesnt check if there is an entity

**Comment by aljawary** [comment]
maybe someone can make shotdelay for auto shot

**Comment by aljawary** [comment]
make shotdelay for autoshot
in Aimbot.cpp

>             if (config->aimbot[weaponIndex].autoShot && activeWeapon->nextPrimaryAttack() <= memory->globalVars->serverTime() && !clamped && ((config->aimbot[weaponIndex].shotdelay > 0 && (lastTime + config->aimbot[weaponIndex].shotdelay / 1000.f) <= now) || !(config->aimbot[weaponIndex].shotdelay > 0)))

**Comment by aljawary** [comment]
make an shotdelay for autoshot
in aimbot.cpp

>             if (config->aimbot[weaponIndex].autoShot && activeWeapon->nextPrimaryAttack() <= memory->globalVars->serverTime() && !clamped && ((config->aimbot[weaponIndex].shotdelay > 0 && (lastTime + config->aimbot[weaponIndex].shotdelay / 1000.f) <= now) || !(config->aimbot[weaponIndex].shotdelay > 0)))
above void aimbot::run

> static auto lastTime = 0.0f;

in config.cpp

>         if (aimbotJson.isMember("Shot Delay")) aimbotConfig.shotdelay = aimbotJson["Shot Delay"].asInt();

>         aimbotJson["Shot Delay"] = aimbotConfig.shotdelay;
config.h

> int shotdelay {0};
gui.cpp

>     ImGui::InputInt("Shot Delay", &config->aimbot[currentWeapon].shotdelay);

**Comment by dapaster** [comment]
> 
> 
> **an ugly code shotdelay for autoshot**
> 
> in aimbot.cpp
> 
> > ```
> >         if (config->aimbot[weaponIndex].autoShot && activeWeapon->nextPrimaryAttack() <= memory->globalVars->serverTime() && !clamped && ((config->aimbot[weaponIndex].shotdelay > 0 && (lastTime + config->aimbot[weaponIndex].shotdelay / 1000.f) <= now) || !(config->aimbot[weaponIndex].shotdelay > 0)))
> > ```
> 
> above void aimbot::run
> 
> > static auto lastTime = 0.0f;
> 
> in config.cpp
> 
> > ```
> >     if (aimbotJson.isMember("Shot Delay")) aimbotConfig.shotdelay = aimbotJson["Shot Delay"].asInt();
> >     aimbotJson["Shot Delay"] = aimbotConfig.shotdelay;
> > ```
> 
> config.h
> 
> > int shotdelay {0};
> 
> gui.cpp
> 
> > ```
> > ImGui::InputInt("Shot Delay", &config->aimbot[currentWeapon].shotdelay);
> > ```

    const auto now = memory->globalVars->realtime;
