### ISSUE TITLE
What does Far Z do?

### ISSUE THREAD

**Issue by notgoodusename** [danielkrupinski/Osiris#2013]
as title says

**Comment by rosesware** [comment]
If I'm not mistaken, it's the render distance in battle royale, but I'm not sure how it works.

**Comment by Frouk3** [comment]
Far z works how render distance but you need fog to set far z im trying at my server its working with sv_cheats 1

**Comment by danielkrupinski** [comment]
It extends rendering distance, it's noticable when you're playing Danger Zone with disabled fog.
