### ISSUE TITLE
Unhook make my Game crash

### ISSUE THREAD

**Issue by aljawary** [danielkrupinski/Osiris#2014]
When i try to unhook cheat from lobby it makes my cheat crash, how to fix? Im using osiris with custom features

**Comment by 0xE232FE** [comment]
Give Stacktrace please.

**Comment by 0xE232FE** [comment]
Please provide stacktrace!

**Comment by techzin** [comment]
> Quando tento desengatar fraudes do lobby, ocorre uma falha na fraude, como consertar? Estou usando o osiris com recursos personalizados

Reload the original source.
