### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by koon666** [danielkrupinski/Osiris#2015]
how do i remove for when you inject osiris, the menu does not appear, you need to press Insert first to open the menu

**Comment by braken1** [comment]
wtf this is how it works

**Comment by dapaster** [comment]
https://github.com/danielkrupinski/Osiris/commit/aa1287821128839cc16e732243b10a56b5daf4b5

**Comment by newcommerdontblame** [comment]
Imagine being that lazy to press one key

**Comment by koon666** [comment]
> Make GUI opened by default -[aa12878](https://github.com/danielkrupinski/Osiris/commit/aa1287821128839cc16e732243b10a56b5daf4b5)

thank u
