### ISSUE TITLE
how to change text color on console 

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#2016]
how to change the color text on console ?

example:

echo _danielkrupinski_  is voting F1 (Green)

echo _notgoodusename_ is voting F2 (Red)

**Comment by danielkrupinski** [comment]
https://github.com/danielkrupinski/Osiris/blob/ef974a7cfda29aff15f841a06dc9de91866647a2/Osiris/Memory.h#L63

**Comment by dapaster** [comment]
Thank you!
