### ISSUE TITLE
Сonfigs do not load correctly

### ISSUE THREAD

**Issue by Frouk3** [danielkrupinski/Osiris#2018]
So when i change between configs ESP,VISUALS and MISC sometimes ANTI-AIM didn`t load correctly
At first i load legit cfg without Esp after i load rage cfg he got hes esp,visuals and misc so when i back to legit cfg i mean load cfg legit got rages cfg esp misc visuals so fix it please

**Comment by sserve-kr** [comment]
press reset config -> Whole before load other cfg.
It clears whole your cfg

**Comment by danielkrupinski** [comment]
I brought back the old config load behaviour.
