### ISSUE TITLE
Opossite hand knife

### ISSUE THREAD

**Issue by braken1** [danielkrupinski/Osiris#2019]
i know you can bind it but i use q as weapon switch so the feature would work better

i have this code but its not for osiris:

if (knife->IsOut())
{
    g_Panel->ClientCumand("cl_righthand 0");
}
else
{
    g_Engine->ClientCmdPrompt("cl_lefthand 1");
}

**Comment by RyDeem** [comment]
check out #2020 its what you are looking for but better. ;D

**Comment by danielkrupinski** [comment]
Added
