### ISSUE TITLE
(REQUEST) Add no recoil and weapon nospread

### ISSUE THREAD

**Issue by Frouk3** [danielkrupinski/Osiris#2023]
As title says

**Comment by braken1** [comment]
nospread fixed

**Comment by aljawary** [comment]
Its patched

**Comment by RyDeem** [comment]
afaik thease functions only work in HVH servers, not valve matchmaking

**Comment by DoomFishWasTaken** [comment]
_nospread fixing was patched in 2018 and it worked in only in dm/casual_

**Comment by Frouk3** [comment]
> _nospread fixing was patched in 2018 and it worked in only in dm/casual_

uh okay
