### ISSUE TITLE
help me pls everyone!

### ISSUE THREAD

**Issue by koon666** [danielkrupinski/Osiris#2024]
can someone tell me the number or the source code of verdana?

**Comment by RyDeem** [comment]
would in gui.cpp line 47

`fonts.verdana = io.Fonts->AddFontFromFileTTF((path / "verdana.ttf").string().c_str(), 15.0f, &cfg, Helpers::getFontGlyphRanges());`

work?

**Comment by koon666** [comment]
> would in gui.cpp line 47
> 
> `fonts.verdana = io.Fonts->AddFontFromFileTTF((path / "verdana.ttf").string().c_str(), 15.0f, &cfg, Helpers::getFontGlyphRanges());`
> 
> work?

I want to put the font of verdana in my velocity code, how can I put this code in velocity?

**Comment by koon666** [comment]
and also have codes for the fonts
