### ISSUE TITLE
(REQUEST) spectator list

### ISSUE THREAD

**Issue by koon666** [danielkrupinski/Osiris#2026]
does anyone have a code for me to put "Spectators" on top of osiris spectator list?

Example: https://prnt.sc/tugt9w

**Comment by aljawary** [comment]
its already on osiris

**Comment by koon666** [comment]
> its already on osiris

but I want to put the text "Spectators" on top of the normal spectator list

**Comment by rosesware** [comment]
Just use the `"Watermark"` code as base.

**Comment by koon666** [comment]
> Just use the `"Watermark"` code as base.

thank u
