### ISSUE TITLE
[REQUEST] Aim at Backtrack?

### ISSUE THREAD

**Issue by aljawary** [danielkrupinski/Osiris#2030]
As a tittle says how to make aimbot aim at backtrack? Is it possible for osiris?

**Comment by dapaster** [comment]
+1

**Comment by senisditron** [comment]
+2

**Comment by dayz2000** [comment]
+3

**Comment by NekoRem** [comment]
first you would get the ticks like how chams do and make the aimbot target the backtrack hitboxes
