### ISSUE TITLE
CEngineClient::SetViewAngles:  rejecting invalid value [-nan(ind) 0.000000 0.000000]

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#2031]
what is this error mean when it appear on console?
plus i can't move my crosshair when this error appear.

**Comment by notgoodusename** [comment]
are you calling SetViewAngles?
The error is from SetViewAngles you are passing through a invalid value

**Comment by Xoom7573** [comment]
@notgoodusename  , Do you have a discord?

**Comment by notgoodusename** [comment]
yes, i do
send yours and i will add you

**Comment by dapaster** [comment]
> are you calling SetViewAngles?
> The error is from SetViewAngles you are passing through a invalid value

Yeah i'm adding auto stop on aimbot

**Comment by notgoodusename** [comment]
> Yeah i'm adding auto stop on aimbot 


normalize and clamp the angles

**Comment by Xoom7573** [comment]
@notgoodusename  my discord -> Xoom#7573

**Comment by notgoodusename** [comment]
> @notgoodusename  my discord -> Xoom#7573

done

**Comment by dapaster** [comment]
Problem Solved! Thanks

**Comment by dapaster** [comment]
@notgoodusename can you add me too. 

`dahacker#5820`

**Comment by dapaster** [comment]
@notgoodusename can you add me too

`dacheater#5820`
