### ISSUE TITLE
What is the weapon model id or index?

### ISSUE THREAD

**Issue by sheavyq** [danielkrupinski/Osiris#2033]
I try to change my weapon model, I precached my model in Visuals.cpp at Visuals::playerModel():
`modelprecache->addString(false, "models/weapons/awp/freedom.mdl");`

and change weapon model(at Visuals::playerModel())
```
const auto cwid = interfaces->entityList->getEntityFromHandle(localPlayer->getActiveWeapon()->handle());
cwid->setModelIndex(interfaces->modelInfo->getModelIndex("models/weapons/awp/freedom.mdl"));
```

this didnt change anything, can you help me what is wrong with this code? :d

**Comment by danielkrupinski** [comment]
Didn't it change the weapon model you see in thirdperson view?

**Comment by sheavyq** [comment]
Nope, its isn't change anything
![model](https://user-images.githubusercontent.com/68903936/89579739-951fa700-d834-11ea-9bf3-f9dfd9b4504e.png)
