### ISSUE TITLE
Move to a Vector point

### ISSUE THREAD

**Issue by sheavyq** [danielkrupinski/Osiris#2036]
Hi, i want to create a movement recorder, everything works, fine, but i dont know how to move to the record start point
I created a startVec, when movement record start, startVec set to current position, and when i want to playback, i need to set viewangles into the startVec point. (and walk, and when dist < 1 stop, and start playback)
I tried this way, but its didn't look into the start point:

```
auto dist = localPlayer->getAbsOrigin().distTo(startVec);
if (GetAsyncKeyState(0x56))
{
	if (dist < 1)
		playback.StartPlayback(recorder.GetActiveRecording());
	else
	{
		Vector finalVec;
		VectorSubtract(startVec, localPlayer->getAbsOrigin(), finalVec);
		VectorAngles(finalVec, cmd->viewangles);
		cmd->forwardmove = dist;
	}
}
```

VectorSubtract:

```
void VectorSubtract(Vector va, Vector vb, Vector out)
{
	out.x = va.x - vb.x;
	out.y = va.y - vb.y;
	out.z = va.z - vb.z;
}
```

VectorAngles:

```
void VectorAngles(Vector forward, Vector angles)
{
	float	tmp, yaw, pitch;

	if (forward.y == 0 && forward.x == 0)
	{
		yaw = 0;
		if (forward.z > 0)
			pitch = 270;
		else
			pitch = 90;
	}
	else
	{
		yaw = (atan2(forward.y, forward.x) * 180 / M_PI);
		if (yaw < 0)
			yaw += 360;

		tmp = sqrt(forward.x * forward.x + forward.y * forward.y);
		pitch = (atan2(-forward.z, tmp) * 180 / M_PI);
		if (pitch < 0)
			pitch += 360;
	}

	angles.x = pitch;
	angles.y = yaw;
	angles.z = 0;
}
```

Can you help me how to make this working? :d

**Comment by notgoodusename** [comment]
save vieawangles when starting, and then set them

**Comment by sheavyq** [comment]
> save vieawangles when starting, and then set them

I want to move into the point, so i need to set my viewangles into the point, and start forward move.
Like this, in 0:07 https://streamable.com/ald28

**Comment by notgoodusename** [comment]
Aimbot::calculateRelativeAngle
is what you are looking for

**Comment by sheavyq** [comment]
> Aimbot::calculateRelativeAngle
> is what you are looking for

okay i try it

**Comment by sheavyq** [comment]
> Aimbot::calculateRelativeAngle
> is what you are looking for

Working, thanks a lot :D
