### ISSUE TITLE
We need a head-level indicator

### ISSUE THREAD

**Issue by SunzBody** [danielkrupinski/Osiris#2037]
I know there have been several requests about this feature but it would be well worth its place in one of the open-source CS:GO cheats that contains a lot of legit features.

Some will say that this feature is not necessary and that "Head Dot ESP" does the trick, but that's not the case, because you can accidentally look through a wall...

No this feature is certainly not vital but would be super useful and I think it wouldn't take too much time to develop.

I know there's going to be some debate about the usefulness of this feature, but like the sniper crosshair  it's useful but not essential once you understand where to place the crosshair. I don't think I'm the only one who wants this feature, it would really be a plus.
Even a pull request from any of you is welcome.
Let me know what you think below my issue. (Please Daniel make our dream come true)
Have a good day !

**Comment by infinity1211** [comment]
i dont understand, what do u mean by head-level indicator?

**Comment by SunzBody** [comment]
Ah yes, sorry indeed :p
https://prnt.sc/rww0x0
https://prnt.sc/rww1f6

**Comment by danielkrupinski** [comment]
So it

**Comment by rosesware** [comment]
https://github.com/danielkrupinski/Osiris/issues/1407

**Comment by infinity1211** [comment]
you can do this with the help of head box esp
![Untitled](https://user-images.githubusercontent.com/65710399/89881487-35821c80-dbe3-11ea-8b37-56cd07ef6664.png)
![esp](https://user-images.githubusercontent.com/65710399/89881494-36b34980-dbe3-11ea-93b7-f9879082e432.png)
