### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by jainyash8888** [danielkrupinski/Osiris#2040]
hello guys 
i have been trying to use osiris hack but not able to complete it
can anyone give me a deep walkthrough or guide how to do it
i have downloaded source code and got dll file 
but after injecting it dosent work
when i open my game after injecting i cant access hacks or menu

**Comment by sserve-kr** [comment]
test [my dll](https://github.com/sserve-kr/MyOsiris).
if it works on your computer, the problem is on your dll file.

**Comment by avidretard** [comment]
put the dll in a folder inside your windows folder and then use a manual map injector to inject it

**Comment by tirziz** [comment]
Check your injector, maybe your injection is blocked by trust mode.

**Comment by jainyash8888** [comment]
thanks alot guys 
avidretard your suggestion worked 
thanks to everyone
