### ISSUE TITLE
Recoil Crosshair inaccurate due to No aim punch

### ISSUE THREAD

**Issue by infinity1211** [danielkrupinski/Osiris#2041]
![aim punch](https://user-images.githubusercontent.com/65710399/89726448-59edc580-da38-11ea-8102-bac7ea6fce6b.png)
![no aim punch](https://user-images.githubusercontent.com/65710399/89726449-5a865c00-da38-11ea-9e36-b84d553f75e9.png)

Thanks to @tirziz for pointing it out

**Comment by tirziz** [comment]
I think if we make a check for visual:noaimpunch and then double the aimpunch{vector} should fix it.
