### ISSUE TITLE
Nade Helper

### ISSUE THREAD

**Issue by SunzBody** [danielkrupinski/Osiris#2042]
https://www.youtube.com/watch?v=px-3Skl6GHk
https://www.youtube.com/watch?v=JVGJKC9TMIY&list=PLlefgn9QXzvg2fyuQ3lCPdcbVYZmSESob&index=19
If someone could develop one of its features (or both) it could be really interesting. 

Here's the source of Sensum if it helps (the cheat in the video): https://github.com/martinjanas/Sensum

**Comment by tirziz** [comment]
Check project riptide remastered source, I think it has this feature. This make cheat unstable and hard to maintain

**Comment by newcommerdontblame** [comment]
> https://www.youtube.com/watch?v=JVGJKC9TMIY&list=PLlefgn9QXzvg2fyuQ3lCPdcbVYZmSESob&index=19

tf is this mess
