### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jainyash8888** [danielkrupinski/Osiris#2043]
i injected dll and its working 
but when i enabled the aimbot its not working
can anyone tell me hoe to use them 
i can open the menu but is there any settings we need to do

**Comment by SwagsRGB** [comment]
Increase FOV to something like 5 6 and smoothness to 1 or 2. Hop into AimBotz workshop map and check if working

**Comment by jainyash8888** [comment]
> 
> 
> Increase FOV to something like 5 6 and smoothness to 1 or 2. Hop into AimBotz workshop map and check if working

thanks alot
