### ISSUE TITLE
How to render a Circle in a Vector point?

### ISSUE THREAD

**Issue by sheavyq** [danielkrupinski/Osiris#2044]
Hi, how can i render a Circle in a Vector point/position?

**Comment by notgoodusename** [comment]
use
worldToScreen()
and surface or imgui

**Comment by sheavyq** [comment]
> use
> worldToScreen()
> and surface or imgui

I tried this, but this isnt rendering anything

`ImVec2 pos;

worldToScreen(startVec, pos);
interfaces->surface->drawCircle(pos.x, pos.y, 10, 50);`

startVec is the movement recorder start point

**Comment by notgoodusename** [comment]
you have to do
if(worldToScreen())
also remember to setDrawColor

**Comment by sheavyq** [comment]
> you have to do
> if(worldToScreen())
> also remember to setDrawColor

I tried, but didnt rendering anything :/

	if (ImVec2 pos; isRecordingActive && worldToScreen(startVec, pos))
	{
		interfaces->surface->setDrawColor(0.f, 1.f, 1.f, 255);
		interfaces->surface->drawCircle(pos.x, pos.y, 2, 5);
		memory->debugMsg("rendered\n");
	}

![render](https://user-images.githubusercontent.com/68903936/89738964-0d78a900-da7d-11ea-8fdf-4180c8a68d59.png)

**Comment by sheavyq** [comment]
I forgot to render the void, now rendering, but in my screen, not in the world:

https://streamable.com/bk9gny

**Comment by notgoodusename** [comment]
startVec must be in absolute coordinates 
```
ImVec2 pos;
if(worldToScreen(startVec, pos))
{
        interfaces->surface->setDrawColor(255, 255, 255);
        interfaces->surface->drawCircle(pos.x, pos.y, 0, 10);
}
```

**Comment by sheavyq** [comment]
> startVec must be in absolute coordinates
> 
> ```
> ImVec2 pos;
> if(worldToScreen(startVec, pos))
> {
>         interfaces->surface->setDrawColor(255, 255, 255);
>         interfaces->surface->drawCircle(pos.x, pos.y, 0, 10);
> }
> ```

Same issue :/

Code:

	if (worldToScreen(startVec, pos)/* && worldToScreen(localPlayer->getAbsOrigin(), pos2)*/)
		{
			interfaces->surface->setDrawColor(255, 255, 255);
			interfaces->surface->drawCircle(pos.x, pos.y, 4, 10);

			//interfaces->surface->drawLine(pos2.x, pos2.y, pos.x, pos.y);

			interfaces->surface->setTextPosition(pos.x, pos.y);
			interfaces->surface->setTextFont(Surface::font);
			interfaces->surface->setTextColor(255, 255, 255);
			interfaces->surface->printText(L"test");
		}

Video: https://streamable.com/25bjb7

**Comment by notgoodusename** [comment]
what values do you set to startVec

**Comment by sheavyq** [comment]
> what values do you set to startVec

	void StartRecording()
	{
		startVec = localPlayer->getAbsOrigin();
		this->is_recording_active = true;
	}

**Comment by notgoodusename** [comment]
when do u set it

**Comment by sheavyq** [comment]
> when do u set it

	void Misc::HookRecorder(UserCmd* cmd) noexcept
	{
		[...]
		if (GetAsyncKeyState(0x45)) //E Key
		{
			if (!isRecordingActive)
				recorder.StartRecording();
		}
	}



	void StartRecording()
	{
		startVec = localPlayer->getAbsOrigin();
		newStartVec = true;
		drawTimer_save = memory->globalVars->serverTime();
		this->is_recording_active = true;
	}

**Comment by notgoodusename** [comment]
try origin instead of getAbsOrigin

**Comment by sheavyq** [comment]
> try origin instead of getAbsOrigin

same :/

**Comment by sheavyq** [comment]
> try origin instead of getAbsOrigin

I think, the issue isnt with the startVec, because, if i start my playback, this automatically going to the good Vector position

Video: https://streamable.com/13t259

**Comment by sheavyq** [comment]
@danielkrupinski Can you help? :d

**Comment by sheavyq** [comment]
@notgoodusename 

I Tried to render my recorded moveposition, but its render very 'glitchly', but i use the same code, what u writed :/

https://streamable.com/imlwj8

**Comment by notgoodusename** [comment]
are u calling it in paintTraverse?

**Comment by sheavyq** [comment]
> are u calling it in paintTraverse?

Yes
