### ISSUE TITLE
help

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#2047]
https://streamable.com/prryus

    void Visuals::hitMarkerDamageIndicator(GameEvent* event) noexcept
    {
        if (!config->visuals.hitMarkerDamageIndicator) return;

        static std::vector<HitMarkerInfo> hitMarkerInfo;

        if (event && interfaces->engine->getPlayerForUserID(event->getInt("attacker")) == localPlayer)
        {
            hitMarkerInfo.push_back({
            memory->globalVars->realtime + config->visuals.hitMarkerTime, event->getInt("dmg_health")
            });
            return;
        }

        if (hitMarkerInfo.empty() || event) return;

        for (size_t i = 0; i < hitMarkerInfo.size(); i++)
        {
            const auto diff = hitMarkerInfo.at(i).hitMarkerExpTime - memory->globalVars->realtime;
            auto entity = interfaces->entityList->getEntity(i);

            if (diff < 0.f)
            {
                hitMarkerInfo.erase(hitMarkerInfo.begin() + i);
                continue;
            }

            Vector head;
            if (!worldToScreen(entity->getBonePosition(8), head))
            return;

            renderPositionedText(5, (std::to_wstring(hitMarkerInfo.at(i).hitMarkerDmg)).c_str(), { head.x, head.y });
        }
    }

i want it to be like this

https://www.youtube.com/watch?v=Rpsnnp3qeeI

**Comment by notgoodusename** [comment]
what does renderPositionedText do

**Comment by dapaster** [comment]
> 
> 
> what does renderPositionedText do

    static void renderPositionedText(unsigned font, const wchar_t* text, std::pair<float, float&> position) noexcept
    {
        interfaces->surface->setTextFont(font);
        interfaces->surface->setTextPosition(position.first, position.second);
        position.second += interfaces->surface->getTextSize(font, text).second;
        interfaces->surface->printText(text);
    }
