### ISSUE TITLE
[REQUEST] RESOLVER

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#2049]
Anyone has done simple legit or rage resolver for osiris? its very needed thing for cheat i think can someone share with us

**Comment by mkot2** [comment]
> Anyone has done simple legit or rage resolver for osiris? its very needed thing for cheat i think can someone share with us

paste one from uc

**Comment by newcommerdontblame** [comment]
> paste one from uc
 
All posts from 2017 and half of resolver posts are just meme

**Comment by igre3zy** [comment]
honestly all @danielkrupinski needs to do is update the legit aa and add a resolver then osiris will actually be a multihack

**Comment by afulsamet** [comment]
That simple desync resolver - 5 month ago
[Sensum/resolver.cpp](https://github.com/martinjanas/Sensum/blob/master/src/features/resolver.cpp)

**Comment by notgoodusename** [comment]
> That simple desync resolver - 5 month ago
> [Sensum/resolver.cpp](https://github.com/martinjanas/Sensum/blob/master/src/features/resolver.cpp)

that is a meme

**Comment by newcommerdontblame** [comment]
@notgoodusename i think only you can make this thing in this forum bro xd

**Comment by mkot2** [comment]
> > That simple desync resolver - 5 month ago
> > [Sensum/resolver.cpp](https://github.com/martinjanas/Sensum/blob/master/src/features/resolver.cpp)
> 
> that is a meme

well what do you expect
