### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by ViniciusSchifferGuedes** [danielkrupinski/Osiris#205]
Daniel my lord kk, I want ask about a timing c4? it inst so useful but kind fun kk sorry for bad english and thanks for all bro !

**Comment by cojo1989** [comment]
Uhh yea, it would be great a timing for c4 ❤️❤️❤️. Up for it :)

**Comment by toprak1224** [comment]
yess plss add c4 timer

**Comment by h4x0reL** [comment]
+

**Comment by h4x0reL** [comment]
+1

**Comment by effex1337** [comment]
+1

**Comment by Shaxzy** [comment]
+1

**Comment by Flaam** [comment]
+1
