### ISSUE TITLE
UserCmd to string?

### ISSUE THREAD

**Issue by hoklaaa** [danielkrupinski/Osiris#2051]
Hey, how can i convert cmd's into string? I want to save my cmd's into a txt or ini file, and load back etc..., but i cant covert it into string, can you help me?

**Comment by enescglyn** [comment]
cmd?

**Comment by hoklaaa** [comment]
> cmd?

Yes.
i want to create a simple movement playbacker and save it into a file to load back anytime on the map

**Comment by enescglyn** [comment]
you mean command by cmd? then where is the command bar so i can execute commands

**Comment by hoklaaa** [comment]
> you mean command by cmd? then where is the command bar so i can execute commands

i pasted a simple movement playbacker https://aixxe.net/2017/04/source-input-recorder , and i want to save it into a file to load back anytime on the map, but i dont know how to save the cmd's (like button press and viewangles and etc..)

**Comment by notgoodusename** [comment]
you dont need to a make a cmd to a string, rather you can save the values in x string
ex
Backtrack
Time Limit : 200
The cheat will read Time Limit and overwrite that value

**Comment by barbadully** [comment]
https://streamable.com/u2mnm
this shit looks dope

**Comment by hoklaaa** [comment]
> you dont need to a make a cmd to a string, rather you can save the values in x string
> ex
> Backtrack
> Time Limit : 200
> The cheat will read Time Limit and overwrite that value

And how can i save my movement into x string?
I tried this, but i dont know how can i save that because if i try to put it into WritePrivateProfileString, i get error.

Code:
```
namespace MovementRB {
	struct Record {
		Vector origin;
		float simulationTime;
		matrix3x4 matrix[256];
	};
	extern std::deque<Record> records[1000];
}

std::deque<MovementRB::Record> MovementRB::records[1000];

MovementRB::Record record{ };
```

Save:

	for (int i = 0; i < recording.size(); i++)
		{
			std::string cframe = "frame";
			cframe = cframe + std::to_string(i);
			//std::string cvector = recording.at(i);
			WritePrivateProfileString("Movement", cframe.c_str(), record, file.c_str());
		}

Movement:

	auto recordss = &MovementRB::records[recording.size()];
			recordss[current_recording_frame].push_front(record);

**Comment by notgoodusename** [comment]
look at config.cpp

**Comment by newcommerdontblame** [comment]
When u done make pr please

**Comment by hoklaaa** [comment]
> When u done make pr please

I think i can't make that :/

**Comment by sheavyq** [comment]
> > When u done make pr please
> 
> I didnt know how to make it in the easiest way, so i think i cant make that, i make a pr, and if anyone can make save file i add it to update

Hey, i have same problem, idk how to save movement into a file, and i have some problems with the visualize movement positions. Currently i make a pr about that
