### ISSUE TITLE
Legit AA problems/suggestions (for daniel)

### ISSUE THREAD

**Issue by igre3zy** [danielkrupinski/Osiris#2055]
Personally I think the legit aa is pretty shit on Osiris. The cheat itself is amazing for legit and is slowly getting better for rage. With all these other settings being added/updated, i havent seen legit aa updated since it was added. A couple issues i have with the legit aa is; when walking, you will move slightly in the direction of your yaw (yes i know there is a fix movement option, but it makes rage inaccurate. Secondly, a bind or option to switch yaw should be added. If the movement is fixed, and you are able to switch your YAW, the legit aa would be perfect. Please take this into consideration @danielkrupinski <3

**Comment by 3Ld4D** [comment]
i have made proper legit aa with lby breaker but sometimes it flicks with fake instead of real,so when i fix it i will make a pull.

**Comment by newcommerdontblame** [comment]
Take aa from here #1546
Then update ur animfix from here #1819

**Comment by igre3zy** [comment]
> Take aa from here #1546
> Then update ur animfix from here #1819

anything more updated?
