### ISSUE TITLE
Triggerbot doesn't allow for user to fire with own click

### ISSUE THREAD

**Issue by TheFantasticLoki** [danielkrupinski/Osiris#2056]
When on hold key only afaik

**Comment by hyperxpro** [comment]
If you want to click, why you need a trigger bot? Dafaq?

**Comment by TheFantasticLoki** [comment]
It's good to have both aimbot and trigger bot setup for pistols to simulate a well timed flickshot but if it misses or doesn't kill it won't fire again till you release the hold button
