### ISSUE TITLE
Angry hackers best config

### ISSUE THREAD

**Issue by A1gaoshanlaiyige** [danielkrupinski/Osiris#2057]
hack vs hack

**Comment by aljawary** [comment]
i dont get it what do u mean?

**Comment by notgoodusename** [comment]
he means rage cfg

**Comment by aljawary** [comment]
u can try this 
https://anonfiles.com/J901p1Mfo0/rage_as_fuck
old osiris cfg

**Comment by newcommerdontblame** [comment]
Title makes me laugh hard

**Comment by EzekielCloud** [comment]
Air out of nose

**Comment by A1gaoshanlaiyige** [comment]
https://anonfiles.com/91cdOfM5o3/HVH
What does he need to improve?
