### ISSUE TITLE
[REQUEST] drawGradientLine

### ISSUE THREAD

**Issue by playday3008** [danielkrupinski/Osiris#2059]
Same as drawLine in Surface.h, but with gradient
If you don't want to do this, just close this issue

**Comment by danielkrupinski** [comment]
You can achieve this with imgui: https://github.com/danielkrupinski/Osiris/blob/d29cd90f0f461df45aa37f20f8b4acc9a5780efc/Osiris/imgui/imgui_widgets.cpp#L4870-L4872
