### ISSUE TITLE
Night Mode!

### ISSUE THREAD

**Issue by TrackyBunny** [danielkrupinski/Osiris#206]
Yo! Can you please add nightmode?

Late at night when I'm playing my eyes are literally burning ang I'm not enjoying a single second of a cs match.

Could you work on it? Thanks.

**Comment by effex1337** [comment]
There's a brightness slider in visuals
Use that it works like night mode

**Comment by TrackyBunny** [comment]
> There's a brightness slider in visuals
> Use that it works like night mode

Well yes but that messes up with the actual models and lowers the brightnes of the whole game without the HUD itself.

**Comment by danielkrupinski** [comment]
You want to lower HUD brightness?

**Comment by NexSqaud** [comment]
@danielkrupinski Nightmode make world darker.

**Comment by danielkrupinski** [comment]
@NexSqaud Currently it does.

**Comment by NexSqaud** [comment]
@danielkrupinski No. Now world color cant make world darker

**Comment by TrackyBunny** [comment]
@danielkrupinski no. Go ahead and try changing and lowering the brightness of the game. It lowers the brightness of the map AND THE MODELS of the game, but it doesn't mess with the HUD. What I'm saying is you could make a proper nightmode that doesn't mess with player models or other bs, but messes with just the map.

**Comment by Gino** [comment]
Is it possible to fix this? The brightness slider indeed also lowers the model brightness (and also your own viewmodel). Is it possible to add like a checkbox that says ‘Include models’ or something? @danielkrupinski I tried it too but can’t fix it since it doesn’t use the normal MaterialSystem stuff.
