### ISSUE TITLE
Get Player Looking Position?

### ISSUE THREAD

**Issue by sheavyq** [danielkrupinski/Osiris#2060]
Hey, i trying to create a simple nade helper, when i record one, I need to get my current position, and looking position (not getEyePosition()) to visualize where I need to look to drop perfect smokes and etc...

How can I get looking position ? (+10meter I think)

**Comment by danielkrupinski** [comment]
```cpp
localPlayer->getEyePosition() + Vector::fromAngle(interfaces->engine->getViewAngles()) * howManyUnitsForward
```

**Comment by sheavyq** [comment]
> ```c++
> localPlayer->getEyePosition() + Vector::fromAngle(interfaces->engine->getViewAngles()) * howManyUnitsForward
> ```

Thanks
