### ISSUE TITLE
add obs bypass?

### ISSUE THREAD

**Issue by debruh** [danielkrupinski/Osiris#2062]
will obs bypass be added in the future? If not, does anyone know how to easily add this feature?

**Comment by techzin** [comment]
Already have :) is the actual ESP. :)

**Comment by debruh** [comment]
> Already have :) is the actual ESP. :)

but I mean for all features, like so nothing shows on obs (fov, recoil cross hair, chams, backtrack) I would still want skins to show tho.

**Comment by Cyk-Fad** [comment]
that sound so funny

**Comment by rosesware** [comment]
> > Already have :) is the actual ESP. :)
> 
> but I mean for all features, like so nothing shows on obs (fov, recoil cross hair, chams, backtrack) I would still want skins to show tho.

Some features don't get the "bypass", "fov" is one of them.

**Comment by tirziz** [comment]
Anything that render using game engine can not be stream proof. You just need to deal with it.

**Comment by bruhmoment21** [comment]
> that sound so funny

if someone knows at least the most basic thing about programming these issues will hurt their eyes no cap

**Comment by DoomFishWasTaken** [comment]
> Anything that render using game engine can not be stream proof. You just need to deal with it.

actually it can be done its just _difficult_ 
![image](https://user-images.githubusercontent.com/30623715/90636695-aa80d200-e233-11ea-92af-bdea3f579c26.png)
[if you want it, you can make it](https://www.unknowncheats.me/forum/counterstrike-global-offensive/252754-chams-stream-proof-bypass-streaming-obs.html)

**Comment by Re0xF** [comment]
so rendering the game 2 times?
