### ISSUE TITLE
(Request) edge bug 

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#2063]
Anyone done this or can u implement this to osiris 
https://www.unknowncheats.me/forum/counterstrike-1-5-1-6-and-mods/177297-src-ebug-hns.html

**Comment by newcommerdontblame** [comment]
I dont know how it works but kinda looks like ducking in the edges and blocking fall damage

**Comment by newcommerdontblame** [comment]
Pretty usefull i guess

**Comment by braken1** [comment]
if somebody could do that that would be really cool i want this feature too

**Comment by infinity1211** [comment]
#1829

**Comment by koon666** [comment]
you just need to call cmd->IN_DUCK for the localPlayer flags

**Comment by aljawary** [comment]
> #1829

cant u read the tittle?

**Comment by newcommerdontblame** [comment]
> you just need to call cmd->IN_DUCK for the localPlayer flags

i tried but it didnt work perfectly

**Comment by koon666** [comment]
> > you just need to call cmd->IN_DUCK for the localPlayer flags
> 
> i tried something but it didnt work perfectly
> 
> if (const auto mt = localPlayer->moveType(); mt == MoveType::LADDER || mt == MoveType::NOCLIP)
> return;
> 
> ```
> if ((EnginePrediction::getFlags() & 1) && !(localPlayer->flags() & 1))
>     cmd->buttons |= UserCmd::IN_DUCK;
> ```

if (config->misc.edgeBug && GetAsyncKeyState(config->misc.edgeBugKey) && localPlayer->flags() & 1)
        cmd->buttons |= UserCmd::IN_DUCK;

I made this code in 40 seconds and it works very well

**Comment by newcommerdontblame** [comment]
> > > you just need to call cmd->IN_DUCK for the localPlayer flags
> > 
> > 
> > i tried something but it didnt work perfectly
> > if (const auto mt = localPlayer->moveType(); mt == MoveType::LADDER || mt == MoveType::NOCLIP)
> > return;
> > ```
> > if ((EnginePrediction::getFlags() & 1) && !(localPlayer->flags() & 1))
> >     cmd->buttons |= UserCmd::IN_DUCK;
> > ```
> 
> if (config->misc.edgeBug && GetAsyncKeyState(config->misc.edgeBugKey) && localPlayer->flags() & 1)
> cmd->buttons |= UserCmd::IN_DUCK;
> 
> I made this code in 40 seconds and it works very well

its literally normal duck command its isnt edgebug

**Comment by newcommerdontblame** [comment]
Hey @danielkrupinski its very usefull and pretty cool feature

**Comment by koon666** [comment]
> > > > you just need to call cmd->IN_DUCK for the localPlayer flags
> > > 
> > > 
> > > i tried something but it didnt work perfectly
> > > if (const auto mt = localPlayer->moveType(); mt == MoveType::LADDER || mt == MoveType::NOCLIP)
> > > return;
> > > ```
> > > if ((EnginePrediction::getFlags() & 1) && !(localPlayer->flags() & 1))
> > >     cmd->buttons |= UserCmd::IN_DUCK;
> > > ```
> > 
> > 
> > if (config->misc.edgeBug && GetAsyncKeyState(config->misc.edgeBugKey) && localPlayer->flags() & 1)
> > cmd->buttons |= UserCmd::IN_DUCK;
> > I made this code in 40 seconds and it works very well
> 
> its literally normal duck command its isnt edgebug



> > > > you just need to call cmd->IN_DUCK for the localPlayer flags
> > > 
> > > 
> > > i tried something but it didnt work perfectly
> > > if (const auto mt = localPlayer->moveType(); mt == MoveType::LADDER || mt == MoveType::NOCLIP)
> > > return;
> > > ```
> > > if ((EnginePrediction::getFlags() & 1) && !(localPlayer->flags() & 1))
> > >     cmd->buttons |= UserCmd::IN_DUCK;
> > > ```
> > 
> > 
> > if (config->misc.edgeBug && GetAsyncKeyState(config->misc.edgeBugKey) && localPlayer->flags() & 1)
> > cmd->buttons |= UserCmd::IN_DUCK;
> > I made this code in 40 seconds and it works very well
> 
> its literally normal duck command its isnt edgebug

all edge bug code and thus, a duck with localplayer-> flags 1, that means it will only work when you fall ON GROUND. this code works very well, test and you will see

**Comment by newcommerdontblame** [comment]
@koon666 can u record a vid please

**Comment by aljawary** [comment]
what does edgebug do? can u explain?

**Comment by twangsriprasoet** [comment]
> what does edgebug do? can u explain?

falling on a edge and absorb any damage, as if you surfed for a sec.

**Comment by twangsriprasoet** [comment]
btw it just an assist that only help you to perform an edgebug a little bit easier. not auto 100% edgebug. it's depend on how can you get very close to the edge.
