### ISSUE TITLE
How to load back this file?

### ISSUE THREAD

**Issue by sheavyq** [danielkrupinski/Osiris#2070]
Hey, currently I working on a movement recorder, and I want to save it to a file and load it back (#2054)
I created a file with 'WritePrivateProfileString', to save my start position, and my movement(UserCmd):

	for (int i = 0; i < recording.size() + 1; i++)
	{
		std::string cFrameString = "Frame" + std::to_string(i);
		WritePrivateProfileString("AllFrames", cFrameString.c_str(), (char*)& recording[i], visfile.c_str());
	}

the saving works, i saves my movement frame**, but** i dont know how to load it back into recording, I tried this, but didnt worked:
	char cRecvalues[32];

	for (int a = 0; a < 248; a++)
	{
		std::string cFrameString = "Frame" + std::to_string(a);

		GetPrivateProfileString("AllFrames", cFrameString.c_str(), "", cRecvalues, 50, visfile.c_str());
		recording.push_back({ (UserCmd*)cRecvalues });
	}

Can you help me how to load this file back, or how to save in another method to load back? :d

**Comment by aljawary** [comment]
@danielkrupinski

**Comment by bruhmoment21** [comment]
hey bro that function is deprecated. you could make use of this pseudo
```
// psuedocode
nlohmanm::json json; // put this in load and save func in the beginning

static TYPE var // this is ur var

for (..){
     var = ...
     json["frames"] = var
}

and for loading
for (..)
     var = json["frames"]
```

**Comment by sheavyq** [comment]
> hey bro that function is deprecated. you could make use of this pseudo
> 
> ```
> // psuedocode
> nlohmann::json json; // put this in load and save func in the beginning
> 
> static TYPE var // this is ur var
> 
> for (..){
>      var = ...
>      json["frames"][std::tostring(i)] = var
> }
> 
> and for loading
> for (..)
>      var = json["frames"][std::tostting(i)]
> ```

i tried that, but i dont know how to convert frames (movement) into string to save with json

**Comment by cmd51** [comment]
hi @sheavyq have you finished the config system for your movement recorder? I pasted your movement recorder code in my osiris source and now it needs a config system. If you finished could you send me? pllz

**Comment by sheavyq** [comment]
> hi @sheavyq have you finished the config system for your movement recorder? I pasted your movement recorder code in my osiris source and now it needs a config system. If you finished could you send me? pllz

If I remember correctly, I finished it, but because osiris is a free cheat, and I dont want to use it on any account, only just learning, I writed a movement recorder lua for another cheat which one is undetected as I know. You can view the finished version of it: https://youtu.be/mQwUqGvKzMc
If i found the osiris source, I will send it to here, but because I stopped cheating some months ago, I dont think it was saved.

**Comment by cmd51** [comment]
understanded, if you have saved I would love to have the code
