### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Deciy** [danielkrupinski/Osiris#2072]
Serious suggestions
-draw FOV (makes it easier to config)
-bunnyhop hitchance 
-bunnyhop min and max hits
-chams through walls (at least it doesn't work for me)
-fire timers and smoke timers (basically a bomb timer but you can see when a fire or smoke is done)
Just stuff that would be cool to have
-show keybind states
-flip knife hand
-head level indicator (https://prnt.sc/rww1f6)
----------------------
This is all I have for now

**Comment by mkot2** [comment]
1,2,3 and 7 are in pull requests already

**Comment by Deciy** [comment]
> 1,2,3 and 7 are in pull requests already

I didn't notice :/

**Comment by Deciy** [comment]
I also might add more stuff that is already in pull requests, I'm not going to go through and see what is already there (at least not right now)

**Comment by SwagsRGB** [comment]
> 
> 
> I also might add more stuff that is already in pull requests, I'm not going to go through and see what is already there (at least not right now)

Also: Footstep ESP. Although I doubt thesse will be added

**Comment by Deciy** [comment]
I’m finna close this but yes, footstep esp would be awesome too. Also a nade helper
