### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by YallAintthehomies** [danielkrupinski/Osiris#2073]
Wtf is pull requests, explain it to me. I see good stuff in there that I would like to add but don't know how to. If that is not how it works pls explain :(

**Comment by sserve-kr** [comment]
Pull requests feature allows people to add their own code to the copy of existing code and post the changes to apply to the original source code.

if you want to apply changes to your code, just go to Files changed tab, add green thing and delete red thing on your source code.

**Comment by YallAintthehomies** [comment]
I tried to do this but stuff came out with errors and I couldn't find correct files that needed change

**Comment by YallAintthehomies** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/68182147/90304735-7c844200-de6f-11ea-83c4-56fbd444bbf9.png)
File explorer is open to show that i located the file they told me too.
As you can see the code does not match

**Comment by aljawary** [comment]
> ![Screenshot (1)](https://user-images.githubusercontent.com/68182147/90304735-7c844200-de6f-11ea-83c4-56fbd444bbf9.png)
> File explorer is open to show that i located the file they told me too.
> As you can see the code does not match

change it to new way to load config

**Comment by infinity1211** [comment]
read(j, "Draw aimbot FOV", m.drawAimbotFov);

and

WRITE("Draw aimbot FOV", drawAimbotFov);
