### ISSUE TITLE
inventory changer?

### ISSUE THREAD

**Issue by debruh** [danielkrupinski/Osiris#2075]
Does anyone have the code for an inventory changer? I want to put it in Osiris because I personally prefer inventory changer to skin changer.

**Comment by bruhmoment21** [comment]
there is a thread on uc (inventory changer no protobuf) very in depth and detailed. do it on your own don t expect anyone to spoonfeed you. oh i forgot to say u need to modify ur skin changer for skins to be applied good luck with that G
