### ISSUE TITLE
suggestion Engine Prediction

### ISSUE THREAD

**Issue by nikita-tarasov3** [danielkrupinski/Osiris#2077]
I noticed that aimbot, triggerbot are work not very well without Engine Prediction. @danielkrupinski please add this important feature.

**Comment by newcommerdontblame** [comment]
https://github.com/danielkrupinski/Osiris/pull/1040

**Comment by nikita-tarasov3** [comment]
> #1040

Ok. I have problem next: aimbot misses more. i cant make headshot from 1 time.
