### ISSUE TITLE
[bug?]

### ISSUE THREAD

**Issue by ViniciusSchifferGuedes** [danielkrupinski/Osiris#208]
why seems old osiris better than new osiris? i dont know how explain but, i'm the only1 with this bug? seems aimbot is pushing for wrong side but old osiris works perfectly... what are u guys thinking about it?

**Comment by ViniciusSchifferGuedes** [comment]
if u turn on silent aim and try spray after a headshot(sv_cheats 1 + gods), the silent aim make ur bullets hit above the bots O.o

**Comment by ViniciusSchifferGuedes** [comment]
![image](https://user-images.githubusercontent.com/50452687/58376770-822ef880-7f48-11e9-8f1d-ba03eefe6687.png)
![image](https://user-images.githubusercontent.com/50452687/58376774-88bd7000-7f48-11e9-985f-328541629642.png)

**Comment by ViniciusSchifferGuedes** [comment]
![image](https://user-images.githubusercontent.com/50452687/58376777-9c68d680-7f48-11e9-95a2-aa19fbb4da77.png)
![image](https://user-images.githubusercontent.com/50452687/58376782-ac80b600-7f48-11e9-8e30-7e8ac70a2055.png)

**Comment by effex1337** [comment]
Umm did you mean that enabling silent ans shooting bugs your movement? 
That happens to me as well

**Comment by effex1337** [comment]
Just found that out cause i don't use silent aim

**Comment by HeadlessCpp** [comment]
RCS should fix the shooting over heads, and the movement "bug" is because your body isn't looking the same direction; because silent aim.

**Comment by ViniciusSchifferGuedes** [comment]
i need make a comparison video to u guys understand x.x, my aimbot(even without silent aim) it target even above bots/players, isnt calibraded

**Comment by ViniciusSchifferGuedes** [comment]
wtf, i did try it now but its "auto fixed" my silent now is targeting his head, idk what i did wrong, i'll try to found and report
