### ISSUE TITLE
[Request]triggerbot hitchance

### ISSUE THREAD

**Issue by liucyin** [danielkrupinski/Osiris#2083]
#1129 dosent work

**Comment by newcommerdontblame** [comment]
better https://github.com/danielkrupinski/Osiris/pull/1551/commits/e7185ceb4a70af614cf1e4fd0bd59e5273698d7f

**Comment by liucyin** [comment]
> better [e7185ce](https://github.com/danielkrupinski/Osiris/commit/e7185ceb4a70af614cf1e4fd0bd59e5273698d7f)

need fix

**Comment by liucyin** [comment]
> better [e7185ce](https://github.com/danielkrupinski/Osiris/commit/e7185ceb4a70af614cf1e4fd0bd59e5273698d7f)

nice.How do I set the inaccuracy to make the hitchance reach 100%？^_^
