### ISSUE TITLE
Set drawList Font?

### ISSUE THREAD

**Issue by sheavyq** [danielkrupinski/Osiris#2084]
Hey, how can i set custom fonts to drawList (like Arial, Calibri, etc... from Windows/Fonts folder)?

**Comment by nosexynomoney** [comment]
ImGui::GetIO().font->AddFontFromFileTTF(...)

**Comment by nosexynomoney** [comment]
![XHX2SH~%PAR~P1N 618Z8VN](https://user-images.githubusercontent.com/54616349/90392281-27d80580-e0c1-11ea-83fa-440c21786352.png)
And then use AddText
