### ISSUE TITLE
CAN SOMEONE JUST LOOK AT THIS MF 2 LINES OF CODE PLEASE 

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#2086]
Very dump question i guess but why am i getting these errors while im tryna build 
isnt everything ok?

![Untitled](https://user-images.githubusercontent.com/65455170/90338883-74560f00-dff5-11ea-88de-f8155cc9f4c7.png)

**Comment by 3Ld4D** [comment]
```cpp
auto weaponIndex = getWeaponIndex(activeWeapon->itemDefinitionIndex2());
config->aimbot[weaponIndex].enabled
