### ISSUE TITLE
auto stop

### ISSUE THREAD

**Issue by ifeelthegamesensewhynot** [danielkrupinski/Osiris#2087]
who have auto stop code? (clear and easy)

**Comment by dayz2000** [comment]
#2039

**Comment by newcommerdontblame** [comment]
> #2039

it is fast stop not auto stop

**Comment by SunzBody** [comment]
what's auto stop ?

**Comment by newcommerdontblame** [comment]
> what's auto stop ?

basicly stops player millisecond before ragebot starts shooting to enemy 
++better accuracy

**Comment by dayz2000** [comment]
#2074
ragebot have auto stop when u shot
