### ISSUE TITLE
[QUESTION]why add opposite hand knife? when you can do it with "CSGO" console and autoexec 

### ISSUE THREAD

**Issue by infinity1211** [danielkrupinski/Osiris#2089]
bind "1" "slot1; cl_righthand 1"
bind "2" "slot2; cl_righthand 1"
bind "3" "slot3; cl_righthand 0"
bind "4" "slot5; cl_righthand 1;"

change values accordingly for right hand knife

**Comment by newcommerdontblame** [comment]
Why not bro? also it spamming console cl-righthand

**Comment by infinity1211** [comment]
> Why not bro? also it spamming console cl-righthand 

bind "1" "slot1; cl_righthand 1; clear"
bind "2" "slot2; cl_righthand 1; clear"
bind "3" "slot3; cl_righthand 0; clear"
bind "4" "slot5; cl_righthand 1; clear"

Now it wont spam

**Comment by danielkrupinski** [comment]
Zeus x27 is also in slot 3.

**Comment by infinity1211** [comment]
oh. Thanks!
