### ISSUE TITLE
[Bug?²] Aimbot !

### ISSUE THREAD

**Issue by ViniciusSchifferGuedes** [danielkrupinski/Osiris#209]
This is what i'm trying to say.

I did make the same mouse moviment*

https://youtu.be/NMgBZjA6DWM

**Comment by ViniciusSchifferGuedes** [comment]
Now with old version of osiris.

I did make the same mouse moviment*

https://youtu.be/9wTAyg_j4vE

**Comment by NexSqaud** [comment]
I think fixed now https://youtu.be/oVByRxHCjrs
https://github.com/danielkrupinski/Osiris/commit/2150387e2670f1fe37c9fd6c2be637d889f94c29
(i dont have on key checkbox and 1 slider because, but have newer aimbot.cpp and aimbot.h)

**Comment by danielkrupinski** [comment]
Fixed.
