### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by XeroX001** [danielkrupinski/Osiris#2094]
I injected the dll file with process hacker and pressed insert in menu but nothing happen. Wut to do now?

**Comment by EzekielCloud** [comment]
It might have been your anti virus. Try disabling it before injecting, you can enable it right after the menu pops up. If not you can try another injector like ExtremeInjector with manualmap and secure mode.

**Comment by Tsun0193** [comment]
Since the last update, process hacker can't inject osiris into CS:GO anymore. You should have used loadlib injector instead.

**Comment by XeroX001** [comment]
Thank you guys.. it worked by changing injector
