### ISSUE TITLE
How to update the cheat? what files need to be updated! ?

### ISSUE THREAD

**Issue by BALCETUL** [danielkrupinski/Osiris#2095]
If auto update and where is it! 7 Do I always need to download the source from you? or enough, create a new dll?

**Comment by 0xE232FE** [comment]
This is not a ready to use product! For this you need to pay! If this is on your mind stop reading!

If you intent to learn start with  [how to use git](https://www.youtube.com/watch?v=SWYqp7iY_Tc)

**Comment by notgoodusename** [comment]
> This is not a ready to use product! For this you need to pay!

what

**Comment by nikita-tarasov3** [comment]
> > This is not a ready to use product! For this you need to pay!
> 
> what

lol!
