### ISSUE TITLE
anti-aim no works

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#2098]
anti-aim no works. tested with thirdperson and anti-aim no works

**Comment by sheavyq** [comment]
try with bot_mimic 1?

**Comment by 0xE232FE** [comment]
Did you enabled aimbot?

**Comment by nikita-tarasov3** [comment]
> Did you enabled aimbot?

yes

**Comment by Cyk-Fad** [comment]
You need animation fix and better LegitCode

**Comment by igre3zy** [comment]
The Legit AA does work, you need to turn choked packets in the misc tab to 1. The pitch slider is up and down, and the yaw only peeks the fake towards the right with no way to switch. The Legit AA does work, but it definitely needs some work by daniel. @danielkrupinski

**Comment by uzdiiilekk** [comment]
Antiaim working but you dont see it
