### ISSUE TITLE
velocity line graph?

### ISSUE THREAD

**Issue by sheavyq** [danielkrupinski/Osiris#2099]
![image](https://user-images.githubusercontent.com/68903936/90527253-9f656d80-e171-11ea-8af4-c9b9c1e56fdd.png)
I seen it in movesiris, and Interium, and i think its a cool feature, I tried this with rendering a line from (graph y pos + current velocity) and (graph x pos - 1), but i dont know how to make it always moving left, or how to render line from latest velocity to latest velocity + 1 :/
Can anyone help me how to do that? (just the white line, not the numbers or etc...):d

**Comment by newcommerdontblame** [comment]
https://yougame.biz/threads/153567/#post-1651086 hey you can use movesiris

**Comment by sheavyq** [comment]
> https://yougame.biz/threads/153567/#post-1651086 hey you can use movesiris

Uhm i know that, but i have some self features in my paste and i want to use these with velocity line graph and etc, what movesiris didnt have

**Comment by aljawary** [comment]
> https://yougame.biz/threads/153567/#post-1651086 hey you can use movesiris

do u have movesiris source?

**Comment by sheavyq** [comment]
> ![image](https://user-images.githubusercontent.com/68903936/90527253-9f656d80-e171-11ea-8af4-c9b9c1e56fdd.png)
> I seen it in movesiris, and Interium, and i think its a cool feature, I tried this with rendering a line from (graph y pos + current velocity) and (graph x pos - 1), but i dont know how to make it always moving left, or how to render line from latest velocity to latest velocity + 1 :/
> Can anyone help me how to do that? (just the white line, not the numbers or etc...):d

I close this because I finished with the velocity line graph :d

**Comment by koon666** [comment]
please pass me this code on my discord :(. I've been trying for a long time but I don't think

**Comment by joshuaisafemboy** [comment]
> > ![image](https://user-images.githubusercontent.com/68903936/90527253-9f656d80-e171-11ea-8af4-c9b9c1e56fdd.png)
> > I seen it in movesiris, and Interium, and i think its a cool feature, I tried this with rendering a line from (graph y pos + current velocity) and (graph x pos - 1), but i dont know how to make it always moving left, or how to render line from latest velocity to latest velocity + 1 :/
> > Can anyone help me how to do that? (just the white line, not the numbers or etc...):d
> 
> I close this because I finished the velocity line graph :d

could u help me pls??

**Comment by stacyonthatbeat** [comment]
> please pass me this code on my discord :(. I've been trying for a long time but I don't think

yo can you pass me the code/talk? triplex#0048

**Comment by Qoft** [comment]
yeahhhh need source of that, i would put my own into the original Osiris but too much work kek
