### ISSUE TITLE
CSGO crashes after inject

### ISSUE THREAD

**Issue by CSkya32** [danielkrupinski/Osiris#21]
The cheat worked fine yesterday.
CSGO crashes without any error message.
I have updated the cheat to the latest version (recompiling with the latest src) and it still happens

**Comment by CSkya32** [comment]
Another cheat I use for rage cheating works (I use the same injector for osiris and my rage cheat)

**Comment by danielkrupinski** [comment]
Is there any error message?

**Comment by danielkrupinski** [comment]
Please verify game files https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335

**Comment by CSkya32** [comment]
I did and it still crashes

**Comment by CSkya32** [comment]
(It closes itself it does not really freeze or crash it just closes)

**Comment by danielkrupinski** [comment]
Attach debugger to game process before injection, and check what's crash cause. Also try different dll injectors.

**Comment by CSkya32** [comment]
I attached the vs debugger and this is what I got: Exception thrown at 0x41D49D50 (Osiris.dll) in csgo.exe: 0xC0000005: Access violation reading location 0x0000390A. occurred

**Comment by danielkrupinski** [comment]
Should now be fixed. Thanks for your report!

**Comment by Aidan7831** [comment]
im getting crashes now

**Comment by xAkiraMiura** [comment]
this issue is 15 months old. (over a year!)
can we make new issues and not necro post?
