### ISSUE TITLE
jump check ?

### ISSUE THREAD

**Issue by dayz2000** [danielkrupinski/Osiris#2100]
maybe ?

**Comment by aljawary** [comment]
#1712 here

**Comment by dayz2000** [comment]
> #1712 here

but i got 4 warning in config.cpp

**Comment by dayz2000** [comment]
help me pls

**Comment by aljawary** [comment]
> help me pls

u just need to sync code with new config saving

**Comment by dayz2000** [comment]
> > help me pls
> 
> u need to sync code with new config saving

dont know how to do

**Comment by aljawary** [comment]
in config.cpp 

read(j, "jump check", a.JumpCheck);
and 
WRITE("jump check", JumpCheck);

**Comment by dayz2000** [comment]
> WRITE("jump check", JumpCheck);

thx bro

**Comment by dayz2000** [comment]
> in config.cpp
> 
> read(j, "jump check", a.JumpCheck);
> and
> WRITE("jump check", JumpCheck);

but still have erroes in line 308 and line 772

**Comment by aljawary** [comment]
> > in config.cpp
> > read(j, "jump check", a.JumpCheck);
> > and
> > WRITE("jump check", JumpCheck);
> 
> but still have erroes in line 308 and line 772

can u screenshots

**Comment by dayz2000** [comment]
> > > in config.cpp
> > > read(j, "jump check", a.JumpCheck);
> > > and
> > > WRITE("jump check", JumpCheck);
> > 
> > 
> > but still have erroes in line 308 and line 772
> 
> can u screenshots

how to fix ?

**Comment by infinity1211** [comment]
struct Aimbot {
        bool enabled{ false };
        bool onKey{ false };
        int key{ 0 };
        int keyMode{ 0 };
        bool aimlock{ false };
        bool silent{ false };
        bool friendlyFire{ false };
        bool visibleOnly{ true };
        bool scopedOnly{ true };
        bool ignoreFlash{ false };
        bool ignoreSmoke{ false };
        bool autoShot{ false };
        bool autoScope{ false };
        float fov{ 0.0f };
        float smooth{ 1.0f };
        int bone{ 0 };
        float maxAimInaccuracy{ 1.0f };
        float maxShotInaccuracy{ 1.0f };
        int minDamage{ 1 };
        bool killshot{ false };
        bool betweenShots{ true };
**     bool JumpCheck { true }

**Comment by infinity1211** [comment]
you have "j" instead of "J"
