### ISSUE TITLE
New recoil crosshair

### ISSUE THREAD

**Issue by lordeternity000** [danielkrupinski/Osiris#2102]
The new recoil crosshair thing is shit. I don't want two crosshairs on my screen. The previous way was better.

**Comment by caiocinel** [comment]
Undo the commit, simple.

**Comment by lordeternity000** [comment]
I know, i have already done that. Just pointing out

**Comment by liucyin** [comment]
> I know, i have already done that. Just pointing out

how did you do that

**Comment by caiocinel** [comment]
> > I know, i have already done that. Just pointing out
> 
> how did you do that

Undo this:
https://github.com/danielkrupinski/Osiris/commit/2f8a91635fa2aa0d8bc83b31690b419f7ed8fe2c

**Comment by liucyin** [comment]
> > > I know, i have already done that. Just pointing out
> > 
> > 
> > how did you do that
> 
> Undo this:
> [2f8a916](https://github.com/danielkrupinski/Osiris/commit/2f8a91635fa2aa0d8bc83b31690b419f7ed8fe2c)

thanks :D
