### ISSUE TITLE
helpful features i guess

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#2103]
Note : I already have added these features to my version of the cheat, but I think it would be nice to have @danielkrupinski implement them when he can/wants.

 [Features that can be added]
- Fast stop( Auto counter strafe)
- Standalone RCS
- Trigger hitchance (ray trace)
- Aimbot hitchance (ray trace)
- Aimbot Reaction time

[Features that should be improved]
- Grenade Prediction should be redone, the game's Grenade Prediction is bad.

**Comment by dayz2000** [comment]
share ?

**Comment by XeroX001** [comment]
RCS  standalone is all I want

**Comment by aljawary** [comment]
> RCS standalone is all I want

U can paste from there #1277
