### ISSUE TITLE
Add Legit Anti-Aim and Resolver?

### ISSUE THREAD

**Issue by mxrcxlxgx** [danielkrupinski/Osiris#2105]
Hello. 

Osiris is great against anything except HvH against paid cheats that have Legit Anti-Aim (LAA) since Osiris does not have LAA and does not have a resolver that allows the aim-bot to headshot LAA users.
Are LAA and resolver planned to be added? This would make Osiris even better.

Thank you.

**Comment by aljawary** [comment]
#2074 1 more missing is resolver

**Comment by SwagsRGB** [comment]
Osiris is not actually a HvH cheat; its a legit based cheat. So if you take it against paid hvh cheats it will definitely underperform. I'd suggest using it just as a legit cheat and not as hvh. That being said, #2065 might help you.

**Comment by AntonDoil** [comment]
For the resolver (legit aa, rage aa) you need proper anim fix, make resolver takes too much hours if you want quality resolver.
