### ISSUE TITLE
ESP "smooth", ESP 3D box issue, (FIXED) ESP font change

### ISSUE THREAD

**Issue by playday3008** [danielkrupinski/Osiris#2106]
![зображення](https://user-images.githubusercontent.com/18056374/90822052-219d8f80-e334-11ea-8d5d-13a22c095350.png)

if I move the mouse quickly, I see this

**Comment by playday3008** [comment]
![зображення](https://user-images.githubusercontent.com/18056374/90823490-4135b780-e336-11ea-8922-60be188058a7.png)
in GOESP same

**Comment by danielkrupinski** [comment]
Could you record a video?

**Comment by playday3008** [comment]
@danielkrupinski bonus https://streamable.com/d5jumu

**Comment by playday3008** [comment]
@danielkrupinski founded "Arial Black" font bug https://streamable.com/7bms8r

**Comment by playday3008** [comment]
Also, all this bugs tested on Windows 7 and Windows 10, and enabled/disabled milticore rendering

**Comment by danielkrupinski** [comment]
Build as "Debug" and show the line where it crashes.

**Comment by danielkrupinski** [comment]
Build as "Debug" and show the line where it crashes.

**Comment by playday3008** [comment]
![image](https://user-images.githubusercontent.com/18056374/93027980-00694f80-f611-11ea-8db4-cf33aac32123.png)

**Comment by w1ldac3** [comment]
Verified that this issue occurs on my PC as well.

**Comment by danielkrupinski** [comment]
@playday3008 Please check if the font config issue persists after 9c7d4a92aa3e5ed93a6af2b79845421b9fef1f04.

**Comment by playday3008** [comment]
Worked, and "Arial Black ?" this is "Arial Black Default"

**Comment by newcommerdontblame** [comment]
@playday3008  how do u fix that same thing happened on me

**Comment by playday3008** [comment]
ESP "smooth", ESP 3D box issue not fixed
