### ISSUE TITLE
Aimbot Bug

### ISSUE THREAD

**Issue by EGTLoneWolf** [danielkrupinski/Osiris#211]
When i am using the aimbot , it locks and i cannot pull mouse down

**Comment by ViniciusSchifferGuedes** [comment]
i did get it too, i make a video 

new osiris > (with bug) https://youtu.be/NMgBZjA6DWM

Old Osiris > (working perfectly) https://youtu.be/9wTAyg_j4vE

**Comment by danielkrupinski** [comment]
Fixed.
