### ISSUE TITLE
[REQUEST]Asus wall ?

### ISSUE THREAD

**Issue by dayz2000** [danielkrupinski/Osiris#2115]

**Comment by AntonDoil** [comment]
> void Visuals::transparentWorld() noexcept
> {
> if (!config->visuals.worldtrans && !config->visuals.proptrans)
> return;
> 
> for (short h = interfaces->materialSystem->firstMaterial(); h != interfaces->materialSystem->invalidMaterial(); h = interfaces->materialSystem->nextMaterial(h)) {
> const auto mat = interfaces->materialSystem->getMaterial(h);
> 
> ```
> if (!mat || ((!config->visuals.Ignore_precache && !mat->isPrecached()) ^ (config->visuals.Precache_Only && mat->isPrecached())))
>    continue;
> 
> 
> const std::string_view textureGroup = mat->getTextureGroupName();
> 
> if ((textureGroup.starts_with("World") && config->visuals.worldtrans)) {
>         mat->alphaModulate((config->visuals.alphaval / 1000.0f));
> }
> if ((textureGroup.starts_with("StaticProp") && config->visuals.proptrans)) {
>     
>     ConVar* static_Prop = interfaces->cvar->findVar("r_DrawSpecificStaticProp");
>     static_Prop->setValue(0);    
> 
>     mat->alphaModulate((config->visuals.propalphaval / 1000.0f));
> }
> ```
> 
> }

crashing for some reason
