### ISSUE TITLE
Issue with injecting.

### ISSUE THREAD

**Issue by Pootisberd** [danielkrupinski/Osiris#2118]
I have tried multiple times after creating the .dll, the menu does not come up. I do not know if osiris is injecting or not. (Tried while in untrusted mode)

**Comment by ugurisik** [comment]
You must type -insecure in the launch options,(If I do not write this, the menu does not open )

**Comment by Pootisberd** [comment]
well now i cannot join VAC servers

**Comment by Pootisberd** [comment]
@ugurisik could i get a response please

**Comment by infinity1211** [comment]
Try pressing insert?

**Comment by infinity1211** [comment]
Probably Injector issue. Try Xenos with Native inject (Caution: will get you untrusted ban!)

**Comment by ugurisik** [comment]
@Pootisberd  You can try this injector -> [here](https://dosya.co/r3cjddnr6fwf/RadionInjector.exe.html
)  your dll name should be Cheat.dll and both must be in the same file

**Comment by igre3zy** [comment]
just use sazzinjector it works in trusted mode ive been cheating for 135 hours and 15 comp wins already, no ban.

**Comment by HowToMakeFaceitAB** [comment]
> well now i cannot join VAC servers, is there anyway i can get the menu working and be able to play on valve servers?

????????????????????????????? just use a manual map injector

**Comment by Tothale** [comment]
@Pootisberd I think you need to bypass CS:GO's LoadLibrary injection prevention mechanism
and you can do this with:
1. download [OneByteLdr](https://github.com/danielkrupinski/OneByteLdr)
2. extract
3. download [python](https://www.python.org/ftp/python/3.8.5/python-3.8.5.exe)
4. open cmd or something like that with **administrator**
5. write `pip install Pymem` (this needed for using OneByteLdr.py)
6. open CS:GO
7. you need to cd your OneByteLdr.py location like: `cd C:\user\Desktop\OneByteLdr` (I don't know yours, you have to look at yours)
8. write (in cmd with administrator) `python OneByteLdr.py`
9. open your injector (i don't know but it may require **run with administrator**)
10. That's it press insert and open your Osiris menu.

**Comment by techzin** [comment]
> > well now i cannot join VAC servers, is there anyway i can get the menu working and be able to play on valve servers?
> 
> ????????????????????????????? just use a manual map injector

Manual Map not work with Osiris.

**Comment by HowToMakeFaceitAB** [comment]
> > > well now i cannot join VAC servers, is there anyway i can get the menu working and be able to play on valve servers?
> > 
> > 
> > ????????????????????????????? just use a manual map injector
> 
> Manual Map not work with Osiris.

it works perfectly fine for me, use a different injector
