### ISSUE TITLE
Faceit support

### ISSUE THREAD

**Issue by TracerOW** [danielkrupinski/Osiris#2119]
Hey! i would like to know if the current version works with faceit without getting detected?
if not i would like to know why\whats missing 
i saw 2 answers from 2 different contributors - one said it works and the other said its not so if you have an answer it will help me a lot.
Thanks (:

**Comment by newcommerdontblame** [comment]
it doesnt work normally but somehow faceit doesnt want anticheat at some accounts idk why u can use if u are lucky too

**Comment by rishavmitra05** [comment]
I used it and played 2 matches ..still not banned..idk for sure if u can use it or not

**Comment by danielkrupinski** [comment]
It isn't safe to use aimbot on Faceit because we don't calculate mouse delta to match view angles change.

**Comment by TracerOW** [comment]
> I used it and played 2 matches ..still not banned..idk for sure if u can use it or not

were you running faceit anti cheat while playing those 2 games?

**Comment by TracerOW** [comment]
> It isn't safe to use aimbot on Faceit because we don't calculate mouse delta to match view angles change.

for this particular issue im asking only regarding wall hack feature, do you think it is safe? will work? id love to get some info
also i sent you an email from an address starts with: DLRP.fivem
thanks!

**Comment by rishavmitra05** [comment]
Yes the Anticheat was on but I was only using Radar Hack

**Comment by MasterChief220** [comment]
> > It isn't safe to use aimbot on Faceit because we don't calculate mouse delta to match view angles change.
> 
> for this particular issue im asking only regarding wall hack feature, do you think it is safe? will work? id love to get some info
> cuz i do mean to run the wall hack cheat with faceit anti cheat activated
> also i sent you an email from an address starts with: DLRP.fivem
> thanks!

did it work?

**Comment by rishavmitra05** [comment]
Can it work in SoStronk though...I'm Curious
