### ISSUE TITLE
what's fake duck looks like in demo ?

### ISSUE THREAD

**Issue by dayz2000** [danielkrupinski/Osiris#2120]
will get ban for use ?

**Comment by Pootisberd** [comment]
yes you get ban for cheat

**Comment by AntonDoil** [comment]
@Pootisberd Aint true, i cheating on my account more then 3 months and im without ban (every game i semi raging)

**Comment by rosesware** [comment]
> @Pootisberd Aint true, i cheating on my account more then 3 months and im without ban (every game i semi ragin')

Read the title.

**Comment by AntonDoil** [comment]
> > @Pootisberd Aint true, i cheating on my account more then 3 months and im without ban (every game i semi ragin')
> 
> Read the title.

What u talkin' about? I know on what i typed answer

**Comment by newcommerdontblame** [comment]
Why people so scaring about ow its hard to get ban even if u autowallin

**Comment by newcommerdontblame** [comment]
u cant use fakeduck in valve servers u just can fast duck and its not problem cuz demos are 32tick
