### ISSUE TITLE
Recoil Crosshair

### ISSUE THREAD

**Issue by hyldos144fps** [danielkrupinski/Osiris#2123]
The new recoil crosshair doesn't show recoil when spamming pistols. Earlier it used to. Also two crosshairs on the screen are a bit of a mess. I can still use the old osiris file but how to get the previous crosshair while also being able to use new features from the new versions of osiris?

**Comment by igre3zy** [comment]
the old recoil crosshair on the pistol was inaccurate. i found it easier to shoot with pistols after it was removed

**Comment by eating-pogfish** [comment]
how does it work? I can't see anything on the screen

**Comment by hayyaun** [comment]
There is no recoil crosshair in new version or I can't find it?
