### ISSUE TITLE
How to know player's weapons? even player's activeweapon is not it.

### ISSUE THREAD

**Issue by Cyk-Fad** [danielkrupinski/Osiris#2124]
example. enemy has Ak47. but his active weapon is glock. how to know his other weapons?

**Comment by Cyk-Fad** [comment]
I make a WeaponRecordSystem but it works not good

**Comment by danielkrupinski** [comment]
https://github.com/danielkrupinski/Osiris/blob/4b161f9a650121f44386d676bbd121cee631b620/Osiris/SDK/Entity.h#L202

**Comment by Cyk-Fad** [comment]
> https://github.com/danielkrupinski/Osiris/blob/4b161f9a650121f44386d676bbd121cee631b620/Osiris/SDK/Entity.h#L202

oh thankyou danie
