### ISSUE TITLE
(Request) weapon,nade icons for esp 

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#2126]
i tried to add nade image but it fucked my fps so i found this (https://www.unknowncheats.me/forum/cs-go-releases/169881-csgo-weapon-icons-ttf-font.html) post that he made icons for every gun ((its just font))(u can see it in here(https://prnt.sc/u57shr))

im just gonna ask can someone make it for osiris please @danielkrupinski its nice if u can add this to main cheat better than "granade" text i think

Here is example: https://streamable.com/254fu0

**Comment by newcommerdontblame** [comment]
+++ nade timer is necessary feature for legit cheat

**Comment by 3Ld4D** [comment]
just paste it from sensum.
