### ISSUE TITLE
fresh download of osiris, getting errors in hooks and stuff

### ISSUE THREAD

**Issue by CantRememberMyself** [danielkrupinski/Osiris#2129]
![image](https://user-images.githubusercontent.com/57680049/91181239-9aa83880-e6e0-11ea-98cc-079ff615b6b9.png)
![image](https://user-images.githubusercontent.com/57680049/91181295-aa278180-e6e0-11ea-9f13-f78b5b401d1d.png)
the weird part is that the inputsystem and stuff works in some files, but not others.

**Comment by infinity1211** [comment]
it's a bug with intellisense.
