### ISSUE TITLE
Can't inject.

### ISSUE THREAD

**Issue by Hertz3241** [danielkrupinski/Osiris#2130]
I used multiple injectors, each with default options. 

I get an error in every single injector I used so far, which are Xenos, X Injector, and Extreme injector.
None of them worked.

Please help.

**Comment by NuclearC** [comment]
hmm whats the error man, u know we cant help u IF WE DONT KNOW THE GOD DAMN ERROR

**Comment by Tothale** [comment]
maybe you need to turn off your antivirus or you need to bypass CS:GO's LoadLibrary injection prevention mechanism
if you want to try:
1. download [OneByteLdr](https://github.com/danielkrupinski/OneByteLdr)
2. extract
3. download [python](https://www.python.org/ftp/python/3.8.5/python-3.8.5.exe)
4. open cmd or something like that with **administrator**
5. write `pip install Pymem` (this needed for using OneByteLdr.py)
6. open CS:GO
7. you need to cd your OneByteLdr.py location like: `cd C:\user\Desktop\OneByteLdr` (I don't know yours, you have to look at yours)
8. write (in cmd with administrator) `python OneByteLdr.py`
9. open your injector (i don't know but it may require **run with administrator**)
10. That's it press insert and open your Osiris.

**Comment by Hertz3241** [comment]
Nevermind, I used Extreme Injector on Manual Map mode and it worked, but I had to use an older version of the cheat.
