### ISSUE TITLE
400ms backtrack. (from pullrequest)

### ISSUE THREAD

**Issue by JacksonDon** [danielkrupinski/Osiris#2131]
So today, i added 400ms backtrack from pull request and everytime i get crash. 

It crashing there: 

[Screen](https://imgur.com/a/VGdaIDA)

I guess it only get happened when i hit last few ticks of backtrack, fake latency 200. (400ms bt)

**Comment by AntonDoil** [comment]
@danielkrupinski @lofcz @RyDeem some idea how to fix it?

**Comment by Im-Beast** [comment]
I bet daniel wont help you because its not in his interest

**Comment by AntonDoil** [comment]
Why its crashin? 
I guess... 

`while (records[i].size() > 3 && records[i].size() > static_cast<size_t>(timeToTicks(static_cast<float>(config.backtrack.timeLimit) / 1000.f + getExtraTicks())))`

It started crash when i added this: getExtraTicks() 

Everything before was okay, there is problem when we add fake latency.

**Comment by RyDeem** [comment]
what do you mean you add fake latency? 
a differrent function interacting with ping, or from my pull c+p sting error? 
Try my pull with clean master from dan it works fine in matches that ive tested on
