### ISSUE TITLE
FPS DROP

### ISSUE THREAD

**Issue by eating-pogfish** [danielkrupinski/Osiris#2132]
Hello, I'm using osiris for a while and never got drop, I actually even got more fps using some features, I decided going with aimbot and bhop only, and still, my fps is average around 300, now it drops to sometimes, 14 fps.
Any fix for that?

**Comment by AntonDoil** [comment]
you can try launch options what i usin' : -novid -high -d3d9ex -noubershader

**Comment by SapphireCodenz** [comment]
make sure you have built it like that:
![image](https://user-images.githubusercontent.com/55666872/91335237-cc042f80-e7d8-11ea-8e61-72bcc808e695.png)

**Comment by igre3zy** [comment]
dont use launch options, use AVX2 code gen
