### ISSUE TITLE
How can i add image ?

### ISSUE THREAD

**Issue by ugurisik** [danielkrupinski/Osiris#2133]
Hello guys, 
I've edited the menu, but I can't add an image to the buttons or next to it Can anyone help ? 
![image](https://user-images.githubusercontent.com/54710006/91337195-af1d2b80-e7db-11ea-9128-519e11a6ead8.png)

**Comment by hydemods** [comment]
Use a font with the images in it

**Comment by AntonDoil** [comment]
ImGui::PushFont(nameoffont); 
//There you draw your button, **BUT** you cannot use text "Aimbot" you need to use text "H" 
ImGui::PopFont();

> Now please close this issue, you got your answer.

**Comment by ugurisik** [comment]
@AntonDoil I did as you said but it gave such an error, how can I solve it?

![Adsız](https://user-images.githubusercontent.com/54710006/91636960-5af98d80-ea0d-11ea-8316-30f33813d877.png)
