### ISSUE TITLE
Question about skinchanger

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#2137]
is it hard to make skin changer changes also names of skins at buy menu and weapon that localplayer holding ? how can i do that ?

**Comment by AntonDoil** [comment]
Like when u hold ak47 and want ak47 in the skinchanger as activeweapon?

**Comment by newcommerdontblame** [comment]
@AntonDoil nah
its like when u enable any skin from changer 
ur buy menu is not changing its still shows default skin that u have. 
Its pretty bad for people who streaming or taking video with osiris

**Comment by newcommerdontblame** [comment]
same as for playermodels 
when u change ur playermodel from visuals it shows default it doesnt changing at buy menu

**Comment by AntonDoil** [comment]
For that you need inventory changer, not possible with skin changer.

**Comment by igre3zy** [comment]
> For that you need inventory changer, not possible with skin changer/model changer.
> 
> > When you implement the inventory changer, u'll be fine. Now please close this issue you actually got answer.

ive seen cheats w/o an inv changer that can do this. Pretty sure thats false
