### ISSUE TITLE
Failed to inject

### ISSUE THREAD

**Issue by kaustuv90** [danielkrupinski/Osiris#2139]
I am not able to inject 
showing failed to inject image.

![Screenshot (31)_LI](https://user-images.githubusercontent.com/42085276/91592399-22f63a00-e97c-11ea-9285-a2c4738014ce.jpg)

**Comment by SunzBody** [comment]
Try to inject Osiris with Process Hacker in Administrator

**Comment by kaustuv90** [comment]
> Try to inject Osiris with Process Hacker in Administrator

Can you give me the injector which you use?

**Comment by AntonDoil** [comment]
> > Try to inject Osiris with Process Hacker in Administrator
> 
> Can you give me the injector which you use?

Dont use the latest LoadLibrary injection method, its actually fixed by Valve. 
Use some injector with manualmap. 

I can share the injector (loadlibrary + bypass) 

[https://anonfiles.com/veA3LaP6o8/csgoInjector_exe](Download here) 

> Put the injector in the same file where is ur .dll, and change name of the .dll onto > cheat.dll
> Open injector and enjoy.

Information: I had source of the injector, but I dont know where I downloaded it.. (I dont have source..)

**Comment by kaustuv90** [comment]
> > > Try to inject Osiris with Process Hacker in Administrator
> > 
> > 
> > Can you give me the injector which you use?
> 
> Dont use the latest LoadLibrary injection method, its actually fixed by Valve.
> Use some injector with manualmap.
> 
> I can share the injector (loadlibrary + bypass)
> 
> [Download here](https://anonfiles.com/veA3LaP6o8/csgoInjector_exe)
> 
> > Put the injector in the same file where is ur .dll, and change name of the .dll onto > cheat.dll
> > Open injector and enjoy.
> 
> Information: I had source of the injector, but I dont know where I downloaded it.. (I dont have source..)
> 
> Be aware, cause its public injector without any security/junkcodes, is possible you can get vac banned in few weeks.

Thanks bro will give it a try
