### ISSUE TITLE
removing commits

### ISSUE THREAD

**Issue by hyldos144fps** [danielkrupinski/Osiris#2140]
How do i remove a previous commit while still be able to use the newer commits?

**Comment by igre3zy** [comment]
you talking about a commit to the master branch? or something that someone has added otherwise?

**Comment by lordeternity000** [comment]
In the master branch

**Comment by lordeternity000** [comment]
> you talking about a commit to the master branch? or something that someone has added otherwise?

The master branch, like the new recoil crosshair
