### ISSUE TITLE
cheat not working.

### ISSUE THREAD

**Issue by LogoPiz** [danielkrupinski/Osiris#2145]
injecting through process hacker 2. 
cheat won't start

**Comment by EzekielCloud** [comment]
Have you tried using another Injector? Perhaps ExtremeInjector with manual map and secure mode. https://github.com/master131/ExtremeInjector/releases/tag/v3.7.3

**Comment by LogoPiz** [comment]
> Have you tried using another Injector? Perhaps ExtremeInjector with manual map and secure mode. https://github.com/master131/ExtremeInjector/releases/tag/v3.7.3

csgo crashed.

**Comment by zajkos** [comment]
process hacker not injecting right now (or injecting when u type -insecure on starts options)
use injector!

u can try this (I'm not the author) https://www.cshacked.pl/csh-injector-09072020-t156933/?tab=comments#comment-1022060
to inject u must:
1. add cheat and injector to one folder
2. change name of cheat to "cshacked.pl.dll" 
3. open the injector as administrator

**Comment by cacvabuoi** [comment]
Do we need to use VACbypass first?

**Comment by igre3zy** [comment]
use sazzinjector, ive been cheating on osiris for 160 hours with sazz, no ban.
