### ISSUE TITLE
[PROBLEM] C2027 and E0393

### ISSUE THREAD

**Issue by Mikilis** [danielkrupinski/Osiris#2149]
Hey,
this line return me 2 errors: c2027 and e0393 WHY? https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hooks.cpp#L136

**Comment by danielkrupinski** [comment]
Now the error should be gone as we include GlobalVars.h explicitly. (https://github.com/danielkrupinski/Osiris/blob/57550094e30111976fde8ab2f89732a0d2af24b1/Osiris/Hooks.cpp#L39)
