### ISSUE TITLE
Game lags out, it's like having fakelag on

### ISSUE THREAD

**Issue by Looopering** [danielkrupinski/Osiris#215]
the title says it, all it happend in the newest commitment. feels like i have a very bad ping even though it says on net_graph and your ping watermark that i have 50 ms, could you please fix this? And sometimes, my config loads the wrong things.

**Comment by NexSqaud** [comment]
Check Max Accepatable Game Traffic Bandwitch in Game Settings.

**Comment by Looopering** [comment]
Yeah it's on max.

**Comment by danielkrupinski** [comment]
Sorry, can't help you with that problem.
