### ISSUE TITLE
[Help] migi support

### ISSUE THREAD

**Issue by kenedy3** [danielkrupinski/Osiris#2152]
I put sv_pure bypass in osiris to use with migi, but when I try to inject with the migi , do not inject.
Would have any code to support migi?

**Comment by koon666** [comment]
but it already has migi support, I use osiris myself with migi

**Comment by kenedy3** [comment]
@koon666 what loader do you use?

**Comment by blxckshark** [comment]
> already has migi support, I use osiris myself with

False positive.
