### ISSUE TITLE
shoot at non-latest backtrack records?

### ISSUE THREAD

**Issue by r3muxd** [danielkrupinski/Osiris#2153]
if you use osiris backtrack, you can only hit the LAST backtrack record
![csgo_4NBB5YHV2c](https://user-images.githubusercontent.com/46062054/92152050-16486a80-edf0-11ea-8e8e-a4dae1037a92.png)
and not any of the others in-between
it'd be helpful for legit configs so you can aim anywhere where they used to be and get a hit

**Comment by notgoodusename** [comment]
not exactly, aimbotz bots are broken

**Comment by r3muxd** [comment]
i can't hit legits either though unless i aim at last record

**Comment by aydenli530** [comment]
> if you use osiris backtrack, you can only hit the LAST backtrack record
> ![csgo_4NBB5YHV2c](https://user-images.githubusercontent.com/46062054/92152050-16486a80-edf0-11ea-8e8e-a4dae1037a92.png)
> and not any of the others in-between
> it'd be helpful for legit configs so you can aim anywhere where they used to be and get a hit

why I enable the backtrack,  the backtrack is not working, the backtrack has not to show the screen that same with you

**Comment by aljawary** [comment]
> > if you use osiris backtrack, you can only hit the LAST backtrack record
> > ![csgo_4NBB5YHV2c](https://user-images.githubusercontent.com/46062054/92152050-16486a80-edf0-11ea-8e8e-a4dae1037a92.png)
> > and not any of the others in-between
> > it'd be helpful for legit configs so you can aim anywhere where they used to be and get a hit
> > ![image](https://user-images.githubusercontent.com/48648162/92188686-d933b500-ee8f-11ea-850e-29087c62a798.png)
> 
> why I enable the backtrack, the backtrack is not working, the backtrack has not to show the screen that same with you

Turn on backtrack chams in chams tab

**Comment by aydenli530** [comment]
thx, it's work now

**Comment by HowToMakeFaceitAB** [comment]
thats wrong @r3muxd , you can shoot all the backtrack records, but osiris only draws the last one

**Comment by igre3zy** [comment]
> thats wrong @r3muxd , you can shoot all the backtrack records, but osiris only draws the last one

this is true. the only time osiris has had a problem with last tick is with ignore smoke on, but that problem was fixed a while ago. Osiris only draws the last tick, if ur missing between the last tick and the player, its probably ping related.

**Comment by r3muxd** [comment]
> probably ping related
but it's on a local server?
