### ISSUE TITLE
[REQUEST] Edgebug

### ISSUE THREAD

**Issue by SapphireCodenz** [danielkrupinski/Osiris#2158]
Can someone make an edgebug code for osiris? would be really cool

**Comment by AntonDoil** [comment]
LMFAO

**Comment by SapphireCodenz** [comment]
> LMFAO

what's funny

**Comment by newcommerdontblame** [comment]
if (config->misc.edgeBug && GetAsyncKeyState(config->misc.edgeBugKey) && localPlayer->flags() & 1)
cmd->buttons |= UserCmd::IN_DUCK;

just duck when u fall on ground 
Kinda assist for edgebug its not proper way but it works if u can get close to edge 
++ there is cheat sources outta here with edgebug (etc. hydraware.xyz , zu krass)  u can paste it from here easily

**Comment by AntonDoil** [comment]
> if (config->misc.edgeBug && GetAsyncKeyState(config->misc.edgeBugKey) && localPlayer->flags() & 1)
> cmd->buttons |= UserCmd::IN_DUCK;
> 
> just duck when u fall on ground
> Kinda assist for edgebug its not proper way but it works if u can get close to edge
> ++ there is cheat sources outta here with edgebug (etc. hydraware.xyz , zu krass) u can paste it from here easily

In the few lines you can make proper edgebug/jumpbug what has 90% hitchance to get success jb/eb.

**Comment by newcommerdontblame** [comment]
@AntonDoil so do it ??
why you tryna flex with 2 lines of code lmao

**Comment by aljawary** [comment]
> > if (config->misc.edgeBug && GetAsyncKeyState(config->misc.edgeBugKey) && localPlayer->flags() & 1)
> > cmd->buttons |= UserCmd::IN_DUCK;
> > just duck when u fall on ground
> > Kinda assist for edgebug its not proper way but it works if u can get close to edge
> > ++ there is cheat sources outta here with edgebug (etc. hydraware.xyz , zu krass) u can paste it from here easily
> 
> In the few lines you can make proper edgebug/jumpbug what has 90% hitchance to get success jb/eb (automatized)

Then make it

**Comment by AntonDoil** [comment]
> @AntonDoil so do it ??
> why you tryna flex with 2 lines of code lmao

I actually did it, but i dont want to share it and give it out for free lol, when its my main feature in cheat.

**Comment by SapphireCodenz** [comment]
@JacksonDon not like it's gonna get detected, it's a public cheat source anyways why you tryna make it private

**Comment by aljawary** [comment]
> > @AntonDoil so do it ??
> > why you tryna flex with 2 lines of code lmao
> 
> I actually did it, but i dont want to share it and give it out for free lol, when its my main feature in cheat.

Bruh

**Comment by newcommerdontblame** [comment]
> I actually did it, but i dont want to share it and give it out for free lol, when its my main feature in cheat.
![118711941_3274595612621922_4808138439225291558_n](https://user-images.githubusercontent.com/65455170/92331701-465a6c80-f081-11ea-8ef0-0b235c41083a.jpg)

**Comment by newcommerdontblame** [comment]
> 
> I actually did it, but i dont want to share it and give it out 
> > why you tryna flex with 2 lines of code lmao
> 
> I actually did it, but i dont want to share it and give it out for free lol, when its my main feature in cheat.

![118711941_3274595612621922_4808138439225291558_n](https://user-images.githubusercontent.com/65455170/92331726-743fb100-f081-11ea-955f-4c1750a51de3.jpg)

**Comment by JacksonDon** [comment]
> > > @AntonDoil so do it ??
> > > why you tryna flex with 2 lines of code lmao
> > 
> > 
> > I actually did it, but i dont want to share it and give it out for free lol, when its my main feature in cheat.
> 
> Imagine using public cheat source as private cheat

Who tf said im using osiris?

**Comment by s4ammy** [comment]
> > @AntonDoil so do it ??
> > why you tryna flex with 2 lines of code lmao
> 
> I actually did it, but i dont want to share it and give it out for free lol, when its my main feature in cheat.

i dont want to share it and give it out for free lol, when its my main feature in cheat.

nigga this is public code you implying you'd be down to sell 1 line of bullshit?

if (!(stored_flags & fl_onground) && (local_player->flags() & fl_onground)) cmd->buttons |= in_duck;

**Comment by blxckshark** [comment]
> > > @AntonDoil so do it ??
> > > why you tryna flex with 2 lines of code lmao
> > 
> > 
> > I actually did it, but i dont want to share it and give it out for free lol, when its my main feature in cheat.
> 
> i dont want to share it and give it out for free lol, when its my main feature in cheat.
> 
> nigga this is public code you implying you'd be down to sell 1 line of bullshit?
> 
> if (!(stored_flags & fl_onground) && (local_player->flags() & fl_onground)) cmd->buttons |= in_duck;

thats not proper way

**Comment by gabesmithdev** [comment]
leak.codes posted proper edgebug source this week. I cant unlock it tho. U will have to go there to get it.
