### ISSUE TITLE
Survey!

### ISSUE THREAD

**Issue by Asado-san** [danielkrupinski/Osiris#216]
Anyone got hit by VAC net prevously ?

i don't know the day when my account was hit but it was around 5 days ago. also Never got VACCED-IN Game but after logging out and a couple of hours .
my account which i was using for like 2weeks now got hitted my VAC NET & got VACCED + OW banned , thought i could go on until i get to DMG but my last Rank is GNM 

TT_TT

**Comment by NexSqaud** [comment]
Why do you think this is VAC NET? I gets VAC only after OW ban.

**Comment by Asado-san** [comment]
> Why do you think this is VAC NET? I gets VAC only after OW ban.

cause i get VAC ban fist before i get OW ban.
your account could get VAC ban fist before OW ban
OW can't turn into VAC ban
