### ISSUE TITLE
[REQUEST] draw aimbot fov

### ISSUE THREAD

**Issue by Tothale** [danielkrupinski/Osiris#2161]
I think this is a good feature for testing aimbot.

**Comment by aljawary** [comment]
#1852

**Comment by aljawary** [comment]
#1114

**Comment by HowToMakeFaceitAB** [comment]
> #1114

I think most people requesting things want it to be added to the main fork

**Comment by Tothale** [comment]
I tried to add but this is for old osiris I think. I couldn't added.

**Comment by newcommerdontblame** [comment]
void Misc::drawFov() noexcept
{
    auto local = localPlayer.get();
    if (config->misc.drawFov)
    {
        if (!local || !local->isAlive()) return;
        int weaponId = getWeaponIndex(localPlayer->getActiveWeapon()->itemDefinitionIndex2());
        if (!config->aimbot[weaponId].enabled) weaponId = 0;
        if (!config->aimbot[weaponId].enabled) return;
        auto screenSize = interfaces->surface->getScreenSize();
        if (config->aimbot[weaponId].silent) interfaces->surface->setDrawColor(255, 10, 10, 255);
        else interfaces->surface->setDrawColor(10, 255, 10, 255);
        float radius = std::tan(degreesToRadians(config->aimbot[weaponId].fov) / 2.f) / std::tan(degreesToRadians(local->isScoped() ? local->fov() : (105 + config->visuals.fov)) / 2.f) * screenSize.first;
        interfaces->surface->drawOutlinedCircle(screenSize.first / 2, screenSize.second / 2, radius, 100);
    }

}
