### ISSUE TITLE
fps drops 

### ISSUE THREAD

**Issue by MasterChief220** [danielkrupinski/Osiris#2162]
I usually get around 200 fps but when i inject osiris my fps drop to around 100 and game lags randomly. Any fix?

**Comment by igre3zy** [comment]
diable post processing and compile ur code as avx2 code gen. lemme know how it goes

**Comment by newcommerdontblame** [comment]
> diable post processing and compile ur code as avx2 code gen. lemme know how it goes

What is avx2?

**Comment by yaelahrip** [comment]
> 
> 
> > diable post processing and compile ur code as avx2 code gen. lemme know how it goes
> 
> What is avx2?
AVX2 is yet another extension to the venerable x86 line of processors, doubling the width of its SIMD vector registers to 256 bits, and adding dozens of new instructions.

_Project Property Pages | Configuration Properties | C/C++ | Code Generation | Enable Enhanced Instruction Set_

**Comment by MasterChief220** [comment]
> diable post processing and compile ur code as avx2 code gen. lemme know how it goes

compiled my code using avx2 and fps drops reduced to 120 from 200 . improvement of 20 fps and fps drops still come randomly meaning that fps drops to 30 or 20 for a second or 2 seeming as if the game has freezed .

**Comment by MasterChief220** [comment]
I also noticed that my cpu utilization of cs go after injecting osiris increases to 40 percent from 20 percent

**Comment by hahafunnyjoebro** [comment]
nice pc usell?

**Comment by MasterChief220** [comment]
> nice pc usell?

huh?

**Comment by SwagsRGB** [comment]
please research online whether your processor supports avx2 @MasterChief220

**Comment by MasterChief220** [comment]
> please research online whether your processor supports avx2 @MasterChief220

no it doesnt but how can i fix that.

**Comment by SwagsRGB** [comment]
if ur pc doesnt support avx2 then dont compile it  using avx2. The default is SSE2. Just use that and you'll be gucci

**Comment by uzdiiilekk** [comment]
Id you need add me on discord uzdiiilekk_#3312 i send you my upgraded osiris with fps drop fix
