### ISSUE TITLE
(Question)Ragdoll force

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#2164]
Someone has ragdoll force code or what cvar is changing ragdoll force

**Comment by sidekek** [comment]
assuming you mean ragdoll **gravity**, the convar is cl_ragdoll_gravity, and you need to unset FCVAR_CHEAT

**Comment by newcommerdontblame** [comment]
Ragdoll force and ragdoll gravity different things

**Comment by newcommerdontblame** [comment]
https://youtu.be/4oJ1k4X-qhM

Start from 3:16

**Comment by psycho147** [comment]
I think it's cl_phys_timescale but I might be wrong
