### ISSUE TITLE
[REQUEST] Silent aim with smooth

### ISSUE THREAD

**Issue by SapphireCodenz** [danielkrupinski/Osiris#2165]
If someone can make a slider for slient aim itself and can fix the silent aim not working if you change the smooth other than 1
Really helpful

**Comment by JacksonDon** [comment]
You cannot use smooth with silent.

**Comment by SapphireCodenz** [comment]
> You cannot use smooth with silent.

Other cheats let you do that, wym ??

**Comment by newcommerdontblame** [comment]
> Other cheats let you do that, wym ??

lmao silent aim with smooth is meme feature 

If you want smooth aimbot use normal aimbot you can't see it anyways its client sided

**Comment by YallAintthehomies** [comment]
@newcommerdontblame Its not client sided aimlock is definitely server sided everyone can see it.

**Comment by SwagsRGB** [comment]
> 
> 
> @newcommerdontblame Its not client sided aimlock is definitely server sided everyone can see it.

Lol. That's what client side means: It wont be visible to you but for everyone else watching the demo the crosshair will be "shaky".

**Comment by SwagsRGB** [comment]
> 
> 
> > Other cheats let you do that, wym ??
> 
> lmao silent aim with smooth is meme feature
> 
> If you want smooth aimbot use normal aimbot you can't see it anyways its client sided

i dont think normal aimbot is client sided man....

**Comment by newcommerdontblame** [comment]
I said silent aim dude?
