### ISSUE TITLE
(Request)disable visible only when enemy hitboxes are visible (a.k.a. Legit Autowall)

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#2167]
Idk how to describe it but its kinda semirage feature thats called legit autowall

when enemy's arms or legs(some hitboxes)are visible but ur weapon's hitbox priority is not visible aimbot able to shot from walls

**Comment by newcommerdontblame** [comment]
..

**Comment by newcommerdontblame** [comment]
@danielkrupinski here is how it looks in our view and demo

https://youtu.be/D6yGLJf8_24  

Osiris doesnt have autowall thing so u can make it as i said in title i guess hope you take a look 👍

**Comment by danielkrupinski** [comment]
Should it be togglable or always on?

**Comment by newcommerdontblame** [comment]
> Should it be togglable or always on?

Make checkbox to enable if no key always on 
if u choose key its toggleable (same as prepare revolver thing)

**Comment by newcommerdontblame** [comment]
@danielkrupinski also when i found u i wanna say something lol 
every cheat has indicators to see what keybinds working on or what things are on i think u can make it easily but i already made something on this #2076 pr kinda broke but u can take a look anyways thanks :)
