### ISSUE TITLE
How to compile the .DLL on Atom or VSCodium?

### ISSUE THREAD

**Issue by JIGASHI** [danielkrupinski/Osiris#2169]
Hi, how do you compile the latest updated version / release into a .dll file in Atom, or VSCodium? A step by step, if you please.

**Comment by newcommerdontblame** [comment]
Download Visual studio 2019
Download latest source (u can use git desktop its easier)
go osiris.sln from ur source
Choose release one in tabs (in vs)
Then build it

**Comment by JIGASHI** [comment]
No, specifically Atom or VScodium is what I'm asking. There is no "release" tab from what I could see, nor "build" or "compile" button, only run.

**Comment by Coolboy1384** [comment]
Atom and VScodium are text editors and not coding environments. You need to download Visual Studio 2019 for this. Atom is like an advanced notepad with addons.

**Comment by JIGASHI** [comment]
Surely there must be some open source pro privacy alternative(s)? Would any of these work?

https://alternativeto.net/software/visual-studio/

**Comment by danielkrupinski** [comment]
You need a compiler, not an IDE. If you don't want to install anything I think you can setup GitHub Actions to build a .dll and then just download the file.

**Comment by JIGASHI** [comment]
> 
> 
> You need a compiler, not an IDE. If you don't want to install anything I think you can setup GitHub Actions to build a .dll and then just download the file.

Do you know which actions I need to install? I'm very new to this, idk if I need to create a repo and fork your stuff and installl several actions. Would like to have it automated so when you push an update the workflow is setup on my account that it updates it and compiles the .dll and even updates it on desktop through svn update / tortoise svn.

**Comment by danielkrupinski** [comment]
https://github.com/marketplace/actions/github-action-publish-binaries
or
https://github.com/marketplace/actions/upload-files-to-a-github-release
