### ISSUE TITLE
Fuck it...add an option to replace the new gun sounds with the old ones

### ISSUE THREAD

**Issue by YallAintthehomies** [danielkrupinski/Osiris#2172]
Why fucking not
I've seen other cheats do it
also I am sorry I always forget to close my issues

**Comment by aljawary** [comment]
no need to be toxic

**Comment by debruh** [comment]
yea bro came off a little strong .-.

**Comment by notgoodusename** [comment]
> no need to be toxic

i dont think this is toxic
#1781

**Comment by YallAintthehomies** [comment]
How is this toxic

**Comment by BaiAlbert** [comment]
Just make an sv_pure bypass.
Get the convar and force it to be 0.
Then you replace the sounds in csgo files and enable the sv_pure thing to play
