### ISSUE TITLE
Error when trying to inject dll

### ISSUE THREAD

**Issue by zeshable** [danielkrupinski/Osiris#2173]
Hi whenever I try to inject Oriris dll (Compiled from GitHub) I get this error (Injector is Xenos): 
![2020-09-09 19_49_02-Window](https://user-images.githubusercontent.com/67027648/92676038-9cbfe900-f2d5-11ea-8db9-a7800c5d8790.png)

**Comment by SwagsRGB** [comment]
Delete the "Release" folder in the Osiris folder and recompile using "Release" and NOT "Debug" in Visual Studio. Also, might be an injector problem too.

**Comment by zeshable** [comment]
@SwagsRGB When I built the solution to the "Release" folder (I was recompiling into "Debug" before) I still got the same problem. Is their an injector that you recommend?

**Comment by SwagsRGB** [comment]
try recompiling it and i personally use sazz injector

**Comment by zeshable** [comment]
Hi, I just solved the problem with a different injector thanks so much!
