### ISSUE TITLE
[REQUEST] Adding a medal changer?

### ISSUE THREAD

**Issue by SwagsRGB** [danielkrupinski/Osiris#2174]
Can a medal changer be added? if not, can someone do a pull for it? Adding medals help in making the profile look much more legit.

**Comment by TrotzeyOnPC** [comment]
this would be sick, but it would be hard asf

**Comment by SunzBody** [comment]
I think it would be possible but only client-side. CS:GO's servers are not fooled and to succeed in spoofing a medal would be very, very complicated or even impossible.

**Comment by Rosic33** [comment]
Therere is a chanager but there is no menu so its commented out of the code,but its already in the cheat and it works serverside (kinda),only the equipped medal shows to others,ex. if I give myself 10 year n 5 year and equip 10 year other people only see the 10 year.

**Comment by newcommerdontblame** [comment]
> Therere is a chanager but there is no menu so its commented out of the code,but its already in the cheat and it works serverside (kinda),only the equipped medal shows to others,ex. if I give myself 10 year n 5 year and equip 10 year other people only see the 10 year.

Where

**Comment by MasterChief220** [comment]
> Therere is a chanager but there is no menu so its commented out of the code,but its already in the cheat and it works serverside (kinda),only the equipped medal shows to others,ex. if I give myself 10 year n 5 year and equip 10 year other people only see the 10 year.

how does that happen and which cheat???Slipchanger??

**Comment by Rosic33** [comment]
> > Therere is a chanager but there is no menu so its commented out of the code,but its already in the cheat and it works serverside (kinda),only the equipped medal shows to others,ex. if I give myself 10 year n 5 year and equip 10 year other people only see the 10 year.
> 
> how does that happen and which cheat???Slipchanger??



> > Therere is a chanager but there is no menu so its commented out of the code,but its already in the cheat and it works serverside (kinda),only the equipped medal shows to others,ex. if I give myself 10 year n 5 year and equip 10 year other people only see the 10 year.
> 
> Where
sorry im late,its in the nskinz source (osiris uses nskinz) here https://github.com/namazso/nSkinz/blob/master/src/Hooks/PostDataUpdate.cpp#L153 ,i dont know the exact location in osiris,but if you fix it you can implement it into osiris source

**Comment by newcommerdontblame** [comment]
@Rosic33 owner left the project while doing the thing we need lol
