### ISSUE TITLE
Get localplayer transparant while 3rdperson

### ISSUE THREAD

**Issue by yaelahrip** [danielkrupinski/Osiris#2176]
_I dont know how to make pull request hahaha _

`if (!localPlayer || !localPlayer->isAlive())
        return;

    if (config->visuals.trans3rd && std::strstr(modelName, "models/player"))
    {
        interfaces->renderView->setBlend(localPlayer->isScoped() ? 0.5f : 1.f);
    }`

make a function then call it on drawmodelexecute ( hooks.php )

**Comment by newcommerdontblame** [comment]
Make sliderint for transparancy

**Comment by newcommerdontblame** [comment]
Also https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/creating-an-issue-or-pull-request
