### ISSUE TITLE
[REQUEST] Lobby messages

### ISSUE THREAD

**Issue by vladimirdabic** [danielkrupinski/Osiris#2179]
Is it still possible to fake lobby messages and if so is there any chance of it being added?

**Comment by unnamed01X** [comment]
fake lobby messages / notifications for trolling are still alive. You can find them in lua codes, there's a still working lua with that, in skeet

**Comment by vladimirdabic** [comment]
Yeah I know but it would be really nice to have it in here too.

**Comment by NekoRem** [comment]
> Yeah I know but it would be really nice to have it in here too.

So get the lua and convert it

**Comment by vladimirdabic** [comment]
I don't know how to make cheats, and I'm not very good at C++.

**Comment by JacksonDon** [comment]
I has this few months and its cool, it take 10 mins to add it and rechange the code.

**Comment by NekoRem** [comment]
> I don't know how to make cheats, and I'm not very good at C++.

I don't think you should be here then

**Comment by vladimirdabic** [comment]
> > I don't know how to make cheats, and I'm not very good at C++.
> 
> I don't think you should be here then

That's a bit rude isn't it?
I don't work with C++. I just made a request. I work in other languages.

**Comment by NekoRem** [comment]
> > > I don't know how to make cheats, and I'm not very good at C++.
> > 
> > 
> > I don't think you should be here then
> 
> That's a bit rude isn't it?
> I don't work with C++. I just made a request. I work in other languages.

it may be a bit rude but its true! You have dove head first into something where you very clearly lack experience and without research or intelligence I guarantee you will fail every single time. try learncpp.com

**Comment by vladimirdabic** [comment]
> > > > I don't know how to make cheats, and I'm not very good at C++.
> > > 
> > > 
> > > I don't think you should be here then
> > 
> > 
> > That's a bit rude isn't it?
> > I don't work with C++. I just made a request. I work in other languages.
> 
> It may be a bit rude but its true! You have dove head first into something where you very clearly lack experience and without research or intelligence I guarantee you will fail every single time. Try learncpp.com

You're still being rude. I didn't say I don't know C++ at all.
And guaranteeing I will fail every single time I try something new is a very very false statement.
You're clearly begin very rude here. If you tried something new and someone told you to f*** off like you're doing right now you probably wouldn't like it either.

**Comment by vladimirdabic** [comment]
Imagine your sport coach telling you the first day you won't make it because you have no experience in this sport.

**Comment by vladimirdabic** [comment]
I'm sorry for overreacting but I do find this very rude and it makes me feel sad for something I shouldn't feel sad.

**Comment by vladimirdabic** [comment]
Let's just pretend this never happend...

**Comment by NekoRem** [comment]
lets pretend you never happened

**Comment by vladimirdabic** [comment]
It's easy to be a dick on the internet isn't it?
