### ISSUE TITLE
CONFIG ENCRYPTION

### ISSUE THREAD

**Issue by PUREHAX** [danielkrupinski/Osiris#218]
Hey, can you remove the encrypion of the configs ? its pretty annoying

**Comment by cojo1989** [comment]
If you dont want to have problems, update the source manualy. And you will not have any problems with the config.

**Comment by danielkrupinski** [comment]
They are not encrypted, just saved in binary form. You can edit config file using hex editor.

**Comment by cojo1989** [comment]
@danielkrupinski For me it`s working fine now. No problems between config versions. But i updated the source manualy.

**Comment by PUREHAX** [comment]
Why don't you use a normal Txt file ? Like the config from Smefs Indigo ?

AIMBOT_ENABLED = 1
AIMBOT_SMOOTH = 5
...
ESP_ENABLED = 1

and so on.

Wouldn't this be much easier ?

**Comment by cojo1989** [comment]
Because is better this way. ;) nobody complain.
