### ISSUE TITLE
D3D9X Img Support

### ISSUE THREAD

**Issue by DoctorYasin** [danielkrupinski/Osiris#2180]
I am having a problem when I try to add the byte file I translated from the image to the menu.

Codes;
```
IDirect3DTexture9* Aim = nullptr;
if (Aim == nullptr)D3DXCreateTextureFromFileInMemoryEx(g_D3DDevice9, &Aim, sizeof(Aim), 50, 50, D3DX_DEFAULT, 0, D3DFMT_UNKNOWN, D3DPOOL_MANAGED, D3DX_DEFAULT, D3DX_DEFAULT, 0, NULL, NULL, &Aim);
```
Error;
**device or g_D3DDevice9 or pDevice**
I tried adding d3d9x support from other hacks to advertise the two files but unfortunately current osiris does not accept it.

I convert the byte and add it as a header file, but in no way can I add it to the menu. As there is no d3d9x support.

The program I use: (aByte) = https://yadi.sk/d/TepcB2is3NCFcj
Virus Total : https://www.virustotal.com/gui/file/4aa2d0d6a0f2c8c6ca4e9323f4c156c34fff6a7f26f4e4180e4f7ba235574d21/detection

**Comment by DoctorYasin** [comment]
Virus Total : https://www.virustotal.com/gui/file/4aa2d0d6a0f2c8c6ca4e9323f4c156c34fff6a7f26f4e4180e4f7ba235574d21/detection

**Comment by 3Ld4D** [comment]
u need directx sdk for that

**Comment by DoctorYasin** [comment]
> u need directx sdk for that

I downloaded SDK 2010. I made the connections.
Osiris is missing some codes to insert the d3d9x image.

**Comment by DoctorYasin** [comment]
I tried pulling the indigo and gladiator d3d9x codes but I can't set the hook and memory to osiris at all.

**Comment by NekoRem** [comment]
take a look at this #1842

**Comment by DoctorYasin** [comment]
> take a look at this #1842

Crashing CSGO

ImGui::ImageButtonWithText(Aim, "Aim" ImVec2(100, 100)))

**My Modified ImageButtonWithText Button**

**imgui.h**

`    IMGUI_API bool			ImageButtonWithText(ImTextureID texId, const char* label, const ImVec2& imageSize = ImVec2(0, 0), const ImVec2& uv0 = ImVec2(0, 0), const ImVec2& uv1 = ImVec2(1, 1), int frame_padding = -1, const ImVec4& bg_col = ImVec4(0, 0, 0, 0), const ImVec4& tint_col = ImVec4(1, 1, 1, 1));`


**imgui_widgets.h**

```
bool ImGui::ImageButtonWithText(ImTextureID texId, const char* label, const ImVec2& imageSize, const ImVec2& uv0, const ImVec2& uv1, int frame_padding, const ImVec4& bg_col, const ImVec4& tint_col) {
    ImGuiWindow* window = GetCurrentWindow();
    if (window->SkipItems)
        return false;

    ImVec2 size = imageSize;
    if (size.x <= 0 && size.y <= 0) { size.x = size.y = ImGui::GetTextLineHeightWithSpacing(); }
    else {
        if (size.x <= 0)          size.x = size.y;
        else if (size.y <= 0)     size.y = size.x;
        size *= window->FontWindowScale * ImGui::GetIO().FontGlobalScale;
    }

    ImGuiContext& g = *GImGui;
    const ImGuiStyle& style = g.Style;

    const ImGuiID id = window->GetID(label);
    const ImVec2 textSize = ImGui::CalcTextSize(label, NULL, true);
    const bool hasText = textSize.x > 0;

    const float innerSpacing = hasText ? ((frame_padding >= 0) ? (float)frame_padding : (style.ItemInnerSpacing.x)) : 0.f;
    const ImVec2 padding = (frame_padding >= 0) ? ImVec2((float)frame_padding, (float)frame_padding) : style.FramePadding;
    const ImVec2 totalSizeWithoutPadding(size.x + innerSpacing + textSize.x, size.y > textSize.y ? size.y : textSize.y);
    const ImRect bb(window->DC.CursorPos, window->DC.CursorPos + totalSizeWithoutPadding + padding * 2);
    ImVec2 start(0, 0);
    start = window->DC.CursorPos + padding; if (size.y < textSize.y) start.y += (textSize.y - size.y) * .5f;
    const ImRect image_bb(start, start + size);
    start = window->DC.CursorPos + padding; start.x += size.x + innerSpacing; if (size.y > textSize.y) start.y += (size.y - textSize.y) * .5f;
    ItemSize(bb);
    if (!ImGui::ItemAdd(bb, id))
        return false;

    bool hovered = false, held = false;
    bool pressed = ButtonBehavior(bb, id, &hovered, &held);

    // Render
    const ImU32 col = GetColorU32((hovered && held) ? ImGuiCol_ButtonActive : hovered ? ImGuiCol_ButtonHovered : ImGuiCol_Button);
    RenderFrame(bb.Min, bb.Max, col, true, ImClamp((float)ImMin(padding.x, padding.y), 0.0f, style.FrameRounding));
    if (bg_col.w > 0.0f)
        window->DrawList->AddRectFilled(image_bb.Min, image_bb.Max, GetColorU32(bg_col));

    window->DrawList->AddImage(texId, image_bb.Min, image_bb.Max, uv0, uv1, GetColorU32(tint_col));

    if (textSize.x > 0) ImGui::RenderText(start, label);
    return pressed;
}
```

**Comment by NekoRem** [comment]
> i available my problem.
> 
> tImage = D3DXCreateTextureFromFileInMemory(device, &My_Image_Bytes, sizeof(My_Image_Bytes), &my_texture);
> 
> how can i adjust the size of this?

You set the image size when using ImGui::Image

**Comment by DoctorYasin** [comment]
> > i available my problem.
> > tImage = D3DXCreateTextureFromFileInMemory(device, &My_Image_Bytes, sizeof(My_Image_Bytes), &my_texture);
> > how can i adjust the size of this?
> 
> You set the image size when using ImGui::Image

https://imgur.com/P6tkevq

I can never get rid of the download button.

```
Logo = D3DXCreateTextureFromFileInMemoryEx(device, &Logom2, sizeof(Logom2), 50, 50, D3DX_DEFAULT, 0, D3DFMT_UNKNOWN, D3DPOOL_DEFAULT, D3DX_DEFAULT, D3DX_DEFAULT, 0, NULL, NULL, &Logox);
ImGui::Image(Logox, ImVec2(50, 50));
```

**Comment by NekoRem** [comment]
> > > i available my problem.
> 
> > > tImage = D3DXCreateTextureFromFileInMemory(device, &My_Image_Bytes, sizeof(My_Image_Bytes), &my_texture);
> 
> > > how can i adjust the size of this?
> 
> > 
> 
> > You set the image size when using ImGui::Image
> 
> 
> 
> https://imgur.com/P6tkevq
> 
> 
> 
> I can never get rid of the download button.
> 
> 
> 
> ```
> 
> Logo = D3DXCreateTextureFromFileInMemoryEx(device, &Logom2, sizeof(Logom2), 50, 50, D3DX_DEFAULT, 0, D3DFMT_UNKNOWN, D3DPOOL_DEFAULT, D3DX_DEFAULT, D3DX_DEFAULT, 0, NULL, NULL, &Logox);
> 
> ImGui::Image(Logox, ImVec2(50, 50));
> 
> ```
> 
> 

You need a better translator

**Comment by techzin** [comment]
see my pull request in https://github.com/danielkrupinski/Osiris/pull/1842

**Comment by DoctorYasin** [comment]
> see my pull request in #1842
> 
> Edit your Hooks.cpp
> and your GUI.h and GUI.cpp
> 
> in my pull request you see this code.

There is an extreme fps drop on a 100x50 logo.
Since the pictures are not clear, I updated the code as follows.
Logo = D3DXCreateTextureFromFileInMemoryEx(device, &Logom, sizeof(Logom), 100, 50, D3DX_DEFAULT, 0, D3DFMT_UNKNOWN, D3DPOOL_DEFAULT, D3DX_DEFAULT, D3DX_DEFAULT, 0, NULL, NULL, &Logox);

But I still have one more problem to add each img;

HRESULT Logo = NULL;
LPDIRECT3DTEXTURE9 Logox = NULL;

When you create these new codes, the fps completely drops to 20.

**Comment by 3Ld4D** [comment]
you are supposed to make it static and do it at init (look where font is done), otherwise it loads the image every frame.

**Comment by DoctorYasin** [comment]
> you are supposed to make it static and do it at init (look where font is done), otherwise it loads the image every frame.

I do not know how to do it.

-
https://imgur.com/HZjOso1

I'm thinking of doing something like this.
