### ISSUE TITLE
[REQUEST] velocity old

### ISSUE THREAD

**Issue by kenedy3** [danielkrupinski/Osiris#2181]
currently I only have the velocity in my cheat, but I wanted that when I landed on the ground my speed appears on the velocity side between ()

example: 
![old](https://user-images.githubusercontent.com/70678207/93021539-fce5b200-f597-11ea-9a90-b6680fb55625.PNG)

**Comment by koon666** [comment]
pass me ur discord

**Comment by kenedy3** [comment]
kenedy#8441

**Comment by JacksonDon** [comment]
save that value when ur on ground 
and show it up

**Comment by braken1** [comment]
@koon666 if you have it can u send pls? :(      braken#0133

**Comment by kenedy3** [comment]
@JacksonDon how? im new on c++ o_0

**Comment by blxckshark** [comment]
> @JacksonDon how? im new on c++ o_0

example: 
`auto velocity = player->velocity().length2D() + 0.5;
interfaces.surface->printText(std::to_wstring(velocity));`
