### ISSUE TITLE
After Injecting CSGO breaks.

### ISSUE THREAD

**Issue by soomX** [danielkrupinski/Osiris#2183]
After one time injecting with a brand new osiris NOTHING CHANGED, I normally close the game open it and inject.... nothing. Ok. SO I try another injector... nothing. I try a different cheat, nothing. Osiris broke my csgo. This happened before my only solution was resetting MY WHOLE PC

**Comment by DoctorYasin** [comment]
Change injector, Verify CSGO Files.

**Comment by soomX** [comment]
Have tried.

**Comment by DoctorYasin** [comment]
delete the osiris folder from the documents.
