### ISSUE TITLE
[REQUEST] add delay before shoot for aimbot

### ISSUE THREAD

**Issue by ramboi234** [danielkrupinski/Osiris#2184]
this cheat so amazing best free cheat I ever use 1000x better than aimware, but if we can add a delay before we shoot(aimbot on -> delay/wait -> shoot/fire) this cheat will be perfect, because when I use deaggle I need to set smooth to 1 and that kinda obv

**Comment by newcommerdontblame** [comment]
Add urself #2097

**Comment by ramboi234** [comment]
may you help me I cant make it work,still no delay, I didn't know much c++ , for example for shot function I assume md->buttons |= UserCmd::IN_ATTACK; is func to shot and  cmd->buttons &= ~UserCmd::IN_ATTACK; prevent to shot , IDK maybe Im wrong , because when I use cmd->buttons &= ~UserCmd::IN_ATTACK I cant shot,

 float delayshot{ 0.0f };

 ImGui::SliderFloat("Shot Delay", &config->aimbot[currentWeapon].delayshot, 0.0f, 10.0f, "%.1f ms");

aimbot.cpp

 if (bestTarget.notNull()) {
            static DWORD delay = GetTickCount();
         
            if (GetTickCount() - delay > config->aimbot[weaponIndex].delayshot * 100)
            {
                cmd->buttons |= UserCmd::IN_ATTACK;
                delay = GetTickCount();
            }




//or maybe I shouldn't place the code inside 
 if (bestTarget.notNull()) { 
//delay 
}
???

sc: https://www.unknowncheats.me/forum/2455881-post3.html
