### ISSUE TITLE
[REQUEST] Bullet Tracers

### ISSUE THREAD

**Issue by zeshable** [danielkrupinski/Osiris#2186]
Title says it all!

**Comment by SwagsRGB** [comment]
+1 would be nice

**Comment by newcommerdontblame** [comment]
Just paste from #2074

**Comment by zeshable** [comment]
@newcommerdontblame Can you expain how I would paste from #2074? Thanks.

**Comment by DoomFishWasTaken** [comment]
@zeshable how about:
1. ctrl + f
2. type in "beams"
3. take a look at the code
4. profit???

**Comment by zeshable** [comment]
@DoomFishWasTaken Where is the code and how do I paste it into the cheat

**Comment by DoomFishWasTaken** [comment]
> @DoomFishWasTaken Where is the code and how do I paste it into the cheat

#1546 #2074

**Comment by zeshable** [comment]
@DoomFishWasTaken Sorry about all the questions, but I do not see any sort to of code on the pages you sent me. And how would I paste the code into the cheat?

**Comment by sserve-kr** [comment]
I'll make a pull request for bullet tracer as soon as possible.

**Comment by aljawary** [comment]
> I'll make a pull request for bullet tracer as soon as possible.
Can u implement this blockbot into osiris?
https://www.unknowncheats.me/forum/counterstrike-global-offensive/352947-crosshair-blockbot.html

**Comment by aljawary** [comment]
> I'll make a pull request for bullet tracer as soon as possible.

Can u implement this blockbot into osiris?
https://www.unknowncheats.me/forum/counterstrike-global-offensive/352947-crosshair-blockbot.html

**Comment by zeshable** [comment]
Nevermind, I got the tracers to work!
Thanks.

**Comment by danielkrupinski** [comment]
Added.
