### ISSUE TITLE
[QUESTION] anyone know where the full panorama.h/UIPanel class can be found

### ISSUE THREAD

**Issue by poopings** [danielkrupinski/Osiris#2189]
title

**Comment by Scui1** [comment]
This part of panorama isn't open source.

**Comment by danielkrupinski** [comment]
You can look at [Fuzion's IUIPanel class](https://github.com/LWSS/Fuzion/blob/1e2b66d4afe7bd827af4734b283b7d5ee6fed0cf/src/SDK/panorama/IUIPanel.h#L26) but it doesn't include all methods. DOTA2 linux binaries with symbols can be helpful in reverse engineering UIPanel but they differ from CS:GO ones.
