### ISSUE TITLE
Path to Utils.h

### ISSUE THREAD

**Issue by cojo1989** [danielkrupinski/Osiris#219]
#include "Utils.h" should be "SDK/Utils.h" in file "GameEventManager.h" or something like that. Otherwise error while you are compileing. 

@danielkrupinski

**Comment by effex1337** [comment]
Hec?

**Comment by cojo1989** [comment]
@effex1337 check GameEventManager.h you will see what i`m speaking about. Path for included Utils.h it`s not completed. :D

**Comment by NexSqaud** [comment]
GameEventManager.h located at same folder with Utils.h
