### ISSUE TITLE
Legit AA

### ISSUE THREAD

**Issue by soomX** [danielkrupinski/Osiris#2190]
Antiaim is not working, any solutions?

**Comment by sserve-kr** [comment]
1. set chocked packet to 1, do not bind key
2. check movement fix in misc tab
If you want to see how it is working, you should add legit aa charm

**Comment by soomX** [comment]
Any example of legit aa charms? Also i can't see my own anti aim, is that normal? Others can

**Comment by sserve-kr** [comment]
Yes, you can't see legit anti aim without aa charm.

**Comment by yaelahrip** [comment]
@sserve-kr any idea? every legit play  still can hit  my head. even when  im using aa
legit

**Comment by sserve-kr** [comment]
I don't use legit aa anymore, so i cant help you.
Sorry.

**Comment by debruh** [comment]
Osiris doesn't even have legit AA what are you talking about?

**Comment by BaiAlbert** [comment]
osiris aa sucks, dont use it
