### ISSUE TITLE
Please add Silent and Aimlock draw FOV or update the pull request

### ISSUE THREAD

**Issue by Deciy** [danielkrupinski/Osiris#2191]
You literally can't use the pull request cause its so out of date

**Comment by newcommerdontblame** [comment]
What

**Comment by Deciy** [comment]
My bad I messed the title up

**Comment by Deciy** [comment]
Many cheats have it so you can see the FOV of the legitbot. Currently, Osiris doesn't have one. There is the pull request for fov draw but is out of date and you cant change the code anymore because its changed so much. If anyone still needs clarification pls lmk im bad at english

**Comment by newcommerdontblame** [comment]
Here is for ya must be working 
aimlock green silent red 
call it paint traverse in hooks.cpp)

``
void Misc::drawFov() noexcept
{
    auto local = localPlayer.get();
    if (config->misc.drawFov)
    {
        if (!local || !local->isAlive()) return;
        int weaponId = getWeaponIndex(localPlayer->getActiveWeapon()->itemDefinitionIndex2());
        if (!config->aimbot[weaponId].enabled) weaponId = 0;
        if (!config->aimbot[weaponId].enabled) return;
        auto screenSize = interfaces->surface->getScreenSize();
        if (config->aimbot[weaponId].silent) interfaces->surface->setDrawColor(255, 10, 10, 255);
        else interfaces->surface->setDrawColor(10, 255, 10, 255);
        float radius = std::tan(degreesToRadians(config->aimbot[weaponId].fov) / 2.f) / std::tan(degreesToRadians(local->isScoped() ? local->fov() : (105 + config->visuals.fov)) / 2.f) * screenSize.first;
        interfaces->surface->drawOutlinedCircle(screenSize.first / 2, screenSize.second / 2, radius, 100);
    }

}
``

**Comment by Deciy** [comment]
thx bae
