### ISSUE TITLE
ESP text becomes smaller and ureadable once ESP font is changed

### ISSUE THREAD

**Issue by SwagsRGB** [danielkrupinski/Osiris#2196]
The ESP when kept at default works fine but once I try to change the font, ESP txt becomes small and unreadable. Even when I switch back to default font it stays that way and is forever stuck to that config even after restart. Images attached:
Normal ESP text:
![Screenshot (49)](https://user-images.githubusercontent.com/69312785/93694264-45b4e200-fb27-11ea-9b4c-abfcceec522e.png)

When Font is changed:
![Screenshot (50)](https://user-images.githubusercontent.com/69312785/93694279-62e9b080-fb27-11ea-9152-8057d300e703.png)

**Comment by SwagsRGB** [comment]
I play at 4:3 resolution if that helps

**Comment by RyDeem** [comment]
This is true, on 1080p even the text is too small, Requesting a Font size option in ESP
