### ISSUE TITLE
(Request)play different killsound if its headshot

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#2198]
Like the title says 
guess its easy to make and better

**Comment by newcommerdontblame** [comment]
S

**Comment by BaiAlbert** [comment]
Just use the event listener is used in preserve kill when headshots, and paste hitsound but with the headshot event listener.

**Comment by newcommerdontblame** [comment]
> Just use the event listener is used in preserve kill when headshots, and paste hitsound but with the headshot event listener.

Yea i did xd forgot to close
