### ISSUE TITLE
Rage

### ISSUE THREAD

**Issue by rohan-patra** [danielkrupinski/Osiris#220]
please add an hvh/rage bot

**Comment by cojo1989** [comment]
I would like it. But im not a fan of it. But for boring its good or if somebody f*ck with you :)

**Comment by cojo1989** [comment]
But i think will be best after Daniel finish legit. What i would like to get fix for legit is to max the fov at 30 or something and to fix that RCS. RCS is shitty... in rest its perfect.

**Comment by Asado-san** [comment]
> please add an hvh/rage bot

go search deadcell.cc on Github. or just use EZ Fragz Rage Hack 

also, PPL in this GIT is not interested in HVH & Rage Hack. so Get the hell outta here now !

**Comment by effex1337** [comment]
Yeah the cheat is a really good legit cheat.
