### ISSUE TITLE
[REQUEST] Velocity graph, eb and jb indicators

### ISSUE THREAD

**Issue by SapphireCodenz** [danielkrupinski/Osiris#2200]
and uh a speed graph that shows when you're losing/gaining speed

**Comment by newcommerdontblame** [comment]
Is there even edgebug or jumpbug here lol

**Comment by koon666** [comment]
> and uh a speed graph that shows when you're losing/gaining speed

pass me ur discord

**Comment by SapphireCodenz** [comment]
> > and uh a speed graph that shows when you're losing/gaining speed
> 
> pass me ur discord

sapphire#2912

**Comment by joshuaisafemboy** [comment]
> > > and uh a speed graph that shows when you're losing/gaining speed
> > 
> > 
> > pass me ur discord
> 
> sapphire#2912

lmao hi sapphire

**Comment by asu29** [comment]
> > and uh a speed graph that shows when you're losing/gaining speed
> 
> pass me ur discord

can you add me too 
asu#4756

**Comment by newcommerdontblame** [comment]
itscraused#5786

**Comment by joshuaisafemboy** [comment]
> > and uh a speed graph that shows when you're losing/gaining speed
> 
> pass me ur discord

hey, whats ur discord i need some help
