### ISSUE TITLE
[REQUEST] Disable bt chams when player is standing still

### ISSUE THREAD

**Issue by SapphireCodenz** [danielkrupinski/Osiris#2201]
title ^^

**Comment by HowToMakeFaceitAB** [comment]
you mean when velocity is 0?

**Comment by HowToMakeFaceitAB** [comment]
its easy, all you have to do is add a check in the tab (or do it automatically) , check if velocity = 0 if yes, then disable backtrack chams, ORRRRRRR instead, make it so that the backtrack chams isnt layered which could fix ur problem easily

**Comment by yaelahrip** [comment]
hahahha funny  af

**Comment by yaelahrip** [comment]
loop try maxentity
and check the entity velocity < 20 then return;

**Comment by synvy** [comment]
Then create a velocity check?

Seriously, people, this shit isn't hard at **_all_**.

Pseudo:
```
if (m_vecVelocity().2d >= 0.1f) {
    // chams
}
```

**Comment by yaelahrip** [comment]
@synvy yea ikr .
