### ISSUE TITLE
[REQUEST] Quick stop when shooting, share codes

### ISSUE THREAD

**Issue by thisisprettyepic** [danielkrupinski/Osiris#2202]
Config system share codes so you can copy a share code and paste it to your friend and they’ll be able to use your config right away instead of putting it in a specific folder (this exists in cheats such as rainbow****). Quick stop everytime you shoot for more accuracy.

**Comment by DoctorYasin** [comment]
You probably made a mistake in the config section. If you share the code, we can check it.

**Comment by ny-4** [comment]
sharecodes wouldnt work. You can copy and paste the whole cfg as a text file if you want that lmao.
actually yeah that might be a better idea since we dont have cloud configs.

Import / Export to/from clipboard????
