### ISSUE TITLE
Imgui language problem.

### ISSUE THREAD

**Issue by DoctorYasin** [danielkrupinski/Osiris#2204]
![skin](https://user-images.githubusercontent.com/49906809/94349908-d3c22880-0051-11eb-9384-e2d26b7671df.PNG)
![menu](https://user-images.githubusercontent.com/49906809/94349911-d4f35580-0051-11eb-8070-58470be57405.PNG)

While Turkish language is working in skinchanger area, Turkish language is broken in normal imgui area. osiris was fine until 5 update. I then downloaded the version and updated it again, but the error still persists.

I am using the d3d9x startdevice feature.

**Comment by DoctorYasin** [comment]
Although I close the next column, after selecting the skin, the paint kit area automatically shrinks.

and I think we need to separate knife skins like gloves.

It may be more ideal if we collect gloves and knives in one menu.

**Comment by danielkrupinski** [comment]
Imgui requires strings to be utf-8 encoded.

**Comment by DoctorYasin** [comment]
@danielkrupinski 
The current osiris started giving imgui language error after 5-6 updates.
It gives an error when I add the u8 suffix to the beginning

![menu](https://user-images.githubusercontent.com/49906809/94361012-03a51680-00ba-11eb-85be-9b9a9f12d10e.PNG)

**Comment by newcommerdontblame** [comment]
Kanka neden türkçe yapıyosun ki gereksiz uğraş değil mi

**Comment by DoctorYasin** [comment]
> Kanka neden türkçe yapıyosun ki gereksiz uğraş değil mi

I use multiple languages.
1-English 2-Turkish 3-Russian 4-Arabic

**Comment by danielkrupinski** [comment]
Use **u8** string literal and cast to **const char***.
