### ISSUE TITLE
[REQUEST] See the enemy team chat (dead & alive)

### ISSUE THREAD

**Issue by llDoomSlayerll** [danielkrupinski/Osiris#2209]
IT would be really useful to track the people who accuses you of cheats or know who is being suspicious at you

**Comment by Shuvi-Moro** [comment]
an interesting idea, but I don't think this is possible, since the information about this chat itself may not come from the server

**Comment by Shuvi-Moro** [comment]
> an interesting idea, but I don't think this is possible, since the information about this chat itself may not come from the server

I mean competitive mode

**Comment by llDoomSlayerll** [comment]
Yes, it would really useful, to blacklist someone with the cheat

**Comment by newcommerdontblame** [comment]
> IT would be really useful to track the people who accuses you of cheats or know who is being suspicious at you

It makes no sense

**Comment by tirziz** [comment]
I don't think there is a way to recive this from the server yet.

**Comment by Allerek** [comment]
Prob the server, doesnt send enemy chat to your game at all, it only send your own team chat to your game, so its not possible to check what they are saying to each other.
