### ISSUE TITLE
Skin converter cannot be saved.

### ISSUE THREAD

**Issue by HeiDaShuai666** [danielkrupinski/Osiris#221]
Skin converter cannot be saved.
When I selected several skins, I restarted the game. After loading, the selected skin disappeared.

**Comment by HeiDaShuai666** [comment]
But the configuration of Aimbot, Triggerbot, Backtrack, Glow, Chams and so on is not a problem.
Is that the only way my computer works?

**Comment by HeiDaShuai666** [comment]
The gun has too many skins, so it's difficult to choose. Can you add a sort or search?

**Comment by effex1337** [comment]
That's a problem listed to be fixed in the near future.
