### ISSUE TITLE
How to add pull request to your own Osiris cheat

### ISSUE THREAD

**Issue by phantomexile** [danielkrupinski/Osiris#2211]
as the title says

**Comment by newcommerdontblame** [comment]
1 Download Github Desktop.
2 download master branch of osiris (clone on main page/open in desktop x-github-client://openRepo/https://github.com/danielkrupinski/Osiris)
3 click "current branch" on top of the github desktop app
4 click "New branch" button on top next to search box
5 use upstream/master
6 then when its created go into "current branch" again but this time click on the bottom most button choose a branch to merge in to branch.
7 then select the pull request you want to merge.

**Comment by phantomexile** [comment]
i think you misunderstood my question, what i meant is a way to add other people pull request codes to my Osiris source
