### ISSUE TITLE
Cheat is Aimlocking enemy through smoke.

### ISSUE THREAD

**Issue by AbhinayNegi** [danielkrupinski/Osiris#2212]
I just encounter this yesterday that I  toggled my aimlock and what I see that cheat is aimlocking enemies through smoke even though I have checked the "Visible only" enemy option. And aimlock that I am using looks legit if there is no smoke but I have killed 3 people through smoke with headshot which is really fishy. Please fix this or If I making any mistake please help me.

**Comment by newcommerdontblame** [comment]
Just off ignore smoke

**Comment by AbhinayNegi** [comment]
> Just off ignore smoke

Where is this option, I dont see it in the Aimbot section.

**Comment by newcommerdontblame** [comment]
Look smoothly dude its in aimbot tab if u didint delete from ur source

**Comment by RyDeem** [comment]
tf

**Comment by BaiAlbert** [comment]
Disable "Ignore Smoke" under "Ignore flash"
