### ISSUE TITLE
Help with pull request

### ISSUE THREAD

**Issue by phantomexile** [danielkrupinski/Osiris#2216]
1 Download Github Desktop.
2 download master branch of osiris (clone on main page/open in desktop x-github-client://openRepo/https://github.com/danielkrupinski/Osiris)
3 click "current branch" on top of the github desktop app
4 click "New branch" button on top next to search box
5 use upstream/master
6 then when its created go into "current branch" again but this time click on the bottom most button choose a branch to merge in to branch.
7 then select the pull request you want to merge.

_Originally posted by @newcommerdontblame in https://github.com/danielkrupinski/Osiris/issues/2211#issuecomment-701312981_

can you be more specific? since there is no pull request available for me to merge. If you could please add me on Discord 999#2338

**Comment by iraizo** [comment]
You fork the repo, make changes to it and create a pull request, the people having access to the repo (write permissions) can merge it

**Comment by phantomexile** [comment]
> You fork the repo, make changes to it and create a pull request, the people having access to the repo (write permissions) can merge it

what i meant was a way to add pull requests features to my Osiris source without having to copy and paste the raw files and getting 100+ errors

**Comment by 0xE232FE** [comment]
@phantomexile 
This magic is called merge ;-)

**Comment by iraizo** [comment]
Merge the pr?

**Comment by phantomexile** [comment]
can you leave a clear instruction? i can't figure out a way to do it

**Comment by Gangster8192** [comment]
Literally the first result on google: https://stackoverflow.com/questions/36628859/git-how-to-merge-a-pull-request-into-a-fork

**Comment by newcommerdontblame** [comment]
Just take a look on git-desktop u can understand how it works easily
