### ISSUE TITLE
disconnected by vac | skinchanger problem

### ISSUE THREAD

**Issue by bootkitt** [danielkrupinski/Osiris#2217]
I think it's a problem from Skin Changer.
Because there are error codes such as bayonet.mdl files not found on the console, a solution should be found.
I am thrown in the middle of a competitive match.

Not only in bayonet, but in all other skins, red inscriptions appear because they could not be found on the console.

@danielkrupinski fix pls.

**Comment by DoctorYasin** [comment]
Not only in bayonet, but in all other skins, red inscriptions appear because they could not be found on the console.

**Comment by 3Ld4D** [comment]
that's not why you are getting disconnected.
also u get that error without skin changer with default knife.

**Comment by rishavmitra05** [comment]
U can try to verify yhe game files or reinstall the game

**Comment by rishavmitra05** [comment]
U can try to verify the game files or reinstall the game

**Comment by Frouk3** [comment]
Download vac bypass loader
