### ISSUE TITLE
Vector operator

### ISSUE THREAD

**Issue by yaelahrip** [danielkrupinski/Osiris#2219]
`entity->getCollideable()->obbMins() = backup.mins;

const Vector = Vector
binary '=': no operator found which takes a left-hand operand of type 'const Vector' (or there is no acceptable conversion)	`

Anyone  knows how to fix this operator Vector ?

**Comment by danielkrupinski** [comment]
You cannot assign to a variable by const reference. Change return type of `Collideable::obbmins()` to `Vector&` to make it assignable.
