### ISSUE TITLE
How can i change the watermark like other cheats have

### ISSUE THREAD

**Issue by gr1ndy** [danielkrupinski/Osiris#2220]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by newcommerdontblame** [comment]
I will add imgui watermark when its done it looks so basic rn

**Comment by newcommerdontblame** [comment]
I will add imgui watermark when its done it looks so basic rn 
work in progress..

**Comment by gr1ndy** [comment]
> I will add imgui watermark when its done it looks so basic rn
> work in progress..

thanks man, appreciate it

**Comment by gr1ndy** [comment]
> I will add imgui watermark when its done it looks so basic rn 
> work in progress..

any update?

**Comment by newcommerdontblame** [comment]
@gr1ndy send me ur discord

**Comment by gr1ndy** [comment]
> @gr1ndy send me ur discord

gr1ndy#7802
