### ISSUE TITLE
(Code help)drawing faded circle

### ISSUE THREAD

**Issue by newcommerdontblame** [danielkrupinski/Osiris#2222]
Most p2c has the dravfov and spread circle in misc  idk if its usefull but it looks cool feature i think so i made for osiris too in here #2218 (spread thing is WiP rn)
But its just simple circle i think it doesnt look that good im asking for how to made it look like fading thru crosshair 

![images (6)](https://user-images.githubusercontent.com/65455170/95025787-f1684100-0694-11eb-9e9d-5787d01d66de.jpeg)

I dont wanna use shitty png to do this so somene can help with code to improve pr

(@danielkrupinski hope u take a look tho:))

**Comment by ny-4** [comment]
[Relevant UnknownCheats Post](https://www.unknowncheats.me/forum/counterstrike-global-offensive/288729-esoteriks-spread-circle-surface.html)

**Comment by newcommerdontblame** [comment]
> [Relevant UnknownCheats Post](https://www.unknowncheats.me/forum/counterstrike-global-offensive/288729-esoteriks-spread-circle-surface.html)
> edit: ofc this is in ISurface, but the math in [this](https://www.unknowncheats.me/forum/2167860-post6.html) post may prove useful.

I couldnt make it work....ffs
