### ISSUE TITLE
Disconnected By VAC, Unable to play any Competitive Match

### ISSUE THREAD

**Issue by DrZeldaGlitch** [danielkrupinski/Osiris#2223]
Hi there, I am always getting disconnected by VAC saying there is 3rd-Party Software Running or i cant sustain a stable connection to VAC or some software is blocking VAC, i tried changing the code of Osiris, didnt work, tried uninstalling all possible Applications that could interfere with VAC, didnt work, tried turning off my Firewall, still **didnt** **work.**

This only Applies to Competitive, Wingman wasn't tested, I tested this is Deathmatch and had no problems whatsoever
Even happens when i dont have anything running, Yes my Internet Connection is 100Mbps, stable enough, i always Verify Integrity of Game Files and there is always **1 or more Files** that are faulty, even the VAC-Clear Batch i downloaded doesnt help.

Running "ipconfig /flushdns" in CMD also doesnt help.

I reinstalled CSGO but cant test it for now because i got a 24hr Competitive Cooldown.

And if i were to test it, i would probably get kicked again and get an 7 day Competitive Cooldown which i really dont want.

I already have a 24hr Competitive Cooldown because of this, and **NO** i am **NOT** blaming Osiris **NEITHER** danielkrupinski, its just VAC being salty af.

@danielkrupinski is there anything else i could do?

Regards, DZG

**Comment by Gangster8192** [comment]
Use the vac-bypass-loader, https://github.com/danielkrupinski/VAC-Bypass-Loader.

**Comment by Jayderp** [comment]
Happens with every cheat, unfortunately.
VAC is a pain in the ass, and competitive cooldowns stack hard AF.
Here's a graph of cooldowns:
![image](https://user-images.githubusercontent.com/49515406/95050108-80ce2c80-0747-11eb-95e6-d10a55f830f2.png)
Pain in the dilders.

Anyway, just relog Steam and you should be sweet.
