### ISSUE TITLE
Any way to change the imgui?

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#2224]
im trying to change the imgui to a skeet imgui for fun. any way?

**Comment by KernCS** [comment]
yes

**Comment by JacksonDon** [comment]
i will make it for cash.

**Comment by g1gantino** [comment]
No, it's not possible. Actually very impossible.

**Comment by Curiouss312** [comment]
its impossible dude the imgui is literally THe MOsT dIFFiCUlT gUI
