### ISSUE TITLE
(suggestion) Add customizable yaw + antiaim preview

### ISSUE THREAD

**Issue by Jayderp** [danielkrupinski/Osiris#2225]
Salutations and greetings, I am suggesting an addition to the Osiris client that adds a customizable yaw value (rotation around Y axis).
So far, the only customizable thing is your pitch (rotation around Z axis).

Maybe something like this:
![image](https://user-images.githubusercontent.com/49515406/95060526-dd851380-0756-11eb-9b64-7f92ecb4e6a9.png)

For antiaim preview, all I mean is what you see in third person is what other people see.
So if your pitch is -90 (looking down), then in third person you should see yourself looking down.
Currently, you see yourself normally, and others see your real rotation.

Thanks!

**Comment by DoomFishWasTaken** [comment]
Take a look at pull requests (to start with: #2074, #1546 and #1819)

**Comment by newcommerdontblame** [comment]
I dont think u want rage aimbot so just take a look 

#2065 simple sway legit aa 
#1819 paste desync chams and simple animfix

Dont use memey fakewalk things :))
