### ISSUE TITLE
Osiris-master\Osiris\SDK\Utils.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file SDK\GlobalVars.cpp)

### ISSUE THREAD

**Issue by NightFuryPrime** [danielkrupinski/Osiris#2226]
Hello guys,

During build up phase, this message shows up, can anyone check if everything is in place and nothing is missing in the repository?

Thank you

**Comment by Ni1kko** [comment]
https://github.com/danielkrupinski/Osiris/commit/61eedf88625cc1942474db65fa3dca0c231fb349
