### ISSUE TITLE
If you follow the build instructions you cannot start the cheat

### ISSUE THREAD

**Issue by Ferryistaken** [danielkrupinski/Osiris#2227]
If you follow the instructions in the readme(open in vs, change to release x86, inject the dll) nothing happens. If you press insert nothing pops up, but if I use process hacker 2 to search for modules the module is loaded. Tried with xenos injector and process hacker 2

**Comment by newcommerdontblame** [comment]
use this injector maded for osiris
https://github.com/AMATEURZ1337/load-lib-injector 
change ur dll name to cheat.dll and run the injector as administrator mode 
also make sure both files at same location

**Comment by Ferryistaken** [comment]
Thanks that worked. You might want to add that in the readme or in other writeups
