### ISSUE TITLE
Fuck pasting the rage/multipaste thing

### ISSUE THREAD

**Issue by Deciy** [danielkrupinski/Osiris#2228]
PASTE IT FOR ME AND SEND IT TOO ME Yodawg#0420
(This is half a joke but I mean if you are really down to send it go ahead ;)    )
#2074

**Comment by Khajiitos** [comment]
pretty sure you can do `git clone https://github.com/lofcz/Osiris.git`

**Comment by Deciy** [comment]
wait you mean I don't have to copy and paste everything
I am not big brain

**Comment by Deciy** [comment]
fatal: destination path 'Osiris' already exists and is not an empty directory.

**Comment by Deciy** [comment]
@Khajiitos

**Comment by Khajiitos** [comment]
or you can download the source https://github.com/lofcz/Osiris/archive/master.zip

**Comment by Deciy** [comment]
Can you explain how you did this? I'm small brain and new please eggsplain

**Comment by Khajiitos** [comment]
Can't tell if you're joking or not, but I suspect that you downloaded the source code of osiris as a zip, and you open the project using the sln file, with the link I gave you you download the source code of the fork which you don't have to do edit anymore, and you just open the sln file in it in vs and compile like usual

**Comment by Deciy** [comment]
It didn't work in the past for me and it isn't working now.

**Comment by Deciy** [comment]
Sorry for the trouble I just realized that I'm dumb. But if I want multiple features say, b-hop hitchance and draw FOV is there anyway to combine the two? Or would I have to do that manually?
