### ISSUE TITLE
The cheat is totally broken

### ISSUE THREAD

**Issue by thoma202411** [danielkrupinski/Osiris#223]
1.loaded cfg in lobby crash when join in game
2.In game insanely lagging like a power point cant even play 
3.Got kicked out of game b/o this:
![image](https://user-images.githubusercontent.com/41808115/58681016-52ed0280-831f-11e9-952e-084296e581b4.png)

**Comment by thoma202411** [comment]
I am pretty sure its not my problem i personally love this cheat and cheat makers,plz fix it tks a lot. And btw don't forget the skin cfg issue

**Comment by rohan-patra** [comment]
This is not broken it often happens when injecting dll into csgo just close csgo and verify game files then restart steam client ususally fixes problem for a week or so

**Comment by thoma202411** [comment]
> This is not broken it often happens when injecting dll into csgo just close csgo and verify game files then restart steam client ususally fixes problem for a week or so

that is one of the 3 issues that i faced

**Comment by thoma202411** [comment]
the lagging is the most annoying part

**Comment by travispresko** [comment]
it all happens in majority of csgo community as I have read in a reddit post

**Comment by cojo1989** [comment]
I dont have any problems like that. So its from your laptop/pc/game files/settings
