### ISSUE TITLE
Global Untrusted Cooldown

### ISSUE THREAD

**Issue by ny-4** [danielkrupinski/Osiris#2234]
hey yeah i know "dont cheat if u care about the account" yeh i get that.
just a word of warning to people, got my account permanently untrusted by using Osiris in dangerzone. I have no idea honestly what wouldve triggered an UT ban but heres my cfg if anyone wants to guess lol.

Was using vac-bypass-loader aswell as the new loadlib injector that daniel and hitchance or whoever was working on.
[rage.txt](https://github.com/danielkrupinski/Osiris/files/5337289/rage.txt)

**Comment by ny-4** [comment]
nevermind im dumb as fuck, sorry for unnecessary issue :)

**Comment by markito12** [comment]
what triggered your ban?
