### ISSUE TITLE
[REQUEST] velocity graph/line 

### ISSUE THREAD

**Issue by asu29** [danielkrupinski/Osiris#2235]
velocity/speed graph that shows your current speed 
![image](https://user-images.githubusercontent.com/70149482/95293223-32cb3d00-089d-11eb-8688-898d6073fccb.png)

**Comment by newcommerdontblame** [comment]
Im making both velocity pos done tho but need help on velocity graph 
if someone can help me for a few lines it could be done fast. Here is my discord itscraused#5786

**Comment by ny-4** [comment]
> Im making both velocity pos done tho but need help on velocity graph
> if someone can help me for a few lines it could be done fast. Here is my discord itscraused#5786

bruh just ImGui::Graph or some shit with a std::vector of floats, every frame remove front item from the vector, 
use smth like `std::rotate(velocities.begin(), velocities.begin() + 1, velocities.end());` to shift them over, then push_back the latest velocity value and draw it in a special imgui window with like `ImGuiWindowFlags_NoBackground | ImGuiWindowFlags_NoDecoration`

**Comment by asu29** [comment]
```
void Visuals::VelocityInfo()
{
    auto last_log = 0;

    if (!g_LocalPlayer || !g_LocalPlayer->IsAlive())
        return;

    if (!g_Options.velocity_info)
        return;

    int x, y;
    g_EngineClient->GetScreenSize(x, y);

    Vector vec = g_LocalPlayer->m_vecVelocity();
    float velocity = sqrt(vec[0] * vec[0] + vec[1] * vec[1]);
    bool in_air = g_LocalPlayer->m_fFlags() & IN_JUMP /*|| g_LocalPlayer->m_fFlags() & IN_SPEED*/;

    Render::Get().RenderText(std::to_string(round(velocity)), ImVec2(x / 2, y / 2 + 450), 4, Color(245, 245, 220, 255));
    Render::Get().RenderText("u/s", ImVec2(x / 2 + 1, y / 2 + 485), 2, Color(255, 255, 255, 255));

    Render::Get().RenderLine(x / 2 - 100, y / 2 + 325, x / 2 - 100, y / 2 + 445, Color(100, 100, 100, 125));
    Render::Get().RenderLine(x / 2 - 115, y / 2 + 430, x / 2 + 95, y / 2 + 430, Color(100, 100, 100, 125));

    if (g_GlobalVars->curtime - last_log > g_GlobalVars->interval_per_tick)
    {
        last_log = g_GlobalVars->curtime;

        velocity_data.unshift([velocity, in_air]);
    }

    if (velocity_data.length > 40)
        velocity_data.pop();

    for (auto i = 0; i < velocity_data.length - 1; i++)
    {
        auto cur = velocity_data[i][0];
        auto next = velocity_data[i + 1][0];
        auto landed = velocity_data[i][1] && !velocity_data[i + 1][1];

        Render::Get().RenderLine(x / 2 + 90 - (i - 1) * 5, y / 2 + 430 - (clamp(cur, 0, 450) * 75 / 320), x / 2 + 90 - i * 5, y / 2 + 130 - (clamp(next, 0, 450) * 75 / 320), Color(200,200,200,255));

        if (landed)
        {
            Render::Get().RenderLine(x / 2 + 90 - (i - 1) * 5, y / 2 + 430 - (clamp(cur, 0, 450) * 75 / 320), x / 2 + 90 - i * 5, y / 2 + 130 - (clamp(next, 0, 450) * 75 / 320), Color(200, 200, 200, 255));
            Render::Get().RenderText(std::to_string(round(next)), ImVec2(x / 2 + 100 - (i + 1) * 5, y / 2 + 415 - (clamp(next, 0, 450) * 75 / 320)), 3, Color(245, 245, 220, 255));
        }
    }
}
```

Someone has already posted this on yougame but I'm not sure how to get it to work. It's for csgosimple.

**Comment by newcommerdontblame** [comment]
@ny-4 @asu29 maybe u guys can fix my ugly as code velocity pos is working fine but graph drawimg as a straight line on top of screen

`
void Misc::velocityGraph() noexcept
{
    if (!config->misc.velocityGraph)
        return;

    if (interfaces->engine->isConnected() && !interfaces->engine->isInGame())
        if (!localPlayer || !localPlayer->isAlive()) return;

    float vel = localPlayer->velocity().length2D();
    std::wstring velwstr{ L"(" + std::to_wstring(static_cast<int>(vel)) + L")" };

    const auto [width, height] = interfaces->surface->getScreenSize();
    interfaces->surface->setTextColor(0, 255, 100, 255);
    interfaces->surface->setTextPosition(width / 0 - 4, height - 200);
    interfaces->surface->printText(velwstr);

    static int x1 = 400;
    static int y1 = -200;
    static int x2 = 800;
    static int y2 = (localPlayer->velocity().length2D());

    interfaces->surface->setDrawColor(200, 200, 255, 255);
    interfaces->surface->drawLine(x1, y1, x2, y2);

}`

**Comment by ny-4** [comment]
> static int y1 = -200;

well you are telling it to start drawing 200 pixels off the top of your screen lol
Ill take a looksie

**Comment by ny-4** [comment]
Ok yeah here ya go. not saying my code is any cleaner but this works in ISurface lol

```cpp
if (!config->misc.showVelocity)
        return;

    if (!localPlayer)
        return;
    if (!interfaces->engine->isInGame() || !localPlayer.get()->isAlive())
        return;

    static std::vector<float> velData(120, 0);

    Vector vecVelocity = localPlayer.get()->velocity();
    float currentVelocity = sqrt(vecVelocity.x * vecVelocity.x + vecVelocity.y * vecVelocity.y);

    velData.erase(velData.begin());
    velData.push_back(currentVelocity);

    float vel = localPlayer->velocity().length2D();
    std::wstring velwstr{ L"(" + std::to_wstring(static_cast<int>(vel)) + L")" };

    const auto [width, height] = interfaces->surface->getScreenSize();
    interfaces->surface->setTextColor(0, 255, 100, 255);
    interfaces->surface->setTextFont(12);
    interfaces->surface->setTextPosition(width / 2 - interfaces->surface->getTextSize(12, velwstr.c_str()).first / 2, height / 2 + 200);
    interfaces->surface->printText(velwstr);

    interfaces->surface->setDrawColor(255, 255, 255, 255);

    for (auto i = 0; i < velData.size() - 1; i++)
    {
        int cur = velData.at(i);
        int next = velData.at(i + 1);

        interfaces->surface->drawLine(
            width / 2 + (velData.size()*5/2) - (i - 1) * 5.f,
            height / 2 - (std::clamp(cur, 0, 450) * .2f) + 200,
            width / 2 + (velData.size() * 5 / 2) - i * 5.f,
            height / 2 - (std::clamp(next, 0, 450) * .2f) + 200
        );
    }
```

**Comment by asu29** [comment]
lol im a bit of a paster but ill try and figure out how to inverse it thanks for the share

**Comment by newcommerdontblame** [comment]
@ny-4 ahahah good job mate atleast we made it (just a backwards :))

**Comment by ny-4** [comment]
well you see, i would, but i don't know your discord.

**Comment by newcommerdontblame** [comment]
> well you see, i would, but i don't know your discord.

@ny-4 itscraused#5786

**Comment by koon666** [comment]
close pls

**Comment by koon666** [comment]
thank u

**Comment by oreothegod** [comment]
> Ok yeah here ya go. not saying my code is any cleaner but this works in ISurface lol
> 
> ```c++
>     if (!config->misc.showVelocity)
>         return;
> 
>     if (!localPlayer)
>         return;
>     if (!interfaces->engine->isInGame() || !localPlayer.get()->isAlive())
>         return;
> 
>     static std::vector<float> velData(120, 0);
> 
>     Vector vecVelocity = localPlayer.get()->velocity();
>     float currentVelocity = sqrt(vecVelocity.x * vecVelocity.x + vecVelocity.y * vecVelocity.y);
> 
>     velData.erase(velData.begin());
>     velData.push_back(currentVelocity);
> 
>     float vel = localPlayer->velocity().length2D();
>     std::wstring velwstr{ L"(" + std::to_wstring(static_cast<int>(vel)) + L")" };
> 
>     const auto [width, height] = interfaces->surface->getScreenSize();
>     interfaces->surface->setTextColor(0, 255, 100, 255);
>     interfaces->surface->setTextFont(12);
>     interfaces->surface->setTextPosition(width / 2 - interfaces->surface->getTextSize(12, velwstr.c_str()).first / 2, height / 2 + 200);
>     interfaces->surface->printText(velwstr);
> 
>     interfaces->surface->setDrawColor(255, 255, 255, 255);
> 
>     for (auto i = 0; i < velData.size() - 1; i++)
>     {
>         int cur = velData.at(i);
>         int next = velData.at(i + 1);
> 
>         interfaces->surface->drawLine(
>             width / 2 + (velData.size()*5/2) - (i - 1) * 5.f,
>             height / 2 - (std::clamp(cur, 0, 450) * .2f) + 200,
>             width / 2 + (velData.size() * 5 / 2) - i * 5.f,
>             height / 2 - (std::clamp(next, 0, 450) * .2f) + 200
>         );
>     }
> ```
> 
> edit: oops lol looks like it goes in the wrong direction. im sure you could figure that out tho :)

hey can u help me a bit with the velocity graph my discord eqzxtic#7916 if you want to help me,ty in advance
