### ISSUE TITLE
Apparently detected !

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#2236]
It is known that between 2 and 6 October there was a new vac wave

Many friends and acquaintances who use Osiris have received VAC BAN, including myself on 2 accounts

We do not all use the same injector, so we assume that the cheat has been detected and not the injector

I also went to read cheater.fun and many users complaining about the same

Regards

**Comment by newcommerdontblame** [comment]
Injector issue

**Comment by TauCSGO** [comment]
[ We do not all use the same injector, so we assume that the cheat has been detected and not the injector ]

**Comment by newcommerdontblame** [comment]
so why ''WE" dont get vac or someshit only u posted this

**Comment by Gangster8192** [comment]
Injector issue, use [the vac bypass loader](https://github.com/danielkrupinski/VAC-Bypass-Loader), and any decent injector.

**Comment by TauCSGO** [comment]
> Injector issue, use [the vac bypass loader](https://github.com/danielkrupinski/VAC-Bypass-Loader), and any decent injector.

vac bypass loader send your trust factor automatically to RED
It's proven
https://github.com/danielkrupinski/VAC-Bypass-Loader/issues/12

**Comment by MasterChief220** [comment]
> > Injector issue, use [the vac bypass loader](https://github.com/danielkrupinski/VAC-Bypass-Loader), and any decent injector.
> 
> vac bypass loader send your trust factor automatically to RED
> It's proven
> [danielkrupinski/VAC-Bypass-Loader#12](https://github.com/danielkrupinski/VAC-Bypass-Loader/issues/12)

bruh i've been using it since 2 months . havent had any problem

**Comment by Gangster8192** [comment]
Definitely doesn't set your trust factor to red, the issue shown is literally just speculation.

**Comment by Gangster8192** [comment]
If you don't want to use the vac-bypass-loader, use any load-lib injector that bypasses the vac check, [here.](https://github.com/danielkrupinski/OneByteLdr)

**Comment by MasterChief220** [comment]
> If you don't want to use the vac-bypass-loader, use any load-lib injector that bypasses the vac check, [here is the bypass in question.](https://github.com/danielkrupinski/OneByteLdr)

Better yet us CSGhost

**Comment by Gangster8192** [comment]
> > If you don't want to use the vac-bypass-loader, use any load-lib injector that bypasses the vac check, [here is the bypass in question.](https://github.com/danielkrupinski/OneByteLdr)
> 
> Better yet us CSGhost

v2.4 is detected, and v2.6 isn't approved yet.

**Comment by debruh** [comment]
You need to VMP your dll and use a good injector like csghost

**Comment by ny-4** [comment]
> If you don't want to use the vac-bypass-loader, use any load-lib injector that bypasses the vac check, [here is the bypass in question.](https://github.com/danielkrupinski/OneByteLdr)

ok yeah thats all fine and dandy but you can still easily get vac'd. all that load-lib injector does is patch NtLoadsomethingoranother in csgo, injects the dll, and restores the patched function. VAC still runs on the system and you can still get banned. vac-bypass-loader essentially disables VAC entirely, keeping you safe from VAC scanning. all load-lib injector does is get your dll into the game without it knowing, not keeping you safe from bans.

**Comment by BaiAlbert** [comment]
Maybe add junk code to osiris, change some things or vm protecting it.
Im making a paste with osiris and the first thing i made was the junk code lmao

**Comment by caiocinel** [comment]
> Maybe add junk code to osiris, change some things or vm protecting it.
> Im making a paste with osiris and the first thing i made was the junk code lmao

I don't know who the idiot was who said junkcode is for something, but now there are lots of naive people thinking they are safe just by adding a few lines of code with no value.

**Comment by RealSkyr0** [comment]
Just code your own injector and you will never be banned. Been using osiris for over a year now and no bans yet.
