### ISSUE TITLE
How to call the font file

### ISSUE THREAD

**Issue by 22553456** [danielkrupinski/Osiris#2241]
Ask how to load fonts

**Comment by BlackEyeCheats** [comment]
ImGuiIO& io = ImGui::GetIO();
fontnamehere = io.Fonts->AddFontFromMemoryCompressedBase85TTF(MyFont_compressed_data_base85, 14.f);

Use https://github.com/ocornut/imgui/blob/master/misc/fonts/binary_to_compressed_c.cpp to get compressed_data_base85

then place
ImGui::PushFont(fontnamehere);
and end with
ImGui::PopFont();
