### ISSUE TITLE
[Request] More ESP to Stream Proof

### ISSUE THREAD

**Issue by OscarMorrisUCD** [danielkrupinski/Osiris#2242]
Hi,

Just wanted to ask if the Spectator List, Bomb Timer and Hitmarker could be migrated to the stream proof overlay as they are all visible in OBS and would imagine them being easy enough to put on the new overlay. Also if its not to much to ask maybe a way to track Backtrack ticks using the Stream Proof overlay (I know the last one is alot to ask compared to the others but the only way to track ticks currently is using chams). 
Cheers for all the hard work, Hope this feedback helps.

**Comment by newcommerdontblame** [comment]
Take a look how recoilcrosshair or purchase list done then do it urself call it in here its ok https://github.com/danielkrupinski/Osiris/blob/b782d0a8cca9c0ff86c277c75f95bb154496cf15/Osiris/Hooks.cpp#L98
