### ISSUE TITLE
auto search for game from main menu help request

### ISSUE THREAD

**Issue by RyDeem** [danielkrupinski/Osiris#2245]
Does anyone have an idea how to make this?
 i want to know how to click a "you have been kicked from server" dialog,
And how to automatically que up for another.
Any help appreciated.

(aimed at casual deathmatch mainly)

Would be used to just afk in DM, and farm xp scraps just by 360 aimbot wit low max angle delta (20), +duck +forward. 
Id use an autobuyer feature too, but there is no need because CSGO got F3 autobuy random allready, it's good enuf.

**Comment by newcommerdontblame** [comment]
Take a look at these https://www.unknowncheats.me/forum/counterstrike-global-offensive/223405-auto-queue.html

https://www.unknowncheats.me/forum/counterstrike-global-offensive/213145-joining-deathmatch-games-automatically.html

https://www.unknowncheats.me/forum/counterstrike-global-offensive/318498-auto-queue-panorama.html

https://www.unknowncheats.me/forum/counterstrike-global-offensive/218279-auto-queue.html

**Comment by RyDeem** [comment]
Damn man, thank you very much, 
i was looking in uc from google, and i could not find anything, but thats just my own fault for not knowing the right keywords.

**Comment by RyDeem** [comment]
I am closing this to not clutter issues on Oss page.
