### ISSUE TITLE
[QUESTION] [REQUEST] Killfeed

### ISSUE THREAD

**Issue by crados** [danielkrupinski/Osiris#2251]
Hi, i've been using Osiris for a couple of months and consider it so far the best free cheat for CSGO.

I would like to ask something, is it possible to make an option that makes my killfeed be only normal shots instead of headshots when using aimbot? i mean if it's possible to "hide" the fact that my shots are only headshots due to aimbot?

I know there is an option in Misc called Preserve Killfeed, but that i think only shows headshots or maybe i'm using it wrong, in that case how do i use it? is possible show normal shots instead of head, when using aimbot?

If this is not how it works can anyone explain? if this option doesn't exist i would like to request if possible to add, that way we can appear as we are noobs, when we actually are using some aim :p

**Comment by sidekek** [comment]
if you want other clients to think you aren't hitting headshots then what you're asking for is probably impossible. if you for some reason want it clientside, then i've seen people call the death notice function from memory.

**Comment by crados** [comment]
> 
> 
> if you want other clients to think you aren't hitting headshots then what you're asking for is probably impossible. if you for some reason want it clientside, then i've seen people call the death notice function from memory.

No no, what i wanted was to hide the fact that i'm doing only headshots, but it's ok if it's not possible.

Still, what does the Preserve Killfeed option do?

**Comment by crados** [comment]
Thanks.
