### ISSUE TITLE
StreamProof

### ISSUE THREAD

**Issue by Allerek** [danielkrupinski/Osiris#2257]
StreamProof moze nie działać bez -untrusted(nie mozna przechwytywać gry w OBS, trzeba przechwytywac okno co pokazuje cheata).
Rozwiązaniem może być rysowanie na nakładce Discorda zamiast nakładce Steam.

**Comment by KernCS** [comment]
The solution [here](https://www.unknowncheats.me/forum/counterstrike-global-offensive/409060-obs-gamecapture.html)

**Comment by Allerek** [comment]
> Your solution [here](https://www.unknowncheats.me/forum/counterstrike-global-offensive/409060-obs-gamecapture.html)
Doesnt work for me, in game capture the screen is black, in window capture it still see the cheat
