### ISSUE TITLE
How to delete other functions and only keep the skin changer

### ISSUE THREAD

**Issue by wyz155** [danielkrupinski/Osiris#2258]
How to delete other functions and only keep the skin changer

**Comment by gr1ndy** [comment]
delete or comment out the render___Window(); besides the skinchanger.

**Comment by tirziz** [comment]
Better go to nskinz

**Comment by wyz155** [comment]
> 删除或注释掉render ___ Window（）; 除了换皮肤。

How to change the menu style so that only the skinning window will pop up

**Comment by wyz155** [comment]
> 删除或注释掉render ___ Window（）; 除了换皮肤。

Only keep the window of the skin changer, cancel the top menu

**Comment by wyz155** [comment]
> delete or comment out the render___Window(); besides the skinchanger.

How to change the menu style so that only the skinning window will pop up

**Comment by wyz155** [comment]
> delete or comment out the render___Window(); besides the skinchanger.

Only keep the window of the skin changer, cancel the top menu

**Comment by wyz155** [comment]
> Better go to nskinz

Outdated

**Comment by gr1ndy** [comment]
> > Better go to nskinz
> 
> Outdated

in gonna do it for u when i go home add me ln discord gr1ndy#7802

**Comment by wyz155** [comment]
> > > Better go to nskinz
> > 
> > 
> > Outdated
> 
> in gonna do it for u when i go home add me ln discord gr1ndy#7802

ok
