### ISSUE TITLE
New VFunc for engine.h

### ISSUE THREAD

**Issue by NexSqaud** [danielkrupinski/Osiris#226]
clientCmdUnrestricted can execute console commands. for example:when cheat loaded you can send commands
* clear
* echo "Osiris now in your console! :)"

Or you can make a chat spam.
```c++
constexpr auto clientCmdUnrestricted(const char* CmdString) noexcept
	{
		callVirtualMethod<void, const char*>(this, 112, CmdString);
	}
```

**Comment by danielkrupinski** [comment]
Added.
