### ISSUE TITLE
Player models are super broken on movement.

### ISSUE THREAD

**Issue by jewfuck** [danielkrupinski/Osiris#2261]
Im suprised that almost nobody reported this sort of issue.
https://imgur.com/a/Yd4U5Pl
this is just small example of this issue. players are seemt very jittery which makes game unlegit/annoying.

anyone have idea that why this is happening?

**Comment by jewfuck** [comment]
also no, animation fix / bone fix / movement fix doesnt solves this issue.

**Comment by tirziz** [comment]
Try fast crouch or fast plant

**Comment by jewfuck** [comment]
> 
> 
> Try disable fast crouch or fast plant

how are they even related with this issue? also no, i dont even use them.
Please do noy throw bs answers if you have 0 clue about problem.

**Comment by piee-kun** [comment]
there's no need to be rude mate. he's trying to help you with the issue.

**Comment by rosesware** [comment]
> > Try disable fast crouch or fast plant
> 
> how are they even related with this issue? also no, i dont even use them.
> Please do noy throw bs answers if you have 0 clue about problem.

They can be related, Fast crouch and fast plant force an action, then force the animation.

**Comment by jewfuck** [comment]
> 
> 
> > > Try disable fast crouch or fast plant
> > 
> > 
> > how are they even related with this issue? also no, i dont even use them.
> > Please do noy throw bs answers if you have 0 clue about problem.
> 
> They can be related, Fast crouch and fast plant force an action, then force the animation.

you clearly didnt read OP.
