### ISSUE TITLE
[REQUEST] Re-add rcs value (y and x) back

### ISSUE THREAD

**Issue by SapphireCodenz** [danielkrupinski/Osiris#2263]
and make it to work on pistols too, thanks

**Comment by newcommerdontblame** [comment]
Pistol rcs hhh

**Comment by SapphireCodenz** [comment]
> Pistol rcs hhh

ppl use it

**Comment by VuBrian22** [comment]
idk if this is rlly necessary because Aim RCS is already implemented and turned on by default. Otherwise look in the pull requests if you want Standalone RCS with the slider values of x and y.

**Comment by tirziz** [comment]
yes, the RCS is buggy. Maybe someone can fix it.
