### ISSUE TITLE
[REQUEST] X crosshair

### ISSUE THREAD

**Issue by dayz2000** [danielkrupinski/Osiris#2264]
As the title say

**Comment by danielkrupinski** [comment]
What is it?

**Comment by dayz2000** [comment]
> What is it?

change + crosshair to X crosshair like this 
https://www.nicepng.com/png/detail/28-281738_losing-track-of-your-aiming-reticle-enel-x.png

**Comment by DEVjeSucks** [comment]
isnt that hitmark ?

**Comment by dayz2000** [comment]
> isnt that hitmark ?

yep but always on not hitmark

**Comment by newcommerdontblame** [comment]
i have the possibly dumbest way to make it lol 

make logaritmic slider for hitmarker disappear time 
make float 0 to 382173127sec for if u wanna use as hitmarker use in 0.2sec if u wanna use as crosshair make it 83247234sec 
hit someone in game make ur crosshair alpha 0 
here is ur x crosshair :P

**Comment by newcommerdontblame** [comment]
https://github.com/danielkrupinski/Osiris/pull/2275

**Comment by newcommerdontblame** [comment]
@dayz2000 @danielkrupinski https://github.com/danielkrupinski/Osiris/pull/2275
