### ISSUE TITLE
I have a problem, I cannot compile Osiris

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#2265]
https://i.imgur.com/wHCQTue.png

**Comment by Khajiitos** [comment]
Update your visual studio

**Comment by crados** [comment]
I have the same errors, and my visual studio is updated

**Comment by Khajiitos** [comment]
> I have the same errors, and my visual studio is updated

If you have this error your visual studio must be older than version 16.5 as that's the version where numbers.h was implemented

**Comment by crados** [comment]
No, i have latest version 16.7.6, the error that is showing is this 

Fatal Error C1083

**Comment by crados** [comment]
Fixed it, some visual studio files where missing idk why, downloaded and installed it again and its working.

**Comment by Shuvi-Moro** [comment]
Thnx
