### ISSUE TITLE
triggerbot missing a lot and visual lags

### ISSUE THREAD

**Issue by tlgz** [danielkrupinski/Osiris#2266]
hi,
triggerbot is missing so much like shooting air when someone peeks.

also flickering when someone peeks the viewmodel of chams and almost everything lags 

anything to do better?

**Comment by newcommerdontblame** [comment]
streamable esp causes that
also u can solve triggerbot problem easily just check for local player flags() & 1

**Comment by tlgz** [comment]
can you give a .little more about the triggerbot fix how to do that

> streamable esp causes that
> also u can solve triggerbot problem easily just check for local player flags() & 1

**Comment by Khajiitos** [comment]
> also u can solve triggerbot problem easily just check for local player flags() & 1

Why would you want to check if localplayer is on the ground? Like sure, it won't shoot while you're in air, but why would you even triggerbot mid-air

**Comment by newcommerdontblame** [comment]
> > also u can solve triggerbot problem easily just check for local player flags() & 1
> 
> Why would you want to check if localplayer is on the ground? Like sure, it won't shoot while you're in air, but why would you even triggerbot mid-air

He could add checkbox for that bro

**Comment by newcommerdontblame** [comment]
@tlgz @Khajiitos something like this https://github.com/danielkrupinski/Osiris/pull/2272

**Comment by tlgz** [comment]
nono i mean when i shoot w triggerbot casually it misses like doesnt hit the player
