### ISSUE TITLE
[Help] Watermark and spec list font

### ISSUE THREAD

**Issue by BaiAlbert** [danielkrupinski/Osiris#2268]
Hello, so im making my own paste with osiris and i want to change the font of the watermark and the spectator list.
I tried some things but still not works.
I would appreciate if someone helps me :))

**Comment by Khajiitos** [comment]
`interfaces->surface->setTextFont(number);`

**Comment by BaiAlbert** [comment]
> `interfaces->surface->setTextFont(number);`
Still not working, with 1 its very small, and with 2 its not the font i want.

**Comment by Khajiitos** [comment]
What I like to do is make the number a variable in the config and put an inputint in the gui and then you can look through every font and pick the one that suits you the best

**Comment by OdogWare187** [comment]
hi,

can you send me the code for this?

i'm a beginner.
