### ISSUE TITLE
Nade helper, movement recorder

### ISSUE THREAD

**Issue by uzdiiilekk** [danielkrupinski/Osiris#2269]
I can send you movement recorder and nade helper.
I need Granade helper because this cheat is Very good for legit hacking and nade helper really upgrade the cheat

**Comment by DEVjeSucks** [comment]
> I can send you movement recorder and nade helper.
> I need Granade helper because this cheat is Very good for legit hacking and nade helper really upgrade the cheat

DEVje#8824 please contact, I want to try it :)

**Comment by thisisprettyepic** [comment]
lets hope that someone experienced can port over a grenade helper sometime soon

**Comment by BaiAlbert** [comment]
> I can send you movement recorder and nade helper.
> I need Granade helper because this cheat is Very good for legit hacking and nade helper really upgrade the cheat

BaiAlbert#0819 add me and send me the movement recorder pls :))

**Comment by PatrixCheats** [comment]
> I can send you movement recorder and nade helper.
> I need Granade helper because this cheat is Very good for legit hacking and nade helper really upgrade the cheat

Please send it to me too thx Patrix#1178

**Comment by Curiouss312** [comment]
Cur1ouS$#7208 it will be good if u can send it to me to 👍 :)

**Comment by zium-xyz** [comment]
zium#0001 im waiting
