### ISSUE TITLE
Source update

### ISSUE THREAD

**Issue by Flaam** [danielkrupinski/Osiris#227]
How can i apply the new updates to my source without replacing it every time?

**Comment by NexSqaud** [comment]
Two ways:
* Write C# or Python program for auto download new source, compile and inject
* Update sources once per week or month

**Comment by Flaam** [comment]
@NexSqaud seems too difficult

**Comment by NexSqaud** [comment]
[¯\_(ツ)_/¯](https://github.com/NexSqaud/OsirisUpdate)

**Comment by Flaam** [comment]
@NexSqaud i have some junk code in my source and some changes, i dont need the dll updater, i want something that changes only the updated strings

**Comment by NexSqaud** [comment]
Install GitHub plugin for visual studio, add Osiris repo, and get updates directly. W/o changing your code(I think)

**Comment by Flaam** [comment]
@NexSqaud i will try, thanks.
