### ISSUE TITLE
About recoil

### ISSUE THREAD

**Issue by rosesware** [danielkrupinski/Osiris#2270]
After recoil got upgraded to "auto", seems so much obvious when I make one.
Like, when a start shooting at someone, and this guys is running, my aim just follows him so perfetly and seems so obvious.
I also use FOV at 1.5 and Smooth at 20-22.

**Is just for me?**

**Comment by newcommerdontblame** [comment]
use it in holdkey mode with your shoot bind(mouse1 or whatever) also recommend to use drawfov

**Comment by rosesware** [comment]
> use it in holdkey mode with your shoot bind(mouse1 or whatever) also recommend to use drawfov

I use Hold option on key, and about the Draw FOV, I don't really like, I wanna stay my screen clean.
