### ISSUE TITLE
[REQUEST] Indicators

### ISSUE THREAD

**Issue by BaiAlbert** [danielkrupinski/Osiris#2271]
I just want some help for making an indicator for triggerbot (or any other keybind).
Thanks

**Comment by Khajiitos** [comment]
`
const auto height = interfaces->surface->getScreenSize().second;
interfaces->surface->setTextPosition(0, static_cast<int>(heigth * 0.95));
interfaces->surface->setTextFont(number);
// definition of weaponIndex should be somewhere in triggerbot i think
if (GetAsyncKeyState(config->triggerbot[weaponIndex]).key)
    interfaces->surface->setTextColor(0, 255, 0);
else
    interfaces->surface->setTextColor(255, 0, 0);
interfaces->surface->printText(L"TRIGGERBOT");
`
This will print TRIGGERBOT on the bottom left corner of your screen, and if the triggerbot key is pressed, it's gonna be green, and if it's not, it's gonna be red.

**Comment by TheFantasticLoki** [comment]
Request: Indicators for Enemy to the left right and behind and also a side profile third person to check if weapon is visible around corner. Thanks in advance!

**Comment by newcommerdontblame** [comment]
hey u can paste it from my broke ass code in here :) https://github.com/danielkrupinski/Osiris/pull/2076
