### ISSUE TITLE
[Help] Crashing when shooting with https://github.com/danielkrupinski/Osiris/pull/1716 

### ISSUE THREAD

**Issue by spleatz** [danielkrupinski/Osiris#2276]
Everything compiles normally but I crash when I shoot. I debugged and it showed me this error:
https://media.discordapp.net/attachments/742586673552031785/770262793021816852/unknown.png?width=1204&height=677
Any help is appreciated.

**Comment by yEsPaP** [comment]
ask the pr maker not daniel

**Comment by Frouk3** [comment]
Compile in release

**Comment by spleatz** [comment]
> Compile in release

i did compile it in release and it still crashes
