### ISSUE TITLE
[Suggestion] Menu color changer

### ISSUE THREAD

**Issue by Flaam** [danielkrupinski/Osiris#228]
Can you add a button in the visuals/misc menu to change the menu/gui color (color scale+rainbow)

**Comment by danielkrupinski** [comment]
I can implement menu style editor if more people would be interested.

**Comment by Mufinekkk** [comment]
Menu style editor sounds good.

**Comment by effex1337** [comment]
I have implemented menu coolor editor in my build of Osiris but it's 3 different sliders instead of a single color edit box. I could share that but I'd rather prefer a single color edit box

**Comment by danielkrupinski** [comment]
Added.
