### ISSUE TITLE
[HELP] Old Checkmark

### ISSUE THREAD

**Issue by BaiAlbert** [danielkrupinski/Osiris#2280]
I would appreciate if someone helps me getting back the old checkmark (https://prnt.sc/v875gn)
Thanks in advance :D

**Comment by Frouk3** [comment]
(In game) Open osiris and click to style. Customize what ever you want

**Comment by BaiAlbert** [comment]
> (In game) Open osiris and click to style. Customize what ever you want

thats just for color, im saying to change from a check to a square like in the screenshot

**Comment by DEVjeSucks** [comment]
> > (In game) Open osiris and click to style. Customize what ever you want
> 
> thats just for color, im saying to change from a check to a square like in the screenshot

I think you need from somewhere called Checkmark to rename it to rectfilled - or filledrect ? Idk actually, so yeah... I only heard that from my friend which was pasting hydra

**Comment by Curiouss312** [comment]
> > (In game) Open osiris and click to style. Customize what ever you want
> 
> thats just for color, im saying to change from a check to a square like in the screenshot

I think u want to change the imgui just go to imgui_widgets.cpp and search for checkbox and make ur own checkbox or copy and paste some from google and fix the errors and u are done
