### ISSUE TITLE
Failed to find VClient018 interface.

### ISSUE THREAD

**Issue by eyupahmetyilmazz** [danielkrupinski/Osiris#2282]
I selected Manual Map and it gave this error.

**Comment by eyupahmetyilmazz** [comment]
And the game is over.
(Sorry im use translate)

**Comment by Frouk3** [comment]
What injector do you use?

**Comment by Frouk3** [comment]
Inject when you're in menu

**Comment by eyupahmetyilmazz** [comment]
ExtremeInjector

**Comment by eyupahmetyilmazz** [comment]
Error comes in main menu

**Comment by uzdiiilekk** [comment]
Use xenox injector

**Comment by Frouk3** [comment]
> Use xenox injector

or csghost
