### ISSUE TITLE
any one who have a line of code that will add rcs back?

### ISSUE THREAD

**Issue by Wiselyx** [danielkrupinski/Osiris#2284]
so im trying to add rcs(not standalone) back but i dont know how cuz im new to pasting.
im not really fond of the automatic rcs when u enable aimbot..

**Comment by spleatz** [comment]
pretty sure rcs is active automaticly

**Comment by Wiselyx** [comment]
> pretty sure rcs is active automaticly

i know.. but its annoying.. i cant hit shit when i use pistol recoil goes down.

**Comment by Wiselyx** [comment]
i want the rcs like the 2019 version of osirs.. pls anyone of you
