### ISSUE TITLE
Osiris detected

### ISSUE THREAD

**Issue by w6f** [danielkrupinski/Osiris#2286]
I've gotten many accounts of mine VAC banned during the past few days... Daniel do something

**Comment by Tothale** [comment]
i have nothing in my accounts, maybe your injector has been detected.
you can use wmprotect or like this for undetected dll.
you can use daniel's vac bypass loader [https://github.com/danielkrupinski/VAC-Bypass-Loader](url)

**Comment by Frouk3** [comment]
I'm used extreme injector and i've got banned
Then i changed injector to csghost before that i haven't in my account any bans

**Comment by hyperxpro** [comment]
Stop cheating. The perfect solution to prevent bans. :)

**Comment by PanSmuggler** [comment]
> I used extreme injector and i've got banned
> Then i changed injector to csghost before that i haven't in my account any bans

extreme injector is old and detected lol

**Comment by rosesware** [comment]
Injector.

**Comment by RealSkyr0** [comment]
Code your own injector and you will be fine. I have had no bans in the last 6 months using osiris with my own injector

**Comment by uzdiiilekk** [comment]
Can you send me the injector please ? I try to make own secure loader and it doesnt work and then i try to make own injector and if i turn the injector it open but after 0.5 second it close and nothing ..  
discord - uzdiiilekk_#3312 if you send me it

**Comment by uzdiiilekk** [comment]
Your create accounts with the same email ? Xd

**Comment by RealSkyr0** [comment]
@uzdiiilekk just use loadlibary, it's literally like 10 lines for the injection part with C# :P

**Comment by RealSkyr0** [comment]
but if you really want I do have an injector on my github page called reinject v4

**Comment by uzdiiilekk** [comment]
Idk how

**Comment by RealSkyr0** [comment]
@uzdiiilekk if you want you can use ReInject V4 which is on my github page.

**Comment by uzdiiilekk** [comment]
Ok thanks <3

**Comment by uzdiiilekk** [comment]
@RealSkyr0 can you add me on discord for the injector please ?

**Comment by RealSkyr0** [comment]
@uzdiiilekk what is your username

**Comment by uzdiiilekk** [comment]
uzdiiilekk#3312

**Comment by uzdiiilekk** [comment]
uzdiiilekk_#3312

**Comment by kschou95** [comment]
getting vac ban is injector got detected, not the hack got detected

**Comment by ramboi234** [comment]
mine also got vac ban, using csghost injector, the ban is so delayed, I was using the hack like 4 days ago after that stop playing csgo then I got vac ban yesterday 31/10/2020 
![image](https://user-images.githubusercontent.com/65648767/97799677-12a35980-1c62-11eb-8794-977060b44a1c.png)

cfg only aimbot no esp/wh

**Comment by Frouk3** [comment]
Show your aimbot cfg

**Comment by ramboi234** [comment]
> Show your aimbot cfg

https://pastebin.com/raw/2UfVjBFL

**Comment by uzdiiilekk** [comment]
Its obvious aimbot ..

**Comment by RealSkyr0** [comment]
cfg does not matter for vac bans, just code your own injector and you will never be banned. I have been using it for 6 months and no ban yet

**Comment by Frouk3** [comment]
> cfg does not matter for vac bans, just code your own injector and you will never be banned. I have been using it for 6 months and no ban yet

matter if you configure aimbot to very small smooth

**Comment by RealSkyr0** [comment]
> > cfg does not matter for vac bans, just code your own injector and you will never be banned. I have been using it for 6 months and no ban yet
> 
> matter if you configure aimbot to very small smooth

only matters for overwatch, not vac

**Comment by ramboi234** [comment]
> > cfg does not matter for vac bans, just code your own injector and you will never be banned. I have been using it for 6 months and no ban yet
> 
> matter if you configure aimbot to very small smooth

meh use more blatant aimbot cfg with aimware never get vac even set smooth to 1(max) 

I was using this cheat more like 3 months,  using Xenos64 injector and got vac ban after 2 half months

the reason why I use Xenos because we can just bypass trust mode by injecting it on windows folder, 2 half  months have no problem until valve do smthng

then I use my main acc use csghost that I know its undetected until now prob
![image](https://user-images.githubusercontent.com/65648767/97856883-80698700-1d2f-11eb-87b5-a727d6606049.png)
no vac yet after 3 weeks, but after I stop play csgo then I want to play it again, and just got that vac notification

just not my luck probably:/

**Comment by pparadoxx** [comment]
> > cfg does not matter for vac bans, just code your own injector and you will never be banned. I have been using it for 6 months and no ban yet
> 
> matter if you configure aimbot to very small smooth

im losing braincells

**Comment by wemanzoz** [comment]
> > > cfg does not matter for vac bans, just code your own injector and you will never be banned. I have been using it for 6 months and no ban yet
> > 
> > 
> > matter if you configure aimbot to very small smooth
> 
> meh use more blatant aimbot cfg with aimware never get vac even set smooth to 1(max)
> 
> I was using this cheat more like 3 months, using Xenos64 injector and got vac ban after 2 half months
> 
> the reason why I use Xenos because we can just bypass trust mode by injecting it on windows folder, 2 half months have no problem until valve do smthng
> 
> then I use my main acc use csghost that I know its undetected until now prob
> ![image](https://user-images.githubusercontent.com/65648767/97856883-80698700-1d2f-11eb-87b5-a727d6606049.png)
> no vac yet after 3 weeks, but after I stop play csgo then I want to play it again, and just got that vac notification
> 
> just not my luck probably:/

vacwave, also use daniels vacbypass

**Comment by squizzyv9** [comment]
osiris is dont detected your injector is so bad and cfg big shit
