### ISSUE TITLE
Number HP

### ISSUE THREAD

**Issue by DEVjeSucks** [danielkrupinski/Osiris#2287]
hi, anyone who can make Health but in numbers ? maybe add another checkbox for Healt Number, or replace the bar, I have the hydraware source about it, but Im too dumb to make it to Osiris

void Visuals::Player::RenderHealth(C_BaseEntity* pl)
{
    auto  hp = ctx.pl->m_iHealth();
    float box_h = (float)fabs(ctx.bbox.bottom - ctx.bbox.top);
    //float off = (box_h / 6.f) + 5;
    float off = 8;

    int height = (box_h * hp) / 100;

    int x = ctx.bbox.left - off;
    int y = ctx.bbox.top;
    int w = 4;
    int h = box_h;
    std::string text = std::to_string(hp);

//    Render::Get().RenderBox(x, y, x + w, y + h, Color::Black, 1.f, true);
//    Render::Get().RenderBox(x + 1, y + 1, x + w - 1, y + height - 2, Color(0, 255, 0, 255), 1.f, true);

    Render::Get().RenderBox(x, y - 1, x + w, y + h + 1, Color(0, 0, 0, flPlayerAlpha[pl->EntIndex()]));
    Render::Get().RenderBox(x + 1, y + h - height, x + w - 1, y + h, Color(0, 255, 0, flPlayerAlpha[pl->EntIndex()]));
    Render::Get().RenderText(text, x - 20, y + h - height, 12.f, Color(255, 255, 255, flPlayerAlpha[pl->EntIndex()]));

}

**Comment by newcommerdontblame** [comment]
Get old osiris source then paste it

**Comment by DEVjeSucks** [comment]
> Get old osiris source then paste it

thanks, but isnt that like with something which is old ? I mean, there was some updates... so just asking if it still work :)
thx btw

**Comment by newcommerdontblame** [comment]
Nah its ok to use
