### ISSUE TITLE
[Help] Best legit aimbot settings?

### ISSUE THREAD

**Issue by Flaam** [danielkrupinski/Osiris#229]
I tried every settings but they are all obvious, can someone help me?
Thanks

**Comment by effex1337** [comment]
Depends on your rank
Use max 3 fov and smoothing around 10-15 for full auto weapons. 
The weapons like deag, usp, glock, ssg, awp should use like 1.1 smooth and even lower fov.
Don't use esp (visible only chams) + radar.
And you should be fine.

**Comment by Flaam** [comment]
@effex1337 isnt it too legit? I want to use it on prime and non prime

**Comment by Flaam** [comment]
@effex1337 Btw there is a problem, there aren't fov settings for every gun in this cheat..

**Comment by effex1337** [comment]
1. The settings depend on your rank (eg i can play on mge with just backtrack and radar and still top frag)
2. There is a setting for every weapon

**Comment by Flaam** [comment]
I play on smurf accounts gn4/mg and i would like to use aimbot? What do u reccomend
