### ISSUE TITLE
Help please 

### ISSUE THREAD

**Issue by uzdiiilekk** [danielkrupinski/Osiris#2292]
Are there any coders ? I need help please 
Discord -       uzdiiilekk_#3312

**Comment by Khajiitos** [comment]
Specify what you need help with

**Comment by uzdiiilekk** [comment]
I need add features to the cheat

**Comment by Khajiitos** [comment]
Why don't you tell us exactly what you want here? We're not able to help you if we only know that you want to add features to the cheat
