### ISSUE TITLE
Medal Changer, Inventory Changer, Profile Changer

### ISSUE THREAD

**Issue by make82777** [danielkrupinski/Osiris#2293]
Hi!

I just wanted to say that this cheat is being better and better with every update. I would like that next update will be medal changer and inventory changer instead of skin changer. Also it will be great if we can get also profile changer ( rank lvl ... ).

**Comment by thisisprettyepic** [comment]
Try and port if over from the riptide remastered source or hope that someone else does it and actually shares it

**Comment by thes4ns** [comment]
> Try and port if over from the riptide remastered source or hope that someone else does it and actually shares it

Good idea, I'll try and do that.

**Comment by zium-xyz** [comment]
Good idea.

**Comment by Curiouss312** [comment]
so if you guys were able to do it can u please share it I tried a lot but failed so I would rlly appreciate it if u guys share it

**Comment by wemanzoz** [comment]
i would like to see this happen
