### ISSUE TITLE
[REQUEST] GS Style clantag and jumpbug

### ISSUE THREAD

**Issue by BaiAlbert** [danielkrupinski/Osiris#2296]
I would like if someone can help me with that features :)))

**Comment by gr1ndy** [comment]
> I would like if someone can help me with that features :)))

check on discord

**Comment by BaiAlbert** [comment]
> > I would like if someone can help me with that features :)))
> 
> check on discord

discord? a server or something?

**Comment by caiocinel** [comment]
https://github.com/danielkrupinski/Osiris/pull/1829
https://github.com/danielkrupinski/Osiris/pull/2076

Search does not kill
