### ISSUE TITLE
how can i move the tabs to the left side of the menu

### ISSUE THREAD

**Issue by Curiouss312** [danielkrupinski/Osiris#2300]
i want to change the tab from top to the left side of menu how can I do that any help?

**Comment by BlackEyeCheats** [comment]
**Ghetto way**

Stack the buttons

`if (something) {
if (ImGui::Button("Aimbot", ImVec2(width, 70)));
if (ImGui::Button("Visuals", ImVec2(width, 70)));
if (ImGui::Button("Misc", ImVec2(width, 70)));
}`

Afterward, use
`ImGui::SameLine();`

The add a child or something else
`ImGui::BeginChild("Aimbot", ImVec2(280, 460), true); {
	checkboxes and stuff here;
}`

just practice and move around with stuff and you'll figure it out.
