### ISSUE TITLE
[HELP] How do i change the default menu style

### ISSUE THREAD

**Issue by brave-minecraft** [danielkrupinski/Osiris#2304]
Like how do i change when i inject the hack to be setted to the style named "One Window" not "Classic" one?

**Comment by brave-minecraft** [comment]
And another this how do i connect this https://github.com/danielkrupinski/VAC-Bypass-Loader
to the cheat like when i start the Vac Bypass Loader to start my csgo with the cheat injected

**Comment by Curiouss312** [comment]
> Like how do i change when i inject the hack to be setted to the style named "One Window" not "Classic" one?

go to config.h and search for menyStyle then change 0 to 2

**Comment by brave-minecraft** [comment]
> > Like how do i change when i inject the hack to be setted to the style named "One Window" not "Classic" one?
> 
> go to config.h and search for menuStyle then change 0 to 2

isnt working bruh

**Comment by Curiouss312** [comment]
it worked for me maybe rebuild the solution

**Comment by caiocinel** [comment]
> > > Like how do i change when i inject the hack to be setted to the style named "One Window" not "Classic" one?
> > 
> > 
> > go to config.h and search for menuStyle then change 0 to 2
> 
> isnt working bruh

Change to "1".

0 = Classic (MenuBar)
1 = One Window (Begin)

**Comment by brave-minecraft** [comment]
> > > > Like how do i change when i inject the hack to be setted to the style named "One Window" not "Classic" one?
> > > 
> > > 
> > > go to config.h and search for menuStyle then change 0 to 2
> > 
> > 
> > isnt working bruh
> 
> Change to "1".
> 
> 0 = Classic (MenuBar)
> 1 = One Window (Begin)
> 
> https://github.com/danielkrupinski/Osiris/blob/e89bc7c6dd388bece8832bb6b9e4c57ea4288492/Osiris/GUI.cpp#L49-L69

    struct Style {
        int menuStyle{ 1 };
        int menuColors{ 0 };
    } style; 
this is how its looks like and still when i inject the cheat its the menubar not the one window

**Comment by caiocinel** [comment]
Show me the GUI :render() function

**Comment by brave-minecraft** [comment]
void GUI::render() noexcept
{
    if (!config->style.menuStyle) {
        renderMenuBar();
        renderAimbotWindow();
        renderAntiAimWindow();
        renderTriggerbotWindow();
        renderBacktrackWindow();
        renderGlowWindow();
        renderChamsWindow();
        renderStreamProofESPWindow();
        renderVisualsWindow();
        renderSkinChangerWindow();
        renderSoundWindow();
        renderStyleWindow();
        renderMiscWindow();
        renderConfigWindow();
    } else {
        renderGuiStyle2();
    }
}
this one?

**Comment by caiocinel** [comment]
void GUI::render() noexcept
{
if (!config->style.menuStyle) {
  renderGuiStyle2();
} else {
renderMenuBar();
renderAimbotWindow();
renderAntiAimWindow();
renderTriggerbotWindow();
renderBacktrackWindow();
renderGlowWindow();
renderChamsWindow();
renderStreamProofESPWindow();
renderVisualsWindow();
renderSkinChangerWindow();
renderSoundWindow();
renderStyleWindow();
renderMiscWindow();
renderConfigWindow();
}
}

Invert everything, this will revert and allow use menubar again in menu
(remember change in menu also)

Em seg., 9 de nov. de 2020 às 14:48, brave-minecraft <
notifications@github.com> escreveu:

**Comment by brave-minecraft** [comment]
1>------ Build started: Project: Osiris, Configuration: Debug Win32 ------
1>GUI.cpp
1>Misc.cpp
1>Hooks.cpp
1>GUI.obj : error LNK2019: unresolved external symbol "private: void __thiscall GUI::renderHomeWindow(bool)" (?renderHomeWindow@GUI@@AAEX_N@Z) referenced in function "private: void __thiscall GUI::renderGuiStyle2(void)" (?renderGuiStyle2@GUI@@AAEXXZ)
1>S:\Curse.cc\Debug\Osiris.dll : fatal error LNK1120: 1 unresolved externals
1>Done building project "Osiris.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
that happend when i build after i add that

**Comment by brave-minecraft** [comment]
oh and another thing can i add up from the menu to be typed "CURSED.cc" or something?

**Comment by caiocinel** [comment]
What I tried to say was not "Copy and paste", read the code and understand
what is going on, any modifications made must have caused this problem.

Em seg., 9 de nov. de 2020 às 16:33, brave-minecraft <
notifications@github.com> escreveu:
