### ISSUE TITLE
How to add gradient bar at the top of the menu

### ISSUE THREAD

**Issue by Curiouss312** [danielkrupinski/Osiris#2305]
how can i add a rainbow bar can be static or moving idc

**Comment by caiocinel** [comment]
https://gist.github.com/galloscript/8a5d179e432e062550972afcd1ecf112

**Comment by KernCS** [comment]
https://pastebin.com/GBqJCeJk

**Comment by Curiouss312** [comment]
> https://pastebin.com/GBqJCeJk

![image](https://user-images.githubusercontent.com/69954129/98789476-58ada980-2428-11eb-98aa-7125b3346270.png)
how to fix this errors

**Comment by caiocinel** [comment]
I would recommend you learn a minimum of cpp (and programming) before trying to mess with it.
