### ISSUE TITLE
Crash On Injection?

### ISSUE THREAD

**Issue by TrotzeyOnPC** [danielkrupinski/Osiris#2307]
Its Crashing On Injection, Fix?

**Comment by TrotzeyOnPC** [comment]
lol i fixed it ;)

**Comment by TrotzeyOnPC** [comment]
.

**Comment by OprekerSejati** [comment]
> 
> 
> .



> 
> 
> lol i fixed it ;)

how did u fix it? I have the problem and using extreme injector 3.7.2 and 3.7.3

**Comment by caiocinel** [comment]
> > .
> 
> > lol i fixed it ;)
> 
> how did u fix it? I have the problem and using extreme injector 3.7.2 and 3.7.3

Extreme Injector is detected
