### ISSUE TITLE
some issues i found

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#231]
when switching maps from aim_botz to aim_ag_texture2 the new nskinz skinchanger crashes the game

backtrack is just...
https://youtu.be/BEzFTYj7hHU

other than that i didnt find any issues

**Comment by effex1337** [comment]
Hello Mr furry fag 😀
I pointed out this issue as well once upon a time when backtrack was just introduced to this cheat.

**Comment by Shaxzy** [comment]
The backtrack doesn’t work at all for me either anymore. It worked fine before, but after all the newest commits it simply don’t work.

**Comment by Flaam** [comment]
The backtrack for me works fine
