### ISSUE TITLE
How to change the tab to an image/icon?

### ISSUE THREAD

**Issue by Curiouss312** [danielkrupinski/Osiris#2312]
title

**Comment by polonium20** [comment]
Use Buttons as tab control and change the font to an icon font

**Comment by Curiouss312** [comment]
> Use Buttons as tab control and change the font to an icon font

can you tell how can i change the font the button please

**Comment by polonium20** [comment]
Look at GUI::GUI() in https://github.com/danielkrupinski/Osiris/blob/master/Osiris/GUI.cpp or https://github.com/ocornut/imgui
