### ISSUE TITLE
Semirage ??

### ISSUE THREAD

**Issue by bckup9638** [danielkrupinski/Osiris#2313]
Any one have tried to do a semirage cheat from this?
SemiRage  = 
legit aa resolver
legit aa
ragebot (with fov and bind)
awall (with toggle)

**Comment by gr1ndy** [comment]
![kekw](https://user-images.githubusercontent.com/71841362/98868362-a6ea9900-2478-11eb-9ee4-4aa1c1eba68d.png)
![kekw](https://user-images.githubusercontent.com/71841362/98868367-a81bc600-2478-11eb-9e82-44a6f596b5fd.png)
![kekw](https://user-images.githubusercontent.com/71841362/98868371-a94cf300-2478-11eb-9338-08e86401f340.png)

**Comment by gr1ndy** [comment]
just buy AdvancedAim Sub lmao

**Comment by thisisnotagithub** [comment]
i have managed to make a semirage cheat with osiris but the only thing i'm missing is autowall on toggle
