### ISSUE TITLE
[config] Legit config

### ISSUE THREAD

**Issue by w6f** [danielkrupinski/Osiris#2314]
Anybody has legit config for osiris?

**Comment by zajkos** [comment]
https://www.cshacked.pl/osiris-legit-config-t159547/

**Comment by wemanzoz** [comment]
I suggest to make one your own

**Comment by MrClue** [comment]
True legit settings depends on your current crosshair placement/movement, and mouse sensitivity.
I would suggest, that you use a small FoV for every gun and stick to nearest bone.

Also dont use wallhack, as it is never legit. Maybe audible only, but for me it makes me react slower as i get too dependent on the visuals lol.
