### ISSUE TITLE
About rage/hvh multipaste

### ISSUE THREAD

**Issue by Frouk3** [danielkrupinski/Osiris#2316]
There are a lot's of errors when i compile and no one hasn't fix it

**Comment by zajkos** [comment]
hmm i compiled already and its 99% working (1 or 2 func crashing --> 1 on AA and 1 on misc )

**Comment by zajkos** [comment]
TO DOWNLAND https://www.cshacked.pl/applications/core/interface/file/attachment.php?id=58669
VT: https://www.virustotal.com/gui/file/2062983675e10e5eb8328919e8b1701ee4d23efce9b232d72219c3c66d5381e7/detection

**Comment by caiocinel** [comment]
Github is a development community, not cheats, if you want to make your compiled files available, make a release in your repository.

**Comment by zajkos** [comment]
yep sry
