### ISSUE TITLE
Quick question about previous version of Osiris and the missing features

### ISSUE THREAD

**Issue by FalloutBruhMoments** [danielkrupinski/Osiris#2317]
So i was looking at some videos of Osiris and i saw that in a few videos from earlier this year/last year that the Aimbot was more fleshed out and had an RCS system as well as a few other things.

What happened to all those options and why aren't they in the newer editions of Osiris?
It feels like the cheat has been downgraded.

**Comment by zajkos** [comment]
i had (in my repository) working RCS (standalone) and few other options
