### ISSUE TITLE
My rage config (Copy paste into a note, then save as .cfg)

### ISSUE THREAD

**Issue by FalloutBruhMoments** [danielkrupinski/Osiris#2318]
{
  "Aimbot": [
    {
      "Bone": 2,
      "Enabled": true,
      "Fov": 255.0,
      "Ignore flash": true,
      "Ignore smoke": true,
      "Key mode": 1,
      "Scoped only": false,
      "Silent": true,
      "Visible only": false
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {}
  ],
  "Anti aim": {
    "Pitch angle": 20.65
  },
  "Backtrack": {
    "Ignore smoke": true
  },
  "Chams": {
    "Allies": {
      "Materials": [
        {
          "Color": [
            1.0,
            0.0,
            0.0,
            1.0
          ]
        },
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Backtrack": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Defusing": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Enemies": {
      "Materials": [
        {
          "Cover": true,
          "Enabled": true,
          "Material": 10
        },
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Hands": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Local player": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Planting": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Sleeves": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Weapons": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    }
  },
  "ESP": {
    "Allies": {
      "Occluded": {
        "Enabled": true
      },
      "Visible": {
        "Enabled": true
      }
    },
    "Enemies": {
      "All": {
        "Box": {
          "Color": [
            1.0,
            0.0,
            0.0,
            1.0
          ],
          "Enabled": true
        },
        "Enabled": true,
        "Health Bar": true,
        "Name": {
          "Enabled": true
        },
        "Snapline": {
          "Type": 2
        },
        "Weapon": {
          "Color": [
            1e-06,
            9.9999e-07,
            9.9999e-07,
            1.0
          ],
          "Enabled": true
        }
      }
    },
    "Other Entities": {
      "Planted C4": {
        "Enabled": true
      }
    }
  },
  "Glow": [
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {}
  ],
  "Misc": {
    "Auto strafe": true,
    "Bunny hop": true,
    "Disable HUD blur": true,
    "Grenade predict": true,
    "Noscope crosshair": {
      "Color": [
        1e-06,
        9.9999e-07,
        9.9999e-07,
        1.0
      ],
      "Enabled": true
    },
    "Radar hack": true,
    "Recoil crosshair": {
      "Color": [
        0.0,
        0.06349206,
        1.0,
        1.0
      ],
      "Enabled": true
    },
    "Reveal ranks": true
  },
  "Skin changer": [
    {
      "Definition index": 42,
      "Definition override": 507,
      "Definition override vector index": 9,
      "Enabled": true,
      "Paint Kit": 568,
      "Paint Kit vector index": 284
    },
    {},
    {
      "Definition index": 7,
      "Definition vector index": 2,
      "Enabled": true,
      "Paint Kit": 180,
      "Paint Kit vector index": 11,
      "StatTrak": 155,
      "Stickers": [
        {
          "Kit": 60,
          "Kit vector index": 1980
        },
        {
          "Kit": 60,
          "Kit vector index": 1980
        },
        {
          "Kit": 60,
          "Kit vector index": 1980
        },
        {
          "Kit": 60,
          "Kit vector index": 1980
        },
        {
          "Kit": 60,
          "Kit vector index": 1980
        }
      ]
    },
    {},
    {},
    {
      "Definition index": 63,
      "Definition vector index": 5
    },
    {
      "Custom name": "Blaze It",
      "Definition vector index": 6,
      "Enabled": true,
      "Paint Kit": 37,
      "Paint Kit vector index": 130,
      "StatTrak": 518,
      "Stickers": [
        {
          "Kit": 60,
          "Kit vector index": 1980
        },
        {
          "Kit": 60,
          "Kit vector index": 1980
        },
        {
          "Kit": 60,
          "Kit vector index": 1980
        },
        {
          "Kit": 60,
          "Kit vector index": 1980
        },
        {
          "Kit": 60,
          "Kit vector index": 1980
        }
      ]
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {}
  ],
  "Sound": {
    "Players": [
      {},
      {},
      {}
    ]
  },
  "Style": {
    "Colors": {
      "Border": [
        0.43,
        0.43,
        0.5,
        0.5
      ],
      "BorderShadow": [
        0.0,
        0.0,
        0.0,
        0.0
      ],
      "Button": [
        0.26,
        0.59,
        0.98,
        0.4
      ],
      "ButtonActive": [
        0.06,
        0.53,
        0.98,
        1.0
      ],
      "ButtonHovered": [
        0.26,
        0.59,
        0.98,
        1.0
      ],
      "CheckMark": [
        0.26,
        0.59,
        0.98,
        1.0
      ],
      "ChildBg": [
        0.0,
        0.0,
        0.0,
        0.0
      ],
      "DragDropTarget": [
        1.0,
        1.0,
        0.0,
        0.9
      ],
      "FrameBg": [
        0.16,
        0.29,
        0.48,
        0.54
      ],
      "FrameBgActive": [
        0.26,
        0.59,
        0.98,
        0.67
      ],
      "FrameBgHovered": [
        0.26,
        0.59,
        0.98,
        0.4
      ],
      "Header": [
        0.26,
        0.59,
        0.98,
        0.31
      ],
      "HeaderActive": [
        0.26,
        0.59,
        0.98,
        1.0
      ],
      "HeaderHovered": [
        0.26,
        0.59,
        0.98,
        0.8
      ],
      "MenuBarBg": [
        0.14,
        0.14,
        0.14,
        1.0
      ],
      "ModalWindowDimBg": [
        0.8,
        0.8,
        0.8,
        0.35
      ],
      "NavHighlight": [
        0.26,
        0.59,
        0.98,
        1.0
      ],
      "NavWindowingDimBg": [
        0.8,
        0.8,
        0.8,
        0.2
      ],
      "NavWindowingHighlight": [
        1.0,
        1.0,
        1.0,
        0.7
      ],
      "PlotHistogram": [
        0.9,
        0.7,
        0.0,
        1.0
      ],
      "PlotHistogramHovered": [
        1.0,
        0.6,
        0.0,
        1.0
      ],
      "PlotLines": [
        0.61,
        0.61,
        0.61,
        1.0
      ],
      "PlotLinesHovered": [
        1.0,
        0.43,
        0.35,
        1.0
      ],
      "PopupBg": [
        0.08,
        0.08,
        0.08,
        0.94
      ],
      "ResizeGrip": [
        0.26,
        0.59,
        0.98,
        0.25
      ],
      "ResizeGripActive": [
        0.26,
        0.59,
        0.98,
        0.95
      ],
      "ResizeGripHovered": [
        0.26,
        0.59,
        0.98,
        0.67
      ],
      "ScrollbarBg": [
        0.02,
        0.02,
        0.02,
        0.53
      ],
      "ScrollbarGrab": [
        0.31,
        0.31,
        0.31,
        1.0
      ],
      "ScrollbarGrabActive": [
        0.51,
        0.51,
        0.51,
        1.0
      ],
      "ScrollbarGrabHovered": [
        0.41,
        0.41,
        0.41,
        1.0
      ],
      "Separator": [
        0.43,
        0.43,
        0.5,
        0.5
      ],
      "SeparatorActive": [
        0.1,
        0.4,
        0.75,
        1.0
      ],
      "SeparatorHovered": [
        0.1,
        0.4,
        0.75,
        0.78
      ],
      "SliderGrab": [
        0.24,
        0.52,
        0.88,
        1.0
      ],
      "SliderGrabActive": [
        0.26,
        0.59,
        0.98,
        1.0
      ],
      "Tab": [
        0.17999999,
        0.34999996,
        0.58000004,
        0.862
      ],
      "TabActive": [
        0.19999999,
        0.40999997,
        0.68,
        1.0
      ],
      "TabHovered": [
        0.26,
        0.59,
        0.98,
        0.8
      ],
      "TabUnfocused": [
        0.068,
        0.10199998,
        0.14800003,
        0.9724
      ],
      "TabUnfocusedActive": [
        0.13599998,
        0.26199996,
        0.424,
        1.0
      ],
      "Text": [
        1.0,
        1.0,
        1.0,
        1.0
      ],
      "TextDisabled": [
        0.5,
        0.5,
        0.5,
        1.0
      ],
      "TextSelectedBg": [
        0.26,
        0.59,
        0.98,
        0.35
      ],
      "TitleBg": [
        0.04,
        0.04,
        0.04,
        1.0
      ],
      "TitleBgActive": [
        0.16,
        0.29,
        0.48,
        1.0
      ],
      "TitleBgCollapsed": [
        0.0,
        0.0,
        0.0,
        0.51
      ],
      "WindowBg": [
        0.06,
        0.06,
        0.06,
        0.94
      ]
    }
  },
  "Triggerbot": [
    {
      "Hitgroup": 1,
      "Scoped only": false
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {}
  ],
  "Visuals": {
    "Flash reduction": 100,
    "No aim punch": true,
    "No blur": true,
    "No grass": true,
    "No shadows": true,
    "No smoke": true,
    "Sky": {
      "Color": [
        1e-06,
        9.9999e-07,
        9.9999e-07
      ]
    },
    "Thirdperson": true,
    "Thirdperson key": 37,
    "Viewmodel FOV": 30,
    "Zoom": true,
    "Zoom key": 39
  }
}

**Comment by osamawahed** [comment]
take my Heart <3

**Comment by Scui1** [comment]
omg I'm hitting p with this

**Comment by HkyHa** [comment]
Super
