### ISSUE TITLE
So i need some help

### ISSUE THREAD

**Issue by FalloutBruhMoments** [danielkrupinski/Osiris#2319]
I've tried to import some configs for osiris but when i get into the game and try to load them, it doesn't work.
Most of the settings besides Misc, AA and Backtrack are completely default.
It may be because i'm trying to load configs that were made before a couple updates, but regardless this is annoying.

**Comment by zajkos** [comment]
mby these configs are to old osiris?>

**Comment by 0xb77a9** [comment]
yes, you can check if it is from an old Osiris version as @zajkos said
so on this situation, you can make a cfg from the new Osiris and compare it with the config you want to load and change anything that isn't in its place
