### ISSUE TITLE
Skinchanger Improvement 

### ISSUE THREAD

**Issue by EGTLoneWolf** [danielkrupinski/Osiris#232]
Can you sort the skin changer so only certain skins can fit on that specific weapon?

**Comment by effex1337** [comment]
custom skins are cool
he could add something like a checkbox for custom skins which
makes it show the applicable skins when unchecked and all when checked or vice versa
e.g. gamesense.pub

**Comment by Flaam** [comment]
@EGTLoneWolf +1

**Comment by EGTLoneWolf** [comment]
> custom skins are cool
> he could add something like a checkbox for custom skins which
> makes it show the applicable skins when unchecked and all when checked or vice versa
> e.g. gamesense.pub

it is cool . but it is not neat

**Comment by danielkrupinski** [comment]
Now you can search skins for certain weapon.
