### ISSUE TITLE
Weapon Revealer

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#2320]
Suggestion

![](https://i.imgur.com/B3WuD7n.png)

@danielkrupinski

**Comment by anarbmw** [comment]
@dapaster what hack is that?

**Comment by thisisprettyepic** [comment]
> @dapaster what hack is that?
 it’s a skeet lua

**Comment by DEVjeSucks** [comment]
its pretty cool, never saw it before

**Comment by wemanzoz** [comment]
yes, i want this to happen

**Comment by grey-stack** [comment]
this would be cool
