### ISSUE TITLE
[IDEA] Custom glow style

### ISSUE THREAD

**Issue by nikita-tarasov3** [danielkrupinski/Osiris#2323]
I have new idea for glow:
**Custom glow style** is change the thickness of the glow.
It make again glow customizable.
But the styles of glow (Default, Rim3d, Edge, Edge Pulse) will remain.

**Comment by danielkrupinski** [comment]
Just change alpha of glow color.

**Comment by nikita-tarasov3** [comment]
> Just change alpha of glow color.

Ok. I try it late.
