### ISSUE TITLE
[IDEA] Auto queue

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#2325]
**Auto queue** will useful when you was kicked or boosting rank.
It will offer which gamemode will auto queue.

**Comment by nikita-tarasov3** [comment]
@danielkrupinski Concept:
![MS Paint _ Microsoft Paint Online-1](https://user-images.githubusercontent.com/53124843/99291465-4cc34c80-2859-11eb-8d16-d3cf004fd745.png)
