### ISSUE TITLE
[IDEA] Movement recorder

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#2326]
**Movement recorder (like walkbot)**: will record, stop, play with key and without key (auto i.e repeat instant) _choosed movement_.
Will also record jump.
This feature will usefull for boosting prime.
@danielkrupinski Add please it and make my idea better.

Concept: 
![MS Paint _ Microsoft Paint Online](https://user-images.githubusercontent.com/53124843/99288144-9d847680-2854-11eb-8edb-2c94c7102045.png)

**Comment by DEVjeSucks** [comment]
just... why

**Comment by wemanzoz** [comment]
yes, now we can do sick vent tops and movemints

**Comment by 0xb77a9** [comment]
Make sure to check this https://github.com/danielkrupinski/Osiris/pull/2054

**Comment by sheavyq** [comment]
> Make sure to check this #2054

:)

> Make sure to check this #2054

:)

**Comment by sheavyq** [comment]
> Make sure to check this #2054

:)
