### ISSUE TITLE
Cant hit headshots with backtrack enabled

### ISSUE THREAD

**Issue by MrClue** [danielkrupinski/Osiris#2328]
Anyone else notice that you almost cant hit a headshot while backtrack is enabled?

If anyone got a fix for this, please share :)

**Comment by Curiouss312** [comment]
that dosent happen to me did u did any changes to backtrack?

**Comment by MrClue** [comment]
Im using default source, no changes.

**Comment by 0xb77a9** [comment]
maybe the other player uses legit aa

**Comment by zyrexbr** [comment]
yep having same issues

**Comment by MrClue** [comment]
> maybe the other player uses legit aa

i dont think bots playing on my local server are using legit aa >_>

**Comment by 0xb77a9** [comment]
LMFAO
try to make the aimbot aim at the BT not he player
or any tick between them

**Comment by MrClue** [comment]
> LMFAO
> try to make the aimbot aim at the BT not he player
> or any tick between them
 
LMFAO are you retarded? How about you stop changing the subject of the issue. And for the record, I am not using aimbot, I AM ONLY TALKING ABOUT BACKTRACK.

**Comment by MrClue** [comment]
bump
