### ISSUE TITLE
Need help compiling and editing

### ISSUE THREAD

**Issue by SAmme064** [danielkrupinski/Osiris#2332]
I downloaded the repository and opened it in vs19. I changed the gui style to 1 in config.h so it will start in one window from start. and i removed a couple of tabs in "renderGUIstyle2". But the tabs i removed still shows up in game. How????

**Comment by SAmme064** [comment]
Like i can change everything but when i compile and inject nothing happens like wtf

**Comment by SAmme064** [comment]
An update. It does compile etc. So i tried to change which button to open the menu with in config.h. I set it to shift. but you still opened and closed the menu with insert. But why

**Comment by 0xb77a9** [comment]
I can't get it good
can you explain what do you want to do
like removing the GUI or making the other GUI as default
if you still need help, make sure to DM me BETA#0530
