### ISSUE TITLE
VAC's/Untrusted

### ISSUE THREAD

**Issue by allynier** [danielkrupinski/Osiris#2334]
So im curious, and i need a little help, My accounts keep getting vac banned or untrusted but my friend who uses all my stuff isnt getting it, so im curious as to why this is? im using a custom injector, not the best but i learnt how to make a simple loadlibrary one. any ideas would be appreciated!

**Comment by VuBrian22** [comment]
From what I can see, you may have a detected injector. You say that your injector is a simple load-library one. I'm assuming it doesn't have the VAC DLL bypass check. That may be the case.

**Comment by allynier** [comment]
> From what I can see, you may have a detected injector. You say that your injector is a simple load-library one. I'm assuming it doesn't have the VAC DLL bypass check. That may be the case.

what would be the best way to implement a VAC DLL bypass check?

**Comment by VuBrian22** [comment]
You can use Daniel's OneByteLdr found here: https://github.com/danielkrupinski/OneByteLdr in your own injector. Or, alternatively you can download an injector that's pretty undetected and popular with the DLL check bypass already implemented. The name of that injector is [CSGhost v2.6](https://www.unknowncheats.me/forum/cs-go-releases/408519-csghost-v2-trusted-bypassing-injector.html)

**Comment by Scui1** [comment]
Another very good way would be to add "-allow_third_party_software" to csgo start params and just use cheat engine to inject the dll
