### ISSUE TITLE
Adding visual desync to Anti Aim (help)

### ISSUE THREAD

**Issue by LocalRabbi** [danielkrupinski/Osiris#2335]
`void AntiAim::run(UserCmd* cmd, const Vector& previousViewAngles, const Vector& currentViewAngles, bool& sendPacket) noexcept
{
    if (config->antiAim.enabled) {
        if (!localPlayer)
            return;

        if (config->antiAim.pitch && cmd->viewangles.x == currentViewAngles.x)
            cmd->viewangles.x = config->antiAim.pitchAngle;

        if (config->antiAim.yaw && !sendPacket && cmd->viewangles.y == currentViewAngles.y) {
            cmd->viewangles.y += localPlayer->getMaxDesyncAngle();
            if (fabsf(cmd->sidemove) < 5.0f) {
                if (cmd->buttons & UserCmd::IN_DUCK)
                    cmd->sidemove = cmd->tickCount & 1 ? 3.25f : -3.25f;
                else
                    cmd->sidemove = cmd->tickCount & 1 ? 1.1f : -1.1f;
            }
        }
    }
}`

Thats the code in Osiris. I want it to show the anti aim, but I dont know what to do or where to put it! Please help.

**Comment by 0xb77a9** [comment]
I think chams.cpp

**Comment by 0xb77a9** [comment]
or Hooks.cpp

**Comment by debooga** [comment]
I recommend following [this](https://www.learncpp.com/) link.
