### ISSUE TITLE
[Help] Untrusted bans

### ISSUE THREAD

**Issue by Flaam** [danielkrupinski/Osiris#234]
I play non-prime with my friends with this cheat, i added junkcode. We have the same dll, the same injector and the same config. Why i got like 4/5 untrusted bans and them only 1?

**Comment by NexSqaud** [comment]
junkcode AA?

**Comment by Flaam** [comment]
@NexSqaud ?

**Comment by Flaam** [comment]
@NexSqaud what do u mean

**Comment by NexSqaud** [comment]
You added Anti-aim to osiris?

**Comment by Flaam** [comment]
@NexSqaud no the source is the same, no changes to the hacks, i only added junkcode

**Comment by NexSqaud** [comment]
What a junkcode added?

**Comment by Flaam** [comment]
@NexSqaud i use a site called junkcode.gethaxelt.in

**Comment by NexSqaud** [comment]
https://void.to/Thread-STRANGE-UNTRUSTED-BAN

**Comment by NexSqaud** [comment]
Junkcode useless, osiris not detected. Your injector can be detected.

**Comment by Flaam** [comment]
@NexSqaud im using process hacker, but the thing is that my friends got banned only once

**Comment by NexSqaud** [comment]
ahhaha process hacker detected

**Comment by Flaam** [comment]
@NexSqaud what you think is better for injecting?

**Comment by NexSqaud** [comment]
I use [Inflame](https://github.com/danielkrupinski/Inflame)

**Comment by Flaam** [comment]
@NexSqaud how can i make it undetected

**Comment by Flaam** [comment]
Ok thank you Nex for helping me. I will try later

**Comment by NexSqaud** [comment]
Fasm size about 3MB.

**Comment by Flaam** [comment]
@NexSqaud last question, how can i install fasm?

**Comment by NexSqaud** [comment]
google -> fasm
