### ISSUE TITLE
Sound tab

### ISSUE THREAD

**Issue by marka117** [danielkrupinski/Osiris#2340]
I was trying to use the sound tab and I realized that on the new version of osiris the sound tab doesn't show anything except the local player configurations. So I am asking is this some mistake or is this a problem with sv_pure (Sorry if I am wrong).
Have a nice day.

**Comment by caiocinel** [comment]
What would be the source code for your sound window?

**Comment by marka117** [comment]
The normal code from here.

**Comment by caiocinel** [comment]
You said you made some changes to the code, what would they be? I ran tests and everything worked perfectly.
