### ISSUE TITLE
Show WASD keys on screen

### ISSUE THREAD

**Issue by 0xb77a9** [danielkrupinski/Osiris#2343]
Title explains everything
if you can help me please add me BETA#0530

**Comment by franiodat** [comment]
You can make this with `interfaces->surface` or `ImDrawList`, just check when `UserCmd::IN_FORWARD, UserCmd::IN_BACK, UserCmd::IN_MOVELEFT, UserCmd::IN_MOVERIGHT` and next draw text and filled rectangles in the corner of the screen. 

sry for my bad english xd

**Comment by 0xb77a9** [comment]
Thanks!
i wish if you can make a repo with this
