### ISSUE TITLE
[REQUEST] Movement Features.

### ISSUE THREAD

**Issue by antoninsz** [danielkrupinski/Osiris#2345]
My suggestion is to add movement features, like edgebug, jumpbug, long jump, etc...

**Comment by 0xb77a9** [comment]
Hey!
I can help you on some features
I already made (jumpbug, edgebug). currently I’m not on my pc but i can send them later
If u would like you can DM on discord (BETA#0530)

Thanks.

**Comment by DEVjeSucks** [comment]
Jumpbug #1829
[REQUEST] Edgebug #2158
[REQUEST] velocity graph/line #2235

just why don't you search for it
