### ISSUE TITLE
Esp font

### ISSUE THREAD

**Issue by thisisprettyepic** [danielkrupinski/Osiris#2346]
I’m new to visual studio and would like to know how to change the font of the esp (names etc)

**Comment by 0xb77a9** [comment]
You want to change name or font and name

**Comment by thisisprettyepic** [comment]
Just the font itself of the ESP as I don’t find it to be very nice looking

**Comment by caiocinel** [comment]
https://github.com/danielkrupinski/Osiris/blob/d41c876f41ff2a49b7793fc457863869341efdf5/Osiris/GUI.cpp#L50

Here is the line where you can add new files in .TTF, don't forget to declare in all the necessary places afterwards!
