### ISSUE TITLE
Visual Studio error while compiling (vc142.pdb)

### ISSUE THREAD

**Issue by AmazingHvH** [danielkrupinski/Osiris#2348]
Fatal error c1033 - Cannot open program database (Visual Studio 2019)

Cannot open program database "C://.../.../osiris/debug/vc142.pdb
Any help in solver this error?

**Comment by VuBrian22** [comment]
Compile in Release mode and not Debug. Otherwise if you have to compile Osiris in Debug mode than delete the .pdb file and reload the .sln project and recompile again.

**Comment by AmazingHvH** [comment]
@VuBrian22 Thanks, it works.
