### ISSUE TITLE
Can´t inject Osiris

### ISSUE THREAD

**Issue by voltexde** [danielkrupinski/Osiris#2349]
Hello Osiris Community,

i can´t inject osiris. I get every time this error and if i try to inject with Manual Map the game crash.

![osirisfail](https://user-images.githubusercontent.com/45499032/100392617-74739b00-3037-11eb-8bc1-454494ebf104.PNG)

**Comment by DEVjeSucks** [comment]
so I build rando injector with 200 lines of junkcode, put it in the same file with Osiris and With .exe file

https://anonfiles.com/d2IfBetfp5/RandoInjector_exe

hope that fixs it

**Comment by caiocinel** [comment]
> i can´t inject osiris. I get every time this error and if i try to inject with Manual Map the game crash.
make sure that the Extreme Injector is using "Manual Map", LoadLibrary usually results in this error, but it is always worth mentioning that there are several history of detections using the Extreme Injector.


> so I build rando injector with 200 lines of junkcode, put it in the same file with Osiris and With .exe file
Congratulations on making a poorly optimized project! Junkcode does not help at all, if using it makes you more "safe", you are using a placebo.

**Comment by Khajiitos** [comment]
> so I build rando injector with 200 lines of junkcode, put it in the same file with Osiris and With .exe file
> 
> https://anonfiles.com/d2IfBetfp5/RandoInjector_exe
> 
> hope that fixs it

By the way; Rando injector uses Load Library and it doesn't work with Trusted Mode, however you can run it from the Windows directory and it will work fine

**Comment by igre3zy** [comment]
bro just use sazzinjector ive been using it with osiris for so long and never got a vac

**Comment by caiocinel** [comment]
https://steamcommunity.com/id/cailloubackup


ehh

>
