### ISSUE TITLE
Hitsound 

### ISSUE THREAD

**Issue by EGTLoneWolf** [danielkrupinski/Osiris#235]
I tried to replace the hitsound to buttons\arena_switch_press_02 but it didn't work ... can some1 help me?

- Can you add hitmarker now that u have added hitsound? ( Please make adjustable size )

**Comment by Flaam** [comment]
+1 for the hitmarker thing
If you can add different types of sounds.

**Comment by NexSqaud** [comment]
adjust game master sound to adjust hitsound.
hitSound function in Misc.h
``` c++
if (config.misc.hitSound && interfaces.engine->isInGame()
			&& !strcmp(event->getName(), "player_hurt")
			&& interfaces.engine->getPlayerForUserID(event->getInt("attacker")) == interfaces.engine->getLocalPlayer()) {
			switch (config.misc.hitSoundType) {
			case 0:
				interfaces.engine->clientCmdUnrestricted("play physics/metal/metal_solid_impact_bullet2");
				break;
			case 1:
				interfaces.engine->clientCmdUnrestricted("play buttons/arena_switch_press_02");
				break;
			case 2:
				interfaces.engine->clientCmdUnrestricted("play training/timer_bell");
				break;
			}
		}
```
renderMiscWindow line 450
``` c++
                ImGui::Checkbox("Hit sound", &config.misc.hitSound);
		ImGui::Combo("Hit Sound", &config.misc.hitSoundType, "Metal\0Gamesense\0Bell\0");
```
config.h line 173
``` c++
                bool hitSound{ false };
		int hitSoundType{ 0 };
```

**Comment by EGTLoneWolf** [comment]
> adjust game master sound to adjust hitsound.
> hitSound function in Misc.h
> 
> ```c++
> if (config.misc.hitSound && interfaces.engine->isInGame()
> 			&& !strcmp(event->getName(), "player_hurt")
> 			&& interfaces.engine->getPlayerForUserID(event->getInt("attacker")) == interfaces.engine->getLocalPlayer()) {
> 			switch (config.misc.hitSoundType) {
> 			case 0:
> 				interfaces.engine->clientCmdUnrestricted("play physics/metal/metal_solid_impact_bullet2");
> 				break;
> 			case 1:
> 				interfaces.engine->clientCmdUnrestricted("play buttons/arena_switch_press_02");
> 				break;
> 			case 2:
> 				interfaces.engine->clientCmdUnrestricted("play training/timer_bell");
> 				break;
> 			}
> 		}
> ```
> 
> renderMiscWindow line 450
> 
> ```c++
>                 ImGui::Checkbox("Hit sound", &config.misc.hitSound);
> 		ImGui::Combo("Hit Sound", &config.misc.hitSoundType, "Metal\0Gamesense\0Bell\0");
> ```
> 
> config.h line 173
> 
> ```c++
>                 bool hitSound{ false };
> 		int hitSoundType{ 0 };
> ```

Thanks !!

**Comment by ViniciusSchifferGuedes** [comment]
is that a way to put hitsound only on granades? it dont feels worthy on weapons

**Comment by effex1337** [comment]
I have the codea for nades only as well.
If you want i can give when I'm on my PC

**Comment by effex1337** [comment]
But seriously who puts hitsound on nade only

**Comment by Shaxzy** [comment]
That’s a new one. Never heard of someone wanting hitsound on nades only through my 4 years of csgo cheating lmao

**Comment by effex1337** [comment]
Yeah XD

**Comment by danielkrupinski** [comment]
Added those sounds. If you've got more sounds post them here.

**Comment by NexSqaud** [comment]
weapon/party_horn_01 - killsound :D
weapon/lowammo_01
physics/rubber/ball_impact_a_02
physics/glass/glass_impact_bullet1
physics/plastic/plastic_box_impact_bullet1
