### ISSUE TITLE
Can't inject Osiris 2

### ISSUE THREAD

**Issue by trashcuff** [danielkrupinski/Osiris#2350]
I use process hacker, when i inject the newest build of the dll nothing happens

**Comment by franiodat** [comment]
try csghost  or something

**Comment by franiodat** [comment]
process hacker has inject func, but this is not a injector

**Comment by trashcuff** [comment]
> process hacker has inject func, but this is not a injector

it has worked for me with osiris in the past tho

**Comment by veikkop** [comment]
csgo has started to block processhacker so it doesnt work

**Comment by trashcuff** [comment]
yeah seems like it, i am using sazinjector now

**Comment by caiocinel** [comment]
If your problem has been resolved close the issue, it helps to keep things in order.

**Comment by debooga** [comment]
**For anyone reading this issue:** This may be caused by load library injectors, just use a manual mapping one.
