### ISSUE TITLE
2 questions about ' new ' osiris

### ISSUE THREAD

**Issue by unnamed01X** [danielkrupinski/Osiris#2352]
**1.** is that possible (after recent changes about linux etc.), to inject the osiris on windows? and if yes, how it will work etc.
**2.** what injector do you recommend? about 2 years ago i used rando with tone of junkcode, i had untrusted only once after like couple of months with the same signature. Since july i used 'load-lib-injector-master', with simple junkcode, it was fine but since a week im getting untrusted banned on expensive accounts. 
The source of Osiris with self changes is really good cheat for legit/semi, but i got a problem with injector, like i would not like to use a public one exe or something, i would like to have the 'self own' injector, like rando had (with source code that i can add junkcode and stuff.

Thanks for your attention, I hope for a nice conversation at the bottom that would help in solving my problem. 
_(sorry for my bad english grammar etc, im working on it)_
**_Have a nice weekend!_**

@danielkrupinski @support @community

**Comment by danielkrupinski** [comment]
There is no changes to the Windows version and it still will be the primary development platform.

**Comment by unnamed01X** [comment]
So the changes to the Linux code do not in any way affect the use of Osiris on Windows right?
Could someone help me to resolve second question? :)

**Comment by SwagsRGB** [comment]
I personally use SazInjector. It has an auto update feature and the dev is quite active. I dont think your "no public injector" stigma will take you any longer, as less and less public injectors are being updated, especially since osiris doesnt work with manual map injection; it needs load lib injection. So old "self own" injectors start to give untrusted. I'd advice using SazInjector.

**Comment by unnamed01X** [comment]
> I personally use SazInjector. It has an auto update feature and the dev is quite active. I dont think your "no public injector" stigma will take you any longer, as less and less public injectors are being updated, especially since osiris doesnt work with manual map injection; it needs load lib injection. So old "self own" injectors start to give untrusted. I'd advice using SazInjector.

where do you downloading it from? and how about updates? who doing that?
i can test it actually, but i don't think it will be safe for a long because a lot of people use that

**Comment by unnamed01X** [comment]
I would like to hear other users' opinions about injectors etc.

**Comment by VuBrian22** [comment]
I personally use an injector called CSGhost, however many have recently reported getting untrusted bans with the injector so I'm questioning its undetectablility,

**Comment by caiocinel** [comment]
1. I have used several tests with injectors and arrived at:

ExtremeInjector: banned
SazInjector: banned
load-lib-injector-master: banned
CSGhost: banned
Private: normal

Public injectors are not very reliable as far as I can tell.

2. Junkcode is useless, forget that crap.

3. Github is not a cheating community, the second question should have been asked on some other site (UC, MPGH) as it has no relation to the development itself.

**Comment by unnamed01X** [comment]
> 1. I have used several tests with injectors and arrived at:
> 
> ExtremeInjector: banned
> SazInjector: banned
> load-lib-injector-master: banned
> CSGhost: banned
> Private: normal
> 
> Public injectors are not very reliable as far as I can tell.
> 
> 1. Junkcode is useless, forget that crap.
> 2. Github is not a cheating community, the second question should have been asked on some other site (UC, MPGH) as it has no relation to the development itself.

thank's for that nice answer. I would like to have my own private injector, but my pasting/coding skills are not on that level i can make it 100% alone. I tried many times to change things etc. in sources, most of them i did without any help, but anyways, it's not that easy for me, i need to learn more and more to do it alone
