### ISSUE TITLE
Text color in Tab

### ISSUE THREAD

**Issue by DEVjeSucks** [danielkrupinski/Osiris#2353]
hi, im kinda dumb and I cant find where to change text  color only in tabs, not whole text in menu, someone who could give me a small hint ? thx

**Comment by ny-4** [comment]
```
ImGui::PushStyleColor(ImGuiCol_Text);
// draw menu tabs...
ImGui::PopStyleColor();
```

**Comment by DEVjeSucks** [comment]
thanks

**Comment by caiocinel** [comment]
> thanks

If an issue is resolved, close it, it helps to keep it organized.

**Comment by DEVjeSucks** [comment]
> > thanks
> 
> If an issue is resolved, close it, it helps to keep it organized.

ah yes, sorry forgot about that
