### ISSUE TITLE
I need undetected injector (loader) for my community

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#2354]
hi, i need a injector for my community
I would need the injector to be able to fill a file with different email addresses. those addresses would be the active users
If the email is in the list, the user can load the cheat, if it is not in the list, the program gives an error message
I can pay for its development by paypal

**Comment by VuBrian22** [comment]
This is a community for the Osiris cheat and anything directly related to it only. Send your request elsewhere like on unknowncheats or something. Make your own. Depending on how you would store those email addressees, it could be pretty simple, if ofc you don't mind security and people trying to reverse engineer it.

**Comment by wemanzoz** [comment]
did you mean loader?

**Comment by TauCSGO** [comment]
> did you mean loader?

Yes

**Comment by caiocinel** [comment]
> > did you mean loader?
> 
> Yes

I suggest that you read a little before leaving creating accounts on internet sites, close this issue, it only harms Osiris even though it has no relationship with him.

**Comment by TauCSGO** [comment]
> > > did you mean loader?
> > 
> > 
> > Yes
> 
> I suggest that you read a little before leaving creating accounts on internet sites, close this issue, it only harms Osiris even though it has no relationship with him.

If you do not provide solutions, shut up

**Comment by VuBrian22** [comment]
> > > > did you mean loader?
> > > 
> > > 
> > > Yes
> > 
> > 
> > I suggest that you read a little before leaving creating accounts on internet sites, close this issue, it only harms Osiris even though it has no relationship with him.
> 
> If you do not provide solutions, shut up

I'd actually agree what @caiocinel is saying is true. Your search for finding a willing dev on here to do that request for you is dead as far as I'm concerned. This issue will be buried with all the other unnecessary issues that is repo has. Considering @caiocinel has actually contributed to this repo, I'd think twice about disrespecting a fellow developer. That's just my word of thought :/

**Comment by TauCSGO** [comment]
> I'd actually agree what @caiocinel is saying is true. Your search for finding a willing dev on here to do that request for you is pretty much dead as far as I'm concerned. This issue will be buried with all the other unnecessary issues that this repo has. Considering @caiocinel has actually contributed to this repo, I'd think twice about disrespecting a fellow developer. That's just my word of thought :/ EDIT: You've also made really redundant issue posts in the past so this one's no exception. Again, please close this Issue.

Your opinion does not interest me
This topic is for anyone interested to answer.

(Blocked)
