### ISSUE TITLE
[request] multiple hitboxes

### ISSUE THREAD

**Issue by thisisprettyepic** [danielkrupinski/Osiris#2356]
Still haven’t seen this added to the cheat even though it’s pretty much a must for a legit cheat, adding multiple hitboxes for aimbot & triggerbot like a checkmark or something instead of just one hitbox or ’all’

**Comment by nikita-tarasov3** [comment]
> Still haven’t seen this added to the cheat even though it’s pretty much a must for a legit cheat, adding multiple hitboxes for aimbot & triggerbot like a checkmark or something instead of just one hitbox or ’all’

Great idea!

**Comment by zajkos** [comment]
#1750

**Comment by notgoodusename** [comment]
> #1750

doesnt do anything to the aimbot

**Comment by MrClue** [comment]
Just look at how he implemented the current hitbox, and add another one? Easy.

**Comment by thisisprettyepic** [comment]
> Just look at how he implemented the current hitbox, and add another one? Easy.

That’s not the point though, I’m saying that it should be implemented into the cheat itself as a standard feature.
