### ISSUE TITLE
When debugging it crashes.

### ISSUE THREAD

**Issue by degeneratehyperbola** [danielkrupinski/Osiris#2361]
I compile in debug, inject and die.
Regardless of advanced instruction set.
My processor is Ryzen 5 2500u, it supports AVX, AVX2 and SSE, yet none of them work.
Tried /MTd and /MDd - nothing.

**Comment by franiodat** [comment]
you inject only dll or dll + vs debugger

**Comment by degeneratehyperbola** [comment]
The thing is that I would inject DLL first and attach the debugger afterwards. But because DLL crashes the game when compiled in debug i can't attach it :(
Also i can't really use release for debugging because it doesn't do breakpoints just shows the address violation.

**Comment by danielkrupinski** [comment]
1. Attach debugger before injecting.
2. Do not use manual map injector for debug dll.

**Comment by debooga** [comment]
Are you injecting an unmodified Osiris DLL? Some forks and pull requests are known to crash very often.

**Comment by degeneratehyperbola** [comment]
It does not seem to matter whether you attach the debugger before or after injection.
But anyway, indeed using loadlibrary it doesn't crash and i can safely attach the debugger afterwards, thank you!
