### ISSUE TITLE
New CSGO update

### ISSUE THREAD

**Issue by lordeternity000** [danielkrupinski/Osiris#2363]
Is osiris undetected after the new update?

**Comment by EzekielCloud** [comment]
Please dont ever use it on your main account + I suggest you use osiris together with Daniel's Vac Bypass Loader which can be found  [here](https://github.com/danielkrupinski/VAC-Bypass-Loader)

**Comment by Scui1** [comment]
> 
> 
> Please dont ever use it on your main account + I suggest you use osiris together with Daniel's Vac Bypass Loader which can be found [here](https://github.com/danielkrupinski/VAC-Bypass-Loader)

Don't listen to him, osiris is very undetected. Im using it on my main account with 10k inventory, who needs this shit vac bypass? It's undetected without "vac bypass" axaxaxa

**Comment by lordeternity000** [comment]
Vac bypass is detected. I used on a prime accnt with good trust factor. It turned red immediately. It got vac banned on this august vac wave.I used the same injector before and after on another accnt it worked fine which means injector was undetected.  Osiris is perfect without vac bypass and junk code.

**Comment by mjlin1334** [comment]
> > Please dont ever use it on your main account + I suggest you use osiris together with Daniel's Vac Bypass Loader which can be found [here](https://github.com/danielkrupinski/VAC-Bypass-Loader)
> 
> Don't listen to him, osiris is very undetected. Im using it on my main account with 10k inventory, who needs this shit vac bypass? It's undetected without "vac bypass" axaxaxa

can you send me your injector? i use my injector(https://github.com/AMATEURZ1337/load-lib-injector) then i got 2acc vac banned without vac bypass!

**Comment by wemanzoz** [comment]
> > > Please dont ever use it on your main account + I suggest you use osiris together with Daniel's Vac Bypass Loader which can be found [here](https://github.com/danielkrupinski/VAC-Bypass-Loader)
> > 
> > 
> > Don't listen to him, osiris is very undetected. Im using it on my main account with 10k inventory, who needs this shit vac bypass? It's undetected without "vac bypass" axaxaxa
> 
> can you send me your injector? i use my injector(https://github.com/AMATEURZ1337/load-lib-injector) then i got 2acc vac banned without vac bypass!

loadlib is long detected, i use csghost + vacbypass loader

**Comment by igre3zy** [comment]
osiris is very undetected. Ive been using it with sazzinjector and never gotten a VAC. It really depends on if your injector is detected or not.
