### ISSUE TITLE
Disable aimbot for specific weapon

### ISSUE THREAD

**Issue by NexSqaud** [danielkrupinski/Osiris#237]
Add function to disable aimbot for specific weapon. For example: I want to enable aimbot for all weapon, but not for AWP.

**Comment by NexSqaud** [comment]
That takes a lot of time.

**Comment by Flaam** [comment]
@NexSqaud i've done it yesterday and, yes, you are right

**Comment by danielkrupinski** [comment]
Check "Enabled" on AWP and leave fov set to 0.

**Comment by NexSqaud** [comment]
For sure! As I immediately did not guess
