### ISSUE TITLE
Bomb Timer Not working

### ISSUE THREAD

**Issue by smurfsmfc** [danielkrupinski/Osiris#2370]
I guess the bomb timer ain't workin maybe there's a issue inside it please fix it guyz.
Thanks

**Comment by 3Ld4D** [comment]
Use latest version.
Or manually add the latest commit.

**Comment by smurfsmfc** [comment]
Thanks mate.
One more question - can u add nearby and recent player invite spammer which invites nearby and recently played with players on a click in the lobby please brother 👍

**Comment by veikkop** [comment]
> Thanks mate.
> One more question - can u add nearby and recent player invite spammer which invites nearby and recently played with players on a click in the lobby please brother 👍

Shut up.
