### ISSUE TITLE
I cant write to sdk Osiris pls help me 

### ISSUE THREAD

**Issue by pixelsurf123** [danielkrupinski/Osiris#2373]
Who can write that code "		if ((g_LocalPlayer->m_fFlags() & FL_ONGROUND) && g_LocalPlayer->IsAlive()) if (g_Options.edge_bug && GetAsyncKeyState(g_Options.edge_bug_key)) cmd->buttons = 4;
		prediction->EndPrediction();" 

On sdk Osiris Please

**Comment by franiodat** [comment]
no one will help you, cuz you're lazy paster -_-

**Comment by daisuki333** [comment]
Here are some websites to help you:
www.learncpp.com - for learning c++
https://github.com/ValveSoftware/source-sdk-2013  - valve's source development kit for gaining some understanding
