### ISSUE TITLE
[request]Draw ESP on localplayer

### ISSUE THREAD

**Issue by Frouk3** [danielkrupinski/Osiris#2374]
As title says

**Comment by danielkrupinski** [comment]
Why?

**Comment by Frouk3** [comment]
At the most popular cheats like Aimware,Onetap and etc. got esp on local player

**Comment by rosesware** [comment]
> At the most popular cheats like Aimware,Onetap and etc. got esp on local player

Why you need that if **Osiris** is a legit cheat.

**Comment by thisisprettyepic** [comment]
> > At the most popular cheats like Aimware,Onetap and etc. got esp on local player
> 
> Why you need that if **Osiris** is a legit cheat.

Well, it looks clean

**Comment by debooga** [comment]
In my opinion, it's useless even in rage cheats. Just use localPlayer chams.
