### ISSUE TITLE
VAC

### ISSUE THREAD

**Issue by FalloutBruhMoments** [danielkrupinski/Osiris#2376]
Is Inflame detected or is osiris?

**Comment by rosesware** [comment]
Your injector, close.

**Comment by squizzyv9** [comment]
use undetected injector or vac bypass

**Comment by FalloutBruhMoments** [comment]
> Your injector, close.

Inflame is literally the injector that Daniel says to use though, and he hasnt updated it.
I'm also manual mapping with CMD using inflame.


> use undetected injector or vac bypass

I am also using vac bypass

**Comment by Scui1** [comment]
vac bypass is detected, don't use it. I would recommend using osiris + extreme injector

**Comment by uzdiiilekk** [comment]
Vac bypass is not detected i use it on account with global elite on mm and prime and without ban lul

**Comment by FalloutBruhMoments** [comment]
> vac bypass is detected, don't use it. I would recommend using osiris + extreme injector

Are you retarded? extreme injector has been detected since fuckin 2016
