### ISSUE TITLE
Compiled Osiris.dll gets detected as Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by markojerry** [danielkrupinski/Osiris#2379]
Compiling the Source Code makes Windows Security alert me about it finding Trojan:Win32/Wacatac.B!ml in the compiled Osiris.dll File.

Any ideas why?

**Comment by caiocinel** [comment]
Make a program that terminates any process and send it for analysis, it will probably be detected, as Osiris is a loadable DLL, can be used maliciously, to fix this it is necessary to perform code signing, which solves most of these problems, making antivirus "trust" her.

**Comment by debooga** [comment]
Any cheating software may be detected as malware. Osiris is open-source and you are able verify if the software is safe yourself. **Never use compiled binaries of Osiris.**

**Comment by squizzyv9** [comment]
lol some shit defender problems

**Comment by caiocinel** [comment]
> lol some shit defender problems

This is definitely not a problem, it is essential for good security software.
