### ISSUE TITLE
[Help] Legit Config

### ISSUE THREAD

**Issue by Flaam** [danielkrupinski/Osiris#238]
Can someone send me a really good config for legit cheating? I have made one yesterday but isn't that legit.

**Comment by B0ruK** [comment]
is this p2c forum?

**Comment by ViniciusSchifferGuedes** [comment]
no esp, no glow, chams visible pam health, 2.5 fov(nearest), +15 smooth(variable), X = 0.3, Y = 1, no trigger, no backtrack, recoil crosshair, sniper crosshair, no blur, auto pistol on, for more legit just more smooth(keep  less than 100 points and -50% headshots)

**Comment by Flaam** [comment]
@B0ruK who asked for ur opinion

**Comment by Flaam** [comment]
@ViniciusSchifferGuedes thank you very much

**Comment by B0ruK** [comment]
> @B0ruK who asked for ur opinion

lol dont @ me child
