### ISSUE TITLE
Hooking

### ISSUE THREAD

**Issue by Tigerfy** [danielkrupinski/Osiris#2382]
What hooking method does Osiris use? And would osiris be undetected if I add junkcode and vm protect it?

**Comment by debooga** [comment]
**Readme says:** 

_MinHook_ - trampoline hook
_VmtHook_ - hook a function directly in a vtable
_VmtSwap_ - create a copy of a vtable and swap the pointer on the class instance

Junkcode and VM Protect might slow the detection detection, but there's still a big risk of getting detected. I recommend Daniel's VAC Bypass and some manual mapping injector for bypassing CS:GO's Trusted Mode. **You should not use Osiris on your main account.**

**Comment by yourmom-jpeg** [comment]
@debooga The VAC Bypass doesn't work anymore. I still get VAC errors

**Comment by debooga** [comment]
It does work but it doesn't prevent VAC errors which are server-sided.

**Comment by yourmom-jpeg** [comment]
Now I think opting out of the Steam beta really helped! Played two games
straight with Osiris with no issue. Don’t do the beta guys.

**Comment by caiocinel** [comment]
> Junkcode and VM Protect might slow the detection

I wanted to find out who was the first person who had this idea that junkcode is for something, it must be some joke.

**Comment by debooga** [comment]
> > Junkcode and VM Protect might slow the detection
> 
> I wanted to find out who was the first person who had this idea that junkcode is for something, it must be some joke.

Most of the signatures are the same so it doesn't do anything.

**Comment by debooga** [comment]
masterlooser15 made a few videos about hex editing and all that bullshit in 2017 and I'm surprised too that people think junk code does anything.

**Comment by Tigerfy** [comment]
Is process hacker 2 a manual mapping injector?

**Comment by caiocinel** [comment]
https://github.com/processhacker/processhacker/

Load Library

Em seg., 7 de dez. de 2020 às 10:39, Tigerfy <notifications@github.com>
escreveu:

**Comment by Tigerfy** [comment]
Alright, I have been using procces hacker for around a month and no problems. I just put dll in windows folder to bypass trusted mode. Would you consider it safe against vac?

**Comment by FalloutBruhMoments** [comment]
> @debooga The VAC Bypass doesn't work anymore. I still get VAC errors

Dont use the Anti Aim you will get vac authed every single time

**Comment by yourmom-jpeg** [comment]
I just opted out of the steam beta and it works fine

**Comment by debooga** [comment]
> > @debooga The VAC Bypass doesn't work anymore. I still get VAC errors
> 
> Dont use the Anti Aim you will get vac authed every single time

True, VAC bypass prevents cheat detection but it does not prevent VAC auth errors caused by not using anti-aim or high FOV aimbot without aimstep in deathmatch, casual, etc.
