### ISSUE TITLE
Suggestion: arrows for Offscreen esp

### ISSUE THREAD

**Issue by nikita-tarasov3** [danielkrupinski/Osiris#2383]
Suggestion: arrows for Offscreen esp + ability change colors, size
![arrows](https://user-images.githubusercontent.com/53124843/101365238-fc219b00-38bc-11eb-9e07-fa72656d3bba.PNG)

**Comment by thisisprettyepic** [comment]
Yeah arrows would look much nicer

**Comment by nikita-tarasov3** [comment]
> Yeah arrows would look much nicer

having multiple styles will be helpful

**Comment by debooga** [comment]
> Yeah arrows would look much nicer

bloat

**Comment by debooga** [comment]
> > Yeah arrows would look much nicer
> 
> having multiple styles will be helpful

bloat
