### ISSUE TITLE
[Request] Aimbot FOV Circle 

### ISSUE THREAD

**Issue by grey-stack** [danielkrupinski/Osiris#2384]
Please add an FOV circle with modifiable alpha (transparency) and colour values

**Comment by franiodat** [comment]
there is pull requests tab next to the issues tab -_- #2218

**Comment by egssy0** [comment]
Okay so theres bunch of Pulls about this "Not issue" issue. 
You can make it yourself too its too easy, if you can't theres bunch of forums you can get help.
**Close this issue.**

**Comment by tirziz** [comment]
#2218 check this out

**Comment by zwientje** [comment]
I thought github was for people that are coding or learning to code. why would you ask for extra features if there's plenty of information that you can use to implement such a thing yourself??? 

but I agree with @franiodat and @tirziz when they say to check out #2218 it works fine.
