### ISSUE TITLE
[Issue] Skinchanger

### ISSUE THREAD

**Issue by igre3zy** [danielkrupinski/Osiris#2386]
Anybody else experiencing issues with the skinchanger where you will pick up enemy or teamates guns and your skin will sometimes apply to it, other times it will be names, stickers, or stattrak. Is this an issue with me or is anybody else experiencing this?

**Comment by yourmom-jpeg** [comment]
I am. Doesn't bother me tho

**Comment by wemanzoz** [comment]
doesn't bother me lol

**Comment by danielkrupinski** [comment]
Should no longer happen.
