### ISSUE TITLE
[QUESTION] Can ayyware's ragebot work in Osiris

### ISSUE THREAD

**Issue by yourmom-jpeg** [danielkrupinski/Osiris#2388]
Hi Osiris community,

I am planning on making a fork of Osiris to implement [ayyware's ragebot ](https://github.com/dnkaUC/ayywareRemake/blob/master/AYYWARE%20CSGO/RageBot.cpp) because it is open-source like Osiris and have heard that it has a good ragebot. I also plan on adding some of its dependencies (like ayyware's resolver, autowall, etc.) and incorporate them into the modified Osiris project. I also plan on adding a tab in the menu so the user can adjust the settings to their liking. Would this work?

**Comment by KernCS** [comment]
I mean if you recode the features sure it's gonna work?
