### ISSUE TITLE
Is it possible to change the hooking method?

### ISSUE THREAD

**Issue by AverageShade** [danielkrupinski/Osiris#2394]
Apparently, VMThook is detected, would it be possible to change the hooking method or would it require me to do something such as recode the entire cheat? I am not too familiar with all of this.

**Comment by danielkrupinski** [comment]
Absolutely, [see Hooks.h](https://github.com/danielkrupinski/Osiris/blob/9ba275d18289e267b3808ddfc8b7159ce092f375/Osiris/Hooks.h#L24)

**Comment by AverageShade** [comment]
Sorry to inconvenience you with this, but would you have any guide or resource that you would recommend on something such as which hooking methods are suitable for this or what hooking methods are available? I am new to this and would like to learn more

**Comment by AverageShade** [comment]
> Absolutely, [see Hooks.h](https://github.com/danielkrupinski/Osiris/blob/9ba275d18289e267b3808ddfc8b7159ce092f375/Osiris/Hooks.h#L24)

Sorry to inconvenience you with this, but would you have any guide or resource that you would recommend on something such as which hooking methods are suitable for this or what hooking methods are available? I am new to this and would like to learn more

**Comment by AverageShade** [comment]
Nevermind, I took a look around and it seems like the guides and videos from Guided Hacking seems to have a lot of information regarding this, will look into it and see how far I can go.
