### ISSUE TITLE
Doesn't work when VAC is enabled

### ISSUE THREAD

**Issue by nice0x45** [danielkrupinski/Osiris#2395]
As stated in the title, when i launch CSGO without the -insecure flag and inject the DLL with Cheat Engine, the menu doesn't show up. Is there a way to change this?

**Comment by zwientje** [comment]
you're the same guy that opened the issue about the aimbot not shooting through walls... now this... you better move to a p2c type of thing if you ask these kind of questions.

anyway to answer the question:

1) you can use something like extreme injector or CSGhost that are publically available. (public means risk of detection)
2) you can create your own manual mapper (I suggest searching for examples on github but don't just copy paste it!!!!)

**Comment by debooga** [comment]
> you're the same guy that opened the issue about the aimbot not shooting through walls... now this... you better move to a p2c type of thing if you ask these kind of questions.
> 
> anyway to answer the question:
> 
> 1. you can use something like extreme injector or CSGhost that are publically available. (public means risk of detection)
> 2. you can create your own manual mapper (I suggest searching for examples on github but don't just copy paste it!!!!)

You think he can create his own injector? I know you're joking 😆.

**Comment by nice0x45** [comment]
> > you're the same guy that opened the issue about the aimbot not shooting through walls... now this... you better move to a p2c type of thing if you ask these kind of questions.
> > anyway to answer the question:
> > 
> > 1. you can use something like extreme injector or CSGhost that are publically available. (public means risk of detection)
> > 2. you can create your own manual mapper (I suggest searching for examples on github but don't just copy paste it!!!!)
> 
> You think he can create his own injector? I know you're joking 😆.

yeah, if i wasn't a fucking script kiddie that wants to flex on his friends I wouldn't be here begging for help in the first place. But i want to learn, can you maybe give me some pointers (pun intended) on where i should start?

**Comment by debooga** [comment]
Don't use public injectors if you don't want to get banned (if you don't care use something like Extreme Injector). I recommend following some tutorials on Youtube or using a public manual mapping injector with Daniel's VAC bypass.

**Comment by zwientje** [comment]
> > you're the same guy that opened the issue about the aimbot not shooting through walls... now this... you better move to a p2c type of thing if you ask these kind of questions.
> > anyway to answer the question:
> > 
> > 1. you can use something like extreme injector or CSGhost that are publically available. (public means risk of detection)
> > 2. you can create your own manual mapper (I suggest searching for examples on github but don't just copy paste it!!!!)
> 
> You think he can create his own injector? I know you're joking 😆.

It was a legit reply explaining his options. I assume he won't be trying option 2 but who knows, he might surprise us all ;)

**Comment by zwientje** [comment]
> > > you're the same guy that opened the issue about the aimbot not shooting through walls... now this... you better move to a p2c type of thing if you ask these kind of questions.
> > > anyway to answer the question:
> > > 
> > > 1. you can use something like extreme injector or CSGhost that are publically available. (public means risk of detection)
> > > 2. you can create your own manual mapper (I suggest searching for examples on github but don't just copy paste it!!!!)
> > 
> > 
> > You think he can create his own injector? I know you're joking 😆.
> 
> yeah, if i wasn't a fucking script kiddie that wants to flex on his friends I wouldn't be here crying for help in the first place. I thought that opening an issue here would magically solve my problem without any effort. But i want to learn enough to understand and maybe even improve this code, could you give me some pointers (pun intended) on where I should start?

Learning is a good thing! 
Github is a great place to help you with source code but if you don't know what it means you'll always remain a paster kid.

I started my journey at the guidedhacking forums learning the basics. maybe you should check it out.

**Comment by debooga** [comment]
We want to help you, but you have to put a bit of effort yourself.

**Comment by nice0x45** [comment]
So i investigated a bit (another pun) and it seems that csgo has something to do with DirectX9 which is a "set of graphics and physics programming interfaces" for windows. So should i learn that? Also do you have some recommendations for learning c++ in general? Im a python noob now.

**Comment by debooga** [comment]
Not really, I think you should start learning c++ basics and then stuff like pointers. Learning c++ is gonna  make you smarter 🧠. Try adding some features to Osiris without pasting them.

**Comment by caiocinel** [comment]
> Not really, I think you should start learning c++ basics and then stuff like pointers.

The first step is to forget about reverse engineering, if he doesn't know how to make a Hello World in cpp, he is far from knowing anything about memory.

Search the basics, then progressively go to the advanced, don't skip the steps.

**Comment by igre3zy** [comment]
i use sazz and its worked fine for years

**Comment by HowToMakeFaceitAB** [comment]
hello friend. it could take you up to 6 months to learn cpp by learning 1 chapter every day on learncpp.com

ofc my guess is you're not a complete loser sooo, instead of reading a mere 1 chapter every day, LEARN atleast 5 chapters every day and boom, you've got cpp in about a month or two! , but, ofc you have to practice and thoroughly understand what you're gonna learn PRACITICE MAKES PERFECT DONT FORGET THAT OK???

**Comment by nice0x45** [comment]
> hello friend. it could take you up to 6 months to learn cpp by learning 1 chapter every day on learncpp.com
> 
> ofc my guess is you're not a complete loser sooo, instead of reading a mere 1 chapter every day, LEARN atleast 5 chapters every day and boom, you've got cpp in about a month or two! , but, ofc you have to practice and thoroughly understand what you're gonna learn PRACITICE MAKES PERFECT DONT FORGET THAT OK???

Thanks my friend your speach was so inspiring to me that instead of learning a mere 5 chapters every day, i will learn 10.
