### ISSUE TITLE
Aimbot button is fixed for every type of gun

### ISSUE THREAD

**Issue by hungdz1234** [danielkrupinski/Osiris#2396]
Hi. With the old version of Osiris I used to assign aimbot key for rifle (AK, M4A4) is mouse1 and but for AWP is ALT.
But now after the last update I can only use mouse1 for all rifles. I cannot use separate button for rifles and AWP anymore
Can u fix pls

**Comment by danielkrupinski** [comment]
Why would you use mouse1 as an aimbot key?

**Comment by nikita-tarasov3** [comment]
> Why would you use mouse1 as an aimbot key?

Some people prefer use MOUSE1 for aimbot for legit gameplay

**Comment by debooga** [comment]
There's no need to use mouse1 as an aimbot key because aimbot aims while shooting if you have aimlock off.

**Comment by yourmom-jpeg** [comment]
Using mouse1 worked fine for me for a while while I used to use OTC. Really
hid the aimbot with a low FOV. That was before I knew right clicking gave
me more options

**Comment by debooga** [comment]
https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hacks/Aimbot.cpp#L164

You shouldn't bind it to mouse1, just look at the code.

**Comment by dz1102** [comment]
> Why would you use mouse1 as an aimbot key?

I know it's weird but I have low FOV aimbot for rifles so it's always safe for me to use it on mouse1. But can u tell me the reason why you fix the aimbot key? You used to let us choose separate key why you fix only 1 key now :(

**Comment by debooga** [comment]
its not a fixed key, it just aimbots while shooting. enable aimlock to aimbot even when youre not shooting and bind it to some key (but please, not mouse1, as it is useless)

**Comment by dz1102** [comment]
> its not a fixed key, it just aimbots while shooting. enable aimlock to aimbot even when youre not shooting and bind it to some key (but please, not mouse1, as it is useless)

I know. But I want to be legit so I don't use aimlock :)

**Comment by dz1102** [comment]
> Why would you use mouse1 as an aimbot key?

I hope u change it back and let us choose keys we prefer :) Tks

**Comment by debooga** [comment]
But if you bind it to mouse1 it does absolutely fucking nothing.

**Comment by 0xAB51NTH** [comment]
> There's no need to use mouse1 as an aimbot key because aimbot aims while shooting if you have aimlock off.

ayy but what if I want to aimlock. Then using a M1 is necessary.

**Comment by debooga** [comment]
Holy shit. Read the code.

**Comment by kalilc** [comment]
> > There's no need to use mouse1 as an aimbot key because aimbot aims while shooting if you have aimlock off.
> 
> ayy but what if I want to aimlock. Then using a M1 is necessary.

??????

**Comment by debooga** [comment]
???????????????????????????????????????????????????????????????????????????????????????????????????????????
