### ISSUE TITLE
Aimbot not shooting through walls

### ISSUE THREAD

**Issue by nice0x45** [danielkrupinski/Osiris#2398]
On Nuke, the aimbot doesn't shoot through the containers, even though the can be shot through, can this be fixed by changing the handleBulletPenetration calculation?

**Comment by Frouk3** [comment]
What is your minimum damage?

**Comment by nice0x45** [comment]
> What is your minimum damage?

My minimum damage is 1. If i just lower the damage reduction when the bullet goes through wall will it break the aimbot on other maps?

**Comment by Frouk3** [comment]
Are you off visible only?

**Comment by nice0x45** [comment]
> Are you off visible only?

Listen, i'm dumb, but not that dumb. Not trying to be rude or anything, but i could really use some help

**Comment by Frouk3** [comment]
Container its a prop maybe osiris aimbot dont shoot through prop
Maybe osiris aimbot shoots only through walls
Or osiris dont have that prop

**Comment by zwientje** [comment]
> > Are you off visible only?
> 
> Listen, i'm dumb, but not that dumb. Not trying to be rude or anything, but i could really use some help

Well then start by explaining the steps you have tried to troubleshoot this issue.
what have you done before opening this "issue"?

Since it's not mentioned in the first post, people assume you haven't done anything so it's reasonable to start by answering with the obvious solutions like "min damage" and "visible only" configs.

**Comment by zwientje** [comment]
oh and if you didn't know already... play around with the "anti aim" option ;) @nice0x45

**Comment by anarbmw** [comment]
why would u want osiris to aimbot through the walls? Are u using it for legit or what? It's not a rage or hvh cheat to do that(it does, but bad), and I think you have at least some skill to manually kill people through walls.

**Comment by nice0x45** [comment]
> why would u want osiris to aimbot through the walls? Are u using it for legit or what? It's not a rage or hvh cheat to do that(it does, but bad), and I think you have at least some skill to manually kill people through walls.

Looking at this issue in retrospective i agree that this is a bad question, I played against a spinbotter and he always killed me through walls. I was unable to fix it myself so i posted this question here, and i was informed that this is in fact not a bug, but rather a feature.
