### ISSUE TITLE
Guys! PLS! This problem really means a lot for me!

### ISSUE THREAD

**Issue by KastenTop** [danielkrupinski/Osiris#2403]
PLS Give me Osiris Discord! I deleted it yesterday from my list, and now I need it a lot! PLS!

**Comment by KastenTop** [comment]
I can't find it ANYWHERE

**Comment by KastenTop** [comment]
I also think Daniel should leave the link for it on github main page

**Comment by caiocinel** [comment]
Official Osiris discord? Scammers are increasingly sophisticated.

**Comment by debooga** [comment]
@caiocinel thats kinda sad, people sell open source software

**Comment by KastenTop** [comment]
> @caiocinel thats kinda sad, people sell open source software

no. It's just official Discord named "Osiris & GOESP team". They don't sell anything there, you can download the latest release there. Also, if ya know, where can I download the latest without ccompiling?

**Comment by debooga** [comment]
lmfao u probably goy ratted

**Comment by debooga** [comment]
danielkrupinski is the only coder and theres no "team". you can only download the source from github

**Comment by notgoodusename** [comment]
> no. It's just official Discord named "Osiris & GOESP team". They don't sell anything there, you can download the latest release there. Also, if ya know, where can I download the latest without ccompiling?

@playday3008 he is talking about your dc

**Comment by debooga** [comment]
hi @notgoodusename !

**Comment by notgoodusename** [comment]
> hi @notgoodusename !

hi

**Comment by playday3008** [comment]
bruh, https://discord.gg/xWEtQAn

**Comment by playday3008** [comment]
> Official Osiris discord? Scammers are increasingly sophisticated.

I never said and nowhere is it written that my server is official, and I don't sell anything

**Comment by playday3008** [comment]
Just compiling with GitHub Actions and pushing to Discord using webhooks

**Comment by playday3008** [comment]
sooo, close this pr

**Comment by debooga** [comment]
1. youre violating discord tos
2. this is free and open source software
3. people think its official because u made it look like it is
4. you can rat almost 2k people by just simply sending a malicious dll

**Comment by playday3008** [comment]
> 1. youre violating discord tos
> 2. this is free and open source software
> 3. people think its official because u made it to look like it is
> 4. you can rat almost 2k people by just simply sending a malicious dll

1. i know
2. and?
3. these are their problems
4. all compilation and sending script are public

**Comment by debooga** [comment]
its free software not because it doesnt cost money but because its free to modify

**Comment by debooga** [comment]
posting compiled dlls is defeating the whole purpose and is really unsafe

**Comment by debooga** [comment]
sadly daniel cant do anything about it

**Comment by playday3008** [comment]
mb 2% of 2k users from my server know what is C++, I just compile and publish dll to discord and some forums, who want to modify source can do it, bcoz under each publication there is a link to the repository
and why its unsafe?

**Comment by debooga** [comment]
osiris uses mit license and youre not violating it. im just saying that posting binaries is pointless and unsafe

**Comment by playday3008** [comment]
mb pointless bcoz its free, but why unsafe?

**Comment by debooga** [comment]
cheating software usually triggers antivirus software so people are used to disabling it while cheating. that is a problem though because your binaries can be modified in a malicious way. im not saying youre doing it but maybe some staff member is, you will never know.

**Comment by playday3008** [comment]
> cheating software usually triggers antivirus software so people are used to disabling it while cheating. that is a problem though because your binaries can be modified in a malicious way. im not saying youre doing it but maybe some staff member is, you will never know.

"but maybe some staff member is", sounds reasonable, but anybody can go to GitHub and download any zip from GitHub 
 Actions and check dll checksum, also the archives that are published on the server have checksum files that can be compared with files included into GitHub Actions artifacts and vice versa

**Comment by debooga** [comment]
youre right but people who download compiled binaries dont even know what checksums are

**Comment by playday3008** [comment]
True, but if you're paranoid then you can check every archive on the server, and by the way, only I have access to webhooks

**Comment by playday3008** [comment]
Better way, it's using link to GitHub Actions artifact instead of uploading archive, but I don't know how to do this

**Comment by playday3008** [comment]
Also, I have commits channel and GitHub reports to channel CI status, so publication and successes compilation message are synced
![image](https://user-images.githubusercontent.com/18056374/102516644-6261a700-408f-11eb-9e4e-ceb6f2773598.png)
![image](https://user-images.githubusercontent.com/18056374/102516662-6988b500-408f-11eb-9db6-bb748327ecd2.png)
