### ISSUE TITLE
Legit AA?

### ISSUE THREAD

**Issue by ItsTeo04** [danielkrupinski/Osiris#2404]
will ever legit aa be added

**Comment by Scui1** [comment]
yes, osiris has very good legit antiaim 😎

**Comment by ItsTeo04** [comment]
> yes, osiris has very good legit antiaim 😎

wait osiris has legit aa?
what is it called in menu i cant find it

**Comment by igre3zy** [comment]
> yes, osiris has very good legit antiaim 😎

its not very good, you cant switch your yaw, aka your real/fake angle. You can turn it on by enabling it and turning on yaw in the antiaim tab, then turing choked packets to 1 in the misc tab

**Comment by notgoodusename** [comment]
u need to fix it yourself
