### ISSUE TITLE
Where Can I Download or compile Osiris Beta?

### ISSUE THREAD

**Issue by KastenTop** [danielkrupinski/Osiris#2405]

**Comment by debooga** [comment]
osiris beta? whats that

**Comment by debooga** [comment]
youre probably talking about some osiris fork. youre not going to find help here

**Comment by yourmom-jpeg** [comment]
I don’t think we have a beta. I could be wrong

**Comment by debooga** [comment]
we dont, its just a fork which is called like that and people think its official

**Comment by tirziz** [comment]
what

**Comment by playday3008** [comment]
That's my fork, and it named "Osiris Beta" bcoz unstable shit, and now it's outdated from master brunch
