### ISSUE TITLE
A bug, Code for trash talk on kill, death, constant spam and some suggestions

### ISSUE THREAD

**Issue by effex1337** [danielkrupinski/Osiris#241]
Bugs : 
1. Chickens get a white cham when using glow (style 0)
2. Exclude sleeves in remove hand
3. Backtrack is very random
4. The blinking cham should have a color as all the other cheats have
5. Manual map injection didn't work for some reason in the latest update.

And some suggestions : 
(these are the ones i think a regular cheat should have)
ESP - 
1. HP bar
2. Weapon Esp
3. Ammo
4. Flags like (scoped, flashed, money, armor, bomb)
5. Grenade Predict
6. Implement CGrenadeApi
Source : https://github.com/Blick1337/GRENADE-API
Implementation Example : https://www.unknowncheats.me/forum/counterstrike-global-offensive/258976-grenade-helper.html

RCS - 
1. Standalone rcs

Chams - 
1. A better body for the cham (it looks like the chams are flat from a distance) or maybe shadows

Movement - 
1. Edge Jump
2. Directional Strafer

(these are like the cosmetic stuff)
Glow - 
1. Weapon and Hand Glow

Code for trash talk:
Misc.h
Kill Say : https://pastebin.com/jqasW8YS
Death Say : https://pastebin.com/A4Xyh6w4
Chat Spam : https://pastebin.com/Q3G1CceD

Config.h

>         bool killsay{ false };
>         bool deathSay{ false };
>         bool chatspam{ false};

GUI.cpp 
>ImGui::Checkbox("Trash talk on kill", &config.misc.killsay);
>ImGui::Checkbox("Trash talk on death", &config.misc.deathSay); 
>ImGui::Checkbox("Constant Spam", &config.misc.chatspam);
> if (config.misc.chatspam){
> config.misc.killsay = false;
> config.misc.deathSay = false;// this is because you might not want to flood
> }
> Chat spam could have been done better if there was a function for getting tick count.
> 
The edits are for styling because add code looked bad :/

**Comment by Flaam** [comment]
Wow nice work, thanks

**Comment by Flaam** [comment]
And yes, manual map is bugged, i tried to inject and game is crashing

**Comment by tirziz** [comment]
I think we should add C4 timer and location ( A or B ). It quite helpful

**Comment by effex1337** [comment]
Yeah i forgot that.

**Comment by NexSqaud** [comment]
And XQZ Chams

**Comment by effex1337** [comment]
Isnt xqz occluded chams?

**Comment by NexSqaud** [comment]
Normal chams: https://gyazo.com/8c8e67d60e3b2241da0c24c80bb5f885
XQZ Chams: https://i.imgur.com/RHM7dcG.png

**Comment by Shaxzy** [comment]
@effex1337 Thanks for for chat spamming code, highly appreciated!
Kill and death spam works like a charm, however I do get a compile error when I add the chatspammer. I have tried most things to resolve it but I simply can't.

With chat spam commented out:
https://gyazo.com/ad651014cc2c1727396f9c6273122609

With chat spam implemented:
https://gyazo.com/25e4077550aaf416e2e30bc03550f697

I am probably just blind. I haven't slept for 2 days..

**Comment by NexSqaud** [comment]
@Shaxzy 
1)please, dont make private cheat from public sources. 
2) learncpp.com - you need this
3) that spam method dont stabile, spam rate = fps.
```c++
static float lastSpamTime = 0.0f;
constexpr void Spam() noexcept
{
    if(lastSpamTime < memory.currenttime + 0.25f){
        interfaces.engine->clientCmdUnrestricted(@"say 'It's private cheat(free pasta)'");
        lastSpamTime = memory.currenttime;
    }
}
```

**Comment by effex1337** [comment]
@Shaxzy @NexSqaud 
Well I said that it could have been better if i had get tick count but i completely forgot that we had memory.currenttime. Thanks for that :)
But i don't really think it would cause too much fps drops.

**Comment by NexSqaud** [comment]
@effex1337 Yes, your method will not cause a large drop in FPS, just the spam rate will depend on FPS. And you calling this from FireEventClientSide? Seriuos? In this case, the spam rate depends on the events rate. More events - more spam. Few event - few spam.

**Comment by effex1337** [comment]
OK i actually face palmed myself when i re read the code i had just written killsay copied to death say then to constant spam after removing the death event. Thanks for reminding :)

**Comment by danielkrupinski** [comment]
1. Chicken glow works just fine.
2. "Fixed", corrected
3. I've just updated backtrack so give it a try.
4. Added.
5. It's problem with your injector, I can't really help you.

**Comment by B0ruK** [comment]
> 1. Chicken glow works just fine.
> 2. "Fixed", corrected
> 3. I've just updated backtrack so give it a try once more.
> 4. Added.
> 5. It's problem with your injector, I can't really help you.

amazing work also ignore people who treat you project like your some pay2cheat provider

**Comment by Shaxzy** [comment]
@NexSqaud Bruh it's not even a private cheat just because it says so. 0 IQ btw
I just changed a bunch of stuff and made it undetected for some friends. No money involved or anything like that, just to help them cheat without getting a ban.

**Comment by woah1337** [comment]
@danielkrupinski manual map doesn't work with bleak
https://github.com/Akaion/Bleak
Works with pretty much any other dll fine

**Comment by NexSqaud** [comment]
@woah1337 Manual map works for me. I using [Inflame](https://github.com/danielkrupinski/Inflame)
