### ISSUE TITLE
Crash with visibleOnly unchecked (Linux only?)

### ISSUE THREAD

**Issue by SM9CC** [danielkrupinski/Osiris#2412]
Hi, the cheat seems to crash with visibleOnly unchecked on Arch Linux, Could somebody please explain how I would attach a debugger in Clion so I can use break points and hopefully I will be able to give some more information.

It is probably happening somewhere in the canScan function.

Thank you.

**Comment by danielkrupinski** [comment]
Should not crash anymore.
