### ISSUE TITLE
Get current paintkit name

### ISSUE THREAD

**Issue by caiocinel** [danielkrupinski/Osiris#2416]
Hello, I would like to know some way to get the raw name of the skin equipped in SkinChanger because the only way I found is in initializeKits and it is still very poorly done and nothing optimized.

Ty

**Comment by danielkrupinski** [comment]
What do you mean by "raw name"?

**Comment by caiocinel** [comment]
I need to get the Paint Kit class for the skin I selected in the ListBox (to get the buffer), I've tested it with vector_index and paintkit, but they all return incorrect data.

![image](https://user-images.githubusercontent.com/60858720/102694186-3ca6e000-41fe-11eb-9938-2f8f8e7555db.png)

**Comment by caiocinel** [comment]
After some time I did the most intelligent thing, which is to define together when the skins are initialized.

![image](https://user-images.githubusercontent.com/60858720/102701570-03d72d00-4237-11eb-9255-263e2ed4e40d.png)

Btw, ty
