### ISSUE TITLE
how do i turn the customisable clantag in osiris into a permanent one

### ISSUE THREAD

**Issue by dwadawd7890** [danielkrupinski/Osiris#2417]
how do i make it so that when i check 'custom clantag' a premade clantag appears and you cant put your own custom one

**Comment by DEVjeSucks** [comment]
I changed code of clocktag to static (in my case animated) clantag, deleted custom clantag checkbox, and clocktag checkbox renamed to (my cheat name) clantag

**Comment by caiocinel** [comment]
> how do i make it so that when i check 'custom clantag' a premade clantag appears and you cant put your own custom one

https://github.com/danielkrupinski/Osiris/blob/d61b5de49c7d56abc497ca9cb8d0de1700e2f50d/Osiris/Config.h#L205
Set your clantag


https://github.com/danielkrupinski/Osiris/blob/d61b5de49c7d56abc497ca9cb8d0de1700e2f50d/Osiris/GUI.cpp#L1294
Add ImGuiItemFlags_Disabled flag to disable input.

**Comment by dwadawd7890** [comment]
> > how do i make it so that when i check 'custom clantag' a premade clantag appears and you cant put your own custom one
>
> https://github.com/danielkrupinski/Osiris/blob/d61b5de49c7d56abc497ca9cb8d0de1700e2f50d/Osiris/GUI.cpp#L1294
> 
> 
> Add ImGuiItemFlags_Disabled flag to disable input.

how do i do this?

**Comment by caiocinel** [comment]
`bool ImGui::InputText(const char* label, char* buf, size_t buf_size, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, void* user_data)`
In ImGui, flags are the 4th parameter, so you must pass them in 4th place:

 ` if (ImGui :: InputText ("", config-> misc.clanTag, sizeof (config-> misc.clanTag)))`

"" -> Parameter 1
"config-> misc.clanTag" -> Parameter 2
  "sizeof (config-> misc.clanTag)" -> Paramtro 3

Then just add a comma and the flag mentioned:

`if (ImGui::InputText("", config->misc.clanTag, sizeof(config->misc.clanTag),ImGuiItemFlags_Disabled )) `
