### ISSUE TITLE
Issue Compiling

### ISSUE THREAD

**Issue by beersud** [danielkrupinski/Osiris#2419]
When i tried to compile i got this issue
![Osiris-maste](https://user-images.githubusercontent.com/65162886/102699537-cc23b180-4245-11eb-91aa-5cb906107812.PNG)

**Comment by sonicrules11** [comment]
Did you modify the file?

**Comment by beersud** [comment]
nope

**Comment by caiocinel** [comment]
#2418

**Comment by beersud** [comment]
i added that and now it added more issues
![gg](https://user-images.githubusercontent.com/65162886/102701270-971f5b00-4255-11eb-9026-331536baed98.PNG)

**Comment by danielkrupinski** [comment]
Try after 8cb516a49b565ae31cdaed20a59023ae5d553880

**Comment by beersud** [comment]
It worked for me Thanks
