### ISSUE TITLE
When I load the settings file, the stickers do not appear.

### ISSUE THREAD

**Issue by sauranecs** [danielkrupinski/Osiris#2422]
My settings:
One Window
I am uploading a config file and the stickers are not showing.

The setting that fixes this problem is:
When the cheat menu opens, I open the "Skin changer" window. When the "Skin changer" window is open, I open the "Config" window and load my configuration file and the stickers are installed properly.

Sorry for the cooperation with Google Translate :)

**Comment by sauranecs** [comment]
There is no "Fade" option in butterfly knife skins, instead I choose "Glock-18 Fade". This is a temporary solution but it needs to be fixed.

**Comment by danielkrupinski** [comment]
The issue with loading is resolved as of 73a78007b58d4b16293807703e03fe8acbe78087

**Comment by sauranecs** [comment]
Butterfly knife "Fade" skin has been added? Thank you.
