### ISSUE TITLE
Unknown crash after few games in Dark Zone

### ISSUE THREAD

**Issue by nikita-tarasov3** [danielkrupinski/Osiris#2423]
Unknown crash after few games in Dark Zone.
@danielkrupinski Fix this crash please

**Comment by franiodat** [comment]
u can fix it on your own, just debug the process. 
The steps: 
1. download source code and compile it
2. run csgo and inject the cheat
3. In VS 2019 go to the debug section
4. click "Attach to Process..."
5. select csgo
6. go to the danger zone and play few games
7. when ur game crash u will see what line of code crashed
8. fix it yourself or post issue there.

**Comment by nikita-tarasov3** [comment]
> u can fix it on your own, just debug the process.
> The steps:
> 
> 1. download source code and compile it
> 2. run csgo and inject the cheat
> 3. In VS 2019 go to the **Debug** section
> 4. click **Attach to Process...**
> 5. select **csgo.exe**
> 6. go to the danger zone and play few games
> 7. when ur game crash u will see what line of code crashed
> 8. fix it yourself or post issue there.

For **Attach to Process** from visual studio its possible get vac ban?

**Comment by Khajiitos** [comment]
> For **Attach to Process** from visual studio its possible get vac ban?

No, at least from my/other's experience

**Comment by nikita-tarasov3** [comment]
> > For **Attach to Process** from visual studio its possible get vac ban?
> 
> No, at least from my/others' experience

Ok. I never did debug so I found out.
