### ISSUE TITLE
Anyone knows how to make proper custom model changer?

### ISSUE THREAD

**Issue by franiodat** [danielkrupinski/Osiris#2426]
Recently I was trying to do custom models myself, but I had huge problems with it. Sometimes custom model flicks in thirdperson, but nothing else. So if anyone can help me, please help me. I also saw this on UC: https://www.unknowncheats.me/forum/counterstrike-global-offensive/214919-precache-models.html but we have it already in Osiris. If you want to DM me or something here is my discord: `'-'#0581`

EDIT: ik that there were request and issues with this topic (#2033, #2005) but I couldn't find anything useful

**Comment by caiocinel** [comment]
Do you want to change the model of the localplayer or all players?

**Comment by franiodat** [comment]
Mainly I want to change weapon model and localPlayer model
