### ISSUE TITLE
Medal changer 

### ISSUE THREAD

**Issue by make82777** [danielkrupinski/Osiris#2434]
Any possibilities ?

**Comment by caiocinel** [comment]
I was messing with a profile changer for Osiris recently, and everything worked fine, maybe it might be possible, I'll take a look soon.

**Comment by thes4ns** [comment]
Ok , can you send the files of that Osiris here ? Thank you, in advance.

**Comment by caiocinel** [comment]
> Ok , can you send the files of that Osiris here ? Thank you, in advance.

#2503

**Comment by ishaangamer27** [comment]
wait osris has a profile changer like level changer or pins
