### ISSUE TITLE
VAC Auth when not using AA

### ISSUE THREAD

**Issue by FalloutBruhMoments** [danielkrupinski/Osiris#2436]
So, i know the anti aim is complete ass in this cheat, and if you use it in casual game modes you will get VAC Auth'd.

But i didnt, instead I aimed at the ground and jiggled my mouse a bit.

Can anyone confirm if that's what got me it? cuz i haven't ever had one of these before.

**Comment by igre3zy** [comment]
When in casual, put max angle delta to 30 or below. This will stop vac auths

**Comment by FalloutBruhMoments** [comment]
> When in casual, put max angle delta to 30 or below. This will stop vac auths

Im not using anti aim though, i just look at the ground and jiggle my mouse and use auto shoot w high FOV

unless this will help regardless
