### ISSUE TITLE
[Request] Bullet tracers

### ISSUE THREAD

**Issue by nikita-tarasov3** [danielkrupinski/Osiris#2437]
Bullet tracers for weapons. And many styles for bullet tracers like zeus, simple and etc. Even ability change colors for them.
Example:
https://youtube.com/watch?time_continue=7&v=QcDVx1AeZYg

**Comment by franiodat** [comment]
check this out: #1546 + my code: https://hastebin.com/olamihajon.php (I won't give u hooks.cpp, config.cpp and so on, cuz I don't want you to paste this)
