### ISSUE TITLE
Doesn't do anything on injection or it just crashes.

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#2438]
I don't know if I'm just dumb or something, but I did compile it, I made my own injector, tried other injectors, etc, even SasZ and it just wont inject. I already have proper knowledge of C++ and Visual Studio. I did put it on Release & X86. What am I doing wrong, if anything?

Edit: After some further looking, I noticed people suggested using manual mapping, but all that does is make it crash, any other suggestions?

**Comment by frionx** [comment]
I also noticed other people have this issue, but some don't.

**Comment by franiodat** [comment]
I don't have this issue, maybe i have older version of osiris. You can debug the process to find what line of code is crashing.
The steps:

1. download source code and compile it
2. run csgo and inject the cheat
3. In VS 2019 go to the **Debug** section
4. click **Attach to Process...**
5. select **csgo.exe**
6. when ur game crash u will see what line of code crashed
7. fix it yourself or post issue there.

**Comment by frionx** [comment]
> I don't have this issue, maybe i have older version of osiris. You can debug the process to find what line of code is crashing.
> The steps:
> 
> 1. download source code and compile it
> 2. run csgo and inject the cheat
> 3. In VS 2019 go to the **Debug** section
> 4. click **Attach to Process...**
> 5. select **csgo.exe**
> 6. when ur game crash u will see what line of code crashed
> 7. fix it yourself or post issue there.
> 
> or try with another injector
> (run ur game with **-insecure** mode)
I did that and it worked. Thanks.

**Comment by frionx** [comment]
> I don't have this issue, maybe i have older version of osiris. You can debug the process to find what line of code is crashing.
> The steps:
> 
> 1. download source code and compile it
> 2. run csgo and inject the cheat
> 3. In VS 2019 go to the **Debug** section
> 4. click **Attach to Process...**
> 5. select **csgo.exe**
> 6. when ur game crash u will see what line of code crashed
> 7. fix it yourself or post issue there.
> 
> or try with another injector
> (run ur game with **-insecure** mode)

I modified some stuff in the vs settings I shouldn't have messed with

**Comment by Thyanaz** [comment]
I have the same issue. I use manual mapping but it don't crash my game. It just do nothing. When i start the game with -insecure then the cheat is working. I used my own Injector btw. I tried 3 different Injectors with manual mapping and they did nothing too when i start the game normally. But i used sazlnjector with Load Library Injection and it just worked. Please help me do this in my own Injector. Thank you.

**Comment by mkot2** [comment]
> 
> 
> I have the same issue. I use manual mapping but it don't crash my game. It just do nothing. When i start the game with -insecure then the cheat is working. I used my own Injector btw. I tried 3 different Injectors with manual mapping and they did nothing too when i start the game normally. But i used sazlnjector with Load Library Injection and it just worked. Please help me do this in my own Injector. Thank you.

you need to bypass trusted mode, here's one: https://github.com/danielkrupinski/OneByteLdr
