### ISSUE TITLE
Skin Changer Crashes

### ISSUE THREAD

**Issue by kschou95** [danielkrupinski/Osiris#244]
Skin changer will cause csgo to crash when the tab is pressed.

**Comment by HeadlessCpp** [comment]
Did you load a config?

**Comment by kschou95** [comment]
yes, but skin changer settings is in default... but i think the problem is i compiled it in AVX2, i recompile it using SSE2 will not have the problem

**Comment by HeadlessCpp** [comment]
It doesn't matter if you haven't used it, if he added a variable the bytes after get shifted. This happened to me too but once I tried without a config it worked fine.
