### ISSUE TITLE
[Suggestion] Custom name

### ISSUE THREAD

**Issue by nikita-tarasov3** [danielkrupinski/Osiris#2440]
Custom name ingame (not name stealer).
I know this feature works in other source engine games.

**Comment by rosesware** [comment]
### Console:
`name (name you want)`

**Comment by nikita-tarasov3** [comment]
> ### Console:
> `name (name you want)`

no works

**Comment by Frouk3** [comment]
> ### Console:
> `name (name you want)`

first you need to enable and disable name stealer
and then you can type in console `name (name you want)`

**Comment by nikita-tarasov3** [comment]
> > ### Console:
> > `name (name you want)`
> 
> first you need to enable and disable name stealer
> and then you can type in console `name (name you want)`

Thx! I try later.

**Comment by nikita-tarasov3** [comment]
> > ### Console:
> > `name (name you want)`
> 
> first you need to enable and disable name stealer
> and then you can type in console `name (name you want)`

No works still. i found solution its feature Fake ban setup
