### ISSUE TITLE
[Question]How to debug

### ISSUE THREAD

**Issue by Cyk-Fad** [danielkrupinski/Osiris#2441]
I got a bug on Osiris.
I added some funtions on it.
But osiris is not a exe.It's a DLL
so I have no idea to debug.
Could you tell me the way to debug on DLL?
Thanks danie.

**Comment by franiodat** [comment]
you mean this?
1. download source code and compile it
2. run csgo and inject the cheat
3. In VS 2019 go to the **Debug** section
4. click **Attach to Process...**
5. select **csgo.exe**
6. when ur game crash u will see what line of code crashed

**Comment by Cyk-Fad** [comment]
> you mean this?
> 
> 1. download source code and compile it
> 2. run csgo and inject the cheat
> 3. In VS 2019 (or any version of vs) go to the **Debug** section
> 4. click **Attach to Process...**
> 5. select **csgo.exe**
> 6. when ur game crash u will see what line of code crashed

yes
do you have idea to do that?

**Comment by sonicrules11** [comment]
> > you mean this?
> > 
> > 1. download source code and compile it
> > 2. run csgo and inject the cheat
> > 3. In VS 2019 (or any version of vs) go to the **Debug** section
> > 4. click **Attach to Process...**
> > 5. select **csgo.exe**
> > 6. when ur game crash u will see what line of code crashed
> 
> yes
> do you have idea to do that?

They literally told you how to do it...

**Comment by Cyk-Fad** [comment]
but it's in fact that I can't get the line of code

**Comment by HowToMakeFaceitAB** [comment]
> but it's in fact that I can't get the line of code

all you have to do is : 
1.download visual studio
2.open your project in visual stdio(the .sln file)
3. try to compile, if it works then it works
4. if you encounter a glitch in-game, try debugging by hovering your mouse over debug in visual studio clicking Attach to process then select csgo and boom, if your game crashes then you will know what caused the crash:

ps: in the case your game doesn't crash which is presumably your problem,you're gonna have to go back to each line of code individually and if there are any reasons that could cause the cheat to bug out, but i recommend just reimplementing it carefully on another build because you clearly don't know anything about programming( I don't mean to be offensive)

**Comment by Cyk-Fad** [comment]
> > but it's in fact that I can't get the line of code
> 
> all you have to do is :
> 1.download visual studio
> 2.open your project in visual stdio(the .sln file)
> 3. try to compile, if it works then it works
> 4. if you encounter a glitch in-game, try debugging by hovering your mouse over debug in visual studio clicking Attach to process then select csgo and boom, if your game crashes then you will know what caused the crash:
> 
> ps: in the case your game doesn't crash which is presumably your problem,you're gonna have to go back to the stuff you implemented and check if there are any reasons that could cause the cheat to bug out, but i recommend just reimplementing it carefully on another build because you clearly don't know anything about programming( I don't mean to be offensive)

I injected the releasex86 DLL into csgo and csgo was crashed.
I got something not useful from vs2019 though I Attach to process.These messages aren't I want

**Comment by MrClue** [comment]
> > > but it's in fact that I can't get the line of code
> > 
> > 
> > all you have to do is :
> > 1.download visual studio
> > 2.open your project in visual stdio(the .sln file)
> > 3. try to compile, if it works then it works
> > 4. if you encounter a glitch in-game, try debugging by hovering your mouse over debug in visual studio clicking Attach to process then select csgo and boom, if your game crashes then you will know what caused the crash:
> > ps: in the case your game doesn't crash which is presumably your problem,you're gonna have to go back to the stuff you implemented and check if there are any reasons that could cause the cheat to bug out, but i recommend just reimplementing it carefully on another build because you clearly don't know anything about programming( I don't mean to be offensive)
> 
> I injected the releasex86 DLL into csgo and csgo was crashed.
> I got something not useful from vs2019 though I Attach to process.These messages aren't I want

Maybe show us what messages you got? A screenshot? Like we cant read your mind bro...

**Comment by jakubiakdev** [comment]
> I injected the releasex86 DLL into csgo and csgo was crashed.

Try to compile it as debug

**Comment by franiodat** [comment]
> > I injected the releasex86 DLL into csgo and csgo was crashed.
> 
> Try to compile it as debug

It must be in Debug x86!!!

**Comment by Cyk-Fad** [comment]
> > > I injected the releasex86 DLL into csgo and csgo was crashed.
> > 
> > 
> > Try to compile it as debug
> 
> It must be in Debug x86!!!

Oh in DEBUG x86 I can't inject.if I do, it will crash without any bug

**Comment by mkot2** [comment]
> 
> 
> > > > I injected the releasex86 DLL into csgo and csgo was crashed.
> > > 
> > > 
> > > Try to compile it as debug
> > 
> > 
> > It must be in Debug x86!!!
> 
> Oh in DEBUG x86 I can't inject.if I do, it will crash without any bug

Have the project set to debug x86. When you have it on debug x86, build the project. 
![obrázok](https://user-images.githubusercontent.com/31155321/103440056-d92ba200-4c42-11eb-9ded-c3c42fde8afe.png)
After you build it, you want to attach the VS debugger to CS:GO.
![obrázok](https://user-images.githubusercontent.com/31155321/103440098-2a3b9600-4c43-11eb-805a-93ddd62d5770.png)
Find "csgo.exe" on the list, click it and then click "Attach". A pop-up may appear that will ask you to restart Visual Studio in administrator mode. If that happens, you want to click "Restart" or "OK".
![obrázok](https://user-images.githubusercontent.com/31155321/103440121-5b1bcb00-4c43-11eb-92a2-28a2444e2bc5.png)
When the debugger is attached, you want to inject the Debug DLL in the <your project>/Debug folder. When the game crashes, the place where the error occured shoud show up in Visual Studio.

**Comment by hamad12a** [comment]
@mkot2 @HowToMakeFaceitAB  How to follow the same procedure on Linux?
