### ISSUE TITLE
Manual mapping doesn't do anything.

### ISSUE THREAD

**Issue by Thyanaz** [danielkrupinski/Osiris#2443]
I use manual mapping but it don't crash my game. It just do nothing. When i start the game with -insecure then the cheat is working. But when i am using old osiris dlls with the same Injector, cheat is working normally again.  I used my own Injector btw. I tried 3 different Injectors with manual mapping and they did nothing too. I used sazlnjector with Load Library Injection and it worked. Please help me do this in my own Injector. Thank you.

**Comment by Frouk3** [comment]
try to update Osiris and download csghost injector

**Comment by Thyanaz** [comment]
Thank you the Injector that you said is working but using my own Injector instead of a public Injector is more safer right ? I need help about this.
