### ISSUE TITLE
[Request] Head Level Indicator

### ISSUE THREAD

**Issue by WhatsupDanger** [danielkrupinski/Osiris#2447]
It would be a cool legit feature which will allow the user to always place their crosshair at head level.
this would help to aim better and if aimbot is set to priority HEAD then the crosshair wont flick directly to head, it will look like you're aming for head
also better crosshair placement = pro player
if you end up in overwatch they'll think you're smurfing (if doing legit cheating)

head over to this image to see what i'm talking about
https://imgur.com/LaYMWEM

watch this video for details
https://youtu.be/vO1ialrX9sg?t=479

**Comment by wemanzoz** [comment]
+
