### ISSUE TITLE
Sound issue in main menu [Possible Linux only issue]

### ISSUE THREAD

**Issue by sonicrules11** [danielkrupinski/Osiris#2448]
Whenever going back the the main menu your game repeats the `UI/panorama/bg_chlorine_01.wav` file and displays this error in console `Error: Total static audio channels have been used: 160 96, +UI/panorama/bg_chlorine_01.wav`

Its only happening while injected
https://streamable.com/db0agp

**Comment by JostBrand** [comment]
just set the volume of the soundfile to 0
