### ISSUE TITLE
[Bind Request] Chams, Glow & ESP (Toggle/ Hold)

### ISSUE THREAD

**Issue by ClaudiuHKS** [danielkrupinski/Osiris#2449]
Allowing people to set a key for the wall hacks would be really nice and easy to do.
Thanks!

**Comment by HowToMakeFaceitAB** [comment]
hey thats a genius idea

**Comment by nikita-tarasov3** [comment]
> Allowing people to set a key for the wall hacks would be really nice and easy to do.
> Thanks!

Will be usefull for legit gameplay for gamemodes with overwatch.

**Comment by danielkrupinski** [comment]
Added
