### ISSUE TITLE
Draw fov draws on the ground

### ISSUE THREAD

**Issue by effex1337** [danielkrupinski/Osiris#245]
> void Visuals::drawfov() noexcept
> {
> 	const auto [width, height] = interfaces.surface->getScreenSize();
> 	const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
> 	const auto activeWeapon = interfaces.entityList->getEntityFromHandle(localPlayer->getProperty<int>("m_hActiveWeapon"));
> 
> 	if (!interfaces.engine->isInGame())	return;
> 	if (!localPlayer->isAlive()) return;
> 	else
> 	{
> 		auto weaponIndex = getWeaponIndex(activeWeapon->getProperty<WeaponId>("m_iItemDefinitionIndex"));
> 		if (!weaponIndex)
> 			return;
> 		if (interfaces.engine->isInGame() && config.aimbot[weaponIndex].enabled)
> 		{
> 			float w2, h2;
> 			w2 = width / 2;
> 			h2 = height / 2;
> 
> 			float diagonal = sqrt(pow(width, 2) + pow(height, 2));
> 			float fov = (config.aimbot[weaponIndex].fov * (diagonal / 145.f)) /** diagonal*/;
> 			interfaces.surface->setDrawColor(config.extra.active_menu_theme_r, config.extra.active_menu_theme_g, config.extra.active_menu_theme_b, 255);
> 
> 			if (activeWeapon->isSniperRifle()) {
> 				if (localPlayer->getProperty<bool>("m_bIsScoped") == 1) {
> 					interfaces.surface->drawOutlinedCircle(w2, h2, fov * 2.72f, 50);
> 				}
> 				else if (localPlayer->getProperty<bool>("m_bIsScoped") == 2) {
> 					interfaces.surface->drawOutlinedCircle(w2, h2, fov * 8.16f, 50);
> 				}
> 				else
> 					interfaces.surface->drawOutlinedCircle(w2, h2, fov, 50);
> 			}
> 			else
> 				interfaces.surface->drawOutlinedCircle(w2, h2, fov, 50);
> 		}
> 	}
> }

This is my code for drawing aimbot fov.
Which i obviously didn't write by myself.

I created the needed weapon classes and the result are like the following.

![20190605120140_1](https://user-images.githubusercontent.com/48663440/59007549-b40f4d00-87db-11e9-9f3e-a55339ff6b8c.jpg)
![20190605120132_1](https://user-images.githubusercontent.com/48663440/59007550-b4a7e380-87db-11e9-8acd-afafbbbc97ac.jpg)
![20190605120136_1](https://user-images.githubusercontent.com/48663440/59007551-b4a7e380-87db-11e9-9338-2d50b6721718.jpg)

Any advise on how to draw in the middle of the screen?

**Comment by NexSqaud** [comment]
```c++
void Visuals::drawfov() noexcept
{
    const auto [width, height] = interfaces.surface->getScreenSize();
    const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
    if(!localPlayer) return;
    const auto activeWeapon = interfaces.entityList->getEntityFromHandle(localPlayer->getProperty("m_hActiveWeapon"));

    if (!interfaces.engine->isInGame()) return;
    if (!localPlayer->isAlive()) return;
    else
    {
    auto weaponIndex = getWeaponIndex(activeWeapon->getProperty("m_iItemDefinitionIndex"));
    if (!weaponIndex) return;
    if (!config.aimbot[weaponIndex].enabled) weaponIndex = 0; 
    if (config.aimbot[weaponIndex].enabled) // check IsInGame 2 times?
    {
    float w2, h2;
    w2 = width / 2;
    h2 = height / 2;

      	float diagonal = sqrt(pow(width, 2) + pow(height, 2));
      	float fov = (config.aimbot[weaponIndex].fov * (diagonal / 145.f)) /** diagonal*/;
      	interfaces.surface->setDrawColor(config.extra.active_menu_theme_r, config.extra.active_menu_theme_g, config.extra.active_menu_theme_b, 255);

      	if (activeWeapon->isSniperRifle()) {
      		if (localPlayer->getProperty<bool>("m_bIsScoped") == 1) { // bool == int ? what?
      			interfaces.surface->drawOutlinedCircle(w2, h2, fov * 2.72f, 50);
      		}
      		else if (localPlayer->getProperty<bool>("m_bIsScoped") == 2) { // bool == int? what?
      			interfaces.surface->drawOutlinedCircle(w2, h2, fov * 8.16f, 50);
      		}
      		else
      			interfaces.surface->drawOutlinedCircle(w2, h2, fov, 50);
      	}
            else
      		interfaces.surface->drawOutlinedCircle(w2, h2, fov, 50);
          }
    }
}
```

**Comment by effex1337** [comment]
Maybe @danielkrupinski could implement this in a correctly.
