### ISSUE TITLE
Features that could improve the cheat

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#2450]
1. allow us to bind esp/glow/chams so we can toggle it / hold it
2. Footstep esp : Incredibly legit feature and pretty helpful too, I think this definitely beats the esp feature draw while they're making noise because that feature gets kinda glitched out when someone shoots with an awp seeing the fact the awp has a long sound duration : https://www.youtube.com/watch?v=lqBxz0JzU7I
the feature(s) below is/are not necessary but would be helpful:

1. Standalone RCS(there is already a pull request for this so anyone can easily just use it)
 this is it for now, If you guys have any suggestions , feel free to post it below

**Comment by tirziz** [comment]
Auto buy bot. (for deathmatch and mm)

**Comment by mkot2** [comment]
> 
> 
> Auto buy bot. (for deathmatch and mm)

a buybot is only really useful in hvh

**Comment by HowToMakeFaceitAB** [comment]
yeah a buy bot isn't a helpful adition at all unless ur using the cheat for hvh purposes
