### ISSUE TITLE
[Help] Change Volume for Kill/Hit Sounds

### ISSUE THREAD

**Issue by grey-stack** [danielkrupinski/Osiris#2451]

**Comment by franiodat** [comment]
why??

**Comment by caiocinel** [comment]
https://github.com/danielkrupinski/Osiris/blob/097a48433c5153911a8fb4b9fdb998dc9402b389/Osiris/Hacks/Misc.cpp#L751

The sounds are simply commands executed in the game, their volume is linked to the volume of your game.

**Comment by franiodat** [comment]
if u want to use custom path, `PlaySoundA()` is a good way to do it. everything is there: **https://docs.microsoft.com/en-us/previous-versions/dd743680(v=vs.85)** 

_` btw @caiocinel u know how to do a weapon model changer? I just made player model changer, but idk how to change weapon models. `_

**Comment by caiocinel** [comment]
> _`btw @caiocinel u know how to do a weapon model changer? I just made player model changer, but idk how to change weapon models.`_

https://github.com/danielkrupinski/Osiris/blob/7fc91566d8f468aedeb8b0c6ace114726c0692d5/Osiris/Hacks/SkinChanger.cpp#L88

This should help you

**Comment by blackMasterLord** [comment]
```
void Misc::playHitSound(GameEvent& event) noexcept
{
    if (!config->misc.hitSound)
        return;

    if (!localPlayer)
        return;

    if (const auto localUserId = localPlayer->getUserId(); event.getInt("attacker") != localUserId || event.getInt("userid") == localUserId)
        return;

    constexpr std::array hitSounds{
        "physics/metal/metal_solid_impact_bullet2",
        "buttons/arena_switch_press_02",
        "training/timer_bell",
        "physics/glass/glass_impact_bullet1"
    };

    char sndbuffer[128] = "";

    if (static_cast<std::size_t>(config->misc.hitSound - 1) < hitSounds.size())
        sprintf_s(sndbuffer, "playvol \"%s.wav\" \"%.2f\"", hitSounds[config->misc.hitSound - 1], ((float)config->sound.hitSoundVolume / 100.0f));
    else if (config->misc.hitSound == 5)
        sprintf_s(sndbuffer, "playvol \"%s.wav\" \"%.2f\"", config->misc.customHitSound.c_str(), ((float)config->sound.hitSoundVolume / 100.0f));

    interfaces->engine->clientCmdUnrestricted(sndbuffer);
}
```
