### ISSUE TITLE
Easy Anti Cheat Bypass

### ISSUE THREAD

**Issue by PUREHAX** [danielkrupinski/Osiris#2452]
Would like to know if its possible to bypass Easy Anti Cheat

**Comment by caiocinel** [comment]
It was designed for VAC only.

**Comment by egssy0** [comment]
Wrong Project, Close this Issue

**Comment by franiodat** [comment]
Yep. Close this issue. EAC is a lot different than VAC.

**Comment by mkot2** [comment]
go ask on uc bro
