### ISSUE TITLE
[Suggestion] OppositeHandKnife

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#2453]
Instead of forcing cl_righthand we can just hook: C_BaseViewModel::ShouldFlipModel and then return whatever value we want.
This is the proper way of doing it.

Greetings 🥀

**Comment by MrClue** [comment]
Then do it and make a pull request?

**Comment by v45-0x8** [comment]
> Then do it and make a pull request?

Looks like you didn't read the thread name correctly, it's a "suggestion" if you don't know the definition of this word here you go: "an idea or plan put forward for consideration"

Greetings 🥀
