### ISSUE TITLE
[Suggestion] Fake friends

### ISSUE THREAD

**Issue by pointydev** [danielkrupinski/Osiris#2464]
Hey there,

Saw [this](https://www.unknowncheats.me/forum/counterstrike-global-offensive/311848-spoofing-friends-cs.html) on UC earlier and thought it'd be useful to have a way in Osiris to add "fake friends" into your friends list, as you can invite them as you would normal friends, even on limited accounts.

Currently the best you can do while limited is copy friend codes to each other and invite via the "add friend" dialog, which can be annoying and tedious if you want to play with multiple people quickly.

Thanks,
Pointy

**Comment by Lenteguppie** [comment]
This is a great idea, I'd like to see this implemented
