### ISSUE TITLE
Not Injecting

### ISSUE THREAD

**Issue by Android1337** [danielkrupinski/Osiris#2468]
Hi, Im built that source and tried to inject in my csgo game but is not doing anything I built release x86 and I tried differents injectors. What am I doing wrong?

**Comment by Tigerfy** [comment]
Same here with the new version cs:go just crash when I inject?

**Comment by mkot2** [comment]
it works just fine for me, use a loadlibrary injector and try running this: https://github.com/danielkrupinski/OneByteLdr before you inject

**Comment by Androigenius** [comment]
It worked Thank You!

**Comment by HowToMakeFaceitAB** [comment]
use a load lib injector , and when compiling with vs use release instead of debug

**Comment by mjlin1334** [comment]
> it works just fine for me, use a loadlibrary injector and try running this: https://github.com/danielkrupinski/OneByteLdr before you inject

OneByteLdr is before injecting or after injecting?

**Comment by Thyanaz** [comment]
Use that before injecting.
