### ISSUE TITLE
[Help] solving an unresolved external symbol

### ISSUE THREAD

**Issue by stacyonthatbeat** [danielkrupinski/Osiris#2473]
![image](https://user-images.githubusercontent.com/76887028/103467704-fac77f00-4d51-11eb-8e50-aa13a0bb6d63.png)

i really don't know how to fix this issue i got here, after i implemented daniel's most recent commits (2 Jan + 1 Jan) i had this and ive been stuck here for awhile :/

**Comment by caiocinel** [comment]
b4ca9c2041996436dd4d4f0954981d5d4f815bc4?

**Comment by danielkrupinski** [comment]
You're missing a definition of SkinChanger::getKnifeTypes() function.
