### ISSUE TITLE
please fix the animation butterfly knife

### ISSUE THREAD

**Issue by rosty022** [danielkrupinski/Osiris#2474]
please fix the animation butterfly knife

**Comment by danielkrupinski** [comment]
What's wrong with it?

**Comment by AlisaCiya** [comment]
If you press the left button of the mouse after pressing F and switch back to grab, it will trigger a reload

**Comment by rosty022** [comment]
> What's wrong with it?

when I click on f (that is, inspection or animation of the knife), then I have an animation as if I stick a knife in someone's back

**Comment by danielkrupinski** [comment]
@rosty022 Post a video with the issue and your skin changer knife settings.

**Comment by doggobot-owner** [comment]
this is not a cheat issue though, you can do it with default knife

**Comment by danielkrupinski** [comment]
Fixed in b4ca9c2041996436dd4d4f0954981d5d4f815bc4
