### ISSUE TITLE
How to manually set current weapon in code?

### ISSUE THREAD

**Issue by flowxrc** [danielkrupinski/Osiris#2477]
I've tried that:
ImGui::Checkbox("Enabled", &config->aimbot[6 ? 6 + 23 : 38].enabled); // 6 - currentWeapon (ssg-08)
it doesnt work

**Comment by blackMasterLord** [comment]
😐
`ImGui::Checkbox("Enabled", &config->aimbot[currentWeapon == 6 ? 23 : 38].enabled);`
