### ISSUE TITLE
Which injector is best for Osiris

### ISSUE THREAD

**Issue by Etherealand** [danielkrupinski/Osiris#2480]
I've tried a lot of injector, like csghostn,Since it is not open source, there may be Trojan，Is there an injector that is open source and will not be ban by vac?

**Comment by HowToMakeFaceitAB** [comment]
make your own or learn how to code basic stuff and paste it

**Comment by linuxer9** [comment]
I'm using process hacker 2 and I put the dll in windows folder.
I guess process hacker won't (ever?) trigger vac, since it's used by many people for legitimate purposes.
Also remember to use vac bypass.

**Comment by Etherealand** [comment]
@linuxer9 I'll try it,thanks

**Comment by Etherealand** [comment]
i got the Memject
