### ISSUE TITLE
[idea] skinchanger preview

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#2482]
will be good ngl

**Comment by HowToMakeFaceitAB** [comment]
nop, there are a ton of better features to add, add it yourself

**Comment by Scui1** [comment]
good idea and easy to implement, hopefully daniel won't be lazy this time :-)

**Comment by caiocinel** [comment]
I put a preview on my build, but it wasn't really worth it in compensation for the loss of performance, probably because I used filesystem instead of the paintkit URL.

https://github.com/danielkrupinski/Osiris/blob/c66d944452414cd65f0f719a68d7cbe50c9b1638/Osiris/SDK/ItemSchema.h#L132

**Comment by linuxer9** [comment]
I found the code that gets wepon png image in a leaked P2C, I'm not sure if it's ok to post it here
but the idea it get's the png image from "resource/flash/econ/weapons/base_weapons/" then converts it to texture using "D3DXCreateTextureFromFileInMemory"
the file isn't stored on drive but on memory and you retrieve it using VBaseFileSystem interface

**Comment by Scui1** [comment]
> 
> 
> I found the code that gets wepon png image in a leaked P2C, I'm not sure if it's ok to post it here
> but the idea it get's the png image from "resource/flash/econ/weapons/base_weapons/" then converts it to texture using "D3DXCreateTextureFromFileInMemory"
> the file isn't stored on drive but on memory and you retrieve it using VBaseFileSystem interface

Why would you need BaseFileSystem for that? It's possible without. 😎

**Comment by caiocinel** [comment]
> Why would you need BaseFileSystem for that? It's possible without.

As I said above, just use ItemSchema values.

Less suspense, more code.

**Comment by Scui1** [comment]
> 
> 
> > Why would you need BaseFileSystem for that? It's possible without.
> 
> As I said above, just use ItemSchema values.
> 
> Less suspense, more code.

If you were able to code properly, you would know that it's not more code 😉

**Comment by osirisbestlegitcheat** [comment]
That's a pretty good idea not ganna lie

**Comment by wemanzoz** [comment]
LETS GO HE ADDED IT, WE DID IT BOIS
