### ISSUE TITLE
Menu doesn't show up

### ISSUE THREAD

**Issue by degeneratehyperbola** [danielkrupinski/Osiris#2483]
Steps to reproduce:
1. Compile in debug
2. Run csgo.exe with -insecure argument
3. Use Xenos64 native injection with this configuration
![image](https://user-images.githubusercontent.com/65950527/104018589-b5c4a200-51c2-11eb-8236-cb925f4aa455.png)
4. Voila! Menu captures all inputs but fails to render.

**Comment by danielkrupinski** [comment]
Are you using third-party in-game overlays?

**Comment by degeneratehyperbola** [comment]
I am using vanilla CS:GO. Compiling in release did nothing, as well as using manual map injection with the release build.

**Comment by shakeit1337** [comment]
i have the same problem.

i start cs:go with -insecure and i see the menu 
but i start cs:go normaly without -insecure i dont see the menu.

i dont know why mhh

**Comment by caiocinel** [comment]
> i have the same problem.
> 
> i start cs:go with -insecure and i see the menu
> but i start cs:go normal without -insecure i dont see the menu.
> 
> i dont know why mhh

Use manualmap injection

**Comment by degeneratehyperbola** [comment]
I have found out something, Daniel's VAC Bypasser causes menu to fail to render. I haven't yet found out how to fix it though.
