### ISSUE TITLE
Aimbot is kinda different

### ISSUE THREAD

**Issue by hungdz1234** [danielkrupinski/Osiris#2484]
Hi. I know it's weird but I use mouse1 for pistol aimbot (cuz I play legit with low FOV) so basically whenever I press mouse1 the aimbot hit the target and that's enough for me (I don't hold the aimbot key to lock on target like most people do).

However, after your last update I realize that the new aimbot (2nd image) doesn't work as good as the old one (1st image). When I press mouse1 the new aimbot sometimes doesn't respond instantly. Sometimes I press 6 times and only 1 time the aimbot works. In the old version of Osiris the aimbot works perfectly everytime I press mouse1. 

I don't know about C++ so I don't know why you change the aimbot but I think the old DLL is better :) 

![old](https://user-images.githubusercontent.com/54879097/104026847-1c64b280-51f9-11eb-8722-f3643bd4e26f.png)
![new](https://user-images.githubusercontent.com/54879097/104027177-99902780-51f9-11eb-8c0d-b03565ccf3fa.png)

**Comment by dz1102** [comment]
And also please don't change the interface of aimbot so often (like the aimbot button). I have 15 different configs and everytime you change the aimbot interface I have to adjust my config because the aimbot button of the old config is no longer accepted...

**Comment by linuxer9** [comment]
disable on key, aimbot in general works only if you are shooting (providing that you don't toggle aimlock)
on the current aimbot, for pistols I set fov to 1.5 or below and smooth 1 (no between shots, no on key) and it's prettey good for deagle headshots (not 100% legit, so I use it situationally)
for rifles fov 3 and smoothness 10 or more, and add the [autostop feature](https://github.com/danielkrupinski/Osiris/pull/2411) if your movement is not so good

**Comment by dz1102** [comment]
> disable on key, aimbot in general works only if you are shooting (providing that you don't toggle aimlock)
> on the current aimbot, for pistols I set fov to 1.5 or below and smooth 1 (no between shots, no on key) and it's prettey good for deagle headshots (not 100% legit, so I use it situationally)
> for rifles fov 3 and smoothness 10 or more, and add the [autostop feature](https://github.com/danielkrupinski/Osiris/pull/2411) if your movement is not so good

Yeah I know. The problem is that with the old DLL of Osiris Deagle 1.5 FOV + smooth 1 hits perfectly while with the new DLL Deagle 1.5 FOV + smooth 1 sometimes doesn't hit.

**Comment by linuxer9** [comment]
> Yeah I know. The problem is that with the old DLL of Osiris Deagle 1.5 FOV + smooth 1 hits perfectly while with the new DLL Deagle 1.5 FOV + smooth 1 sometimes doesn't hit.

If you really want the old version, check the commit history of "aimbot.cpp" down to the date of your dll file, then take that old "aimbot.cpp" and "paste" it to the current version (of course you want to check variables names or config structure changes).

**Comment by hugohabicht01** [comment]
> for rifles fov 3 and smoothness 10 or more, and add the autostop feature if your movement is not so good
Tbh i wouldnt advise to use that if you're trying to play legit... FOV 3 and smoothness 10 is extremly blatant, everybody who is at least decent at the game will call you out...

**Comment by linuxer9** [comment]
> 
> 
> > for rifles fov 3 and smoothness 10 or more, and add the autostop feature if your movement is not so good
> 
> Tbh i wouldnt advise to use that if you're trying to play legit... FOV 3 and smoothness 10 is extremly blatant, everybody who is at least decent at the game will call you out...
yes you are correct, in the last few days I became used to maximum FOV of 1.5 and nearest bone,
I think this won't look fishy if you have good positioning and crosshair placement
