### ISSUE TITLE
Hello, i have a question about help with fixing an modified version of osiris

### ISSUE THREAD

**Issue by SluXzZ** [danielkrupinski/Osiris#2487]
Ive made an version with ragebot, anti aim, and much more but it needs an update its crashing sometimes and while holding smokes, etc. Ive added new item indexes and more but its still crashing. So my question is if i could get some help for it.
Best regards, sluxz

**Comment by Leak3611** [comment]
Have you tried debugging to see what is crashing you?

**Comment by SluXzZ** [comment]
So apparently if i debug the process it doesnt crash

**Comment by debooga** [comment]
Add me on Discord. debooger#0001

**Comment by SluXzZ** [comment]
I added you on discord

**Comment by linuxer9** [comment]
I took a look at your code before you deleted the repository, It looks like you use the code from this pull #1546 ? 
I use the same code and I have the same issue with random crashes when holding a smoke, I can't even inject a debug build, so if you got a solution for this issue would you please post it ?

**Comment by debooga** [comment]
It's a problem with grenade prediction - it uses nSkinz weapon indexes instead Osiris'. We forgot to fix it lmao.

**Comment by linuxer9** [comment]
> 
> 
> It's a problem with grenade prediction - it uses nSkinz weapon indexes instead Osiris'. We forgot to fix it lmao.

never mind, it was a problem with my weaponId.h I updated it and everything works
sorry for bothering you.
have a great day
