### ISSUE TITLE
My game lags whenever I use osiris.

### ISSUE THREAD

**Issue by 4melts** [danielkrupinski/Osiris#2488]
Hello! Not sure if this is happening to anyone else but when im playing with osiris sometimes when i switch weapons it doesnt switch only plays the sound and goes back to the weapon i just used before switching like its lagging or something? Is it happening to anyone else?

**Comment by linuxer9** [comment]
off topic: did you add any junk code to your build ? like those youtubers recommend?

**Comment by 4melts** [comment]
Why would I every do that?

**Comment by senisditron** [comment]
if your processor support avx2, maybe check this out #2456

**Comment by M3351AN** [comment]
Too high fake lag?
