### ISSUE TITLE
How to change animstate of one particular entity?

### ISSUE THREAD

**Issue by aezerboy** [danielkrupinski/Osiris#2489]
Working on a resolver that works by reading animstate and I was wondering how I would go about reading each individual entities animstate and then resolving them individually.

Currently I'm pretty sure I'm just reading info from the entity with the highest index and then applying my resolving method from that info to all of the other entities.

Thanks in advance

**Comment by Khajiitos** [comment]
`for (int i = 1; i < 65; i++) {
    Entity* entity = interfaces->entityList->getEntity();
    if (!entity)
        continue;

    AnimState* animState = entity->getAnimState();
}`

**Comment by notgoodusename** [comment]
you can create a func to resolve each entity individually, and then loop through them
