### ISSUE TITLE
Question about Detection

### ISSUE THREAD

**Issue by LuizDanG** [danielkrupinski/Osiris#249]
Hello Daniel, I have little question about hooking. 

Is actually detected vmt hooking in osiris? 
Or what about hooking some jmp or something? 

Thanks for answer.

**Comment by Nyarukocqc** [comment]
osiris use undetected vmt hook.

**Comment by cojo1989** [comment]
Anyway its your job to change the signature.

**Comment by LuizDanG** [comment]
I know how to change signature. 
But im so scared of the hooking, thats all.
