### ISSUE TITLE
Walkbot for osiris (i have source) 

### ISSUE THREAD

**Issue by uzdiiilekk** [danielkrupinski/Osiris#2491]
If you need i have walk bot source so i can give you it

**Comment by caiocinel** [comment]
If you want to make a contribution, make a pull request.

**Comment by uzdiiilekk** [comment]
This is not request i dont need it

**Comment by caiocinel** [comment]
> This is not request i dont need it

"Pull Request" is when you have a contribution to the project, it allows you to include it in the repository.

I recommend that you browse GitHub before starting to interact with the community, most of the things you post here are irreversible.
