### ISSUE TITLE
Some features are not working in Linux

### ISSUE THREAD

**Issue by Dr4iv3rNope** [danielkrupinski/Osiris#2493]
I have some issues with Osiris in Linux.

1. Edge jump is not working
2. Auto accept is crashing the game
3. Watermark, Spectator list are not draw text on the screen
4. Auto wall is not working
5. I can't bind to mouse 4, mouse 5

**These features works perfectly in windows**

**Comment by danielkrupinski** [comment]
"Auto accept" has been fixed (49573ddc2e41105f8cb5f7d56acba1fd831e0dcc) and you should now be able to bind MOUSE4 & MOUSE5 buttons (257ff4db8094fc5c27f74992c8b478b773d349d5).

**Comment by SM9CC** [comment]
Should probably be easy to fix https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hacks/Aimbot.cpp#L23, not sure why ASM is being used here tbh.
