### ISSUE TITLE
aimbot system is not the best for now..(idk)

### ISSUE THREAD

**Issue by yabedabedu786** [danielkrupinski/Osiris#2494]
can someone actually do a pull request RCS and old aimbot system for the latest version? thanks! :D 

if you guys don't mind, hopefully you guys can teach me too! 

i'm new here and sorry for the bad english, thank you!

**Comment by linuxer9** [comment]
there is a pull request for standalone RCS [here](https://github.com/danielkrupinski/Osiris/pull/2135)
IMO, the current aimbot is great for a legit player, just adjust each weapon minimum damage, fov and smoothing according to your play style.
also there is no legit aimbot would make a bad player a god, think of a legitbot like a training tool not a headshot machine with epic resolver.
also AFAIK, aimbot didn't change so much for a long time ago, the only thing that may have affected aimbot is the engine prediction, it's supposed to make the aimbot better.

**Comment by yabedabedu786** [comment]
so, it's means there's a no way to use old aimbot system in the latest version of osiris?

**Comment by debooga** [comment]
wdym with 'old aimbot'?

**Comment by yabedabedu786** [comment]
> wdym with 'old aimbot'?

for my opinion, aimbot is not functionally as well for the new version based on my opinion, sorry if i'm mistaken

**Comment by debooga** [comment]
it works exactly the same, only input system changed and its so much better

**Comment by yabedabedu786** [comment]
> it works exactly the same, only input system changed and its so much better

oh i see, but for me i don't know it's seems different and weird from my perspective, but that's okay i would try build a new osiris version later and find out by myself. thank you for helping me sir, appreciated!
