### ISSUE TITLE
[ Not a issue ] Help with custom weapon models

### ISSUE THREAD

**Issue by 4melts** [danielkrupinski/Osiris#2496]
So i've been trying a long time now, setup custom weapon models but I can't seem to do it. I tried and ended up scratching it. Could someone help me?

**Comment by linuxer9** [comment]
It's not that hard, first you need to bypass sv_pure (look here #1802 )
then [hook findmdl ](https://www.unknowncheats.me/forum/counterstrike-global-offensive/214760-hooking-findmdl.html)

**Comment by 4melts** [comment]
> It's not that hard, first you need to bypass sv_pure (look here #1802 )
> then [hook findmdl ](https://www.unknowncheats.me/forum/counterstrike-global-offensive/214760-hooking-findmdl.html)
> 

Yeah ik, but im unsure how to properly add hooking findmdl, adding to correct places

**Comment by tirziz** [comment]
take a look at riptide v3 source but I recommend you find another way instead of findmdl since it is wonky and not very effective.
