### ISSUE TITLE
how do I install it on Linux

### ISSUE THREAD

**Issue by ArnoldasMk** [danielkrupinski/Osiris#2501]
Hello, how do I install it on linux? Can anyone help me ? There's my specs:
```
vega@pop-os:~$ neofetch
             /////////////                vega@pop-os 
         /////////////////////            ----------- 
      ///////*767////////////////         OS: Pop!_OS 20.04 LTS x86_64 
    //////7676767676*//////////////       Kernel: 5.8.0-7630-generic 
   /////76767//7676767//////////////      Uptime: 11 hours, 57 mins 
  /////767676///*76767///////////////     Packages: 2661 (dpkg), 5 (flatpak) 
 ///////767676///76767.///7676*///////    Shell: bash 5.0.17 
/////////767676//76767///767676////////   Resolution: 2560x1440 
//////////76767676767////76767/////////   DE: Plasma 
///////////76767676//////7676//////////   WM: KWin 
////////////,7676,///////767///////////   WM Theme: Breeze 
/////////////*7676///////76////////////   Theme: Breeze Dark [Plasma], Breeze [GTK2/3] 
///////////////7676////////////////////   Icons: breeze-dark [Plasma], breeze-dark [GTK2/3] 
 ///////////////7676///767////////////    Terminal: konsole 
  //////////////////////'////////////     CPU: Intel i5-3450 (4) @ 3.500GHz 
   //////.7676767676767676767,//////      GPU: AMD ATI Radeon RX Vega 56/64 
    /////767676767676767676767/////       Memory: 7074MiB / 15957MiB 
      ///////////////////////////
         /////////////////////                                    
             /////////////                                        
```
Thank you!

**Comment by hugohabicht01** [comment]
I haven't tried it myself yet, but just took a look at .github/workflows/linux.yml
Apparently you need to install the following dependencies
sudo apt-get update && sudo apt-get install -y libsdl2-dev gcc-10 g++-10
then configure:
mkdir Release && cd Release && cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=gcc-10 -D 
and then compile:
cd Release && make -j $(nproc --all)

No clue how to inject tho. My guess would be that you could just attach gdb to the process and then use gdb to inject

**Comment by ArnoldasMk** [comment]
Hey, thanks! When I am trying to configure it outputs me this:
```
vega@pop-os:~/Osiris$ mkdir Release && cd Release && cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=gcc-10 -D CMAKE_CXX_COMPILER=g++-10 ..
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_C_COMPILER:

    gcc-10

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_CXX_COMPILER:

    g++-10

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/vega/Osiris/Release/CMakeFiles/CMakeOutput.log".
See also "/home/vega/Osiris/Release/CMakeFiles/CMakeError.log".
vega@pop-os:~/Osiris/Release$
```
Any clue how do I fix it?

**Comment by DrunkenBlyatHvH** [comment]
it looks like you miss a package

**Comment by DrunkenBlyatHvH** [comment]
CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_CXX_COMPILER:

    g++-10

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

// without a compiler compiling is kinda hard

**Comment by hugohabicht01** [comment]
well but if he followed the instructions i gave him gcc would be installed, its probably just not in the path. My best bet would  be to check if the gcc is in $PATH

**Comment by DrunkenBlyatHvH** [comment]
depends on his distro the package may called a different way so it would not be installed

**Comment by hugohabicht01** [comment]
since pop os is based on ubuntu, I highly doubt it.

**Comment by hugohabicht01** [comment]
Ok, I just compiled Osiris on Arch and was able to solve the problem by replacing g++-10 in the commands with just g++ and gcc-10 with just gcc. Worked for me

**Comment by juanjoayala01** [comment]
> Ok, I just compiled Osiris on Arch and was able to solve the problem by replacing g++-10 in the commands with just g++ and gcc-10 with just gcc. Worked for me

Hey, after what you solved i ran the make command line and go the libOsiris.so, then tried to inject it with the injector you forked in github i believe. Then a message of succesfully injected came in the console but nothing came up even if i press 'insert' key (focused on the CS:GO window). Are you familiar with this problem? Im using Manjaro distro, pretty much new to all this linux stuff, but still i think i followed all the instructions correcrtly.
i would really appreciate a reply from from you, thanks in advance.

**Comment by hugohabicht01** [comment]
ngl really no clue what to do in that case... it worked for me personally on arch and manjaro, tried it with i3, sway, gnome and KDE. Are you sure that you are actually pressing insert and not something else?

**Comment by juanjoayala01** [comment]
> ngl really no clue what to do in that case... it worked for me personally on arch and manjaro, tried it with i3, sway, gnome and KDE. Are you sure that you are actually pressing insert and not something else?

Just solved the issue! I had csgo installed in an external drive. I could run it, but not load .so files into it. Thanks anyway for the fast response man
