### ISSUE TITLE
[Problem] I get These weird errors when i launch the solution

### ISSUE THREAD

**Issue by gr1ndy** [danielkrupinski/Osiris#2506]
so like the title says, I get These weird errors when i launch the solution and its the first time i get them.

![bro_why](https://user-images.githubusercontent.com/71841362/105199285-4ac28600-5b47-11eb-9c44-c2e9a8a0277a.png)

**Comment by franiodat** [comment]
change your Windows SDK Version to newest installed (should be 10.0)

**Comment by franiodat** [comment]
and c++ version to newest

**Comment by franiodat** [comment]
also delete previous issue

**Comment by franiodat** [comment]
![e3](https://user-images.githubusercontent.com/73391151/105205552-adb31d80-5b45-11eb-893c-22dd6554fb51.PNG)

**Comment by gr1ndy** [comment]
i havent changed anything, i just loaded the solution got into gui.cpp and got all of those errors.

**Comment by gr1ndy** [comment]
it happens with every other source i have on my computer.

**Comment by franiodat** [comment]
btw I had similar issue, my fix that I did: reinstall vs 2019

**Comment by franiodat** [comment]
and those errors are appearing when u opening the project or when u are bulding the project?

**Comment by gr1ndy** [comment]
When I open it

**Comment by gr1ndy** [comment]
> btw I had similar issue, my fix that I did: reinstall vs 2019

imma try

**Comment by gr1ndy** [comment]
> btw I had similar issue, my fix that I did: reinstall vs 2019

it worked bro :) thanks

**Comment by franiodat** [comment]
> > btw I had similar issue, my fix that I did: reinstall vs 2019
> 
> it worked bro :) thanks

np :)
