### ISSUE TITLE
VAC Detected?

### ISSUE THREAD

**Issue by doggobot-owner** [danielkrupinski/Osiris#2508]
Just got VAC errored, can someone check is it detected?

**Comment by caiocinel** [comment]
VAC errors are not VAC bans, this can be caused if you have a very high Delta Angle in conjunction with a Silent Aimbot,

**Comment by franiodat** [comment]
make sure that your aimbot fov is lower than 8 and that you are using injector with VAC bypasser (BetaLoader, daniel's VAC bypass)

**Comment by Scui1** [comment]
> 
> 
> VAC errors are not VAC bans, this can be caused if you have a very high Delta Angle in conjunction with a Silent Aimbot,

that is also possible without silent aimbot :-)

**Comment by pablocs77** [comment]
yes

**Comment by igre3zy** [comment]
> make sure that your aimbot fov is lower than 8 and that you are using injector with VAC bypasser (BetaLoader, daniel's VAC bypass)

you don’t need to change your aimbot fov if you go to *misc* and change max angle delta to a number lower than 30
