### ISSUE TITLE
How to download Osrirs I'm new to this 

### ISSUE THREAD

**Issue by ishaangamer27** [danielkrupinski/Osiris#2509]
I've been using an old osrirs for a long time and want to start downloading from here since I can get the newest version but i dont know how to download it and want the ddl file not the code but i dont know where to download i know this may come of as me being stupid and just find it but i really just don't know

**Comment by franiodat** [comment]
click **Code** button and download zip file containing osiris folder, next, unzip it and open **.sln** solution file (you must install Visual Studio 2019 to do that https://visualstudio.microsoft.com/pl/downloads
![Przechwytywanie](https://user-images.githubusercontent.com/73391151/105318916-65871000-5bc4-11eb-979b-84440b8acf02.PNG)
) and when u opened it just compile it (**Ctrl + B**)

**Comment by linuxer9** [comment]
I advise you against downloading and using public binaries (i.e. dll's), you will getting banned within a few days; most of public dll got already sigged by vac.
as the comment above said, you should compile your own build, and preferably change or add features (see pull requests tab).

**Comment by franiodat** [comment]
to use updated osiris u must know basics of c++, IDE, compilers and stuff. it open source project and you should make your "custom" build with your preferences.

**Comment by ishaangamer27** [comment]
> click **Code** button and download zip file containing osiris folder, next, unzip it and open **.sln** solution file (you must install Visual Studio 2019 to do that https://visualstudio.microsoft.com/downloads) and when u opened it just compile it (**Ctrl + B**)
> ![Przechwytywanie](https://user-images.githubusercontent.com/73391151/105318916-65871000-5bc4-11eb-979b-84440b8acf02.PNG)

**Comment by ishaangamer27** [comment]
> I advise you against downloading and using public binaries (i.e. dll's), you will getting banned within a few days; most of public dll got already sigged by vac.
> as the comment above said, you should compile your own build, and preferably change or add features (see pull requests tab).

I don't know to make compile my own build i thought that i just need thecode and turn it into a ddl file and if it helps i use a vac bypasser?

**Comment by ishaangamer27** [comment]
> click **Code** button and download zip file containing osiris folder, next, unzip it and open **.sln** solution file (you must install Visual Studio 2019 to do that https://visualstudio.microsoft.com/downloads) and when u opened it just compile it (**Ctrl + B**)
> ![Przechwytywanie](https://user-images.githubusercontent.com/73391151/105318916-65871000-5bc4-11eb-979b-84440b8acf02.PNG)

I've tried doing this and its says successful but no ddl shows up idk what to do if you have a discord could you please contact me .noclipsishaan#8993

**Comment by 0xE232FE** [comment]
You easily download the Source Code with git!
`git clone https://github.com/danielkrupinski/Osiris`

**Comment by linuxer9** [comment]
> 
> 
> > click **Code** button and download zip file containing osiris folder, next, unzip it and open **.sln** solution file (you must install Visual Studio 2019 to do that https://visualstudio.microsoft.com/downloads) and when u opened it just compile it (**Ctrl + B**)
> > ![Przechwytywanie](https://user-images.githubusercontent.com/73391151/105318916-65871000-5bc4-11eb-979b-84440b8acf02.PNG)
> 
> I've tried doing this and its says successful ("Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped) but no ddl shows up idk what to do if you have a discord could you please contact me .noclipsishaan#8993

it will literally show you the path of that dll file , like this
```
1>Finished generating code
1>Osiris.vcxproj -> C:\Users\b\Documents\osiris\Release\Osiris.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
also check your anti-virus that may auto delete/quarantine the file, so disable it during the build or add exception

**Comment by CrazyCSIW6** [comment]
The build fails with 171 errors.
