### ISSUE TITLE
Engine Error

### ISSUE THREAD

**Issue by piterxyz** [danielkrupinski/Osiris#251]
So, I get errors like this:
"CL_CallPostDataUpdates: missing ent 546"
Labeled "Engine Error"

And how to fix it?

**Comment by Mufinekkk** [comment]
bump

**Comment by danielkrupinski** [comment]
Can't help you unless you post more information. This is game engine error, not caused diretly by the cheat.

**Comment by Mufinekkk** [comment]
It`s only do when I'm playing on casual community servers, I think this is an glove changer error. I dont have that on previous versions.

**Comment by danielkrupinski** [comment]
I've just updated glove changer. Please re-check if issue persists.
