### ISSUE TITLE
MaxClients

### ISSUE THREAD

**Issue by v45-0x8** [danielkrupinski/Osiris#2510]
Hello,
I'm just wondering why instead of using GlobalVars->maxClients u are using Engine->GetMaxClients()
e. g. in StealNames function u are using GlobalVars but everywhere else u are grabbing maxclients from Engine
As far i know there is no big difference between this but using GlobalVars would 'kinda' improve the fps.

Greetings 🥀

**Comment by Scui1** [comment]
omg man you're right, we're missing out a HUGE performance improvement here! 😆

**Comment by mkot2** [comment]
> 
> 
> omg man you're right, we're missing out a HUGE performance improvement here! 😆

why toxic bro
