### ISSUE TITLE
Osiris dll

### ISSUE THREAD

**Issue by igre3zy** [danielkrupinski/Osiris#2512]
First of all, no, i am not a newgen. I just don’t have a pc rn and my friend needs updated osiris. Could someone please compile the latest osiris as AVX2 and reply with your disc? thanks in advance

**Comment by doggobot-owner** [comment]
hey, i can send my own remade version with profile, fast ladder and other things, Pluto#1337, i dont have the original dll though

**Comment by linuxer9** [comment]
here it's with avx2 set
https://anonfiles.com/vdZ9y3B5p3/Osiris_dll
