### ISSUE TITLE
Suggestion: autoreconnect Matchmaking

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#2514]
Suggestion: autoreconnect Matchmaking

**Comment by Scui1** [comment]
wtf why do you need that? The game already has a button for it

**Comment by nikita-tarasov3** [comment]
> wtf why do you need that? The game already has a button for it

I meant autoreconnect

**Comment by Scui1** [comment]
useless af, please name a valid reason why someone should need this

**Comment by osirisbestlegitcheat** [comment]
Dont waste his time this idea alone is retarded

**Comment by osirisbestlegitcheat** [comment]
close it NOW
