### ISSUE TITLE
[Suggestion] Please add #2492 Location Spammer

### ISSUE THREAD

**Issue by smurfsmfc** [danielkrupinski/Osiris#2519]
Gyz i respect your work a lot but i just want suggest you to add #2492 on the code it can help get some important calls to the team when u dont have a mic. 

Please add if u really think its good and important.
And Respect gyz all working fine right now.

**Comment by doggobot-owner** [comment]
but its a ready code just put it into your build

**Comment by smurfsmfc** [comment]
I think it should officialy be on the build.

**Comment by KernCS** [comment]
My intentions with that pull was never to get it in to the main build, but i just wanted to make #2147 more clear:)

**Comment by smurfsmfc** [comment]
@KernCS man can we add invite spammer on the build ? its cool man.
