### ISSUE TITLE
Please correct the animation of the knives,I will be very happy, well, all other users

### ISSUE THREAD

**Issue by rosty022** [danielkrupinski/Osiris#2525]
Can you please fix the animation of the knives that are on the video (3 links below). Is it possible to make the animations of the knives as in the onetap v3 cheat? Because there are no knife animation lags at all and there are all the animations of each knife. More Tramp Knife and Paracord Knife need to be tweaked to Osiris.
https://oxy.st/d/cfhd
https://oxy.st/d/dfhd
https://oxy.st/d/efhd

**Comment by osirisbestlegitcheat** [comment]
Why are you sending weird Russian scam websites.

**Comment by mkot2** [comment]
> 
> 
> Why are you sending weird Russian scam websites.

they're not scam websites although i'm not sure why he didn't upload to imgur or something
