### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by ronin2022** [danielkrupinski/Osiris#2527]
1>------ Build started: Project: Osiris, Configuration: Release Win32 ------
1>GameData.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\xmemory(694,82): error C2661: 'Vector::Vector': no overloaded function takes 3 arguments
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\vector(682): message : see reference to function template instantiation 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,float,float,float>(_Alloc &,_Objty *const ,float &&,float &&,float &&)' being compiled
1>        with
1>        [
1>            _Alloc=std::allocator<Vector>,
1>            _Ty=Vector,
1>            _Objty=Vector
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\vector(687): message : see reference to function template instantiation 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,float,float,float>(_Alloc &,_Objty *const ,float &&,float &&,float &&)' being compiled
1>        with
1>        [
1>            _Alloc=std::allocator<Vector>,
1>            _Ty=Vector,
1>            _Objty=Vector
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\vector(700): message : see reference to function template instantiation '_Ty &std::vector<_Ty,std::allocator<_Ty>>::_Emplace_back_with_unused_capacity<float,float,float>(float &&,float &&,float &&)' being compiled
1>        with
1>        [
1>            _Ty=Vector
1>        ]
1>E:\Project\Osiris-master\Osiris\GameData.cpp(559): message : see reference to function template instantiation '_Ty &std::vector<_Ty,std::allocator<_Ty>>::emplace_back<float,float,float>(float &&,float &&,float &&)' being compiled
1>        with
1>        [
1>            _Ty=Vector
1>        ]
1>Done building project "Osiris.vcxproj" -- FAILED.

**Comment by mc-0bit** [comment]
Change 
https://github.com/danielkrupinski/Osiris/blob/c5beaf86c73ebed53551822788bf7663fe1a7276/Osiris/GameData.cpp#L559
to 
`Vector tmpVec = { inferno->fireXDelta()[i] + origin.x, inferno->fireYDelta()[i] + origin.y, inferno->fireZDelta()[i] + origin.z };`
`points.emplace_back(tmpVec);`

**Comment by doggobot-owner** [comment]
same issue

**Comment by wirekuro** [comment]
> Change
> https://github.com/danielkrupinski/Osiris/blob/c5beaf86c73ebed53551822788bf7663fe1a7276/Osiris/GameData.cpp#L559
> 
> 
> to
> `Vector tmpVec = { inferno->fireXDelta()[i] + origin.x, inferno->fireYDelta()[i] + origin.y, inferno->fireZDelta()[i] + origin.z };`
> `points.emplace_back(tmpVec);`

identifier "tmpVec" is undefined

**Comment by wirekuro** [comment]
@danielkrupinski

**Comment by danielkrupinski** [comment]
Fixed.
