### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by doggobot-owner** [danielkrupinski/Osiris#2529]
Same issue as in #2527

1>------ Build started: Project: Osiris, Configuration: Release Win32 ------
1>GameData.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\xmemory(694,82): error C2661: 'Vector::Vector': no overloaded function takes 3 arguments

**Comment by danielkrupinski** [comment]
Fixed.
