### ISSUE TITLE
[Idea] Fake Lag Not Blocking The Game

### ISSUE THREAD

**Issue by ClaudiuHKS** [danielkrupinski/Osiris#2530]
Normal legit anti aim features (view angle changers) are really obvious for legit hacking. Maybe not on the demo but to those that are spectators or observers.
Choked packets result in game lagging hard.
Can we somehow safely hook [sendto()](https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-sendto) function or I don't know, which functions send internet data to the game server and not send some info? This way, the game wouldn't lag anymore, I guess.

**Comment by Scui1** [comment]
That's a really good idea man! Can you maybe hook the sendTo function and make a pull request? I can't code 😢

**Comment by KleiFrickHeckDeck264** [comment]
thats how chocking a packet works?

**Comment by debooga** [comment]
its a worse idea than sendpacket = false, just saying
