### ISSUE TITLE
[Suggestion] Easy implementation (but i can’t code)

### ISSUE THREAD

**Issue by igre3zy** [danielkrupinski/Osiris#2531]
Someone, preferably @danielkrupinski, should add the option to force onshot on a key. With this simple implementation, osiris wouldn’t be half bad for semi rage

**Comment by ClaudiuHKS** [comment]
Or a **Checkbox** with setting **Only on stand still** and check **(localPlayer->velocity()).length2D() < 0.0015f** or **(localPlayer->getAimPunch()).x == 0.0f && (localPlayer->getAimPunch()).y == 0.0f**.

**Comment by Scui1** [comment]
> 
> 
> Someone, preferably @danielkrupinski, should add the option to force onshot on a key. With this simple implementation, osiris wouldn’t be half bad for semi rage

If you're talking about semi rage, people mostly have legitaa. Against legitaa onshot is mostly useless

**Comment by igre3zy** [comment]
> > Someone, preferably @danielkrupinski, should add the option to force onshot on a key. With this simple implementation, osiris wouldn’t be half bad for semi rage
> 
> If you're talking about semi rage, people mostly have legitaa. Against legitaa onshot is mostly useless. Nevertheless it's very easy to implement

that’s not true. Antiaim disables for a split second on shot. hence why shit resolvers prefer onshot

**Comment by igre3zy** [comment]
> Or a **Checkbox** with setting(s) **Only on stand still**/ **Only on no recoil** and check **(localPlayer->velocity()).length2D() < 0.0015f** or **(localPlayer->getAimPunch()).x == 0.0f && (localPlayer->getAimPunch()).y == 0.0f**

would you mind compiling this into a dll with AVX2? ion have a pc rn
