### ISSUE TITLE
[Bug] Non-Config files

### ISSUE THREAD

**Issue by doggobot-owner** [danielkrupinski/Osiris#2536]
If you put any file in config folder (even .exe), you can load it as a config and it will show in Osiris too. Try it yourself

**Comment by danielkrupinski** [comment]
What's wrong with it?

**Comment by doggobot-owner** [comment]
like nothing major but even exe files are shown in it

**Comment by osirisbestlegitcheat** [comment]
I tried something. If you load something like that, it will crash the game when you load it.
