### ISSUE TITLE
[HELP] CSGO Panorama API

### ISSUE THREAD

**Issue by blackMasterLord** [danielkrupinski/Osiris#2539]
**Hello**.
I'm was trying hooking, get pointer [CSGO Panorama API](https://developer.valvesoftware.com/wiki/CSGO_Panorama_API), but its unsuccessfully.
I also did not find any source code.
Any help with this will help me a lot.

_......It's even possible?_

**Comment by Scui1** [comment]
What did you try to hook?
There is no "pointer to the panorama api", but there is a panorama engine interface that you can get : `panoramaEngine = GetInterface<IPanoramaUIEngine>("PanoramaUIEngine001");`
You can find the functions [listed here](https://developer.valvesoftware.com/wiki/CSGO_Panorama_API) by doing a stringsearch in ida.
