### ISSUE TITLE
Add name stealer?

### ISSUE THREAD

**Issue by chovss** [danielkrupinski/Osiris#254]
Please

**Comment by Flaam** [comment]
+1

**Comment by tirziz** [comment]
what is the purpose of this feature ? , they still can report you

**Comment by Flaam** [comment]
@tirziz on deathmatch when i rank to level 2 my accounts i always get kicked, so if you steal a name they cant kick you

**Comment by effex1337** [comment]
@Flaam Why don't you try by yourself just add an invisible char after your name.
You're activities are really sus asking how to make a loader hard to crack when you just wanted to give it to your friend. I can't code at all but I've added some stuff to my build of osiris myself. Don't just go +1 to every suggestions. I didn't block you on discord for no reason. Think about it retard!

**Comment by Flaam** [comment]
@effex1337 i dont listen to retards like you

**Comment by Flaam** [comment]
If i comment +1 is because i think is a good idea for the cheat, i know i can put an invisible char after my name but i think it would be useful on the cheat

**Comment by LuizDanG** [comment]
You can add this feature by urself, Daniel dont must add It.
FeelsGoodMan and paste it from other source ;)

**Comment by effex1337** [comment]
@Flaam Alright please don't beg for configs on github next time. 
I don't dance waste my time saying much so yeah.

**Comment by cojo1989** [comment]
Guys we need to help Daniel to improve Osiris not to fight between us. :)

**Comment by danielkrupinski** [comment]
Added.
