### ISSUE TITLE
Some of the features in the misc tab are inaccessible when you are on 4:3 800x600 

### ISSUE THREAD

**Issue by osirisbestlegitcheat** [danielkrupinski/Osiris#2540]
When you strech to 800x600 or below the acpect ratio, report bot, unhook and more are blocked because menu is to big.

**Comment by 3Ld4D** [comment]
Stop playing on gameboy.

**Comment by wemanzoz** [comment]
just use aspect ration module lol, no need change ur res

**Comment by linuxer9** [comment]
remove "ImGuiWindowFlags_NoScrollbar" and "ImGuiWindowFlags_NoResize" frome window flags

```
constexpr auto windowFlags = ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize
| ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse;
```
and then you will have a resizable window, you may need to change window size here
`ImGui::SetNextWindowSize({ 580.0f, 0.0f });`
set it to whatever you want.

**Comment by osirisbestlegitcheat** [comment]
where is this code located?

**Comment by osirisbestlegitcheat** [comment]
> just use aspect ration module lol, no need change ur res

I'm playing on a 2008 windows 8.1 Toshiba  laptop. ideally need that stretch.

**Comment by osirisbestlegitcheat** [comment]
This is the output I get with the errors.

Build started...
1>------ Build started: Project: Osiris, Configuration: Release Win32 ------
1>Config.cpp
1>EventListener.cpp
1>GameData.cpp
1>Aimbot.cpp
1>AntiAim.cpp
1>Backtrack.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\Hacks\AntiAim.cpp(64,137): error C2065: 'ImGuiWindowFlags_NoScrollWithMouse': undeclared identifier
1>Chams.cpp
1>EnginePrediction.cpp
1>Glow.cpp
1>SkinChanger.cpp
1>StreamProofESP.cpp
1>Triggerbot.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\Hacks\Glow.cpp(176,136): error C2065: 'ImGuiWindowFlags_NoScrollWithMouse': undeclared identifier
1>Visuals.cpp
1>Helpers.cpp
1>imguiCustom.cpp
1>imgui_stdlib.cpp
1>imgui_tables.cpp
1>InputUtil.cpp
1>Netvars.cpp
1>GUI.cpp
1>Misc.cpp
1>Hooks.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\GUI.cpp(32,34): error C2065: 'ImGuiWindowFlags_NoScrollWithMouse': undeclared identifier
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\GUI.cpp(31,16): error C2737: 'windowFlags': 'constexpr' object must be initialized
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\GUI.cpp(172,59): error C3536: 'windowFlags': cannot be used before it is initialized
1>imgui.cpp
1>imgui_demo.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui_demo.cpp(2142,33): error C2065: 'ImGuiWindowFlags_NoScrollWithMouse': undeclared identifier
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui_demo.cpp(2155,33): error C2065: 'ImGuiWindowFlags_NoScrollWithMouse': undeclared identifier
1>imgui_draw.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.cpp(3624,118): error C2065: 'ImGuiWindowFlags_NoScrollWithMouse': undeclared identifier
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.cpp(3626,31): error C2065: 'ImGuiWindowFlags_NoScrollWithMouse': undeclared identifier
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.cpp(3639,118): error C2065: 'ImGuiWindowFlags_NoScrollWithMouse': undeclared identifier
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.cpp(3641,31): error C2065: 'ImGuiWindowFlags_NoScrollWithMouse': undeclared identifier
1>imgui_impl_dx9.cpp
1>imgui_impl_win32.cpp
1>imgui_widgets.cpp
1>Entity.cpp
1>GlobalVars.cpp
1>Done building project "Osiris.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by osirisbestlegitcheat** [comment]
Ok now i know how to do it bye lol.
