### ISSUE TITLE
Glow Issue & Cfg Reset (Anti Aim) Issue

### ISSUE THREAD

**Issue by ClaudiuHKS** [danielkrupinski/Osiris#2542]
https://github.com/danielkrupinski/Osiris/blob/cb131733f811bc3e95cae823a272b55db429ed60/Osiris/Hacks/Glow.cpp#L96

Something is wrong here for sure, not working as expected.

**Comment by danielkrupinski** [comment]
What is the expected behavior and what do you observe?

**Comment by ClaudiuHKS** [comment]
auto applyPlayerGlow = [applyGlow](const std::string& name, Entity* entity) noexcept {
            const auto& cfg = playerGlowConfig[name];
            if (cfg.all.enabled)
                applyGlow(cfg.all, entity->health());
            else if (cfg.visible.enabled && entity->visibleTo(localPlayer.get()))
                applyGlow(cfg.visible, entity->health());
            else if (cfg.occluded.enabled)
                applyGlow(cfg.occluded, entity->health());
        };

When only **cfg.occluded.enabled** is _true_, there are no occlusion tests performed and the enemies appears through walls while they shouldn't.

**Comment by danielkrupinski** [comment]
Fixed
