### ISSUE TITLE
[Suggestion] Grenade Tracers NOT prediction

### ISSUE THREAD

**Issue by MorganaBRKSRL** [danielkrupinski/Osiris#2545]
Hello. I tried to implement this with this piece of code:
```
static auto nadeVar{ interfaces->cvar->findVar("sv_grenade_trajectory") };

    nadeVar->onChangeCallbacks.size = 0;
    nadeVar->setValue(config->misc.nadeTrajectory);
```
which didn't ofc work, so I'm asking for help. I tried to draw, not a lot of succes. Thanks!

**Comment by danielkrupinski** [comment]
ESP > Projectiles > Trails

**Comment by MorganaBRKSRL** [comment]
> ESP > Projectiles > Trails

I see what you mean, it gets closer to what I want to do. I wanted to also show the impacts, to replicate sv_grenade_trajectory. Would there be any detectCollision, but for projectiles ?

**Comment by mkot2** [comment]
> 
> 
> > ESP > Projectiles > Trails
> 
> I see what you mean, it gets closer to what I want to do. I wanted to also show the impacts, to replicate sv_grenade_trajectory. Would there be any detectCollision, but for projectiles ?

https://github.com/notgoodusename/osiriswithstuff
specifically Hacks/GrenadePrediction.cpp
it's all in there

**Comment by MorganaBRKSRL** [comment]
> > > ESP > Projectiles > Trails
> > 
> > 
> > I see what you mean, it gets closer to what I want to do. I wanted to also show the impacts, to replicate sv_grenade_trajectory. Would there be any detectCollision, but for projectiles ?
> 
> https://github.com/notgoodusename/osiriswithstuff
> specifically Hacks/GrenadePrediction.cpp
> it's all in there

I see, thanks! Can confirm is what I wanted
