### ISSUE TITLE
Osiris crashing if disabling optimizations

### ISSUE THREAD

**Issue by MorganaBRKSRL** [danielkrupinski/Osiris#2547]
![image_2021-02-01_113210](https://user-images.githubusercontent.com/77856125/106440112-2046c600-6481-11eb-9226-52d909854cae.png)
Crashing at injection, why that happens and what would a fix would be? ( other than enabling optimizations )
EDIT: it seems that turning off "Whole Program Optimizations" is causing the crash

**Comment by wemanzoz** [comment]
hmmmmm

**Comment by wemanzoz** [comment]
i literally turned off EVERYTHING once when im using junk codes. nothing crashes, user issue?

**Comment by mkot2** [comment]
> 
> 
> i literally turned off EVERYTHING once when im using junk codes. nothing crashes, user issue?

not a user issue, it happens to me as well, however it doesn't matter since you shouldn't disable the optimizations anyways

**Comment by MorganaBRKSRL** [comment]
> > i literally turned off EVERYTHING once when im using junk codes. nothing crashes, user issue?
> 
> not a user issue, it happens to me as well, however it doesn't matter since you shouldn't disable the optimizations anyways

what I'm trying to achieve is not that possible with optimizations on

**Comment by Scui1** [comment]
> what I'm trying to achieve is not that possible with optimizations on

what are you trying to achieve? There's another way to disable it in the code, maybe I can help you when you explain a little more what you're trying to do.

**Comment by linuxer9** [comment]
If a specifc part of your code requires disabling optimization, then you should put it inside this modifier:
```
#pragma optimize ("", off)
// junk code goes here
#pragma optimize ("", on)
```
there is no need to disable "whole program optimization" it only hurts the performance.
side note: I wouldn't recommend adding a junk code, If you want to evade signature detection it's as simple as modifying the original code a little.

**Comment by SwagsRGB** [comment]
Imagine being on 2021 and thinking junk code woks. NO IT DOESNT. Pls stop making projects that are so carefully optimized to have the least frame drops into fps eating junk code shits. Junk code do not bypass sig verification by vac, Just use the Vac Bypasser by Daniel

**Comment by Scui1** [comment]
> 
> 
> Imagine being on 2021 and thinking junk code woks. NO IT DOESNT. Pls stop making projects that are so carefully optimized to have the least frame drops into fps eating junk code shits. Junk code do not bypass sig verification by vac, Just use the Vac Bypasser by Daniel

vac bypass is ditected, only junkcode works 😃 Now be quiet please

**Comment by linuxer9** [comment]
> 
> vac bypass is ditected, only junkcode works 😃 Now be quiet please

how it got detected ? I have been using the bypass for 4 months and injecting a cracked p2c still no ban

**Comment by mkot2** [comment]
> 
> 
> > Imagine being on 2021 and thinking junk code woks. NO IT DOESNT. Pls stop making projects that are so carefully optimized to have the least frame drops into fps eating junk code shits. Junk code do not bypass sig verification by vac, Just use the Vac Bypasser by Daniel
> 
> vac bypass is ditected, only junkcode works 😃 Now be quiet please

- vac bypass
- detected
???
detected by what lmao there's nothing to detect it
also junk code never worked? all it does is change the hash of the dll, vac uses much more than that to detect cheats
