### ISSUE TITLE
autooffset

### ISSUE THREAD

**Issue by tomasz-rg** [danielkrupinski/Osiris#2549]
czy mozesz zamiescić autoffsety wraz z kodem zrodłowym ? przydołoby się by nie pobierac co chwile :)

**Comment by Dynamooo1** [comment]
mordo internal ma auto offsety

**Comment by tomasz-rg** [comment]
Okej dzięki wielkie ale każdy internal ma autooffsety ?

sob., 6 lut 2021, 22:30 użytkownik Dynamooo1 <notifications@github.com>
napisał:

**Comment by tomasz-rg** [comment]
Jak mogę zmienić offsety w go ESP ps.wydlalem donate na PayPal

niedz., 7 lut 2021, 14:02 użytkownik PATUS <kubavstomek@gmail.com> napisał:
