### ISSUE TITLE
Problem injecting Osiris

### ISSUE THREAD

**Issue by olanelson85** [danielkrupinski/Osiris#2550]
Whenever I inject Osiris (using Sazzinjector) with LoadLibrary, nothing happens in-game; The menu never shows up. And when I use Manual Map, the game just crashes. Any ideas on what could be causing this? I have used Osiris in the past with non of these issues, using this same computer, which makes me wonder.

**Comment by linuxer9** [comment]
I believe that LoadLibrary is detected, you can try Memject or shtreeba

**Comment by mkot2** [comment]
download shtreeba

**Comment by olanelson85** [comment]
Ty
