### ISSUE TITLE
PLEASE ADD A SCROLL BAR TO THE MISC TAB

### ISSUE THREAD

**Issue by osirisbestlegitcheat** [danielkrupinski/Osiris#2552]
When you stretch CS:GO to 4:3 800x600 many important features will be hidden, for example the unhook will not be visible.

**Comment by wemanzoz** [comment]
then dont launch csgo in that specific aspect ratio + resolution

**Comment by franiodat** [comment]
ImGui::BeginChild = profit

**Comment by osirisbestlegitcheat** [comment]
> then dont launch csgo in that specific aspect ratio + resolution

I NEED TO MY COMPUTER IS A TOASTER

**Comment by osirisbestlegitcheat** [comment]
> ImGui::BeginChild = profit

what does that mean????

**Comment by blackMasterLord** [comment]
https://github.com/danielkrupinski/Osiris/blob/e610c50f64945929757cc2175abf587d8562d766/Osiris/GUI.cpp#L32-L33
`constexpr auto windowFlags = ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoScrollWithMouse;`

**Comment by osirisbestlegitcheat** [comment]
> https://github.com/danielkrupinski/Osiris/blob/e610c50f64945929757cc2175abf587d8562d766/Osiris/GUI.cpp#L32-L33
> 
> 
> `constexpr auto windowFlags = ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoScrollWithMouse;`

What do I do with this information?

**Comment by blackMasterLord** [comment]
delete ImGuiWindowFlags_NoScrollbar flag

**Comment by osirisbestlegitcheat** [comment]
> delete ImGuiWindowFlags_NoScrollbar flag

After i do that it gives me these errors 

Build started...
1>------ Build started: Project: Osiris, Configuration: Release Win32 ------
1>Config.cpp
1>EventListener.cpp
1>GameData.cpp
1>Aimbot.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file EventListener.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file EventListener.cpp)
1>AntiAim.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file Hacks\Aimbot.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file Hacks\Aimbot.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file GameData.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file GameData.cpp)
1>Backtrack.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file Config.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file Config.cpp)
1>Chams.cpp
1>EnginePrediction.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file Hacks\AntiAim.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file Hacks\AntiAim.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\Hacks\AntiAim.cpp(64,106): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier
1>Glow.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file Hacks\Chams.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file Hacks\Chams.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file Hacks\Backtrack.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file Hacks\Backtrack.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\Hacks\Backtrack.cpp(201,115): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier
1>SkinChanger.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file Hacks\EnginePrediction.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file Hacks\EnginePrediction.cpp)
1>StreamProofESP.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file Hacks\Glow.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file Hacks\Glow.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file Hacks\StreamProofESP.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file Hacks\StreamProofESP.cpp)
1>Triggerbot.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file Hacks\SkinChanger.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file Hacks\SkinChanger.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\Hacks\Glow.cpp(176,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier
1>Visuals.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file Hacks\Visuals.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file Hacks\Visuals.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file Hacks\Triggerbot.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file Hacks\Triggerbot.cpp)
1>Helpers.cpp
1>MinHook.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file Helpers.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file Helpers.cpp)
1>VmtHook.cpp
1>VmtSwap.cpp
1>imguiCustom.cpp
1>imgui_stdlib.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file imguiCustom.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file imguiCustom.cpp)
1>imgui_tables.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file imgui\imgui_stdlib.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file imgui\imgui_stdlib.cpp)
1>InputUtil.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file imgui\imgui_tables.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file imgui\imgui_tables.cpp)
1>Netvars.cpp
1>Osiris.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file InputUtil.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file InputUtil.cpp)
1>GUI.cpp
1>Misc.cpp
1>Hooks.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file Netvars.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file Netvars.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file Hooks.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file Hooks.cpp)
1>imgui.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file Hacks\Misc.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file Hacks\Misc.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file GUI.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file GUI.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file imgui\imgui.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file imgui\imgui.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.cpp(5056,145): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.cpp(5057,145): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.cpp(5859,158): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.cpp(5860,212): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.cpp(5862,107): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.cpp(5992,50): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.cpp(5992,38): error C2789: 'allow_scrollbar_x': an object of const-qualified type must be initialized
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.cpp(5992): message : see declaration of 'allow_scrollbar_x'
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.cpp(5993,50): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.cpp(5993,38): error C2789: 'allow_scrollbar_y': an object of const-qualified type must be initialized
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.cpp(5993): message : see declaration of 'allow_scrollbar_y'
1>imgui_demo.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file imgui\imgui_demo.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file imgui\imgui_demo.cpp)
1>imgui_draw.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui_demo.cpp(307,45): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier
1>imgui_impl_dx9.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\GUI.cpp(33,3): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\GUI.cpp(32,16): error C2737: 'windowFlags': 'constexpr' object must be initialized
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\GUI.cpp(173,59): error C3536: 'windowFlags': cannot be used before it is initialized
1>imgui_impl_win32.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file imgui\imgui_draw.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file imgui\imgui_draw.cpp)
1>imgui_widgets.cpp
1>Memory.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file imgui\imgui_impl_win32.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file imgui\imgui_impl_win32.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file imgui\imgui_impl_dx9.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file imgui\imgui_impl_dx9.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file imgui\imgui_widgets.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file imgui\imgui_widgets.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui_widgets.cpp(6535,121): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier
1>Entity.cpp
1>GlobalVars.cpp
1>KeyValues.cpp
1>Utils.cpp
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file SDK\Entity.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file SDK\Entity.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,105): error C2065: 'ImGuiWindowFlags_NoScrollbar': undeclared identifier (compiling source file SDK\GlobalVars.cpp)
1>C:\Users\willp\OneDrive\Desktop\Osiris-master\Osiris\imgui\imgui.h(890,163): error C2056: illegal expression (compiling source file SDK\GlobalVars.cpp)
1>Done building project "Osiris.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by egssy0** [comment]
Are you know anything about C++?

**Comment by osirisbestlegitcheat** [comment]
> Are you know anything about C++ or Dear ImGui?

No I just like the cheat.

**Comment by CyborgPlatypus64** [comment]
whats ur discord?

**Comment by osirisbestlegitcheat** [comment]
> whats ur discord?

its Jasveer Babbar#9791

**Comment by osirisbestlegitcheat** [comment]
Yes that guy in discord told me how to do it so bye lol.

**Comment by osirisbestlegitcheat** [comment]
> whats ur discord?

RARI WTF HAPPEND TO YOU

**Comment by osirisbestlegitcheat** [comment]
YOU GOT BANNED AND YOU UNFREINDED ME FROM EVERYTHING
