### ISSUE TITLE
(question) how to change tab size

### ISSUE THREAD

**Issue by CyborgPlatypus64** [danielkrupinski/Osiris#2553]
Trying to change the size of the tabs in the menu can anyone help?

**Comment by franiodat** [comment]
1. Use buttons instead tabs.
2. Profit!

**Comment by CyborgPlatypus64** [comment]
> 
> 
>     1. Use buttons instead of tabs.
> 
>     2. Profit!

ive tried this but i have an issue where when i click on each tab it will pop out a seperate window even though its on the second style

**Comment by linuxer9** [comment]
you cann't change the tab button size unless you change the ImGui code.
so you should use regular buttons instead as franiodat said.

> ive tried this but i have an issue where when i click on each button it will pop out a seperate window even though its on the second style

It shouldn't run a seperate window, make sure you pass true in contentonly boolean, for example use "renderAimbotWindow(true);" instead of "renderAimbotWindow();"

**Comment by CyborgPlatypus64** [comment]
> 
> 
> you cann't change the tab button size unless you change the ImGui code.
> so you should use regular buttons instead as franiodat said.
> 
> > ive tried this but i have an issue where when i click on each button it will pop out a seperate window even though its on the second style
> 
> It shouldn't run a seperate window, make sure you pass true in contentonly boolean, for example use "renderAimbotWindow(true);" instead of "renderAimbotWindow();"

okay thanks

**Comment by CyborgPlatypus64** [comment]
> 
> 
> you cann't change the tab button size unless you change the ImGui code.
> so you should use regular buttons instead as franiodat said.
> 
> > ive tried this but i have an issue where when i click on each button it will pop out a seperate window even though its on the second style
> 
> It shouldn't run a seperate window, make sure you pass true in contentonly boolean, for example use "renderAimbotWindow(true);" instead of "renderAimbotWindow();"
this is what ive got so far but it doesnt work the windows dont show up when i press each button in the menu. any idea what im doing wrong?
```void GUI::renderGuiStyle2() noexcept
{
    ImGui::SetNextWindowSize(ImVec2(700, 400));

    ImGui::Begin("mDMYeu7SIb6sqCny4", nullptr, windowFlags);

    ImGui::BeginGroup();
    static int selected_Tab = 0;

    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(1.0, 1.0));
    ImGui::PushStyleVar(ImGuiStyleVar_ItemInnerSpacing, ImVec2(1.0, 1.0));
    
    if (ImGui::Button("Aim", ImVec2(85, 35))) {renderAimbotWindow(true);
    }
    ImGui::SameLine();
    if (ImGui::Button("Skins", ImVec2(85, 35))) {renderSkinChangerWindow(true);
    }
    ImGui::SameLine();
    if (ImGui::Button("Misc", ImVec2(85, 35))) {renderMiscWindow(true);
    }
    ImGui::SameLine();
    if (ImGui::Button("Backtrack", ImVec2(85, 35))) {renderBacktrackWindow(true);
    }
    ImGui::SameLine();
    if (ImGui::Button("Config", ImVec2(85, 35))) {renderConfigWindow(true);
    }
    ImGui::SameLine();
    if (ImGui::Button("Chams", ImVec2(85, 35))) {renderChamsWindow(true);
    }
    ImGui::SameLine();
    if (ImGui::Button("ESP", ImVec2(85, 35))) {renderStreamProofESPWindow(true);
    }
    ImGui::SameLine();
    if (ImGui::Button("Visuals", ImVec2(85, 35))) {renderVisualsWindow(true);
    }
    ImGui::SameLine();
    ImGui::PopStyleVar();
    ImGui::PopStyleVar();
    ImGui::EndGroup();

    ImGui::BeginGroup();
    ImGui::PushID(selected_Tab);

    renderAimbotWindow();
    renderBacktrackWindow();
    renderChamsWindow();
    renderStreamProofESPWindow();
    renderVisualsWindow();
    renderSkinChangerWindow();
    renderSoundWindow();
    renderStyleWindow();
    renderMiscWindow();
    renderConfigWindow();
    ImGui::PopID();
    ImGui::EndGroup();

    ImGui::End();

}```

**Comment by linuxer9** [comment]
you are doing it completely wrong.
you are calling rendring windows twice.
try this code

```
{
    ImGui::SetNextWindowSize(ImVec2(700, 400));

    ImGui::Begin("mDMYeu7SIb6sqCny4", nullptr, windowFlags);

    ImGui::BeginGroup();
    static int selected_Tab = 0;

    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(1.0, 1.0));
    ImGui::PushStyleVar(ImGuiStyleVar_ItemInnerSpacing, ImVec2(1.0, 1.0));
    
    if (ImGui::Button("Aim", ImVec2(85, 35))) 
    {
    	selected_Tab = 0;
    }
    ImGui::SameLine();
    if (ImGui::Button("Skins", ImVec2(85, 35))) 
    {
    	selected_Tab = 1;
    }
    ImGui::SameLine();
    if (ImGui::Button("Misc", ImVec2(85, 35))) 
    {
    	selected_Tab = 2;
    }
    ImGui::SameLine();
    if (ImGui::Button("Backtrack", ImVec2(85, 35))) 
    {
    	selected_Tab = 3;
    }
    ImGui::SameLine();
    if (ImGui::Button("Config", ImVec2(85, 35))) 
    {
    	selected_Tab = 4;
    }
    ImGui::SameLine();
    if (ImGui::Button("Chams", ImVec2(85, 35))) 
    {
    	selected_Tab = 5;
    }
    ImGui::SameLine();
    if (ImGui::Button("ESP", ImVec2(85, 35))) 
    {
    	selected_Tab = 6;
    }
    ImGui::SameLine();
    if (ImGui::Button("Visuals", ImVec2(85, 35))) 
    {
    	selected_Tab = 7;
    }
    ImGui::SameLine();
    ImGui::PopStyleVar();
    ImGui::PopStyleVar();
    ImGui::EndGroup();

    ImGui::BeginGroup();

    switch (selected_Tab){
    	case 0:
    		renderAimbotWindow(true);
    		break;
    	case 1:
    		renderSkinChangerWindow(true);
    		break;
    	// continue case switching I'm too lazy to do it 

    }
    ImGui::EndGroup();

    ImGui::End();

}
```

**Comment by CyborgPlatypus64** [comment]
> 
> 
> you are doing it completely wrong.
> you are calling rendring windows twice.
> try this code
> 
> ```
> {
>     ImGui::SetNextWindowSize(ImVec2(700, 400));
> 
>     ImGui::Begin("mDMYeu7SIb6sqCny4", nullptr, windowFlags);
> 
>     ImGui::BeginGroup();
>     static int selected_Tab = 0;
> 
>     ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(1.0, 1.0));
>     ImGui::PushStyleVar(ImGuiStyleVar_ItemInnerSpacing, ImVec2(1.0, 1.0));
>     
>     if (ImGui::Button("Aim", ImVec2(85, 35))) 
>     {
>     	selected_Tab = 0;
>     }
>     ImGui::SameLine();
>     if (ImGui::Button("Skins", ImVec2(85, 35))) 
>     {
>     	selected_Tab = 1;
>     }
>     ImGui::SameLine();
>     if (ImGui::Button("Misc", ImVec2(85, 35))) 
>     {
>     	selected_Tab = 2;
>     }
>     ImGui::SameLine();
>     if (ImGui::Button("Backtrack", ImVec2(85, 35))) 
>     {
>     	selected_Tab = 3;
>     }
>     ImGui::SameLine();
>     if (ImGui::Button("Config", ImVec2(85, 35))) 
>     {
>     	selected_Tab = 4;
>     }
>     ImGui::SameLine();
>     if (ImGui::Button("Chams", ImVec2(85, 35))) 
>     {
>     	selected_Tab = 5;
>     }
>     ImGui::SameLine();
>     if (ImGui::Button("ESP", ImVec2(85, 35))) 
>     {
>     	selected_Tab = 6;
>     }
>     ImGui::SameLine();
>     if (ImGui::Button("Visuals", ImVec2(85, 35))) 
>     {
>     	selected_Tab = 7;
>     }
>     ImGui::SameLine();
>     ImGui::PopStyleVar();
>     ImGui::PopStyleVar();
>     ImGui::EndGroup();
> 
>     ImGui::BeginGroup();
> 
>     switch (selected_Tab){
>     	case 0:
>     		renderAimbotWindow(true);
>     		break;
>     	case 1:
>     		renderSkinChangerWindow(true);
>     		break;
>     	// continue case switching I'm too lazy to do it 
> 
>     }
>     ImGui::EndGroup();
> 
>     ImGui::End();
> 
> }
> ```

ah i see thank you !
