### ISSUE TITLE
aimbot 

### ISSUE THREAD

**Issue by lukuj23** [danielkrupinski/Osiris#2557]
Aimbot is failing a lot in any hitbox (head, cheat ...) It was like that after the new keybind system

**Comment by deathdate** [comment]
I remember using legit aimbot by puddin poppin.. It used to look very human and was good with the smooth.
Just mentioning it here incase something from it can be reused here to improve.
https://www.mpgh.net/forum/showthread.php?t=917932&highlight=Puddin+Poppin
