### ISSUE TITLE
Anti-kick in casual

### ISSUE THREAD

**Issue by NexSqaud** [danielkrupinski/Osiris#256]
If call vote to change map, when kick vote begin, kick vote have been canceled
https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events#start_vote

**Comment by NexSqaud** [comment]
callvote Kick <userID>
callvote RestartGame
callvote ChangeLevel <mapname>
callvote ScrambleTeams
callvote SwapTeams

**Comment by danielkrupinski** [comment]
@NexSqaud Have you tested which of these cancels kick vote?

**Comment by NexSqaud** [comment]
Any. You just need to call the vote. Easiest way is ScrampleTeams and SwapTeams

**Comment by danielkrupinski** [comment]
Are you sure "start_vote" event is fired in game?

**Comment by NexSqaud** [comment]
🤔 Maybe that in [usermessages?](https://github.com/ValveSoftware/csgo-demoinfo/blob/master/demoinfogo/cstrike15_usermessages_public.proto#L68)

**Comment by danielkrupinski** [comment]
Patched.
