### ISSUE TITLE
*Custom* model change not working in Official Servers

### ISSUE THREAD

**Issue by kruz1337** [danielkrupinski/Osiris#2563]
I used the Precache Model method, it worked successfully in single player mode and community servers, but models appear as an error box in multiplayer mode. When I exit the multiplayer mode, switch to single player mode and then try to switch to multiplayer mode, I get this error "Third Party Files Loaded".

![Untitled-1](https://user-images.githubusercontent.com/61029407/107154838-17288e00-6986-11eb-8eb4-ef3c20a758f3.png)

**Comment by 3Ld4D** [comment]
u need to bypass sv_pure.

**Comment by Kruziikrel1** [comment]
> u need to bypass sv_pure.

I bypass sv_pure with OTC v3 but still not working

**Comment by wemanzoz** [comment]
bypass sv_pure doesn't exist yet on osiris, waiting someone to add it on a pull tbh
