### ISSUE TITLE
Crash on round 1 start.

### ISSUE THREAD

**Issue by deathdate** [danielkrupinski/Osiris#2564]
Sometimes the game crashes on after waiting for players when the round starts...
Could be some specific setting.. because only happens when loaded a particular config..

**Comment by wemanzoz** [comment]
config issue

**Comment by danielkrupinski** [comment]
Please post the faulty config here.

**Comment by deathdate** [comment]
[Osiris.zip](https://github.com/danielkrupinski/Osiris/files/5946071/Osiris.zip)
Uploading my 3 configs where i've noticed it in past.. i'll keep an eye out and next time share even more precise info if possible.
