### ISSUE TITLE
Multiple Hitbox selection and Hitbox priority, draw aimbot fov

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#2569]
Allow us to select multiple hitboxes(ex: head,chest,stomach,pelvis)
and allow us to set hitbox priority(ex: Head, body) (body includes: chest, stomach, pelvis) ( can only be set to either Head, or body)
These features would be very good to have in osiris
and there's also draw aimbot fov which would allow us to customize the fov in more detail.

**Comment by mkot2** [comment]
#2218

**Comment by linuxer9** [comment]
hitboxes are not reliable for an aimbot, bone aimbot is better. regarding your request of mulitiple "spots" for aimbot to work with it will eventually lock your crosshair to one "spot", which is the same as "nearest bone" selection.
you could do bone selection in the current osiris without any modification; just set minimum damage to a value that favours your hitboxes and choose nearest bone.
for example if I set minimum damage for AWP to a value above 85, the aimbot will lock my crosshair to any bone but the legs, i.e: head, chest, stomach. (that is of course considering there's a little to no damage drop off).
and so on, do the rest of weapons according to their meta
