### ISSUE TITLE
Redo legit anti aim, Desync chams/glow

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#2570]
no comment, the anti aim needs a rework and a desync chams/glow would be very helpful

**Comment by Scui1** [comment]
> 
> 
> no comment, the anti aim needs a rework and a desync chams/glow would be very helpful

Daniel won't add this because he doesn't know how to do it 🤣. Also he will use "ThIs Is A LeGiT cHeAt" as excuse for not adding it.

**Comment by olanelson85** [comment]
People getting mad and trying to poke fun at the cheat for not having the features they want instead of recommending fixes never ceases to amaze me. 

Let me recommend a couple fixes to your problem:

- Learn how to program and try recommending actual solutions
- Use another cheat

**Comment by Scui1** [comment]
> 
> 
> People getting mad and trying to poke fun at the cheat for not having the features they want instead of recommending fixes never ceases to amaze me.
> 
> Let me recommend a couple fixes to your problem:
> 
>     * Learn how to program and try recommending actual solutions
> 
>     * Use another cheat

Not sure who you mean, but probably me. I'm not mad at all, since I don't even use this cheat, I'm just here to laugh about all the retards and the cheat itself.
