### ISSUE TITLE
Perfect legit recoil compensation

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#2571]
perfect smooth rcs

**Comment by tirziz** [comment]
this

**Comment by mkot2** [comment]
#2135

**Comment by HowToMakeFaceitAB** [comment]
> #2135

ah, i already added perfect legit rcs to my osiris build, i just wanted it to be added to the master branch because i thought it would be a good addition to osiris

**Comment by HowToMakeFaceitAB** [comment]
> #2135

and also, I had to add my own RCS because that one wasn't compensating for my mouse movements

**Comment by mkot2** [comment]
> 
> 
> > #2135
> 
> and also, I had to add my own RCS because that one wasn't compensating for my mouse movements

wdym it does compensate even when the aimbot is not doing anything, it works only when aimbot is on tho
