### ISSUE TITLE
Inventory changer

### ISSUE THREAD

**Issue by HackerGeo-sp1ne** [danielkrupinski/Osiris#2572]
you can add inventory changer and medails and more features

**Comment by wemanzoz** [comment]
we have skinchanger already

**Comment by HowToMakeFaceitAB** [comment]
> you can add inventory changer and medails and more features

inventory changer is pointless. others can't even see your skins anyway so why bother adding them to your inventory? just use the skinchanger

**Comment by HowToMakeFaceitAB** [comment]
and if you say "it's meant for streaming" that's understandable but can't you just disable skin changer on stream? why do you feel the need to fake having something you don't

**Comment by Scui1** [comment]
> 
> 
> and if you say "it's meant for streaming" that's understandable but can't you just disable skin changer on stream? why do you feel the need to fake having something you don't

Wow calm down mr paster. It's a valid feature request and more convenient to use the ingame inventory to equip weapons rather than selecting them in the ugly osiris gui.

**Comment by cyanewfag** [comment]
> > and if you say "it's meant for streaming" that's understandable but can't you just disable skin changer on stream? why do you feel the need to fake having something you don't
> 
> Wow calm down mr paster. It's a valid feature request and more convenient to use the ingame inventory to equip weapons rather than selecting them in the ugly osiris gui.

don't call someone a paster when you're mad that daniel won't add a feature that you could easily code in
https://github.com/danielkrupinski/Osiris/issues/2570#issuecomment-775802703

**Comment by mkot2** [comment]
> 
> 
> > > and if you say "it's meant for streaming" that's understandable but can't you just disable skin changer on stream? why do you feel the need to fake having something you don't
> > 
> > 
> > Wow calm down mr paster. It's a valid feature request and more convenient to use the ingame inventory to equip weapons rather than selecting them in the ugly osiris gui.
> 
> don't call someone a paster when you're mad that daniel won't add a feature that you could easily code in
> [#2570 (comment)](https://github.com/danielkrupinski/Osiris/issues/2570#issuecomment-775802703)

making an animfix and making the desync work properly aint that easy chef

**Comment by cyanewfag** [comment]
> > > > and if you say "it's meant for streaming" that's understandable but can't you just disable skin changer on stream? why do you feel the need to fake having something you don't
> > > 
> > > 
> > > Wow calm down mr paster. It's a valid feature request and more convenient to use the ingame inventory to equip weapons rather than selecting them in the ugly osiris gui.
> > 
> > 
> > don't call someone a paster when you're mad that daniel won't add a feature that you could easily code in
> > [#2570 (comment)](https://github.com/danielkrupinski/Osiris/issues/2570#issuecomment-775802703)
> 
> making an animfix and making the desync work properly aint that easy chef

speak for yourself

**Comment by linuxer9** [comment]
As said above, Osiris has already a skin changer and it works perfectly. an inventory changer will be redundant.
the only thing that isn't in current skin changer is the medals and music kits, and like skins it's only client side.
whatever, take a look at [this PR](https://github.com/danielkrupinski/Osiris/pull/2503), the author/paster claims it can be used for an inventory changer

**Comment by wemanzoz** [comment]
the skinchanger is very good lol, it has preview , and an easy application. just need knife preview

**Comment by Scui1** [comment]
> 
> 
> > > and if you say "it's meant for streaming" that's understandable but can't you just disable skin changer on stream? why do you feel the need to fake having something you don't
> > 
> > 
> > Wow calm down mr paster. It's a valid feature request and more convenient to use the ingame inventory to equip weapons rather than selecting them in the ugly osiris gui.
> 
> don't call someone a paster when you're mad that daniel won't add a feature that you could easily code in
> [#2570 (comment)](https://github.com/danielkrupinski/Osiris/issues/2570#issuecomment-775802703)

wdym mad about him not adding it? I'm just laughing about this trash cheat 🤣

**Comment by wemanzoz** [comment]
> > and if you say "it's meant for streaming" that's understandable but can't you just disable skin changer on stream? why do you feel the need to fake having something you don't
> 
> Wow calm down mr paster. It's a valid feature request and more convenient to use the ingame inventory to equip weapons rather than selecting them in the ugly osiris gui.

bruhh, dk literally added skin preview on skinchanger to combat that, also if you say "Calm down mr paster" you can code right? now fucking code inv changer urself retard

**Comment by wemanzoz** [comment]
> > > > and if you say "it's meant for streaming" that's understandable but can't you just disable skin changer on stream? why do you feel the need to fake having something you don't
> > > 
> > > 
> > > Wow calm down mr paster. It's a valid feature request and more convenient to use the ingame inventory to equip weapons rather than selecting them in the ugly osiris gui.
> > 
> > 
> > don't call someone a paster when you're mad that daniel won't add a feature that you could easily code in
> > [#2570 (comment)](https://github.com/danielkrupinski/Osiris/issues/2570#issuecomment-775802703)
> 
> wdym mad about him not adding it? I'm just laughing about this trash cheat 🤣

he wont add inv changer because its useless. "trash cheat" XD dont use osiris then fucking idiot

**Comment by mkot2** [comment]
> 
> 
> > > > > and if you say "it's meant for streaming" that's understandable but can't you just disable skin changer on stream? why do you feel the need to fake having something you don't
> > > > 
> > > > 
> > > > Wow calm down mr paster. It's a valid feature request and more convenient to use the ingame inventory to equip weapons rather than selecting them in the ugly osiris gui.
> > > 
> > > 
> > > don't call someone a paster when you're mad that daniel won't add a feature that you could easily code in
> > > [#2570 (comment)](https://github.com/danielkrupinski/Osiris/issues/2570#issuecomment-775802703)
> > 
> > 
> > making an animfix and making the desync work properly aint that easy chef
> 
> speak for yourself

who am i speaking for if not for myself?

**Comment by wemanzoz** [comment]
this scui dude is retarded tbh

**Comment by HowToMakeFaceitAB** [comment]
> > > > and if you say "it's meant for streaming" that's understandable but can't you just disable skin changer on stream? why do you feel the need to fake having something you don't
> > > 
> > > 
> > > Wow calm down mr paster. It's a valid feature request and more convenient to use the ingame inventory to equip weapons rather than selecting them in the ugly osiris gui.
> > 
> > 
> > don't call someone a paster when you're mad that daniel won't add a feature that you could easily code in
> > [#2570 (comment)](https://github.com/danielkrupinski/Osiris/issues/2570#issuecomment-775802703)
> 
> wdym mad about him not adding it? I'm just laughing about this trash cheat 🤣

says the retarded loser, trash or not we're still smarter than you are, so , in other words, go fuck yourself, shithead

**Comment by Scui1** [comment]
> says the retarded loser, trash or not we're still smarter than you are, so , in other words, go fuck yourself, shithead
Why are you insulting me now? Seems like i hit a sore spot 🤣

**Comment by HowToMakeFaceitAB** [comment]
> > says the retarded loser, trash or not we're still smarter than you are, so , in other words, go fuck yourself, shithead
> 
> Why are you insulting me now? Seems like i hit a sore spot 🤣

no, you didn't, but i was just in a shitty mood that day

**Comment by HowToMakeFaceitAB** [comment]
> > says the retarded loser, trash or not we're still smarter than you are, so , in other words, go fuck yourself, shithead
> 
> Why are you insulting me now? Seems like i hit a sore spot 🤣

and also, fuck you you fucking piece of shit , go live in the streets where you belong, your parents must be dissapointed in your trash ass doing nothing good all day
