### ISSUE TITLE
Different triggerbot binds

### ISSUE THREAD

**Issue by osirisbestlegitcheat** [danielkrupinski/Osiris#2578]
If I use q for my AWPthen i make Zeus trigger bot to mouse2 then my AWP trigger bot will also be mouse2. Please allow us to make separate binds for our trigger bot.

**Comment by ishaangamer27** [comment]
Hey man I had the same issue for Slient aim I use mouse 2 for rifles and alt for pistols or snipers can you please contact me if you find a fix I've already made this issue twice in this poll but nada
