### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Keiserin0** [danielkrupinski/Osiris#258]
I think you can add a callout esp / location esp

**Comment by danielkrupinski** [comment]
How it works?

**Comment by Shaxzy** [comment]
I think OP means feature that spams the chat with info about enemies. 
Example: Shaxzy" | "B Site" | HP: "100" | Gun: "M4A1"

**Comment by EGTLoneWolf** [comment]
My idea was like since there such thing as name esp , why can't there be a esp that shows their location

**Comment by cojo1989** [comment]
This should be interesting

**Comment by EGTLoneWolf** [comment]
I do feel that obs proof would be very useful rn

**Comment by Shaxzy** [comment]
@EGTLoneWolf my mistake. Never seen that before so I thought you meant the chat callout thing.

**Comment by EGTLoneWolf** [comment]
> @EGTLoneWolf my mistake. Never seen that before so I thought you meant the chat callout thing.

Np .
