### ISSUE TITLE
Problem with Injection

### ISSUE THREAD

**Issue by iuliw** [danielkrupinski/Osiris#2580]
Hi, i have a problem with Injection
I use Process Hacker to inject de .dll file and nothing happens
I didn t try another injection tool bcs i don t know wich one is good and wich one is bad
i need some help please!

**Comment by linuxer9** [comment]
you should put your dll in windows folder to bypass injection prevention

**Comment by HowToMakeFaceitAB** [comment]
> Hi, i have a problem with Injection
> I use Process Hacker to inject de .dll file and nothing happens
> I didn t try another injection tool bcs i don t know wich one is good and wich one is bad
> i need some help please!

you can do two things : 
1. use a manual map injector
2. put dll in windows folder and inject using any injection method, it should work perfectly fine

**Comment by HowToMakeFaceitAB** [comment]
> you should put your dll in windows folder to bypass injection prevention

also thank you, i didn't know this. i thought it was bs at first but then i found a thread on uc and tried it out and it was legit, so thx
