### ISSUE TITLE
[Help] meeeeee

### ISSUE THREAD

**Issue by MirzaGorgAli** [danielkrupinski/Osiris#2581]
Hi guys. I need help ( I'm sorry to ask this here no one answer me there ):
Can anyone tell me how to fix this ?:
[An awesome project by notgoodusename](https://github.com/notgoodusename/osiriswithstuff)
When I compile it and choose smoke/decoy (only these two), my game crashes :///
and When I enable "Grenade prediction" in MISC TAB, it fixes this !!!!
Can you guys tell me how to fix it Totally?
and *SORRY ABOUT MY ENGLISH*

Thanks

**Comment by linuxer9** [comment]
find this line in `isEnabled` function

`if (!localPlayer || !localPlayer->isAlive())`

and replace it with

`if (!localPlayer || !localPlayer->isAlive()|| !config->misc.nadePredict)`

**Comment by MirzaGorgAli** [comment]
> find this line in `isEnabled` function
> 
> `if (!localPlayer || !localPlayer->isAlive())`
> 
> and replace it with
> 
> `if (!localPlayer || !localPlayer->isAlive()|| !config->misc.nadePredict)`

I love you @linuxer9. Thank you 😍😍😍
