### ISSUE TITLE
help with #1802

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#2582]
Tried to add bypass sv_pure. Did everything, besides the backtrack related stuffs, giving me errors lol. can't do much on github, so dm Vicarious#002. type your tag below btw so i know

**Comment by mkot2** [comment]
> 
> 
> Tried to add bypass sv_pure. Did everything, besides the backtrack related stuffs, giving me errors lol. can't do much on github, so dm Vicarious#002. type your tag below btw so i know

you need to put the backtrack stuff in too
