### ISSUE TITLE
Should I run CSGO on trusted mode?

### ISSUE THREAD

**Issue by ishaangamer27** [danielkrupinski/Osiris#2589]
Was wondering if i should run CSGO on trusted mode I haven't been banned so far but was wondering If i could cheat and run using trusted mode and i understand that it makes it more obsolete and it also says in can detect patterns of injecting dll's and will lead to a VAC ban is this true?

**Comment by HowToMakeFaceitAB** [comment]
if you use manual map injection method you should be fine, and you should use csghost injector, its really good and undetected.
also i recommend using daniel's vac bypass loader in order to avoid getting banned.

**Comment by Scui1** [comment]
just use extremeinjector and put the dll inside windows folder. Extremeinjector has it's name from being EXTREMELY undetected

**Comment by rosesware** [comment]
> just use extremeinjector and put the dll inside windows folder. Extremeinjector has it's name from being EXTREMELY undetected

You really lose your time like this, funny.

**Comment by NotYetHAX** [comment]
What about Linux?
