### ISSUE TITLE
Rage mode

### ISSUE THREAD

**Issue by CleverSource** [danielkrupinski/Osiris#259]
Add a rage bot, spinbot and all. In general better wallbang stuff would be nice

**Comment by tirziz** [comment]
hvh now is dead now, legit is more funny to play. I prefer some new legit stuff like bomb timer not ragebot

**Comment by Shaxzy** [comment]
@tirziz hvh isn’t dead lmao.

**Comment by EGTLoneWolf** [comment]
Personally I feel that rage is wayy too early for osiris currently . Maybe in the future :D

**Comment by CleverSource** [comment]
I mean max settings on the aimbot already is ragebot at this point, really the only difference is the fact it won't shoot through wallbangable spots.

**Comment by Nyarukocqc** [comment]
It called anti aim not spinbot!

**Comment by danielkrupinski** [comment]
Added wallbang check.
