### ISSUE TITLE
Crash on cfg load

### ISSUE THREAD

**Issue by LafeTV** [danielkrupinski/Osiris#2591]
Hello dear Coder.

I have this one consistent error which comes up everytime i load an config.
When im creating the cofig everything is allright. But when i reload it its crashing my game.
i will put the issue down as a ScreeenShot

Thx for our work keep it up mate

![osiriscrash](https://user-images.githubusercontent.com/79286383/108427806-ff7ebe80-723d-11eb-9156-5fa27151d8f0.png)

**Comment by danielkrupinski** [comment]
Post config file here.

**Comment by LafeTV** [comment]
here you go
[Osiris.zip](https://github.com/danielkrupinski/Osiris/files/6009484/Osiris.zip)

**Comment by danielkrupinski** [comment]
Fixed

**Comment by LafeTV** [comment]
thx
