### ISSUE TITLE
[SUGGESTION] Customizable no-scope crosshair 

### ISSUE THREAD

**Issue by hydemods** [danielkrupinski/Osiris#2592]
Like the title says, make the no-scope crosshair customizable. 
eg. https://youtu.be/QkIyojqsPdk?t=16

**Comment by linuxer9** [comment]
you can set the no-scope crosshair to your original crosshair using the code below, and then change it to whatever you like from csgo settings

```
void Misc::noscopeCrosshair() noexcept
{
    static auto showSpread = interfaces->cvar->findVar("weapon_debug_spread_show");
    showSpread->setValue(config->misc.noscopeCrosshair && localPlayer && !localPlayer->isScoped() ? 3 : 0);
}
```

**Comment by babasheep-alt** [comment]
> you can set the no-scope crosshair to your original crosshair using the code below, and then change it to whatever you like from csgo settings
> 
> ```
> void Misc::noscopeCrosshair() noexcept
> {
>     static auto showSpread = interfaces->cvar->findVar("weapon_debug_spread_show");
>     showSpread->setValue(config->misc.noscopeCrosshair && localPlayer && !localPlayer->isScoped() ? 3 : 0);
> }
> ```

i have this error no operator "&&" matches these operands

**Comment by linuxer9** [comment]
> 
> 
> > you can set the no-scope crosshair to your original crosshair using the code below, and then change it to whatever you like from csgo settings
> > ```
> > void Misc::noscopeCrosshair() noexcept
> > {
> >     static auto showSpread = interfaces->cvar->findVar("weapon_debug_spread_show");
> >     showSpread->setValue(config->misc.noscopeCrosshair && localPlayer && !localPlayer->isScoped() ? 3 : 0);
> > }
> > ```
> 
> i have this error no operator "&&" matches these operands

it's because config->misc.noscopeCrosshair is not a bool, change it to bool type in config.h, change this line:
https://github.com/danielkrupinski/Osiris/blob/d501a97cbfd463f1dfa70ca493bc2a4a198cc269/Osiris/Config.h#L221
to this:
`bool noscopeCrosshair;`
