### ISSUE TITLE
Crashing ??

### ISSUE THREAD

**Issue by blxckshark** [danielkrupinski/Osiris#2593]
![image](https://user-images.githubusercontent.com/73445286/108524854-c7c05700-72cf-11eb-9553-8929d83b2b9c.png)

**Comment by danielkrupinski** [comment]
Show call stack.

**Comment by ClaudiuHKS** [comment]
It crashes for me too. After your commit that takes Observers handle instead of userid, while spectator list is enabled, on deathmatch, for example. In 3-4 minutes.
