### ISSUE TITLE
Radar hack not working in community server

### ISSUE THREAD

**Issue by dz1102** [danielkrupinski/Osiris#2596]
Hi. I just found a problem, the radar hack is not working when I play in community server. However it works perfectly with offline server. 
And also the spectators function is the same, not working with community server that I play. It doesn't show who specs me. But it works with offline server.

**Comment by wemanzoz** [comment]
@danielkrupinski bug?

**Comment by danielkrupinski** [comment]
It would be helpful if you gave an IP address of the server.

**Comment by dz1102** [comment]
103.141.138.68:27065
This is the IP of the server :)
I realize that all the wall hack function does not work here. The spectators does not show, the off screen enemy is not shown (as you can see in the picture, even though I'm standing near t base, I see no off screen indication. The wall hack like chams, glow does not work. The radar not showing. It only works if I see the enemy on my screen. I don't know why.

![image](https://user-images.githubusercontent.com/54879097/108603712-21ae4300-73dc-11eb-8f73-2ac4796da82e.png)

**Comment by dz1102** [comment]
As you can see in this picture, I'm able to see the enemy
![image](https://user-images.githubusercontent.com/54879097/108603939-61295f00-73dd-11eb-948a-e549cdea10c9.png)
But when i look away, it doesn't show the off screen enemy (as it should).
![image](https://user-images.githubusercontent.com/54879097/108603947-74d4c580-73dd-11eb-8e98-7c0469e302c3.png)
The radar, chams, glow is the same. Only the esp for grenade works

**Comment by dz1102** [comment]
> It would be helpful if you gave an IP address of the server.

Can u fix?
