### ISSUE TITLE
GOTV

### ISSUE THREAD

**Issue by pablocs77** [danielkrupinski/Osiris#2598]
I was rage hacking in casual, demolition, deathmatch and arms race for 2 days.
I have spectator menu open and today everytime i join a these games, after a few rounds GOTV will start to spectate me, but tab is showing no viewers.

**Comment by HowToMakeFaceitAB** [comment]
close the issue or edit your comment

**Comment by piee-kun** [comment]
when GOTV spectates you, it means the autodirector has noticed your sick ass play and wants to spectate you now to catch all the good action.
