### ISSUE TITLE
Aim hitchance?

### ISSUE THREAD

**Issue by moonway-dev** [danielkrupinski/Osiris#2599]
Guys who have the source code for AIM HITCHANCE please give it to me.
I tried to integrate quite old hitchance and VS 2019 gives 400 errors.
Does anyone have hitchance for the updated OSIRIS?

**Comment by HowToMakeFaceitAB** [comment]
trace ray hitchance is ideal

**Comment by HowToMakeFaceitAB** [comment]
dont paste it, do it yourself
