### ISSUE TITLE
Problem strcpy

### ISSUE THREAD

**Issue by Obscuretk** [danielkrupinski/Osiris#26]
its says something like _CTR_NO_WARNING or something like that

**Comment by danielkrupinski** [comment]
It's just warning, not an error.

**Comment by LuanDevecchi** [comment]
Hey!
you can fix this warning by using
```cpp
strcpy_s(buf, IM_ARRAYSIZE(buf) , config.misc.clanTag.c_str());
```
you can also hardcode array size to 16.
