### ISSUE TITLE
Radar hack not working in community server

### ISSUE THREAD

**Issue by hungdz1234** [danielkrupinski/Osiris#2605]
Hi. I just found a problem, the radar hack, off screen enemy, spectator list and wallhack function like glow, chams is not working when I play in community server. However it works perfectly with offline server.

This is the IP of the server: 103.141.138.68:27065

As you can see in this picture, I'm able to see the enemy
![image](https://user-images.githubusercontent.com/54879097/108621844-b5792100-7467-11eb-9b88-41ed1a2d22dc.png)
But when i look away, it doesn't show the off screen enemy (as it should).
![image](https://user-images.githubusercontent.com/54879097/108621852-c9248780-7467-11eb-9013-6a2652172055.png)
The radar, chams, glow and other is the same. It only works if I see the enemy on my screen. 
Sorry I accidentally close the issue thread yesterday.

**Comment by blackMasterLord** [comment]
hotguard?🤨

**Comment by dz1102** [comment]
> hotguard?🤨

What do u mean?

**Comment by dz1102** [comment]
> hotguard?🤨

I don't know if it using hotguard or not. I can still use aimbot and other function. Only the wall hack functions like chams, glow, esp, radar,... don't work.

I cheat on this server for 1 year and since last week I can't use these functions like I used to

**Comment by blackMasterLord** [comment]
type "sm plugins" in console and check, use this server hotgurad or not

**Comment by dz1102** [comment]
![image](https://user-images.githubusercontent.com/54879097/108630221-4f57c280-7496-11eb-8f2a-42cb0887479a.png)
I have no idea

**Comment by dz1102** [comment]
> type "sm plugins" in console and check, use this server hotgurad or not

![image](https://user-images.githubusercontent.com/54879097/108630574-056fdc00-7498-11eb-8006-69903354e90e.png)

So what now?

**Comment by blackMasterLord** [comment]
there is no plugin list, so nothing

**Comment by dz1102** [comment]
> there is no plugin list, so nothing

So why the radar not work? I can still cheat on other server but not this one. Kinda sad

**Comment by blackMasterLord** [comment]
just find another server and close this issue

**Comment by linuxer9** [comment]
the server disables radar entirely so unless you implement a custom radar you can't hack the engine radar.
regarding the wallhack, if you can enable chams on enemies so you can add chams with ignore-z too and disable model occlusion and it will function as a wallhack
