### ISSUE TITLE
Custom hitsounds on valve servers.

### ISSUE THREAD

**Issue by sorrowvibez** [danielkrupinski/Osiris#2606]
Can you make custom hitsounds work on valve servers?

**Comment by sorrowvibez** [comment]
@danielkrupinski

**Comment by blackMasterLord** [comment]
what?🤨

**Comment by sorrowvibez** [comment]
> what?🤨

custom hitsounds dont work in matchmaking

**Comment by blackMasterLord** [comment]
everything works fine

1)check hitsound file name 
2)check directory (should be in csgo/sound)

**Comment by 3Ld4D** [comment]
u need to bypass sv_pure to use on valve servers.

**Comment by mkot2** [comment]
#1802

**Comment by sorrowvibez** [comment]
> #1802

sv_pure bypass doesent work anymore
