### ISSUE TITLE
Anti aim

### ISSUE THREAD

**Issue by moonway-dev** [danielkrupinski/Osiris#2608]
Hi guys. I would like to inquire about anti aim. Does anyone have a code with a normal anti aim. For some reason this does not unfold the player. WTF? Anti aim looks forward. What is the point if it does not fulfill its function yet.

**Comment by wemanzoz** [comment]
needs animfix, and you dont need anti aim lol. its a legit cheat

**Comment by linuxer9** [comment]
See PR 2074, vanilla osiris is not an HvH software.
