### ISSUE TITLE
Plant the C4 faster

### ISSUE THREAD

**Issue by tirziz** [danielkrupinski/Osiris#261]
All credit goes to masterloser .
Usually when planting a bomb, you have to run through a part of the site ( even when holding E and running ). this tweak will fix it.

```
void FixedBombPlant(CUserCmd* cmd){
    if (!(cmd->buttons & IN_USE) && !(cmd->buttons & IN_ATTACK))return; if (!pLocal || pLocal->GetHealth() <= 0)return;
    C_BaseCombatWeapon* pWeapon = (C_BaseCombatWeapon*)pLocal->GetActive();
    if (!pWeapon || !pWeapon->IsBomb() || pLocal->getm_bInBombZone())return;//m_bInBombZone
 
    //dont run 10m into site
    cmd->buttons &= ~IN_USE;
    cmd->buttons &= ~IN_ATTACK;
}
```

**Comment by HeadlessCpp** [comment]
`	
constexpr void FixedBombPlant(UserCmd* cmd) {
		if (config.misc.fastplant) {
			const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());

			if (!(cmd->buttons & UserCmd::IN_ATTACK))
				return;

			if (!localPlayer || !localPlayer->isAlive())
				return;

			const auto activeWeapon = interfaces.entityList->getEntityFromHandle(localPlayer->getProperty<int>("m_hActiveWeapon"));

			if (!activeWeapon || !(activeWeapon->getProperty<WeaponId>("m_iItemDefinitionIndex") == WeaponId::C4) || !localPlayer->getProperty<bool>("m_bInBombZone"))
				return;

			cmd->buttons |= (UserCmd::IN_ATTACK);
		}
	}
`

**Comment by HeadlessCpp** [comment]
```c
constexpr void FixedBombPlant(UserCmd* cmd) {
        if (config.misc.fastplant) {
		const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());

		if (!(cmd->buttons & UserCmd::IN_ATTACK))
				return;

		if (!localPlayer || !localPlayer->isAlive())
				return;

		const auto activeWeapon = interfaces.entityList->getEntityFromHandle(localPlayer->getProperty<int>("m_hActiveWeapon"));

		if (!activeWeapon || !(activeWeapon->getProperty<WeaponId>("m_iItemDefinitionIndex") == WeaponId::C4) || !localPlayer->getProperty<bool>("m_bInBombZone"))
			return;

		cmd->buttons |= (UserCmd::IN_ATTACK);
	}
}
```

**Comment by danielkrupinski** [comment]
Added. Also supports door interaction while holding bomb.
