### ISSUE TITLE
smoke tactics demonstrator

### ISSUE THREAD

**Issue by Swayy1337** [danielkrupinski/Osiris#2610]
**smoke tactics demonstrator**  very good legit.

photo:  https://hizliresim.com/jagFKt

**Comment by linuxer9** [comment]
I ported this feature from sensum but it is buggy

**Comment by wemanzoz** [comment]
> I ported this feature from sensum but it is buggy

make a pull plez

**Comment by Scui1** [comment]
easy to do, already [done in aimtux](https://github.com/AimTuxOfficial/AimTux/blob/master/src/Hacks/grenadehelper.cpp)

**Comment by osirisbigfan** [comment]
> easy to do, already [done in aimtux](https://github.com/AimTuxOfficial/AimTux/blob/master/src/Hacks/grenadehelper.cpp)

how can i add it in my osiris build without errors?

**Comment by Scui1** [comment]
> how can i add it in my osiris build without errors?

That's almost impossible, you really need to be a nasa engineer to be able to do that
