### ISSUE TITLE
[question] How would I "stop" myself holding down buttons 

### ISSUE THREAD

**Issue by Nigma1337** [danielkrupinski/Osiris#2614]
I'm currently trying to create an auto stop, but i'm kinda getting stuck on how i'd stop, when i hold something down. 

It seems that me holding down m1 or some other button will make my cmd->forwaardmmove = 0.0f; not do anything.
I've also tried just taking the code from fast stop, but that only works again when a user isn't holding down any buttons.

Any help is apperciated

**Comment by hydemods** [comment]
use the slow walk feature

**Comment by Bakedpurple** [comment]
#2411
