### ISSUE TITLE
Finding a good DLL injecter

### ISSUE THREAD

**Issue by roodje123** [danielkrupinski/Osiris#2616]
Does someone have a good DLL injector?

**Comment by Leak3611** [comment]
GuidedHacking injector.

**Comment by linuxer9** [comment]
memject
shtreeba
process hacker 2 (put the dll in windows folder)

**Comment by osirisbestlegitcheat** [comment]
The easiest to use injector to use is CSGhostV3 you can download directly from https://anonym.ninja/download/kHMglIRSeobXFKt.
