### ISSUE TITLE
After CSGO UPDATE today, Crash when injected

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#2618]
CSGO has been updated minutes ago
After CSGO UPDATE today, Crash when injected

Regards

[CFG_LEGIT.zip](https://github.com/danielkrupinski/Osiris/files/6047100/CFG_LEGIT.zip)

**Comment by cacvabuoi** [comment]
yep i got crashed right after load a config, verify the game didnt help

**Comment by smurfsmfc** [comment]
> yep i got crashed right after load a config, verify the game didnt help

Skin changer is crashing the game disable it and you are fine :)

**Comment by ishaangamer27** [comment]
same with me i thought i was the only one will there be a fix

**Comment by ishaangamer27** [comment]
> > yep i got crashed right after load a config, verify the game didnt help
> 
> Skin changer is crashing the game disable it and you are fine :)

but if I want to load a config that has a skin-changer what do I do?

**Comment by mina9999** [comment]
yes also aa dosnt work too
