### ISSUE TITLE
Osiris Fps Drops After Update

### ISSUE THREAD

**Issue by KesuX** [danielkrupinski/Osiris#2621]
before this new update i had 200 fps something like that .
And after the update i have my fps locked to 30 and it's very often fall to 9 fps and the game is not playable .
Someone know how to fix that?

**Comment by uzdiiilekk** [comment]
Message me on discord i send you protected osiris with fixed fps - uzdiiilekk_#3312

**Comment by wemanzoz** [comment]
how r u playing it lol, it crashes

**Comment by wemanzoz** [comment]
nvm

**Comment by KesuX** [comment]
It don't crash for me im using sazinjector and manual  map :p

**Comment by KesuX** [comment]
> Message me on discord i send you protected osiris with fixed fps - uzdiiilekk_#3312

added u

**Comment by osirisbigfan** [comment]
same

**Comment by osirisbigfan** [comment]
> Message me on discord i send you protected osiris with fixed fps - uzdiiilekk_#3312

how do you fixed it? i want to fix it in my build

**Comment by wemanzoz** [comment]
> > Message me on discord i send you protected osiris with fixed fps - uzdiiilekk_#3312
> 
> how do you fixed it? i want to fix it in my build

download the newest build in the code section
