### ISSUE TITLE
nothing showing up after injection

### ISSUE THREAD

**Issue by lauge123** [danielkrupinski/Osiris#2622]
so a week a go i used osiris and i got overwacth banned. but after a small break from cheating in cs i can't use the osiris when a start cs and after start the injector i have (1tap injector) and i worked a week ago with that injector but now when i do the same things as a did a week ago nothing shows up anymore ingame as i normaly did. and yes all my anti-virus programs is truned off.
what can cause this problem I have tried to reinstall the dll file and injector i have use it's still the same probelm i run into. I have tried to run my injector as administrator but then i can't put the dll file into the injector.

can it be the new opdate that came out some days ago,. that maube does do it not works. i have onetap to but the wornt work either atm.

**Comment by rosesware** [comment]
> I have tried to run my injector as administrator but then i can't put the dll file into the injector.

Makes no sense, the injector need admin permissions to inject something. Close this issue.
