### ISSUE TITLE
cheat doesnt injecting

### ISSUE THREAD

**Issue by ZokyChecks** [danielkrupinski/Osiris#2632]
yesterday all worked fine but today it crashes or doesnt injecting

**Comment by cacvabuoi** [comment]
daniel updated the cheat you should recompile it

**Comment by HowToMakeFaceitAB** [comment]
download the latest build and compile it, otherwise it'll crash

**Comment by distinguisherdev** [comment]
still crashes, what injector do you guys use?

**Comment by cacvabuoi** [comment]
i used csghost v3.1 from uc

**Comment by ZokyChecks** [comment]
> daniel updated the cheat you should recompile it

thank you!
