### ISSUE TITLE
multiple hitbox on triggerbot

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#2640]
yeah, would be cool if this is added. (very useful for getting awp flicks etc)

**Comment by osirisbigfan** [comment]
just use "all" hitboxes

**Comment by wemanzoz** [comment]
> just use "all" hitboxes

tfw you shoot toes when trying to flick

**Comment by linuxer9** [comment]
> 
> 
> > just use "all" hitboxes
> 
> tfw you shoot toes when trying to flick

you set your minimum damage to 86 for AWP for example
and choose the nearest bone
then the aimbot will flick to any bone except the feet (as they deal 85 damage)
