### ISSUE TITLE
[Suggestion] Change default weapon sounds

### ISSUE THREAD

**Issue by MirzaGorgAli** [danielkrupinski/Osiris#2642]
Check this : [How to Replace Weapon Sounds](https://www.unknowncheats.me/forum/counterstrike-global-offensive/216322-replace-weapon-sounds.html)

It is awesome If you add, sir @danielkrupinski or anybody else

**THANKS**

***Sorry About My English***

**Comment by Cryptor-droid** [comment]
Hello, you may want to look at the misc.cpp file and browse for Misc::playHitSound when you find that void you will get an idea how to play a sound in game. I made my headshot sound custom that way.

**Comment by MirzaGorgAli** [comment]
> 
> 
> Hello, you may want to look at the misc.cpp file and browse for Misc::playHitSound when you find that void you will get an idea how to play a sound in game. I made my headshot sound custom that way.

Hi man. I know that but I want to change default weapon sounds. something like:
When you reload a weapon It plays a custom sound you added
