### ISSUE TITLE
My build got detected after using MinHook.

### ISSUE THREAD

**Issue by MorganaBRKSRL** [danielkrupinski/Osiris#2649]
Hello, I've downloaded Osiris, changed it and got banned with minhook. What do you guys use as hooking method ?

**Comment by linuxer9** [comment]
probably detected injector 
what injector did you use?

**Comment by wemanzoz** [comment]
injector issue? what injector

**Comment by MorganaBRKSRL** [comment]
Oh, what injector would you recommend ? Are there any sources for undetected injectors, as I want to make my own ?

**Comment by linuxer9** [comment]
-shtreeba
-memject
-process hacker 2
-any public and detected injector using vac bypass
remember to change your old build probably it got sigged

**Comment by Scui1** [comment]
MinHook is trash anyways 😅 
Did you get vac or ow banned?

**Comment by mkot2** [comment]
> 
> 
> MinHook is trash anyways 😅

continue to use detected VMT then retard what else do you want to use

**Comment by Scui1** [comment]
> 
> 
> > MinHook is trash anyways 😅
> 
> continue to use detected VMT then retard what else do you want to use

vmt is not detected if done right, retard 🤣

**Comment by wemanzoz** [comment]
> > > MinHook is trash anyways 😅
> > 
> > 
> > continue to use detected VMT then retard what else do you want to use
> 
> vmt is not detected if done right, retard 🤣

ROFL

**Comment by mkot2** [comment]
> 
> 
> > > MinHook is trash anyways 😅
> > 
> > 
> > continue to use detected VMT then retard what else do you want to use
> 
> vmt is not detected if done right, retard 🤣

wdym "done right", vmt is easily detectable

**Comment by SphinX2k6** [comment]
> > > > MinHook is trash anyways 😅
> > > 
> > > 
> > > continue to use detected VMT then retard what else do you want to use
> > 
> > 
> > vmt is not detected if done right, retard 🤣
> 
> wdym "done right", vmt is easily detectable

Minhook
Uses inline function patching (jmp trampolines).
Easier for anti-cheats to detect

VMT
Changes virtual table pointers instead of patching code bytes.
Usually less obvious than inline hooks
