### ISSUE TITLE
dll download link

### ISSUE THREAD

**Issue by ImLorio** [danielkrupinski/Osiris#2651]
Can you make release with the dll thx

**Comment by danielkrupinski** [comment]
No

**Comment by VuBrian22** [comment]
Lmao imagine being a fellow developer and not being able to compile a simple dll....like c'mon seriously smh.

**Comment by ImLorio** [comment]
> Lmao imagine being a fellow developer and not being able to compile a simple dll....like c'mon seriously smh.

Lmao imagine having a good connection to be able to install Visual Studio.

**Comment by danielkrupinski** [comment]
You can setup GitHub Actions to build a .dll for you and then download it.

**Comment by VuBrian22** [comment]
> > Lmao imagine being a fellow developer and not being able to compile a simple dll....like c'mon seriously smh.
> 
> Lmao imagine having a good connection to be able to install Visual Studio.

You could try what daniel suggested. Or you don't even need Visual Studio at all to compile a dll. You can use MinGW to compile C++ to a DLL from the commandline. Or you can just use a stand-alone version of MSBuild Tools and compile the dll from the commandline. You don't need to download 24GB of stuff you don't need from Visual Studio. Like Imagine not having ligthweight alternatives...smh
