### ISSUE TITLE
Invisible menu

### ISSUE THREAD

**Issue by Deciy** [danielkrupinski/Osiris#2654]
After opening up skinchanger/esp the menu goes invisible. The only way to solve it is by restarting your game

**Comment by wemanzoz** [comment]
u sure? lemme try this

**Comment by wemanzoz** [comment]
> u sure? lemme try this

false information, close this thread

**Comment by Deciy** [comment]
1, He just updated it
2, you don't choose when I close the thread, sorry, the world doesn't revolve around you
3, It doesn't happen everytime
4, Im still investigating the glitch to find out why it's happening

**Comment by Deciy** [comment]
Issue was handled in newest update #2643

**Comment by wemanzoz** [comment]
> 1, He just updated it
> 2, you don't choose when I close the thread, sorry, the world doesn't revolve around you
> 3, It doesn't happen everytime
> 4, Im still investigating the glitch to find out why it's happening

:kekw:

**Comment by Deciy** [comment]
> > 1, He just updated it
> > 2, you don't choose when I close the thread, sorry, the world doesn't revolve around you
> > 3, It doesn't happen everytime
> > 4, Im still investigating the glitch to find out why it's happening
> 
> :kekw:

Damn. Imagine saying kekw unironically
