### ISSUE TITLE
[SUGGESTION] dead (ragdoll) chams

### ISSUE THREAD

**Issue by wirekuro** [danielkrupinski/Osiris#2655]
I'd be really thankful if you'd add ragdoll chams.

**Comment by KisSsArt** [comment]
the same as in the skeet?

**Comment by wirekuro** [comment]
![de_mirage0015](https://user-images.githubusercontent.com/75095332/110217274-64c7e600-7eb3-11eb-892d-4f1e262a65c3.png)

**Comment by KisSsArt** [comment]
mmmmmm i can add it

**Comment by KisSsArt** [comment]
check pull request <3

**Comment by wirekuro** [comment]
> check pull request <3

luv u <3
