### ISSUE TITLE
failed to find VBaseFileSystem0011 interface

### ISSUE THREAD

**Issue by hentaidono** [danielkrupinski/Osiris#2656]
I do not have any idea what is this
I inject VAC-Bypass first then the Osiris into the CSGO then the error "failed to find VBaseFileSystem0011 interface" after these CSGO and steam stops working and I should force stop them from task manager : | HELP !

**Comment by blackMasterLord** [comment]
`filesystem_stdio.dll - VBaseFileSystem011`
works great

**Comment by wemanzoz** [comment]
wdym inject vacbypass? you dont inject vacbypass to csgo

**Comment by hentaidono** [comment]
> wdym inject vacbypass? you dont inject vacbypass to csgo

nvm that wasn't the problem the whole thing is that I inject Osiris into the CSGO I get that error from Osiris itself and then CSGO and steam stops working until I end the tasks ..

**Comment by hentaidono** [comment]
> `filesystem_stdio.dll - VBaseFileSystem011`
> works great

I did a little bit search about these the thing I found was reinstalling steam , I did it , It did not solve anything.
Any idea?
