### ISSUE TITLE
Hotkey - Unable to use extra mouse keys (ex. 4 or 5) for hotkey

### ISSUE THREAD

**Issue by Wadimabr** [danielkrupinski/Osiris#266]
**Description:**
Unable to set extra mouse key as a hotkey.

**Actual result:**
Setting Mouse 5 button for triggerbot hotkey does nothing.

**Expected result:**
User is able to set any button as a hotkey.

**Comment by bruteforcehacker** [comment]
https://docs.microsoft.com/en-us/windows/desktop/inputdev/about-mouse-input 

Maybe study this and try to fix it urself?

**Comment by danielkrupinski** [comment]
Should be working now.
