### ISSUE TITLE
Who can help with code

### ISSUE THREAD

**Issue by pixelsurf123** [danielkrupinski/Osiris#2661]
Who can help me why my code dont work

void Misc::bombdefusel(UserCmd* cmd) noexcept
{
    if (!config->misc.defuselasttick || !localPlayer || !localPlayer->isAlive())
        return;
        for (int i = interfaces->engine->getMaxClients(); i <= interfaces->entityList->getHighestEntityIndex(); i++) {
            Entity* entity = interfaces->entityList->getEntity(i);
            continue;

        float flBlow = (entity->c4BlowTime());
        float lifetime = (memory->globalVars->intervalPerTick * localPlayer->tickBase());
        if (lifetime < (localPlayer->hasDefuser() ? 5.1f : 10.1f))
            cmd->buttons |= UserCmd::IN_USE;
    }
}

**Comment by blackMasterLord** [comment]
```
void Misc::bombdefusel(UserCmd* cmd) noexcept
{
    if (!config->misc.defuselasttick || !localPlayer || !localPlayer->isAlive() || localPlayer->team() != 3)
        return;

    GameData::Lock lock;

    const auto& plantedC4 = GameData::plantedC4();
    if (plantedC4.blowTime == 0.0f)
        return;

    if (const auto networkChannel = interfaces->engine->getNetworkChannel())
    {
        const auto outgoing_latency = networkChannel->getLatency(0);

        const auto countdown = plantedC4.blowTime - memory->globalVars->currenttime;
        const auto last_time = (localPlayer->hasDefuser() ? 5.f : 10.f) + (memory->globalVars->intervalPerTick * 4 + outgoing_latency);

        if (countdown <= last_time)
            cmd->buttons |= UserCmd::IN_USE;
    }
}
```
