### ISSUE TITLE
Hooking to entity::eyeangles function.

### ISSUE THREAD

**Issue by Cryptor-droid** [danielkrupinski/Osiris#2662]
Hello I made very simple anti aim engine and I want to visualise my anti aim angles. I made lag visualiser by setuping local player bones when sendpacket is true and calling drawmodelexecute accordingly. The part that I failed to do is hooking to eyeangles function. If you guys help me with that I am willing to work on fake and real player model visualiser with you.

**Comment by Scui1** [comment]
Okay nice that you made an "anti aim engine". What part of hooking eyeAngles do you struggle with?

**Comment by Cryptor-droid** [comment]
I have looked in the hooks.cpp and hooks.h files and got an idea how it would be but I have no idea what should I use as a base. I don't know that to write inside eyehook.init() function. (I'm learning c++)

**Comment by InfernoLum** [comment]
```	QAngle* __fastcall hkEyeAngles(void* _this, void*)
	{
		C_BaseEntity* ent = (C_BaseEntity*)_this;

		static auto oEyeAngles = playerHooks[ent->EntIndex()].VMThook.GetOriginalFunc<decltype(&hkEyeAngles)>(169);

		static auto retPitch = Utils::PatternScan(GetModuleHandleA(_("client.dll")), _("8B CE F3 0F 10 00 8B 06 F3 0F 11 45 ? FF 90 ? ? ? ? F3 0F 10 55 ?"));
		static auto retYaw = Utils::PatternScan(GetModuleHandleA(_("client.dll")), _("F3 0F 10 55 ? 51 8B 8E ? ? ? ?"));

		if (_this != (void*)(g_LocalPlayer))
			return oEyeAngles(_this, 0);

		if (_ReturnAddress() == retPitch || _ReturnAddress() == retYaw)
			return &yourDesiredViewAngles;

		if (!g_Input->m_fCameraInThirdPerson)
			return oEyeAngles(_this, 0);

		return oEyeAngles(_this, 0);
	}```
This isn't for osiris specifically, this is the code in my cheat.
If you want to know why exactly certain things are done the way they are checkout this post
https://www.unknowncheats.me/forum/counterstrike-global-offensive/340475-properly-setting-thirdperson-angles.html

How to hook: 
1. Init your vmt hook with your local entity ( C_BaseEntity* or whatever its called in osiris )
2. Hook the function with index 169 ( that's the index of EyeAngles ) 
3. ???
4. Profit

**Comment by Cryptor-droid** [comment]
@InfernoLum I have seen the link you have given but I couldn't understand it. Your example however is very helpful, thank you. I'm will share my hooks.cpp and hooks.h files if I succeed so the person after me wouldn't deal with this.
