### ISSUE TITLE
[INJECTOR] What's the best injector for Osiris>undetected

### ISSUE THREAD

**Issue by ishaangamer27** [danielkrupinski/Osiris#2664]
I've been using Osiris for a couple of months still no ban I now currently use CSGHOST v3 along with VAC bypass is there a better alternative or should I just stick to the "if it ain't broke don't fix it"

**Comment by Scui1** [comment]
No it's good 😄

**Comment by acey1337** [comment]
GH injector, extreme injector, process hacker 2 to name a few

**Comment by SlicedDev** [comment]
Sazinjector pretty good with vac bypass
