### ISSUE TITLE
Vote Revealer

### ISSUE THREAD

**Issue by shakeit1337** [danielkrupinski/Osiris#2667]
have one a code for Vote Revealer? 

make pls a Pull.

**Comment by wemanzoz** [comment]
@danielkrupinski consider adding this? ik it sounds useless but, its cool

**Comment by dapaster** [comment]
Hint:

    event.getInt("vote_option");
    event.getInt("entityid");

**Comment by mkot2** [comment]
> 
> 
> Hint:
> 
> ```
> event.getInt("vote_option");
> event.getInt("entityid");
> ```

how to output to local chat

**Comment by dapaster** [comment]
> > Hint:
> > ```
> > event.getInt("vote_option");
> > event.getInt("entityid");
> > ```
> 
> how to output to local chat

interfaces->engine->clientCmdUnrestricted

`say`

**Comment by mkot2** [comment]
> 
> 
> > > Hint:
> > > ```
> > > event.getInt("vote_option");
> > > event.getInt("entityid");
> > > ```
> > 
> > 
> > how to output to local chat
> 
> interfaces->engine->clientCmdUnrestricted
> 
> `say`

doesnt that send the message to chat?

**Comment by danielkrupinski** [comment]
Added
