### ISSUE TITLE
resolver, model changer, cleaner visuals (similar to how onetap,advanced aim,skeet's visuals are) 

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#2668]
just some suggestions not a coder so not sure how hard it would be to implement.

**Comment by danielkrupinski** [comment]
What do you mean by "cleaner visuals" ?

**Comment by kamikazeghost** [comment]
> What do you mean by "cleaner visuals" ?

its most likely a preference thing but the text, health bar doesn't exactly look as clean as something like advanced aim, onetap and such the chams can be a bit buggy too

**Comment by aHf58fK5K8hD2fKu7** [comment]
> 
> 
> > What do you mean by "cleaner visuals" ?
> 
> its most likely a preference thing but the text, health bar doesn't exactly look as clean as something like advanced aim, onetap and such the chams can be a bit buggy too

but it's original, not pasted from/like any other cheat

**Comment by kamikazeghost** [comment]
> > > What do you mean by "cleaner visuals" ?
> > 
> > 
> > its most likely a preference thing but the text, health bar doesn't exactly look as clean as something like advanced aim, onetap and such the chams can be a bit buggy too
> 
> but it's original, not pasted from/like any other cheat

i think other ones look much much cleaner, maybe a choice to switch between a "onetap/skeet" type one and the one that's used right now

**Comment by linuxer9** [comment]
so you are talking about ESP visuals? not the menu itself
yes the default settings looks aweful, make your settings look nice, try different fonts, semi transparent colors, different color for each thing, appropriate cull distance, and then it would be better than anything else.
those P2C videos are ads, they intentionally use better configs to sell.
osiris ESP is near perfect with the appropriate settings, it only would be perfect if it had armor and dormant ESP but you can paste them from GOESP, it's the same base
if you don't like rainbow health bar, well, remove it and add your own with simple colored line, if you want fancy round cornered boxes, it's pretty easy too just change the god damn source

the same thing goes for chams, just use better settings, or even change the default materials from the source itself!
