### ISSUE TITLE
Legit AA

### ISSUE THREAD

**Issue by bruteforcehacker** [danielkrupinski/Osiris#267]
Legit AA?

https://www.unknowncheats.me/forum/counterstrike-global-offensive/232942-legit-anti-aim.html

Help?

**Comment by synvy** [comment]
That's old and won't work anymore since fake angles were "patched".

**Comment by bruteforcehacker** [comment]
https://void.to/Thread-Legit-AA-Source?page=2  ? Can’t see what is in the link page block for me maybe this works?

**Comment by effex1337** [comment]
That wont work as well
Just look at the date Feb 2018

**Comment by NexSqaud** [comment]
That works! I saw a video where they played with legit aa, dated May 13, 2019

**Comment by effex1337** [comment]
How is that not using fake angles?

**Comment by NexSqaud** [comment]
No, that using usual AA algorithms, but w/o jitters or spin

**Comment by Shaxzy** [comment]
I use legit aa when I play against rage hackers. The way the aa works is because of desync anti aim I think
