### ISSUE TITLE
About faceit anticheat

### ISSUE THREAD

**Issue by bootkitt** [danielkrupinski/Osiris#2673]
After doing a little browsing about Faceit anticheat, I noticed something.

Faceit injects faceit.sys file into the system while the computer is booting.

BOOT Start - FACEIT.sys

> %systemroot%/System32/Drivers >> FACEIT.sys
> C:/Windows/System32/Drivers >> FACEIT.sys

If I stop it through faceit.sys ph (process-hacker), it understands faceit ac ph (process-hacker).
And it asks you to restart the computer.

So how can we stop this .sys file that prevents dll injection in the system.

My opinion is that we can overcome this in 2 ways.
1- unload faceit.sys without restart.
2- making an injector that can blind this anti-injection.

Manualmap is a very good foundation for this, but I don't know what I can do.

Can those who want to help me on this subject contact me privately?

MAIL: technolite2007@yandex.com
Discord: ᛋᛋBootKitᛋᛋ#2368

**Comment by wemanzoz** [comment]
go on uc, better solution for you. since most of us here are brainlets

**Comment by DoctorYasin** [comment]
> go on uc, better solution for you. since most of us here are brainlets

There is nothing else in uc except just talking about the subject.

**Comment by wemanzoz** [comment]
> > go on uc, better solution for you. since most of us here are brainlets
> 
> There is nothing else in uc except just talking about the subject.

Just tell them your shit, serveral people will answer your question. including kittenpop, masterlooser if its interesting for them

**Comment by Scui1** [comment]
Ye bro, just unload their driver, this will definetly work!!! Easy bajpass 😎

**Comment by DoctorYasin** [comment]
> You don't need to do that much work to bajpass faceit. Just use extremeinjector and inject osiris into running csgo. Faceit won't notice it, trust me, I speak from experience 😎

are you seriously :D omg.

**Comment by DoctorYasin** [comment]
> You don't need to do that much work to bajpass faceit. Just use extremeinjector and inject osiris into running csgo. Faceit won't notice it, trust me, I speak from experience 😎

extremeinjector does not see csgo.exe :|

**Comment by MirzaGorgAli** [comment]
> 
> 
> After doing a little browsing about Faceit anticheat, I noticed something.
> 
> Faceit injects faceit.sys file into the system while the computer is booting.
> 
> BOOT Start - FACEIT.sys
> 
> > %systemroot%/System32/Drivers >> FACEIT.sys
> > C:/Windows/System32/Drivers >> FACEIT.sys
> 
> If I stop it through faceit.sys ph (process-hacker), it understands faceit ac ph (process-hacker).
> And it asks you to restart the computer.
> 
> So how can we stop this .sys file that prevents dll injection in the system.
> 
> My opinion is that we can overcome this in 2 ways.
> 1- unload faceit.sys without restart.
> 2- making an injector that can blind this anti-injection.
> 
> Manualmap is a very good foundation for this, but I don't know what I can do.
> 
> Can those who want to help me on this subject contact me privately?
> 
> MAIL: [technolite2007@yandex.com](mailto:technolite2007@yandex.com)
> Discord: ᛋᛋBootKitᛋᛋ#2368

Hi Man. First of all read this: [GuidedHacking(Faceit AC)](https://guidedhacking.com/threads/anticheat-faceit-bypass.16113/)
If you want to bypass it you must have enough knowledge, because it is difficult to bypass.

You can bypass **EAC**, **BATTLEYE** and **FACEIT SERVER SIDE AC** with a kernel driver but **FACEIT CLIENT SIDE AC** in not like these three

***SORRY ABOUT MY ENGLISH***

**Comment by DoctorYasin** [comment]
> > After doing a little browsing about Faceit anticheat, I noticed something.
> > Faceit injects faceit.sys file into the system while the computer is booting.
> > BOOT Start - FACEIT.sys
> > > %systemroot%/System32/Drivers >> FACEIT.sys
> > > C:/Windows/System32/Drivers >> FACEIT.sys
> > 
> > 
> > If I stop it through faceit.sys ph (process-hacker), it understands faceit ac ph (process-hacker).
> > And it asks you to restart the computer.
> > So how can we stop this .sys file that prevents dll injection in the system.
> > My opinion is that we can overcome this in 2 ways.
> > 1- unload faceit.sys without restart.
> > 2- making an injector that can blind this anti-injection.
> > Manualmap is a very good foundation for this, but I don't know what I can do.
> > Can those who want to help me on this subject contact me privately?
> > MAIL: [technolite2007@yandex.com](mailto:technolite2007@yandex.com)
> > Discord: ᛋᛋBootKitᛋᛋ#2368
> 
> Hi Man. First of all read this: [GuidedHacking(Faceit AC)](https://guidedhacking.com/threads/anticheat-faceit-bypass.16113/)
> If you want to bypass it you must have enough knowledge, because it is difficult to bypass.
> 
> You can bypass **EAC**, **BATTLEYE** and **FACEIT SERVER SIDE AC** with a kernel driver but **FACEIT CLIENT SIDE AC** in not like these three
> 
> _**SORRY ABOUT MY ENGLISH**_

thanks bro.

I did some more research. The faceit ac notices this when you disable faceit.sys. and asks us to reboot the system.
the only remedy is the kerneldriver injector.

**Comment by AnriGameS** [comment]
> You don't need to do that much work to bajpass faceit. Just use extremeinjector and inject osiris into running csgo. Faceit won't notice it, trust me, I speak from experience 😎

Where could I get extreme injector?
