### ISSUE TITLE
Can't seem to save, create, or reset configs

### ISSUE THREAD

**Issue by KurastikO** [danielkrupinski/Osiris#2674]
**I don't know what's creating this problem, I've tried many things including reinstalling CS:GO and it's still not saving configs. Maybe a little help**

**Comment by wemanzoz** [comment]
hmm, build issue?

**Comment by blackMasterLord** [comment]
if u using windows 10, check **defender -> controlled folder access**

**Comment by KurastikO** [comment]
Thank you!
