### ISSUE TITLE
[Suggestion] Grenade Helper. 

### ISSUE THREAD

**Issue by ghostboy2112** [danielkrupinski/Osiris#2675]
As osiris is a legit cheat and then best legit cheat available in the community. the only thing which it misses on is Grenade Helper. the Grenade Helper make a player looks so legit and the risk of overwatch is also reduced a lot. so its a humble request to add a grenade helper.

**Comment by acey1337** [comment]
it's better to learn your grenades man

**Comment by blackMasterLord** [comment]
its possible but it's as hard to as add a good inventory changer:
1) need db with nades
2) need good GH (you can paste it, but it will need to improve)
3) a lot of work with gui

**Comment by wemanzoz** [comment]
> its possible but it's as hard to as add a good inventory changer:
> 
> 1. need db with nades
> 2. need good GH (you can paste it, but it will need to improve)
> 3. a lot of work with gui

sensum nade helper is without db, and i guess you can paste it from sensum. or aimtux's

**Comment by linuxer9** [comment]
> 
> 
> its possible but it's as hard to as add a good inventory changer:
> 
>     1. need db with nades
> 
>     2. need good GH (you can paste it, but it will need to improve)
> 
>     3. a lot of work with gui

it's not that hard, the database already exists, sensum hardcode it's db in a header file, ratpoison puts it in a text files
https://github.com/TheRatCode/RatPoison/tree/master/settings/NadeHelper
just import these coordinations and use world to screen function and draw lines or text

**Comment by ghostboy2112** [comment]
thanks for help guys.
