### ISSUE TITLE
Osiris keeps crashing

### ISSUE THREAD

**Issue by wade0202** [danielkrupinski/Osiris#2680]
Hey, I'm using Osiris v2, and when I inject it it's fine but 5-10 minutes in the game it crashes, and it keeps crashing until I turn off the cheat. Any solutions?

**Comment by uzdiiilekk** [comment]
What is osiris “v2” ?

**Comment by wade0202** [comment]
I downloaded a source it's basically Osiris but with a new menu.

**Comment by danielkrupinski** [comment]
I can't help you if you're using a modified source.

**Comment by FlameProfi** [comment]
Were you able to fix the problem?
