### ISSUE TITLE
how i can do delay

### ISSUE THREAD

**Issue by pixelsurf123** [danielkrupinski/Osiris#2682]
how i can do delay look like
if(localplayer flag 1)
In_duck
delay
-in_duck

**Comment by blackMasterLord** [comment]
like this?
```
static float last_duck = 0.f;
int duck_delay;
if(localPlayer flag 1)
{
last_duck = memory->globalVars->realtime;
in_duck
}

if(last_duck + duck_delay = memory->globalVars->realtime)
{
-in_duck
}
```

**Comment by pixelsurf123** [comment]
Thanks

**Comment by pixelsurf123** [comment]
![image](https://user-images.githubusercontent.com/57488947/110675185-a9b98880-81e3-11eb-8c6b-34bf625ed1fc.png)
hm why wrong

> like this?
> 
> ```
> static float last_duck = 0.f;
> int duck_delay = 2.f;
> if(localPlayer flag 1)
> {
> last_duck = memory->globalVars->realtime;
> in_duck
> }
> 
> if(last_duck + duck_delay = memory->globalVars->realtime)
> {
> -in_duck
> }
> ```

**Comment by blackMasterLord** [comment]
if(last_duck + duck_delay == memory->globalVars->realtime)

**Comment by pixelsurf123** [comment]
it delay in sec or in tick?

> *float duck_delay = 2.f;

**Comment by blackMasterLord** [comment]
in seconds
