### ISSUE TITLE
[SUGGESTION] Reaction Time System and Auto Stop

### ISSUE THREAD

**Issue by godasuna** [danielkrupinski/Osiris#2683]
Adding a Reaction Time System in ms and an Auto Stop on shoot, would be really nice for peeking

**Comment by osirisbigfan** [comment]
i dont think that reaction time system is necessary and for auto stop, just use fast stop

**Comment by mkot2** [comment]
> 
> 
> i dont think that reaction time system is necessary and for auto stop, just use fast stop

no need to use fast stop, just press the opposite key right?

**Comment by osirisbigfan** [comment]
> > i dont think that reaction time system is necessary and for auto stop, just use fast stop
> 
> no need to use fast stop, just press the opposite key right?

if u dont want use fast stop, yes.
