### ISSUE TITLE
how i can track loacalplayer

### ISSUE THREAD

**Issue by pixelsurf123** [danielkrupinski/Osiris#2685]
how i can track loacalplayer when he on surf?

**Comment by blackMasterLord** [comment]
`interfaces->engine->GetLevelName()` contains full map name 
```
if(!interfaces->engine->isInGame() || !interfaces->engine->isConnected())
   return;

if(std::strstr(interfaces->engine->GetLevelName(), "surf") != NULL)
{
   localPlayer on surf
}
```

**Comment by pixelsurf123** [comment]
> `interfaces->engine->GetLevelName()` contains full map name
> 
> ```
> if(!interfaces->engine->isInGame() || !interfaces->engine->isConnected())
>    return;
> 
> if(std::strstr(interfaces->engine->GetLevelName(), "surf") != NULL)
> {
>    localPlayer on surf
> }
> ```

No i mean when localplayer flag on surf

**Comment by mkot2** [comment]
> 
> 
> > `interfaces->engine->GetLevelName()` contains full map name
> > ```
> > if(!interfaces->engine->isInGame() || !interfaces->engine->isConnected())
> >    return;
> > 
> > if(std::strstr(interfaces->engine->GetLevelName(), "surf") != NULL)
> > {
> >    localPlayer on surf
> > }
> > ```
> 
> No i mean when localplayer flag on surf

there's no such flag
