### ISSUE TITLE
Watermark png

### ISSUE THREAD

**Issue by idkplayer** [danielkrupinski/Osiris#269]
Hi, how to add png file to watermark?

**Comment by effex1337** [comment]
I don't think anyone would support that changing stuff in a watermark.

**Comment by tirziz** [comment]
ya that do nothing

**Comment by idkplayer** [comment]
I'm a graphic artist and I could do it for Osiris and I think it would be a nice thing that osiris stood out from

**Comment by effex1337** [comment]
-1

**Comment by idkplayer** [comment]
it means bad to say, I mean how to upload png to watermark and whether wogule can and by the way I could do it for osiris

**Comment by effex1337** [comment]
Well @danielkrupinski didn't even wanna put the build info like whose cheat is this and stuff.
So no fancy stuff. Further mote we wouldn't help accomplish a leecher's goal.
