### ISSUE TITLE
Custom sound effects are very delaid..

### ISSUE THREAD

**Issue by osirisbestlegitcheat** [danielkrupinski/Osiris#2693]
I used custom killsounds but whenever i kill someone it does not play the sound at the right time.

**Comment by Bakedpurple** [comment]
What format to the custom sounds have to be in? And what directory?

**Comment by osirisbestlegitcheat** [comment]
> What format do the custom sounds have to be in? And what directory?

csgo/sound .mp3

**Comment by osirisbestlegitcheat** [comment]
my bad, i editied the files on audiocity and the files were delaied lol
