### ISSUE TITLE
how i can do tab better

### ISSUE THREAD

**Issue by pixelsurf123** [danielkrupinski/Osiris#2694]
how i can do tab legitbot and under this tab have aimbot backtrack triggerbot 
![image](https://user-images.githubusercontent.com/57488947/111027355-cf6fa900-8400-11eb-8a64-3368870fd14d.png)

**Comment by caiocinel** [comment]
I could see that you have no idea what you're trying to do, I recommend:
https://www.learncpp.com/

and after some time:
https://github.com/ocornut/imgui/

**Comment by mkot2** [comment]
https://github.com/notgoodusename/osiriswithstuff/blob/master/Osiris/GUI.cpp

Also this is not a pasting help forum, please close all of the "issues" you posted
