### ISSUE TITLE
how i can add health esp

### ISSUE THREAD

**Issue by pixelsurf123** [danielkrupinski/Osiris#2695]
how i can add health in text

**Comment by caiocinel** [comment]
https://github.com/danielkrupinski/Osiris/blob/775bab9f55c81654657f28ec290d1905001a4577/Osiris/Hacks/StreamProofESP.cpp#L284

**Comment by pixelsurf123** [comment]
> https://github.com/danielkrupinski/Osiris/blob/775bab9f55c81654657f28ec290d1905001a4577/Osiris/Hacks/StreamProofESP.cpp#L284

I mean in text
