### ISSUE TITLE
how i can hook

### ISSUE THREAD

**Issue by pixelsurf123** [danielkrupinski/Osiris#2697]
how i can hook func with
 interfaces->surface->printText

**Comment by ny-4** [comment]
Why would you want to hook that ??

**Comment by caiocinel** [comment]
https://github.com/danielkrupinski/Osiris/blob/775bab9f55c81654657f28ec290d1905001a4577/Osiris/Hooks.cpp#L617

**Comment by pixelsurf123** [comment]
I mean where this in new osiris 

{
static void __stdcall paintTraverse(unsigned int panel, bool forceRepaint, bool allowForce) noexcept
{

    if (interfaces->panel->getName(panel) == "MatSystemTopPanel") {
        Misc::KeyStorkes();
        Misc::edgebugindndicators();
        Misc::jumpbugindndicators();
    }
    hooks->panel.callOriginal<void, 41>(panel, forceRepaint, allowForce);
}
}

**Comment by mkot2** [comment]
> 
> 
> I mean where this in new osiris
> 
> {
> static void __stdcall paintTraverse(unsigned int panel, bool forceRepaint, bool allowForce) noexcept
> {
> 
> ```
> if (interfaces->panel->getName(panel) == "MatSystemTopPanel") {
>     Misc::KeyStorkes();
>     Misc::edgebugindndicators();
>     Misc::jumpbugindndicators();
> }
> hooks->panel.callOriginal<void, 41>(panel, forceRepaint, allowForce);
> ```
> 
> }
> }

https://github.com/danielkrupinski/Osiris/commit/9fa2c4504994cfdb1db33a791eb7bbfb10d28d52
