### ISSUE TITLE
how i can add colorpicker

### ISSUE THREAD

**Issue by pixelsurf123** [danielkrupinski/Osiris#2698]
how i can add colorpicker on this Style->Colors[ImGuiCol_WindowBg] = ImColor(55, 39, 92);

**Comment by caiocinel** [comment]
Use ImGui Style Editor as inspiration

https://github.com/ocornut/imgui/blob/287bd9b98488d5f7bc0f730904af7f0c842971eb/imgui_demo.cpp#L5977
