### ISSUE TITLE
can't inject osiris.dll with any injector

### ISSUE THREAD

**Issue by kernelpanic32** [danielkrupinski/Osiris#2699]
i can't seem to inject the osiris.dll with any injector. i've tried GH Injector, Xenos64 (gives an error "Failed to inject image, error code 0xC0000135"), extreme injector, process hacker 2, but no one works, i press INSERT ingame and menu doesn't pop up. Visual studio doesn't give any errors compiling the solution, so i don't have any idea what could be

**Comment by osirisbigfan** [comment]
use a loadlibrary injector, such as SazInjector

**Comment by MirzaGorgAli** [comment]
> 
> 
> i can't seem to inject the osiris.dll with any injector. i've tried GH Injector, Xenos64 (gives an error "Failed to inject image, error code 0xC0000135"), extreme injector, process hacker 2, but no one works, i press INSERT ingame and menu doesn't pop up. Visual studio doesn't give any errors compiling the solution, so i don't have any idea what could be

Compile this: [MemJect](https://github.com/danielkrupinski/MemJect)
1: Compile Osiris and use HxD to get binary (go to "Edit" then copy as "C")
2: In the [MemJect](https://github.com/danielkrupinski/MemJect) put your binary instead of this line [uint8_t binary[] =](https://github.com/danielkrupinski/MemJect/blob/master/MemJect/MemJect.c#L20) 
3: Have fun(It is UNDETECTED)

**SORRY ABOUT MY ENGLISH**

**Comment by kernelpanic32** [comment]
> 
> 
> > i can't seem to inject the osiris.dll with any injector. i've tried GH Injector, Xenos64 (gives an error "Failed to inject image, error code 0xC0000135"), extreme injector, process hacker 2, but no one works, i press INSERT ingame and menu doesn't pop up. Visual studio doesn't give any errors compiling the solution, so i don't have any idea what could be
> 
> Compile this: [MemJect](https://github.com/danielkrupinski/MemJect)
> 1: Compile Osiris and use HxD to get binary (go to "Edit" then copy as "C")
> 2: In the [MemJect](https://github.com/danielkrupinski/MemJect) put your binary instead of this line [uint8_t binary[] =](https://github.com/danielkrupinski/MemJect/blob/master/MemJect/MemJect.c#L20)
> 3: Have fun(It is UNDETECTED)
> 
> **SORRY ABOUT MY ENGLISH**

ty man that worked

**Comment by kernelpanic32** [comment]
> 
> 
> > i can't seem to inject the osiris.dll with any injector. i've tried GH Injector, Xenos64 (gives an error "Failed to inject image, error code 0xC0000135"), extreme injector, process hacker 2, but no one works, i press INSERT ingame and menu doesn't pop up. Visual studio doesn't give any errors compiling the solution, so i don't have any idea what could be
> 
> Compile this: [MemJect](https://github.com/danielkrupinski/MemJect)
> 1: Compile Osiris and use HxD to get binary (go to "Edit" then copy as "C")
> 2: In the [MemJect](https://github.com/danielkrupinski/MemJect) put your binary instead of this line [uint8_t binary[] =](https://github.com/danielkrupinski/MemJect/blob/master/MemJect/MemJect.c#L20)
> 3: Have fun(It is UNDETECTED)
> 
> **SORRY ABOUT MY ENGLISH**

ty man that worked

**Comment by kernelpanic32** [comment]
> 
> 
> > i can't seem to inject the osiris.dll with any injector. i've tried GH Injector, Xenos64 (gives an error "Failed to inject image, error code 0xC0000135"), extreme injector, process hacker 2, but no one works, i press INSERT ingame and menu doesn't pop up. Visual studio doesn't give any errors compiling the solution, so i don't have any idea what could be
> 
> Compile this: [MemJect](https://github.com/danielkrupinski/MemJect)
> 1: Compile Osiris and use HxD to get binary (go to "Edit" then copy as "C")
> 2: In the [MemJect](https://github.com/danielkrupinski/MemJect) put your binary instead of this line [uint8_t binary[] =](https://github.com/danielkrupinski/MemJect/blob/master/MemJect/MemJect.c#L20)
> 3: Have fun(It is UNDETECTED)
> 
> **SORRY ABOUT MY ENGLISH**

ty man that worked
