### ISSUE TITLE
Crash cheat

### ISSUE THREAD

**Issue by antosha22rus** [danielkrupinski/Osiris#27]
Hi Daniel, after the launch of the second card in MM, the osiris began to crash, by debugging I found out that it crashes setMaterialVarFlag
![image](https://user-images.githubusercontent.com/37859984/50689082-464ad380-1039-11e9-9e7a-d97fc442b7b2.png)

**Comment by danielkrupinski** [comment]
Please verify game files https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335

**Comment by antosha22rus** [comment]
did not help, crash

**Comment by danielkrupinski** [comment]
Should now be fixed. Thanks for you report!

**Comment by antosha22rus** [comment]
Thanks for the correction!
Good luck in the development of the project.
