### ISSUE TITLE
Make chams and glow obs proof

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#2700]
![image](https://user-images.githubusercontent.com/72364877/111058076-ed9fdc80-84c6-11eb-8f06-e77ed582d20e.png)

**Comment by blackMasterLord** [comment]
I don't know why, but it seems to me that this is impossible.

**Comment by osirisbigfan** [comment]
> I don't know why, but it seems to me that this is impossible.
OBS Proof Chams is possible, glow i don't think so
Example of OBS Proof Chams: https://www.youtube.com/watch?v=sv1J5Py4Odk

**Comment by wemanzoz** [comment]
make this happen

**Comment by wemanzoz** [comment]
> > I don't know why, but it seems to me that this is impossible.
> 
> OBS Proof Chams is possible, glow i don't think so
> Example of OBS Proof Chams: https://www.youtube.com/watch?v=sv1J5Py4Odk

ooof, then chams only is enough. hope daniel isn't lazy to implement this :D

**Comment by debooga** [comment]
its possible, but why? just use esp only

**Comment by caiocinel** [comment]
Glow / Chams would have to be done by an overlay, in the same way as the menu, and this in the current way is not possible since it uses functions from the game itself, it is not a drawing in itself.
