### ISSUE TITLE
how i can track local player

### ISSUE THREAD

**Issue by pixelsurf123** [danielkrupinski/Osiris#2705]
how i can track local player when he in air which flag

**Comment by dapaster** [comment]
**IN AIR**  
  (!(localPlayer->flags() & 1))

**GROUND**
    (localPlayer->flags() & 1)

**Comment by pixelsurf123** [comment]
> **IN AIR**
> (!(localPlayer->flags() & 1))
> 
> **GROUND**
> (localPlayer->flags() & 1)

thx

**Comment by caiocinel** [comment]
> > **IN AIR**
> > (!(localPlayer->flags() & 1))
> > **GROUND**
> > (localPlayer->flags() & 1)
> 
> thx

pls close issue

**Comment by mkot2** [comment]
can you stop opening so many retarded "issues"?
