### ISSUE TITLE
more movement functions

### ISSUE THREAD

**Issue by Zvondaaa** [danielkrupinski/Osiris#2707]
I think it could be useful but who knows

**Comment by mkot2** [comment]
what sort of movement features

**Comment by wemanzoz** [comment]
paste it

**Comment by wemanzoz** [comment]
> paste it

there are sources in xtremecheats

**Comment by ko0lino** [comment]
:ddd

**Comment by Zvondaaa** [comment]
I pasted some movement features , im closing this issue
