### ISSUE TITLE
[SUGGEST] Wall transparency and Prop transparency

### ISSUE THREAD

**Issue by mliiyyyyy** [danielkrupinski/Osiris#2715]
sometime Prop transparency is useful in 'hide and seek'

**Comment by KurastikO** [comment]
why do you want to cheat at hide and seek

**Comment by wemanzoz** [comment]
> sometime Prop transparency is useful in 'hide and seek'

just use walls :v

**Comment by linuxer9** [comment]
easy pasta 
https://github.com/notgoodusename/osiriswithstuff/blob/13f04fe8d41395c35ab5d990ee574e50186ecb41/Osiris/Hacks/Visuals.cpp#L128
but come on kid don't cheat in  hide and seek, it's fun with friends

**Comment by debooga** [comment]
> easy pasta
> https://github.com/notgoodusename/osiriswithstuff/blob/13f04fe8d41395c35ab5d990ee574e50186ecb41/Osiris/Hacks/Visuals.cpp#L128
> but come on kid don't cheat in hide and seek, it's fun with friends

hey! i coded that garbage!
