### ISSUE TITLE
[SUGGEST] Auto Pistol Delay

### ISSUE THREAD

**Issue by BakedDot** [danielkrupinski/Osiris#2719]
Useful feature for pistol accuracy when used with Aimbot and Autostop for 100% accuracy.

**Comment by wemanzoz** [comment]
+rep, now pray that daniel will see this and say ye. also, pls add triggerbot hitchance

**Comment by KisSsArt** [comment]
no one has updated aimbot for a long time in this cheat xd

**Comment by king1919djdj** [comment]
because it works fine without updates XD

**Comment by KisSsArt** [comment]
auto scope bug?
