### ISSUE TITLE
Game crash 

### ISSUE THREAD

**Issue by FlameProfi** [danielkrupinski/Osiris#2720]
When i injected dll, game crashed. What could be the reason for this?

**Comment by FlameProfi** [comment]
40F6554F  mov         al,byte ptr [eax] 
Error in this line

**Comment by FlameProfi** [comment]
1>Previous IPDB not found, fall back to full compilation.
1>All 9718 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.

**Comment by FlameProfi** [comment]
Поток 0x1e20 завершился с кодом 1035141120 (0x3db30000).

**Comment by blackMasterLord** [comment]
1. Запускаешь CS
2. Подключаешь отладчик VS
3. Инжектишь чит
4. Смотришь где проблемы

**Comment by wemanzoz** [comment]
outdated dll?

**Comment by FlameProfi** [comment]
> 1. Запускаешь CS
> 2. Подключаешь отладчик VS
> 3. Инжектишь чит
> 4. Смотришь где проблемы

я сделал, было написано что можно глянуть в асемблере

**Comment by muahaha00** [comment]
Excuse me, with the source code of osiris and the offset of the latest game, can you update osiris through the software VS (want to learn)

**Comment by muahaha00** [comment]
Excuse me, with the source code of osiris and the offset of the latest game, can you update osiris through the software VS (want to learn)

**Comment by muahaha00** [comment]
The machine translation is not very accurate. I'm sorry.

**Comment by blackMasterLord** [comment]
> > 1. Запускаешь CS
> > 2. Подключаешь отладчик VS
> > 3. Инжектишь чит
> > 4. Смотришь где проблемы
> 
> я сделал, было написано что можно глянуть в асемблере

что за инжектор юзаешь?

**Comment by FlameProfi** [comment]
> > > 1. Запускаешь CS
> > > 2. Подключаешь отладчик VS
> > > 3. Инжектишь чит
> > > 4. Смотришь где проблемы
> > 
> > 
> > я сделал, было написано что можно глянуть в асемблере
> 
> что за инжектор юзаешь?

Через процес хакер пробовал и еще хуйню какую то

**Comment by blackMasterLord** [comment]
> > > > 1. Запускаешь CS
> > > > 2. Подключаешь отладчик VS
> > > > 3. Инжектишь чит
> > > > 4. Смотришь где проблемы
> > > 
> > > 
> > > я сделал, было написано что можно глянуть в асемблере
> > 
> > 
> > что за инжектор юзаешь?
> 
> Через процес хакер пробовал и еще extreme inejctor

попробуй [CHEATERFUN](https://cheater.run/injectors/751-download-injector-for-csgo-cheaterfun-injector-dll-files.html)
уже год с ним играю, всё нормально

**Comment by FlameProfi** [comment]
> > > > > 1. Запускаешь CS
> > > > > 2. Подключаешь отладчик VS
> > > > > 3. Инжектишь чит
> > > > > 4. Смотришь где проблемы
> > > > 
> > > > 
> > > > я сделал, было написано что можно глянуть в асемблере
> > > 
> > > 
> > > что за инжектор юзаешь?
> > 
> > 
> > Через процес хакер пробовал и еще extreme inejctor
> 
> попробуй [CHEATERFUN](https://cheater.run/injectors/751-download-injector-for-csgo-cheaterfun-injector-dll-files.html)
> уже год с ним играю, всё нормально

брат, а у тебя в скинченджере все скины?
