### ISSUE TITLE
Excuse me, how can I update osiris by myself?

### ISSUE THREAD

**Issue by muahaha00** [danielkrupinski/Osiris#2721]
The machine translation is not very accurate. I'm sorry. 
I would like to ask, is the update of osiris achieved by changing the game offset by VS? If so, how do you operate it? Or is there any course to help me with my study? thank you.

**Comment by wemanzoz** [comment]
> The machine translation is not very accurate. I'm sorry.
> I would like to ask, is the update of osiris achieved by changing the game offset by VS? If so, how do you operate it? Or is there any course to help me with my study? thank you.

Daniel will update it once theres a game update that will result crash, you can just open commit tab and click the commit or just download newest source
