### ISSUE TITLE
watermark edit

### ISSUE THREAD

**Issue by shakeit1337** [danielkrupinski/Osiris#2722]
PlayerInfo playerInfo;
const auto nickname = 1.0f;
nickname = 1.0f * interfaces->engine->getPlayerInfo(localPlayer->index(), playerInfo);

std::string name{ std::to_string(static_cast<int>(1 / nickname)) + " Name" };

what is wrong on this code ?

its for see my name in watermark.

**Comment by blackMasterLord** [comment]
1. learn c++
2. wtf is that "const auto nickname = 1.0f;"?
3. "localPlayer->index()" only works if u connected in game

**Comment by cyanewfag** [comment]
https://www.learncpp.com/

**Comment by blackMasterLord** [comment]
when you finish learning c++, look [here](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/public/steam/isteamfriends.h#L163)

**Comment by mkot2** [comment]
ah yes modifying const var

**Comment by debooga** [comment]
is this a troll post?
