### ISSUE TITLE
[ISSUE] Third Person Not Centered

### ISSUE THREAD

**Issue by NKPublic** [danielkrupinski/Osiris#2725]
When using third person, it is off centered with the play model. The camera is pointed at the local player but is rotated to be looking at the side of the local player. This results in the crosshair being shown in third person not being where the actual crosshair is.
I tried doing this with and without my configs, rebuilding the dll, etc. and the issue persists.

**Comment by morganwall** [comment]
It is, you're delusional.

**Comment by mkot2** [comment]
> 
> 
> It is, you're delusional.

damn

**Comment by NKPublic** [comment]
2 images shown are shown with no config. One shows just thirdperson enabled, the other shows thirdperson + distance. The camera is very clearly shown to the right of the player, rather than being dead on with the player.

![Counter-strike  Global Offensive Screenshot 2021 03 24 - 14 26 19 34](https://user-images.githubusercontent.com/73808018/112371820-0c635780-8cad-11eb-95ac-67d802d2a31f.png)
![Counter-strike  Global Offensive Screenshot 2021 03 24 - 14 26 27 41](https://user-images.githubusercontent.com/73808018/112371824-0e2d1b00-8cad-11eb-9ee2-0f3972ff519b.png)

**Comment by morganwall** [comment]
That is still centered. Try loading up csgo without anything injected and use the thirdperson command. I'm guessing that the reason the model isn't directly centered is due to them not standing entirely straight, especially when you're turned. This isn't an issue in the first place, and even if you classed it as one, it's not an issue with the cheat, hence opening an issue about it makes no sense.

**Comment by NKPublic** [comment]
I see what you mean. My apologies, it seems I had messed with mayamode third person without realizing. I was not aware the cheat relied on the player settings for thirdperson, and was issue with my settings rather than the cheat. My thinking was that there was yaw or pitch value that the cheat was using. Again, my apologies, and thanks for the help.
