### ISSUE TITLE
[QUESTION] So I know how to apply a pull requests and compile them, but there are some old Osiris pull requests that I want to try out. How do I apply/fix some old pull requests?

### ISSUE THREAD

**Issue by YeetingWaterbottle** [danielkrupinski/Osiris#2726]

**Comment by wemanzoz** [comment]
config.cpp, if the pull request has old config.cpp style, adapt the code to the new one (write, read), remember to do config.h. but, if its so old that it causes shit tons of errors, maybe you need to do some basic pasting (read the code, and ask people on uc, learn cpp)

**Comment by YeetingWaterbottle** [comment]
> config.cpp, if the pull request has old config.cpp style, adapt the code to the new one (write, read), remember to do config.h. but, if its so old that it causes shit tons of errors, maybe you need to do some basic pasting (read the code, and ask people on uc, learn cpp)

Thanks, I were trying to make the bomb damage to work, but there were 2 errors. It was like "c4Ticking" and "getLocalePlayer" or something. It is an error from "hacks/misc.cpp", not on the config.cpp

I _think_ I modified it to the latest version's "format"

**Comment by mkot2** [comment]
most of them just require you to change the config read/save stuff

**Comment by YeetingWaterbottle** [comment]
> most of them just require you to change the config read/save stuff

Ok thanks
