### ISSUE TITLE
why func dont predict

### ISSUE THREAD

**Issue by pixelsurf123** [danielkrupinski/Osiris#2727]
if (GetAsyncKeyState(config->misc.edgebugkey) && (localPlayer->flags() & 1) && !(EnginePrediction::getFlags() & 1)) 
    {
        std::string cmd = "+duck";
        interfaces->engine->clientCmdUnrestricted(cmd.c_str());
    }

**Comment by wemanzoz** [comment]
maybe engine prediction issue? send me the source of the code you're pasting on btw

**Comment by mkot2** [comment]
b1g jumpbug pasta

**Comment by blackMasterLord** [comment]
> if (GetAsyncKeyState(config->misc.edgebugkey) && (localPlayer->flags() & 1) && !(EnginePrediction::getFlags() & 1))
> {
> std::string cmd = "+duck";
> interfaces->engine->clientCmdUnrestricted(cmd.c_str());
> }

dude, I'll say it again
1. learn c++
2. if u need something - go to [UC](https://www.unknowncheats.me/forum/counterstrike-global-offensive/)

and **STOP** creating stupid issues with stupid code

**Comment by pixelsurf123** [comment]
> b1g jumpbug pasta

No if i use usercmd edgebug have sound it test
