### ISSUE TITLE
How i can do local message in chat

### ISSUE THREAD

**Issue by pixelsurf123** [danielkrupinski/Osiris#2728]
How i can do local message in chat like
Osiris| Hitted
i mean only i can see this message

**Comment by linuxer9** [comment]
ez pasta
https://www.unknowncheats.me/forum/counterstrike-global-offensive/171375-printing-text-chat.html

**Comment by mkot2** [comment]
> 
> 
> ez pasta
> https://www.unknowncheats.me/forum/counterstrike-global-offensive/171375-printing-text-chat.html

how to use lmao

**Comment by blackMasterLord** [comment]
this works mb
```
class CHudChat
{
public:
    void ChatPrintf(int iPlayerIndex, int iFilter, const char* fmt, ...)
    {
        VirtualMethod::call<void(__cdecl*)(void*, int, int, const char*, ...), 26>(this, iPlayerIndex, iFilter, fmt);
    }
};
```
```
if (auto hud_element = (CHudChat*)memory->findHudElement(memory->hud, "CHudChat")) {
            hud_element->ChatPrintf(0, 0, "format %s %i", "test" 10);
}
```

**Comment by pixelsurf123** [comment]
> this works mb
> 
> ```
> class CHudChat
> {
> public:
>     void ChatPrintf(int iPlayerIndex, int iFilter, const char* fmt, ...)
>     {
>         VirtualMethod::call<void(__cdecl*)(void*, int, int, const char*, ...), 26>(this, iPlayerIndex, iFilter, fmt);
>     }
> };
> ```
> 
> ```
> if (auto hud_element = (CHudChat*)memory->findHudElement(memory->hud, "CHudChat")) {
>             hud_element->ChatPrintf(0, 0, "format %s %i", "test" 10);
> }
> ```

dont work :(

**Comment by blackMasterLord** [comment]
86dd5ea865e8b29b5942caebe9991253f736617f

> > this works mb
> > ```
> > class CHudChat
> > {
> > public:
> >     void ChatPrintf(int iPlayerIndex, int iFilter, const char* fmt, ...)
> >     {
> >         VirtualMethod::call<void(__cdecl*)(void*, int, int, const char*, ...), 26>(this, iPlayerIndex, iFilter, fmt);
> >     }
> > };
> > ```
> > 
> > 
> > ```
> > if (auto hud_element = (CHudChat*)memory->findHudElement(memory->hud, "CHudChat")) {
> >             hud_element->ChatPrintf(0, 0, "format %s %i", "test" 10);
> > }
> > ```
> 
> dont work :(
