### ISSUE TITLE
Does Reveal Suspect Ever Work?

### ISSUE THREAD

**Issue by ishaangamer27** [danielkrupinski/Osiris#2733]
I'm using my 27IQ that's it when you are in any sort of game mode that supports Overwatch Osiris will let you know when you are the Suspect but so Far I haven't seen it in action am I doing something wrong I know I'm bound to get an OW ban

**Comment by KernCS** [comment]
Reveal Suspect reveals who you are watching when you are doing overwatch cases

**Comment by hydemods** [comment]
Lolz that's not how that works. When you do an overwatch case it basically makes it a normal demo, you can click on the player profiles and see medals, level, etc. + you can see the steam profile.

**Comment by debooga** [comment]
lmao

**Comment by linuxer9** [comment]
you should check your email, it should send you an email telling you that you have been a suspect in OW case.
_joke_

**Comment by HowToMakeFaceitAB** [comment]
damn people are retarded

**Comment by debooga** [comment]
> you should check your email, it should send you an email telling you that you have been a suspect in OW case.
> _joke_

make sure your email is on yandex.ru
