### ISSUE TITLE
[SUGGESTION] Add Rank And Inventory Changer

### ISSUE THREAD

**Issue by xylias** [danielkrupinski/Osiris#2734]
If you have time and motivation please add rank and inventory changer

**Comment by KernCS** [comment]
Not like there is are shit ton suggestions about it already 
https://github.com/danielkrupinski/Osiris/issues/1379
https://github.com/danielkrupinski/Osiris/issues/1516
https://github.com/danielkrupinski/Osiris/issues/1590
https://github.com/danielkrupinski/Osiris/issues/2192
https://github.com/danielkrupinski/Osiris/issues/2293
https://github.com/danielkrupinski/Osiris/issues/2463
https://github.com/danielkrupinski/Osiris/issues/2572

**Comment by KurastikO** [comment]
Oh god, please just shut the fuck up about this... There are already so many pull requests that you can use.

**Comment by KurastikO** [comment]
Close the issue please, and if you have any more bad ideas just post it in Discussions.

**Comment by blackMasterLord** [comment]
Changing the inventory requires a lot of work, because the source codes that are publicly available are only 50% ready.

**Comment by linuxer9** [comment]
ez pasta
https://github.com/B3akers/csgo-fake-opening
this software contains the code of fully functional inventory changer, the only thing is missing is the skin changer part, but it's easy just get the item id from inventory and apply it to the current weapon

**Comment by linuxer9** [comment]
there is a profile changer PR https://github.com/danielkrupinski/Osiris/pull/2503

**Comment by blackMasterLord** [comment]
> ez pasta
> https://github.com/B3akers/csgo-fake-opening
> this software contains the code of fully functional inventory changer, the only thing is missing is the skin changer part, but it's easy just get the item id from inventory and apply it to the current weapon

how will you equip the weapon?



> there is a profile changer PR #2503

what about DUO and DZ ranks?

**Comment by linuxer9** [comment]
> 
> 
> > ez pasta
> > https://github.com/B3akers/csgo-fake-opening
> > this software contains the code of fully functional inventory changer, the only thing is missing is the skin changer part, but it's easy just get the item id from inventory and apply it to the current weapon
> 
> how will you equip the weapon?
> 

https://www.unknowncheats.me/forum/counterstrike-global-offensive/276335-inventory-changer-game.html
as I said you grab the equipped item from loadout and get its ID and change the current weapon ID to that ID. it's easy and beakers' fake openings code contains the code for that.

> > there is a profile changer PR #2503
> 
> what about DUO and DZ ranks?

It's possible, I remember there was a solution for that, I will find it and tell you.
