### ISSUE TITLE
ask Detect 

### ISSUE THREAD

**Issue by pixelsurf123** [danielkrupinski/Osiris#2742]
vmtswap detect?
and which hook better

**Comment by wemanzoz** [comment]
Minhook, although maybe, vmtswap detected, my sv_pure bypass uses it and i haven't get a single ban. better safe then sorry though

**Comment by linuxer9** [comment]
what is the point? you are bypassing vac anyway (or you should)
> 
> 
> Minhook, although maybe, vmtswap detected, my sv_pure bypass uses it and i haven't get a single ban. better safe then sorry though

you can use minhook for that, I think.
