### ISSUE TITLE
Hack detect

### ISSUE THREAD

**Issue by Fragrus** [danielkrupinski/Osiris#2744]
Don't use. Detect. -5 accounts

**Comment by xylias** [comment]
Yes ITS open source you have to protect it yourself

**Comment by linuxer9** [comment]
yo
any public software is already detected, so you should bypass vac.
I have been using my build of osiris for 6 months now with vac bypass still no bans

**Comment by osirisbestlegitcheat** [comment]
> yo
> any public software is already detected, so you should bypass vac.
> I have been using my build of osiris for 6 months now with vac bypass still no bans

Just use a vac bypasser no need to build Osiris again.

**Comment by osirisbestlegitcheat** [comment]
worked for me never vac banned. i got vac banned when I forgot to use it

**Comment by misterbister8123** [comment]
> worked for me never vac banned. i got vac banned when I forgot to use it

what vac bypass u use?

**Comment by heqmat** [comment]
i guess he means vac bypass loader. Actually yeah, vac is garbage that's why if you know this topics a bit. Probably it's gonna be not problem for you.

**Comment by ArtemSokolovskiy** [comment]
LoL? Dll is undetect, detected only loader

**Comment by popoyeLetal** [comment]
> yo
> any public software is already detected, so you should bypass vac.
> I have been using my build of osiris for 6 months now with vac bypass still no bans

Got questions about this sir

**Comment by linuxer9** [comment]
> 
> 
> > yo
> > any public software is already detected, so you should bypass vac.
> > I have been using my build of osiris for 6 months now with vac bypass still no bans
> 
> Got questions about this sir

what?
