### ISSUE TITLE
How to avoid VAC ban

### ISSUE THREAD

**Issue by ImChinaNB** [danielkrupinski/Osiris#2745]
I'm currently using osiris with Process Hacker 2 (and VAC Bypass Loader),
I have only modified the font part of the source code. (which means its MinHook)
Would I get a VAC ban?

**Comment by linuxer9** [comment]
I have been using this vac bypass (https://github.com/zyhp/vac3_inhibitor) for 6 months now
and I used multiple injectors (Process hacker, memject, shtreeba..)
with multiple dlls (some of them are cracked P2C and detected)
still no bans
the only thing you should worry about is Vacnet (if you raging) and OW (if you obvious cheating)
other than that bypassing VAC is a joke

**Comment by osirisbestlegitcheat** [comment]
> I have been using this vac bypass (https://github.com/zyhp/vac3_inhibitor) for 6 months now
> and I used multiple injectors (Process hacker, memject, shtreeba..)
> with multiple dlls (some of them are cracked P2C and detected)
> still no bans
> the only 2 things you should worry about are Vacnet (if you raging) and OW (if you obvious cheating)
> other than that bypassing VAC is a joke

SEE TOLD YOU VAC BYPASS DOES THE JOB!

**Comment by blxckshark** [comment]
> I have been using this vac bypass (https://github.com/zyhp/vac3_inhibitor) for 6 months now
> and I used multiple injectors (Process hacker, memject, shtreeba..)
> with multiple dlls (some of them are cracked P2C and detected)
> still no bans
> the only 2 things you should worry about are Vacnet (if you raging) and OW (if you obvious cheating)
> other than that bypassing VAC is a joke

weird, cause this vac bypass is outdated.

**Comment by SevenEight123** [comment]
> I have been using this vac bypass (https://github.com/zyhp/vac3_inhibitor) for 6 months now
> and I used multiple injectors (Process hacker, memject, shtreeba..)
> with multiple dlls (some of them are cracked P2C and detected)
> still no bans
> the only 2 things you should worry about are Vacnet (if you raging) and OW (if you obvious cheating)
> other than that bypassing VAC is a joke

When did you actually use this bypass the last time?

**Comment by linuxer9** [comment]
> 
> 
> > I have been using this vac bypass (https://github.com/zyhp/vac3_inhibitor) for 6 months now
> > and I used multiple injectors (Process hacker, memject, shtreeba..)
> > with multiple dlls (some of them are cracked P2C and detected)
> > still no bans
> > the only 2 things you should worry about are Vacnet (if you raging) and OW (if you obvious cheating)
> > other than that bypassing VAC is a joke
> 
> When did you actually use this bypass the last time?

today.

**Comment by SevenEight123** [comment]
That's interesting. I also tried it, but I didn't see any output or response in the Steam console. Should it actually be like this? By the way I used it a few times for a week on 2nd account, no ban there. But the fact that isn't saying anything like ''successful" is weird.

**Comment by linuxer9** [comment]
> 
> 
> That's interesting. I also tried it, but I didn't see any output or response in the Steam console. Should it actually be like this? By the way I used it a few times for a week on 2nd account, no ban there. But the fact that isn't saying anything like ''successful" is weird.

it should output something like this 
```
[ VAC3 ] nulled _runfunc ***
[ VAC3 ] patched ret from uid ***
```
it shouldn't say "successful". also to be extra sure it's working try using it on a throw away account and run cheat engine or a detected injector etc.. if it's not working, you should get banned within a few hours.

**Comment by blxckshark** [comment]
> > That's interesting. I also tried it, but I didn't see any output or response in the Steam console. Should it actually be like this? By the way I used it a few times for a week on 2nd account, no ban there. But the fact that isn't saying anything like ''successful" is weird.
> 
> it should output something like this
> 
> ```
> [ VAC3 ] nulled _runfunc ***
> [ VAC3 ] patched ret from uid ***
> ```
> 
> it shouldn't say "successful". also to be extra sure it's working try using it on a throw away account and run cheat engine or a detected injector etc.. if it's not working, you should get banned within a few hours.

works?

**Comment by SevenEight123** [comment]
Used it for a week and a half, works so far.

**Comment by linuxer9** [comment]
> 
> 
> > > That's interesting. I also tried it, but I didn't see any output or response in the Steam console. Should it actually be like this? By the way I used it a few times for a week on 2nd account, no ban there. But the fact that isn't saying anything like ''successful" is weird.
> > 
> > 
> > it should output something like this
> > ```
> > [ VAC3 ] nulled _runfunc ***
> > [ VAC3 ] patched ret from uid ***
> > ```
> > 
> > 
> > it shouldn't say "successful". also to be extra sure it's working try using it on a throw away account and run cheat engine or a detected injector etc.. if it's not working, you should get banned within a few hours.
> 
> works?

yes, it's been 6 months now, now bans, although I rage few times a week,
BTW, there is a pull request which adds more modules

**Comment by linuxer9** [comment]
ok, I was dumb, this vac3 inhibitor was working perfectly all the time, I looked at the code and from what I understand it replaces the begining function of all modules with nullptr, no matter if it's known or unknown,
this message:
`[ VAC3 ] unknown module loaded.`
its purpose is to let you know that vac now has a new module, but the software already dealt with it, like a known module.
in fact, yesterday zyhp has just removed this feature entirely.
@blxckshark
