### ISSUE TITLE
why i have wrong

### ISSUE THREAD

**Issue by pixelsurf123** [danielkrupinski/Osiris#2746]
![image](https://user-images.githubusercontent.com/57488947/112748109-653f3280-8fc2-11eb-9172-3f45dff9a790.png)
who know ho i can fix this

**Comment by wemanzoz** [comment]
what does the error say

**Comment by mkot2** [comment]
what is this supposed to do and what is the error

**Comment by pixelsurf123** [comment]
int dont work with const char \\ sorry for bad eng

**Comment by mkot2** [comment]
> 
> 
> int dont work with const char \ sorry for bad eng

that problem is trivial to fix, did you google it?

**Comment by pixelsurf123** [comment]
> > int dont work with const char \ sorry for bad eng
> 
> that problem is trivial to fix, did you google it?

I try to fix but i dont know how i can do this

**Comment by mkot2** [comment]
> 
> 
> > > int dont work with const char \ sorry for bad eng
> > 
> > 
> > that problem is trivial to fix, did you google it?
> 
> I try to fix but i dont know how i can do this

https://cboard.cprogramming.com/c-programming/131512-convert-int-const-char-*.html
https://kodlogs.com/blog/688/how-to-convert-int-to-char-c
https://www.cplusplus.com/forum/general/154370/

**Comment by mkot2** [comment]
close pls
