### ISSUE TITLE
How to play csgo on the gaming platform after cleaning osiris

### ISSUE THREAD

**Issue by muahaha00** [danielkrupinski/Osiris#2747]
Hello, I used osiris to play the official csgo game before, and now I want to play games on the game platform, is it safe to just delete files and clean up the registry?

**Comment by mkot2** [comment]
what?

**Comment by muahaha00** [comment]
> 什么？

Sorry, machine translation is not very accurate.
I want to play csgo, on the game platform because the game platform scans the hard drive, just like Faceit. I used osiris, before to ask how to clean the computer, delete the files, clean the registry, will the computer be safe? thank you.

**Comment by mina9999** [comment]
when u unhook or restart csgo u are safe.

**Comment by muahaha00** [comment]
> 当您解开或重启csgo时，您是安全的。

No, the platform will scan the hard drive, and the residual files of the plug-in will be scanned to

**Comment by mina9999** [comment]
where is the proof that it scan hard drive? 
im a face it player too. i inject osiris and when i want to play face it i restart csgo. 
when u enable face it anti cheat you cant inject osiris to csgo.

**Comment by wemanzoz** [comment]
lol, faceit scans your harddrive POOOG

**Comment by linuxer9** [comment]
just restart cs go and delete osiris dll and any injector and you good to go.
VAC probably scans your hard drive (I can't confirm that tbh). but it will never convect you for just having the cheat itself without injecting.

**Comment by king1919djdj** [comment]
i am not sure that VAC scans your hard drive because from scanning hard drive it should also be able to confirm cheat injection ?
and it will a bit too resource consuming ?

**Comment by caiocinel** [comment]
> i am not sure that VAC scans your hard drive because from scanning hard drive it should also be able to confirm cheat injection ?
> and it will a bit too resource consuming ?

The VAC barely scans for modules loaded in the game.
