### ISSUE TITLE
[Suggestion] Aspect Ratio mode

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#2748]
maybe a checkbox that automatically config your aspect ratio? (4:3 mode etc). or any way i can add this myself

**Comment by ishaangamer27** [comment]
Well in the misc tab there is an aspect ratio and you can customize I use 16:9 and a res of 1280x720 with a 0.92 aspect ratio

**Comment by wemanzoz** [comment]
> Well in the misc tab there is an aspect ratio and you can customize I use 16:9 and a res of 1280x720 with a 0.92 aspect ratio

ik theres that aspect ratio slider, what i meant is like. a button that we press to "autoconfig" the slider to a certain number (modes)
