### ISSUE TITLE
[SUGGESTION] Triggerbot that will lock onto enemies for you and shoot

### ISSUE THREAD

**Issue by acey1337** [danielkrupinski/Osiris#2750]
Would be nice if a triggerbot like that could be added so I can semirage with this cheat.

**Comment by KernCS** [comment]
Aimlock ??

**Comment by wemanzoz** [comment]
> Would be nice if a triggerbot like that could be added so I can semirage with this cheat.

why lmao,

**Comment by king1919djdj** [comment]
use both aimlock and trigger bot simultaneously

**Comment by hydemods** [comment]
create a second bind for aimbot in the source. Then just bind that secondary key to your trigger key. profit.

**Comment by acey1337** [comment]
> create a second bind for aimbot in the source. Then just bind that secondary key to your trigger key. profit.

big brain 200 iq

**Comment by Rynav** [comment]
Can't you just use aimbot with auto shoot function on?
