### ISSUE TITLE
Anybody successful Manual Mapping Osiris to CSGO?

### ISSUE THREAD

**Issue by Bakedpurple** [danielkrupinski/Osiris#2751]
I've only been successful using Load Library injection to csgo using any injector and I'm wondering if I have to do anything to enable my dll to be able to manual map injected. I use the same injector and it appears only some DLLs are able to inject successfully using manual map without crash. Thank you!

**Comment by linuxer9** [comment]
[shtreeba ](https://github.com/mdilai/Shtreeba)works
