### ISSUE TITLE
Get banned because of anti DLL?

### ISSUE THREAD

**Issue by dz1102** [danielkrupinski/Osiris#2758]
Hi, I inject Osiris into CS:GO and get banned by this server: 103.9.158.241:27019

![image](https://user-images.githubusercontent.com/54879097/113382247-3f8fa000-93ab-11eb-8eec-481c22343bf0.png)

They're using some kind of antiDLL method to ban whoever using DLL the moment they connect to the server. Is there anything I can do to Osiris to bypass this? I changed my injector and injection method to manual map but it didn't work

**Comment by mkot2** [comment]
got banned before i even connected, interesting

**Comment by dz1102** [comment]
> got banned before i even connected, interesting

Yeah, that's kinda lame

**Comment by danielkrupinski** [comment]
The plugin is open source (https://github.com/JDW1337/AntiDLL/) and it detects registered event listeners. Calling `CGameEventManager::HasClientListenersChanged(true)` after registering our listeners may bypass the anticheat.

**Comment by dz1102** [comment]
> The plugin is open source (https://github.com/JDW1337/AntiDLL/) and it detects registered event listeners. Calling `CGameEventManager::HasClientListenersChanged(true)` after registering our listeners may bypass the anticheat.

Can u pls update osiris to bypass this :( pleaseee

**Comment by SM9CC** [comment]
Should not be hard, I don't know how to get vtable indexes though.

**Comment by danielkrupinski** [comment]
AntiDLL detects `item_purchase` and `bullet_impact` event listeners.
Unfortunately the client has to let the server know which events it listens to, otherwise the server won't transmit them to the client. That means "Purchase List" and "Bullet Tracers" can't be used on servers with AntiDLL installed.
A temporary solution to avoid being banned is to comment-out lines with `item_purchase` and `bullet_impact` https://github.com/danielkrupinski/Osiris/blob/99cf9d2796e3bc380efa1f742413da72e8c6bb85/Osiris/EventListener.cpp#L16-L20

**Comment by danielkrupinski** [comment]
You should now (2c6bb36eb01ae0db7a9af1a491c13284da54e373, 2e2a03e4fa219e9c31d8a4820ae0799ef57ae146) be able to play on a server with AntiDLL, but remember to **turn off "Purchase list" and "Bullet tracers" before connecting to the server**.

**Comment by fast-kill** [comment]
> You should now ([2c6bb36](https://github.com/danielkrupinski/Osiris/commit/2c6bb36eb01ae0db7a9af1a491c13284da54e373), [2e2a03e](https://github.com/danielkrupinski/Osiris/commit/2e2a03e4fa219e9c31d8a4820ae0799ef57ae146)) be able to play on a server with AntiDLL, but remember to **turn off "Purchase list" and "Bullet tracers" before connecting to the server**.

do not forget to turn off your mother and throw it into the ditch when animals enter the server with cheats

**Comment by rcon420** [comment]
fuck u cunts why you even play with cheats on community servers? Can't u go and play HvH. You are the aid of csgo no matter what anti cheat admins still gonna ban you

**Comment by dz1102** [comment]
> You should now ([2c6bb36](https://github.com/danielkrupinski/Osiris/commit/2c6bb36eb01ae0db7a9af1a491c13284da54e373), [2e2a03e](https://github.com/danielkrupinski/Osiris/commit/2e2a03e4fa219e9c31d8a4820ae0799ef57ae146)) be able to play on a server with AntiDLL, but remember to **turn off "Purchase list" and "Bullet tracers" before connecting to the server**.

Thank u. May I ask why the AntiDLL only detects the DLL when the Purchase List and Bullet Tracers is on? Does it detect anything else?

**Comment by mkot2** [comment]
> 
> 
> f*ck u c**ts why you even play with cheats on community servers? Can't u go and play HvH or MM. You are the aid of csgo no matter what anti-cheat admins still gonna ban you. Quit sad me as Server Owner gotta crowdfund projects like AntiDLL just to get rid off of a bunch of degenerates.

imagine posting this on a github repo of a cheat, also all anti cheats can be bypassed so saying "no matter what anti-cheat admins still gonna ban you" is pretty dumb
