### ISSUE TITLE
[Feature] Bomb Timer

### ISSUE THREAD

**Issue by henrydatei** [danielkrupinski/Osiris#2762]
Could you please add a feature, that shows the remaining time of the planted C4 until it explodes?

**Comment by VuBrian22** [comment]
The feature already exists in the cheat.

**Comment by wemanzoz** [comment]
> Could you please add a feature, that shows the remaining time of the planted C4 until it explodes?

it exist, on misc tab :)

**Comment by henrydatei** [comment]
Ok, and what's the name of it? I spend yesterday about 5 minutes starring at the misc tab but I couldn't find it...

**Comment by KernCS** [comment]
Bomb timer, It's under Fast stop https://github.com/danielkrupinski/Osiris/blob/99cf9d2796e3bc380efa1f742413da72e8c6bb85/Osiris/GUI.cpp#L1348

**Comment by caiocinel** [comment]
Sometimes the price you pay for knowing how to read is too expensive.

**Comment by wemanzoz** [comment]
LMAO
