### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by MirzaGorgAli** [danielkrupinski/Osiris#2764]
Can anyone tell me how to hook this please? 

[Replace Weapon Sounds](https://www.unknowncheats.me/forum/counterstrike-global-offensive/216322-replace-weapon-sounds.html)

I had tried using VBaseFileSystem011 and VFileSystem017, but didn't work :/

Thank you ❤️

***SORRY ABOUT MY ENGLISH***

**Comment by egssy0** [comment]
Yes I can tell you, Learn pasting

**Comment by MirzaGorgAli** [comment]
> 
> 
> Yes I can tell you, Learn pasting

Hi man, if you know tell me how to hook it Please ❤️❤️❤️

**Comment by mkot2** [comment]
> 
> 
> Yes I can tell you, Learn pasting

haha
