### ISSUE TITLE
[bug] most of time anti aim dosnt work.

### ISSUE THREAD

**Issue by kpopdev** [danielkrupinski/Osiris#2767]
i test it with my friend and every matches i was staying and they can always headshot me and it dosnt work when they look at my legs it dosnt look like it working.
i have yaw enabled too.

**Comment by wemanzoz** [comment]
not a semirage/rage cheat

**Comment by linuxer9** [comment]
the current anti aim is bad, use the anti aim in this build
https://github.com/notgoodusename/osiriswithstuff
