### ISSUE TITLE
[suggestion] seperate skins for ct and tside

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#2768]
would be cool (very cool)

**Comment by KurastikO** [comment]
why though

**Comment by wemanzoz** [comment]
> why though

why not? i feel like this is a quality of life update. also wanted this just so i can have 2 skin themes in 1 config

**Comment by ShadowwEx** [comment]
I want this to happen

**Comment by wemanzoz** [comment]
just like interiums skin changer. dual slots (ct and t side) per gun. feels
more "realistic" imo to have 2 slots per weapon

**Comment by caiocinel** [comment]
you can just add a new check in SkinChanger.cpp, but the best way is a InventoryChanger.

**Comment by falseCloud** [comment]
cool idea tho

**Comment by wemanzoz** [comment]
waiting for this to happen
