### ISSUE TITLE
config issue

### ISSUE THREAD

**Issue by Tothale** [danielkrupinski/Osiris#2769]
hello, i selected my settings and pressed "save selected" button on the config tab, but when i click the "load selected" button this loads old config, is this my issue or cheat's issue?

**Comment by Thugilmo** [comment]
Cheat issue. The cheat does not save options that are not activated and that's the reason which causes an override when loading another config with less options.

**Comment by danielkrupinski** [comment]
Check if the config file contains setting you set. Do you have "Incremental load" checked or unchecked? @Thugilmo That's not an issue, all options are reverted to defaults before config is loaded.

**Comment by Tothale** [comment]
1) I loaded a config with "disable HUD blur" checked. (with incremental load unchecked)
2) I unchecked "disable HUD blur" setting in misc tab.
3) I pressed "save selected" button in config tab. 
4) I pressed "load selected" button.
5) and "disable HUD blur" reopened.
briefly i think the settings are not saving with "save selected" button (I just haven't tried only "disable hud blur" this is an example)

**Comment by mkot2** [comment]
> 
> 
>     1. I loaded a config with "disable HUD blur" checked. (with incremental load unchecked)
> 
>     2. I unchecked "disable HUD blur" setting in misc tab.
> 
>     3. I pressed "save selected" button in config tab.
> 
>     4. I pressed "load selected" button.
> 
>     5. and "disable HUD blur" reopened.
>        briefly i think the settings are not saving with "save selected" button (I just haven't tried only "disable hud blur" this is an example)

i tried this and it worked fine

**Comment by Tothale** [comment]
I found the problem and fixed it.
solution: **defender -> controlled folder access** 
thanks @blackMasterLord (#2674)
