### ISSUE TITLE
Fake prime not working on linux?

### ISSUE THREAD

**Issue by henrydatei** [danielkrupinski/Osiris#2770]
A couple days ago "Fake prime" was working fine on linux. Currently it's not. I've updated the cheat to the newest version of the repo, but it still doesn't work.

**Comment by JostBrand** [comment]
It couldnt work check the source. It is in a #ifdef _WIN32,#endif. It does nothing on linux.

**Comment by mkot2** [comment]
find the pattern on linux and make it work

**Comment by mdilai** [comment]
PR #2829 fixes this

**Comment by ArtemSokolovskiy** [comment]
Pull requests
