### ISSUE TITLE
[HOLD] Aimbot doesn't work

### ISSUE THREAD

**Issue by floydGG** [danielkrupinski/Osiris#2776]
I build the dll, injected, and aimbot with holding key doesn't work.
But without key working perfectly, any help?

**Comment by wemanzoz** [comment]
> I build the dll, injected, and aimbot with holding key doesn't work.
> But without key working perfectly, any help?
user issue i guess, maybe your smoothing?

**Comment by floydGG** [comment]
> > I build the dll, injected, and aimbot with holding key doesn't work.
> > But without key working perfectly, any help?
> 
> smoothing to high?

no smoothing at all, set to 1 (default) but low fov about 0.9

**Comment by rosesware** [comment]
Same here, just working with menu opened.

**Comment by mina9999** [comment]
i have problem that when autoshot is on it miss alot even when im staying or im using slow walk.

**Comment by wemanzoz** [comment]
> i have problem that when autoshot is on it miss alot even when im staying or im using slow walk.

osiris has no aimbot hitchance

**Comment by wemanzoz** [comment]
osiris = not hvh cheat @mina9999

**Comment by floydGG** [comment]
> osiris = not hvh cheat @mina9999

i'm using it for legit btw just in case if u need to know.
any help? and yeah can we actually got the previous version of osiris? i mean before the new input system?

**Comment by floydGG** [comment]
yeah anyway, someone still have the old source? i was using this version of osiris, and the hold aimbot working like charm 
![Uploading old.png…]()
