### ISSUE TITLE
make -j24 failed

### ISSUE THREAD

**Issue by Linus42069** [danielkrupinski/Osiris#2777]
When building osiris using the script, I after a short ammount of time i get this error. Not sure what it means. I went into the build-log or whatever it's called, and mentioned something about fseeko.c and freehead.c (I USE LINUX DEBIAN)

**Comment by danielkrupinski** [comment]
Show the error message.

**Comment by Linus42069** [comment]
This was a issue I solved, will close it. Although I have a other issue with compiling it. Will open another issue
