### ISSUE TITLE
VAC ban

### ISSUE THREAD

**Issue by FrankFeenix** [danielkrupinski/Osiris#2778]
today i got a VAC ban of being ur cheat. Sad

**Comment by rosesware** [comment]
?

**Comment by wemanzoz** [comment]
> not using vac bypass

**Comment by linuxer9** [comment]
it's guaranteed to get vac banned using any public cheat or public injector without vac bypass.

**Comment by xpossed-you** [comment]
> today i got a VAC ban of being ur cheat. Sad

the chances of getting VAC ban using this cheat is very low because @danielkrupinski update this cheat almost daily, maybe your using outdated injector that already detected or you're using detected cheat before you using this cheat

**Comment by Heyter** [comment]
I have been using this hack for 1 year and the account is alive.
