### ISSUE TITLE
Unable to compile "linux"

### ISSUE THREAD

**Issue by Linus42069** [danielkrupinski/Osiris#2779]
So I'm trying to install Osiris on Linux Debian (buster 10) (Language - Swedish which may implicate some messages are written in Swedish)
What I've done is. 
1 Clone the repository 
2 Made a "build" folder inside of Osiris
3 Did "cd Osiris/build" and then ran these 2 commands "cmake .." and "make -j12" 
The first command "cmake .." worked and gave this output "

-- Configuring done
-- Generating done
-- Build files have been written to: /home/linusj/Osiris

After I ran "make -j12" and got this output

[  3%] Building CXX object CMakeFiles/Osiris.dir/Osiris/GameData.cpp.o
[  3%] Building CXX object CMakeFiles/Osiris.dir/Osiris/Config.cpp.o
[  5%] Building CXX object CMakeFiles/Osiris.dir/Osiris/GUI.cpp.o
[  7%] Building CXX object CMakeFiles/Osiris.dir/Osiris/Hacks/AntiAim.cpp.o
[  8%] Building CXX object CMakeFiles/Osiris.dir/Osiris/EventListener.cpp.o
[ 10%] Building CXX object CMakeFiles/Osiris.dir/Osiris/Hacks/Backtrack.cpp.o
[ 14%] Building CXX object CMakeFiles/Osiris.dir/Osiris/Hacks/Aimbot.cpp.o
[ 14%] Building CXX object CMakeFiles/Osiris.dir/Osiris/Hacks/EnginePrediction.cpp.o
[ 17%] Building CXX object CMakeFiles/Osiris.dir/Osiris/Hacks/Misc.cpp.o
[ 17%] Building CXX object CMakeFiles/Osiris.dir/Osiris/Hacks/Chams.cpp.o
[ 19%] Building CXX object CMakeFiles/Osiris.dir/Osiris/Hacks/SkinChanger.cpp.o
[ 21%] Building CXX object CMakeFiles/Osiris.dir/Osiris/Hacks/Glow.cpp.o
In file included from /home/linusj/Osiris/Osiris/SDK/Vector.h:5,
                 from /home/linusj/Osiris/Osiris/SDK/matrix3x4.h:12,
                 from /home/linusj/Osiris/Osiris/GameData.h:10,
                 from /home/linusj/Osiris/Osiris/EventListener.cpp:5:
/home/linusj/Osiris/Osiris/SDK/Utils.h:3:10: fatal error: numbers: Filen eller katalogen finns inte
 #include <numbers>
          ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Osiris.dir/build.make:76: CMakeFiles/Osiris.dir/Osiris/EventListener.cpp.o] Fel 1
make[2]: *** Inväntar oavslutade jobb...
In file included from /home/linusj/Osiris/Osiris/Hacks/../SDK/Vector.h:5,
                 from /home/linusj/Osiris/Osiris/Hacks/../SDK/Engine.h:7,
                 from /home/linusj/Osiris/Osiris/Hacks/EnginePrediction.cpp:4:
/home/linusj/Osiris/Osiris/Hacks/../SDK/Utils.h:3:10: fatal error: numbers: Filen eller katalogen finns inte
 #include <numbers>
          ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Osiris.dir/build.make:167: CMakeFiles/Osiris.dir/Osiris/Hacks/EnginePrediction.cpp.o] Fel 1
In file included from /home/linusj/Osiris/Osiris/Hacks/../SDK/Vector.h:5,
                 from /home/linusj/Osiris/Osiris/Hacks/../SDK/matrix3x4.h:12,
                 from /home/linusj/Osiris/Osiris/Hacks/Backtrack.h:8,
                 from /home/linusj/Osiris/Osiris/Hacks/Backtrack.cpp:1:
/home/linusj/Osiris/Osiris/Hacks/../SDK/Utils.h:3:10: fatal error: numbers: Filen eller katalogen finns inte
 #include <numbers>
          ^~~~~~~~~
compilation terminated.
In file included from /home/linusj/Osiris/Osiris/Hacks/../SDK/Vector.h:5,
                 from /home/linusj/Osiris/Osiris/Hacks/../SDK/Engine.h:7,
                 from /home/linusj/Osiris/Osiris/Hacks/AntiAim.cpp:3:
/home/linusj/Osiris/Osiris/Hacks/../SDK/Utils.h:3:10: fatal error: numbers: Filen eller katalogen finns inte
 #include <numbers>
          ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Osiris.dir/build.make:141: CMakeFiles/Osiris.dir/Osiris/Hacks/Backtrack.cpp.o] Fel 1
make[2]: *** [CMakeFiles/Osiris.dir/build.make:128: CMakeFiles/Osiris.dir/Osiris/Hacks/AntiAim.cpp.o] Fel 1
In file included from /home/linusj/Osiris/Osiris/Hacks/../SDK/Vector.h:5,
                 from /home/linusj/Osiris/Osiris/Hacks/../SDK/matrix3x4.h:12,
                 from /home/linusj/Osiris/Osiris/Hacks/Backtrack.h:8,
                 from /home/linusj/Osiris/Osiris/GUI.cpp:30:
/home/linusj/Osiris/Osiris/Hacks/../SDK/Utils.h:3:10: fatal error: numbers: Filen eller katalogen finns inte
 #include <numbers>
          ^~~~~~~~~
compilation terminated.
In file included from /home/linusj/Osiris/Osiris/SDK/Vector.h:5,
                 from /home/linusj/Osiris/Osiris/SDK/matrix3x4.h:12,
                 from /home/linusj/Osiris/Osiris/GameData.h:10,
                 from /home/linusj/Osiris/Osiris/GameData.cpp:8:
/home/linusj/Osiris/Osiris/SDK/Utils.h:3:10: fatal error: numbers: Filen eller katalogen finns inte
 #include <numbers>
          ^~~~~~~~~
compilation terminated.
In file included from /home/linusj/Osiris/Osiris/Hacks/../SDK/Vector.h:5,
                 from /home/linusj/Osiris/Osiris/Hacks/../SDK/matrix3x4.h:12,
                 from /home/linusj/Osiris/Osiris/Hacks/Backtrack.h:8,
                 from /home/linusj/Osiris/Osiris/Hacks/Chams.cpp:9:
/home/linusj/Osiris/Osiris/Hacks/../SDK/Utils.h:3:10: fatal error: numbers: Filen eller katalogen finns inte
 #include <numbers>
          ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Osiris.dir/build.make:89: CMakeFiles/Osiris.dir/Osiris/GUI.cpp.o] Fel 1
make[2]: *** [CMakeFiles/Osiris.dir/build.make:102: CMakeFiles/Osiris.dir/Osiris/GameData.cpp.o] Fel 1
In file included from /home/linusj/Osiris/Osiris/Hacks/../SDK/Vector.h:5,
                 from /home/linusj/Osiris/Osiris/Hacks/../SDK/matrix3x4.h:12,
                 from /home/linusj/Osiris/Osiris/Hacks/Backtrack.h:8,
                 from /home/linusj/Osiris/Osiris/Config.cpp:18:
/home/linusj/Osiris/Osiris/Hacks/../SDK/Utils.h:3:10: fatal error: numbers: Filen eller katalogen finns inte
 #include <numbers>
          ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Osiris.dir/build.make:154: CMakeFiles/Osiris.dir/Osiris/Hacks/Chams.cpp.o] Fel 1
make[2]: *** [CMakeFiles/Osiris.dir/build.make:63: CMakeFiles/Osiris.dir/Osiris/Config.cpp.o] Fel 1
In file included from /home/linusj/Osiris/Osiris/Hacks/../SDK/Vector.h:5,
                 from /home/linusj/Osiris/Osiris/Hacks/../SDK/Engine.h:7,
                 from /home/linusj/Osiris/Osiris/Hacks/../SDK/Entity.h:6,
                 from /home/linusj/Osiris/Osiris/Hacks/Misc.cpp:20:
/home/linusj/Osiris/Osiris/Hacks/../SDK/Utils.h:3:10: fatal error: numbers: Filen eller katalogen finns inte
 #include <numbers>
          ^~~~~~~~~
compilation terminated.
In file included from /home/linusj/Osiris/Osiris/Hacks/../SDK/Vector.h:5,
                 from /home/linusj/Osiris/Osiris/Hacks/../SDK/Engine.h:7,
                 from /home/linusj/Osiris/Osiris/Hacks/../SDK/Entity.h:6,
                 from /home/linusj/Osiris/Osiris/Hacks/Aimbot.cpp:5:
/home/linusj/Osiris/Osiris/Hacks/../SDK/Utils.h:3:10: fatal error: numbers: Filen eller katalogen finns inte
 #include <numbers>
          ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Osiris.dir/build.make:193: CMakeFiles/Osiris.dir/Osiris/Hacks/Misc.cpp.o] Fel 1
make[2]: *** [CMakeFiles/Osiris.dir/build.make:115: CMakeFiles/Osiris.dir/Osiris/Hacks/Aimbot.cpp.o] Fel 1
In file included from /home/linusj/Osiris/Osiris/Hacks/../SDK/Vector.h:5,
                 from /home/linusj/Osiris/Osiris/Hacks/../SDK/Engine.h:7,
                 from /home/linusj/Osiris/Osiris/Hacks/../SDK/Entity.h:6,
                 from /home/linusj/Osiris/Osiris/Hacks/Glow.cpp:10:
/home/linusj/Osiris/Osiris/Hacks/../SDK/Utils.h:3:10: fatal error: numbers: Filen eller katalogen finns inte
 #include <numbers>
          ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Osiris.dir/build.make:180: CMakeFiles/Osiris.dir/Osiris/Hacks/Glow.cpp.o] Fel 1
In file included from /home/linusj/Osiris/Osiris/Hacks/../SDK/Vector.h:5,
                 from /home/linusj/Osiris/Osiris/Hacks/../SDK/Engine.h:7,
                 from /home/linusj/Osiris/Osiris/Hacks/SkinChanger.cpp:25:
/home/linusj/Osiris/Osiris/Hacks/../SDK/Utils.h:3:10: fatal error: numbers: Filen eller katalogen finns inte
 #include <numbers>
          ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Osiris.dir/build.make:206: CMakeFiles/Osiris.dir/Osiris/Hacks/SkinChanger.cpp.o] Fel 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/Osiris.dir/all] Fel 2
make: *** [Makefile:84: all] Fel 2

(fyi Fel means error)

I'm not sure if what I've done is what I'm supposed to do. If not then what am I supposed to do, if otherwise how do I compile/fix this error?

**Comment by wemanzoz** [comment]
@danielkrupinski hi

**Comment by danielkrupinski** [comment]
#2760

**Comment by Linus42069** [comment]
I did

cd Osiris/build

then

linusj@r2z26x1:~/Osiris/build$ cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=gcc-10 -D CMAKE_CXX_COMPILER=g++-10 ..
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
The CMAKE_C_COMPILER:

gcc-10
is not a full path and was not found in the PATH.

Tell CMake where to find the compiler by setting either the environment
variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:2 (project):
The CMAKE_CXX_COMPILER:

g++-10
is not a full path and was not found in the PATH.

Tell CMake where to find the compiler by setting either the environment
variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
to the compiler, or to the compiler name if it is in the PATH.

linusj@r2z26x1:~/Osiris/build$ cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=gcc-10 -D CMAKE_CXX_COMPILER=g++-10 ..
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
The CMAKE_C_COMPILER:

gcc-10
is not a full path and was not found in the PATH.

Tell CMake where to find the compiler by setting either the environment
variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:2 (project):
The CMAKE_CXX_COMPILER:

g++-10
is not a full path and was not found in the PATH.

Tell CMake where to find the compiler by setting either the environment
variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/linusj/Osiris/CMakeFiles/CMakeOutput.log".
See also "/home/linusj/Osiris/CMakeFiles/CMakeError.log"

**Comment by danielkrupinski** [comment]
Do you have g++-10 installed? What does `g++ --version` return?

**Comment by Linus42069** [comment]
g++ (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by danielkrupinski** [comment]
Install gcc-10 and g++-10.
