### ISSUE TITLE
Heath bar / Armor bar

### ISSUE THREAD

**Issue by cojo1989** [danielkrupinski/Osiris#278]
Hello Daniel, any chance to add soon Health Bar and Armor bar?

**Comment by effex1337** [comment]
I've added hp and armor (text) but in a really messy way.
Would you like it?  @danielkrupinski

**Comment by cojo1989** [comment]
Its better to have bar and text for health and only bar for armor :)

**Comment by effex1337** [comment]
Well doing anything in surface makes me want to kill myself

**Comment by cojo1989** [comment]
Chill bud, life is to short anyway :)

**Comment by EGTLoneWolf** [comment]
just use glow esp ( health ) 
ez fix

**Comment by cojo1989** [comment]
I know i can use that. But i would prefer more the bars.

**Comment by cojo1989** [comment]
Cool update @danielkrupinski can you add the bar also?

**Comment by cojo1989** [comment]
I love you !!! You can close this thicket.

**Comment by NexSqaud** [comment]
@cojo1989 you forgot about armor bar
