### ISSUE TITLE
error with memory.cpp while compiling for linux

### ISSUE THREAD

**Issue by asdffdsdaf** [danielkrupinski/Osiris#2780]
![image](https://user-images.githubusercontent.com/43644672/114311341-049e1280-9af7-11eb-8e41-e8dae17edad6.png)

**Comment by asdffdsdaf** [comment]
![image](https://user-images.githubusercontent.com/43644672/114313621-d40ea680-9aff-11eb-9e34-3a7558291c71.png)

**Comment by wemanzoz** [comment]
`use windows` :/

**Comment by asdffdsdaf** [comment]
> `use windows` :/

`nah`

**Comment by danielkrupinski** [comment]
@asdffdsdaf Try building again, the latest version of Osiris.

**Comment by asdffdsdaf** [comment]
> @asdffdsdaf Try building again, the latest version of Osiris.

![image](https://user-images.githubusercontent.com/43644672/114897717-2c081e80-9e1a-11eb-9da4-bfd6582b7c6a.png)
thank you
