### ISSUE TITLE
Installation guide for linux

### ISSUE THREAD

**Issue by Linus42069** [danielkrupinski/Osiris#2781]
There are NO instructions for the linux verision.

**Comment by asdffdsdaf** [comment]
true

**Comment by hugohabicht01** [comment]
Just take a look at https://github.com/danielkrupinski/Osiris/blob/master/.github/workflows/linux.yml
If you are on Ubuntu you can basically just copy and run the commands, on other distributions some commands may vary. On Arch  for example you will need to install the packages with pacman. Everything worked flawlessly for me on Arch

**Comment by asdffdsdaf** [comment]
> Just take a look at https://github.com/danielkrupinski/Osiris/blob/master/.github/workflows/linux.yml
> If you are on Ubuntu you can basically just copy and run the commands, on other distributions some commands may vary. On Arch  for example you will need to install the packages with pacman. Everything worked flawlessly for me on Arch

too bad, i am a fedora user

**Comment by hugohabicht01** [comment]
Doesn't matter, it worked for me to just use gcc and g++ instead of gcc-10 and g++-10

**Comment by asdffdsdaf** [comment]
> Doesn't matter, it worked for me to just use gcc and g++ instead of gcc-10 and g++-10

gcc and g++ dont work for me
they are version 11 and -std doesnt work

**Comment by hugohabicht01** [comment]
Well then just install version 10....

**Comment by asdffdsdaf** [comment]
> Well then just install version 10....

and how
its not in package manager nor the internet

**Comment by asdffdsdaf** [comment]
i mean i can compile from src

**Comment by MrOpxDRS** [comment]
@hugohabicht01 can you give me your .so file i dont know how to compile it :) pls
