### ISSUE TITLE
Create a self-flash event

### ISSUE THREAD

**Issue by vadbut** [danielkrupinski/Osiris#2782]
I'm wondering if it is possible to create a flash grenade event (for myself without affecting other players) when there is no real flash grenade is dropped (it's a long story why I need this).

I know for sure that changing flashMaxAlpha or flash duration variables (e,g, setting the duration to a typical value during a flash event of 4.0f) don't result in anything. Can someone pls give me a hint on where I should be looking?

**Comment by KernCS** [comment]
Not sure if I understand your question, but how I understand it, you need to fill your screen with a "white image" and then have it fade?

**Comment by vadbut** [comment]
yes, - you got it right. And it should be done by tapping onto CS GO functionality.

**Comment by blackMasterLord** [comment]
[check](https://github.com/perilouswithadollarsign/cstrike15_src/blob/f82112a2388b841d72cb62ca48ab1846dfcc11c8/game/shared/cstrike15/flashbang_projectile.cpp#L317-L325)
