### ISSUE TITLE
I have some problems translating some things into Chinese. Can you help me and teach me some solutions? I'll thank you very much

### ISSUE THREAD

**Issue by hani-lengxi** [danielkrupinski/Osiris#2783]
I have some problems translating some things into Chinese. Can you help me and teach me some solutions? I'll thank you very much
![image](https://user-images.githubusercontent.com/82372239/114372746-7ab47f00-9bb4-11eb-9262-bdbf4fd09957.png)

**Comment by dapaster** [comment]
try 
translate.google.com

**Comment by rosesware** [comment]
You can change it on Backtrack.cpp, Glow.cpp & Sound.cpp.

**Comment by hani-lengxi** [comment]
I know it's there, but when I try to translate these documents into Chinese, there's a "?" , I want to know how to translate them into Chinese, like GUI. CPP reference font file like that

**Comment by hani-lengxi** [comment]
> 您可以在Backtrack.cpp、Glow.cpp和Sound.cpp上更改它。

I know it's there, but when I try to translate these documents into Chinese, there's a "?" , I want to know how to translate them into Chinese, like GUI. CPP reference font file like that

**Comment by danielkrupinski** [comment]
Make sure the source files are using UTF-8 encoding.
