### ISSUE TITLE
Turn flashbang effect into black

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#2785]
is it possible to change the flashbang effect from white to black?

**Comment by danielkrupinski** [comment]
[Yes](https://github.com/perilouswithadollarsign/cstrike15_src/blob/f82112a2388b841d72cb62ca48ab1846dfcc11c8/game/client/cstrike15/cs_view_scene.cpp#L190)

**Comment by dapaster** [comment]
Thanks!
