### ISSUE TITLE
Tree Cham???

### ISSUE THREAD

**Issue by EGTLoneWolf** [danielkrupinski/Osiris#279]
![image](https://user-images.githubusercontent.com/37926526/59489014-ae88c580-8eb3-11e9-8688-15a854e87698.png)
Why is the tree visible LOL

**Comment by danielkrupinski** [comment]
Did you use occluded palm chams?

**Comment by NexSqaud** [comment]
You modified chams code?

**Comment by EGTLoneWolf** [comment]
nope just the most basic 1 and i didnt edit cham code . it was a bug i guess , disappeared the next time i played d2

**Comment by EGTLoneWolf** [comment]
that was when i had allies occluded chams enabled

**Comment by danielkrupinski** [comment]
Closing now. If the problem occurs again, open new issue with screenshot of you settings.
