### ISSUE TITLE
[Maybe Small Fix] BulletTracers Json Saving

### ISSUE THREAD

**Issue by ClaudiuHKS** [danielkrupinski/Osiris#2794]
At:

https://github.com/danielkrupinski/Osiris/blob/ac1f25eb76891d7d418472121d9ba42a679439e0/Osiris/Config.cpp#L220

..

`static void from_json(const json& j, BulletTracers& o)`
`{`
`    read(j, "Enabled", o.enabled);`
`    read<value_t::object>(j, "Color", o.color);`
`}`

I think it should be replaced with:

`static void from_json(const json& j, BulletTracers& o)`
`{`
`from_json(j, static_cast<ColorToggle&>(o));`
`}`

**Comment by danielkrupinski** [comment]
You are right. dc91f71b7fe0709df61977bbbdda841b12f39c3f
