### ISSUE TITLE
[Help] Osiris crashing

### ISSUE THREAD

**Issue by igre3zy** [danielkrupinski/Osiris#2795]
Trying to use configs from about a week ago makes osiris crash, any help?

**Comment by YeetingWaterbottle** [comment]
The config is probably another version of the cheat. Try to make one yourself.

**Comment by igre3zy** [comment]
> The config is probably another version of the cheat. Try to make one yourself.

My configs are really complex and will take hours to re make thats why im asking if theres a fix

**Comment by YeetingWaterbottle** [comment]
> > The config is probably another version of the cheat. Try to make one yourself.
> 
> My configs are really complex and will take hours to re make thats why im asking if theres a fix

I'm **__not sure__** there is one, because the cheat changed the config system.

**Comment by danielkrupinski** [comment]
Post the configs that crash.

**Comment by mina9999** [comment]
{
  "Aimbot": [
    {
      "Auto scope": true,
      "Auto shot": true,
      "Bone": 1,
      "Enabled": true,
      "Fov": 255.0,
      "Ignore flash": true,
      "Ignore smoke": true,
      "Killshot": true,
      "Min damage": 50,
      "Scoped only": false,
      "Silent": true,
      "Visible only": false
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {}
  ],
  "Aimbot Key": "MOUSE1",
  "Aimbot Key mode": 0,
  "Aimbot On key": false,
  "Anti aim": {
    "Pitch angle": 17.8,
    "Yaw": true
  },
  "Backtrack": {
    "Enabled": true,
    "Ignore smoke": true,
    "Recoil based fov": true
  },
  "Chams": {
    "Allies": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Backtrack": {
      "Materials": [
        {
          "Alpha": 1.0,
          "Blinking": true,
          "Color": "#52d4d6",
          "Enabled": true,
          "Material": 9
        },
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "DESYNC": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Defusing": {
      "Materials": [
        {
          "Alpha": 1.0,
          "Color": "#fc7f00",
          "Enabled": true,
          "Ignore-Z": true,
          "Material": 10
        },
        {
          "Alpha": 1.0,
          "Color": "#0041ff",
          "Enabled": true,
          "Ignore-Z": true
        },
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Desync": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Enemies": {
      "Materials": [
        {
          "Alpha": 1.0,
          "Color": "#92d37c",
          "Enabled": true,
          "Health based": true,
          "Ignore-Z": true,
          "Material": 1
        },
        {
          "Alpha": 1.0,
          "Color": "#0c0c0c",
          "Health based": true,
          "Ignore-Z": true,
          "Material": 10
        },
        {
          "Alpha": 1.0,
          "Color": "#b90fc2",
          "Material": 3
        },
        {
          "Alpha": 1.0,
          "Color": "#5c5e50",
          "Ignore-Z": true,
          "Material": 1
        },
        {
          "Alpha": 1.0,
          "Color": "#00ff69",
          "Enabled": true
        },
        {
          "Alpha": 1.0,
          "Color": "#625757",
          "Ignore-Z": true,
          "Material": 4
        },
        {}
      ]
    },
    "Hands": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Local player": {
      "Materials": [
        {
          "Material": 4
        },
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Planting": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Sleeves": {
      "Materials": [
        {
          "Alpha": 1.0,
          "Color": "#232d6b",
          "Cover": true,
          "Material": 10,
          "Rainbow": true,
          "Rainbow Speed": 0.79999983
        },
        {
          "Wireframe": true
        },
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Weapons": {
      "Materials": [
        {
          "Alpha": 1.0,
          "Color": "#742dba"
        },
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    }
  },
  "ESP": {
    "Enemies": {
      "All": {
        "Box": {
          "Alpha": 1.0,
          "Color": "#f81f1f",
          "Enabled": true,
          "Type": 3
        },
        "Enabled": true,
        "Flash Duration": {
          "Alpha": 1.0,
          "Color": "#e16464",
          "Enabled": true
        },
        "Font": {
          "Name": "Arial Black"
        },
        "Head Box": {
          "Enabled": true
        },
        "Health Bar": {
          "Enabled": true
        },
        "Name": {
          "Alpha": 1.0,
          "Color": "#4be293",
          "Enabled": true
        },
        "Weapon": {
          "Alpha": 1.0,
          "Color": "#d8ec61",
          "Enabled": true
        }
      },
      "Visible": {
        "Box": {
          "Enabled": true
        },
        "Font": {
          "Name": "Default"
        }
      }
    },
    "Other Entities": {
      "All": {
        "Enabled": true
      }
    },
    "Projectiles": {
      "All": {
        "Box": {
          "Alpha": 1.0,
          "Color": "#db0202",
          "Enabled": true,
          "Type": 2
        },
        "Enabled": true,
        "Name": {
          "Enabled": true
        },
        "Snapline": {
          "Type": 1
        }
      }
    },
    "Weapons": {
      "All": {
        "Font": {
          "Name": "Ebrima"
        },
        "Name": {
          "Enabled": true
        }
      },
      "Grenades": {
        "Enabled": true,
        "Font": {
          "Name": "Candara"
        }
      },
      "Pistols": {
        "Font": {
          "Name": "Aldhabi"
        }
      }
    }
  },
  "Glow": {
    "Items": {
      "C4": {
        "Alpha": 1.0,
        "Color": "#ff0069",
        "Enabled": true
      },
      "Defuse Kits": {
        "Alpha": 1.0,
        "Color": "#1df438",
        "Enabled": true
      },
      "Hostages": {
        "Alpha": 1.0,
        "Color": "#f57f7f",
        "Enabled": true
      },
      "Planted C4": {
        "Alpha": 1.0,
        "Color": "#69ff00",
        "Enabled": true
      },
      "Weapons": {
        "Alpha": 1.0,
        "Color": "#e22e2e",
        "Enabled": true
      }
    },
    "Players": {
      "Defusing": {
        "All": {
          "Alpha": 1.0,
          "Color": "#00c0fc",
          "Enabled": true
        }
      },
      "Enemies": {
        "All": {
          "Alpha": 1.0,
          "Color": "#ff0000"
        }
      },
      "Planting": {
        "All": {
          "Alpha": 1.0,
          "Color": "#4e09fa",
          "Enabled": true
        }
      }
    }
  },
  "Misc": {
    "Anti AFK kick": true,
    "Auto accept": true,
    "Auto pistol": true,
    "Auto reload": true,
    "Auto strafe": true,
    "Bomb timer": {
      "Color": [
        0.94859815,
        0.6713328,
        0.33245265
      ],
      "Enabled": true,
      "Rainbow": true
    },
    "Bunny hop": true,
    "Choked packets": 2,
    "Choked packets key": "LCTRL",
    "Clan tag": "VAC PEEK ☣",
    "Deathmatch godmode": true,
    "Disable HUD blur": true,
    "Disable model occlusion": true,
    "Edge Jump Key": "LALT",
    "Fast Stop": true,
    "Fast duck": true,
    "Fast plant": true,
    "Fix animation LOD": true,
    "Fix bone matrix": true,
    "Fix movement": true,
    "Fix tablet signal": true,
    "Grenade predict": true,
    "Hit sound": 2,
    "Kill message string": "حیف ننت کص میده برات نت بخره مادر سگ",
    "Noscope crosshair": {
      "Alpha": 1.0,
      "Color": "#fefffe",
      "Thickness": 3.7999988
    },
    "Offscreen Enemies": {
      "Enabled": true
    },
    "Opposite Hand Knife": true,
    "Prepare revolver": true,
    "Preserve Killfeed": {
      "Enabled": true
    },
    "Quick reload": true,
    "Radar hack": true,
    "Reportbot": {
      "Abusive Communications": true,
      "Griefing": true,
      "Rounds": 100000001
    },
    "Reveal money": true,
    "Reveal ranks": true,
    "Reveal suspect": true,
    "Reveal votes": true,
    "Slowwalk": true,
    "Slowwalk key": "\\",
    "Spectator list": {
      "Enabled": true,
      "Pos": {
        "X": 1618.0,
        "Y": 660.0
      },
      "Size": {
        "X": 200.0,
        "Y": 200.0
      }
    }
  },
  "Skin changer": [
    {
      "Definition index": 42
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {}
  ],
  "Sound": {
    "Players": [
      {},
      {},
      {}
    ]
  },
  "Style": {
    "Colors": {
      "Border": [
        0.0,
        0.0,
        0.0,
        0.3
      ],
      "BorderShadow": [
        0.0,
        0.0,
        0.0,
        0.0
      ],
      "Button": [
        0.26,
        0.59,
        0.98,
        0.4
      ],
      "ButtonActive": [
        0.06,
        0.53,
        0.98,
        1.0
      ],
      "ButtonHovered": [
        0.26,
        0.59,
        0.98,
        1.0
      ],
      "CheckMark": [
        0.26,
        0.59,
        0.98,
        1.0
      ],
      "ChildBg": [
        0.0,
        0.0,
        0.0,
        0.0
      ],
      "DragDropTarget": [
        0.26,
        0.59,
        0.98,
        0.95
      ],
      "FrameBg": [
        1.0,
        1.0,
        1.0,
        1.0
      ],
      "FrameBgActive": [
        0.26,
        0.59,
        0.98,
        0.67
      ],
      "FrameBgHovered": [
        0.26,
        0.59,
        0.98,
        0.4
      ],
      "Header": [
        0.26,
        0.59,
        0.98,
        0.31
      ],
      "HeaderActive": [
        0.26,
        0.59,
        0.98,
        1.0
      ],
      "HeaderHovered": [
        0.26,
        0.59,
        0.98,
        0.8
      ],
      "MenuBarBg": [
        0.86,
        0.86,
        0.86,
        1.0
      ],
      "ModalWindowDimBg": [
        0.2,
        0.2,
        0.2,
        0.35
      ],
      "NavHighlight": [
        0.26,
        0.59,
        0.98,
        0.8
      ],
      "NavWindowingDimBg": [
        0.2,
        0.2,
        0.2,
        0.2
      ],
      "NavWindowingHighlight": [
        0.7,
        0.7,
        0.7,
        0.7
      ],
      "PlotHistogram": [
        0.9,
        0.7,
        0.0,
        1.0
      ],
      "PlotHistogramHovered": [
        1.0,
        0.45,
        0.0,
        1.0
      ],
      "PlotLines": [
        0.39,
        0.39,
        0.39,
        1.0
      ],
      "PlotLinesHovered": [
        1.0,
        0.43,
        0.35,
        1.0
      ],
      "PopupBg": [
        1.0,
        1.0,
        1.0,
        0.98
      ],
      "ResizeGrip": [
        0.35,
        0.35,
        0.35,
        0.17
      ],
      "ResizeGripActive": [
        0.26,
        0.59,
        0.98,
        0.95
      ],
      "ResizeGripHovered": [
        0.26,
        0.59,
        0.98,
        0.67
      ],
      "ScrollbarBg": [
        0.98,
        0.98,
        0.98,
        0.53
      ],
      "ScrollbarGrab": [
        0.69,
        0.69,
        0.69,
        0.8
      ],
      "ScrollbarGrabActive": [
        0.49,
        0.49,
        0.49,
        1.0
      ],
      "ScrollbarGrabHovered": [
        0.49,
        0.49,
        0.49,
        0.8
      ],
      "Separator": [
        0.39,
        0.39,
        0.39,
        0.62
      ],
      "SeparatorActive": [
        0.14,
        0.44,
        0.8,
        1.0
      ],
      "SeparatorHovered": [
        0.14,
        0.44,
        0.8,
        0.78
      ],
      "SliderGrab": [
        0.26,
        0.59,
        0.98,
        0.78
      ],
      "SliderGrabActive": [
        0.46,
        0.54,
        0.8,
        0.6
      ],
      "Tab": [
        0.764,
        0.797,
        0.83599997,
        0.931
      ],
      "TabActive": [
        0.596,
        0.728,
        0.884,
        1.0
      ],
      "TabHovered": [
        0.26,
        0.59,
        0.98,
        0.8
      ],
      "TabUnfocused": [
        0.9208,
        0.9274,
        0.9352,
        0.9862
      ],
      "TabUnfocusedActive": [
        0.74160004,
        0.8208,
        0.9144,
        1.0
      ],
      "TableBorderLight": [
        0.68,
        0.68,
        0.74,
        1.0
      ],
      "TableBorderStrong": [
        0.57,
        0.57,
        0.64,
        1.0
      ],
      "TableHeaderBg": [
        0.78,
        0.87,
        0.98,
        1.0
      ],
      "TableRowBg": [
        0.0,
        0.0,
        0.0,
        0.0
      ],
      "TableRowBgAlt": [
        0.3,
        0.3,
        0.3,
        0.09
      ],
      "Text": [
        0.0,
        0.0,
        0.0,
        1.0
      ],
      "TextDisabled": [
        0.6,
        0.6,
        0.6,
        1.0
      ],
      "TextSelectedBg": [
        0.26,
        0.59,
        0.98,
        0.35
      ],
      "TitleBg": [
        0.96,
        0.96,
        0.96,
        1.0
      ],
      "TitleBgActive": [
        0.82,
        0.82,
        0.82,
        1.0
      ],
      "TitleBgCollapsed": [
        1.0,
        1.0,
        1.0,
        0.51
      ],
      "WindowBg": [
        0.94,
        0.94,
        0.94,
        1.0
      ]
    },
    "Menu colors": 1
  },
  "Triggerbot": [
    {
      "Enabled": true,
      "Killshot": true,
      "Min damage": 50,
      "Scoped only": false
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {}
  ],
  "Triggerbot Key": "LALT",
  "Visuals": {
    "Brightness": 1.0,
    "FOV": 27,
    "Flash reduction": 100,
    "Molotov Hull": {
      "Enabled": true
    },
    "Thirdperson": true,
    "Thirdperson distance": 105,
    "Thirdperson key": "V",
    "Viewmodel FOV": 10
  }
}

**Comment by mina9999** [comment]
me too when i change to this config

**Comment by jpie726** [comment]
@YeetingWaterbottle 

> 
> 
> Post the configs that crash.

**Comment by YeetingWaterbottle** [comment]
> @YeetingWaterbottle 
> 
> > 
> > 
> > Post the configs that crash.
> 
> 

But I'm not the one who have those problem. lol

**Comment by jpie726** [comment]
Right, sorry. @igre3zy 

> 
> 
> Post the configs that crash.
