### ISSUE TITLE
glow broke 

### ISSUE THREAD

**Issue by antosha22rus** [danielkrupinski/Osiris#28]
Hi Daniel. After adding a flat chams broke the glow of the style 1,2,3. Only one player is highlighted. Waiting for your fix :) 
![50749622-1c6bf980-1251-11e9-884c-451cd11b3a05](https://user-images.githubusercontent.com/37859984/50749678-82588100-1251-11e9-9141-6022d6f473a2.png)

**Comment by danielkrupinski** [comment]
Fixed. Thanks for your report!

**Comment by antosha22rus** [comment]
Thanks for the correction!
Good luck in the development of the project
