### ISSUE TITLE
Config doesnt save

### ISSUE THREAD

**Issue by pisklakboo** [danielkrupinski/Osiris#280]
When i "save" a config, it doesnt save and i know that because when i tried to load my legit config it didnt load, if you could, bring an update or tell me a fix if theres any

(yes i got another injector)

**Comment by Mufinekkk** [comment]
Create new config.

**Comment by pisklakboo** [comment]
> Create new config.

I create a new config, with all the settings but when i want to load it the next day, it doesnt load...

**Comment by NexSqaud** [comment]
You pressed save, after create config?

**Comment by pisklakboo** [comment]
yup
