### ISSUE TITLE
Blockbot 2021 working

### ISSUE THREAD

**Issue by Flow512** [danielkrupinski/Osiris#2803]
please i need working blockbot

**Comment by KurastikO** [comment]
why

**Comment by Flow512** [comment]
> why

just idk for fun

**Comment by mkot2** [comment]
https://github.com/danielkrupinski/Osiris/pull/2520

**Comment by Flow512** [comment]
> #2520

this doesnt work

**Comment by E4zily** [comment]
fixed in #3326
