### ISSUE TITLE
[REQUEST] sound esp (waves, and such)

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#2805]
like this https://www.youtube.com/watch?v=eLswLAzN92o, https://www.youtube.com/watch?v=sfqXXfRfSdk etc. would be good if this existed tbhwu

**Comment by cristeigabriel** [comment]
this is commonly made with beam rings with a procedural halo scale, but you can handle it yourself and expiration easily. emitsound IIRC gives origin to a sound, but this can also be done with the player_footstep event (it's fired on server btw)
