### ISSUE TITLE
INJECTING ON LINUX 

### ISSUE THREAD

**Issue by tar420** [danielkrupinski/Osiris#2807]
I have followed this guide: [Linux Installation guide](https://github.com/danielkrupinski/Osiris/blob/master/.github/workflows/linux.yml)
But it doesnt explain how to inject the cheat at all. the last command is: make -j $(nproc --all)
and that only builds the cheat for me. Any information would help thank you

**Comment by JostBrand** [comment]
Just attach with gdb

**Comment by wemanzoz** [comment]
switch to windows, profit

**Comment by tar420** [comment]
Nvm I did it

**Comment by tar420** [comment]
Thanks for the support

**Comment by A-Random-Lantern** [comment]
Would be nice if you explained how you injected it, instead of leaving it off at "Nvm I did it"
