### ISSUE TITLE
Glow Style & Life bar

### ISSUE THREAD

**Issue by cojo1989** [danielkrupinski/Osiris#281]
Glow style beside 0 it's not showing through wall even if occlusion on.
Life bar it`s everytime full even if you hit the enemy.

**Comment by LeonScene** [comment]
Hello! You can use Chams Health based until this is fixed. Its full chams, but this still shows health.

**Comment by cojo1989** [comment]
I know bud. I'm just saying where are the bugs. Also the HP and ARMOR ar not working proper. For example if i hit him 2 times it`s saying 96, 98, 86 does not do anything else. It's not showing the true life of the enemy.

**Comment by danielkrupinski** [comment]
Health & armor bars are fixed. Glow styles are managed by game so can't fix it right now.
