### ISSUE TITLE
[Question]No misses for Osiris

### ISSUE THREAD

**Issue by Frouk3** [danielkrupinski/Osiris#2810]
Can someone test is var sv_usercmd_custom_random_seed
tagged by a server?
Also when i switched var from 1 to 0 Osiris without visible only and with autoshot started to kill without misses in a local server

**Comment by Frouk3** [comment]
Maybe other cheats using this cvar

**Comment by Frouk3** [comment]
One more question:
Will it crush your game on official Valve servers?

**Comment by mkot2** [comment]
it is a server cvar so it will only work on local games, and it wont crash your game it just wont do anything

**Comment by Frouk3** [comment]
> it is a server cvar so it will only work on local games, and it wont crash your game it just wont do anything

Nope it's working on official servers, and you can set to 0 in console

**Comment by mkot2** [comment]
> 
> 
> > it is a server cvar so it will only work on local games, and it wont crash your game it just wont do anything
> 
> Nope it's working on official servers, and you can set to 0 in console

there is absolutely no way it actually does anything on non local servers

**Comment by Frouk3** [comment]
> > > it is a server cvar so it will only work on local games, and it wont crash your game it just wont do anything
> > 
> > 
> > Nope it's working on official servers, and you can set to 0 in console
> 
> there is absolutely no way it actually does anything on non local servers

It's actually working if you dont believe me test it

**Comment by mkot2** [comment]
> 
> 
> > > > it is a server cvar so it will only work on local games, and it wont crash your game it just wont do anything
> > > 
> > > 
> > > Nope it's working on official servers, and you can set to 0 in console
> > 
> > 
> > there is absolutely no way it actually does anything on non local servers
> 
> It's actually working if you dont believe me test it

tested it on deathmatch and as expected it does nothing

**Comment by Frouk3** [comment]
Value of cvar (sv_usercmd_custom_random_seed) can be changed in console

**Comment by Frouk3** [comment]
So i will close issue
