### ISSUE TITLE
Colored Molotov ?

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#2814]
Opinion ?

![](https://i.imgur.com/NNlWuGo.png)

![](https://i.imgur.com/97OGkhT.png)

**Comment by JukoiDev** [comment]
Nice looking!

**Comment by HowToMakeFaceitAB** [comment]
good idea, it looks cool but to be honest, draw molly area would be much more helpful than colored mollys

**Comment by mkot2** [comment]
> 
> 
> good idea, it looks cool but to be honest, draw molly area would be much more helpful than colored mollys

molotov hull does exactly that

**Comment by SquidmarcHD** [comment]
how did you do it? get the particles and changes the color?
