### ISSUE TITLE
[LINUX] crashing on connect 

### ISSUE THREAD

**Issue by JostBrand** [danielkrupinski/Osiris#2816]
Game is only crashing when I injected Osiris.

I injected the master branch without any modifications. I loaded no config and the menu worked perfectly in the main menu. When I connect it crashes. Debugger is empty. 

Any1 has a clue what changed?

**Comment by ronin2022** [comment]
maybe your multicore rendering, try turning it off

**Comment by JostBrand** [comment]
> maybe your multicore rendering, try turning it off

tried it. had no effect 

but surprisingly one time it worked without changing anything and then after restarting the game it stopped working again. I tried it at least 10 times after that.

**Comment by JostBrand** [comment]
A random system upgrade fixed it.

just archlinux things ~
