### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by ronin2022** [danielkrupinski/Osiris#2817]
![image](https://user-images.githubusercontent.com/78011950/115705435-b9a5ba00-a396-11eb-9c7d-b4484f335ca2.png)

**Comment by mkot2** [comment]
vs2019?

**Comment by ronin2022** [comment]
> vs2019?
yeah

**Comment by jpie726** [comment]
You are probably building in x64 mode. If not, use `git reset` which will remove any changes you have made, and pull the latest

**Comment by namekh** [comment]
where do I put in "git reset"

**Comment by coolguy187** [comment]
had the same issue, just fixed it by updating vs 2019, should help

**Comment by jpie726** [comment]
I already checked for updates, but thanks

**Comment by coolguy187** [comment]
yeah, but I also installed various kinds of platform toolsets v142, just modify your vs2019 installation and tick mutliple v142 (with x86 behind them), thats what I did aswell and it worked

**Comment by jpie726** [comment]
Can you please say which ones? I cant afford to download 30gb of extensions and them not work.

**Comment by danielkrupinski** [comment]
Just install the latest release of Visual Studio and the package for C++ development.
