### ISSUE TITLE
Yucky IN_DUCK sound

### ISSUE THREAD

**Issue by daisuki333** [danielkrupinski/Osiris#2818]
yes hello so like i wanted to know how to get rid of this yucky sound 
https://streamable.com/bgi2cf

Thats from a very simple engine prediction edge bug code.

I know what is used to fix it but i have no idea how to actually do it.

https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/shared/baseplayer_shared.cpp#L675

This is what should fix the yucky ducking sound i just don't know how i'm supposed to implement it.

ik kinda irrelevant and useless but ye.

**Comment by koon666** [comment]
send me your discord, maybe i can help you with that.

**Comment by daisuki333** [comment]
> send me your discord, maybe i can help you with that.

coles#1382 my alt discord acc
