### ISSUE TITLE
Weird Issue (Skin changer).

### ISSUE THREAD

**Issue by ghostboy2112** [danielkrupinski/Osiris#2819]
Problem.:
In skin changer tab i have saved m9 bayonet(knife) with m9 bayonet doppler skin(Paint kit) in my config, but when i load my config the "Paint Kit" tab automatically changes to (bayonet : doppler ) rest every thing remains unchanged i mean wear, seed,etc. other weapons remain same. i only face this problem in the knife tab. 

Solution tried: 
1. Changing knife to Other knife example butterfly, knife changes but paint kit remains same in my case bayonet : doppler.
2. config delete and making new one. 
3. Osiris rebuild.
4. Osiris clean and build again. 
5. gaming reinstallation.

Image Link.: https://imgur.com/oiDbB2i

Config Link.: https://anonfiles.com/R1l521s3uc/SHUBU

Osiris build.: https://anonfiles.com/rbl92fs2u8/Osiris_dll

Request.: please help.

**Comment by wemanzoz** [comment]
i've experienced this issue, still do but it doesnt annoy me that much. but a fix will do better. @danielkrupinski :)

**Comment by ImChinaNB** [comment]
I've experienced this issue too. Also another issue (though it doesn't affect the actual skin): for example, if I change the paint kit to Butterfly Knife - Fade, it would become M9 - Fade after reloading the config. This should be fixed as well.
