### ISSUE TITLE
After any update of the source

### ISSUE THREAD

**Issue by cojo1989** [danielkrupinski/Osiris#282]
Everytime when you update the source of osiris when you load config settings are wrong and if you click on skin changer it will close your game.
Any posibility to update the source without destroy your configs? It's starting to be annoying... im making my configs every day after an update...

**Comment by FerrisSandCanyon** [comment]
just create a new struct for the new added features that modifies config.h then in your config.cpp just add the new struct in the load and save functions.

for reference: https://gist.github.com/FerrisSandCanyon/d890140a7825f7a9ca22002ec7c28cc8

**Comment by rohan-patra** [comment]
I don't think this guy knows enough about c++ to do that. Otherwise, he would know that the config is saved as a binary file and different versions of the source will read it differently.

**Comment by cojo1989** [comment]
If you know better then help Daniel to make a better way to save the config. And i dont understand why people like you are so frustrated. You could just shut up. Thank you ferris for your suggestion but i will wait to see if Daniel will change in the future the config system.

**Comment by danielkrupinski** [comment]
New config system will be released soon.
