### ISSUE TITLE
nSkinz saved settings to Osiris

### ISSUE THREAD

**Issue by kcboiz** [danielkrupinski/Osiris#2821]
Does anyone know how to import skin saved file of nSkinz to Osiris, cuz I just realize that Osiris use nSkinz as skin changer, and already had a setting for all guns, I don't want to repeat this process again so is it possible to import skin file to Orisis?

**Comment by wemanzoz** [comment]
c+p the config

**Comment by jpie726** [comment]
Close this

**Comment by danielkrupinski** [comment]
No
