### ISSUE TITLE
Disconnected by VAC: You cannot play on secure servers

### ISSUE THREAD

**Issue by peyman8487777** [danielkrupinski/Osiris#2822]
Hello
I will encounter this error after a few minutes of play. Please help me to solve this problem
full text:
Disconnected by VAC: You cannot play on secure servers
Modifying game files and/or in-game textures may cause this error.

 
Please remove any custom textures, skin changers, or software that modifies game files and restart your computer. We also recommend verifying your game files after making these changes.

**Comment by peyman8487777** [comment]
@danielkrupinski pls help me

**Comment by Scui1** [comment]
osiris is ditected man

**Comment by peyman8487777** [comment]
@Scui1 Thanks, I have been using it for several weeks without any problems, but today, everything I used, after 5 to 10 minutes, gives a verify error.

**Comment by wemanzoz** [comment]
vac error, not detection. unless you got the global cooldown popup

**Comment by mkot2** [comment]
> 
> 
> Hello
> I will encounter this error after a few minutes of play. Please help me to solve this problem
> full text:
> Disconnected by VAC: You cannot play on secure servers
> Modifying game files and/or in-game textures may cause this error.
> 
> Please remove any custom textures, skin changers, or software that modifies game files and restart your computer. We also recommend verifying your game files after making these changes.

if you are playing casual game modes then set misc->max angle delta to something under 30

**Comment by peyman8487777** [comment]
@mkot2 I only enable the aim bot and glow options

**Comment by wemanzoz** [comment]
> @mkot2 I only enable the aim bot and glow options

just do what he say

**Comment by jpie726** [comment]
Close this

**Comment by peyman8487777** [comment]
@mkot2 Thanks to everyone who helped guide the problem
