### ISSUE TITLE
Question: how to make Aimbot aims at backtraces

### ISSUE THREAD

**Issue by ImChinaNB** [danielkrupinski/Osiris#2825]
My idea is to save StudioHDR of the Backtrace into backtrace record, and then Multipoints through the records.
But it would give me a violation error because the bone things of the StudioHDR are already freed.
Please help.

**Comment by mkot2** [comment]
https://github.com/notgoodusename/osiriswithstuff/blob/master/Osiris/Hacks/Legitbot.cpp

**Comment by jpie726** [comment]
Close this
