### ISSUE TITLE
How do you inject the cheat under linux?

### ISSUE THREAD

**Issue by A-Random-Lantern** [danielkrupinski/Osiris#2828]
The only instructions made were how to compile it, but it is never explained how to inject it into csgo.exe. And the issues only say to use gdb with no further explanation.

**Comment by mdilai** [comment]
I use this slightly modified LWSS/Fuzion script:
```
#!/usr/bin/env bash

function echo_green {
        echo -e "\\e[32m$*\\e[0m"
}

function echo_orange {
        echo -e "\\e[33m$*\\e[0m"
}

function echo_red {
        echo -e "\\e[31m$*\\e[0m"
}

csgo_pid=$(pidof csgo_linux64)
if [ -z "$csgo_pid" ]; then
    echo_red "CS:GO needs to be open before you can inject, exiting..."
    exit 1
fi

# pBypass for crash dumps being sent
# You may also want to consider using -nobreakpad in your launch options.
sudo rm -rf /tmp/dumps # Remove if it exists
sudo mkdir --mode=000 /tmp/dumps # Make it as root with no permissions

if [ ! -f build_id ]; then
    echo "Build ID not found. Please rebuild using the './build' script."
    exit
fi

filename=$(cat build_id)

# Credit: Aixxe @ aixxe.net
if grep -q "$filename" /proc/"$csgo_pid"/maps; then
    echo_orange "Osiris is already injected, aborting..."
    exit
fi
echo "Injecting Build ID: $filename"

# https://www.kernel.org/doc/Documentation/security/Yama.txt
echo "2" | sudo tee /proc/sys/kernel/yama/ptrace_scope # Only allows root to inject code. This is temporary until reboot.

sudo cp "$filename" "/usr/lib/${filename}"

sudo killall -19 steam
sudo killall -19 steamwebhelper

lib_dir_name="lib"

input="$(
sudo gdb -n -q -batch-silent \
        -ex "set logging file /dev/null" \
        -ex "set logging redirect on" \
        -ex "set logging on" \
        -ex "attach $csgo_pid" \
        -ex "call ((void*(*)(const char*, int))dlopen)(\"/usr/lib/$filename\", 1)"   \
        -ex "detach" \
        -ex "quit"
)"

sleep 1
sudo killall -18 steamwebhelper
sudo killall -18 steam

sudo rm "/usr/lib/${filename}"

last_line="${input##*$'\n'}"

if [ "$last_line" != "\$1 = (void *) 0x0" ]; then
    echo_green "Successfully injected!"
else
    echo_red "Injection failed, make sure you have compiled..."
fi
```

Change `filename=$(cat build_id)` to your library name(e.g. `filename="libOsiris.so"`).

**Comment by A-Random-Lantern** [comment]
Thanks, this works. You might consider wanting to do PR with this change.

**Comment by mdilai** [comment]
> Thanks, this works. You might consider wanting to do PR with this change.

There is very similar PR waiting for approval but, in my opinion, injectors and injection methods should be kept separately from cheat itself

**Comment by A-Random-Lantern** [comment]
Sorry, but since I can't figure this out, how do you find the "library name"? I got a bit ahead of myself when I said I got it working.

**Comment by mdilai** [comment]
> Sorry, but since I can't figure this out, how do you find the "library name"? I got a bit ahead of myself when I said I got it working.

Assuming that you are using default CMakeLists.txt, after "cmake ." and "make" you get file named libOsiris.so in build folder. Put script above to file named, for example, `load.sh` in same folder as libOsiris.so and change line #31 from `filename=$(cat build_id)` to `filename="libOsiris.so"`

As for me, my build script generate library with a new name (from list of 1.5k generic so-names) on each compilation so i write last used filename to file "build_id", but you may just replace it directly with default name - libOsiris.so.

I hope this explanation is enough for you.

**Comment by A-Random-Lantern** [comment]
Doesn't seem to be working for me, despite me changing line 31, and placing the script inside /Release. I just get "Build ID not found" 

I've tried recompiling it, with different methods to no success. I've tried GCC and clang.

**Comment by mdilai** [comment]
Damn, my fault. Just "touch build_id" in same folder if you can't remove this checking from code itself.

**Comment by A-Random-Lantern** [comment]
Yes this solved it, thanks. Just to make it clear for everyone else, place the script in /Release, and replace line 31 in the script with filename="libOsiris.so"

Then run "touch build_id" in /Release.

**Comment by ayaanjaved07** [comment]
> Yes this solved it, thanks. Just to make it clear for everyone else, place the script in /Release, and replace line 31 in the script with filename="libOsiris.so"
> 
> Then run "touch build_id" in /Release.

can you tell what the last line means as i am a complete noob and what to do

**Comment by IAmV0id** [comment]
> > Yes this solved it, thanks. Just to make it clear for everyone else, place the script in /Release, and replace line 31 in the script with filename="libOsiris.so"
> > Then run "touch build_id" in /Release.
> 
> can you tell what the last line means as i am a complete noob and what to do

Run `cd /Osiris/Release` in the folder where osiris is located. Once you do that, you can run 'touch build_id'

**Comment by IAmV0id** [comment]
> > Yes this solved it, thanks. Just to make it clear for everyone else, place the script in /Release, and replace line 31 in the script with filename="libOsiris.so"
> > Then run "touch build_id" in /Release.
> 
> can you tell what the last line means as i am a complete noob and what to do

Run `cd /Osiris/Release` in the folder where osiris is located. Once you do that, you can run 'touch build_id'

**Comment by ayaanjaved07** [comment]
> > > Yes this solved it, thanks. Just to make it clear for everyone else, place the script in /Release, and replace line 31 in the script with filename="libOsiris.so"
> > > Then run "touch build_id" in /Release.
> > 
> > 
> > can you tell what the last line means as i am a complete noob and what to do
> 
> Run the command `cd /Osiris/Release` in a terminal where the directory with Osiris is located. Once you do that, you can run `touch build_id` in the terminal.

oh
will try
thanks for telling

**Comment by gamenic-pawanrai** [comment]
@IAmV0id @mdilai  can anyone of you please write step wise procedure ? Downloaded the package but I don't see `release` directory.

**Comment by IAmV0id** [comment]
Did you compile it? You need to do that to get /Release

**Comment by ayaanjaved07** [comment]
> @IAmV0id @mdilai can anyone of you please write step wise procedure ? Downloaded the package but I don't see `release` directory.

compile it first https://github.com/danielkrupinski/Osiris/blob/master/.github/workflows/linux.yml
then go into release, open a text editor and paste the script
Change(line 31) filename=$(cat build_id) to your library name(e.g. filename="libOsiris.so").
then save it in osiris/release as load.sh
open terminal and go there
do chmod +x load.sh
then open csgo, run touch build_id in terminal(in directory Osiris/Release)
and then to inject do ./load.sh
