### ISSUE TITLE
Seems to be detected

### ISSUE THREAD

**Issue by MidgeC** [danielkrupinski/Osiris#2834]
used osiris on a fresh 10 yr account and was banned on the first day (not overwatch, its a vac ban, and I was only using chams, rcs crosshair, and skinchanger). so, either osiris is detected or the account i bought was cheated on before i bought it.
Edit:
forgot to mention that i was using extreme injector v3.7.3, that could've been what caused it. if it is, any alternatives?

**Comment by 192L** [comment]
forgot to mention: i was using extreme injector v3, that might be what caused it. (if it was, any alternatives?)

**Comment by KernCS** [comment]
99.9% sure extreme injector is detected, make your own:)

**Comment by 192L** [comment]
> 99.9% sure extreme injector is detected, make your own:)

I don't see the point in making my own. I don't have the knowledge to make one, so I would have to follow a tutorial or paste one, which wouldn't change the signature at all. How would I make sure mine isn't detected?

**Comment by mkot2** [comment]
> 
> 
> > 99.9% sure extreme injector is detected, make your own:)
> 
> I don't see the point in making my own. I don't have the knowledge to make one, so I would have to follow a tutorial or paste one, which wouldn't change the signature at all. How would I make sure mine isn't detected?

https://github.com/mdilai/Shtreeba (best one)
https://github.com/danielkrupinski/MemJect
https://github.com/martinjanas/RandoInjector

also themida/vmp should be enough and im pretty sure these arent detected anyways
always use vac bypass (https://github.com/danielkrupinski/VAC-Bypass-Loader)

**Comment by 192L** [comment]
> > > 99.9% sure extreme injector is detected, make your own:)
> > 
> > 
> > I don't see the point in making my own. I don't have the knowledge to make one, so I would have to follow a tutorial or paste one, which wouldn't change the signature at all. How would I make sure mine isn't detected?
> 
> https://github.com/mdilai/Shtreeba (best one)
> https://github.com/danielkrupinski/MemJect
> https://github.com/martinjanas/RandoInjector
> 
> also themida/vmp should be enough and im pretty sure these arent detected anyways
> always use vac bypass (https://github.com/danielkrupinski/VAC-Bypass-Loader)

Should I use Shtreeba or RandoInjector for least detectability?

**Comment by notgoodusename** [comment]
use Shtreeba

**Comment by AsukiiJapan** [comment]
how to make the vac byapsser undetected ?

**Comment by mkot2** [comment]
> 
> 
> how to make the vac byapsser undetected ?

there is nothing to detect it since it disables VAC

**Comment by Zvondaaa** [comment]
> 99.9% sure extreme injector is detected, make your own:)

100% sure

**Comment by debooga** [comment]
i got banned with my fork on 2 accounts with vac bypass and inflame injector

https://steamcommunity.com/id/notdebooger/
https://steamcommunity.com/id/debooger/

**Comment by ArtemSokolovskiy** [comment]
Permanently undetect
