### ISSUE TITLE
No RCS?

### ISSUE THREAD

**Issue by edzio123421** [danielkrupinski/Osiris#2835]
I remember osiris used to have RCS but now I don't see such thing. Was is removed for specific reason?

**Comment by notgoodusename** [comment]
it was removed, now rcs is actived on certain weapons

**Comment by wemanzoz** [comment]
> it was removed, now rcs is actived on certain weapons

such as?

**Comment by notgoodusename** [comment]
> > it was removed, now rcs is actived on certain weapons
> 
> such as?

ak, m4, negev, etc

**Comment by edzio123421** [comment]
> > > it was removed, now rcs is actived on certain weapons
> > 
> > 
> > such as?
> 
> ak, m4, negev, etc

Sorry bro but this is so false. There is no compensation on any weapon at all.

**Comment by notgoodusename** [comment]
> > > > it was removed, now rcs is actived on certain weapons
> > > 
> > > 
> > > such as?
> > 
> > 
> > ak, m4, negev, etc
> 
> Sorry bro but this is so false. There is no compensation on any weapon at all.

there is, but it only works when shooting at players

**Comment by mkot2** [comment]
> 
> 
> > > > it was removed, now rcs is actived on certain weapons
> > > 
> > > 
> > > such as?
> > 
> > 
> > ak, m4, negev, etc
> 
> Sorry bro but this is so false. There is no compensation on any weapon at all.

it always compensates 100%

**Comment by wemanzoz** [comment]
> > 
> > 
> > > > > it was removed, now rcs is actived on certain weapons
> > > > 
> > > > 
> > > > such as?
> > > 
> > > 
> > > ak, m4, negev, etc
> > 
> > Sorry bro but this is so false. There is no compensation on any weapon at all.
> 
> it always compensates 100%

wtf i need to find this xd

**Comment by SquidmarcHD** [comment]
it only controlls the recoil when you are aimbotting people as it is factoring in aimpunch
