### ISSUE TITLE
[bug] please fix this problem

### ISSUE THREAD

**Issue by mina9999** [danielkrupinski/Osiris#2836]
![unknown](https://user-images.githubusercontent.com/28566705/116497820-8050db00-a8bd-11eb-92e8-45337a4a95f8.png)
when i want to build i get this error

**Comment by wemanzoz** [comment]
oof @danielkrupinski

**Comment by mina9999** [comment]
after last update it dosnt work

**Comment by wemanzoz** [comment]
> after last update it dosnt work

ik, lets just wait until dk is back online

**Comment by ImChinaNB** [comment]
make_unique_for_overwrite is added since C++14.. Would a /std:c++latest solve the problem?

**Comment by mina9999** [comment]
![image](https://user-images.githubusercontent.com/28566705/116556093-5970c400-a912-11eb-9b81-e6e9bb4b11b1.png)
new error @danielkrupinski

**Comment by playday3008** [comment]
> `make_unique_for_overwrite` is added since C++20.. Would a /std:c++latest solve the problem? @mina9999

Bruh, just update VS to last version, bcoz `/std:c++latest` presented in vcxproj file, and not needed to set it again
