### ISSUE TITLE
No UI showing up

### ISSUE THREAD

**Issue by SpAnDaNpAtIl** [danielkrupinski/Osiris#2838]
Till yesterday, osiris was working fine with vac bypasser by daniel and csghost v3. 1 as my injector. Today, after injecting, it shows as injected in process but does not do anything in CSGO. Usually , after injection, when i switched tabs, game used to freeze for 2 seconds and then UI appeared. But now no signs of UI and I cant even check if dll was injected. Same for latest csghost v4.

**Comment by mkot2** [comment]
loadlib in 2021 lol
https://github.com/mdilai/Shtreeba

**Comment by SpAnDaNpAtIl** [comment]
I know about Shtreeba bro.. But Csghost is way easier. No build no setup. It detects process ID of csgo and injects. No risk of ban even after a month of raging in compi, DM and casual servers. I guess I have to go with shtreeba now.

**Comment by mkot2** [comment]
> 
> 
> I know about Shtreeba bro.. But Csghost is way easier. No build no setup. It detects process ID of csgo and injects. No risk of ban even after a month of raging in compi, DM and casual servers. I guess I have to go with shtreeba now.

shtreeba:
1. download
2. compile
3. change dll name in config
4. ???
5. profit
