### ISSUE TITLE
Legit Visuals feature (x88's Dead ESP) + Help

### ISSUE THREAD

**Issue by FerrisSandCanyon** [danielkrupinski/Osiris#284]
demo: https://streamable.com/k838x

ESP / Occluded / XQZ only shows when your dead (forgot to demo it) but this one has an override key in case you really need walls.

ps: Im trying to get a name changer working but im going nowhere i tried obtaining the name cvar, doing a call back then setting its value but i know im doing it wrong.

**Comment by l0ccy** [comment]
+++1 code for it ?

**Comment by FerrisSandCanyon** [comment]
There's no specific source code for it but its simply making a Boolean flag for all the visuals that lets you see through walls then you can just change that flag by checking for a key press or if local player is dead.
