### ISSUE TITLE
how can it be injected? give me some advice please

### ISSUE THREAD

**Issue by idimo** [danielkrupinski/Osiris#2840]
I tried this one but he dropped fps to 30 

https://github.com/Felpsz1337/Dll-Injector

**Comment by YeetingWaterbottle** [comment]
Use [csghost](https://www.unknowncheats.me/forum/2872114-post1.html), if the fps drop to 30, then it's not the cheat's problem, you probably capped the fps.

**Comment by Konvikt** [comment]
> Use [csghost](https://www.unknowncheats.me/forum/2872114-post1.html), if the fps drop to 30, then it's not the cheat's problem, you probably capped the fps.

In addition to this, it will say that csghost is "possibly detected" but this is only with FluidAim afaik, I use osiris daily on my main, haven't been detected so far.

**Comment by YeetingWaterbottle** [comment]
> > Use [csghost](https://www.unknowncheats.me/forum/2872114-post1.html), if the fps drop to 30, then it's not the cheat's problem, you probably capped the fps.
> 
> In addition to this, it will say that csghost is "possibly detected" but this is only with FluidAim afaik, I use osiris daily on my main, haven't been detected so far.

I don't recommend that but you do you. If you have ran the VA bypass loader, you should be fine.
