### ISSUE TITLE
[Request]Show hidden cvars in console

### ISSUE THREAD

**Issue by Frouk3** [danielkrupinski/Osiris#2847]
There are so many commands that hidden by VALVE. There are so many cheats that can unlock hidden cvars.

**Comment by SquidmarcHD** [comment]
you can still spoof them with cmdunrestricted just make a input box and a button

**Comment by Frouk3** [comment]
> you can still spoof them with cmdunrestricted just make a input box and a button

lol otc v3 have button to show hidden cvars in console
