### ISSUE TITLE
How to Change IMGUI

### ISSUE THREAD

**Issue by ROCKIv** [danielkrupinski/Osiris#2849]
Hi, im new at  C++, i want to change the IMGUI for osiris, i see people saying "edit GUI, etc" but i dont know what i need to put there, like i need to delete the 2 options "classic, one window" and only put 1 option. I need to replace the actual imgui (https://imgur.com/gallery/SFhcxIg) to this imgui (https://www.youtube.com/watch?v=xofBgnLH6-w) and i dont know how to do it, i want to learn how to do it. Sorry for bad english.

If u want to help me contact me in discord: ROCKITA#9313

**Comment by mkot2** [comment]
> 
> 
> Hi, im new at C++, i want to change the IMGUI for osiris, i see people saying "edit GUI, etc" but i dont know what i need to put there, like i need to delete the 2 options "classic, one window" and only put 1 option. I need to replace the actual imgui (https://imgur.com/gallery/SFhcxIg) to this imgui (https://www.youtube.com/watch?v=xofBgnLH6-w) and i dont know how to do it, i want to learn how to do it. Sorry for bad english.
> 
> If u want to help me contact me in discord: ROCKITA#9313

how old is that version of osiris?

**Comment by ROCKIv** [comment]
2 months (?

**Comment by ArtemSokolovskiy** [comment]
Learn c++
