### ISSUE TITLE
Menu Not Closing After Loading Config

### ISSUE THREAD

**Issue by sollyw** [danielkrupinski/Osiris#285]
After creating and saving a config when I close the game and reload the cheat and load the config I am unable to close the menu by the insert key or at all.

**Comment by JohnRich1372** [comment]
Maybe you accidentally changed the menu key?

**Comment by cojo1989** [comment]
Wait for new config system. You made update and now you need to make new configs

**Comment by NexSqaud** [comment]
@cojo1989 i think problem with accidentally changed menu ley

**Comment by cojo1989** [comment]
For me its doing that when after i make an update. :)

**Comment by EGTLoneWolf** [comment]
config outdated
