### ISSUE TITLE
ARCH LINUX  is there is REAL guide for it ?

### ISSUE THREAD

**Issue by kalashnikov-555** [danielkrupinski/Osiris#2851]
is there is someone able to use the cheat in arch linux i cant compile it i need help and didint find the existing guide useful it gave eror didint work on arch linux and there is AUR package called osiris is it the osiris hack and there is no link to github page on that  arch wiki aur page if its the cheat if i downloadid and compiled whit aur how do i use the oisirs hack on osiris aur anyone can help me .

**Comment by hugohabicht01** [comment]
Just check out the github actions for linux to see how to compile it.
For injecting I personally use this: https://gist.github.com/hugohabicht01/f04ab7e45daedaca34a2e6916be7fa17

**Comment by DOG248** [comment]
Hello @kalashnikov-555, for compile it on **Arch Linux** is a bit different.

**Install dependencies through pacman**
`sudo pacman -S sdl2 cmake `

**Create the build directory**
`mkdir -p build && cd build`
 **Create the build files**
`cmake -D CMAKE_BUILD_TYPE=Release ..`
**Compile it**
`make -j $(nproc --all)`
