### ISSUE TITLE
180 Errors (cant build)

### ISSUE THREAD

**Issue by Deciy** [danielkrupinski/Osiris#2852]
![fiels](https://user-images.githubusercontent.com/63680832/116827975-c2457f80-ab50-11eb-8ff3-1e1c04d2edb0.JPG)
Not sure if its a me problem.

**Comment by wemanzoz** [comment]
wtf is this, how did you get this

**Comment by Rynav** [comment]
compile it as x86 release

**Comment by mkot2** [comment]
how old is your source

**Comment by Deciy** [comment]
> wtf is this, how did you get this

Didnt do fuckin nothin

**Comment by Deciy** [comment]
> how old is your source

Most recent source

**Comment by mkot2** [comment]
are you using vs2019? because this doesnt work in vs2017

**Comment by Deciy** [comment]
> compile it as x86 release
> 
> if still can't, download osiris source again

Tried that.

**Comment by Deciy** [comment]
> are you using vs2019? because this doesnt work in vs2017

Yup i have 2019

**Comment by SquidmarcHD** [comment]
same problem here. i think it isnt initializing const auto's and thats why its failing. it works fine for my friend on the other hand. might actually be vs versions

**Comment by SquidmarcHD** [comment]
ill be trying with vs 17 and see how it goes

**Comment by danielkrupinski** [comment]
Update Visual Studio 2019 to the latest release.

**Comment by SquidmarcHD** [comment]
looks like my current vs is 16.6.2 and the latest one is 16.9.4

**Comment by SquidmarcHD** [comment]
![image](https://user-images.githubusercontent.com/70035086/117203771-b9bea480-adef-11eb-8096-cc19c4238174.png)
we do a little trolling

**Comment by SquidmarcHD** [comment]
can confirm new version works
