### ISSUE TITLE
[UPDATE] New skins

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#2856]
snakebite collection i guess

**Comment by KurastikO** [comment]
New collection or not, Osiris already has the skins available because it finds the textures in the pak01_dir.vpk :)

**Comment by wemanzoz** [comment]
> New collection or not, Osiris already has the skins available because it finds the textures in the pak01_dir.vpk :)

and new update breaks osiris afaik, one of my friends mentioned it
