### ISSUE TITLE
How to inject and HvH????

### ISSUE THREAD

**Issue by phobologicalt** [danielkrupinski/Osiris#2857]
Yo, I wanna start HvH in Cs:go and I dont really wanna pay 20 euros a month for a paid cheat because I dont know if I will like it or not, also could someone link me a HvH config? Thanks.

**Comment by wemanzoz** [comment]
you cant hvh with osiris, bad anti aim, no resolver, and legit aimbot

**Comment by acey1337** [comment]
osiris isn't a hvh cheat, it's meant strictly for legit or closet cheating. i'd suggest you try asking on reddit r/CsgoHacks

**Comment by HowToMakeFaceitAB** [comment]
> Yo, I wanna start HvH in Cs:go and I dont really wanna pay 20 euros a month for a paid cheat because I dont know if I will like it or not, also could someone link me a HvH config? Thanks.

well if you're knew, use a free cheat like otc, learn how shit works, how to play, ect... and after that, go buy Neverlose.cc and dont bother playing with free cheats because you're going to miss a LOT

**Comment by wemanzoz** [comment]
> > Yo, I wanna start HvH in Cs:go and I dont really wanna pay 20 euros a month for a paid cheat because I dont know if I will like it or not, also could someone link me a HvH config? Thanks.
> 
> well if you're knew, use a free cheat like otc, learn how shit works, how to play, ect... and after that, go buy Neverlose.cc and dont bother playing with free cheats because you're going to miss a LOT

buy me NL troll

**Comment by mkot2** [comment]
> 
> 
> > Yo, I wanna start HvH in Cs:go and I dont really wanna pay 20 euros a month for a paid cheat because I dont know if I will like it or not, also could someone link me a HvH config? Thanks.
> 
> well if you're knew, use a free cheat like otc, learn how shit works, how to play, ect... and after that, go buy Neverlose.cc and dont bother playing with free cheats because you're going to miss a LOT

if you want to hvh with osiris you probs dont have money to buy a p2c now gtfo

**Comment by ProjecterN1N3** [comment]
> 
> 
> > > Yo, I wanna start HvH in Cs:go and I dont really wanna pay 20 euros a month for a paid cheat because I dont know if I will like it or not, also could someone link me a HvH config? Thanks.
> > 
> > 
> > well if you're knew, use a free cheat like otc, learn how shit works, how to play, ect... and after that, go buy Neverlose.cc and dont bother playing with free cheats because you're going to miss a LOT
> 
> buy me NL troll

stop begging :trollface:

**Comment by phobologicalt** [comment]
> > Yo, I wanna start HvH in Cs:go and I dont really wanna pay 20 euros a month for a paid cheat because I dont know if I will like it or not, also could someone link me a HvH config? Thanks.
> 
> well if you're knew, use a free cheat like otc, learn how shit works, how to play, ect... and after that, go buy Neverlose.cc and dont bother playing with free cheats because you're going to miss a LOT

where do I get OTCv3 without also getting a rat?

**Comment by acey1337** [comment]
> > > Yo, I wanna start HvH in Cs:go and I dont really wanna pay 20 euros a month for a paid cheat because I dont know if I will like it or not, also could someone link me a HvH config? Thanks.
> > 
> > 
> > well if you're knew, use a free cheat like otc, learn how shit works, how to play, ect... and after that, go buy Neverlose.cc and dont bother playing with free cheats because you're going to miss a LOT
> 
> where do I get OTCv3 without also getting a rat?

i made it a loader for it, you can just use that. the .dll is taken from the official otc server idk why i cant invite rn its not allowing me to but ill link my loader here
https://github.com/acey1337/otc3updated
load vac bypass first and open cs, then click the inject button and otc3 should pop up in ur game

**Comment by flolep2607** [comment]
> > > > Yo, I wanna start HvH in Cs:go and I dont really wanna pay 20 euros a month for a paid cheat because I dont know if I will like it or not, also could someone link me a HvH config? Thanks.
> > > 
> > > 
> > > well if you're knew, use a free cheat like otc, learn how shit works, how to play, ect... and after that, go buy Neverlose.cc and dont bother playing with free cheats because you're going to miss a LOT
> > 
> > 
> > where do I get OTCv3 without also getting a rat?
> 
> i made it a loader for it, you can just use that. the .dll is taken from the official otc server idk why i cant invite rn its not allowing me to but ill link my loader here
> https://github.com/acey1337/otc3updated/releases/download/csgo-otc/SimpleLoader.exe
> load vac bypass first and open cs, then click the inject button and otc3 should pop up in ur game

lol

**Comment by Frouk3** [comment]
> you cant hvh with osiris, bad anti aim, no resolver, and legit aimbot

I play semi rage with osiris vs spinbotter, i hit him in head always(sometimes body) cuz i enabled function "Fix bone matrix" and "Fix animation LOD". I don't know if spinbotter has bad aa or osiris have resolver

**Comment by ArtemSokolovskiy** [comment]
Use rage/hvh multipaste
