### ISSUE TITLE
aimbot

### ISSUE THREAD

**Issue by adriangames147** [danielkrupinski/Osiris#286]
Did also anyone have this "BUG" ?
https://youtu.be/13gp_QyLE14

And I also saw this in console:

CEngineClient::SetViewAngles:  rejecting invalid value [inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [-inf -inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [inf inf -nan(ind)]
CEngineClient::SetViewAngles:  rejecting invalid value [inf -inf -nan(ind)]

**Comment by cojo1989** [comment]
Check your aimbot settings. I think you put some invalid numbers.

**Comment by adriangames147** [comment]
@cojo1989 Okay, I fixed it....I had to make new config
I was been still loading old config
