### ISSUE TITLE
recoil control on pull request is outdated

### ISSUE THREAD

**Issue by kang-kung** [danielkrupinski/Osiris#2871]

**Comment by mkot2** [comment]
which one

**Comment by caiocinel** [comment]
Just update it to a new version, Pull Requests are just templates.

**Comment by wemanzoz** [comment]
that pr is not that good either lol, its snaps

**Comment by mkot2** [comment]
> 
> 
> that pr is not that good either lol, its snaps

which one bro wdym

**Comment by ArtemSokolovskiy** [comment]
cmd->viewangles -= aimPunch

**Comment by caiocinel** [comment]
Native osiris aimbot have recoil control, but haven't configs available.

Em ter., 18 de mai. de 2021 às 07:26, ArtemSokolovskiy <
***@***.***> escreveu:
