### ISSUE TITLE
Gamedata::update FPS drop.

### ISSUE THREAD

**Issue by voidzero-development** [danielkrupinski/Osiris#2874]
The GameData::update function in framstagenotify drops alot of frames and seems very CPU heavy, drops around 100 fps average.

Also what is the use of sorting all the vectors using std::sort, afaik the ESP renders fine without the sorting.

**Comment by danielkrupinski** [comment]
What's your CPU and how many FPS do you have with and without cheat? Are you using **Release** build?

**Comment by voidzero-development** [comment]
CPU: AMD R7 2700X  RAM: 32GB ram GPU: AMD RX5700XT
Tested on latest version compiled as release.
Unhooked: 330FPS
Hooked without gamedata::update: 310FPS
Hooked with gamedata::update: 280FPS

Tested on aim_botz looking at 5 bots without having any features enabled at all.

**Comment by voidzero-development** [comment]
Why is  setupbones being called in gamedata if you can just copy the existing matrix?

**Comment by ArtemSokolovskiy** [comment]
Maybe system issue

**Comment by danielkrupinski** [comment]
I've made some optimizations to GameData module that should improve fps.

**Comment by voidzero-development** [comment]
This does improve FPS, thanks :)

You should consider copying the exists setupbones matrix into the mutex in the future if you feel like you want to improve it further.
