### ISSUE TITLE
Compiling Problem

### ISSUE THREAD

**Issue by iSyncKey** [danielkrupinski/Osiris#2878]
Since the skinchanger updated I cant compile Osiris anymore.
I using Osiris for a while now and never had this problem.
VS2019 cant find std::ranges::lower_bound but the right files are imported. Please help

**Comment by SquidmarcHD** [comment]
are you using the newest vs version?

**Comment by SquidmarcHD** [comment]
16.9.4 should be the newest
/close when you verify that it works

**Comment by iSyncKey** [comment]
Ok, im downloading it rn

**Comment by iSyncKey** [comment]
But anyways, shouldnt it work if im using the right sdk version and the right platform toolset?

**Comment by iSyncKey** [comment]
it was the problem lol
ty
