### ISSUE TITLE
[SUGGESTIONS]

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#288]
Hello Daniel,
I really appreciate your work. This is one of the best open-source cheats out there!

I think you might like new challenges, so here is some ideas that you could use in a new version of the cheat:

- Aimbot: maybe a minimal damage chance, so it would shot if it is "possible" to take damage;
- Grenade prediction: there has been a lot of people asking for this, and I think it would be great;
- Anti-OBS: by hooking Steam overlay (thank you @Shaxzy);
- C4 timer and defuse time check (recommended by @tirziz);
- Config conversion for older versions of the cheat;
- Grenade ESP: when enemy throws a grenade we could be capable to see it;
- Profile changer (rank, level...).

Congratulations for your work and time effort on this!

**Comment by Shaxzy** [comment]
Anti-OBS is possible in internal cheats by hooking steam overlay

**Comment by cojo1989** [comment]
Last 2 points i like it. First one with minimal dmg is useless.

**Comment by tirziz** [comment]
I recommend C4 timer and defuse time check

**Comment by NexSqaud** [comment]
@cojo1989 when you play vs shit rage pasta, hit change and min damage is useful!

**Comment by cojo1989** [comment]
Just put hit everybone and only visible. But to tell you the truth im not into rage... just legit. Its better for Daniel to focus on finishing the legit then maybe if he wants to add light rage features. But only when legit is finished.

**Comment by 4lb3** [comment]
@Shaxzy Nice, Daniel needs to know that!

@cojo1989 No, it isn't useless if you're playing with Only visible unchecked and playing against a bad cheater.

@tirziz I'm going to put this on my post, thank you!

@NexSqaud True!

**Comment by aysx** [comment]
imo the most needed funcs is legit desync + desync resolver

**Comment by 4lb3** [comment]
I've added "config conversion" on my post.

**Comment by cojo1989** [comment]
up for it :)
