### ISSUE TITLE
What is  m_bWaitForNoAttack ? 

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#2880]
what is
 
NETVAR(waitForNoAttack, "CCSPlayer", "m_bWaitForNoAttack", bool)

how does it work ?

any preview?

**Comment by SquidmarcHD** [comment]
would guess waiting to stop attacking

**Comment by dapaster** [comment]
u mean 

if (enemy shooting)
return;

?

**Comment by 3Ld4D** [comment]
it waits for you to release the shoot button. (for semi auto weapons)

**Comment by dapaster** [comment]
thanks !
