### ISSUE TITLE
[SUGGESTION] Adding penetration dot to Osiris.

### ISSUE THREAD

**Issue by wirekuro** [danielkrupinski/Osiris#2882]
Penetration dot is a little white dot in the middle of the crosshair, which turns green if you aim at a wallbangable surface.
I would be very thankful if anyone would make a pull request about it.

**Comment by ArtemSokolovskiy** [comment]
Look for canScan() in aimbot.cpp

**Comment by mkot2** [comment]
> 
> 
> Look for canScan() in aimbot.cpp

doing entire autowall for penetration dot is stupid, just trace ray and check if wallbangable

**Comment by SquidmarcHD** [comment]
> > Look for canScan() in aimbot.cpp
> 
> doing entire autowall for penetration dot is stupid, just trace ray and check if wallbangable

altough you can add autowall damage 
![image](https://user-images.githubusercontent.com/70035086/118696988-233aac00-b80f-11eb-9be3-c0c1ecdb7651.png)

**Comment by wirekuro** [comment]
> Look for canScan() in aimbot.cpp

Im not good at programming, that's why I need someone else to add this function.

**Comment by SquidmarcHD** [comment]
then learn how to write c++

**Comment by wirekuro** [comment]
> then learn how to write c++

![Uploading ef851516d068ab140a519fc273cda053.jpg…]()
