### ISSUE TITLE
One of the most popular CS:GO cheats just got hit by a full VAC detection.

### ISSUE THREAD

**Issue by WhatsupDanger** [danielkrupinski/Osiris#2883]
It's all over the news that the Most Popular Free Cheat named RatPoison got full detected by VAC and a VAC wave is coming to whoever used this cheat in the past 2-3 months.
The developers of the hack informed users that Valve had recently updated their anti-cheat system without any announcement, and that it was now capable of detecting and VAC banning those who had used it before.

Vac Updates according to the cheat developers:
In the last ~240MB update two modules were introduced 

Module 1: Consists of a Process Memory handle listener which would flag all calls to ReadProcessMemory/WriteProcessMemory. rendering externals that aren't utilizing thread hijacking detected.

Module 2: This was referred to as an integrity check which will utilize a variety of assorted hashing algorithms implemented in C++. It would further run a full S&I check on the currently running game platform, be it Half life 2, CSGO or Source. To prevent false positives it runs the checks on the modules loaded as well

----------------------------------------------------------------------------------------------------------------------------------------------
People also reported that their main account also got banned on which they never cheated on. Reports says this happened because Steam now tracks your alt accounts based on directory structure. It happens through the "userdata" folder in your Steam installation directory.
Hackers have already come up with tools to counteract this: https://pastebin.com/CP8V94MB & https://pastebin.com/KBCAf2Xt

News Source:
https://www.reddit.com/r/csgo/comments/nczfb7/one_of_the_most_popular_csgo_cheats_just_got_hit/

https://www.dexerto.com/csgo/valve-finally-cracking-down-on-one-of-csgos-most-common-cheats-1574686/

https://www.talkesport.com/news/csgo-vac-wave-wipes-cheaters-with-new-detections/

Now the question remains should we continue using osiris like we used to or wait till this new module thing is reverse engineered/bypassed? @danielkrupinski

**Comment by 3Ld4D** [comment]
yes they improved vac and they are logging alot of shit, also you get flagged and sent to overwatch.

**Comment by danielkrupinski** [comment]
VAC couldn't have got a 240 MB modules update because all its modules are less than 100kB. I don't know what reading process memory has to do with thread highjacking.
