### ISSUE TITLE
Fail to inject image

### ISSUE THREAD

**Issue by matianhe3** [danielkrupinski/Osiris#2887]
IDE: VS 2019 preview latest
Injector : Xenos

![11621387458_ pic](https://user-images.githubusercontent.com/24929062/118743103-46ec0980-b884-11eb-8fdc-9e478c4a35e3.jpg)

**Comment by matianhe3** [comment]
I am try Xenos Advance by other issues.

**Comment by SquidmarcHD** [comment]
is it a load library injector?
did you bypass the loadlibrary restriction?
do you have admin priviliges?

**Comment by matianhe3** [comment]
![image](https://user-images.githubusercontent.com/24929062/118811339-7845f300-b8df-11eb-813e-1f658477e9e9.png)
![image](https://user-images.githubusercontent.com/24929062/118811365-809e2e00-b8df-11eb-9579-79b2bb90daa8.png)

**Comment by SquidmarcHD** [comment]
no, loadlibrary is a bad really easily detectable way of injection. it doesnt inject because blackbone doesnt like osiris totally forgot about that

**Comment by king1919djdj** [comment]
well you may be right but isn't load lib an easy and effective injection method since the 3rd party application restriction update of csgo ?

**Comment by matianhe3** [comment]
> most probably you need to change the injection type to load lib or get a new injectors that supports load lib method

which  injectors can use?

**Comment by king1919djdj** [comment]
CS Ghost V4.0 is the one i use 
comes with a vac bypass
