### ISSUE TITLE
how can i fix this?

### ISSUE THREAD

**Issue by Flowsux69** [danielkrupinski/Osiris#2889]
idk why but this giving me error
i tried to paste it from here -> https://github.com/danielkrupinski/Osiris/pull/2520
this is the error 
![Desktop Screenshot 2021 05 20 - 11 46 34 39](https://user-images.githubusercontent.com/82530290/118916454-95bba100-b961-11eb-9117-ab4d15c8a84c.png)
![Desktop Screenshot 2021 05 20 - 11 46 44 42](https://user-images.githubusercontent.com/82530290/118916459-96ecce00-b961-11eb-8bbe-76c9faa03b3f.png)

**Comment by SquidmarcHD** [comment]
how about you declare fake prime first in misc.cpp

**Comment by SquidmarcHD** [comment]
also radianst to degrees is in Helpers now

**Comment by notgoodusename** [comment]
replace radiansToDegrees with Helpers::rad2deg

**Comment by Flowsux69** [comment]
@notgoodusename i like ur works dude<3

**Comment by Flowsux69** [comment]
how can you fix this one
![Desktop Screenshot 2021 05 20 - 19 28 41 52](https://user-images.githubusercontent.com/82530290/118971230-bdcaf480-b9a1-11eb-8a39-f777b7d8f2e6.png)

**Comment by Flowsux69** [comment]
how can you fix this one
![Desktop Screenshot 2021 05 20 - 19 28 41 52](https://user-images.githubusercontent.com/82530290/118971324-dcc98680-b9a1-11eb-9c47-1aada1fac170.png)

**Comment by Flowsux69** [comment]
how can you fix this one
![Desktop Screenshot 2021 05 20 - 19 36 56 00](https://user-images.githubusercontent.com/82530290/118972117-c53ecd80-b9a2-11eb-9ad5-4b26bb35cd8d.png)

**Comment by mkot2** [comment]
`Vector angles{ Helpers::rad2deg(atan2f(-delta.z, std::hypotf(delta.x, delta.y))), Helpers::rad2deg(atan2f(delta.y, delta.x)), 0.f };`

**Comment by mkot2** [comment]
or better yet, make the function just this
`return ((destination - source).toAngle()).normalize();`
and even better, use the aimbot one
`Vector angles = Misc::calculateRelativeAngle(localPlayer->origin(), target->origin());`

`Vector angles = Aimbot::calculateRelativeAngle(localPlayer->origin(), target->origin(), {});`

**Comment by Flowsux69** [comment]
YOOOOOOOOOOO TY SO MUCH @mkot2
