### ISSUE TITLE
About VMT hook

### ISSUE THREAD

**Issue by jackKiZhu** [danielkrupinski/Osiris#2890]
After I changed my hook to VMT hook, my account was blocked by VAC in a few days. Do you think VMT hook has been detected?

**Comment by 3Ld4D** [comment]
yes it's detected for 2 years now. I don't see the point of not using `MinHook` or at least `VMTSwap` which has less chances of being detected.

**Comment by jackKiZhu** [comment]
> yes it's detected for 2 years now. I don't see the point of not using or at least which has less chances of being detected.`MinHook``VMTSwap`

If I use VAC bypass, will VMT hook be detected?

**Comment by SquidmarcHD** [comment]
no, vac bypass completely disables vac

**Comment by mkot2** [comment]
> 
> 
> > yes it's detected for 2 years now. I don't see the point of not using or at least which has less chances of being detected.`` MinHook``VMTSwap ``
> 
> If I use VAC bypass, will VMT hook be detected?

vac bypass disables vac but why do you even care, you shouldnt use vmt hook

**Comment by kang-kung** [comment]
how do you change the hooking method

**Comment by SquidmarcHD** [comment]
hooks.h change it to hooktype
