### ISSUE TITLE
how can i change this? HELP

### ISSUE THREAD

**Issue by Flowsux69** [danielkrupinski/Osiris#2892]
how can i change this blockbot into head standind runboost bot

**Comment by Flowsux69** [comment]
void Misc::playerBlocker(UserCmd* cmd) noexcept
{
    if (config->misc.playerBlocker) {
        float bestdist = 1.f;
        int index = -1;
        for (int i = 1; i <= interfaces->engine->getMaxClients(); i++) {
            auto entity = interfaces->entityList->getEntity(i);

            if (!entity)
                continue;

            if (!entity->isAlive() || entity->isDormant() || entity == localPlayer.get() || !GetAsyncKeyState(config->misc.playerBlockerKey))
                continue;

            float dist = distance(localPlayer->origin(), entity->origin());
            if (dist < bestdist)
            {
                bestdist = dist;
                index = i;
            }
        }

        if (index == -1)
            return;

        auto target = interfaces->entityList->getEntity(index);

        if (!target)
            return;

        Vector angles = Misc::calculateRelativeAngle(localPlayer->origin(), target->origin());

        angles.y -= localPlayer->eyeAngles().y;
        angles.normalize();
        angles.y = std::clamp(angles.y, -180.f, 180.f);

        if (angles.y < 0.0f)
            cmd->sidemove = 450.f;
        else if (angles.y > 0.0f)
            cmd->sidemove = -450.f;;

    }
}

**Comment by Flowsux69** [comment]
![Desktop Screenshot 2021 05 21 - 11 41 43 33](https://user-images.githubusercontent.com/82530290/119078861-97509c00-ba29-11eb-9d5d-a18f48042228.png)

**Comment by mkot2** [comment]
try to use brain

**Comment by Flowsux69** [comment]
> try to use brain

i dont have one :(
 at least i tried like 20 different times

**Comment by Flowsux69** [comment]
angles.X -= localPlayer->eyeAngles().X;
 
    angles.X = std::clamp(angles.X, -180.f, 180.f);

    if (angles.X < 0.0f)
        cmd->forwardmove = 450.f;
    else if (angles.X > 0.0f)
        cmd->forwardmove = -450.f;;

**Comment by Flowsux69** [comment]
i tried that one

**Comment by mkot2** [comment]
you still have to compare yaw not pitch

**Comment by Flow512** [comment]
Agles

**Comment by Flow512** [comment]
Angles.z?

**Comment by mkot2** [comment]
> 
> 
> Angles.z?

    auto toAngle() const noexcept
    {
        return Vector{ Helpers::rad2deg(std::atan2(-z, std::hypot(x, y))),
                       Helpers::rad2deg(std::atan2(y, x)),
                       0.0f };
    }

there is no z in an angle

**Comment by Flow512** [comment]
@Flowsux69 I tried this this kinda works

if (angles.y < 0.0f)
        cmd->sidemove = 450.f;
        cmd->forwardmove = 450.f;
    else if (angles.y > 0.0f)
        cmd->sidemove = -450.f;
        cmd->forwardmove = -450.f;

**Comment by Flowsux69** [comment]
it dont

**Comment by Flowsux69** [comment]
@mkot2 so i should get localplayer location?

**Comment by Flowsux69** [comment]
i dont get it

**Comment by Flowsux69** [comment]
should i use my eyeangles or use other stuff?
