### ISSUE TITLE
400ms backtrack

### ISSUE THREAD

**Issue by wirekuro** [danielkrupinski/Osiris#2894]
I'm very excited about adding 400ms backtrack to Osiris. I used #1922 before but it's outdated already. Would you mind adding 400ms backtrack to Osiris? @danielkrupinski

**Comment by mkot2** [comment]
i have it in my paste and it still works, the config stuff is in Backtrack.cpp now tho

**Comment by wirekuro** [comment]
> i have it in my paste and it still works, the config stuff is in Backtrack.cpp now tho

Can you help me please? wirekurosastak#3796

**Comment by BBamsterdam** [comment]
how do i get this in my paste
