### ISSUE TITLE
Unchecked Vizible Only and still doesnt work (Linux)

### ISSUE THREAD

**Issue by ReShout876** [danielkrupinski/Osiris#2895]
So, I go to aimbot thab, uncheck the vizible only box, doesnt shoot if someone is behind the wall. How do I "fix" this.

**Comment by mkot2** [comment]
autowall doesnt work on linux
https://github.com/danielkrupinski/Osiris/pull/2518 fixes this so just put it in there

**Comment by DumitruStepa** [comment]
> autowall doesnt work on linux
> #2518 fixes this so just put it in there

and what do i do now?
