### ISSUE TITLE
[REQUEST]Make semirage

### ISSUE THREAD

**Issue by Frouk3** [danielkrupinski/Osiris#2898]
Can someone make semirage tab? Semirage include fov,silent,aimlock,hitgroup,autoshot and resolver. Osiris good for semirage

**Comment by rosesware** [comment]
Code yourself a resolver and you have a "semirage tab" you want.

**Comment by Frouk3** [comment]
I tried but it won't compile

**Comment by wemanzoz** [comment]
use notgoodusername's osiris with stuff
