### ISSUE TITLE
[SUGGESTION] Add cases in inventory changer?

### ISSUE THREAD

**Issue by Qoft** [danielkrupinski/Osiris#2905]
It would honestly be pretty cool if it would be possible to add cases to your inventory and open them in lobby/in game. other people wouldnt be able to see it but its client sided. :)

**Comment by wemanzoz** [comment]
+rep

**Comment by Kikinth** [comment]
I would really like that. 
+1

**Comment by SquidmarcHD** [comment]
search for # in inventorychanger.cpp and add #CSGO_Type_WeaponCase and #CSGO_Tool_WeaponCase_KeyTag to the other ones

**Comment by Xonn1com** [comment]
> 
> 
> search for # in inventorychanger.cpp and add #CSGO_Type_WeaponCase and #CSGO_Tool_WeaponCase_KeyTag to the other ones

Is it working? Have you tested it?

**Comment by SquidmarcHD** [comment]
yes. you would still need to add the function for the opening tho. atleast you can click on open and the animation plays

**Comment by danielkrupinski** [comment]
You can now open cases (86e1c5ccf6606e26d88fc7d5c4ce4faeb144603b).
