### ISSUE TITLE
[BUG] Inv changer tab is so small at theme 2 

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#2906]
[link, tixte](https://doing-something.with-your.mom/kp3d1i3v29a)

**Comment by linuxer9** [comment]
the window auto resizes depending on the dimensions of its content
you could remove this window flag to enable the resize button
`ImGuiWindowFlags_NoResize`
or you can add the whole content of this tab in ImGui::BeginChildFrame and add a fixed width and height to it.

**Comment by wemanzoz** [comment]
> ~the window auto resizes depending on the dimensions of its content you could remove this window flag to enable the resize button `ImGuiWindowFlags_NoResize` or you can add the whole content of this tab in ImGui::BeginChildFrame and add a fixed width and height to it.~
> edit: sorry my bad, didn't know about inventory changer branch

eh ill do the no resize thing
