### ISSUE TITLE
[BUG] can't findpattern with present and reset

### ISSUE THREAD

**Issue by InnovationLou** [danielkrupinski/Osiris#2907]
I think this is not a problem caused by the game update, I don’t know if it’s a problem with my device.
![image](https://user-images.githubusercontent.com/20527528/119477735-cf394580-bd81-11eb-835d-333a26904b12.png)
![image](https://user-images.githubusercontent.com/20527528/119477757-d4969000-bd81-11eb-8fea-f8ed7533a2bc.png)i

**Comment by Svenstihl2** [comment]
Hello I have exactly the same: / Google was no help either ..

**Comment by dapaster** [comment]
same here, waiting for the Captain ..

**Comment by dapaster** [comment]
something wrong with Memory.h

**Comment by InnovationLou** [comment]
yesterday game updated,It does need to be updated patterns in Memory.cpp .But how to locate origin present function in x32dbg and how game really calls,I have no ideas

**Comment by wemanzoz** [comment]
odd, osiris works for me

**Comment by wemanzoz** [comment]
lemme try in a few

**Comment by dapaster** [comment]
eedf05d

this one fix mine

**Comment by Svenstihl2** [comment]
@dapaster  Can you send me a working file?

**Comment by InnovationLou** [comment]
@dapaster I understand this algorithm you mentioned in [https://github.com/danielkrupinski/Osiris/commit/eedf05da2eeaac1d010b9f3a5fff8bf89dcb7823](url)
but I tried to use string matching scan by x64dbg and did not return results.

**Comment by ClaudiuHKS** [comment]
Hello.

CPU `i7 4790K` / OS Version `10.0.21387` = NOT WORKING
CPU `i5 8250U` / OS Version `10.0.19042` = WORKING

It seems that it has nothing to do with the algorithm and stuff.
Maybe it works on Laptops only, no idea.

@danielkrupinski :(

**Comment by ClaudiuHKS** [comment]
LOL, it works if you opt out of Steam BETA. From Steam settings.

**Comment by InnovationLou** [comment]
@ClaudiuHKS solved! thx a lot.

**Comment by danielkrupinski** [comment]
I've added support for Steam Beta (e3d8f1d60e186c5c6dc06044e4e8973700b80e8b).
