### ISSUE TITLE
Headshot sound remove

### ISSUE THREAD

**Issue by AvelineStack** [danielkrupinski/Osiris#291]
Hi all,

Is it possible to remove or replace the headshot sound inside the game in Osiris' way?

The headshot sound is too loud and it causes ear ringing and hearing impairment, and there is no suitable way to avoid that.

Hope one day I can learn to write C++ to contribue this project.

Thank you.

**Comment by bruteforcehacker** [comment]
You can change the game sound files

**Comment by AvelineStack** [comment]
> You can change the game sound files

I know, but if .vpk file is changed, all community servers will not allow u to play.

**Comment by tirziz** [comment]
Also I want to remove all weapon sound, Its way too loud,

**Comment by designer1337** [comment]
Hook emit sound and mute needed sound.

**Comment by danielkrupinski** [comment]
Added headshot & weapon sounds volume sliders.

**Comment by AvelineStack** [comment]
Thank you for your great work!

It seems the sounds volume sliders are controlling the headshot sound when I shot them, but not the sound when I get headshot.

**Comment by danielkrupinski** [comment]
Then change volume of local player headshot sound.
