### ISSUE TITLE
[ERRORS] MANY ERRORS!

### ISSUE THREAD

**Issue by TacklerGamers** [danielkrupinski/Osiris#2910]
Guys I am getting so many errors when I open .sln file I set my properties to just Multi byte character set and when I compile I get 100+ errors please I need help

**Comment by linuxer9** [comment]
what errors?
can you post them?

**Comment by mdilai** [comment]
Anybody asked you to change any options without understanding what them means?

**Comment by mkot2** [comment]
> 
> 
> Guys I am getting so many errors when I open .sln file I set my properties to just Multi byte character set and when I compile I get 100+ errors please I need help

why do you need to do that

**Comment by TacklerGamers** [comment]
> Anybody asked you to change any options without understanding what them means?

well with the unicode character set it was still wasn't working

**Comment by TacklerGamers** [comment]
![image](https://user-images.githubusercontent.com/49683529/120154920-c7f2bb80-c209-11eb-982c-fcc32107de0f.png)

This is the error

**Comment by r3s1l13nt** [comment]
> ![image](https://user-images.githubusercontent.com/49683529/120154920-c7f2bb80-c209-11eb-982c-fcc32107de0f.png)
> 
> This is the error

Brother moment
Are you sure you have all sdk and cpp files installed ?...
