### ISSUE TITLE
[SUGGESTION] Can you make it easier to navigate the inventory changer?

### ISSUE THREAD

**Issue by KurastikO** [danielkrupinski/Osiris#2911]
The current menu makes it hard for a person to navigate the changer, can you at least make the icons a lot bigger?

_PS: please consider the size of the menu to be bigger or smaller :)_

**Comment by KurastikO** [comment]
ALSO MAKE IT POSSIBLE TO CHANGE THE SEED OF THE GUNSSSSSSSSSSSSSS

**Comment by danielkrupinski** [comment]
1. Icons can be enlarged when horeved with mouse.
2. You can change seed by editing the config file.

**Comment by wemanzoz** [comment]
@danielkrupinski add a feature to delete stuff that you added before, preview of items that you added (lists of items that we are going to add).
