### ISSUE TITLE
[Inventory Changer] Weapons don't change correctly

### ISSUE THREAD

**Issue by Dr4iv3rNope** [danielkrupinski/Osiris#2912]
Weapons don't change correctly when using inventory changer

# Example:
Without using inventory changer, i'm using M4A4.
If i'm using inventory changer and choose M4A1-S skin, in game it will use M4A4 with M4A1-S skin.
I think it will be same issue with Deagle/Revolver, P2000/USP-S and etc.

# Screenshots:
[Inventory: without changer](https://puu.sh/HJQeH/ecd93abf58.png)
[Inventory: with changer](https://puu.sh/HJQfF/c908aaa1b7.png)
[In game (valve DM server)](https://puu.sh/HJQgl/364cd971bd.png)

**Comment by danielkrupinski** [comment]
You have to equip default M4A1-S first, then equip the one from inventory changer.

**Comment by SquidmarcHD** [comment]
@danielkrupinski why cant we just switch between the two. many people prefer the old skinchanger

**Comment by Dr4iv3rNope** [comment]
> You have to equip default M4A1-S first, then equip the one from inventory changer.

I have already done that, but this is annoying.
Why can't it just automatically equip the weapon?

**Comment by danielkrupinski** [comment]
@SquidmarcHD You can use 60f0a327ba2c55cd3c4d8ae81e37d03adb800a8c
