### ISSUE TITLE
not injecting with debug

### ISSUE THREAD

**Issue by techzin** [danielkrupinski/Osiris#2914]
for some reason still unknown, I cannot inject with any injector when in Debug x86, only Release X86, which can hinder the search for errors.

**Comment by mdilai** [comment]
Use LoadLibrary type injector with debug builds. And dont forget -insecure launch option for CSGO or almost instant VAC.

**Comment by techzin** [comment]
GH Injector, i've tryed 4 injectors methods, but not working, i will try
