### ISSUE TITLE
just wanted to flex on not crate opening having osiris user

### ISSUE THREAD

**Issue by SquidmarcHD** [danielkrupinski/Osiris#2916]
![Unbenannt](https://user-images.githubusercontent.com/70035086/119724441-033e6480-be6f-11eb-823e-279fd0d2622e.PNG)

**Comment by Scui1** [comment]
cringe flexing with something that's open source. Imagine having no 3d preview for skins/stickers

**Comment by wemanzoz** [comment]
why menu so sexy
