### ISSUE TITLE
[ISSUE] Gloves doesnt change 

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#2917]
If you use a glove skin on ct side and you applied another different one on tside. it will just turn pitch black until you press "force reload". any way to do this without pressing force reload?

**Comment by SquidmarcHD** [comment]
call force reload on match start in event listener

**Comment by wemanzoz** [comment]
> call force reload on match start in event listener
> 

hmmm..... ill see what i can do since im no coder lol

**Comment by wemanzoz** [comment]
> call force reload on match start in event listener

can you send me the code?

**Comment by wemanzoz** [comment]
or @danielkrupinski pls fix
