### ISSUE TITLE
How can i make skinchanger use ct knife on t side?

### ISSUE THREAD

**Issue by cmd51** [danielkrupinski/Osiris#2919]
help

**Comment by SquidmarcHD** [comment]
force the equip on t

**Comment by SquidmarcHD** [comment]
or just add it to the gameitems in initialize kits

**Comment by SquidmarcHD** [comment]
change this
```
        if (itemTypeName == "#CSGO_Type_Knife" && item->getRarity() == 6) {
            if (const auto image = item->getInventoryImage()) {
                skins.emplace_back(0, item->getWeaponId());
                gameItems.emplace_back(Type::Skin, 6, skins.size() - 1, interfaces->localize->findSafe(item->getItemBaseName()), image);
            }
        }
```
to this
        if (itemTypeName == "#CSGO_Type_Knife") {
            if (const auto image = item->getInventoryImage()) {
                skins.emplace_back(0, item->getWeaponId());
                gameItems.emplace_back(Type::Skin, 6, skins.size() - 1, interfaces->localize->findSafe(item->getItemBaseName()), image);
            }
        }

**Comment by SquidmarcHD** [comment]
![Uploading Unbenannt.PNG…]()

**Comment by SquidmarcHD** [comment]
![Unbenannt](https://user-images.githubusercontent.com/70035086/119796945-18041200-beda-11eb-9e09-6de76b495712.PNG)

**Comment by SquidmarcHD** [comment]
also remove the check for the equip

**Comment by cmd51** [comment]
Thanks ❤️
