### ISSUE TITLE
[Suggestion] Add ESP/Glow on key

### ISSUE THREAD

**Issue by chovss** [danielkrupinski/Osiris#292]

**Comment by danielkrupinski** [comment]
Why would it be useful?

**Comment by cojo1989** [comment]
Maybe sometimes you want to be legit. Its just easy way to have that. For example i use it :)

**Comment by idkplayer** [comment]
is not it better to add a lua script and players would do it themselves?

**Comment by cojo1989** [comment]
And if they dont know how to make lua?

**Comment by danielkrupinski** [comment]
Added
