### ISSUE TITLE
AddFontFromMemoryCompressedTTF Are Crashing.

### ISSUE THREAD

**Issue by techzin** [danielkrupinski/Osiris#2921]
I've been trying to load fonts directly from memory using AddFontFromMemoryCompressedTTF (), and I haven't been successful, is anyone getting it?

my Code: 
fonts.test1 = io.Fonts->AddFontFromMemoryCompressedTTF(BurBank_bold_compressed_data, BurBank_bold_compressed_size, 20.0f, NULL, io.Fonts->GetGlyphRangesCyrillic());

I remember well that a few months ago it was working, I believe that @danielkrupinski  updated his ImGui, and so something changed.

**Comment by nieatty** [comment]
You need to pass in an `ImFontConfig` with `FontDataOwnedByAtlas` set to `false`.

```cpp
ImFontConfig config;
config.FontDataOwnedByAtlas = false;
fonts->whateverFont = io.Fonts->AddFontFromMemoryCompressedTTF(
    compressed_data, 
    compressed_size,
    20.0f, &config, 
    io.Fonts->GetGlyphRangesCyrillic()
);
```

**Comment by techzin** [comment]
Thanks :)
