### ISSUE TITLE
[Do Not Reply]

### ISSUE THREAD

**Issue by 0a736b85** [danielkrupinski/Osiris#2923]
![4](https://user-images.githubusercontent.com/68378883/120021707-0166d380-c01e-11eb-92a0-77bc7c079cd7.PNG)
![8](https://user-images.githubusercontent.com/68378883/120021753-0f1c5900-c01e-11eb-955c-03df2ba419ea.png)
![1](https://user-images.githubusercontent.com/68378883/120021813-21969280-c01e-11eb-8eed-e55bea6a9ff4.PNG)
![5](https://user-images.githubusercontent.com/68378883/120021857-2f4c1800-c01e-11eb-9b5f-213afcccd003.PNG)
![7](https://user-images.githubusercontent.com/68378883/120021903-412dbb00-c01e-11eb-9970-642dcebf4e84.PNG)
![6](https://user-images.githubusercontent.com/68378883/120021929-48ed5f80-c01e-11eb-8d5f-a31546a31339.PNG)
![2](https://user-images.githubusercontent.com/68378883/120021981-56a2e500-c01e-11eb-901d-35e46b0eb3d9.PNG)
![10](https://user-images.githubusercontent.com/68378883/120022026-691d1e80-c01e-11eb-842a-5d56e26ec309.PNG)
![9](https://user-images.githubusercontent.com/68378883/120022064-73d7b380-c01e-11eb-88eb-ba072457ba93.png)

**Comment by SquidmarcHD** [comment]
im in the screenshot 😁

**Comment by wemanzoz** [comment]
thats a nice menu

**Comment by xpossed-you** [comment]
man really upset about a free cheat

**Comment by SquidmarcHD** [comment]
> thats a nice menu

thanks im currently trying to make an even better one

**Comment by SquidmarcHD** [comment]
![Unbenannt](https://user-images.githubusercontent.com/70035086/120079931-a2a16880-c0b6-11eb-82c6-43e793fc8987.PNG)

**Comment by Scui1** [comment]
What the fuck is this? You mad huh 🤣

**Comment by SquidmarcHD** [comment]
looks like youre the mad one here

**Comment by mdilai** [comment]
Osiris is the greatest code i've ever seen, it was a really pleasure to write my functions top on it. I'm really shocked of this greedy asshole. Long live Daniel 😄

**Comment by wemanzoz** [comment]
@SquidmarcHD leak source when? 😳

**Comment by wemanzoz** [comment]
jk jk

**Comment by 0a736b85** [comment]
![download](https://user-images.githubusercontent.com/68378883/120107935-89bbb480-c195-11eb-8dc2-c80be12f988f.jpg)
![9](https://user-images.githubusercontent.com/68378883/120107892-5711bc00-c195-11eb-9d0e-b50e20e9df97.png)

**Comment by SquidmarcHD** [comment]
lmao he complains about a cheat which he doesnt even use

**Comment by SquidmarcHD** [comment]
![Unbenannt](https://user-images.githubusercontent.com/70035086/120117715-d354d100-c18e-11eb-9c73-7508c285be61.PNG)
hmmmmmmmmmm

**Comment by ny-4** [comment]
@SquidmarcHD Boy howdy is that my shitty pasta particle.js ripoff from uc ??? (the triangle mesh background on the menu) 
I didn't expect anybody to use that lmfao.

**Comment by SquidmarcHD** [comment]
> @SquidmarcHD Boy howdy is that my shitty pasta particle.js ripoff from uc ??? (the triangle mesh background on the menu)
> I didn't expect anybody to use that lmfao.

no.... i coded it myself by absolutely overenginnering and underthinking tge absolute shit out of it xd. sorry i didnt use ur code

**Comment by ny-4** [comment]
Hahahah no worries man, I was hoping it wasn't my code anyways, It was
certified hot garbage. 👌
