### ISSUE TITLE
Question about hooking

### ISSUE THREAD

**Issue by ic3dm4ng0** [danielkrupinski/Osiris#2925]
On the README file, it says Osiris using trampoline and Vmt hooking. Is there a way to make it EXCLUSIVLY use trampoline hooking, as Vmt hooking is very detected by VAC.

**Comment by 3Ld4D** [comment]
it uses MinHook (trampoline) by default.

**Comment by ic3dm4ng0** [comment]
> it uses MinHook (trampoline) by default.

Would that mean it would not be detected for it's hooking method? And would only be detected for things like signature being sus?

**Comment by SquidmarcHD** [comment]
it doesnt use vmt if you dont define it in hooks
