### ISSUE TITLE
[Linux - Manjaro] Built and Injected succesfully, yet cant see the UI after pressing  'Insert'

### ISSUE THREAD

**Issue by juanjoayala01** [danielkrupinski/Osiris#2937]
![image](https://user-images.githubusercontent.com/42329001/120094359-e2377700-c0ed-11eb-8ef1-cfda98880655.png)

For that im using this injector: https://gist.github.com/hugohabicht01/f04ab7e45daedaca34a2e6916be7fa17 (thanks Hugo btw)

Basically that, i think i did everything correctly, mainly because the error alerts were none, but still i cant see the cheat UI :(

**Comment by deboogerxyz** [comment]
gdb binary in Arch-based distros is known to have some issues. Many GNU/Linux cheats come with working gdb binaries (see gamesneeze or cathook).

**Comment by juanjoayala01** [comment]
> gdb binary in Arch-based distros is known to have some issues. Many GNU/Linux cheats come with working gdb binaries (see gamesneeze or cathook).

So no Osiris for me? ou
Guess im gonna try those you mentioned. Thanks for the answer!

**Comment by juanjoayala01** [comment]
btw, does someone knows of any linux distro good for programming and compatible with this gbd binary library of Osiris?

**Comment by juanjoayala01** [comment]
nvm it works now, i had CSGO installed in an external drive. I could run it, but not load .so files into it hehe

**Comment by deboogerxyz** [comment]
> btw, does someone knows of any linux distro good for programming and compatible with this gnu library of Osiris?
> (before i close the issue)

artix, gentoo
