### ISSUE TITLE
Unable to use to m4a1-s and so on...

### ISSUE THREAD

**Issue by Kikinth** [danielkrupinski/Osiris#2946]
Don't know if this is just my issue or not but when I use the inventory changer and want to equip CZ, M4A1-S or MP5-SD, I still have to play with M4A4... but just with the skin of M4A1-S. For example, when I equip M4A1-S Printstream, in the game I still have M4A4 with bugged Printstream skin.

**Comment by blackMasterLord** [comment]
equipt default weapon first
and then equip skin

**Comment by Liam5750** [comment]
Yes, as blackMasterLord said it

**Comment by Kikinth** [comment]
Thank you much. <3
