### ISSUE TITLE
Im trying to add fast stop to a older version of osiris, but get error code C2737

### ISSUE THREAD

**Issue by zoominh0** [danielkrupinski/Osiris#2947]
I'm trying to add faststop #2039 to osiris with standalone rcs from pull request #2135, but after I add all the lines of code and I try to build the solution, I get a error from Config.cpp "C2737 'dummy': const object must be initialized" any help would be great. 
![capture](https://user-images.githubusercontent.com/75226968/120316180-6bf96700-c2dd-11eb-97c0-8167b775cc17.PNG)

**Comment by dapaster** [comment]
remove that line maybe?

**Comment by wemanzoz** [comment]
i must warn you that the rcs on that pull is dogshit (snappy af)

**Comment by SquidmarcHD** [comment]
you dont even need that line

**Comment by zoominh0** [comment]
> i must warn you that the rcs on that pull is dogshit (snappy af)
Then which one should I use?

**Comment by zoominh0** [comment]
> you dont even need that line/use the same syntax as the other functions

It was actually a problem with the whole build, I copied the code for the rcs and pasted it on the official osiris build, and now it works fine, the only thing that doesnt work is the random rcs option, when its enabled the mouse has a seizure everytime you try to shoot. Anyways thank you for trying to help

**Comment by zoominh0** [comment]
> > i must warn you that the rcs on that pull is dogshit (snappy af)
Then which one do you suggest I use?

**Comment by PlinBlin** [comment]
just add {}, const Config::Misc dummy{};
