### ISSUE TITLE
Failed to inject image...   ... Error code 0xc0000135

### ISSUE THREAD

**Issue by KawaiiWolfy** [danielkrupinski/Osiris#2953]
(my main language is german so i use Google translate.)

I followed the steps exactly and Visual studio already reported that Osiris.dll is not a valid win32 application

then in my injector comes the message failed to inject image. my injektor is Xenos64
![Osiris dll fehler](https://user-images.githubusercontent.com/85310007/120690539-a31a7480-c4a5-11eb-918e-9b80ba75dc7b.png)

**Comment by alexezz21** [comment]
You need to use Xenos32 because is on x32 :clown_face:

**Comment by KawaiiWolfy** [comment]
im so dumb yeah.... but i dont need it anymore. my pc freeze any time if i try to start Csgo... without cheat or anything. that piece of shit goes straight in the trash
