### ISSUE TITLE
cant inject "failed to find pattern #22"

### ISSUE THREAD

**Issue by EncryptedAqua** [danielkrupinski/Osiris#2955]
whenever I try to inject I get this error message accompanied by csgo crashing  
![image](https://user-images.githubusercontent.com/85323149/120730468-27212c00-c4a7-11eb-8034-a932f15828c9.png)

**Comment by mkot2** [comment]
i think pattern 22 is for fake prime, it would make sense that it doesnt work anymore because of the last update

**Comment by wemanzoz** [comment]
> i think pattern 22 is for fake prime, it would make sense that it doesnt work anymore because of the last update

oh thats why

**Comment by gr1ndy** [comment]
> i think pattern 22 is for fake prime, it would make sense that it doesnt work anymore because of the last update

what about #26?
