### ISSUE TITLE
[Enchancement] Manual map injection support

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#2959]
.

**Comment by mkot2** [comment]
i always manual map with no problem

**Comment by wemanzoz** [comment]
> i always manual map with no problem

what injector

**Comment by degeneratehyperbola** [comment]
You need to turn off TLS

**Comment by mkot2** [comment]
> 
> 
> > i always manual map with no problem
> 
> what injector

https://github.com/mdilai/Shtreeba

**Comment by mdilai** [comment]
The "problem" is not a MMap but a thread creation method of your injectors. It detected anyway, so it's even better that Osiris crashing before you get troubles.
