### ISSUE TITLE
cannot find pattern 22#

### ISSUE THREAD

**Issue by joana19** [danielkrupinski/Osiris#2960]
Im using an older version of osiris, and I cannot seem to find the reason of this error.
(IDK what pattern the error points to, and call stack doesnt show a thing.)
![image](https://user-images.githubusercontent.com/71457615/120886484-eafce100-c5f6-11eb-82c7-fe45a34abb52.png)

I've tried debugging but it gives me nothing.
any help would be appreciated.

**Comment by acey1337** [comment]
remove fake prime

**Comment by danielkrupinski** [comment]
fb985d6a3fd4810db03ce796e5b5236c6e188d4b
