### ISSUE TITLE
How to use on Linux?

### ISSUE THREAD

**Issue by Smellon69** [danielkrupinski/Osiris#2961]
I have windows but also have a Linux Ubuntu PC. In the title it has the tag Linux yet there is no build scripts or anything. How do I inject it? (I am retarded please don't say confusing stuff)

**Comment by lukizel** [comment]
https://github.com/danielkrupinski/Osiris/blob/master/.github/workflows/linux.yml

This should work, however I never got it to work since I get instant VAC errors whenever I have a folder named 'Osiris' :/

**Comment by Liam5750** [comment]
Didn't work for some reason
Say's "CMake Error: The source directory "/home/myname/Release" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
"

**Comment by linuxer9** [comment]
I don't use linux, but read instructions made by this guy
https://github.com/danielkrupinski/Osiris/pull/2853

**Comment by syazskylex** [comment]
https://github.com/danielkrupinski/Osiris/issues/3283
