### ISSUE TITLE
Logitech G502 Hero

### ISSUE THREAD

**Issue by leninismus** [danielkrupinski/Osiris#2963]
Hello my friends.

Unlike cheating, there's something I need to consult with you, something I need to know. I would be very happy if you could help me.

I am using Logitech G502 Hero Mouse. It seems possible to assign macros to the mouse with the Logitech G-Hub software. But apart from that, there is something called "Script".

With a script application called Lua, you can assign mouse movements for each game and have it spray by pressing a button.

But I am not a programmer. My English is also very poor. I am writing this article on Translate and translating what you wrote here. I don't know how to script as I am not a programmer.

On the Internet, such spray scripts are sold for money on Youtube. Prices are around $25.

But $25 is a high price for me as my country's currency is so worthless.

I need your help as you know coding and can show improvements in scripting.

Is it possible to create scripts for weapons like AK47, M4A4 for CS:GO?

 Thank you very much in advance.

**Comment by Zvondaaa** [comment]
smaller tip , search it on uc

**Comment by Liam5750** [comment]
unknowncheats.net

**Comment by linuxer9** [comment]
these scripts sucks
It will made you aim like an avarage gold nova
use osiris + standalone rcs pr with vac bypass, and save your $25 to buy prime accounts after you got OW banned.

**Comment by popoyeLetal** [comment]
> these scripts sucks
> It will make you aim like an avarage gold nova
> use osiris + standalone rcs pr with vac bypass, and save your $25 to buy prime accounts after you get OW banned.

What is standlone rcs pr??

**Comment by linuxer9** [comment]
> 
> 
> > these scripts sucks
> > It will make you aim like an avarage gold nova
> > use osiris + standalone rcs pr with vac bypass, and save your $25 to buy prime accounts after you get OW banned.
> 
> What is standlone rcs pr??

this: https://github.com/danielkrupinski/Osiris/pull/2135
