### ISSUE TITLE
Inflame vs MemJect osiris detection

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#2967]
Wich is "better" in terms of making osiris.dll undetected?? And why??
Thanks

**Comment by Scui1** [comment]
just add 10gb of junkcode, vmprotect it and use extreme injector or cheat engine to inject osiris. Is undetected for me since years

**Comment by wemanzoz** [comment]
@Scui1 is def a troll, dont listen to him :)

**Comment by Pixelsuft** [comment]
But VAC Bypass is not a joke

**Comment by 0a736b85** [comment]
> just add 10gb of junkcode, vmprotect it and use extreme injector or cheat engine to inject osiris. Is undetected for me since years

yikes

**Comment by 0a736b85** [comment]
![9](https://user-images.githubusercontent.com/68378883/121184950-2b2ebe80-c898-11eb-9941-e4d307bad05d.png)

**Comment by mkot2** [comment]
> 
> 
> just add 10gb of junkcode, vmprotect it and use extreme injector or cheat engine to inject osiris. Is undetected for me since years

not even funny
