### ISSUE TITLE
functions

### ISSUE THREAD

**Issue by idkplayer** [danielkrupinski/Osiris#297]
https://github.com/danielkrupinski/Osiris/issues/240
https://github.com/danielkrupinski/Osiris/issues/266
https://github.com/danielkrupinski/Osiris/issues/186
https://github.com/danielkrupinski/Osiris/issues/230
https://github.com/danielkrupinski/Osiris/issues/205
when it comes to the last, it's best if the menu style would be nice to see such a watermark in Osiris, and if you can do it in esp no those black borders, and hit marker.I understand that it is very heavy and you need time, but only reminded

**Comment by danielkrupinski** [comment]
No need to create issues like this one.
