### ISSUE TITLE
FAILED TO FIND PATTERN AFTER NEW UPDATES

### ISSUE THREAD

**Issue by floydGG** [danielkrupinski/Osiris#2970]
Just like the title

**Comment by dapaster** [comment]
only happen to the old source. try the latest one

**Comment by caiocinel** [comment]
The Steam Overlay has been updated, it seems to me that it now uses the beta version (already supported due to c5095f3 )

**Comment by Be4zZz** [comment]
hey, can someone compile the latest version of Osiris and upload the dll please?
its very laborious to download the whole visual studio sh** and set it up just to cheat in csgo

would be definitley nice - thanks to advance
