### ISSUE TITLE
How does force sv cheat works

### ISSUE THREAD

**Issue by Flow512** [danielkrupinski/Osiris#2972]

**Comment by Flow512** [comment]
> https://github.com/danielkrupinski/Osiris/blob/084848b54fb6a93badc055e70995befa88631cef/Osiris/Hooks.cpp#L636

I tried making the value 1 it didnt work.
Im trying to do onetap force svcheat thing.

**Comment by linuxer9** [comment]
> 
> 
> > https://github.com/danielkrupinski/Osiris/blob/084848b54fb6a93badc055e70995befa88631cef/Osiris/Hooks.cpp#L636
> 
> I tried making the value 1 it didnt work.
> Im trying to do onetap force svcheat thing.

It doesn't work like that, svCheatsGetBool function returns true whenever you want to force sv_cheat 1, for example when you want to set third person view.
anyway, why do you want to force sv_cheats? what is the onetap thing?

**Comment by Flow512** [comment]
when you join like pivate server or your friends host you can get godmode, noclip

**Comment by linuxer9** [comment]
> 
> 
> when you join like pivate server or your friends host you can get godmode, noclip

if the server owner enables sv_cheats, there is no need to spoof that with cheats on your side.
all you have to do is open your console and type any command.
spoofing sv_cheats won't give you god mode or noclip.
