### ISSUE TITLE
Oh Dear Daniel!

### ISSUE THREAD

**Issue by PottyTrained** [danielkrupinski/Osiris#2973]
Oh Dear Daniel, once i am using the inventory changer and i have equip a gun like cz for the skin but in the real equipped is the five seven it will bugged in game. Please adds a check where the gun it checks if skin gun is equipped and if not equipped it. Thanks so much daniel

**Comment by blackMasterLord** [comment]
When u equip a REAL skin CS:GO receive message about default equipped weapons(revolver or deagle etc.).
But
When u equip a FAKE skin CS:GO DONT receive message about default equipped weapons(revolver or deagle etc.) -> weapon not change.
### So u need:
1. Equip default weapon (if skin for deagle u need first equip **default** deagle);
2. Then equip FAKE skin;
### OR
1. When u equip FAKE skin, send message to steam to default equipped weapon; 
> its protobuf, maybe

**Comment by PottyTrained** [comment]
> 
> 
> When u equip a REAL skin CS:GO receive message about default equipped weapons(revolver or deagle etc.).
> But
> When u equip a FAKE skin CS:GO DONT receive message about default equipped weapons(revolver or deagle etc.) -> weapon not change.
> ### So u need:
> 
>     1. Equip default weapon (if skin for deagle u need first equip **default** deagle);
> 
>     2. Then equip FAKE skin;
> 
> 
> ### OR
> 
>     1. When u equip FAKE skin, send message to steam to default equipped weapon;
> 
> 
> > its protobuf, maybe

I know blackMasterlord but i am just saying for convenience he can add something to automatically do it for us so we don't need to equip default weapon our self :D

**Comment by danielkrupinski** [comment]
Now it should be done automatically (39d968c02f210a432f1c6512ef2c4f3b7bbbfeac).
