### ISSUE TITLE
Not injecting

### ISSUE THREAD

**Issue by MasterChief220** [danielkrupinski/Osiris#2976]
Even since the new new cs go update osiris does not inject to cs go. Im using cs ghost v3.1 to inject it with admin privileges but it just does not inject to the game and it says injection completed sucessfully.

**Comment by jdbjdb2** [comment]
I also have this problem

I've tried multiple injectors and just compile from latest source

Rando injector has no messages, but xenos returns error code 0xC0000135

**Comment by MasterChief220** [comment]
> I also have this problem
> 
> I've tried multiple injectors and just compile from latest source
> 
> Rando injector has no messages, but xenos returns error code 0xC0000135
> 
> Injecting into a new process returns "Failed to find VBaseFileSystem011 interface!"

It doesnt give me any error . It says injected successfully but doesnt inject at all.
