### ISSUE TITLE
 failed to find pattern

### ISSUE THREAD

**Issue by memorymanager** [danielkrupinski/Osiris#2977]
Hello, I injected normally yesterday and today when I tried I got an error of type failed to find pattern 1,2
and then it crashed any help? (For some reason I don't wanna use the latest version)

**Comment by Zvondaaa** [comment]
any help?

**Comment by floydGG** [comment]
compile the latest updates, good to go

**Comment by gaowq** [comment]
when I run Csgo，there is no problem，but when I run 5e play，alert “Failed to find pattern #6!” and quiet game,  maybe it‘s against cheating when read memory?  anyone know?
