### ISSUE TITLE
How to get rid of failed to find pattern

### ISSUE THREAD

**Issue by hungdz1234** [danielkrupinski/Osiris#2978]
Hi, I'm currently using this version: https://github.com/danielkrupinski/Osiris/commit/047b0c0d61f7b56dab7078ceffc4fb965f6a77be

And I got these errors:
![image](https://user-images.githubusercontent.com/54879097/121387779-24c24480-c975-11eb-966b-b6f4ba9b9709.png)

I already tried this but it didn't work, still have "Failed to find pattern 1, 2, 24"
https://github.com/danielkrupinski/Osiris/commit/e3d8f1d60e186c5c6dc06044e4e8973700b80e8b#diff-34a9c35a09c40ac135a0569b50037dec3bec11d693ce239ade9fe7c99625afacR117

For some reason I don't wanna use the latest version, so how to get rid of this error?

**Comment by Zvondaaa** [comment]
same

**Comment by mdilai** [comment]
Let me suggest you to cherry-pick this commit from master branch https://github.com/danielkrupinski/Osiris/commit/fb985d6a3fd4810db03ce796e5b5236c6e188d4b

**Comment by hungdz1234** [comment]
> Let me suggest you to cherry-pick this commit from master branch [fb985d6](https://github.com/danielkrupinski/Osiris/commit/fb985d6a3fd4810db03ce796e5b5236c6e188d4b)

Thank you. It help remove error of pattern 24. But still pattern 1 & 2 remains. Can u suggest what else should I cherry-pick?

**Comment by r3s1l13nt** [comment]
> Hi, I'm currently using this version: [047b0c0](https://github.com/danielkrupinski/Osiris/commit/047b0c0d61f7b56dab7078ceffc4fb965f6a77be)
> 
> And I got these errors:
> ![image](https://user-images.githubusercontent.com/54879097/121387779-24c24480-c975-11eb-966b-b6f4ba9b9709.png)
> 
> I already tried this but it didn't work, still have "Failed to find pattern 1, 2, 24"
> [e3d8f1d#diff-34a9c35a09c40ac135a0569b50037dec3bec11d693ce239ade9fe7c99625afacR117](https://github.com/danielkrupinski/Osiris/commit/e3d8f1d60e186c5c6dc06044e4e8973700b80e8b#diff-34a9c35a09c40ac135a0569b50037dec3bec11d693ce239ade9fe7c99625afacR117)
> 
> For some reason I don't wanna use the latest version, so how to get rid of this error?

Can I have ur discord ?

**Comment by floydGG** [comment]
> Hi, I'm currently using this version: [047b0c0](https://github.com/danielkrupinski/Osiris/commit/047b0c0d61f7b56dab7078ceffc4fb965f6a77be)
> 
> And I got these errors:
> ![image](https://user-images.githubusercontent.com/54879097/121387779-24c24480-c975-11eb-966b-b6f4ba9b9709.png)
> 
> I already tried this but it didn't work, still have "Failed to find pattern 1, 2, 24"
> [e3d8f1d#diff-34a9c35a09c40ac135a0569b50037dec3bec11d693ce239ade9fe7c99625afacR117](https://github.com/danielkrupinski/Osiris/commit/e3d8f1d60e186c5c6dc06044e4e8973700b80e8b#diff-34a9c35a09c40ac135a0569b50037dec3bec11d693ce239ade9fe7c99625afacR117)
> 
> For some reason I don't wanna use the latest version, so how to get rid of this error?

can u share ur dll? the latest version just nah for me
