### ISSUE TITLE
[QUESTION] Why you set doorRange in fastPlant to 200.0f?

### ISSUE THREAD

**Issue by playday3008** [danielkrupinski/Osiris#2979]
Player use radius in csgo sources is 80.f

https://github.com/perilouswithadollarsign/cstrike15_src/blob/f82112a2388b841d72cb62ca48ab1846dfcc11c8/game/shared/baseplayer_shared.h#L18

https://github.com/danielkrupinski/Osiris/blob/c49dbbc340d879d4e6798ea747dc4b45da22827c/Osiris/Hacks/Misc.cpp#L324

Maybe I don't know something?

**Comment by wirekuro** [comment]
@danielkrupinski
