### ISSUE TITLE
Skin Changer and config issue

### ISSUE THREAD

**Issue by realproud** [danielkrupinski/Osiris#298]
First of, i love the cheat! its so amazing and it doesn't crash like any other free legit cheat out there. I have 2 issues with the cheat. Number 1 is that every time i load into this 1v1 arena server, without activating any cheat yet, it crashes. I even tried it on a new account and it crashes. Number two is the config. I try to save my cfg and it crashes instantly. If you can fix this whenever you have time, that'll be great! Thanks for the amazing cheat

**Comment by danielkrupinski** [comment]
I can't help you with neither of your problems unless you post specific info like call stack and debugger output at the time of the crash.
