### ISSUE TITLE
vac banned

### ISSUE THREAD

**Issue by micsuro** [danielkrupinski/Osiris#2983]
i got vac banned after 1 day of using with the csghost injector

**Comment by sotakoira** [comment]
https://github.com/danielkrupinski/VAC-Bypass-Loader
https://github.com/mdilai/Shtreeba

enjoy not getting banned at all

**Comment by floydGG** [comment]
> https://github.com/danielkrupinski/VAC-Bypass-Loader
> https://github.com/mdilai/Shtreeba
> 
> enjoy not getting banned at all

+1

**Comment by micsuro** [comment]
btw does anyone know whether or not i will get banned on my main witch is on the same computer?

**Comment by Tothale** [comment]
if you not inject anything on your main account you don't get vac. It doesn't matter if they are on the same computer.
Example:
Main acc: Not cheating
Smurf acc 1: Cheating with detected injector or detected cheat
Smurf acc 2: Not cheating
if you get vac banned or overwatch banned on "smurf acc 1" you don't get vac on "Main acc" and "Smurf acc 2"

> btw does anyone know whether or not i will get banned on my main witch is on the same computer?

**Comment by Liam5750** [comment]
NEVER use csghost-v4 always use v3.1 v4 is highly detected

**Comment by linuxer9** [comment]
> 
> 
> NEVER use csghost-v4 always use v3.1 v4 is highly detected

what?
v4 comes with bypass, is it detected now?

**Comment by Tothale** [comment]
You can use **[VAC Bypass](https://github.com/danielkrupinski/VAC-Bypass-Loader) + DLL in Windows Folder + Process Hacker 2**
I think these are good, i have been using them for a few months and still not vac banned but i can't say anything for the future.
Note: **Not recommended for using on main accounts unless you have a private injector and protected dll.**

**Comment by Liam5750** [comment]
> > NEVER use csghost-v4 always use v3.1 v4 is highly detected
> 
> what?
> v4 comes with bypass, is it detected now?

It was detected from release sadly for some odd reason

**Comment by wemanzoz** [comment]
> https://github.com/danielkrupinski/VAC-Bypass-Loader
> https://github.com/mdilai/Shtreeba
> 
> enjoy not getting banned at all

tbh idk why but my build crashed all the time with shtreeba

**Comment by acey1337** [comment]
> > https://github.com/danielkrupinski/VAC-Bypass-Loader
> > https://github.com/mdilai/Shtreeba
> > enjoy not getting banned at all
> 
> tbh idk why but my build crashed all the time with shtreeba

shtreeba uses manualmap to inject if im not mistaken, osiris only supports loadlibrary injection method

**Comment by floydGG** [comment]
> > > https://github.com/danielkrupinski/VAC-Bypass-Loader
> > > https://github.com/mdilai/Shtreeba
> > > enjoy not getting banned at all
> > 
> > 
> > tbh idk why but my build crashed all the time with shtreeba
> 
> shtreeba uses manualmap to inject if im not mistaken, osiris only supports loadlibrary injection method

but it works for me somehow

**Comment by sserve-kr** [comment]
> > > > https://github.com/danielkrupinski/VAC-Bypass-Loader
> > > > https://github.com/mdilai/Shtreeba
> > > > enjoy not getting banned at all
> > > 
> > > 
> > > tbh idk why but my build crashed all the time with shtreeba
> > 
> > 
> > shtreeba uses manualmap to inject if im not mistaken, osiris only supports loadlibrary injection method
> 
> but it works for me somehow

guys just use ExLoader
It's awesome

**Comment by th3nd** [comment]
> 
> 
> > > > > https://github.com/danielkrupinski/VAC-Bypass-Loader
> > > > > https://github.com/mdilai/Shtreeba
> > > > > enjoy not getting banned at all
> > > > 
> > > > 
> > > > tbh idk why but my build crashed all the time with shtreeba
> > > 
> > > 
> > > shtreeba uses manualmap to inject if im not mistaken, osiris only supports loadlibrary injection method
> > 
> > 
> > but it works for me somehow
> 
> guys just use ExLoader
> It's awesome

guys just use rat
It's awesome
