### ISSUE TITLE
[REQUEST] Does anyone have the "older" version of Osiris? But already removed the fake prime feature.

### ISSUE THREAD

**Issue by floydGG** [danielkrupinski/Osiris#2984]
![image](https://user-images.githubusercontent.com/53382214/121537694-56e3ad00-ca2e-11eb-8c1a-4a67ccc179ca.png)

**Comment by floydGG** [comment]
https://i.imgur.com/jDeUcwV.mp4

Latest [HOLD] Aimbot missing at the 3rd bullets and so

**Comment by linuxer9** [comment]
the aimbot works when you shot anyway, no need to bind it to mouse1

**Comment by JostBrand** [comment]
You can always checkout an older commit

**Comment by floydGG** [comment]
> the aimbot works when you shot anyway, no need to bind it to mouse1

the problem is, it looks snappy af.
cuz i only use it for deagle, and without smoothing but low fov

**Comment by linuxer9** [comment]
> 
> 
> > the aimbot works when you shot anyway, no need to bind it to mouse1
> 
> the problem is, it looks snappy af.
> cuz i only use it for deagle, and without smoothing but low fov

also disable aimlock, for me I use deagle with 1-1.5 fov and smoothness 1, it's not very obvious at least in demos.

**Comment by floydGG** [comment]
> > > the aimbot works when you shot anyway, no need to bind it to mouse1
> > 
> > 
> > the problem is, it looks snappy af.
> > cuz i only use it for deagle, and without smoothing but low fov
> 
> also disable aimlock, for me I use deagle with 1-1.5 fov and smoothness 1, it's not very obvious at least in demos.
> 
> anyways, If you still need to use onkey mouse1, try this horrible idea: unbind mouse1 from console and enable autoshot and aimlock.

tried that method, horrible it is.
i just need the old source, idk how to find it.

**Comment by playday3008** [comment]
Just go to any commit, and do this with code https://github.com/danielkrupinski/Osiris/commit/fb985d6a3fd4810db03ce796e5b5236c6e188d4b and compile it

**Comment by floydGG** [comment]
> Just go to any commit, and do this with code [fb985d6](https://github.com/danielkrupinski/Osiris/commit/fb985d6a3fd4810db03ce796e5b5236c6e188d4b) and compile it

do you have discord? i really need help so bad

**Comment by floydGG** [comment]
so yeah, i managed to compile the "old version" of osiris and remove the fake prime.
what is pattern 1 and 2? 
![1](https://user-images.githubusercontent.com/53382214/121770919-6c73e680-cb96-11eb-8352-46aa5ce23b5b.PNG)
![2](https://user-images.githubusercontent.com/53382214/121770922-6da51380-cb96-11eb-9f8c-98fe538d4ed5.PNG)

**Comment by playday3008** [comment]
gameoverlayrenderer patterns, just ignore this

**Comment by floydGG** [comment]
> gameoverlayrenderer patterns, just ignore this

but those things crashed my game.
any solution?

**Comment by floydGG** [comment]
Solved, just replace with the new value from latest source
