### ISSUE TITLE
Inventory Changer; Model. Client bullets

### ISSUE THREAD

**Issue by Xonn1com** [danielkrupinski/Osiris#2986]
This screen followed by video https://streamable.com/oj0n5o
Basically, you see red bullets, while server sees blue ones.
![obraz](https://user-images.githubusercontent.com/64926921/121736362-c40f4500-caf7-11eb-9d23-2445520b9971.png)

**Comment by danielkrupinski** [comment]
Why did you close this?

**Comment by Xonn1com** [comment]
> 
> 
> Why did you close this?

Problem solved. Just needed to build again
