### ISSUE TITLE
Color correction?

### ISSUE THREAD

**Issue by wirekuro** [danielkrupinski/Osiris#2988]
Im not sure what it does exactly but seems like it doesn't do anything.

**Comment by degeneratehyperbola** [comment]
Try increasing your graphics settings in-game

**Comment by wirekuro** [comment]
> Try increasing your graphics settings in-game

I play on high settings.

**Comment by degeneratehyperbola** [comment]
Then you have old version of Osiris, with outdated offsets, they have recently been changed

**Comment by wirekuro** [comment]
> Then you have old version of Osiris, with outdated offsets, they have recently been changed

Like honestly, I downloaded new version 2 days ago and updated it this morning. eksdee

**Comment by wirekuro** [comment]
Update: I just realised it isn't working when Disable post processing is enabled.
