### ISSUE TITLE
render box and bar

### ISSUE THREAD

**Issue by idkplayer** [danielkrupinski/Osiris#299]
Hi, it's me again, if you can change the render box, i.e. without those black borders, please.

**Comment by effex1337** [comment]
Remove lines 54, 55, 56 in ESP.cpp then compile. It's open source for a reason ya know.

**Comment by idkplayer** [comment]
Okey thanks but daniel you add to esp weapon but in symbols? such graphics?

**Comment by ijre** [comment]
You might be able to pull the pictures out from the game itself, but I doubt Daniel will do that since there's no weapon esp to begin with
