### ISSUE TITLE
Oh Dear Daniel! =D

### ISSUE THREAD

**Issue by iandinromania** [danielkrupinski/Osiris#2991]
can u make config  on button.(hotkeys)..Ex: F1- Legits , F2- semirage ,F3- only wall .... you understand this idea PLS....I love u @danielkrupinski

**Comment by iandinromania** [comment]
auto& vecConfigs = pConfig->getConfigs();
				for (auto& config : vecConfigs)

					if(ImGui::HotKey(config.c_str(), &g_Config.g_Hotkeys.configs[config])); but not work

**Comment by iandinromania** [comment]
@danielkrupinski

**Comment by Shuvi-Moro** [comment]
Do not ask someone to do something, if you need to do it yourself, here you have to ask if suddenly something is not clear and you are at a dead end.
PLS Close issue
