### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Flow512** [danielkrupinski/Osiris#2992]
void Misc::blockbot(UserCmd* cmd) noexcept
{
    if (!config->misc.blockbot || !config->misc.blockbotKey.isDown())
        return;

    if (!localPlayer || !localPlayer->isAlive())
        return;

    float bestdist = 250.f;
    int index = -1;
    for (int i = 1; i <= interfaces->engine->getMaxClients(); i++) {
        auto entity = interfaces->entityList->getEntity(i);

        if (!entity)
            continue;

        if (!entity->isAlive() || entity->isDormant() || entity == localPlayer.get())
            continue;

        Vector ownPos = localPlayer->origin();
        Vector enemyPos = entity->origin();

        float dist = distance(localPlayer->origin(), entity->origin());
        if (dist < bestdist)
        {
            bestdist = dist;
            index = i;
        }   
        
        const Vector targetvelocity = entity->velocity();

        if (dist < 60 && enemyPos.z + 10 < ownPos.z)
        {

            float yaw = cmd->viewangles.y;
            Vector offset = ownPos - enemyPos;

            Vector translatedVelocity = Vector(
                (float)(offset.x * cos(yaw / 180) + offset.y * sin(yaw / 180)),
                (float)(offset.y * cos(yaw / 180) - offset.x * sin(yaw / 180)),
                offset.z
            );
            translatedVelocity.x -= entity->eyeAngles().x;
            translatedVelocity.normalize();
            translatedVelocity.x = std::clamp(translatedVelocity.x, -180.f, 180.f);

            if (translatedVelocity.x < -1.0f)
                cmd->forwardmove = 450.f;
            else if (translatedVelocity.x > 1.0f)
                cmd->forwardmove = -450.f;
            //cmd->forwardmove = -translatedVelocity.x * 100, targetvelocity;
        }
        
    }

    if (index == -1)
        return;

    auto target = interfaces->entityList->getEntity(index);

    if (!target)
        return;

    Vector angles = Misc::calculateRelativeAngle(localPlayer->origin(), target->origin());

    angles.y -= localPlayer->eyeAngles().y;
    angles.normalize();
    angles.y = std::clamp(angles.y, -180.f, 180.f);

    if (angles.y < -1.0f)
        cmd->sidemove = 450.f;
    else if (angles.y > 1.0f)
        cmd->sidemove = -450.f;

}

**Comment by Flow512** [comment]
its runboost bot and its glitchy

**Comment by Flow512** [comment]
pls help

**Comment by KurastikO** [comment]
you know it's also easy to just runboost easily right?

**Comment by Flow512** [comment]
> you know it's also easy to just runboost easily right?

YEA but im trying to make crouch block bot
