### ISSUE TITLE
Push3DView don't work, please help

### ISSUE THREAD

**Issue by worstdeveloperboy** [danielkrupinski/Osiris#2993]
I added Push3DView function like this:
`class RenderView {
public:
    INCONSTRUCTIBLE(RenderView)

    VIRTUAL_METHOD(void, setBlend, 4, (float alpha), (this, alpha))
    VIRTUAL_METHOD(void, setColorModulation, 6, (const float* colors), (this, colors))

    VIRTUAL_METHOD(void, Push3DView, 43, (RenderContext* pRenderContext, const ViewSetup& view, int nFlags, ITexture* pRenderTarget, Frustum frustumPlanes), (this, pRenderContext, std::cref(view), nFlags, pRenderTarget, frustumPlanes))
    VIRTUAL_METHOD(void, PopView, 45, (RenderContext* pRenderContext, Frustum frustumPlanes), (this, pRenderContext, frustumPlanes))

    void setColorModulation(float r, float g, float b) noexcept
    {
        float color[3]{ r, g, b };
        setColorModulation(color);
    }
};`
but it doesn't work. What am i doing wrong?
![Безымянный](https://user-images.githubusercontent.com/59305582/121896004-08465380-cd4b-11eb-832c-576501561cf2.png)
![Безымянный2](https://user-images.githubusercontent.com/59305582/121896124-27dd7c00-cd4b-11eb-97c9-f520b9ff7e69.png)

**Comment by Scui1** [comment]
Just stop trying if you already fail at this stage, paste. All you need to do is already in the post https://www.unknowncheats.me/forum/counterstrike-global-offensive/347519-draw-model.html
Also this method wont work for mainmenu 😄
