### ISSUE TITLE
ESP is unrelyable

### ISSUE THREAD

**Issue by DarkReaper231** [danielkrupinski/Osiris#2999]
Currently Enemy ESP kinda sucks. Like it doesn't always show correctly, for example a person is behind the wall and moving but the EPS is lagging behind which makes it unrelyable to predict.

**Comment by danielkrupinski** [comment]
Please show a video of that happening.

**Comment by DarkReaper231** [comment]
As you can see here when I am on the B site. The ESP is kinda lagging. I mean it is sticked to the bones precisely but it does disappears and appears even tho the enemy is pretty close. I have been using Rat and this wasn't happening there.
I can't tell what the issue is but it might be possible to fix since Rat had this working perfectly.

https://www.youtube.com/watch?v=0RN8__OHTQA

**Comment by notgoodusename** [comment]
That limitation is part of the game so its impossible to avoid

**Comment by 3Ld4D** [comment]
> That limitation is part of the game so its impossible to avoid

It is possible to avoid, this happens when player goes dormant and back.
Pretty sure Interpolation causes this issue.

**Comment by DarkReaper231** [comment]
Then how RatPoison solved it?

**Comment by notgoodusename** [comment]
> > That limitation is part of the game so its impossible to avoid
> 
> It is possible to avoid, this happens when player goes dormant and back.
> Pretty sure Interpolation causes this issue.

idk if i misintrepeted anything but from what i understood, op is saying that people in the esp dont update often
also dormancy happens server side

**Comment by KurastikO** [comment]
> Then how RatPoison solved it? I mean sure, you don't see the enemy through whole map either in Rat but at least in close range it doesn't cut like this. It can be pretty annoying.

It still does???

**Comment by linuxer9** [comment]
I think the player goes dormant, meaning the game doesn't recieve his exact location use GOESP it has dormant ESP, I believe ratpoison has dormant esp feature also.
