### ISSUE TITLE
can you make it detect the enemy behind the wall?

### ISSUE THREAD

**Issue by cha222554** [danielkrupinski/Osiris#3]
like 
behind wall = red
if not = blue

and can u add me on discord ? Mianbai#4578
im want ask u something about coding problem i can pay for u time.

**Comment by danielkrupinski** [comment]
I think I will add such feature in future but it will require some work.

About Discord - I don't have one. If you have some questions/problems not related with this project feel free to mail me (e-mail is on my profile).

**Comment by cha222554** [comment]
can u get my emails?

**Comment by cha222554** [comment]
i just sent u details
