### ISSUE TITLE
I can't build the Project

### ISSUE THREAD

**Issue by LucaSchild** [danielkrupinski/Osiris#30]
When I try to build the project I keep getting this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C4996	'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	Osiris	c:\users\ich\onedrive\desktop\veiled\osiris-master\osiris\gui.cpp	140	

What am I supposed to do?

**Comment by M0V3** [comment]
https://stackoverflow.com/questions/16883037/remove-secure-warnings-crt-secure-no-warnings-from-projects-by-default-in-vis

**Comment by danielkrupinski** [comment]
Warning / error is gone now.
