### ISSUE TITLE
Remove blur on scope

### ISSUE THREAD

**Issue by AuriumWorld** [danielkrupinski/Osiris#3002]
Blur removal on scope is not working

**Comment by KurastikO** [comment]
Blur Removal is a feature that removes the blur outside of the scopes(AWP,SSG,SG,AUG) 

The feature is still working in the latest version, are you perhaps talking about the blur of the scope when you move?

**Comment by AuriumUSA** [comment]
> Blur Removal is a feature that removes the blur outside of the scopes(AWP,SSG,SG,AUG) 
> 
> 
> 
> The feature is still working in the latest version, are you perhaps talking about the blur of the scope when you move?

Oh okay I guess the feature I'm thinking of isn't included, thanks for that info.

**Comment by dapaster** [comment]
> Blur removal on scope is not working

try `Disable Scope Overlay` and `Disable Post Processing` at the same time

**Comment by dapaster** [comment]
> > Blur Removal is a feature that removes the blur outside of the scopes(AWP,SSG,SG,AUG)
> > The feature is still working in the latest version, are you perhaps talking about the blur of the scope when you move?
> 
> Oh okay I guess the feature I'm thinking of isn't included, thanks for that info.

if you want to remove the scope,
return `interfaces->panel->getName(panel) == "HudZoom"` on the *paintTraverse* and manually draw a line `drawList->AddLine()`
