### ISSUE TITLE
Client-sided bullets aren't in the same position as my crosshair when I try to crouch.

### ISSUE THREAD

**Issue by KurastikO** [danielkrupinski/Osiris#3008]
The server-sided bullets however are normal and there's nothing wrong with it, I don't know what happened but since the last commit this has happened. Does anybody know why?

_Also clarifying that I don't have anti-aim on._

**Comment by Xonn1com** [comment]
Try loading other config then loading cfg you want.
Worked for me

**Comment by KurastikO** [comment]
> Try loading other config then loading cfg you want.
> Worked for me

Fucking hell thanks mate
