### ISSUE TITLE
Radar hack doesnt work when inside smoke

### ISSUE THREAD

**Issue by lordeternity000** [danielkrupinski/Osiris#3013]
Radar hack doesnt work when I or the enemy is inside smoke

**Comment by hydemods** [comment]
game mechanic. pretty sure that cant be fixed.

**Comment by KurastikO** [comment]
**THIS IS AS THE GAME INTENDED AND WHEN WILL PEOPLE EVER LEARN ABOUT THIS**

**Comment by HowToMakeFaceitAB** [comment]
> **THIS IS AS THE GAME INTENDED AND WHEN WILL PEOPLE EVER LEARN ABOUT THIS**

Its still fixable

**Comment by HowToMakeFaceitAB** [comment]
> **THIS IS AS THE GAME INTENDED AND WHEN WILL PEOPLE EVER LEARN ABOUT THIS**

I mean you still get info about their positions all you gotta do is draw them on the minimap

**Comment by mxez** [comment]
> I mean you still get info about their positions all you gotta do is draw them on the minimap
why, all what you have to do is just to hook draw points on radar func and disable "check if enemy is in smoke"

**Comment by HowToMakeFaceitAB** [comment]
> > I mean you still get info about their positions all you gotta do is draw them on the minimap
> 
> why, all what you have to do is just to hook draw points on radar func and disable "check if enemy is in smoke"

ah that works thanks
