### ISSUE TITLE
Chat edgebug stat (Pull request)

### ISSUE THREAD

**Issue by r3s1l13nt** [danielkrupinski/Osiris#3014]
Yep. Like in clarity, interium, some other big name pastes 😎

Clarity | edgebugged
Interium | Edgebug [1]

https://youtu.be/m_uhWdSBvSo

I dont really understand how it works. Will be grateful if you will help me!

I will try selfcoding it soon

**Comment by 3Ld4D** [comment]
I can only help you with the chat print part.
https://www.unknowncheats.me/wiki/Counter_Strike_Global_Offensive:Printing_text_to_chat

**Comment by ethxun** [comment]
this would be helpful!

**Comment by ethxun** [comment]
> Yep. Like in clarity, interium, some other big name pastes 😎
> 
> Clarity | edgebugged
> Interium | Edgebug [1]
> 
> https://youtu.be/m_uhWdSBvSo
> 
> I dont really understand how it works. Will be grateful if you will help me!
> 
> I will try selfcoding it soon

this would be helpful!
