### ISSUE TITLE
CASE OPENING ISSUE

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#3016]
if you remove the code that allows you to get the 100% chance for grotto/ibuypower, you will not able to open case. instead it'll just say "we are unable to retrieve your item" @danielkrupinski plz fix

**Comment by zenovi** [comment]
same i always get grotto/IBP Holo pls fix also trade up contracts dont work

**Comment by wemanzoz** [comment]
> same i always get grotto/IBP Holo pls fix also trade up contracts dont work

its the code, @danielkrupinski fix plz

**Comment by danielkrupinski** [comment]
Now items received from cases are generating from loot lists (86e1c5ccf6606e26d88fc7d5c4ce4faeb144603b).
