### ISSUE TITLE
Aimbotz map not showing skins

### ISSUE THREAD

**Issue by hungdz1234** [danielkrupinski/Osiris#3017]
Hi. I enter Aimbotz and some gun doesn't have skin such as: USP-S, Five-Seven. Can u fix this?
![image](https://user-images.githubusercontent.com/54879097/122788014-17e01200-d2e0-11eb-8b33-b15fc7b056e0.png)
![image](https://user-images.githubusercontent.com/54879097/122788026-1adb0280-d2e0-11eb-904d-4059ce933d70.png)
![image](https://user-images.githubusercontent.com/54879097/122787952-0bf45000-d2e0-11eb-8080-f37dd5335903.png)

**Comment by OscarMorrisUCD** [comment]
+1, I presume its to do with a teamcheck.

**Comment by notgoodusename** [comment]
In aimbotz it may seem like you are on ct side, but the server thinks you are on t side (its super weird)
I recommend you use another map that isnt aimbotz to test skins (crashz' Crosshair Generator v3 might be a good one)

**Comment by hungdz1234** [comment]
Let's hope daniel fix this :)

**Comment by 3Ld4D** [comment]
You are on T side with CT sleeves and gloves.

**Comment by linuxer9** [comment]
It shouldn't as it doesn't even display real skins.
that's because this map messes up with team id settings.
