### ISSUE TITLE
Vac banned

### ISSUE THREAD

**Issue by RedTenZ** [danielkrupinski/Osiris#3018]
Hi, i was used Vac Bypass Loader : https://github.com/danielkrupinski/VAC-Bypass-Loader
And Osiris and i got vac banned today, how can i avoid vac ban, is there something i miss ?
Thanks for your answer

**Comment by mxez** [comment]
If you don't want to get banned, you can search for better undetected windows loader, or just try to play on linux, you won't be "VAC" banned there at all.

**Comment by VuBrian22** [comment]
Your injector's detected.

**Comment by RedTenZ** [comment]
Is https://github.com/mdilai/Shtreeba undetected?

**Comment by JukoiDev** [comment]
You can't be sure.

**Comment by gra439** [comment]
One way to make sure your injector isn't detected, is by coding your own, and doing it in a weird/dumb way to the point where valve doesn't see the "signature" of said injector match up with any of their "signature" records of cheat injectors.
