### ISSUE TITLE
[BUG] PLEASE FIX THIS ISSUE

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#3019]
![csgo_BV9VoLAJEm](https://user-images.githubusercontent.com/72364877/122916811-e0c93980-d38f-11eb-860a-281d817f1bcb.png)
this happens when you have 2 seperate gloves on ct and t side. happens when you switched team

**Comment by KurastikO** [comment]
You can just alter the source code where it auto-forceupdates anytime you switch a team, you join a match etc. etc.

**Comment by wemanzoz** [comment]
> You can just alter the source code where it auto-forceupdates anytime you switch a team, you join a match etc. etc.

idek how :v

**Comment by KurastikO** [comment]
macros?

**Comment by Xonn1com** [comment]
Just do Force update in Invertory Changer tab

**Comment by JukoiDev** [comment]
> > You can just alter the source code where it auto-forceupdates anytime you switch a team, you join a match etc. etc.
> 
> idek how :v

Do you even have Visual Studio?

**Comment by wemanzoz** [comment]
i fixed it like a few days ago soz
