### ISSUE TITLE
skybox

### ISSUE THREAD

**Issue by idkplayer** [danielkrupinski/Osiris#302]
can you add more beautiful skybox? e.g red galaxy green galaxy and the like.

**Comment by tirziz** [comment]
You need tho skybox first in order to change that 
. Btw I dont see anypoint of custom skybox

**Comment by HECCYE** [comment]
It would be cool tho

**Comment by danielkrupinski** [comment]
Which one of these:
https://gamebanana.com/textures/cats/1896
https://gamebanana.com/textures/cats/28
would you like to be added?

**Comment by cojo1989** [comment]
122 and 118 :)

**Comment by ogosirisfan** [comment]
how should we add it?
