### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by y3n00** [danielkrupinski/Osiris#3020]
**aim:**
- aim fov
- first bullet delay

**esp:**
- weapon icons
- healthbar with numbers

**misc:**
- better grenade predict

**Comment by KurastikO** [comment]
what do you mean better grenade prediction?

**Comment by cheenaze** [comment]
> what do you mean better grenade prediction?

not buggy and with a customizable line color

**Comment by wemanzoz** [comment]
**also that can bypass obs like player boxes etc.**
this

**Comment by Xonn1com** [comment]
Osiris uses in-game engine to draw grenade prediction (just like the: cl_grenadepreview command)
It will be hard (i'm not a developer) to write such thing, but there is e. g. LegendWare Source Code to work with

**Comment by cumshot** [comment]
its not hard to render a grenade prediction inside the imgui overlay, its how every other render is done in osiris
