### ISSUE TITLE
X-Ray P250 Package & Souvenir skins

### ISSUE THREAD

**Issue by Hayward41** [danielkrupinski/Osiris#3025]
- **X-Ray P250 Package** drops IBUYPOWER (Holo) Katowice 2014 (insted of P250 X-Ray). Same happends with **EMS ONE 2014 Souvenir Package** and **Dreamhack 2013 Souvenir Package**
- Souvenir Packages drops Normal skins(instead of Souvenir skins)

**Comment by danielkrupinski** [comment]
Those cases now work correctly.
