### ISSUE TITLE
Case unboxings not dropping knives

### ISSUE THREAD

**Issue by zenovi** [danielkrupinski/Osiris#3026]
unboxed close to 1000 cases havent gotten a single knife plz fix @danielkrupinski

**Comment by cumshot** [comment]
thats literally just typical csgo odds lmfao

**Comment by wemanzoz** [comment]
luck issue KEKEKEKEKEKEKE

**Comment by InfernoLum** [comment]
The method daniel uses doesn't parse knife drops from cases, hence you can't open a knife. At least in my experience.

**Comment by danielkrupinski** [comment]
Now you can receive knives from Dreams and Nightmares Case and Operation Riptide Case. More to come.
