### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by xKv33n** [danielkrupinski/Osiris#3029]
![Screenshot_7](https://user-images.githubusercontent.com/59332372/123078108-b4fb9180-d42b-11eb-922b-cca9d8861da1.png)
When im trying compile osiris source i have that issue. Who can help me? This file is not in the osiris repository.

**Comment by TobbeLiton** [comment]
If it says Osiris.vcxproj failed or something then i have the same problem. My guess is that Daniel can't fix the problem so he is trying to avoid the issue.
