### ISSUE TITLE
chams crystal

### ISSUE THREAD

**Issue by idkplayer** [danielkrupinski/Osiris#303]
sometimes it does not work for me and sometimes it works as a colleague, it does not work as well, I have high graphic settings

**Comment by cojo1989** [comment]
i don`t have any problems

**Comment by NexSqaud** [comment]
you tried ultra high shader detail setting?

**Comment by danielkrupinski** [comment]
You need to set shader detail to at least 'high'.

**Comment by idkplayer** [comment]
"I have high graphic settings"
