### ISSUE TITLE
Add medalchanger option.

### ISSUE THREAD

**Issue by cheateronly123** [danielkrupinski/Osiris#3035]
Make medals visible to everyone in the lobby.

**Comment by zoominh0** [comment]
> Make medals visible to everyone in the lobby

Yeah thats not possible, those changers are clientsided meaning only you can see them.

**Comment by Hayward41** [comment]
patched by valve over 2 years ago

**Comment by ReShout876** [comment]
> patched by valve over 2 years ago

this
