### ISSUE TITLE
Random Crashes since update on 24/6

### ISSUE THREAD

**Issue by kschou95** [danielkrupinski/Osiris#304]
there are random crashes to the game, no error message nothing, sometimes can finish a match no problem, sometime just crash during playing

**Comment by QR01** [comment]
since I started using extreme injector it didnt crash once.

**Comment by kschou95** [comment]
> since I started using extreme injector it didnt crash once.

do u VMP extreme injector?

**Comment by kschou95** [comment]
i used extreme injector, same and it crashed... can't even VMP, it says "unsupported subsystem" when using extreme injector, some weapon's aimbot need hold key to work, it won't auto target when shot

**Comment by henkka22** [comment]
i got VAC with extreme injector 2 times don't even try

**Comment by kschou95** [comment]
> i got VAC with extreme injector 2 times don't even try

its ok, i generated 50 steam acc just for hacking, and yes, 5 acc VAC-ed... i just want to find out which causes the crash... tried 5 different injectors for csgo, 3 crashes, 2 vac prone, 1 no vac but crashes, the other 2 not even injecting
