### ISSUE TITLE
OSIRIS PROTECT

### ISSUE THREAD

**Issue by cheateronly123** [danielkrupinski/Osiris#3040]
Is Cheat already protected?
If not, how do I protect, what should I use?

**Comment by uzdiiilekk** [comment]
Themida and hash changer is the best way to protect dll or add junk codes i using auto junkcode adder and use own injector or csghost v4

**Comment by ic3dm4ng0** [comment]
> Themida and hash changer is the best way to protect dll or add junk codes i using auto junkcode adder and use own injector or csghost v4

https://github.com/ewwink/MD5-Hash-Changer is this a good hash changer? also csghost v4 is detected

**Comment by weendel11** [comment]
> Themida and hash changer is the best way to protect dll or add junk codes i using auto junkcode adder and use own injector or csghost v4

Give me the link to download Themida and Hash Changer, and also the injector, please.

**Comment by LostKingBlack** [comment]
junk code + vmp protector + hex edior ez

**Comment by weendel11** [comment]
> junk code + vmp protector + hex edior ez
> and protect injector

Give me the link to download please!!

**Comment by ic3dm4ng0** [comment]
> > junk code + vmp protector + hex edior ez
> > and protect injector
> 
> Give me the link to download please!!

if you cant use google maybe you shouldnt be trying to make a cheat undetected

**Comment by weendel11** [comment]
What order should I follow? From programs (Themida, hex, junk code, vmp).
Which injection can I use? What is not detected?

**Comment by kamikazeghost** [comment]
> What order should I follow? From programs (Themida, hex, junk code, vmp).
> Which injection can I use? What is not detected?

don't worry about any of these methods, none of them work.
Junk code is useless
Thermida is to stop the cheat getting cracked (not a worry for you)

The best way is to use daniel's vac bypass
https://github.com/danielkrupinski/VAC-Bypass-Loader

**Comment by Asviix** [comment]
> > Themida and hash changer is the best way to protect dll or add junk codes i using auto junkcode adder and use own injector or csghost v4
> 
> https://github.com/ewwink/MD5-Hash-Changer is this a good hash changer? also csghost v4 is detected

CSGhost V4.2.1 isn't detected lmao

**Comment by mxez** [comment]
Best way to be sure that you won't be banned is to simply cheat on linux.
Any of windows ways can be detected in the future.

**Comment by oniongithub** [comment]
hex editing, vm protect, and junk code are all useless, and yes linux cheats can be detected just look at aimtux. Best way is to just use a vac bypass, danielkrupinski has one and there is also another called vac3 inhibitor.

**Comment by pparadoxx** [comment]
> Themida and hash changer is the best way to protect dll or add junk codes i using auto junkcode adder and use own injector or csghost v4

junk code doesn't do anything with dlls, visual studio removes junk shit that isn't used automatically
