### ISSUE TITLE
How do I add StatTrak™ weapons?

### ISSUE THREAD

**Issue by KurastikO** [danielkrupinski/Osiris#3041]
I saw on one of the commits "0be688346cef7933f01b5ce2c48adf88588b2e40" that you added the feature. How do I add some weapons or knives?  

_will close when answered :)_

**Comment by wemanzoz** [comment]
hmmm, maybe try check ur config file. idk @danielkrupinski how??

**Comment by danielfan61a** [comment]
add your weapons normally to inventory, go to the config file and add
`"StatTrak": 1,` or whatever amount of StaTrak number you want (it's dynamic).
Load the config again and you should have your weapon 
![stattrak](https://user-images.githubusercontent.com/86361358/123277471-0bd19b80-d4fe-11eb-81ad-df75d8022410.png)
![stattrak2](https://user-images.githubusercontent.com/86361358/123277474-0c6a3200-d4fe-11eb-9da7-557906642de2.png)
