### ISSUE TITLE
In-game item deletion

### ISSUE THREAD

**Issue by Hayward41** [danielkrupinski/Osiris#3042]
You can't delete items (cases and graffitis) via delete button
![1](https://user-images.githubusercontent.com/82664161/123272556-86081d00-d50a-11eb-8a1b-9875fcf69151.png)
![2](https://user-images.githubusercontent.com/82664161/123274184-f82d3180-d50b-11eb-9497-c9b1a54a4f19.png)

**Comment by KurastikO** [comment]
Just delete it in the inventory changer menu???

**Comment by danielkrupinski** [comment]
Now it's possible (fb3c1b0a1034248f6189629e78835c7f49534af4).
