### ISSUE TITLE
Add grenade helper and better recoil crosshair

### ISSUE THREAD

**Issue by danielfan61a** [danielkrupinski/Osiris#3045]
Fuzion does this wonderfully and I wish for it to be part of Osiris as well.

-The grenade helper: you save smokes, flashes molotovs on maps, and the cheat helps you position yourself and throw the grenade. For example it shows you a circle on where to stand and where to throw the smoke from T spawn on mirage to mid cross. [Fuzion code](https://github.com/LWSS/Fuzion/blob/master/src/Hacks/grenadehelper.cpp). [Some GH configs for Fuzion](https://github.com/Wristing/FuzionNadeCfgs). You could also search the web "grenade helper csgo" to get a better idea of how this works. This was also mentionned in #321

-The grenade prediction on Fuzion shows you a drone view of where a grenade will land, that especially helpful when the said grenade will have to break a window to land somewhere. [Fuzion code](https://github.com/LWSS/Fuzion/blob/master/src/Hacks/grenadeprediction.cpp).

-When choosing recoil crosshair or noscope crosshair it shows a default crosshair that which you could only change the color. It would be nice if it just uses your crosshair and use that as a noscope and the same shape of crosshair for the recoil one but with the option to change color.
[Recoil crosshair Fuzion](https://github.com/LWSS/Fuzion/blob/master/src/Hacks/recoilcrosshair.cpp)
[noscope crosshair](https://github.com/LWSS/Fuzion/blob/master/src/Hacks/snipercrosshair.cpp)

Thank you for your efforts.

**Comment by Asviix** [comment]
Finally a Grenade Helper in Osiris
Thanks a lot that's god's work right there !

**Comment by weendel11** [comment]
> Fuzion does this wonderfully and I wish for it to be part of Osiris as well.
> 
> -The grenade helper: you save smokes, flashes molotovs on maps, and the cheat helps you position yourself and throw the grenade. For example it shows you a circle on where to stand and where to throw the smoke from T spawn on mirage to mid cross. [Fuzion code](https://github.com/LWSS/Fuzion/blob/master/src/Hacks/grenadehelper.cpp). [Some GH configs for Fuzion](https://github.com/Wristing/FuzionNadeCfgs). You could also search the web "grenade helper csgo" to get a better idea of how this works. This was also mentionned in #321
> 
> -The grenade prediction on Fuzion shows you a drone view of where a grenade will land, that especially helpful when the said grenade will have to break a window to land somewhere. [Fuzion code](https://github.com/LWSS/Fuzion/blob/master/src/Hacks/grenadeprediction.cpp).
> 
> -When choosing recoil crosshair or noscope crosshair it shows a default crosshair that which you could only change the color. It would be nice if it just uses your crosshair and use that as a noscope and the same shape of crosshair for the recoil one but with the option to change color.
> [Recoil crosshair Fuzion](https://github.com/LWSS/Fuzion/blob/master/src/Hacks/recoilcrosshair.cpp)
> [noscope crosshair](https://github.com/LWSS/Fuzion/blob/master/src/Hacks/snipercrosshair.cpp)
> 
> Thank you for your efforts.

That would be very interesting.

**Comment by Asviix** [comment]
Grenade Helper is the ultimate goal for Legit Hacking, if someone can impliment it that would be godlike
i'm not familiar with C++ but i'll try to take a look

**Comment by Asviix** [comment]
Bumping this issue in case a talented person can make it work, hasn't been able to do so myself
