### ISSUE TITLE
How to delete Aimbot  Triggerbot  and many more only left Inventory Changer ？

### ISSUE THREAD

**Issue by PHalkaid** [danielkrupinski/Osiris#3046]
How to modify it. When I press insert, the rest of the functions will disappear and only the inventory modification item？

**Comment by KurastikO** [comment]
??????

**Comment by chuqingaa** [comment]
Please forgive me for a machine translation

**Comment by chuqingaa** [comment]
I just want to share with others to modify the inventory, but not let them use hackers to harm others

**Comment by Xonn1com** [comment]
If you want to reset some options, do it in config section > delete > select what you need

**Comment by blackMasterLord** [comment]
1. Delete all files in the `Osiris/Hacks`directory except InventoryChanger and EnginePrediction.
2. Find and fix all errors in all files.

I think this is the best way.
🤨

**Comment by wemanzoz** [comment]
> 1. Delete all files in the `Osiris/Hacks`directory except InventoryChanger and EnginePrediction.
> 2. Find and fix all errors in all files.
> 
> I think this is the best way.
> 🤨

true

**Comment by caiocinel** [comment]
Isn't it easier for you to just not use the other functions? Functions will be hooked anyway, and you will be banned regardless in the same way.

Except if you make a clean sweep of the project, but I think that's silly, and it won't solve anything either
