### ISSUE TITLE
Make tabs

### ISSUE THREAD

**Issue by master-of-darkness** [danielkrupinski/Osiris#3047]
Make this tabs:
Rage  Legit  Antiaim  Visuals  Misc  Configs  Inventory changer

**Comment by Xonn1com** [comment]
Osiris isn't made for rage
Also use commas! >Rage, legit anti aim, Visuals, Misc, Configs, Inventory changer <!!!!

I'm not sure what did you mean, but some of them (tabs) are already in cheat

**Comment by Minigraymaster** [comment]
> 
> 
> Osiris isn't made for rage
> Also use commas! >Rage, legit anti aim, Visuals, Misc, Configs, Inventory changer <!!!!
> 
> I'm not sure what did you mean, but some of them (tabs) are already in cheat

Osiris have like rage,I think if general developer will made whis it was great
