### ISSUE TITLE
Add option Recoil Control System in Osiris

### ISSUE THREAD

**Issue by cheateronly123** [danielkrupinski/Osiris#3048]
It would be really nice to add a recoil control in the cheat, which could configure the weapon to have no recoil.

**Comment by HowToMakeFaceitAB** [comment]
the problem is here: there already is recoil control in the cheat, but you can't customize/configure it, it's automatic
the reason why you might not notice it is simply because it uses the smoothness of the aimbot in order to control the spray

and even then it wouldn't really be as much help, considering the cheat uses smoothness instead of speed, speed is static while smoothness is not.

**Comment by weendel11** [comment]
> the problem is here: there already is recoil control in the cheat, but you can't customize/configure it, it's automatic
> the reason why you might not notice it is simply because it uses the smoothness of the aimbot in order to control the spray
> 
> and even then it wouldn't really be as much help, considering the cheat uses smoothness instead of speed, speed is static while smoothness is not.

Yes, but it's an aimbot. I believe it would be easier to legit with a Recoil Control System, because you could configure each weapon, it would be better.

**Comment by HowToMakeFaceitAB** [comment]
> > the problem is here: there already is recoil control in the cheat, but you can't customize/configure it, it's automatic
> > the reason why you might not notice it is simply because it uses the smoothness of the aimbot in order to control the spray
> > and even then it wouldn't really be as much help, considering the cheat uses smoothness instead of speed, speed is static while smoothness is not.
> 
> Yes, but it's an aimbot. I believe it would be easier to legit with a Recoil Control System, because you could configure each weapon, it would be better.

yeah that's what i said too, but if the aimbot used speed instead of smoothness, it would be better obviously

**Comment by propane** [comment]
find the line in the aimbot where it gets the current aimPunch which is recoil and multiply it by a percentage, there you go

**Comment by techzin** [comment]
You can see a request pool that gives you an idea of how to create your own RCS #2135

**Comment by zwientje** [comment]
What @techzin said. just go to the files modified and make the same changes on the source files you have downloaded. after that just build the dll and have fun. I've' done the same and it works like a charm. 
Note that aimbot needs to be DISSABLED for it to work.
Remember that you'll have to update your source files manually when osiris gets updated. If you use what is released on github, you'll loose your RCS modifications.

https://github.com/danielkrupinski/Osiris/pull/2135/files

**Comment by cheateronly123** [comment]
> O que @techzin disse. apenas vá para os arquivos modificados e faça as mesmas alterações nos arquivos de origem que você baixou. depois disso é só construir a dll e se divertir. Eu fiz o mesmo e funciona perfeitamente.
> Observe que o aimbot precisa ser DESATIVADO para funcionar.
> Lembre-se de que você terá que atualizar seus arquivos de origem manualmente quando o osiris for atualizado. Se você usar o que é lançado no github, perderá suas modificações RCS.
> 
> https://github.com/danielkrupinski/Osiris/pull/2135/files

Can you help me discord?
