### ISSUE TITLE
ESP to big

### ISSUE THREAD

**Issue by cojo1989** [danielkrupinski/Osiris#305]
@danielkrupinski The ESP is to fucking big, ex: if you have an enemy in front of you and other enemy it`s coming from far but near to your main target the ESP text, and stuff are to fucking big !

**Comment by bruteforcehacker** [comment]
This is a mine craft Christian server

**Comment by bruteforcehacker** [comment]
Pls don’t swear

**Comment by cojo1989** [comment]
It was just to express my annong :)

**Comment by QR01** [comment]
Its more like the scaling is off. When I made a cfg it was fine. Got VAC banned. Made another acc. Started playing and the scaling was way too big. Got VAC banned anyways :(

**Comment by HECCYE** [comment]
Boy i have solution for your problem
https://www.grammarly.com/blog/to-too/

**Comment by cojo1989** [comment]
First of all english is not my main language. Second i write from my phone, third i dont give a f*** 😂😂😂. But thank you, you are so kind.

**Comment by HECCYE** [comment]
np XD
