### ISSUE TITLE
linux and vac bypass?

### ISSUE THREAD

**Issue by fallingDOWN12** [danielkrupinski/Osiris#3051]
Hey, I successfully compiled Osiris and injected it with a script on Ubuntu.

Do I need a vac bypass or something or is [this script](https://gist.githubusercontent.com/hugohabicht01/f04ab7e45daedaca34a2e6916be7fa17/raw/9f12c13a2a5c6f28335a4a4d29900db733bf28b0/load_osiris) for injecting fine?

**Comment by TobbeLiton** [comment]
how did you even compiled it? i got some error. can you maybe send your osiris.dll file?

**Comment by fallingDOWN12** [comment]
> how did you even compiled it? i got some error. can you maybe send your osiris.dll file?

run these commands after cloning the repository

`sudo apt-get update && sudo apt-get install -y libsdl2-dev gcc-10 g++-10 cmake`

`mkdir Release && cd Release && cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=gcc-10 -D CMAKE_CXX_COMPILER=g++-10 ..`
`
make -j $(nproc --all)`

**Comment by TobbeLiton** [comment]
> > how did you even compiled it? i got some error. can you maybe send your osiris.dll file?
> 
> run these commands after cloning the repository
> 
> `sudo apt-get update && sudo apt-get install -y libsdl2-dev gcc-10 g++-10 cmake`
> 
> `mkdir Release && cd Release && cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=gcc-10 -D CMAKE_CXX_COMPILER=g++-10 ..`
> 
> `make -j $(nproc --all)`

im on pc

**Comment by TobbeLiton** [comment]
can you just bring a link where i can download the dll?

**Comment by linuxer9** [comment]
daniel's vac bypass won't work on linux it's a completely different architecture.
Does linux VAC even work as effective as the windows version?
I believe that linux systems are more secure, the last time I heard about linux cheat got detected was aimtux in 2017.
anyway, try osiris yourself and see if it gets detected.

> 
> 
> can you just bring a link where i can download the dll?

he is talking about linux, there is no dll for linux, you need to build the cheat with the commands he provided above.
If you are in windows, just download this repo and compile it with visual studio.

**Comment by TobbeLiton** [comment]
> 
> If you are in windows, just download this repo and compile it with visual studio.
> 
> 

The problem is that I can't compile it says something with Osiris.vcxproj failed or something (look [here](https://github.com/danielkrupinski/Osiris/issues/3050))

(Yes I use Windows)

**Comment by JukoiDev** [comment]
> > If you are in windows, just download this repo and compile it with visual studio.
> 
> The problem is that I can't compile it says something with Osiris.vcxproj failed or something (look [here](https://github.com/danielkrupinski/Osiris/issues/3050))
> 
> (Yes I use Windows)

Dude, Linux and Windows is different!

**Comment by mxez** [comment]
You don't need VAC bypass on linux because VAC can't detect gdb injector
