### ISSUE TITLE
Create Discord or Matrix community

### ISSUE THREAD

**Issue by danielfan61a** [danielkrupinski/Osiris#3052]
Would be nice if there was a [Matrix](https://matrix.org/) group or Discord server or why not both to discuss Osiris and other stuff.

**Comment by danielfan61a** [comment]
I took the liberty of creating both and bridging them together
Matrix: https://matrix.to/#/+danielkrupinski/osiris:matrix.org
Discord: https://discord.gg/qJSMxMPuhn
Will delete if requested by daniel.

**Comment by linuxer9** [comment]
there was a discord server, but it got deleted I think, it's painful to moderate this shit and cheating community is very toxic.

**Comment by acey1337** [comment]
> there was a discord server, but it got deleted I think, it's painful to moderate this shit and cheating community is very toxic.

yeah but it wasn't owned by daniel if im not mistaken

**Comment by mdilai** [comment]
The Osiris community doesn't need non-programmers at all and Github is a perfect place for them. If you are an Osiris fan, you can create fan discord server, but don't expect anyone will go to help noobs with stupid questions for free.

**Comment by floydGG** [comment]
> The Osiris community doesn't need non-programmers at all and Github is a perfect place for them. If you are an Osiris fan, you can create fan discord server, but don't expect anyone will go to help noobs with stupid questions for free.

+1

**Comment by danielfan61a** [comment]
deleted the server.
