### ISSUE TITLE
when i kill someone, my game crashes. help

### ISSUE THREAD

**Issue by koon666** [danielkrupinski/Osiris#3054]
when I kill someone my game crashes, I don't know where to fix it someone help me. (I downloaded an old osiris)

**Comment by TobbeLiton** [comment]
If you downloaded a old version of osiris you can't ask for help. A old version is a old version and that means it is outdated and then he can't fix. I suggest you to download and try to compile the new version.

**Comment by koon666** [comment]
I dont download the new version because I like the old esp and the skin changer, I just want to know where I can fix it, for example, where is the code to fix
