### ISSUE TITLE
Feature Suggestion: Fake skill group/rank

### ISSUE THREAD

**Issue by Rosentti** [danielkrupinski/Osiris#3056]
A rank, skill group and prime that you can see.

**Comment by wemanzoz** [comment]
fake prime wont work anymore since new cs update. and why would u fake ur skill group LMAO

**Comment by playday3008** [comment]
> fake prime wont work anymore since new cs update. and why would u fake ur skill group LMAO

That's like rule 34, but "If it exist in game, there function in Osiris of it"

**Comment by caiocinel** [comment]
> fake prime wont work anymore since new cs update. and why would u fake ur skill group LMAO

To make fun of a staff in the lobby, as they are visible to everyone.

**Comment by danielfan61a** [comment]
> fake prime wont work anymore since new cs update. and why would u fake ur skill group LMAO

for epic screenshots maybe and flex on friends

**Comment by wemanzoz** [comment]
> > fake prime wont work anymore since new cs update. and why would u fake ur skill group LMAO
> 
> for epic screenshots maybe and flex on friends

but when u play with them u kept getting shitted on on ur real skill group AHAHHAHAHAHA

**Comment by caiocinel** [comment]
> but when u play with them u kept getting shitted on on ur real skill group AHAHHAHAHAHA

You don't understand the purpose of the function, it's just for you to fool your friends/lobby players, it's very useful when you don't want to get kicked out of a lobby easily.

**Comment by linuxer9** [comment]
> 
> but when u play with them u kept getting shitted on on ur real skill group AHAHHAHAHAHA

config issue.

**Comment by wemanzoz** [comment]
> > but when u play with them u kept getting shitted on on ur real skill group AHAHHAHAHAHA
> 
> You don't understand the purpose of the function, it's just for you to fool your friends/lobby players, it's very useful when you don't want to get kicked out of a lobby easily.
> 
> I'm going to do a pull-request with this function, it's not ideal for the project, but it works well.

but inside the game instead of contributing to the team you kept getting shitted on ahahhahahha
