### ISSUE TITLE
Crash on inject

### ISSUE THREAD

**Issue by alexezz21** [danielkrupinski/Osiris#3057]
Title, fix it @danielkrupinski

**Comment by Asviix** [comment]
Osiris doesn't need to be fixed, your injector needs to, and if Osiris really is the cause, just go back to a commit when it doesn't crash.

**Comment by danielfan61a** [comment]
works fine. it's your injector.

**Comment by brandii-co** [comment]
> 
> 
> Title, fix it @danielkrupinski

Try Shtreeba, it works fine for me
https://github.com/mdilai/Shtreeba

**Comment by alexezz21** [comment]
It does, sorry. Don't use SazInjector because its bugged! :)"
