### ISSUE TITLE
[QUESTION] Skin Changer lowers the TF?

### ISSUE THREAD

**Issue by Asviix** [danielkrupinski/Osiris#3058]
I use osiris only for the Radar and fast-stop
But also used Skin Changer because it was funny

but as soon as I used it, my TF dropped to red, and when I stopped, it went back to normal.

Is it just a coincidence or is the Skin Changer affecting my TF in any way ?

**Comment by danielfan61a** [comment]
it's probably some other thing you did, i use aimbot, esp inventory changer backtrack... everything basically. I have 200+ wins with osiris and green trust factor. my guess is reports.

**Comment by Asviix** [comment]
Might just be a coincidence then, I'll try using it again and see if my TF goes down, I'll let y'all know

**Comment by propane** [comment]
you probably just cheat blatantly lol

**Comment by reinzmet** [comment]
> 
> 
> it's probably some other thing you did, i use aimbot, esp inventory changer backtrack... everything basically. I have 200+ wins with osiris and green trust factor. my guess is reports.

what injector do you use?

**Comment by danielfan61a** [comment]
> > it's probably some other thing you did, i use aimbot, esp inventory changer backtrack... everything basically. I have 200+ wins with osiris and green trust factor. my guess is reports.
> 
> what injector do you use?

https://github.com/mdilai/Shtreeba, still not banned btw.
