### ISSUE TITLE
[Request] Standalone inventory changer

### ISSUE THREAD

**Issue by danielfan61a** [danielkrupinski/Osiris#3059]
this is mentioned in #3046 but with bad grammar.
I would like to see a project (sln) just for the inventory changer + case unboxings, that would be cool and more people would use it i think. please consider it. thanks.

**Comment by DumitruStepa** [comment]
He already made an inventroy changer.
https://github.com/danielkrupinski/csgo-fake-opening
here

**Comment by danielfan61a** [comment]
he didn't. it's a fork of another project of case opening only and not a skin changer/inventory changer

**Comment by wemanzoz** [comment]
download osiris, remove aimbot and everything then fix errors
 profit
