### ISSUE TITLE
Cant get any knife out of the case "opening" from the Inventory Changer tab.

### ISSUE THREAD

**Issue by ReShout876** [danielkrupinski/Osiris#3060]
I just opened over 1k cases and got NO knife, I got multiple STT Coverts (rarer than a knife) but no actual knife...
Why is it like that??

**Comment by Swiltzy** [comment]
It's normal csgo odds lol.

**Comment by ReShout876** [comment]
> It's normal csgo odds lol.

The Inventory Changer that Daniel Krupiński made had some kid of drop chance modifier.
I guess Daniel set the odds of getting a knife to 0 on Osiris??
Idk lol

**Comment by linuxer9** [comment]
because I guess knives and gloves aren't added to "caseLoot". and odds are completely random, it doesn't stick to valve odds.
https://github.com/danielkrupinski/Osiris/blob/3c5046d198aaddf7eda27c85ce4fe31b73b2bb9b/Osiris/Hacks/InventoryChanger.cpp#L933

**Comment by ReShout876** [comment]
> because I guess knives and gloves aren't added to "caseLoot". and odds are completely random, it doesn't stick to valve odds.
> 
> https://github.com/danielkrupinski/Osiris/blob/3c5046d198aaddf7eda27c85ce4fe31b73b2bb9b/Osiris/Hacks/InventoryChanger.cpp#L933

And how can I "fix" this?
Is there any way??
BTW I am a noob in coding

**Comment by danielkrupinski** [comment]
Odds have been adjusted. Now you can receive knives from Dreams and Nightmares Case and Operation Riptide Case. More to come.
