### ISSUE TITLE
[enhancement] add griefing features

### ISSUE THREAD

**Issue by danielfan61a** [danielkrupinski/Osiris#3063]
this software does it good: https://github.com/sagirilover/AnimeSoftware

- Blockbot

- WeaponSpammer (sound of switching mode on glock/famas; scoping; r8 prepare)

- 98 Nade (if you are without armor, look up, hold down the right mouse button and you will inflict 98 damage from a nade)

- Door spammer.
 etc

**Comment by mxez** [comment]
You can try fork of osiris called [NEPS](https://github.com/degeneratehyperbola/NEPS), it has some griefing functions for example blockbot. If you are playing on windows you should definitely try it.
