### ISSUE TITLE
anyway to add cloud radar

### ISSUE THREAD

**Issue by danielfan61a** [danielkrupinski/Osiris#3064]
i came across [this website](https://spirthack.me) and it has a feature called "cloud radar" which allows you to share the radar with your friends that don't have some software.
![image](https://user-images.githubusercontent.com/86361358/124393433-66cf7380-dcf2-11eb-81ca-7d1348a0c349.png)
how would you go about adding such a feature and would it be possible in osiris since it needs network stuff

**Comment by techzin** [comment]
I believe this is possible using NodeJs.

**Comment by pparadoxx** [comment]
> I believe this is possible using NodeJs.

platinum cheats used nodejs to update a website which updated the platinum cheats website & app
