### ISSUE TITLE
error 'dummy': objectconst must be initialized in config.cpp

### ISSUE THREAD

**Issue by koon666** [danielkrupinski/Osiris#3066]
I have a problem with this "dummy" in config.cpp, it always happens when I put these features to save in config: https://prnt.sc/18ukla9

this is the error: https://prnt.sc/18ukpd3

**Comment by Joth1** [comment]
Burro do karalho

**Comment by koon666** [comment]
> Burro do karalho

Entrosa n mlk esquisito
