### ISSUE TITLE
How to use on ubuntu Linux.

### ISSUE THREAD

**Issue by Smellon69** [danielkrupinski/Osiris#3067]
I have tried every method that anyone has given me and it never works. Please don't link me to another pointless page with a modified aimtux script. Tell me how to fix it instead, thanks!

**Comment by mdilai** [comment]
> Please don't link me to another pointless page with a modified aimtux script. Tell me how to fix it instead, thanks!

Nice request, sure, dude. Just attach csgo_linux64 process to any debugger such as GDB or LLDB, provide a prototype for dlopen() system call, like
’set \$dlopen = (void*(*)(char*, int)) dlopen’

And then just call this function

’call \$dlopen(\"/home/cheater/Osiris/Osiris.so\", 1)‘

Then you can close the debugger.
You're welcome.

**Comment by mxez** [comment]
Use cathook's attach script. You'll have to change path to lib file & change process name from hl2 to csgo_linux64

**Comment by syazskylex** [comment]
https://github.com/danielkrupinski/Osiris/issues/3283
