### ISSUE TITLE
Missing pattern

### ISSUE THREAD

**Issue by r6se** [danielkrupinski/Osiris#3068]
I inject using csghost  and it says failed to find pattern 17

**Comment by techzin** [comment]
i think vclient has been updated in csgo

**Comment by danielfan61a** [comment]
![image](https://user-images.githubusercontent.com/86361358/124681098-b7e09280-debf-11eb-93ed-1a6d083072c8.png)
same thing after the update, plus it crashes after a few seconds or minutes...
I use [Shtreeba](https://github.com/mdilai/Shtreeba)

**Comment by mxez** [comment]
Same on linux, except that we don't have messagebox appear

**Comment by techzin** [comment]
> Same on linux, except that we don't have messagebox appear

MessageBoxA() only works on Win32, on linux will return 0;

**Comment by mxez** [comment]
> MessageBoxA() only works on Win32, on linux will return 0;
already knew that, but didn't know that this function even exist on linux

**Comment by techzin** [comment]
> Same on linux, except that we don't have messagebox appear

if you want to solve this temporarily, go to the findPattern() function and remove the return 0;

**Comment by techzin** [comment]
in Memory.cpp

**Comment by mxez** [comment]
i'll just wait for the commit from daniel

**Comment by techzin** [comment]
![image](https://user-images.githubusercontent.com/61809691/124684245-14828400-dea5-11eb-9a7a-4dfff7c96e52.png)

**Comment by techzin** [comment]
> i'll just wait for the commit from daniel

yes, i just said to calm impatient people.

**Comment by weendel11** [comment]
> > eu só vou esperar pelo commit do Daniel
> 
> sim, acabei de dizer para acalmar pessoas impacientes.

Qual injetor tu recomenda usar?

**Comment by techzin** [comment]
> > > eu só vou esperar pelo commit do Daniel
> > 
> > 
> > sim, acabei de dizer para acalmar pessoas impacientes.
> 
> Qual injetor tu recomenda usar?

Guided Hacking Injection
![image](https://user-images.githubusercontent.com/61809691/124686876-3f230b80-deaa-11eb-8820-b8e7a7206139.png)

**Comment by weendel11** [comment]
> > > > eu só vou esperar pelo commit do Daniel
> > > 
> > > 
> > > sim, acabei de dizer para acalmar pessoas impacientes.
> > 
> > 
> > Qual injetor tu recomenda usar?
> 
> Guided Hacking Injection
> ![image](https://user-images.githubusercontent.com/61809691/124686876-3f230b80-deaa-11eb-8820-b8e7a7206139.png)

Is this Injection good? With him without a VAC? Even using Daniel Bypass?
I was using CSGhost 3.1.

**Comment by techzin** [comment]
> > > > > eu só vou esperar pelo commit do Daniel
> > > > 
> > > > 
> > > > sim, acabei de dizer para acalmar pessoas impacientes.
> > > 
> > > 
> > > Qual injetor tu recomenda usar?
> > 
> > 
> > Guided Hacking Injection
> > ![image](https://user-images.githubusercontent.com/61809691/124686876-3f230b80-deaa-11eb-8820-b8e7a7206139.png)
> 
> Is this Injection good? With him without a VAC? Even using Daniel Bypass?
> I was using CSGhost 3.1.

CSGhost also seems like a good injector.
Maybe even better than GHInjector, but I personally like GHInjector.

**Comment by weendel11** [comment]
> > > > > > eu só vou esperar pelo commit do Daniel
> > > > > 
> > > > > 
> > > > > sim, acabei de dizer para acalmar pessoas impacientes.
> > > > 
> > > > 
> > > > Qual injetor tu recomenda usar?
> > > 
> > > 
> > > Injeção de hackeamento guiado
> > > ![imagem](https://user-images.githubusercontent.com/61809691/124686876-3f230b80-deaa-11eb-8820-b8e7a7206139.png)
> > 
> > 
> > Esta injeção é boa? Com ele sem um VAC? Mesmo usando Daniel Bypass? 
> > Eu estava usando o CSGhost 3.1.
> 
> CSGhost também parece um bom injetor.
> Talvez até melhor do que o GHInjector, mas eu pessoalmente gosto do GHInjector.

How long does it use? Doesn't it cause VAC BAN? Use Daniel's Bypass?

**Comment by techzin** [comment]
Note: I'm not recommending the use of GHInjector, I'm just saying that I haven't had any problems with it.

**Comment by techzin** [comment]
> > > > > > > eu só vou esperar pelo commit do Daniel
> > > > > > 
> > > > > > 
> > > > > > sim, acabei de dizer para acalmar pessoas impacientes.
> > > > > 
> > > > > 
> > > > > Qual injetor tu recomenda usar?
> > > > 
> > > > 
> > > > Injeção de hackeamento guiado
> > > > ![imagem](https://user-images.githubusercontent.com/61809691/124686876-3f230b80-deaa-11eb-8820-b8e7a7206139.png)
> > > 
> > > 
> > > Esta injeção é boa? Com ele sem um VAC? Mesmo usando Daniel Bypass?
> > > Eu estava usando o CSGhost 3.1.
> > 
> > 
> > CSGhost também parece um bom injetor.
> > Talvez até melhor do que o GHInjector, mas eu pessoalmente gosto do GHInjector.
> 
> How long does it use? Doesn't it cause VAC BAN? Use Daniel's Bypass?

I believe that using Daniel's Bypass is not a good deal.

**Comment by weendel11** [comment]
> Note: I'm not recommending the use of GHInjector, I'm just saying that I haven't had any problems with it.

Should I do some configuration on this injector?

> > > > > > > > eu só vou esperar pelo commit do Daniel
> > > > > > > 
> > > > > > > 
> > > > > > > sim, acabei de dizer para acalmar pessoas impacientes.
> > > > > > 
> > > > > > 
> > > > > > Qual injetor tu recomenda usar?
> > > > > 
> > > > > 
> > > > > Injeção de hackeamento guiado
> > > > > ![imagem](https://user-images.githubusercontent.com/61809691/124686876-3f230b80-deaa-11eb-8820-b8e7a7206139.png)
> > > > 
> > > > 
> > > > Esta injeção é boa? Com ele sem um VAC? Mesmo usando Daniel Bypass?
> > > > Eu estava usando o CSGhost 3.1.
> > > 
> > > 
> > > CSGhost também parece um bom injetor.
> > > Talvez até melhor do que o GHInjector, mas eu pessoalmente gosto do GHInjector.
> > 
> > 
> > How long does it use? Doesn't it cause VAC BAN? Use Daniel's Bypass?
> 
> I believe that using Daniel's Bypass is not a good deal.

**Comment by techzin** [comment]
I've used it a few times in the past, had problems with trust factor.

**Comment by weendel11** [comment]
> I've used it a few times in the past, had problems with trust factor.

Should I do some configuration on this injector?

**Comment by weendel11** [comment]
Do you have a bypass that's better than Daniel's?
Serious confidence factor what?

> > > > > > > > eu só vou esperar pelo commit do Daniel
> > > > > > > 
> > > > > > > 
> > > > > > > sim, acabei de dizer para acalmar pessoas impacientes.
> > > > > > 
> > > > > > 
> > > > > > Qual injetor tu recomenda usar?
> > > > > 
> > > > > 
> > > > > Injeção de hackeamento guiado
> > > > > ![imagem](https://user-images.githubusercontent.com/61809691/124686876-3f230b80-deaa-11eb-8820-b8e7a7206139.png)
> > > > 
> > > > 
> > > > Esta injeção é boa? Com ele sem um VAC? Mesmo usando Daniel Bypass?
> > > > Eu estava usando o CSGhost 3.1.
> > > 
> > > 
> > > CSGhost também parece um bom injetor.
> > > Talvez até melhor do que o GHInjector, mas eu pessoalmente gosto do GHInjector.
> > 
> > 
> > How long does it use? Doesn't it cause VAC BAN? Use Daniel's Bypass?
> 
> I believe that using Daniel's Bypass is not a good deal.

Do you have a bypass that's better than Daniel's?
Serious confidence factor what?

**Comment by techzin** [comment]
> > Já usei algumas vezes no passado, tive problemas com o fator de confiança.
> 
> Devo fazer alguma configuração neste injetor?

It's not a good idea to mess with something in the gun if you don't have the knowledge.

**Comment by weendel11** [comment]
> > > Já usei algumas vezes no passado, tive problemas com o fator de confiança.
> > 
> > 
> > Devo fazer alguma configuração neste injetor?
> 
> It's not a good idea to mess with something in the gun if you don't have the knowledge.

can I follow this configuration of the print?

**Comment by techzin** [comment]
> > > > Já usei algumas vezes no passado, tive problemas com o fator de confiança.
> > > 
> > > 
> > > Devo fazer alguma configuração neste injetor?
> > 
> > 
> > It's not a good idea to mess with something in the gun if you don't have the knowledge.
> 
> can I follow this configuration of the print?

Yes.

**Comment by weendel11** [comment]
> > > > > Já usei algumas vezes no passado, tive problemas com o fator de confiança.
> > > > 
> > > > 
> > > > Devo fazer alguma configuração neste injetor?
> > > 
> > > 
> > > It's not a good idea to mess with something in the gun if you don't have the knowledge.
> > 
> > 
> > can I follow this configuration of the print?
> 
> Yes.

Thanks. Do you have a bypass that's better than Daniel's?
Serious confidence factor what?

**Comment by techzin** [comment]
> > > > > > Já usei algumas vezes no passado, tive problemas com o fator de confiança.
> > > > > 
> > > > > 
> > > > > Devo fazer alguma configuração neste injetor?
> > > > 
> > > > 
> > > > It's not a good idea to mess with something in the gun if you don't have the knowledge.
> > > 
> > > 
> > > can I follow this configuration of the print?
> > 
> > 
> > Yes.
> 
> Thanks. Do you have a bypass that's better than Daniel's?
> Serious confidence factor what?

Another Bypass (I didn't tested):
https://github.com/mdilai/Shtreeba

Trust Factor: https://support.steampowered.com/kb_article.php?ref=5966-WKLC-4172

**Comment by weendel11** [comment]
> > > > > > > Já usei algumas vezes no passado, tive problemas com o fator de confiança.
> > > > > > 
> > > > > > 
> > > > > > Devo fazer alguma configuração neste injetor?
> > > > > 
> > > > > 
> > > > > It's not a good idea to mess with something in the gun if you don't have the knowledge.
> > > > 
> > > > 
> > > > can I follow this configuration of the print?
> > > 
> > > 
> > > Yes.
> > 
> > 
> > Thanks. Do you have a bypass that's better than Daniel's?
> > Serious confidence factor what?
> 
> Another Bypass (I didn't tested):
> https://github.com/mdilai/Shtreeba
> 
> Trust Factor: https://support.steampowered.com/kb_article.php?ref=5966-WKLC-4172

Thanks

**Comment by weendel11** [comment]
> > > > > > > Já usei algumas vezes no passado, tive problemas com o fator de confiança.
> > > > > > 
> > > > > > 
> > > > > > Devo fazer alguma configuração neste injetor?
> > > > > 
> > > > > 
> > > > > It's not a good idea to mess with something in the gun if you don't have the knowledge.
> > > > 
> > > > 
> > > > can I follow this configuration of the print?
> > > 
> > > 
> > > Yes.
> > 
> > 
> > Thanks. Do you have a bypass that's better than Daniel's?
> > Serious confidence factor what?
> 
> Another Bypass (I didn't tested):
> https://github.com/mdilai/Shtreeba
> 
> Trust Factor: https://support.steampowered.com/kb_article.php?ref=5966-WKLC-4172

what's your discord

**Comment by MasonRuth1337** [comment]
how do u solve this issue, anyone know?

**Comment by afeer123** [comment]
游戏闪退

**Comment by weendel11** [comment]
> > > > > > > Já usei algumas vezes no passado, tive problemas com o fator de confiança.
> > > > > > 
> > > > > > 
> > > > > > Devo fazer alguma configuração neste injetor?
> > > > > 
> > > > > 
> > > > > It's not a good idea to mess with something in the gun if you don't have the knowledge.
> > > > 
> > > > 
> > > > can I follow this configuration of the print?
> > > 
> > > 
> > > Yes.
> > 
> > 
> > Thanks. Do you have a bypass that's better than Daniel's?
> > Serious confidence factor what?
> 
> Another Bypass (I didn't tested):
> https://github.com/mdilai/Shtreeba
> 
> Trust Factor: https://support.steampowered.com/kb_article.php?ref=5966-WKLC-4172



> > > > > Já usei algumas vezes no passado, tive problemas com o fator de confiança.
> > > > 
> > > > 
> > > > Devo fazer alguma configuração neste injetor?
> > > 
> > > 
> > > It's not a good idea to mess with something in the gun if you don't have the knowledge.
> > 
> > 
> > can I follow this configuration of the print?
> 
> Yes.

what's your discord?

**Comment by Xonn1com** [comment]
Shtreeba is just an injector. You can find this in issues tab.
I think that trust factor has nothing to do with the Vac Bypass, but you could get reported during the match, that's why :)
I tried to use DETECTED onetap with Daniel's Bypass and I didn't get untrusted. So it definitely works!

**Comment by H3artdown** [comment]
> 游戏闪退

wtf is that language

**Comment by Shuvi-Moro** [comment]
> > 游戏闪退
> 
> wtf is that language

https://i.imgur.com/W4qVbGQ.png
Chinese

**Comment by 0xE232FE** [comment]
The Real Translator behind Google -> https://www.deepl.com/translator

**Comment by techzin** [comment]
> O verdadeiro tradutor por trás do Google -> https://www.deepl.com/translator

lol

**Comment by danielkrupinski** [comment]
Updated.
