### ISSUE TITLE
Cheat send me on a VACation to VACanda

### ISSUE THREAD

**Issue by QR01** [danielkrupinski/Osiris#307]
5 VAC bans
1 Untrusted (after disabling triggerbot)
Please fix this cuz this cheat is absolutely amazing and has the best aimbot prolly ever. Tapped rage aimware :)

**Comment by cojo1989** [comment]
I never got VAC....

**Comment by QR01** [comment]
Im happy for u. I just made 2 accs in the last hour and both of them are banned by now. What injector u using?

**Comment by cojo1989** [comment]
Change your injector.

**Comment by QR01** [comment]
Extreme Injector

**Comment by rohan-patra** [comment]
yep it's not the cheat it's the injector hmu rohanpatra2003@gmail.com. I wrote my own injector so it isn't detected.

**Comment by JohnRich1372** [comment]
I use this on prime and I’m not banned yet.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Shaxzy** [comment]
I've used it for several months. Never gotten banned whatsoever

**Comment by MrLLD** [comment]
I was using Osiris in generated accounts for a long time, no VAC, only overwatch bans, so i decided to play "legit" only with ESP boxes On. Got VACed in likely 30 min, on my main account, with prime
