### ISSUE TITLE
QUESTION BYPASS

### ISSUE THREAD

**Issue by weendel11** [danielkrupinski/Osiris#3070]
Is it still safe to use Daniel's BYPASS after CSGO update?

**Comment by 0xE232FE** [comment]
Osiris is still safe as long as you use an undetected injector and hook WINAPI Calls Windows or hide references with Kernel Module under Linux /proc/<pid>/...

**Comment by weendel11** [comment]
> Osiris is still safe as long as you use an undetected injector and hook WINAPI Calls Windows or hide references with Kernel Module under Linux /proc//...

Which injector do you recommend?
How do I make this WINAPI
Can I use Daniel's bypass yet? Still safe after this update?
