### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#3071]
https://www.dropbox.com/s/jfoleke6qktppr1/Counter-strike%20%20Global%20Offensive%202021.07.07%20-%2014.05.06.02.mp4?dl=0
I've been playing for a while and the game starts to crash (no errors)
And when I inject cheat, an error pops up
https://i.imgur.com/iAsuQUZ.png
https://www.dropbox.com/s/mhkbzv07chi2330/Counter-strike%20%20Global%20Offensive%202021.07.07%20-%2014.14.26.03.mp4?dl=0

**Comment by xKv33n** [comment]
same....

**Comment by 0xE232FE** [comment]
Its allready work inprogress I guess.

**Comment by sarahdumby** [comment]
Hope this gets fixed soon
