### ISSUE TITLE
[crash]

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#3073]
crashes after a few minutes of gameplay....

**Comment by sarahdumby** [comment]
Crashes after around 10 minutes, get something that says pattern #17 not found as well.

**Comment by wemanzoz** [comment]
> Crashes after around 10 minutes, get something that says pattern #17 not found as well.

i removed the pattern 17 thing according to the commits. it still crashes so

**Comment by zwientje** [comment]
I made some modifications to the original source so I downloaded the source files again, and build it from scratch but I still encounter the crashes like mentioned above.

**Comment by afeer123** [comment]
> 我做了一些修改的原始来源，所以我再次下载源文件，并从头开始构建它，但我仍然遇到像上面提到的崩溃。

me too

**Comment by afeer123** [comment]
This map did not flash back 
![QQ图片20210707213216](https://user-images.githubusercontent.com/86306447/124768043-e9626800-df6a-11eb-93d7-570b81707985.png)

**Comment by afeer123** [comment]
> 此地图没有闪回
> ![QQ图片20210707213216](https://user-images.githubusercontent.com/86306447/124768043-e9626800-df6a-11eb-93d7-570b81707985.png)

no collapse

**Comment by SM9CC** [comment]
Looks like glowObjectManager and plantedC4s need new signatures

**Comment by danielkrupinski** [comment]
Windows version should no longer crash (f0db120662eb4147e88b8669eeabcf9ad466fd99).

**Comment by Ducky1434** [comment]
Still crashes my game even before I have joined a game.

**Comment by wemanzoz** [comment]
> Windows version should no longer crash (f0db120662eb4147e88b8669eeabcf9ad466fd99).

download newest buld

**Comment by Ducky1434** [comment]
Downloaded just now and it still crashes in the main menu of the game.
