### ISSUE TITLE
Crashing on linux

### ISSUE THREAD

**Issue by mxez** [danielkrupinski/Osiris#3075]
I have tried to figure out what hook can't initialize, and that's my output:

`Failed to find pattern #12!`

Patern is called glowObjectManager.

**Comment by 0xE232FE** [comment]
#3073 Its because of a Game Update! Please be aware.

**Comment by mxez** [comment]
> #3073 Its because of a Game Update! Please no more issues!

Yes i know, just telling that #12 pattern is outdated on linux, no-one did that before me

**Comment by mxez** [comment]
Another patern that is outdated is plantedC4s, `#34` one

**Comment by danielfan61a** [comment]
should be working now.

**Comment by mxez** [comment]
it is
