### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by czSmoG** [danielkrupinski/Osiris#3076]
Hello. Im 15 year old man from czechia. sorry for my bed england. Me and my friend both was playing cs:go on main account, wingman, next day after csgo update we both cant inject the osiris. We fucking need global elite 2 and thats all.
Please help im not coder/paster or jesus christ. how do i fix? Tell me. imbéciles jodidos te demandaré

**Comment by H3artdown** [comment]
wait for update its need time :D

**Comment by czSmoG** [comment]
> wait for update its need time :D

I know but it got updated 2 hours ago men

**Comment by TauCSGO** [comment]
> > wait for update its need time :D
> 
> I know but it got updated 2 hours ago men

It is a free cheat and you demand
Please close the topic

**Comment by 0xE232FE** [comment]
9f24bf663135aeaf3d0283cc69ffb1f79a882e40 Disable traceToExit() function

This doesn't solve the crash problem because the Game has been updated and something must be debugged.

Please don't open more Issues about this. There is already another one #3073

**Comment by danielfan61a** [comment]
lmao

**Comment by danielfan61a** [comment]
should be working now.

**Comment by acey1337** [comment]
> Hello. Im 15 year old man from czechia. sorry for my bed england. Me and my friend both was playing cs:go on main account, wingman, next day after csgo update we both cant inject the osiris. We fucking need global elite 2 and thats all.
> Please help im not coder/paster or jesus christ. how do i fix? Tell me. imbéciles jodidos te demandaré

im was playing on main account too using osiris men. suddenly i got pattern error and got instant red trust im wantr cry now  T-T

**Comment by danielfan61a** [comment]
cry more

**Comment by acey1337** [comment]
> cry more

NOoooOOOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOooo
