### ISSUE TITLE
Create Command Msg Box on Enter

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#3077]
Hello @danielkrupinski (or someone else who knows )
I remember with nostalgia the message when I started the cheat
I am laying the line

`interfaces->gameUI->createCommandMsgBox("TITTLE", "Content");`

in Hooks.cpp, but apparently not correct
I must be doing something wrong
Can you help me?

**Comment by mdilai** [comment]
You remembered me that i've "fixed" this some months ago but never checked if it actually work. Here you go:

```diff --git a/Osiris/SDK/GameUI.h b/Osiris/SDK/GameUI.h
index 9dfb191..dd927cc 100644
--- a/Osiris/SDK/GameUI.h
+++ b/Osiris/SDK/GameUI.h
@@ -7,5 +7,5 @@ class GameUI {
 public:
     INCONSTRUCTIBLE(GameUI)
 
-    VIRTUAL_METHOD(void, createCommandMsgBox, 20, (const char* title, const char* message, bool showOk = true, bool showCancel = false, const char* okCommand = nullptr, const char* cancelCommand = nullptr, const char* closedCommand = nullptr, const char* legend = nullptr, const char* unknown = nullptr), (this, title, message, showOk, showCancel, okCommand, cancelCommand, closedCommand, legend, unknown))
+    VIRTUAL_METHOD(void, createCommandMsgBox, 19, (const char* title, const char* message, bool showOk = true, bool showCancel = false, const char* okCommand = nullptr, const char* cancelCommand = nullptr, const char* closedCommand = nullptr, const char* legend = nullptr, const char* unknown = nullptr), (this, title, message, showOk, showCancel, okCommand, cancelCommand, closedCommand, legend, unknown))
 };
```

Check and tell if this shit really work and i'll make a pull request.

**Comment by TauCSGO** [comment]
WORKS!
Thanks

**Comment by wemanzoz** [comment]
> Hello @danielkrupinski (or someone else who knows )
> I remember with nostalgia the message when I started the cheat
> I am laying the line
> 
> `interfaces->gameUI->createCommandMsgBox("TITTLE", "Content");`
> 
> in Hooks.cpp, but apparently not correct
> I must be doing something wrong
> Can you help me?

how can i do this?
