### ISSUE TITLE
Ideas to a new version of the cheat

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#308]
Hello Daniel,
I really appreciate your work. This is one of the best open-source cheats out there!

I've been searching and I saw there are lots of users that have been suggesting new enhancements to this cheat, so I'm putting all together in this post:

 - Aimbot: a minimal damage chance, so it would shot if it is "possible" to take damage;
 - Grenade prediction: there has been a lot of people asking for this, and I think it would be great;
 - Anti-OBS: by hooking Steam overlay (thank you @Shaxzy);
 - C4 timer and defuse time check (recommended by @tirziz);
 - Grenade ESP: when enemy throws a grenade we could be capable to see it;
 - Profile changer: this would be cool to spoof our rank or level.

ATTENTION: these are just ideas, you decide what to do. I'm not saying you must do this, I'm just putting all the ideas together.
Congratulations for your work and time effort on this!

**Comment by NexSqaud** [comment]
Duplicate
