### ISSUE TITLE
Pattern error VAC?

### ISSUE THREAD

**Issue by UniqueSola** [danielkrupinski/Osiris#3081]
Heard someone got red trust factor because of this pattern error.
Will this lead to VAC ban?
I injected and crashed several times on my main account yesterday. 
Now trying to sell my knife

**Comment by blurpsk** [comment]
iq?

**Comment by wemanzoz** [comment]
i dont think that this can result to red trust factor. if u got red trust factor, go check lfg option. if you get below 10 that means that either no one playing near u yet or red trust (if u get 2-3 ppl most of the time)

**Comment by Swiltzy** [comment]
> i dont think that this can result to red trust factor. if u got red trust factor, go check lfg option. if you get below 10 that means that either no one playing near u yet or red trust (if u get 2-3 ppl most of the time)

That's just false. Seeing more or less people in LFG is not how you determine trust factor lol.

**Comment by real-Shigure** [comment]
I suggest you don't use opensource cheat on ur main account, as time goes by it may cause VAC ban.

**Comment by wemanzoz** [comment]
> > i dont think that this can result to red trust factor. if u got red trust factor, go check lfg option. if you get below 10 that means that either no one playing near u yet or red trust (if u get 2-3 ppl most of the time)
> 
> That's just false. Seeing more or less people in LFG is not how you determine trust factor, and has nothing to do with it.

i mean, its based on my experience lol. less then 20 means either no ppl play on ur location rn or u have yellow - red

**Comment by danielfan61a** [comment]
> I suggest you don't use opensource cheat on ur main account, as time goes by it may cause VAC ban.

you're a dumbass

**Comment by M3351AN** [comment]
> > I suggest you don't use opensource cheat on ur main account, as time goes by it may cause VAC ban.
> 
> you're a dumbass

But it is true,even gamesense ever get VAC detected
