### ISSUE TITLE
InventoryChanger knife issues

### ISSUE THREAD

**Issue by 2933968621** [danielkrupinski/Osiris#3082]
When I use inventory changer add butterfly knife, the content of drop butterfly knife in the game is "You cannot drop your knife" instead of "You cannot drop your butterfly knife"

**Comment by tyler82916** [comment]
lol？

**Comment by 2933968621** [comment]
> lol？[]
![csgo - 21781320](https://user-images.githubusercontent.com/53483352/124866997-e6f62180-dfef-11eb-9e21-7cfce6808453.png)
![csgo - 21781321](https://user-images.githubusercontent.com/53483352/124867003-e8bfe500-dfef-11eb-9bb5-bbcdb75f6fb0.png)
(url)

**Comment by blackMasterLord** [comment]
If you want to fix it
[CLICK](https://github.com/perilouswithadollarsign/cstrike15_src/blob/f82112a2388b841d72cb62ca48ab1846dfcc11c8/game/server/cstrike15/cs_player.cpp#L12771)

**Comment by 2933968621** [comment]
> If you want to fix it
> [CLICK](https://github.com/perilouswithadollarsign/cstrike15_src/blob/f82112a2388b841d72cb62ca48ab1846dfcc11c8/game/server/cstrike15/cs_player.cpp#L12771)

idk how change this msg;

**Comment by linuxer9** [comment]
Interesting issue, I didn't know that it shows that when you have a real knife.

**Comment by bruhmoment21** [comment]
> When I use inventory changer add butterfly knife, the content of drop butterfly knife in the game is "You cannot drop your knife" instead of "You cannot drop your butterfly knife"

blackMasterLord posted a function where `ClientPrint` is called. `ClientPrint` is basically just `TextMsg`. In your `DispatchUserMessage` hook you can check if the type is equal to 7 (cs_um_textmsg) and then parse the data. If first string is "#SFUI_Notice_CannotDropWeapon" and then set the second string to your active weapon name(figure it out how).

https://github.com/SteamDatabase/Protobufs/blob/master/csgo/cstrike15_usermessages.proto#L130
For parsing data search `bf_read` class on uc.

**Comment by danielkrupinski** [comment]
Should be ok now (1a19a50dfe4540a8ac3f08fc0abb48bea7f13042).
