### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Azdon1312** [danielkrupinski/Osiris#3083]
1>------ Build started: Project: Osiris, Configuration: Release Win32 ------
1>Config.cpp
1>EventListener.cpp
1>GameData.cpp
1>Aimbot.cpp
1>AntiAim.cpp
1>Backtrack.cpp
1>Chams.cpp
1>EnginePrediction.cpp
1>Glow.cpp
1>Sound.cpp
1>StreamProofESP.cpp
1>Triggerbot.cpp
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Hacks\StreamProofESP.cpp(5,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file Hacks\EnginePrediction.cpp)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file Hacks\Backtrack.cpp)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file EventListener.cpp)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file GameData.cpp)
1>Visuals.cpp
1>Helpers.cpp
1>MinHook.cpp
1>VmtHook.cpp
1>VmtSwap.cpp
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file Hacks\Glow.cpp)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file Hacks\AntiAim.cpp)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file Hacks\Sound.cpp)
1>InputUtil.cpp
1>Inventory.cpp
1>InventoryChanger.cpp
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(24,37): error C2039: 'to_array': is not a member of 'std'
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\nlohmann\json.hpp(25704): message : see declaration of 'std'
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(24,46): error C2275: 'Key': illegal use of this type as an expression
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(16): message : see declaration of 'Key'
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(24,51): error C2059: syntax error: '{'
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(24,51): error C2143: syntax error: missing ';' before '{'
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(24,51): error C2143: syntax error: missing ')' before ';'
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(24,51): error C2447: '{': missing function header (old-style formal list?)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(128,2): error C2059: syntax error: ')'
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(130,21): error C3536: 'keyMap': cannot be used before it is initialized
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(131,28): error C2039: 'is_sorted': is not a member of 'std::ranges'
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file Hooks\VmtHook.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xutility(2052): message : see declaration of 'std::ranges'
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file Hooks\VmtSwap.cpp)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(131,37): error C2131: expression did not evaluate to a constant
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(131,38): message : failure was caused by a read of an uninitialized symbol
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(131,38): message : see usage of 'keyMap'
1>StaticData.cpp
1>Netvars.cpp
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(140,28): error C2039: 'lower_bound': is not a member of 'std::ranges'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xutility(2052): message : see declaration of 'std::ranges'
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(140,39): error C2672: 'lower_bound': no matching overloaded function found
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(140,71): error C2780: '_FwdIt std::lower_bound(_FwdIt,_FwdIt,const _Ty &)': expects 3 arguments - 4 provided
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\algorithm(2829): message : see declaration of 'std::lower_bound'
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(140,71): error C2782: '_FwdIt std::lower_bound(_FwdIt,const _FwdIt,const _Ty &,_Pr)': template parameter '_FwdIt' is ambiguous
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xutility(4844): message : see declaration of 'std::lower_bound'
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(140,71): message : could be 'const char *'
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(140,71): message : or       'int'
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(140,71): error C2784: '_FwdIt std::lower_bound(_FwdIt,const _FwdIt,const _Ty &,_Pr)': could not deduce template argument for 'const _FwdIt' from 'const char *'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xutility(4844): message : see declaration of 'std::lower_bound'
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(141,8): error C3536: 'it': cannot be used before it is initialized
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file Hooks\MinHook.cpp)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(142,45): error C2672: 'std::distance': no matching overloaded function found
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(164,52): error C2677: binary '[': no global operator found which takes type 'const KeyBind::KeyCode' (or there is no acceptable conversion)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(166,99): error C2677: binary '[': no global operator found which takes type 'const KeyBind::KeyCode' (or there is no acceptable conversion)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(181,49): error C2677: binary '[': no global operator found which takes type 'const KeyBind::KeyCode' (or there is no acceptable conversion)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(183,96): error C2677: binary '[': no global operator found which takes type 'const KeyBind::KeyCode' (or there is no acceptable conversion)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(210,42): error C2039: 'find': is not a member of 'std::ranges'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xutility(2052): message : see declaration of 'std::ranges'
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(210,12): error C3861: 'find': identifier not found
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(211,49): error C2672: 'std::distance': no matching overloaded function found
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\InputUtil.cpp(213,86): error C2677: binary '[': no global operator found which takes type 'KeyBind::KeyCode' (or there is no acceptable conversion)
1>GUI.cpp
1>Misc.cpp
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file InventoryChanger\StaticData.cpp)
1>Hooks.cpp
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file Netvars.cpp)
1>Entity.cpp
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file Hacks\Chams.cpp)
1>GlobalVars.cpp
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file InventoryChanger\Inventory.cpp)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file Hacks\Visuals.cpp)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file Hacks\Aimbot.cpp)
1>Utils.cpp
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file Config.cpp)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file Hacks\Triggerbot.cpp)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Hacks\Misc.cpp(4,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file SDK\Entity.cpp)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\SDK\Utils.cpp(2,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file InventoryChanger\InventoryChanger.cpp)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file SDK\GlobalVars.cpp)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file Helpers.cpp)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file GUI.cpp)
1>C:\Users\Αντώνης\Desktop\Osiris-master\Osiris-master\Osiris\Helpers.h(3,10): fatal error C1083: Cannot open include file: 'numbers': No such file or directory (compiling source file Hooks.cpp)
1>Done building project "Osiris.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Azdon1312** [comment]
Any help?

**Comment by danielfan61a** [comment]
no it works, it's something you're doing wrong

**Comment by danielfan61a** [comment]
did you even download the repo
