### ISSUE TITLE
spin bot

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#3085]
Hello world! How can i add spin bot? i want to add it on the antiaim page

**Comment by linuxer9** [comment]
enter this in console:
+right;

**Comment by mdilai** [comment]
https://www.youtube.com/watch?v=UCQ8OBAGX0M

**Comment by floydGG** [comment]
you really open an issue just to ask that dumb question?

**Comment by mdilai** [comment]
Look at his registration time, he literally created GitHub account especially to ask this. :smile:

**Comment by danielfan61a** [comment]
please close this dumbass issue
