### ISSUE TITLE
Grenade Helper

### ISSUE THREAD

**Issue by Asviix** [danielkrupinski/Osiris#3086]
Bumping this issue as I've had no luck trying this myself, if a talented person can look at it and make it work it would be god like.

https://github.com/danielkrupinski/Osiris/issues/3045#issue-930676772

**Comment by linuxer9** [comment]
it's very easy, I don't know why people keep asking about it, here's what I did in my paste, got the code from sensum with a little edit, and made smoke target based on position on world not angle, smoke data are stolen from ratpoison btw, there's also LUA for aimware I think you can get nade data from it, but ratpoison data is quite rich, I got only smokes for mirage, since there's no other map worth playing in this shitty game
I'm too lazy to make a pull request
here is nadehelper.cpp
https://gist.github.com/linuxer9/ac98b67e76ac69bf3f04db417253e0fa
nadehelper.h
https://gist.github.com/linuxer9/05b926c33804fa8643a7847647345b74

add this line in SDK/Entity.h to check if equiped weapon is smoke grenade
`auto isSmoke() noexcept { return itemDefinitionIndex2() == WeaponId::SmokeGrenade; }`
and add this to present function in hooks.cpp
`SmokeHelper(ImGui::GetBackgroundDrawList());`
the rest is config and gui shit, figure it yourself.

**Comment by danielfan61a** [comment]
> it's very easy, I don't know why people keep asking about it, here's what I did in my paste, got the code from sensum with a little edit, and made smoke target based on position on world not angle, smoke data are stolen from ratpoison btw, there's also LUA for aimware I think you can get nade data from it, but ratpoison data is quite rich, I got only smokes for mirage, since there's no other map worth playing in this shitty game
> I'm too lazy to make a pull request
> here is nadehelper.cpp
> https://gist.github.com/linuxer9/ac98b67e76ac69bf3f04db417253e0fa
> nadehelper.h
> https://gist.github.com/linuxer9/05b926c33804fa8643a7847647345b74
> 
> add this line in SDK/Entity.h to check if equiped weapon is smoke grenade
> `auto isSmoke() noexcept { return itemDefinitionIndex2() == WeaponId::SmokeGrenade; }`
> and add this to present function in hooks.cpp
> `SmokeHelper(ImGui::GetBackgroundDrawList());`
> the rest is config and gui shit, figure it yourself.

open a pull request

**Comment by n0verify** [comment]
i got this working but i cant figure out making it work for different maps

**Comment by n0verify** [comment]
> it's very easy, I don't know why people keep asking about it, here's what I did in my paste, got the code from sensum with a little edit, and made smoke target based on position on world not angle, smoke data are stolen from ratpoison btw, there's also LUA for aimware I think you can get nade data from it, but ratpoison data is quite rich, I got only smokes for mirage, since there's no other map worth playing in this shitty game
> I'm too lazy to make a pull request
> here is nadehelper.cpp
> https://gist.github.com/linuxer9/ac98b67e76ac69bf3f04db417253e0fa
> nadehelper.h
> https://gist.github.com/linuxer9/05b926c33804fa8643a7847647345b74
> 
> add this line in SDK/Entity.h to check if equiped weapon is smoke grenade
> `auto isSmoke() noexcept { return itemDefinitionIndex2() == WeaponId::SmokeGrenade; }`
> and add this to present function in hooks.cpp
> `SmokeHelper(ImGui::GetBackgroundDrawList());`
> the rest is config and gui shit, figure it yourself.

got this working for mirage, now how do i go about making other maps work? cant figure it out :(

**Comment by linuxer9** [comment]
> got this working for mirage, now how do i go about making other maps work? cant figure it out :(

paste them from [here](https://github.com/RatPoison-dev/RatPoison/tree/master/settings/NadeHelper) using the same structure, you can add a check for map name like this:

```
GrenadeData* currentLevel;
switch(interfaces->engine->getLevelName())
{
   case "mirage":
        currentLevel = &Mirage;
        break;
   case "inferno":
        currentLevel = &Inferno;
        break;
...
}
```
and in the loop replace this
`for (const auto& it : Mirage)`
with something like this:
`for (const auto& it : *currentLevel)`
you can also call the previous switch-case once when the player join the match, no need to repeat it

**Comment by n0verify** [comment]
> > got this working for mirage, now how do i go about making other maps work? cant figure it out :(
> 
> paste them from [here](https://github.com/RatPoison-dev/RatPoison/tree/master/settings/NadeHelper) using the same structure, you can add a check for map name like this:
> 
> ```
> GrenadeData* currentLevel;
> switch(interfaces->engine->getLevelName())
> {
>    case "mirage":
>         currentLevel = &Mirage;
>         break;
>    case "inferno":
>         currentLevel = &Inferno;
>         break;
> ...
> }
> ```
> 
> and in the loop replace this
> `for (const auto& it : Mirage)`
> with something like this:
> `for (const auto& it : *currentLevel)`
> you can also call the previous switch-case once when the player join the match, no need to repeat it
> also remember to check if currentLevel isn't null

thank you so much! got it all working with proper lines drawn to each correct smoke point. i converted the rest of the ratpoison smoke data aswell if you would like it

**Comment by n0verify** [comment]
> it's very easy, I don't know why people keep asking about it, here's what I did in my paste, got the code from sensum with a little edit, and made smoke target based on position on world not angle, smoke data are stolen from ratpoison btw, there's also LUA for aimware I think you can get nade data from it, but ratpoison data is quite rich, I got only smokes for mirage, since there's no other map worth playing in this shitty game
> I'm too lazy to make a pull request
> here is nadehelper.cpp
> https://gist.github.com/linuxer9/ac98b67e76ac69bf3f04db417253e0fa
> nadehelper.h
> https://gist.github.com/linuxer9/05b926c33804fa8643a7847647345b74
> 
> add this line in SDK/Entity.h to check if equiped weapon is smoke grenade
> `auto isSmoke() noexcept { return itemDefinitionIndex2() == WeaponId::SmokeGrenade; }`
> and add this to present function in hooks.cpp
> `SmokeHelper(ImGui::GetBackgroundDrawList());`
> the rest is config and gui shit, figure it yourself.

i have fixed a few bugs, such as circles not appearing when you look down and such, but whenever smoke helper is on, if my smoke auto equips while im in the buy menu it crashes. how would i go about fixing this?

**Comment by n0verify** [comment]
> it's very easy, I don't know why people keep asking about it, here's what I did in my paste, got the code from sensum with a little edit, and made smoke target based on position on world not angle, smoke data are stolen from ratpoison btw, there's also LUA for aimware I think you can get nade data from it, but ratpoison data is quite rich, I got only smokes for mirage, since there's no other map worth playing in this shitty game
> I'm too lazy to make a pull request
> here is nadehelper.cpp
> https://gist.github.com/linuxer9/ac98b67e76ac69bf3f04db417253e0fa
> nadehelper.h
> https://gist.github.com/linuxer9/05b926c33804fa8643a7847647345b74
> 
> add this line in SDK/Entity.h to check if equiped weapon is smoke grenade
> `auto isSmoke() noexcept { return itemDefinitionIndex2() == WeaponId::SmokeGrenade; }`
> and add this to present function in hooks.cpp
> `SmokeHelper(ImGui::GetBackgroundDrawList());`
> the rest is config and gui shit, figure it yourself.

there is a bug where you crash if you equip a smoke while in the buy menu. 

I fixed it by adding the following bool to check if player can shoot
`bool can_shoot()
{
    const int centerx = GetSystemMetrics(SM_CXSCREEN) / 2;
    const int centery = GetSystemMetrics(SM_CYSCREEN) / 2;
    const int difference = 15;
    const int one = centerx - difference;
    const int two = centerx + difference;
    const int three = centery - difference;
    const int four = centery + difference;
    POINT cursor_position;
    GetCursorPos(&cursor_position);

    if (cursor_position.x < one || cursor_position.x > two || cursor_position.y < three || cursor_position.y > four)
        return false;

    return true;
}`

and also add this before the loop
`if (!can_shoot())
            return;`

**Comment by cheateronly123** [comment]
> > it's very easy, I don't know why people keep asking about it, here's what I did in my paste, got the code from sensum with a little edit, and made smoke target based on position on world not angle, smoke data are stolen from ratpoison btw, there's also LUA for aimware I think you can get nade data from it, but ratpoison data is quite rich, I got only smokes for mirage, since there's no other map worth playing in this shitty game
> > I'm too lazy to make a pull request
> > here is nadehelper.cpp
> > https://gist.github.com/linuxer9/ac98b67e76ac69bf3f04db417253e0fa
> > nadehelper.h
> > https://gist.github.com/linuxer9/05b926c33804fa8643a7847647345b74
> > add this line in SDK/Entity.h to check if equiped weapon is smoke grenade
> > `auto isSmoke() noexcept { return itemDefinitionIndex2() == WeaponId::SmokeGrenade; }`
> > and add this to present function in hooks.cpp
> > `SmokeHelper(ImGui::GetBackgroundDrawList());`
> > the rest is config and gui shit, figure it yourself.
> 
> there is a bug where you crash if you equip a smoke while in the buy menu.
> 
> I fixed it by adding [this](https://ghostbin.com/paste/DdKfz) to check if player can shoot
> 
> and also add this before the loop
> `if (!can_shoot()) return;`

Can you send me your complete file? For me it was wrong.
