### ISSUE TITLE
ESP font size

### ISSUE THREAD

**Issue by cojo1989** [danielkrupinski/Osiris#309]
How can i mod the ESP font size? Thank you !

**Comment by danielkrupinski** [comment]
You can create your own font or use game's font (`vgui_spew_fonts` command shows available fonts with their size etc.)

**Comment by cojo1989** [comment]
I dont want to change the font i just want to make a smaller size.

**Comment by danielkrupinski** [comment]
There are several sizes for each font in vgui_spew_fonts output. Just pick smaller one.

**Comment by danielkrupinski** [comment]
I've added font selection which allows you to use any game font for esp (there are more than 200 of them, in many sizes).
