### ISSUE TITLE
Game crashes in main menu when I inject

### ISSUE THREAD

**Issue by Ducky1434** [danielkrupinski/Osiris#3091]
Pls god I need all the help I need pls god somebody help.

**Comment by demitriusdemarcus** [comment]
> Pls god I need all the help I need pls god somebody help.

Download the latest version, compile and inject. If it still crashes, attach a debugger to CS:GO and fix.

**Comment by wabbs1** [comment]
where do I get a debugger

**Comment by mxez** [comment]
> where do I get a debugger

Google exist, find it by yourself, it is not that hard

**Comment by demitriusdemarcus** [comment]
> where do I get a debugger

visual studio can be used to debug. If you don't even know simple things such as debug a program or search how to do it you shouldn't touch any source code. Just download a DLL instead

**Comment by Ducky1434** [comment]
> you shouldn't touch any source code.

I don't want to touch any source code I just want to build my cheat and play.

**Comment by demitriusdemarcus** [comment]
> > you shouldn't touch any source code.
> 
> 
> 
> I don't want to touch any source code I just want to build my cheat and play. 

Building "your cheat" requires touching a source code so i don't really understand what you mean. As i said previously, download the latest source, compile and debug if it crashes.
