### ISSUE TITLE
Vac bypass outdated

### ISSUE THREAD

**Issue by tyler82916** [danielkrupinski/Osiris#3092]
Is daniels vac bypass loader or vac bypass dll still working. It has been sooo looong since last update...

**Comment by linuxer9** [comment]
it's working, try it yourself!
load vac bypass and cheat engine on throw away account.

**Comment by danielfan61a** [comment]
change the misleading title.

**Comment by Xonn1com** [comment]
If software isn't updated for a long time, it doesn't mean it is outdated.
also add question mark to your title..
