### ISSUE TITLE
Only shoot on guaranteed shot

### ISSUE THREAD

**Issue by snoopchallenge** [danielkrupinski/Osiris#3093]
I have no idea if this is an option or if there is a way to do this

**Comment by mxez** [comment]
Try playing with custom "Max aim inaccuracy" and "Max shot inaccuracy"
Maybe they are what you need

**Comment by wemanzoz** [comment]
> Try playing with custom "Max aim inaccuracy" and "Max shot inaccuracy"
> Maybe they are what you need

isnt max aim inaccuracy and maxshot rcs?

**Comment by wemanzoz** [comment]
> I have no idea if this is an option or if there is a way to do this
> 

wdym? if its triggerbot ye osiris have triggerbot. if its triggerhitchance. its entirely different then

**Comment by linuxer9** [comment]
> 
> 
> > Try playing with custom "Max aim inaccuracy" and "Max shot inaccuracy"
> > Maybe they are what you need
> 
> isnt max aim inaccuracy and maxshot rcs?

no, it isn't. they told the aimbot to work at certain accuracy, i.e. it won't shoot (or snap) if you are in are or moving (minimizing the chances you miss). it's similar to hitchance system, but it's more inferior obviously.

**Comment by snoopchallenge** [comment]
o im dumb i meant in aimbot im assuming setting max aim inaccuracy and max shot inaccuracy to 0 wont shoot if there is any chance of missing
