### ISSUE TITLE
QUESTION PROTECT

### ISSUE THREAD

**Issue by cheateronly123** [danielkrupinski/Osiris#3095]
What can I use besides bypass loader to avoid vacnet?
Protect DLL?

**Comment by demitriusdemarcus** [comment]
> What can I use besides bypass loader to avoid vacnet?
> Protect DLL?

Well I don't really understand what you really mean but imma try to answer your question how I comprehend it. The VAC bypass loader only protects you against VAC and not VAC-net. VAC-net is an AI that sends suspected cheaters to overwatch automatically. The only way to bypass it while using Osiris is not raging / using rage AA. Protecting the DLL ( probably VMprotecting it based on your question) does not do anything good.

**Comment by weendel11** [comment]
> > O que posso usar além do bypass loader para evitar o vacnet? 
> > Proteger DLL?
> 
> Bem, eu realmente não entendo o que você realmente quer dizer, mas vou tentar responder à sua pergunta como eu a compreendo. O carregador de bypass VAC protege você apenas contra VAC e não VAC-net. VAC-net é uma IA que envia trapaceiros suspeitos para vigiar automaticamente. A única maneira de contorná-lo durante o uso de Osiris é não usar o raging / rage AA. Proteger a DLL (provavelmente VMproteger com base na sua pergunta) não adianta nada.

But how do I use Osiris without receiving the VAC?

**Comment by wemanzoz** [comment]
> > What can I use besides bypass loader to avoid vacnet?
> > Protect DLL?
> 
> Well I don't really understand what you really mean but imma try to answer your question how I comprehend it. The VAC bypass loader only protects you against VAC and not VAC-net. VAC-net is an AI that sends suspected cheaters to overwatch automatically. The only way to bypass it while using Osiris is not raging / using rage AA. Protecting the DLL ( probably VMprotecting it based on your question) does not do anything good.

I dont think theres any VAC-NET bypass. all you can do is play as "legit" as you can

**Comment by demitriusdemarcus** [comment]
> > > O que posso usar além do bypass loader para evitar o vacnet? 
> 
> > > Proteger DLL?
> 
> > 
> 
> > Bem, eu realmente não entendo o que você realmente quer dizer, mas vou tentar responder à sua pergunta como eu a compreendo. O carregador de bypass VAC protege você apenas contra VAC e não VAC-net. VAC-net é uma IA que envia trapaceiros suspeitos para vigiar automaticamente. A única maneira de contorná-lo durante o uso de Osiris é não usar o raging / rage AA. Proteger a DLL (provavelmente VMproteger com base na sua pergunta) não adianta nada.
> 
> 
> 
> But how do I use Osiris without receiving the VAC?

Modify the source code, use the vac bypass loader

**Comment by demitriusdemarcus** [comment]
> > > What can I use besides bypass loader to avoid vacnet?
> > > Protect DLL?
> > 
> > Well I don't really understand what you really mean but imma try to answer your question how I comprehend it. The VAC bypass loader only protects you against VAC and not VAC-net. VAC-net is an AI that sends suspected cheaters to overwatch automatically. The only way to bypass it while using Osiris is not raging / using rage AA. Protecting the DLL ( probably VMprotecting it based on your question) does not do anything good.
> 
> I dont think theres any VAC-NET bypass. all you can do is play as "legit" as you can

Playing as legit as possible = vac net bypass

**Comment by weendel11** [comment]
> Modify the source code

How do I modify source code?

**Comment by demitriusdemarcus** [comment]
> > Modify the source code
> 
> 
> 
> How do I modify source code?

Learncpp.com

**Comment by weendel11** [comment]
> Learncpp.com

Which chapter?

**Comment by demitriusdemarcus** [comment]
> > Learncpp.com
> 
> Which chapter?

Read until you understand c++ basics. There is no definitive chapter for you. If you want to modify the source without any errors you need to spend time learning.
