### ISSUE TITLE
knife/gloves from cases drop

### ISSUE THREAD

**Issue by rbt234** [danielkrupinski/Osiris#3099]
i openned like 200+ cases and i didnt drop any knife/glove, could change chance drop or something like that?

**Comment by ReShout876** [comment]
I had the same problem.
#3060

**Comment by rbt234** [comment]
maybe @danielkrupinski   he can help us

**Comment by Asviix** [comment]
I'll take a look into it asap, I'll come back if I can get a fix to work

**Comment by danielkrupinski** [comment]
Now you can receive knives from Dreams and Nightmares Case and Operation Riptide Case. More to come.
