### ISSUE TITLE
Exception thrown at 0x45F6BD5D in csgo.exe: 0xC0000005: Access violation reading location 0x00000000.

### ISSUE THREAD

**Issue by Ducky1434** [danielkrupinski/Osiris#3100]
So recently I submitted an issue basicly saying that osiris crashed my game the moment I injected it and some guy recommended I attach a debugger to csgo to see what the issue was and this is what I got.

**Comment by wemanzoz** [comment]
Download newest source, compile it

**Comment by demitriusdemarcus** [comment]
> So recently I submitted an issue basicly saying that osiris crashed my game the moment I injected it and some guy recommended I attach a debugger to csgo to see what the issue was and this is what I got.

code issue. Make sure you are using the latest orisis, has all prerequisites installed, compile in release x86  using latest visual studio 2019
