### ISSUE TITLE
can somebody help me compile osiris?

### ISSUE THREAD

**Issue by zEx121** [danielkrupinski/Osiris#3101]
i get a lot of errors and i cant fix it

https://prnt.sc/1ajnikl
https://prnt.sc/1ajnonc
https://prnt.sc/1ajntur

**Comment by zEx121** [comment]
Any help?

**Comment by AuG-24** [comment]
Are you trying to compile a custom version of Osiris or  is it the vanilla one (downloaded fresh from github)?
 The first step would be to make sure that you have all dependencies installed (listed on the main page)
Re-install visual studio 2019 community  if issues persist

**Comment by demitriusdemarcus** [comment]
> Any help?

download latest osiris and try again
