### ISSUE TITLE
Butterfly knife animation fix 

### ISSUE THREAD

**Issue by MasonRuth1337** [danielkrupinski/Osiris#3102]
When im in the private games it works fine, the animation is smooth. but matchmaking, for some reason it skips and stutters during the animation. Anyone have a fix?

(using old osiris when it had skinchanger not inv changer) any help appreciated :)

**Comment by wemanzoz** [comment]
you should consider moving into inv changer update

**Comment by rosesware** [comment]
> you should consider moving into inv changer update

Agreed. Inventory Changer is much more solid with skins animations in general.
