### ISSUE TITLE
can i have dll

### ISSUE THREAD

**Issue by plexiigg2323** [danielkrupinski/Osiris#3106]
where can i find dll for osiris cus i have too little space on my pc to compile

**Comment by KurastikO** [comment]
.dlls can't be shared through github

**Comment by plexiigg2323** [comment]
i got visual studio but i have 5 gb left!!!!!!!!!!!!

**Comment by Cassiedee** [comment]
> i got visual studio but i have 5 gb left!!!!!!!!!!!!

Use something like GitHub Workflows to compile the dll.
