### ISSUE TITLE
QUESTION HELP

### ISSUE THREAD

**Issue by cheateronly123** [danielkrupinski/Osiris#3108]
Which injector is good to use together with Osiris? IN THE VAC?

**Comment by tusharborkar360** [comment]
Go with latest version of Extreme Injector. It's available on Github. After downloading, you have to change settings to these:- 1. Enable Stealth Inject. 2.Manual Mapping Injection Method. 3.Always start the Injector in Secure mode.
Along with the Injector download Daniel's VAC Bypass Loader. 
I'm using these since last 2 months with Osiris and I haven't got any VAC Ban till now.
Don't use aimbot and triggerbot... It'll increase the chance of VAC Ban. Always play Legit with Radar hack.. Chams... ESP

**Comment by demitriusdemarcus** [comment]
> Don't use aimbot and triggerbot... It'll increase the chance of VAC Ban. Always play Legit with Radar hack.. Chams... ESP

There are no features currently on stock osiris that can cause a VAC ban. Aimbot and triggerbot is never related to a VAC whatsoever. It is as detectable as every other features in Osiris

**Comment by floydGG** [comment]
I use shtreeba using it almost 7 months, no VAC

**Comment by cheateronly123** [comment]
> Eu uso shtreeba usando quase 7 meses, sem VAC

PRIME?

**Comment by cheateronly123** [comment]
> Vá com a última versão do Extreme Injector. Está disponível no Github. Após o download, você deve alterar as configurações para: - 1. Habilite o Stealth Inject. 2. Método de injeção de mapeamento manual. 3. Sempre inicie o injetor no modo Seguro.
> Junto com o injetor, baixe o carregador de bypass VAC de Daniel.
> Estou usando isso desde os últimos 2 meses com o Osiris e não tenho nenhum VAC Ban até agora.
> Não use aimbot e triggerbot ... Isso aumentará a chance de VAC Ban. Sempre jogue Legit com Radar hack .. Chams ... ESP

PRIME? Thanks

**Comment by cheateronly123** [comment]
> Eu uso shtreeba usando quase 7 meses, sem VAC

Do you use it on the prime account?

**Comment by cheateronly123** [comment]
> Vá com a última versão do Extreme Injector. Está disponível no Github. Após o download, você deve alterar as configurações para: - 1. Habilite o Stealth Inject. 2. Método de injeção de mapeamento manual. 3. Sempre inicie o injetor no modo Seguro.
> Junto com o injetor, baixe o carregador de bypass VAC de Daniel.
> Estou usando isso dos últimos 2 meses com o Osiris e não tenho nenhum VAC Ban até agora.
> Não use aimbot e triggerbot ... Isso aumentará uma chance de VAC Ban. Sempre jogue Legit com Radar hack .. Chams ... ESP

Do you use it on the prime account?

**Comment by floydGG** [comment]
> > Eu uso shtreeba usando quase 7 meses, sem VAC
> 
> Do you use it on the prime account?

yes, supreme rank now

**Comment by Shuvi-Moro** [comment]
> > > Eu uso shtreeba usando quase 7 meses, sem VAC
> > 
> > 
> > Do you use it on the prime account?
> 
> yes, supreme rank now

How can you use it if it doesn't work with the latest version of Osiris?

If it's not difficult, I would like to get a link to download your version of Osiris!

https://www.dropbox.com/s/7dfpcmz3plt0c7w/NKPzKPYHD2.mp4?dl=0

**Comment by floydGG** [comment]
> > > > Eu uso shtreeba usando quase 7 meses, sem VAC
> > > 
> > > 
> > > Do you use it on the prime account?
> > 
> > 
> > yes, supreme rank now
> 
> How can you use it if it doesn't work with the latest version of Osiris?
> 
> If it's not difficult, I would like to get a link to download your version of Osiris!
> 
> https://www.dropbox.com/s/7dfpcmz3plt0c7w/NKPzKPYHD2.mp4?dl=0

What is exactly didn't work with latest Osiris? the injector? or what? Mine working fine, i build once and still working till now.
I only updated Osiris dll

**Comment by cheateronly123** [comment]
> > > Eu uso shtreeba usando quase 7 meses, sem VAC
> > 
> > 
> > Você usa na conta principal?
> 
> sim, classificação suprema agora



> > > > > Eu uso shtreeba usando quase 7 meses, sem VAC
> > > > 
> > > > 
> > > > Você usa na conta principal?
> > > 
> > > 
> > > sim, classificação suprema agora
> > 
> > 
> > Como você pode usá-lo se ele não funciona com a versão mais recente do Osiris?
> > Se não for difícil, gostaria de obter um link para baixar sua versão do Osiris!
> > https://www.dropbox.com/s/7dfpcmz3plt0c7w/NKPzKPYHD2.mp4?dl=0
> 
> O que exatamente não funcionou com o último Osiris? o injetor? ou o que? O meu está funcionando bem, eu construí uma vez e ainda estou trabalhando até agora.
> Eu só atualizei Osiris dll

Did you use VMProtect?

**Comment by cheateronly123** [comment]
> > > > > Eu uso shtreeba usando quase 7 meses, sem VAC
> > > > 
> > > > 
> > > > Do you use it on the prime account?
> > > 
> > > 
> > > yes, supreme rank now
> > 
> > 
> > How can you use it if it doesn't work with the latest version of Osiris?
> > If it's not difficult, I would like to get a link to download your version of Osiris!
> > https://www.dropbox.com/s/7dfpcmz3plt0c7w/NKPzKPYHD2.mp4?dl=0
> 
> What is exactly didn't work with latest Osiris? the injector? or what? Mine working fine, i build once and still working till now.
> I only updated Osiris dll

Did you use VMProtect?

**Comment by floydGG** [comment]
> > > > > > Eu uso shtreeba usando quase 7 meses, sem VAC
> > > > > 
> > > > > 
> > > > > Do you use it on the prime account?
> > > > 
> > > > 
> > > > yes, supreme rank now
> > > 
> > > 
> > > How can you use it if it doesn't work with the latest version of Osiris?
> > > If it's not difficult, I would like to get a link to download your version of Osiris!
> > > https://www.dropbox.com/s/7dfpcmz3plt0c7w/NKPzKPYHD2.mp4?dl=0
> > 
> > 
> > What is exactly didn't work with latest Osiris? the injector? or what? Mine working fine, i build once and still working till now.
> > I only updated Osiris dll
> 
> Did you use VMProtect?

Nope, never.
Only adding some junkcodes

**Comment by cheateronly123** [comment]
> > > > > > > Eu uso shtreeba usando quase 7 meses, sem VAC
> > > > > > 
> > > > > > 
> > > > > > Do you use it on the prime account?
> > > > > 
> > > > > 
> > > > > yes, supreme rank now
> > > > 
> > > > 
> > > > How can you use it if it doesn't work with the latest version of Osiris?
> > > > If it's not difficult, I would like to get a link to download your version of Osiris!
> > > > https://www.dropbox.com/s/7dfpcmz3plt0c7w/NKPzKPYHD2.mp4?dl=0
> > > 
> > > 
> > > What is exactly didn't work with latest Osiris? the injector? or what? Mine working fine, i build once and still working till now.
> > > I only updated Osiris dll
> > 
> > 
> > Did you use VMProtect?
> 
> Nope, never.
> Only adding some junkcodes

Thanks.

**Comment by floydGG** [comment]
> > > > > > > > Eu uso shtreeba usando quase 7 meses, sem VAC
> > > > > > > 
> > > > > > > 
> > > > > > > Do you use it on the prime account?
> > > > > > 
> > > > > > 
> > > > > > yes, supreme rank now
> > > > > 
> > > > > 
> > > > > How can you use it if it doesn't work with the latest version of Osiris?
> > > > > If it's not difficult, I would like to get a link to download your version of Osiris!
> > > > > https://www.dropbox.com/s/7dfpcmz3plt0c7w/NKPzKPYHD2.mp4?dl=0
> > > > 
> > > > 
> > > > What is exactly didn't work with latest Osiris? the injector? or what? Mine working fine, i build once and still working till now.
> > > > I only updated Osiris dll
> > > 
> > > 
> > > Did you use VMProtect?
> > 
> > 
> > Nope, never.
> > Only adding some junkcodes
> 
> Thanks.

Make sure u use it with VAC Bypass from @danielkrupinski aswell.
GLHF

**Comment by Shuvi-Moro** [comment]
I can't use the latest version of shtreeba !!!

**Comment by Shuvi-Moro** [comment]
My cs go crashes

**Comment by floydGG** [comment]
> I can't use the latest version of shtreeba !!!

Compile it yourself, don't use the precompiled version.

**Comment by Shuvi-Moro** [comment]
> > I can't use the latest version of shtreeba !!!
> 
> Compile it yourself, don't use the precompiled version.

How do I get an exe file? I can't use with a compiled dll file with an old exe

**Comment by floydGG** [comment]
> > > I can't use the latest version of shtreeba !!!
> > 
> > 
> > Compile it yourself, don't use the precompiled version.
> 
> How do I get an exe file? I can't use with a compiled dll file with an old exe

https://github.com/mdilai/Shtreeba#compiling-from-source All you need is just to read brother

**Comment by Shuvi-Moro** [comment]
Oh thnx

**Comment by Shuvi-Moro** [comment]
But I don't get the exe file

**Comment by Shuvi-Moro** [comment]
https://i.imgur.com/C5mSxFz.png

**Comment by Shuvi-Moro** [comment]
What am I doing wrong

**Comment by Shuvi-Moro** [comment]
np im idiot

**Comment by Shuvi-Moro** [comment]
I cant use 
https://www.dropbox.com/s/wjn5uxlawr1pzwn/uIZx6hm2Vf.mp4?dl=0

**Comment by floydGG** [comment]
Are u sure that's the latest version of Osiris? Well i'm in game right now with Shtreeba injector, working fine.

**Comment by Shuvi-Moro** [comment]
How

**Comment by Shuvi-Moro** [comment]
https://www.dropbox.com/s/4z4fu6g05sbqrsp/e72LjLopax.mp4?dl=0

**Comment by Shuvi-Moro** [comment]
It doesn't work

**Comment by Shuvi-Moro** [comment]
> Are u sure that's the latest version of Osiris? Well i'm in game right now with Shtreeba injector, working fine.

In short, okay, thank you for your help and good night

**Comment by gr1ndy** [comment]
> > > > > > > Eu uso shtreeba usando quase 7 meses, sem VAC
> > > > > > 
> > > > > > 
> > > > > > Do you use it on the prime account?
> > > > > 
> > > > > 
> > > > > yes, supreme rank now
> > > > 
> > > > 
> > > > How can you use it if it doesn't work with the latest version of Osiris?
> > > > If it's not difficult, I would like to get a link to download your version of Osiris!
> > > > https://www.dropbox.com/s/7dfpcmz3plt0c7w/NKPzKPYHD2.mp4?dl=0
> > > 
> > > 
> > > What is exactly didn't work with latest Osiris? the injector? or what? Mine working fine, i build once and still working till now.
> > > I only updated Osiris dll
> > 
> > 
> > Did you use VMProtect?
> 
> Nope, never.
> Only adding some junkcodes

junk code aint shit bruh stop using that kekw

**Comment by floydGG** [comment]
> > > > > > > > Eu uso shtreeba usando quase 7 meses, sem VAC
> > > > > > > 
> > > > > > > 
> > > > > > > Do you use it on the prime account?
> > > > > > 
> > > > > > 
> > > > > > yes, supreme rank now
> > > > > 
> > > > > 
> > > > > How can you use it if it doesn't work with the latest version of Osiris?
> > > > > If it's not difficult, I would like to get a link to download your version of Osiris!
> > > > > https://www.dropbox.com/s/7dfpcmz3plt0c7w/NKPzKPYHD2.mp4?dl=0
> > > > 
> > > > 
> > > > What is exactly didn't work with latest Osiris? the injector? or what? Mine working fine, i build once and still working till now.
> > > > I only updated Osiris dll
> > > 
> > > 
> > > Did you use VMProtect?
> > 
> > 
> > Nope, never.
> > Only adding some junkcodes
> 
> junk code aint shit bruh stop using that kekw

old habits

**Comment by demitriusdemarcus** [comment]
> old habits
 Then learn to fix them

**Comment by floydGG** [comment]
> > old habits
> 
> Then learn to fix those habits

yes, sir!
