### ISSUE TITLE
Need a little help about Recoil Crosshair.

### ISSUE THREAD

**Issue by floydGG** [danielkrupinski/Osiris#3109]
![Capture](https://user-images.githubusercontent.com/53382214/126045126-caf60e81-0de8-45a2-8230-fc55ab416c19.JPG)

I managed to delete those 4 extras lines, and wanted to make it dot only.
I wanted to size up the dot with outline, but when i change those codes the outline messed up a bit.
Any help maybe?  excuses for my English

**Comment by blackMasterLord** [comment]
```
static void drawCrosshair(ImDrawList* drawList, const ImVec2& pos, ImU32 color) noexcept
{
    drawList->AddCircleFilled(pos, miscConfig.recoilCrosshair.thickness, color, 360);
    drawList->AddCircle(pos, miscConfig.recoilCrosshair.thickness, IM_COL32_BLACK, 360, 0.5);
}
```

**Comment by floydGG** [comment]
> ```
> static void drawCrosshair(ImDrawList* drawList, const ImVec2& pos, ImU32 color) noexcept
> {
>     drawList->AddCircleFilled(pos, miscConfig.recoilCrosshair.thickness, color, 360);
>     drawList->AddCircle(pos, miscConfig.recoilCrosshair.thickness, IM_COL32_BLACK, 360, 0.5);
> }
> ```

Thank you!
