### ISSUE TITLE
[Add a feature] Antiaim

### ISSUE THREAD

**Issue by yEsPaP** [danielkrupinski/Osiris#311]
So, I myself tried to add antiaim but i go a build error that i couldn't fix. Could you please try to add antiaim :)

**Comment by cojo1989** [comment]
I would like to see @danielkrupinski adding just legit AA [desync]

**Comment by EGTLoneWolf** [comment]
too early i would say , menu still need work

**Comment by yEsPaP** [comment]
> I would like to see @danielkrupinski adding just legit AA [desync]

thats what i tried UwU

**Comment by WeasselDW** [comment]
pld close @danielkrupinski

**Comment by l0ccy** [comment]
+++1

**Comment by yEsPaP** [comment]
closed
