### ISSUE TITLE
Cheat without inject

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#3110]
What about a cheat (that is, a dll file) to replace some dll file that is used when loading (and is not critical for launch)
There are two problems.
Which file to replace?
And is it safe?

**Comment by KurastikO** [comment]
Was possible back in 2016 but that was patched, there's probably no way to do that again.

**Comment by wemanzoz** [comment]
it will mostlikely cause a thing called "invalid file" or u cant launch the game bcs valve

**Comment by Hayward41** [comment]
You can replace crashhandler.dll that is located in steam folder
(C:\Program Files (x86)\Steam\crashhandler.dll)
