### ISSUE TITLE
Can someone help me inject it 

### ISSUE THREAD

**Issue by EXC3L-YT** [danielkrupinski/Osiris#3111]
I have injected it with process hacker and nothing happens, I have injected I with extreme hacker and it doesn’t work says something about NULL and I have also injected it with CSGhost and it just crashes my game please can someone help me.

**Comment by demitriusdemarcus** [comment]
> I have injected it with process hacker and nothing happens, I have injected I with extreme hacker and it doesn’t work says something about NULL and I have also injected it with CSGhost and it just crashes my game please can someone help me

Use latest osiris version.

**Comment by tusharborkar360** [comment]
Use Extreme Injecter latest version to inject. It's available on Github.
In settings of the Injector, change injection method to Manual Map and always start the Injector in Secure mode.
