### ISSUE TITLE
Option to disable all custom skins

### ISSUE THREAD

**Issue by Mike-Reddick** [danielkrupinski/Osiris#3114]
Please add a feature to disable all custom skins and sounds, this include custom skins for weapons, knifes, gloves, players (agents), ALL imaginable custom materials, all skins, sounds etc, so the user can just see the default skins. And a option to hide all Graffitis, so user can't see anything in the wall. Have many adult CSGO players which hate this custom skins and graffitis, and want a way to disable it, but don't has anyway, as you now Valve can't allow it because this is money. Please add it.

**Comment by wemanzoz** [comment]
what, i mean ur injecting which valve doesnt allow soop

**Comment by linuxer9** [comment]
you can use weapon chams and player chams
