### ISSUE TITLE
How to interact with the Menu in fullscreen?

### ISSUE THREAD

**Issue by 1hAck-0** [danielkrupinski/Osiris#3115]
Hi, I have a quick and simple question. Do you know how to free your mouse/cursor from CS:GO in fullscreen, when the menu is opened, so that I can actually interact with the menu, just like Osiris does? When I try to interact with my menu in CS:GO in fullscreen, it doesn't work at all, but in windowed fullscreen it does. And I also want to know how to not interact with CS:GO at the same time, just like Osiris also doesn't.

**Comment by KurastikO** [comment]
even on fullscreen, i can still move my cursor on fullscreen maybe you haven't updated it your Osiris yet? if not try downloading the newest version

**Comment by 1hAck-0** [comment]
@KurastikO  That's not what I meant. I can interact with Osiris in fullscreen, but I want to make my own menu, and it doesn't work for my menu. So I was asking how he coded it so that menu can interact with the mouse/cursor even in fullscreen.

**Comment by demitriusdemarcus** [comment]
> @KurastikO That's not what I meant. I can interact with Osiris in fullscreen, but I want to make my own menu, and it doesn't work for my menu. So I was asking how he coded it so that menu can interact with the mouse/cursor even in fullscreen.

the cheat is open-source so you can just read it yourself and make a menu based on that.
