### ISSUE TITLE
Injector

### ISSUE THREAD

**Issue by Flaam** [danielkrupinski/Osiris#312]
I can't find injectors, i tried Process Hacker but i get banned, i try Inflame but is not working, i tried some source but are all outdated. Can someone help me

**Comment by troniac** [comment]
Are you serious? Daniel Krupinski have several working "undetected" injectors in his repository. By the way there are hundereds of source codes for injector examples. Build the injector yourself and its undetected! Add code for your own and change Injector entrypoint + entropy.

**Comment by HECCYE** [comment]
If you want ill send you mine,once i get on my pc XD

**Comment by kschou95** [comment]
> Are you serious? Daniel Krupinski have several working "undetected" injectors in his repository. By the way there are hundereds of source codes for injector examples. Build the injector yourself and its undetected! Add code for your own and change Injector entrypoint + entropy.
> 
> https://github.com/danielkrupinski/MemJect

i tried, but stuck at the python script... when i wanted to convert dll to bytes, it says "SyntaxError: invalid syntax" and highlighted "Osiris"

**Comment by kschou95** [comment]
> Are you serious? Daniel Krupinski have several working "undetected" injectors in his repository. By the way there are hundereds of source codes for injector examples. Build the injector yourself and its undetected! Add code for your own and change Injector entrypoint + entropy.
> 
> https://github.com/danielkrupinski/MemJect

okay, i got the py file work, but when i put it into the MemJect.c, i got these 2 error message
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C26451	Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).	MemJect	D:\INJECTOR\MEMJECT\MEMJECT.C	160	

and 

Severity	Code	Description	Project	File	Line	Suppression State
Warning	C6001	Using uninitialized memory 'processSnapshot'.	MemJect	D:\INJECTOR\MEMJECT\MEMJECT.C	219

**Comment by NexSqaud** [comment]
@kschou95 this is not a critical error; file compiled

**Comment by NexSqaud** [comment]
@Flaam For me, inflame works well. Did you follow the instructions exactly?
Batch file for easy Inflame injecting
```batch
@echo off

set pid=NUL

for /F "tokens=1,2" %%a in ('tasklist') do if %%a==csgo.exe set pid=%%b 

IF %pid%==NUL (
goto fail 
)ELSE (
goto sucess)
IF %pid%=="" (goto fail
) ELSE (
goto sucess)

:fail
echo Failed, run game before injecting
pause
exit

:sucess
Inflame -manual-map Osiris.dll %pid%
echo CSGO PID: %pid% - Osiris Injected
pause

```

**Comment by yEsPaP** [comment]
> I can't find injectors, i tried Process Hacker but i get banned, i try Inflame but is not working, i tried some source but are all outdated. Can someone help me

randoinjector

**Comment by HECCYE** [comment]
> I can't find injectors, i tried Process Hacker but i get banned, i try Inflame but is not working, i tried some source but are all outdated. Can someone help me

at my github profile is free prebuilded injector, ill release source when i get my pc back (fixing shit XD)

**Comment by adriangames147** [comment]
> 
> 
> I can't find injectors, i tried Process Hacker but i get banned, i try Inflame but is not working, i tried some source but are all outdated. Can someone help me

I recommend you randoinjector
But duplicate and change numbers at junk codes
https://github.com/bananasss00/Rando-Injector

**Comment by Kane67** [comment]
> 
> 
> > Are you serious? Daniel Krupinski have several working "undetected" injectors in his repository. By the way there are hundereds of source codes for injector examples. Build the injector yourself and its undetected! Add code for your own and change Injector entrypoint + entropy.
> > https://github.com/danielkrupinski/MemJect
> 
> okay, i got the py file work, but when i put it into the MemJect.c, i got these 2 error message
> Severity Code Description Project File Line Suppression State
> Warning C26451 Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2). MemJect D:\INJECTOR\MEMJECT\MEMJECT.C 160
> 
> and
> 
> Severity Code Description Project File Line Suppression State
> Warning C6001 Using uninitialized memory 'processSnapshot'. MemJect D:\INJECTOR\MEMJECT\MEMJECT.C 219

**Use Python 3.x** the Python Version 2.x will not work with the convert script!

The Compile Error? You just need to replace the part with: (Compile x86 and Release) and its working!
```
static const uint8_t binary[] = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x00,
0xb8, 0x00, 0x00, ....
};
```
