### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by hungdz1234** [danielkrupinski/Osiris#3128]
Please help. I inject and the game keeps on crashing after 15s of freeze time :(

**Comment by tusharborkar360** [comment]
Use Extreme Injector. It's available on Github for download. Download latest version of Osiris.

**Comment by hungdz1234** [comment]
> Use Extreme Injector. It's available on Github for download. Download latest version of Osiris.Try disabling Real-Time Protection and any other Antivirus

No. It has nothing to do with the injector. My injector is still doing just fine with old version of Osiris. And I have no Antivirus turned on. It just the latest update's error.
