### ISSUE TITLE
How can I add standalone RCS to my build?

### ISSUE THREAD

**Issue by syst3mm** [danielkrupinski/Osiris#3130]
The only method I found is out of date, and I was wondering if there is any method to add this function to the current build of Osiris.

**Comment by floydGG** [comment]
Just use LUA script on Logitech Software

**Comment by Xonn1com** [comment]
I belive that RCS is in Aimbot?

**Comment by linuxer9** [comment]
ez pasta : https://github.com/danielkrupinski/Osiris/pull/2135

**Comment by syst3mm** [comment]
> ez pasta : #2135

I keep getting these errors and warnings
![image](https://user-images.githubusercontent.com/36554390/126927831-a1889456-626e-46a4-a5ea-bfa2a33e3f51.png)

**Comment by cheateronly123** [comment]
> > macarrão ez: [# 2135](https://github.com/danielkrupinski/Osiris/pull/2135)
> 
> Eu continuo recebendo esses erros e avisos
> ![imagem](https://user-images.githubusercontent.com/36554390/126927831-a1889456-626e-46a4-a5ea-bfa2a33e3f51.png)
 Me too, does anyone have a solution?

**Comment by cheateronly123** [comment]
> > macarrão ez: [# 2135](https://github.com/danielkrupinski/Osiris/pull/2135)
> 
> Eu continuo recebendo esses erros e avisos
> ![imagem](https://user-images.githubusercontent.com/36554390/126927831-a1889456-626e-46a4-a5ea-bfa2a33e3f51.png)

Me too, does anyone have a solution?

**Comment by floydGG** [comment]
> > > macarrão ez: [# 2135](https://github.com/danielkrupinski/Osiris/pull/2135)
> > 
> > 
> > Eu continuo recebendo esses erros e avisos
> > ![imagem](https://user-images.githubusercontent.com/36554390/126927831-a1889456-626e-46a4-a5ea-bfa2a33e3f51.png)
> 
> Me too, does anyone have a solution?

yeah google

**Comment by cheateronly123** [comment]
> > > > macarrão ez: [# 2135](https://github.com/danielkrupinski/Osiris/pull/2135)
> > > 
> > > 
> > > Eu continuo recebendo esses erros e avisos
> > > ![imagem](https://user-images.githubusercontent.com/36554390/126927831-a1889456-626e-46a4-a5ea-bfa2a33e3f51.png)
> > 
> > 
> > Me too, does anyone have a solution?
> 
> yeah google

Update the code there pls.

**Comment by cheateronly123** [comment]
> > > > macarrão ez: [# 2135](https://github.com/danielkrupinski/Osiris/pull/2135)
> > > 
> > > 
> > > Eu continuo recebendo esses erros e avisos
> > > ![imagem](https://user-images.githubusercontent.com/36554390/126927831-a1889456-626e-46a4-a5ea-bfa2a33e3f51.png)
> > 
> > 
> > Me too, does anyone have a solution?
> 
> yeah google

Update the code there pls.
