### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by hungdz1234** [danielkrupinski/Osiris#3131]
Please help me. I don't know why my CS:GO crash 5 minutes after injection. This is my config

{
  "Aimbot": [
    {},
    {},
    {},
    {},
    {},
    {
      "Aimlock": true,
      "Between shots": false,
      "Bone": 1,
      "Enabled": true,
      "Fov": 2.5,
      "Ignore flash": true,
      "Key": 115,
      "Key mode": 1,
      "On key": true,
      "Scoped only": false,
      "Smooth": 3.63
    },
    {},
    {},
    {},
    {
      "Aimlock": true,
      "Between shots": false,
      "Bone": 1,
      "Fov": 2.5,
      "Ignore flash": true,
      "Key": 115,
      "Key mode": 1,
      "On key": true,
      "Scoped only": false,
      "Smooth": 3.63
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {
      "Enabled": true,
      "Fov": 7.03,
      "Ignore flash": true,
      "Ignore smoke": true,
      "Key": 115,
      "Key mode": 1,
      "On key": true,
      "Scoped only": false,
      "Visible only": false
    },
    {},
    {},
    {
      "Enabled": true,
      "Fov": 7.03,
      "Ignore flash": true,
      "Ignore smoke": true,
      "Key": 115,
      "Key mode": 1,
      "On key": true,
      "Scoped only": false,
      "Visible only": false
    },
    {},
    {},
    {
      "Aimlock": true,
      "Between shots": false,
      "Bone": 1,
      "Enabled": true,
      "Fov": 2.62,
      "Ignore flash": true,
      "Ignore smoke": true,
      "Key": 18,
      "On key": true,
      "Scoped only": false,
      "Smooth": 2.31
    },
    {
      "Enabled": true,
      "Fov": 2.19,
      "Ignore flash": true,
      "Ignore smoke": true,
      "Key": 18,
      "On key": true,
      "Scoped only": false,
      "Smooth": 3.0,
      "Visible only": false
    },
    {
      "Enabled": true,
      "Fov": 2.19,
      "Ignore flash": true,
      "Ignore smoke": true,
      "Key": 18,
      "On key": true,
      "Scoped only": false,
      "Smooth": 3.0
    },
    {
      "Bone": 1,
      "Enabled": true,
      "Fov": 2.5,
      "Ignore flash": true,
      "Ignore smoke": true,
      "Key": 18,
      "On key": true,
      "Scoped only": false,
      "Smooth": 1.2,
      "Visible only": false
    },
    {}
  ],
  "Anti aim": {
    "Pitch angle": 70.49
  },
  "Backtrack": {
    "Enabled": true,
    "Ignore smoke": true,
    "Recoil based fov": true,
    "Time limit": 110
  },
  "Chams": {
    "Allies": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Backtrack": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Enemies": {
      "Materials": [
        {
          "Alpha": 1.0,
          "Color": "#00ff00",
          "Enabled": true,
          "Material": 1
        },
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Hands": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Sleeves": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    },
    "Weapons": {
      "Materials": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
    }
  },
  "ESP": {
    "Enemies": {
      "All": {
        "Enabled": true,
        "Skeleton": {
          "Alpha": 1.0,
          "Color": "#fff300",
          "Enabled": true
        },
        "Weapon": {
          "Alpha": 1.0,
          "Color": "#fff300",
          "Enabled": true
        }
      }
    },
    "Hold Key": "LSHIFT",
    "Toggle Key": "F1"
  },
  "Glow": {
    "Players": {
      "Enemies": {
        "All": {
          "Alpha": 1.0,
          "Color": "#ff0000"
        }
      }
    }
  },
  "Inventory Changer": {
    "Equipment": [
      {
        "CT": 34,
        "Slot": 0,
        "TT": 34
      },
      {
        "CT": 56,
        "Slot": 2,
        "TT": 43
      },
      {
        "CT": 52,
        "Slot": 4,
        "TT": 52
      },
      {
        "CT": 38,
        "Slot": 5,
        "TT": 54
      },
      {
        "CT": 41,
        "Slot": 6,
        "TT": 41
      },
      {
        "CT": 23,
        "Slot": 8,
        "TT": 51
      },
      {
        "CT": 17,
        "Slot": 10,
        "TT": 17
      },
      {
        "CT": 1,
        "Slot": 14,
        "TT": 42
      },
      {
        "CT": 48,
        "Slot": 15,
        "TT": 22
      },
      {
        "CT": 53,
        "Slot": 16,
        "TT": 53
      },
      {
        "CT": 14,
        "Slot": 17
      },
      {
        "CT": 31,
        "Slot": 18,
        "TT": 31
      },
      {
        "CT": 5,
        "Slot": 38,
        "TT": 7
      },
      {
        "CT": 16,
        "Slot": 41,
        "TT": 15
      }
    ],
    "Items": [
      {
        "Weapon ID": 5504
      },
      {
        "Paint Kit": 371,
        "Seed": 224,
        "Weapon ID": 10,
        "Wear": 0.010622118
      },
      {
        "Paint Kit": 302,
        "Seed": 791,
        "Weapon ID": 7,
        "Wear": 0.01492431
      },
      {
        "Paint Kit": 10035,
        "Seed": 666,
        "Weapon ID": 5034,
        "Wear": 0.09718893
      },
      {
        "Paint Kit": 180,
        "Seed": 346,
        "Weapon ID": 7,
        "Wear": 0.06708906
      },
      {
        "Weapon ID": 5308
      },
      {
        "Paint Kit": 360,
        "Seed": 628,
        "Weapon ID": 60,
        "Wear": 0.031002212
      },
      {
        "Weapon ID": 4732
      },
      {
        "Paint Kit": 10048,
        "Seed": 503,
        "Weapon ID": 5030,
        "Wear": 0.060614247
      },
      {
        "Paint Kit": 653,
        "Seed": 71,
        "Weapon ID": 61,
        "Wear": 0.01759333
      },
      {
        "Paint Kit": 400,
        "Seed": 741,
        "Weapon ID": 16,
        "Wear": 0.035401702
      },
      {
        "Paint Kit": 10067,
        "Seed": 17,
        "Weapon ID": 5034,
        "Wear": 0.08371549
      },
      {
        "Paint Kit": 10047,
        "Seed": 661,
        "Weapon ID": 5030,
        "Wear": 0.10388699
      },
      {
        "Paint Kit": 792,
        "Seed": 529,
        "Weapon ID": 60,
        "Wear": 0.03176821
      },
      {
        "Paint Kit": 886,
        "Seed": 726,
        "Weapon ID": 8,
        "Wear": 0.03971556
      },
      {
        "Paint Kit": 10045,
        "Seed": 67,
        "Weapon ID": 5030,
        "Wear": 0.09214982
      },
      {
        "Paint Kit": 10072,
        "Seed": 35,
        "Weapon ID": 5031,
        "Wear": 0.060093448
      },
      {
        "Paint Kit": 802,
        "Seed": 902,
        "Weapon ID": 24,
        "Wear": 0.022490112
      },
      {
        "Paint Kit": 10051,
        "Seed": 853,
        "Weapon ID": 5033,
        "Wear": 0.10620378
      },
      {
        "Paint Kit": 838,
        "Seed": 475,
        "Weapon ID": 9,
        "Wear": 0.054633863
      },
      {
        "Paint Kit": 10037,
        "Seed": 217,
        "Weapon ID": 5030,
        "Wear": 0.0906993
      },
      {
        "Paint Kit": 512,
        "Seed": 745,
        "Weapon ID": 16,
        "Wear": 0.043647286
      },
      {
        "Paint Kit": 456,
        "Seed": 744,
        "Weapon ID": 7,
        "Wear": 0.010296981
      },
      {
        "Paint Kit": 39,
        "Seed": 527,
        "Weapon ID": 34,
        "Wear": 0.075215794
      },
      {
        "Paint Kit": 600,
        "Seed": 961,
        "Weapon ID": 7,
        "Wear": 0.014311354
      },
      {
        "Paint Kit": 941,
        "Seed": 798,
        "Weapon ID": 7,
        "Wear": 0.011344413
      },
      {
        "Paint Kit": 959,
        "Seed": 260,
        "Weapon ID": 7,
        "Wear": 0.04285509
      },
      {
        "Paint Kit": 675,
        "Seed": 127,
        "Weapon ID": 7,
        "Wear": 0.05229533
      },
      {
        "Paint Kit": 1004,
        "Seed": 401,
        "Weapon ID": 7,
        "Wear": 0.061904036
      },
      {
        "Paint Kit": 801,
        "Seed": 444,
        "Weapon ID": 7,
        "Wear": 0.058515217
      },
      {
        "Paint Kit": 644,
        "Seed": 899,
        "Weapon ID": 60,
        "Wear": 0.05504273
      },
      {
        "Paint Kit": 943,
        "Seed": 790,
        "Weapon ID": 9,
        "Wear": 0.05577454
      },
      {
        "Paint Kit": 185,
        "Seed": 619,
        "Weapon ID": 1,
        "Wear": 0.008335259
      },
      {
        "Paint Kit": 1026,
        "Seed": 851,
        "Weapon ID": 9,
        "Wear": 0.004118714
      },
      {
        "Paint Kit": 415,
        "Seed": 619,
        "Weapon ID": 515,
        "Wear": 0.0028500676
      },
      {
        "Paint Kit": 718,
        "Seed": 854,
        "Weapon ID": 9,
        "Wear": 0.03218066
      },
      {
        "Paint Kit": 805,
        "Seed": 508,
        "Weapon ID": 1,
        "Wear": 0.015620192
      },
      {
        "Paint Kit": 336,
        "Seed": 55,
        "Weapon ID": 16,
        "Wear": 0.040088773
      },
      {
        "Paint Kit": 660,
        "Seed": 269,
        "Weapon ID": 3,
        "Wear": 0.010092308
      },
      {
        "Paint Kit": 468,
        "Seed": 941,
        "Weapon ID": 1,
        "Wear": 0.040098034
      },
      {
        "Paint Kit": 1048,
        "Seed": 702,
        "Weapon ID": 39,
        "Wear": 0.049868796
      },
      {
        "Paint Kit": 645,
        "Seed": 913,
        "Weapon ID": 1,
        "Wear": 0.003377582
      },
      {
        "Paint Kit": 308,
        "Seed": 866,
        "Weapon ID": 13,
        "Wear": 0.038736604
      },
      {
        "Paint Kit": 963,
        "Seed": 450,
        "Weapon ID": 4,
        "Wear": 0.024420612
      },
      {
        "Paint Kit": 353,
        "Seed": 104,
        "Weapon ID": 4,
        "Wear": 0.03316363
      },
      {
        "Paint Kit": 430,
        "Seed": 883,
        "Weapon ID": 60,
        "Wear": 0.048729338
      },
      {
        "Paint Kit": 632,
        "Seed": 733,
        "Weapon ID": 16,
        "Wear": 0.03608461
      },
      {
        "Paint Kit": 971,
        "Seed": 204,
        "Weapon ID": 16,
        "Wear": 0.03685623
      },
      {
        "Paint Kit": 695,
        "Seed": 441,
        "Weapon ID": 16,
        "Wear": 0.0061775004
      },
      {
        "Paint Kit": 588,
        "Seed": 870,
        "Weapon ID": 16,
        "Wear": 0.004313821
      },
      {
        "Paint Kit": 167,
        "Seed": 382,
        "Weapon ID": 16,
        "Wear": 0.09887895
      },
      {
        "Paint Kit": 433,
        "Seed": 658,
        "Weapon ID": 17,
        "Wear": 0.012148562
      },
      {
        "Paint Kit": 551,
        "Seed": 348,
        "Weapon ID": 36,
        "Wear": 0.10557744
      },
      {
        "Paint Kit": 624,
        "Seed": 384,
        "Weapon ID": 40,
        "Wear": 0.03091731
      },
      {
        "Paint Kit": 555,
        "Seed": 734,
        "Weapon ID": 30,
        "Wear": 0.028799087
      },
      {
        "Paint Kit": 318,
        "Seed": 64,
        "Weapon ID": 61,
        "Wear": 0.012482517
      },
      {
        "Paint Kit": 637,
        "Seed": 95,
        "Weapon ID": 61,
        "Wear": 0.03392345
      }
    ],
    "Version": 3
  },
  "Misc": {
    "Bomb timer": {
      "Color": [
        1.0,
        0.72897196,
        0.0
      ]
    },
    "Clan tag": "BomBarDieR",
    "Edge Jump Key": "MOUSE3",
    "Grenade predict": true,
    "Menu key": "HOME",
    "Offscreen Enemies": {
      "Enabled": true,
      "Health Bar": {
        "Enabled": true,
        "Type": 2
      }
    }
  },
  "Sound": {
    "Players": [
      {},
      {},
      {}
    ]
  },
  "Style": {
    "Colors": {
      "Border": [
        0.43,
        0.43,
        0.5,
        0.5
      ],
      "BorderShadow": [
        0.0,
        0.0,
        0.0,
        0.0
      ],
      "Button": [
        0.26,
        0.59,
        0.98,
        0.4
      ],
      "ButtonActive": [
        0.06,
        0.53,
        0.98,
        1.0
      ],
      "ButtonHovered": [
        0.26,
        0.59,
        0.98,
        1.0
      ],
      "CheckMark": [
        0.26,
        0.59,
        0.98,
        1.0
      ],
      "ChildBg": [
        0.0,
        0.0,
        0.0,
        0.0
      ],
      "DragDropTarget": [
        1.0,
        1.0,
        0.0,
        0.9
      ],
      "FrameBg": [
        0.16,
        0.29,
        0.48,
        0.54
      ],
      "FrameBgActive": [
        0.26,
        0.59,
        0.98,
        0.67
      ],
      "FrameBgHovered": [
        0.26,
        0.59,
        0.98,
        0.4
      ],
      "Header": [
        0.26,
        0.59,
        0.98,
        0.31
      ],
      "HeaderActive": [
        0.26,
        0.59,
        0.98,
        1.0
      ],
      "HeaderHovered": [
        0.26,
        0.59,
        0.98,
        0.8
      ],
      "MenuBarBg": [
        0.14,
        0.14,
        0.14,
        1.0
      ],
      "ModalWindowDimBg": [
        0.8,
        0.8,
        0.8,
        0.35
      ],
      "NavHighlight": [
        0.26,
        0.59,
        0.98,
        1.0
      ],
      "NavWindowingDimBg": [
        0.8,
        0.8,
        0.8,
        0.2
      ],
      "NavWindowingHighlight": [
        1.0,
        1.0,
        1.0,
        0.7
      ],
      "PlotHistogram": [
        0.9,
        0.7,
        0.0,
        1.0
      ],
      "PlotHistogramHovered": [
        1.0,
        0.6,
        0.0,
        1.0
      ],
      "PlotLines": [
        0.61,
        0.61,
        0.61,
        1.0
      ],
      "PlotLinesHovered": [
        1.0,
        0.43,
        0.35,
        1.0
      ],
      "PopupBg": [
        0.08,
        0.08,
        0.08,
        0.94
      ],
      "ResizeGrip": [
        0.26,
        0.59,
        0.98,
        0.2
      ],
      "ResizeGripActive": [
        0.26,
        0.59,
        0.98,
        0.95
      ],
      "ResizeGripHovered": [
        0.26,
        0.59,
        0.98,
        0.67
      ],
      "ScrollbarBg": [
        0.02,
        0.02,
        0.02,
        0.53
      ],
      "ScrollbarGrab": [
        0.31,
        0.31,
        0.31,
        1.0
      ],
      "ScrollbarGrabActive": [
        0.51,
        0.51,
        0.51,
        1.0
      ],
      "ScrollbarGrabHovered": [
        0.41,
        0.41,
        0.41,
        1.0
      ],
      "Separator": [
        0.43,
        0.43,
        0.5,
        0.5
      ],
      "SeparatorActive": [
        0.1,
        0.4,
        0.75,
        1.0
      ],
      "SeparatorHovered": [
        0.1,
        0.4,
        0.75,
        0.78
      ],
      "SliderGrab": [
        0.24,
        0.52,
        0.88,
        1.0
      ],
      "SliderGrabActive": [
        0.26,
        0.59,
        0.98,
        1.0
      ],
      "Tab": [
        0.17999999,
        0.34999996,
        0.58000004,
        0.862
      ],
      "TabActive": [
        0.19999999,
        0.40999997,
        0.68,
        1.0
      ],
      "TabHovered": [
        0.26,
        0.59,
        0.98,
        0.8
      ],
      "TabUnfocused": [
        0.068,
        0.10199998,
        0.14800003,
        0.9724
      ],
      "TabUnfocusedActive": [
        0.13599998,
        0.26199996,
        0.424,
        1.0
      ],
      "TableBorderLight": [
        0.23,
        0.23,
        0.25,
        1.0
      ],
      "TableBorderStrong": [
        0.31,
        0.31,
        0.35,
        1.0
      ],
      "TableHeaderBg": [
        0.19,
        0.19,
        0.2,
        1.0
      ],
      "TableRowBg": [
        0.0,
        0.0,
        0.0,
        0.0
      ],
      "TableRowBgAlt": [
        1.0,
        1.0,
        1.0,
        0.06
      ],
      "Text": [
        1.0,
        1.0,
        1.0,
        1.0
      ],
      "TextDisabled": [
        0.5,
        0.5,
        0.5,
        1.0
      ],
      "TextSelectedBg": [
        0.26,
        0.59,
        0.98,
        0.35
      ],
      "TitleBg": [
        0.04,
        0.04,
        0.04,
        1.0
      ],
      "TitleBgActive": [
        0.16,
        0.29,
        0.48,
        1.0
      ],
      "TitleBgCollapsed": [
        0.0,
        0.0,
        0.0,
        0.51
      ],
      "WindowBg": [
        0.06,
        0.06,
        0.06,
        0.94
      ]
    }
  },
  "Triggerbot": [
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {}
  ],
  "Visuals": {
    "Flash reduction": 30,
    "No blur": true,
    "No fog": true,
    "No grass": true,
    "No sleeves": true
  }
}

**Comment by tusharborkar360** [comment]
There's a problem with skins in Inventory Changer. Add somewhat 5 to 9 skins only in your Inventory and save to config.
Adding too many of skins and then loading config at one time causes it to crash while playing. Some skins are maybe corrupt.

**Comment by hungdz1234** [comment]
> There's a problem with skins in Inventory Changer. Add somewhat 5 to 9 skins only in your Inventory and save to config.
> Adding too many of skins and then loading config at one time causes it to crash while playing. Some skins are maybe corrupt.

But which one is corrupt?

**Comment by hungdz1234** [comment]
The old version still works fine. I dont know wjy thw latest version has this error

**Comment by sonicrules11** [comment]
> There's a problem with skins in Inventory Changer. Add somewhat 5 to 9 skins only in your Inventory and save to config.
> Adding too many of skins and then loading config at one time causes it to crash while playing. Some skins are maybe corrupt.

It seems to crash even if you dont have anything added

**Comment by syst3mm** [comment]
> > There's a problem with skins in Inventory Changer. Add somewhat 5 to 9 skins only in your Inventory and save to config.
> > Adding too many of skins and then loading config at one time causes it to crash while playing. Some skins are maybe corrupt.
> 
> It seems to crash even if you dont have anything added

osiris is crashing to me too
