### ISSUE TITLE
[HELP] Adding consoleColorPrintf function to Cvar interface

### ISSUE THREAD

**Issue by propane** [danielkrupinski/Osiris#3132]
Inside Cvar.h I would like to add the call for the virtual method ConsoleColorPrintf

I have tried multiple methods, but none working
(also im aware that in the end of the parameters i dont include the arg array, i just put this here for example)

VIRTUAL_METHOD(void, consoleColorPrintf, 25, (const Color& clr, const char* pFormat, ...), (this, clr, pFormat))

If you have this working please share, thank you.

**Comment by linuxer9** [comment]
you need to print a colored text to console, right?
use this: memory->conColorMsg

**Comment by propane** [comment]
@linuxer9 thank you for the reply, but I have used this and it does not seem to work for me, maybe I am doing something else wrong, I'll assume it is functioning properly and double check my code, was quite tired last night, thank you and have a good day

**Comment by propane** [comment]
I realized the problem was that, I have set up a console text filter to remove all the games console output, making it less messy when reading logs, but the conColorMsg ends up being removed from this, when previously using the stated method I was trying to add above did not get filtered, I have this conColorMsg working though, so I will just use that and remove the console filtering or find a workaround later.
