### ISSUE TITLE
QUESTION HELP FEATURE

### ISSUE THREAD

**Issue by cheateronly123** [danielkrupinski/Osiris#3133]
How do I add Recoil Control System in Osiris?

**Comment by HowToMakeFaceitAB** [comment]
> How do I add Recoil Control System in Osiris?

learn how to code

**Comment by HowToMakeFaceitAB** [comment]
+ get an iq over 70

**Comment by wemanzoz** [comment]
just pull down your mouse

**Comment by propane** [comment]
It already has one, its just not customizable, close thread.
