### ISSUE TITLE
Inventory Changer knife bug

### ISSUE THREAD

**Issue by 2933968621** [danielkrupinski/Osiris#3134]
![) FSD6L0$R} VYC7})D4%YJ](https://user-images.githubusercontent.com/53483352/126898568-c57bbba9-955a-4419-8316-b164da117299.png)
![3G{4H3T~EO)EUM~ICI$Y3GI](https://user-images.githubusercontent.com/53483352/126898570-d7cfde51-8767-4a6e-9b90-464feedba176.png)

As shown in the figure, the name of the knife in the kill enemy prompt will not be changed

**Comment by AquaticBUBU** [comment]
had the exact same issue

**Comment by blackMasterLord** [comment]
#3145

**Comment by 2933968621** [comment]
> #3145

this working, thank!
