### ISSUE TITLE
ISSUE: traceToExit

### ISSUE THREAD

**Issue by propane** [danielkrupinski/Osiris#3135]
traceToExit was disabled in the Aimbot after one of the recent CS:GO updates, I assume just so the cheat would not crash but I do not know if you had an intention of fixing again.

**Comment by R3nzTheCodeGOD** [comment]
#3088

**Comment by acey1337** [comment]
what does traceToExit do?

**Comment by real-Shigure** [comment]
> what does traceToExit do?
+1
when traceToExit function was disabled, game still run and never crashed.  O_O??
