### ISSUE TITLE
state of cheat detection on linux

### ISSUE THREAD

**Issue by linuxer9** [danielkrupinski/Osiris#3136]
Anyone used osiris on linux for a long period of time, was it detected?

**Comment by Asviix** [comment]
Osiris won't be detected, your method of injection can, sadly I don't use linux thus cannot guide you towards a good injector.

**Comment by linuxer9** [comment]
> 
> 
> Osiris won't be detected, your method of injection can, sadly I don't use linux thus cannot guide you towards a good injector.

It's not the injector, all linux internals use GNU debugger to inject, VAC can't flag GDB because it's used by programmers...
I'm talking about the cheat itself, what its detection rate?

**Comment by mxez** [comment]
Using cathook's gdb script for a month now, still not  banned. (used cathook in tf2 for like a year, still not banned)

**Comment by r3cidis** [comment]
I've taken Osiris, but edited the code a bit (to not be a blind copy). As I have 0 experience in Source Engine Hacking + VAC I do not know how much editing is needed to lose fingerprinting.
+ I am using an injector just found here by someones issue:
`sudo gdb -n -q -batch-silent \
       -ex "set logging file /dev/null" \
       -ex "set logging redirect on" \
       -ex "set logging on" \
       -ex "attach $csgo_pid" \
       -ex "call ((void*(*)(const char*, int))dlopen)(\"/usr/lib/$filename\", 1)"   \
       -ex "detach" \
       -ex "quit"`

I am on Arch (Manjaro KDE Plasma 5) with Steam that was pre-installed with this Distro

It's been two weeks, hoping to at least 6 months more to be guaranteed and if that's the case - would be fun to start developing similar or my own.

Ping me after a while I will give you an update

**Comment by linuxer9** [comment]
It's nice to see osiris users on linux, I inject my build with fuzion script using the distro gdb, I'll update this if anything got detected.
