### ISSUE TITLE
Failed to find Pattern #19

### ISSUE THREAD

**Issue by configbrowser** [danielkrupinski/Osiris#3139]
anyone know a fix?

**Comment by tusharborkar360** [comment]
Delete everything from your PC related to Osiris. Now with a fresh start, Compile latest version of Osiris and use only Extreme Injector with Manual Map Injection Method.

**Comment by configbrowser** [comment]
> Delete everything from your PC related to Osiris. Now with a fresh start, Compile latest version of Osiris and use only Extreme Injector with Manual Map Injection Method.

its something with gameoverlayrenderer I think, but osiris current use same one :/

**Comment by 2933968621** [comment]
maybe because csgo update

**Comment by tusharborkar360** [comment]
I checked and got to know that it's because of the new CS:GO Update

**Comment by tusharborkar360** [comment]
> anyone know a fix?

We should wait for the update of Osiris... Then the issue will be resolved automatically.

**Comment by danielkrupinski** [comment]
Updated.

**Comment by maciekszparka** [comment]
@danielkrupinski mam blad z tym pattern ale #12

**Comment by watchermuna5** [comment]
Please add movement recorder.. this https://aixxe.net/2017/04/source-input-recorder
