### ISSUE TITLE
ESP/Chams invisible sometimes. and aimbot completely off target

### ISSUE THREAD

**Issue by ItsOnlyMeNL** [danielkrupinski/Osiris#314]
Hi,

I am just curious if some of you also have this. For me some times the ESP/Chams are not showing the enemies, they become completely invisible to me and unable to see the player. Do some of you also experience this?

I also notice that from time to time the aimbot is completely off target.  as example, 
i have rounds where it hits all shots i take. ( with scout ) and some rounds where it misses all shots even when the target is standing still. Also with guns like AK-47 or M4A1-S its missing a lot. This without configurations not being changed.

Am i the only one that experience this or any suggestions to my config that could resolve this issue? 

Regards,

**Comment by cojo1989** [comment]
Are alot of reasons wheb you miss. Maybe enemy is useing desync, or you need to remake the config. Just recompile it, remake from scratch config and try it. If the enemy is useing desync i recomand you just body shots.

**Comment by danielkrupinski** [comment]
Please post screenshot of that esp / chams bug.

To increase aimbot accuracy higher "recoil control" values in aimbot window.

**Comment by ItsOnlyMeNL** [comment]
Hi,

Not the best quality but hope this is good enough to show you what i mean. 
https://prtscn.pics/csgo_esp.mp4

**Comment by danielkrupinski** [comment]
This is because server stops sending information about distant players behind thick walls.

**Comment by ItsOnlyMeNL** [comment]
Strange. Because its also happening to teammates from time to time even without having glow or chams enabled on team and only enemy.

The exact same thing is happening to the enemy player where it completely disappears from ESP/Glow/chams also the character itself is invisible at that moment.  Please see the next 2 links:

https://prtscn.pics/image/KY4NI
https://prtscn.pics/image/KYAoz

**Comment by unabjuuh** [comment]
i got the same issue. the guy on the right wasnt visible at first but to slow to make a pic but still cant see the other guy.

https://scrns.nl/image/DWt1

**Comment by ItsOnlyMeNL** [comment]
Any idea's/ solutions to this? the ESP falling away and making players invisible is really starting to get an issue. It is also happening even when they are not behind a wall. I can hear them walk but not see. When i see them its to late to counter them.
