### ISSUE TITLE
pattern 17 error

### ISSUE THREAD

**Issue by SPVoss1** [danielkrupinski/Osiris#3140]
since the newest update (07.28.2021) it always gives me the "failed to find pattern 17" message and crashes a few seconds after. im using the newest build and couldnt find anything online. the patchnotes of cs also dont contain anything on this.

**Comment by syst3mm** [comment]
i'm getting this error too

**Comment by m0L3cuL3** [comment]
I think the pattern for traceToExit is outdated. not sure.

**Comment by CHRIZZ83** [comment]
> since the newest update (07.28.2021) it always gives me the "failed to find pattern 17" message and crashes a few seconds after. im using the newest build and couldnt find anything online. the patchnotes of cs also dont contain anything on this.

CSGO was updated AFTER the Osiris update earlier today. Just hang tight for Osiris to be updated.

**Comment by tusharborkar360** [comment]
> > since the newest update (07.28.2021) it always gives me the "failed to find pattern 17" message and crashes a few seconds after. im using the newest build and couldnt find anything online. the patchnotes of cs also dont contain anything on this.
> 
> CSGO was updated AFTER the Osiris update earlier today. Just hang tight for Osiris to be updated.

Yeah, we should wait for Osiris to update. Then the issue will be resolved automatically.

**Comment by Shuvi-Moro** [comment]
I also get this error but does not crash

**Comment by danielkrupinski** [comment]
Updated.
