### ISSUE TITLE
[SUGGESTION] Add StatTrak for items

### ISSUE THREAD

**Issue by SafwanSipai** [danielkrupinski/Osiris#3141]
I think i have an idea on how to implement StatTrak on items. Maybe you can have variables assigned to skins and they detect it during the game when they get kills and they store it and the next time we load the config, it could add the stored variable to the already existing kills.

I am not sure how feasible it is but i think i should just suggest it.

Thank you :)

**Comment by blackMasterLord** [comment]
Dude, `StatTrak` is already implemented. 
For it to work, you need to write **"StatTrak 0"** in the config.

**Comment by SafwanSipai** [comment]
> Dude, `StatTrak` is already implemented.
> For it to work, you need to write **"StatTrak 0"** in the config.

You mean like this? -> StatTrak: 0

**Comment by blackMasterLord** [comment]
> > Dude, `StatTrak` is already implemented.
> > For it to work, you need to write **"StatTrak 0"** in the config.
> 
> You mean like this? -> StatTrak: 0

yes

**Comment by SafwanSipai** [comment]
> > > Dude, `StatTrak` is already implemented.
> > > For it to work, you need to write **"StatTrak 0"** in the config.
> > 
> > 
> > You mean like this? -> StatTrak: 0
> 
> yes, "StatTrak": 0

Okay, thank you :)

**Comment by SafwanSipai** [comment]
> > > Dude, `StatTrak` is already implemented.
> > > For it to work, you need to write **"StatTrak 0"** in the config.
> > 
> > 
> > You mean like this? -> StatTrak: 0
> 
> yes, "StatTrak": 0

oh btw, do i need to save the config everytime i close cs go to retain the stattrak kills?

**Comment by blackMasterLord** [comment]
> > > > Dude, `StatTrak` is already implemented.
> > > > For it to work, you need to write **"StatTrak 0"** in the config.
> > > 
> > > 
> > > You mean like this? -> StatTrak: 0
> > 
> > 
> > yes, "StatTrak": 0
> 
> oh btw, do i need to save the config everytime i close cs go to retain the stattrak kills?

yes
