### ISSUE TITLE
Help with enable aimbot after shot

### ISSUE THREAD

**Issue by GioFrandiz** [danielkrupinski/Osiris#3142]
Good day people, could someone help me with the code to add an option that has to do with activating the aimbot after the first shots or shot.
From the reviews I saw of some cheats, I could see that there are some of these that have this option, so the movements of the aim are not so obvious and only activates the aimbot after the first shot.

![Captura](https://user-images.githubusercontent.com/13192759/127377531-7b13fd82-5011-462b-826a-59de9ec6038d.PNG)

I saw this code: 
https://github.com/danielkrupinski/Osiris/pull/2097/files/01f4c747ee3cfab5266588329a033a490118157a

but it only delays the shot, I would like to know if it is possible to add the option to make a shot and then activate the aimbot on key pressed.

**Comment by Metaphysical1** [comment]
add this check in aimbot::run() 
```
if (!localPlayer->shotsFired() > 1)
    return;
```
or add field in Config.h and make it like this
```
if (!localPlayer->shotsFired() > config->aimbotIgnoreShots)
    return;
```

**Comment by GioFrandiz** [comment]
ty my friend, do i only have to add those commands in the aimbot.cpp file? or do i have to make any changes in another file?

**Comment by Shuvi-Moro** [comment]
https://i.imgur.com/MVTR9nM.jpeg

**Comment by Shuvi-Moro** [comment]
Good luck

**Comment by GioFrandiz** [comment]
thank you very much friend, I will try to make the changes, in case I succeed I will buy you a coffee.

**Comment by Shuvi-Moro** [comment]
)
thnx

**Comment by Shuvi-Moro** [comment]
But better not buy coffee, but put it aside for a dream)

**Comment by GioFrandiz** [comment]
friend, I could make the change (it took me a little time :) ) but when I activate "first shot to fire" and set to 1, nothing happens, the aimbot is activated automatically when the first shot is fired and the purpose is that the aimbot is activated after the first shot, in other words: activate the aimbot from the second shot, if you know how to do it I will be very grateful to you.
