### ISSUE TITLE
HELP PLS

### ISSUE THREAD

**Issue by cheateronly123** [danielkrupinski/Osiris#3144]
Why doesn't the simple charger inject osiris?

**Comment by tusharborkar360** [comment]
Just use Extreme Injector. It's available here on Github.

**Comment by cheateronly123** [comment]
> Just use Extreme Injector. It's available here on Github.

I wanted a loader, not an injector.

**Comment by Asviix** [comment]
> Just use Extreme Injector. It's available here on Github.

boi you'll get banned in 2 days lmaoo

Use CSGhost lmfao

**Comment by tusharborkar360** [comment]
> > Just use Extreme Injector. It's available here on Github.
> 
> boi you'll get banned in 2 days lmaoo
> 
> Use CSGhost lmfao

I got banned on one experimental account when I used that CSghost. Now I use Extreme Injector and haven't got banned.

**Comment by Metaphysical1** [comment]
> > > Just use Extreme Injector. It's available here on Github.
> > 
> > 
> > boi you'll get banned in 2 days lmaoo
> > Use CSGhost lmfao
> 
> I got banned on one experimental account when I used that CSghost. Now I use Extreme Injector and haven't got banned.

you used csghost c4 ? and ran it when steam was closed?

**Comment by floydGG** [comment]
5 months with shtreeba oof nothing at all

**Comment by cheateronly123** [comment]
> 5 months with shtreeba oof nothing at all

I'm using it too, but I wanted a loader with hwid
