### ISSUE TITLE
Small issue on Linux.

### ISSUE THREAD

**Issue by SmokingDuckk** [danielkrupinski/Osiris#3146]
Hello, i'm really sorry to ask this here because thats not completely related with the cheat himself, the cheat works really fine on Manjaro.

So yeah, i use the cheat on Linux Manjaro and i followed these instructions:
https://github.com/danielkrupinski/Osiris/pull/2853/commits/9f75020c880e899687db5c505a0a70d7dd18168c

It works fine, but i have a small problem. There's the build_arch file and the load_osiris file.

Both of them doesnt run, i get this error trying to run them into my terminal:

_Warning: Could not find '/home/nameofuser/Bureau/Osiris/load_osiris', starting '/bin/bash' instead.  Please check your profile settings._

I'm kinda tired to open the console into the release folder and copy and paste the code of the load_osiris file everytimes i want to inject the cheat. Is there a way to run it directly please? Thank you. And again, sorry to ask this here. The cheat works fine on Manjaro.

**Comment by linuxer9** [comment]
make a shortcut?

**Comment by SmokingDuckk** [comment]
> make a shortcut?

what do you mean make a shortcut? it doesnt change anything, or maybe i dont understand

**Comment by Taughtimp2786** [comment]
> > make a shortcut?
> 
> what do you mean make a shortcut? it doesnt change anything, or maybe i dont understand
> 
> nvm fixed ty

How did you make a shortuct?
