### ISSUE TITLE
Obs bypass

### ISSUE THREAD

**Issue by Teodor9776** [danielkrupinski/Osiris#3153]
how does it work? display capture windows capture or game capture for obs? does it work for glow and chams? can it hide the esp on nvidia geforce recordings?

**Comment by Xonn1com** [comment]
esp wont display on your recording/stream
game capture (i think?) [-allow_third_party_software]
no
idk

**Comment by Teodor9776** [comment]
> esp wont display on your recording/stream
> game capture (i think?) [-allow_third_party_software]
> no
> idk

cant use game capture on csgo
:/

**Comment by sotakoira** [comment]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/409060-obs-gamecapture.html

**Comment by awesomeusername69420** [comment]
> cant use game capture on csgo
> :/
"""-allow_third_party_software"""

**Comment by floydGG** [comment]
dude u can google it for this, no need to open the fucking issues

**Comment by wemanzoz** [comment]
> > cant use game capture on csgo
> > :/
> 
> """-allow_third_party_software"""
> thanks for the retarded formatting github

dont use this launch options ^^^ it will turn your tf to red very-very fast

**Comment by acey1337** [comment]
> > > cant use game capture on csgo
> > > :/
> > 
> > 
> > """-allow_third_party_software"""
> > thanks for the retarded formatting github
> 
> dont use this launch options ^^^ it will turn your tf to red very-very fast

+1
