### ISSUE TITLE
ADD FUNCTION GRENADE HELPER

### ISSUE THREAD

**Issue by cheateronly123** [danielkrupinski/Osiris#3154]
Add the Grenade Helper feature, pls.

**Comment by awesomeusername69420** [comment]
Misc -> Grenade Prediction

**Comment by Xonn1com** [comment]
> 
> 
> Misc -> Grenade Prediction

he didnt meant grenade prediction, but something like helper for smokes for places

**Comment by cheateronly123** [comment]
> > Misc -> Grenade Prediction
> 
> he didnt meant grenade prediction, but something like helper for smokes for places



> > Misc -> Grenade Prediction
> 
> he didnt meant grenade prediction, but something like helper for smokes for places

That's right, if anyone has a Grenade Helper feature, paste it here in the chat.

**Comment by n0verify** [comment]
look at my github repo, my osiris paste has smoke helper

**Comment by Xonn1com** [comment]
> 
> 
> look at my github repo, my osiris paste has smoke helper

Thats some dedication! I would love to daniel cooperate with you! Can you make some pull requests for Osiris to implement it?
