### ISSUE TITLE
(suggestion) Stand alone inventory changer?

### ISSUE THREAD

**Issue by CalvinBens** [danielkrupinski/Osiris#3155]
To whoever is reading this, feel absolutely no obligation at all to do this. I'm just saying it would be cool for dum dums like me who can't do it themselves because they can't code. One might ask why I dont just switch to nskinz. Thats because its suuper buggy for me, especially the knife animations.

One thing, I did try to do it myself despite of my inability and it was a disaster lmao.

**Comment by YeetingWaterbottle** [comment]
He already made a repository with inventory changer stand alone, https://github.com/danielkrupinski/OsirisInventory, you just have to compile it im pretty sure.

**Comment by CalvinBens** [comment]
> He already made a repository with inventory changer stand alone, https://github.com/danielkrupinski/OsirisInventory, you just have to compile it im pretty sure.


First of all, thank you for the response. Second, you and the dude who made this are legends. Third, how tf do u use this lmao. I seem to be clicking update but nothings happening haha.

**Comment by YeetingWaterbottle** [comment]
> > He already made a repository with inventory changer stand alone, https://github.com/danielkrupinski/OsirisInventory, you just have to compile it im pretty sure.
> 
> 
> First of all, thank you for the response. Second, you and the dude who made this are legends. Third, how tf do u use this lmao. I seem to be clicking update but nothings happening haha.

First, he is the person who made osiris, bruh
Second, can u send a screenshot of the menu? I havent tried it out yet.

**Comment by CalvinBens** [comment]
> > > He already made a repository with inventory changer stand alone, https://github.com/danielkrupinski/OsirisInventory, you just have to compile it im pretty sure.
> > 
> > 
> > First of all, thank you for the response. Second, you and the dude who made this are legends. Third, how tf do u use this lmao. I seem to be clicking update but nothings happening haha.
> 
> First, he is the person who made osiris, bruh
> Second, can u send a screenshot of the menu? I havent tried it out yet.

![Capture](https://user-images.githubusercontent.com/81130904/127826534-e8a3d0d1-050f-4a54-8e0a-715af21c961e.PNG)

So I was just being dumb, it works perfectly.

**Comment by Xonn1com** [comment]
Remember to save config after getting some kills on stattrak!
To apply stattrak to any weapon you must add a line "StatTrak": 20, to your config file. feel free to ask any questions.

**Comment by CalvinBens** [comment]
> Remember to save config after getting some kills on stattrak!
> To apply stattrak to any weapon you must add a line "StatTrak": 20, to your config file. feel free to ask any questions.

I just have one question, why do some knife animations bug out a little bit when playing matchmaking but not offline? I’ve seen this with other skin and inventory changers as well. Is this an issue that just can’t be fixed?
