### ISSUE TITLE
An interesting bug I’ve seen with other skin and inventory changers

### ISSUE THREAD

**Issue by CalvinBens** [danielkrupinski/Osiris#3156]
Knife animations stuttering when playing mm, but they’re fine in custom games. You can recreate this bug by enabling fake lag. I’ve seen this with nSkinz and and seaside skin changer. Is this something that just can’t be fixed?

**Comment by CalvinBens** [comment]
I made a video to show this bug.

[](https://www.youtube.com/watch?v=x6SMx2rFMR0)

**Comment by lordeternity000** [comment]
I experienced the same on high ping servers. But if you play with ping lower than around 60. This doesn't happen.
