### ISSUE TITLE
Need Help 

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#3159]
Z: \ Users \ Peeeach-Moro \ source \ repos \ 210728 multipoints \ Osiris \ SDK \ Entity.cpp (33,1): error C2084: function "Vector Entity :: getBonePosition (Entity *, int, Vector, Vector, int ) noexcept "already has implementation text
![image](https://user-images.githubusercontent.com/63977167/127930162-a9a0238e-f617-43ce-a3db-5283731d646f.png)

**Comment by KurastikO** [comment]
use release-x64 not debug lul

**Comment by Xonn1com** [comment]
Release x86*
