### ISSUE TITLE
[Suggestion] Rank, Medals, Grenade Predicition, No Recoil

### ISSUE THREAD

**Issue by Alpha878** [danielkrupinski/Osiris#316]
@danielkrupinski I would like to see Rank Changer & Medal Changer and Grenade Prediction and No Recoil in Osiris. If you could add it I would be so happy.

**Comment by cojo1989** [comment]
And legit AA beside that :D

**Comment by HECCYE** [comment]
Slide walk would be also cool.

**Comment by Shaxzy** [comment]
> Slide walk would be also cool.

Pretty useless if you ask me.
