### ISSUE TITLE
Need Help 

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#3160]
#2503
https://www.dropbox.com/s/laldqcd2qd2d3yg/Desktop%202021.08.03%20-%2002.10.33.26.mp4?dl=0

Please help to solve the crash problem!!!

1>------ Сборка запущено: проект: Osiris, конфигурация: Debug|Win32 ------
1>  compilation header save succeeded; see Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\Resources\Shaders\Build\default_vs.h
1>  pch-c.c
1>  pch.cpp
1>  Config.cpp
1>  ConfigStructs.cpp
1>  EventListener.cpp
1>  GameData.cpp
1>  Aimbot.cpp
1>  AntiAim.cpp
1>  Backtrack.cpp
1>  Chams.cpp
1>  EnginePrediction.cpp
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\Hooks\vfunc_hook.hpp(2,1): warning C4005: NOMINMAX: изменение макроопределения (компилируется исходный файл Hacks\Chams.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\pch.cpp : message : см. предыдущее определение "NOMINMAX" (компилируется исходный файл Hacks\Chams.cpp)
1>  Glow.cpp
1>  ProfileChanger.cpp
1>  Sound.cpp
1>  StreamProofESP.cpp
1>  Triggerbot.cpp
1>  Visuals.cpp
1>  Helpers.cpp
1>  MinHook.cpp
1>  vfunc_hook.cpp
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\Hooks\vfunc_hook.hpp(2,1): warning C4005: NOMINMAX: изменение макроопределения (компилируется исходный файл Hooks\vfunc_hook.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\pch.cpp : message : см. предыдущее определение "NOMINMAX" (компилируется исходный файл Hooks\vfunc_hook.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\Hooks\vfunc_hook.hpp(2,1): warning C4005: NOMINMAX: изменение макроопределения (компилируется исходный файл Hacks\Visuals.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\pch.cpp : message : см. предыдущее определение "NOMINMAX" (компилируется исходный файл Hacks\Visuals.cpp)
1>  VmtHook.cpp
1>  VmtSwap.cpp
1>  imguiCustom.cpp
1>  imgui_freetype.cpp
1>  imgui_stdlib.cpp
1>  imgui_tables.cpp
1>  InputUtil.cpp
1>  Inventory.cpp
1>  InventoryChanger.cpp
1>  ItemGenerator.cpp
1>  StaticData.cpp
1>  ToolUser.cpp
1>  Netvars.cpp
1>  Osiris.cpp
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\Hooks\vfunc_hook.hpp(2,1): warning C4005: NOMINMAX: изменение макроопределения (компилируется исходный файл Osiris.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\pch.cpp : message : см. предыдущее определение "NOMINMAX" (компилируется исходный файл Osiris.cpp)
1>  GUI.cpp
1>  Misc.cpp
1>  Hooks.cpp
1>  imgui.cpp
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\GUI.cpp(311,115): warning C4244: аргумент: преобразование "float" в "ImGuiSliderFlags", возможна потеря данных
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\GUI.cpp(312,117): warning C4244: аргумент: преобразование "float" в "ImGuiSliderFlags", возможна потеря данных
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\Hooks\vfunc_hook.hpp(2,1): warning C4005: NOMINMAX: изменение макроопределения (компилируется исходный файл Hacks\Misc.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\pch.cpp : message : см. предыдущее определение "NOMINMAX" (компилируется исходный файл Hacks\Misc.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\Hooks\vfunc_hook.hpp(2,1): warning C4005: NOMINMAX: изменение макроопределения (компилируется исходный файл Hooks.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\pch.cpp : message : см. предыдущее определение "NOMINMAX" (компилируется исходный файл Hooks.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\Hacks\Misc.cpp(359,23): warning C4018: <: несоответствие типов со знаком и без знака
1>  imgui_demo.cpp
1>  imgui_draw.cpp
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\Hacks\Misc.cpp(1607,32): warning C4018: <: несоответствие типов со знаком и без знака
1>  imgui_impl_dx9.cpp
1>  imgui_impl_win32.cpp
1>  imgui_widgets.cpp
1>  Memory.cpp
1>  Protobuffs.cpp
1>  valve_parser.cpp
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\ProfileChanger\valve_parser.h(1,1): warning C4828: Файл содержит знак, начинающийся со смещения 0x67d, который является недопустимым в текущей исходной кодировке (кодовая страница 65001). (компилируется исходный файл ProfileChanger\valve_parser.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\ProfileChanger\valve_parser.h(1,1): warning C4828: Файл содержит знак, начинающийся со смещения 0x683, который является недопустимым в текущей исходной кодировке (кодовая страница 65001). (компилируется исходный файл ProfileChanger\valve_parser.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\ProfileChanger\valve_parser.h(1,1): warning C4828: Файл содержит знак, начинающийся со смещения 0x8cc, который является недопустимым в текущей исходной кодировке (кодовая страница 65001). (компилируется исходный файл ProfileChanger\valve_parser.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\ProfileChanger\valve_parser.h(1,1): warning C4828: Файл содержит знак, начинающийся со смещения 0x8d2, который является недопустимым в текущей исходной кодировке (кодовая страница 65001). (компилируется исходный файл ProfileChanger\valve_parser.cpp)
1>  EconItemView.cpp
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\ProfileChanger\valve_parser.h(53,22): warning C4244: аргумент: преобразование "char32_t" в "_Ty", возможна потеря данных
1>          with
1>          [
1>              _Ty=char16_t
1>          ] (компилируется исходный файл ProfileChanger\valve_parser.cpp)
1>  Entity.cpp
1>  GlobalVars.cpp
1>  KeyValues.cpp
1>  Utils.cpp
1>  Texture.cpp
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\ProfileChanger\valve_parser.h(1,1): warning C4828: Файл содержит знак, начинающийся со смещения 0x67d, который является недопустимым в текущей исходной кодировке (кодовая страница 65001). (компилируется исходный файл ProfileChanger\Protobuffs.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\ProfileChanger\valve_parser.h(1,1): warning C4828: Файл содержит знак, начинающийся со смещения 0x683, который является недопустимым в текущей исходной кодировке (кодовая страница 65001). (компилируется исходный файл ProfileChanger\Protobuffs.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\ProfileChanger\valve_parser.h(1,1): warning C4828: Файл содержит знак, начинающийся со смещения 0x8cc, который является недопустимым в текущей исходной кодировке (кодовая страница 65001). (компилируется исходный файл ProfileChanger\Protobuffs.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\ProfileChanger\valve_parser.h(1,1): warning C4828: Файл содержит знак, начинающийся со смещения 0x8d2, который является недопустимым в текущей исходной кодировке (кодовая страница 65001). (компилируется исходный файл ProfileChanger\Protobuffs.cpp)
1>Z:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30130\include\xstring(2575,23): warning C4244: аргумент: преобразование "char16_t" в "const _Elem", возможна потеря данных
1>          with
1>          [
1>              _Elem=char
1>          ] (компилируется исходный файл ProfileChanger\valve_parser.cpp)
1>Z:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30130\include\xstring(2586): message : выполняется компиляция ссылки на экземпляр шаблон функции "void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<char16_t*>(_Iter,const _Iter,std::input_iterator_tag)"
1>          with
1>          [
1>              _Iter=char16_t *
1>          ] (компилируется исходный файл ProfileChanger\valve_parser.cpp)
1>Z:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30130\include\xstring(2586): message : выполняется компиляция ссылки на экземпляр шаблон функции "void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<char16_t*>(_Iter,const _Iter,std::input_iterator_tag)"
1>          with
1>          [
1>              _Iter=char16_t *
1>          ] (компилируется исходный файл ProfileChanger\valve_parser.cpp)
1>Z:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30130\include\xstring(2566): message : выполняется компиляция ссылки на экземпляр шаблон функции "void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<char16_t*>(const _Iter,const _Iter,std::forward_iterator_tag)"
1>          with
1>          [
1>              _Iter=char16_t *
1>          ] (компилируется исходный файл ProfileChanger\valve_parser.cpp)
1>Z:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30130\include\xstring(2566): message : выполняется компиляция ссылки на экземпляр шаблон функции "void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<char16_t*>(const _Iter,const _Iter,std::forward_iterator_tag)"
1>          with
1>          [
1>              _Iter=char16_t *
1>          ] (компилируется исходный файл ProfileChanger\valve_parser.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\ProfileChanger\valve_parser.h(53,22): warning C4244: аргумент: преобразование "char32_t" в "_Ty", возможна потеря данных
1>          with
1>          [
1>              _Ty=char16_t
1>          ] (компилируется исходный файл ProfileChanger\Protobuffs.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\ProfileChanger\valve_parser.h(66): message : выполняется компиляция ссылки на экземпляр шаблон функции "std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Elem>>>,0>(_Iter,_Iter,const _Alloc &)"
1>          with
1>          [
1>              _Elem=char16_t,
1>              _Iter=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<char16_t>>>,
1>              _Alloc=std::allocator<char>
1>          ] (компилируется исходный файл ProfileChanger\valve_parser.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\ProfileChanger\valve_parser.h(66): message : выполняется компиляция ссылки на экземпляр шаблон функции "std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Elem>>>,0>(_Iter,_Iter,const _Alloc &)"
1>          with
1>          [
1>              _Elem=char16_t,
1>              _Iter=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<char16_t>>>,
1>              _Alloc=std::allocator<char>
1>          ] (компилируется исходный файл ProfileChanger\valve_parser.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\ProfileChanger\valve_parser.h(700): warning C4715: valve_parser::Document::identify: значение возвращается не при всех путях выполнения
1>Z:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30130\include\xstring(2575,23): warning C4244: аргумент: преобразование "char16_t" в "const _Elem", возможна потеря данных
1>          with
1>          [
1>              _Elem=char
1>          ] (компилируется исходный файл ProfileChanger\Protobuffs.cpp)
1>Z:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30130\include\xstring(2586): message : выполняется компиляция ссылки на экземпляр шаблон функции "void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<char16_t*>(_Iter,const _Iter,std::input_iterator_tag)"
1>          with
1>          [
1>              _Iter=char16_t *
1>          ] (компилируется исходный файл ProfileChanger\Protobuffs.cpp)
1>Z:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30130\include\xstring(2586): message : выполняется компиляция ссылки на экземпляр шаблон функции "void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<char16_t*>(_Iter,const _Iter,std::input_iterator_tag)"
1>          with
1>          [
1>              _Iter=char16_t *
1>          ] (компилируется исходный файл ProfileChanger\Protobuffs.cpp)
1>Z:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30130\include\xstring(2566): message : выполняется компиляция ссылки на экземпляр шаблон функции "void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<char16_t*>(const _Iter,const _Iter,std::forward_iterator_tag)"
1>          with
1>          [
1>              _Iter=char16_t *
1>          ] (компилируется исходный файл ProfileChanger\Protobuffs.cpp)
1>Z:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30130\include\xstring(2566): message : выполняется компиляция ссылки на экземпляр шаблон функции "void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<char16_t*>(const _Iter,const _Iter,std::forward_iterator_tag)"
1>          with
1>          [
1>              _Iter=char16_t *
1>          ] (компилируется исходный файл ProfileChanger\Protobuffs.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\ProfileChanger\valve_parser.h(66): message : выполняется компиляция ссылки на экземпляр шаблон функции "std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Elem>>>,0>(_Iter,_Iter,const _Alloc &)"
1>          with
1>          [
1>              _Elem=char16_t,
1>              _Iter=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<char16_t>>>,
1>              _Alloc=std::allocator<char>
1>          ] (компилируется исходный файл ProfileChanger\Protobuffs.cpp)
1>Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Osiris\ProfileChanger\valve_parser.h(66): message : выполняется компиляция ссылки на экземпляр шаблон функции "std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Elem>>>,0>(_Iter,_Iter,const _Alloc &)"
1>          with
1>          [
1>              _Elem=char16_t,
1>              _Iter=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<char16_t>>>,
1>              _Alloc=std::allocator<char>
1>          ] (компилируется исходный файл ProfileChanger\Protobuffs.cpp)
1>  autofit.c
1>  ftbase.c
1>  ftbitmap.c
1>  ftdebug.c
1>  ftglyph.c
1>  ftinit.c
1>  ftsynth.c
1>  ftsystem.c
1>  cff.c
1>  psaux.c
1>  pshinter.c
1>  psnames.c
1>  raster.c
1>  sfnt.c
1>  smooth.c
1>  truetype.c
1>  buffer.c
1>  hde32.c
1>  hde64.c
1>  hook.c
1>  trampoline.c
1>  LINK : не найден или не выполнена сборка Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Debug\Osiris.dll при последней инкрементной компоновке; выполняется полная компоновка
1>  Osiris.vcxproj -> Z:\Users\Peeeach-Moro\source\repos\210728 — копия\Debug\Osiris.dll
========== Сборка: 1 успешно, 0 неудачно, 0 актуально, 0 пропущено ==========

**Comment by R3nzTheCodeGOD** [comment]
Dude, you're kidding us, you're copying a feature from the pull request section and then posting it here because it didn't work.

Your game crashes while loading the config file, don't you think the first places to look are clear?
