### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#3161]
WTF, I don't understand why the error is
![image](https://user-images.githubusercontent.com/63977167/127941849-548c14bc-323d-46ba-8129-973f55f8df53.png)
![image](https://user-images.githubusercontent.com/63977167/127941854-c22a7db7-36bd-4420-a9ff-66d87b3e15fb.png)

**Comment by R3nzTheCodeGOD** [comment]
look dude, you're really funny, first of all, you changed the code, how do we know how your Entity class is?

Secondly
```cpp
if (!entity || !(entity->getClientClass()->classId == ClassId::CSRagdoll))
```
The second condition of this if statement is wrong. You should put the `!` operator at the beginning. Do not open an issue here for the places you changed from the pull request section.

**Comment by floydGG** [comment]
> look dude, you're really funny, first of all, you changed the code, how do we know how your Entity class is?
> 
> Secondly
> 
> ```c++
> if (!entity || !(entity->getClientClass()->classId == ClassId::CSRagdoll))
> ```
> 
> The second condition of this if statement is wrong. You should put the `!` operator at the beginning. Do not open an issue here for the places you changed from the pull request section.

he just really create a new issues for his stupidity, like wtf
