### ISSUE TITLE
[BUG] custom kill/hitsound doesnt work on mm

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#3164]
If you loaded offline with bots or custom map, hitsound will work. But, once you cliked play button. it says "unable to queue due to thirdparty files loaded", if you restarted the game and loaded the config with custom hitsound. when you clicked the play button and you are in the game. custom kill/hit doenst work

**Comment by Xonn1com** [comment]
Bypass sv_pure #2935

**Comment by floydGG** [comment]
> Bypass sv_pure #2935

doesn't work anymore

**Comment by wemanzoz** [comment]
pls fix
