### ISSUE TITLE
Can someone help me please ? 

### ISSUE THREAD

**Issue by uzdiiilekk** [danielkrupinski/Osiris#3165]
Hello i want to ask if can someone help me with error because i trying to search it on google how to fix it but without any progress..
 These errors - There is no suitable function to convert from "KeyBind" to." Int" https://ctrlv.cz/0IYE
                      - SHORT GetAsyncKeyState (int): Cannot convert argument 1 from: KeyBind to: int.
 and i have the same problem with jumpbug

**Comment by floydGG** [comment]
#3163
