### ISSUE TITLE
Can't inject, prob system issue

### ISSUE THREAD

**Issue by AquaticBUBU** [danielkrupinski/Osiris#3166]
I've used multiple injectors such as newest version csghost and Osiris. I built Osiris myself and turned off all antivirus and window defender. I haven't have this issue for the past 3 weeks. I think it is a system issue cause I've used multiple dlls and injectors and non of them inject successfully. All of them show success but nothing is getting injected.

**Comment by AquaticBUBU** [comment]
the dll isn't a loaded module after injection

**Comment by wemanzoz** [comment]
huh, odd

**Comment by wemanzoz** [comment]
idk the fix but at this point try reinstall windows

**Comment by AquaticBUBU** [comment]
tried -insecure, but that didn't work either, currently running csghost 4.2.1. Had contacted with the creator of csghost but the problem is still unfixed.

**Comment by 0xMDIV** [comment]
still no fix
