### ISSUE TITLE
FPS drops right after injection

### ISSUE THREAD

**Issue by psSenpai** [danielkrupinski/Osiris#3167]
Hello,
after I inject Osiris my fps ingame drop under 60 instantly. I used Osiris several times and had no issue, but now that happens.
I already looked trough some issues here, unfortunately nothing helped. If any of you know a fix, I would appreciate it a lot if you could drop 'em in this issue thread.
Edit: After I unhook it I have my 240+ fps again

**Comment by sarahdumby** [comment]
Been having the same. I get around 300 fps before, but after injecting I get 120.

**Comment by R3nzTheCodeGOD** [comment]
Clone the latest version of Osiris and enable AVX2 technology if your processor supports it.

**Comment by psSenpai** [comment]
> Clone the latest version of Osiris and enable AVX2 technology if your processor supports it.

Doesn't work
