### ISSUE TITLE
[Linux] Crashing when using inventory changer in retake matches (config provided)

### ISSUE THREAD

**Issue by Metaphysical1** [danielkrupinski/Osiris#3168]
Game crashes when you equip item with inventory changer during weapon selection screen in retake matches, in both offline and online matches on linux.
edit: It seems it crashes with some skins of some weapons, anyways here is my config:
https://gist.github.com/Metaphysical1/acd4e7c555835b20d5a2debecaa9048c

**Comment by Xonn1com** [comment]
Strange :/ Works for me

**Comment by mdilai** [comment]
I have feel that this isn't related to inventory changer configuration. Sometimes i got this bug until i disable quick reload. But than i enable it and have no crashes anymore. Probably this is a weird memory bug, but i don't know how to use gdb properly :(

**Comment by Metaphysical1** [comment]
close this, it turns out it's a bug with the game itself as it sometimes crashes even without injection.
