### ISSUE TITLE
Aimbot not working with Left Mouse (firing button)

### ISSUE THREAD

**Issue by KevinRommens** [danielkrupinski/Osiris#3169]
The aimbot doesn't lock on an enemy with pistols when I press and hold down Left Mouse, which is my firing button. I have tested with turning Between Shots on and off, and it's practically the same for the pistols. Please do make the aimbot able to be turned on when the firing button is held down.

Thanks.

**Comment by kcboiz** [comment]
I have same problem, other keys work normally except left mouse button

**Comment by floydGG** [comment]
Just enable without key, and disable Aimlock

**Comment by blackMasterLord** [comment]
This happens due to the different response times of the button press.

**Comment by KevinRommens** [comment]
> This happens due to the different response times of the button press.

bruh. why not make a check where it does GetASyncKeyState, with the button selected, and then checks 0x8000. 0x8000 is a check to see if a button is held down or not*.
I don't know if this is actually done in the cheat. but I have searched the menu and the aimbot and i haven't found 0x8000 anywhere.

**Comment by blackMasterLord** [comment]
Here, button clicks are checked by ImGui.

**Comment by blackMasterLord** [comment]
GetAsyncKeyState is not used.
