### ISSUE TITLE
Auto Shoot, Silient Aim

### ISSUE THREAD

**Issue by NameNotTakenYAY** [danielkrupinski/Osiris#317]
Auto Shoot, Silient Aim. Both not working. and add  a fov circle or box pls

**Comment by Alpha878** [comment]
Silent Aim is working if you don't use Auto Shoot. Auto Shoot basically breaks somehow Silent Aim and both of not working. Just use Silent Aim only until @danielkrupinski will fix it.

**Comment by danielkrupinski** [comment]
You need to set "Max angle delta" when using autoshot option.
