### ISSUE TITLE
[Question] Can i remove the RCS in Aimbot?

### ISSUE THREAD

**Issue by floydGG** [danielkrupinski/Osiris#3170]
Just like the title, and if so what should i change?

**Comment by Shuvi-Moro** [comment]
You can, but why do you need it?

**Comment by floydGG** [comment]
> You can, but why do you need it?

That is why i want to remove it, cuz i don't need it.

**Comment by blackMasterLord** [comment]
use this #3171
and disable **"Between Shots"**

**Comment by floydGG** [comment]
> use this #3171
> and turn off **"Between Shots"**

Turn off in Aimbot tab or in sln? i never use Between shots tho

**Comment by blackMasterLord** [comment]
> > use this #3171
> > and turn off **"Between Shots"**
> 
> Turn off in Aimbot tab or in sln? i never use Between shots tho

Turn off in Aimbot tab

**Comment by floydGG** [comment]
> > > use this #3171
> > > and turn off **"Between Shots"**
> > 
> > 
> > Turn off in Aimbot tab or in sln? i never use Between shots tho
> 
> Turn off in Aimbot tab

So the rcs only active when using Between Shots on?

**Comment by blackMasterLord** [comment]
> o the rcs only active when using B

yes

**Comment by floydGG** [comment]
> > o the rcs only active when using B
> 
> yes

Ah thank you
