### ISSUE TITLE
during Arms race my m4a4 skin gets applied to my m4a1-s this also happens to usp and cz does someone know how to fix this o

### ISSUE THREAD

**Issue by 0killdude** [danielkrupinski/Osiris#3173]

**Comment by blackMasterLord** [comment]
#3174

**Comment by 0killdude** [comment]
hey blackmaster i tried to buld the cheat with visual studio code 2019 but im unbale to for some reason is there a video on the internet that can show me how to do this

**Comment by blackMasterLord** [comment]
just download and compile this [CLICK](https://github.com/blackMasterLord/Osiris/tree/Arms-Race-Inventory-Changer-fix)

**Comment by danielkrupinski** [comment]
Fixed by 27f83ac6042902b4562ba522f8e29c8f8edc8f11.
