### ISSUE TITLE
Assertion Failed Error

### ISSUE THREAD

**Issue by NickzAlz** [danielkrupinski/Osiris#3187]
I get an assertion failed error everytime i load csgo with osiris

**Comment by danielkrupinski** [comment]
Please post a screenshot of the error.

**Comment by n0verify** [comment]
> Please post a screenshot of the error.

Error just started popping after update

![download](https://user-images.githubusercontent.com/86177056/128949209-1ac76f9a-f162-42c7-9b5e-b48e0dd9bef9.png)

appears here:



```
static std::uintptr_t findPattern(const char* moduleName, std::string_view pattern, bool reportNotFound = true) noexcept
{
    static auto id = 0;
    ++id;

    const auto [moduleBase, moduleSize] = getModuleInformation(moduleName);

    if (moduleBase && moduleSize) {
        const auto lastIdx = pattern.length() - 1;
        const auto badCharTable = generateBadCharTable(pattern);

        auto start = static_cast<const char*>(moduleBase);
        const auto end = start + moduleSize - pattern.length();

        while (start <= end) {
            int i = lastIdx;
            while (i >= 0 && (pattern[i] == '?' || start[i] == pattern[i]))
                --i;

            if (i < 0)
                return reinterpret_cast<std::uintptr_t>(start);

            start += badCharTable[static_cast<std::uint8_t>(start[lastIdx])];
        }
    }

    assert(false);
#ifdef _WIN32
    if (reportNotFound)
        MessageBoxA(nullptr, ("Failed to find pattern #" + std::to_string(id) + '!').c_str(), "FUCKTHEPOPULATION", MB_OK | MB_ICONWARNING);
#endif
    return 0;
}
```

by the looks of it, the update has fucked with some patterns

**Comment by Xonn1com** [comment]
> 
> 
> > Please post a screenshot of the error.
> 
> Error just started popping after update
> 
> ![download](https://user-images.githubusercontent.com/86177056/128949209-1ac76f9a-f162-42c7-9b5e-b48e0dd9bef9.png)
> 
> appears here:
> 
> ```
> static std::uintptr_t findPattern(const char* moduleName, std::string_view pattern, bool reportNotFound = true) noexcept
> {
>     static auto id = 0;
>     ++id;
> 
>     const auto [moduleBase, moduleSize] = getModuleInformation(moduleName);
> 
>     if (moduleBase && moduleSize) {
>         const auto lastIdx = pattern.length() - 1;
>         const auto badCharTable = generateBadCharTable(pattern);
> 
>         auto start = static_cast<const char*>(moduleBase);
>         const auto end = start + moduleSize - pattern.length();
> 
>         while (start <= end) {
>             int i = lastIdx;
>             while (i >= 0 && (pattern[i] == '?' || start[i] == pattern[i]))
>                 --i;
> 
>             if (i < 0)
>                 return reinterpret_cast<std::uintptr_t>(start);
> 
>             start += badCharTable[static_cast<std::uint8_t>(start[lastIdx])];
>         }
>     }
> 
>     assert(false);
> #ifdef _WIN32
>     if (reportNotFound)
>         MessageBoxA(nullptr, ("Failed to find pattern #" + std::to_string(id) + '!').c_str(), "FUCKTHEPOPULATION", MB_OK | MB_ICONWARNING);
> #endif
>     return 0;
> }
> ```
> 
> by the looks of it, the update has fucked with some patterns

actually, this screen isn't from Osiris but repo "ftp_loader"

**Comment by n0verify** [comment]
> > > Please post a screenshot of the error.
> > 
> > 
> > Error just started popping after update
> > ![download](https://user-images.githubusercontent.com/86177056/128949209-1ac76f9a-f162-42c7-9b5e-b48e0dd9bef9.png)
> > appears here:
> > ```
> > static std::uintptr_t findPattern(const char* moduleName, std::string_view pattern, bool reportNotFound = true) noexcept
> > {
> >     static auto id = 0;
> >     ++id;
> > 
> >     const auto [moduleBase, moduleSize] = getModuleInformation(moduleName);
> > 
> >     if (moduleBase && moduleSize) {
> >         const auto lastIdx = pattern.length() - 1;
> >         const auto badCharTable = generateBadCharTable(pattern);
> > 
> >         auto start = static_cast<const char*>(moduleBase);
> >         const auto end = start + moduleSize - pattern.length();
> > 
> >         while (start <= end) {
> >             int i = lastIdx;
> >             while (i >= 0 && (pattern[i] == '?' || start[i] == pattern[i]))
> >                 --i;
> > 
> >             if (i < 0)
> >                 return reinterpret_cast<std::uintptr_t>(start);
> > 
> >             start += badCharTable[static_cast<std::uint8_t>(start[lastIdx])];
> >         }
> >     }
> > 
> >     assert(false);
> > #ifdef _WIN32
> >     if (reportNotFound)
> >         MessageBoxA(nullptr, ("Failed to find pattern #" + std::to_string(id) + '!').c_str(), "FUCKTHEPOPULATION", MB_OK | MB_ICONWARNING);
> > #endif
> >     return 0;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > by the looks of it, the update has fucked with some patterns
> 
> actually, this screen isn't from Osiris but repo "ftp_loader"

same cheat, different name

**Comment by floydGG** [comment]
lmao

**Comment by Xonn1com** [comment]
> 
> 
> > > > Please post a screenshot of the error.
> > > 
> > > 
> > > Error just started popping after update
> > > ![download](https://user-images.githubusercontent.com/86177056/128949209-1ac76f9a-f162-42c7-9b5e-b48e0dd9bef9.png)
> > > appears here:
> > > ```
> > > static std::uintptr_t findPattern(const char* moduleName, std::string_view pattern, bool reportNotFound = true) noexcept
> > > {
> > >     static auto id = 0;
> > >     ++id;
> > > 
> > >     const auto [moduleBase, moduleSize] = getModuleInformation(moduleName);
> > > 
> > >     if (moduleBase && moduleSize) {
> > >         const auto lastIdx = pattern.length() - 1;
> > >         const auto badCharTable = generateBadCharTable(pattern);
> > > 
> > >         auto start = static_cast<const char*>(moduleBase);
> > >         const auto end = start + moduleSize - pattern.length();
> > > 
> > >         while (start <= end) {
> > >             int i = lastIdx;
> > >             while (i >= 0 && (pattern[i] == '?' || start[i] == pattern[i]))
> > >                 --i;
> > > 
> > >             if (i < 0)
> > >                 return reinterpret_cast<std::uintptr_t>(start);
> > > 
> > >             start += badCharTable[static_cast<std::uint8_t>(start[lastIdx])];
> > >         }
> > >     }
> > > 
> > >     assert(false);
> > > #ifdef _WIN32
> > >     if (reportNotFound)
> > >         MessageBoxA(nullptr, ("Failed to find pattern #" + std::to_string(id) + '!').c_str(), "FUCKTHEPOPULATION", MB_OK | MB_ICONWARNING);
> > > #endif
> > >     return 0;
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > by the looks of it, the update has fucked with some patterns
> > 
> > 
> > actually, this screen isn't from Osiris but repo "ftp_loader"
> 
> same cheat, different name

Well, yes and no;
Using FTP I get the same error and i don't have any Aubrey folder in users
![obraz](https://user-images.githubusercontent.com/64926921/129085558-23c15b8b-4d78-4938-90a9-6faa18417ba8.png)

**Comment by mdilai** [comment]
Go and bore fork author, here you can complain only about latest master commit. Probably it just have outdated signatures. Any cheat valid only few weeks after release at most.
