### ISSUE TITLE
failed to find pattern #17

### ISSUE THREAD

**Issue by max-zhouu** [danielkrupinski/Osiris#3188]
I keep getting this message even though I rebuilt Osiris.dll multiple times. Im using Shtreeba injector. is that the problem?

**Comment by H3artdown** [comment]
no game update issue, wait for danie update or just update by yourself

**Comment by configbrowser** [comment]
How do you update this by yourself

Its something with     present = findPattern(L"gameoverlayrenderer", "\xFF\x15????\x8B\xF0\x85\xFF") + 2;
    reset = findPattern(L"gameoverlayrenderer", "\xC7\x45?????\xFF\x15????\x8B\xD8") + 9;

anyone here know how to update it yourself?

**Comment by 2933968621** [comment]
modify traceToExit pattern to \x55\x8B\xEC\x83\xEC\x4C\xF3\x0F\x10\x75

**Comment by floydGG** [comment]
> modify traceToExit pattern to \x55\x8B\xEC\x83\xEC\x4C\xF3\x0F\x10\x75

the new updates about traceToExit ? or game overlay?

**Comment by 2933968621** [comment]
> > modify traceToExit pattern to \x55\x8B\xEC\x83\xEC\x4C\xF3\x0F\x10\x75
> 
> the new updates about traceToExit ? or game overlay?

traceToExit

**Comment by floydGG** [comment]
> > > modify traceToExit pattern to \x55\x8B\xEC\x83\xEC\x4C\xF3\x0F\x10\x75
> > 
> > 
> > the new updates about traceToExit ? or game overlay?
> 
> traceToExit

thanks man

**Comment by floydGG** [comment]
> > > modify traceToExit pattern to \x55\x8B\xEC\x83\xEC\x4C\xF3\x0F\x10\x75
> > 
> > 
> > the new updates about traceToExit ? or game overlay?
> 
> traceToExit

yeah anyway, changing the pattern make ur game crashed after few minutes.

**Comment by 2933968621** [comment]
> > > > modify traceToExit pattern to \x55\x8B\xEC\x83\xEC\x4C\xF3\x0F\x10\x75
> > > 
> > > 
> > > the new updates about traceToExit ? or game overlay?
> > 
> > 
> > traceToExit
> 
> yeah anyway, changing the pattern make ur game crashed after few minutes.

u can try disable aimbot traceToExit (return false)

**Comment by floydGG** [comment]
> > > > > modify traceToExit pattern to \x55\x8B\xEC\x83\xEC\x4C\xF3\x0F\x10\x75
> > > > 
> > > > 
> > > > the new updates about traceToExit ? or game overlay?
> > > 
> > > 
> > > traceToExit
> > 
> > 
> > yeah anyway, changing the pattern make ur game crashed after few minutes.
> 
> u can try disable aimbot traceToExit (return false)

what lines? in aimbot.cpp right?

**Comment by floydGG** [comment]
> > > > > > > modify traceToExit pattern to \x55\x8B\xEC\x83\xEC\x4C\xF3\x0F\x10\x75
> > > > > > 
> > > > > > 
> > > > > > the new updates about traceToExit ? or game overlay?
> > > > > 
> > > > > 
> > > > > traceToExit
> > > > 
> > > > 
> > > > yeah anyway, changing the pattern make ur game crashed after few minutes.
> > > 
> > > 
> > > u can try disable aimbot traceToExit (return false)
> > 
> > 
> > what lines? in aimbot.cpp right?
> 
> yes,bool traceToExit,u need return false;>

https://github.com/danielkrupinski/Osiris/blob/965022065ea3ea190384eec9db36c7a0ed75dd26/Osiris/Hacks/Aimbot.cpp#L30
this one?

**Comment by 2933968621** [comment]
> > > > > > > > modify traceToExit pattern to \x55\x8B\xEC\x83\xEC\x4C\xF3\x0F\x10\x75
> > > > > > > 
> > > > > > > 
> > > > > > > the new updates about traceToExit ? or game overlay?
> > > > > > 
> > > > > > 
> > > > > > traceToExit
> > > > > 
> > > > > 
> > > > > yeah anyway, changing the pattern make ur game crashed after few minutes.
> > > > 
> > > > 
> > > > u can try disable aimbot traceToExit (return false)
> > > 
> > > 
> > > what lines? in aimbot.cpp right?
> > 
> > 
> > yes,bool traceToExit,u need return false;>
> 
> https://github.com/danielkrupinski/Osiris/blob/965022065ea3ea190384eec9db36c7a0ed75dd26/Osiris/Hacks/Aimbot.cpp#L30
> 
> 
> this one?

yes, u can see this https://github.com/danielkrupinski/Osiris/commit/9f24bf663135aeaf3d0283cc69ffb1f79a882e40

**Comment by floydGG** [comment]
> > > > > > > > > modify traceToExit pattern to \x55\x8B\xEC\x83\xEC\x4C\xF3\x0F\x10\x75
> > > > > > > > 
> > > > > > > > 
> > > > > > > > the new updates about traceToExit ? or game overlay?
> > > > > > > 
> > > > > > > 
> > > > > > > traceToExit
> > > > > > 
> > > > > > 
> > > > > > yeah anyway, changing the pattern make ur game crashed after few minutes.
> > > > > 
> > > > > 
> > > > > u can try disable aimbot traceToExit (return false)
> > > > 
> > > > 
> > > > what lines? in aimbot.cpp right?
> > > 
> > > 
> > > yes,bool traceToExit,u need return false;>
> > 
> > 
> > https://github.com/danielkrupinski/Osiris/blob/965022065ea3ea190384eec9db36c7a0ed75dd26/Osiris/Hacks/Aimbot.cpp#L30
> > 
> > this one?
> 
> yes, u can see this [9f24bf6](https://github.com/danielkrupinski/Osiris/commit/9f24bf663135aeaf3d0283cc69ffb1f79a882e40)

@danielkrupinski just updated it, thanks anyway
