### ISSUE TITLE
[Suggestion] Add a blockbot

### ISSUE THREAD

**Issue by bruhdood** [danielkrupinski/Osiris#319]
You will be able to hold down a button and you will copy the movement of the person in front of you, most likely a teammate. Also have it so when you are on someone's head you will copy their movements so they cant get you off of them.

**Comment by KriXxPlay** [comment]
Useless af

**Comment by B0ruK** [comment]
> Useless af

usefull for griefing

**Comment by effex1337** [comment]
I'm guessing blockbot is coming soon I was trying to add it but i didn't have get eye angles which is now available. :)

**Comment by bruhdood** [comment]
> I'm guessing blockbot is coming soon I was trying to add it but i didn't have get eye angles which is now available. :)

yeah im hoping it will be added soon ive been looking for a good free cheat with a blockbot

**Comment by l0ccy** [comment]
+++1
