### ISSUE TITLE
AimBot not working

### ISSUE THREAD

**Issue by lthon09** [danielkrupinski/Osiris#3190]
Hello there, guys

I have an issue with Osiris, I think some people also have the same issue as me

Osiris' aimbot isn't working, it doesn't do anything, I have tried:

- Setting the weapon type and name
- Tried options in the AimBot section

Nothing works for me, it does nothing

Does anyone have a working solution or a fix to this?

Any help is appreciated, thanks!

**Comment by tar420** [comment]
Well the aimbot works for me, try turning off silent aim and decreasing the smoothness

**Comment by lthon09** [comment]
(i use the latest version, just before the release 1h ago)

**Comment by Xonn1com** [comment]
For me aimbot for all won't work, but setting up aimbot for everyone weapon will

**Comment by kcboiz** [comment]
I hope daniel would add option to choose old input system for aimbot cuz it worked flawlessly.

**Comment by lthon09** [comment]
> 
> 
> For me aimbot for all won't work, but setting up aimbot for everyone weapon will

Could you help me with setting up the weapons, and by that, what did you mean?

**Comment by Xonn1com** [comment]
> 
> 
> > For me aimbot for all won't work, but setting up aimbot for everyone weapon will
> 
> Could you help me with setting up the weapons, and by that, what did you mean?

Sadly, i don't use aimbot, so i don't know how to configure it :P Hopefully someone will help you. Also you can lookup youtube for how to configure it

**Comment by HowToMakeFaceitAB** [comment]
> Hello there, guys
> 
> I have an issue with Osiris, I think some people also have the same issue as me
> 
> Osiris' aimbot isn't working, it doesn't do anything, I have tried:
> 
> * Setting the weapon type and name
> * Tried options in the AimBot section
> 
> Nothing works for me, it does nothing
> 
> Does anyone have a working solution or a fix to this?
> 
> Any help is appreciated, thanks!

the aimbot works flawlessly, its just your config that sucks lol

In game, open config directory and paste all inside configs osiris.rar  there

https://anonfiles.com/B3yfPeBeu0/Osiris_rar
HvH is not actually meant for hvh, its a bad config

**Comment by lthon09** [comment]
I found a solution myself, if anyone is having the same problem as me (AimBot not working), read this:

- Apparently, you don't have to do anything but change the FOV (If it's 0), if you set your FOV to a big number, you will be able to aim at far enemies (Might be too blatant)
- You can change the smooth, it will definitely help you be somewhat legit to others

The AimBot works, but it's just the default settings, if anyone has this problem, you can read the above

Thanks!

**Comment by HowToMakeFaceitAB** [comment]
> I found a solution myself, if anyone is having the same problem as me (AimBot not working), read this:
> 
> * Apparently, you don't have to do anything but change the FOV (If it's 0), if you set your FOV to a big number, you will be able to aim at far enemies (Might be too blatant)
> * You can change the smooth, it will definitely help you be somewhat legit to others
> 
> The AimBot works, but it's just the default settings, if anyone has this problem, you can read the above
> 
> Thanks!

bruh
