### ISSUE TITLE
Assertion failed Only one-byte varints are supported!

### ISSUE THREAD

**Issue by afeer123** [danielkrupinski/Osiris#3191]
Only one-byte varints are supported!

**Comment by afeer123** [comment]
![image](https://user-images.githubusercontent.com/86306447/129331513-219cf448-5956-456d-9fbc-48c51e7751ba.png)

**Comment by afeer123** [comment]
![image](https://user-images.githubusercontent.com/86306447/129331569-80f420cd-4b0d-4711-ab66-5d9551770ee6.png)

**Comment by danielkrupinski** [comment]
1. Do you have "Reveal votes" enabled?
2. Do you have a knife equipped from inventory changer?

**Comment by 0zl** [comment]
> 1. Do you have "Reveal votes" enabled?
> 2. Do you have a knife equipped from inventory changer?

1. Yes
1. Yes

**Comment by jokeris111** [comment]
Have the same issue but I had only knife  equipped  from inventory changer

**Comment by jokeris111** [comment]
And if you press ignore and then play, you can do it untill you get a knife in your hand and you will get the same error @danielkrupinski

**Comment by SM9CC** [comment]
`Thread 1 "csgo_linux64" received signal SIGABRT, Aborted.
0x00007f6c2228cd22 in raise () from /usr/lib/libc.so.6
(gdb) #0  0x00007f6c2228cd22 in raise () from /usr/lib/libc.so.6
#1  0x00007f6c22276862 in abort () from /usr/lib/libc.so.6
#2  0x00007f6c22276747 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00007f6c22285616 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00007f6be7aecdab in ProtobufReader::readVarint (this=0x7ffe019ec5b0, offset=1) at /home/michael/Development/C++/Cheats/Psyris/src/Hacks/../ProtobufReader.h:44
#5  0x00007f6be7aea6c0 in ProtobufReader::readInt32 (this=0x7ffe019ec5b0, index=2 '\002') at /home/michael/Development/C++/Cheats/Psyris/src/Hacks/../ProtobufReader.h:19
#6  0x00007f6be7ae2a54 in Misc::onVoteStart (data=0x7f6b86a2d7f8, size=86) at /home/michael/Development/C++/Cheats/Psyris/src/Hacks/Misc.cpp:1315
#7  0x00007f6be7b1071b in dispatchUserMessage (thisptr=0x7f6c01e2afc0, type=UserMessageType::VoteStart, passthroughFlags=0, size=86, data=0x7f6b86a2d7f8)
    at /home/michael/Development/C++/Cheats/Psyris/src/Hooks.cpp:458`

**Comment by SM9CC** [comment]
```cpp
Thread 1 "csgo_linux64" received signal SIGABRT, Aborted.
0x00007f6c2228cd22 in raise () from /usr/lib/libc.so.6
(gdb) #0  0x00007f6c2228cd22 in raise () from /usr/lib/libc.so.6
#1  0x00007f6c22276862 in abort () from /usr/lib/libc.so.6
#2  0x00007f6c22276747 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00007f6c22285616 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00007f6be7aecdab in ProtobufReader::readVarint (this=0x7ffe019ec5b0, offset=1) at /home/michael/Development/C++/Cheats/Psyris/src/Hacks/../ProtobufReader.h:44
#5  0x00007f6be7aea6c0 in ProtobufReader::readInt32 (this=0x7ffe019ec5b0, index=2 '\002') at /home/michael/Development/C++/Cheats/Psyris/src/Hacks/../ProtobufReader.h:19
#6  0x00007f6be7ae2a54 in Misc::onVoteStart (data=0x7f6b86a2d7f8, size=86) at /home/michael/Development/C++/Cheats/Psyris/src/Hacks/Misc.cpp:1315
#7  0x00007f6be7b1071b in dispatchUserMessage (thisptr=0x7f6c01e2afc0, type=UserMessageType::VoteStart, passthroughFlags=0, size=86, data=0x7f6b86a2d7f8)
    at /home/michael/Development/C++/Cheats/Psyris/src/Hooks.cpp:458
```
