### ISSUE TITLE
[Suggestion] Legit-aa mr. Osiris man

### ISSUE THREAD

**Issue by Smellon69** [danielkrupinski/Osiris#3194]
Hello danielkrupinski a.k.a osiris dev (built like the rock) I would love legit aa. Some packet manipulation and angles should do the trick

**Comment by floydGG** [comment]
no need since this is legit cheat

**Comment by rosesware** [comment]
> no need since this is legit cheat

?

**Comment by wemanzoz** [comment]
no need legit aa lol, its useless + its blatant af

**Comment by floydGG** [comment]
> > no need since this is legit cheat
> 
> ?

? you too

**Comment by Liam5750** [comment]
Huh? The whole point of legit as is to gain an advantage while legit cheating without turning on rage antiaim

**Comment by wemanzoz** [comment]
> Huh? The whole point of legit as is to gain an advantage while legit cheating without turning on rage antiaim

it aint legit cz its snappy af lol

**Comment by ReShout876** [comment]
> > Huh? The whole point of legit as is to gain an advantage while legit cheating without turning on rage antiaim
> 
> it aint legit cz its snappy af lol

The only snappy legitAA i know is from ot3/otc3

**Comment by Liam5750** [comment]
He means snappy aimbot he needs to fix the smoothing

**Comment by ReShout876** [comment]
Oh yeah.
