### ISSUE TITLE
Pattern error

### ISSUE THREAD

**Issue by Liam5750** [danielkrupinski/Osiris#3196]
This is #17 and pretty much instant untrusted ban

**Comment by floydGG** [comment]
use latest osiris my man, where u been?

**Comment by floydGG** [comment]
that is your injector not the cheats, lmao been using Osiris since forever

**Comment by reinzmet** [comment]
> 
> 
> that is your injector not the cheats, lmao been using Osiris since forever

what injector are you using?

**Comment by floydGG** [comment]
> > that is your injector not the cheats, lmao been using Osiris since forever
> 
> what injector are you using?

[https://github.com/mdilai/Shtreeba](url)
