### ISSUE TITLE
not injecting

### ISSUE THREAD

**Issue by aqsatti** [danielkrupinski/Osiris#32]
Been using osiris for a week now. One of the best free cheat out rn. I was using the previous version of osiris and saw that it was updated so i recompiled it and injected but my game crashed. It continued crashing for a few times as I was injecting but after fifth try it injected, but now as i pressed insert nothing showed up. Saw an old issue with same problem and verified the game files ,downloaded again and compiled but same issue.

**Comment by aleksander96** [comment]
Yes daniel, I am getting same issue after the new update. I tried with different injector but same results.

**Comment by danielkrupinski** [comment]
I can not reproduce the issue. Please delete your config file and try injecting again.

**Comment by aqsatti** [comment]
worked,thanks.
