### ISSUE TITLE
Not a refinement of the trigger

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#3200]
Trigger does not work when there is smoke behind the player, but the player is at a great distance from him https://www.dropbox.com/s/s6ml4t9uwgi39n3/Counter-strike%20%20Global%20Offensive%202021.08.17%20-%2020.15.07.04.mp4?dl=0

**Comment by Shuvi-Moro** [comment]
And yes I have a very heavily rewritten osiris, but I have not touched the trigger

**Comment by blackMasterLord** [comment]
If you've can rewrite Osiris, then fixing a couple of lines of code should be easy for you.
https://github.com/danielkrupinski/Osiris/blob/fe0fbfe23697fce2ba6948c65f073478ce2267ac/Osiris/Hacks/Triggerbot.cpp#L69-L73
