### ISSUE TITLE
The bullet tracer does not work

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#3201]
I did not touch the bullet tracer and I also did not touch all the functions associated with them
This bullet tracer is the original
https://www.dropbox.com/s/ojr5pis6mmbifaf/Counter-strike%20%20Global%20Offensive%202021.08.17%20-%2021.21.43.05.mp4?dl=0

**Comment by blackMasterLord** [comment]
Check your code please.
Everything works fine.
