### ISSUE TITLE
Skybox doesn't work

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#3202]
https://www.dropbox.com/s/03hoeei4nbhopgh/Desktop%202021.08.18%20-%2013.31.56.01.mp4?dl=0

**Comment by blackMasterLord** [comment]
Чел🤡, обнови **Osiris**, и проверь код на кастомные скайбоксы.
Всё работает.

**Comment by Shuvi-Moro** [comment]
на прямую скомпилировал чит скай бокс не работал сразу

**Comment by blackMasterLord** [comment]
Это у тебя проблема.
Всё работает.

**Comment by wheremyfiji** [comment]
Мужик, No 3d sky включи
