### ISSUE TITLE
Osiris crashed mid game.

### ISSUE THREAD

**Issue by Smallkittyy** [danielkrupinski/Osiris#3207]
yeah i cant play anymore with osiris,
after the last update of CS:GO (1day ago) osiris is crashing mid game.... 

everything work, i jhust get like 1000000 error messages in 1 minute.

please fix osiris...

**Comment by floydGG** [comment]
still works for me, might be using latest one.

**Comment by floydGG** [comment]
bro nothing crashed, pasted some features as well, working fine tho
