### ISSUE TITLE
add anti aim more features

### ISSUE THREAD

**Issue by homeless1337** [danielkrupinski/Osiris#3210]

**Comment by KurastikO** [comment]
Once again, this is a _legit cheat_ . If you want more features with anti-aim use interium or onetapv4

**Comment by wemanzoz** [comment]
> Once again, this is a _legit cheat_ . If you want more features with anti-aim +se interium or onetapv4

+

**Comment by b0yk3x** [comment]
??? this is a legit cheat and aa works very decent for an open-source cheat without any license
