### ISSUE TITLE
[suggestion] ragebot and anti aim

### ISSUE THREAD

**Issue by Mikquaj** [danielkrupinski/Osiris#3217]

**Comment by Liam5750** [comment]
ITS A LEGIT CHEAT STOP ASKING FOR RAGE. And it will be shit anyways sense all the newgens have nl

**Comment by Shuvi-Moro** [comment]
> ITS A LEGIT CHEAT STOP ASKING FOR RAGE. And it will be shit anyways sense all the newgens have nl

+

**Comment by Shuvi-Moro** [comment]
However, I agree that the anti-aim to do, as in the zone is not particularly convenient to go to the chelip and turn around 180 degrees and look down (if you can see that he cheats) and with anti-aim I would be able to reduce the angle of operation of the reader and it is useful
