### ISSUE TITLE
Anyone got a fix for the crashes? Constantly crash while loading into games and loading out.

### ISSUE THREAD

**Issue by sarahdumby** [danielkrupinski/Osiris#3218]

**Comment by floydGG** [comment]
try shtreeba ;)

**Comment by Shuvi-Moro** [comment]
I think shtreeba is not the best option, you just get fucked up with him to solve problems!
I don't remember where I got it.
https://www.dropbox.com/s/zkqo6537vc1m8ee/csgo-injector.exe?dl=0

**Comment by Shuvi-Moro** [comment]
The maximum I got with this injector is a patrol and after that in 3-4 days VAC

**Comment by floydGG** [comment]
something is wrong with ur pc lol
nothing is wrong with that injector, only u experience that
