### ISSUE TITLE
Help me write an auto-search once you are in the main menu

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#3219]
### Discussed in https://github.com/danielkrupinski/Osiris/discussions/3214

<div type='discussions-op-text'>

<sup>Originally posted by **Shuvi-Moro** August 25, 2021</sup>
How do I let the cheat know that you're in the main menu and what command can I use to configure the search</div>

danielkrupinski said:
You can check whether you're in the main menu with bool isInMainMenu = !interfaces->engine->isConnected();

And I still have a question how to get CSGO to start searching!

**Comment by blackMasterLord** [comment]
If you mean auto-search of competitive game - [THIS](https://www.unknowncheats.me/forum/counterstrike-global-offensive/289573-panorama-lobby-stuffs.html) would help u.
**OR**
Call `'onactivate'` event of `'#StartMatchBtn'` [CLICK](https://github.com/sapphyrus/panorama/blob/f8530fa796bf58699388f5fe7a69cd4ffc594258/scripts/mainmenu_play.js#L134)

**Comment by wemanzoz** [comment]
wdym?

**Comment by Liam5750** [comment]
U don't know how to code ig he just told you what to do xD
