### ISSUE TITLE
[Suggestion] Overwatch name revealer

### ISSUE THREAD

**Issue by AimlessDude** [danielkrupinski/Osiris#322]
A funtion which allows us to see the name of the suspect in the overwatch case.

I just saw that function in a video of bhop and it was kinda cool to see if the suspect gets banned or nah.

**Comment by 0xE232FE** [comment]
Most of my OW Cases are not players I played against with. Because this is against the independent judgment.

But I saw suspects from my other Accounts where I played against the suspect in a game. But I never judged a game where I played against the suspect myself! This is useless!

**Comment by temper1840** [comment]
You can use wireshark to find their profiles, its also kind of a useless feature tbh.

**Comment by danielkrupinski** [comment]
I've added some prototype revealer. It would be great if you could test it (it is enabled by default).
