### ISSUE TITLE
detected?

### ISSUE THREAD

**Issue by BigSmoke102** [danielkrupinski/Osiris#3222]
got banne din one day used visuals (only used sezinjecotor x86 build debug vac not overwatch)

**Comment by sarahdumby** [comment]
Why don't you use vac bypass and release build

**Comment by BigSmoke102** [comment]
> Why don't you use vac bypass and release build

(im new) how do i use vac bypass

**Comment by sarahdumby** [comment]
Just search it up here, I've heard csghost worked as well but i haven't checked

**Comment by BigSmoke102** [comment]
i found this https://github.com/danielkrupinski/VAC-Bypass lets say i wanna use it what do i do

**Comment by BigSmoke102** [comment]
m using sez injector btw it has a bypass

**Comment by sarahdumby** [comment]
> m using sez injector btw it has a bypass

Apparently not, use vac bypass loader by daniel, it has instructions on how to do it there.

**Comment by BigSmoke102** [comment]
> > m using sez injector btw it has a bypass
> 
> Apparently not, use vac bypass loader by daniel, it has instructions on how to do it there.

ill try another time

**Comment by yEsPaP** [comment]
use https://github.com/mdilai/Shtreeba injector
and https://github.com/danielkrupinski/vac-bypass-loader

close steam and open the vac-bypass-loader

**Comment by linuxer9** [comment]
no it's not, your injector is detected.
I've been using osiris with no modification and Injecting with process hacker, without vac bypass and no bans yet.

**Comment by sarahdumby** [comment]
> no it's not, your injector is detected.
> 
> I've been using osiris with no modification and Injecting with process hacker, without vac bypass and no bans yet.

How do you inject using process hacker? I thought they removed that.

**Comment by Shuvi-Moro** [comment]
> > no it's not, your injector is detected.
> > I've been using osiris with no modification and Injecting with process hacker, without vac bypass and no bans yet.
> 
> How do you inject using process hacker? I thought they removed that.

![image](https://user-images.githubusercontent.com/63977167/131568311-40aa121e-ae05-4663-954b-74312adcebcd.png)

**Comment by linuxer9** [comment]
> 
> 
> > no it's not, your injector is detected.
> > I've been using osiris with no modification and Injecting with process hacker, without vac bypass and no bans yet.
> 
> How do you inject using process hacker? I thought they removed that.

put the dll in windows folder

**Comment by linuxer9** [comment]
> 
> 
> > no it's not, your injector is detected.
> > I've been using osiris with no modification and Injecting with process hacker, without vac bypass and no bans yet.
> 
> hey, what about your trust factor? Cuz mine went red after 2 games, without reports

tbh, I don't know, I don't care, I'm only testing some code in osiris in windows on a non prime account, and I stopped using windows for cheating on prime...
I've been cheating under linux for more than a month now, VAC on linux is very weak and It's very easy to get under the radar of vac flagging or detection on linux.
while process hacker is probably whitelisted by vac, VAC already hooks many funtions of system that is responsible for injection or dll execution..

so if you care about your trust factor or getting banned, you should do more research than that. don't use public injectors, or vac bypassing and definetly don't use vanilla osiris (osiris with no modifications).

**Comment by cheateronly123** [comment]
> > > no it's not, your injector is detected.
> > > I've been using osiris with no modification and Injecting with process hacker, without vac bypass and no bans yet.
> > 
> > 
> > hey, what about your trust factor? Cuz mine went red after 2 games, without reports
> 
> tbh, I don't know, I don't care, I'm only testing some code in osiris in windows on a non prime account, and I stopped using windows for cheating on prime...
> I've been cheating under linux for more than a month now, VAC on linux is very weak and It's very easy to get under the radar of vac flagging or detection on linux.
> while process hacker is probably whitelisted by vac, VAC already hooks many funtions of system that is responsible for injection or dll execution..
> 
> so if you care about your trust factor or getting banned, you should do more research than that. don't use public injectors, or vac bypassing and definetly don't use vanilla osiris (osiris with no modifications).

Does using VAC BYPASS make the Confidence Factor low?

**Comment by 0zl** [comment]
> > > > > > no it's not, your injector is detected.
> > > > > > I've been using osiris with no modification and Injecting with process hacker, without vac bypass and no bans yet.
> > > > > 
> > > > > 
> > > > > hey, what about your trust factor? Cuz mine went red after 2 games, without reports
> > > > 
> > > > 
> > > > tbh, I don't know, I don't care, I'm only testing some code in osiris in windows on a non prime account, and I stopped using windows for cheating on prime...
> > > > I've been cheating under linux for more than a month now, VAC on linux is very weak and It's very easy to get under the radar of vac flagging or detection on linux.
> > > > while process hacker is probably whitelisted by vac, VAC already hooks many funtions of system that is responsible for injection or dll execution..
> > > > so if you care about your trust factor or getting banned, you should do more research than that. don't use public injectors, or vac bypassing and definetly don't use vanilla osiris (osiris with no modifications).
> > > 
> > > 
> > > Does using VAC BYPASS make the Confidence Factor low?
> > 
> > 
> > Yes, using vac bypass will make your trust factor red.
> > In fact, Shtreeba & any injector also lower your trust factor, mostly affected to non-prime or new account.
> 
> What would be the solution then?

Improve your gameplay first obv. Don't act like a fool using aimbot and aiming through walls, also frequent bhopping is a dead giveaway.

At least, modify your Osiris source and any open-source injector to have unique sig.
Just research more, there's more tips lying around in Osiris issues post.

Also try using linux.
https://www.unknowncheats.me/forum/counterstrike-global-offensive/257620-vac-linux-external-cheat.html

**Comment by badrshs** [comment]
> > no it's not, your injector is detected.
> > I've been using osiris with no modification and Injecting with process hacker, without vac bypass and no bans yet.
> 
> hey, what about your trust factor? Cuz mine went red after 2 games, without reports

How do you check your trust factory anyway? how did you know it went to red after two days?
