### ISSUE TITLE
Check if players are desyncing

### ISSUE THREAD

**Issue by cristyanul** [danielkrupinski/Osiris#3224]
It would be a nice feature to be able to see if a player is desyncing.

**Comment by ReShout876** [comment]
cool, that would be actually useful.

**Comment by linuxer9** [comment]
that's called a resolver.

**Comment by HowToMakeFaceitAB** [comment]
> that's called a resolver.

umm no? its not called a resolver lol
a resolver is an entirely different thing

**Comment by HowToMakeFaceitAB** [comment]
> that's called a resolver.

usually desyncing checking comes with a resolver in order to avoid the intial miss to determine whether a player is desyncing or not

**Comment by Liam5750** [comment]
> > that's called a resolver.
> 
> 
> 
> usually desyncing checking comes with a resolver in order to avoid the intial miss to determine whether a player is desyncing or not
> 
> thus resulting in a faster "resolve"

Get resolved faster nn
