### ISSUE TITLE
Nothing happens when i inject using csghost

### ISSUE THREAD

**Issue by hitman2933** [danielkrupinski/Osiris#3226]
I followed the instructions on github and I try to inject to dll and it says its successful but nothing happens. I press insert and still nothing

**Comment by 2933968621** [comment]
If you inject in some arena game, it may not work

**Comment by hitman2933** [comment]
> If you inject in some arena game, it may not work

No, I just start up the game and I'm at the main menu, I hit inject with the dll i built in visual studio. Im using csghost

**Comment by Shuvi-Moro** [comment]
https://github.com/danielkrupinski/Osiris/discussions/3221

**Comment by hitman2933** [comment]
> #3221

What is this? :D

**Comment by 2933968621** [comment]
> > If you inject in some arena game, it may not work
> 
> No, I just start up the game and I'm at the main menu, I hit inject with the dll i built in visual studio. Im using csghost

try restart ur computer
if this problem still occurs, pls check u using "Release" build project
not wrong with osiris.
