### ISSUE TITLE
Thirdperson bug with antiaim (i think)

### ISSUE THREAD

**Issue by effex1337** [danielkrupinski/Osiris#323]
I added some anti aims to osiris but the problem i'm getting is the anti aim isn't visible in thirdperson. bot_mimic 1 works

**Comment by effex1337** [comment]
and when i queue up with friends it works as well :)

**Comment by danielkrupinski** [comment]
You probably need to draw antiaim position yourself.

**Comment by synvy** [comment]
Prediction set local view angles to your real. Sorry I'm on my phone otherwise I would've posted code

**Comment by NexSqaud** [comment]
```c++
interfaces.engine->setViewAngles(realAngles);
```

**Comment by effex1337** [comment]
Its not defined tho
i remember adding 
Vector realangles;
in Interfaces.h but couldn't complete it

**Comment by NexSqaud** [comment]
You make AA in Interface.h?

**Comment by effex1337** [comment]
no i meant someone was helping me with third person but he had to go so i never finished he was trying to change the thirdperson. and as for anti aim i have aa.cpp and aa.h separately.

**Comment by effex1337** [comment]
my aa is something like

> if (GetKeyState(config.hvh.manualleft))
> 		{
> 			config.hvh.manualaastate = 1;
> 		}
> 		else if (GetKeyState(config.hvh.manualright))
> 		{
> 			config.hvh.manualaastate = 2;
> 		}
> 		else if (GetKeyState(config.hvh.manualback))
> 		{
> 			config.hvh.manualaastate = 3;
> 		}
> 		if (config.hvh.manualaastate != 0)
> 		{
> 			switch (config.hvh.manualaastate)
> 			{
> 			case 1: //left
> 				cmd->viewangles.y -= 90.f;
> 				break;
> 
> 			case 2: //right
> 				cmd->viewangles.y += 90.f;
> 				break;
> 
> 			case 3:
> 				cmd->viewangles.y += 180.f;
> 				break;
> 			}
> 			return;
> 		}

**Comment by effex1337** [comment]
@NexSqaud i think i get what u meant now but how tdo you define real angles?

**Comment by effex1337** [comment]
i tried making a global vector
in visuals.cpp
`    if (config.visuals.thirdperson)
		if (memory.input->isCameraInThirdPerson = (!config.visuals.thirdpersonKey || isInThirdperson)
			&& interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer())->isAlive()) {
			memory.input->cameraOffset.z = static_cast<float>(config.visuals.thirdpersonDistance);
			interfaces.engine->setViewAngles(realangle);
		}`
in aa.cpp
`realangle = cmd->viewangles;`
but it just made me look at a certain direction

**Comment by NexSqaud** [comment]
```c++
float maxDesync = getMaxDesync();
if(config.hvh.yaw == 1){
    if(sendPacket)
        cmd->viewAngles += maxDesync / 2;
    else cmd->viewAngles -= maxDesync / 2;
}
```
Simple balance desync(anti aim)

**Comment by effex1337** [comment]
well i got this
`if (sendPacket) {
		cmd->viewangles.y = cmd->viewangles.y;
	}
	else {
		flip = !flip;
		cmd->viewangles.y += (flip ? 58 : -58);
	}`
for my desync
the problem is with thirdperson angles and movement as well

**Comment by NexSqaud** [comment]
```c++
class AntiAim{
static Vector realAngles;
static Vector fakeAngles;
/** calc real and fake angles **/
    if(sendPacket)
        cmd->viewangles.y = fakeAngles.y;
    else
        cmd->viewangles.y = realAngles.y;
```
```c++
void Visuals::thirdperson() noexcept
{
    static bool isInThirdperson{ true };
    static float lastTime{ 0.0f };

    if (GetAsyncKeyState(config.visuals.thirdpersonKey) && memory.globalVars->realtime - lastTime > 0.5f) {
        isInThirdperson = !isInThirdperson;
        lastTime = memory.globalVars->realtime;
    }

    if (config.visuals.thirdperson)
        if (memory.input->isCameraInThirdPerson = (!config.visuals.thirdpersonKey || isInThirdperson)
            && interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer())->isAlive()){
                if(config.hvh.enable)
                    interfaces.engine->setViewAngles(AntiAim::realAngles);    
            memory.input->cameraOffset.z = static_cast<float>(config.visuals.thirdpersonDistance);
        }
}
```
Or you needs to make customBoneToWorld matrix for chams.

**Comment by effex1337** [comment]
not really what i wanted but figured it out myself.

**Comment by Ezb2661** [comment]
> not really what i wanted but figured it out myself.

How did you do it? I am having the same issue right now
