### ISSUE TITLE
Osiris crashing game

### ISSUE THREAD

**Issue by MasterChief220** [danielkrupinski/Osiris#3232]
The game works find but sometime after injection the game starts to crash and doesn't work. I'm using csghost 3.1

**Comment by sarahdumby** [comment]
Have you tried using a different injector? Try process hacker 2.

**Comment by MasterChief220** [comment]
> Have you tried using a different injector? Try process hacker 2.

isn't process hacker 2 detected? and how do i inject using that?

**Comment by xxdeeznutz420xx** [comment]
Download CSGhost v4.2.1 it's not detected.

**Comment by sarahdumby** [comment]
> > Have you tried using a different injector? Try process hacker 2.
> 
> 
> 
> isn't process hacker 2 detected? and how do i inject using that?
> 
> 
> 
> 

Not detected for me, run it as admin, then right click on cs, go to misc, inject dll, then inject osiris, you may have to put the dll in the windows folder, I'm not 100% sure if you need to or not though.

**Comment by HowToMakeFaceitAB** [comment]
> > > Have you tried using a different injector? Try process hacker 2.
> > 
> > 
> > isn't process hacker 2 detected? and how do i inject using that?
> 
> Not detected for me, run it as admin, then right click on cs, go to misc, inject dll, then inject osiris, you may have to put the dll in the windows folder, I'm not 100% sure if you need to or not though.

Its obligatory to put a dll in the windows folder to inject using LoadLibrary instead of manual map.

I would recommend using vac bypass loader(https://github.com/danielkrupinski/VAC-Bypass-Loader) in order to prevent vac bans.
