### ISSUE TITLE
How do I add more features to my osiris build?

### ISSUE THREAD

**Issue by snoopexe** [danielkrupinski/Osiris#3233]
I'm not sure how to add the draw aimbot fov and the viewmodel xyz to my build can someone explain

**Comment by Liam5750** [comment]
Go and check pull request and find one that is at max 2 months old. Then go add the code. Some code will be altered so do try to be careful or you might break it.

**Comment by Liam5750** [comment]
ato explain find the pu and pull requests, click on them. Then press code changed. now find the file and the code line number. Repleace the red witht the green and add the green
