### ISSUE TITLE
How to add Draw FOV and better AA

### ISSUE THREAD

**Issue by ic3dm4ng0** [danielkrupinski/Osiris#3236]
Title says it all. (fine with the code being stolen from other cheats).

**Comment by Liam5750** [comment]
U want better AA eh? stop tryna use a f*cking legit cheat! fixed!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Liam5750** [comment]
also Draw FOV #3127

**Comment by ic3dm4ng0** [comment]
> U want better AA eh? stop tryna use a f*cking legit cheat! fixed!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

ah yes, because legit aa that works in a legit cheat is so outrageous and has never been done before

**Comment by Liam5750** [comment]
Well I didn't know what you meant, sorry. Just kinda tired of five year olds wanting him to code ragebot better than neverlose. Its all good xD

**Comment by Liam5750** [comment]
I can maybe try to code it and add pull request

**Comment by cristyanul** [comment]
i have a fork. The aa is very good for legit cheating (can't shoot head)

**Comment by Liam5750** [comment]
Sure send or smth idk lol
