### ISSUE TITLE
Difficulties building freetype files

### ISSUE THREAD

**Issue by wolfdugulas** [danielkrupinski/Osiris#3237]
I'm getting a lot of errors when building the solution.
Has anyone encountered these errors yet?
![p](https://user-images.githubusercontent.com/90682641/133224439-415759f0-4c10-4bb1-aebf-936340ff87e4.png)

**Comment by ericksabino** [comment]
Update your Visual Studio Code

**Comment by halallovas** [comment]
> Update your Visual Studio Code

What does visual studio code have to do with vs19?

**Comment by ericksabino** [comment]
Sorry man. Update your IDE (VS19)

**Comment by halallovas** [comment]
It is up to date tho.

**Comment by mdilai** [comment]
X86, not x64
