### ISSUE TITLE
Danger Zone Crash

### ISSUE THREAD

**Issue by TheBorn** [danielkrupinski/Osiris#324]
When playing Danger Zone specifically, the game closes itself.

I tried everything from changing Visual Studio version to different injectors.

My friends have the same issue.

My guess is this is a deliberate game closing due to some form of anti cheat but It's just a theory as the game gives no error message and just closes itself.

**Comment by danielkrupinski** [comment]
Compile cheat in debug mode, attach debugger, inject using LoadLibrary. When it crashes make screenshot of call stack and post it here.

**Comment by TheBorn** [comment]
Hey, I got the call stack picture you asked for right here.

https://pasteboard.co/In1nbWm.png Shows the Exception Thrown message.
https://pasteboard.co/In1ntS3.png Shows the Call Stack.

I hope this info will help you on fixing this! :D

**Comment by danielkrupinski** [comment]
Try replacing https://github.com/danielkrupinski/Osiris/blob/5940f149d047c54162a20fc57fca0ff7904a3414/Osiris/Hooks.cpp#L322
with
```cpp
if (auto entity = interfaces.entityList->getEntity(soundInfo.entityIndex); entity && entity->isPlayer()) {
```

**Comment by NexSqaud** [comment]
https://imgur.com/a/vuA39mK

**Comment by TheBorn** [comment]
Oh I did it and I havn't experienced crashes when I tried it. So it must work better now! sorry I forgot about this thread XD
