### ISSUE TITLE
unknown crash

### ISSUE THREAD

**Issue by KevinRommens** [danielkrupinski/Osiris#3243]
I crashed 2 times in the same match before i RQ'd. one time a teammate threw a nade in my face and the other time i was looking down monster on overpass. I have no clue what causes it but if someone knows how to fix it then please respond.

**Comment by Shuvi-Moro** [comment]
Honestly in the shower I don't fuck!!!
But fuck it and either don't play with Osiris or get over it.
And please shut this down.

**Comment by Liam5750** [comment]
Sometimes csgo just hates when you inject. 99% chance you'll never have that again

**Comment by KevinRommens** [comment]
> Sometimes csgo just hates when you inject. 99% chance you'll never have that again

The thing is. This doesn't happen with any other cheat for me, so it's something that Osiris is doing wrong.
