### ISSUE TITLE
when you apply stickers they are mirrored 

### ISSUE THREAD

**Issue by ocewot** [danielkrupinski/Osiris#3244]
when you apply stickers they are mirrored (or backwards) for some reason as in the text ONLY IN INVENTORY
![d943bcccb5b7720744df33887dd11e50](https://user-images.githubusercontent.com/63646551/133981732-61952c8f-2ac1-4c5f-96c8-cd0f616df10f.png)

**Comment by KurastikO** [comment]
stop switching cl_righthand lol

**Comment by KurastikO** [comment]
restart your client and it'll be fixed, just stop switching between being left-handed and right-handed
