### ISSUE TITLE
OPERATION RIPTIDE - CSGO Updated  - Crash

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#3247]
CSGO has been **updated** for the new **OPERATION RIPTIDE** and after injecting the cheat into a game, the game closes

**Comment by afeer123** [comment]
me too

**Comment by KurastikO** [comment]
Everybody' crashing, don't worry about it.

**Comment by AuG-24** [comment]
fix?

**Comment by Shuvi-Moro** [comment]
![image](https://user-images.githubusercontent.com/63977167/134329520-39d71bb4-4716-4503-b212-34442dab1e06.png)

**Comment by afeer123** [comment]
Enter game crash

**Comment by wemanzoz** [comment]
@Shuvi-Moro gimme

**Comment by Shuvi-Moro** [comment]
+

**Comment by TauCSGO** [comment]
**Updated!**
Thank you @danielkrupinski

**Comment by invakid404** [comment]
Still appears to crash for me, Ubuntu Focal, just built from master.

**Comment by TauCSGO** [comment]
> Still appears to crash for me, Ubuntu Focal, just built from master.

Working fine here in windows
Linux issue here: https://github.com/danielkrupinski/Osiris/issues/3246

**Comment by mx667** [comment]
same for me on windows crashing when enter in the game

**Comment by TauCSGO** [comment]
> same for me on windows crashing when enter in the game

In windows it works OK
If you crash with an error message for .WAV files in Workshop maps, this is because the developers of the maps must update them. It is not a problem of the cheat

**Comment by mx667** [comment]
i don't understand but when i start a game and i come in the warmup that
crash in everymode

**Comment by mx667** [comment]
i inject and it inject but when i launch the game that close the game with
no error messages


Le mer. 22 sept. 2021 à 18:23, Delattre Max ***@***.***> a
écrit :

> i don't understand but when i start a game and i come in the warmup that
> crash in everymode
>
>

**Comment by mx667** [comment]
i just try to launch a deathmatch and that do the same in wingman in comp
and casu

Le mer. 22 sept. 2021 à 18:25, Delattre Max ***@***.***> a
écrit :

> i inject and it inject but when i launch the game that close the game with
> no error messages
>
>
> Le mer. 22 sept. 2021 à 18:23, Delattre Max ***@***.***>
> a écrit :
>
>> i don't understand but when i start a game and i come in the warmup that
>> crash in everymode
>>
>>
