### ISSUE TITLE
Still crashing as of new update

### ISSUE THREAD

**Issue by Jay6icK** [danielkrupinski/Osiris#3248]
I tested the new update for this Osiris hack and it still crashes upon "Retrieving game data" upon queuing for a match.
I am using 
https://github.com/danielkrupinski/Osiris
https://github.com/danielkrupinski/VAC-Bypass-Loader
https://dottabz.boards.net/thread/41/randoinjector-vac-bypass

**Comment by wemanzoz** [comment]
it doesnt crash for me but some features are just broken, eg skinchanger and triggerbot

**Comment by impoggin** [comment]
I know you said "upon queueing for a match" but are you by any chance trying to load into a bot game/workshop map? There is a known bug where many people (including non cheaters) are crashing while loading into offline games
