### ISSUE TITLE
How to compile cheat in .exe

### ISSUE THREAD

**Issue by Mufinekkk** [danielkrupinski/Osiris#325]
Hello Daniel, I saw that cheat in .exe format and injector wasn`t needed.

How to do that?

**Comment by NexSqaud** [comment]
It's impossible. Search external cheats

**Comment by HECCYE** [comment]
Well there are two types of exe cheats
1. Loader type:
Using loader to download cheat from server(i think xd) like Aimware
2. External type:
Search on google, i dont care about those

**Comment by danielkrupinski** [comment]
You can embed .dll file in .exe, see https://github.com/danielkrupinski/MemJect
