### ISSUE TITLE
Skin changer does not work

### ISSUE THREAD

**Issue by afeer123** [danielkrupinski/Osiris#3250]
Inventory can be added But I can't use it in the game

**Comment by AuG-24** [comment]
aimbot doesnt work either

**Comment by wemanzoz** [comment]
> aimbot doesnt work either

the thing is everything broked after new update, let daniel do the fixes

**Comment by AuG-24** [comment]
yup.. will download new build after 72 hours

**Comment by jackKiZhu** [comment]
这语法。。一看就是国人QAQ

**Comment by danielkrupinski** [comment]
Working now.
