### ISSUE TITLE
i hope u r aware abt the scam -  https://osiris-cheats.net/

### ISSUE THREAD

**Issue by OminousReaper** [danielkrupinski/Osiris#3255]
i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/i hope u r aware abt the scam -  https://osiris-cheats.net/

**Comment by TauCSGO** [comment]
Osiris is licensed by MIT, so if someone wishes, they can modify and resell it.
https://opensource.org/licenses/mit-license.php

🤷‍♂️

**Comment by Jay6icK** [comment]
What scam it's free lmao

**Comment by Jay6icK** [comment]
Is there adware, malware, trojans, anything of actual concern lmao?

**Comment by mkot2** [comment]
> 
> 
> What scam it's free lmao

wdym
![firefox_p1TvO3SFBj](https://user-images.githubusercontent.com/31155321/134609086-2c229c79-56f0-4434-bcd5-0c85d3ddf43a.png)
