### ISSUE TITLE
How do I give my guns stat track?

### ISSUE THREAD

**Issue by CalvinBens** [danielkrupinski/Osiris#3258]

**Comment by wemanzoz** [comment]
go to ur config file, then add StatRak: 1; or somth

**Comment by Jay6icK** [comment]
made no sense

**Comment by floydGG** [comment]
![image](https://user-images.githubusercontent.com/53382214/134523504-bb4894d7-1b2f-40f2-a26e-e18f5a4106e9.png)

Open your config, and then add like this.
