### ISSUE TITLE
Skins are not working?

### ISSUE THREAD

**Issue by yesntsire** [danielkrupinski/Osiris#3259]
I know that after the update it may take some time to update it but as I saw a few people claiming that it works for them, I thought the issues were fixed. I can inject the new file (updated 22nd September at around 1pm CEST) and launch the game without any issues. While I can load my config and add Skins to my inventory, these skins won't show In-Game, but instead just the default knife for example. 

I believe the cheats work, but I didn't try that as I am primarily using it for the Skin Changer.

Did I do anything wrong or were the other people in the 'issues' section just referring to the Cheat and the Skin Changer still takes some time?

**Comment by shybruh** [comment]
Works for me
try forceupdating
