### ISSUE TITLE
ESP Projectile not working sometimes

### ISSUE THREAD

**Issue by hungdz1234** [danielkrupinski/Osiris#3260]
After the latest game update, ESP for projectile is unstable. Sometimes it works, sometimes it doesn't. 

![image](https://user-images.githubusercontent.com/54879097/134472392-f2e4bf68-def2-40db-b7a5-7b3366960e6e.png)

![image](https://user-images.githubusercontent.com/54879097/134472270-a154cdd9-ccd0-4ae4-b158-65d51eac245c.png)

**Comment by wemanzoz** [comment]
i think projectile signature changed, @danielkrupinski pls fix

**Comment by R3nzTheCodeGOD** [comment]
@wemanzoz If there was a problem with the signature, it would not work at all and would give a pattern error.

**Let the experts reverse engineer the game and be patient instead of coming up with the same issues over and over again**

**Comment by wemanzoz** [comment]
> @wemanzoz If there was a problem with the signature, it would not work at all and would give a pattern error.
> 
> **Let the experts reverse engineer the game and be patient instead of coming up with the same issues over and over again**

good point m8
