### ISSUE TITLE
Crashes after a few seconds in a map

### ISSUE THREAD

**Issue by yesntsire** [danielkrupinski/Osiris#3261]
I didn't fully test this, but I tried loading an offline Game vs BOTs with the Skin Changer, but after a few seconds in the map, the game crashes. I stayed for the same amount of time in the inventory/menu area and it didn't crash. I did download the latest update and tried it several times.

**Comment by sarahdumby** [comment]
Works perfectly for me, try using process hacker as an injector and vac bypass if you don't already
