### ISSUE TITLE
Bullet issue

### ISSUE THREAD

**Issue by 2933968621** [danielkrupinski/Osiris#3268]
Why if my ducking or in air, fire bullet position not is i'm aiming (just client-side)
but if my force update, this issue will disappear
![csgo](https://user-images.githubusercontent.com/53483352/134633151-623ed8be-3fcf-4023-b0bc-465d73708c68.gif)

**Comment by wemanzoz** [comment]
?

**Comment by 2933968621** [comment]
> ?

?
