### ISSUE TITLE
Recoil issue

### ISSUE THREAD

**Issue by ItsJay22** [danielkrupinski/Osiris#3271]
So since i cant record a quick video i have to describe the problem.
The recoil issue happens when shooting with a gun (at least for me) when shooting without a target (a player) it randomly shoots the ground or under the crosshair which is weird. idk how to make it more clear but the recoil just behaves how it shouldnt. 
Ive noticed this while playing TDM (Team vs Team mode).

**Comment by emreires** [comment]
experiencing the same problem, any idea / solution?

**Comment by emreires** [comment]
@SluXzZ @danielkrupinski

**Comment by ItsJay22** [comment]
Hey any solutions ?
