### ISSUE TITLE
Failed to find VClient018 interface!

### ISSUE THREAD

**Issue by Boomer118** [danielkrupinski/Osiris#3272]
I downloaded latest code(5 minutes before writing this), built it with a fresh Visual Studio Install. Build was fine but when I injected it in CSGO, "Failed to find VClient018 interface!" popup came. Clicking OK shuts down the game and leaving it as it is does not inject cheat. Someone else facing same issue?

**Comment by R3nzTheCodeGOD** [comment]
https://github.com/danielkrupinski/Osiris/blob/572219582f9fab59c205e0ee5b42385d70b59b43/Osiris/SDK/Platform.h#L37

If you are using windows, try changing the reference path to `panoramauiclient`. If you are using Linux, you can check the new name. I don't know.

**Comment by Boomer118** [comment]
@R3nzTheCodeGOD 
![Screenshot (68)](https://user-images.githubusercontent.com/91342033/134725558-9dab1d32-cf95-4557-82ac-5ef59a9caab5.png)
I tried this as you said but still same problem. Am I doing it right? panoramauiclient.dll exists in csgo files but I have no idea about .so extensions

**Comment by Boomer118** [comment]
Tried changing it still same problem

**Comment by Boomer118** [comment]
I changed it to panoramauiclient, confirmed with csgo files that there is indeed panoramauiclient.dll which is probably replaced by older one by Valve. But I guess, Valve has made some more changes into this dll which is not returning to regular osiris calls probably. Again I have no idea which files of osiris are actually using CLIENT_DLL

**Comment by R3nzTheCodeGOD** [comment]
I said it might have changed, hypothetically. @Boomer118 
**But the client.dll is fine**

![image](https://user-images.githubusercontent.com/58574988/134730361-67d4e444-a768-4551-9596-2fa18d749dc5.png)

**Comment by Boomer118** [comment]
I dont see any client.dll in csgo bin files. Which is why I said that probably valve replaced client.dll with panoramauiclient.dll

**Comment by Boomer118** [comment]
@danielkrupinski Any solution on this? It seems like this issue is only coming up for me.

**Comment by baobao2167** [comment]
no i also have this issue

**Comment by Boomer118** [comment]
I started using exloader, their dll is working fine but does not get injected sometimes. I wont recommend but to you as daniels vac bypasser is way safer option.

**Comment by qualk** [comment]
I also have the issue, I use CS-Ghost

**Comment by qualk** [comment]
> https://github.com/danielkrupinski/Osiris/blob/572219582f9fab59c205e0ee5b42385d70b59b43/Osiris/SDK/Platform.h#L37
> 
> If you are using windows, try changing the reference path to `panoramauiclient`. If you are using Linux, you can check the new name. I don't know.

Thank you, this worked!
