### ISSUE TITLE
Error in game (Assertion failed)

### ISSUE THREAD

**Issue by ikusiss** [danielkrupinski/Osiris#3273]
Im not that good on this things of coding and that, but idk why Im getting this error message while playing everytime and just freezes completely the game, someone can help?
![Desktop Screenshot 2021 09 23 - 00 39 57 83](https://user-images.githubusercontent.com/91351345/134746734-b3ec6dba-2755-4f5d-9f74-746057fe8b96.png)

![Desktop Screenshot 2021 09 25 - 00 40 20 40](https://user-images.githubusercontent.com/91351345/134746763-b796a637-55e2-4e03-941a-b29acf7767c9.png)

**Comment by wemanzoz** [comment]
compile in release

**Comment by Desperons** [comment]
I had the same error, but I modified that part of the code and now it's working wonders after I compiled it.
This is how I changed it:
![snip](https://user-images.githubusercontent.com/49241773/134768443-34f73000-eedd-475e-a333-b83b432f710e.png)
There's aren't any new errors and every functionality of Osiris is working as it should (for me at least). Try this change and then test it, let me now if you solved it!

**Comment by ikusiss** [comment]
> 
> 
> I had the same error, but I modified that part of the code and now it's working wonders after I compiled it.
> This is how I changed it:
> ![snip](https://user-images.githubusercontent.com/49241773/134768443-34f73000-eedd-475e-a333-b83b432f710e.png)
> There's aren't any new errors and every functionality of Osiris is working as it should (for me at least). Try this change and then test it, let me now if you solved it!

Well, I played now a couple of hours and seems to be okay! So I think it fixed the problem for me also, thanks m8!! ;)
