### ISSUE TITLE
Case opening // drop possibility

### ISSUE THREAD

**Issue by Callum151800** [danielkrupinski/Osiris#3274]
Can you please add or change the inventory config so that drops of every case have the same possibility as a real case opening?
Now it seems that chances for red and purple drops are much higher than normal cases. In addition, the floats of weapons are lower than usual, too.
There are some case opening statistics that you can refer to. 
(I mean, if you want any skin, you can just add it to your inventory. Case opening should be nearly the same as a real case opening, isn't it? XD )
(PS: I'm still learning C#, and not able to handle this problem yet... If anyone can help me, that will be great! )

**Comment by R3nzTheCodeGOD** [comment]
https://github.com/B3akers/csgo-fake-opening

The base of Osiris is very strong, you can easily do what you want to use this source.

**Comment by Callum151800** [comment]
Thank. I will try  <3

**Comment by danielkrupinski** [comment]
The drop chances have been adjusted.
