### ISSUE TITLE
ESP Projectile and Aimbot through walls not working

### ISSUE THREAD

**Issue by hungdz1234** [danielkrupinski/Osiris#3278]
Like the title:
- ESP Projectile is not working
- Aimbot through walls (which means uncheck the "Visible only" function") does not work

**Comment by danielkrupinski** [comment]
Aimbot has been fixed (109724f460dd811d0481864b4698b3fc71bb2885)

**Comment by hungdz1234** [comment]
> Aimbot has been fixed ([109724f](https://github.com/danielkrupinski/Osiris/commit/109724f460dd811d0481864b4698b3fc71bb2885))

Thank you. Hope u can fix projectile soon

**Comment by danielkrupinski** [comment]
Projectile ESP has been fixed too (ed6552494201dd8319c5bd7ffade1eab09937964).
