### ISSUE TITLE
Which commit(s) should I copy and paste for the standalone skin changer to work?

### ISSUE THREAD

**Issue by CalvinBens** [danielkrupinski/Osiris#3281]

**Comment by acey1337** [comment]
https://github.com/danielkrupinski/OsirisInventory
You can use this version of Osiris, it only has the skinchanger. Just compile it in release x86 like normal and you're done

**Comment by CalvinBens** [comment]
> https://github.com/danielkrupinski/OsirisInventory
> You can use this version of Osiris, it only has the skinchanger. Just compile it in release x86 like normal and you're done

Not working atm
