### ISSUE TITLE
[HELP] How do I change config path?

### ISSUE THREAD

**Issue by xXsnip3rXx** [danielkrupinski/Osiris#3286]
Title, don't know anything about coding but I want to change where configs are saved :p

**Comment by Liam5750** [comment]
Ctrl+h then type Osiris then make sure the drop down is on entire solution and start searching. Find one thats like Osiris in a box thingy or smth and change it from Osiris to "insert your new name of it here"

**Comment by xXsnip3rXx** [comment]
oh I thought that only changed the folder name not the path xDD thanks man
