### ISSUE TITLE
how could I make it manualmap.

### ISSUE THREAD

**Issue by Liam5750** [danielkrupinski/Osiris#3288]
I want to make it manualmap so I can make loader(testing the loader) and I was  wondering how I could do this.

**Comment by ic3dm4ng0** [comment]
manual map is a form of injection.
you're the same guy calling me an idiot asking for legit aa in a legit cheat.

**Comment by Liam5750** [comment]
?xd I know what manualmapping is and how to code. Get 1d xD. I was just tryna make the stupid dll manualmap. I had to rewrite some hooking methods and such

**Comment by mkot2** [comment]
> 
> 
> ?xd I know what manualmapping is and how to code. Get 1d xD. I was just tryna make the stupid dll manualmap. I had to rewrite some hooking methods and such

idk what shit you using bro but it works with manualmap without changes for me

**Comment by HowToMakeFaceitAB** [comment]
> ?xd I know what manualmapping is and how to code. Get 1d xD. I was just tryna make the stupid dll manualmap. I had to rewrite some hooking methods and such

hey, just make a loadlibrary injector that injects a dll from the windows file on the drive where windows is installed.
You won't be facing issues with injection if you do this.

**Comment by HowToMakeFaceitAB** [comment]
> ?xd I know what manualmapping is and how to code. Get 1d xD. I was just tryna make the stupid dll manualmap. I had to rewrite some hooking methods and such

and btw, stop asking questions that google can answer.

**Comment by mkot2** [comment]
> 
> 
> > ?xd I know what manualmapping is and how to code. Get 1d xD. I was just tryna make the stupid dll manualmap. I had to rewrite some hooking methods and such
> 
> hey, just make a loadlibrary injector that injects a dll from the windows file on the drive where windows is installed. You won't be facing issues with injection if you do this.

loadlibrary is easily detectable, manualmap is not

**Comment by ic3dm4ng0** [comment]
> ?xd I know what manualmapping is and how to code. Get 1d xD. I was just tryna make the stupid dll manualmap. I had to rewrite some hooking methods and such

xd You don't need to change the the code to use manual map. Get 1d xD.
