### ISSUE TITLE
How to use it on linux { New User _ dont know about coding }

### ISSUE THREAD

**Issue by MrOpxDRS** [danielkrupinski/Osiris#3289]
Please say it step wise step or make a video tutorial it will be a big help @danielkrupinski . I actually tried this also but i m getting errors hope you help me out 
![Screenshot from 2021-09-27 17-07-26](https://user-images.githubusercontent.com/85931150/134899120-5910ccf0-775c-499f-8109-857f1cbd2704.png)

**Comment by Callum151800** [comment]
I found this video helpful when I tried to use this on windows. I think everything will be similar on Linux. Check it out: (link below)

https://www.youtube.com/watch?v=-d4LuwSn1wk

**Comment by danielkrupinski** [comment]
Show the contents of `/home/rahul/Osiris` directory.

**Comment by MrOpxDRS** [comment]
@danielkrupinski  Thanks a lot u replied but actually i completed it. My release folder was not inside osiris folder sorry for your time
