### ISSUE TITLE
Any chance add no spread? + auto aim bug

### ISSUE THREAD

**Issue by NameNotTakenYAY** [danielkrupinski/Osiris#329]
Add a no bloom please. And silient aim dosent work with silient im.

**Comment by effex1337** [comment]
No bloom? What does it do?
`silient aim dosent work with silient im` what do you mean? 
no spread is not a feature spread/inaccuracy is a random seed generated by the server which cannot be predicted correctly afaik

**Comment by Shaxzy** [comment]
Nospread only works for community servers which support this (aka nospread hvh servers). Wouldn’t work for valve servers, and would be useless for these hvh servers because you would need a top tier cheat along with this feature.
