### ISSUE TITLE
[REQUEST] make it so we dont need to save config to keep statrak number

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#3290]

**Comment by danielkrupinski** [comment]
Should it be saved to lately loaded config?

**Comment by skirtsandflirts** [comment]
This could be done (not by saving stattrack every kill, but) by saving it on match end.

**Comment by PaulAndreiRO** [comment]
> This could be done (not by saving stattrack every kill, but) by saving it on match end.

 how?

**Comment by lattemango** [comment]
> > This could be done (not by saving stattrack every kill, but) by saving it on match end.
> 
> how?

I cannot fathom why you replied to a 2 year old issue.

**Comment by PaulAndreiRO** [comment]
> 
because it would be great to have this feature implemented
