### ISSUE TITLE
SV_PURE

### ISSUE THREAD

**Issue by x55ch** [danielkrupinski/Osiris#3293]
SV_PURE BYPASS NOW plese

**Comment by cincovp** [comment]
i did
![funny jotaro](https://user-images.githubusercontent.com/53921095/135016877-b83ab866-3a53-4097-b7ee-608c6589c321.png)

**Comment by mkot2** [comment]
> 
> 
> i did ![funny jotaro](https://user-images.githubusercontent.com/53921095/135016877-b83ab866-3a53-4097-b7ee-608c6589c321.png)

close this then?
