### ISSUE TITLE
Trade Up Contract

### ISSUE THREAD

**Issue by Nep-Timeline** [danielkrupinski/Osiris#3294]
Add trade up contract to InventoryChanger?

**Comment by Liam5750** [comment]
This is extremely hard to do. If you understand coding and game hacking  to even the smallest extent just thunk of how one would go about coding this.

**Comment by skirtsandflirts** [comment]
> 
> 
> This is extremely hard to do. If you understand coding and game hacking to even the smallest extent just thunk of how one would go about coding this.

Thank you for pushing the concept.
