### ISSUE TITLE
[REQUEST] auto commend.

### ISSUE THREAD

**Issue by Ativ3k** [danielkrupinski/Osiris#3296]
The option automatic recommendations forrandom or selected people.
A nice option would also be the option to change accounts because even accounts without prime can give recommendations on servers with "sv_prime_accounts_only 0" so it would be enough to automatically change the account and automatically join the server. Kind of like a report bot that is already present in osiris.
It is possible?

**Comment by Liam5750** [comment]
Yes I will maybe try to make it and make a pull request
