### ISSUE TITLE
Aimbot not working

### ISSUE THREAD

**Issue by santi4003** [danielkrupinski/Osiris#3297]
I tried the hack with bots and it seems aimbot isnt working

**Comment by qualk** [comment]
Same with me, so isn't ESP and stuff.

**Comment by qualk** [comment]
A lot of hacks ain't working for me.

**Comment by Liam5750** [comment]
Just the ritide upsate. Wait for him to fix it

**Comment by wemanzoz** [comment]
its fixed lol, download newest osiris
