### ISSUE TITLE
Osiris crashing after 1 to 2 minutes of use.

### ISSUE THREAD

**Issue by Arctrometa** [danielkrupinski/Osiris#3298]
I only use osiris for the inventory changer, I use CS Ghost 4.2.1 for the injector. After about 1 to 2 minutes of working absolutely flawlessly it suddenly freezes and crashes. (On the latest version of Osiris) Any fix for this?

**Comment by danielkrupinski** [comment]
There will be no fix if you don't provide more details. Does it crash in the game with bots?

**Comment by EzequielDM** [comment]
I've been crashing while playing War Games Retakes every 3-5 minutes.
I don't get any errors nor anything, just a random crash

**Comment by Arctrometa** [comment]
> There will be no fix if you don't provide more details. Does it crash in the game with bots?

After a few more crashes it somehow started working fine, it still has the occasional freeze that lasts about 3 seconds or so but it doesn't crash anymore, and yes the game crashes with bots in it and in a online match as well. The problem is fixed for me now, don't know why it was acting up at the start.
