### ISSUE TITLE
Failed to find VClicent018 interface

### ISSUE THREAD

**Issue by baobao2167** [danielkrupinski/Osiris#3299]
Failed to find VClicent018 interface

**Comment by Liam5750** [comment]
Some people have this error and idk why. How and when does it occur. No one gives details so no one can fix it. Maybe send a screenshot of it braking also.

**Comment by baobao2167** [comment]
> Some people have this error and idk why. How and when does it occur. No one gives details so no one can fix it. Maybe send a screenshot of it braking also.

https://cdn.discordapp.com/attachments/892579918909669457/892617330801135666/unknown.png

**Comment by baobao2167** [comment]
Like once i execute the dll, and cs launches, instead of opening to the main menu it shows and error and crashes

**Comment by Liam5750** [comment]
Have you modified csgo launch options csgo or the Osiris source?

**Comment by baobao2167** [comment]
> Have you modified csgo launch options csgo or the Osiris source?

i tried changing the code abiit but i gave up cuz it was confusing sooo no

**Comment by Liam5750** [comment]
Well idk then if you have csgo launch options disable then and use losdlibrary to inject or csghost wich loadlibrarys

**Comment by crmpe** [comment]
im pretty sure this happens when you inject the dll before csgo loads up. Try loading up csgo first, wait to be on the main menu (in the lobby), then inject osiris.

**Comment by floydGG** [comment]
> im pretty sure this happens when you inject the dll before csgo loads up. Try loading up csgo first, wait to be on the main menu (in the lobby), then inject osiris.

+1
