### ISSUE TITLE
Retakes mode enemy weapons issue

### ISSUE THREAD

**Issue by 2933968621** [danielkrupinski/Osiris#3300]
retakes mode can get enemy weapons, but inventory changer not work
![Issue](https://user-images.githubusercontent.com/53483352/135288732-aeee74d1-1d67-4cc7-84c4-b36580e8a40d.png)

**Comment by Liam5750** [comment]
? Just an error for you. The inventory changer breaks rarely from sometimes. Please don't post if you have inventory changer problems. This is just an issue with you for some reason. There is no way to fix this as far as I know :(

**Comment by 2933968621** [comment]
maybe
