### ISSUE TITLE
[Question] player marks

### ISSUE THREAD

**Issue by qqqZXzz123** [danielkrupinski/Osiris#3301]
Is it possible to put a mark not by using the cursor, but with the help of the cheat at the given coordinates, say on the coordinates of the player?

**Comment by Liam5750** [comment]
Yes it is. It can be added by tracking player coordinates and displaying them through float to int into number. But why would this be helpful?

**Comment by Ativ3k** [comment]
> Yes it is. It can be added by tracking player coordinates and displaying them through float to int into number. But why would this be helpful?

For legit.
Hacker will be last, his friends will get info and win match.
whenever anyone report last guy with 0 kills?

**Comment by Ativ3k** [comment]
> Is it possible to put a mark not by using the cursor, but with the help of the cheat at the given coordinates, say on the coordinates of the player?

Or maybe web host for radar? Live time radar on website for teammates.
