### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by afeer123** [danielkrupinski/Osiris#3304]

**Comment by afeer123** [comment]
![image](https://user-images.githubusercontent.com/86306447/135643649-e698dec9-a757-4932-ae07-e6073f0fd013.png)

**Comment by mkot2** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/86306447/135643649-e698dec9-a757-4932-ae07-e6073f0fd013.png)

compile as release
