### ISSUE TITLE
[Request] Turn away from flash.

### ISSUE THREAD

**Issue by AuG-24** [danielkrupinski/Osiris#3306]
As per my understanding , flash reduction exists in osiris but using it would look super blatant.. and here comes the OW ban.. My idea is to implement a "quick turn away from flash" where based on the trajectory of the flash , our POV turns away from it and then returns to as it was , after the flash pops. This would benefit players trying to play legit.

**Comment by notgoodusename** [comment]
Something like [this](https://www.youtube.com/watch?v=dbkAFW2hdWc&ab_channel=MasterLooserLIVE)

**Comment by 0zl** [comment]
If your aim is wiggly and suddenly flick to avoid flash, it'll still be suspicious

**Comment by sarahdumby** [comment]
Just look away?

**Comment by king1919djdj** [comment]
just activate ESP with [box,snaplines,etc] for flash only and turn away when the it draws the snaplines
that will make your movement look natural (well it is natural) 
or you can link ur mouse movement macro with the esp for flash activation to achieve this but that will destroy ur fps
unless you can afford that
