### ISSUE TITLE
Custom chams black in MM

### ISSUE THREAD

**Issue by notarchs** [danielkrupinski/Osiris#3308]
When I try to add custom chams to Osiris, they work fine while in a private match but when I try to go into mm it either tells me I've got third party files loaded or they appear black and don't work is there any way to fix this?

I can also provide the code I'm using for my custom chams in case there's something wrong I'm doing and I don't realise it.

**Comment by Kawaii33** [comment]
Hey, try to save your confing and then restart your game so you wont load third-party files because when you start a private match, you load third-party files in your cs:go. Hope it work ^^

**Comment by notarchs** [comment]
> Hey, try to save your confing and then restart your game so you wont load third-party files because when you start a private match, you load third-party files in your cs:go. Hope it work ^^

Yeah I tried this but it says it can't find my material when i'm in MM which is weird because i'm literally creating it like within the cheat so idk what's going on lmao
