### ISSUE TITLE
[suggestion] add bhop hitchance?

### ISSUE THREAD

**Issue by 29380482390** [danielkrupinski/Osiris#331]
as in the title - chance for ' hitting ' the hops, something like that - https://imgur.com/a/QyWgie2 - it would look more legit when someone's spectating you. if you need reference you can look at aristois source( i think it has it, not sure tho )

**Comment by cojo1989** [comment]
Useless it should just be legit and silent i think aimware have this what im saying now. Its much better then chance and stuff.

**Comment by l0ccy** [comment]
+++1
