### ISSUE TITLE
velocity indicator

### ISSUE THREAD

**Issue by hupper2** [danielkrupinski/Osiris#3310]

**Comment by skirtsandflirts** [comment]
cmon bruh this is just not neccesary. If you want this, add it yourself.

**Comment by floydGG** [comment]
fuck off, stop opening issue for begging features.

**Comment by skirtsandflirts** [comment]
> 
> 
> > > fuck off, stop opening issue for begging features.
> > 
> > 
> > You have no say here either, hypocrite.
> 
> oh did i hurt ur feelings ? aww

You never said I was wrong about what I said. All I did was tell the person that it's not necessary and that @danielkrupinski most likely wont put that addition into the cheat.
You then come along and be overly aggressive saying "stop opening issue for begging features" and yet you literally did the same (your GitHub profile has enough proof). So that is why you are a hypocrite in this situation.
You didn't at all hurt my feelings, if I had any towards this discussion which I don't. You act like you are superior here and that everything you do is write and that is just outright wrong.

**Comment by skirtsandflirts** [comment]
> 
> 
> > > > > fuck off, stop opening issue for begging features.
> > > > 
> > > > 
> > > > You have no say here either, hypocrite.
> > > 
> > > 
> > > oh did i hurt ur feelings ? aww
> > 
> > 
> > You never said I was wrong about what I said. All I did was tell the person that it's not necessary and that @danielkrupinski most likely wont put that addition into the cheat. You then come along and be overly aggressive saying "stop opening issue for begging features" and yet you literally did the same (your GitHub profile has enough proof). So that is why you are a hypocrite in this situation. You didn't at all hurt my feelings, if I had any towards this discussion which I don't. You act like you are superior here and that everything you do is right and that is just outright wrong.
> 
> um okay i guess? did mama give enuff attention to u sweetheart?

What are you saying, you can't even spell properly. Can you just stop with this?

**Comment by karambitlore** [comment]
auto vel = local->vel();
draw_list->text( velocity);
psudo code

**Comment by Liam5750** [comment]
> > 
> 
> > 
> 
> > > > > > fuck off, stop opening issue for begging features.
> 
> > > > > 
> 
> > > > > 
> 
> > > > > You have no say here either, hypocrite.
> 
> > > > 
> 
> > > > 
> 
> > > > oh did i hurt ur feelings ? aww
> 
> > > 
> 
> > > 
> 
> > > You never said I was wrong about what I said. All I did was tell the person that it's not necessary and that @danielkrupinski most likely wont put that addition into the cheat. You then come along and be overly aggressive saying "stop opening issue for begging features" and yet you literally did the same (your GitHub profile has enough proof). So that is why you are a hypocrite in this situation. You didn't at all hurt my feelings, if I had any towards this discussion which I don't. You act like you are superior here and that everything you do is right and that is just outright wrong.
> 
> > 
> 
> > um okay i guess? did mama give enuff attention to u sweetheart?
> 
> 
> 
> What are you saying, you can't even spell properly. Can you just stop with this?
Everyone stfu. Please. Ur hurting my head.
