### ISSUE TITLE
Errors in Visual studio.

### ISSUE THREAD

**Issue by Kawaii33** [danielkrupinski/Osiris#3311]
Hey, I have 2 errors in visual studio. Do sombody know how to fix that?

1: 1> [CMake] CMake Error: The source "C:/Users/lea/Desktop/Osiris/CMakeLists.txt" does not match the source "C:/Users/lea/Desktop/Osiris test/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.

2:1> [CMake] CMake Error: The current CMakeCache.txt directory C:/Users/lea/Desktop/Osiris/out/build/x86-Release/CMakeCache.txt is different than the directory c:/Users/lea/Desktop/Osiris test/out/build/x86-Release where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt

Ty ^^.

**Comment by skirtsandflirts** [comment]
tbh just redownload the source
or redownload the individual `CMakeCache.txt` file
