### ISSUE TITLE
Rank & Medal Changer, Grenade Pred., Anti-OBS, C4 timer & defuse time check and Resolver

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#332]
How to make this cheat the best cheat out there:

- [ ] Rank Changer & Medal Changer;
- [ ] Grenade Prediction;
- [ ] Anti-OBS;
- [ ] C4 timer and defuse time check;
- [ ] Grenade ESP;
- [ ] Anti-Aim (it's being done i think);
- [ ] Resolver.

Menu is great and damage chance on aimbot is working nicely! Congratulations!

**Comment by Bywnb** [comment]
Rank Changer & Medal Changer;
its nice!

**Comment by Shaxzy** [comment]
> Rank Changer & Medal Changer;
> its nice!

Kinda useless though

**Comment by 4lb3** [comment]
> Kinda useless though
You might want to spoof it so your lobby mates think you are in a high rank, or make the enemies think your account is not fresh...

**Comment by cojo1989** [comment]
I see this preatty usefull also.

**Comment by LawtoNDA17** [comment]
+1 for Rank Changer! Good for excusing aimbot skills and for trolling friends!

**Comment by tirziz** [comment]
Still dont have C4 timer yet , so sad

**Comment by noob-cat** [comment]
All these features need to be added so bad.

**Comment by cojo1989** [comment]
If Daniel will be able to do resolver for this legit hack... it would be the best out there. But its kinda hard i think

**Comment by noob-cat** [comment]
Yeah actually tried HVH with it so if anybody is using somewhat of a good anti aim you're toasted since it dooesn't have a resolver. Plus the anti aim is slow, makes grenades unusable and ruins auto-bhop. Other than all of this - this cheat is godly.

**Comment by BlackmanWhite** [comment]
If you want a HVH cheat just get eternity or X0Y, this is more of a legit cheat than anything, also C4 timer got added and I hope that rank & medal changer gets added but it's not probable.

**Comment by noob-cat** [comment]
Everything that was suggested (except the resolver) are legit features, considering he suggested legit AA.
