### ISSUE TITLE
How can I make a grenade prediction like in moonlight.uno

### ISSUE THREAD

**Issue by Andrius86** [danielkrupinski/Osiris#3321]
I heard moonlight is an Osiris paste so how I can make grenade prediction like this in osiris 
![image](https://user-images.githubusercontent.com/83015208/136914104-38f8c60b-557d-4d82-91f0-3495b7bb13d4.png)

**Comment by Liam5750** [comment]
Simple fix: Learn how to code. Hard fix: Find the code on unknowncheats.me after hours of searching on a post from 2016
