### ISSUE TITLE
how to launch linux

### ISSUE THREAD

**Issue by peyman8487777** [danielkrupinski/Osiris#3325]
pls help me :|
I can not run it on Linux

**Comment by Metaphysical1** [comment]
use run script on my repo

**Comment by peyman8487777** [comment]
> use run script on my repo

How? 
Doc or helper?

**Comment by peyman8487777** [comment]
> use run script on my repo
cp: cannot stat 'libOsiris.so': No such file or directory
rm: cannot remove '/usr/lib/libOsiris.so': No such file or directory

**Comment by mdilai** [comment]
Install freetype headers according to your distro. It's literally says that.
