### ISSUE TITLE
SUGGESTION Anti AFK 

### ISSUE THREAD

**Issue by wieisstimpee** [danielkrupinski/Osiris#333]
will rotate circles in order to prevent getting kicked for inactivity.

**Comment by cojo1989** [comment]
Up for it !

**Comment by danielkrupinski** [comment]
Do you know after what time of inactivity server kicks you?

**Comment by chovss** [comment]
From my experience moving your mouse doesn't prevent you from being kicked only character movements

**Comment by wieisstimpee** [comment]
> Do you know after what time of inactivity server kicks you?

unsure, but i would say about every 5 minutes or so?

**Comment by wieisstimpee** [comment]
> From my experience moving your mouse doesn't prevent you from being kicked only character movements

i mean if he can make the mouse move would moving back and forward be much harder?

**Comment by danielkrupinski** [comment]
I've checked how server decides to kick player and it looks like server does **not** take into account:
- player view angles change
- player position change
- player mouse movement

Instead it counts time since last `cmd->buttons` change and kicks player if duration is too long.

**Comment by wieisstimpee** [comment]
> I've checked how server decides to kick player and it looks like server does **not** take into account:
> 
> * player view angles change
> * player position change
> * player mouse movement
> 
> Instead it counts time since last `cmd->buttons` change and kicks player if duration is too long.

Do you think you'll be able to create a anti-afk for that or will that be too hard?

**Comment by danielkrupinski** [comment]
Added, but not tested.

**Comment by wieisstimpee** [comment]
@danielkrupinski Thanks, will test it out now! On another note, I saw you added something that had to do with AntiAim are you planning on adding the actual feature or are you working on that? I saw a lot of suggestions about that.

**Comment by WeasselDW** [comment]
Please close
