### ISSUE TITLE
shtreeba injector

### ISSUE THREAD

**Issue by WhatsupDanger** [danielkrupinski/Osiris#3335]
Hello community i started using osiris back in august 2020 with VBL (Vac Bypass Loader) and SazInjector and also i used VMP (VM protect) to protect my dll and i haven't got any vac ban yet but recently sazinjector stopped working for many people and there's no response from the developer so i wanted to talk about shtreeba injector which i'm thinking to use.
the problem is shtreeba injector doesn't inject VM protected dll into csgo.exe and other injectors like extreme or Xenos or csghost many people have reported that they have been vac banned by using them

my other concern is that if i use VBL (Vac Bypass Loader) and shtreeba with raw osiris.dll (aka without junk code or VMP) what are the chances of me getting vac banned

PS: i've been using aimbot at 0.52 fov and backtrack at 200ms for a year now.

Thanks in advance!!

**Comment by mdilai** [comment]
@WhatsupDanger catch a lifehack - just get overwatch ban and if you had triggered VAC it will be changed with VAC ban in a day or two, instead of waiting for next VAC-wave about several weeks. But anyway its unlikely to be ever happen.

**Comment by lordeternity000** [comment]
What was your issue when injecting osiris using Shtreeba? Because I just injected VM protected dll using that and it worked.

**Comment by WhatsupDanger** [comment]
> @WhatsupDanger catch a lifehack - just get overwatch ban and if you had triggered VAC it will be changed with VAC ban in a day or two, instead of waiting for next VAC-wave about several weeks. But anyway its unlikely to be ever happen.

so its been 5 days and i've been using unprotected osiris (without VMP and junk code) with Vac Bypass Loader and still no VAC ban yet
