### ISSUE TITLE
[SUGGESTIONS!] Spinbot, Anti Aim, BOMB Timer, Bhop hit chance, Anti OBS, No spread, Projectile prediction, fake body, tracers

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#334]
I have browsed through the issues tab a bit, and have added what I believe would be the best cheats to add to this cheat. Thanks for all your hard work!

**Comment by RXJpaw** [comment]
x Spinbot
^ Anti-Aim
^ Bomb-Timer
^ Bhop %
^ Anti OBS
^ No spread
^ Projectile prediction
? fake body
? tracers

x = no
^ = yea
? = idk

**Comment by Nichealys** [comment]
> x Spinbot
> ^ Anti-Aim
> ^ Bomb-Timer
> ^ Bhop %
> ^ Anti OBS
> ^ No spread
> ^ Projectile prediction
> ? fake body
> ? tracers
> 
> x = no
> ^ = yea
> ? = idk

Does this show what you think would be good?
Also, fake body makes it so that there is always a fake you in front of your actual body, other aimbots aim for your fake. Tracers are lines that come out from your gun when you shoot.

**Comment by effex1337** [comment]
Do you even know what you're talking about? 
Spinbot, Anti-Aim, fake body (the general purpose/what it (is/does) of is the same)
no spread (not a feature)

**Comment by Nichealys** [comment]
> Do you even know what you're talking about?
> Spinbot, Anti-Aim, fake body (the general purpose/what it (is/does) of is the same)
> no spread (not a feature)

Yes, I realize these are extremely similar. I’m quite new to the cheating/coding community and thought they’d work quite well together.

**Comment by RXJpaw** [comment]
> Does this show what you think would be good?


yea xd

**Comment by Nichealys** [comment]
> > Does this show what you think would be good?
> 
> yea xd

Lol, why don’t you think spinbot would be good?

**Comment by RXJpaw** [comment]
> Lol, why don’t you think spinbot would be good?

i dont like spinbots ig... its just cancer to watch an everyone hates it. this cheats supposed to be "legit" tho... Legit-AA is fine to me

**Comment by Nichealys** [comment]
> > Lol, why don’t you think spinbot would be good?
> 
> i dont like spinbots ig... its just cancer to watch and everyone hates it. this cheats supposed to be "legit" tho... Legit-AA is fine to me

I do agree, although I’ve made a pretty good hvh config that I’ve had a fair match with sleek players! This cheat has lots of potential even just for a legit/light hvh cheat! I love it!

**Comment by RXJpaw** [comment]
> I do agree, although I’ve made a pretty good hvh config that I’ve had a fair match with sleek players! This cheat has lots of potential even just for a legit/light hvh cheat! I love it!

hvh-config for Osiris? wanna send me xd? i think i created one of the most legit configs for Osiris... i never got banned but i dont have a hvh-config for non-prime acc's or something

you cant share configs through files 
just send your aimbot-conf if you want to xd

**Comment by Nichealys** [comment]
> > I do agree, although I’ve made a pretty good hvh config that I’ve had a fair match with sleek players! This cheat has lots of potential even just for a legit/light hvh cheat! I love it!
> 
> hvh-config for Osiris? wanna send me xd? i think i created one of the most legit configs for Osiris... i never got banned but i dont have a hvh-config for non-prime acc's or something
> 
> you cant share configs through files
> just send your aimbot-conf if you want to xd

If you have discord I could send the whole config to you tommorow?

**Comment by RXJpaw** [comment]
huh? i thought you cant send entire configs cuz of the weird config-mechanics but yea... "Yui＃Yuffi#3293"

**Comment by Nichealys** [comment]
> huh? i thought you cant send entire configs cuz of the weird config-mechanics but yea... "Yui＃Yuffi#3293"

Idk, we’ll find out haha!

**Comment by RXJpaw** [comment]
> Idk, we’ll find out haha!
xd yea

**Comment by RXJpaw** [comment]
> Idk, we’ll find out haha!

yea xd

**Comment by NexSqaud** [comment]
> ? fake body
fake body? i think you mean fake angles(when you can rotate your model at 360 degrees), it fixed.

**Comment by jdb-jdb** [comment]
This has decent AA - https://github.com/ijre/Osiris
