### ISSUE TITLE
CSGO anti-server crasher

### ISSUE THREAD

**Issue by AuG-24** [danielkrupinski/Osiris#3340]
Recently , lots of people have been crashing csgo servers using their private cheats. Can a feature be implemented so that these crashes dont affect us?
![image](https://user-images.githubusercontent.com/54177940/137635334-820e748d-fe87-44a6-b9af-dc0f0f27a873.png)

LINK--> https://www.unknowncheats.me/forum/counterstrike-global-offensive/455278-server-crashers.html

**Comment by Liam5750** [comment]
> add cl_timeout 6 6 6
> to your autoexec
> 
> >
> 

Fkin retarded. U need a feature that sets the cvar cl_timeout to 1836428 I aint gonna provide code u need to figure it out. You also need a sv_pure bypass which is in a pull requests.

**Comment by r3muxd** [comment]
both of you are fucking morons
setting it to "6 6 6" sets it to -1 without hitting the limit, test it for yourself
