### ISSUE TITLE
(REQ) Event log

### ISSUE THREAD

**Issue by hitman2933** [danielkrupinski/Osiris#3343]
is there an event log like if someone takes damage you can see it

**Comment by skirtsandflirts** [comment]
> 
> 
> > You mean a damage log? I can put a simple one in, similarly to the Purchase Log that is in Osiris currently.
> > #3178
> 
> No, like the one OT has where it says who damaged who for how much. If you can make one then please teach me how so I can do it every osiris update, ty

https://i.imgur.com/TjbqIYR.png
I made a simple one that goes in chat, similarly to how the votelogger is made. Is this similar to what you want? If so I will PR it so you can add it.
