### ISSUE TITLE
Case Hardened Blue Gem

### ISSUE THREAD

**Issue by MrOpxDRS** [danielkrupinski/Osiris#3348]
Not a Issue But What about changing case hardened pattern to blue gem @danielkrupinski . If its hard then too sorry its ok

**Comment by wemanzoz** [comment]
Go to your cfg folder, find seed then change it to bluegem seed

**Comment by MrOpxDRS** [comment]
> Go to your cfg folder, find seed then change it to bluegem seed

Im so stupid sry tq

**Comment by yashguptaji** [comment]
Can u pls elaborate on how to do this, I couldnt find the cfg folder

**Comment by skirtsandflirts** [comment]
> 
> 
> Can u pls elaborate on how to do this, I couldnt find the cfg folder

Documents\Osiris
