### ISSUE TITLE
Bug/feature improvement reqd? Idk

### ISSUE THREAD

**Issue by effex1337** [danielkrupinski/Osiris#335]
I can only shoot through thin surfaces like really thin. Ik this might sound dumb but i do not shoot through some walls that are actually penetrable. For example safehouse in flying scoutman the wall that divides the map in two.

**Comment by Shaxzy** [comment]
I don't think that wall is penetrateable though.
Correct me if I'm wrong. What weapon did you try with anyways?

**Comment by effex1337** [comment]
Scout and i've been boosting accounts all the time if i get banned on flying scoutsman as i feel like its the fastest. I used to use a rage cheat that crashed like crazy so yeah that wall is penetrable.

**Comment by Shaxzy** [comment]
Hmm.. That’s very strange then
