### ISSUE TITLE
viewmodel xyz and hitmarker world

### ISSUE THREAD

**Issue by OsoM4n** [danielkrupinski/Osiris#3358]
i think it'll be perfect with xyz viewmodel changer and hitmarker with world option.

**Comment by skirtsandflirts** [comment]
I changed my mind in that I don't think it would be beneficial to make the viewmodel changer as there are minimal use cases for it.

**Comment by heftybuffer** [comment]
https://github.com/danielkrupinski/Osiris/issues/574
https://github.com/danielkrupinski/Osiris/pull/2359
