### ISSUE TITLE
Is my osiris outdated ?

### ISSUE THREAD

**Issue by Drevakis** [danielkrupinski/Osiris#3363]
So basicly i saw that some people have osiris with features like spray control and other stuff. I dont have that. And in general its broken. For example i have my aimbot turned and in workshop maps it works perfectly, but when i join a community server its not working. Same with chams and other stuff. I just wanna know if other people have this same problem or if it is just me.

**Comment by Xonn1com** [comment]
Someone might have done custom-build osiris?
