### ISSUE TITLE
SUGGESTION Sound ESP

### ISSUE THREAD

**Issue by wieisstimpee** [danielkrupinski/Osiris#337]
Sound ESP will be good  for legit hacking, you can make it draw beams from the player when hes walking so you dont have to focus so hard on footsteps.

**Comment by RXJpaw** [comment]
not only walking but yea... great idea.

**Comment by wieisstimpee** [comment]
> not only walking but yea... great idea.

why not only walking? thats the point of SOUND esp, when you hear someone shooting is loud and obvious where it comes from.

**Comment by RXJpaw** [comment]
> why not only walking?

i mean... not only walking. Not only sounds caused by players... but player sounds and every other sound...
like a dot that gets bigger caused by noiseness level

**Comment by wieisstimpee** [comment]
> > why not only walking?
> 
> i mean... not only walking. Not only sounds caused by players... but player sounds and every other sound...
> like a dot that gets bigger caused by noiseness level

Honestly sounds like its gonna be very hard for the developer to code if it needs to be a dot getting bigger caused by every sound by a enemy player. I'd rather have a simple beam coming from a non-shift walking enemy player. :) but thats just me

**Comment by RXJpaw** [comment]
hm... i dont think its that hard. you can intercept every movement why not sounds? sounds can be easily classified by the level of noiseness... 

btw "like a dot that gets bigger caused by noiseness level"
i said "like" for visual demonstration

**Comment by effex1337** [comment]
Its not really that hard
How to do it:
When theres a footstep a event named "player_footstep" is triggered then tou just need to draw them (and that part is what i am failing at i only have a "footstep" text poping up when someone makes a footstep. I just couldnt re create the ring :(

**Comment by wieisstimpee** [comment]
> Its not really that hard
> How to do it:
> When theres a footstep a event named "player_footstep" is triggered then tou just need to draw them (and that part is what i am failing at i only have a "footstep" text poping up when someone makes a footstep. I just couldnt re create the ring :(

Cant you just put for example *step* when the player is walking and that would be visible through walls at all times? Iniuria does this as far as i can remember

**Comment by effex1337** [comment]
" i only have a "footstep" text poping up when someone makes a footstep"

**Comment by wieisstimpee** [comment]
> " i only have a "footstep" text poping up when someone makes a footstep"

yes sir thats what i meant, could you give me the code or do you rather not share? Im fine with both :) thanks for taking time to reply by the way

**Comment by effex1337** [comment]
@wieisstimpee 
not 100% spoonfeed but https://pastebin.com/cxB5Hb0Y
you'd need to figure some stuff out gl :)

**Comment by effex1337** [comment]
sorry the old version was stoopid
https://pastebin.com/1y6XSCk7
This should work but you'd need to figure out some stuff hf :)

**Comment by synvy** [comment]
Just use render beams. Takes 20 mins tops to make this feature. Draw it in framestagenotify

**Comment by NexSqaud** [comment]
@synvy dont draw in framestagenotify! draw only in painttraverse!

**Comment by synvy** [comment]
@NexSqaud you draw beams in FramestageNotify.  Not OnPaintTraverse.
