### ISSUE TITLE
[HELP]Game crashes 2 minutes after you start a work shop map EDIT: ISSUE STILL ACTIVE 

### ISSUE THREAD

**Issue by kingofgivingup** [danielkrupinski/Osiris#3371]
i think it has something to do with the inventory changer 
edit:
video of the game starting and the crash
https://kapwi.ng/c/pS7fiodgpF
sorry for the music but here is the cfg too 
[walls.txt](https://github.com/danielkrupinski/Osiris/files/7439115/walls.txt)

**Comment by kingofgivingup** [comment]
i have it

**Comment by kingofgivingup** [comment]
> get newest build

i have it

**Comment by kingofgivingup** [comment]
THIS ISSUE STILL IS NOT FIXED WHEN YOU ADD TO MANY SKINS TO THE INVITORY CHANGER WORKSHOP MAPS/PRACTICE WITH BOTS CRASH YOUR GAME NEW UPDATES DONT FIX THIS

**Comment by sharkzxo** [comment]
i had same issue just fix the createmove hook.. (calloriginal, get original, auto result)
