### ISSUE TITLE
I can not open any knifes from cases

### ISSUE THREAD

**Issue by eXro222** [danielkrupinski/Osiris#3372]
I opened about 500 cases with my friends for fun and i got no knifes cloud this be a issue or danielkrupinski didnt add it yet?
Can someone help me

**Comment by Liam5750** [comment]
Knifes arent added in drops for some readon. Sorry

**Comment by eXro222** [comment]
^
Thanks , i hope they will be added :(

**Comment by svistiik** [comment]
yup same here, would love to see knives/glove drop from cases

**Comment by mindz0r** [comment]
well i want to bump because i would like that, or any code to change idk

**Comment by danielkrupinski** [comment]
Now you can receive knives from Dreams and Nightmares Case and Operation Riptide Case. More to come.
