### ISSUE TITLE
Is Osiris undetectable?

### ISSUE THREAD

**Issue by davintera** [danielkrupinski/Osiris#3376]
Hi! Are Osiris offsets undetectable to CSGO, and where are they? Thanks!

**Comment by eXro222** [comment]
Yes , if youre going to use vac bypass there is no chanse of getting vac only overwatch ban

**Comment by davintera** [comment]
> Yes , if youre going to use vac bypass there is no chanse of getting vac only overwatch ban

Thank you for clarifying my doubt!
