### ISSUE TITLE
How to use the cheat ;-;

### ISSUE THREAD

**Issue by Cyanide334** [danielkrupinski/Osiris#338]
Im sorry but im a noob.. all i know is how to dload stuff.. and i dont know how to "compile" or use ur cheat or whatever.. can u please explain what i need to download from github and elsewhere and how to get the cheat up and running? Please ;-;

**Comment by Nichealys** [comment]
If you scroll down on the main page of the cheat, you can see the instructions. :)

**Comment by Cyanide334** [comment]
Ye i cant understand the language.. cloning, code, injector, buil, sdk. .sln.. can you please explain in simple words..? And how exactly am i supposed to opem files? Notepad.?

**Comment by Nichealys** [comment]
The instructions are pretty simple. But, you open the .sln files in Visual Studio 2019. You can download it on Microsoft’s official website.

**Comment by Cyanide334** [comment]
How exactly to do the fitst step.. to obtain the source code??

**Comment by Nichealys** [comment]
If I’m hearing you correctly, you just download the files. It’s the .sln file.

**Comment by Cyanide334** [comment]
Whats your umm.. favourite* or most optimal dll injector? And is the cheat safe to use?

**Comment by Nichealys** [comment]
Alright, I use a pasted injector for this cheat. It’s called rando injector, and it’s on github as well. I’d recommend watching a YouTube tutorial on how to configure it.

**Comment by Cyanide334** [comment]
Thanks for ypur time good sir! :)
