### ISSUE TITLE
[HELP] can we/how to change watermark text color?

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#3380]
lmao i dont know what im doing help 😳

**Comment by CRiQ01** [comment]
learncpp.com . good luck

**Comment by xXsnip3rXx** [comment]
learncpp.com like i asked for a whole recode why reply if ur not gonna try to help

**Comment by CRiQ01** [comment]
> learncpp.com like i asked for a whole recode why reply if ur not gonna try to help 

Yo. My dude. Changing a color is one of the most basic things ever existing. Just take it from the beginning and learn how to do it.

**Comment by xXsnip3rXx** [comment]
I know its basic that's why i asked ._. I don't have time to learn it yet. I'm gonna start tho just not this year. 
~~_also some dude literally coded a whole event log just because someone asked so you dont have to go learncpp.com on every newbie thread :p_~~

**Comment by Nonsocial9** [comment]
> > learncpp.com like i asked for a whole recode why reply if ur not gonna try to help
> 
> Yo. My dude. Changing a color is one of the most basic things ever existing. Just take it from the beginning and learn how to do it.

See you know whats funny this is ImGui not directly c++ so don't be more of a retard than you are and just help

**Comment by CRiQ01** [comment]
> > > learncpp.com like i asked for a whole recode why reply if ur not gonna try to help
> > 
> > Yo. My dude. Changing a color is one of the most basic things ever existing. Just take it from the beginning and learn how to do it.
> 
> See you know whats funny this is ImGui not directly c++ so don't be more of a retard than you are and just help

My guy. After this comment, I assume you aren't far from the first guy. If imgui is not directly c++, then why is it in a c++ project? It is literally pure c++ powerful library. Changing a color isn't more than Literally finding the place where you want to change it (if you really are a beginner, just guide yourself using strings), and changing it. In case it is used as rgb (255, 255, 0) or as hex #FFFF00 using a website that convert color picking into rgb, hex, hsb or whatever the code requires.

If you needed help too, you are welcome. "learn c++" was meant to encourage that guy to learn a little bit before working on a complex source written by people who took their time to learn.
