### ISSUE TITLE
coding in lua for csgo

### ISSUE THREAD

**Issue by lordeternity000** [danielkrupinski/Osiris#3381]
I am very new to lua and dont know the syntax much
Can anyone suggest lua code for below C ++ code.

recoilCrosshair = interfaces->cvar->findVar("cl_crosshair_recoil");
recoilCrosshair->setValue(config->misc.recoilCrosshair ? 1 : 0);

its part for recoil crosshair code that daniel used earlier.

Thanks

**Comment by linuxer9** [comment]
you need this to work on another paid cheat with lua?
if so, look at their documentation or wiki on how to change cvars.

**Comment by lordeternity000** [comment]
Oh i found it. Forgot to close this thread.
