### ISSUE TITLE
[Help] Trying to port forceRelayCluster to Osiris.

### ISSUE THREAD

**Issue by AuG-24** [danielkrupinski/Osiris#3385]
Quick intro - **forceRelayCluster** is a feature I spotted in NEPS (an open source cheat based heavily on osiris) . It basically lets you select the region you wish to queue for (for eg. US South , west , east , London , frankfurt , vienna , hong kong etc etc). 
The main code for it is as follows:- (not my work)

```
void Misc::forceRelayCluster() noexcept
{
	std::string dataCentersList[] = {"", "syd", "vie", "gru", "scl", "dxb", "par", "fra", "hkg",
	"maa", "bom", "tyo", "lux", "ams", "limc", "man", "waw", "sgp", "jnb",
	"mad", "sto", "lhr", "atl", "eat", "ord", "lax", "mwh", "okc", "sea", "iad"};

	*memory->relayCluster = dataCentersList[config->misc.forceRelayCluster];
}
```

You can find this under [ _**NEPS-master\NEPS\Hacks\Misc.cpp**_  ] and scroll over to the ending of the code.

SInce I am only a beginner at coding , I tried to simply copy paste the command but it did not work (obv.) and I realised that we need to  add all the relevant code like ImGUI code and some declarations etc . But that is beyond my skill level and it'll take me a long time to solve all the errors..

Could anyone from the community please help me with this? I would really like to queue in diff. regions with my buddies.
All help appreciated :)

**Comment by wemanzoz** [comment]
first you need to change the "config->misc.forcerelaycluster" to something like miscconfig.forcerelaycluster. Do the read-write stuffs on misc.cpp and some other stuffs idk. Or, find the commit then do exactly what degenhyperbola did but adapt the code to newest osiris thing

**Comment by AuG-24** [comment]
i'll try this but I understand only so much

**Comment by AuG-24** [comment]
> first you need to change the "config->misc.forcerelaycluster" to something like miscconfig.forcerelaycluster. Do the read-write stuffs on misc.cpp and some other stuffs idk. Or, find the commit then do exactly what degenhyperbola did but adapt the code to newest osiris thing

tried it.. its really hard for me and i am in a sea of errors..

**Comment by AuG-24** [comment]
[https://github.com/degeneratehyperbola/NEPS/commit/7f2a56dd60b154d3fd0b2634c099f4a2a31f9b01](url)
relevant commit

**Comment by wemanzoz** [comment]
> https://github.com/degeneratehyperbola/NEPS/commit/7f2a56dd60b154d3fd0b2634c099f4a2a31f9b01

its not that hard tbh, do the read~write on Misc.cpp, ctrl f and find read/write stuffs. then go ctrl f and search for "bool bombTimer = false;" or "bomb timer" in general. then do the 2nd step. then do the 

bool Misc::shouldRevealMoney() noexcept
{
    return miscConfig.revealMoney;
}

thing but name it something like misc::forcerelaycluster and miscconfig.forcerelaycluster. then do the gui thing. then pasta the code for the forcerelay cluster but instead of config->misc you do the miscconfig.forcerelaycluster. then ur done at misc.cpp now you go to misc.h and do the steps. after that do the hooks.cpp thing, memory.cpp things if the memory outdated there should be on uc (idk tbh). do the memory.h and boom

**Comment by AuG-24** [comment]
gonna try this.. thanks for bigger explanation

**Comment by AuG-24** [comment]
> > [degeneratehyperbola/NEPS@7f2a56d](https://github.com/degeneratehyperbola/NEPS/commit/7f2a56dd60b154d3fd0b2634c099f4a2a31f9b01)
> 
> its not that hard tbh, do the read~write on Misc.cpp, ctrl f and find read/write stuffs. then go ctrl f and search for "bool bombTimer = false;" or "bomb timer" in general. then do the 2nd step. then do the
> 
> bool Misc::shouldRevealMoney() noexcept { return miscConfig.revealMoney; }
> 
> thing but name it something like misc::forcerelaycluster and miscconfig.forcerelaycluster. then do the gui thing. then pasta the code for the forcerelay cluster but instead of config->misc you do the miscconfig.forcerelaycluster. then ur done at misc.cpp now you go to misc.h and do the steps. after that do the hooks.cpp thing, memory.cpp things if the memory outdated there should be on uc (idk tbh). do the memory.h and boom

I guess I am not smart enough.. I did everything you asked but I am still getting 9-10 erros .. I did all the #include stuff yet I am getting undefined variables kind of errors.  I am gonna call it a day and try this again later . I would be glad if you could maybe try it out and share the files so that I can learn and do it myself in the next updates.

**Comment by wemanzoz** [comment]
ill do so when i can

**Comment by SM9CC** [comment]
This needs a sig for linux though.

**Comment by AuG-24** [comment]
> This needs a sig for linux though.

what do you mean sir?

**Comment by SM9CC** [comment]
> > This needs a sig for linux though.
> 
> what do you mean sir?

https://github.com/degeneratehyperbola/NEPS/commit/7f2a56dd60b154d3fd0b2634c099f4a2a31f9b01#diff-9d7c5070347a91b61b427c5b91b68e16e82c3f2549d8971c1b8f4921fa8794e2R76

Sig is short for signature.
