### ISSUE TITLE
Failed to find VClient018 interface

### ISSUE THREAD

**Issue by N1mEHax** [danielkrupinski/Osiris#3386]
Hello, I reinstaled csgo today again and when i inject Ossiris.dll it gives me this error. I did rebuild ossiris in visual studio, moved the dll to c://windows and verify csgo files integriti 2 times, but the error stil pops up. I am sorry for my english talking level.

![20211105_193401](https://user-images.githubusercontent.com/77936052/140566905-e43728e5-20ac-4b23-91ec-c92c38ce324c.jpg)

**Comment by uzdiiilekk** [comment]
Ask on selectfire.cc because they changing osiris so it cannot be osiris issue

**Comment by N1mEHax** [comment]
> Ask on selectfire.cc because they changing osiris so it cannot be osiris issue 

I re-downloaded osiris and build it again ( i deleted every osiris file before downloading it again) and still same issue,

**Comment by kingofgivingup** [comment]
> > Ask on selectfire.cc because they changing osiris so it cannot be osiris issue
> 
> I re-downloaded osiris and build it again ( i deleted every osiris file before downloading it again) and still same issue,

it might be because you injected before csgo was fully launched wait till cs opens fully then inject

**Comment by N1mEHax** [comment]
> > > Ask on selectfire.cc because they changing osiris so it cannot be osiris issue
> > 
> > I re-downloaded osiris and build it again ( i deleted every osiris file before downloading it again) and still same issue,
> 
> it might be because you injected before csgo was fully launched wait till cs opens fully then inject

Thx that worked :)
