### ISSUE TITLE
List of features that could be added

### ISSUE THREAD

**Issue by GetRektLOL** [danielkrupinski/Osiris#3388]
- Vote Kick Reverser (When a player tries to vote kick you, they vote kick themselves)
- Turning Away From Flash Automatically
- Fake Prime, though i think it is patched
- Graffiti support

If You could add something like this, Osiris would totally be the best legit cheat

**Comment by wemanzoz** [comment]
You cant do number 1. Fake prime is patched and its useless. Turning flash automatically is useless lmao it will snap and ppl will think ur cheating very fast. and then graffiti support i dont think its possible since its clientsided

**Comment by GetRektLOL** [comment]
1st one can be done, I have seen it while I tried to kick some spinbotters but I do not expect this from a free cheat. 2nd should be done with some smoothing so it is not instant. Others I understand why they are not present

**Comment by KurastikO** [comment]
#1 isn't possible, you probably got kicked because of the _sleight of hand_

**Comment by sanikbug2k18** [comment]
movement recorder would be great :)

**Comment by uzdiiilekk** [comment]
> movement recorder would be great :)

why everyone need movement recorder ? if you need movement recorder then you can´t do jumps and then you can´t record it for it so it´s useless for you

**Comment by Liam5750** [comment]
> > movement recorder would be great :)
> 
> 
> 
> why everyone need movement recorder ? if you need movement recorder then you can´t do jumps and then you can´t record it for it so it´s useless for you 

Hey uzdiiilekk <3 Smellon mastercoder
