### ISSUE TITLE
Crashing after the update (Linux)

### ISSUE THREAD

**Issue by MrOpxDRS** [danielkrupinski/Osiris#3389]
Its crashing in ubuntu 20.04 @danielkrupinski 
i even again compileed

**Comment by GetRektLOL** [comment]
Doesnt Crash for me on windows 10 21h1, probably a linux issue or some issue with the newest commit

**Comment by relativist** [comment]
Crash for me too after update. Ubuntu 20.04.3 LTS 5.4.0-90-generic.

**Comment by GetRektLOL** [comment]
Actually, I tried on linux now, crashes for me as well. Ubuntu 21.10

**Comment by mxez** [comment]
moveData (#41 pattern) is outdated.

**Comment by GetRektLOL** [comment]
> moveData (#41 pattern) is outdated.

Any way to fix this on Linux?

**Comment by mxez** [comment]
Doesn't crash anymore after last commit. Close this.
