### ISSUE TITLE
Config not saving

### ISSUE THREAD

**Issue by jdb-jdb** [danielkrupinski/Osiris#339]
Don't know if it's a problem on my part or others as well but the newest release is what I have compiled but I change all settings fine I click save config and the name shows up but the config file is not created in osiris at all. I see people have trouble with skins not saving but my whole config is not saving. I didn't modify the repo I just compiled and ran.
Thanks

**Comment by Shaxzy** [comment]
I see you closed this issue which I suppose is because you managed to fix it / solved the issue yourself.
I just wanted to let you know that I do not have such issue whatsoever.

**Comment by jdb-jdb** [comment]
Yeah, it was a mistake on my part to avoid doing any checks or hashes at compilation(is there a verified md5 or sha512 or whatever hash?) and the only file with missing bytes was config. The actual file looked fine in vs but upon debugging some bytes not visible were deleted so just didn't work. Its no problem I just made a new one.

-------- Original Message --------
