### ISSUE TITLE
Any Way to make profile picture changer

### ISSUE THREAD

**Issue by GetRektLOL** [danielkrupinski/Osiris#3394]
Name Stealer Feature is good and prevents some people from kick you, but since the pfp is visible in the kick menu, most people know that you are hacker and can kick you. Is there any way to make it so that profile picture is also replaced with the pfp of other players. I know this might be not possible, so please add it if you can.

**Comment by Liam5750** [comment]
Would be delayed like crazy and you would have to have some sytem to "screenshot" it and then store it and apply. Steam caps this type of thing and in about 3 seconds it would force stop it.
