### ISSUE TITLE
How do I make the aimbot only shoot at people that are not behind a wall

### ISSUE THREAD

**Issue by JayneFrack** [danielkrupinski/Osiris#34]
How would I make an Option that makes the aimbot only shoot at people that are not behind a wall?
This is kind of a Request for a feature or for code that can do it thanks.

**Comment by designeruc** [comment]
U need engine trace interface and isvisible check.

**Comment by JayneFrack** [comment]
Do you know a way of how I could do that?

**Comment by synvy** [comment]
Add the ivenginetrace class and call it in your interfaces. Then make an is visible check to see if you can see a certain bone of the enemy. If you can't see the bone, don't lock on.
