### ISSUE TITLE
XINPUT1_4.dll is missing from your computer error

### ISSUE THREAD

**Issue by travispresk0** [danielkrupinski/Osiris#340]
I compiled and injected it using Visual Studio and an undetected injector. Worked fine from my Windows 10 laptop, but this error shows up on my Windows 7 pc. I think the last working version of the cheat (in Windows 7) was at June 26-ish.

**Comment by Shaxzy** [comment]
Are you using latest version? I think Daniel fixed this in one of the most recent commits.

**Comment by travispresk0** [comment]
> Are you using latest version? I think Daniel fixed this in one of the most recent commits.

I haven't used the latest just yet. Thanks for reminding he did. Might check later

**Comment by Bywnb** [comment]
plz use the latest version :)

**Comment by travispresk0** [comment]
works now :)
