### ISSUE TITLE
About community-server's anticheat issue

### ISSUE THREAD

**Issue by 2933968621** [danielkrupinski/Osiris#3401]
when I was playing on the community server, I found that ESP did not work when the player was not visible
If players are not visible, they are dormant
I found a server-side anticheat source. Its video function is consistent with the problem.
Source:https://github.com/HonestGamingInc/CSGO_SauRay
Video:https://www.youtube.com/watch?v=MqztLKqYGiU
WebSite:https://honestgaming.io/
Is there anyway to fix it?

**Comment by notgoodusename** [comment]
since its server sided, there is no way to fix it

**Comment by 2933968621** [comment]
> since its server sided, there is no way to fix it

omg I find this anti-cheat on a lot of fucking servers

**Comment by ConniBug** [comment]
> > since its server sided, there is no way to fix it
> 
> omg I find this anti-cheat on a lot of fucking servers

You angery that they have decent anticheat?

**Comment by 2933968621** [comment]
> 

his client have a good anticheat system, why server need use plugin anticheat

**Comment by ConniBug** [comment]
???...
