### ISSUE TITLE
csgo crashing when i inject

### ISSUE THREAD

**Issue by Dino-log** [danielkrupinski/Osiris#3402]
i am using guided hacking dll injector (GH Injector) here are my settings when injecting (i use default ones)
![Screenshot_25](https://user-images.githubusercontent.com/66836260/141682876-5b9406ed-837b-4ea6-b9e5-eb2ec0707a18.png)

**Comment by tusharborkar360** [comment]
Please use Process Hacker 2 to inject the DLL.
It is like whitelisted by Valve so chances of errors are also low.

**Comment by Slipsource** [comment]
> Please use Process Hacker 2 to inject the DLL. It is like whitelisted by Valve so chances of errors are also low.
crashes for me too but i use newest version of ghost

**Comment by 1211786712** [comment]
> 请使用 Process Hacker 2 注入 DLL。 它就像被 Valve 列入白名单，所以出错的几率也很低。

Can I use process hacker without using vacbypass? Because vacbypass will reduce credit

**Comment by tusharborkar360** [comment]
You're right that VAC Bypass reduces Trust Factor but I haven't tried without using VAC bypass... I'm scared that I'll recieve VAC Ban. I just use Osiris in Casual matches and enjoy the game.. not so into compi, as can't just find any match for compi.
