### ISSUE TITLE
Can I use process hacker without using vacbypass? Because vacbypass will reduce credit

### ISSUE THREAD

**Issue by 1211786712** [danielkrupinski/Osiris#3407]
Will it be forbidden to directly use process hacker without using vacbypass? Because vacbypass will reduce credit, competitive mode HVH

**Comment by 1211786712** [comment]
Will injecting Osiris directly using process hacker be prohibited

**Comment by Shuvi-Moro** [comment]
You can use the process hacker, but I do not work and cheat sticks vaс. All at your own risk. 
P.S. I do not know how other cheats work, but I can assure you that if you rewrite cheat for himself and just update it as updates appear, he top!

**Comment by Shuvi-Moro** [comment]
And if you're looking for cheats and think that the free cheat is for you, then either you zheyuto proarenye or you're a beginner, and in the latter case, I advise to abandon this endeavor.

**Comment by Shuvi-Moro** [comment]
fiercely knowledgeable*
