### ISSUE TITLE
Aimbot Key

### ISSUE THREAD

**Issue by travispresk0** [danielkrupinski/Osiris#341]
How do I set the key for aimbot?

**Comment by cojo1989** [comment]
Aimbot key you got it in Aimbot tab

**Comment by travispresk0** [comment]
> Aimbot key you got it in Aimbot tab

Yea I see it, but how can I assign the key?

**Comment by danielkrupinski** [comment]
Hover `[ key ]` text and press desired button.

**Comment by travispresk0** [comment]
> Hover `[ key ]` text and press desired button.

Thank you Daniel!
