### ISSUE TITLE
feature suggestion: Model Changer

### ISSUE THREAD

**Issue by ocewot** [danielkrupinski/Osiris#3412]
Well first sv pure bypass i think its needed (for model changer)
basically a feature that allows you to use any custom models off of websites they are like custom knives and such

also can the inventory changer be changed to allow any custom skins like it used to before it was an inventory changer? 
i just want the ability to apply custom skins to stuff not just what is already a real skin like doppler on an awp if you get what i mean. 

maybe im dumb but ya let me know XD

**Comment by Liam5750** [comment]
He makes ever bit about this cheat easy to use and newbie friendly. So adding things like this will confuse people(this is his logic btw not mine lol) thats why you will never see this added

**Comment by ocewot** [comment]
some cheats that have model changer have preset models to pick from it doesnt have to be something you can add yourself but alright it was just a suggestion

**Comment by Liam5750** [comment]
Ik but he never adds. I dmed him on discord abt adding pull reqs and he said "suck my d*ck"

**Comment by Metaphysical1** [comment]
> Ik but he never adds. I dmed him on discord abt adding pull reqs and he said "suck my d*ck"

I don't think he has discord, you just contacted an imposter I think.

**Comment by IstAuchEgal** [comment]
> I don't think he has discord, you just contacted an imposter I think.

he is active on the gamesneeze discord
