### ISSUE TITLE
CSGO crashes when I inject even when i inject with process hacker 2

### ISSUE THREAD

**Issue by Thehappycoder123** [danielkrupinski/Osiris#3415]
I used Process Hacker 2 to inject the Osiris.dll file and I press insert and nothing happens. I do not have an extended keyboard so I'm guessing this could be the issue.

**Comment by Thehappycoder123** [comment]
nevermind you just have to put it in the windows folder

**Comment by Thehappycoder123** [comment]
but now csgo crashes when i try and inject

**Comment by Frouk3** [comment]
Use other injector

**Comment by Shuvi-Moro** [comment]
@Frouk3 What injectors can you recommend

**Comment by Frouk3** [comment]
> @Frouk3 What injectors can you recommend

I downloaded manual map injector and make bat file for that(dll names applies for dlls in the folder where batch file starts)
Injector is detected so use vac bypass
