### ISSUE TITLE
Paste movement features

### ISSUE THREAD

**Issue by ikusiss** [danielkrupinski/Osiris#3416]
Im dont really know how to code or anything like that. But maybe we can use some movement paste cheats sources to add the same features to osiris? (edgebug, jumpbug, autostrafe bind, etc) I mean, it would be really cool but i dont know if it is posible.

**Comment by fullyonline** [comment]
edgejump (with togglekey) and autostrafe (only on/off) are already in the cheat.

**Comment by csgofever** [comment]
i think he meant edgebug not edgejump.

**Comment by csgofever** [comment]
i made a pull request for edgebug if you are still looking for edgebug code, #3517
