### ISSUE TITLE
Different hitbox models than normal cs:go.

### ISSUE THREAD

**Issue by arthures11** [danielkrupinski/Osiris#3418]
Imagine you are playing on a cs:go surf server with different skin models and enemies look+have different head hitboxes but the aimbot will still aim like they are normal and if you aim for bone Head it won't hit head. 
Is there any pull to get the actual hitboxes and hit head as supposed?

**Comment by arthures11** [comment]
anyone able to help how to fix the hitboxes? Fix bone matrix in Misc doesn’t do anything to that

**Comment by wemanzoz** [comment]
bro, why u cheat ON FUCKING SURF LMAO

**Comment by arthures11** [comment]
> bro, why u cheat ON FUCKING SURF LMAO

its just an exmaple, aim won't work propertly on custom player models and i'm trying to fix it
