### ISSUE TITLE
Checkbox size

### ISSUE THREAD

**Issue by Gino** [danielkrupinski/Osiris#342]
Hi there,

Does anyone know how to make the checkboxes less large and also make the label, next to it, align correctly? Since it might get aligned incorrectly when I make the checkbox smaller.

Quite new to all of this so I hope that someone could help me with this.

Thanks.

**Comment by Mufinekkk** [comment]
You can do that in imgui folder.

**Comment by Gino** [comment]
@Mufinekkk, could you tell me where? Since there are multiple files there.

**Comment by Mufinekkk** [comment]
In imgui.cpp or imgui_draw.cpp, now idk that.

**Comment by danielkrupinski** [comment]
You can achieve that by altering  https://github.com/ocornut/imgui/blob/ea79992d9add90f5e6d23b7b7941aceb20734bd5/imgui_widgets.cpp#L986
