### ISSUE TITLE
Injecting Issue On New Update (Linux)

### ISSUE THREAD

**Issue by GetRektLOL** [danielkrupinski/Osiris#3421]
Injecting libOsiris.so with the load script just freezes the game without crashing or anything and there is no error message in the terminal too. Arch Linux x64 Latest Update. This is happening after the new update which came out today. Please fix this

**Comment by Metaphysical1** [comment]
it doesn't crash for me, try debugging?

**Comment by GetRektLOL** [comment]
Still Happening For Me, I think it is a issue with the latest kernel, (correct me if i am wrong)

**Comment by Metaphysical1** [comment]
I'm using linux mint 20.2 and kernel 5.4.0-81-generic

**Comment by SM9CC** [comment]
Yes, it fails to inject on kernel 5.15+
