### ISSUE TITLE
Crashes again when steam loads

### ISSUE THREAD

**Issue by yashguptaji** [danielkrupinski/Osiris#3422]
It crashes when steam loads, saying that pls update steam, but my steam is already updated. Says its a fatal error

**Comment by tusharborkar360** [comment]
Open steam with VAC bypass Loader. Then open CS:GO and when in lobby at that time inject the Osiris DLL with Process Hacker 2.

**Comment by yashguptaji** [comment]
I did that, but process hacker doesnt work smh. The osiris menu doenst open up

**Comment by tusharborkar360** [comment]
Have you pasted the Osiris DLL in Windows folder?

**Comment by wemanzoz** [comment]
use csghost 3.1

**Comment by yashguptaji** [comment]
is it safe?

**Comment by yashguptaji** [comment]
> Have you pasted the Osiris DLL in Windows folder?
yup, that worked, thanks :)

**Comment by tusharborkar360** [comment]
Okay great!
