### ISSUE TITLE
is vac bypass necessary?

### ISSUE THREAD

**Issue by ocewot** [danielkrupinski/Osiris#3423]
i see a lot of people saying "use vac bypass" but i heard it makes your trust factor low. id like to avoid using it if possible. anyone got any information? I've added a couple features and removed a couple so the signature is a little bit different not sure if that makes a big difference or not though.

**Comment by Metaphysical1** [comment]
if you are using detected injectors, or public builds you should use vac bypass

**Comment by tusharborkar360** [comment]
> i see a lot of people saying "use vac bypass" but i heard it makes your trust factor low. id like to avoid using it if possible. anyone got any information? I've added a couple features and removed a couple so the signature is a little bit different not sure if that makes a big difference or not though.

Okay then, you should use Process Hacker 2 as Injector as it is something like whitelisted by Valve. I've been using it without VAC Bypass Loader. I haven't recieved any VAC ban since. Process Hacker 2 is non-detectable while injecting any DLL.

Just paste the updates Osiris DLL in your Windows Folder.

**Comment by arthures11** [comment]
don't use it, patched and vac bannable

**Comment by ReShout876** [comment]
Just make sure your build is updated.

**Comment by EXC3L-YT** [comment]
> don't use it, patched and vac bannable

What is patched ?

**Comment by arthures11** [comment]
> > don't use it, patched and vac bannable
> 
> What is patched ?

apparently the bypass itself was patched, theres no other explanation why the acc would get vacbanned, there was only bypass used. You can test it by yourself on fresh steam acc

**Comment by ocewot** [comment]
> > > don't use it, patched and vac bannable
> > 
> > 
> > What is patched ?
> 
> apparently the bypass itself was patched, theres no other explanation why the acc would get vacbanned, there was only bypass used. You can test it by yourself on fresh steam acc

your account or someone else?

**Comment by arthures11** [comment]
> > > > don't use it, patched and vac bannable
> > > 
> > > 
> > > What is patched ?
> > 
> > 
> > apparently the bypass itself was patched, theres no other explanation why the acc would get vacbanned, there was only bypass used. You can test it by yourself on fresh steam acc
> 
> your account or someone else?

mine, my friends too

**Comment by ocewot** [comment]
> > > > > don't use it, patched and vac bannable
> > > > 
> > > > 
> > > > What is patched ?
> > > 
> > > 
> > > apparently the bypass itself was patched, theres no other explanation why the acc would get vacbanned, there was only bypass used. You can test it by yourself on fresh steam acc
> > 
> > 
> > your account or someone else?
> 
> mine, my friends too

which injector did you use? (while using the bypass)

**Comment by arthures11** [comment]
> > > > > > don't use it, patched and vac bannable
> > > > > 
> > > > > 
> > > > > What is patched ?
> > > > 
> > > > 
> > > > apparently the bypass itself was patched, theres no other explanation why the acc would get vacbanned, there was only bypass used. You can test it by yourself on fresh steam acc
> > > 
> > > 
> > > your account or someone else?
> > 
> > 
> > mine, my friends too
> 
> which injector did you use? (while using the bypass)

old CSGHOST v3.1, ive been using it together with bypass for around 1/2 years and never been banned, now it changed

**Comment by 1211786712** [comment]
You mean VAC bannable didn't actually work, did you?

**Comment by 1211786712** [comment]
> > > > > > > 不要使用它，修补和 vac 禁止
> > > > > > 
> > > > > > 
> > > > > > 什么是补丁？
> > > > > 
> > > > > 
> > > > > 显然旁路本身已被修补，没有其他解释为什么 acc 会被 vacbanned，只使用了旁路。您可以在新鲜蒸汽 acc 上自行测试
> > > > 
> > > > 
> > > > 您的帐户还是其他人？
> > > 
> > > 
> > > 我的，我的朋友也是
> > 
> > 
> > 你用的是哪个注射器？（使用旁路时）
> 
> 旧的CSGHOST v3.1，我和bypass一起用了大约1/2年，从未被禁止，现在它改变了

You mean VAC bannable didn't actually work, did you?

**Comment by arthures11** [comment]
> > > > > > > > 不要使用它，修补和 vac 禁止
> > > > > > > 
> > > > > > > 
> > > > > > > 什么是补丁？
> > > > > > 
> > > > > > 
> > > > > > 显然旁路本身已被修补，没有其他解释为什么 acc 会被 vacbanned，只使用了旁路。您可以在新鲜蒸汽 acc 上自行测试
> > > > > 
> > > > > 
> > > > > 您的帐户还是其他人？
> > > > 
> > > > 
> > > > 我的，我的朋友也是
> > > 
> > > 
> > > 你用的是哪个注射器？（使用旁路时）
> > 
> > 
> > 旧的CSGHOST v3.1，我和bypass一起用了大约1/2年，从未被禁止，现在它改变了
> 
> You mean VAC bannable didn't actually work, did you?

Yes, it DOES NOT work anymore. If you think i'm wrong you can check it by yourself on fresh steam account, use the bypass and see by yourself if acc gets bac within a week or so.

**Comment by HowToMakeFaceitAB** [comment]
> > > > > > > > > 不要使用它，修补和 vac 禁止
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 什么是补丁？
> > > > > > > 
> > > > > > > 
> > > > > > > 显然旁路本身已被修补，没有其他解释为什么 acc 会被 vacbanned，只使用了旁路。您可以在新鲜蒸汽 acc 上自行测试
> > > > > > 
> > > > > > 
> > > > > > 您的帐户还是其他人？
> > > > > 
> > > > > 
> > > > > 我的，我的朋友也是
> > > > 
> > > > 
> > > > 你用的是哪个注射器？（使用旁路时）
> > > 
> > > 
> > > 旧的CSGHOST v3.1，我和bypass一起用了大约1/2年，从未被禁止，现在它改变了
> > 
> > 
> > You mean VAC bannable didn't actually work, did you?
> 
> Yes, it DOES NOT work anymore. If you think i'm wrong you can check it by yourself on fresh steam account, use the bypass and see by yourself if acc gets vac within a week or so.

You are wrong, it does work.

**Comment by arthures11** [comment]
> > > > > > > > > > 不要使用它，修补和 vac 禁止
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 什么是补丁？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 显然旁路本身已被修补，没有其他解释为什么 acc 会被 vacbanned，只使用了旁路。您可以在新鲜蒸汽 acc 上自行测试
> > > > > > > 
> > > > > > > 
> > > > > > > 您的帐户还是其他人？
> > > > > > 
> > > > > > 
> > > > > > 我的，我的朋友也是
> > > > > 
> > > > > 
> > > > > 你用的是哪个注射器？（使用旁路时）
> > > > 
> > > > 
> > > > 旧的CSGHOST v3.1，我和bypass一起用了大约1/2年，从未被禁止，现在它改变了
> > > 
> > > 
> > > You mean VAC bannable didn't actually work, did you?
> > 
> > 
> > Yes, it DOES NOT work anymore. If you think i'm wrong you can check it by yourself on fresh steam account, use the bypass and see by yourself if acc gets vac within a week or so.
> 
> You are wrong, it does work.

so did you test it or what makes you so confident?

**Comment by Ativ3k** [comment]
> apparently the bypass itself was patched, theres no other explanation why the acc would get vacbanned, there was only bypass used. You can test it by yourself on fresh steam acc

u use v3.1, newer version with fixes and other "dumb bypass method" is 4.3.1
after +400h in ~3 months 0 bans.

**Comment by arthures11** [comment]
> > old CSGHOST v3.1, ive been using it together with bypass for around 1/2 years and never been banned, now it changed
> 
> u use v3.1, newer version with fixes and other "dumb bypass method" is 4.3.1 after +400h in ~3 months 0 bans.

newer versions have bypass inbuilt thats why i never wanted to use them, i prefered to run the bypass seperately.
after ~2 years i never got banned but now, new account and bypass got me vac.

**Comment by ocewot** [comment]
okay well imma close this because it seems like a lot of people disagree cant really get a definitive answer here haha its fine though thank you guys for your input i appreciate it.

**Comment by 1211786712** [comment]
> 好吧，我马上关闭这个，因为似乎很多人不同意在这里无法真正得到明确的答案，哈哈，虽然谢谢你们的投入，但我很感激。

I wonder if it really doesn't work

**Comment by notgoodusename** [comment]
> okay well imma close this because it seems like a lot of people disagree cant really get a definitive answer here haha its fine though thank you guys for your input i appreciate it.

ALWAYS use a vac bypass, dont listen to arthures, VAC bypass works fine, been using a detected injector for 2 months and its working fine

**Comment by arthures11** [comment]
are yo

> > okay well imma close this because it seems like a lot of people disagree cant really get a definitive answer here haha its fine though thank you guys for your input i appreciate it.
> 
> ALWAYS use a vac bypass, dont listen to arthures, VAC bypass works fine, been using a detected injector for 2 months and its working fine

are you sure its not bannable? theres no other reason for me to get vac then, account was pure, only used the bypass LOADER

**Comment by HowToMakeFaceitAB** [comment]
> > > > > > > > > > > 不要使用它，修补和 vac 禁止
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 什么是补丁？
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 显然旁路本身已被修补，没有其他解释为什么 acc 会被 vacbanned，只使用了旁路。您可以在新鲜蒸汽 acc 上自行测试
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 您的帐户还是其他人？
> > > > > > > 
> > > > > > > 
> > > > > > > 我的，我的朋友也是
> > > > > > 
> > > > > > 
> > > > > > 你用的是哪个注射器？（使用旁路时）
> > > > > 
> > > > > 
> > > > > 旧的CSGHOST v3.1，我和bypass一起用了大约1/2年，从未被禁止，现在它改变了
> > > > 
> > > > 
> > > > You mean VAC bannable didn't actually work, did you?
> > > 
> > > 
> > > Yes, it DOES NOT work anymore. If you think i'm wrong you can check it by yourself on fresh steam account, use the bypass and see by yourself if acc gets vac within a week or so.
> > 
> > 
> > You are wrong, it does work.
> 
> so did you test it or what makes you so confident?

I have indeed tested it. several times.

**Comment by HowToMakeFaceitAB** [comment]
And it works perfectly fine. Personal experience
