### ISSUE TITLE
Anyone got a working Anti-Aim fix?

### ISSUE THREAD

**Issue by AhmedtHvH** [danielkrupinski/Osiris#3426]
I know someone used to have it but its outdated now. Also no, I do not know how to code my own. Thanks!

**Comment by notgoodusename** [comment]
You can find one on [OsirisAndExtra](https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Hacks/AntiAim.cpp)

**Comment by AhmedtHvH** [comment]
> It's a legit cheat not hvh

Yes but it has rage features and it would be fun to use them.

**Comment by AhmedtHvH** [comment]
> You can find one on [OsirisAndExtra](https://github.com/notgoodusename/OsirisAndExtra/blob/main/Osiris/Hacks/AntiAim.cpp)

tyty

**Comment by Frouk3** [comment]
Close the issue if it got solved
