### ISSUE TITLE
Adding all skins to Inventory Changer

### ISSUE THREAD

**Issue by ocewot** [danielkrupinski/Osiris#3429]
would be cool if all skins were added to inventory changer not just the ones that are possible. 
like doppler on an awp (example)
this is how the skinchanger used to work before the update to inventory changer. also if anyone is willing to help out id try adding it myself but im a brain ded paster maybe its complex i dont really know..

**Comment by Metaphysical1** [comment]
you can edit config file and add custom paintkit

**Comment by ocewot** [comment]
> you can edit config file and add custom paintkit
![0f450ea5052a18e6ec3a2e2604db5c4d](https://user-images.githubusercontent.com/63646551/144527034-a749843b-e807-4500-9a74-8409ea958a07.png)
what am i doing wrong then it doesnt seem to work its just blank in game

**Comment by linuxer9** [comment]
> > you can edit config file and add custom paintkit
> > ![0f450ea5052a18e6ec3a2e2604db5c4d](https://user-images.githubusercontent.com/63646551/144527034-a749843b-e807-4500-9a74-8409ea958a07.png)
> > what am i doing wrong then it doesnt seem to work its just default in game

paint kit name is useless it's not even used by the cheat, its only purpose is to let you know where is the item in config file.
you should change paintkit **number** you can get paintkit number from sites like csgostash https://csgostash.com/skin/782/Karambit-Gamma-Doppler

**Comment by ocewot** [comment]
> > > you can edit config file and add custom paintkit
> > > ![0f450ea5052a18e6ec3a2e2604db5c4d](https://user-images.githubusercontent.com/63646551/144527034-a749843b-e807-4500-9a74-8409ea958a07.png)
> > > what am i doing wrong then it doesnt seem to work its just default in game
> 
> paint kit name is useless it's not even used by the cheat, its only purpose is to let you know where is the item in config file. you should change paintkit **number** you can get paintkit number from sites like csgostash https://csgostash.com/skin/782/Karambit-Gamma-Doppler

the paint kit id 416 is doppler though not sure if im doing something wrong.. im confused
![277ec147e7e789fd746abb6c43cc74ae](https://user-images.githubusercontent.com/63646551/144530788-55d031bb-3ef2-4c56-98e5-150b4c12cfb5.png)
gh

**Comment by Metaphysical1** [comment]
sorry I tested this out and it didn't work apparently,
the script puts paint kit index of each weapon separate, you can't use paintkit of another weapon, unless you hack the code, but even then I don't think the game would accept this custom weapon.
here is a simple solution, get the latest build of osiris with skin changer, and update it, it shouldn't be that difficult
https://github.com/danielkrupinski/Osiris/releases/tag/pre-inventory-changer

**Comment by ocewot** [comment]
> sorry I tested this out and it didn't work apparently, the script puts paint kit index of each weapon separate, you can't use paintkit of another weapon, unless you hack the code, but even then I don't think the game would accept this custom weapon. here is a simple solution, get the latest build of osiris with skin changer, and update it, it shouldn't be that difficult https://github.com/danielkrupinski/Osiris/releases/tag/pre-inventory-changer

alright yea. i was just making a suggestion because ive seen other cheats with inventory changer and custom skins. i have a build of osiris that has the older skinchanger ill just use that. thanks for the help anyways i appreciate it

**Comment by Metaphysical1** [comment]
I tested this code which should add deagle with gamma doppler skin, it doesn't work, the game just displays blank square like this
https://imgur.com/9iHZJy5
```
// const auto itemIndex = StaticData::getItemIndex(WeaponId::Deagle, 1090); //deagle with ocean drive skin "works!"
const auto itemIndex = StaticData::getItemIndex(WeaponId::Deagle, 1121); // deagle with glock gamma doppler skin "doesn't work"
DynamicSkinData dynamicData;
dynamicData.wear = .1337f;
dynamicData.seed = 137;
dynamicData.statTrak = 1337;
auto dynamicDataIdx = Inventory::emplaceDynamicData(std::move(dynamicData));
Inventory::addItemAcknowledged(itemIndex, dynamicDataIdx);
```
so there's no way the game will accept custom skins in inventory, it was working in skin changer because the script applied skins differently by forcing "fallbackpaintkit" value and item index to -1 so the game displays skin in "fallbackpaintkit".

the current inventory changer has a skin changer but it just maps item index to the item index of the skin equipped in inventory (i.e. our false inventory).
so here is an idea: add option of "custom paintkit", when the cheat sees this custom paintkit field , it applies skin by old method "fallbackpaintkit".

**Comment by ocewot** [comment]
> 

good idea thanks for looking into this man ;)
