### ISSUE TITLE
Some Suggestions to optimize the logic

### ISSUE THREAD

**Issue by Bywnb** [danielkrupinski/Osiris#343]
I'm Chinese. I dont speak English very well. Sorry.I would like to suggest that when you choose all ,you cant choose visible or occluded,when you choose visible or occluded ,you cant choose all in glow,chams and esp

**Comment by danielkrupinski** [comment]
"All" overrides both "visible" and "occluded" settings.

**Comment by Bywnb** [comment]
> "All" overrides both "visible" and "occluded" settings.

I mean that when you choose "All",you can still choose "visible" and "occluded".Then someone will be puzzled

**Comment by danielkrupinski** [comment]
I will left this as is.
