### ISSUE TITLE
No eye traces?

### ISSUE THREAD

**Issue by Ativ3k** [danielkrupinski/Osiris#3431]
There is no option [Eye traces](https://github.com/danielkrupinski/Osiris/blob/7b43221eee5011af2ff4bfc7becd946f3f09216a/README.md?plain=1#L98)?
![image](https://user-images.githubusercontent.com/63321725/144727602-093eec82-0bb9-498d-a05a-e16a2a1210d6.png)

**Comment by ReShout876** [comment]
I remember when I firstly used Osiris, that build had eye tracers, I guess it was a build made by someone else.

**Comment by Ativ3k** [comment]
And no health, only health bar?
