### ISSUE TITLE
csgo update crashing (failed to load pattern #12)

### ISSUE THREAD

**Issue by ocewot** [danielkrupinski/Osiris#3435]
pretty sure osiris is not working now i got failed to load pattern 12 or something

**Comment by 2933968621** [comment]
try modify clearHudWeapon pattern to "\x55\x8B\xEC\x51\x53\x56\x8B\x75\x08\x8B\xD9\x57\x6B\xFE\x34"

**Comment by ocewot** [comment]
> try modify clearHudWeapon pattern to "\x55\x8B\xEC\x51\x53\x56\x8B\x75\x08\x8B\xD9\x57\x6B\xFE\x34" (WIN32)

ur a fkin legend <3 i love you

**Comment by alucard12345678** [comment]
how?

**Comment by ocewot** [comment]
> how?

Memory.CPP

**Comment by alucard12345678** [comment]
sorry, i'm new. i don't understand. please help. thanks

**Comment by 2933968621** [comment]
> sorry, i'm new. i don't understand. please help. thanks

#3437

**Comment by Ni1kko** [comment]
omg do you actually need this much help wow...... he explained it good enough, if you don't have basic skill in c++ or working with memory maybe don't download source :/ change this pattern is memory.cpp like this -> https://github.com/Ni1kko/Spatial/commit/9b2d4cbf57fb3cd919ee05acf728464123145889 

or if still to much just download my release https://github.com/Ni1kko/Spatial/releases/tag/SpatialV1.2

**Comment by ocewot** [comment]
> sorry, i'm new. i don't understand. please help. thanks

go to Source files filter (folder) click Memory.cpp press ctrl f (search) type clearHudWeapon in the search replace the numbers there with these "\x55\x8B\xEC\x51\x53\x56\x8B\x75\x08\x8B\xD9\x57\x6B\xFE\x34" compile build

**Comment by alucard12345678** [comment]
i finally got. i downloaded the neccesary files. thanks.

**Comment by Ni1kko** [comment]
Just because im bored here is a video showing how to update it for anyone struggling and proof its working https://youtu.be/HqZHMVg7FKI i dont make video so no audio but 1080p ;)

**Comment by hungdz1234** [comment]
> 34

Hi. Can you kindly teach me how do you know that changing this will fix the error?

**Comment by Ni1kko** [comment]
> > 34
> 
> Hi. Can you kindly teach me how do you know that changing this will fix the error?

well as you can see by changing the pattten the cheat no longer crashes so with that being said im happy to say that has resolved the crashing but it may need other tweaks still i have not tested any further than i have in that video as im watching a movie and going to bed. 
 
https://youtu.be/HqZHMVg7FKI

**Comment by hungdz1234** [comment]
> > > 34
> > 
> > 
> > Hi. Can you kindly teach me how do you know that changing this will fix the error?
> 
> well as you can see by changing the pattten the cheat no longer crashes so with that being said im happy to say that has resolved the crashing but it may need other tweaks still i have not tested any further than i have in that video as im watching a movie and going to bed.
> 
> https://youtu.be/HqZHMVg7FKI

I know how to do this. But I don't know how you know that changing x2C to x34?

**Comment by hungdz1234** [comment]
> try modify clearHudWeapon pattern to "\x55\x8B\xEC\x51\x53\x56\x8B\x75\x08\x8B\xD9\x57\x6B\xFE\x34" (WIN32)

Bro, how you know that changing x2C to x34 will solve the problem? Why not x35 or x36

**Comment by Ni1kko** [comment]
> > > > 34
> > > 
> > > 
> > > Hi. Can you kindly teach me how do you know that changing this will fix the error?
> > 
> > 
> > well as you can see by changing the pattten the cheat no longer crashes so with that being said im happy to say that has resolved the crashing but it may need other tweaks still i have not tested any further than i have in that video as im watching a movie and going to bed.
> > https://youtu.be/HqZHMVg7FKI
> 
> I know how to do this. But I don't know how you know that changing x2C to x34?

Debug logging till you find your error then you can fix it lol and if you mean for how do i know the new offsets ect i use hazedumper

**Comment by Ni1kko** [comment]
> pattern

the '2c' & '34' represent the memory address its how we find vars ect in memory i'm trying to explain this the best i can but im not amazing with all this i just have comon sense and alot of free time to learn what i dont know. google is your best friend ask it he questions you have about memory :)

**Comment by Ni1kko** [comment]
> > try modify clearHudWeapon pattern to "\x55\x8B\xEC\x51\x53\x56\x8B\x75\x08\x8B\xD9\x57\x6B\xFE\x34" (WIN32)
> 
> Bro, how you know that changing x2C to x34 will solve the problem? Why not x35 or x36

the '2c' & '34' represent the memory address its how we find vars ect in memory i'm trying to explain this the best i can but im not amazing with all this i just have comon sense and alot of free time to learn what i dont know. google is your best friend ask it he questions you have about memory :)

**Comment by hungdz1234** [comment]
> > > > > 34
> > > > 
> > > > 
> > > > Hi. Can you kindly teach me how do you know that changing this will fix the error?
> > > 
> > > 
> > > well as you can see by changing the pattten the cheat no longer crashes so with that being said im happy to say that has resolved the crashing but it may need other tweaks still i have not tested any further than i have in that video as im watching a movie and going to bed.
> > > https://youtu.be/HqZHMVg7FKI
> > 
> > 
> > I know how to do this. But I don't know how you know that changing x2C to x34?
> 
> Debug logging till you find your error then you can fix it lol and if you mean for how do i know the new offsets ect i use hazedumper

hazedumper offsets quite different from Osiris.

**Comment by Ni1kko** [comment]
> hazedumper offsets quite different from Osiris.

Are you sure? im not sure i use an edited version from corsair.wtf, but regardless you would be able to use for testing as you can check that module and signature is found on that pattern and if you dont know how to get pattern you can use things like cheat engine ect, Actually are you trying to find out info or just be dick? you seem to know so enlighten me, i want to learn more.

**Comment by hungdz1234** [comment]
> > hazedumper offsets quite different from Osiris.
> 
> Are you sure? im not sure i use an edited version from corsair.wtf, but regardless you would be able to use for testing as you can check that module and signature is found on that pattern and if you dont know how to get pattern you can use things like cheat engine ect, Actually are you trying to find out info or just be dick? you seem to know so enlighten me, i want to learn more. im too tired for this.... night!

Just tryin to find out info bro

**Comment by 2933968621** [comment]
> > try modify clearHudWeapon pattern to "\x55\x8B\xEC\x51\x53\x56\x8B\x75\x08\x8B\xD9\x57\x6B\xFE\x34" (WIN32)
> 
> Bro, how you know that changing x2C to x34 will solve the problem? Why not x35 or x36

umm, i use imhex.

**Comment by Ni1kko** [comment]
> Just tryin to find out info bro

okay bro

**Comment by stew-iwnl** [comment]
Will you lose your configs if you do this?

**Comment by Ni1kko** [comment]
> Will you lose your configs if you do this?

By doing what? the fix? or using another version?

Owner has updated main repo now anyway so this issue should have been closed....

**Comment by apkx27** [comment]
> > Will you lose your configs if you do this?
> 
> By doing what? the fix? or using another version?
> 
> Owner has updated main repo now anyway so this issue should have been closed....

i tried the updated dll you posted both versions it still crashes with no error code, was able to get the old osiris to inject about 1/30 tries it will work rarely with failed to find pattern #12 error

**Comment by Ni1kko** [comment]
Must be your injector or somthing on your side mate... I have a few friends who also use my version....
Here is The latest update with injector in .zip file https://github.com/Ni1kko/Spatial/releases/tag/SpatialV1.3

screenshot proof im currently working on it and have 0 issues with loading or crashing with my version or with osiris main build no issues you maybe have thought you replaced dll maybe still the old one?
 
Try again, but that issue is sorted my firend :) 
https://i.imgur.com/UVpk8nh.jpeg

**Comment by YMY1666527646** [comment]
i Unable to inject

**Comment by apkx27** [comment]
> Must be your injector or somthing on your side mate... I have a few friends who also use my version.... Here is The latest update with injector in .zip file https://github.com/Ni1kko/Spatial/releases/tag/SpatialV1.3
> 
> screenshot proof (https://i.imgur.com/UVpk8nh.jpeg)
> 
> im currently working on my version and have 0 issues with loading or crashing with my version or with osiris main build no issues you maybe have thought you replaced dll maybe still the old one?
> 
> Try again, but that issue is sorted my firend :)

i tried the old dll that one works 1/30 times with pattern 12 error (1330 kb)

the dll in the zip 1350 kb crashes
the newest updated one that isnt in the zip is 1360 kb that one crashes too

process name csgo.exe pid 3932: trid: 616

**Comment by YMY1666527646** [comment]
> > 必须是你的注射器或你的同伴上的东西...我有几个朋友也使用我的版本....这是[.zip文件](https://github.com/Ni1kko/Spatial/releases/tag/SpatialV1.3)https://github.com/Ni1kko/Spatial/releases/tag/SpatialV1.3 中注入器的最新更新
> > 屏幕截图证明 （https://i.imgur.com/UVpk8nh.jpeg)
> > im目前正在处理我的版本，并且有0问题加载或崩溃与我的版本或osiris主构建没有问题，你可能认为你替换了dll也许仍然是旧的？
> > 再试一次，但这个问题已经解决了我的火:)
> 
> 我尝试了旧的dll，一个工作1/30次与模式12错误（1330 kb）
> 
> zip 中的 dll 1350 kb崩溃 了不在 zip 中的最新更新的 dll 是 1360 kb，一个也会崩溃
> 
> 它说"成功"过程名称 csgo.exe pid 3932： trid： 616
> 
> 崩溃， 我再试 30 次与这个 1350 kb dll

Thank you very much. I've injected it

**Comment by Ni1kko** [comment]
> Thank you very much. I've injected it

No problem, i made some updates since then... https://github.com/Ni1kko/Spatial/releases/tag/V1.3r2

**Comment by YMY1666527646** [comment]
> > Thank you very much. I've injected it
> 
> No problem, i made some updates since then... https://github.com/Ni1kko/Spatial/releases/tag/V1.3r2

Why is there no inventory changer？

**Comment by YMY1666527646** [comment]
> > > 谢谢。我已经注射了它
> > 
> > 
> > 没问题，从那时起我做了一些更新...https://github.com/Ni1kko/Spatial/releases/tag/V1.3r2
> 
> 为什么没有库存更换器？

sorry! I misread it

**Comment by YMY1666527646** [comment]
> > > > 谢谢。我已经注射了它
> > > 
> > > 
> > > 没问题，从那时起我做了一些更新...https://github.com/Ni1kko/Spatial/releases/tag/V1.3r2
> > 
> > 
> > 为什么没有库存更换器？
> 
> sorry! I misread it

There is no option Eye traces?

**Comment by apkx27** [comment]
> > Thank you very much. I've injected it
> 
> No problem, i made some updates since then... https://github.com/Ni1kko/Spatial/releases/tag/V1.3r2

new version still crashes with shtreeba tried many times again. new csghost injector is buggy as hell so imma try that next with osiris
old fluidaim from months ago +shtreeba esp still works but aimbot/trigger doesnt, no crashes

**Comment by Ni1kko** [comment]
> > > Thank you very much. I've injected it
> > 
> > 
> > No problem, i made some updates since then... https://github.com/Ni1kko/Spatial/releases/tag/V1.3r2
> 
> new version still crashes with shtreeba tried many times again. new csghost injector is buggy as hell so imma try that next with osiris old fluidaim from months ago +shtreeba esp still works but aimbot/trigger doesnt, no crashes

Mate its working disable your antivirus i have been using Spatial v1.3r2 for the last 5-6hrs no issues, same with my friends, tested on windows 10 pro and windows 11 pro.  and what do you mean '+shtreeba esp still works but aimbot/trigger doesnt' Shtreeba is to used to inject Spatial or osiris https://github.com/mdilai/Shtreeba#usage
