### ISSUE TITLE
Failed to find pattern #12

### ISSUE THREAD

**Issue by Koibeta** [danielkrupinski/Osiris#3436]
Hi i believe that csgo just updated on the 10th of December so im not sure if its the update that is causing this error (failed to find pattern #12), but if it has nothing to do with the update then could someone suggest to me how to fix it please ;) it would be greatly appriciated. I have tried to delete all files related to osiris and recompiled it again, but it didn't work and I have tried to verify the integrity of the files and the error still appears.

**Comment by 2933968621** [comment]
#3435 look this

**Comment by Koibeta** [comment]
where can i find that im rlly sorry im not good in those kinda stuff

**Comment by 2933968621** [comment]
what you need? source or dll file?

**Comment by Ni1kko** [comment]
https://github.com/danielkrupinski/Osiris/issues/3435#issuecomment-991472563

**Comment by Koibeta** [comment]
> Go here i have posted dll\injector\vac bypass and posted a video of how to fix yourself [#3435 (comment)](https://github.com/danielkrupinski/Osiris/issues/3435#issuecomment-991472563)

ohhh thank you so much I found it thanks @2933968621 and @Ni1kko

**Comment by Koibeta** [comment]
the error dosen't come out anymore :)

**Comment by mxez** [comment]
On linux we are getting error "Failed to find PanoramaUIEngine001 interface." and "Failed to find pattern #18"

**Comment by mxez** [comment]
btw they also broke bones on linux LOL
![2021-12-11T1209564101853020300](https://user-images.githubusercontent.com/86112382/145671553-221da219-4dd9-417d-88b0-c8c3a761b4d6.png)
