### ISSUE TITLE
How to install Osiris on Arch-Based/Manjaro? 

### ISSUE THREAD

**Issue by czSmoG** [danielkrupinski/Osiris#3438]
I moved from ubuntu-based  to arch-based distros.

Since ubuntu-based distros actually sucks, or they arent stable.
My quastion/Issue is how do i run Osiris on Arch Linux.

Im not a developer or something, im not on level github average user. But i tried to find anything that could fix my problem/issue.

Distro: Manjaro Pahvo Gnome 21.1.6

**Comment by mxez** [comment]
```
sudo pacman -Syu git gdb cmake make gcc wget
git clone https://github.com/danielkrupinski/Osiris
cd Osiris && cmake -D CMAKE_BUILD_TYPE=Release ./

make -j $(nproc --all)
```

After compiling osiris you have to inject it. You can use this script to do it.
`wget https://pastebin.com/raw/P0GUvkis && mv P0GUvkis attach && chmod +x attach`

Now when you are ready to inject use this command:
`sudo ./attach`
(Have to be done in Osiris directory)

**Comment by JustaMax18** [comment]
can't make anything work cuz of /usr/bin/env bash/r: no such file or dir.... error comes up every time doesn't matter do i try to use -vS or other types
