### ISSUE TITLE
About thirdperson

### ISSUE THREAD

**Issue by 2933968621** [danielkrupinski/Osiris#3439]
thirdperson is working?
idk why i can't use thirdperson, I don't know it's my own problem or the latest csgo update

**Comment by ThebestkillerTBK** [comment]
valve did a lot to this update, so thirdperson offset also broken

**Comment by 2933968621** [comment]
> valve did a lot to this update, so thirdperson offset also broken

ok i know, thanks

**Comment by ThebestkillerTBK** [comment]
reopen the commit so people can notice and fix it

**Comment by 2933968621** [comment]
> reopen the commit so people can notice and fix it

i think #3433 is same problem
