### ISSUE TITLE
Can you hook findMDL?

### ISSUE THREAD

**Issue by NexSqaud** [danielkrupinski/Osiris#344]
Can you hook findMDL function? I tried to hook it myself, but [result](https://imgur.com/a/AfuDtiw) leaves much to be desired.
Some info about this function:
fastcall function
parameters void* ecx, void* edx, char* filePath
return MDLHandle (unsigned short)
index 10
MDLCache004 interface in datacache.dll
parameters for original function void* ecx, char* filePath

**Comment by danielkrupinski** [comment]
Are you trying to replace model or just call original function?

**Comment by effex1337** [comment]
The only use of findmdl i know rn is to change the model.
Fron the result he showed he probably hooked it but its not displayed correctly.
Probably issue with the file location maybe.

**Comment by NexSqaud** [comment]
@danielkrupinski I'm tried just hook function and call original function from hooked
```c++
static MDLHandle __fastcall findMDL(void* ecx, void* edx, char* path) noexcept
{
	return hooks.mdlCache.callOriginal<MDLHandle, void*, char*>(10, ecx, path);
}
```

**Comment by NexSqaud** [comment]
Okay, problem solved.
```c++
static MDLHandle __fastcall findMDL(void* ecx, void* edx, char* path) noexcept
{
	return hooks.mdlCache.callOriginal<MDLHandle, char*>(10, path);
}
```

**Comment by danielkrupinski** [comment]
That's strange it didn't crash due to stack misalignment. You can make hook use `__stdcall` convention and remove ecx and edx arguments.

**Comment by mercyples** [comment]
Hello @NexSqaud 
I was trying to hook findmdl as well but i couldn't.
My progress till now:
Hooks.cpp
`
typedef MDLHandle_t(__thiscall* iFindMdl)(void*, char*);
iFindMdl oFindMDL;
MDLHandle_t __fastcall hkFindMDL(void*, void*, char*);

static MDLHandle __fastcall mdlCache(void* ecx, void* edx, char* path) noexcept
{
	return hooks.mdlCache.callOriginal<MDLHandle, char*>(10, path);
}

MDLHandle_t __fastcall hkFindMDL(void* ecx, void* edx, char* FilePath)
{

	if (strstr(FilePath, "ak47.mdl"))
		return oFindMDL(ecx, "models/weapons/v_cod_ak117.mdl");

	return oFindMDL(ecx, FilePath);
}`

Hooks.cpp in Hooks::Hooks
`	mdlCache.hookAt(10, mdlCache);
`

Interfaces.h
`       class MDLHandle;
	MDLHandle* ModelCache;
`

Interfaces.cpp
`	ModelCache = find<MDLHandle>(L"datacache", "MDLCache004");
`
Can you please help me out. Thanks in advance

**Comment by NexSqaud** [comment]
@mercyples delete typedef, iFindMdl oFindMDL
```c++
static MDLHandle __stdcall findMDL(char* path) noexcept
{
    if(strstr(path, "ak47"))
        return hooks.mdlCache.callOriginal<MDLHandle, char*>(10, "path to model");
    return hooks.mdlCache.callOriginal<MDLHandle, char*>(10, path);
}
```

**Comment by JHompesc-dev** [comment]
> @mercyples delete typedef and iFindMdl oFindMDL
> 
> ```c++
> static MDLHandle __stdcall findMDL(char* path) noexcept
> {
>     if(strstr(path, "ak47"))
>         return hooks.mdlCache.callOriginal<MDLHandle, char*>(10, "path to model");
>     return hooks.mdlCache.callOriginal<MDLHandle, char*>(10, path);
> }
> ```

The char*'th index of the vtable? You using a devine intellect table or smth?

hooks.mdlCache.callOriginal<MDLHandle, 10>(path);

**Comment by xAkiraMiura** [comment]
NexSqaud commented on 29 Jul 2019 •
 JHompesc-dev commented 9 hours ago •

according to my calculations, you just necro'd.
the issue is 8 months old and closed, no reason to comment.
