### ISSUE TITLE
Ugly skins and crushed with injection.

### ISSUE THREAD

**Issue by relativist** [danielkrupinski/Osiris#3440]
I play on linux. After last CS update player skins looks ugly. and doesn't inject Osiris, game crushed. I think we need wait new update.

**Comment by ReShout876** [comment]
https://github.com/ValveSoftware/csgo-osx-linux/issues/2873

**Comment by henrydatei** [comment]
I have the same issues. I play on linux and the game crashes immediately after injection.

**Comment by ReShout876** [comment]
> I have the same issues. I play on linux and the game crashes immediately after injection.

Do what I wrote above...

**Comment by relativist** [comment]
@ReShout876 thank you! It helped me!
