### ISSUE TITLE
Third person not working

### ISSUE THREAD

**Issue by 888195uywiurh** [danielkrupinski/Osiris#3442]

**Comment by Miller005** [comment]
input struct update
@_@

**Comment by ThebestkillerTBK** [comment]
yeah, struct update like usercmd also updated

**Comment by Directorware** [comment]
user cmd too? I didnt see any changes in ida

**Comment by danielkrupinski** [comment]
Fixed (a2d01b0d11bfedf372db1540d9f95a7731db59f5)
