### ISSUE TITLE
Cannot use old config

### ISSUE THREAD

**Issue by alkpersonaluse** [danielkrupinski/Osiris#3444]
Why everytime i use new osiris.dll from the new update, i can't use my old config?? Do i really have to add all inventory all over again?? Or is there another way around??

**Comment by Boomer118** [comment]
Osiris saves ur configs somewhere else, documents folder i guess, don't remember. They are in json format and can be deleted only if you manually go there, or overwrite these inside cheat injected while playing. Never faced such issue, as it is independent of the DLLs injected as updates come up.

**Comment by alkpersonaluse** [comment]
i mean i can use it, as to change the inventory, but when i tried to play, it always crashes. The only way i know how to fix it is to redo all the inventory addition all over again one by one. I'm just wondering if there's another way around it
