### ISSUE TITLE
Can't disable anti-aim when game in freeze period or player is frozen

### ISSUE THREAD

**Issue by Frouk3** [danielkrupinski/Osiris#3445]
I can't do that, i just added a netvar in entity`NETVAR(freezePeriod, "CCSGameRulesProxy", "m_bFreezePeriod", bool)`
In anti-aim i typed `if (localPlayer->freezePeriod())
return;`
But it didn't give anything
Even tho with player flag FL_FROZEN (1<<5)

**Comment by notgoodusename** [comment]
You need to use `memory->gameRules`, so it ends up like this `(*memory->gameRules)->freezePeriod()`

**Comment by Frouk3** [comment]
> You need to use `memory->gameRules`, so it ends up like this `(*memory->gameRules)->freezePeriod()`

How to made it with player flag?

**Comment by notgoodusename** [comment]
> How to made it with player flag?

`(localPlayer->flags() & FL_FROZEN)`

**Comment by Frouk3** [comment]
> > How to made it with player flag?
> 
> `(localPlayer->flags() & FL_FROZEN)`

anti-aim stop working when i use this

**Comment by notgoodusename** [comment]
> anti-aim stop working when i use this

how do you use it?

**Comment by Frouk3** [comment]
> > anti-aim stop working when i use this
> 
> how are you using it?

`#define FL_FROZEN (1<<5)`

`if (localPlayer->flags() & FL_FROZEN) { //not accurate because i'm aren't at computer
return;
}`

**Comment by notgoodusename** [comment]
FL_FROZEN isnt equal to 1<<5, its  equal 1<<6
`#define FL_FROZEN (1<<6)`
also checking for this only works an the end of the round when the game freezes you

**Comment by Frouk3** [comment]
it says  "identificator "memory" not defined"

**Comment by notgoodusename** [comment]
Just do
`if (localPlayer->flags() & (1 << 6)) {  return; }`

**Comment by Frouk3** [comment]
k thank you
