### ISSUE TITLE
Aimbot issue

### ISSUE THREAD

**Issue by retarded-person** [danielkrupinski/Osiris#3446]
While using aimbot, it messes around with your movement. Sometimes it works perfectly, other times moving backwards sends you sideways. I am using the latest osiris build with no modifications.

**Comment by Frouk3** [comment]
Are you using silent aim?

**Comment by retarded-person** [comment]
Yeah

**Comment by Frouk3** [comment]
Enable fix movement in misc it might help you

**Comment by retarded-person** [comment]
I researched more into it and that is probably the issue, gonna try rn
