### ISSUE TITLE
Deagle spin animation

### ISSUE THREAD

**Issue by Koibeta** [danielkrupinski/Osiris#3451]
This is not that big of a deal but I really hope someone could help me with it, so when i inspect the deagle with the deagle spin module on, the animation does not do the complete spin at the last spin, instaid, it just goes back to holding the gun. Im not sure if it just me but yea. I was hoping someone could teach me how to fix that animation bug

**Comment by 2933968621** [comment]
all(maybe) cheat has this problem

**Comment by Koibeta** [comment]
ohh is there anyway to fix it?

**Comment by floydGG** [comment]
Just hold mouse2 while inspecting ur gun

**Comment by Koibeta** [comment]
omg it work

> Just hold mouse2 while inspecting ur gun

omg it works now thank you so much for your help @floydGG and @2933968621

**Comment by Koibeta** [comment]
ohh ya and do you know where to find the code for the deagle spinner animation??

**Comment by notgoodusename** [comment]
> ohh ya and do you know where to find the code for the deagle spinner animation??

https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Netvars.cpp#L42-L43

**Comment by Koibeta** [comment]
thanks bro
