### ISSUE TITLE
Auto shot should shoot through penetrable walls.

### ISSUE THREAD

**Issue by diekunstderfuge** [danielkrupinski/Osiris#3452]
If "Visible only" is unchecked and "Auto shot" is checked, there should be automatic fire through penetrable walls.

Why that doesn't happen?

**Comment by Frouk3** [comment]
Autoshot based on aimbot fov

**Comment by prontodos** [comment]
> If "Visible only" is unchecked and "Auto shot" is checked, there should be automatic fire through penetrable walls.
> 
> Why that doesn't happen?

Yes this should happen. Because of "visible only" set to off. or does it work ?

**Comment by ReShout876** [comment]
Common Linux autowall issue.

**Comment by diekunstderfuge** [comment]
**Killshot** was preventing **autowall** from all weapons except sniper rifles.

Disabling it solved the problem for me.
