### ISSUE TITLE
Nomad Knife animation suddenly ending

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#3459]
Hi,
The Nomad Knife has a rare animation where the player cuts their finger. Unfortunately, the animation doesn't play correctly and ends abruptly. This happens with Osiris and nSkinz. I'm not sure what causes this, I'm suspecting it's because the anim duration is not synced with the default knife anim. Could someone look into this?

**Comment by KurastikO** [comment]
unfortunately, this probably can't be fixed unless you have a legit classic/nomad knife. Their animations are not synced to the default one and therefore it cuts off. IDK if this can be fixed or not but I'm sure you have to wait a very long time to get this fxed
