### ISSUE TITLE
Add Troll vote kick (included how it works)

### ISSUE THREAD

**Issue by effex1337** [danielkrupinski/Osiris#346]
Basically how it works is your add a bunch of /n aka newlines before and after your name.
For example:/n/n/n.....press f1 for a free skin/n/n/n....
You change your name to that then try to kick someone.
I tried doing this but the name just wouldnt change.

**Comment by Shaxzy** [comment]
Wasn’t this patched a month ago?

**Comment by effex1337** [comment]
wait what i didn't know that :(

**Comment by woah1337** [comment]
No I don't think it was patched

**Comment by hydemods** [comment]
No it still works

**Comment by tirziz** [comment]
Cool , but still no C4 timer yet :(

**Comment by EGTLoneWolf** [comment]
isn't it lua?

**Comment by effex1337** [comment]
Lua is simply a feature extender if the cheat doesnt have the feature by default.

**Comment by effex1337** [comment]
> No it still works
> Edit: i have the code if you wanna try and paste it in.

Sure

**Comment by woah1337** [comment]
You need to first change your name to newlines then it will go blank then you can do the name glitch.

**Comment by hydemods** [comment]
> > No it still works
> > Edit: i have the code if you wanna try and paste it in.
> 
> Sure

https://pastebin.com/zfpVtSUw
From spuri legit. Whole namespam function. just in case you wanted anything else. Fake vote kick is the one with a bunch on "/n"

**Comment by effex1337** [comment]
Well that didnt work as the name changer function wasn't working.
