### ISSUE TITLE
updating Osiris

### ISSUE THREAD

**Issue by prontodos** [danielkrupinski/Osiris#3464]
How do we update Osiris ?

**Comment by diekunstderfuge** [comment]
What do you mean? Just download the source and compile it again everytime Daniel updates.

**Comment by prontodos** [comment]
Yes that's what I meant.
Some hacks provide an ./update feature apparently this does not. 
It's no biggie though. 

Thanks.

**Comment by Ni1kko** [comment]
you could create a workflow and have it build after each commits build checks passes ;-)

**Comment by ReShout876** [comment]
@prontodos 
Firstly check if it got any updates
###### Go to the Osiris' directory if you didn't do it already
`git pull`

If it shows that stuff got changed, then
`cd Release && make -j $(nproc --all)`
Let it recompile and you are good to go.

**Comment by prontodos** [comment]
good stuff !!
thank you !!

**Comment by Frouk3** [comment]
> good stuff !! thank you !!

so you must to close the issue if it got solved
