### ISSUE TITLE
ProtobufReader.h crash

### ISSUE THREAD

**Issue by 1337Proxy1337** [danielkrupinski/Osiris#3466]
error line 40 on protobufreader.h file. 
leads to a crash after approximately 2 rounds. 

Assertion failed!

Expression: (data[offset] & 0x80) == 0 && 'Only one-byte varints are supported!

FIX: don't use inventory changer.

**Comment by 1337Proxy1337** [comment]
Don't know if it will help but it crashes more frequrently when i alt tab.

**Comment by Vadenez** [comment]
this is happening to me as well.
