### ISSUE TITLE
Crush when inject.

### ISSUE THREAD

**Issue by relativist** [danielkrupinski/Osiris#3469]
Game crushed when inject . Within update:
//constexpr auto PANORAMA_DLL = WIN32_LINUX("panorama", "panorama_gl_client.so");

it worked find with:
constexpr auto PANORAMA_DLL = WIN32_LINUX("panorama", "panorama_client.so");

I get all git updates and it crashed at injection. May be only I have this issue?

(When revert this line as before, build and it injected correctly, but crashed when game starts. But it will be next issue)

**Comment by Frouk3** [comment]
what injector do you use?

**Comment by relativist** [comment]
I copy "load.sh" from Fusion and create some changes on load:
https://pastebin.com/zndMQzcL
It works fine and no crush as Fusion can.

**Comment by Frouk3** [comment]
okay so this is linux issue,i can't fix this tho

**Comment by Frouk3** [comment]
> I copy "load.sh" from Fusion and create some changes on load: https://pastebin.com/zndMQzcL It works fine and no crush as Fusion can.

so close the issue if it got solved

**Comment by Frouk3** [comment]
*Crash not the crush

**Comment by Taughtimp2786** [comment]
> I copy "load.sh" from Fusion and create some changes on load: https://pastebin.com/zndMQzcL It works fine and no crush as Fusion can.

@relativist link down
