### ISSUE TITLE
[REQUEST]RCS and Draw Aimbot Fov

### ISSUE THREAD

**Issue by squizzyv9** [danielkrupinski/Osiris#3474]
Can you add RCS and Aimbot Fov

**Comment by Frouk3** [comment]
RCS is already in aimbot but there's no options that will access to the rcs control x and y

**Comment by Frouk3** [comment]
draw aimbot fov #3127

**Comment by squizzyv9** [comment]
Does this feature exist?

**Comment by Frouk3** [comment]
> Does this feature exist?

RCS exists but aimbot fov no

**Comment by squizzyv9** [comment]
Ok, hopefully it will be added.
