### ISSUE TITLE
[REQUEST]Inventory Changer add some things

### ISSUE THREAD

**Issue by Frouk3** [danielkrupinski/Osiris#3477]
Can you add shift+select? Its like choosing files in windows by pressing the first file and then shift+select the last file you want to select,between selections it will chose the items that were between and add the combo box where you can select weapon or item and button that will add all skins to inventory, lets say you select desert eagle,pressed the button and in inventory adds all skins that are belong to the selected weapon or item

**Comment by MyNameIsKodak** [comment]
No.

**Comment by Frouk3** [comment]
and whats is the problem eh?
