### ISSUE TITLE
Add working graffiti?

### ISSUE THREAD

**Issue by Frouk3** [danielkrupinski/Osiris#3478]
Adding graffiti to the inventory and apply to spray it out, it doesn't,there's only spray interface
I guess making this as decal will do it right?

**Comment by skirtsandflirts** [comment]
I actually wanted to make this work but I don't know how I would. I am too inexperienced.
Something like using the engine to make a texture which contains the spray texture and then apply that texture in the world at wherever the user sprayed.
No clue how this will be implemented, though.
