### ISSUE TITLE
Stream proof esp not working on Discord

### ISSUE THREAD

**Issue by contingency1111** [danielkrupinski/Osiris#3482]
is it only supposed to be for obs? when i screenshare cs:go (the window) in discord they can still see my esp so im just wondering

**Comment by skirtsandflirts** [comment]
It should be for any hooks capturing the game window. Make sure you are capturing the game window itself and not your whole screen.

**Comment by Patrixsin** [comment]
for me it works well even with discord, did u choose CS:GO window or whole screen?

**Comment by Liam5750** [comment]
ONLY Esp works. Not glow or chams or anything else

**Comment by Liam5750** [comment]
That could be the issue

**Comment by MarieJoker** [comment]
i am using tracers and box esp and it isnt working
