### ISSUE TITLE
Osiris broke after latest update (1.1.2021 crash)

### ISSUE THREAD

**Issue by BurAndBY** [danielkrupinski/Osiris#3483]
Crashes with "Failed to find VClient018 interface" error. Similar to #1683 update.

![image](https://user-images.githubusercontent.com/48630651/147839896-af82a912-9848-4ec1-8860-ce81cd761947.png)

**Comment by 2933968621** [comment]
why i no new update?

**Comment by sharkzxo** [comment]
bump

**Comment by sharkzxo** [comment]
same problem :/

**Comment by TauCSGO** [comment]
New Year!, I think @danielkrupinski  deserves to celebrate and a break
Tomorrow surely be an update

**Comment by BurAndBY** [comment]
> New Year!, I think @danielkrupinski deserves to celebrate and a break Tomorrow surely be an update

Yes, you are right! Just decided to report this so it will be noticed.

**Comment by danielkrupinski** [comment]
There was no game update on 1/1/2022.

**Comment by BurAndBY** [comment]
Oops, I had some files corrupted. Checking files fixed it
