### ISSUE TITLE
That version of Osiris only has a skin changer

### ISSUE THREAD

**Issue by aibhan** [danielkrupinski/Osiris#3491]

**Comment by csgofever** [comment]
??

**Comment by sharkzxo** [comment]
wtf XDDDDDD

**Comment by aibhan** [comment]
There is only one inventory converter and does not want hacker function~

**Comment by Patrixsin** [comment]
?

**Comment by waffleboycs** [comment]
he has one go search in daniel's repositories 
https://github.com/danielkrupinski/OsirisInventory

**Comment by aibhan** [comment]
> 



> 他可以在 daniel 的存储库中一次性搜索 https://github.com/danielkrupinski/OsirisInventory

This version reports an error and cannot load mode #4 injection. CS displays a question mark

**Comment by thes4ns** [comment]
I mean you can make it yourself ?
