### ISSUE TITLE
cannot find pattern #33

### ISSUE THREAD

**Issue by csgofever** [danielkrupinski/Osiris#3496]
I'm using an older version of Osiris, and I cannot seem to find the reason for this error.
(IDK what pattern the error points to, and call stack doesn't show a thing.)

I've tried debugging but it gives me nothing.
any help would be appreciated.

**Comment by Frouk3** [comment]
> I'm using an older version of Osiris, and I cannot seem to find the reason for this error. (IDK what pattern the error points to, and call stack doesn't show a thing.)
> 
> I've tried debugging but it gives me nothing. any help would be appreciated.

Download a newest version so issue will be solved ¯\_(ツ)_/¯

**Comment by skirtsandflirts** [comment]
https://github.com/danielkrupinski/Osiris/commit/a5c0bb78894c8a9f4783ce80d317e68109c53f83#diff-34a9c35a09c40ac135a0569b50037dec3bec11d693ce239ade9fe7c99625afacR268
This line of code fixes it. Daniel already implemented this fix. If you need to update it manually, there you go.
Pattern #33 refers to that pattern Daniel updated. (cameraThink)
