### ISSUE TITLE
Linux version of this cheat is very unstable

### ISSUE THREAD

**Issue by ReShout876** [danielkrupinski/Osiris#3497]
As I said, it is very unstable. Since the recent update and how the compilation changed made the cheat very unstable. The `.so` size changed from 1.1mb to around 8mb. It crashes randomly. @danielkrupinski please fix, it's getting annoying

**Comment by danielkrupinski** [comment]
There was no changes to building Osiris locally. Make sure you set `CMAKE_BUILD_TYPE` to **Release**.

**Comment by ReShout876** [comment]
@danielkrupinski where/which file has `CMAKE_BUILD_TYPE`, because I didn't found it.

**Comment by ReShout876** [comment]
I did a little change in the workflows file and it seems to be back to normal, normal `.so` size. Thanks Daniel for your help.
