### ISSUE TITLE
Don't mark every method as "noexcept"...

### ISSUE THREAD

**Issue by cyanidee** [danielkrupinski/Osiris#350]
No, it doesn't mean your cheat will never throw an exception LULW.

[noexcept - cppreference.com](https://en.cppreference.com/w/cpp/language/noexcept)
[noexcept specifier - cppreference.com](https://en.cppreference.com/w/cpp/language/noexcept_spec)

https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hacks/SkinChanger.cpp#L29

Here, you don't even check if the `V_UCS2ToUTF8` is a valid pointer, therefore it **may** throw already...

I could find couple more examples, but that just seems pointless, everything that you are doing is not always 100% safe, and therefore might throw an exception.

**Comment by danielkrupinski** [comment]
It means the function is not supposed to throw C++ exceptions. Derefencing null pointer will throw SEH/VEH exception not C++ one.
