### ISSUE TITLE
Osiris constant crash issue, Assertion failed!

### ISSUE THREAD

**Issue by ex4rs** [danielkrupinski/Osiris#3500]
I'm getting a Microsoft Visual C++ Issue that crashes my game and shows up after 3-10 minutes of playing. Here is an image of what happens. Is there a line of code or something I can edit to fix it?
![osiris](https://user-images.githubusercontent.com/97701479/149402248-c1b29d2c-5a80-43f4-9933-2a04a87f2643.jpg)
.

**Comment by csgofever** [comment]
set the build to release not debug

**Comment by AdiNotFound** [comment]
i have same issue and i dont know how to set to realese!

**Comment by peachypeace** [comment]
i set it to release and it works perfectly now thanks for the help btw you press where it says debug press debug and it shows options
