### ISSUE TITLE
"Incremental Load"  what's the effect?

### ISSUE THREAD

**Issue by yxb6846928** [danielkrupinski/Osiris#3505]
I don't understand this function

It's in GUI.cpp.
532 lines

**Comment by danielkrupinski** [comment]
It allows you to load configs that contains only some settings.
Example: Imagine you have multiple configs for aimbot, but one for inventory changer. You can load another aimbot config without affecting inventory changer.

**Comment by yxb6846928** [comment]
https://github.com/danielkrupinski/OsirisInventory
If I only use "inventory changer"
This feature can be removed, right?
