### ISSUE TITLE
add movement functions (edgebug,jumpbug)

### ISSUE THREAD

**Issue by realavast** [danielkrupinski/Osiris#3506]
Hi, can you add edgebug and jumpbug?

**Comment by stealer1337** [comment]
Im dont really know how to code or anything like that. But maybe we can use some movement paste cheats sources to add the same features to osiris? (edgebug, jumpbug, autostrafe bind, etc) I mean, it would be really cool but i dont know if it is posible.

**Comment by csgofever** [comment]
Add me on discord, I can help you: Zenz.#5147

**Comment by stealer1337** [comment]
i add
