### ISSUE TITLE
CSGO Inventory/Profile Issues & Suggestions

### ISSUE THREAD

**Issue by SynnAyyy** [danielkrupinski/Osiris#3509]
(Some things could've been an issue with just me but, here is some of the bugs)

- Some guns wouldn't work with using skins for them (USP/AUG)
- Graffitis don't work
- Souvenir stickers aren't applied.

============================================

- Maybe add a feature to make case opening have random wear etc. (So it's fully random, good for fake unboxing videos)

- Is it possible to add other items like add a storage unit? 

- Fake prime, fake rank? Is that possible?

**Comment by GetRektLOL** [comment]
Fake prime is in NEPS but for some reason @danielkrupinski hasent added it yet

**Comment by SynnAyyy** [comment]
Weird, also I found a possible issue with the guns, when enabling guns if it's the USP, it won't work if you are a T on a map that allows you to get said gun (AIMBOTZ map)

Hopefully the other things can be added/fixed :D
