### ISSUE TITLE
[Idea] Overwatch match crash/Overwatch bypass

### ISSUE THREAD

**Issue by KyleIsDork** [danielkrupinski/Osiris#351]
Make it so that your Overwatch investigator doesn't receive their match data or get a demo of the game. Alternatively, attempt to just crash the investigator's pc when they open the demo by causing some sort of error

**Comment by tirziz** [comment]
More specific?

**Comment by cojo1989** [comment]
This bug was patched. And was not crashing anything just flooding the server and the match does not get recorded. This bug was patched.

**Comment by danielkrupinski** [comment]
Probably not possible.
