### ISSUE TITLE
"Osiris.dll is not a valid win32 application" error while building Osiris.dll

### ISSUE THREAD

**Issue by azzlak** [danielkrupinski/Osiris#3510]
The upper described error pops up after building the Osiris.dll. 
Is that normal?
After injecting the csgo process and pressing the INSERT-key nothing happens

**Comment by csgofever** [comment]
are you sure you are clicking build instead of run or something?

**Comment by t0int** [comment]
NO, thisi s not an error! you cant open dll files like exe files right? THATS WHY go to projects path and go to debug folder or release folder. then inject the dll!

**Comment by azzlak** [comment]
> are you sure you are clicking build instead of run or something?

OK thats the problem i guess

**Comment by azzlak** [comment]
> NO, this is not an error! you cant open dll files like exe files right? THATS WHY go to projects path and go to debug folder or release folder. then inject the dll!

Nothing happens after injection. I tried it with many diffrent injectiors

**Comment by azzlak** [comment]
> are you sure you are clicking build instead of run or something?

didnt work. i dont get an error anz more but after injection nothing happens

**Comment by Patrixsin** [comment]
Mbe ur antivirus moves dll to quarantine after building

**Comment by t0int** [comment]
> > NO, this is not an error! you cant open dll files like exe files right? THATS WHY go to projects path and go to debug folder or release folder. then inject the dll!
> 
> Nothing happens after injection. I tried it with many diffrent injectiors

what injector do u use?

**Comment by azzlak** [comment]
> > > NO, this is not an error! you cant open dll files like exe files right? THATS WHY go to projects path and go to debug folder or release folder. then inject the dll!
> > 
> > 
> > Nothing happens after injection. I tried it with many diffrent injectiors
> 
> what injector do u use?

i used process hacker 2 and other diffrent injektors

**Comment by t0int** [comment]
> > > > NO, this is not an error! you cant open dll files like exe files right? THATS WHY go to projects path and go to debug folder or release folder. then inject the dll!
> > > 
> > > 
> > > Nothing happens after injection. I tried it with many diffrent injectiors
> > 
> > 
> > what injector do u use?
> 
> i used process hacker 2 and other diffrent injektors

Do you build with x86?

**Comment by t0int** [comment]
Be sure you see x86 at here: 
![image](https://user-images.githubusercontent.com/56300981/151195193-2dd1bba6-2451-4ac0-9975-98023ef1b74a.png)

**Comment by azzlak** [comment]
> Be sure you see x86 at here: ![image](https://user-images.githubusercontent.com/56300981/151195193-2dd1bba6-2451-4ac0-9975-98023ef1b74a.png)

Yes release x86
