### ISSUE TITLE
[Request] Force crosshair instead of drawing a new one (noscope crosshair)

### ISSUE THREAD

**Issue by ethxun** [danielkrupinski/Osiris#3511]

**Comment by azzlak** [comment]
Just use an app from microsoft store to have a sniper crosshair. Crosshair v2 works for me

**Comment by ethxun** [comment]
and explain why I would do that if i could just turn on noscope crosshair?

**Comment by azzlak** [comment]
> and explain why I would do that if i could just turn on noscope crosshair?

because it wont work for you

**Comment by ethxun** [comment]
dude. what? im simply saying forcing the crosshair would be better than drawing a new on imo. why would i buy a app that wouldnt change anything.

**Comment by Rafael2030** [comment]
#3119
`void Misc::noscopeCrosshair() noexcept
{
	static auto crosshair = interfaces->cvar->findVar("weapon_debug_spread_show");

	GameData::Lock lock;
	if (const auto& local = GameData::local(); !miscConfig.noscopeCrosshair || !local.exists || !local.alive || !local.noScope)
		crosshair->setValue(0);
	else
		crosshair->setValue(3);
}`

**Comment by Rafael2030** [comment]
#3119

**Comment by ethxun** [comment]
thank u
