### ISSUE TITLE
Menu not opening after Injekting

### ISSUE THREAD

**Issue by azzlak** [danielkrupinski/Osiris#3514]
i built the dll and injekted it in csgo but nothing happens

**Comment by azzlak** [comment]
> @azzlak u in windows 7?

No win 11

**Comment by Ni1kko** [comment]
Try another injector and let us know if still occurs. try a few from this post https://github.com/danielkrupinski/Osiris/issues/3489

**Comment by azzlak** [comment]
works thanks

> Try another injector and let us know if still occurs. try a few from this post #3489

**Comment by Ni1kko** [comment]
No problem :)
