### ISSUE TITLE
[Suggestion] Allow random seed/wear/etc in cases & the choice to pick when adding a item.

### ISSUE THREAD

**Issue by SynnAyyy** [danielkrupinski/Osiris#3518]
Kinda what the title says, add the choice to pick what wear/seed/etc & have the choice to pick random so it's all random.

And the same for cases, have not seen a bad looking skin yet xD, hopefully they get added

**Comment by danielkrupinski** [comment]
Items retrieved from cases have random wear and seed already:
https://github.com/danielkrupinski/Osiris/blob/7241c94083cda793e9499e3d8485fb4f4193e3c3/Osiris/InventoryChanger/ItemGenerator.cpp#L58-L59

**Comment by SynnAyyy** [comment]
Oh, hell yeah! Quick question, are you able to make graffitis work and the choice to get a knife from cases?
