### ISSUE TITLE
Assertion failed! error.

### ISSUE THREAD

**Issue by Smallkittyy** [danielkrupinski/Osiris#3519]
Hey i have the issue that i always get the "Assertion failed" error, and idk how to fix it, i didnt build the dll by myself since im using a loader which has the .ddl

how do i fix the error? do i neeed to download a different version of c++? 
pls help :(

**Comment by danielkrupinski** [comment]
Build in Release mode. Assertions are present only in Debug builds.

**Comment by Smallkittyy** [comment]
yeah but im not using a own dll.
im using a launcher who is using a .dll

**Comment by danielkrupinski** [comment]
I can't help you then.
