### ISSUE TITLE
Auto Strafe not working..?

### ISSUE THREAD

**Issue by KyleIsDork** [danielkrupinski/Osiris#352]
Whenever I attempt to auto-strafe + bhop I continue in 1 direction, and don't strafe. idk how to fix it, but i thought i should bring it up :s

**Comment by danielkrupinski** [comment]
You need to move mouse left or right to strafe.

**Comment by KyleIsDork** [comment]
I did, continues to just move forward, losing momentum, until i hold A or D and manual strafe

**Comment by Gino** [comment]
I’m having the same issue. I’m not sure if it because of Anti Aim, but Auto Strafe sometimes bugs yeah.

**Comment by PackedUP32** [comment]
still doesn't work.
Plz fix
