### ISSUE TITLE
CSGO Linux crashes after injection (new update)

### ISSUE THREAD

**Issue by hayyaun** [danielkrupinski/Osiris#3521]
Hi, I had my Osiris working fine before new CSGO version.
but after updating these were not like before.
I'm not sure if this is caused by any other package updates.

#### Here are some of the files having version errors

```gdb: error while loading shared libraries: libboost_regex.so.1.76.0: cannot open shared object file: No such file or directory```
```gdb: error while loading shared libraries: libicudata.so.70: cannot open shared object file: No such file or directory```
```gdb: error while loading shared libraries: libicui18n.so.70: cannot open shared object file: No such file or directory```
```gdb: error while loading shared libraries: libicuuc.so.70: cannot open shared object file: No such file or directory```

I have all the files below but not the same version.
So each time I copied and renamed them to get it work, but got new errors shown above. 
Finally after renaming 4 files mentioned above the Osiris worked but the CSGO crashed.

I'm currently running CSGO on Manjaro Linux515.

<details>
<summary>
This is my injector
</summary>

```bash

#!/usr/bin/env bash

# Injector script for osiris
# shamelessly stolen from https://github.com/LWSS/Fuzion
# and modified for osiris
# undetected as of right now, but that might change
# please do not use this to cheat against normal players
# cheating against normal players is very scummy
# I do not endorse cheating
# I personally use this only on a local server to 
# check out sticker crafts before I craft them

export PATH="$HOME/.local/bin:$PATH"

function echo_green {
	echo -e "\\e[32m$*\\e[0m"
}

function echo_orange {
	echo -e "\\e[33m$*\\e[0m"
}

function echo_red {
	echo -e "\\e[31m$*\\e[0m"
}

csgo_pid=$(pidof csgo_linux64)
if [ -z "$csgo_pid" ]; then
    echo_red "CS:GO needs to be open before you can inject, exiting..."
    exit 1
fi

# pBypass for crash dumps being sent
# You may also want to consider using -nobreakpad in your launch options.
sudo rm -rf /tmp/dumps # Remove if it exists
sudo mkdir --mode=000 /tmp/dumps # Make it as root with no permissions

filename="libOsiris.so"

# Credit: Aixxe @ aixxe.net
if grep -q "$filename" /proc/"$csgo_pid"/maps; then
    echo_orange "Osiris is already injected, aborting..."
    exit
fi

echo "Injecting Build ID: $filename"

# https://www.kernel.org/doc/Documentation/security/Yama.txt
echo "2" | sudo tee /proc/sys/kernel/yama/ptrace_scope # Only allows root to inject code. This is temporary until reboot.

sudo cp "$filename" "/usr/lib/${filename}"

sudo killall -19 steam
sudo killall -19 steamwebhelper

lib_dir_name="lib"
if [ $(getconf LONG_BIT) = 64 ]; then
    lib_dir_name+="64"
fi

input="$(
sudo gdb -n -q -batch-silent \
  -ex "set logging on" \
  -ex "set logging file /dev/null" \
  -ex "set logging redirect on" \
  -ex "set auto-load safe-path /usr/share/gdb/auto-load/usr/$lib_dir_name/:/usr/$lib_dir_name/" \
  -ex "attach $csgo_pid" \
  -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
  -ex "call \$dlopen(\"/usr/lib/$filename\", 1)" \
  -ex "detach" \
  -ex "quit"
)"

sleep 1
sudo killall -18 steamwebhelper
sudo killall -18 steam

sudo rm "/usr/lib/${filename}"

last_line="${input##*$'\n'}"

if [ "$last_line" != "\$1 = (void *) 0x0" ]; then
    echo_green "Successfully injected!"
else
    echo_red "Injection failed, make sure you have compiled..."
fi

```
</details>

**Comment by hayyaun** [comment]
Fixed by manually installing older versions of the mentioned packages, ```boost``` and ```icu```.
[Boost 1.76.0](https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/)
[ICU 70](https://www.linuxfromscratch.org/blfs/view/svn/general/icu.html)

But the game crashes each time injecting the Osiris.

**Comment by danielkrupinski** [comment]
Are you using unmodified source code? Osiris originally does not use Boost or ICU.

**Comment by hayyaun** [comment]
> Are you using unmodified source code? Osiris originally does not use Boost or ICU.

I use the repo mentioned in REAME.
What do you mean of unmodified?

**Comment by hayyaun** [comment]
I use this repo
git clone --depth=1 https://github.com/danielkrupinski/Osiris.git
