### ISSUE TITLE
Crash while running perfectly

### ISSUE THREAD

**Issue by SENAllu** [danielkrupinski/Osiris#3523]
see i was playing csgo legit and suddenly my osiris dialog box poped up and my game andd cheat crashed. it was showing some assertion faild error and telling me to reinstall visual redistributable i did it but again it happened i ll post the photo when i play next time and get that error.

**Comment by GetRektLOL** [comment]
Compile The Release x86 Version and not the debug version. Alternatively, use precompiled dll :- https://anonfiles.com/Lcc5k5E5x8/Osiris_dll

**Comment by SENAllu** [comment]
Ty now its not crashing.
