### ISSUE TITLE
Can someone upload the new .Dll?

### ISSUE THREAD

**Issue by ikusiss** [danielkrupinski/Osiris#3525]
I would like if someone could because Im getting some errors when compiling in visual studio that I didnt get last time I did. And I didn't get any solutions on internet. x,d
![Desktop Screenshot 2022 01 28 - 22 14 15 43 (2)](https://user-images.githubusercontent.com/91351345/151622536-b90f68bc-44c5-4eb6-a2d9-1983446e3764.png)

**Comment by Ni1kko** [comment]
add me on discord :) `TᕼᗩT ᑎOᖇTᕼGᑌY#1652`

**Comment by mdilai** [comment]
Be careful, as right now you literally say "I know nothing about programming and completely ready to run custom binary from random scammer which will steal my Steam/PayPal/insert_valuable_data_here and I won't even realize it until it's too late."

Better is to realize how to install Visual Studio properly and compile Osiris by yourself.

**Comment by Ni1kko** [comment]
I tried to help him fix his issue and told him the same but he was in a call and didn't want too

**Comment by E4zily** [comment]
https://cdn.discordapp.com/attachments/790994549194620959/937446862108114944/Osiris.dll
here you go, it also has some fun stuff added such as fake case open in chat (when you open a container added thru inventory changer), blockbot and door spammer
