### ISSUE TITLE
Possible missing cast to `uintptr_t` in `ItemSchema.h`

### ISSUE THREAD

**Issue by cryeprecision** [danielkrupinski/Osiris#3526]
https://github.com/danielkrupinski/Osiris/blob/9a6f4f876bad7c1e94c80e3761ef28b96561a184/Osiris/SDK/ItemSchema.h#L87
https://github.com/danielkrupinski/Osiris/blob/9a6f4f876bad7c1e94c80e3761ef28b96561a184/Osiris/SDK/ItemSchema.h#L150

I believe those functions need to cast `this` to `uintptr_t`.
Or is this on purpose and it should actually be `(uintptr_t)this + offset * sizeof(*this)`

**Comment by danielkrupinski** [comment]
If `sizeof(*this)` is 1 it works the same with or without uintptr_t.

**Comment by cryeprecision** [comment]
Ohhh right, because your class doesn't have a vfunc-table!
With a vfunc-table `sizeof(*this)` would've been 4 (or 8 on 64bit).

Thank you for the answer!
