### ISSUE TITLE
what is fast plant

### ISSUE THREAD

**Issue by EJianZQ** [danielkrupinski/Osiris#353]
i have read the readme.md but i still dont know what is fast plant...

**Comment by hydemods** [comment]
before fast plant: https://www.youtube.com/watch?v=KIlfI8WPtQY

after fast plant: https://www.youtube.com/watch?v=sn6eOLip7IA

from masterlooser

**Comment by Bywnb** [comment]
> without fast plant: https://www.youtube.com/watch?v=KIlfI8WPtQY
> 
> with fast plant: https://www.youtube.com/watch?v=sn6eOLip7IA
> 
> from masterlooser

sry,but i still know...can you explain in words?...

**Comment by effex1337** [comment]
You basically save some time while holding plant button (m1/e) and running into the site as you dont need to run a bit before planting.
