### ISSUE TITLE
Can't connect to CSGO server

### ISSUE THREAD

**Issue by afeer123** [danielkrupinski/Osiris#3532]
Can't connect to CSGO server after game update

**Comment by GetRektLOL** [comment]
This has nothing to do with osiris, close this

**Comment by afeer123** [comment]
This is the problem after injection

**Comment by afeer123** [comment]
> 这是注射后的问题
![image](https://user-images.githubusercontent.com/86306447/152147887-c103abde-8706-4b72-be5b-da50b7b3ab90.png)

**Comment by Patrixsin** [comment]
ye im getting the same error, so its osiris problem

**Comment by cristyanul** [comment]
Pretty much no internals work rn: [https://www.unknowncheats.me/forum/counterstrike-global-offensive/488231-valve-add-retaddr-checks-update.html](url)

**Comment by collinsmao** [comment]
ye, after injection

**Comment by SENAllu** [comment]
Same error can i get a fix or update of orisis?

**Comment by tirziz** [comment]
yo this, I have this error too haha

**Comment by azzlak** [comment]
i have it too. also with other cheats

**Comment by Patrixsin** [comment]
I checked this again and getting this even without cheats.

**Comment by notgoodusename** [comment]
just need some hooks to fix this, i did a [commit ](https://github.com/notgoodusename/OsirisAndExtra/commit/d0bc1fa1b835ff791639ca6636f36e4e386df96d)on my repo that fixes this update

**Comment by danielkrupinski** [comment]
I've made an update to address this: 435dc809675239b894fb948b02c8580ddf56fffa

**Comment by TauCSGO** [comment]
> just need some hooks to fix this, i did a [commit ](https://github.com/notgoodusename/OsirisAndExtra/commit/d0bc1fa1b835ff791639ca6636f36e4e386df96d)on my repo that fixes this update

I LIKE YOUR MENU
How can I learn to make a similar menu? it's simple but beautiful

**Comment by notgoodusename** [comment]
> > just need some hooks to fix this, i did a [commit ](https://github.com/notgoodusename/OsirisAndExtra/commit/d0bc1fa1b835ff791639ca6636f36e4e386df96d)on my repo that fixes this update
> 
> I LIKE YOUR MENU
> How can I learn to make a similar menu? it's simple but beautiful

Its not my menu, it was done by somebody i used to work with in the past, but now they are gone

**Comment by TauCSGO** [comment]
> > > just need some hooks to fix this, i did a [commit ](https://github.com/notgoodusename/OsirisAndExtra/commit/d0bc1fa1b835ff791639ca6636f36e4e386df96d)on my repo that fixes this update
> > 
> > 
> > I LIKE YOUR MENU
> > How can I learn to make a similar menu? it's simple but beautiful
> 
> Its not my menu, it was done by somebody i used to work with in the past, but now they are gone

Thanks for the reply
Is it very difficult to learn to modify the current one?
i'm a bit new

**Comment by TauCSGO** [comment]
> I've made an update to address this: [435dc80](https://github.com/danielkrupinski/Osiris/commit/435dc809675239b894fb948b02c8580ddf56fffa)

Thank you!

**Comment by notgoodusename** [comment]
> > > > just need some hooks to fix this, i did a [commit ](https://github.com/notgoodusename/OsirisAndExtra/commit/d0bc1fa1b835ff791639ca6636f36e4e386df96d)on my repo that fixes this update
> > > 
> > > 
> > > I LIKE YOUR MENU
> > > How can I learn to make a similar menu? it's simple but beautiful
> > 
> > Its not my menu, it was done by somebody i used to work with in the past, but now they are gone
> 
> Thanks for the reply
> Is it very difficult to learn to modify the current one?
> i'm a bit new

I really dont have much idea about imgui, you should probably experiment with it yourself to learn about it
And as far as i know its not that hard to modify it

**Comment by diekunstderfuge** [comment]
> I've made an update to address this: [435dc80](https://github.com/danielkrupinski/Osiris/commit/435dc809675239b894fb948b02c8580ddf56fffa)

Worked for some time, I played 3 matches but then the error happened again.

**Comment by notgoodusename** [comment]
> > I've made an update to address this: [435dc80](https://github.com/danielkrupinski/Osiris/commit/435dc809675239b894fb948b02c8580ddf56fffa)
> 
> Worked for some time, I played 3 matches but then the error happened again.

This new update made Valve servers crash at random, so it maybe the server rather than the cheat

**Comment by Patrixsin** [comment]
It works like cheat crashes valve's servers. At least my paste does this

**Comment by SENAllu** [comment]
so how to use it huh??

**Comment by SENAllu** [comment]
so i got and now osiris is working perfectly fine download cheat update from
https://anonfiles.com/Jf1az5Ffxc/Osiris_dll

**Comment by diekunstderfuge** [comment]
> Has the related update ([435dc80](https://github.com/danielkrupinski/Osiris/commit/435dc809675239b894fb948b02c8580ddf56fffa)) fixed the 'connection lost' problem? Has anyone tried?

As far as Osiris goes it is fixed, you can play for some time, but the error still happens because of valve servers.

**Comment by Patrixsin** [comment]
> Has the related update ([435dc80](https://github.com/danielkrupinski/Osiris/commit/435dc809675239b894fb948b02c8580ddf56fffa)) fixed the 'connection lost' problem? Has anyone tried?

i'd recommend use @notgoodusename's version of osiris, his works today at least

**Comment by diekunstderfuge** [comment]
> Has the related update ([435dc80](https://github.com/danielkrupinski/Osiris/commit/435dc809675239b894fb948b02c8580ddf56fffa)) fixed the 'connection lost' problem? Has anyone tried?

It is stable now, I played a lot of matches today without the error.
