### ISSUE TITLE
New update broke some things

### ISSUE THREAD

**Issue by GetRektLOL** [danielkrupinski/Osiris#3539]
1. Low fps
2. Music kits not saving to cfg and are replaced with random music kit when loaded again

**Comment by Shuvi-Moro** [comment]
XD
I have my own version of Osiris and it generally puts the server ks, I dunno why but it's so!

**Comment by Shuvi-Moro** [comment]
[](https://www.dropbox.com/s/axqtyxv2mtl2ztd/Counter-strike%20%20Global%20Offensive%202022.02.03%20-%2015.51.49.03.mp4?dl=0)

**Comment by Shuvi-Moro** [comment]
https://www.dropbox.com/s/axqtyxv2mtl2ztd/Counter-strike%20%20Global%20Offensive%202022.02.03%20-%2015.51.49.03.mp4?dl=0

**Comment by Shuvi-Moro** [comment]
@danielkrupinski

**Comment by ValikSherenok** [comment]
> 
added a new check for returned functions
Pattern: 55 8B EC 56 8B F1 33 C0 57 8B 7D 08 8B 8E ? ? ? ? 85 C9 7E 12 3B 3C 86 72 06 3B 7C 86 04 72 49 83 C0 02 3B C1 7C EE -> patch B0 01 C2 04 00 (mov al, 1; retn 4) 
Source: https://yougame.biz/threads/242254/#post-2513465

**Comment by Patrixsin** [comment]
@Shuvi-Moro Use this https://github.com/notgoodusename/OsirisAndExtra/commit/d0bc1fa1b835ff791639ca6636f36e4e386df96d#diff-7d482f6c96d1ee875d3180e95f33751bda4451d3c3ae16149b291bfe0875988e
It works well for me

**Comment by danielkrupinski** [comment]
Load music kits has been fixed in https://github.com/danielkrupinski/Osiris/commit/1559783fcad3999cc2560e356da6a7c2cf83065d
