### ISSUE TITLE
Giant fps drop?

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#3542]
it seems im not the only person experiencing fps drops.
Any idea what is causing this?

**Comment by hitman2933** [comment]
There is no known fix, reverting to older versions doesn't fix anything

**Comment by danielkrupinski** [comment]
Fps drops are most likely caused by the return address checks added by game developers. I've reduced calls to one of the checked function that was called frequently (304ae47b8a3e6479cb8f244515ac6dced9f278d6) - that should improve framerates.
