### ISSUE TITLE
MusicKit cfg loading is broken | Crash on cheat load if rename cfg to 'default.json'

### ISSUE THREAD

**Issue by playday3008** [danielkrupinski/Osiris#3544]
Screenshot can describe this much better than me
![image](https://user-images.githubusercontent.com/18056374/152435938-01322989-cddb-480e-9960-4b1a322744f5.png)

(All MusicKits have id 58 after loading)

Also game will crash on Osiris loading if I will rename my cfg to `default.json`

**Comment by danielkrupinski** [comment]
Load music kits has been fixed in 1559783fcad3999cc2560e356da6a7c2cf83065d

**Comment by playday3008** [comment]
Ok, music fixed, but new bug appears

**Comment by playday3008** [comment]
@danielkrupinski 
![image](https://user-images.githubusercontent.com/18056374/152611815-610089ae-e773-47b3-82f1-cf3dc138754e.png)

**Comment by playday3008** [comment]
Agents and pins not loaded
