### ISSUE TITLE
CS crash when inject

### ISSUE THREAD

**Issue by lllgamingchicken** [danielkrupinski/Osiris#3550]
![image](https://user-images.githubusercontent.com/95076142/152644412-231167d3-1115-47ea-ad79-e3d681fc81d5.png)
Hello, every time I inject osiris using csghost it always crash and show this message when I press debug. I need help. Thank you.

**Comment by Patrixsin** [comment]
Are u sure its osiris fault?

**Comment by suckma420** [comment]
release not debug

**Comment by tirziz** [comment]
build as release profile, not debug

**Comment by lllgamingchicken** [comment]
I built osiris in release and did everything but when inject with csghost, csgo crashed and I press debug then that error window opens up not that I built osiris in debug mode. Need help

**Comment by crmpe** [comment]
you may be injecting too early. ive had this problem with some injectors, wait for csgo to fully start up and get you onto the loading screen before injecting.
