### ISSUE TITLE
How to add libcurl to Osiris?

### ISSUE THREAD

**Issue by aldias14** [danielkrupinski/Osiris#3551]
I add libcurl with openssl to make some features, but I get error LNK2001 curl_easy_global_init() and etc. If I add it to other dll it works fine, so how can I fix this?

![image](https://user-images.githubusercontent.com/75922463/152648788-c3ba147e-610c-4638-a76a-f31092cae472.png)

**Comment by aldias14** [comment]
Pls help

**Comment by aldias14** [comment]
solved

**Comment by 0zl** [comment]
stop making osiris p2c holy fuck

**Comment by Xonn1com** [comment]
> stop making osiris p2c holy fuck

+
