### ISSUE TITLE
Case odds way too good?

### ISSUE THREAD

**Issue by fallingDOWN12** [danielkrupinski/Osiris#3554]
I opened Souvenir Packages and got out of 60 packages 3 covert skins, which seems quite high

I was wondering if I should buy a lottery ticket or are the odds for covert skins way too good in osiris?

If yes, how can I change them back to the original csgo odds?

**Comment by loicnestler** [comment]
As far as I know, case odds are calculated server-side. So there is no way of a client modification to alter the case odds.
Not 100% sure about that, tho.

**Comment by unavailable-888** [comment]
there use to be an inventory changer that had case odds changer but that only client side i experience the same thing with osiris inventory changer the odds are way batter then default

**Comment by propane** [comment]
> As far as I know, case odds are calculated server-side. So there is no way of a client modification to alter the case odds. Not 100% sure about that, tho.

the odds would be calculated server-side if the item was also a real server-side case, the items are completely client-side and you can change every detail about them in game, including the odds of opening certain items, you can modify the code to make it so every case you add has a 100% chance to open a knife and so on, to my knowledge if you tinker enough you can force items as well, down to the pattern id and seed (aka fake opening blue gems or what not)

**Comment by propane** [comment]
yes the odds of opening cases in osiris is better than default, i think this is a mistake since there was a previous branch i think that daniel made about 'fixing' case odds to be closer to real csgo odds

**Comment by danielkrupinski** [comment]
Odds have been adjusted.
