### ISSUE TITLE
give me the new osiris dll, Thanks.

### ISSUE THREAD

**Issue by ApoloGGLow** [danielkrupinski/Osiris#3555]

**Comment by GetRektLOL** [comment]
no

**Comment by 0zl** [comment]
no

**Comment by ufgf** [comment]
tip: it's not difficult, you can use windows sandbox for the whole process

**Comment by ApoloGGLow** [comment]
NO

**Comment by Ni1kko** [comment]
[Osiris.zip](https://github.com/danielkrupinski/Osiris/files/8063801/Osiris.zip)

**Comment by Ni1kko** [comment]
[Osiris(15.feb.2022).zip](https://github.com/danielkrupinski/Osiris/files/8075412/Osiris.15.feb.2022.zip)

**Comment by Ni1kko** [comment]
[Osiris(17.feb.2022).zip](https://github.com/danielkrupinski/Osiris/files/8087902/Osiris.17.feb.2022.zip)
