### ISSUE TITLE
So im trying to compile the code myself and this happened

### ISSUE THREAD

**Issue by skiMFF** [danielkrupinski/Osiris#3561]
i know nothing about this pls help 
![image](https://user-images.githubusercontent.com/97688981/153239709-27023680-e1fd-4766-a314-531cf518741c.png)

**Comment by skiMFF** [comment]
> pretty sure this is just a wrong version of vstools, try to use v142 or newer, but you can safely ignore the warnings

alright then, thanks :D

**Comment by Lightzzzv** [comment]
Make sure its on release! and X86
