### ISSUE TITLE
Is it possible to do a backtracking trigerbot?

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#3574]
It would be handy to have a trigerbot by backtracking, in order to make the cheat more powerful.

**Comment by ocewot** [comment]
yes but someone told me its complex (this could be wrong but i know its possible) iniuria for example has an option to make trig shoot backtrack

**Comment by Okay5041** [comment]
If you want to get fancy with it... you could:
1. store StudioBbox's, for all of the hitboxes you wanna backtrack triggerbot
2. cycle through all the records, and for each studioBbox in those records
    1. do ray math (does ray intersect capsule, somethin like https://gist.github.com/jdryg/ecde24d34aa0ce2d4d87)
    2. if it does hit, and it is visible/autowallable (do the damage calculation, but instead of returning false if fraction == 1,
        return true, as the ray has fully reached the end, and then do the damage calculation based on what hitbox ur shooting at
    3. if the autowall, and damage works... shoot, and adjust your tickcount to account for lag compensation
   
Some issues I see...
It might be difficult do get the correct delay timing with this, i'm not using osiris's method 
Writing the code for the "does ray intersect capsule" problem might be somewhat difficult for yall
The probably won't be super accurate, as the current backtrack method/record storing doesn't account for:
1. a needed animation fix,
2. interpolation/extrapolating lagging players
3. Resolving desyncing players...

But alas, I think it is VERY doable, and could probably write it myself. If other people would like that, and people react with a thumbs up 👍 , ill write and release :D

**Comment by Okay5041** [comment]
> > It would be handy to have a trigerbot by backtracking, in order to make the cheat more powerful.
> 
> get the tick count of closest backtrack record, and set your current tick count to that one, should do the trick feel free to correct me if im wrong

Doing that constantly will mess up your "manual" shots, and the triggerbot will almost never shoot because of the damage calculation only looking at the current record, not the old backtrack record. (it will sometimes shoot if you are over a limb, and in that case it will adjust the tick count to give you much more likely hit, but probably not for the user inputted damage, or hitbox).

**Comment by notgoodusename** [comment]
I have a repo with a backtracking triggerbot and its very easy
how to
1. Get closest backtrack record
2. Backup entity boneCache, origin and absangle
3. Based on that record, set boneCache, origin and absangle
4. Run triggerbot
5. Restore
