### ISSUE TITLE
[Request] Stop making the recoil crosshair disappear when you dont shoot

### ISSUE THREAD

**Issue by FrenchWave** [danielkrupinski/Osiris#3575]
Hello! First i'm sorry to make a request here.

I havent legit hacked on CSGO since some time but i remember using the recoil crosshair on a paid cheat (dont want to share names not sure if its allowed) and the crosshair was always visible. When you were not shooting it was at the middle, like a simple crosshair.

This allows people to play with the original game crosshair disabled (with the command crosshair 0), so you only have one, the recoil crosshair. Its SO MUCH better than having your two crosshairs at the same time. I think this is pretty important for legit hacking. 

Hopefully someone explain me how i could do that by editing the code. Thank you.

**Comment by FrenchWave** [comment]
well that was pretty easy,

go the the recoil crosshair code in Misc.cpp and remove the line that says the condition "if player is shooting" and voila.

The crosshair is shaking a little bit in game when you move (its really small) because our real recoil move when you move, its already WAY better like that, if anyone has an idea to make it stable when i'm not shooting feel free to tell me thank you!

**Comment by Okay5041** [comment]
> well that was pretty easy,
> 
> go to the recoil crosshair code in Misc.cpp and remove the line that says the condition "if player is shooting" and voila.
> 
> The crosshair is shaking a little bit in game when you move (its really small) because our real recoil move when you move, its already WAY better like that, if anyone has an idea to make it stable when i'm not shooting feel free to tell me thank you!

Hey! Just draw the crosshair in the center of the screen if they are not shooting, otherwise run the default code. something like this...
```
// if the player is shooting, draw the recoil crosshair
if (localPlayerData.shooting)       
{
   if (ImVec2 pos; Helpers::worldToScreenPixelAligned(localPlayerData.aimPunch, pos))
      drawCrosshair(drawList, pos, Helpers::calculateColor(miscConfig.recoilCrosshair.asColorToggle().asColor4()));
}
// otherwise draw in the center, to remove the shaking
else
{
   int w, h;
   interfaces->engine->getScreenSize(w, h); // get screen width/height
   // draw the crosshair in the center of the screen
   drawCrosshair(drawList, ImVec2(w/2, h/2), Helpers::calculateColor(miscConfig.recoilCrosshair.asColorToggle().asColor4()));
}
```

    
```

**Comment by hamad12a** [comment]
@Okay5041 Can't get in the middle. My resolution is 1280x720 (16:9) running CSGO on Linux.
