### ISSUE TITLE
CSGO Crash after load the map - CSGO last update

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#3577]
Title
*********************************************************************************
EDIT
*********************************************************************************
### Temporary solution

in hooks.cpp , line 183
replace:
`bool& sendPacket = *reinterpret_cast<bool*>(*reinterpret_cast<std::uintptr_t*>(FRAME_ADDRESS()) - 0x1C);`
with
`bool sendPacket = true;`

**Comment by Callum151800** [comment]
same

**Comment by sarahdumby** [comment]
> https://www.unknowncheats.me/forum/counterstrike-global-offensive/490199-internal-cheat-broken-2022-02-18-update.html

doesn't help if we're retarded tbh

**Comment by hyperxpro** [comment]
Any update?

**Comment by Callum151800** [comment]
not yet

**Comment by hck8899** [comment]
Do we need to wait for an update now? Or already have a solution? I'm just a user

**Comment by SquidmarcHD** [comment]
but the vfunc and the sig are the same between the two commits arent they?

**Comment by SquidmarcHD** [comment]
"B9 ?? ?? ?? ?? 8D 44 24 10 89 54 24 14" + 0x1 this is the new inventorymanager sig (well atleast works for me)

**Comment by SquidmarcHD** [comment]
may still crash for yall tho because some other shit might also have changed for osiris

**Comment by hyperxpro** [comment]
Can you show your code?

**Comment by OukiLove** [comment]
Where is the new signature stored?

**Comment by TauCSGO** [comment]
Still the problem continues, but csgo closes when entering the maps

@danielkrupinski 

https://github.com/danielkrupinski/Osiris/issues/3582

**Comment by PKCELLULOID** [comment]
For me it crashes on inject, I have never experienced a crash while loading a map.

**Comment by TauCSGO** [comment]
### Temporary solution

in hooks.cpp , line 183
replace:
`bool& sendPacket = *reinterpret_cast<bool*>(*reinterpret_cast<std::uintptr_t*>(FRAME_ADDRESS()) - 0x1C);`
with
`bool sendPacket = true`

**Comment by PKCELLULOID** [comment]
> ### Temporary solution
> in hooks.cpp , line 183 replace: `bool& sendPacket = *reinterpret_cast<bool*>(*reinterpret_cast<std::uintptr_t*>(FRAME_ADDRESS()) - 0x1C);` with `bool sendPacket = true;`

My game still crashed when loading into a map

**Comment by hackerjackerA1** [comment]
all right it works.

**Comment by hackerjackerA1** [comment]
it works,thank you.are you helping for osiris??how do you know this method？

**Comment by ayaanjaved07** [comment]
can you send the source? not the dll

**Comment by emreires** [comment]
SendPacket variable is now in [ebp-0x34] rather than [ebp-0x1C].

#3586, you can try this version.

**Comment by diekunstderfuge** [comment]
> https://anonfiles.com/x4O7QfI1x4/Osiris_that_does_not_crash_rar this is the fixed version that I coded

It is working, thanks!
