### ISSUE TITLE
[Request] better no-scope crosshair

### ISSUE THREAD

**Issue by Callum151800** [danielkrupinski/Osiris#3579]
add a feature to use our own crosshair when holding sniper rifle

**Comment by Okay5041** [comment]
do you mean force crosshair? 

`
bool forceCrosshair = true;`
`
static ConVar* m_iCrosshairData = I::cvar->FindVar("weapon_debug_spread_show");
`
`
if(ingame)
`
`
{
`
`
if(Localplayer && localplayeralive)
`
`
    m_iCrosshairData->SetValue(!(Localplayer->IsScoped() || !forceCrosshair) ? 3 : 0);
`
`
}`
