### ISSUE TITLE
CS:GO Crashes when loading into a game.

### ISSUE THREAD

**Issue by S3RAPH-1M** [danielkrupinski/Osiris#3582]
Game crashes when loading into the match.

**Comment by alucard12345678** [comment]
same here

**Comment by 0xJX** [comment]
They changed something related to the sendpacket, if you can't reverse the new offset:
https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hooks.cpp#L182-L187
You can temp fix it by removing it from use, just rename the variable to bool sendPacket = true.

**Comment by PKCELLULOID** [comment]
> > > They changed something related to the sendpacket, if you can't reverse the new offset: https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hooks.cpp#L182-L187 You can temp fix it by removing it from use, just rename the variable to bool sendPacket = true.
> > 
> > 
> > This did not work for me, cs:go still crashes
> 
> Ended up completely scrapping SendPacket. That fixed it for me.

can you send me your osiris.dll file to see if it will work on my pc.

**Comment by Callum151800** [comment]
> > bool sendPacket = true
> 
> in hooks.cpp , line 183 replace: `bool& sendPacket = *reinterpret_cast<bool*>(*reinterpret_cast<std::uintptr_t*>(FRAME_ADDRESS()) - 0x1C);` with `bool sendPacket = true;`

Thanks, it works on my PC

**Comment by PKCELLULOID** [comment]
https://anonfiles.com/x4O7QfI1x4/Osiris_that_does_not_crash_rar this is the fixed version that I coded

**Comment by S3RAPH-1M** [comment]
> bool sendPacket = true;

Delete line 182 to 187, Fix any errors you get and then compile. Make sure not to use ur old config as it will not work!
