### ISSUE TITLE
cannot build file

### ISSUE THREAD

**Issue by estnoem** [danielkrupinski/Osiris#3584]
when opening the .sln file i cannot build it. i have no option to and when changing to to c++ instead of plain text it does not fix anything

**Comment by PKCELLULOID** [comment]
Have you tried using visual studio to open the .sln file/

**Comment by estnoem** [comment]
> Have you tried using visual studio to open the .sln file?

yes i have, it opens as a plain text file

**Comment by PKCELLULOID** [comment]
> > Have you tried using visual studio to open the .sln file?
> 
> yes I have, it opens as a plain text file

I have never heard of this problem before, the only thing I can say is to reinstall visual studio.

**Comment by Shuvi-Moro** [comment]
![setup_bCU6zSdvni](https://user-images.githubusercontent.com/63977167/154797772-abcfa216-468e-48a4-a933-7bfa1aa5806d.png)

**Comment by Shuvi-Moro** [comment]
and by the way, you need to change the version of PlatformToolset from 142 to 143
<PlatformToolset>v142</PlatformToolset> >>> <PlatformToolset>v143</PlatformToolset> (C:\Users\...\source\repos\Osirisclasiccc19022022\Osiris\Osiris.vcxproj)

**Comment by GetRektLOL** [comment]
stupid bitch

**Comment by floydGG** [comment]
stupid bitch (2)
