### ISSUE TITLE
The game crashed*

### ISSUE THREAD

**Issue by hoangxuanlam2007** [danielkrupinski/Osiris#3585]
The game crashed after I click on a match making game. I already checked for the Osiris version, It is the latest version and I'm using the CSGhost 4.3.1

**Comment by TauCSGO** [comment]
Please, close
https://github.com/danielkrupinski/Osiris/issues/3577

**Comment by emreires** [comment]
> https://anonfiles.com/x4O7QfI1x4/Osiris_that_does_not_crash_rar this is the fixed version that I coded

This is GitHub.
If you want to help or contribute, please fork the project and send a pull request.

Please try this one: #3586

**Comment by hoangxuanlam2007** [comment]
> https://anonfiles.com/x4O7QfI1x4/Osiris_that_does_not_crash_rar this is the fixed version that I coded
Thanks for helping me but I already know where to code.
