### ISSUE TITLE
Stickers do not work in InventoryChanger

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#3588]
Stickers do not work in InventoryChanger (same problem as with music)
Yes, I have a modified osiris but I have not touched InventoryChanger

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

![image](https://user-images.githubusercontent.com/63977167/155023082-5aee2cff-29df-4def-8ad3-e49e28c9fa19.png)

**Comment by danielkrupinski** [comment]
Should be working now.
