### ISSUE TITLE
Can't inject Osirris

### ISSUE THREAD

**Issue by TheGraySpy** [danielkrupinski/Osiris#3595]
Cant inject osiris.I am using process hacxker and I made the settings 86 and release but It doesn't work.I tried all the solutions but none of them work.Help me!!!

**Comment by Shuvi-Moro** [comment]
the process hacker can't do it

**Comment by Shuvi-Moro** [comment]
https://www.dropbox.com/s/4qyz7uxdion69sn/csgo-injector.exe?dl=0

**Comment by Patrixsin** [comment]
U cant inject cheat with process hacker, unless u use -allow_third_party_software startup parameter. I guess

**Comment by playday3008** [comment]
If you want to use PH, put your doll into Windows folder, and then try to inject

**Comment by TheGraySpy** [comment]
What can I use?

**Comment by wumpy2k** [comment]
I think most people use csghost

https://www.unknowncheats.me/forum/cs-go-releases/454734-csghost-v4-injector-integrated-vac-bypass.html

**Comment by BuddyBoi** [comment]
You can use github to find a cheat source but not an injector source?

**Comment by alucard12345678** [comment]
> https://www.dropbox.com/s/4qyz7uxdion69sn/csgo-injector.exe?dl=0

how to use this?
