### ISSUE TITLE
How do you Manual-Map Osiris

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#3596]
How do you exactly manual map Osiris? Crashes CS everytime for me

**Comment by ayaanjaved07** [comment]
use csghost
https://www.unknowncheats.me/forum/cs-go-releases/454734-csghost-v4-injector-integrated-vac-bypass.html

**Comment by wemanzoz** [comment]
> use csghost
> https://www.unknowncheats.me/forum/cs-go-releases/454734-csghost-v4-injector-integrated-vac-bypass.html

csghost is a load library injector afaik

**Comment by Metaphysical1** [comment]
https://github.com/mdilai/Shtreeba
