### ISSUE TITLE
Antiobs

### ISSUE THREAD

**Issue by adriangames147** [danielkrupinski/Osiris#36]
Can you add some antiobs button like its in aimware or something like that? This is best cheat I  ever used but I want to record it :(

**Comment by adriangames147** [comment]
and BTW why you removed autobunnyhop autopistol and totaly bugged aimbot after latest update?

**Comment by danielkrupinski** [comment]
What do you mean by saying 
>  why you removed autobunnyhop autopistol
?

**Comment by adriangames147** [comment]
Now autobunnyhop and autopistol is working. i dont know yesterday in cheat didnt had it but now I have it, it was been only bug, but when I use smoothing in aimbot it turns me in wrong angle :(

**Comment by adriangames147** [comment]
And also can you make something like sniper crosshair? (Crosshair on AWP, SSG-08, AUTOSNIPER)
Thanks

**Comment by JayneFrack** [comment]
Antiobs would be pretty good

**Comment by adriangames147** [comment]
> Antiobs would be pretty good

I think yes

**Comment by NexSqaud** [comment]
@adriangames147 i think this better https://www.unknowncheats.me/forum/counterstrike-global-offensive/276438-stream-proof-visuals-method.html

**Comment by adriangames147** [comment]
> @adriangames147 i think this better https://www.unknowncheats.me/forum/counterstrike-global-offensive/276438-stream-proof-visuals-method.html

But where should I put that code?

**Comment by danielkrupinski** [comment]
Stream Proof ESP has been added.
