### ISSUE TITLE
Close/delete

### ISSUE THREAD

**Issue by DownAP** [danielkrupinski/Osiris#360]
Close/delete

**Comment by NexSqaud** [comment]
buy new pc?

**Comment by DownAP** [comment]
It has nothing to do... I'm having in game 200 fps, in obs I have no drop frames but on recording it keeps stuttering

**Comment by NexSqaud** [comment]
how much is the bitrate?

**Comment by Nichealys** [comment]
> It has nothing to do... I'm having in game 200 fps, in obs I have no drop frames but on recording it keeps stuttering

What CPU do you have?

**Comment by DownAP** [comment]
Ryzen 5 2600... with any other cheat or without cheat I have no problem

**Comment by Nichealys** [comment]
> Ryzen 5 2600... with any other cheat or without cheat I have no problem

That’s really weird, when I record I have no problems. Are you using game capture or display capture?

**Comment by DownAP** [comment]
I've tried both.. same problem
