### ISSUE TITLE
Manual map inject!

### ISSUE THREAD

**Issue by PowerfullPower** [danielkrupinski/Osiris#3600]
Hi i am surfe you have heard that issues where guys said they can not use manual map. (you gave them injectors)
I have my own injector and its manual map. How do i change dll to not crash on manual map???

**Comment by bluebewwy** [comment]
You should be able to use ManualMap. I can inject Osiris with ManualMap on most injectors fine. Make sure you are compiling the project properly. (x64 Release)

**Comment by Wiselyx** [comment]
what? csgo is a x86 game. building the cheat on x64 will most definetly crash the game or will cause instability
