### ISSUE TITLE
what kind of offsets do Osiris use?

### ISSUE THREAD

**Issue by Wiselyx** [danielkrupinski/Osiris#3601]
i want to try and update the cheat myself. i saw a yt video about how to update a cheat using hazedumper offsets but osiris doesnt use hazedumper(or atleast from what i see). i have a idea on where the offsets maybe but im not sure yet. so anyone can confirm my idea.

**Comment by BasicllyMaximqs** [comment]
osiris doesnt use those offsets, osiris scans and finds its own using its own findpattern() function

**Comment by tirziz** [comment]
you dont need to update it unless a big update break the cheat

**Comment by Wiselyx** [comment]
i see....  thanks for the info guys!
