### ISSUE TITLE
Planning to use this on my main but im kinda scared lol

### ISSUE THREAD

**Issue by Wiselyx** [danielkrupinski/Osiris#3602]
is this cheat ud? if i compile this myself and change or remove stuffs a bit and add junk code (even tho it doesnt do shit but oh well) does it make the cheat ud?

**Comment by tirziz** [comment]
just dont use cheat on your main. not worth it

**Comment by Patrixsin** [comment]
no, u gonna regret then

**Comment by sarahdumby** [comment]
Only cheat on your main if you don't care. I really don't care and have been cheating on my main using it for about a year, but there is definitely a big possibility you will be banned

**Comment by unavailable-888** [comment]
dont be stupit dont use main even with prv cheat like skeet just dont use on main just use an alt prime is like 15 usd i think

**Comment by Metaphysical1** [comment]
> is this cheat ud? if i compile this myself and change or remove stuffs a bit and add junk code (even tho it doesnt do shit but oh well) does it make the cheat ud?

doesn't matter, eventually vac will dump it and send it to vac team for automatic or manual analysis and then you will get vac banned.
to stay undetected you must hide your dll from vac, self mutating code will make it harder for vac to signature scan your cheat, if you managed to add junk assembly randomally at runtime this will be helpful, other than that it's useless and will make your code unreadable, hooking winapi or patching them will make vac unable to read your code in memory... 
these are a few ways to truely bypass vac and stay undetected for long time, also I consider dumping vac modules from time to time and see if you get any new modules and reverse them.
most payed cheats will just block vac modules from loading, this will eventually drop your trust factor, but they still use that shit.
I cheat on my main for more than a year now, but I know what I'm doing.

**Comment by peybb11** [comment]
> > is this cheat ud? if i compile this myself and change or remove stuffs a bit and add junk code (even tho it doesnt do shit but oh well) does it make the cheat ud?
> 
> doesn't matter, eventually vac will dump it and send it to vac team for automatic or manual analysis and then you will get vac banned. to stay undetected you must hide your dll from vac, self mutating code will make it harder for vac to signature scan your cheat, if you managed to add junk assembly randomally at runtime this will be helpful, other than that it's useless and will make your code unreadable, hooking winapi or patching them will make vac unable to read your code in memory... these are a few ways to truely bypass vac and stay undetected for long time, also I consider dumping vac modules from time to time and see if you get any new modules and reverse them. most payed cheats will just block vac modules from loading, this will eventually drop your trust factor, but they still use that shit. I cheat on my main for more than a year now, but I know what I'm doing.

do u have a discord server. educate me

**Comment by OsirisUser** [comment]
Why has nobody told this guy that vac bypass exists. It's made by the same guy who made Osiris. It prevents the vac reader from launching. I have been using onetapv3 (detected) and I haven't been banned ever since.
