### ISSUE TITLE
Not sure if I can call this an issue or not

### ISSUE THREAD

**Issue by Jonizz** [danielkrupinski/Osiris#3607]
Okay so I've been searching through some pull requests and found some cool ones but they all are outdated for this version's Osiris.

For example look at this one: https://github.com/danielkrupinski/Osiris/pull/389
It craves that you edit line 201 in the Config.h file
However my Config.h file only has 129 lines?

**Comment by tirziz** [comment]
its fine

**Comment by OsirisUser** [comment]
Biggest tip I can give you is that you should never trust the numbers on pull requests, they are just sometimes incorrect. You should always use the thing above what you are trying to do as a reference instead of the numbers.
