### ISSUE TITLE
[HELP] how do you make "one window" the default menu style

### ISSUE THREAD

**Issue by wemanzoz** [danielkrupinski/Osiris#3608]

**Comment by okwannabe** [comment]
https://github.com/notgoodusename/OsirisAndExtra

**Comment by okwannabe** [comment]
or this 
https://imgur.com/MeoLOod

https://easyupload.io/xukoek

**Comment by fullyonline** [comment]
Change this to 1:
https://github.com/danielkrupinski/Osiris/blob/ea34a6b15b24b56f78f61ecc0e8f8a6118826859/Source/Config.h#L112

so this check will be false and render the GuiStyle 2:
https://github.com/danielkrupinski/Osiris/blob/ea34a6b15b24b56f78f61ecc0e8f8a6118826859/Source/GUI.cpp#L97

tadaa 😄
