### ISSUE TITLE
Modify item probability

### ISSUE THREAD

**Issue by afeer123** [danielkrupinski/Osiris#3609]
![image](https://user-images.githubusercontent.com/86306447/158060335-703e1847-2b56-4359-8065-6e2d4485479b.png)
I changed it but it didn't work help

**Comment by Metaphysical1** [comment]
you doing it wrong, learn math

**Comment by afeer123** [comment]
> you doing it wrong, learn math

？

**Comment by Metaphysical1** [comment]
> > you doing it wrong, learn math
> 
> ？

https://imgur.com/hqcA7DW
you see, me not good at math either, but I can tell this is pretty larger than 1, isn't it? you can't be a cheater and a blind, can you?
but whatever, let me guide you, you need to change all other values to 0.0f and only leave the last value as 1.0f

**Comment by notgoodusename** [comment]
> https://imgur.com/hqcA7DW
> you see, me not good at math either, but I can tell this is pretty larger than 1, isn't it? you can't be a cheater and a blind, can you?

those numbers arent bigger than 1, they have decimals in them
