### ISSUE TITLE
Specific Seeds | edit items/configure manually 

### ISSUE THREAD

**Issue by yesntsire** [danielkrupinski/Osiris#3612]
Hello,
not sure whether this belongs to the issues category but I might as well try.
Is there a way and if not is it possible to add a way to either configure items in an inventory or to configure items prior to adding them to an inventory. I'm talking about things like seed/condition to practically enable us to have things like the scar pattern on the AK Case Hardened and similar things. I believe I saw a request to add an "edit items" feature, but I cannot find it.
If this is already possible, I would appreciate help in achieving said things, as I'm afraid I either didn't see it or lack the necessary skills to do so.
Thank you in advance

**Comment by Metaphysical1** [comment]
https://github.com/danielkrupinski/Osiris/pull/3430
or else you can edit config file yourself

**Comment by wemanzoz** [comment]
> #3430 or else you can edit config file yourself

stuff broken xd

**Comment by yesntsire** [comment]
I'll close this, settling with manually editing the config myself, which is not as good but sufficient I guess.

**Comment by PaulAndreiRO** [comment]
> I'll close this, settling with manually editing the config myself, which is not as good but sufficient I guess.

how do you do that
