### ISSUE TITLE
Osiris crashing ingame on Ubuntu

### ISSUE THREAD

**Issue by IstAuchEgal** [danielkrupinski/Osiris#3613]
Im playing on the newest version of mint, I also updated Osiris but didnt change anything.

Everythings fine in the menu but when I join a game it crashes after a few minutes, when i inject after i already loaded into the server i crashes instantly.

I also tried `sudo apt update`, but still no change.

**Comment by BasicllyMaximqs** [comment]
are you sure you are building it correctly? have you tried `apt upgrade`? (with "sudo" if you arent running root of course)
try redownloading the Project and building it again

**Comment by danielkrupinski** [comment]
Make sure you set `CMAKE_BUILD_TYPE=Release` when invoking cmake.

**Comment by IstAuchEgal** [comment]
`sudo apt upgrade` didnt do anything, and i already redownloaded it again without any improvement.
Also i think cmake defaults to release if i dont say otherwise?
