### ISSUE TITLE
Gloves render bug

### ISSUE THREAD

**Issue by Tomascpp** [danielkrupinski/Osiris#3617]
![bug](https://user-images.githubusercontent.com/69238912/159156039-93069210-9d4d-4a43-a387-09baa20d7b9d.PNG)

**Comment by romphee** [comment]
I think this is just a CS:GO issue, sometimes you get Gloves/Items that're fine, sometimes you don't.
You see Legits with items that have weird Red / Green / Blue patches on items in their Inventory all the time.
I don't think theres really much that danielkrupinski can do :\

**Comment by danielkrupinski** [comment]
It's a bug of the game itself. You can use `econ_clear_inventory_images` command or delete the contents of `csgo\resource\flash\econ\weapons\cached` directory to remove those icons and they will be regenerated next time you open the game.
