### ISSUE TITLE
a mistake in danger zone

### ISSUE THREAD

**Issue by Bywnb** [danielkrupinski/Osiris#362]
My csgo.exe will crash when i play in danger zone.Have you ever had that？

**Comment by NexSqaud** [comment]
do you use last sources?

**Comment by Bywnb** [comment]
> do you use last sources?

i am sure , i release the lastest source and test just now

**Comment by NexSqaud** [comment]
Compile cheat in debug mode, attach debugger, inject using LoadLibrary. When it crashes make screenshot of call stack and post it here.

**Comment by danielkrupinski** [comment]
Should be fixed already - #324 9ac336ead2bbfc94425877f1be8423aed1a5c90b
