### ISSUE TITLE
Is there a way to add fake trade up feature in inventory changer :D

### ISSUE THREAD

**Issue by egwrl** [danielkrupinski/Osiris#3621]

**Comment by Longfei-Jiao** [comment]
There are many trade-up simulator available. If you know how to calculate the possibilities of every possible item, it is doable.

**Comment by bluebewwy** [comment]
> There are many trade-up simulator available. If you know how to calculate the possibilities of every possible item, it is doable.

The leaked source engine sdk might have some values you can grab or something
