### ISSUE TITLE
Inventory changer causing crashes?

### ISSUE THREAD

**Issue by CalvinBens** [danielkrupinski/Osiris#3629]
After moving for around half a minute, my game ends up crashing in both custom and mm. I've only been using the inventory changer as well, everything else is disabled. I've injected with extreme injector, process hacker, and csghost, crashing still happens.

**Comment by OsirisUser** [comment]
Try rebuilding Osiris because no one else is having this issue.

**Comment by McFlyest** [comment]
> Try rebuilding Osiris because no one else is having this issue.

How do you rebuild osiris?
