### ISSUE TITLE
Icon on the buy menu is incorrect

### ISSUE THREAD

**Issue by OsirisUser** [danielkrupinski/Osiris#3630]
Whenever I try to buy an m4a1-s  it shows the icon of an m4a4 and when I buy it I get an m4a1-s. If I go to my inventory, it says that the m4a4 is selected even though I get an m4a1-s.

This only happens when I use Osiris.

**Comment by danielkrupinski** [comment]
Are you using M4A4 or M4A1-S from the inventory changer?

**Comment by OsirisUser** [comment]
> Are you using M4A4 or M4A1-S from the inventory changer?

no

**Comment by OsirisUser** [comment]
https://user-images.githubusercontent.com/99542210/162605166-150c938d-2c86-42e1-9821-f2e027eb29a0.mp4

This is a video of the problem
