### ISSUE TITLE
I am a novice. I request to provide a basic tutorial for converting Chinese language. Thank you

### ISSUE THREAD

**Issue by common556** [danielkrupinski/Osiris#3635]

**Comment by common556** [comment]
I am very interested in this aspect and feel language confusion in the process of daily games

**Comment by common556** [comment]
So ask for help

**Comment by common556** [comment]
I need a detailed tutorial

**Comment by ardaevin0** [comment]
menuBarItem("Aimbot", window.aimbot);
lets say you are translating this line. What you want to do is changing the part between ""

 menuBarItem("Chinese", window.aimbot);
 doing this will simply replace the aimbot window name to chinese.

**Comment by H-xiaoH** [comment]
you need to load chinese fonts like 微软雅黑.
