### ISSUE TITLE
Stattrack Inventory Changer 

### ISSUE THREAD

**Issue by Coffyyy** [danielkrupinski/Osiris#3642]
Is it possible to get a stattrack skin without opening cases?

**Comment by DavidBumi** [comment]
> Actually yes. But you need to your Osiris config file and find the weapon you want Stattrack on it. The you just add "Stattrak" : 0 (or any number) then comma and that's it. I'm not sure if is "Stattrak" or "stattrak". Hope I helped you!

You didn't specify enough. You need to put "Stattrak" : 21 for example below "Paint Kit".

**Comment by savvy010** [comment]
> Is it possible to get a stattrack skin without opening cases?

yes! go to your config, and if you've already opened some cases and opened a stattrak(doesnt need to be any specifc skin), copy the text from that stattrak, and paste it right below in the same spot for the other skin. if you need help please contact me at savvy#6792, i'd be happy to help!
