### ISSUE TITLE
Default knife swapper

### ISSUE THREAD

**Issue by yukrix** [danielkrupinski/Osiris#3643]
im sorry, this isnt an issue, just a request because i dont know what im doing

im trying to be able to use the CT default knife while on T side, and vice versa. if anyone can slide some code to paste over that can allow this option for me, I would appreciate it very much 🙂

sorry again if this is the wrong place to put this

**Comment by propane** [comment]
why?

**Comment by yukrix** [comment]
> why?

because i like it. obviously its not worth being implemented as a feature, but i personally want it
