### ISSUE TITLE
C++ library error

### ISSUE THREAD

**Issue by Gordoxzxx** [danielkrupinski/Osiris#3647]
![unknown](https://user-images.githubusercontent.com/104533417/165636574-e84c6ffb-8124-4f18-9022-4daf9eace909.png)

**Comment by Metaphysical1** [comment]
update

**Comment by Gordoxzxx** [comment]
> update

I'm using hackplex.cc as the injector and Osiris alrd comes in it

**Comment by Patrixsin** [comment]
Build in Release | x86 Mode, not Debug | x86 Mode

**Comment by Gordoxzxx** [comment]
> Build in Release | x86 Mode, not Debug | x86 Mode

How do i do that

**Comment by HowToMakeFaceitAB** [comment]
> > Build in Release | x86 Mode, not Debug | x86 Mode
> 
> How do i do that

Hello, if you want to do that, all you simply need to do is just change the build mode from debug to release

https://www.eclipse.org/4diac/documentation/html/installation/img/VSreleaseDebug.png

view this picture as reference
