### ISSUE TITLE
Fake latency + extended backtrack

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#3648]
Add extended backtrack to the base, I already added myself but I think it would be a good idea.
Extended backtrack works simply as the name implies, it extends the backtrack, this is done by using fake latency which extends the max time / amount of ticks you can abuse lagcomp for. All we need to do is simply abuse lagcomp.

**Comment by OzymoGit** [comment]
actually a good thing to add. I do remember this #1802
