### ISSUE TITLE
Inventory Changer - Feature improvement

### ISSUE THREAD

**Issue by DipsiTheCreeper** [danielkrupinski/Osiris#3651]
Osiris is the only cheat I know that actually adds items to the inventory (they're not sellable or anything like that but still- amazing feature, you're able to show off.)

_While using the changer, I've came across some difficulties using it - a simple few lines of code could drastically improve it, so here is what I had in mind._

**1. Ability to have a some sort of menu for each item. (Stickers, Cases, Keys, Agents Weapons (sorted into multiple tabs -> Pistols -> Weapon Name)** _Let's say I only want to see weapons available in the game, I click the weapons tab. I'd like to see the red rarity of weapons. No problem, I divide them by rarity and check them out._

2. **More options on current inventory (when you added a lot of items (1000+), it's pretty hard to manage them without a search function).** _So basically, a search function & sorting function would be nice, eg. we can search the currently modified inventory by Osiris by rarity, name, weapon type, StatTrak and so on._

**3. Option to add all items to your inventory with one click (able to be customized; add weapon skins, gloves, knives of selected rarity only etc**. _Example would be adding all gloves of red rarity to your inventory with one click, or adding red & pink rarity items with one click._

**4. The weapon modifiers. Probably the most wanted feature in the inventory changer.** _What if you wanted to test the float values directly from CS:GO instead of going to some websites that do this? Customizable paint seed too. A perfect Case hardened Karambit ftw! StatTrak would also be an option too so we can directly add StatTrak weapons instead of going to the config file._

_**Down here are some features which are not required at the moment, but could potentially improve the changer. (Not sure if some of them are possible, tho.**_

_1. Ability to hear agent's voice lines when having them equipped._

_2. A remastered GUI of the inventory changer, it'd be bigger and easier to manage. As I mentioned, it should contain all the main features I requested:_

_3. See other Osiris' users, their skins, agents and such._

_4. Fake ranks & prime that is showed in the lobby and in-game (client sided, mainly for flexing & legitness)_

Thanks for reading this, I hope someone could try to implement this other than the developer as I'm sure he is pretty busy and I don't wanna ask for too much, please work on this in your free time only <3

**Comment by danielkrupinski** [comment]
> I don't think the third one will ever be possible unless Osiris connects users to a server to distribute data.

I think that an extra server isn't required as inventory data won't change often. In-game chat could be used to broadcast information about skins.

**Comment by lewwdcat** [comment]
I've implemented what I can only describe as an experiment LOL.
Anyways, here's the filtering in a basic form.
https://github.com/lewwdcat/Osiris/commit/fc29103ef9a94d49c18db1c3808e9ea1d1f95de3

**Comment by lewwdcat** [comment]
Filtering: https://github.com/lewwdcat/Osiris/commit/e2e0b0c9298818a8c9446a94869b4bade430c7b7

**Comment by Lkuiri** [comment]
3rd would be really cool since there are no free sources available with "Shared Skin Changer".

**Comment by IceBL0X** [comment]
can anyone do the The weapon modifiers.
