### ISSUE TITLE
Osiris Menu Only Shows Up in Csgo - Insecure Mode (Doesn't Open on Secured Client)

### ISSUE THREAD

**Issue by greevak** [danielkrupinski/Osiris#3652]
As stated,
![image](https://user-images.githubusercontent.com/38337258/166093282-aa065b20-177b-49c2-969c-d858ee644c8f.png)
Menu only shows up when i have (-insecure) in my launch options.

I'm using the vanilla version of osiris incase my edited version doesn't work,
Iv'e been pasting osiris for the past 3 years, so i know all the stuff about optimization, Release 86, i even add and delete features by myself, but this is my first time facing this issue, any ideas?

I tried many other injectors beside my own that i have written in python,
Shtreeba doesn't work, it injects but nothing ahows up just like my injector.

One injector gives me this message:
![image](https://user-images.githubusercontent.com/38337258/166093346-d201fc81-65d4-4596-95f5-d0b1b5a5966a.png)

But that's for it, I'm very confused on why i can't use the cheat on the secured client

**Comment by Patrixsin** [comment]
have u checked with another injector?

**Comment by greevak** [comment]
> have u checked with another injector?

I did actually, i used 4 different injectors
Mat you suggest one that works for you?
I have check the post about injectors btw

**Comment by Patrixsin** [comment]
weird, i use csghost and works everything fine

**Comment by KubaMorinkton** [comment]
maybe u have vanguard or faceit or shit like that?

**Comment by greevak** [comment]
> maybe u have vanguard or faceit or shit like that?

I do, However i'm aware they are not active, and doesn't prevent osiris from running,
As i had no issues with older versions of osiris, Or cs go in any manner.

**Comment by greevak** [comment]
3

> weird, i use csghost and works everything fine

I used Csghost and it works fine!
But the catch is, 5 minutes into the game and the game crashes.. Still don't know why

**Comment by Ruqen** [comment]
Can you try to inject another DLL into process?

**Comment by greevak** [comment]
> 

Other DLLs Work Fine, And with my own injector
For osiris i need external injectors Csghost. And it Still crashes

**Comment by greevak** [comment]
Update:
1- I have fixed the crashing issue by updating osiris to the latest version, (3/5/2022 Patch), Patches before that one couldn't work. And that new patch was 18 hours ago, Omegalul?
2- Osiris do work on secure mode too, but only if i use other injectors, not my personal one.
Perhaps cs:go update related problem, but i don't mind that change, i'll fix my injector.
3- Now a weird issue is caused after the last update by osiris, my hands FOV is always at a very high amount, and i can't reduce it. even using the misc tab. 
![image](https://user-images.githubusercontent.com/38337258/166454205-1eb13473-efa2-4b92-b06c-905e43768d48.png)
Like this one, but even higher and it prevents me from playing.
4- One other issue is: All weapons are always on inspecting mode, Means; during the entire game the gun is inspecting itself and prevent me from viewing in a good way.

**Comment by Ruqen** [comment]
Okay so I have a few theories:

1 - Your injector is broken, if you are using a VAC bypass, update it. Or use https://github.com/zyhp/vac3_inhibitor or https://github.com/Jackbail4/VAC-Bypass if you don't want to mess with the bypass.

2 - Are you sure you are using Release | x86 while compiling? I'm using my own injector, compiling in release and everything works fine.

3 - What is your Windows version?

**Comment by Ruqen** [comment]
> I'm Not using VAC Bypasser, But since the last updates to cs go for the past year, did the injection method change? I haven't been keeping up with that.

You should do that since your injector is really old and there is a possibility VAC uses integrity check to remove your external DLL from their program.

> I'm using a modifed version of https://github.com/bananasss00/Rando-Injector

Oh, that looks really old. Make sure you use a manual map injector to get the full experience. This looks really cool and some of my friends use it: https://github.com/b1scoito/cozinha_loader it also has a full VAC bypass.

**Comment by greevak** [comment]
Update:
Messing with the misc.cpp file got me somewhere, now the FOV is fixed.

The only remaning problem is a good injector with source code, or just the safest option.
And new ways to improve the cheat security, Junk code doesn't work anymore iirc.
Thank you.

**Comment by Ruqen** [comment]
> One more remaning problem is a good injector with source code, or just the safest option. And new ways to improve the cheat security, Junk code doesn't work anymore iirc. Thank you.

I already provided a good injector with a decent VAC bypass.
