### ISSUE TITLE
InventoryChanger gloves turned black

### ISSUE THREAD

**Issue by xillaLove** [danielkrupinski/Osiris#3660]
After adding gloves from InventoryChanger, the gloves turned black (see the video below)

additional information:
built & running osiris on linux (Arch) & injected using gdb

https://user-images.githubusercontent.com/102897181/167049205-7cd733d4-2f3f-458f-8744-217fbb9928a4.mp4

**Comment by KurastikO** [comment]
Force update. 

It usually fixes these kinds of bugs.

**Comment by xillaLove** [comment]
@KurastikO i did, it didn't work.

**Comment by KurastikO** [comment]
Hmm, maybe try doing it on a higher resolution?

**Comment by xillaLove** [comment]
It's not working, i tried changing texture detail to high, still not working

https://user-images.githubusercontent.com/102897181/167054943-86250212-b820-49b4-9ae9-5c2aa9638188.mp4

**Comment by xillaLove** [comment]
ah i see where the problem is. this is a non osiris problem (my bad)
[after reading this](https://github.com/ValveSoftware/csgo-osx-linux/issues/2102) it's amd problem(?) 
with `-vulkan` gloves does work, but osiris doesn't (it's crashing)

![image](https://user-images.githubusercontent.com/102897181/167063009-a7ba4a3d-8a86-4593-b339-689bbc3deedc.png)

oh well, unlucky i guess. closing this now because non osiris problem
