### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by OllumHD** [danielkrupinski/Osiris#3665]
Hello,

I can't build osiris anymore, it worked like 2 days ago, i tried using older builds of osiris, redownloading osiris, reinstalling visual studio, etc. I wanna know if this happened/is happening to anyone else or if I did something wrong, the only thing I remember doing that might've caused this is installing the DirectX SDK, that was a bit longer ago tho.
Anyways, these are my logs

I'm using VS2022, WinSDK 10.0.19041, v143 (tried this with VS2019 v142 as well, same error)

------------------------------------

Build started...
1>------ Build started: Project: Osiris, Configuration: Release Win32 ------
1>compilation header save succeeded; see C:\Users\xxxx\Desktop\Osiris-master\Source\Resources\Shaders\Build\default_vs.h
1>pch-c.c
1>pch.cpp
1>autofit.c
1>ftbase.c
1>ftbitmap.c
1>ftdebug.c
1>ftglyph.c
1>ftinit.c
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(55,5): error C2371: 'FT_Int64': redefinition; different basic types (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\vcpkg\installed\x86-windows\include\freetype\config\integer-types.h(244): message : see declaration of 'FT_Int64' (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>ftsynth.c
1>ftsystem.c
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(305,8): error C2223: left of '->lo' must point to struct/union (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>cff.c
1>psaux.c
1>pshinter.c
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(306,8): error C2223: left of '->hi' must point to struct/union (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(357,13): error C2223: left of '->lo' must point to struct/union (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(357,21): error C2223: left of '->lo' must point to struct/union (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(358,13): error C2223: left of '->hi' must point to struct/union (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(358,21): error C2223: left of '->hi' must point to struct/union (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(358,36): error C2223: left of '->lo' must point to struct/union (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(360,8): error C2223: left of '->lo' must point to struct/union (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(361,8): error C2223: left of '->hi' must point to struct/union (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(446,13): error C2224: left of '.hi' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(447,13): error C2224: left of '.lo' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(452,18): error C2224: left of '.hi' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>psnames.c
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(452,35): error C2224: left of '.lo' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(453,49): error C2224: left of '.hi' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(453,58): error C2224: left of '.lo' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(453,42): error C2198: 'ft_div64by32': too few arguments for call (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(495,18): error C2224: left of '.hi' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(495,35): error C2224: left of '.lo' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(496,49): error C2224: left of '.hi' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(496,58): error C2224: left of '.lo' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(496,42): error C2198: 'ft_div64by32': too few arguments for call (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(639,12): error C2224: left of '.hi' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(640,12): error C2224: left of '.lo' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(641,13): error C2224: left of '.hi' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(642,13): error C2224: left of '.lo' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(645,30): error C2224: left of '.hi' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(645,39): error C2224: left of '.lo' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(645,23): error C2198: 'ft_div64by32': too few arguments for call (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(1024,15): error C2224: left of '.hi' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(1024,23): error C2224: left of '.hi' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(1026,20): error C2224: left of '.hi' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(1026,28): error C2224: left of '.hi' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(1028,20): error C2224: left of '.lo' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(1028,28): error C2224: left of '.lo' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(1030,20): error C2224: left of '.lo' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftcalc.c(1030,28): error C2224: left of '.lo' must have struct/union type (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>raster.c
1>sfnt.c
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftglyph.c(457,35): warning C4028: formal parameter 2 different from declaration
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftglyph.c(458,35): warning C4028: formal parameter 3 different from declaration
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftglyph.c(538,39): warning C4028: formal parameter 3 different from declaration
1>smooth.c
1>truetype.c
1>buffer.c
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\psaux\afmparse.c(671,3): error C2061: syntax error: identifier 'afm_compare_kern_pairs' (compiling source file ..\Dependencies\freetype\src\psaux\psaux.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\psaux\afmparse.c(671,3): error C2059: syntax error: ';' (compiling source file ..\Dependencies\freetype\src\psaux\psaux.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\psaux\afmparse.c(671,37): error C2059: syntax error: '<parameter-list>' (compiling source file ..\Dependencies\freetype\src\psaux\psaux.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\psaux\afmparse.c(772,42): error C2065: 'afm_compare_kern_pairs': undeclared identifier (compiling source file ..\Dependencies\freetype\src\psaux\psaux.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\psaux\afmparse.c(772,42): warning C4047: 'function': '_CoreCrtNonSecureSearchSortCompareFunction' differs in levels of indirection from 'int' (compiling source file ..\Dependencies\freetype\src\psaux\psaux.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\psaux\afmparse.c(772,19): warning C4024: 'qsort': different types for formal and actual parameter 4 (compiling source file ..\Dependencies\freetype\src\psaux\psaux.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftrfork.c(171,3): error C2061: syntax error: identifier 'ft_raccess_sort_ref_by_id' (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftrfork.c(171,3): error C2059: syntax error: ';' (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftrfork.c(171,42): error C2059: syntax error: '<parameter-list>' (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\base\ftrfork.c(297,26): error C2061: syntax error: identifier 'FT_CDECL' (compiling source file ..\Dependencies\freetype\src\base\ftbase.c)
1>hde32.c
1>hde64.c
1>hook.c
1>trampoline.c
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\pngshim.c(297,49): error C2440: 'function': cannot convert from 'void (__vectorcall *)(png_structp,png_const_charp)' to 'png_error_ptr' (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\pngshim.c(297,35): warning C4024: 'png_create_read_struct': different types for formal and actual parameter 3 (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\pngshim.c(298,52): error C2440: 'function': cannot convert from 'void (__vectorcall *)(png_structp,png_const_charp)' to 'png_error_ptr' (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\pngshim.c(298,35): warning C4024: 'png_create_read_struct': different types for formal and actual parameter 4 (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\pngshim.c(319,61): error C2440: 'function': cannot convert from 'void (__vectorcall *)(png_structp,png_bytep,png_size_t)' to 'png_rw_ptr' (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\pngshim.c(319,36): warning C4024: 'png_set_read_fn': different types for formal and actual parameter 3 (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\pngshim.c(410,61): error C2440: 'function': cannot convert from 'void (__vectorcall *)(png_structp,png_row_infop,png_bytep)' to 'png_user_transform_ptr' (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\pngshim.c(410,44): warning C4024: 'png_set_read_user_transform_fn': different types for formal and actual parameter 2 (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\pngshim.c(415,66): error C2440: 'function': cannot convert from 'void (__vectorcall *)(png_structp,png_row_infop,png_bytep)' to 'png_user_transform_ptr' (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\pngshim.c(415,44): warning C4024: 'png_set_read_user_transform_fn': different types for formal and actual parameter 2 (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\sfwoff.c(70,3): error C2061: syntax error: identifier 'compare_offsets' (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\sfwoff.c(70,3): error C2059: syntax error: ';' (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\sfwoff.c(70,30): error C2059: syntax error: '<parameter-list>' (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\sfwoff.c(248,31): error C2065: 'compare_offsets': undeclared identifier (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\sfwoff.c(248,31): warning C4047: 'function': '_CoreCrtNonSecureSearchSortCompareFunction' differs in levels of indirection from 'int' (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\sfwoff.c(248,15): warning C4024: 'qsort': different types for formal and actual parameter 4 (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\sfwoff2.c(105,3): error C2061: syntax error: identifier 'compare_tags' (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\sfwoff2.c(105,3): error C2059: syntax error: ';' (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\sfwoff2.c(105,27): error C2059: syntax error: '<parameter-list>' (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\sfwoff2.c(2210,28): error C2065: 'compare_tags': undeclared identifier (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\sfwoff2.c(2210,28): warning C4047: 'function': '_CoreCrtNonSecureSearchSortCompareFunction' differs in levels of indirection from 'int' (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>C:\Users\olekw\Desktop\CSGO CHEATS trollface\Osiris-master\Dependencies\freetype\src\sfnt\sfwoff2.c(2210,15): warning C4024: 'qsort': different types for formal and actual parameter 4 (compiling source file ..\Dependencies\freetype\src\sfnt\sfnt.c)
1>Done building project "Osiris.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by OllumHD** [comment]
Happens with OsirisInventory as well, i have no issues compiling anything else

**Comment by KurastikO** [comment]
Are you using Debug | x86 instead of Release | x86?

**Comment by Patrixsin** [comment]
> Are you using Debug | x86 instead of Release | x86?

Exactly second line of log says:
1>------ Build started: Project: Osiris, Configuration: Release Win32 ------

**Comment by OllumHD** [comment]
> Are you using Debug | x86 instead of Release | x86?

both come out with an error i havent checked if its the same error but im not sure if it matters

**Comment by MJMODZZ** [comment]
> 

- MAke sure have all required C++ Packs installed,
- Make sure having Debug/ Release | x86

**Comment by rorosin** [comment]
I have same error, did you resolve it?
