### ISSUE TITLE
Detected OSIRIS

### ISSUE THREAD

**Issue by deepzking** [danielkrupinski/Osiris#3677]
I was using Osiris with a VAC bypass. Was hacking for 2 hours and i got banned

"Global Cooldown"
"This account is Permanently Untrusted"

**Comment by Patrixsin** [comment]
too high max angle delta

**Comment by autumnlikescode** [comment]
yeah "untrust" doesnt mean its detected

**Comment by lewwdcat** [comment]
This can mean a multitude of things. It could happen due to certain features being enabled like choking packets in competitive play or enabling aimbot with low smoothing that snaps.

**Comment by OzymoGit** [comment]
its a server thing, there is something wrong with your setting

**Comment by Ecstxsy** [comment]
> This can mean a multitude of things. It could happen due to certain features being enabled like choking packets in competitive play or enabling aimbot with low smoothing that snaps.

Personally, ive used osiris on 3 different accounts as of right now. My aimbot is set to pretty much as blatant as it ever could be, hitting instant heads while looking 90 degrees away from people. None of the accounts have been banned, the first one even after a week.
