### ISSUE TITLE
Clan tag bug

### ISSUE THREAD

**Issue by tirziz** [danielkrupinski/Osiris#368]
It is not showing origin my clan tag even I dont use clan tag changer,

**Comment by Bywnb** [comment]
i think its not a bug

**Comment by NexSqaud** [comment]
I think this will fix this problem:
In misc.h
```c++
constexpr void setClanTag(const char* clanTag) noexcept
{
    if (strlen(clanTag) != 0) 
    { 
        memory.setClanTag(clanTag, clanTag); 
    }
}
```

**Comment by tirziz** [comment]
And this function keep update clan tag like every tick, It might be dangerous if u play in community servers

**Comment by danielkrupinski** [comment]
> And this function keep update clan tag like every tick, It might be dangerous if u play in community servers

It updates clan tag every 0.6 s.

**Comment by danielkrupinski** [comment]
Should be fixed now.
