### ISSUE TITLE
opening source code for osiris and vac bypass in visual studio not allowing for compiling

### ISSUE THREAD

**Issue by spoooked** [danielkrupinski/Osiris#3686]
basically whenever I try and open either of the .sln files provided in the zip they show up in the solution explorer as (file name) (unloaded)
i have tried running visual studio as an administrator, but i cant seem to find a solution to this problem.

**Comment by KurastikO** [comment]
That's weird. Try downloading the latest version of Visual studio.

**Comment by autumnlikescode** [comment]
If you haven't fixed it yet, can you try reloading the project by;
Right Click Solutions File
Choose Reload Project

**Comment by spoooked** [comment]
I managed to fix it. Turns out I didnt have a build package in Visual Studio fully installed
