### ISSUE TITLE
Add Fake Level & Rank (Lobby only)

### ISSUE THREAD

**Issue by DipsiTheCreeper** [danielkrupinski/Osiris#3688]
It would be great to perhaps have a feature which spoofs ranks or/and levels. I think this is possible, also I'm pretty sure that others can see it as well if done correctly, although in-game would be impossible and it would still match you with players at your original rank. 

Pretty much, any player that joins your lobby can see that you are global elite and such. Even if it's client sided, I'd be happy because I can still show off.

**Comment by Patrixsin** [comment]
possible and https://github.com/danielkrupinski/Osiris/pull/2503

**Comment by milkboy77** [comment]
Verry much! I'm also looking forward to this feature.
