### ISSUE TITLE
Eye traces / barrel esp is missing

### ISSUE THREAD

**Issue by alerion921** [danielkrupinski/Osiris#3689]
Can someone add code for the eye traces its in the old esp code but when i try to render it it crashes on new entities and i cant get eyeangles out of entitydata struct, can someone help with that ?

**Comment by alerion921** [comment]
Old code for refrence only

~~ 
 ​static​ ​void​ ​renderEyeTraces​(Entity* entity, ​const​ ​decltype​(config.esp[​0​])& config) ​noexcept 
 ​{ 
 ​    ​if​ (config.​eyeTraces​) { 
 ​        ​constexpr​ ​float​ maxRange{ ​8192​.​0f​ }; 
  
 ​        ​auto​ eyeAngles = entity->​eyeAngles​(); 
 ​        Vector viewAngles{ ​cos​(​degreesToRadians​(eyeAngles.​x​)) * ​cos​(​degreesToRadians​(eyeAngles.​y​)) * maxRange, 
 ​                           ​cos​(​degreesToRadians​(eyeAngles.​x​)) * ​sin​(​degreesToRadians​(eyeAngles.​y​)) * maxRange, 
 ​                          -​sin​(​degreesToRadians​(eyeAngles.​x​)) * maxRange }; 
 ​        ​static​ Trace trace; 
 ​        Vector headPosition{ entity->​getBonePosition​(​8​) }; 
 ​        interfaces.​engineTrace​->​traceRay​({ headPosition, headPosition + viewAngles }, ​0x46004009​, { entity }, trace); 
 ​        Vector start, end; 
 ​        ​if​ (​worldToScreen​(trace.​startpos​, start) && ​worldToScreen​(trace.​endpos​, end)) { 
 ​            interfaces.​surface​->​setDrawColor​(config.​eyeTracesColor​, ​255​); 
 ​            interfaces.​surface​->​drawLine​(start.​x​, start.​y​, end.​x​, end.​y​); 
 ​        } 
 ​    } 
 ​} 
 ~~

**Comment by FasTerCG** [comment]
i got the same problem, can you share your code of eye traces of course only if it is possible :)
