### ISSUE TITLE
Gamesense menu

### ISSUE THREAD

**Issue by flamed0g** [danielkrupinski/Osiris#369]
Is there someone that could make this menu the same as Gamesense/Skeet their menu? Or just a better menu in general?

I am willing to pay, if someone could do this for me. I do not have enough experience for that.

Communication via Discord, if possible.

Also: I do have a source of Gamesense ImGui, but the features/config links should be converted ofcourse, so I can provide that source. If someone can do this for me.

**Comment by flamed0g** [comment]
I do have a source of Gamesense ImGui, but the features/config links should be converted ofcourse, so I can provide that source. If someone can do this for me.

**Comment by Mufinekkk** [comment]
Close.

**Comment by NexSqaud** [comment]
just make it urself if you need this

**Comment by tirziz** [comment]
"I'll pay"

**Comment by astron-dev** [comment]
Why dont you just do it yourself? Just copy&paste and rename some things

**Comment by Bywnb** [comment]
just make it urself if you need this

**Comment by effex1337** [comment]
@flamed0g contact me on discord @ EffeX#1337 if you're still interested.

**Comment by Shaxzy** [comment]
Or you can just get good get gamesense like me. No need to paste a gamesense menu if you have real gamesense lol

**Comment by effex1337** [comment]
"get good get gamesense"
Not everyone is able to get in :(
But i think it's pretty overrated as esoterik doesn't care about it
I don't see any gs vids on yo channel tho ¯\_(ツ)_/¯

**Comment by flamed0g** [comment]
> get good get gamesense

Not invited.

**Comment by Shaxzy** [comment]
@effex1337 I have been a member for a while now lol. There is 2 videos on my channel eventhough they’re trash. You can check screens on my steam profile if you still don’t believe me. 
https://steamcommunity.com/id/ShaxzyHVHLegenden/screenshots/
Now watch your mouth

**Comment by effex1337** [comment]
Why so toxic :(
I never said you're a newcomer i know you're og but i didn't see any gamesense vids(in title at least)
Only thing that has gs title is the last day with gs.

**Comment by Shaxzy** [comment]
There’s another video I posted a few months ago I believe «Bulletproof ft gamesense» idk. Sorry didn’t mean to be toxic pal.

**Comment by linkupbiz** [comment]
>did your discord tag changer?
