### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by coolst3r** [danielkrupinski/Osiris#3690]
CMake Error at /usr/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):                                                           
  Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)  
Call Stack (most recent call first):                                         
  /usr/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)                                                          
  /usr/share/cmake-3.23/Modules/FindFreetype.cmake:162 (find_package_handle_standard_args)                                                                
  Dependencies/imgui/CMakeLists.txt:15 (find_package)

**Comment by floydGG** [comment]
oh no

**Comment by Xtendera** [comment]
I believe this is a Windows cheat and cannot be compiled on macOS or Linux.
