### ISSUE TITLE
Can't open cases because of X-ray feature

### ISSUE THREAD

**Issue by ZegoFr34ks** [danielkrupinski/Osiris#3697]
Valve added an X-Ray feature a while ago for French people only, so it always shows me to scan the case before opening it. But I can't scan it (because of connection error), and can't open the case (because of the x-ray feature).

**Comment by Patrixsin** [comment]
People living in Netherland either cannot open cases

**Comment by Patrixsin** [comment]
People living in Netherland cannot open cases either

**Comment by danielkrupinski** [comment]
X-Ray Scanner is now usable in [xray-scanner](https://github.com/danielkrupinski/Osiris/tree/xray-scanner) branch.

**Comment by ZegoFr34ks** [comment]
Working! Thank you very much!
