### ISSUE TITLE
Errors when adding Misc Features

### ISSUE THREAD

**Issue by vexo7** [danielkrupinski/Osiris#3698]
Im getting 61 errors (LNK2005) when im trying to add misc features into gui.cpp
does anyone know how to fix this?
![image](https://user-images.githubusercontent.com/71598720/173161251-62b94cab-5858-41ea-91d4-66e579c0b4f5.png)
![image](https://user-images.githubusercontent.com/71598720/173161603-65f559a1-9af0-4034-a7c8-00726fc955dc.png)
^^ im trying to add bhop into a new menu

**Comment by Patrixsin** [comment]
Tip: 
if u use function from Imgui namespace starts with Begin, rember to close this with End. I mean
```
ImGui::BeginChild("Misc");
ImGui::Checkbox("bhop", &miscConfig.bunnyHop);
ImGui::EndChild("");
```
Backing to problem, Do u call DrawMenu fuction out of Misc.cpp file?

**Comment by FuzzCS** [comment]
> Also dont include .cpp files. if u already included Misc.cpp in GUI.cpp i guess, remove then

 i need to include misc.cpp, otherwise miscConfig isnt defined

**Comment by Patrixsin** [comment]
> > Also dont include .cpp files. if u already included Misc.cpp in GUI.cpp i guess, remove then
> 
> i need to include misc.cpp, otherwise miscConfig isnt defined

by including Misc.cpp u got links error LNK2005
