### ISSUE TITLE
Butterfly Knife Issue

### ISSUE THREAD

**Issue by milkteaaa** [danielkrupinski/Osiris#3700]
Upon equipping a butterfly knife, it would randomly play the left mouse click animation
Inspecting the knife would drag the viewmodel offscreen, and can only be brought back by clicking LMB or RMB

Is there a way to fix it or not?

**Comment by KyeOnDiscord** [comment]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/326785-automated-sequence-fix-knife-model-changer.html

**Comment by milkteaaa** [comment]
> https://www.unknowncheats.me/forum/counterstrike-global-offensive/326785-automated-sequence-fix-knife-model-changer.html

I've found this while searching for a solution to the problem, where would I implement this?

**Comment by n4vi98** [comment]
> > https://www.unknowncheats.me/forum/counterstrike-global-offensive/326785-automated-sequence-fix-knife-model-changer.html
> 
> I've found this while searching for a solution to the problem, where would I implement this?

+1
