### ISSUE TITLE
Config save problem

### ISSUE THREAD

**Issue by noping5811** [danielkrupinski/Osiris#3701]
Hi. I have written cfg name then create but it has not been created juts pop-on and off? Thank you.

**Comment by DipsiTheCreeper** [comment]
Please disable "Controlled Folder Access" in Windows Security. If that's not the case, check for any anti-virus software which protects the encryption of some common locations, eg. C:/Users/Documents, C:/Users/Pictures etc. 

That was my issue and it's how I got it fixed.
