### ISSUE TITLE
Build inventory changer

### ISSUE THREAD

**Issue by kirill-21** [danielkrupinski/Osiris#3704]
Is it possible to build only inventory changer?

**Comment by kirill-21** [comment]
I know that there's a separate source https://github.com/danielkrupinski/OsirisInventory, but it's outdated

**Comment by kirill-21** [comment]
> https://www.youtube.com/watch?v=3w3zSv_w-ug
> 
> Using positive IQ , you can achieve your objective . Remove everything except the bits you need.

Surprisingly, I didn't think there could be clowns here

**Comment by Patrixsin** [comment]
Why do u need only inv changer? just dont use other features. What's the problem?
