### ISSUE TITLE
dll compiled size

### ISSUE THREAD

**Issue by n4vi98** [danielkrupinski/Osiris#3705]
hey guys im new to this please guide me i manage to build the dll for this and the complete dll size is 7mb. is this right? i downloaded a different dll in cheater.fun its under 2mb. please correct me if I did miss something in VS Studio

**Comment by Patrixsin** [comment]
make sure u compiled osiris in release mode, not in debug

**Comment by n4vi98** [comment]
oh ok thanks!

**Comment by n4vi98** [comment]
ok it works tysm
