### ISSUE TITLE
Cue

### ISSUE THREAD

**Issue by Shuvi-Moro** [danielkrupinski/Osiris#3707]
Can anyone tell me how backtracking works in code?
I want to write an aim that will trigger on backtrack.
Also, I would be glad if you could throw a link to an amhibot with multipoint.

**Comment by codecheck01** [comment]
> It interlaces the DWOD unique backtrack tick to then bypass the iterator non-stop conforming HRT BRATTTT mode. This can be easily bypassed by changing the DWORD for a std::byte class which can then interlace all of the ticks with a modulated __shidcall. Hope this helps 🥺

Not funny at all, nice shitpost.
