### ISSUE TITLE
i want to Chineseization it

### ISSUE THREAD

**Issue by chinabestcountry** [danielkrupinski/Osiris#3708]
i want to Chineseization it.Can somebody tell me where the language file is?
如果有国人想一起来，T__A__T#1370

**Comment by LaxdalGe** [comment]
支持！

**Comment by LaxdalGe** [comment]
有些功能到现在我还没有弄懂

**Comment by Cyk-Fad** [comment]
加我Q 785249313 我有资深经验做这个

**Comment by milkboy77** [comment]
GUI.cpp以及cheat目录下的诸如EnginePrediction.cpp文件。
您只需修改“ESP”成“透视”，高级保存选项改为unicode。
构建即可。

**Comment by chinabestcountry** [comment]
![image](https://user-images.githubusercontent.com/94364764/174524637-cb9aaba7-a512-4a11-8577-b4f2164d07e8.png)
但是我并没有找到例如‘aimbot’一类的字符串

**Comment by chinabestcountry** [comment]
![image](https://user-images.githubusercontent.com/94364764/174524754-b908774d-3f25-4f94-add2-fb5e92054c19.png)
是指这些吗？

**Comment by milkboy77** [comment]
![image](https://user-images.githubusercontent.com/106000834/174524879-680a9076-e0e6-4428-9ed5-04481ced1663.png)

**Comment by milkboy77** [comment]
这是那个横栏最开始的界面的Aimbot

**Comment by milkboy77** [comment]
> ![image](https://user-images.githubusercontent.com/94364764/174524754-b908774d-3f25-4f94-add2-fb5e92054c19.png) 是指这些吗？

你这些是开启那个AIMBOT窗口以后的界面

**Comment by milkboy77** [comment]
Osiris拥有两个风格，一个是最顶部的横栏模式，还有一个单窗口模式，注意最开始的定义就行。(我也不知道那个是不是应该叫横栏XD)

**Comment by chinabestcountry** [comment]
感激不尽，它成功的显示了中文:)

**Comment by chinabestcountry** [comment]
但gui.cpp里只有一些横栏的内容，没有其他类如anti-aim的内容

**Comment by milkboy77** [comment]
> 但gui.cpp里只有一些横栏的内容，没有其他类如anti-aim的内容

去Hack目录下寻找对应功能，例如anti-aIm.cpp
![image](https://user-images.githubusercontent.com/106000834/174525964-331aff33-6a7d-4fa0-ace5-7a73bc26b3a9.png)

**Comment by chinabestcountry** [comment]
aimbot中一些变量例如pistols手枪该如何更改？plz

**Comment by milkboy77** [comment]
![image](https://user-images.githubusercontent.com/106000834/174526635-26e994ad-b607-40b8-bacb-311589670736.png)
你想说Aimbot窗口下的关于手枪一类的？
他们如果能在GUI.cpp下找到，下面其实就有关于他们内容。

**Comment by chinabestcountry** [comment]
是的。如果我想修改pistols为手枪，我是不是只需要更改'all\0pistols'等为中文即可

**Comment by milkboy77** [comment]
> 是的。如果我想修改pistols为手枪，我是不是只需要更改'all\0pistols'等为中文即可

是的，但请不要删除\0:)

**Comment by chinabestcountry** [comment]
![image](https://user-images.githubusercontent.com/94364764/174527455-6c632fc2-c01e-445a-bf03-03eefaa0f0af.png)
这个变量是否需要改为中文？

**Comment by milkboy77** [comment]
> ![image](https://user-images.githubusercontent.com/94364764/174527455-6c632fc2-c01e-445a-bf03-03eefaa0f0af.png) 这个变量是否需要改为中文？

NO。:)
