### ISSUE TITLE
CSGO updated and 2 errors

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#3709]
- Failed to find pattern # 73
- Failed to find pattern # 74

**Comment by n4vi98** [comment]
yes i have that error too hopefully they will fix it.

**Comment by yxb6846928** [comment]
Failed to find pattern # 68
Failed to find pattern # 69

I haven't updated since April 26th. .
The error code is 68、69...

**Comment by NGGYOK** [comment]
yes boom timer will not work

**Comment by wjh060828** [comment]
I need a new osiris.dll to play game.   who can give me?
sorry,bad English

**Comment by danielkrupinski** [comment]
Upda

**Comment by danielkrupinski** [comment]
Updated

**Comment by n4vi98** [comment]
> I need a new osiris.dll to play game. who can give me? sorry,bad English

i can just message me

**Comment by wjh060828** [comment]
> > I need a new osiris.dll to play game. who can give me? sorry,bad English
> 
> i can just message me

message you?what to do?can you speak Chinese？

**Comment by wjh060828** [comment]
> > I need a new osiris.dll to play game. who can give me? sorry,bad English
> 
> i can just message me

i dont know how to message you，im Chinese

**Comment by n4vi98** [comment]
> > > I need a new osiris.dll to play game. who can give me? sorry,bad English
> > 
> > 
> > i can just message me
> 
> i dont know how to message you，im Chinese

mail me n4vi1998@gmail.com

**Comment by wjh060828** [comment]
> > > > I need a new osiris.dll to play game. who can give me? sorry,bad English
> > > 
> > > 
> > > i can just message me
> > 
> > 
> > i dont know how to message you，im Chinese
> 
> mail me [n4vi1998@gmail.com](mailto:n4vi1998@gmail.com)

OK，look the gmail，i mail you
