### ISSUE TITLE
Name changer and Visible check?

### ISSUE THREAD

**Issue by shakeit1337** [danielkrupinski/Osiris#371]
hey, do you want to add name changer and visible check?

**Comment by NexSqaud** [comment]
visible check of what?

**Comment by shakeit1337** [comment]
ESP Boxes for legit play's

**Comment by tirziz** [comment]
I think name stealer will be more beneficial and visible check is not necessary

**Comment by deprale** [comment]
U can already set chams and esp for visible only -_-' jesus bro

**Comment by Bywnb** [comment]
U can already set chams and esp for visible only

**Comment by Evilhelder** [comment]
name steal would be cool

**Comment by cojo1989** [comment]
Yea, i would like name steal and why not the slideing thing also 😈😈😈
