### ISSUE TITLE
memory.cpp error live 135 after inject and game crash

### ISSUE THREAD

**Issue by hrna94** [danielkrupinski/Osiris#3710]
Hello everyone,

after last update after inject I get this error and dont know what to do. Are you facing something similar or its my local issue? I would appreciate every help.
![Screenshot 2022-06-24 105036](https://user-images.githubusercontent.com/52915108/175500412-4894c8cb-35e7-43de-9039-c7ce9b9f3d36.png)

**Comment by Patrixsin** [comment]
Build Osiris in Release Mode instead of Debug Mode

**Comment by danielkrupinski** [comment]
Fixed
