### ISSUE TITLE
got vac banned

### ISSUE THREAD

**Issue by n4vi98** [danielkrupinski/Osiris#3712]
i got vac banned but I suspect what this caused is when i inject the dll i always close the injector after it maybe that is the caused idk.. tell me if this is cause im new to this thanks... it doesnt really matter because my inventory worth nothing.. and im only using inventory changer not aimbot or wallhack.

sorry bad english

**Comment by n4vi98** [comment]
> You're not using a VAC bypass

i was using cghost v4.3.1 but my mistake was after i injected the dll i close the cghost and got vac this day.

**Comment by mina9999** [comment]
cghost v4.3.1 is detected lol

**Comment by lolman213** [comment]
no its not lmao

**Comment by Patrixsin** [comment]
it causes red trust factor
