### ISSUE TITLE
Csgo update crash (failed to load mode #68#69)

### ISSUE THREAD

**Issue by aibhan** [danielkrupinski/Osiris#3714]
Csgo update crash (failed to load mode #68#69)

**Comment by aibhan** [comment]
Please help me. Thank you

**Comment by 2933968621** [comment]
This problem has been solved. please use the latest Osiris

**Comment by SuShuo125** [comment]
你好，我是在别人那购买的这个软件，上面还显示这个github地址，今天发生了6869问题奔溃了。在这个页面我没有找到exe文件，我有点看不懂这个软件

**Comment by 2933968621** [comment]
> 你好，我是在别人那购买的这个软件，上面还显示这个github地址，今天发生了6869问题奔溃了。在这个页面我没有找到exe文件，我有点看不懂这个软件

坏消息：你被骗了
在某些交易平台 如“淘宝”，“闲鱼”，“拼多多”等平台售卖的此软件均为诈骗
使用此软件的方法非常简单
首先您需要您下载一个叫做'Visual Studio'的软件 (2019以上) 并搭配Windows SDK
然后使用Visual Studio打开这个项目的sln文件 选择Release来构建这个作弊程式
构建完成后 你会在Release文件夹中得到一个叫做Osiris.dll的文件 如果没有 那么你就构建失败了
如果成功 选择一款你喜欢的DLL注入器 将文件指向构建获得的Osiris.dll 并将目标选择csgo.exe
当CSGO窗口中出现UI时 恭喜你 成功了

**Comment by SuShuo125** [comment]
emm看不懂，你能不能发我一个dll这我会注入，或者exe文件，这是那个卖家发我的，但是已经出现6869问题了。这个软件已经汉化过，求万分感谢……

**Comment by SuShuo125** [comment]
我发不出去那个软件，显示不支持

**Comment by 2933968621** [comment]
> emm看不懂，你能不能发我一个dll这我会注入，或者exe文件，这是那个卖家发我的，但是已经出现6869问题了。这个软件已经汉化过，求万分感谢……

这个没汉化的

**Comment by SuShuo125** [comment]
我买的已经汉化过了

**Comment by 2933968621** [comment]
> 我买的已经汉化过了

如果要汉化去找商家，这个是没有汉化过的

**Comment by SuShuo125** [comment]
我已经有喜欢的一直再用的配置，直接一键加载就出来了，你能不能给我发个dll或者exe，万分感谢

**Comment by 2933968621** [comment]
> 我已经有喜欢的一直再用的配置，直接一键加载就出来了，你能不能给我发个dll或者exe，万分感谢

没问题

**Comment by SuShuo125** [comment]
外国友人我爱你

**Comment by 2933968621** [comment]
[Osiris.zip](https://github.com/danielkrupinski/Osiris/files/8986454/Osiris.zip)

**Comment by 2933968621** [comment]
> 外国友人我爱你

[Osiris.zip](https://github.com/danielkrupinski/Osiris/files/8986456/Osiris.zip)
哥们我不是外国人

**Comment by SuShuo125** [comment]
好家伙原来你是中国人

**Comment by SuShuo125** [comment]
更爱了

**Comment by SuShuo125** [comment]
我原来的那个单板库存换肤一开始进入页面显示要过vac，你这个直接进入游戏注入就行了是吧，不用过vac吧

**Comment by 2933968621** [comment]
> 我原来的那个单板库存换肤一开始进入页面显示要过vac，你这个直接进入游戏注入就行了是吧，不用过vac吧

过VAC是防止被VAC封禁 跟注入没任何关系

**Comment by SuShuo125** [comment]
![I14W8EE`}X@A{TR`_NT3E B](https://user-images.githubusercontent.com/102451726/175811346-b67249f2-2b6a-4f88-8f05-b750270f830a.png)
ji
![O1JV0}DNAOA7{ `YCO6%E 8](https://user-images.githubusercontent.com/102451726/175811350-0fa3743c-6d03-44f4-a16c-4aa20ff62b97.png)
jius就是这个，然后进入csgo按ins显示

**Comment by 2933968621** [comment]
> 

那你先过VAC然后自己开游戏注入呗

**Comment by SuShuo125** [comment]
好的谢谢老哥

**Comment by SuShuo125** [comment]
好的谢谢

**Comment by aibhan** [comment]
> 这个问题已经解决了。请使用最新的 Osiris

If I use the old version of Osiris, I need to modify the memory The section in CPP can fix the crash problem

**Comment by SuShuo125** [comment]
老哥为啥我注入后只要换枪皮肤就开始闪退了
