### ISSUE TITLE
[Question] How do I update offsets for older versions...

### ISSUE THREAD

**Issue by Liam5750** [danielkrupinski/Osiris#3719]
So, I have a older version of Osiris I put alot of time and love into but I tried to inject after so long and I'm getting "Failed to find pattern #76" and #77. Idk how danielkrupnski get's the stuff to fix this but any help would be nice.

**Comment by Patrixsin** [comment]
https://github.com/danielkrupinski/Osiris/commit/05a9e37f4f191e01fceb778fae8f20e9396c05c6
https://github.com/danielkrupinski/Osiris/commit/282cc4454cfa5837e775d8feac6549338714d97c

**Comment by Liam5750** [comment]
tysm
