### ISSUE TITLE
Stattrack Skins?

### ISSUE THREAD

**Issue by Maxomer** [danielkrupinski/Osiris#3723]
Is it still possible to get Stattrack skins with the Inventory changer? If so, how?

**Comment by SpryerS** [comment]
It is, all you have to do is go to "Config" - "Open config directory" - Open the config you want to get a StatTrak skin on - Search the skin and add the text under "Seed" -> "StatTrak": Amount of kills, 

![Screenshot from 2022-07-21 19-10-49](https://user-images.githubusercontent.com/94826860/180273377-3c34060d-2a9c-4c9f-9844-4c2dd7a6550d.png)
