### ISSUE TITLE
csgo.exe crash after injecting - Debug

### ISSUE THREAD

**Issue by afafontes** [danielkrupinski/Osiris#3724]
Hello,

I'm trying to inject and csgo crash (like it automatically closes).

I attached a debug to csgo.exe process and I'm getting the following error:

`Exception thrown at 0x6B2881C0 in csgo.exe: 0xC0000005: Access violation when executing location 0x6B2881C0.`

I'm using CSGhost v4.3.1 injector, not sure if you can reproduce the same error.

CSGO and Osiris updated.

Thanks

**Comment by Patrixsin** [comment]
somewhere is null, send full photo with exactly line where is happens

**Comment by afafontes** [comment]
> Not sure this is what you were asking for but it's all I'm getting

![2022-07-06 203135](https://user-images.githubusercontent.com/25420787/177628407-e5861c16-aab5-4a7b-aeee-29d817a0a1d7.jpg)

**Comment by Patrixsin** [comment]
Did u add someting to Osiris?

**Comment by afafontes** [comment]
> Did u add something to Osiris?

Absolutely nothing, compiled straight from the source

**Comment by Patrixsin** [comment]
try to compile it again in release x86

**Comment by afafontes** [comment]
I've done it before multiple times, I did it again now you were asking and still no luck.
Also verified integrity of CSGO game files to make sure nothing is broken with my game and the problem persists.

**Comment by Patrixsin** [comment]
i use csghost and works fine. You can try with process hacker with csgo in -insecure mode

**Comment by afafontes** [comment]
> i use csghost and works fine. You can try with process hacker with csgo in -insecure mode

Yes, with -insecure flag I can successfully inject...

**Comment by Patrixsin** [comment]
u injected with csghost with -insecure flag?

**Comment by afafontes** [comment]
> u injected with csghost with -insecure flag?

Yeah I did and it worked, but once I remove -insecure flag I get the exception

**Comment by Patrixsin** [comment]
i have no idea, what is the issue. Maybe it's hardware issue idk. What's ur CPU?

**Comment by afafontes** [comment]
> i have no idea, what is the issue. Maybe it's hardware issue idk. What's ur CPU?

Solved not fixed! Lol
I ended up formatting another disk with a new Windows image and it's working so I believe it was either something with my OS, profile or CSGO installation.
