### ISSUE TITLE
Injector

### ISSUE THREAD

**Issue by GuMilano** [danielkrupinski/Osiris#3727]
Can you point me to an injector? I tried using CSGOInjector-1.3, but it says it injected but it doesn't

**Comment by SunnySissi** [comment]
some platform cant injector by usual way,no one cant figure it out ，just like 5E

**Comment by SightDev** [comment]
try hitting insert

**Comment by 2933968621** [comment]
> some platform cant inject by usual way,no one cant figure it out ，just like 5E

5EArena is different from the original window name of the game
For example, get the main window of its own process

**Comment by SunnySissi** [comment]
> > some platform cant inject by usual way,no one cant figure it out ，just like 5E
> 
> 5EArena is different from the original window name of the game For example, get the main window of its own process

some way could make name back to csgo,but 5e anti-cheat will detect Osiris and ban the account
