### ISSUE TITLE
some kid wanted to sell osiris and he was claiming that its he's cheat lol

### ISSUE THREAD

**Issue by NeaWare** [danielkrupinski/Osiris#373]
so the title explains itself at the start he wanted to sell it then I think it didnt worked so he posted the compiled cheat on some forum and said that its he's cheat

the imgur album :  https://imgur.com/a/tHs6i2z

**Comment by Bywnb** [comment]
There's no need to pay attention to these poor people.

**Comment by NexSqaud** [comment]
he can do it since it permits MIT license ¯\\_(ツ)_/¯

**Comment by NeaWare** [comment]
oh ok

**Comment by danielkrupinski** [comment]
I can't do much about it.
