### ISSUE TITLE
Lock headers

### ISSUE THREAD

**Issue by JoesephsMother** [danielkrupinski/Osiris#3732]
Does anyone know how to lock the headers so they cannot be dragged and moved? This is in reference to the one window mode.

**Comment by JoesephsMother** [comment]
I have had a look but I cannot locate it, could u tell me where to find it?

**Comment by Rafa2k8** [comment]
> I have had a look but I cannot locate it, could u tell me where to find it?

It’s on the bottom of GUI.cpp, if you look closely you will see something like GUI::renderGuiStyle2
Then 2 lines down you’ll see ImGuiTabBarFlags_Reorderable, just delete this part and you will be good to go

**Comment by Rafa2k8** [comment]
Only delete ImGuiTabBarFlags_Reorderable

**Comment by JoesephsMother** [comment]
Thanks bro <3
