### ISSUE TITLE
Build Inventory Changer only 

### ISSUE THREAD

**Issue by Rafa2k8** [danielkrupinski/Osiris#3734]
I wanted to build the inventory changer and config, and the GUI 2 which is the one that is a separate window.
I want to remove the hack features because I really love this skin changer and i wanna minimize the risks of getting vac banned since if I modify and dele the hacks and unnecessary features in the misc section.
I can’t seem to work it out, I try and delete the hooks.cpp part where it hooks the aimbot and hacks stuff but when I load it into the game after building in release and debug with no errors it instantly crashes the game any help? Thanks

**Comment by Xsintashi** [comment]
deleting all features except inventory changer isn't decrease chance of getting VAC 💀

**Comment by Rafa2k8** [comment]
> deleting all features except inventory changer isn't decrease chance of getting VAC 💀



> deleting all features except inventory changer isn't decrease chance of getting VAC 💀

Then what will ?

**Comment by rrhyast** [comment]
> > deleting all features except inventory changer isn't decrease chance of getting VAC 💀
> 
> > deleting all features except inventory changer isn't decrease chance of getting VAC 💀
> 
> Then what will ?

don't cheat or accept the risk.

**Comment by Teemoplays** [comment]
> > > deleting all features except inventory changer isn't decrease chance of getting VAC 💀
> > 
> > 
> > > deleting all features except inventory changer isn't decrease chance of getting VAC 💀
> > 
> > 
> > Then what will ?
> 
> you can always make your own loader (don't paste it) and after that you can put your dll into the loader you made 😉

you will also need to make your own vac bypass (a public one will prob get you in red trust factor)
