### ISSUE TITLE
The Inventory Changer Tab is buggy

### ISSUE THREAD

**Issue by hoangxuanlam2007** [danielkrupinski/Osiris#3736]
I'm using Windows 11 22H2. Everything seems to be normal until I click add item in Inventory Changer, the tab width keep increasing until it fit with the  monitor width which reallly strange and it made me feel so upset
Can anyone help me get through this?

**Comment by Rafa2k8** [comment]
> I'm using Windows 11 22H2. Everything seems to be normal until I click add item in Inventory Changer, the tab width keep increasing until it fit with the monitor width which reallly strange and it made me feel so upset Can anyone help me get through this?

its normal i have that too just live with it lol

**Comment by danielkrupinski** [comment]
Fixed
