### ISSUE TITLE
hook user chat and overwrite it

### ISSUE THREAD

**Issue by E4zily** [danielkrupinski/Osiris#3739]
hello,

im kinda new to this language and im wondering if someone could tell me how to hook the chat messages and overwrite them. for example, i type something else and it changes the text to caps or something.

thank you

**Comment by lstrsrt** [comment]
You can hook IVEngineClient::ClientCmd (https://github.com/perilouswithadollarsign/cstrike15_src/blob/master/public/cdll_int.h#L332) and check if szCmdString starts with "say". If yes, the rest of the string is the chat message. You can then change the string to whatever you want and return the original with it.
