### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by KRISTJANOLEN** [danielkrupinski/Osiris#374]
i got this error when starting the build 
Error	C4996	 'Entity::getProperty': was declared deprecated 
Osiris
\Osiris-master\Osiris\SDK\GlobalVars.cpp  line 11

**Comment by danielkrupinski** [comment]
- compile in Release mode
or
- remove deprecation attribute from Entity::getProperty and Entity::setProperty methods
or
- add `#pragma warning(disable : 4996)` in Entity.h
