### ISSUE TITLE
Using Osiris on Linux makes my CS:GO Stutter.

### ISSUE THREAD

**Issue by SpryerS** [danielkrupinski/Osiris#3742]
So I have been using Linux for about 4 months now and played CS with Osiris on it and saw that when my CS is injected it gets frequent stutters via FPS from 200+ -> 20fps, I have no idea why it does this but it's only when my CS has Osiris injected.

**Comment by mdilai** [comment]
Do alt-tab to desktop and back when Osiris menu is hidden.

**Comment by danielkrupinski** [comment]
Are you building with optimizations ( `-DCMAKE_BUILD_TYPE=Release`)?

**Comment by SpryerS** [comment]
> 

How do I know if I have built it with that?

**Comment by danielkrupinski** [comment]
`libOsiris.so` built in release mode should weight around 1.5 MB, unoptimized builds are significantly larger.

**Comment by SpryerS** [comment]
I have it built in -D CMAKE_BUILD_TYPE=Release.

**Comment by SpryerS** [comment]
> Do alt-tab to desktop and back when Osiris menu is hidden.

What do you mean by this?

**Comment by SpryerS** [comment]
> `libOsiris.so` built in release mode should weight around 1.5 MB, unoptimized builds are significantly larger.

So like I said in my latest post to you, it's built in -D CMAKE_BUILD_TYPE=Release. and I do not think that's the issue.

**Comment by gr1ndy** [comment]
> Are you building with optimizations ( `-DCMAKE_BUILD_TYPE=Release`)?

where do i check that?
