### ISSUE TITLE
Are you sure that this thing is fine? 

### ISSUE THREAD

**Issue by R3BHXAB** [danielkrupinski/Osiris#3743]
Hello, it isn't really an issue, but i want to ask,
about things like SetClanTag or `KeyValues* KeyValues::fromString(const char* name, const char* value)` (KeyValues.cpp line 20) doesn't need to have return address spoofed?

**Comment by danielkrupinski** [comment]
Eventually all game function calls should have their return address spoofed. Those functions don't seem to have return address checks +
currently there is a hook which prevents return address checks results from being sent to the server.
