### ISSUE TITLE
[SUGGESTION] Custom kill message

### ISSUE THREAD

**Issue by 4lb3** [danielkrupinski/Osiris#375]
Instead of changing it on the code, users could be able to change it in-game.

**Comment by deprale** [comment]
that's a nice feature

I think I can implement it on my own, if I get it to work I'll let you know bud!

**Comment by 4lb3** [comment]
Nice! It would be great if Daniel added this feature to everyone!

**Comment by NexSqaud** [comment]
```c++
constexpr void killMessage(GameEvent* event) noexcept
{
    auto localPlayer = interfaces.engine->getLocalPlayer();
    if (config.misc.killMessage
	&& interfaces.engine->getPlayerForUserID(event->getInt("attacker")) == localPlayer
	&& interfaces.engine->getPlayerForUserID(event->getInt("userid")) != localPlayer)
    {
        std::string msg("say ");
        msg += config.messages.kill;
        interfaces.engine->clientCmdUnrestricted(msg.c_str());
    }
}
```

**Comment by deprale** [comment]
> ```c++
> constexpr void killMessage(GameEvent* event) noexcept
> {
>     auto localPlayer = interfaces.engine->getLocalPlayer();
>     if (config.misc.killMessage
> 	&& interfaces.engine->getPlayerForUserID(event->getInt("attacker")) == localPlayer
> 	&& interfaces.engine->getPlayerForUserID(event->getInt("userid")) != localPlayer)
>     {
>         std::string msg("say ");
>         if(!event->getBool("headshot"))
>         {
>             msg += config.messages.kill;
>             interfaces.engine->clientCmdUnrestricted(msg.c_str());
>         }else
>         {
>             msg += config.messages.headshot;
>             interfaces.engine->clientCmdUnrestricted(msg.c_str());
>         }
>     }
> }
> ```

include everything else too bro

**Comment by NexSqaud** [comment]
in config.h
```c++
struct {
    char kill[256];
    char headshot[256];
} messages;
```
in config.cpp Config::load()
```c++
auto& messagesJson = json["Messages"];

if(messagesJson.isMember("Kill message"))strcpy_s(messages.kill, 256, messagesJson["Kill message"].asCString());
if(messagesJson.isMember("Headshot message"))strcpy_s(messages.headshot, 256, messagesJson["Headshot message"].asCString());
```
in config.cpp Config::save()
```c++
auto& messagesJson = json["Messages"];

messagesJson["Kill message"] = messages.kill;
messagesJson["Headshot message"] = messages.headshot;
```
in GUI.cpp 
```c++
GUI::renderMessagesWindow() noexcept
{
    if(window.messages) {
        if(!config.misc.menuStyle) {
            ImGui::SetNextWindowSize({ 0.0f, 0.0f });
            ImGui::Begin("Messages", &window.messages, windowFlags);
        }
        ImGui::InputText("Kill message", config.messages.kill, IM_ARRAYSIZE(config.messages.kill));
        ImGui::InputText("Headshot message", config.messages.headshot, IM_ARRAYSIZE(config.messages.headshot));
        if (!config.misc.menuStyle)
            ImGui::End();
    }
}
```
in GUI::render() in near of ` renderMiscWindow(); `
```c++
renderMessagesWindow();
```
in GUI::renderGuiStyle2()
```c++
if(ImGui::BeginTabItem("Messages")) {
    window = { };
    window.misc = true;
    ImGui::EndTabItem();
}
```
near of 
```c++
if (ImGui::BeginTabItem("Misc")) {
    window = { };
    window.misc = true;
    ImGui::EndTabItem();
}
```
and 
```c++
renderMessagesWindow();
```
near of ` renderMiscWindow(); `

in GUI.h in window struct in near of ` bool misc{false}; `
```c++
bool messages{false};
```
and 
```c++
void renderMessagesWindow() noexcept;
```
near of ` void renderMiscWindow() noexcept; `

**Comment by deprale** [comment]
Nice, you should make a pull request!
Works flawlessly, so far no bugs @NexSqaud 

@danielkrupinski make him a collaborator already jeez :dancer:

**Comment by tirziz** [comment]
I dont understand why you guys want this feature , this only make ur opponents report you and that is bad

**Comment by danielkrupinski** [comment]
Added.
