### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by WhosOn** [danielkrupinski/Osiris#3753]
Spin Bot IS A MUSTTTTTTTTT.

And Can you "anti kick", which votes no when they are trying to kick you.
Its a thing in Skeet / gamesense

**Comment by Xsintashi** [comment]
Daniel isn't gonna add ragebot features.
About anti votekick idk.

**Comment by gr1ndy** [comment]
> Spin Bot IS A MUSTTTTTTTTT.

https://github.com/notgoodusename/OsirisAndExtra/
