### ISSUE TITLE
What changes needed to make to get previous versions work?

### ISSUE THREAD

**Issue by hamad12a** [danielkrupinski/Osiris#3755]
Please provide some guidelines in order to make the previous codes work, like memory addresses, etc.

**Comment by Xsintashi** [comment]
https://github.com/danielkrupinski/Osiris/commits/master

**Comment by hamad12a** [comment]
> https://github.com/danielkrupinski/Osiris/commits/master

@Xsintashi Those are committed changes but I want a **_procedure_** to make older codes work take for example [this code version](https://github.com/danielkrupinski/Osiris/tree/2685a6c093d46c6ce171d95544b4a33c6e3ad342), what are the necessary files needed to change and how to make it compatible with current CSGO game?

**Comment by Xsintashi** [comment]
idk. who knows

**Comment by hamad12a** [comment]
@faithfullunaa Are you serious?

**Comment by mdilai** [comment]
If you are completely noob, it can be very hard, but here is where you must look:
1) Update [memory](https://github.com/danielkrupinski/Osiris/blob/master/Source/Memory.cpp) and [interfaces](https://github.com/danielkrupinski/Osiris/blob/master/Source/Interfaces.h) patterns to latest one.
2) Update SDK files by referring to https://github.com/danielkrupinski/Osiris/commits/master/Source/SDK and https://github.com/danielkrupinski/Osiris/commits/master/Osiris/SDK . You may look through all commits to find the ones which are fixing exist SDKs, or maybe for such old code base its easier to just replace old SDK folder with new one and fix incompatibles in old code. As a bonus, you will probably learn more about code during this process, as you want.

**Comment by hamad12a** [comment]
@mdilai Gladly you answered my question.
