### ISSUE TITLE
Help Inject Osiris in ManualMap

### ISSUE THREAD

**Issue by weendelzera** [danielkrupinski/Osiris#3758]
I'm not able to inject Osiris with ManualMap, does anyone know why this happens or have you seen this problem?

**Comment by Xsintashi** [comment]
uafaik u cant manual map osiris

**Comment by weendelzera** [comment]
> afaik u cant manual map osiris

Why not?

**Comment by faithfullunaa** [comment]
> afaik u cant manual map osiris

Never knew why but I can manual map Osiris and have been doing it for ages. All injectors I have tried work.

**Comment by ByMynix** [comment]
Manualmap with Osiris is possible, but there is something wrong with your injector.
