### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by relativist** [danielkrupinski/Osiris#3760]
Cant build for Linux (UBUNTU). I always build with success, but now it fails. It fails at least for 3 days.

> [ 84%] Building CXX object CMakeFiles/OsirisOBJ.dir/Source/InventoryChanger/ItemGenerator/ItemGenerator.cpp.o
> /home/rest/proj/Osiris/Source/InventoryChanger/ItemGenerator/ItemGenerator.cpp: In function ‘time_t getStartOfYearTimestamp(uint16_t)’:
> /home/rest/proj/Osiris/Source/InventoryChanger/ItemGenerator/ItemGenerator.cpp:852:45: error: unable to find numeric literal operator ‘operator""d’
>   852 |     return system_clock::to_time_t(sys_days(1d / January / year));
>       |                                             ^~
> compilation terminated due to -Wfatal-errors.
> make[2]: *** [CMakeFiles/OsirisOBJ.dir/build.make:709: CMakeFiles/OsirisOBJ.dir/Source/InventoryChanger/ItemGenerator/ItemGenerator.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:347: CMakeFiles/OsirisOBJ.dir/all] Error 2
> make: *** [Makefile:84: all] Error 2

Use this make file to build:
https://pastebin.com/QaXTMvpy

cmake --version
cmake version 3.16.3

**Comment by paintrain76** [comment]
> cuccess

**Comment by danielkrupinski** [comment]
Minimal required g++ version is 11. Ubuntu can default to an older version, so you can specify the compiler with `-DCMAKE_CXX_COMPILER=g++-11` option to the `cmake` command.

**Comment by hamad12a** [comment]
His @relativist  case is reproducible at least for me.

**Comment by relativist** [comment]
Sorry for success word!

Ubuntu G++ version:
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

and max available 10. 

Try compile with lines in Makefile:

> export CC=/usr/bin/gcc-10
> export CXX=/usr/bin/g++-10
> DCMAKE_CXX_COMPILER=g++-10
> CMAKE_COMMAND = /usr/bin/cmake

BUT with another error:

> [ 84%] Building CXX object CMakeFiles/OsirisOBJ.dir/Source/InventoryChanger/ItemGenerator/ItemGenerator.cpp.o
> /home/rest/proj/Osiris/Source/InventoryChanger/ItemGenerator/ItemGenerator.cpp: In function ‘time_t getStartOfYearTimestamp(uint16_t)’:
> /home/rest/proj/Osiris/Source/InventoryChanger/ItemGenerator/ItemGenerator.cpp:852:45: error: unable to find numeric literal operator ‘operator""d’
>   852 |     return system_clock::to_time_t(sys_days(1d / January / year));
>       |                                             ^~
> compilation terminated due to -Wfatal-errors.
> make[2]: *** [CMakeFiles/OsirisOBJ.dir/build.make:709: CMakeFiles/OsirisOBJ.dir/Source/InventoryChanger/ItemGenerator/ItemGenerator.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:347: CMakeFiles/OsirisOBJ.dir/all] Error 2
> make: *** [Makefile:87: all] Error 2

**Comment by danielkrupinski** [comment]
Execute `sudo add-apt-repository ppa:ubuntu-toolchain-r/test` command and then g++-11 should be available for installation.

**Comment by hamad12a** [comment]
It turns out that [this answer](https://askubuntu.com/a/1376051/585227) solved my problem!

**Comment by relativist** [comment]
Thank you. installed 11 version and it built with success!

--reinstall commands was not helped me.
