### ISSUE TITLE
How to debug under Linux?

### ISSUE THREAD

**Issue by hamad12a** [danielkrupinski/Osiris#3764]
I use VS Code for code development, with installed GDB.

```
gdb --version
GNU gdb (Ubuntu 12.0.90-0ubuntu1) 12.0.90
...
```
But I didn't understand attaching to the game process how helps to debug the hack in question.

**Comment by mdilai** [comment]
GDB is command-line tool so you need to use a commands to debug, [Here is a large manual](https://sourceware.org/gdb/current/onlinedocs/gdb/)

But me personally using Visual Studio Code for Linux which provide Visual Studio-like GUI for GDB.

**Comment by deboogerxyz** [comment]
https://github.com/deboogerxyz/ah4/blob/master/debug.sh

This script loads the library with GDB and doesn't detach when it's finished. The most common commands are "continue" (or "c") and "backtrace" (or "bt").

**Comment by hamad12a** [comment]
@mdilai Could you describe how you attach to the process using VS Code?

**Comment by deboogerxyz** [comment]
Breakpoints are made from the GDB CLI but I guess Code has a GUI for that;
ah4 is my CS:GO cheat for GNU/Linux, written in C99;

**Comment by hamad12a** [comment]
Yes VSC has Gui for breakpoints but not sure if running GSB CLI will detect them autocatically.
