### ISSUE TITLE
Stickers on skins?

### ISSUE THREAD

**Issue by v1ll3** [danielkrupinski/Osiris#3766]
Is there a way to add stickers to skins in the config file? 

It's possible to make them StatTrack but I don't know how to add stickers.

**Comment by danielkrupinski** [comment]
You can apply stickers in CS:GO inventory :)

[](https://user-images.githubusercontent.com/34515229/119382342-31cb0c80-bcc2-11eb-96eb-fd1d2f6bf675.gif)

**Comment by v1ll3** [comment]
Ok thank you for replying! For some reason it gave error when I tried to apply stickers maybe because they were unboxed stickers? But I'll try with the manually added stickers and hope it works. :)
