### ISSUE TITLE
can't build osiris

### ISSUE THREAD

**Issue by lishues** [danielkrupinski/Osiris#3769]
![Bild_2022-08-21_011927742](https://user-images.githubusercontent.com/111376024/185769132-34983b78-eb6a-46d7-a826-341f8b6301e5.png)
 
i get some errors for some weird shit, how could i fix this

**Comment by TH1ts2Ez4m3** [comment]
Same with me

**Comment by lishues** [comment]
everyone with the same problem, it's a problem with visual studio, reinstall and it should be fixed
