### ISSUE TITLE
[Suggestion] Blockbot or Run boost assist

### ISSUE THREAD

**Issue by Evilhelder** [danielkrupinski/Osiris#377]
If you could, could you put a Run boost assist or a Blockbot? It would be really cool to have this in the hack...
 I have this blockbot code, but I don't know if it would be usefu .... :T

    void blockbot(CUserCmd* pCmd) {
     
    	
    	float bestdist = 150.f;
    	int index = -1;
     
    	for (int i = 1; i < Interfaces::Engine()->GetMaxClients(); i++)
    	{
    		CPlayer* entity = g_pPlayers->GetPlayer(i);
    		
    		if (!entity)
    			continue;
     
    		if (!entity->iHealth > 0 || !entity->m_pEntity || entity->m_pEntity == g_pPlayers->GetLocal()->m_pEntity )
    			continue;
     
    		float dist = entity->iDistance;
     
    		if (dist < bestdist)
    		{
    			bestdist = dist;
    			index = i;
    		}
    	}
     
    	if (index == -1)
    		return;
     
    	CPlayer* target = g_pPlayers->GetPlayer(index);
     
    	if (!target)
    		return;
     
    	
     
    	
     
    	if (Client::g_vCenterScreen.x < target->vOriginScreen.x - 10)
    		pCmd->sidemove = 450.f;
    	else if (Client::g_vCenterScreen.x > target->vOriginScreen.x + 10)
    		pCmd->sidemove = -450.f;
     
    }

**Comment by Evilhelder** [comment]
Another code: 

    void Misc_Movement::blockbot( CUserCmd* m_pcmd ) {
    	auto m_local = game::localdata.localplayer( );
     
    	float bestdist = 150.f;
    	int index = -1;
     
    	if ( GetAsyncKeyState( miscconfig.iBlockbotKey ) ) {
    		for ( int i = 0; i < m_pGlobals->maxClients; i++ ) {
    			auto entity = m_pEntityList->GetClientEntity( i );
     
    			if ( !entity ) continue;
    			if ( !entity->IsAlive( ) || entity->IsDormant( ) || entity == m_local ) continue;
     
    			float dist = ( m_local->GetOrigin( ) - entity->GetOrigin( ) ).Length( );
     
    			if ( dist < bestdist ) {
    				bestdist = dist;
    				index = i;
    			}
    		}
    	}
     
    	if ( index == -1 ) return;
     
    	auto target = m_pEntityList->GetClientEntity( index );
     
    	if ( !target ) return;
     
    	Vector angles;  game::math.calculate_angle( m_local->GetEyePosition( ), target->GetEyePosition( ), angles );
    	angles.Normalized( );
     
    	if ( angles.y < 0.0f ) m_pcmd->sidemove = 450.f;
    	else if ( angles.y > 0.0f ) m_pcmd->sidemove = -450.f;
    }

**Comment by tirziz** [comment]
What is runbooat assist ?

**Comment by deprale** [comment]
> What is runbooat assist ?

basically (what I think he means) is following what a player does that is underneath you(so you don't fail a run boost), it's sad that you don't know tbh.

**Comment by Evilhelder** [comment]
> basically (what I think he means) is following what a player does that is underneath you(so you don't fail a run boost), it's sad that you don't know tbh.

Exactly. I've been trying for a long time to find or create a Run boost assist or Blockbot cheat.... But to no avail. So I thought and give this suggestion... :T

**Comment by tirziz** [comment]
Run boost maybe look cool but kidda useless , it just it only works in very specific situations and you cant do it alone

**Comment by Evilhelder** [comment]
> Run boost maybe look cool but kidda useless , it only works in very specific situations and you cant do it alone.
> Anyway this could be done

I want to use it to troll my friends in the competitive ... xD Please add this.

**Comment by Evilhelder** [comment]
I found this code to make it easier, perhaps, and a MimicBot code. I beg you, put this in Osiris code... ;-;


    for (i=0 ; i<2 ; i++)       // Determine x and y parts of velocity
    	wishvel[i] = pmove->forward[i]*fmove + pmove->right[i]*smove;
    	
    wishvel[2] = 0;             // Zero out z part of velocity
     
    VectorCopy (wishvel, wishdir);   // Determine maginitude of speed of move
    wishspeed = VectorNormalize(wishdir);
     
    if (wishspeed > pmove->maxspeed)
    {
    	VectorScale (wishvel, pmove->maxspeed/wishspeed, wishvel);
    	wishspeed = pmove->maxspeed;
    }

**Comment by l0ccy** [comment]
blockbot ++++

**Comment by BlackmanWhite** [comment]
Yes, please, I beg you.

**Comment by BlackmanWhite** [comment]
Still waiting
