### ISSUE TITLE
I cannot build, need pre-built.

### ISSUE THREAD

**Issue by maceromsdahl** [danielkrupinski/Osiris#3770]
I do not have enough space on my computer for VS Studio. Can someone please provide me with a prebuilt DLL?

**Comment by Xsintashi** [comment]
[Osiris 16.08.2022.zip](https://github.com/danielkrupinski/Osiris/files/9410886/Osiris.16.08.2022.zip)

**Comment by Nedudis** [comment]
why my browser says it contains a virus?

> [Osiris 16.08.2022.zip](https://github.com/danielkrupinski/Osiris/files/9410886/Osiris.16.08.2022.zip)

**Comment by kmsvape** [comment]
> why my browser says it contains a virus?
> 
> > [Osiris 16.08.2022.zip](https://github.com/danielkrupinski/Osiris/files/9410886/Osiris.16.08.2022.zip)

because its a cheat??

**Comment by maceromsdahl** [comment]
closed
