### ISSUE TITLE
Anti-aim problem

### ISSUE THREAD

**Issue by andogy** [danielkrupinski/Osiris#3771]
Enable anti-aim(pitch+yaw) may crash the game.
Clicking the mouse manually will shoot to the ground(same as throwing out a projectile).

**Comment by Xsintashi** [comment]
AA doesnt crash for me. Increase your `Max Angle Delta` if u shoot at ground. With grenades, it's common issue.

**Comment by removed0** [comment]
> Enable anti-aim(pitch+yaw) may crash the game.
same
