### ISSUE TITLE
Issues with Linux compilation.

### ISSUE THREAD

**Issue by ReShout876** [danielkrupinski/Osiris#3777]
After I switched from Debian 11 to Fedora 36 I couldn't compile Osiris (had some issue). I decided to make an Ubuntu VM and compile  there. It works but there is an issue.
The .so file I get after compilation it's not normal(?)
The file size is not ~1.3MB, it is 8MB which lags the game when you open the inventory changer tab when you are looking for an item to "add".

How do I fix?
(image as reference)
@danielkrupinski hopefully you know how
![image](https://user-images.githubusercontent.com/63971777/187071159-215baf81-5cfd-47f1-a63c-8626da084b56.png)

edit:
these are the commands i used for the compilation
`cmake CMakeLists.txt`
`cmake --build /home/reshot/Osiris/ -j $(nproc --all)`

**Comment by ReShout876** [comment]
Ok...
Somehow I got it to compile in Fedora, but the .so is 7MB big, not around 1.3 as it should be

**Comment by mdilai** [comment]
-DCMAKE_BUILD_TYPE=Release

**Comment by ReShout876** [comment]
> -DCMAKE_BUILD_TYPE=Release

i did `cmake -DCMAKE_BUILD_TYPE=Release`
then rebuilt
had this thing at the end
```
[100%] Linking CXX shared library libOsiris.so
lto-wrapper: warning: using serial compilation of 23 LTRANS jobs
lto-wrapper: note: see the ‘-flto’ option documentation for more information
In function ‘ImFontAtlasBuildPackCustomRects’,
    inlined from ‘ImFontAtlasBuildWithFreeTypeEx’ at /home/reshout/Osiris/Dependencies/imgui/imgui_freetype.cpp:580:36:
/home/reshout/Osiris/Dependencies/imgui/imgui_draw.cpp:2591:11: warning: ‘memset’ specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
 2591 |     memset(pack_rects.Data, 0, (size_t)pack_rects.size_in_bytes());
      |           ^
[100%] Built target Osiris
```
not too sure what it means BUT i no longer lag when looking for items to add.
Thank you so much :pray:
