### ISSUE TITLE
[Question] Skinchanger forceupdate

### ISSUE THREAD

**Issue by tirziz** [danielkrupinski/Osiris#378]
Is there anyway to make skinchanger force full-update less often?

**Comment by tirziz** [comment]
This nSkinz is old, I wonder is there any way to improve it too

**Comment by deprale** [comment]
i dont think replying to your own ticket is very smart.
it will just make other people think that someone answered your ticket already, just edit your initial statement ffs..

also interested in this btw.

**Comment by danielkrupinski** [comment]
Skinchanger updates only on:
- config load
- config reset
- "Update" button press
