### ISSUE TITLE
Inventory modifier not working

### ISSUE THREAD

**Issue by lanting200** [danielkrupinski/Osiris#3781]
Add Inventory not working after CSGO update

**Comment by jackKiZhu** [comment]
Me too.

**Comment by milkboy77** [comment]
Me too.

**Comment by jackKiZhu** [comment]
> Me too.

我突然发现都是我们国人在等...🤣

**Comment by jaiisbored** [comment]
damn i was scared cus i thought i got banned or something

**Comment by jaiisbored** [comment]
how long will it take to fix this approx?

**Comment by amircheragi** [comment]
yes unfortunately. i thought it might be a problem on my computer so i reinstalled the game. everything works fine except the inventory changer :(

**Comment by johnaps94** [comment]
+1 for this, it is because of the latest game update i believe
