### ISSUE TITLE
Possible fix for GetSoc() failing because of an outdated offset

### ISSUE THREAD

**Issue by InfernoLum** [danielkrupinski/Osiris#3782]
The newest offset is now 0xB4, however it can be retrieved dynamically from game memory using a simple IDA pattern.  I'm sure @danielkrupinski already knows how to retrieve the index. Here is the pattern: `33 F6 39 B7 ? ? ? ? 0F 85 ? ? ? ?` Then add 4 bytes so we move from the `xor esi esi` to the offset contained inside the instruction `cmp [edi+0B4h], esi`
In case this pattern somehow gets outdated I suggest looking for the string "could not find SOC data for item" this string is referenced inside the function CInventoryManager::UpdateInventoryEquippedState and the string is outputted as a Warning() if GetSOCDataForItem fails. De-compiling this function will provide you with the offset. 
Some images:
![aodGVwt](https://user-images.githubusercontent.com/42121738/187482361-5e6ff8c4-3f31-46f1-92ed-a9b57fa7fd17.png)
![ekPPegt](https://user-images.githubusercontent.com/42121738/187482365-e437b482-ca7f-4e68-a8f0-f29a0afcfc3b.png)

**Comment by jackKiZhu** [comment]
good job!

**Comment by InfernoLum** [comment]
Yeah, I suppose that works as well, but point is, you can simply
