### ISSUE TITLE
Is NoSpread posibble?

### ISSUE THREAD

**Issue by PastedX** [danielkrupinski/Osiris#3787]
if its posibble please open a pr
im looking for no spread legit if not posibble then
I Will Kill My Self :D

**Comment by PastedX** [comment]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/126011-csgo-no-spread-explanation.html

if this helps

**Comment by notgoodusename** [comment]
no spread isnt possible anymore, that post is from 6 years ago
