### ISSUE TITLE
csgo lagging

### ISSUE THREAD

**Issue by adriangames147** [danielkrupinski/Osiris#379]
after I inject osiris to csgo, my fps drops below 60

**Comment by NexSqaud** [comment]
buy new pc

**Comment by Shaxzy** [comment]
I agree with @NexSqaud here
Osiris does not affect my fps, at least not noticeable.

Also you say it drops your fps below 60 but you didn't say anything about how much fps you have without any cheats enabled.

**Comment by deprale** [comment]
Compile the cheat with AVX2 instructionset if your cpu supports it.

**Comment by deprale** [comment]
Also + LOD ANIMATION FIX has lots of fps drops and lags imho.

**Comment by MasterChief220** [comment]
> Compile the cheat with AVX2 instructionset if your cpu supports it.

how do you do that?
