### ISSUE TITLE
is quick scope for legit posibble?

### ISSUE THREAD

**Issue by PastedX** [danielkrupinski/Osiris#3790]
someone please add quick scope for
legit bot no auto shot beacause im trying to hit some quick scope clips

also if posibble add nade helper here is link
{ https://github.com/FluxDotWOOP/GRENADE-API }

**Comment by fanat1cc** [comment]
the nade helper is a must for legit play is you don't wanna learn all the nade lineups

**Comment by PastedX** [comment]
dicky
