### ISSUE TITLE
[Off-Topic] what is this?

### ISSUE THREAD

**Issue by dapaster** [danielkrupinski/Osiris#3800]
can someone tell me what is this??

https://github.com/Ven0xa/Aimware-CSGO-Legit-and-Rage-cheat-cracked-by-VenomX

virus? trojan? mining? keylogger?

**Comment by deboogerxyz** [comment]
The links to the repository and the author are dead, probably because it was malware.

**Comment by BellBush** [comment]
It was a crypto miner, doesn't do anything, it would load then crash, and then post some crap.
Then justs keeps running in the background.

**Comment by dapaster** [comment]
thanks for the info guys
