### ISSUE TITLE
Crash on Newest Version

### ISSUE THREAD

**Issue by Zurek0x** [danielkrupinski/Osiris#3813]
Recently I compiled the newest version (as of making this post) using Visual Studio 2022 and noticed a few issues.

The newest version would randomly crash at random times (not specific) leaving back no Error codes or Log Files (even with -debug)
While the old version I had (Leatest as of September 3rd) worked fine with minimal to 0 Crashes.

I also noticed a file size increase from the old one being around 1.3Mb to the new one being 7.7Mb.
The old one while taking around 2 Seconds to inject, New one taking around 6 Seconds to inject. (freeze times)

All I used in the cheat was the (inventory changer) and even tried with no config and still crashed.
It is not a issue with any settings, It is a issue with some part in the main DLL (Not when injection)

My Specs:
OS: Windows 11 21H2 Pro
RAM: 8Gb RAM
GPU: RTX 3060 8Gb VRAM
CPU: AMD Ryzen 5 3600X

**Comment by Zurek0x** [comment]
Disregard, It crashes on the newest CS Update, There is no (Newest) or (Old) version crashing or not.
Both DLL's don't work.

**Comment by Xsintashi** [comment]
> I also noticed a file size increase from the old one being around 1.3Mb to the new one being 7.7Mb.
The old one while taking around 2 Seconds to inject, New one taking around 6 Seconds to inject. (freeze times)

Cuz u compiled the cheat in debug mode, than in release I guess. I havent tested new ver yet, so im not 100% sure

**Comment by Zurek0x** [comment]
> > I also noticed a file size increase from the old one being around 1.3Mb to the new one being 7.7Mb.
> > The old one while taking around 2 Seconds to inject, New one taking around 6 Seconds to inject. (freeze times)
> 
> Cuz u compiled the cheat in debug mode, than in release I guess. I havent tested new ver yet, so im not 100% sure

No, only in debug.

**Comment by fanat1cc** [comment]
Only ever build osiris on release in my option, i suggest you try on release
