### ISSUE TITLE
Microsoft Defender marks this file as malicious

### ISSUE THREAD

**Issue by OrianSss** [danielkrupinski/Osiris#3818]

**Comment by 1310s** [comment]
got to > Virus & threat protection > Manage Settings > Exclusions > Add Exclusion > select osiris dll

done!

**Comment by OrianSss** [comment]
Is there really no malicious code in there?

**Comment by 1310s** [comment]
> Is there really no malicious code in there?


no

**Comment by OrianSss** [comment]
Thanks
