### ISSUE TITLE
detected?

### ISSUE THREAD

**Issue by aqsatti** [danielkrupinski/Osiris#384]
my friends with me got convicted live, is it detected? using rando injector

**Comment by EGTLoneWolf** [comment]
I think you prolly got overwatched.

**Comment by aqsatti** [comment]
but my friend got convicted at the same exact moment with me....

**Comment by Shaxzy** [comment]
It's open source. Make it undetected yourself.

**Comment by danielkrupinski** [comment]
Using old injector with randomly inserted CPU instructions isn't generally a good idea.

**Comment by deprale** [comment]
LMFAO

bruh, just put some junk code like everyone else, even in your rando injector and make it literally RANDOM, not just get it compiled smh.

never got convicted doing so.

**Comment by 0xE232FE** [comment]
- The cheat actually got never detected or sigged by Valve. If that is going on everybody would cry.
- There are million injector methods you can do, why you all use Random Inject from Unknowncheats forum? There are tons of better injection methods without random shit code.
- Actually I can confirm too, that your Injector might cause the VAC Ban or Overwatch you was playing too obvious. Keep in mind that 90% of all Overwatch are statistically based over time, only 10% were decided by Humans! I think the Human cases will go up to 1% of human judgments and later 99% will decided by an Algorithm or Machinelearning Tool.
