### ISSUE TITLE
Failed to to find pattern #91

### ISSUE THREAD

**Issue by Liam5750** [danielkrupinski/Osiris#3844]
just another pattern thing. Wondering how people find the broken one and find the new value. if someone could tell me the second an update hits I would make a pull request.

Help for anyone who can actually update it. 

Hint:
findHudElement needs to be updated

**Comment by Liam5750** [comment]
I opened this pr on osiris and not a fork. anyways, anyone reading this know how to fix it so I can fix a forked version of Osiris

**Comment by Metaphysical1** [comment]
well, the signature in osiris works after the update (or in other words how osiris gets the pointer to function)
anyway here is the noob version of how to get a new signature:
open client.dll in ida pro, wait untill it's done dissassmbling the file, and then open strings subview search for "[%d] Could not find Hud Element: %s\n" and then you can see the function where this string is referenced in :
https://imgur.com/BZCRPBf
now you can take a signature of it with sigmaker.
it's:
`direct reference: [actual address in first opcode] E8 ? ? ? ? 8B 4D 04 89 45 FC `
of course you need to convert that shit to absolute address in your cheat

in case of other signatures when you don't know how to get it, then you can download old version of the file (i.e. client.dll or engine.dll) and reverse that in ida pro and search for unique thing in the function like strings, vtable reference, etc...

**Comment by SightDev** [comment]
> 

I learned how to do this in a 48+ minute video and you explained it all in like a 60 second read at max
