### ISSUE TITLE
Crashing on map after loading config

### ISSUE THREAD

**Issue by free0ne87** [danielkrupinski/Osiris#3848]
As in mentioned in this issue https://github.com/danielkrupinski/Osiris/issues/3838 I think problem persists. This is actually happening when I load config immediately after injecting - game crashes after few kills on aim_botz, not tested in other maps. But if I load the map with cheat injected, do some 10 kills and load config after, it works without crashing. I tried also enabling features one by one and there was no crash, but if I save the config and load it again next time - same problem happens. Tried saving without inventory, same problem.

**Comment by 1310s** [comment]
i got the answer for you, this happened to me and i find out how to fix, just make a new config by creating one and the new one wont crash!

**Comment by free0ne87** [comment]
Tried already. Did not help.

**Comment by 1310s** [comment]
did you complied latest dll? or what injector ur using?

**Comment by free0ne87** [comment]
Cant recreate after last update. Seems ton work. Closing.
