### ISSUE TITLE
[REOPEN] Crashing game when loading config with inventory

### ISSUE THREAD

**Issue by Essential87** [danielkrupinski/Osiris#3852]
I've already closed the issue prevously. But it seems that problem still persists. All configs were created from zero on newest version.
I've investigated a bit more and found the following:

[SCENARIO 1]
1. Start CSGO
2. Inject
3. Load config without inventory items
4. Start Workshop aim_botz
5. Do 4-5 kills
6. No crash, keep playing

[SCENARIO 2]
1. Start CSGO
2. Inject
3. Load same config with saved inventory items
4. Start Workshop aim_botz
5. Do 4-5 kills
6. Game crashes

[SCENARIO 3]
1. Start CSGO
2. Inject
3. Start Workshop aim_botz
4. Do some kills
5. Load same config with saved inventory items
6. Do 4-5 kills
7. No crash, keep playing

---

[Link to configs](https://drive.google.com/file/d/108D6bkP7iBTPQY1BD_L5Nmgk5ryPgWQ0/view?usp=share_link)

---

Latest source, Microsoft Visual Studio Community 2022 (64 bit) Version 17.3.5, Windows 11 Pro 22H2 build 22621.525, Windows SDK 10.0.19041.0, Platform Visual Studio 2022 v143

---

Issue mentioned in:
#3838 - #3848 - #3840 - #3843

**Comment by horizon1g** [comment]
for me it crashes when literally walking around with the inventory changer

**Comment by Essential87** [comment]
Still persists
[c4964783e74814adf395691f363c6ff4200e7ee9](https://github.com/danielkrupinski/Osiris/commit/c4964783e74814adf395691f363c6ff4200e7ee9)

**Comment by Essential87** [comment]
@danielkrupinski 
Still persists
[01e9e735056c4a8938a74f48bdf56f09d50de4fd](https://github.com/danielkrupinski/Osiris/commit/01e9e735056c4a8938a74f48bdf56f09d50de4fd)

**Comment by danielkrupinski** [comment]
Could you try without gloves equipped?

**Comment by Essential87** [comment]
Yes, working good without gloves

**Comment by Essential87** [comment]
@danielkrupinski 
Issue persists

**Comment by free0ne87** [comment]
No fix for me yet.

**Comment by free0ne87** [comment]
Mentioned in #3882

**Comment by Essential87** [comment]
Persists

**Comment by danielkrupinski** [comment]
Maybe fixed in 3912fdcea25ed91dde9a4fe3f44d6ccc57c1aa18

**Comment by Essential87** [comment]
> Maybe fixed in [3912fdc](https://github.com/danielkrupinski/Osiris/commit/3912fdcea25ed91dde9a4fe3f44d6ccc57c1aa18)
[SOLVED]
