### ISSUE TITLE
[Feature Request] ImGUI Radar

### ISSUE THREAD

**Issue by 0xE232FE** [danielkrupinski/Osiris#386]
Hello Everyone,

Can you implement a ImGUI Radar with Orientation information?

Something similar to this.
https://www.unknowncheats.me/forum/general-programming-reversing/135529-how-implement-simple-radar.html

So it is more legit to know where the enemy is looking at instead of watching his orientation through the wall. You know what I mean? I have seen it on some Linux Hacks and it is pretty cool for legit cheating!

**Comment by NexSqaud** [comment]
Than you do not like the radar hack?

**Comment by Kron1Q** [comment]
AimTux has this. Just c+p

https://github.com/AimTuxOfficial/AimTux/blob/master/src/Hacks/radar.cpp

**Comment by 0xE232FE** [comment]
oh yes that is a good orientation for the Radar Hack. Thanks!
