### ISSUE TITLE
Injected but no menu

### ISSUE THREAD

**Issue by Mehdi2000-hub** [danielkrupinski/Osiris#3862]
Injected DLL successfully but when press `insert` ..nothing happens
(injected with process hacker 2 & checked if dll file loaded ([image](https://1drv.ms/u/s!AvVpKV5xlp48nU6Hy3UdAHakhIH4?e=nswEAP)))

**Comment by Mehdi2000-hub** [comment]
Doesn't matter anymore ,Solved by moving Osiris.dll to `C:\Windows\SysWOW64`

**Comment by Xsintashi** [comment]
also u could use better injector

**Comment by SuperK2-OS** [comment]
> also u could use better injector

Any injector suggestions that are not full of malware?
