### ISSUE TITLE
Afraid of BAN

### ISSUE THREAD

**Issue by Mehdi2000-hub** [danielkrupinski/Osiris#3863]
Hi there ,Thanks for this awesome tool!
But I'm a little afraid of getting banned ,Can this cheat be detected by the game??

**Comment by free0ne87** [comment]
Use vac bypass

**Comment by Mehdi2000-hub** [comment]
> Use vac bypass

How?

**Comment by free0ne87** [comment]
https://github.com/danielkrupinski/VAC-Bypass/blob/master/README.md

But it is good practice to never use cheats on your main account.

**Comment by free0ne87** [comment]
Currently vac bypass is detected, but it only ruins the trust factor, and you can not get vac ban, only thing valve can do for now is do competitive cooldown as for griefing.

**Comment by free0ne87** [comment]
Be advised, vac detects also kernelmode cheats.
