### ISSUE TITLE
errors building on linux

### ISSUE THREAD

**Issue by meth1337** [danielkrupinski/Osiris#3865]
`CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindFreetype.cmake:157 (find_package_handle_standard_args)
  Dependencies/imgui/CMakeLists.txt:15 (find_package)
`
xD 
help pls 
gcc/g++ installed 
how do i manage to fix all the issues with finding packages?

**Comment by danielkrupinski** [comment]
Install freetype.
