### ISSUE TITLE
[Triggerbot] Not shoting on Dust2 from T-Spawn to middle Double Door.

### ISSUE THREAD

**Issue by 0xE232FE** [danielkrupinski/Osiris#387]
Hello Everyone,

It happens that the Triggerbot doesn't shot the Enemy standing in Doubledoor clear visible and the Triggerbot doesn't fire. Can someone explain this? And sometimes it shots sometimes not.

Thanks for declaration! I am totally confused.

**Comment by jdb-jdb** [comment]
It works fine on mine. I have ran stable and forked and edited versions of Osiris and all systems work. Maybe it's your config, you could try changing the shot delay. It could also be if the fov and crosshair plaecment isn't on the person ie(too high or low whatever) that it doesn't work then. I'm not sure. Feel free to send me a vid of what exactly happens and I will try help as best as I can
