### ISSUE TITLE
Two questions out here

### ISSUE THREAD

**Issue by Mehdi2000-hub** [danielkrupinski/Osiris#3871]
`1` First sorry for posting a lot ..I'm new to this
`2` Can other players see my skins&stickers(etc) or only me?
`3` I got this [`cooldown`](https://help.steampowered.com/en/faqs/view/1A06-BC6C-B2EA-1FD2)
Thanks

**Comment by gr1ndy** [comment]
1. No, its clientsided

2. verify game files.

**Comment by free0ne87** [comment]
Close the issues once solved. And things that are not Osiris issues, should be opened in discussions section.
