### ISSUE TITLE
Crashes game when using "unhook"

### ISSUE THREAD

**Issue by Essential87** [danielkrupinski/Osiris#3872]
As title

**Comment by BasicllyMaximqs** [comment]
unhooking doesn't necessarily mean a clean "pullout" of csgo, alot of features or changes made still apply, i wouldn't see why you would like to unhook anyway, i believe its normal behavior if you are still in-game

**Comment by free0ne87** [comment]
It's one of the cheat functions, else @danielkrupinski should have been removed it.

**Comment by Essential87** [comment]
@danielkrupinski issue persists

**Comment by TauCSGO** [comment]
This error has not yet been solved and I also add the following

https://github.com/danielkrupinski/Osiris/issues/3882

Regards
