### ISSUE TITLE
Help, Chinese is not available after Visual Studio update

### ISSUE THREAD

**Issue by Bywnb** [danielkrupinski/Osiris#388]
am chinese and always use imgui.I can compile Osiris properly before.When I updated Visual Studio to the latest version this morning, the code reported errors.

ImGui::Text(u8"Color颜色");

This code works fine before Visual Studio version 16.2.0,But it doesn't works after I updated it this morning.

The wrong:
Including Chinese: error C2664: “void ImGui::Text(const char *,...)”: 无法将参数 1 从“const char8_t [7]”转换为“const char *”

English:void ImGui::Text(const char *,...)”: Cannot convert parameter 1 from "const char8_t [7]" to "const char *"

In addition, my project compiles normally when I delete "u8". However, after deleting "u8", Chinese cannot be displayed normally

Maybe code error related to imgui

**Comment by danielkrupinski** [comment]
Add `/Zc:char8_t-` option to compiler command line.

**Comment by Bywnb** [comment]
> Add `/Zc:char8_t-` option to compiler command line.

I'm sorry your method doesn't seem to work, but I've changed the C++ language standard.
When I change std:c++latest to std:c++17, the project compiles properly
But does compiling like this have any bad effects?

**Comment by danielkrupinski** [comment]
Nope, you just will be unable to use C++20 features.
