### ISSUE TITLE
Crash when loading any cfg within a map

### ISSUE THREAD

**Issue by TauCSGO** [danielkrupinski/Osiris#3882]
As the title says, when there are several cfgs, if they are loaded and changed outside the map, lobby, there are no problems. When we proceed to change a cfg for any other within a map or playing a game, csgo closes

I have tried with new cfgs created from 0 since this last update a few hours ago and the same thing happens

**Comment by TauCSGO** [comment]
This was **not** fixed @danielkrupinski 
Loading, editing and saving a cfg within a map causes the game to crash

**Comment by danielkrupinski** [comment]
Do you have gloves added to the inventory in the config?

**Comment by TauCSGO** [comment]
> Do you have gloves added to the inventory in the config?

Nothing, I don't use inventory change

**Comment by TauCSGO** [comment]
> Do you have gloves added to the inventory in the config?

You can do this test
Create any configuration, with some active options
Create other configurations, with other options active
(aimbot, glow, chams, a few misc)

Enter any map, load one cfg, switch to another cfg = crash

**Comment by TauCSGO** [comment]
**The problem was already fixed in this latest update.** 
Thank you very much @danielkrupinski
