### ISSUE TITLE
Crash on config loading

### ISSUE THREAD

**Issue by kirill-21** [danielkrupinski/Osiris#3885]
If you switch configs on the map - it crashes, if you load config before loading to the map, everything is okay

**Comment by kirill-21** [comment]
[legit-osiris-by-w1ndyxz.txt](https://github.com/danielkrupinski/Osiris/files/10047302/legit-osiris-by-w1ndyxz.txt)
[RedLegit.txt](https://github.com/danielkrupinski/Osiris/files/10047303/RedLegit.txt)

**Comment by danielkrupinski** [comment]
Maybe fixed by 95658fb1e570cb3e7a5f5e77c5b2a20bab8b8aeb

**Comment by kirill-21** [comment]
> Maybe fixed by [95658fb](https://github.com/danielkrupinski/Osiris/commit/95658fb1e570cb3e7a5f5e77c5b2a20bab8b8aeb)

No, still crashes

**Comment by kirill-21** [comment]
![image](https://user-images.githubusercontent.com/63228361/202865850-2888c9cf-a251-4038-9019-aebbd03b3d96.png)
Seems to be fixed in one of these commits, thank you

**Comment by TauCSGO** [comment]
https://github.com/danielkrupinski/Osiris/issues/3882#issuecomment-1320958721
