### ISSUE TITLE
No armor bar

### ISSUE THREAD

**Issue by doesdismatter** [danielkrupinski/Osiris#3888]
The README.md file mentions an armor bar but it's not in  the cheat, has anyone made on or can I find it anywhere?

**Comment by fanat1cc** [comment]
It's apart of the health bar in esp

**Comment by doesdismatter** [comment]
Ok, sorry, I may be blind but i still don't see it anywhere, armor is mentioned 4 times in the whole code and none of those times is it mentioned to draw an armor bar, or at least I didn't see  it anywhere esle.
