### ISSUE TITLE
pattern finder will treat all 0x3F opcodes as wildcard

### ISSUE THREAD

**Issue by rollraw** [danielkrupinski/Osiris#3889]
the `?` char have `U+003F` byte representation what is also valid one-byte opcode

current implementation of pattern scanner expects that all `?` are wildcards and since you didn't make mask separate, this may lead to wrong address/search fail
https://github.com/danielkrupinski/Osiris/blob/cfabd39bafea43e6a9a55ff4a14c6862404f7bfa/Source/Utils/PatternFinder.cpp#L53

possible fast solution would be change wildcard to double `?` character because `3F 3F` isn't valid two-byte opcode, and threat only them as ssingle wildcard

**Comment by danielkrupinski** [comment]
Why did you close this?

**Comment by rollraw** [comment]
uh i revisited that and thought you were checking everything correctly, now i read that again and issue is still valid. lol my bad

**Comment by danielkrupinski** [comment]
Now patterns are validated at compile time, so it's not possible to use 3F byte.
