### ISSUE TITLE
Some settings enabled in Visuals

### ISSUE THREAD

**Issue by Essential87** [danielkrupinski/Osiris#3897]
Some settings are enabled by default in Visuals tab. I do reset config and it clears, but when I inject again it returns with some features enabled.

I think @danielkrupinski has forgot something while doing this: [Commit](https://github.com/danielkrupinski/Osiris/commit/b9f30642a814e6d9d9c267ba7576479f69b453fa#diff-8962f6453a633118ddb09f11f2472f8a4306d646151567e2bc13742046486c8bR80-R95)

**Comment by CrayonShinChin** [comment]
i agree with you bro
