### ISSUE TITLE
Add Balance aa aka Desync anda dd flip so we can make it left,right or back

### ISSUE THREAD

**Issue by HugeSwantz** [danielkrupinski/Osiris#391]

**Comment by Bywnb** [comment]
you can do it yourself

**Comment by l0ccy** [comment]
++++

**Comment by ijre** [comment]
https://github.com/ijre/Osiris/blob/master/Hacks/AntiAim.cpp
https://github.com/ijre/Osiris/blob/master/Hacks/AntiAim.h
https://github.com/ijre/Osiris/blob/master/Config.cpp#L83
https://github.com/ijre/Osiris/blob/master/Config.cpp#L410
https://github.com/ijre/Osiris/blob/master/Config.h#L55
https://github.com/ijre/Osiris/blob/master/Hooks.cpp#L110
https://github.com/ijre/Osiris/blob/master/SDK/Entity.h#L38 (last one needed as i have certain weapons "banned" from the antiaim)

feel free to paste as needed

**Comment by Bywnb** [comment]
thanks




------------------ 原始邮件 ------------------
发件人: "Paige Seivertson"<notifications@github.com>;
发送时间: 2019年8月7日(星期三) 晚上9:53
收件人: "danielkrupinski/Osiris"<Osiris@noreply.github.com>;
抄送: "铁血硬汉蔡徐坤"<1746935696@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [danielkrupinski/Osiris] Add Balance aa aka Desync anda dd flipso we can make it left,right or back (#391)




https://github.com/ijre/Osiris/blob/master/Hacks/AntiAim.cpp
 https://github.com/ijre/Osiris/blob/master/Hacks/AntiAim.h
 https://github.com/ijre/Osiris/blob/master/Config.cpp#L83
 https://github.com/ijre/Osiris/blob/master/Config.cpp#L410
 https://github.com/ijre/Osiris/blob/master/Config.h#L55
 https://github.com/ijre/Osiris/blob/master/Hooks.cpp#L110
 https://github.com/ijre/Osiris/blob/master/SDK/Entity.h#L38 (last one needed as i have certain weapons "banned" from the antiaim)
 
feel free to paste as needed
