### ISSUE TITLE
Suspicious movement of the player model.

### ISSUE THREAD

**Issue by relativist** [danielkrupinski/Osiris#3915]
The movements are strange, unnatural when you walk slowly. I especially see on replays when they kill me. The legs move on their own. Walking steps look like zombie legs.

Has anyone experienced a similar display issue?
After all, this is the first sign that a person uses cheats.

How to fix player movements like all normal models?
Build with ubuntu 20.04

>cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=gcc-11 -D CMAKE_CXX_COMPILER=g++-11 ..
> make -j $(nproc --all)

and then inject

**Comment by Xsintashi** [comment]
its visual glitch

**Comment by diekunstderfuge** [comment]
Sometimes I have the same problem and I also see other players moving this way. Some people have even said on chat that I was moving strangely and I was kicked because of that.
