### ISSUE TITLE
new update 

### ISSUE THREAD

**Issue by vnlrob** [danielkrupinski/Osiris#3916]
cheat crash :7

**Comment by vnlrob** [comment]
is it possible to update it myself

**Comment by ofyria** [comment]
[hazedumper](https://github.com/frk1/hazedumper) - UC's official .exe off it => [Haze-Dumper](https://www.unknowncheats.me/forum/downloads.php?do=file&id=24050)
Must be into Source/Memory

That should be enough. If you don't know how to replace offsets, you can find a list to copy paste off. Or just read a tut in UC's csgo category.

**Comment by Xsintashi** [comment]
as long as u used debug to show what causes the crash
