### ISSUE TITLE
Will I get banned with this code?

### ISSUE THREAD

**Issue by wirekuro** [danielkrupinski/Osiris#3919]
void Misc::forceCrosshair(const csgo::Engine& engine) noexcept
{
    static auto disablecrosshair = interfaces.getCvar().findVar("weapon_debug_spread_show");

    if (engine.isInGame()) {
        if (miscConfig.forceCrosshair == true && localPlayer.get().isScoped() == 0) {

            {
                GameData::Lock lock;
                if (const auto& local = GameData::local(); !local.exists || !local.alive || !local.noScope)
                    return;
            }
            csgo::ConVar::from(retSpoofGadgets->client, disablecrosshair).setValue(3);
        }

        else {
            csgo::ConVar::from(retSpoofGadgets->client, disablecrosshair).setValue(0);
        }
    }
}

**Comment by ofyria** [comment]
Code itself doesn't get stuffs detected unless you go for odd features that are untrusted or vmt hooks kinda stuffs.

Signatures are.
