### ISSUE TITLE
question

### ISSUE THREAD

**Issue by cutiehvst** [danielkrupinski/Osiris#3920]
Hello, this isn't really an issue, but just a question.

Does it actually matter from where i call game functions?
Is it bad when i call client.dll's function from engine.dll and otherwise?
Does it actually change anything in terms of trustfactor?

2. Have you found anything related to detection of vmtswap's hooking method?

Best regards.

**Comment by Xsintashi** [comment]
1. 50/50
2. What do u mean by calling client.dll's function from engine.dll and otherwise. Give an example.
3. No

**Comment by cutiehvst** [comment]
by first and second meant the same. sorry, i was a little bit chaotic.
I mean:
calling client.dll function with engine's returnaddress

**Comment by ClaudiuHKS** [comment]
@cutiehvst Osiris uses engine gadget in all minhook calls, including createmove which is clientmode related.

https://github.com/danielkrupinski/Osiris/blob/master/Source/Hooks/MinHook.h#L30

**Comment by danielkrupinski** [comment]
Return addresses have to be inside any of the game modules. This check may be extended in the future (if CSGO devs decide to), so it's better to use a gadget from the same game module which normally calls the function.
