### ISSUE TITLE
Bomb Timer is broken

### ISSUE THREAD

**Issue by SeedCrackerXEnjoyer** [danielkrupinski/Osiris#3922]
No matter where the bomb has been planted, the bomb timer in the miscellaneous tab with always say the bomb was planted at A site.

**Comment by KaSock** [comment]
I found the same problem.

**Comment by SeedCrackerXEnjoyer** [comment]
> I found the same problem.

I hope he fixes it soon.

**Comment by SeedCrackerXEnjoyer** [comment]
Thanks Daniel!
