### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by JannesBonk** [danielkrupinski/Osiris#3923]
![image](https://user-images.githubusercontent.com/86556266/209692464-a5711af6-0581-4822-8e16-a92b5acfde20.png)
Any way to fix?

**Comment by SeedCrackerXEnjoyer** [comment]
I would try building osiris again

**Comment by SeedCrackerXEnjoyer** [comment]
if that doesn't work i would wait for Daniel to help you.

**Comment by danielkrupinski** [comment]
Have you made any modifications to the source code?
