### ISSUE TITLE
Grenades with Antiaim fucked up

### ISSUE THREAD

**Issue by PUREHAX** [danielkrupinski/Osiris#393]

**Comment by Bywnb** [comment]
Yes.When u enable the antiaim , the grenade you throw will deflect

**Comment by cojo1989** [comment]
Yep, Daniel will fix it soon. Its first time when he do something like this. Just wait

**Comment by noob-cat** [comment]
Yeah this is very annoying and inconsistent to pull off.

**Comment by l0ccy** [comment]
++++
