### ISSUE TITLE
Is osiris detected?

### ISSUE THREAD

**Issue by SeedCrackerXEnjoyer** [danielkrupinski/Osiris#3930]
I got vacced 2 times

I am using extreme injector v3 with manual map to inject osiris into csgo with all the scramble features enabled. 

Is it my injector thats detected or is it osiris?

**Comment by Xsintashi** [comment]
extreme injector 💀 
Injector is hella detected. idk how osiris is doing

**Comment by ClaudiuHKS** [comment]
It's not VAC detected but I always get a game ban in exactly 40-45 days after the first injection on an account.

**Comment by danielkrupinski** [comment]
There was an unnoticed change to the UserCmd which was likely the cause of trust factor issues. It was fixed last week.

**Comment by 1310s** [comment]
> There was an unnoticed change to the UserCmd which was likely the cause of trust factor issues. It was fixed last week.

what injector do you recommend?
