### ISSUE TITLE
Osiris not working on windows anymore

### ISSUE THREAD

**Issue by zanex78** [danielkrupinski/Osiris#3934]
I inject the client and the only thing happening is this (Yes I tried reinstalling .net runtime and core):

![image](https://user-images.githubusercontent.com/81015632/213533153-07d8f6bf-c4a4-4004-8931-99bcbe84feb3.png)

**Comment by zanex78** [comment]
What source? I have the client updated .net core and framework and visual c++ idk what to update

**Comment by Xsintashi** [comment]
first of all update source code, second build in release, not in debug. voila

**Comment by Xsintashi** [comment]
First of all, use latest source code. Second, build in release, not in debug. Voila!
