### ISSUE TITLE
trust factor

### ISSUE THREAD

**Issue by stereokumonomu** [danielkrupinski/Osiris#3943]
i've been playing for a couple games and then my trust factor turned out to be red. what is happening actually? i've been using osiris for a years and haven't got ban, until this one day maybe it wasn't my lucky day which is i got banned just because of my trust factor turned out to be permenantly red. is it about the injector itself or the source code itself? can someone help me? thanks in advance :)

**Comment by sevcator** [comment]
you must use a CSGhost or other undetectable injector, try re download source of Osiris and build again, or you get more reports

**Comment by stereokumonomu** [comment]
do you have discord? can we talk there? > you must use a CSGhost or other undetectable injector, try re download source of Osiris and build again, or you get more reports

**Comment by sevcator** [comment]
bro [here link](https://www.unknowncheats.me/forum/cs-go-releases/454734-csghost-v4-injector-integrated-vac-bypass.html) i don't know my account no prime don't get banned

**Comment by Xsintashi** [comment]
CSGHOST causes red tf

**Comment by stereokumonomu** [comment]
> bro [here link](https://www.unknowncheats.me/forum/cs-go-releases/454734-csghost-v4-injector-integrated-vac-bypass.html) i don't know my account no prime don't get banned

thanks buddy, appreciate it

**Comment by stereokumonomu** [comment]
> CSGHOST causes red tf

hi buddy, do you got discord? can we talk there? :D

**Comment by Zurek0x** [comment]
> > CSGHOST causes red tf
> 
> hi buddy, do you got discord? can we talk there? :D

ZYB#0001

**Comment by stereokumonomu** [comment]
> > > CSGHOST causes red tf
> 
> > 
> 
> > hi buddy, do you got discord? can we talk there? :D
> 
> 
> 
> ZYB#0001

done send request :)
