### ISSUE TITLE
Osiris immediately crashes after injecting on Linux. 

### ISSUE THREAD

**Issue by itswolt** [danielkrupinski/Osiris#3949]
I have tried using the latest two updates and the prior update and both immediately crash after the latest CSGO update.

**Comment by MaxHecateII** [comment]
yeah,steam update 2 days ago,then linux cheat engine like Osiris、kali、gamesneeze cant load in game now(csgo will crash after sucessfully injected).I try many system,but the result is same .

**Comment by fluentpwn** [comment]
Same here. ah4 crashes too.

**Comment by MissedShot** [comment]
CS:GO was updated recently, some patterns are outdated now. Just wait for fix

**Comment by hamad12a** [comment]
> patterns

Could you explain why the injection fails after game updates? 
Which file does define these patterns?
