### ISSUE TITLE
Cheat doesn't unhook properly

### ISSUE THREAD

**Issue by Deeb2323** [danielkrupinski/Osiris#395]
Hello,

I am doing heavy debugging sessions in general, and on this cheat I am not able to reinject the DLL after that I unhook the cheat from the GUI.

You should normally be able to reinject in the same process when unhooking properly, actually the only way is to restart the game.

**Comment by deprale** [comment]
Yes it's not properly unhooked, many changes done to the game are still in progress for example night mode.

**Comment by effex1337** [comment]
@Deeb2323 The unload doesn't support loadlib.
@deprale U got it wrong, it unhhoks properly the brightness works by changing a variable and has nothing to do with hooks.

**Comment by Bywnb** [comment]
when you unlocked, the changes still left in csgo.

**Comment by effex1337** [comment]
It changes some variables and has nothing to do with hooks. @Bywnb

**Comment by effex1337** [comment]
That's how it's supposed to be

**Comment by woah1337** [comment]
> It changes some variables and has nothing to do with hooks. @Bywnb

he means cvars not variables

**Comment by danielkrupinski** [comment]
You should now be able to reinject (4c4a5109101b30ec90d57636e513e468ab81b1f5).
