### ISSUE TITLE
Cannot inject Osiris.dll with Manual Map (sazinjector)

### ISSUE THREAD

**Issue by hoangxuanlam2007** [danielkrupinski/Osiris#3954]

**Comment by diekunstderfuge** [comment]
Saz himself says that manual map injection doesn't work with Osiris:

"Good to know :
**Some dlls aren't working with the Manual Map injection (For example : Osiris.dll).
If the game crash after the injection, try to use Load Library injection type."

[Source](https://corsair.wtf/topic/2269-new-sazinjector-v4-working-for-all-games-vac-bypass-integrated/)

If you want to use Manual Map you can use Extreme Injector, it is working. You can find a safe and trusted source [Here](https://www.unknowncheats.me/forum/downloads.php?do=file&id=21570).
