### ISSUE TITLE
Menu thingy..

### ISSUE THREAD

**Issue by bruhmoment21** [danielkrupinski/Osiris#396]
Sometimes when i press Insert the menu doesn't open.. is anyone experiencing the same thing rn?

**Comment by GaghiZor** [comment]
It happens to me too. Sometimes I can't even close the cheat's interface.

**Comment by wieisstimpee** [comment]
never happened to me

**Comment by cojo1989** [comment]
Replace in hooks.cpp
This:
``` if (GetAsyncKeyState(config.misc.menuKey) & 1) {```
with this: 
```if (msg == WM_KEYDOWN && LOWORD(wParam) == config.misc.menuKey) {```
