### ISSUE TITLE
Big problem

### ISSUE THREAD

**Issue by StixuYT** [danielkrupinski/Osiris#3963]
Cannot build (removed a few features)

![image](https://user-images.githubusercontent.com/93591585/218278713-020b88dd-cc55-472e-92fc-a8f6452483d6.png)

any help? please

**Comment by fanat1cc** [comment]
That's always there, did you make sure your building in release x86

**Comment by fanat1cc** [comment]
If there are any other errors plz link them

**Comment by StixuYT** [comment]
Something very weird is going on, when I tried to build in debug mode(I was building it in debug), because I wanted to test both methods now that you've told me about the fact that release mode could fix the operator template error, I have gotten more errors from GlobalContext.obj; Aimbot.obj and GUI.obj, I fixed those errors and it seems to build fine even in debug, but yesterday I didn't get a single error besides the one that I mentioned above. Hidden errors?

**Comment by Xsintashi** [comment]
i guess u dont have any basic knowledge about c++. Cuz of this, u didnt remove features properly. Thats why u get link errors, I think

**Comment by Xsintashi** [comment]
Also i dont see a reason deleting features cuz >>> It doesnt make cheat less detected <<<
