### ISSUE TITLE
[Bug] Inventory changer

### ISSUE THREAD

**Issue by MissedShot** [danielkrupinski/Osiris#3964]
### Affected version

Latest Osiris build
Tested on Fedora Linux Workstation

### Bug summary

Weapon start shooting floor after applying skins

### Steps to reproduce

1. Inject Osiris and add some skins in main menu
2. Load on map
3. Start shooting in crouch

### Workaround
Can be fixed by Force Update or rejoin on map

### Relevant logs, screenshots, screencasts etc.

https://user-images.githubusercontent.com/49341012/218328632-2c9cbf17-0d54-445a-a3de-1cc7f0643a87.mp4

**Comment by loginquitas** [comment]
here is simple fix:

don't use skin changer.

**Comment by gr1ndy** [comment]
well thats weird, ngl.
