### ISSUE TITLE
Old custom osiris pattern errors.

### ISSUE THREAD

**Issue by Liam5750** [danielkrupinski/Osiris#3968]
Idk how this failed to find pattern thing works but here are the wrong patterns:
#8
#75
~~#76~~
~~#77~~
Then it injects but my inventory changer I added from new osiris don't work. It used to work so I am assuming it's from the outdated patterns. Any help on how to find these patterns would be appreciated <3

**Comment by Liam5750** [comment]
Update: fixed 76 and 77.

**Comment by diangian07** [comment]
Did you figure out how to fix the pattern 8 error?

**Comment by Liam5750** [comment]
U gotta change memory.cpp. I just used the ones from OsirisAndExtra.

**Comment by diangian07** [comment]
when you say used do you mean you literally like copy and pasted the memory files in?

**Comment by Liam5750** [comment]
> when you say used do you mean you literally like copy and pasted the memory files in?

no
