### ISSUE TITLE
Adding login system

### ISSUE THREAD

**Issue by augis01** [danielkrupinski/Osiris#3969]
has anyone made login system on osiris with like keyauth or something similar? if so, please dm me on discord JoddYt#2320, i would like to get some advice

**Comment by Frouk3** [comment]
why do you need that for free cheat 💀

**Comment by gr1ndy** [comment]
dawg..

**Comment by gr1ndy** [comment]
> > why do you need that for free cheat 💀
> 
> why do you need luas for a legit cheat 💀

why not?? why are u gate keeping scripting api only for p2c?

**Comment by afafontes** [comment]
because he wants to sell a free cheat to kids lmao isn't it obvious

**Comment by DrunkenBlyatHvH** [comment]
> has anyone made login system on osiris with like keyauth or something similar? if so, please dm me on discord JoddYt#2320, i would like to get some advice

so you want to make money with a cheat that anyone can get for free?

**Comment by ImsilverDev** [comment]
LMAO
