### ISSUE TITLE
Do you need "set solib-search-path" or "set sysroot"?

### ISSUE THREAD

**Issue by daniliammo** [danielkrupinski/Osiris#3972]
sudo gdb -batch-silent -p $(pidof csgo_linux64) -ex "call (void*)__libc_dlopen_mode(\"$PWD/libOsiris.so\", 2)"

warning: Could not load shared library symbols for bin/linux64/launcher_client.so.
Do you need "set solib-search-path" or "set sysroot"?
78	../sysdeps/unix/sysv/linux/clock_nanosleep.c: Нет такого файла или каталога.

Ubuntu 22.04.2 LTS

**Comment by faroperfect** [comment]
type " make all "
and type that given line again, then it has been inserted.
