### ISSUE TITLE
Need help in implementing something (mostly done)

### ISSUE THREAD

**Issue by dyson12** [danielkrupinski/Osiris#3980]
```cpp
void __fastcall getColorModulation(void* ecx, void* edx, float* r, float* g, float* b) {
	hooks->matsystem.call_original_detour<void>(ecx, r, g, b);

	const auto material = Material::from(ret_spoof_gadgets->engine, (MaterialPOD*)(ecx));
	if (material.getPOD() == nullptr)
		return;

	if (material.isErrorMaterial())
		return;

	auto group = HASH_RT(material.getTextureGroupName());
	switch (group) {
	case HASH("World textures"):
	{
		*r *= 0.25f;
		*g *= 0.25f;
		*b *= 0.25f;
	}
	break;
	case HASH("SkyBox textures"):
	{
		*r *= 84.f / 255.f;
		*g *= 47.f / 255.f;
		*b *= 130.f / 255.f;
	}
	break;
	case HASH("StaticProp textures"):
	{
		*r *= 0.4f;
		*g *= 0.4f;
		*b *= 0.4f;
	}
	break;
	}
}
```

this is how far I got
this is the signature "55 8B EC 83 EC ? 56 8B F1 8A 46"

then i get this error
```
Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.
```
in
```cpp
template <typename T, typename... Args>
    T invokeFastcall(std::uintptr_t ecx, std::uintptr_t edx, std::uintptr_t functionAddress, std::uintptr_t gadgetAddress, Args... args) noexcept {
        detail::Context context;
        return invokeFastcall<T, Args...>(ecx, edx, context, functionAddress, gadgetAddress, args...);
    }
```
Tracing the call stack leads to getTextureGroupName()

this hook is for better world modulation.
Please take a look @danielkrupinski 
Thanks!

**Comment by Xsintashi** [comment]
how do u hook it?

**Comment by dyson12** [comment]
sigscan in memory.cpp then hook using minhook, calling original with ret spoof works fine too.

**Comment by danielkrupinski** [comment]
`invokeFastcall()` shouldn't be called there at all. Maybe `call_original_detour` uses fastcall instead of thiscall?

**Comment by dyson12** [comment]
> `invokeFastcall()` shouldn't be called there at all. Maybe `call_original_detour` uses fastcall instead of thiscall?

Calling original works fine, the issue is calling the virtual functions from Material; getTextureGroupName() in this case

**Comment by dyson12** [comment]
![image](https://user-images.githubusercontent.com/126135998/222862300-e7d8d2bd-4243-4ec3-8675-27a919e5fc7c.png)
Here's the call stack

**Comment by dyson12** [comment]
![image](https://user-images.githubusercontent.com/126135998/222862983-92fd50b6-d225-4574-ac08-3ea375c0efb4.png)
Callstack and auto variables

**Comment by dyson12** [comment]
I am fully out of ideas. @danielkrupinski maybe you could give it a shot, I've updated the post with my latest progress on it.
