### ISSUE TITLE
Exception thrown at 0x18E789F8 (vgui2.dll) in csgo.exe: 0xC0000005: Access violation reading location 0x77C38AAC.

### ISSUE THREAD

**Issue by Smellon69** [danielkrupinski/Osiris#3981]
I know one of yall mfs got the commit with the fix. I think it's for thirdperson or smth

**Comment by Liam5750** [comment]
fuck me. I fixed and now it's just crashing $$$

**Comment by Xsintashi** [comment]
nullptr at line 43

**Comment by Liam5750** [comment]
Ok don't be mean :(

**Comment by Xsintashi** [comment]
dude, we can't help you if we don't see any code

**Comment by Liam5750** [comment]
Please I will help later ahhhh
