### ISSUE TITLE
[Question] Where is the custom hit/killsound location?

### ISSUE THREAD

**Issue by smithx1337** [danielkrupinski/Osiris#3983]
"csgo/sound", means on Osiris's source (CSGO folder, and I need to make a "sound" folder there and recompile?) or on the CSGO folder (Steam\steamapps\common\Counter-Strike Global Offensive\csgo and I need to make a "sound" folder there?)?

I tried to place a sound file (both on .wav and .mp3 formats) at the csgo "sound" directory that I made but it didn't work.

**Comment by smithx1337** [comment]
nevermind, it works against bots. CSGO detects it though, and doesn't let me start a new game against people (no bans so far however).

**Comment by danbln1** [comment]
how did u make it work

**Comment by M3351AN** [comment]
afaik, the .wav files should be mono
