### ISSUE TITLE
CMake Error: The source directory "Osiris/build" does not exist.

### ISSUE THREAD

**Issue by 8fn** [danielkrupinski/Osiris#3984]
➜  Osiris git:(master) git clone --depth=1 https://github.com/danielkrupinski/Osiris.git
Cloning into 'Osiris'...
remote: Enumerating objects: 1127, done.
remote: Counting objects: 100% (1127/1127), done.
remote: Compressing objects: 100% (841/841), done.
^Cceiving objects:  17% (192/1127)   
➜  Osiris git:(master) 
➜  Osiris git:(master) cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_CXX_COMPILER=g++-11 -S . -B build

CMake Error: The source directory "/home/tanjil/Osiris/build" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by ImsilverDev** [comment]
you interrupted the cloning process
run this cmd:
git clone --depth=1 https://github.com/danielkrupinski/Osiris.git
once its done do:
cd Osiris
after that you can do this:
cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_CXX_COMPILER=g++-11 -S . -B build
and finally this:
cmake --build .

**Comment by 8fn** [comment]
Fixed it by upgrading cmake and installing gcc-11
https://askubuntu.com/questions/829310/how-to-upgrade-cmake-in-ubuntu
```
sudo apt install gcc-11 g++-11
```
And used following command
```
sudo apt-get install libfreetype6-dev
```
