### ISSUE TITLE
Endpoints.obj

### ISSUE THREAD

**Issue by kasterialgit** [danielkrupinski/Osiris#3988]
what does Endpoints.obj I'm getting 19 erros from that file. No idea on how to fix.

**Comment by Xsintashi** [comment]
Have u changed something in code?

**Comment by kasterialgit** [comment]
> Have u changed something in code?

Yes I removed some unwanted misc features

**Comment by Xsintashi** [comment]
> > Have u changed something in code?
> 
> Yes I removed some unwanted misc features

conclusion is u didnt remove these featueres entirely. Checks headers in files where they were, there should bedeclarations from deleted files which u didnt remove,

**Comment by kasterialgit** [comment]
yes yes the feature was still included in globcontext
thx
