### ISSUE TITLE
Bomb timer better ui suggestion

### ISSUE THREAD

**Issue by Bywnb** [danielkrupinski/Osiris#400]
Bomb time  could be changed to a progress bar to the left of the game window.The progress bar has a countdown function.When time is running out, the progress bar changes from green to yellow and preferably red.That's cool

**Comment by cojo1989** [comment]
Actualy will not be a bad ideea, we will see if Daniel would agree us. I would like to see a better design for that and maybe a little bigger text. :)

**Comment by noob-cat** [comment]
That would look a lot cleaner but is it really that better? I think knowing exact seconds is better. Or just merge both somehow.

**Comment by Bywnb** [comment]
The exact seconds can follow the progress bar.

**Comment by wieisstimpee** [comment]
great idea! I hope he sees this and wants to implement.

**Comment by tirziz** [comment]
And maybe Bom timer tell us the defuser got it or not, sometimes its very difficult see

**Comment by l0ccy** [comment]
++++

**Comment by PUREHAX** [comment]
And also maybe a moveable window +++
