### ISSUE TITLE
VAC errors

### ISSUE THREAD

**Issue by noob-cat** [danielkrupinski/Osiris#401]
After like 5 mins on a vac server I get disconnected and sent to this site
https://support.steampowered.com/kb_article.php?ref=2117-ILZV-2837
And only after restarting my pc and waiting 10 minutes this problem solves. But after I go back in with this cheats same happens again. Thought it may be my injector but I've tested 3 injectors and the same happens. Having a feeling it's because of the nskinz since it was detected a few months back.

**Comment by danielkrupinski** [comment]
What aimbot fov you use?

**Comment by noob-cat** [comment]
Yesterday all day I was using nothing but rage settings (all aimbot settings on max to HVH) and nothing happened. Today I get VAC errors every 5 minutes. Havent tried low fov, maybe it will not happen. I'll write here when I test

**Comment by noob-cat** [comment]
The cheat itself isnt detected, no untrusted bans or VAC bans.

**Comment by danielkrupinski** [comment]
Set max angle delta to 30 when playing casual game modes.

**Comment by wieisstimpee** [comment]
> The cheat itself isnt detected, no untrusted bans or VAC bans.

Never had this happen to me, ever. did you try verifying file integrity on steam? go to steam, game library right click csgo, properties >   local files > verify file integrity or something along of those lines? But do you use a public injector and what injection method did/do you use?

**Comment by noob-cat** [comment]
I'll try max delta to 30.

I was using extreme injector but it wasnt gettinf detected on other cheats. I doubt it's my injector since I tried xenos same problem. 
My injection settings using extreme injector:
- close on inject
- stealth inject
- erase pe
I first open the injector, then reopen in secure mode and only then inject.
Using for lets sake Katebot i havent been detected for about a week playing prime matchmaking.

**Comment by noob-cat** [comment]
Oh and I always keep my dll with the injector on usb and then eject it after I load up a config just in case. Dont know if it helps at all

**Comment by wieisstimpee** [comment]
> I'll try max delta to 30.
> 
> I was using extreme injector but it wasnt gettinf detected on other cheats. I doubt it's my injector since I tried xenos same problem.
> My injection settings using extreme injector:
> 
> * close on inject
> * stealth inject
> * erase pe
>   I first open the injector, then reopen in secure mode and only then inject.
>   Using for lets sake Katebot i havent been detected for about a week playing prime matchmaking.

I do recommend using literally anything else then ExtremeInjector and Xenos a site called "guidedhacking" has its own injector. you do need to register to download but they have a great injector which isnt that known or at least not as known as extreme and xenos once you downloaded that use these settings:  ManualMap hidefrom debugger shift module clean data unlink from PEB randomize file names all enabled. This ensures that there are no traces left behind

**Comment by noob-cat** [comment]
Yeah well lowring max delta angle didnt help. I'll tey another injector you gave me then. Plus I compiled xenos myself since it was updated like 3 days ago so I thought it might not be detected after a source update.

**Comment by wieisstimpee** [comment]
> Yeah well lowring max delta angle didnt help. I'll tey another injector you gave me then. Plus I compiled xenos myself since it was updated like 3 days ago so I thought it might not be detected after a source update.

alright keep me updated!

**Comment by noob-cat** [comment]
Probably the easiest solution would be to just not to rage aimbot with 255 fov but it's so fun. Have you been raging and not having the same problem? Because I doubt I'd get this while using 3 fov trying to closet cheat.

**Comment by wieisstimpee** [comment]
> Probably the easiest solution would be to just not to rage aimbot with 255 fov but it's so fun. Have you been raging and not having the same problem? Because I doubt I'd get this while using 3 fov trying to closet cheat.

i never raged with this cheat

**Comment by noob-cat** [comment]
> > Probably the easiest solution would be to just not to rage aimbot with 255 fov but it's so fun. Have you been raging and not having the same problem? Because I doubt I'd get this while using 3 fov trying to closet cheat.
> 
> i never raged with this cheat

It's great but is only missing a resolver and more anti-aim options.

**Comment by tirziz** [comment]
Have u tried randoinjector, I never get detected with it

**Comment by noob-cat** [comment]
> Have u tried randoinjector, I never get detected with it

I really doubt it's the injector. But I'm trying out every suggestion so thanks.

**Comment by noob-cat** [comment]
> > I'll try max delta to 30.
> > I was using extreme injector but it wasnt gettinf detected on other cheats. I doubt it's my injector since I tried xenos same problem.
> > My injection settings using extreme injector:
> > 
> > * close on inject
> > * stealth inject
> > * erase pe
> >   I first open the injector, then reopen in secure mode and only then inject.
> >   Using for lets sake Katebot i havent been detected for about a week playing prime matchmaking.
> 
> I do recommend using literally anything else then ExtremeInjector and Xenos a site called "guidedhacking" has its own injector. you do need to register to download but they have a great injector which isnt that known or at least not as known as extreme and xenos once you downloaded that use these settings: ManualMap hidefrom debugger shift module clean data unlink from PEB randomize file names all enabled. This ensures that there are no traces left behind

Even with your injector and settings still got disconnected by VAC. It's definitely the rage aimbot settings. I'll just stop rageing.

**Comment by wieisstimpee** [comment]
> > > I'll try max delta to 30.
> > > I was using extreme injector but it wasnt gettinf detected on other cheats. I doubt it's my injector since I tried xenos same problem.
> > > My injection settings using extreme injector:
> > > 
> > > * close on inject
> > > * stealth inject
> > > * erase pe
> > >   I first open the injector, then reopen in secure mode and only then inject.
> > >   Using for lets sake Katebot i havent been detected for about a week playing prime matchmaking.
> > 
> > 
> > I do recommend using literally anything else then ExtremeInjector and Xenos a site called "guidedhacking" has its own injector. you do need to register to download but they have a great injector which isnt that known or at least not as known as extreme and xenos once you downloaded that use these settings: ManualMap hidefrom debugger shift module clean data unlink from PEB randomize file names all enabled. This ensures that there are no traces left behind
> 
> Even with your injector and settings still got disconnected by VAC. It's definitely the rage aimbot settings. I'll just stop rageing.

do you use silent aim?

**Comment by wieisstimpee** [comment]
if you do use silent aim then if you go above 1 fov it will disconnect you since it got better server side protection

**Comment by noob-cat** [comment]
> if you do use silent aim then if you go above 1 fov it will disconnect you since it got better server side protection

I'll try disabling silent aim but what you said makes a lot of sense. I was using aristois legit cheat and I got detected only after I turned on silent aim. Before turning on silent aim I was legit hacking a lot.

**Comment by wieisstimpee** [comment]
> > if you do use silent aim then if you go above 1 fov it will disconnect you since it got better server side protection
> 
> I'll try disabling silent aim but what you said makes a lot of sense. I was using aristois legit cheat and I got detected only after I turned on silent aim. Before turning on silent aim I was legit hacking a lot.

alright keep me updated i am curious :)

**Comment by noob-cat** [comment]
> > > if you do use silent aim then if you go above 1 fov it will disconnect you since it got better server side protection
> > 
> > 
> > I'll try disabling silent aim but what you said makes a lot of sense. I was using aristois legit cheat and I got detected only after I turned on silent aim. Before turning on silent aim I was legit hacking a lot.
> 
> alright keep me updated i am curious :)

So yeah it was the silent aim. Don't know why but I was using silent aim yesterday with rage settings all day long and didnt have this problem. Maybe it needs updating or something I don't know. But it wasn't the injector and this is the solution to the problem - turn of silent aim xD

**Comment by wieisstimpee** [comment]
> > > > if you do use silent aim then if you go above 1 fov it will disconnect you since it got better server side protection
> > > 
> > > 
> > > I'll try disabling silent aim but what you said makes a lot of sense. I was using aristois legit cheat and I got detected only after I turned on silent aim. Before turning on silent aim I was legit hacking a lot.
> > 
> > 
> > alright keep me updated i am curious :)
> 
> So yeah it was the silent aim. Don't know why but I was using silent aim yesterday with rage settings all day long and didnt have this problem. Maybe it needs updating or something I don't know. But it wasn't the injector and this is the solution to the problem - turn off silent aim xD

daniel should just remove silent aim, pretty useless with 1fov.. but nice

**Comment by noob-cat** [comment]
Or maybe improve it since aimbot is very annoying to control without it if you're rageing.

**Comment by wieisstimpee** [comment]
> Or maybe improve it since aimbot is very annoying to control without it if you're rageing.

in my experience its a great legit aimbot

**Comment by noob-cat** [comment]
Legit yes it's perfect.

**Comment by 0xE232FE** [comment]
My VAC Error was hard, it was my SSD from 2012. It have corrupted Data, thank got its just for the Steam Library. I changed the SSD to a new one and the VAC Error was gone after verify game files on the new SSD.
