### ISSUE TITLE
Streamproof

### ISSUE THREAD

**Issue by prolikeme** [danielkrupinski/Osiris#4015]
Can I ask if how does the streamproof work? Tried on nvidia instant replay but esp is still visible. Also tried on discord but it didnt also work. TIA!

**Comment by fanat1cc** [comment]
Chams and glow are visible on stream the stream proof esp is the esp things like Skeleton and that are stream proof

**Comment by prolikeme** [comment]
> Chams and glow are visible on stream the stream proof esp is the esp things like Skeleton and that are stream proof

Yeah I know but it doesn't work. Esp is still visible on nvidia instant replay and I read that it supports discord and steam but it doesn't work. Its still visible when I tried streaming it on discord

**Comment by fanat1cc** [comment]
> Yeah I know but it doesn't work. Esp is still visible on nvidia instant replay and I read that it supports discord and steam but it doesn't work. Its still visible when I tried streaming it on discord. The one I used was the snaplines since skeleton and others ruins my gameplay.

Is it in screen cap more or game cap , it requires direct game cap to work, that's why I suggest using obs instead

**Comment by prolikeme** [comment]
> > Yeah I know but it doesn't work. Esp is still visible on nvidia instant replay and I read that it supports discord and steam but it doesn't work. Its still visible when I tried streaming it on discord. The one I used was the snaplines since skeleton and others ruins my gameplay.
> 
> Is it in screen cap more or game cap , it requires direct game cap to work, that's why I suggest using obs instead

Im not sure. I just want to record my highlights through nvidia instant replay or even stream it on discord sometimes to clown my friends lol. I dont wanna use obs everytime I play since it can affect performance if im not mistaken so idk how stream proof works.

**Comment by fanat1cc** [comment]
> > > Yeah I know but it doesn't work. Esp is still visible on nvidia instant replay and I read that it supports discord and steam but it doesn't work. Its still visible when I tried streaming it on discord. The one I used was the snaplines since skeleton and others ruins my gameplay.
> > 
> > 
> > Is it in screen cap more or game cap , it requires direct game cap to work, that's why I suggest using obs instead
> 
> Im not sure. I just want to record my highlights through nvidia instant replay or even stream it on discord sometimes to clown my friends lol. I dont wanna use obs everytime I play since it can affect performance if im not mistaken so idk how stream proof works.

Well on discord it works fine just aslong as you use csgo application and not stream display/desktop

If you want to go more indepth on what shows up and maybe how to fix it to work with nvidia add me on discord.
fanatic_fire#8395

**Comment by prolikeme** [comment]
> > > > Yeah I know but it doesn't work. Esp is still visible on nvidia instant replay and I read that it supports discord and steam but it doesn't work. Its still visible when I tried streaming it on discord. The one I used was the snaplines since skeleton and others ruins my gameplay.
> > > 
> > > 
> > > Is it in screen cap more or game cap , it requires direct game cap to work, that's why I suggest using obs instead
> > 
> > 
> > Im not sure. I just want to record my highlights through nvidia instant replay or even stream it on discord sometimes to clown my friends lol. I dont wanna use obs everytime I play since it can affect performance if im not mistaken so idk how stream proof works.
> 
> Well on discord it works fine just aslong as you use csgo application and not stream display/desktop
> 
> If you want to go more indepth on what shows up and maybe how to fix it to work with nvidia add me on discord. fanatic_fire#8395 And about obs with the right settings there is no fps drop and I run on 2013 hardware with integrated graphics, 8gbs of ram so

Tried on discord with game capture (not desktop/display) but it didnt work and I always have black bars even tho my res is on full screen. Added you on discord. cheeba#6822

TIA!
