### ISSUE TITLE
请问作者这个如何处理呢

### ISSUE THREAD

**Issue by LxAnC** [danielkrupinski/Osiris#4019]
osiris不是有效的win32应用程序，这个无法正确生成dll文件无法正常启动

**Comment by Xsintashi** [comment]
use injector

**Comment by LxAnC** [comment]
<img width="349" alt="屏幕截图_20230413_231443" src="https://user-images.githubusercontent.com/76821521/231805682-008d2af8-d8bf-403a-b66c-fed345399044.png">

**Comment by LxAnC** [comment]
我使用debug目录的dll注入返回这个错误信息，请问我需要怎样正确操作，我的步骤是直接打开osiris,sin然后选择release与x86直接执行返回一个无法启动应用程序dll我不知道这是否有错，求解惑

**Comment by Xsintashi** [comment]
> 

I see this first time

**Comment by LxAnC** [comment]
> 我第一次看到这个

你们生成的dll文件输出在哪个目录呢？

**Comment by Xsintashi** [comment]
> 

in release
