### ISSUE TITLE
Strona która sprzedaje twojego cheata za 20zł

### ISSUE THREAD

**Issue by lakstick** [danielkrupinski/Osiris#402]
Cześć Daniel chciałbym cię poinformować ze strona advboost.eu sprzedaje twojego cheata za 20zł na miesiac nie wiem czy na to pozwalasz ale chcialem cię tylko poinformować.

**Comment by wieisstimpee** [comment]
> Cześć daniel chciałbym cię poinformować ze strona advboost.eu sprzedaje twojego cheata za 20zł na miesiac nie wiem czy na to pozwalasz ale chcialem cię tylko poinformować.

I am sure daniel doesnt approve of this ill tag him to make sure he sees this thanks for reporting @danielkrupinski 

POLISH (if you dont speak english):
Jestem pewien, że Daniel nie pochwala tego złego tagu, aby upewnić się, że zobaczy to dzięki za zgłoszenie

**Comment by Bywnb** [comment]
I don't know polish very well. What you're saying is that Daniel's project was secretly sold on advboost.eu？

**Comment by wieisstimpee** [comment]
> I don't know polish very well. What you're saying is that Daniel's project was secretly sold on advboost.eu？

I put it in google translate and thats what it came down to, he asked if daniel approved of this and i dont think he does (why would he sell something that is open source and free?)

**Comment by effex1337** [comment]
Daniel approves as the licence allows selling it

**Comment by wieisstimpee** [comment]
> Daniel approves as the licence allows selling it

oh well :V still kinda scummy though

**Comment by Bywnb** [comment]
> Daniel approves as the licence allows selling it

Is that true?In my opinion, Daniel really deserves to be rewarded for his open source project
