### ISSUE TITLE
[Question] Bhop SMAC proof

### ISSUE THREAD

**Issue by tirziz** [danielkrupinski/Osiris#403]
I just got auto trigger ban from SMAC secure servers , would be best if we can send some ramdom +Jump after a hop, it might bypass that detection

**Comment by wieisstimpee** [comment]
hitchance bhop would be nice :D

**Comment by tirziz** [comment]
Already add hit chance, still banned, hit chance only help you look more legit in OW but some plugin still can detect cheat

**Comment by wieisstimpee** [comment]
> Already add hit chance, still banned, hit chance only help you look more legit in OW not when playing on Community servers,

hmh still would be nice to be able to bhop with a hitchance to not get OW'd ill do a quick research on how people bypass SMAC bhop

**Comment by tirziz** [comment]
> hmh still would be nice to be able to bhop with a hitchance to not get OW'd ill do a quick research on how people bypass SMAC bhop
Check the pull request by @desinger1337 , the hit chance work fine for me
https://github.com/danielkrupinski/Osiris/pull/389

**Comment by wieisstimpee** [comment]
> > hmh still would be nice to be able to bhop with a hitchance to not get OW'd ill do a quick research on how people bypass SMAC bhop
> 
> Check this #389 pull request by @desinger1337 , the hit chance work fine for me.

what are your settings on the hitchance? might be too high

**Comment by tirziz** [comment]
> what are your settings on the hitchance? might be too high
>
No, this is how SMAC ban trigger, you can take a look
 ``
/* BunnyHop */
static Float:fCheckTime[MAXPLAYERS+1];
 
// Player didn't jump immediately after the last jump.
if (!(buttons & IN_JUMP) && (GetEntityFlags(client) & FL_ONGROUND) && (fCheckTime[client] > 0.0))
	fCheckTime[client] = 0.0;
	
// Ignore this jump if the player is in a tight space or stuck in the ground.
if ((buttons & IN_JUMP) && !(iPrevButtons[client] & IN_JUMP))
{
	// Player is on the ground and about to trigger a jump.
	if (GetEntityFlags(client) & FL_ONGROUND)
	{
		new Float:fGameTime = GetGameTime();
			
		// Player jumped on the exact frame that allowed it.
		if ((fCheckTime[client] > 0.0) && (fGameTime > fCheckTime[client]))
			AutoTrigger_Detected(client, METHOD_BUNNYHOP);
		else
			fCheckTime[client] = (fGameTime + MIN_JUMP_TIME);
	}
	else
		fCheckTime[client] = 0.0;
}
``

**Comment by Kron1Q** [comment]
u got SMAC ban because this bhop dont have smac proof (oh how simple lol). Took me less than 10s to find this:
https://www.unknowncheats.me/forum/1691836-post2.html
(SMAC proof, yes.)

**Comment by tirziz** [comment]
> u got SMAC ban because this bhop dont have smac proof (oh how simple lol). Took me less than 10s to find this:
> https://www.unknowncheats.me/forum/1691836-post2.html
> (SMAC proof, yes.)
I dont get it, what is bLastJumped  and bShouldFake , can you definite it ?

**Comment by tirziz** [comment]
Just paste a new bhop from unknowncheat and no more smac, close issus here

**Comment by pparadoxx** [comment]
https://github.com/danielkrupinski/Osiris/pull/450

I don't know why he closed it, but it still works, enjoy.
