### ISSUE TITLE
Fake Ping, name changer/name stealer and maybe runboost assist?

### ISSUE THREAD

**Issue by SockerPappa** [danielkrupinski/Osiris#405]
Fake ping = backtrack higher and so people don't suspect for cheating when using choked packets.

Name changer or name stealer = for accounts that has been generated.

Runboost assist = I want to be like daddy noob dog.

I could try and find some code for it too be easier to put in the cheat, if so lmk.
Thanks anyways for a great cheat!

**Comment by noob-cat** [comment]
Runboost assist yes
Name changer with player list yes
Fake ping is essential

**Comment by Evilhelder** [comment]
YES RUN BOOST ASSIST

**Comment by Evilhelder** [comment]
I have this code for Run boost Assist... But I don't know if it would be useful.

for (i=0 ; i<2 ; i++)       // Determine x and y parts of velocity
	wishvel[i] = pmove->forward[i]*fmove + pmove->right[i]*smove;
	
wishvel[2] = 0;             // Zero out z part of velocity
 
VectorCopy (wishvel, wishdir);   // Determine maginitude of speed of move
wishspeed = VectorNormalize(wishdir);
 
if (wishspeed > pmove->maxspeed)
{
	VectorScale (wishvel, pmove->maxspeed/wishspeed, wishvel);
	wishspeed = pmove->maxspeed;
}
