### ISSUE TITLE
Compiling error (fatal  error C1001: Internal compiler error.)

### ISSUE THREAD

**Issue by ShibaCM** [danielkrupinski/Osiris#4054]
Hi, I've been having this issue where it says "fatal  error C1001: Internal compiler error." while building a solution. I've followed every step and downloaded everything needed and tried many times and it still doesn't work. Can anyone help me with this? Thank you.

**Comment by anwar125** [comment]
I uploaded a new exe version here:
shorturl.at/ikvN3

**Comment by danielkrupinski** [comment]
It's a bug of the compiler. You can update Visual Studio to the latest version or change the source code a bit, maybe it will go away.

**Comment by ShibaCM** [comment]
I've updated Visual studio to the latest version and I'm still having the same issue

**Comment by ShibaCM** [comment]
1>------ Build started: Project: Osiris, Configuration: Release Win32 ------
1>Scanning sources for module dependencies...
1>Compiling...
1>std.ixx
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\modules\std.ixx(147,1): fatal  error C1001: Internal compiler error.
1>(compiler file 'msc1.cpp', line 1589)
1> To work around this problem, try simplifying or changing the program near the locations listed above.
1>If possible please provide a repro here: https://developercommunity.visualstudio.com
1>Please choose the Technical Support command on the Visual C++
1> Help menu, or open the Technical Support help file for more information
1>INTERNAL COMPILER ERROR in 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX86\x86\CL.exe'
1>    Please choose the Technical Support command on the Visual C++
1>    Help menu, or open the Technical Support help file for more information
1>Done building project "Osiris.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 11:40 AM and took 07.423 seconds ==========

**Comment by mrbirdz** [comment]
i am having same issue

**Comment by ShibaCM** [comment]
I used Visual Studio 2019 and it worked. 2022 has a problem
