### ISSUE TITLE
[Question] Somebody know how to use backtrack?

### ISSUE THREAD

**Issue by 3L337-n2** [danielkrupinski/Osiris#406]
I enable it and backtrack not works for me in offline/online. So is backtrack needs some special condition to use it?

**Comment by ItsKriminal** [comment]
Backtrack shouldn't need a special condition I have set mine to 120ms and it's working perfectly without anything other enabled.

**Comment by 3L337-n2** [comment]
But why i enable it but doesn't work ?Is it need to enable in game not menu?

**Comment by ItsKriminal** [comment]
U sure u know what backtrack is supposed to do?

**Comment by Leeon123** [comment]
not sure , can u tell me?

**Comment by 3L337-n2** [comment]
Not sure, i just see that on youtube before.

**Comment by 3L337-n2** [comment]
And....i just got vac banned!?
https://steamcommunity.com/profiles/76561198982458410/

**Comment by Bywnb** [comment]
> And....i just got vac banned!?
> https://steamcommunity.com/profiles/76561198982458410/

Stupid people better not use this program!

**Comment by Bywnb** [comment]
> And....i just got vac banned!?
> https://steamcommunity.com/profiles/76561198982458410/

Stupid people better not use this program!

**Comment by GaghiZor** [comment]
> And....i just got vac banned!?
> https://steamcommunity.com/profiles/76561198982458410/

You got a VAC ban because of your injector.

**Comment by 3L337-n2** [comment]
Hmm, i use another account still got banned but banned by Game developer.

**Comment by Mufinekkk** [comment]
Use another injector...

**Comment by ItsKriminal** [comment]
"banned by Game developer" Yea no

**Comment by gulu-gulu** [comment]
> "banned by Game developer" Yea no

banned by game developer is an [overwatch](https://support.steampowered.com/kb_article.php?ref=7562-IPJN-1009&l=english) ban!

kind regards 😃 👍

**Comment by ItsKriminal** [comment]
> > "banned by Game developer" Yea no
> 
> banned by game developer is an [overwatch](https://support.steampowered.com/kb_article.php?ref=7562-IPJN-1009&l=english) ban!
> 
> kind regards 😃 👍

From what I remember it just said "You have been banned by Overwatch"

**Comment by gulu-gulu** [comment]
> > > "banned by Game developer" Yea no
> > 
> > 
> > banned by game developer is an [overwatch](https://support.steampowered.com/kb_article.php?ref=7562-IPJN-1009&l=english) ban!
> > kind regards 😃 👍
> 
> From what I remember it just said "You have been banned by Overwatch"

Yes this is being displayed in-game however the Steam notification says "game developer" which is for every game ban you receive in any game that is in Steam.

kind regards 😃 👍

**Comment by noob-cat** [comment]
> I enable it and backtrack not works for me in offline/online. So is backtrack needs some special condition to use it?

enable backtrack, set ms, go to chams. enable backtrack chams - glhf.

**Comment by 3L337-n2** [comment]
> > I enable it and backtrack not works for me in offline/online. So is backtrack needs some special condition to use it?
> 
> enable backtrack, set ms, go to chams. enable backtrack chams - glhf.
Thx, alought i have already found it.
