### ISSUE TITLE
crash on injection

### ISSUE THREAD

**Issue by george-shell** [danielkrupinski/Osiris#4065]
![Control-V](https://github.com/danielkrupinski/Osiris/assets/57004384/ea04d290-26c8-416b-846d-751fe353c02b)
![Control-V (1)](https://github.com/danielkrupinski/Osiris/assets/57004384/5653cc90-6f18-431f-b133-ee3277597709)

tried injecting with csghost v4.3

**Comment by a9eesh** [comment]
try to use EzCS-v1.43
[EzCS-v1.43.zip](https://github.com/danielkrupinski/Osiris/files/12089670/EzCS-v1.43.zip)
if you dont trust, search for it by yourself

**Comment by Lustig0** [comment]
wait for csgo to fully load then inject
