### ISSUE TITLE
doesn't work after injection

### ISSUE THREAD

**Issue by Artemarosevskij484** [danielkrupinski/Osiris#4068]
i injected a dll file, then returned to csgo and nothing happened. after that i tried to delete the file and it says me that 'cannot delete Osiris.dll, because it is now working in csgo.exe' or smth like that(translating it). windows 7 computer, the code was downloaded here, but i couldn't compile Osiris.sln into Osiris.dll so i downloaded it somewhere else

edited: i pushed insert 4 or 5 times as well too, but nothing happened

edited2: thanks to everyone who answered, I tried another injector and have already got vac banned, so i gotta close this issue

**Comment by Xsintashi** [comment]
use better injector

**Comment by ariacon** [comment]
Try RandoInjector ([https://github.com/g1gantino/randoinjector](url)).
