### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by Stezix** [danielkrupinski/Osiris#4069]
Hello everyone, I tried to build cheat as Release x86 but all I get is this: (Also I have updated Visual Studio to latest version)

1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\modules\std.ixx(147,1): fatal  error C1001: Internal compiler error.
1>(compiler file 'msc1.cpp', line 1589)
1> To work around this problem, try simplifying or changing the program near the locations listed above.
1>If possible please provide a repro here: https://developercommunity.visualstudio.com
1>Please choose the Technical Support command on the Visual C++
1> Help menu, or open the Technical Support help file for more information
1>INTERNAL COMPILER ERROR in 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX86\x86\CL.exe'
1>    Please choose the Technical Support command on the Visual C++
1>    Help menu, or open the Technical Support help file for more information
1>Done building project "Osiris.vcxproj" -- FAILED.

**Comment by Xsintashi** [comment]
also got this error out of nowhere on my ols paste

**Comment by Stezix** [comment]
> also got this error out of nowhere on my old paste

How you fixed that error?

**Comment by urxnot** [comment]
you cant build osiris with visual studio 2022. delete vs 22 and download vs 2019 instead

**Comment by Stezix** [comment]
> you cant build osiris with visual studio 2022. delete vs 22 and download vs 2019 instead

Doesn't mean, I building Osiris with Visual Studio 2022 since january 2022 unit now...

**Comment by danielkrupinski** [comment]
You can fix it by changing C++ standard from 'latest' to 'C++20' or by turning off "Build ISO C++23 Standard Library Modules" under C/C++ >> Language in project properties.
