### ISSUE TITLE
Aimbot + rcs

### ISSUE THREAD

**Issue by maqabra** [danielkrupinski/Osiris#407]
Hi. I just tried that source and i saw a little bit problem with aimbot. I must taping when i use aimbot because when i want to spray aimbot isn't good. Crosshair is going above head. I tried edit source but without changes ingame. I have no idea.

**Comment by wieisstimpee** [comment]
> Hi. I just tried that source and i saw a little bit problem with aimbot. I must taping when i use aimbot because when i want to spray aimbot isn't good. Crosshair is going above head. I tried edit source but without changes ingame. I have no idea.

it doesnt do all the work for you, you need to hold down your mouse a bit too when spraying. Its a legit cheat its supposed to not do everything for you.

**Comment by danielkrupinski** [comment]
Set recoil control in aimbot settings.
