### ISSUE TITLE
CS:GO Lags with Osiris.

### ISSUE THREAD

**Issue by SpryerS** [danielkrupinski/Osiris#4070]
My CS:GO is lagging only while I am using Osiris and I am not sure as to why this happens.

**Comment by Xsintashi** [comment]
we also

**Comment by SpryerS** [comment]
I am guessing that you are talking about this "cmake --build build -j $(nproc --all)" but I should point out that I am on Linux.

> we also Bet u built debug version instead of release

**Comment by Xsintashi** [comment]
> I am guessing that you are talking about this "cmake --build build -j $(nproc --all)" but I should point out that I am on Linux.
> 
> > we also Bet u built debug version instead of release

Im dont use linux everyday, so can't really help you
