### ISSUE TITLE
Question about csgo Network (not related to cheat)

### ISSUE THREAD

**Issue by dummys** [danielkrupinski/Osiris#4071]
dear @danielkrupinski,
I'm contacting you because I think you can answer one of my problem on csgo.
As you are writting one of the most prolific and used cheat for this game you should understand greatly how their client/server infrastructure works. My problem is the following:
At home I play on my game PC which is a high end one and I have a good internet connection 10Bgbit. All my infrastructure are behind a enterprise grade firewall and I dont have fixed internet IP address unfortunately. When I play in Lan, I can feel the bot are responding and my bullet hit very well my target. When I play faceit/MM, it is another story. I feel like my bullet are not hiting, I lose q lot of duel despite my skill is the same. I checked net_graph, no choke/loss, but after checking my firewall drop log, I see a lot of UDP packet 27000-27036 range dropped from Valve/facit IP. My question is, what are those packet for ? As my computer id sending each ticks user command to the server and I guess their server is responding using those udp ports. but as the UDP protocol is not stateful, my firewall doesn't to whom it belong and as no port is open on incoming, he dropped it. On normal router for home, how it works ? With Upnp protocol ? 
Thanks for you help. and if you wanna talk we can do it on discord/twitter/whatever.

**Comment by ariacon** [comment]
@dummys did you ever tried to factory reset your system?
