### ISSUE TITLE
How to load after building on linux

### ISSUE THREAD

**Issue by milchevdimitar** [danielkrupinski/Osiris#4076]

**Comment by Cang-Yue** [comment]
sudo gdb -batch-silent -p $(pidof csgo_linux64) -ex "call (void*)__libc_dlopen_mode(\"$PWD/libOsiris.so\", 2)"

**Comment by UDIA-GOD** [comment]
https://github.com/kubo/injector works as well :D

**Comment by UDIA-GOD** [comment]
better question tho is how did u manage to compile it lmfao
