### ISSUE TITLE
[Suggestion] player list? ;)

### ISSUE THREAD

**Issue by 29380482390** [danielkrupinski/Osiris#408]
as in title - add playerlist ( so you can report check their steamid etc last usernames, you kno' just simple things, im not saying like baim check for them etc but just simple things that could be fun to use )

**Comment by noob-cat** [comment]
+++++

**Comment by Bywnb** [comment]
+++++

**Comment by l0ccy** [comment]
+++++++

**Comment by Kron1Q** [comment]
https://github.com/AimTuxOfficial/AimTux/blob/master/src/ATGUI/Windows/playerlist.cpp

**Comment by yEsPaP** [comment]
> https://github.com/AimTuxOfficial/AimTux/blob/master/src/ATGUI/Windows/playerlist.cpp

this is for linux

**Comment by 0xE232FE** [comment]
And yes its Linux but Data are same on Windows and Linux because of **Source Engine**!
