### ISSUE TITLE
fixing older versions of osiris

### ISSUE THREAD

**Issue by Tempfyyyy** [danielkrupinski/Osiris#4082]
idk how and where to update the netvars and offsets pls help!

**Comment by Tempfyyyy** [comment]
of older version

**Comment by Xsintashi** [comment]
memory.cpp/h & whole SDK folder

**Comment by Tempfyyyy** [comment]
how to update them ?

**Comment by Xsintashi** [comment]
copy paste latest patterns, classes, structs to older osiris
