### ISSUE TITLE
Aimbot on key doesnt work

### ISSUE THREAD

**Issue by wieisstimpee** [danielkrupinski/Osiris#410]
I toggled on key but it just didnt work. I dont have the knowledge to find out myself how to fix it so I am hoping someone here does have the required knowledge! :D

**Comment by danielkrupinski** [comment]
Bind key and select appropriate mode (hold/toggle).

**Comment by wieisstimpee** [comment]
Do I need to reselect the mode I wanna use? Like I had it on hold before using the bind do I need to switch to toggle back to hold for it to work? (Can’t test it right now)

**Comment by Bywnb** [comment]
> Bind key and select appropriate mode (hold/toggle).

Hello,maybe move appropriate mode (hold/toggle) next to enable checkbox will make ui better

**Comment by wieisstimpee** [comment]
> Bind key and select appropriate mode (hold/toggle).

ok so it only works when aimlock is enabled.. is it supposed to be like this ?

**Comment by gulu-gulu** [comment]
> > Bind key and select appropriate mode (hold/toggle).
> 
> ok so it only works when aimlock is enabled.. is it supposed to be like this ?

Yes, you need to have the checkbox enabled in order to use the feature. Just setup your bind and you are good to go.

kind regards 😃 👍

**Comment by mindofenzo** [comment]
It works but you must have Max angle delta >0
