### ISSUE TITLE
Failed to write DLL path (0)

### ISSUE THREAD

**Issue by Gordoxzxx** [danielkrupinski/Osiris#4102]
Im currently using cs ghost as my injector and when i try to inject osiris dll this error pops up.

**Comment by Lustig0** [comment]
send me a ss of your error

**Comment by Lustig0** [comment]
https://www.reddit.com/r/Csgohacks/comments/thgq5w/csghost_dll_error/

**Comment by Gordoxzxx** [comment]
> https://www.reddit.com/r/Csgohacks/comments/thgq5w/csghost_dll_error/

like that helped 0 just ramdom ppl complaining about the same

**Comment by Lustig0** [comment]
only thing i couf find ask daniel
