### ISSUE TITLE
Osiris Is VAC Detected

### ISSUE THREAD

**Issue by Roasterbation** [danielkrupinski/Osiris#4104]
For the past few days, i have played in numerous 2 year old accounts and 1 day old accounts.After few hours of injecting the cheat the account gets RED TRUST.

I have tested the cheat with enabling every features in every injection(one cheat at a time,like: aimbot only,chams only,Engine Crosshair only etc).Also i tried adding junk code and MD5 hash changer and file row changer for bypassing the detection.I also tried playing with oldest versions after 'Anti-aim' was removed.But nothing worked.

I guess daniel is aware that the recent VAC WAVE Detected so many Popular cheats with advanced Cheat methods.VanityCheats,gamesense etc are the example.

As Osiris is a PUBLIC Cheat i dont expect much cause daniel working so hard already to make it faster, optimized and undetected.

My request is to change the files pattern so that it doesnt look like the old versions.

Also if possible add some advanced hooking method even if they are slow.Update bytepattern and memory allocator frequently so that it remains undetected.

I am sorry for asking you about that much improvement for a free cheat but please you are a god in our eyes of FREE CHEAT USERS.Osiris is the best cheat by far for every aspect of CSGO legit cheating.Been using it from 2020.Lets make the last few moments of CSGO Cheating memorable.You dont have to make cheats for CS2.Take a break.Good luck.Thanks for reading.

**Comment by z3ro72** [comment]
I have 500 hours with osiris and green trust factor

**Comment by Roasterbation** [comment]
> 

I am being honest as you.I played with highest trust factor for like 14 days every ban but now its just banning me everyday and can you list the features you use?

**Comment by Lustig0** [comment]
yeah but it also depends on how you cheat if you full rage yeah you will get detected faster by the new ai detector if you reallly dont use much you will not by the way today i played for over 4h green trust i can share my config after im done tweaking it to be more legit

**Comment by z3ro72** [comment]
> > 
> 
> I am being honest as you.I played with highest trust factor for like 14 days every ban but now its just banning me everyday and can you list the features you use?

Very Legit Aimbot, Chams, ESP, Triggerbot, Inv Changer, Backtrack, Visible Glow and so many things from visuals and misc. Almost everything except radar hack. I thought i am gonna get banned and i am already low trust factor but i used [osiris and extras](https://github.com/notgoodusename/OsirisAndExtra) and i got red trust factor after 1 match in one of my accs that i was using normal osiris for like 250 hours without being detected. I don't know how everyone gets red trust by normal osiris, never happened to me

**Comment by Lustig0** [comment]
> > > 
> > 
> > 
> > I am being honest as you.I played with highest trust factor for like 14 days every ban but now its just banning me everyday and can you list the features you use?
> 
> Very Legit Aimbot, Chams, ESP, Triggerbot, Inv Changer, Backtrack, Visible Glow and so many things from visuals and misc. Almost everything except radar hack. I thought i am gonna get banned and i am already low trust factor but i used [osiris and extras](https://github.com/notgoodusename/OsirisAndExtra) and i got red trust factor after 1 match in one of my accs that i was using normal osiris for like 250 hours without being detected. I don't know how everyone gets red trust by normal osiris, never happened to me

same here 3weeks everyday not banned green trust factor

**Comment by Roasterbation** [comment]
> > > 
> > 
> > 
> > I am being honest as you.I played with highest trust factor for like 14 days every ban but now its just banning me everyday and can you list the features you use?
> 
> Very Legit Aimbot, Chams, ESP, Triggerbot, Inv Changer, Backtrack, Visible Glow and so many things from visuals and misc. Almost everything except radar hack. I thought i am gonna get banned and i am already low trust factor but i used [osiris and extras](https://github.com/notgoodusename/OsirisAndExtra) and i got red trust factor after 1 match in one of my accs that i was using normal osiris for like 250 hours without being detected. I don't know how everyone gets red trust by normal osiris, never happened to me

so

> > > 
> > 
> > 
> > I am being honest as you.I played with highest trust factor for like 14 days every ban but now its just banning me everyday and can you list the features you use?
> 
> Very Legit Aimbot, Chams, ESP, Triggerbot, Inv Changer, Backtrack, Visible Glow and so many things from visuals and misc. Almost everything except radar hack. I thought i am gonna get banned and i am already low trust factor but i used [osiris and extras](https://github.com/notgoodusename/OsirisAndExtra) and i got red trust factor after 1 match in one of my accs that i was using normal osiris for like 250 hours without being detected. I don't know how everyone gets red trust by normal osiris, never happened to me

So basically you got detected after 500 hours?lol

**Comment by Roasterbation** [comment]
> yeah but it also depends on how you cheat if you full rage yeah you will get detected faster by the new ai detector if you reallly dont use much you will not by the way today i played for over 4h green trust i can share my config after im done tweaking it to be more legit

i am scared to turn on chams wdym?My playstyle is more like like a camper lol

**Comment by Lustig0** [comment]
> > > > 
> > > 
> > > 
> > > I am being honest as you.I played with highest trust factor for like 14 days every ban but now its just banning me everyday and can you list the features you use?
> > 
> > 
> > Very Legit Aimbot, Chams, ESP, Triggerbot, Inv Changer, Backtrack, Visible Glow and so many things from visuals and misc. Almost everything except radar hack. I thought i am gonna get banned and i am already low trust factor but i used [osiris and extras](https://github.com/notgoodusename/OsirisAndExtra) and i got red trust factor after 1 match in one of my accs that i was using normal osiris for like 250 hours without being detected. I don't know how everyone gets red trust by normal osiris, never happened to me
> 
> so
> 
> > > > 
> > > 
> > > 
> > > I am being honest as you.I played with highest trust factor for like 14 days every ban but now its just banning me everyday and can you list the features you use?
> > 
> > 
> > Very Legit Aimbot, Chams, ESP, Triggerbot, Inv Changer, Backtrack, Visible Glow and so many things from visuals and misc. Almost everything except radar hack. I thought i am gonna get banned and i am already low trust factor but i used [osiris and extras](https://github.com/notgoodusename/OsirisAndExtra) and i got red trust factor after 1 match in one of my accs that i was using normal osiris for like 250 hours without being detected. I don't know how everyone gets red trust by normal osiris, never happened to me
> 
> So basically you got detected after 500 hours?lol

nah most people tend to get detected cuz they think they can be more and more blatant but look legit basiccly its ego that gets them detected

**Comment by Lustig0** [comment]
> > yeah but it also depends on how you cheat if you full rage yeah you will get detected faster by the new ai detector if you reallly dont use much you will not by the way today i played for over 4h green trust i can share my config after im done tweaking it to be more legit
> 
> i am scared to turn on chams wdym?My playstyle is more like like a camper lol

bro cmon camper if you camping you really only need esp and some visuals

**Comment by Roasterbation** [comment]
my aimbot is 2.0 bruh

**Comment by Roasterbation** [comment]
not even aimlock or through smoke or flash turned on

**Comment by Lustig0** [comment]
> not even aimlock or through smoke or flash turned on

all i gotta say is go ligh on the fov and increase smoothness cuz were in a ban wawe

**Comment by Roasterbation** [comment]
> > > yeah but it also depends on how you cheat if you full rage yeah you will get detected faster by the new ai detector if you reallly dont use much you will not by the way today i played for over 4h green trust i can share my config after im done tweaking it to be more legit
> > 
> > 
> > i am scared to turn on chams wdym?My playstyle is more like like a camper lol
> 
> bro cmon camper if you camping you really only need esp and some visuals

i dont even shoot through smoke or blind flash lol just pre-aim where enemy is not coming

**Comment by Roasterbation** [comment]
> > not even aimlock or through smoke or flash turned on
> 
> all i gotta say is go ligh on the fov and increase smoothness cuz were in a ban wawe

tell me whats smoothness gonna do if i am not using 'AIMLOCK'

**Comment by Roasterbation** [comment]
bruh

**Comment by Roasterbation** [comment]
@Lustig0 gimme the config fr soon lemme see its free 😂

**Comment by Lustig0** [comment]
> @Lustig0 gimme the config fr soon lemme see its free 😂

i dont try and sell it i make it how i like it to be

**Comment by Roasterbation** [comment]
> > @Lustig0 gimme the config fr soon lemme see its free 😂
> 
> i dont try and sell it i make it how i like it to you

> > @Lustig0 gimme the config fr soon lemme see its free 😂
> 
> i dont try and sell it i make it how i like it to be

so i have to buy?

**Comment by Roasterbation** [comment]
Lol

**Comment by Lustig0** [comment]
> > > @Lustig0 gimme the config fr soon lemme see its free 😂
> > 
> > 
> > i dont try and sell it i make it how i like it to you
> 
> > > @Lustig0 gimme the config fr soon lemme see its free 😂
> > 
> > 
> > i dont try and sell it i make it how i like it to be
> 
> so i have to buy?

bro read the reply

**Comment by Roasterbation** [comment]
> > > > @Lustig0 gimme the config fr soon lemme see its free 😂
> > > 
> > > 
> > > i dont try and sell it i make it how i like it to you
> > 
> > 
> > > > @Lustig0 gimme the config fr soon lemme see its free 😂
> > > 
> > > 
> > > i dont try and sell it i make it how i like it to be
> > 
> > 
> > so i have to buy?
> 
> bro read the reply

wdym?

**Comment by z3ro72** [comment]
> > > > 
> > > 
> > > 
> > > I am being honest as you.I played with highest trust factor for like 14 days every ban but now its just banning me everyday and can you list the features you use?
> > 
> > 
> > Very Legit Aimbot, Chams, ESP, Triggerbot, Inv Changer, Backtrack, Visible Glow and so many things from visuals and misc. Almost everything except radar hack. I thought i am gonna get banned and i am already low trust factor but i used [osiris and extras](https://github.com/notgoodusename/OsirisAndExtra) and i got red trust factor after 1 match in one of my accs that i was using normal osiris for like 250 hours without being detected. I don't know how everyone gets red trust by normal osiris, never happened to me
> 
> So basically you got detected after 500 hours?lol

no i didn't. I'm literally using osiris in my main and it's still green factor, no ban. I sometimes get banned because of reports and i play osiris on other acc, as i said i used another version of osiris with more features. That gave me the red trust factor to other account. My main is still safe i'm using normal version of osiris

**Comment by Roasterbation** [comment]
So uh that was 'selectfire'?

**Comment by z3ro72** [comment]
I already linked it in my reply "[Osiris and Extras](https://github.com/notgoodusename/OsirisAndExtra)" i think it has some features that is detected

**Comment by Lustig0** [comment]
> I already linked it in my reply "[Osiris and Extras](https://github.com/notgoodusename/OsirisAndExtra)" i think it has some features that is detected

never use those osiris and extra features cause there always outaded and half the extar features have been detected since god knows when

**Comment by z3ro72** [comment]
> 

Yeah it's outdated when i was checking codes all of them was old osiris codes. It said 10 March last release so i thought they update it from last osiris release everytime but they just update their 2022 version osiris and add new features

**Comment by Roasterbation** [comment]
he just added every feature when it was removed lol

**Comment by fanat1cc** [comment]
Your best bet is learning how to remove features properly and removing all features you don't use and use a vsc bypass I suggest couinjector I used it for about 4months no ban, always check Max aim delta on all of your configs, make sure it's set below 13 default it 255 and that's how the ai detects the aimbot.

**Comment by chiteroman** [comment]
You must use VAC bypass, Osiris always have been a detected cheat.

**Comment by Roasterbation** [comment]
nobody gives a F about CSGO anymore lol
