### ISSUE TITLE
How to simplify features?

### ISSUE THREAD

**Issue by chuncai111** [danielkrupinski/Osiris#4106]
The current feature set is too extensive. I only want to keep the "Glow" feature and remove everything else. I tried deleting the relevant cpp and h files in the code, but it didn't work. The code is too complex. Can someone give me some guidance?

**Comment by Xsintashi** [comment]
why?

**Comment by fanat1cc** [comment]
Just use couglow. Exactly what your looking for

**Comment by Xsintashi** [comment]
funny tho glow is detected and u still wanna use it

**Comment by fanat1cc** [comment]
> funny tho glow is detected and u still wanna use it

Only detected if you don't use a vac bypass, cou injector has that. And I have used cou glow and all of bymynix's programs and got banned using none of them so far. So yea I suggest it.

**Comment by ImsilverDev** [comment]
tbh, you're better off coding your own cheat rather than stripping it off only for glow, and glow is risky,
i'd go with an external overlay made in python, very easy to make + debug and it's good for beginners
