### ISSUE TITLE
Watermark (not an issue)

### ISSUE THREAD

**Issue by TheJAXi** [danielkrupinski/Osiris#4110]
Was wondering... How do you get SteamID on the watermark? A way that would work when not in game.

**Comment by flashintv** [comment]
you should be able to just get the SteamUser using api and then just use its GetSteamID function
https://github.com/perilouswithadollarsign/cstrike15_src/blob/master/public/steam/isteamuser.h#L38

**Comment by TheJAXi** [comment]
Thank You ❤️

JAXi 3124990-9
________________________________
