### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by kirill-21** [danielkrupinski/Osiris#4112]
Hello. Both of these configs are working, however, if you load the second one (RedLegit) after any another config - game will crash. If you load this config (RedLegit) the first one, game won't crash. .txt extensions were added so that files could be uploaded to GitHub. Same situation is with "legit-osiris-by-w1ndyxz" config - if it's loaded after you've applied settings from any another cfg - game will crash. 

Just for testing purposes:
[sky.txt](https://github.com/danielkrupinski/Osiris/files/12225739/sky.txt)

Crashing if loaded after any another cfg but working fine if loaded as the first config:
[RedLegit.txt](https://github.com/danielkrupinski/Osiris/files/12225740/RedLegit.txt)
[legit-osiris-by-w1ndyxz.txt](https://github.com/danielkrupinski/Osiris/files/12225764/legit-osiris-by-w1ndyxz.txt)

**Comment by Xsintashi** [comment]
No shadows is disabled on crashing configs. Its csgo problem itself. No shadows works by setting cl_csm_enabled Convar to 1. Reverting that Convar to 0 results crash in most cases (even without cheats). The best what u can do is not using that option or let csgo load shadows again

**Comment by Xsintashi** [comment]
it can but then csgo have to load all maps shadows again. that's why it may crash
