### ISSUE TITLE
[Question] How to build Osiris with Visual Studio

### ISSUE THREAD

**Issue by amircheg** [danielkrupinski/Osiris#4114]
I am trying to build Osiris. I did read the [Compiling from source ](https://github.com/danielkrupinski/Osiris#compiling-from-source)section of the readme and watched a [video tutorial on how to build Osiris](https://youtu.be/_p4UHxr57CU?si=EzMRpcFNgq_sOkyg), but i still have some questions:

Q1: Which workloads should i select when installing Visual Studio? in the video tutorial it says [Desktop develolment with C++] and [Universal Windows Platform development]. Is that correct?

Q2: Do I need to change Character Set option in Osiris Property Pages? (Project -> Properties -> Advanced -> Character Set -> Use Multi-Byte Character Set)

I appreciate your help in guiding me on this topic.

**Comment by Lustig0** [comment]
yeah just follow the build steps provided by daniel and the characcter set thing dosent do anything its a prefrence

**Comment by amircheg** [comment]
> yeah just follow the build steps provided by daniel and the characcter set thing dosent do anything its a prefrence

Thank you! I always read the instructions carefully before posting any comment or issue. I also did search the issues for this but i didnt seem to find it. So i have to select those 2 workloads during VS installation? daniel didnt mention this in his instructions.

**Comment by amircheg** [comment]
Okay so i managed to successfully build Osiris. Here are the steps for you guys:

1. Download Visual Studio (I downloaded VS2019 (v16.11.7) [from this link](https://soft98.ir/software/programming/263-%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-%D9%88%DB%8C%DA%98%D9%88%D8%A7%D9%84-%D8%A7%D8%B3%D8%AA%D9%88%D8%AF%DB%8C%D9%80%D9%88-ea.html))
2. After downloading all 19 parts (*.part01.rar - *.part19.rar), select all and extract and you should get vs_2019.iso.
3. Mount vs_2019.iso and run vs_setup.exe (Disconnect your insternet connection before installation).
4. Proceed with the defaults. In workloads section of the installer you need to select [Desktop develolment with C++] and [Universal Windows Platform development] and install.
5. Activate Visual Studio using the serial number in Serial.txt file, then close Visual Studio.
6. Download Osiris source code (Download ZIP) extract it and open Osiris.sln using Visual Studio.
7. Change build configuration to Release | x86. Then select Build -> Build Solution.

Thats it. Build should be successful and you should get Osiris.dll.

If you would like to download the latest Osiris.dll builds, you can check my [telegram channel](https://t.me/Osiris_dll).
