### ISSUE TITLE
Need small info

### ISSUE THREAD

**Issue by DAZstar** [danielkrupinski/Osiris#4127]
[[nodiscard]] bool generateStatTrak() const
        {
            return randomEngine(std::uniform_int_distribution<>{ 0, 9 }) == 0;
        }

Do I have to edit this if I need a stattrak item everytime when I add weapons?

**Comment by danielkrupinski** [comment]
No, this is used for items opened from weapon cases. To enable statrak when adding items you can set `skin.statTrak` in [DefaultGenerator::createSkin()](https://github.com/danielkrupinski/Osiris/blob/119f34386bb44e7cea0e7fd469201ae33354b8d5/Source/InventoryChanger/ItemGenerator/DefaultGenerator.h#L46).

**Comment by DAZstar** [comment]
So it will look like this? sorry I am noob, ty for your response tho

[[nodiscard]] inventory::Skin skin.statTrak(const game_items::Item& item) const
