### ISSUE TITLE
Error when building in Microsoft Visual Studio

### ISSUE THREAD

**Issue by dansfilms** [danielkrupinski/Osiris#4129]
Whenever I try to build solution I get the error

Error		The BaseOutputPath/OutputPath property is not set for project 'Osiris.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Release'  Platform='Win32'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.	Osiris	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	832	

Is there a way to fix this?

**Comment by ImsilverDev** [comment]
your output path seems to be wrong, go change it
