### ISSUE TITLE
Desync chams

### ISSUE THREAD

**Issue by NexSqaud** [danielkrupinski/Osiris#414]
Can you add desync chams for understanding where real head and where fake head?

**Comment by Mufinekkk** [comment]
You can do it yourself, just search the code, and paste it into that source.

**Comment by l0ccy** [comment]
+1111

**Comment by cojo1989** [comment]
I want this also

**Comment by effex1337** [comment]
Heads up : the current desync doesnt even work.
Well thats at least from my desync chams.

**Comment by NexSqaud** [comment]
@effex1337 current desync works - look at LBY(lower body yaw)

**Comment by BlackmanWhite** [comment]
Does Osiris even have desync?

**Comment by ogosirisfan** [comment]
Desync indicator?

**Comment by NexSqaud** [comment]
Second player model which shows fake direction
