### ISSUE TITLE
RIP CS:GO and Osiris

### ISSUE THREAD

**Issue by toxic-grl** [danielkrupinski/Osiris#4140]
Due to the new update from CSGO to CS2, Osiris has become useless.

Hopefully @danielkrupinski  can update the code for this new version and we can all collaborate in some way for this update, looking for information or data, I guess

**Comment by Xsintashi** [comment]
Osiris never die

**Comment by fanat1cc** [comment]
Cs2 offsets have already been dumped so that's a start

**Comment by NGGYOK** [comment]
2023.9.28 +R.I.P. Osiris
today cs2 released

**Comment by NGGYOK** [comment]
> 2023.9.28 +R.I.P. Osiris today cs2 released
i found a new that can work on cs2
[https://github.com/WolverinDEV/Valthrun](url)

**Comment by Fr0go1** [comment]
Wont be long til osiris is back in the game id say, maybe a month or so. I feel valve should keep the csgo servers up because cs2 feels weird

**Comment by hamad12a** [comment]
In a way csgo is better in graphics

**Comment by Fr0go1** [comment]
> In a way, CSGO is better with respect to graphics

yeah cs2 feels sluggish in movement and graphics

**Comment by hamad12a** [comment]
So, no way to play CSGO again?

**Comment by 1565413601-wq** [comment]
> So, no way to play CSGO again?

ye

**Comment by Xsintashi** [comment]
you still can play csgo but only on community servers

**Comment by Xsintashi** [comment]
[How to still play csgo](https://youtu.be/YdUJvfic_gM?si=pvLEaqC6dJypRD0e&t=28)

**Comment by bboysteed** [comment]
> > 2023.9.28 +R.I.P. Osiris today cs2 released
> > i found a new that can work on cs2
> > [Valthrun](https://github.com/WolverinDEV/Valthrun)

play cs2just now ,and I have a very strange feel.does this project can take work? how to use kdmapper.exe

**Comment by NGGYOK** [comment]
> > > 2023.9.28 +R.I.P. Osiris today cs2 released
> > > i found a new that can work on cs2
> > > [Valthrun](https://github.com/WolverinDEV/Valthrun)
> 
> play cs2just now ,and I have a very strange feel.does this project can take work? how to use kdmapper.exe
put kdmapper and driver in a same folder
just drag valthrun-driver.sys to kdmapper.exe
or  use cmd as administrator command `kdmapper valthrun-driver.sys`

**Comment by NGGYOK** [comment]
> > > 2023.9.28 +R.I.P. Osiris today cs2 released
> > > i found a new that can work on cs2
> > > [Valthrun](https://github.com/WolverinDEV/Valthrun)
> 
> play cs2just now ,and I have a very strange feel.does this project can take work? how to use kdmapper.exe

put kdmapper and driver in a same folder
just drag valthrun-driver.sys to kdmapper.exe
or  use cmd as administrator command `kdmapper valthrun-driver.sys`

**Comment by 0xE232FE** [comment]
> > > > 2023.9.28 +R.I.P. Osiris today cs2 released
> > > > i found a new that can work on cs2
> > > > [Valthrun](https://github.com/WolverinDEV/Valthrun)
> > 
> > 
> > play cs2just now ,and I have a very strange feel.does this project can take work? how to use kdmapper.exe
> 
> put kdmapper and driver in a same folder just drag valthrun-driver.sys to kdmapper.exe or use cmd as administrator command `kdmapper valthrun-driver.sys`

Easiest way is to put WINDOWS into TESTSIGNING MODE. with BCDEDIT COMMAND.

**Comment by Fr0go1** [comment]
> > > > 2023.9.28 +R.I.P. Osiris today cs2 released
> > > > i found a new that can work on cs2
> > > > [Valthrun](https://github.com/WolverinDEV/Valthrun)
> > 
> > 
> > play cs2just now ,and I have a very strange feel.does this project can take work? how to use kdmapper.exe
> 
> put kdmapper and driver in a same folder just drag valthrun-driver.sys to kdmapper.exe or use cmd as administrator command `kdmapper valthrun-driver.sys`

if i do that i get a error when i open controller.exe

**Comment by Fr0go1** [comment]
![image](https://github.com/danielkrupinski/Osiris/assets/112802612/0c88cd33-4cf0-4be7-ae8b-49969cca9bcd)

**Comment by TauCSGO** [comment]
> > > 2023.9.28 +R.I.P. Osiris today cs2 released
> > > i found a new that can work on cs2
> > > [Valthrun](https://github.com/WolverinDEV/Valthrun)
> 
> play cs2just now ,and I have a very strange feel.does this project can take work? how to use kdmapper.exe

While we wait for the great Osiris... try this... is a good project
https://github.com/IMXNOOBX/cs2-external-esp

**Comment by Nep-Timeline** [comment]
https://github.com/danielkrupinski/Osiris/tree/cs2
