### ISSUE TITLE
Osiris(CS2 Version) is not injecting to Cs2 by any injector

### ISSUE THREAD

**Issue by Roasterbation** [danielkrupinski/Osiris#4143]

**Comment by IoDevl** [comment]
Yeah, that's literally because Osiris is made for CS:GO and not CS2 yet.

**Comment by Xsintashi** [comment]
> Yeah, that's literally because Osiris is made for CS:GO and not CS2 yet.

There is cs2 brach of osiris but there is literally no hooks and funcs to work with cs2.
--------------------------------------------------------------------------------------
Give daniel a time and think a little and check a code before making n issues about the same problem.

**Comment by IoDevl** [comment]
> > Yeah, that's literally because Osiris is made for CS:GO and not CS2 yet.
> 
> There is cs2 brach of osiris but there is literally no hooks and funcs to work with cs2. . Give daniel a time and think a little and check a code before making n issues about the same problem.

I know, I just told him that for now Osiris is not made for CS2 yet.

**Comment by tumuidle** [comment]
injected with extremeninjector, -insecure launch argument

![image](https://github.com/danielkrupinski/Osiris/assets/62649962/d3db7123-35fa-4d55-a16d-0e99385ff204)
