### ISSUE TITLE
- osiris cs2 branch has been released

### ISSUE THREAD

**Issue by ImsilverDev** [danielkrupinski/Osiris#4144]
if you aren't aware of it, the cs2 branch for osiris has been released, you can find it here:
https://github.com/danielkrupinski/Osiris/tree/cs2
or
![image](https://github.com/danielkrupinski/Osiris/assets/44844515/a78b0cb1-d872-4731-b86d-ff2e59a66294)

**Comment by Roasterbation** [comment]
@ImsilverDev Have you injected

**Comment by Roasterbation** [comment]
mine not injecting

**Comment by Xsintashi** [comment]
Dont think its ready to be injected.

**Comment by ImsilverDev** [comment]
> @ImsilverDev Have you injected

its not ready, its just published

**Comment by Xsintashi** [comment]
Anyway It has no features
