### ISSUE TITLE
cs2 recommend injector?

### ISSUE THREAD

**Issue by zallsjsksk** [danielkrupinski/Osiris#4145]
recommend injector，nocsgo

**Comment by Nep-Timeline** [comment]
https://github.com/TheCruZ/Simple-Manual-Map-Injector
work, but maybe detected

**Comment by fanat1cc** [comment]
Smokey injector has been updated to cs2 its manual map, ez cs has also been ported over other than that maybe a kernal driver injector such as a modified face injector
