### ISSUE TITLE
Is my compilation of Osiris for cs2 correct?

### ISSUE THREAD

**Issue by zallsjsksk** [danielkrupinski/Osiris#4146]
![屏幕截图 2023-10-02 144547](https://github.com/danielkrupinski/Osiris/assets/123486621/9e99ecb2-dc5d-40a7-b7d7-5a5d9001cfc3)
I compile Osiris in cs2. How big are the files?

**Comment by censfr** [comment]
it won't work in cs2

**Comment by zallsjsksk** [comment]
> 它在cs2中不起作用

injected with extremeninjector, -insecure launch argument
I tried but no esp
![屏幕截图 2023-10-02 195811](https://github.com/danielkrupinski/Osiris/assets/123486621/2c986708-8c1c-421d-b962-e5b62a67ec24)

**Comment by EXBC-TSJH** [comment]
现在还只有个底子,要有基本功能估计要到很久之后了

**Comment by danielkrupinski** [comment]
Yes, 32 KB is a correct size.
