### ISSUE TITLE
Can't inject

### ISSUE THREAD

**Issue by chiteroman** [danielkrupinski/Osiris#4151]
I can't inject this cheat on Windows 10 22H2. I tried SmokeyInjector and this: https://github.com/TheCruZ/Simple-Manual-Map-Injector

**Comment by fanat1cc** [comment]
Try ez cs2

**Comment by nomnom-DV** [comment]
link?

**Comment by DreamBecomingAgreyhat** [comment]
> Try ez cs2
Please send me the cs2 injector you use, it is very important to me, thanks  T_T.

**Comment by chiteroman** [comment]
NinjaCS did the trick, but there are few options :(

Hope @danielkrupinski add more in the future!

**Comment by nomnom-DV** [comment]
Could you pls make a google drive with your osiris.dll?
i tried using ninjacs but its not opening when i press insert :((((

**Comment by xddMthia** [comment]
> Could you pls make a google drive with your osiris.dll? i tried using ninjacs but its not opening when i press insert :((((

a while ago i made a [website](https://osiris.xdd.moe/) with auto building osiris.dll on each osiris update
today i updated the site to build the cs2 version of the osiris.dll

**Comment by anon65656** [comment]
> ###
> [Oct 7, 2023](#issuecomment-1751699312)

if only dll file is needed why would daniel make people compile it themselves? is it maybe safer? idk anything about source or code stuff but installing visual studio takes up space in my c drive which there isn't much of
