### ISSUE TITLE
weird cs2 error

### ISSUE THREAD

**Issue by nomnom-DV** [danielkrupinski/Osiris#4153]
![image](https://github.com/danielkrupinski/Osiris/assets/85874800/3c5681fe-4833-4c37-a746-c33d1cab5559)
not sure why this happens
i simply compiled the source and ran it through NinjaCS to inject

**Comment by lemonheadgamezlol** [comment]
got the same thing, glad im not the only one

**Comment by nomnom-DV** [comment]
wdym? can u show ss

**Comment by nomnom-DV** [comment]
my game just crashes

**Comment by lemonheadgamezlol** [comment]
im going to add you as well, id like to see this

my discord is w7nter.
