### ISSUE TITLE
Not working after injection

### ISSUE THREAD

**Issue by lemonheadgamezlol** [danielkrupinski/Osiris#4156]
So I tried injecting two ways, one with my own injector, and one with Cheat Engine. Both didnt work, but when I used Cheat Engine I got an actual error message, which read:

"Failed to find pattern 33 f6 48 0d ? ? ? ? 48 85 c9 74 13"

I clicked "Ok" and tried to open the cheat anyway, and when I clicked instert, nothing (on both injectors).

Error screenshot below

![Screenshot 2023-10-07 215321](https://github.com/danielkrupinski/Osiris/assets/107278828/4e329323-4825-49be-9940-9bd17c716443)

**Comment by 80381220** [comment]
There was no response either

**Comment by danielkrupinski** [comment]
Fixed in 3029d40c91bdd36e173aa892119a489497dc9d87
