### ISSUE TITLE
Linux injectionn

### ISSUE THREAD

**Issue by tr0u8le** [danielkrupinski/Osiris#4160]
I inject Osiris and i have this in termial:
Missing separate debuginfo for target:/home/.../.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/cs2
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/5c/c6517a0e1ea0a8ea57f76ff36b1609a7f9cc1d.debug
Missing separate debuginfo for target:/tmp/pressure-vessel-libs-CO1QC2/x86_64/gameoverlayrenderer.so
[...]

In game i have this
![image](https://github.com/danielkrupinski/Osiris/assets/130109122/949f2424-2220-4cbe-8fbc-bc158beca03e)

what is going on?

**Comment by tr0u8le** [comment]
Oh, so it hasn't been expanded yet?

**Comment by Xsintashi** [comment]
> Oh, so it hasn't been expanded yet?

nope
