### ISSUE TITLE
UI translation into other languages is garbled

### ISSUE THREAD

**Issue by hani-lengxi** [danielkrupinski/Osiris#4164]
How to solve this problem
![image](https://github.com/danielkrupinski/Osiris/assets/82372239/25c66855-a4e7-4202-ac90-d92abfcc76bb)

**Comment by jeteki** [comment]
Font missing

**Comment by danielkrupinski** [comment]
Should be fixed now (74aca25fb3a256bf3e709d3f3414190af2731894)

**Comment by hani-lengxi** [comment]
Thank you very much for your reply because this is how I solved the problem before
![image](https://github.com/danielkrupinski/Osiris/assets/82372239/122da4ec-8013-473d-ac04-536b0368124c)
