### ISSUE TITLE
Seems to inject successfully on linux however cant open gui

### ISSUE THREAD

**Issue by GabeeeM** [danielkrupinski/Osiris#4168]
![image](https://github.com/danielkrupinski/Osiris/assets/69842642/c33c1d29-c241-478c-94b3-120e30e5e13a)

is this the only thing implemented on cs2 so far or am I missing the keybind? I am pressing ins on my keyboard however nothing is coming up. I hope i am just being dumb and missing something easy.

**Comment by hani-lengxi** [comment]
Yeah, only three features so far

**Comment by YuWongXX** [comment]
Osiris is not ready for CS2, still on early stage of development.

**Comment by GabeeeM** [comment]
thanks for the replies
