### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by l0ccy** [danielkrupinski/Osiris#417]
- **Fix** Legit AA
- **Add** Manuel Legit AA
- **Add** Freestand Legit AA
- **Add** Edge Legit AA
-----------------------------------------------------------------------------------------------
- **Add** Legit AA Resolver
-----------------------------------------------------------------------------------------------
- **Add** Aimbot/Triggerbot/Magnet Trigger Hitbox Selection (multiple hitboxes possible)
- **Add** Aimbot Non sticky
-----------------------------------------------------------------------------------------------
- **Add** Triggerbot Burstfire
- **Add** Triggerbot Hitchance
-----------------------------------------------------------------------------------------------
- **Add** Magnet Trigger
- **Add** Magnet Trigger Silentaim
- **Add** Magnet TriggerFov
- **Add** Magnet TriggerSmooth
- **Add** Magnet TriggerRCS
- **Add** Magnet TriggerPrefere head
-----------------------------------------------------------------------------------------------
- **Add** Weapon Esp
- **Add** Granade Trace
- **Add** Scope Esp
- **Add** Edge Esp Box
- **Add** Dead Esp only
- **Add** Granade Esp
- **Add** Smoke/Molly Esp timer
-----------------------------------------------------------------------------------------------
- **Add** Fakelag modes (Normal, On Peek, ..)
- **Add** Blockbot
- **Add** Desync chams
- **Add** Name Changer
- **Add** Fake ping
- **Add** Bhop hitchance
- **Add** "Normal" hitmarker
- **Add** Draw Fov
- **Add** Anti OBS
- **Add** Item Purchase List
-----------------------------------------------------------------------------------------------
those updates would be lit af!

**Comment by thoma202411** [comment]
just fix legit aa thats all
add too many function will make this cheat paid!!!

**Comment by Shaxzy** [comment]
> just fix legit aa thats all
> add too many function will make this cheat paid!!!

This^

**Comment by mindofenzo** [comment]
I agree, Fix legit AA so spectators see your fake animation angles instead of the real. Id condense the list to features you cant live without so the developer knows what his community specifically wants.

**Comment by l0ccy** [comment]
updated the list a littelbit its now smaller and less stuff

**Comment by tirziz** [comment]
I have a idea, we can make a Custom MVP Music . it;s play everytime the round end via ingame-mic. just like SLAM but auto triggered. thing is idk where to start

**Comment by l0ccy** [comment]
most useless bullshit i ever heard do it your self if you want this noone else whant useless stuff like this

**Comment by Evilhelder** [comment]
RUN BOOST HELPER PLEASEEEEEEEEEEEEE ;-;

**Comment by Evilhelder** [comment]
I really want to test a BlockBot or RunBoost! I don't credit card or money to buy a cheat with this function .... And I started learning how to program now ...

**Comment by jdb-jdb** [comment]
Daniel just beat me to it with c909cae 747b366 e0d9802 5148e96 but if you just want to have a custom name and not steal names, either create an extra menu element with this or replace the stealer with this

`
if (config.misc.nameChanger) {


        auto name = interfaces.cvar->findVar("name");


		const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
		name->onChangeCallbacks.size = 0;
		std::string newName = config.misc.customName;
		if (newName.compare("") != 0) {
			name->setValue(newName.c_str());
		}	
}`

**Comment by Evilhelder** [comment]
So when will he put the BlockBot or the run boost assist? xD I'm waiting a lot for this.. :(

**Comment by jdb-jdb** [comment]
Don't worry - you don't need money to buy a cheat with the function :). You said you have started to learn to program, how far have you got? What have you programmed?

As for the question about when is it going to be implemented, I could not say as I don't know Daniel's agenda, however, I can assist you if you wish to implement the feature yourself in your own fork if you like? Maybe it may lead to a pull request if it works out well ;)

That's the thing with a great open-source project like this, others can implement features they like and contribute

**Comment by Evilhelder** [comment]
> 
> 
> Don't worry - you don't need money to buy a cheat with the function :). You said you have started to learn to program, how far have you got? What have you programmed?
> 
> As for the question about when is it going to be implemented, I could not say as I don't know Daniel's agenda, however, I can assist you if you wish to implement the feature yourself in your own fork if you like? Maybe it may lead to a pull request if it works out well ;)
> 
> That's the thing with a great open-source project like this, others can implement features they like and contribute

I didn't mean to offend, I was just making a joke. About my programming experience, none of the teachers I've had so far in college have used VS, and only learned the basics of basic alternative programs like NetBeans, Lua and etc... If I had money I would definitely help Daniel or would buy a cheat with this function. And if I knew at least the basics of VS or learned a bit more about C ++ programming, I'd try to implement this function myself and share it here... 

sorry for this. :(

**Comment by Evilhelder** [comment]
Sorry for my english too, I'm Brazilian.

**Comment by Evilhelder** [comment]
> 
> 
> Don't worry - you don't need money to buy a cheat with the function :). You said you have started to learn to program, how far have you got? What have you programmed?
> 
> As for the question about when is it going to be implemented, I could not say as I don't know Daniel's agenda, however, I can assist you if you wish to implement the feature yourself in your own fork if you like? Maybe it may lead to a pull request if it works out well ;)
> 
> That's the thing with a great open-source project like this, others can implement features they like and contribute

About my programming experience, none of the teachers I've had so far in college have used VS, and only learned the basics of basics in some alternative programs like NetBeans, Lua and etc ... If I had money I would help Daniel. And if I knew at least the basics of VS or learned a bit more about C ++ programming, I'd try to implement this function and share it here.

**Comment by jdb-jdb** [comment]
> About my programming experience, none of the teachers I've had so far in college have used VS, and only learned the basics of basics in some alternative programs like NetBeans, Lua and etc ... If I had money I would help Daniel. And if I knew at least the basics of VS or learned a bit more about C ++ programming, I'd try to implement this function and share it here.


I see what you mean. I also don't have much experiance in the way of c++, I studied Java as the place I learnt didn't offer c++. However, I just use code I've found on other github cheats which have similar features and translate the code from that into code that works in this cheat one favourite of mine is to use AimTux eg(

 `C_BasePlayer* localplayer = (C_BasePlayer*) entityList->GetClientEntity(engine->GetLocalPlayer()); `

becomes 

`const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer()); in Osiris`

I just translate code from one to the other

**Comment by Evilhelder** [comment]
> 
> 
> > About my programming experience, none of the teachers I've had so far in college have used VS, and only learned the basics of basics in some alternative programs like NetBeans, Lua and etc ... If I had money I would help Daniel. And if I knew at least the basics of VS or learned a bit more about C ++ programming, I'd try to implement this function and share it here.
> 
> I see what you mean. I also don't have much experiance in the way of c++, I studied Java as the place I learnt didn't offer c++. However, I just use code I've found on other github cheats which have similar features and translate the code from that into code that works in this cheat one favourite of mine is to use AimTux eg(
> 
> `C_BasePlayer* localplayer = (C_BasePlayer*) entityList->GetClientEntity(engine->GetLocalPlayer()); `
> 
> becomes
> 
> `const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer()); in Osiris`
> 
> I just translate code from one to the other

Got it, I'll try to learn how to do that too.
