### ISSUE TITLE
Unable to inject Osiris in CS2

### ISSUE THREAD

**Issue by SpryerS** [danielkrupinski/Osiris#4176]
When I try to inject the following code -> "sudo gdb -batch-silent -p $(pidof cs2) -ex "call (void*)dlopen(\"$PWD/libOsiris.so\", 2)"" I just get met with the error -> 29	../sysdeps/unix/sysv/linux/poll.c: No such file or directory.

I do not know what this means and I have not seen anyone else have this issue.

**Comment by Keinweb** [comment]
same problem here, is there any fix?

**Comment by SpryerS** [comment]
I found that the error message was just there and when trying it a couple of times it somehow worked. Idk if the error is part of the injection but try it and just check your CS if there is a menu at the top of your screen that have a button that looks like a bug.

**Comment by henrydatei** [comment]
same problem here. and trying it a couple times doens't help
