### ISSUE TITLE
Osiris not injecting with Xenos

### ISSUE THREAD

**Issue by Stezix** [danielkrupinski/Osiris#4177]
Hello everyone! I tried to inject Osiris with Xenos DLL Injector, but after injecting it crashing, anyone know how to fix it?
I know so many will say do you changed Injection type to Manual map, yes I changed but also I turn on these features: "Erase PE Headers" and "Ignore TLS". (I'am using Windows 10 Pro newest version with Visual Studio 2022)
So if anyone know how to fix this issue or what I need to change please type bellow! ty!

**Comment by danielkrupinski** [comment]
Check "No exception support" in Xenos

**Comment by Stezix** [comment]
> Check "No exception support" in Xenos

Working thanks! Also I hope any type of ESP will come soon!
