### ISSUE TITLE
Failed to find pattern (CSGO not CS2)

### ISSUE THREAD

**Issue by Mario96TheReal** [danielkrupinski/Osiris#4182]
Hello! I am currently having a problem with Osiris not injecting in CS:GO, **_I downloaded the csgo branch_** and I am getting the exact same error as another user called "amircheg"
where when I inject the dll I compiled gives me these 2 errors and then the game crashes
![272828521-23af1d8b-cbb2-44c3-a26f-3c8611d17459](https://github.com/danielkrupinski/Osiris/assets/116758821/078051ee-976e-4847-9305-0264b41ce5e0)
![272828517-6df89165-3c52-4aa9-8ab3-07e74a5a6625](https://github.com/danielkrupinski/Osiris/assets/116758821/a45d421d-11e7-47e0-bff4-6b85254a6a59)

**Comment by crackermemer** [comment]
Those are the patterns for **present** and **reset** functions inside the **gameoverlayrenderer.dll**
You can find the code inside of **Memory.h** and update the patterns there.

**Comment by Mario96TheReal** [comment]
Oh my goodness I am going to try that right now if it works I do not know how to thank you enough man really you are the best

**Comment by WadamkaLmao** [comment]
I know it may be a bit late but how exactly was this fixed?
