### ISSUE TITLE
tiny aimbot problem

### ISSUE THREAD

**Issue by TrackyBunny** [danielkrupinski/Osiris#42]
Hey man, just wanted to say that the aimbot doesn't work WITH a GLOCK only. I've tried every other pistol/heavy/smg/rifle/sniper etc.. Everything works, except the glock. 

I've also tried to see if it's from the teams and if the aimbot will work with a glock on t or ct side but doesn't seem to work on both teams :D 

Ask me anything you want if you need any information on your future fix.

Little Regards
Kyle

**Comment by danielkrupinski** [comment]
Seems to be fixed.
