### ISSUE TITLE
[BUG] ReportBot config corrupted due typo

### ISSUE THREAD

**Issue by mdilai** [danielkrupinski/Osiris#421]
Nuff said:

https://github.com/danielkrupinski/Osiris/blob/45eeb846a93b9f4b2b0face67c41164b61c9d889/Osiris/Config.cpp#L652

Should be
`reportbotJson["Griefing"] = reportbot.griefing;`

Too lazy to make a pull request.

P.S. So much bugs added in few last days. Daniel, maybe you need a little rest? :)

**Comment by Bywnb** [comment]
Daniel may not be himself recently. He really should take a rest :)

**Comment by wieisstimpee** [comment]
> Daniel may not be himself recently. He really should take a rest :)

I agree, he should just take a week off

**Comment by danielkrupinski** [comment]
Fixed, thanks!
