### ISSUE TITLE
[Ideas] Distance based Aimbot FOV and noAimPunch

### ISSUE THREAD

**Issue by mindofenzo** [danielkrupinski/Osiris#422]
It would be a useful feature to make the aimbot fov scale to the distance between you and the target instead of the current static fov, which creates a larger hitbox at long range and may not be desired by some.

No aim punch is a visual feature where there is no screen movement when you take damage. This helps stay on target during gunfights.

**Comment by wieisstimpee** [comment]
+1 for both, it is a legit cheat in the end so the more aimbot features to make it look legit, the better!

**Comment by mindofenzo** [comment]
I got the noAimPunch code working, but visual studio wanted to act a fool so it doesn't easily show the code I changed to make it work

**Comment by wieisstimpee** [comment]
> I got the noAimPunch code working, but visual studio wanted to act a fool so it doesn't easily show the code I changed to make it work

cant you just give me a copy of your aimbot.cpp (and/or aimbot.h if you had to change that too)

**Comment by mindofenzo** [comment]
I added the files here: https://github.com/mindofenzo/Osiris/commit/9f8e513c281080e6c56c1e8115a367a1f5518092

Just save them and replace them in your project for now. With how easy this was to implement, I'd be surprised if daniel doesn't add it to the official code.
