### ISSUE TITLE
can't see footsteps even when visualize is turned on - Linux

### ISSUE THREAD

**Issue by prontodos** [danielkrupinski/Osiris#4228]
Linux using injector :+1: 
sudo gdb -batch-silent -p $(pidof cs2) -ex "call (void*)dlopen(\"$PWD/libOsiris.so\", 2)"

got error msg : 
../sysdeps/unix/sysv/linux/poll.c: No such file or directory.

but I can see the "bug" icon. 

turned on see footsteps but still can't see the visuals. 

Anyone can help ?

**Comment by Q-666** [comment]
i'm having the same issue

**Comment by danielkrupinski** [comment]
Do you have headphones plugged in? Can you hear footstep sounds?

**Comment by Q-666** [comment]
Yes i have headphones plugged in and i can hear all ingame sounds including footsteps.

**Comment by prontodos** [comment]
yeah. 
just not see the visuals.
this "hack" is turning out to be a joke.

**Comment by danielkrupinski** [comment]
This is an open-source project so you can use a debugger to find out why the feature is not working for you.
