### ISSUE TITLE
This is the worst cheat I have ever seen in a video game

### ISSUE THREAD

**Issue by Ruizlow** [danielkrupinski/Osiris#4233]
It took me a few hours to even figure out how to install this shit on linux and it doesn't even have an ESP? This is literal garbage.

**Comment by Xsintashi** [comment]
> It took me a few hours to even figure out how to install this shit on linux and it doesn't even have an ESP? This is literal garbage.

You could do better, could you?
Also nobody forces you to use it

**Comment by Ruizlow** [comment]
> > It took me a few hours to even figure out how to install this shit on linux and it doesn't even have an ESP? This is literal garbage.
> 
> You could do better, could you? Also nobody forces you to use it

Okay you right. Just got heated, the cheat has a lot of useful things and you have much lower chances of a ban cause it ain't walls.

**Comment by Xsintashi** [comment]
> > > It took me a few hours to even figure out how to install this shit on linux and it doesn't even have an ESP? This is literal garbage.
> > 
> > 
> > You could do better, could you? Also nobody forces you to use it
> 
> Okay you right. Just got heated, the cheat has a lot of useful things and you have much lower chances of a ban cause it ain't walls.

Also cheat is still in early stage and Daniel is gonna 100% improve it
