### ISSUE TITLE
Update Osiris for cs go please.

### ISSUE THREAD

**Issue by ITSBONVOYAGE** [danielkrupinski/Osiris#4236]
Hi, I really like Osiris. It so happened that I still play CS GO on a server where the Kazakhs use cheats and include acting skills. I am also forced to play with WH. But Steam updated GameOverlayRenderer.dll and now Osiris can’t find its patterns, can you please update it for CSGO? Please

And can you tell me if it is updated how to download it from here? I downloaded the required version from another site where there was a DLL version that needed to be injected. How can I find the same version? Otherwise I download it here and don’t understand how to install it

**Comment by doubleOpink** [comment]
+1

**Comment by danielkrupinski** [comment]
Fixed in ef472aa
