### ISSUE TITLE
constexpr error?

### ISSUE THREAD

**Issue by saxomulep** [danielkrupinski/Osiris#424]
please help compile.
https://ibb.co/C8M3BJ0

**Comment by danielkrupinski** [comment]
What Visual Studio version you use?

**Comment by saxomulep** [comment]
visual studio 2019. I could get dll smoothly a few days ago but now it gives error

**Comment by Shaxzy** [comment]
Same error with VS17

**Comment by saxomulep** [comment]
danielkrupinski Waiting for your response :)

**Comment by Bywnb** [comment]
@danielkrupinski I had the same problem.My Visual Studio version is vs2019 16.2.1

**Comment by saxomulep** [comment]
@danielkrupinski @saxomulep @Shaxzy @Bywnb 
problem was solved with the latest update. thanks
