### ISSUE TITLE
error: failed to find pattern... 

### ISSUE THREAD

**Issue by danoo-C** [danielkrupinski/Osiris#4240]
hello, does anybody know how to fix this error? also I included my injector (xenos) and its configuration in the screenshot.

![osoris_error](https://github.com/danielkrupinski/Osiris/assets/108084891/60530caf-9556-4465-bdf3-5d6376c3810c)

**Comment by Xsintashi** [comment]
Cheat is outdated, update it by yourself or wait for Daniel to do it.

**Comment by danielkrupinski** [comment]
Fixed

**Comment by danoo-C** [comment]
thanks!
