### ISSUE TITLE
Failed To Find Pattern

### ISSUE THREAD

**Issue by Wojtek17779388** [danielkrupinski/Osiris#4248]
it said Failed to find pattern
![image](https://github.com/danielkrupinski/Osiris/assets/165857136/515060d8-edf6-485d-9d34-f96cbddf9494)

**Comment by LiLPandemio** [comment]
Same here and for a friend @danielkrupinski

**Comment by akrambak** [comment]
Same

**Comment by Wojtek17779388** [comment]
im using the guided hacking injector if that helps i had a friend compile that and its working

**Comment by danielkrupinski** [comment]
Fixed already
