### ISSUE TITLE
DLL Injetion does not work anymore after Update

### ISSUE THREAD

**Issue by akrambak** [danielkrupinski/Osiris#4250]
Hi,

DLL Injection does not work anymore after Update

![Capture d'écran 2024-04-03 015634](https://github.com/danielkrupinski/Osiris/assets/3879402/db160481-c478-4905-a286-b05d3f3c27f2)

**Comment by ethnyl** [comment]
what injector are you using?

**Comment by danielkrupinski** [comment]
Fixed
