### ISSUE TITLE
(SUGGESTION) DEAD Chams

### ISSUE THREAD

**Issue by MrClue** [danielkrupinski/Osiris#426]
Apply chams on dead players.

**Comment by mindofenzo** [comment]
Why?

**Comment by kschou95** [comment]
y? just use inverse ragdoll

**Comment by BlackmanWhite** [comment]
I mean, it can look cool

**Comment by Bywnb** [comment]
Daniel added it to glow

**Comment by MrClue** [comment]
So what he added it to glow? Im talking about chams not glow ESP lol, stick to the topic.
