### ISSUE TITLE
[WINDOWS] Crashing on injection

### ISSUE THREAD

**Issue by yummbeeUni** [danielkrupinski/Osiris#4264]
i wrote a manual mapper following the Guided Hacking tutorial and build osiris then tried to inject, upon which cs2 crashes instantly. I suspect its to do with the offsets but i cannot find where they are in the osiris code to update them myself. Any ideas?

**Comment by danielkrupinski** [comment]
Osiris is up to date. The problem is with your injector, maybe it's crashing on resolving imports because Osiris does not have import table in Release build.
