### ISSUE TITLE
error while building with visual studio

### ISSUE THREAD

**Issue by Tuho420** [danielkrupinski/Osiris#4267]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C7602	'InRange': the associated constraints are not satisfied	Osiris	C:\Users\...\source\repos\Osiris-cs2\Source\Utils\ColorUtils.h	12

**Comment by Wojtek17779388** [comment]
is it in release x64

**Comment by danielkrupinski** [comment]
Update Visual Studio
