### ISSUE TITLE
[LINUX] Failied to find pattern

### ISSUE THREAD

**Issue by petya8bachey** [danielkrupinski/Osiris#4271]
![Screenshot from 2024-04-27 12-21-22](https://github.com/danielkrupinski/Osiris/assets/123090696/4ef288cb-b766-429c-96de-481088463900)
![Screenshot from 2024-04-27 12-21-04](https://github.com/danielkrupinski/Osiris/assets/123090696/be8c18d6-9924-407e-8ca6-9916d074752f)
Ubuntu 22.04

**Comment by Wojtek17779388** [comment]
its patched

**Comment by danielkrupinski** [comment]
Fixed (c1156df59789bc7d29a98ce2dbb3d51d8d858f7c)
