### ISSUE TITLE
A port to zgui

### ISSUE THREAD

**Issue by darkdawn29** [danielkrupinski/Osiris#428]
anyway to port this to zgui ?
[https://github.com/zxvnme/zgui](url)

**Comment by mindofenzo** [comment]
would be a fun project to take on if you have little coding experience

**Comment by darkdawn29** [comment]
i can if someone walks me through it. i ready to learn and spend shit load of time with it. would be great if that port happens

**Comment by mindofenzo** [comment]
I personally think imgui is amazing and with the customization options it has, it would be better to focus efforts elsewhere unless you really want zgui. I couldnt walk you through it in less than a couple hours.

**Comment by danielkrupinski** [comment]
Yes, it is possible, but you have to do it on your own.

**Comment by mindofenzo** [comment]
[https://github.com/danielkrupinski/Explit](url)
