### ISSUE TITLE
CS:GO Legacy Feature Request Inventory Changer

### ISSUE THREAD

**Issue by Toaaa** [danielkrupinski/Osiris#4286]
It would be cool to be able to set patterns and float for skins and knives in the CS:GO Legacy version of Osiris. Currently you can only give yourself items via the Inventory Manger, but not customize them (e.g. pattern, float, stickers etc.).

**Comment by DieInCalamity** [comment]
You can add stickers. But we all need statrak

**Comment by danielkrupinski** [comment]
You can change these values by editing a config file. CS:GO version will not receive new features.
