### ISSUE TITLE
pattern

### ISSUE THREAD

**Issue by Aliorpse** [danielkrupinski/Osiris#4294]
pattern upd

**Comment by Aliorpse** [comment]
windows can't load any modules

**Comment by Ry4nnnnn** [comment]
because cs2 has been updated

**Comment by Aliorpse** [comment]
can u adapt [this](https://github.com/a2x/cs2-dumper) offset dumper pls?

**Comment by jimitogni** [comment]
On Linux Debian trixie, I'm receiving a lot of these errors. They are appearing since the old versions of Osiris but, despite these error messages, Osiris load and run. But now he steals injections after errors but the visual resources do not work. Anyone can help me, please?

![2024-05-24-212208_621x128_scrot](https://github.com/danielkrupinski/Osiris/assets/32150659/3b9cd88a-2db8-45e0-94e5-bfc094bc5369)
![2024-05-24-212152_576x125_scrot](https://github.com/danielkrupinski/Osiris/assets/32150659/b5b8cc70-ffe6-4b95-b5e9-84be40dec46a)
![2024-05-24-212144_407x126_scrot](https://github.com/danielkrupinski/Osiris/assets/32150659/b6dc7e50-3708-4cf2-82b4-e5d4519090c4)
![2024-05-24-212133_529x144_scrot](https://github.com/danielkrupinski/Osiris/assets/32150659/5a71169e-930d-43ec-be63-5456824fe0d0)

**Comment by Aliorpse** [comment]
> On Linux Debian trixie, I'm receiving a lot of these errors. They are appearing since the old versions of Osiris but, despite these error messages, Osiris load and run. But now he steals injections after errors but the visual resources do not work. Anyone can help me, please?
> 
> ![2024-05-24-212208_621x128_scrot](https://private-user-images.githubusercontent.com/32150659/333758369-3b9cd88a-2db8-45e0-94e5-bfc094bc5369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1OTgyNjUsIm5iZiI6MTcxNjU5Nzk2NSwicGF0aCI6Ii8zMjE1MDY1OS8zMzM3NTgzNjktM2I5Y2Q4OGEtMmRiOC00NWUwLTk0ZTUtYmZjMDk0YmM1MzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDAwNDYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YmNkMDNmZmU3M2RmMThhNzY0MmJhZDExNTk5ZWM3ZTkwZGRkMDNiZGY5Zjc0MmI0OWNmNzM0NTdlNmJjYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nwaw3QZoWgZKNWnrmzvGOLTrIdJBijh77N3_e_U5esM) ![2024-05-24-212152_576x125_scrot](https://private-user-images.githubusercontent.com/32150659/333758370-b5b8cc70-ffe6-4b95-b5e9-84be40dec46a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1OTgyNjUsIm5iZiI6MTcxNjU5Nzk2NSwicGF0aCI6Ii8zMjE1MDY1OS8zMzM3NTgzNzAtYjViOGNjNzAtZmZlNi00Yjk1LWI1ZTktODRiZTQwZGVjNDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDAwNDYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ODYxYjAwMTQxYWE5MWEyZDQ2NGRhZWIwYjg5NDgyNTMxMjlhNWRhZWI0OGEwMDU5MzgxM2UzZjJlZGNmZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NCy5GAj7yZBQe2NBZObynlKhLOzdTJpYcJPK-4p_vsA) ![2024-05-24-212144_407x126_scrot](https://private-user-images.githubusercontent.com/32150659/333758371-b6dc7e50-3708-4cf2-82b4-e5d4519090c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1OTgyNjUsIm5iZiI6MTcxNjU5Nzk2NSwicGF0aCI6Ii8zMjE1MDY1OS8zMzM3NTgzNzEtYjZkYzdlNTAtMzcwOC00Y2YyLTgyYjQtZTVkNDUxOTA5MGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDAwNDYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZWIyODQ0N2E1YTE1MjIzMzMxOGYyMzhlNzE2YjExZTMzMzEyZGYxMjdhMzRiOWVjNDkwYjY2NTdhODRlYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4pPPjQUfW8Xuda2alTd49gBICNDzVmaze-wSUIo2F88) ![2024-05-24-212133_529x144_scrot](https://private-user-images.githubusercontent.com/32150659/333758372-5a71169e-930d-43ec-be63-5456824fe0d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1OTgyNjUsIm5iZiI6MTcxNjU5Nzk2NSwicGF0aCI6Ii8zMjE1MDY1OS8zMzM3NTgzNzItNWE3MTE2OWUtOTMwZC00M2VjLWJlNjMtNTQ1NjgyNGZlMGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDAwNDYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNGNjOGI5ZWNiNjBkZGIyYmMyZmE5NTUzOGI1NTU4N2QwY2UxMmYzMWEwNGU2MjhmNDkzNzNlNjhmYjlmMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SqbCON3tj2bWl_CNpw3E_7BNzM9o-qJ1eSB8XPPqcBw)

wait for osiris upd
