### ISSUE TITLE
failed to find pattern 

### ISSUE THREAD

**Issue by hduser123** [danielkrupinski/Osiris#4296]
error while injecting 
windows build
<details><summary>Details</summary>
<p>

> ![Screenshot 2024-05-26 203702](https://github.com/danielkrupinski/Osiris/assets/170875051/a2fcdd54-db54-4f32-b64a-042146be19b8)
> ![Screenshot 2024-05-26 203654](https://github.com/danielkrupinski/Osiris/assets/170875051/fe4ce22a-2a50-41f7-afde-6d24b631cef5)
> ![Screenshot 2024-05-26 203643](https://github.com/danielkrupinski/Osiris/assets/170875051/a39ad8e2-149f-4f69-b5ab-30d79a7561ba)
> ![Screenshot 2024-05-26 203626](https://github.com/danielkrupinski/Osiris/assets/170875051/95ca5093-e66f-41c8-ba19-bebb737a6236)
> ![Screenshot 2024-05-26 203539](https://github.com/danielkrupinski/Osiris/assets/170875051/20ba37b9-51a4-462f-9fca-3acf072fb237)
> ![Screenshot 2024-05-26 203509](https://github.com/danielkrupinski/Osiris/assets/170875051/ac456071-18cd-4271-b59c-b3b859176c66)

</p>
</details> 

how to fix??

**Comment by Aliorpse** [comment]
wait for osiris upd

**Comment by Alec07007** [comment]
> error while injecting 
> windows build
> <details><summary>Details</summary>
> <p>
> 
> > ![Screenshot 2024-05-26 203702](https://github.com/danielkrupinski/Osiris/assets/170875051/a2fcdd54-db54-4f32-b64a-042146be19b8)
> > ![Screenshot 2024-05-26 203654](https://github.com/danielkrupinski/Osiris/assets/170875051/fe4ce22a-2a50-41f7-afde-6d24b631cef5)
> > ![Screenshot 2024-05-26 203643](https://github.com/danielkrupinski/Osiris/assets/170875051/a39ad8e2-149f-4f69-b5ab-30d79a7561ba)
> > ![Screenshot 2024-05-26 203626](https://github.com/danielkrupinski/Osiris/assets/170875051/95ca5093-e66f-41c8-ba19-bebb737a6236)
> > ![Screenshot 2024-05-26 203539](https://github.com/danielkrupinski/Osiris/assets/170875051/20ba37b9-51a4-462f-9fca-3acf072fb237)
> > ![Screenshot 2024-05-26 203509](https://github.com/danielkrupinski/Osiris/assets/170875051/ac456071-18cd-4271-b59c-b3b859176c66)
> 
> </p>
> </details> 
> 
> 
> 
> 
> how to fix??

Can you lls tell me what is the name of injector you are using?

**Comment by hduser123** [comment]
extreme

**Comment by jimitogni** [comment]
I had same problem here in Linux Debian

**Comment by danielkrupinski** [comment]
Fixed
