### ISSUE TITLE
client_panorama pattern needs to be updated

### ISSUE THREAD

**Issue by lolergg345** [danielkrupinski/Osiris#43]
need to update client_panorama pattern cuz valve just changed it

**Comment by Ni1kko** [comment]
Utils::PatternScan2(GetModuleHandle("client_panorama.dll"), "55 8B EC 8B 0D ? ? ? ? 85 C9 75 ? A1 ? ? ? ? 68 ? ? ? ? 8B 08 8B 01 FF 50 ? 85 C0 74 ? 8B C8 E8 ? ? ? ? 8B C8 EB ? 33 C9 89 0D ? ? ? ? 8B 45 ? FF 70 ? E8 ? ? ? ? B0 ? 5D");

**Comment by Ni1kko** [comment]
Updated offsets ... https://github.com/frk1/hazedumper
