### ISSUE TITLE
offsets

### ISSUE THREAD

**Issue by ogosirisfan** [danielkrupinski/Osiris#430]
which file is responsible for offsets (automatic)

**Comment by NexSqaud** [comment]
There no offsets. You need updating only function indexes.(look at SDK folder)

**Comment by ogosirisfan** [comment]
i have ijre osiris and dosen't work after update.

**Comment by mindofenzo** [comment]
what doesnt work?

**Comment by ogosirisfan** [comment]
antiaim e.g
