### ISSUE TITLE
[SUGGESTION] New feature.

### ISSUE THREAD

**Issue by rosesware** [danielkrupinski/Osiris#431]
A lot of people like to play legit, even without Glow, Chams and even without Aimbot, so I suggested you add if possible "Knife on the left hand" ie weapons and all other items are on the right hand but when we pull to the knife and knife goes to the left hand.

There are binds that help, but they are not so accurate because if we click the "Q" key to change weapons and the knife will not go to the left side.

It is a suggestion that I think is easy to code this feature.

**Comment by hydemods** [comment]
lot of open sources have this my guy, easy paste

**Comment by Kron1Q** [comment]
+1 easy af. just check cl_righthand
and if current weapon is knife then force 0 or 1 (if u want weapon in right and knife in left or vice versa)

**Comment by tirziz** [comment]
Can I ask, why ppl want to have that feature

**Comment by Kron1Q** [comment]
@tirziz idk about others but i feel nostalgic (cs1.6)

**Comment by effex1337** [comment]
> void Misc::swaphandonknife() noexcept {
> 	if (interfaces.engine->isInGame())
> 	{
> 		const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
> 		if (localPlayer->isAlive())
> 		{
> 			const auto activeWeapon = localPlayer->getActiveWeapon();
> 			auto swapknife = interfaces.cvar->findVar("cl_righthand");
> 			if (config.misc.swaphandonknife)
> 			{
> 				if (activeWeapon->getClientClass()->classId == ClassId::Knife)
> 				{
> 					swapknife->setValue(0);
> 				}
> 				if (activeWeapon->getClientClass()->classId != ClassId::Knife)
> 				{
> 					swapknife->setValue(1);
> 				}
> 			}
> 		}
> 	}
> }

**Comment by effex1337** [comment]
i still don't know how to fix the indentation on github

**Comment by DouglasHoyer** [comment]
you don't even need cheats for this. use an autoexec and have it so that when you press 1 and or 2 it makes cl_righthand 1 and when you press 3 it makes it 0. 1 and 2 being main and pistol and 3 being the knife

**Comment by mindofenzo** [comment]
> you don't even need cheats for this. use an autoexec and have it so that when you press 1 and or 2 it makes cl_righthand 1 and when you press 3 it makes it 0. 1 and 2 being main and pistol and 3 being the knife

Yes but a lot of people use q to change weapons

**Comment by thomas0aotian** [comment]
> > void Misc::swaphandonknife() noexcept {
> > if (interfaces.engine->isInGame())
> > {
> > const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
> > if (localPlayer->isAlive())
> > {
> > const auto activeWeapon = localPlayer->getActiveWeapon();
> > auto swapknife = interfaces.cvar->findVar("cl_righthand");
> > if (config.misc.swaphandonknife)
> > {
> > if (activeWeapon->getClientClass()->classId == ClassId::Knife)
> > {
> > swapknife->setValue(0);
> > }
> > if (activeWeapon->getClientClass()->classId != ClassId::Knife)
> > {
> > swapknife->setValue(1);
> > }
> > }
> > }
> > }
> > }

NOT WORKING 
TESTED IT

**Comment by effex1337** [comment]
Did you even call it?

**Comment by thomas0aotian** [comment]
@effex1337 ofc

**Comment by thomas0aotian** [comment]
called in misc.h

**Comment by effex1337** [comment]
Show me the snippet how u called it.

**Comment by effex1337** [comment]
You only define stuff in misc.h and call it in hooks.cpp->createmove.

**Comment by thomas0aotian** [comment]
oh

**Comment by thomas0aotian** [comment]
void stealNames() noexcept;

> You only define stuff in misc.h and call it in hooks.cpp->createmove.

**Comment by thomas0aotian** [comment]
@effex1337 alright bud i think i got it now tks a lot:kissing_heart:
