### ISSUE TITLE
Is it possible to compile it in Clion?

### ISSUE THREAD

**Issue by Map1eUM** [danielkrupinski/Osiris#4312]
On windows it shows: 

-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- The ASM-ATT compiler identification is unknown
-- Didn't find assembler
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_ASM-ATT_COMPILER could be found.

-- Configuring incomplete, errors occurred!

[Failed to reload]

I did use VS toolchain in clion. I wonder if this is a system problem?

**Comment by danielkrupinski** [comment]
Fixed in commit 1147ff9d38ac76397453af5e2f50c908611849f0
