### ISSUE TITLE
cs2 7.23 upd pattern not work

### ISSUE THREAD

**Issue by Aliorpse** [danielkrupinski/Osiris#4313]

**Comment by danielkrupinski** [comment]
Show a screenshot of the error.

**Comment by Aliorpse** [comment]
Im now wondering if it is not Osiris's problem.
my injector seems not worked as expectation and it should inject the dll after the game load but it inject when the game process just start and says:"Cheat loaded."
then there are many errors occurred "Failed to find pattern xx xx xx xx xx xx", there are so many that i can't screenshot them at once.

**Comment by Svxy** [comment]
Which injector are you using? Are you sure you're even injecting properly?

**Comment by Aliorpse** [comment]
> Which injector are you using? Are you sure you're even injecting properly?

using NinjaCS and im not sure for that
ninjacs injects correctly on earlier cs versions
