### ISSUE TITLE
csgo version, not cs2

### ISSUE THREAD

**Issue by Ryssiaczrk** [danielkrupinski/Osiris#4319]
where can I find a version of osiris for the old csgo_legacy 1.38.8.1? any archives?

**Comment by kriebelmuis** [comment]
you should check out the [csgo branch](https://github.com/danielkrupinski/Osiris/tree/csgo) or try the [end of life relesae](https://github.com/danielkrupinski/Osiris/releases/tag/csgo-end-of-life)

**Comment by Ryssiaczrk** [comment]
both have outdated patterns, the csgo branch is more updated tho, how do I fix the patterns?

**Comment by Ryssiaczrk** [comment]
thanks! it works
