### ISSUE TITLE
Shouldn't this be detected?

### ISSUE THREAD

**Issue by Coopyy** [danielkrupinski/Osiris#4332]
Do correct me if im wrong, but it seems like you're swapping the whole VMT in your hooks, shouldnt this get smoked by the checks you discussed [here](https://github.com/danielkrupinski/cs2-anticheat) (CUserMessageRequestInventory)?
`optional int64 offset = 3; // **g_pInterfaceGlobals[index] (address of virtual method table of the interface)`
I've been trying to research vac a bit before adding hooks, and noticed this and wanted to make sure i wasn't missing something obvious

**Comment by danielkrupinski** [comment]
The objects we are hooking are not global interfaces so they're not covered by these checks.
