### ISSUE TITLE
[consideration] Sniper Crosshair disabled when Zoom?

### ISSUE THREAD

**Issue by 0xE232FE** [danielkrupinski/Osiris#434]
Hello Daniel,

May I ask you why you hide the Sniper Cross on **isScoped**?
Isn't it better to remove the check to have the Sniper Cross always visible even in Scoped situations?

https://github.com/danielkrupinski/Osiris/blob/fd2e13ac29575badd553ccede3e61c5592db21dd/Osiris/Hacks/Misc.cpp#L79

Wouldn't it be enough to have the SniperCrosshair always visible?
`showSpread->setValue(config.misc.sniperCrosshair ? 3 : 0);`

**Comment by Shaxzy** [comment]
Why would you need a crosshair when you're scoped anyways? I believe it's meant for noscoping

**Comment by wieisstimpee** [comment]
> Why would you need a crosshair when you're scoped anyways? I believe it's meant for noscoping

thats why he wants it gone when he scopes..

**Comment by 0xE232FE** [comment]
I find the Crosshair very useful because it doesn't blure when you move.
