### ISSUE TITLE
After the update of Counter Strike 2 today, we found that Osiris injection failed. Can you please solve this problem?

### ISSUE THREAD

**Issue by starnotes-xj** [danielkrupinski/Osiris#4347]
After the update of Counter Strike 2 today, we found that Osiris injection failed. Can you please solve this problem?

**Comment by starnotes-xj** [comment]
![image](https://github.com/user-attachments/assets/eb40e6c7-f7c1-459c-bf54-aa2356349f82)
![image](https://github.com/user-attachments/assets/a266f634-4532-48b3-8e3a-19988497b69b)
![image](https://github.com/user-attachments/assets/d9f5df03-2b5e-4ac8-8473-0a6f78b9891f)
![image](https://github.com/user-attachments/assets/8e1afd42-a922-404f-b1b9-c8efaab1bf11)
![image](https://github.com/user-attachments/assets/f7b79bb0-3058-48ce-bfe5-01e3c00d4613)
![image](https://github.com/user-attachments/assets/e525f0c3-d643-478e-9d40-b25b1f1bf024)
![image](https://github.com/user-attachments/assets/50568622-322f-406d-968f-ca38d5c1be97)
![image](https://github.com/user-attachments/assets/6d9b3f7c-226d-4cf0-9e16-781f99c2f69d)
![image](https://github.com/user-attachments/assets/7fab73fc-e874-4c8b-b5aa-06f424fd8353)

**Comment by MrClue** [comment]
There was a game update, the memory patterns are changed and needs updating. 
If you look into MemoryPattern.h you will see a list of Structs each containing patterns that needs to be updated.

**Comment by starnotes-xj** [comment]
> 有游戏更新，内存模式发生了变化，需要更新。如果你查看 MemoryPattern.h，你将看到一个结构列表，每个结构都包含需要更新的模式。

So, may I ask how I can solve this problem?

**Comment by starnotes-xj** [comment]
I have learned a little bit about cheat engine, but I have forgotten. What should I do if I change it? Can you solve this problem? Or update Osiris

> > > 有游戏更新，内存模式发生了变化，需要更新。如果你查看 MemoryPattern.h，你将看到一个结构列表，每个结构都包含需要更新的模式。
> > 
> > 
> > 那么，请问我该如何解决这个问题呢？
> 
> 我认为您必须使用作弊引擎或其他工具扫描签名。通常 unknowncheats 上的 ppl 会在更新后发布更新的签名，这就是我通常看起来的地方:D

**Comment by starnotes-xj** [comment]
> > > 有游戏更新，内存模式发生了变化，需要更新。如果你查看 MemoryPattern.h，你将看到一个结构列表，每个结构都包含需要更新的模式。
> > 
> > 
> > 那么，请问我该如何解决这个问题呢？
> 
> 我认为您必须使用作弊引擎或其他工具扫描签名。通常 unknowncheats 上的 ppl 会在更新后发布更新的签名，这就是我通常看起来的地方:D

I have learned a little bit about cheat engine, but I have forgotten. What should I do? Can you solve this problem? Or update Osiris

**Comment by sjv-afk1** [comment]
> > > > 有游戏更新，内存模式发生了变化，需要更新。如果你查看 MemoryPattern.h，你将看到一个结构列表，每个结构都包含需要更新的模式。
> > > 
> > > 
> > > 那么，请问我该如何解决这个问题呢？
> > 
> > 
> > 我认为您必须使用作弊引擎或其他工具扫描签名。通常 unknowncheats 上的 ppl 会在更新后发布更新的签名，这就是我通常看起来的地方:D
> 
> I have learned a little bit about cheat engine, but I have forgotten. What should I do? Can you solve this problem? Or update Osiris

Did you find a solution?

**Comment by danielkrupinski** [comment]
Fixed
