### ISSUE TITLE
ColorUtils.h Issue? 

### ISSUE THREAD

**Issue by xrt1** [danielkrupinski/Osiris#4369]
When trying to build, this error pops up

![image](https://github.com/user-attachments/assets/bc73f88c-45e9-401a-bd4c-6fc05ecc5548)

**Comment by danielkrupinski** [comment]
[Update your Visual Studio](https://learn.microsoft.com/en-us/visualstudio/install/update-visual-studio?view=vs-2022#use-the-visual-studio-installer-1)

**Comment by xrt1** [comment]
Thank you.
