### ISSUE TITLE
[Suggestion] translate

### ISSUE THREAD

**Issue by jdb-jdb** [danielkrupinski/Osiris#437]
A translator that works in chat. It will auto translate messages in chat not in your language to your language. You can also type a command like @fr... Which will translate your message into the language eg French. This is a good feature given a large player base of the game do not speak English. There is some code that was implemented at [Pastebin](https://pastebin.com/sUcpup5B)  usage of this feature can be seen in this [Video](https://www.youtube.com/watch?v=H05OheiZ01Q)

I tried to implement this myself but had problems with the protobuff api as I don't know cpp to well and couldn't fix the problems

**Comment by tirziz** [comment]
Could be a nice feature

**Comment by Bywnb** [comment]
You should know that automatic translation does not convey the true meaning. Many languages have native characteristics.

**Comment by jdb-jdb** [comment]
Of course, however regardless of actual linguistics, it can translate with some decent accuracy languages and the general meaning can usually be understood which is my reasoning behind using that phrase. It is the closest to universal chat where everyone understand each other. 朋友

-------- Original Message --------

**Comment by Shaxzy** [comment]
Oh yeah I have this in a different cheat I use. It is helpful indeed to understand those polish people but I don't think it's useful in osiris yet if I am going to be honest. There are many features I would like to see be added before this. I don't think a translator should be high priority.

**Comment by LRW1** [comment]
Translator shouldn't be a priority. I don't think it's going to be accurate enough to translate thousands of Russian lines every day.

**Comment by jdb-jdb** [comment]
If you use an api then some other website does the translating probably using ai which the user doesn't care about, the translator just queries the api

-------- Original Message --------
