### ISSUE TITLE
Cant inject into cs:go

### ISSUE THREAD

**Issue by WadamkaLmao** [danielkrupinski/Osiris#4371]
compiled osiris csgo end of life, injecting does nothing. Injected with process hacker

**Comment by WadamkaLmao** [comment]
tried another injector, error seems to be with the build. Trying to rebuild it

**Comment by WadamkaLmao** [comment]
didnt work, sadly

**Comment by WadamkaLmao** [comment]
seems to be a problem with all csgo cheats, just cant inject for some reason

**Comment by WadamkaLmao** [comment]
Tried a few injectors, none worked. Tried rebuilding and using another version, didnt work
One other cheat worked, but didnt have an inventory changer

**Comment by WadamkaLmao** [comment]
apparently the patterns in Memory.h are wrong. Anyone know the updated patterns?

**Comment by zerodev-exe** [comment]
It's not going to work... Because it's a new game now
