### ISSUE TITLE
Update listLeaves pattern

### ISSUE THREAD

**Issue by Kron1Q** [danielkrupinski/Osiris#438]
Siemanko Danielek, zaktualizuj memory.listLeaves w twoim pHeke. Zrobiłbym ci pull request z nowym findpatternem ale jestem copy pasterem i nie potrafię więc bym po prostu tak jak na uc wkleił 0x14244489 ale jeszcze bym zniszczył harmonię w tym pięknym training software.

 89 44 24 14 ( 0x14244489 )

Tak to wygląda teraz; https://i.imgur.com/sdKTjhG.jpg
A jak poprawisz to jest igła; https://i.imgur.com/KkPtCrI.jpg

Pozdrawiam mordko, fartem <3 

tl;dr english
update listLeaves pattern.

**Comment by l0ccy** [comment]
now on english pls ?!?!

**Comment by danielkrupinski** [comment]
The pattern is correct and does essentially the same as yours.
