### ISSUE TITLE
CS2 Linux won't inject

### ISSUE THREAD

**Issue by yourmom-jpeg** [danielkrupinski/Osiris#4383]
Hey y'all,

I built the .so file as directed but when I inject with gdb nothing happens. No terminal output is shown when the command is executed. I'm confident I'm doing something wrong but I don't know what it is.

**Comment by zerodev-exe** [comment]
You're not doing anything wrong. You should see a new icon in the in-game taskbar, just like in the Screenshot
![SS](https://github.com/user-attachments/assets/1b8de993-14a7-4f0e-8a3c-0152a971aae5)

**Comment by yourmom-jpeg** [comment]
Well I thought that it would show the usual cheat menu from the CSGO days.
Thanks lol
