### ISSUE TITLE
CUtlRBTree overflow is not completely solved

### ISSUE THREAD

**Issue by Bywnb** [danielkrupinski/Osiris#439]
Even if I turn every function off, I still get this message box in the game.

**Comment by danielkrupinski** [comment]
Show memory usage (in Task Manager) of csgo.exe at the time of error.

**Comment by Shiv3RPolak** [comment]
try to create new config, old configs made me crash, that was a problem.

**Comment by Bywnb** [comment]
when you crash,can you see a messagebox CUtlRBTree overflow?

**Comment by Bywnb** [comment]
@danielkrupinski  hello,daniel.As Shiv3RPolak says, old configs also made crash.When i create new config,this problem solved.
