### ISSUE TITLE
[SUGGESTIONS & FIXES] New features and somes fixes.

### ISSUE THREAD

**Issue by rosesware** [danielkrupinski/Osiris#442]
### **First of all, thanks.**
**Sorry if my bad English hurts your heart.**

****

**Some new features I thought relevant:**
- **[[Aim FOV Circle](https://prnt.sc/osu183)]** (a circle around the crosshairs depending on the aimbot's FOV you put); ❌ 
- **[[Viewmodel FOV customization](https://i.imgur.com/lApqnii.jpg)]** (added X, Y and Z and roll angles); ❌ 
- **[Better Anti Aim]** (I mean a functional legit AA); ❌  
- **[Profile changer]** (you can change your CS:GO rank, your commends, etc...); ❌
- **[Inventory changer]** (you can change your CS:GO inventory adding knifes, gloves, etc...); ❌ 
- **[Overwatch name revealer]** (shows name and profile of _"The Suspect"_); ✔️
- **[BlockBot]** (gives block to the nearest person); ❌
- **[Custom Hit Sound]** (_.wav_ file in a certain folder, being the new hit sound); ✔️
- **[Grenade Predicition]** (show the grenades trajectory); ✔️
- **[Bypass]** (add _sv_pure_ bypass and enable hidden cvar); ❌
- **[Run Boost helper]** (using BlockBot and Auto Strafe helps on run boosts). ❌

**_❌- Not added yet | ✔️- already added_**

**Some improves I thought relevant:**
- **[Backtrack]** (just add all-ticks); ✔️
- **[No Spread]** (I played on a surf server and when I was shooting I couldn't move); ✔️
- **[Cheat unhook]** (Some functions when cheat is unhooked are not disabled); ✔️

**_❌- Not improved yet | ✔️- already improved_**

****

**Things that I personally think should be added:**
- **[New type of Menu]** (A new menu, unique, I think you should invest on it @danielkrupinski); ✔️
- **[Menu customize colors]** (Fully customized color Menu); ✔️
- **[Watermark]** (Osiris need a better watermark). ✔️

**_❌- Not added yet | ✔️- already added_**

****

### THANK YOU IF YOU READ IT HERE AND SPECIAL THANK'S FOR @danielkrupinski !
Comment what you think, I will be giving update to this Issue.
If you find something to add as a new fix or feature, comment out.

**Comment by tirziz** [comment]
I think we should go Legit cheat since Osiris already very good at it. 
+ Maybe support more AC: SMAC, Faceit or League. 
+ bypass sv_pure and enable hidden cvar
+ support Lua script is good too

**Comment by Kron1Q** [comment]
Whats the point of lua scripts while u have source code?

**Comment by HowToMakeFaceitAB** [comment]
hey, is the actual crash fixed? (CUtIRBTree overflow!)
can you fix it if it's not?

**Comment by tirziz** [comment]
> Whats the point of lua scripts while u have source code?

in case u too lazy to do that, just import a script and Boom !

**Comment by rosesware** [comment]
> I think we should go Legit cheat since Osiris already very good at it.
> 
> * Maybe support more AC: SMAC, Faceit or League.
> * bypass sv_pure and enable hidden cvar
> * support Lua script is good too

**Thanks for your reply, but I don't think there will be any kind of anti cheat support because we have to put the undetectable cheat on us users. As for the moon scripts, _@Kron1Q_  already answered.**

**Comment by Evilhelder** [comment]
Run boost helper :(

**Comment by rosesware** [comment]
@Evilhelder **I will add to the list.**

**Comment by Evilhelder** [comment]
>  **I will add to the list.**

Thanks. :3
