### ISSUE TITLE
CUtIRBTree overflow

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#443]
for some reason, there are some memory leaks I'm confused as to how I can fix this?
welp I can't code so daniel has to do it

**Comment by HowToMakeFaceitAB** [comment]
It needs to be fixed quickly 
I think making a new config fixes this, not fully sure though.
I've seen some comments about it.

**Comment by HowToMakeFaceitAB** [comment]
I bet the Glow function is the problem. SO PLEASE fix it needs to be fixed within 4 - 6 days

**Comment by tirziz** [comment]
Have you tried reset your config or make a newom one. It may help for now

**Comment by HowToMakeFaceitAB** [comment]
Welp
I didn't and am planning to stop csgo until i afford a better oc because 58
- 60 fps is just not satisfying

**Comment by Bywnb** [comment]
@HowToMakeFaceitAB Show memory usage (in Task Manager) of csgo.exe at the time of error.
