### ISSUE TITLE
It won't let me build

### ISSUE THREAD

**Issue by tdaka** [danielkrupinski/Osiris#444]
Everyone time I try to build the solution I get an 29 errors can anyone help?

**Comment by tirziz** [comment]
what error

**Comment by tdaka** [comment]
I get 29 errors

**Comment by tdaka** [comment]
![Capture](https://user-images.githubusercontent.com/50555593/63113261-2466e700-bf60-11e9-92f7-25c7018f717c.PNG)

**Comment by tirziz** [comment]
+ Open the project properties
+ Into General --> SDK Version
+ pick any available version
