### ISSUE TITLE
SMOKE CHECK ON VISABLE CHAMS

### ISSUE THREAD

**Issue by thoma202411** [danielkrupinski/Osiris#445]
SMOKE CHECK ON VISABLE CHAMS
SMOKE CHECK ON VISABLE CHAMS
SMOKE CHECK ON VISABLE CHAMS
SMOKE CHECK ON VISABLE CHAMS
SMOKE CHECK ON VISABLE CHAMS
SMOKE CHECK ON VISABLE CHAMS
SMOKE CHECK ON VISABLE CHAMS

**Comment by tirziz** [comment]
What do you mean, its already work that way.

**Comment by 0xE232FE** [comment]
Yes, its working pretty well! The "ignore smoke" can help you.
