### ISSUE TITLE
SMOKE CHECK ON ESP AND GLOW

### ISSUE THREAD

**Issue by thomas0aotian** [danielkrupinski/Osiris#446]
PLZ ADD SMOKE CHECK ON VISABLE GLOW AND ESP CUZ I ALWAYS HAVE OT TOOGLED WHEN PLAYONG LEGIT AND WHEN PPL HIDE IN THE SMOKE WITH GLOW AND ESP I DONT THINK I CAN INDENTIFY IF THE R IN THE SMOKE R NOT PLZ FIX IT TKX DANIEL

**Comment by danielkrupinski** [comment]
Glow already has that.

**Comment by thoma202411** [comment]
i just tested out on the newest version. But is STILL not working
or some of it will hide inside the smoke
but u can still clearly see the glow of the players. i tested out about a
minute ago. tks 4 the reply tho

**Comment by thoma202411** [comment]
and i am using glow 2 or 3 since its the only two viable only glow
