### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Grazyyt** [danielkrupinski/Osiris#447]
Can you add those things ? :

Stream Proof
Backtrack all Ticks
Better Legit AA
Edge Jump
Custom models

**Comment by Bywnb** [comment]
backtrack all ticks is best!

**Comment by arkx3** [comment]
Custom models are rly useless idea

Bt on all ticks is actually good idea as well as edge jump

**Comment by tirziz** [comment]
Yes Custom model does useless... but ... But still its kidda cool
