### ISSUE TITLE
The aimbot

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#451]
The aimbot is a bit too obvious
You can't have good legit settings that help you while staying legit. 
Why not add some of theese features in
Welp here it comes.
Edge jump(on key or auto) 
Bezier curve fuction to the aimbot
Randomized smooth(Min - max) 
Target switch time : basically the time in MS for the aimbot to change targets like if the current target is not valid anymore (dead or not visible) it waits the  X amount of time chosen by Y to swap  to another visible target within the set fov range
Pretty much it if you add the above your cheat is guaranted to be amazing and legit
If you need help on how  randomized smooth works why not base yourself off of runescape bots like how they move the mouse from point X to Y
Finally Fix the hecking Rcs i have never, honestly never ever seen such a bad rcs
Wtf dude fix that rcs please
And also randomized smooth
Creates a number between MinX and MaxY
And that number changes each tick
If you add these features. Congratz you have beat iniuria

**Comment by HowToMakeFaceitAB** [comment]
I hope you add these features to the cheat guaranted to make it good
And why not an inventory changer(definitly useless but it comes to you)

**Comment by Z-aNT** [comment]
Bro , im using 2 Fov and 60 Smooth , i made level 21 on a non-prime account with this settings without getting VAC.

-Edge jump is a good feature , this should be added.
-Bezier curve its a new ideea here , sounds good too.
-RCS , i havent tested it yet...

**Comment by HowToMakeFaceitAB** [comment]
60 smooth? Does even do anything you are better off using 15-20

**Comment by HowToMakeFaceitAB** [comment]
They have recoil control which sucks
Why not add in recoil compesation

**Comment by tirziz** [comment]
Honesty I dont use Aimbot, trigger or backtrack on this cheat, just charm and skinchanger

**Comment by HowToMakeFaceitAB** [comment]
What the heck are you doing
Not a very good thing to do but guess anyone can do whateva they want

**Comment by HowToMakeFaceitAB** [comment]
I hope you read this daniel

**Comment by effex1337** [comment]
Bruh i use little 5 smoothing with 2-3 fov in automatic weapons and 1 smooth for snipers and pistols (in Prime and i have a 2019, 10 yo medal no bans).

**Comment by effex1337** [comment]
How legit can you be with different settings depends on your actual rank.

**Comment by HowToMakeFaceitAB** [comment]
That's not obvious
For legit cheating i use 10 Smooth with walls and chams
Ultra legit cheating i use 15 smooth and
Chams

**Comment by HowToMakeFaceitAB** [comment]
You want my recommendation
Use 3 fov with 10 Smooth 
156 wins no ban no cooldowns
I never got banned but got reported a lot which led to me having a bad trustfactor
When i use 15 smooth never been called out once always top frag good movrment good peeking ect...

**Comment by HowToMakeFaceitAB** [comment]
Level 31
156 wins
No cooldowns
Good trustfactor
Prime
Very good movement
Very good gamesense
Very good peeking
Very good positioning
The global elite
Lol i got to global in my 20 game
All that was 15 smooth the rest i had ti play a lot to aquire
Now my aim with no aimbot matches global
I sometimes use cheats and sometimes i don't (because i want to keep my legit aim consitent)

**Comment by mindofenzo** [comment]
How the hell... Anything over .6 fov w/ 3smooth doesn't feel natural

**Comment by HowToMakeFaceitAB** [comment]
It doed
