### ISSUE TITLE
[Discussion] Overwatch Ban

### ISSUE THREAD

**Issue by mindofenzo** [danielkrupinski/Osiris#453]
Has anyone else experienced getting overwatch banned recently? I was not being blatant, playing with .3 fov full body, .5 rcs, and radar. I havent been overwatched in 2 years and I have no clue what finally did it. 

My friend brought up a point - "If they are using machine learning to start OW banning, making the game f2p and letting people cheat is only making it progress faster."
I wonder if I could have been banned by the system, rather than an OW case. 🤔

**Comment by l0ccy** [comment]
yep me to rip steam lvl 230 acc :P

**Comment by tirziz** [comment]
I think its actually not OW ban, next 2 days it will change to VAC ban on your profile. This is because of some function that trigger vac on sercured servers, jot only when playing mm or wingman

**Comment by l0ccy** [comment]
its already a vac not ow ban anymore ^^

**Comment by Shaxzy** [comment]
I’ve not been banned on any accounts I have injected this cheat with. Did you even edit the source code or did you just compile and inject?

**Comment by wieisstimpee** [comment]
> I’ve not been banned on any accounts I have injected this cheat with. Did you even edit the source code or did you just compile and inject?

Same, I've never been banned using this cheat and I did edit the source.

**Comment by Bywnb** [comment]
> > I’ve not been banned on any accounts I have injected this cheat with. Did you even edit the source code or did you just compile and inject?
> 
> Same, I've never been banned using this cheat and I did edit the source.

+1，me too

**Comment by HowToMakeFaceitAB** [comment]
Never got banned lmao
Source not edited

**Comment by Evilhelder** [comment]
I am using a 1 month ago version of Osiris where I made a ProtectCode and it is still working without any problem ....

**Comment by ItsOnlyMeNL** [comment]
I have a few accounts that got banned but that was just due to being blatant and trolling around. Also have a account where i just this hack on that haven't got banned yet even to i do rage from time to time on there. 

But yes your friend is right, VACnet is learning from all this and making the game F2P just makes it  easier and the whole deep learning curve way faster.

I must say that the time it takes to get a ban is getting less and less, if you play blatant.

**Comment by noob-cat** [comment]
The signarute is probably detected because I'm getting banned recently way too fast and on some accounts I got banned while not even using any type of aim assist. Mostly overwatch bans turn into VAC bans. Unless Daniel does some major changes to the code to change the signature Memenet is going to keep banning osiris users.

**Comment by tirziz** [comment]
There is nothing to do with signature dude, I think you get ban because of some behave that vac detected as cheating or maybe some hook is detected.

**Comment by noob-cat** [comment]
> There is nothing to do with signature dude, I think you get ban because of some behave that vac detected as cheating or maybe some hook is detected.

VAC check signature lmfao how can you say it's not signature

**Comment by wieisstimpee** [comment]
More people would be banned if it’s signature. Also it would be instant

**Comment by noob-cat** [comment]
VAC doesn't do anything than that lmfao thats why VAC is a joke. Then thats not the problem

**Comment by tirziz** [comment]
Signature can be easy change, some time I got ban even not playing mm or wingman, I'm wondering too

**Comment by wieisstimpee** [comment]
> Signature can be easy change, I dont think anyone care about it anymore, On the other hand, some time I got ban even not playing mm or wingman, I'm wondering too. First its game ban, then 2 day latter it become vac ban

I honestly do not understand how other including me arent banned then if you guys get banned that quick

**Comment by tirziz** [comment]
I do remember one of my account, I just play on community server with obv aimbot and everything on. After few day I got ban. 
Other account only charm and mm 2 months and no ban
