### ISSUE TITLE
what is "Recoil based fov for backtrack"

### ISSUE THREAD

**Issue by Bywnb** [danielkrupinski/Osiris#457]
Sorry, I tried many times, but I didn't find it any different from before.
Could you explain it to me, plz.

**Comment by danielkrupinski** [comment]
It uses recoil pattern for selecting nearest backtrack tick.

**Comment by Bywnb** [comment]
> It uses recoil pattern for selecting nearest backtrack tick.

You mean  backtrack tick based recoil?

**Comment by danielkrupinski** [comment]
See 9372c6046440a5973a7ae606203052b91387384a
