### ISSUE TITLE
I need legit settings

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#459]
Anyone willing to send me a legit config
It has to be legit so send it to
Saitama#7564
Or make a download here
And what is the Folder for Osiris configs?

**Comment by tirziz** [comment]
documents/osiris

**Comment by HowToMakeFaceitAB** [comment]
Can you share a legir config with me?

**Comment by Grazyyt** [comment]
I can

**Comment by DokanBoy** [comment]
I need a good config too. download here, it will be useful for everyone

**Comment by Grazyyt** [comment]
Here are two Legit Configs check them out


Legit Triggerbot 
https://anonfile.com/d077x836na/visiblechams

-Aimbot Off
-Triggerbot On, Scoped Only,250ms Shot delay
-Backtrack On 200ms
-Glow On weapon Glow
-Visuals PostProcessing, no visual recoil, no blur, FOV 31
-SkinChanger some Skins
-ESP On
-Misc Sniper Crosshair, Auto Accept, Spectator List, Fast Plant, Bombtimer, Bunnehopp OFF

Visible Chams
https://anonfile.com/d077x836na/visiblechams

-Aimbot Off
-Triggerbot Off
-Backtrack On 200ms
-Glow On Weapon Glow
-Visuals PostProcessing, no visual recoil, no blur, Wireframe Smoke, FOV 31, Flash reduction 40%
-SkinChanger some Skins
-ESP Off
-Misc Sniper Crosshair, Auto Accept, Spectator List, Fast Plant, Bombtimer, Bunnyhop ON

**Comment by HowToMakeFaceitAB** [comment]
Okk thanks imma just add the aimbot and test them out

**Comment by Grazyyt** [comment]
> Okk thanks imma just add the aimbot and test them out

Its good to only use triggerbot because if you use aimbot + rcs you might get your account permanently untrusted

Trust me I got my account permanently untrusted two times.
If you use it dont rage okay, hide it  ;)

**Comment by HowToMakeFaceitAB** [comment]
Lmao i use legit aimbot settings //2 fov and 15 smooth full rcs
Never been vaced

**Comment by HowToMakeFaceitAB** [comment]
Never been untrusted

**Comment by wieisstimpee** [comment]
> > Okk thanks imma just add the aimbot and test them out
> 
> Its good to only use triggerbot because if you use aimbot + rcs you might get your account permanently untrusted
> 
> Trust me I got my account permanently untrusted two times.
> If you use it dont rage okay, hide it ;)

?? i use RCS full and 1.76FOV with 12smooth never been called out nor untrusted..

**Comment by HowToMakeFaceitAB** [comment]
?

**Comment by HowToMakeFaceitAB** [comment]
Lmao

**Comment by HowToMakeFaceitAB** [comment]
My aimbot settings
Ak47: 3 fov 10 smooth
M4A4: 3 fov 15 smooth
Pistol (all exept deagle) : 1.2 fov 6 smooth
Deagle: 0.9 fov 1 smooth
Awp: 1 fov 1 smooth
Scout: 0.7 fov 1 smooth

**Comment by Grazyyt** [comment]
> My aimbot settings
> Ak47: 3 fov 10 smooth
> M4A4: 3 fov 15 smooth
> Pistol (all exept deagle) : 1.2 fov 6 smooth
> Deagle: 0.9 fov 1 smooth
> Awp: 1 fov 1 smooth
> Scout: 0.7 fov 1 smooth

Are these Safe ?

**Comment by Mufinekkk** [comment]
Yessss

**Comment by HowToMakeFaceitAB** [comment]
Set hitbox to nearest for all of them

**Comment by HowToMakeFaceitAB** [comment]
These are the settings

**Comment by HowToMakeFaceitAB** [comment]
Very good config for legit hacking use it properly

**Comment by HowToMakeFaceitAB** [comment]
Heya i just woke uo

**Comment by HowToMakeFaceitAB** [comment]
Imma hop on my pc

**Comment by HowToMakeFaceitAB** [comment]
https://anonfile.com/p9w7283an5/Legit

**Comment by HowToMakeFaceitAB** [comment]
Good stuff
