### ISSUE TITLE
Release dll

### ISSUE THREAD

**Issue by Hongarc** [danielkrupinski/Osiris#46]
Can you push release version?
With push release of GitHub or push it to your code(not recommend but it can quick update release if you don't have time to push it).
Thank you.

**Comment by Shaxzy** [comment]
Why not just compile it yourself?

**Comment by Hongarc** [comment]
> Why not just compile it yourself?

Yes, but somebody doesn't have VS to compile `dll`

**Comment by Shaxzy** [comment]
Ah, okay.

**Comment by danielkrupinski** [comment]
Sorry, I won't release binaries any time soon.
