### ISSUE TITLE
[Suggestion] some binds

### ISSUE THREAD

**Issue by ccsimplyspolit** [danielkrupinski/Osiris#465]
Binds to most features for on\off. esp on key for example
+ binds for much more functions, esp, chams xyz, etc.
+ binds modes: when key down[hold] when key is up -> working, when key is down - not working [always] toggle [switch]
+ add magnet func to trigger (trigger works with aimbot in fov)
+ **psilent issue**

psilent works with aimbot fov, need fov for psilent, need work psilent on 1\hitchanse(integrate)\ bullet \ works  psilent on number (first bullet when he will be work [3 for example]) bullet, don't work after (after 4 bullet psilent stop works) bullet.

+ add lighting to chams
+ **WASD** Autostrafe

**Comment by effex1337** [comment]
> psilent works with aimbot fov, need fov for psilent, need work psilent on 1\hitchanse(integrate)\ bullet \ works psilent on number (first bullet when he will be work [3 for example]) bullet, don't work after (after 4 bullet psilent stop works) bullet.u

Tf do you mean. 
pSilent is patched long ago you can still use pSilent but with 0.00007 fov.
