### ISSUE TITLE
Feature: Quick Reload

### ISSUE THREAD

**Issue by hyperxpro** [danielkrupinski/Osiris#467]
Add Feature To Quickly Reload Gun

**Comment by danielkrupinski** [comment]
How would it work?

**Comment by hyperxpro** [comment]
> How would it work?

When we'll hit reload, instead of going for full animation which takes 3 seconds or so, the cheat will stop reloading once magazine gets full and will switch back to another weapon and again switch back to the main weapon which we were reloading. This will take much less time and in many situation, it'll help a lot.

**Comment by tirziz** [comment]
I think he mean some gun, for example AK47 when you reload there is a bit of uneedcesary animation and sound, if you quickly change to knife and come back its faster and make less sound

**Comment by hyperxpro** [comment]
> I think he mean some gun, for example AK47 when you reload there is a bit of uneedcesary animation and sound, if you quickly change to knife and come back its faster and make less sound

That's correct!

**Comment by tirziz** [comment]
Not every weapon need that, but might be useful I guess

**Comment by hyperxpro** [comment]
> Not every weapon need that, but might be useful I guess

I have tested this. Not every weapon will take advantage of this but still, it makes a little difference at least.

**Comment by aqsatti** [comment]
the last time i searched about quick reload i found that the game forces you to wait the same amount of time before firing.It may be outdated but check it,
(link to video, just remove space after dot)
https://www.youtube. com/watch?v=Nz8S0t2Ep30

**Comment by hyperxpro** [comment]
> the last time i searched about quick reload i found that the game forces you to wait the same amount of time before firing.It may be outdated but check it,
> (link to video, just remove space after dot)
> https://www.youtube. com/watch?v=Nz8S0t2Ep30

Not all weapon will take benefit of Quick Reload. And Quick Reload performed via Computer and Human will have a huge impact on overall reload time. And I guess, this is why we use cheats? Haha

**Comment by effex1337** [comment]
Sounds interesting

**Comment by danielkrupinski** [comment]
I've done test with `nextAttack` property of local player and it looks like the 'quick` reload is indeed faster by ~0.2s.

**Comment by hyperxpro** [comment]
> I've done test with `nextAttack` property of local player and it looks like the 'quick` reload is indeed faster by ~0.2s.

Let's implement it now? I'd say make it as an option in misc. Making It work on all weapon rather than toggling it for every weapon.

**Comment by hyperxpro** [comment]
Sorry, Accidently closed :-| Reopening...

**Comment by Evilhelder** [comment]
Please @danielkrupinski  Add Run Boost Helper ou Blockbot.... ;-; I beg you...

**Comment by hyperxpro** [comment]
> Please @danielkrupinski Add Run Boost Helper ou Blockbot.... ;-; I beg you...

I don't think this is the right thread for you.

**Comment by Evilhelder** [comment]
> I don't think this is the right thread for you.

Sorry....

**Comment by danielkrupinski** [comment]
Added.
