### ISSUE TITLE
[Suggestion] Funny Features: SlowWalk, RunBoost helper, BlockBot, Troll Vote and  Player List(For name Stealer and Vote)

### ISSUE THREAD

**Issue by hvhdark** [danielkrupinski/Osiris#469]
What to add these functions? 

SlowWalk: 
[SlowWAlk code paste.txt](https://github.com/danielkrupinski/Osiris/files/3522295/SlowWAlk.code.paste.txt)

RunBoost helper: I dont have code source... :(

BlockBot: 
[Paste old code Blockbot.txt](https://github.com/danielkrupinski/Osiris/files/3522314/Paste.old.code.Blockbot.txt)

Troll Vote: https://www.unknowncheats.me/forum/counterstrike-global-offensive/332665-troll-kick-lines.html

Player List: https://www.unknowncheats.me/forum/counterstrike-global-offensive/94965-player-name-entity-list-position-issue.html

There's this videos showing a lot of funny things to do with these functions:

https://youtu.be/D0ZujGF3e-M

https://www.youtube.com/watch?v=mjoQpSmSZBk

(P.S.: Most of these functions need or are easier to create using Lua, but create a "Lua Manager Script" is a puzzle ... :( At least for me, I'm very bad at programming.)

**Comment by Evilhelder** [comment]
RRRRRRRRRUNBOOOST PLEASEEEEEE YEEEEEEEEEEEEEEEEEEEEEEEEEES

**Comment by woah1337** [comment]
can i have the definiton for game::math.calculate_angle()?

**Comment by hydemods** [comment]
so you basically want them to recreate flowhooks. lol.

**Comment by Evilhelder** [comment]
> 
> 
> so you basically want them to recreate flowhooks. lol.

It really looks like this, but it would be awesome XD
