### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ogosirisfan** [danielkrupinski/Osiris#470]
constexpr void NormalWalk(UserCmd* cmd) noexcept
{

	cmd->buttons |= UserCmd::IN_MOVERIGHT;
	cmd->buttons |= UserCmd::IN_MOVELEFT;
	cmd->buttons |= UserCmd::IN_FORWARD;
	cmd->buttons |= UserCmd::IN_BACK;

	if (cmd->forwardmove > 0.0f);
	cmd->buttons |= UserCmd::IN_FORWARD;
	else if (cmd->forwardmove < 0.0f)
	cmd->buttons |= UserCmd::IN_BACK;
	if (cmd->sidemove > 0.0f);

	{
		cmd->buttons |= UserCmd::IN_MOVERIGHT;
	}
	else if (cmd->sidemove < 0.0f)
	{
		cmd->buttons |= UserCmd::IN_MOVELEFT;
	}
}

hi i want to add this code but i don't understand else if
help?

**Comment by effex1337** [comment]
It's just basic English
Else if means :
else plus there's a condition

**Comment by danielkrupinski** [comment]
This code makes no sense + it has syntax errors.

**Comment by tirziz** [comment]
What is this function
