### ISSUE TITLE
Anti-Aim Monitor

### ISSUE THREAD

**Issue by ogosirisfan** [danielkrupinski/Osiris#472]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/302732-anti-aim-monitor.html

**Comment by rosesware** [comment]
Why? If you see fakes angles without this.

**Comment by Shiv3RPolak** [comment]
you don't see fakeangles in osiris. :)

**Comment by ccsimplyspolit** [comment]
how change switch angle of anti-aim?

**Comment by effex1337** [comment]
Nice English
