### ISSUE TITLE
[Question] question from a noobie

### ISSUE THREAD

**Issue by furioushell98** [danielkrupinski/Osiris#474]
I really want to use this cheat ( i used an Osiris paste from MPGH on Alt and it was awesome) but i wanna do that on my main account, but i'm afraid about it being detected. I removed unnecessary features and filled the source code with junkcode and it worked fine, UD. But What other procedures should i do to keep it UD forever? (Changing the junk code every few days for example?)

**Comment by HowToMakeFaceitAB** [comment]
Nope you should change junjcode each 1.5 weeks(10 days)

**Comment by jdb-jdb** [comment]
make sure your injector has some form of obfuscation . Eg junk code or signature change
