### ISSUE TITLE
FPS problem

### ISSUE THREAD

**Issue by JustinLatiao** [danielkrupinski/Osiris#476]
I compiled the latest project, and when I hit Tab after injection, my FPS was suddenly low. This only happens when the TAB key is pressed

**Comment by wieisstimpee** [comment]
then dont press tab lol /s

**Comment by effex1337** [comment]
Not a cheat issue it happens to me as well and also to a buddy of mine who literally never injected any cheat in his laptop.

**Comment by Mufinekkk** [comment]
Off Rank Reveal
