### ISSUE TITLE
[Bug] Item Table Misc out window

### ISSUE THREAD

**Issue by Evilhelder** [danielkrupinski/Osiris#478]
The misc tab items are leaving the screen...

![image](https://user-images.githubusercontent.com/33970481/63554857-34109d80-c515-11e9-8616-df4f18e90b30.png)

**Comment by effex1337** [comment]
That happens because you use a low resolution.
Simplest fix use higher resolution but if you can't then reduce font size.
Search for "arial" in GUI.cpp and reduce the text size by 2 or as you desire.

**Comment by effex1337** [comment]
Those aren't the only easy to fix it but those are the easiest ones.

**Comment by Evilhelder** [comment]
> 
> 
> Those aren't the only easy to fix it but those are the easiest ones.

Thanks so much.... My monitor has a resolution of 720p ... sucks ... I need to change it.
