### ISSUE TITLE
Moving crosshair with triggerbot

### ISSUE THREAD

**Issue by furioushell98** [danielkrupinski/Osiris#479]
Hello, i tried other cheats and well, in all of them you can use Triggerbot by moving the zoomed crosshair while holdingthe trigger button and not just standing still like in Osiris. Could you add this feature?

One more thing, when i turn on anti aim, movement keys gets fucked ( like, buttons move in other directions) what should i do for this?

**Comment by HowToMakeFaceitAB** [comment]
Go to misc section, enable fix movement
You can hold the trigger while moving wdym

**Comment by HowToMakeFaceitAB** [comment]
Go to misc section, enable fix movement
You can hold the trigger while moving wdym

**Comment by furioushell98** [comment]
@HowToMakeFaceitAB i see. I didn't know about that. There are a lot of features that i don't understand. Just like Anti-aim's weird movement or chams working like glow instead of showing visible-only players

**Comment by HowToMakeFaceitAB** [comment]
You can do that
Chams mode is all i guess thats why
Set it to visible

**Comment by furioushell98** [comment]
I didn't see a visible only option yesterday but i'll look more. Also there's CUtIRBTree overflow crash happening every while on MM

**Comment by HowToMakeFaceitAB** [comment]
Delete your config make a new one
Like cheat config, delete it and then make a new one
