### ISSUE TITLE
VAC Errors Only In Deathmatch and Casual

### ISSUE THREAD

**Issue by hyperxpro** [danielkrupinski/Osiris#481]
Every time I play Deathmatch and Casual and have plenty of kills (usually 30-40), I get VAC Error then I revalidate file integrity and 1 file always gets corrupted. How and Why? How to fix? I'm fed up. -_-

Edit 1: Happens with and without Skin Changer.

![VAC_ERROR](https://user-images.githubusercontent.com/24762260/63600591-756e7f00-c5e1-11e9-8648-2ea3affcbd3f.png)
![STEAM](https://user-images.githubusercontent.com/24762260/63600655-96cf6b00-c5e1-11e9-98cb-e772bf79bbdf.png)

**Comment by Shiv3RPolak** [comment]
FOV lower than 30 and don't use antiaim

**Comment by hyperxpro** [comment]
> FOV lower than 30 and don't use antiaim

Not using Anti-Aim and FOV is the default (unchanged).

**Comment by Floraly** [comment]
Did you check your hard disk or ssd?
Sometimes it's an disk error which cause an VAC Kick.

**Comment by mdilai** [comment]
> > FOV lower than 30 and don't use antiaim
> 
> Not using Anti-Aim and FOV is the default (unchanged).

I think Shiv3RPolak talking Aimbot Weapon FOV (which you definitely has not set to "default" 0, which == disabled) and not Visual FOV.

There is option "Max angle delta" which divide aimbot into steps of set radius per tick (put ~25 for avoiding VAC errors). Unfortunately, this option works only if Auto Shoot is enabled (and Auto Shoot works only if "Max angle delta" > 0).

 So you have only two solutions:
1) Use aimbot FOV 255, Max angle delta 25-30 and Auto Shoot On (for any nearest enemy, but can delays up to (255/30) / (1/64) = 544ms before shoot as theoretical maximum for the most distant target)
2) Use aimbot FOV 25-30 and manually aim and shoot chosen target withing this radius (currently cheat don't draw FOV radius indication but FOV 30 is about half of viewscreen, so enough just seeing enemy somewhere in front of you)

The first variant is preferable for instant raging everyone on Casual / DM / GunGame, second one - for HvH in MM / Wingman when you prefer to shoot enemy cheater over random guy in side of you.


About files integrity and corrupted file - this is a common Steam bug and absolutely not related to cheats. You will get this error even if play few games without any cheats, exit the game without any errors and run "revalidate file integrity" again. You can freely ignore it. Next time getting VAC error just reboot your PC - this will reset VAC error without wasting time on checking 20GB of game files.

**Comment by hyperxpro** [comment]
> > > FOV lower than 30 and don't use antiaim
> > 
> > 
> > Not using Anti-Aim and FOV is the default (unchanged).
> 
> I think Shiv3RPolak talking Aimbot Weapon FOV (which you definitely has not set to "default" 0, which == disabled) and not Visual FOV.
> 
> There is option "Max angle delta" which divide aimbot into steps of set radius per tick (put ~25 for avoiding VAC errors). Unfortunately, this option works only if Auto Shoot is enabled (and Auto Shoot works only if "Max angle delta" > 0).
> 
>  So you have only two solutions:
> 
> 1. Use aimbot FOV 255, Max angle delta 25-30 and Auto Shoot On (for any nearest enemy, but can delays up to (255/30) / (1/64) = 544ms before shoot as theoretical maximum for the most distant target)
> 2. Use aimbot FOV 25-30 and manually aim and shoot chosen target withing this radius (currently cheat don't draw FOV radius indication but FOV 30 is about half of viewscreen, so enough just seeing enemy somewhere in front of you)
> 
> The first variant is preferable for instant raging everyone on Casual / DM / GunGame, second one - for HvH in MM / Wingman when you prefer to shoot enemy cheater over random guy in side of you.
> 
> About files integrity and corrupted file - this is a common Steam bug and absolutely not related to cheats. You will get this error even if play few games without any cheats, exit the game without any errors and run "revalidate file integrity" again. You can freely ignore it. Next time getting VAC error just reboot your PC - this will reset VAC error without wasting time on checking 20GB of game files.

Tried both of your solutions. Still getting Error. Should I try changing Injector? Which Injector do you use?

**Comment by Floraly** [comment]
Use one of Daniels injectors would be fine. He have one which removes the PE Header which is quiet nice because it produces an executable instead of dll its very handy.

**Comment by hyperxpro** [comment]
> Use one of Daniels injectors would be fine. He have one which removes the PE Header which is quiet nice because it produces an executable instead of dll its very handy.

Lemme give it a chance and I will let you know.

**Comment by hyperxpro** [comment]
> Use one of Daniels injectors would be fine. He have one which removes the PE Header which is quiet nice because it produces an executable instead of dll its very handy.

I am still getting errors but way less than earlier. Earlier, every 2/3 Deathmatch or Casual used to give VAC error and now it's 1/5 Deathmatch or Casual.

Looks good though.
