### ISSUE TITLE
do i have to recompile with new signature / junk code everyday?

### ISSUE THREAD

**Issue by ccstoragedrivez** [danielkrupinski/Osiris#483]
on mpgh, they release this hack everyday with different signature / junk code but if i do it myself with vmprotect, do i need to it everyday also to reduce chances of getting detected?

**Comment by 0xE232FE** [comment]
Dude no junk + no vmprotect will prevent you from VAC Ban if it gets detected. Do not use any release which is not from Github. It is a good warning for all using exe files and get compromized.
