### ISSUE TITLE
Clantag Changer doesnt work.

### ISSUE THREAD

**Issue by deprale** [danielkrupinski/Osiris#484]
whatever u set it on its always empty -_-'

**Comment by furioushell98** [comment]
Idk what ur talking about fam. It works, and with animation too

**Comment by deprale** [comment]
It doesnt for me, maybe its cuz i already have one from the game setttings? @furioushell98

**Comment by furioushell98** [comment]
Yes maybe disable the one from the game and try again cuz it works

**Comment by deprale** [comment]
i dunno i just recompiled again, still doesnt work, i found a "workaround" if i literally just hit animated clantag real fast and disable it straight away i will have my clantag on but if i dont do that then its empty lol and im not that retarded to not know how to tick a box.

**Comment by rosesware** [comment]
**You have to enable first and write the clan tag next.**
**And if you want to put animated clan tag do all I am saying and enable animated clan tag next.**
