### ISSUE TITLE
two max angle delta

### ISSUE THREAD

**Issue by Bywnb** [danielkrupinski/Osiris#486]
What's the difference of max angle delta between aimbot and misc?

**Comment by Bywnb** [comment]
@danielkrupinski

**Comment by Z-aNT** [comment]
First one from aimbot tab is for Auto-shot option
Second one from misc is for anti-aim
Just test them and see

**Comment by Bywnb** [comment]
> First one from aimbot tab is for Auto-shot option
> Second one from misc is for anti-aim
> Just test them and see
> Btw Daniel should rename them

Thank you for your answer. I see
