### ISSUE TITLE
what is "Between shots"

### ISSUE THREAD

**Issue by EJianZQ** [danielkrupinski/Osiris#488]
**hello, could u tell m what is "Between shots" in aimbot？ i test many times but failed**

**Comment by Bywnb** [comment]
@danielkrupinski

**Comment by tirziz** [comment]
I think it mean aimbot will stop between 2 shots

**Comment by deprale** [comment]
It has delay so it doesnt shoot as fast as possible to let the recoil cooldown.

**Comment by Finndramere** [comment]
On-Aims Between Shots. After a player is killed the aimbot continues to lock on to the next player.
Off-After a player is killed. If the next bullet is ready thats when the aimbot locks on. 
To see the difference set Silent aim to Off with lowest smoothing and auto shoot on.

**Comment by effex1337** [comment]
The way the article worked earlier without this is you have some time before bullets come out of the gun and it wouldn't Arun in that time now with between shot it will continue to lock when bullets are readying up aka when you have ammo but you can't shoot yet. 
@Bywnb @danielkrupinski Time to close this.
