### ISSUE TITLE
CLOSE [SOLVED]

### ISSUE THREAD

**Issue by deprale** [danielkrupinski/Osiris#489]
Tried to implement left hand on wielding knife but I failed after numerous attempts...

anyone who can tell me whats wrong?

```cpp
//Misc.cpp(Including some snippets so you know where I am at)
void Misc::leftKnife() noexcept
{
	if (config.misc.leftKnife) {

		static auto leftKnife = interfaces.cvar->findVar("cl_righthand");

		if (leftKnife->getInt()) return;

		const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
		const auto activeWeapon = localPlayer->getActiveWeapon();

		if (!activeWeapon || activeWeapon->getClientClass()->classId != ClassId::Knife)
			return;

		if (activeWeapon->getClientClass()->classId == ClassId::Knife && localPlayer->isAlive())
		{
			leftKnife->setValue("0");
		}
		else
		{
			leftKnife->setValue("1");
		}
	}
}
```

```cpp
//GUI.cpp (Included some snippet so u know where I am)
        ImGui::Checkbox("Name stealer", &config.misc.nameStealer);
        ImGui::Checkbox("Fast plant", &config.misc.fastPlant);
		ImGui::Checkbox("Left Knife", &config.misc.leftKnife);
        ImGui::Checkbox("Bomb timer", &config.misc.bombTimer);
        ImGui::Checkbox("Quick reload", &config.misc.quickReload);
        ImGui::Checkbox("Prepare revolver", &config.misc.prepareRevolver);
```

```cpp
//Config.cpp
        if (miscJson.isMember("Fast plant")) misc.fastPlant = miscJson["Fast plant"].asBool();
		if (miscJson.isMember("Left knife")) misc.leftKnife = miscJson["Left knife"].asBool();

//.. blablblabla

        miscJson["Name stealer"] = misc.nameStealer;
        miscJson["Fast plant"] = misc.fastPlant;
		miscJson["Left knife"] = misc.leftKnife;

```

```cpp
//Config.h
        bool nameStealer{ false };
        bool fastPlant{ false };
		bool leftKnife{ 0 };
        bool bombTimer{ false };
```

**Comment by effex1337** [comment]
Did you call it ?
In hooks.cpp

**Comment by deprale** [comment]
> Did you call it ?
> In hooks.cpp

Why would I need to call it, it's not a hook... I'm literally changing a cvar name? It's in the Misc Struct so I'd guess everything is already being called.

**Comment by effex1337** [comment]
Add Misc::leftKnife();
In Hooks.cpp line 110 and see the magic. 
If it didn't work then there's something wrong in your code.

**Comment by deprale** [comment]
> Add Misc::leftKnife();
> In Hooks.cpp line 110 and see the magic.
> If it didn't work then there's something wrong in your code.

I was looking at Hooks.h the whole time I'm so fucking dumb LMFAOO...

**Comment by effex1337** [comment]
@deprale 
`void Misc::swaphandonknife() noexcept {
	if (interfaces.engine->isInGame()) {
		const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
		if (localPlayer->isAlive()) {
			const auto activeWeapon = localPlayer->getActiveWeapon();
			auto swapknife = interfaces.cvar->findVar("cl_righthand");
			if (config.misc.knifeonleft)
			{
				if (activeWeapon->getClientClass()->classId == ClassId::Knife)
					swapknife->setValue(0);
				if (activeWeapon->getClientClass()->classId != ClassId::Knife)
					swapknife->setValue(1);
			}
		}
	}
}`

**Comment by effex1337** [comment]
if you cant make this work i cant help you as this is the exact code i'm using straight from my source.
@ijre  i agree `if (leftKnife->getInt()) return;` was useless there but it shouldn't impact the code.

**Comment by deprale** [comment]
>> i agree `if (leftKnife->getInt()) return;` was useless there but it shouldn't impact the code. ...

@ijre oh wow im dumb ill check that later tonight when im at home thanks I forgot I even had that in... I’m so dumb lol. It was a debug if and SEEMS LIKE I DIDNT DELETE IT COMPLETELY.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by deprale** [comment]
@ijre sorry for tagging you 
and @effex1337 
I've another small and last issue if you could try and give it a look at least.
It's related to a viewmodel x/y/z changer with slider.
For some reason my game crashes if I join a multiplayer game like instantly, if I remove everything in Misc.h Misc.cpp Config.h Config.cpp and just leave the null callbacks in the Hooks.cpp I can change the value of viewmodel x y z to whatever value I want without crashing whatsoever

Behold If I implement the feature with saving and in GUI ... CRASH INSTANTLY ON JOINING THE SERVER.
Also the configs look fucked up, for example I could have my settings saved under misc.leftKnife(); but they show up under spectatorlist for some reason? The values get saved but they can't be loaded for some reason??

```cpp
//Misc.h struct
namespace Misc {
	void inverseRagdollGravity() noexcept;
	void updateClanTag(bool = false) noexcept;
	void spectatorList() noexcept;
	void sniperCrosshair() noexcept;
	void recoilCrosshair() noexcept;
	void watermark() noexcept;
	void prepareRevolver(UserCmd*) noexcept;
	void fastPlant(UserCmd*) noexcept;
	void leftKnife() noexcept;
	void viewModel() noexcept;
	void drawBombTimer() noexcept;
	void stealNames() noexcept;
	void quickReload(UserCmd*) noexcept;
```

```cpp
//Misc.cpp function
void Misc::viewModel() noexcept
{
	if (config.misc.viewModel) {
		interfaces.cvar->findVar("viewmodel_offset_x")->setValue(config.misc.viewModel_x);
		interfaces.cvar->findVar("viewmodel_offset_y")->setValue(config.misc.viewModel_y);
		interfaces.cvar->findVar("viewmodel_offset_z")->setValue(config.misc.viewModel_z);
	}
}
```

```cpp
//GUI.cpp implementation
        ImGui::Checkbox("Fast plant", &config.misc.fastPlant);
		ImGui::Checkbox("Left knife", &config.misc.leftKnife);
		ImGui::Checkbox("ViewModel", &config.misc.viewModel);
		if (config.misc.viewModel) {
			ImGui::SliderFloat("ViewModel X", &config.misc.viewModel_x, -10, 30);
			ImGui::SliderFloat("ViewModel Y", &config.misc.viewModel_y, -10, 30);
			ImGui::SliderFloat("ViewModel Z", &config.misc.viewModel_z, -10, 30);
		}
```

```cpp
//Hooks.cpp under createMove (?) I tried putting it up in main Hooks() funct and it still worked but i dunno why i changed it here, saw someone mention it on UC.
	interfaces.cvar->findVar("viewmodel_offset_y")->onChangeCallbacks.size = 0;
	interfaces.cvar->findVar("viewmodel_offset_x")->onChangeCallbacks.size = 0;
	interfaces.cvar->findVar("viewmodel_offset_z")->onChangeCallbacks.size = 0;
```

```cpp
//Config.cpp
        if (miscJson.isMember("Fast plant")) misc.fastPlant = miscJson["Fast plant"].asBool();
		if (miscJson.isMember("Left knife")) misc.leftKnife = miscJson["Left knife"].asBool();
		if (miscJson.isMember("Viewmodel")) misc.viewModel = miscJson["Viewmodel"].asBool();
		if (miscJson.isMember("ViewModel x")) misc.viewModel_x = miscJson["Viewmodel x"].asFloat();
		if (miscJson.isMember("ViewModel y")) misc.viewModel_y = miscJson["Viewmodel y"].asFloat();
		if (miscJson.isMember("ViewModel z")) misc.viewModel_z = miscJson["Viewmodel z"].asFloat();
```

```cpp
//Config.cpp
        miscJson["Name stealer"] = misc.nameStealer;
        miscJson["Fast plant"] = misc.fastPlant;
		miscJson["Left knife"] = misc.leftKnife;
		miscJson["Viewmodel"] = misc.viewModel;
		miscJson["Viewmodel x"] = misc.viewModel_x;
		miscJson["Viewmodel y"] = misc.viewModel_y;
		miscJson["Viewmodel z"] = misc.viewModel_z;
```

```cpp
//Config.h
        bool nameStealer{ false };
        bool fastPlant{ false };
		bool leftKnife{ false };
		bool viewModel{ false };
		float viewModel_x{ 0 };
		float viewModel_y{ 0 };
		float viewModel_z{ 0 };
```

and this is how my config looks upon saving...
```
		"Left knife" : true,
		"Max angle delta" : 255.0,
		"Menu key" : 45,
		"Name stealer" : false,
		"Prepare revolver" : false,
		"Prepare revolver key" : 0,
		"Quick reload" : false,
		"Radar hack" : true,
		"Recoil crosshair" : false,
		"Reveal ranks" : true,
		"Sniper crosshair" : false,
		"Spectator list" : true,
		"Viewmodel" : true,
		"Viewmodel x" : 8.9860000610351563,
		"Viewmodel y" : -3.7679998874664307,
		"Viewmodel z" : 6.6669998168945313,
		"Watermark" : false
```
Which looks pretty stupid as I clearly put it under left knife? So the values get saved, albeit not correctly (for some reason?) but they cannot be loaded back because whatever the hell I did is fucked up and it loads it somewhere hwere it can't take these values hence the crash? I couldn't debug.

**Comment by effex1337** [comment]
I'll just create a pull request(maybe xd depends on my mood) I've been successful in it.

**Comment by effex1337** [comment]
And i literally gave my code for left hand knife it works just had it :man_shrugging:

**Comment by deprale** [comment]
I fixed it long ago this is about something else please read it xd

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by deprale** [comment]
All I had to do was to remove the useless check/return now I have another small issue with a viewmodel x y z uncapper/changer

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by deprale** [comment]
@effex1337  the problem is that I'm just plain crashing when I'm dead with left knife on...

**Comment by effex1337** [comment]
Lemme ask you something @deparle
Do you have a weapon when you're dead? 
If you get this you should be able to debug better.

**Comment by deprale** [comment]
> Lemme ask you something @deparle
> Do you have a weapon when you're dead?
> If you get this you should be able to debug better.

I fixed it, I was compiling an old version of my .dll using Debug preset instead of Release. Just a small bug.
Can you take a look at this, if im not bothering u ? https://github.com/danielkrupinski/Osiris/issues/497

**Comment by effex1337** [comment]
> void Visuals::custom_viewmodel() noexcept {
> 	static ConVar* view_x = interfaces.cvar->findVar("viewmodel_offset_x");
> 	static ConVar* view_y = interfaces.cvar->findVar("viewmodel_offset_y");
> 	static ConVar* view_z = interfaces.cvar->findVar("viewmodel_offset_z");
> 	static ConVar* bob = interfaces.cvar->findVar("cl_bobcycle");
> 	static ConVar* impacts = interfaces.cvar->findVar("sv_showimpacts");//showimpacts (lazy to make new void for this)
> 
> 	ConVar* sv_minspec = interfaces.cvar->findVar("sv_competitive_minspec");
> 	*(int*)((DWORD)& sv_minspec->onChangeCallbacks + 0xC) = 0;
> 	sv_minspec->setValue(0);
> 
> 	bob->setValue(0.98f);
> 	view_x->setValue(config.visuals.customviewmodel_x);
> 	view_y->setValue(config.visuals.customviewmodel_z);
> 	view_z->setValue(config.visuals.customviewmodel_y);
> 	impacts->setValue(config.misc.showimpacts);//showimpacts (lazy to make new void for this)
> }

**Comment by effex1337** [comment]
Hf

**Comment by deprale** [comment]
> Hf

@effex1337 
I have already this feature the problem is saving it in the config...
for example I have everything with custom_viewmodel() under leftknife() yeah?
In the config, my custom_viewmodel x y z appear somewhere under spectator list so it never gets to be loaded, just saved...

**Comment by effex1337** [comment]
ViewModel
viewModel

**Comment by effex1337** [comment]
It's case sensitive while loading and saving Config

**Comment by deprale** [comment]
omggggggg thank you so much <3 love u man!
I'm RETARDED! didnt know that lol

**Comment by effex1337** [comment]
:)

**Comment by deprale** [comment]
do u have discord?

**Comment by effex1337** [comment]
Yeah discord.io/effex

**Comment by ijre** [comment]
Hey, sorry for the super late comment, but it's worth letting you know since effex didn't say anything; the reason the viewmodel stuff doesn't save under left knife is because when it saves it organizes everything alphabetically

**Comment by effex1337** [comment]
No it doesnt need to be ordered correctly
It's just case sensitive and hes already fixed it.
