### ISSUE TITLE
aimbot with rcs is shaking

### ISSUE THREAD

**Issue by didisko33** [danielkrupinski/Osiris#49]
I recorded a GOTV demo with aimbot and rcs, and it's shaking so hard, can you please fix it? 
I wanna play MM, but it is so blatant.

[1demo.zip](https://github.com/danielkrupinski/Osiris/files/2872719/1demo.zip)

**Comment by JayneFrack** [comment]
#metoo

**Comment by danielkrupinski** [comment]
Should be fixed now.
