### ISSUE TITLE
[Injecotr issue] VAC Ban on two Accounts using Inflame injector

### ISSUE THREAD

**Issue by 0xE232FE** [danielkrupinski/Osiris#490]
Hello Everybody,

First it seems that the Cheat isn't detected still !!!

I checked the Injectors that Daniel shares on his Github. One of it seems to cause VAC Bans.

It's the Inflame injector, only Accounts which used it got VAC Banned.
https://github.com/danielkrupinski/Inflame

Check Banned Accounts:
https://steamcommunity.com/profiles/76561198973010109/
https://steamcommunity.com/profiles/76561198982927159/

Can someone else confirm issues with the Inflame injector or does someone use it?

**Comment by Shiv3RPolak** [comment]
why u write it here then?

**Comment by 0xE232FE** [comment]
Because it seems CS:GO related. I tested it for my Teamfortress Cheat and the Account isn't banned yet. Maybe someone experiencing same issues.

Just for your Info. After cheating close Steam and Kill Steam-Services. This restarts VAC!

**Comment by deprale** [comment]
those are throwaway accs probably just goin 2 hard and vacnet owns u

**Comment by 0xE232FE** [comment]
I was just testing the injectors, I did not even play. I was just connected to my Local Game Server which has VAC Security enabled. I was just AFK on my local Game Server, this doesn't cause a VAC Net or Overwatch Ban.

**Comment by danielkrupinski** [comment]
I can't help you with ban. Maybe I will update that injector soon.

**Comment by 0xE232FE** [comment]
@danielkrupinski no problem, I just was expecting someone else might use this injector and experience same. The Injector where you remove the PE Header is working very well without issues. I like the Xor encryption in it. ;-) Thank you for your great work!
