### ISSUE TITLE
Add player list/fix name stealer?

### ISSUE THREAD

**Issue by chovss** [danielkrupinski/Osiris#491]
There's no way to pick the name you want to steal or revert back to your default name.

**Comment by Bywnb** [comment]
name stealer only works in that game.when you start the next game,your default name reverts back

**Comment by danielkrupinski** [comment]
You can disable name stealer and set any name using console command `name your_name`. Also with name stealer disabled your original name will be restored in next match or after reconnect.

**Comment by deprale** [comment]
I will try implementing it tonight and give u a heads up, should be pretty easy to do lol

**Comment by Evilhelder** [comment]
> 
> 
> I will try implementing it tonight and give u a heads up, should be pretty easy to do lol

If you can, put it here, it will be very interesting to test.
