### ISSUE TITLE
[Suggestion] Make visible chams not see through smoke

### ISSUE THREAD

**Issue by dominykqs** [danielkrupinski/Osiris#493]

**Comment by dominykqs** [comment]
Make **visible** chams not see through smoke as this will make **legit** play more convincing.
Nice job I do **really** enjoy using your software Daniel.

**Comment by deprale** [comment]
I will try and implement that later( im not the source owner ) when I get home and play around with it I will update this reply with a tag.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 0xE232FE** [comment]
Look at the Drawmodel in renderable and baseanimation. This might help you alot to understand how the models are drawn and what to apply to them inbetween. Be aware of calling DrawModelEx and DrawModelExecute twice.
[ValveSoftware/source-sdk-2013](https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/public/iclientrenderable.h#L87)

**Comment by Finndramere** [comment]
isnt visible chams working properly? what do you mean by "not see through smoke"?

**Comment by dominykqs** [comment]
It shows visible people (not vehind a wall) but I ask for it not to show people behind smoke. I dont know how to explain it..

**Comment by Finndramere** [comment]
it works properly tho... even with visible chams on you cant see people through smoke...
