### ISSUE TITLE
Some visuals like the skybox are glitching

### ISSUE THREAD

**Issue by You02** [danielkrupinski/Osiris#494]
Most of the visuals are glitching out, no clue whats wrong but it seemed like yesterday they were working perfectly fine. Anyone else having this issue?

**Comment by HowToMakeFaceitAB** [comment]
Idk i use onetap for legit

**Comment by Shaxzy** [comment]
@HowToMakeFaceitAB 
Not helpful at all.

**Comment by HowToMakeFaceitAB** [comment]
🤔🤔

**Comment by deprale** [comment]
Elaborate.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by You02** [comment]
Never mind, it appeared that only in Dust2 it would glitch, the sky boxes wouldent change and generally some skins were taking longer to load than other maps. Could anyone explain why?

**Comment by danielkrupinski** [comment]
Dust 2 uses 3d skybox, which needs to be disabled to change skybox.
