### ISSUE TITLE
SOLVED,CLOSE THX.

### ISSUE THREAD

**Issue by deprale** [danielkrupinski/Osiris#497]

**Comment by deprale** [comment]
@danielkrupinski  pls halp :( what am i doing wrong?

**Comment by tirziz** [comment]
Then close it ?

**Comment by deprale** [comment]
How? Afaik i fucking cant @tirziz 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Shaxzy** [comment]
@deprale 
https://prnt.sc/oz97pn

**Comment by deprale** [comment]
I cant on githawk

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by deprale** [comment]
Can’t on browser with desktop web on:off either ...

https://imgur.com/gallery/0H46rBV
