### ISSUE TITLE
aimbot + Visuals ( No Visual Recoil ) + Recoil Control

### ISSUE THREAD

**Issue by bugaoleg** [danielkrupinski/Osiris#50]
Sometimes mouse is freez for a second and after go to left ... dont know why ... No Visual Recoil does not work. Recoil control working strange ... crosshair goes up ( when it shoud be down ). It will be very nice if you  fix that

**Comment by oddyS1** [comment]
In a demo or spectator your crosshair is going down, perfectly. Just record demo and check it :)

**Comment by snook89** [comment]
Would be nice if coder fix this

**Comment by Shaxzy** [comment]
He’s pushing updates every day. Big respect to tha man. He’s most likely seen this issue/thread and he’s working on it. I bet he has a list of things to add/things and I’m sure this is on there. Be patient bois :)

**Comment by danielkrupinski** [comment]
No visual recoil fixed. Mouse problem not occurs.
