### ISSUE TITLE
update time, data

### ISSUE THREAD

**Issue by ogosirisfan** [danielkrupinski/Osiris#503]
I added it but it doesn't update, do I have to define it?

**Comment by ogosirisfan** [comment]
@danielkrupinski

**Comment by ijre** [comment]
Can you elaborate? This doesn't make any sense, unless it's just something I've never heard before

**Comment by ogosirisfan** [comment]
time and data save when the compilation was made and I would like it to be updated

**Comment by neazen** [comment]
you mean like the build time ?

**Comment by Mufinekkk** [comment]
Just make that with __TIME__

**Comment by ogosirisfan** [comment]
no, I want (local) time to be in the game and date

**Comment by danielkrupinski** [comment]
https://stackoverflow.com/a/16358111
