### ISSUE TITLE
Question about Desync in source

### ISSUE THREAD

**Issue by JacksonDon** [danielkrupinski/Osiris#504]
Hey, 
I was looking in Source, and I find smth on style ("yaw desync") 
Can be used it for Legit AA? Cause when i toggle on it, and record the demo. 
My monitor (screen) is flicking on the sides. 
Some fix or smth? 
I glad somebody help me

**Comment by effex1337** [comment]
The desync doesnt work properly.

**Comment by Kron1Q** [comment]
idk if desync works or not but u wont see this on demo if u do record x, stop, playdemo x.

https://www.unknowncheats.me/forum/1477663-post7.html

do it like that for testing stuff like silent aim, anti aim.

**Comment by littlehurensohn** [comment]
> idk if desync works or not but u wont see this on demo if u do record x, stop, playdemo x.
> 
> https://www.unknowncheats.me/forum/1477663-post7.html
> 
> do it like that for testing stuff like silent aim, anti aim.

Nice idea, but I cant enter into first person mode. 
Only thirdperson what is fucked up?

**Comment by effex1337** [comment]
Manually type firsrperson in console

**Comment by littlehurensohn** [comment]
This desync aa doesnt work properly.. fuck :/

**Comment by danielkrupinski** [comment]
Try setting packet choke to 1 or above.

**Comment by littlehurensohn** [comment]
Still flicking screen @danielkrupinski
