### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by deprale** [danielkrupinski/Osiris#506]
Add a endscene hook please? It will be useful for bypassing OBS.

Would be cool if aimbot had latency and interpolation compensation, you can miss while raging blatantly on legit players.

Why can't the aimbot/triggerbot have an option to "aim" at the backtrack ticks?

Would be cool if you could add fakelag :)

**Comment by hydemods** [comment]
fakelag is already in the cheat

**Comment by deprale** [comment]
Thats choke packets its a whole different thing thats REAL lag

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HowToMakeFaceitAB** [comment]
Damn true

**Comment by neazen** [comment]
The endscene hook would be cool
