### ISSUE TITLE
About the Aimbot

### ISSUE THREAD

**Issue by effex1337** [danielkrupinski/Osiris#507]
The Aimbot aims at the ground and is constantly spinning. The targetted entity seems to be on the ground and also you aim at teammate (only a single guy) even though friendly fire is disabled. 
Not sure if it's only for me as I've modified the source quiet a lot. But don't think it's got anything to do with the modifications i made.

**Comment by deprale** [comment]
Probably only you.

**Comment by effex1337** [comment]
Fixed
