### ISSUE TITLE
HOW ABOUT SOME NEW?

### ISSUE THREAD

**Issue by ADGAYMILK** [danielkrupinski/Osiris#508]
Hmmmm...
WE THINK WE NEED NADES PREDICT
AND AIMBOT AUTO WALL
SO THAT ILL BE A RAGE &LEGIT CHEAT!

**Comment by 4stax** [comment]
The source is open so you should be able to add it yourself pretty easy! ;)

**Comment by danielkrupinski** [comment]
You can turn off "Visible only" option in aimbot.

**Comment by Shaxzy** [comment]
@danielkrupinski 
The problem is that it will constantly wallbanging then. I think he wants an option like, wallbang if it can deal ~25 dmg aka minimal damage and eventually hitchance.

**Comment by rosesware** [comment]
_@Shaxzy_
What Osiris version you had?
Cheat already have autowall, only don't have is min. damage.

**Comment by Shaxzy** [comment]
> _@Shaxzy_
> What Osiris version you had?
> Cheat already have autowall, only don't have is min. damage.

My mistake then. I haven't used this myself for about 1-2 months but I look at the commits being made every day.

**Comment by rosesware** [comment]
> My mistake then. I haven't used this myself for about 1-2 months but I look at the commits being made every day.

Not autowall properly but have.
