### ISSUE TITLE
Error code when starting up CSGO.

### ISSUE THREAD

**Issue by 0x1Eren** [danielkrupinski/Osiris#509]
![Screenshot_4](https://user-images.githubusercontent.com/52881209/64474987-b7b8c400-d17c-11e9-962f-6849d5bd39dc.png)

**Comment by Mufinekkk** [comment]
Ignore

**Comment by BrianVubao** [comment]
Just Verify the game files, restart your computer and try launching the game again.

**Comment by 0x1Eren** [comment]
> Ignore

Closes the cheat.


> Just Verify the game files, restart your computer and try launching the game again.

Didn't work. Still get the error

**Comment by danielkrupinski** [comment]
Attach debugger and press retry.

**Comment by deprale** [comment]
@Mufinekkk braindead?
it literally says ABORT() has been called. the fuck is he gonna ignore? LMFAO

**Comment by 0x1Eren** [comment]
> Attach debugger and press retry.

And now i get:" cl.exe exited with code 2 " error on visual studio.

**Comment by Floraly** [comment]
Please get a clean clone of the Repository!
Use Visual Studio 2019 Community Edition to build.
Nobody have this issue!
git clone https://github.com/danielkrupinski/Osiris

**Comment by deprale** [comment]
Check hooks and hacks namespaces so you dont bave nonexistent stuff or misspelt calls.

Dont build debug to inject lol

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 0x1Eren** [comment]
> Please get a clean clone of the Repository!
> Use Visual Studio 2019 Community Edition to build.
> Nobody have this issue!
> git clone https://github.com/danielkrupinski/Osiris

csgo on linux lul

**Comment by 0x1Eren** [comment]
> Check hooks and hacks namespaces so you dont bave nonexistent stuff or misspelt calls.
> 
> Dont build debug to inject lol
> 
> Sent with [GitHawk](http://githawk.com)

also tried release

**Comment by deprale** [comment]
If you pasted anything probably fked up somewhere

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BrianVubao** [comment]
> > Please get a clean clone of the Repository!
> > Use Visual Studio 2019 Community Edition to build.
> > Nobody have this issue!
> > git clone https://github.com/danielkrupinski/Osiris
> 
> csgo on linux lul

What do you mean by CS:GO on Linux? One thing is for sure, you obviously launched the game on a Windows Machine, as your first screenshot might have shown. And 2, your Visual Studio IDE screenshot, showing the error when compiling, is obviously done on a Windows Machine as well because of the indicators (Win32 as well as the C:/ & D:/ system drives).
