### ISSUE TITLE
Fake Ban / Unbox

### ISSUE THREAD

**Issue by Flaam** [danielkrupinski/Osiris#512]
if ( ImGui::Button("Fake Unbox") )
ChangeName(u8" \x01\x0B\x10 Test \x01has opened a container and found:\x02 ★ M9 Bayonet | Doppler");
if ( ImGui::Button("Fake Ban") )
ChangeName(" \x01\x0B\x07 Test has been permanently banned from official CS:GO servers."); 

Daniel should add a name reset and a way to change the knife on Fake Unbox

**Comment by effex1337** [comment]
Cool shit

**Comment by Flaam** [comment]
@effex1337 idk if it's working but im adding to the source rn
i will let you know

**Comment by Flaam** [comment]
@effex1337 in what document should i add it? im trying but i can't find where to put the code

**Comment by tirziz** [comment]
Is it work ?. I though it is server-side ?

**Comment by Flaam** [comment]
dunno didn't tried that, waiting on daniel pull

**Comment by effex1337** [comment]
> dunno didn't tried that, waiting on daniel pull

Change ChangeName to Misc::ChangeName
Add void ChangeName(std::string name); in misc.h
Add void Misc::ChangeName(std::string name) {
(changename stuff from name stealer)
}
Wrote it from my phone u might need to correct some stuff.

**Comment by effex1337** [comment]
![image](https://user-images.githubusercontent.com/48663440/64643818-f5457780-d430-11e9-8476-9b028073bb77.png)
@Flaam thanks for it bud :D

**Comment by Flaam** [comment]
Perfect :)

**Comment by Evilhelder** [comment]
Aproved :D AUHEAUEUAE

**Comment by Evilhelder** [comment]
It would have to have a code to reset the name, wouldn't it?

**Comment by Flaam** [comment]
@Evilhelder yea it should, maybe Daniel can add it. Thank you guys for the support :)

**Comment by Evilhelder** [comment]
@Flaam 

Thank you guy for submitting. : D

**Comment by Ni1kko** [comment]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/354169-fake-unboxing-vac-ban.html

**Comment by Flaam** [comment]
@Ni1kko yea and? I never said that the code is mine.

**Comment by Evilhelder** [comment]
@Flaam @effex1337 

Sorry for the question, but some of you managed to add this code to osiris or another hack, if so could you pass me?

I just tried that I'm extremely "weak" at Visual Studios ...

**Comment by Evilhelder** [comment]
I'm sorry for my bad english... I'm brazilian.

**Comment by Ni1kko** [comment]
@Flaam I'm not saying anything like that, Merely sharing link to a similar post that has more info about what you posted to try be more helpful :)

**Comment by deXyy999** [comment]
its easy to make and useful as well

**Comment by PassaUmDollar** [comment]
Cool 👍

**Comment by xAkiraMiura** [comment]
this issue is 3 months old and has already been implemented to some capacity, could we close it and stop necroing it.

**Comment by Flaam** [comment]
@xAkiraMiura closing it, thank you
