### ISSUE TITLE
Custom Aimbot FOV on Osiris

### ISSUE THREAD

**Issue by LuxRaze** [danielkrupinski/Osiris#513]
Last night I made a custom aimbot FOV box appear where I could type in a FOV for my aimbot and I can't seem to make the box appear again. Can anyone please tell me how to get the box open again.

**Comment by effex1337** [comment]
1. You did not make it!
2. Hold control and click on the slider for a custom value.

**Comment by LuxRaze** [comment]
Thank you, I didn't mean to put made but yeah
