### ISSUE TITLE
using namestealer in danger zone glitch xd

### ISSUE THREAD

**Issue by AbdallahMehiz** [danielkrupinski/Osiris#516]
When u enable the namestealer in dangerzone, it works fine, it steals names and stuff, but there is a catch
when u enable it
u will not be deployed via a helicopter, instead u will spawn right where u were before the game starts, for the first seconds u cannot jump/shoot after that u can basicly do anything, but when u die in danger zone u cannot respawn because of that glitch. xd
also u cannot get the starting perk :(

**Comment by tirziz** [comment]
Good catch, dangerzone is trash btw

**Comment by AbdallahMehiz** [comment]
i forget it was on xdd
