### ISSUE TITLE
I need Good legit settings

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#518]
Can someone give me a good config?
It needs to  have aimbot, backtrack
Maybe walls (optional)
Hey who knows, if i find agood configs with good settings i might combine them and gove them to you

**Comment by HackerGeo-sp1ne** [comment]
this

**Comment by Madzleii** [comment]
Try mine 


[Legit.zip](https://github.com/danielkrupinski/Osiris/files/3612654/Legit.zip)
