### ISSUE TITLE
Does not work for my friends

### ISSUE THREAD

**Issue by HackerGeo-sp1ne** [danielkrupinski/Osiris#519]
Hello! I have a big problem. I give the hack to my friends and does not work (changed the injectors). For me it works.

Thank you!

**Comment by danielkrupinski** [comment]
I can't help your friends, it's not a problem with the cheat.

**Comment by HackerGeo-sp1ne** [comment]
> I can't help your friends, it's not a problem with the cheat.
Ok. Thank you! Add this: https://www.unknowncheats.me/forum/counterstrike-global-offensive/354169-fake-unboxing-vac-ban.html . If you add you are the best =))
