### ISSUE TITLE
Rage Mode

### ISSUE THREAD

**Issue by hyperxpro** [danielkrupinski/Osiris#520]
How about adding Rage Mode for HvH? This cheat already inherits Aimbot, Visuals, Anti-Aim and other features needed for Rage HvH. 

Will be useful for HvH on HvH Servers.

**Comment by rosesware** [comment]
In my opinion, Rage Mode in an open source is just a mistake.

**Comment by tirziz** [comment]
Negative, Idk ragebot is high priority rightnow

**Comment by hyperxpro** [comment]
> In my opinion, Rage Mode in an open source is just a mistake.
> 
> But, who knows.

Then according to your logic, an open-source cheat is a clear mistake. People can configure anti-aim and aimbot for rage in normal competitive too. 

Rage Mode is only helpful in HvH.
