### ISSUE TITLE
Add new function

### ISSUE THREAD

**Issue by djvksvjhdhvjkdhjbkdhbjdhbdb** [danielkrupinski/Osiris#521]
Please, add new fun function

Fake banned

https://raw.githubusercontent.com/LynxKik/aw-lua-scripts/master/%5BLuaScript%5D%20Fake%20Vac%20Ban%20Message.lua

Color Name
https://raw.githubusercontent.com/LynxKik/aw-lua-scripts/master/%5BLuaScript%5D%20Color%20Name%20Changer.lua

AntiKick
https://github.com/LynxKik/aw-lua-scripts/blob/master/%5BLuaScript%5D%20Anti%20Kick%20Remastered.lua

**Comment by Evilhelder** [comment]
Will he have to convert this code to C++, or add a Lua loader...

**Comment by neazen** [comment]
Yeah but it would be fun :d

**Comment by tirziz** [comment]
Its not just like copy and paste tho. Alot of work it is

**Comment by Jacellen** [comment]
Here is the correct fake ban display and item drop

```
ConVar* Name = g_csgo.m_cvar()->FindVar("name");
Name->m_fnChangeCallbacks = 0;
Name->SetValue(u8" \x01\x0B\x10 Cheater \x01has opened a container and found:\x02 ★ M9 Bayonet | Doppler");

Name->SetValue(" \x01\x0B\x07 Cheater has been permanently banned from official CS:GO servers.");
```

Remember to change the name to

`Name->SetValue("\n\xAD\xAD\xAD");`
