### ISSUE TITLE
[Suggestion] knife bot ?

### ISSUE THREAD

**Issue by maysameso** [danielkrupinski/Osiris#523]
it seems that this cheat contain most of the futures i thought why not to add knife bot

**Comment by Finndramere** [comment]
that could probably be implemented similar to how zeus triggerbot range works

**Comment by anonymouschicken111** [comment]
Can u further elaborate on this feature?
Does it calculate health so the bot can decide when the enemy is in range with knife whether it should attack1 attack1 attack2(In front of person) or attack2(when behind person) or attack1(when enemy low health) or attack2(when enemy low health but can't be killed with attack1)? Or does it do something else?
