### ISSUE TITLE
New GUI

### ISSUE THREAD

**Issue by piotrk12** [danielkrupinski/Osiris#53]
Daniel, czy myślałeś nad nowym GUI?
Aktualne GUI było dobre, jak cheat miał trzy razy mniej funkcji - teraz jest tego po prostu za dużo.

**Comment by yzxahS** [comment]
zgadzam się

**Comment by danielkrupinski** [comment]
Jak miałoby wyglądać nowe GUI?

**Comment by piotrk12** [comment]
Nowe GUI miałoby mieć uproszczony interfejs, wszystko w jednym menu, w którym możemy sobie wybrać zakładkę.

Na pewno rozumiesz, co mam na myśli.

**Comment by TheNotoriousAWP** [comment]
I think that the menu is fine and I like it like this. I think that adding more config files would be useful and also think that moving the menubar to the bottom of the screen would be nicer than the top.

**Comment by piotrk12** [comment]
Daniel, mam na myśli np. takie GUI:
https://github.com/zxvnme/zgui

**Comment by JayneFrack** [comment]
I really like the menu how it is atm

**Comment by mattys0229** [comment]
well, put it into the source yourself.

**Comment by h4x0reL** [comment]
Obecne GUi jest git , masz zakładkę style i możesz robić co chcesz >
minus że nie można rozszerzać interfejsu gdy włączony jest styl one window oraz że pozycje zakładek resetują swoją pozycję :/
