### ISSUE TITLE
[Suggestion] Automatically turn on wallhack after death & Buy info

### ISSUE THREAD

**Issue by Krixx1337** [danielkrupinski/Osiris#531]
It would be nice to have these features :)
1. Automatically turn on wallhack after your death, so you can tell info to other people and turn off wallhack when a new round starts.
2. Basically just show buy info on the chat after the start of the round, which weapons opponents bought, maybe show how many grenades/flashes/smokes they have, etc...

I was using a hack with these features a long time ago and it was super useful.

Buy info example:
![0b1d35eec0eb5a3d418c32bf2f68b2c2](https://user-images.githubusercontent.com/39534939/64925516-e7f20980-d7f1-11e9-8212-e96440e364c7.png)

**Comment by tirziz** [comment]
I remember pHook of poland cheater has that feature, just wonder if osiris can render that ehud

**Comment by anonymouschicken111** [comment]
Well try adding them yourself from other open source cheats and share it here so danielkrupinski can just copy and paste it
