### ISSUE TITLE
What happened to the Skin Changer?

### ISSUE THREAD

**Issue by Adim2P** [danielkrupinski/Osiris#532]
Skin Changer just stopped working after recent updates, I'm still trying to see why? I think nskinz is broken, or the game blocked skin changing completely?

**Comment by tirziz** [comment]
its working for me.

**Comment by neazen** [comment]
Works well for me too

**Comment by BrianVubao** [comment]
> Skin Changer just stopped working after recent updates, I'm still trying to see why? I think nskinz is broken, or the game blocked skin changing completely?

Did you try recompiling the source without making changes to the nskinz source or anything else related to skins.

**Comment by anonymouschicken111** [comment]
Please close issue
