### ISSUE TITLE
aimbot toggle indicator?

### ISSUE THREAD

**Issue by RadicalRedemption** [danielkrupinski/Osiris#538]
Hello, how do i check if the aimbot is toggled on?

**Comment by deprale** [comment]
You can make your own ON/OFF notification either text or sound or both, it's not that hard to be honest.

**Comment by anonymouschicken111** [comment]
Just add drawText in Aimbot
Specify:
Text position
Text color(r, g, b, a) a for alpha, 0-255 0 is transparent and 255 is opaque

If config.aimbot.enable = 1
DrawText ON
If config.aimbot.enable = 0
DrawText OFF

**Comment by RadicalRedemption** [comment]
I couldn't find drawText function?

**Comment by effex1337** [comment]
> I couldn't find drawText function?

Is that supposed to be a question?
Eitherway it's interfaces.surface->printText();
That's what you need

**Comment by RadicalRedemption** [comment]
I'm not familiar with the source code yet, i just cloned it. Any suggestion where to put the text drawing routine?

**Comment by effex1337** [comment]
You can call it nearly everywhere :/
I'll send you a direct c+ p code when i reach home.

**Comment by RadicalRedemption** [comment]
I'll put it inside the Misc::watermark() method, but i was wondering, do i have to iterate through the config.aimbot array, to check if any of its elements is enabled?  Still don't get some of the stuff in the source code.

**Comment by RadicalRedemption** [comment]
Update: i have managed to make it work, but it doesn't work the way i wanted. config.aimbot[].enabled indicates if the aimbot setting is enabled. I need to check if the aimbot toggled on/off, when it is configured to be toggled on/off with a key, instead of "hold". So, i need to check whether it's been toggled on/off.

**Comment by deprale** [comment]
lol then just change the variable lmfao????

**Comment by RadicalRedemption** [comment]
Well onKey was the only variable inside the Aimbot struct that should work, but it doesn't The code is such a mess. 

> 
> 
> lol then just change the variable lmfao????

And you instead of trying to help, why are you being such a toxic bitch?

**Comment by RadicalRedemption** [comment]
```
    if (config.aimbot[weaponIndex].onKey) 
	{
        if (!config.aimbot[weaponIndex].keyMode) 
		{
            if (!GetAsyncKeyState(config.aimbot[weaponIndex].key))
                return;
        } 
		else
		{
            static bool toggle = true;

			if (GetAsyncKeyState(config.aimbot[weaponIndex].key) & 1)
			{
				toggle = !toggle;
			}
            
			if (!toggle)
			{
				return;
			}
        }
    }
```

Isn't the toggle variable supposed to be inside the Aimbot structure? Am i missing something here?

**Comment by RadicalRedemption** [comment]
Anyway, i made it work. But i have to say, this code is a mess.
