### ISSUE TITLE
Restore name, Buy info & desync

### ISSUE THREAD

**Issue by thomas0aotian** [danielkrupinski/Osiris#539]
So after changing name from using fake ban or fake vote function we need a restore name function so we can use it after using the fake ban or vote if we still want our own name back. Is it not possible or bro u just forgot. 

And we kinda need buy info either renders on hud, chat or console. 

Yeah I want desync so bad, so we can have ACTUAL LEGIT ANTI-AIM
that will be the best feature of the year.

**Comment by VuBrian22** [comment]
As of now,You can only change it back by Pressing "~" to open the console. Type "name" without quotes. Unless you want to add that feature yourself and add a function that saves the players name, on injection, in memory and will retrieve it and replace it back with a button press. Link the button to the ImGUI library as well so you can just press the button to revert back to your original name. You can also just "hardcode" your username as a constant in the function if you want, just so you don't have to code the more complicated part of it.

**Comment by anonymouschicken111** [comment]
Or make a function that spams "name" in console

**Comment by deXyy999** [comment]
nice issue, just wanted to write it here.. or just "change custom name" funcvtion, which is easy to add

**Comment by VuBrian22** [comment]
> nice issue, just wanted to write it here.. or just "change custom name" funcvtion, which is easy to add

Agreed, that's were you "hardcode" the name into a function.

**Comment by littlehurensohn** [comment]
This "Legit Antiaim" flicking in demo, just its not legit antiaim.

**Comment by deXyy999** [comment]
ikr
