### ISSUE TITLE
[Suggestion] Disable normal map/bump map/spec map & dynamic light

### ISSUE THREAD

**Issue by brokeDude2901** [danielkrupinski/Osiris#54]
Hi i would like to suggest further increase the fps by disable the rendering of those map, it would help weak gpu

**Comment by brokeDude2901** [comment]
Hi, also on some maps using "ent_fire env_cascade_light fire" kill the light which have like 30 fps boost

**Comment by danielkrupinski** [comment]
Any clue how to do it?

**Comment by midlow** [comment]
@danielkrupinski there are a few sv_cheats protected cvars "mat_specular" "mat_fastnobump" etc... i don't know all of them by memory but you can disable dynamic light sources, specular maps and bump maps

**Comment by brokeDude2901** [comment]
I think somebody just need to find the address but I dont know how. Its the same thing with mat_postprocess enable stuff

**Comment by danielkrupinski** [comment]
I've added shadows removal option which gives bigger fps boost that this. Closing.

**Comment by brokeDude2901** [comment]
nice!
