### ISSUE TITLE
[Improvement] Grenade prediction - c&p friendly

### ISSUE THREAD

**Issue by JDeu** [danielkrupinski/Osiris#546]
Grenade prediction for people who can't code for them selves.

Misc.h
`void nadePredict() noexcept;`

Misc.cpp
`void Misc::nadePredict() noexcept {
	static auto nadeVar = interfaces.cvar->findVar("cl_grenadepreview");
	nadeVar->onChangeCallbacks.size = 0;
	nadeVar->setValue(config.misc.nadePredict ? 1 : 0);
}`

Config.h - In misc struct
`bool nadePredict = false;`

Config.cpp - In load and save

Load
`if (miscJson.isMember("Grenade predict"))  misc.nadePredict = miscJson["Grenade Predict"].asBool();`

Save
`miscJson["Grenade predict"] = misc.nadePredict;`

Hooks.cpp - In create move
`Misc::nadePredict();`

GUI.cpp - In misc tab
`ImGui::Checkbox("Grenade Prediction", &config.misc.nadePredict);`

**Comment by tirziz** [comment]
make a pull request bro.

**Comment by JDeu** [comment]
[Done](https://github.com/danielkrupinski/Osiris/pull/547)
