### ISSUE TITLE
[Suggestion] Grenade Prediction

### ISSUE THREAD

**Issue by anonymouschicken111** [danielkrupinski/Osiris#549]
Last time I spent a while making a nade prediction function, and when I finished Gabe dropped us an update that added grenade prediction to game, so goddammit.

Console command
`cl_grenadepreview 1`

Code:
```
void Visuals::nadePred() noexcept
{
	static auto nadePath = interfaces.cvar->findVar("cl_grenadepreview");
	nadePath->setValue(config.visuals.nadePred ? 1 : 0)
}
```

Add to Misc.cpp or Visuals.cpp(using Visuals.cpp)
Don't forget to add to Visuals `namespace` `void nadePred() noexcept;` in header file
In Hooks.cpp call `Visuals::nadePred();` in `createMove()`
Add to Config.h and Config.cpp
Add to GUI as `ImGui::Checkbox("Grenade Prediction", &config.visuals.nadePred);`

**Comment by anonymouschicken111** [comment]
Fuck, goddamn it JDue did the same thing

**Comment by littlehurensohn** [comment]
Are u sure this can be used in mm? lmfao
