### ISSUE TITLE
Can we please get back the old rcs

### ISSUE THREAD

**Issue by JayneFrack** [danielkrupinski/Osiris#55]
The new rcs is really shaky and It looks so blatant could we please get back the old rcs?

**Comment by danielkrupinski** [comment]
What was the old one?

**Comment by JayneFrack** [comment]
> 
> 
> What was the old one?

It didn't shake it looked like normal recoil control

**Comment by danielkrupinski** [comment]
Please reference commit which contains "old rcs".

**Comment by JayneFrack** [comment]
Idk what I did but when I used this and set the rcs to 0.04 it looked kinda legit
https://github.com/danielkrupinski/Osiris/tree/d44a2549414a3d11135276128a4ca9f534e60028
