### ISSUE TITLE
Anti-aim question

### ISSUE THREAD

**Issue by RadicalRedemption** [danielkrupinski/Osiris#550]
Can i get some extra info about the anti-aim? What exactly it does? What are the "Yaw" and "Pitch" options about?

**Comment by furioushell98** [comment]
Same question here, and whats the best settings for aa in case of raging?

**Comment by LuanGraa** [comment]
The AA in this cheat is not made for raging, its a legit AA and it works by tilting your character sideways to make it harder to land shots, from what i have seen this will only work when you turn up max angle data in the misc tab :)

**Comment by RadicalRedemption** [comment]
> 
> 
> The AA in this cheat is not made for raging, its a legit AA and it works by tilting your character sideways to make it harder to land shots, from what i have seen this will only work when you turn up max angle data in the misc tab :)

What exactly is that option? I didn't see such option.

**Comment by RadicalRedemption** [comment]
> 
> 
> The AA in this cheat is not made for raging, its a legit AA and it works by tilting your character sideways to make it harder to land shots, from what i have seen this will only work when you turn up max angle data in the misc tab :)

You mean max angle delta? What value shud i put there?

**Comment by LuanGraa** [comment]
i leave it on max but its up to you, i dont quite understand it either

**Comment by Kron1Q** [comment]
its about degree between your view angle and your anti aim angle. If you snap more than 30 (or 30 something, idk exact value) then you will end up with vac error in casuals.

**Comment by RadicalRedemption** [comment]
> 
> 
> its about degree between your view angle and your anti aim angle. If you snap more than 30 (or 30 something, idk exact value) degrees in one tick then you will end up with vac error in casuals.

Can you recommend us some proper values for Pitch and max angle delta? Also what is that "Yaw" thingy?

**Comment by LuanGraa** [comment]
@Kron1Q  so thats probably why i am getting kicked every casual match, thanks for the info

**Comment by RadicalRedemption** [comment]
What about the Pitch?

**Comment by sundafused** [comment]
Don't change pitch, that will make you look into the floor or the sky.

**Comment by RadicalRedemption** [comment]
> 
> 
> Don't change pitch, that will make you look into the floor or the sky.

And what about the "Yaw" ?

**Comment by HowToMakeFaceitAB** [comment]
LET ME EXPLAIN DUDES
m_pitch
m_yaw
The pitch is wether you're looking up or down
The yaw is wether you're looking right or left or at the middle of the screen
Anti aim delays the packets sent to the server (it descyns the player model from the hitbox by delaying the sendingof the postion of the pitch and yaw

**Comment by LuanGraa** [comment]
anti-aim doesn't work for me at all, is there other options that need to be turned on for it to work?

**Comment by HowToMakeFaceitAB** [comment]
You can't see the aa
You have tp visualize it(you can't it do that rn since daniel didn't add that feature)

**Comment by LuanGraa** [comment]
ah i see, i will try to add visualize aa then thanks

**Comment by Kron1Q** [comment]
@RadicalRedemption @LuanGraa - Don't use anti aims, aimbots with high FOV and small smooth (or silent) in casuals. If you want to to use them check max angle delta and use it with ~30 degree. For answer about pitch yaw and roll search in google X Y Z math. https://www.pcmag.com/encyclopedia_images/XYMATRIX.GIF

**Comment by HowToMakeFaceitAB** [comment]
@Kron1Q
You mean the coordinate system
And three dimensional vektors and scalers?

**Comment by RadicalRedemption** [comment]
I noticed in the source code that the anti-aim requires Chocked packets to be > 0 to operate. So, what are those "Chocked packets" for?

**Comment by HowToMakeFaceitAB** [comment]
Choked packets make you lag
That's good to avoid trigger botters

Fakelag is like the name says fake lag
Not real lag, fakelag > chocking
And don't set it too high 6 - 10 packets choked is very much enough
