### ISSUE TITLE
VAC was unable to verify your session

### ISSUE THREAD

**Issue by LuanGraa** [danielkrupinski/Osiris#551]
I have restarted multiple times but this issue seems to continue, i don't know if it is my injector(Extreme injector) or the update is blocking some feature in the cheat, pls help.

**Comment by neazen** [comment]
dont use extreme injector and if your using a hour booster disable it

**Comment by LuanGraa** [comment]
What injector do you recommend?

**Comment by neazen** [comment]
RandoInjector with junkcode and vmp, using this and got no problem

**Comment by LuanGraa** [comment]
Thanks boss i will try it out

**Comment by LuanGraa** [comment]
it worked :D ty

**Comment by deprale** [comment]
@neazen why would you add junkcode to rando injector if it already has built in one lol, you dont even have to vmp it, just add more asm emit instructions.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
