### ISSUE TITLE
Osiris is detected

### ISSUE THREAD

**Issue by BangaBanana** [danielkrupinski/Osiris#553]
well its detected ive just got vac banned

**Comment by neazen** [comment]
What injector were you using ? Did you modify it (added junk code or changed some stuff) and are you sure it's a vac ban and not a overwatch?

**Comment by BangaBanana** [comment]
I was using Veiled and no i didnt modify anything

**Comment by LuanGraa** [comment]
Its an open source cheat, getting banned shouldn't surprise you 👍
