### ISSUE TITLE
Osiris is crashing the game after the join the match....

### ISSUE THREAD

**Issue by Evilhelder** [danielkrupinski/Osiris#555]
The title sums up what's going on.. Does anyone know what is going on?

**Comment by rosesware** [comment]
Have a 700kbs of CS:GO update, prob offsets.

**Comment by Evilhelder** [comment]
> 
> 
> Have a 700kbs of CS:GO update, prob offsets.
> 
> EDIT: Wait and paste offsets.

Using the injetor this guy shows Osiris works normally...

https://corsair.wtf/topic/2105-osiris-multi-hack-fixed/

**Comment by neazen** [comment]
I don't suggest downloading from them, they have some history of dox and ddos (probably ratting too) so be careful and I guess try to compile the cheat yourself from this github
