### ISSUE TITLE
The  recoil crosshair isnt working

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#556]
I dont know if its planned to be fixed but the recoil crosshair has been broken for a while now, i would offer to fix it but im a  python maniac

**Comment by VuBrian22** [comment]
Recompile the source. The recoil cross-hair has been working for along time now.

**Comment by Floraly** [comment]
It is working. They changed the ImGUI Based Crosshair to the Original Croshair ingame. I was wondering it isn't working. But it works like a charm!

**Comment by effex1337** [comment]
Weird
It was never broken.

**Comment by anonymouschicken111** [comment]
> It is working. They changed the ImGUI Based Crosshair to the Original Croshair ingame. I was wondering it isn't working. But it works like a charm! Nothing to fix!

Nani? Crosshair isn't Gui based, it cvar spoofin

**Comment by BangaBanana** [comment]
wait then why isnt it working for me ? ive just compiled osiris and it still isnt working

**Comment by effex1337** [comment]
Because it forces a convar which makes your actual.in game crosshair move.

**Comment by BangaBanana** [comment]
so how do i fix it ?

**Comment by BangaBanana** [comment]
> Because it forces a convar which makes your actual.in game crosshair move.

what should i do to fix it ?

**Comment by effex1337** [comment]
It's not broken. 
To know what it does
Just get in a game enable recoil crosshair,  no visual recoil then look at how you're crosshair behaves.
