### ISSUE TITLE
Fake Vote and Fake Ban

### ISSUE THREAD

**Issue by sundafused** [danielkrupinski/Osiris#557]
So, how do you revert your name back to your original after setting up a fake vote/ban? I have a blank name after attempting to do so.

**Comment by deprale** [comment]
open up console
name "your name here"

your name will still be blank in the chat.

**Comment by LuanGraa** [comment]
A quick and easy way i do it is just go to fake ban select white color and write your name, but your name will still be blank in chat too.

**Comment by sundafused** [comment]
thank you guys
