### ISSUE TITLE
[Suggestion] HeadshotLevel Indicator

### ISSUE THREAD

**Issue by 1-Xycro** [danielkrupinski/Osiris#561]
Can you add a headshot level indicator so we are always aiming at the head
It makes it look legit on ow

**Comment by hydemods** [comment]
you can just play the game and not be a silver. simple

**Comment by Kraken69** [comment]
Nah

**Comment by tirziz** [comment]
I dont think that useful

**Comment by Kraken69** [comment]
Is osiris crashing for anybody again?

**Comment by icannotresist** [comment]
i think platinium cheat had this feature
