### ISSUE TITLE
Osiris crashing again

### ISSUE THREAD

**Issue by Kraken69** [danielkrupinski/Osiris#562]
Osiris is crashing again is it just me?
Was working fine few hrs ago

**Comment by AbdallahMehiz** [comment]
maybe just u
i never experienced any crashes with the cheat "except danger zone"

**Comment by HowToMakeFaceitAB** [comment]
Make a new config

**Comment by LuxRaze** [comment]
@HowToMakeFaceitAB 
Just built it and its still crashing when going ingame without a cfg loaded at all

**Comment by HowToMakeFaceitAB** [comment]
Use an older version until daniel fixes it

**Comment by deprale** [comment]
works fine just recompile from scratch

**Comment by kschou95** [comment]
clean and build

**Comment by lukizel** [comment]
does not work for shit for me
