### ISSUE TITLE
skinchanger

### ISSUE THREAD

**Issue by GhostNoc** [danielkrupinski/Osiris#563]
the skin name show “？” when game language is chinese

**Comment by LuxRaze** [comment]
The skin changer doesnt recognize the character thats why

**Comment by HowToMakeFaceitAB** [comment]
It doesn't recognize the character

**Comment by Bywnb** [comment]
套壳的傻逼弟弟

**Comment by Bywnb** [comment]
Yeah, you translated Osiris into Chinese and sold it, right?

**Comment by GhostNoc** [comment]
> Yeah, you translated Osiris into Chinese and sold it, right?

中午界面配置皮肤看不到名字，只能到英文去配置，切换回中文后配置又会乱而已，别张口就来好吧

**Comment by Bywnb** [comment]
> > Yeah, you translated Osiris into Chinese and sold it, right?
> 
> 中午界面配置皮肤看不到名字，只能到英文去配置，切换回中文后配置又会乱而已，别张口就来好吧

我是说， 你想汉化了卖钱吧  @GhostNoc

**Comment by GhostNoc** [comment]
> > > Yeah, you translated Osiris into Chinese and sold it, right?
> > 
> > 
> > 中午界面配置皮肤看不到名字，只能到英文去配置，切换回中文后配置又会乱而已，别张口就来好吧
> 
> 我是说， 你想汉化了卖钱吧 @GhostNoc

我只是自己玩玩而已

**Comment by effex1337** [comment]
English please xd

**Comment by Bywnb** [comment]
有这功夫去学学imgui 而不是在这issue

**Comment by GhostNoc** [comment]
> English please xd

:P I just chatting with him

**Comment by danielkrupinski** [comment]
You need to add Chinese Unicode ranges to https://github.com/danielkrupinski/Osiris/blob/d432198196da9ce83451ef90ea8af5d503d8eb5c/Osiris/GUI.cpp#L37 .

**Comment by GhostNoc** [comment]
> You need to add Chinese Unicode ranges to
> 
> https://github.com/danielkrupinski/Osiris/blob/d432198196da9ce83451ef90ea8af5d503d8eb5c/Osiris/GUI.cpp#L37
> 
> .

I added the range
`io.Fonts->AddFontFromFileTTF(strcat(buffer, "/Fonts/Tahoma.ttf"), 16.0f, nullptr, io.Fonts->GetGlyphRangesChineseFull());`
but it's not working, still display '?'

**Comment by ClaudiuHKS** [comment]
Maybe you need Chinese font file, see https://github.com/ocornut/imgui/issues/1434

**Comment by thomas0aotian** [comment]
xswl
