### ISSUE TITLE
Is the aimbot working for you guys?

### ISSUE THREAD

**Issue by deprale** [danielkrupinski/Osiris#564]
Title

**Comment by ClaudiuHKS** [comment]
I think it does, have you tested it on Dust 2 ?
Maybe some workshop training maps can block it.

Also, try with a fresh config too.

**Comment by deprale** [comment]
I'm debugging right now...
haven't touched the aimbot at all lol 

tested it on all maps/community/official

**Comment by deprale** [comment]
https://i.imgur.com/Lr8LoFv.png

the debugger says that it skips  everything after that highlighted return ;_;

**Comment by deprale** [comment]
I'll just start over.
