### ISSUE TITLE
I need legit aimbot settings

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#565]
I need legit settings because my config is blatant af
I like legit configs, closet configs except, I like to have aimbot with them

**Comment by Madzleii** [comment]
[Osiris.zip](https://github.com/danielkrupinski/Osiris/files/3639481/Osiris.zip)
Legit 1 is more legit, but if you use legit2 you shouldnt get ow banned. I used legit1 config for about 15 games. Im not banned yet :)

**Comment by HowToMakeFaceitAB** [comment]
Thank you :D

**Comment by HowToMakeFaceitAB** [comment]
Sorry I'm on my phone and not home
What is the smooth for ak47 and m4a4 on legit1?

**Comment by Madzleii** [comment]
Around 50 i dont know now

**Comment by HowToMakeFaceitAB** [comment]
50 damn that's high i usually use 15 or 20

**Comment by Madzleii** [comment]
Yeah, well if you can aim a bit its good

**Comment by HowToMakeFaceitAB** [comment]
Ok thankyou

**Comment by Kraken69** [comment]
I use 8 smooth lol

**Comment by furioushell98** [comment]
I use 4 smooth, tbh anything higher than 5 feels like manual aim

**Comment by Madzleii** [comment]
well i dont need that much of asist. I can aim myself

**Comment by neazen** [comment]
I use 1 smooth and silent, and the anti aim pitch -89 and yaw, they're the best for legit, never got overwatched.

**Comment by HowToMakeFaceitAB** [comment]
Lmao that's blatant AF
more blatant than my config
you sure you're not banned



Sarcacsm? what's that ? i never heard about that

**Comment by neazen** [comment]
@HowToMakeFaceitAB sarcasm :d
I suggest not using esp through walls and aimbot smoothness 30-40 that's really nice and legit :)

**Comment by HowToMakeFaceitAB** [comment]
I use 10 Smooth 2 fov
Visible only chams and radar
I am gonna cheat on faceit with esp
