### ISSUE TITLE
[BUG] Font problem

### ISSUE THREAD

**Issue by EGTLoneWolf** [danielkrupinski/Osiris#568]
Bomb timer , spectator font seems to appear in different sizes sometime?
is this a bug?

**Comment by Bywnb** [comment]
Using windows7 may cause this problem

**Comment by EGTLoneWolf** [comment]
I am on Win 10 .

**Comment by Bywnb** [comment]
I'm sorry I don't know. In Windows 7, I see fonts that suddenly get bigger or smaller. This does not happen in windows10

**Comment by EGTLoneWolf** [comment]
it happens rarely . quick restart game will fix it so... not big deal XD

**Comment by tirziz** [comment]
Are you change your resolution of your game after inject osiris ? 
Like from 16:9 to 4:3,

**Comment by EGTLoneWolf** [comment]
Nope. but its alright.
