### ISSUE TITLE
[Suggestion] Bypass sv_pure

### ISSUE THREAD

**Issue by olywxm** [danielkrupinski/Osiris#569]
i think an sv_pure bypass would be nice, allows users to use old sound files

**Comment by tirziz** [comment]
I love that too, if daniel can implement that

**Comment by AbdallahMehiz** [comment]
@danielkrupinski please do that

**Comment by olywxm** [comment]
@danielkrupinski yes yes

**Comment by Novalaki** [comment]
@danielkrupinski please man this would be awesome! with this you could also do stuff like custom models and textures

**Comment by thomas0aotian** [comment]
i think i am the first one who pointed it out #416
