### ISSUE TITLE
{Suggestion} GrenadeHelper

### ISSUE THREAD

**Issue by AmonKing** [danielkrupinski/Osiris#570]
It's not a grenade prediction. It's an auto cast.

**Comment by tirziz** [comment]
Auto cast ? What is that ?

**Comment by AmonKing** [comment]
https://github.com/AimTuxOfficial/AimTux/blob/master/src/Hacks/grenadehelper.cpp

**Comment by Shaxzy** [comment]
Locations close to you:
https://i.imgur.com/DrtAQnF.png

When standing on a location:
https://i.imgur.com/PnXnd9K.png

The triangle indicates where the grenade will land:
https://i.imgur.com/hNDUhZm.png

**Comment by tirziz** [comment]
Pretty sure Riptide v3 has that feature. You can take a look maybe can paste it ,

**Comment by EGTLoneWolf** [comment]
This is a great idea i would say . However if this become a thing , i would prefer the spots to have a separate config by itself to enable sharing and adding
