### ISSUE TITLE
[Suggestion] Blockbot, Edgejump, Jumpbug

### ISSUE THREAD

**Issue by drgn135** [danielkrupinski/Osiris#573]
Adding these features to the cheat would be greatly appreciated! :)

**Comment by Evilhelder** [comment]
Do not forget the Run Boost Helper ... :D

**Comment by deprale** [comment]
Jumpbug has been patched a long time ago

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by drgn135** [comment]
@deprale It's literally a feature in aimware
