### ISSUE TITLE
Desync Problem.

### ISSUE THREAD

**Issue by JacksonDon** [danielkrupinski/Osiris#575]
Hello community,
I have little problem with desync (yaw) 
When i turn on the (yaw), and i want use it like (LegitAA). 
My screen in demo, or when somebody spectating me "flicking". 
And the yaw works only when i have fakelag on 1. 
If fakelag is off the yaw (desync) not works, is there somebody who can help me?
I can give u some little money.. like 3-4 euros.. 
Thanks.

**Comment by neazen** [comment]
Try checking it via GOTV

**Comment by littlehurensohn** [comment]
> Try checking it via GOTV

It doing same.

**Comment by neazen** [comment]
I don't know then, never used the aa in osiris

**Comment by ClaudiuHKS** [comment]
It flicks in X22 too, since 2015 when pSilent was patched, every angle change is sent to the players that are spectating on you (and recorded in a demo too). There is nothing to do about it. That's all I know.

**Comment by designer1337** [comment]
> It flicks in X22 too, since 2015 when pSilent was patched, every angle change is sent to the players that are spectating on you (and recorded in a demo too). There is nothing to do about it. That's all I know.

lmao no, gotv demo is different than spectator pov.

**Comment by littlehurensohn** [comment]
I think Daniel cant fix it, or dont want say how to fix it. 
To prevent use it like legitaa.

**Comment by mdilai** [comment]
**!**sendPacket

Who is able to think will understand.

**Comment by littlehurensohn** [comment]
> !sendPacket
> 
> Who is able to think will understand.

Can you please help how to fix it? Please.

**Comment by neazen** [comment]
@littlehurensohn just learncpp.com and read uc tutorials, it will help you a lot
