### ISSUE TITLE
It crashes when i load in a game

### ISSUE THREAD

**Issue by cooper69046904** [danielkrupinski/Osiris#576]
everytime i inject in menu its fine but when i load in a game it crashes

**Comment by neazen** [comment]
Try to redownload the sourcr

**Comment by cooper69046904** [comment]
i have done that twice

**Comment by cooper69046904** [comment]
do u think u can add me on disc and send the dll please?

**Comment by VuBrian22** [comment]
Just recompile it under x86 Release using AVX/AVX2 compilation under Project Settings. It will compile a more enhanced and optimized version of the cheat unique to your hardware. Therefore there will be a minimal % of crashes.

**Comment by igre3zy** [comment]
> Just recompile it under x86 Release using AVX/AVX2 compilation under Project Settings. It will compile a more enhanced and optimized version of the cheat unique to your hardware. Therefore there will be a minimal % of crashes.

How do I recompile it as an AVX in visual studio?

**Comment by cooper69046904** [comment]
It still crashes ;c

**Comment by VuBrian22** [comment]
> It still crashes ;c

Delete the csgo folder in the directory and check the integrity of the game files.

**Comment by cooper69046904** [comment]
Have u got discord?
