### ISSUE TITLE
[ISSUES] AA still, Viewmodel FOV vs. Aug and sg 553 
[ Suggestion] Player weapon esp!

### ISSUE THREAD

**Issue by thomas0aotian** [danielkrupinski/Osiris#577]
So the anti-aim never worked that's known of fov flicking in demo,pretty sure the samething in gotv.
      And also when u had viewmodel changed ,the size of the scope of aug and sg553 changed too,which is not good! Can we plz fix this problem so when the viewmodel fov is changed but the size of scope(when we right click to zoom in)is the original size still. TKS
      And a little suggestion is that to add a player owned weapon esp option,so we can see which weapon that allies/enermies are using.
THANKS DANIEL I AM UR BIGGEST FRIEND XDDDDDDD

**Comment by twangsriprasoet** [comment]
try to add "Choked Packet" above 1 in Misc and see is AA working.

**Comment by deprale** [comment]
Check if is scoped easy fix for the fov problem

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
