### ISSUE TITLE
PLease help me

### ISSUE THREAD

**Issue by cooper69046904** [danielkrupinski/Osiris#579]

**Comment by neazen** [comment]
We can't do anything til you explain us your problem...

**Comment by effex1337** [comment]
Alright, sending the FBI

**Comment by cooper69046904** [comment]
Keeps crashing ive done all the steps

**Comment by icannotresist** [comment]
Which injector r u using?

**Comment by cooper69046904** [comment]
it is xenos

**Comment by cooper69046904** [comment]
> Which injector r u using?

have u got the dll?

**Comment by deprale** [comment]
Lmao imagine using xenos enjoy the vac kid

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
