### ISSUE TITLE
[HELP] Desync YAW

### ISSUE THREAD

**Issue by JacksonDon** [danielkrupinski/Osiris#580]
Hi, can somebody of you please help me to fix the desync yaw? 
To stop flicking ofc. 
I can pay some little $.

**Comment by tirziz** [comment]
stop spamming issuse plz

**Comment by neazen** [comment]
There is 3-4 issue like this, just close this and check others lmao

**Comment by littlehurensohn** [comment]
> There is 3-4 issue like this, just close this and check others lmao

I actually checked, ye there is more issues but aint fix.

**Comment by deprale** [comment]
How about instead of offering money to randoms you actually donated to daniel instead?? Maybe that’s gonna give him motivation to actually fix the issues??

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by littlehurensohn** [comment]
> How about instead of offering money to randoms you actually donated to daniel instead?? Maybe that’s gonna give him motivation to actually fix the issues??
> 
> Sent with [GitHawk](http://githawk.com)

Maybe cause i want fix only for me, and not sharing yet?

**Comment by deprale** [comment]
Then whats the point of open source? I was gonna post a fix for the people but seeing this attitude towards open source makes me not want to because of dickheads like you.
>> How about instead of offering money to randoms you actually donated to daniel instead?? Maybe that’s gonna give him motivation to actually fix the issues?? ...

@littlehurensohn 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by littlehurensohn** [comment]
I dont thinks it bad, but too many of "pasters" are fucked up and want to sell it for amazing price. 
I respect you if ur normal, but if ur redhead with low brain its not my bad. 
I dont think it offensive at you, whatever, how i said i respecting you. 
I hope u know, how I mean it.

**Comment by deprale** [comment]
@littlehurensohn i know what you mean but pasters will always exist that sell these types of open source cheats, you can’t stop them and if they wanted to they could fix it themselves. I’ve personally exposed 1 paste of osiris using less features but same layout of options which gave it away, the menu was different but the features names and the layout gave it away, funniest part was the 15$ monthly price lmao

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by littlehurensohn** [comment]
> @littlehurensohn i know what you mean but pasters will always exist that sell these types of open source cheats, you can’t stop them and if they wanted to they could fix it themselves. I’ve personally exposed 1 paste of osiris using less features but same layout of options which gave it away, the menu was different but the features names and the layout gave it away, funniest part was the 15$ monthly price lmao
> 
> Sent with [GitHawk](http://githawk.com)

Lmao, do you have discord or something? If yeah, please add me (-insecure#3455)

**Comment by littlehurensohn** [comment]
> @littlehurensohn i know what you mean but pasters will always exist that sell these types of open source cheats, you can’t stop them and if they wanted to they could fix it themselves. I’ve personally exposed 1 paste of osiris using less features but same layout of options which gave it away, the menu was different but the features names and the layout gave it away, funniest part was the 15$ monthly price lmao
> 
> Sent with [GitHawk](http://githawk.com)

Do you have discord or something? If yeah please add me, -insecure#3435

**Comment by VuBrian22** [comment]
@deprale I mean although it is morally wrong to paste free stuff and sell it for profit. This open source repo, like many others do have that MIT License, which is a shame that many abuse it.

**Comment by igre3zy** [comment]
Guys how to i recompile as AVX or AVX2 in visual studio?
