### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by igre3zy** [danielkrupinski/Osiris#582]
Yo someone please fix the skin changer to make a star (★) before the knife names. I know this is probably a simple fix and I could do it myself, but im dogshit at c++. Cheers :)

**Comment by danielkrupinski** [comment]
Set quality to "unusual".

**Comment by littlehurensohn** [comment]
> Set quality to "unusual".

Hey? Can you please answer me? "How to fix Desync"
