### ISSUE TITLE
[FIX] Fixed osiris crash offsets (see comment 7)

### ISSUE THREAD

**Issue by igre3zy** [danielkrupinski/Osiris#585]
I've re-downloaded cs, restarted pc, and even recompiled the source to AVX2 and it crashes when I enter a game. Can someone help me?

**Comment by mengxuan619** [comment]
game was updated, not ur problem  
need new offset

**Comment by igre3zy** [comment]
How exactly do I do that?

**Comment by deprale** [comment]
I’ll try updating if I manage to

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by igre3zy** [comment]
Okay, thank you

**Comment by sundafused** [comment]
Check the pulls, it's already updated.

**Comment by Ni1kko** [comment]
https://github.com/danielkrupinski/Osiris/compare/master...mdilai:offsets?diff=split

**Comment by mengxuan619** [comment]
NICE WORK BRO

**Comment by Phawak** [comment]
can you give me the dll i'm too bad to do these things

**Comment by igre3zy** [comment]
Phawak you got discord? ill send a guide on how to do it and the dll. Just so you can do it next time.

**Comment by Phawak** [comment]
https://discord.gg/CyDZfcq

Yes

**Comment by Ni1kko** [comment]
@igre3zy why not guide him here then others can maybe learn from that too? But all you got to do is i change a few numbers in 1 file and build source.  i even shared the link with the updated virtual method indices (Thanks to mdilai) showing exactly what to change on what file come on it ain't rocket science

**Sarcasm**
if you have no idea what you're doing maybe try "c++ hello world app" instead

**Comment by igre3zy** [comment]
@Ni1kko he doesn't speak english so it would be very hard to guide him. Im sending him the dll and also showing him how to fix it next time the offsets are changed.

**Comment by Anasx69** [comment]
@igre3zy can you also send me the dll and tutorial ? ;
