### ISSUE TITLE
[Question] How do the offsets work on osiris?

### ISSUE THREAD

**Issue by You02** [danielkrupinski/Osiris#586]
I have messed with cheats that have used offsets, and have been able to make a cheat using hazedumper, but im confused on how the offsets work on this

**Comment by tirziz** [comment]
I think you are talking to external cheat.
Osiris is an Internal cheat and we use Signature Scan to make cheat outdate less often.

**Comment by You02** [comment]
Ive used internals that have used hazedumper offsets, but thank you that clears up alot for me
