### ISSUE TITLE
Game Crashing?

### ISSUE THREAD

**Issue by Adim2P** [danielkrupinski/Osiris#588]
As of September 26, the hack is crashing CSGO, probably the offsets changed due to an update

**Comment by tirziz** [comment]
#583 try this, it should work.

**Comment by RXJpaw** [comment]
*too lazy to log the crash
(me too)

**Comment by Adim2P** [comment]
> #583 try this, it should work.

I'm really confused on what to do, I'll change the offsets in the source code then?

**Comment by RadicalRedemption** [comment]
> 
> 
> > #583 try this, it should work.
> 
> I'm really confused on what to do, I'll change the offsets in the source code then?

Change the offsets, compile, inject, play, win. (not so sure about the last one)

**Comment by Ebzdyberybencjusz** [comment]
constexpr Vector getEyePosition() noexcept
    {
        Vector vec{ };
        callVirtualMethod<void, Vector&>(this, 283, vec);
        return vec;
    }
    constexpr bool isWeapon() noexcept
    {
        return callVirtualMethod<bool>(this, 165);
    }
    constexpr bool isAlive() noexcept
    {
        return callVirtualMethod<bool>(this, 155) && health() > 0;
    }
 
    constexpr bool isPlayer() noexcept
    {
        return callVirtualMethod<bool>(this, 157);
    }
 
    constexpr Entity* getActiveWeapon() noexcept
    {
        return callVirtualMethod<Entity*>(this, 267);
    }
 
    constexpr int getWeaponSubType() noexcept
    {
        return callVirtualMethod<int>(this, 279);
    }
 
    constexpr WeaponData* getWeaponData() noexcept
    {
        return callVirtualMethod<WeaponData*>(this, 456);
    }
 
    constexpr float getInaccuracy() noexcept
    {
        return callVirtualMethod<float>(this, 478);
    }
    constexpr Entity* getObserverTarget() noexcept
    {
        return callVirtualMethod<Entity*>(this, 293);
    }
