### ISSUE TITLE
Bypass server side faceit? 

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#589]
Does osiris bypass server side faceit?

**Comment by neazen** [comment]
If you disable aim and some other stuff i guess u can play without problem

**Comment by tirziz** [comment]
Esp and bhop are fine

**Comment by danielkrupinski** [comment]
Aimbot would be detected, other functions should work fine but be careful with bunnyhop.

**Comment by HowToMakeFaceitAB** [comment]
Ok thanks
