### ISSUE TITLE
No view/aim punch doesn't work

### ISSUE THREAD

**Issue by RadicalRedemption** [danielkrupinski/Osiris#592]
Title.

**Comment by sundafused** [comment]
yea it does? Recompile and check again.

**Comment by deprale** [comment]
It does.
What doesnt work for me is the "No hand" or/and "No weapon" feature.

**Comment by AbdallahMehiz** [comment]
@deprale the no hands and no weapons feature only works when the skinchanger is off
like if u had the default knife and gloves it works just fine

**Comment by RadicalRedemption** [comment]
Recompiled the last source, still doesn't work for me. I get aimpunched.
