### ISSUE TITLE
Fix the animation of the Butterfly knife . Also add anti untrusted ?

### ISSUE THREAD

**Issue by Anasx69** [danielkrupinski/Osiris#594]
Title

**Comment by effex1337** [comment]
Anti Untrusted is already there. 
It's just clamping angles check Hooks.cpp last few lines in createmove.

**Comment by ZPDMiller** [comment]
The anims for the butterfly knife works fine

**Comment by Anasx69** [comment]
i dont know why but every anim of every knife is ok except for the Butterfly it glitches an does some weird shit

**Comment by ZPDMiller** [comment]
Is it when you equip the butterfly knife, inspect it, stab or slash, or kill, because when I do all of those things it works like how it would normally work.

**Comment by Anasx69** [comment]
its like when iam using an Ak then switch to the knife it has 2 animations of going out the first one works fine but the second one wich the knife goes forward is bugged AF note it only happens with the butterfly

**Comment by ZPDMiller** [comment]
Alright, I'll check it out in a sec

**Comment by Anasx69** [comment]
the anim only works fine if i go into a custom server or a workshop map also

**Comment by ZPDMiller** [comment]
ok

**Comment by Anasx69** [comment]
So?
