### ISSUE TITLE
Triggerbot sometimes misses

### ISSUE THREAD

**Issue by RadicalRedemption** [danielkrupinski/Osiris#597]
Using AWP, triggerbot sometimes misses the killshot.

**Comment by VuBrian22** [comment]
Does your trigger bot have any delay?

**Comment by RadicalRedemption** [comment]
It currently has 32ms

**Comment by Shaxzy** [comment]
Honestly I use 14ms. Ofc that's matching my playstyle and may not look legit for you however. I am LEM without cheats.

**Comment by thomas0aotian** [comment]
never use triggerbot, I believe my reaction

**Comment by anonymouschicken111** [comment]
14 ms is like wtf Kennys's reaction is around 75 ms
