### ISSUE TITLE
ETA?

### ISSUE THREAD

**Issue by 02diablo32** [danielkrupinski/Osiris#6]
Is there an eta for when u will add a aimbot.

**Comment by pz-z** [comment]
> Is there an eta for when u will add a aimbot.

Adding an aimbot from another source will do the job for you however, it requires a bit of time since you will have errors and such.

**Comment by danielkrupinski** [comment]
It will be shipped when it's ready. You can surely fork the repo, implement aimbot and open PR, if you want to.
