### ISSUE TITLE
AutoUpdate from Github servers

### ISSUE THREAD

**Issue by piotrk12** [danielkrupinski/Osiris#60]
Same as the topic.
Would be great, there are so many updates to update it everyday.

**Comment by danielkrupinski** [comment]
Have you tried
```
git pull
```
?

**Comment by piotrk12** [comment]
I mean auto DLL updating. :)

**Comment by danielkrupinski** [comment]
I don't have cloud build server.

**Comment by piotrk12** [comment]
For example, you can make an autoupdate which will download .dll directly from github.

**Comment by danielkrupinski** [comment]
I won't be uploading builds daily to GitHub.
