### ISSUE TITLE
[HELP] Working stattrak in skinchanger

### ISSUE THREAD

**Issue by igre3zy** [danielkrupinski/Osiris#600]
Could someone guide me on how to make a working stattrak in the skin changer? It could be something as simple as (if the player gets a kill, add a kill to the stattrak number on the current weapon) thanks :)

**Comment by RadicalRedemption** [comment]
Can other players see your changed skin anyway?

**Comment by JDeu** [comment]
The best way I found to do this was to make a function in GameEvent hook and everytime you get a kill, get the current weapon you hold, plus 1 to a variable then at the end of the round open a json file and add the variable value to the weapon property. Then in the skinchanger when its applying the skin, read the json property and set the fallbackstattrack value to it.

**Comment by VuBrian22** [comment]
> Can other players see your changed skin anyway?

No they can't because the skin changer only acts on the client-side and not the server-side of things. All the other players see are the default skins of each weapon, including the knife.
