### ISSUE TITLE
[HELP] EdgeJump

### ISSUE THREAD

**Issue by 3y2189ewq** [danielkrupinski/Osiris#601]
Can someone add edgejump or guide me on how to do it?

**Comment by tirziz** [comment]
``void Misc::EdgeJump(CUserCmd* pCmd)
{
	IClientEntity* LocalP = (IClientEntity*)I::ClientEntList->GetClientEntity(I::Engine->GetLocalPlayer());
 
	if (LocalP->GetMoveType() == MOVETYPE_LADDER || LocalP->GetMoveType() == MOVETYPE_NOCLIP)
		return;
 
	Vector Start, End;
	Start = LocalP->GetOrigin();
 
	VectorCopy(LocalP->GetOrigin(), Start);
	VectorCopy(Start, End);
 
	End.z -= 32;
 
	Ray_t ray;
	ray.Init(Start, End);
 
	trace_t trace;
 
	CTraceFilter filter;
	filter.pSkip = I::ClientEntList->GetClientEntity(I::Engine->GetLocalPlayer());
 
	I::EngineTrace->TraceRay(ray, MASK_PLAYERSOLID_BRUSHONLY, &filter, &trace);
 
	int EdgeJumpKey = Menu::Window.MiscTab.OtherEdgeJump.GetKey();
	if (trace.fraction == 1.0f && EdgeJumpKey > 0 && GUI.GetKeyState(EdgeJumpKey))
	{
		pCmd->buttons |= IN_JUMP;
	}
}
``
Work ? Maybe
