### ISSUE TITLE
[SUGGESTION] Fake duck 

### ISSUE THREAD

**Issue by olywxm** [danielkrupinski/Osiris#602]
Normal fake duck or even legit fake duck would be really cool!
@danielkrupinski

**Comment by EsPiNNt** [comment]
https://github.com/danielkrupinski/Osiris/blob/82b0f6af149c987c071f30b5697ed5b7aa217c92/Osiris/GUI.cpp#L848
u could open ur eyes instead

**Comment by olywxm** [comment]
that removes the cool down between ducks @EsPiNNt fake duck makes it so that on enemies screen ur ducked but on urs you're just standing normally

**Comment by EsPiNNt** [comment]
just spam it

**Comment by olywxm** [comment]
good point i guess, i will add a keybind for it so it spams it on key press/hold

**Comment by hvher** [comment]
spamming duck =/= fakeduck
