### ISSUE TITLE
[Help] Desync Legit

### ISSUE THREAD

**Issue by JacksonDon** [danielkrupinski/Osiris#603]
Is there somebody who can share code for legit aa desync? 
I can pay something if you want, but I want normally working code.
Please, thanks.

**Comment by littlehurensohn** [comment]
@danielkrupinski

**Comment by JDeu** [comment]
this is like your 6th issue. Just buy a cheat if you want it that bad.

Close this.

**Comment by tirziz** [comment]
This is a training project Daniel does not own you anything.

Also feel free to donate https://paypal.me/DanielK19
