### ISSUE TITLE
C4 skin

### ISSUE THREAD

**Issue by HECCYE** [danielkrupinski/Osiris#606]
Hi, i was just wondering if applying skin to c4 is possible.

**Comment by HECCYE** [comment]
unfortunately it crashes but thank you anyways

**Comment by yumyumrice** [comment]
possible, add it yourself. im sure u will find the source somewhere :)

**Comment by tirziz** [comment]
Yes you can

**Comment by HECCYE** [comment]
ive been searching for while sadly i didnt found anything, can you provide me with some more info ?

**Comment by HECCYE** [comment]
> possible, add it yourself. im sure u will find the source somewhere :)

i was searching for a while, do you have any clue where i would find source ?

**Comment by Kron1Q** [comment]
@HECCYE Hook findmdl i guess
