### ISSUE TITLE
[Help/Suggestion] Damage Indicator

### ISSUE THREAD

**Issue by Oly-UK** [danielkrupinski/Osiris#607]
Anybody got code for damage indicator, like fantas, says how much damage your shot is going to do. https://prnt.sc/pcff8j

**Comment by 0xE232FE** [comment]
We have health ESP.

**Comment by deprale** [comment]
thats hitscan, we have it already in aimbot(not true implementation) but you'll have to render it on screen manually if you want that feature lol.
funny enough i was thinking about adding this to the cheat yesterday, with an additional esp text saying how much damage u can do + hit indicator after u shot a player.
