### ISSUE TITLE
[Suggestion] Engine Prediction

### ISSUE THREAD

**Issue by deprale** [danielkrupinski/Osiris#609]
Can we have Engine Prediction for the aimbot? I swear the aimbot sucks without it.
You can verify what I'm saying by just loading up a dangerzone match and test the aimbot for yourself at a distance.
Whiffs 70% of the time even with the most rage settings you can imagine.

EDIT: Ridiculous, I miss literally from hug distance. Not once, not twice, but three times at most...

**Comment by Kraken69** [comment]
good idea

**Comment by HowToMakeFaceitAB** [comment]
Nice idea

**Comment by deprale** [comment]
@danielkrupinski  pls senpai everyone wants this

**Comment by hvher** [comment]
nothing you can do about spread. engine prediction is only going to help you when you're going blazing fast past enemies

**Comment by Cr7mbl3** [comment]
@danielkrupinski pls i think it would be a good idea, so the aimbot doesnt miss that often while raging.
