### ISSUE TITLE
Fake ban\kick issue

### ISSUE THREAD

**Issue by ccsimplyspolit** [danielkrupinski/Osiris#610]
sometimes nick change on empty? 
https://imgur.com/uM27nwv
next click on set fakename after 5 sec is fix that
color issue with fake ban.
![image](https://user-images.githubusercontent.com/29892758/65876901-14318c80-e393-11e9-9781-e43c09afc579.png)

check that pls
suggestion to add change name on original after start callvote

**Comment by AbdallahMehiz** [comment]
xd
that also happened to me
u gotta enable custom clantag for it to work

**Comment by danielkrupinski** [comment]
Fixed.
