### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Tgamer500** [danielkrupinski/Osiris#615]
Suggestion 1: Manual AA (press a key to switch sides)
Suggestion 2: Enemy weapon esp (Icon or text)
Suggestion 3: Switch knife hand
Suggestion 4: fakelag # #

**Comment by anonymouschicken111** [comment]
Fakelag                                                                   THIS FEATURE EXSISTS
Switch knife hand                                                    DUPLICATE ISSUE
Enemy weapon esp(honestly add it yourself)            DUPLICATE ISSUE

Fakelag == choke packets    dummy
fakelag is literally choking packets
