### ISSUE TITLE
clantag issue

### ISSUE THREAD

**Issue by ccsimplyspolit** [danielkrupinski/Osiris#617]
clantag time not working while i not enable custom clantag
clantag custom not working too.

**Comment by anonymouschicken111** [comment]
Update offsets

**Comment by ccsimplyspolit** [comment]
I finded indexes but not offsets, what file define offsets?

**Comment by HowToMakeFaceitAB** [comment]
Idk

**Comment by thomas0aotian** [comment]
client_panaroma.dll in csgo/bin

**Comment by ccsimplyspolit** [comment]
give me filename from source of osiris. not client panorama :/
