### ISSUE TITLE
RCS is broken!(aimPunch)

### ISSUE THREAD

**Issue by snook89** [danielkrupinski/Osiris#62]
The RCS is broken(aimPunch). When you are controlling your spray with the cheat, it does infact control the recoil; however, your crosshair does not go along with the recoil therefore you can never use this cheat while streaming. It is simply impossible for your recoil to control like this. It also throws off your muscle memory.

What the cheat RCS looks like - https://gfycat.com/rewardingzigzaggalapagospenguin

What recoil control looks like legitly - https://gfycat.com/blindweightyhartebeest

Can you see the difference? Please address the issue, I know you make constant updates.

**Comment by piotrk12** [comment]
Yeah, my opinion is same.
Of course, RCS work really great now - but only, if we are talking about where the bullets go, and accuracy.
Other thing is the how RCS works, wtf it wont be ever legit if someone have crosshair 6 feets over where the bullets go.

**Comment by snook89** [comment]
https://www.unknowncheats.me/wiki/Counter_Strike_Global_Offensive:Recoil_Compensation

Read INTERNAL. This is what happened in your cheat! They gave example how to fix it

**Comment by danielkrupinski** [comment]
Should be fixed.

**Comment by danielkrupinski** [comment]
Should be fixed.

**Comment by snook89** [comment]
Now it's standalone RCS  👎
