### ISSUE TITLE
[Suggestion] Bunnyhop Hitchance

### ISSUE THREAD

**Issue by 1-Xycro** [danielkrupinski/Osiris#625]
We need bhop hitchance pls

**Comment by kavavps1** [comment]
> Just paste this #389 in your osiris, it's not hard.

not working anymore, the constexpr void bunnyHop is now in misc.cpp not misc.h and im getting errors after changing this to designer1337's code

**Comment by neazen** [comment]
working fine for me x) check the reply's there is probably a fix or ask for a fix I don't know...

**Comment by kavavps1** [comment]
> working fine for me x) check the reply's there is probably a fix or ask for a fix I don't know...

ok, now i've fixed it :D
