### ISSUE TITLE
MEDAL CHANGER IS ALREADY INTEGRATED

### ISSUE THREAD

**Issue by AbdallahMehiz** [danielkrupinski/Osiris#626]
while i was searching how to make a profile changer
i ran into a post "https://www.unknowncheats.me/forum/counterstrike-global-offensive/298336-rank-win-medal-changer.html"
someone in there said that nskins wich is the skin changer used in osiris
has a medal changer
but it has no GUI for it
@danielkrupinski please add it
its as easy as it can get
i couldn't do it because i didn't know how to edit the GUI
https://github.com/namazso/nSkinz/blob/master/src/Hooks/PostDataUpdate.cpp#L153

**Comment by neazen** [comment]
Editing the GUI is easy as it can get https://github.com/ocornut/imgui/tree/master/docs :)

**Comment by tirziz** [comment]
And we you to include protobuff too

**Comment by AbdallahMehiz** [comment]
what should i do to get it to work

**Comment by Bywnb** [comment]
Add New Feature => PULL REQUEST
The Code by the way isn't helpful on Osiris. If you are so smart and copy & paste it here. Try at least to understand it and change the things like CUserCmd or anything else because any posidocode is better than paste from another cheat.

**Comment by anonymouschicken111** [comment]
@Bywnb I think u meant puesdocode

**Comment by AbdallahMehiz** [comment]
ok
