### ISSUE TITLE
rainbow speed value

### ISSUE THREAD

**Issue by BHOPERGUY** [danielkrupinski/Osiris#627]
Hi, Daniel. Please add rainbow speed value.

**Comment by Bywnb** [comment]
pull requests,ok?

**Comment by VuBrian22** [comment]
Yes, please do a pull request. Find code for it or code it yourself and make a contribution to the repo, if you so dearly want the feature. Although here's a quick tip: add a float or float slider to the ImGUI as well so you have the slider or type in box for values.

**Comment by anonymouschicken111** [comment]
@VuBrian22 what is a rainbow speed value?

**Comment by danielkrupinski** [comment]
Added to chams.
