### ISSUE TITLE
Polyloader

### ISSUE THREAD

**Issue by AlexanderQueen** [danielkrupinski/Osiris#628]
Will it work with PolyLoader (randomization and enc. strings +junks)

**Comment by 0xE232FE** [comment]
You don't need it and it doesn't work and prevent nothing! Add features yourself and change VMT Hook will make it undetected for you! No Junk Code or Randomization prevent VAC! If VAC want to Fuck Osiris it will fuck it even with Polyloader and Junk Code. Don't waste your time with this and learn to code!

**Comment by AlexanderQueen** [comment]
I supposed with poly enc_string + junk lines it will be safe for me till next update? What About VMP? If i add .dll with /MAP file, and mutate function with it?

**Comment by 0xE232FE** [comment]
VMP and Mutation isn't prevnt detection. I can give you list of cheats that got detected with this methods. It doesn't last forever. Even cheats with high randomized codebase in C# is detectable.

Inject a white DLL with ImGUI and Hello World! Window it will not ban you for using ImGUI. If VAC would look for ImGUI Osiris would have been VAC Banned already. So it's defeneitve not detected.

Using VAC Bypass is actually the main aproach to have it undtected. So it doesn't matter if you can avoid checks by modify system functions with Kernl Driver WSD

**Comment by AlexanderQueen** [comment]
> VMP and Mutation isn't prevnt detection. I can give you list of cheats that got detected with this methods. It doesn't last forever. Even cheats with high randomized codebase in C# is detectable.
> 
> Inject a white DLL with ImGUI and Hello World! Window it will not ban you for using ImGUI. If VAC would look for ImGUI Osiris would have been VAC Banned already. So it's defeneitve not detected.
> 
> Using VAC Bypass is actually the main aproach to have it undtected. So it doesn't matter if you can avoid checks by modify system functions with Kernl Driver WSD

What about using blackbone hook?

**Comment by anonymouschicken111** [comment]
Just fucking delete ImGui as a whole right along with Json and make a config class where you modify the class every time you want to change something
