### ISSUE TITLE
Anti-Aimbot shakes while shooting

### ISSUE THREAD

**Issue by kavavps1** [danielkrupinski/Osiris#629]
My settings
Anti aimbot ON
Yaw ON
Chocked Packets 2
Max Angle delta 22.22

I recorded a demo on GOTV and I noticed that when i'm shooting, the crosshair teleports over the head
and returns to the starting position. How can I make this look legit?

**Comment by ZPDMiller** [comment]
Turn off silent and play around with smoothing till you have a value you are comfortable with.

**Comment by kavavps1** [comment]
im playing without silent
without aimbot the problem still exist

**Comment by littlehurensohn** [comment]
> im playing without silent
> without aimbot the problem still exist

Its good, for me flicking screen still..
