### ISSUE TITLE
Osiris02/10/2019 DOESN'T INJECT

### ISSUE THREAD

**Issue by giangero1** [danielkrupinski/Osiris#630]
I was using osiris fine yesterday but after a csgo update at 5 in the morning 1 fricking megabyte update !!!! now makes osiris not inject it doesn't even crash just doesn't inject :(  and probably yall haven't used it today that's why you don't know yet the issue.

**Comment by Bywnb** [comment]
I can use it normally, but you injected it in the wrong way

**Comment by giangero1** [comment]
@Bywnb Giangero#3167 add me on discord if u can :/

**Comment by Bywnb** [comment]
Use APC injection

**Comment by giangero1** [comment]
@Bywnb injects with extreme injector tested it on -insecure , so rando no work which injecto should i use now ? any good source that easily can junk code and use ?

**Comment by Bywnb** [comment]
> @Bywnb injects with extreme injector tested it on -insecure , so rando no work which injecto should i use now ? any good source that easily can junk code and use ?

I'm sorry, I'm Chinese and I don't know how to get in touch with you effectively. But use APC injection is effective, this is one of our China BBS post: https://blog.csdn.net/earbao/article/details/52469811

**Comment by giangero1** [comment]
il close this issue cause for some fricking reason rando works again

**Comment by Bywnb** [comment]
lol
