### ISSUE TITLE
sv_pure bypass

### ISSUE THREAD

**Issue by HECCYE** [danielkrupinski/Osiris#631]
would be great for memes
also why not

**Comment by HECCYE** [comment]
found this
www.unknowncheats.me/forum/counterstrike-global-offensive/279394-dumb-sv_pure-bypass.html
its ghetto but it will do the trick

**Comment by anonymouschicken111** [comment]
Umm Osiris does not have a SendNetMsg hook, and also I can't find a good reason why u would do this

**Comment by VuBrian22** [comment]
Please close this thread, we already have 4+ threads requesting and suggesting this feature already. There should be one open with code that works for Osiris.

**Comment by HECCYE** [comment]
> Umm Osiris does not have a SendNetMsg hook, and also I can't find a good reason why u would do this

there isnt rlly reason for having drone/water screen efects hitmaker and they are in cheat, so why not sv_pure?
