### ISSUE TITLE
Performance Improvement

### ISSUE THREAD

**Issue by EGTLoneWolf** [danielkrupinski/Osiris#634]
Is it still possible to further improve performance of the cheat? I get about 200+ fps in game but it goes under 100 when features are enabled ( mainly chams )

**Comment by GaghiZor** [comment]
It is normal to have a drop in FPS when you're using any kind of visuals (chams included) .

**Comment by anonymouschicken111** [comment]
Please close issue

**Comment by deprale** [comment]
Build with AVX2 instructionset.

**Comment by agshaidun** [comment]
> 
> 
> Build with AVX2 instructionset.

How?

**Comment by EGTLoneWolf** [comment]
Thanks for all information , Really appreciated it.
