### ISSUE TITLE
Antiaim (Shaking)

### ISSUE THREAD

**Issue by JacksonDon** [danielkrupinski/Osiris#635]
Hey, 
I know daniel now updated the antiaim::run.. 
But when i only toggle on yaw, and record it like demo or gotv. 
Its still flicking the screen, is there possible some fix ?

**Comment by RadicalRedemption** [comment]
Isn't that caused by the Choked packets? I mean, isn't that normal?

**Comment by littlehurensohn** [comment]
I don't know, but when i toggle off the choked packets the yaw aint works.

**Comment by kavavps1** [comment]
same here
