### ISSUE TITLE
[Question / Suggestion] Player Following Script

### ISSUE THREAD

**Issue by Evilhelder** [danielkrupinski/Osiris#637]
I have a doubt. I found this code in .Lua, it causes the user to follow the defined player (like a blockbot), what would this code in C ++ look like?

P.S .: This code was made for Gmod.

[PF code lua.txt](https://github.com/danielkrupinski/Osiris/files/3683851/PF.code.lua.txt)

**Comment by Bywnb** [comment]
pull requests , ok?

**Comment by anonymouschicken111** [comment]
Copy pasting code from cheats from other games is totally fucking useless, doesn't matter what programming language it's written in.

**Comment by Evilhelder** [comment]
> 
> 
> Copy pasting code from cheats from other games is totally fucking useless, doesn't matter what programming language it's written in.

Not when it comes to the same engine, "CS: S", Gmod, Half life 2 and "CS: GO" share the same engine and some code, I've seen several times people convert GMOD cheats to Left for dead 2, CSS or CSGO itself. I put this code here because I already see something similar done for CSGO (like blockbot or Run boost helper), but I was wondering if it is possible to convert it from moon to C ++.

**Comment by anonymouschicken111** [comment]
Oh sorry I didn't realize Gmod was written in source I that case I will try and help I gueas

**Comment by Evilhelder** [comment]
> 
> 
> Oh sorry I didn't realize Gmod was written in source I that case I will try and help I guess
> Sorry can't reply immediately, different time zones

Don't worry!

**Comment by 0xE232FE** [comment]
If you want to make a Following Bot than you have to learn how Navmesh works.

Here is the best Library that I am using for my WOW and Diablo 3 Bot. The Bots in CSGO uses the same Mesh Navigation System. PPather got the fundamentals from Counter Strike Source Bots in reversing.
https://github.com/namreeb/PPather

Here is the Wikipedia for the Navmesh its quiet old but still brand new!
https://en.wikipedia.org/wiki/Navigation_mesh

Good luck with it! By the way you can hook the Bot function and use it with normal player! If you don't want to implement Navmesh yourself.  ;-)

You need to precalculate the Navmesh for any Map! For World of Warcraft it is quiet huge so I stream the parts of the map from the cloud. It has been about 70 GByte of Navmesh Data from WOW it its current state. This is the only way to have any Game Object that exists on the Map markt with all its collision properties and directions. So the bot is not getting stuck. The first thing I did was a Waypoint system with manual waypoints but the Navmesh is much better you can set a spot and a radius and the bot find its way accross enemies or items that it have to collect from the field. In CSGO there are other possibilites.

Watch also the Walkbot on Aimtux! You can still use Aimtux for this by pulling the AppDate from 2017 from Steam Repository. And look how it works!

best wishes from Montreal and Good Luck!

**Comment by xsincbt** [comment]
@CallieOwO i am new but do u have discord can u just show me how to add this if possible
i know it spoon feeding but i really am struggling  xsin#0170

**Comment by xsincbt** [comment]
@callieOwO my discord got fking banned AGAIN here add my new one xsin#3124
