### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by embern33** [danielkrupinski/Osiris#638]
Why does Windows Defender flag this as a severe threat?

Judging by the amount of people in the issues tab, I doubt it's harmful but would still like to know what the reason is, since it doesn't happen with Rat Poison and Charlatano.

Also, the file that is flagged is called Conteban.B!ml. What does it do?

So looking at the initernet, Conteban is a known trojan, mind explaining why it's in your cheat?

**Comment by anonymouschicken111** [comment]
U fucking retard you have the fucking source without any fucking Trojan how fucking stupid can u be. LOOK AT THE FUCKING CODE BEFORE YOU TALK SHIT. OR BETTER YET LEARN THE FUCKING CODE.

**Comment by anonymouschicken111** [comment]
@danielkrupinski Oh didn't know u look at these issues but I miss u

**Comment by embern33** [comment]
Actually im not fucking retarded. The fact that there is source code for the cheat itself doesn't mean there isn't possibly a virus hidden elsewhere inside the huge amount of files you fucking idiot.

Great there's a source, but there's also a very well known trojan that's sitting right fucking there in my files.

**Comment by JDeu** [comment]
If you had any idea how programming/anti-virus worked you wouldn't have to make this issue

**Comment by 0xE232FE** [comment]
If I put my compiled osiris.dll into Virustotal.com there is 0 Detection!!! WTF are you talking about`?
