### ISSUE TITLE
Question about the game event manager

### ISSUE THREAD

**Issue by effex1337** [danielkrupinski/Osiris#639]
I was trying to add bullet tracers & footstep esp but i never succeeded so i ran a test by printing every event happening in the chat. And events like player_footstep, player_jump, bullet_impact etc dont register. I also replaced the game event manager but still the same issue. And i got no clue why this is happening. @danielkrupinski Please respond if you know something.

An example of what the chat looks like: https://cdn.otaku.ooo/7w9p5.png

**Comment by anonymouschicken111** [comment]
lol same here trying to add footstep esp but I'm failing

**Comment by danielkrupinski** [comment]
You don't have to register event listener, you can check event name in https://github.com/danielkrupinski/Osiris/blob/e9f4c7b54517741a32efdb86202c1e02b9b291e4/Osiris/Hooks.cpp#L307

**Comment by anonymouschicken111** [comment]
Thanks!

**Comment by effex1337** [comment]
Thanks for the reply but i didnt add a listener. I just added a line to print events in the chat right above line 309. 

For printing in console it would be something like
interfaces.engine->clientcmdunrestricted(event->getName());

**Comment by effex1337** [comment]
This is what i get when i add a listener
https://cdn.otaku.ooo/lgr3j.png

My suspicions were correct as player_hurt worked successfully but bullet_impact didn't. 
@danielkrupinski can you confirm on your end please thanks.

**Comment by effex1337** [comment]
That was disappointing.

**Comment by JDeu** [comment]
Have you figured this out? [The constructor isn't very descriptive].(https://github.com/danielkrupinski/Osiris/blob/e9f4c7b54517741a32efdb86202c1e02b9b291e4/Osiris/SDK/GameEventManager.h#L7)

**Comment by xAkiraMiura** [comment]
since this issue is closed I think we should move to either a new or open one. #975
^ `void*` would be a pointer to a specific class that never got implemented.
