### ISSUE TITLE
Knife Changer Bugs

### ISSUE THREAD

**Issue by TheNotoriousAWP** [danielkrupinski/Osiris#64]
Hello, I found a bug with the knife changer on the cheat. When you select a knife, in the bottom right of the screen, the knife icon does not update, and when killing someone with the knife, the icon in the top right (on the kill feed) does not show the icon of the knife selected. It is also slightly buggy when in game as it switches back and forth sometimes between the default knife and the knife that you have selected.

**Comment by adriangames147** [comment]
I think it's okay. The "Knife Changer" only change the model of knife, and nobody can see that. I this is not "bug"

> Hello, I found a bug with the knife changer on the cheat. When you select a knife, in the bottom right of the screen, the knife icon does not update, and when killing someone with the knife, the icon in the top right (on the kill feed) does not show the icon of the knife selected. It is also slightly buggy when in game as it switches back and forth sometimes between the default knife and the knife that you have selected.

**Comment by TheNotoriousAWP** [comment]
no this isn't what I am saying at all. The icon of the knife weapon on the bottom right doesn't update. same when you kill someone. these are in the memory and you can manipulate them. I understand other people can't see them but it is necessary if you  are going to record with this cheat / stream.

**Comment by danielkrupinski** [comment]
This will be fixed when skin changer comes.

**Comment by Hongarc** [comment]
When I change the gun to knife, sometime it shows an origin knife

**Comment by danielkrupinski** [comment]
Fixed
