### ISSUE TITLE
Question About HeadDot

### ISSUE THREAD

**Issue by anonymouschicken111** [danielkrupinski/Osiris#640]
![unevenShit](https://user-images.githubusercontent.com/47711164/66128414-cd9e9500-e613-11e9-9181-bbf82f0c4392.PNG)

I can't figure out a way to make the headDot smaller when enemy is further

```
Vector head{ };
if (worldToScreen(entity->getBonePosition(8), head)) {
	interfaces.surface->setDrawColor(config.headDotColor, 255);
	for (int i = 1; i <= 3; i++)
		interfaces.surface->drawOutlinedCircle(head.x, head.y, i, 100);
}
```

To find distance
```
float distance(Vector src, Vector des)
{
	const float distance = sqrt((src.x - des.x) * (src.x - des.x) + (src.y - des.y) * (src.y - des.y) + (src.z - des.z) * (src.z - des.z));
	return distance;
}
```

You can multiply it by 0.0254f to find meters away from entity
`distanceToEntity *= 0.0254f`

**Comment by Bywnb** [comment]
BonePosition constant , the  size of headDot is also the same , i also dont  know how to change it

**Comment by Laxybaxy** [comment]
you will have to change the radius of the circle:
interfaces.surface->drawOutlinedCircle(head.x, head.y, i, 100); The i is the radius. You might want to use drawFilledCircle instead tho.

**Comment by anonymouschicken111** [comment]
lol daniel didn't or forgot to add a drawFilledCircle function in Surface.h

**Comment by anonymouschicken111** [comment]
I succeeded on finding the distance from enemy.

Code:
```
Vector localPos{ localPlayer->origin() };
Vector entityPos{ entity->origin() };

float distanceToEntity{ distance(localPos, entityPos) };
```

distance() function:
```
float distance(Vector src, Vector des)
{
	//const float distance = src.length() - des.length();
	const float distance = sqrt((src.x - des.x) * (src.x - des.x) + (src.y - des.y) * (src.y - des.y) + (src.z - des.z) * (src.z - des.z));
	//const float distanceInMeters = distance * 0.0254f;
	return distance * 0.0254f;
}
```

**Comment by anonymouschicken111** [comment]
Finally I am done

```
static constexpr void renderHeadDot(Entity* entity) noexcept
{
	if (!config.esp.headDot)
		return;

	Vector head{ };

	if (worldToScreen(entity->getBonePosition(8), head))
	{
		const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());

		Vector localPos{ localPlayer->origin() };
		Vector entityPos{ entity->origin() };

		float distanceToEntity{ distance(localPos, entityPos) };

		int rad{ (int) ceil(39.0f / distanceToEntity) };

		interfaces.surface->drawOutlinedCircle(head.x + 0.5f, head.y - 0.5f, rad, 20);
	}
}
```
The radius is inversely proportional to the distance of entity
y = k / x
I found that 13.f meters has the perfect radius of 3
So,
y = radius, x = distance
3 = k / 13
k = 39

Btw, distance is just pythagoras theorem
