### ISSUE TITLE
Increase Revolver Prepare Time

### ISSUE THREAD

**Issue by hyperxpro** [danielkrupinski/Osiris#641]
Revolver Prepare Time can be increased to "0.242f". It'll give a more short time to fire. 

https://github.com/danielkrupinski/Osiris/blob/f29f20adc537a757838fb62a2742828552d0dcaa/Osiris/Hacks/Misc.cpp#L131

**Comment by VuBrian22** [comment]
Please make a pull request and wait for approval. Pull Requests are for coded suggestions only. While the issues tab is for well, issues/problems. Let's keep it somewhat organized here, Thank you.

**Comment by Bywnb** [comment]
maybe pull request is better
