### ISSUE TITLE
dual mat chams?

### ISSUE THREAD

**Issue by Malilor** [danielkrupinski/Osiris#642]
Does anyone here know how to do like skeet chams? No glow arms race but like dual pass chams? I really would like to know how to do it heres an example of what i mean

https://cdn.discordapp.com/attachments/587599760601645056/627205033494183955/image0.jpg

**Comment by anonymouschicken111** [comment]
Can you further elaborate on what you are saying?

**Comment by Malilor** [comment]
> Can you further elaborate on what you are saying?

From my understanding it uses 2 materials and forces them together not really sure how it works but they look really cool heres another pic 

https://prnt.sc/n25q6y

and heres a video

https://www.youtube.com/watch?v=YhZHgfLyP3s&feature=youtu.be

as you can see this guy is using 3 materials..

**Comment by thomas0aotian** [comment]
dude isn't it just a plastic chams?

**Comment by thomas0aotian** [comment]
or a arm removal + surface glow tho?

**Comment by thomas0aotian** [comment]
the"3 material chams" is prob the arm removal + surface glow + color chams

**Comment by thomas0aotian** [comment]
there are no such a thing as double chams

**Comment by hyperxpro** [comment]
+1

**Comment by effex1337** [comment]
@thomas0aotian well there is actually something like dual passed chams.
masterlooser did that a long time ago with a black ak47 and white outlines(wireframe)
and it was made popular by a leaked cheat named rifk7. That video there is of a friend of mine and i got the codes but he has hard coded it and has used 3 materials for his hand chams.

**Comment by danielkrupinski** [comment]
How many materials do you want? Keep in mind that every extra model draw reduces your fps.

**Comment by effex1337** [comment]
@danielkrupinski heres some code that might help
https://pastebin.com/jFfTnxJc
the guy in the video uses it but its hard coded so i couldn't implement it.

**Comment by effex1337** [comment]
@danielkrupinski 2 materials would be enough as the title suggests

**Comment by Malilor** [comment]
> How many materials do you want? Keep in mind that every extra model draw reduces your fps.

just 2 but please make em sexy like the image : D

**Comment by giangero1** [comment]
id love this feature looks cool :)

**Comment by Oly-UK** [comment]
+rep this, glow on hands would be lit

**Comment by danielkrupinski** [comment]
Added.
