### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by 1-Xycro** [danielkrupinski/Osiris#645]
Please add night mode

**Comment by neazen** [comment]
It's already in the cheat...

**Comment by Evilhelder** [comment]
I have a question, this cheat of changing the map color would be what?

![image](https://user-images.githubusercontent.com/33970481/66260310-67d91700-e793-11e9-911a-683f9c9a8548.png)

**Comment by VuBrian22** [comment]
@Evilhelder Isn't that cheat a private cheat called FlowHooks? I know a Youtube CS:GO cheater, Boring/Noobdog, uses it and it looks awfully similar.

**Comment by Evilhelder** [comment]
> 
> 
> @Evilhelder Isn't that an extremely private cheat called FlowHooks? I know a Youtube CS:GO cheater, Boring/Noobdog, uses it and it looks awfully similar.

Yes it's him, but I've seen this kind of cheat that changes the color of the map texture instead of just putting a color over it ...

**Comment by VuBrian22** [comment]
@Evilhelder Yeah, I have no idea at this point.

**Comment by VuBrian22** [comment]
@Evilhelder Does the old alpha version of Flowhooks have it? If you we can convert it and eventually make a pull request to try to paste it.

**Comment by Evilhelder** [comment]
> 
> 
> @Evilhelder Does the old alpha version of Flowhooks have it? If it does then we can convert it and eventually make a pull request to try to paste it.

Good idea, I'll look for it.

**Comment by furioushell98** [comment]
Visuals tab> look for world colour..
