### ISSUE TITLE
Suggestions: Glow and Chams

### ISSUE THREAD

**Issue by Oly-UK** [danielkrupinski/Osiris#646]
Model And Inner glow non visible 
AND
Backtrack chams non visible

**Comment by neazen** [comment]
Can you elaborate ? you mean like invisible chams/glow ?

**Comment by Oly-UK** [comment]
Yes, like glow style 1 is visible and non visible but both inner glow and model glow only work when the player is visible, also backtracking only has visible option right now

**Comment by thomas0aotian** [comment]
god ur so retarded it doesn't work like that

**Comment by Oly-UK** [comment]
how doesnt it? onetap has it lmao. and fanta has xqz backtrack @thomas0aotian

**Comment by effex1337** [comment]
Xqz backtrack chams are a thing but all of the glow Styles aren't xqz.

**Comment by Oly-UK** [comment]
any idea what onetap do to get it? is it just another style of chams?

**Comment by moonm00n** [comment]
It's a material like any other chams, u can paste it from UC.
