### ISSUE TITLE
Faceit

### ISSUE THREAD

**Issue by 1-Xycro** [danielkrupinski/Osiris#647]
Can we use this cheat on faceit without ban?

**Comment by tirziz** [comment]
I think ESP, charm and bhop are fine

**Comment by anonymouschicken111** [comment]
No, u will get banned

**Comment by Kraken69** [comment]
Why banned?

**Comment by Shaxzy** [comment]
@tirziz
Bhop is detectable

**Comment by 0xE232FE** [comment]
Is Faceit loading CSGO Process under its control? This is how I would protect a Game from Cheats.

**Comment by tirziz** [comment]
> Is Faceit loading CSGO Process under its control? This is how I would protect a Game from Cheats.

only when you have AC client installed

**Comment by 0xE232FE** [comment]
They let you play FaceIT without AC Client installed! How low is this League???!!! Its like ESL without Anticheat....

**Comment by Laxybaxy** [comment]
when you get enough reports you have to enable their anticheat to play

**Comment by anonymouschicken111** [comment]
Ac turned on u got no chance

**Comment by hyperxpro** [comment]
@Kraken69 I currently boosting my account to 50 Hours Playtime. I will test on FaceIT soon and let you know.

**Comment by cojo1989** [comment]
So is working on faceit?

**Comment by hyperxpro** [comment]
> So is working on faceit?

FaceIT needs minimum 50 hours playtime. So boosting it. It'll take maximum 2 days more to boost it and after it is boosted, I'll directly jump into FaceIT match and let you guys know. 

Keep patience!

**Comment by hyperxpro** [comment]
Cheat not getting injected when FaceIT Anti-Cheat is running.

**Comment by anonymouschicken111** [comment]
Esp is useless, server doesn't send out enemy positions u till they are close by so u can only see enemies very close to u, rendering it a bit useless, aimbot.. no chance

**Comment by Havoccboi** [comment]
anyway to inject it?

**Comment by hyperxpro** [comment]
> anyway to inject it?

Not aware of any yet.

**Comment by xAkiraMiura** [comment]
Have you tried running your injector as administrator? I haven't seen how FaceIt AC works.

**Comment by hyperxpro** [comment]
As stated above, I have tested it pretty well. So it's a common sense thing that I've tried all ways including "RUN AS ADMINISTRATOR".

+_+
________________________________

**Comment by madhatterxk** [comment]
so there is no way to use it in face it anti cheat on ?

**Comment by 0xE232FE** [comment]
External Anti-Cheat protect the Game Client by execute it from within the Anticheat to have full Control over CSGO Process. In ESL AC they also inject into Steam Process this is why many Cheats get detected because they only control CSGO Process and ignore Steam Process which is not Protected by VAC but can be protected from 3rd Party Anticheat because there is no VAC Module scanning for modfications inside steam Process atm.

Simple thing is you inject into Faceit Anticheat and from there inject into CSGO Process. It sounds harder than it is ;-)
