### ISSUE TITLE
Commendbot

### ISSUE THREAD

**Issue by Kraken69** [danielkrupinski/Osiris#648]
Please add commend bot so we can improve tf

**Comment by VuBrian22** [comment]
There has already been an issue opened for this matter. On it is also a workaround for your feature. It is located here: https://github.com/danielkrupinski/Osiris/issues/596

**Comment by VuBrian22** [comment]
And you've commented on that issue as well. That needs a Steam API key. Implementing a commend bot in Osiris will also need an API key. That is how this works!!! Don't be dumb and remind the developers about it. THEY KNOW! The just prioritize other important things than this. If you aren't brain dead yet, you can just buy Steam API keys and use them on the BoopFelix Commend Bot.

**Comment by Kraken69** [comment]
Ok
