### ISSUE TITLE
Backtrack chams

### ISSUE THREAD

**Issue by Kraken69** [danielkrupinski/Osiris#649]
Please add backtrack chams too

**Comment by ZPDMiller** [comment]
backtrack chams are already in the cheat

**Comment by anonymouschicken111** [comment]
Dumbass

**Comment by Bywnb** [comment]
**### So you don't have eyes**

**Comment by neazen** [comment]
@Kraken69 could you close your useless issues please....

**Comment by Kraken69** [comment]
Where r they then i cant see?

**Comment by neazen** [comment]
it says "Close issue" in red click on that x)

**Comment by ZPDMiller** [comment]
Under the Chams tab

**Comment by Kraken69** [comment]
.ok
