### ISSUE TITLE
RCS doesnt work anymore

### ISSUE THREAD

**Issue by JayneFrack** [danielkrupinski/Osiris#65]
So when I put rcs on full 1.00 It doesn't work when I shoot a wall, and it doesn't work when I shoot another player either.

**Comment by danielkrupinski** [comment]
It's compensated inside aimbot.

**Comment by didisko33** [comment]
> It's compensated inside aimbot.

@danielkrupinski RCS compensates recoil for 1 sec, then it's just disables. Test it by your own, please. Set fov 30 and smooth ~10 and try to rcs on the enemy.

**Comment by JayneFrack** [comment]
wait so the rcs just works at the start and If I shoot too long I won't hit anthing anymore?

**Comment by TheNotoriousAWP** [comment]
It's because the crosshair has moved too far away from the enemy. Turn the fov up to fix this or the smooth down

**Comment by JayneFrack** [comment]
ok thx
