### ISSUE TITLE
[Suggestion] (Though im kinda tarded) Weapon on ground chams

### ISSUE THREAD

**Issue by You02** [danielkrupinski/Osiris#651]
I have no clue if that is possible, nor if you could do it, but I love using this cheat purely for visual purposes because it's so refined when it comes to that. Keep up the awesome work daniel, we all really love your work!!!!!

**Comment by 0xE232FE** [comment]
There is Glow available for this!

**Comment by You02** [comment]
Yes, there is glow, but chams fill up the whole weapon. I know that there are different types of glows that fill up the weapon, but they are seeable through a wall. Chams would look a lot better nonetheless with these sexy Osiris chams

**Comment by 0xE232FE** [comment]
You might look at chams.cpp there is a caption where weapons get rendered chams. Its a good trial to make WeaponChams on the ground instead stacked at localplayer.

```
void Chams::renderWeapons(void* ctx, void* state, const ModelRenderInfo& info, matrix3x4* customBoneToWorld) const noexcept
{
    const auto localPlayer{ interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer()) };
    if (!localPlayer->isScoped()) {
        auto applied{ false };
        for (size_t i = 0; i < config.chams[WEAPONS].materials.size(); i++) {
            if (config.chams[WEAPONS].materials[i].enabled) {
                if (applied)
                    hooks.modelRender.callOriginal<void, void*, void*, const ModelRenderInfo&, matrix3x4*>(21, ctx, state, info, customBoneToWorld);
                applyChams_2(config.chams[WEAPONS].materials[i], false, localPlayer->health());
                applied = true;
            }
        }
    }    
}
```

**Comment by ThatCouldBeMe** [comment]
I don't know if there's anything else required, but I've checked for strstr "_dropped.mdl" which does return true, but when applying the chams it doesn't actually do anything, is there anything special required?

**Comment by hvher** [comment]
> I don't know if there's anything else required, but I've checked for strstr "_dropped.mdl" which does return true, but when applying the chams it doesn't actually do anything, is there anything special required/am I doing something wrong?

dropped weapons start with "w_", "_dropped" is only for the C4 afaik

**Comment by ThatCouldBeMe** [comment]
> dropped weapons start with "w_", "_dropped" is only for the C4 afaik

From what I tested it doesn't matter, unless there's a special modifier (like mat_wireframe 1), weapons arent passed through DM/DME.

**Comment by You02** [comment]
Did a little research, a free cheat (open source) has weapon on ground chams. If you guys wanted to look into it, its on multiple forums. Im personally too stupid to implement it myself, so I would be grateful if you guys could. Nonetheless thanks for contributing in this topic.
