### ISSUE TITLE
Minor fix

### ISSUE THREAD

**Issue by Jacellen** [danielkrupinski/Osiris#652]
```
> void Misc::fakeBan(bool set) noexcept {
>     static bool shouldSet = false;
>     if (set)
>         shouldSet = set;
>     std::stringstream ss;
>     ss << " \x01\x0B\x07 " << config.misc.banText << " \x01 ";
>     if (shouldSet && interfaces.engine - > isInGame() && changeName(false, ss.str().c_str(), 5.0 f))
>         shouldSet = false;
> }
```

**Comment by VuBrian22** [comment]
It looks like a change to the Fake Ban, Please make a **Pull Request** with Specific details on what you changed. Thank you,

**Comment by danielkrupinski** [comment]
What does it fix?

**Comment by Jacellen** [comment]
@danielkrupinski The color of the fake ban is displayed correctly

**Comment by VuBrian22** [comment]
If that's the case, I believe it's fine the way it is. No errors have occurred when I tried it. And the color displays correctly.

**Comment by VuBrian22** [comment]
> If that's the case, I believe it's fine the way it is. No errors have occurred when I tried it. And the color displays correctly.
