### ISSUE TITLE
Game Ban or VAC ?

### ISSUE THREAD

**Issue by agshaidun** [danielkrupinski/Osiris#653]
So i have 2 account and one of them got Game Ban while another one got VAC . i am using the same dll and same Randoinjector(Already Modified).

Is it detected by VAC ?

VAC
https://steamcommunity.com/profiles/76561198994535285/

Game Ban
https://steamcommunity.com/profiles/76561198994308374/

And i never Rage on both acc . Only using Legit settings

Update : Game Ban turn into VAC after 12 hours

**Comment by Oly-UK** [comment]
it's an open source cheat, of course it is gonna be detected with no edits to the code.

**Comment by agshaidun** [comment]
> 
> 
> it's an open source cheat, of course it is gonna be detected with no edits to the code.

So the junkcode does not work? anyway thanks for telling me

**Comment by Laxybaxy** [comment]
just scramble dll and shit to make it ud

**Comment by hyperxpro** [comment]
> just scramble dll and shit to make it ud

Sorry to say but that's not how VAC works.

**Comment by littlehurensohn** [comment]
On that account where u get banned, u get vac banned in 24hrs.

**Comment by hyperxpro** [comment]
@agshaidun Don't close. This topic needs some discussion.

**Comment by hyperxpro** [comment]
> On that account where u get banned, u get vac banned in 24hrs.

Many of my accounts got Game Ban using Osiris Aimbot (Random Throwaway Accounts) but they were never converted to VAC Ban (or Delayed VAC Ban) later on.

**Comment by agshaidun** [comment]
> 
> 
> @agshaidun Don't close. This topic needs some discussion.

sorry i missclicked*

**Comment by littlehurensohn** [comment]
> > On that account where u get banned, u get vac banned in 24hrs.
> 
> Many of my accounts got Game Ban using Osiris Aimbot (Random Throwaway Accounts) but they were never converted to VAC Ban (or Delayed VAC Ban) later on.

Yeah, but still is there a question, why? 
Cause I was looking and aimbot is clamped where is problem?

**Comment by hyperxpro** [comment]
@danielkrupinski Thoughts?

**Comment by hyperxpro** [comment]
> > > On that account where u get banned, u get vac banned in 24hrs.
> > 
> > 
> > Many of my accounts got Game Ban using Osiris Aimbot (Random Throwaway Accounts) but they were never converted to VAC Ban (or Delayed VAC Ban) later on.
> 
> Yeah, but still is there a question, why?
> Cause I was looking and aimbot is clamped where is problem?

AIMWARE.net. This cheat changes its signature every time user downloads it from its website. And each file will run only once. But AIMWARE users also get VAC Ban in VAC Wave. So, I am pretty sure Signatures don't have much to do.

**Comment by littlehurensohn** [comment]
Yeah thats true, I think valve find some way how to detect aimbot. 
But now is another question.. 
How the fuck can skeet bypass it?

**Comment by hyperxpro** [comment]
> Yeah thats true, I think valve find some way how to detect aimbot.
> But now is another question..
> How the fuck can skeet bypass it?

Maybe that's what makes Skeet different from AIMWARE.net. I am testing something. Can you give me a list of cheats which are VAC Detected? I need cheats that give VAC Ban just after using it so I can test whether my method hides it or not.

**Comment by littlehurensohn** [comment]
Bro I dont know.. 
Im not fam of free cheats :D 
I used free cheat like 2 years ago, and it was for hvh ;d

**Comment by Evilhelder** [comment]
I use a VM program to change the DLL code, and so not from Vac ban.

**Comment by 0xE232FE** [comment]
1. Game Ban
2. 24 hrs later VAC Ban
-> Injector is mostly detected in combination with osiris.
Mostly they make something that detects an Injector in combination with specific parts of a dll. This is mostly the start of a bigger detection. And first hint that Valve is doing something.

Did you try VAC disabler?

**Comment by Shaxzy** [comment]
@littlehurensohn because skeet is «private». In order to make it detected a valve employee must get invited to the cheat I guess which may not be very easy. I’m a skeeter myself and it took me a long time to get invited, ngl

**Comment by littlehurensohn** [comment]
> @littlehurensohn because skeet is «private». In order to make it detected a valve employee must get invited to the cheat I guess which may not be very easy. I’m a skeeter myself and it took me a long time to get invited, ngl

I trying to get skeet like 3 years, and still nothing. 
Sice was i playing hvh, just congratulation for you.

**Comment by RadicalRedemption** [comment]
Is there any open-source anti-vac?

**Comment by hyperxpro** [comment]
> @littlehurensohn because skeet is «private». In order to make it detected a valve employee must get invited to the cheat I guess which may not be very easy. I’m a skeeter myself and it took me a long time to get invited, ngl

Sorry to say, there is a difference between "PRIVATE" and "RESTRICTED". Skeet is not private, it's restricted. People pay $100 and get Skeet the invite code. 

P.S- Skeet is now gamesense.pub.

**Comment by hyperxpro** [comment]
> Is there any open-source anti-vac?

There is nothing called "ANTI-VAC".

**Comment by hyperxpro** [comment]
@agshaidun Looks like both of your accounts got VAC Ban, Well, here is my account banned for Hardcore Ragebot using Osiris.

For now, its Game Ban. Let's see if it converts to VAC Ban.

https://steamcommunity.com/profiles/76561198995743530/

**Comment by 0xE232FE** [comment]
This Accounts were legit but I was using manual-map inflames injector.
https://steamcommunity.com/profiles/76561198982927159/
https://steamcommunity.com/profiles/76561198973010109/
https://steamcommunity.com/profiles/76561198988597959/

I have 3 other Accounts that use inflames with load-libraryA Mode they are **NOT** game ban + vac ban

**Comment by hyperxpro** [comment]
@agshaidun Can you send me your Injector + DLL which got you VAC Ban? I wanna test myself.

Send here: aayush@shieldblaze.com

**Comment by agshaidun** [comment]
> @agshaidun Can you send me your Injector + DLL which got you VAC Ban? I wanna test myself.
> 
> Send here: [aayush@shieldblaze.com](mailto:aayush@shieldblaze.com)

Check ur email

**Comment by hyperxpro** [comment]
> > @agshaidun Can you send me your Injector + DLL which got you VAC Ban? I wanna test myself.
> > Send here: [aayush@shieldblaze.com](mailto:aayush@shieldblaze.com)
> 
> Check ur email

Got it. I'll check and let you know soon.

**Comment by agshaidun** [comment]
> 1. Game Ban
> 2. 24 hrs later VAC Ban
>    -> Injector is mostly detected in combination with osiris.
>    Mostly they make something that detects an Injector in combination with specific parts of a dll. This is mostly the start of a bigger detection. And first hint that Valve is doing something.
> 
> Did you try VAC disabler?
> 
> @Evilhelder There is nothing what VMProtect can do here. VMProtect is just a meme myth that People telling but it doesn't prevent VAC. Mainly you put your Account on risk because Valve can easily figure out VMProtect Code and ban you for using it. Its like a big signature that makes a DLL suspicious to VAC. So do not use VMProtect at all and don't eat lies from other people!

For this 2 acc i am not using Vac disabler . only using randoinject .

**Comment by agshaidun** [comment]
Is there any Osiris user who has used osiris for a long time without getting ban?

**Comment by AbdallahMehiz** [comment]
i guess me
i used osiris since april 2019 and didn't get vac since
i only get ow bans

**Comment by AbdallahMehiz** [comment]
i use an injector that isn't very popular but it does the job for me for every cheat
and i love it :D u want link ?

**Comment by agshaidun** [comment]
> i use an injector that isn't very popular but it does the job for me for every cheat
> and i love it :D u want link ?

Sure :)) . Email me  agshaidun@gmail.com

**Comment by littlehurensohn** [comment]
> i use an injector that isn't very popular but it does the job for me for every cheat
> and i love it :D u want link ?

Me tho please <3 vojtikcz2001@gmail.com thanks <3

**Comment by AbdallahMehiz** [comment]
i didn't change anything in the files
i just download the code and compile it
injector link[injector link](https://mega.nz/#!LjoWlQ7S!Wew7EdrsVcojPbxh9yPSNjN7ze1HRo-K-VJjU1EksDg)

**Comment by AbdallahMehiz** [comment]
> > i use an injector that isn't very popular but it does the job for me for every cheat
> > and i love it :D u want link ?
> 
> Btw are u using Vac disabler and VMprotect? Did you modified the cpp file?

i don't use any of these

**Comment by RadicalRedemption** [comment]
> 
> 
> > 1. Game Ban
> > 2. 24 hrs later VAC Ban
> >    -> Injector is mostly detected in combination with osiris.
> >    Mostly they make something that detects an Injector in combination with specific parts of a dll. This is mostly the start of a bigger detection. And first hint that Valve is doing something.
> > 
> > Did you try VAC disabler?
> > @Evilhelder There is nothing what VMProtect can do here. VMProtect is just a meme myth that People telling but it doesn't prevent VAC. Mainly you put your Account on risk because Valve can easily figure out VMProtect Code and ban you for using it. Its like a big signature that makes a DLL suspicious to VAC. So do not use VMProtect at all and don't eat lies from other people!
> 
> For this 2 acc i am not using Vac disabler . only using randoinject .

What VAC disabler are you using?

**Comment by agshaidun** [comment]
> > > 1. Game Ban
> > > 2. 24 hrs later VAC Ban
> > >    -> Injector is mostly detected in combination with osiris.
> > >    Mostly they make something that detects an Injector in combination with specific parts of a dll. This is mostly the start of a bigger detection. And first hint that Valve is doing something.
> > > 
> > > Did you try VAC disabler?
> > > @Evilhelder There is nothing what VMProtect can do here. VMProtect is just a meme myth that People telling but it doesn't prevent VAC. Mainly you put your Account on risk because Valve can easily figure out VMProtect Code and ban you for using it. Its like a big signature that makes a DLL suspicious to VAC. So do not use VMProtect at all and don't eat lies from other people!
> > 
> > 
> > For this 2 acc i am not using Vac disabler . only using randoinject .
> 
> What VAC disabler are you using?

https://github.com/danielkrupinski/VAC-Bypass

**Comment by hyperxpro** [comment]
> > > > 1. Game Ban
> > > > 2. 24 hrs later VAC Ban
> > > >    -> Injector is mostly detected in combination with osiris.
> > > >    Mostly they make something that detects an Injector in combination with specific parts of a dll. This is mostly the start of a bigger detection. And first hint that Valve is doing something.
> > > > 
> > > > Did you try VAC disabler?
> > > > @Evilhelder There is nothing what VMProtect can do here. VMProtect is just a meme myth that People telling but it doesn't prevent VAC. Mainly you put your Account on risk because Valve can easily figure out VMProtect Code and ban you for using it. Its like a big signature that makes a DLL suspicious to VAC. So do not use VMProtect at all and don't eat lies from other people!
> > > 
> > > 
> > > For this 2 acc i am not using Vac disabler . only using randoinject .
> > 
> > 
> > What VAC disabler are you using?
> 
> https://github.com/danielkrupinski/VAC-Bypass

Just my personal preference. Hiding is better than Bypass. You don't know when bypass stops working.

**Comment by molendus1001** [comment]
> i didn't change anything in the files
> i just download the code and compile it
> [injector link](https://mega.nz/#!LjoWlQ7S!Wew7EdrsVcojPbxh9yPSNjN7ze1HRo-K-VJjU1EksDg)

We hope you know what you're doing, if you just shared same exact injector build that you use, then noone will be surprised if this will be your first vac ban

**Comment by furioushell98** [comment]
@AbdallahMehiz wtf? A 20mb injector? Seems suspicious..
Junkcode/vmprotect doesn't do shit, you need to edit the code and add/remove features, to change the signature and make the cheat undetected.

**Comment by AbdallahMehiz** [comment]
> @AbdallahMehiz wtf? A 20mb injector? Seems suspicious..
> Junkcode/vmprotect doesn't do shit, you need to edit the code and add/remove features, to change the signature and make the cheat undetected.

well
i downloaded this injector from a guy on youtube named votrix
when he posted a free cheat that i actually liked :D
I think the name of the cheat was "XY0" or something i don't know, and the injector was with the cheat's dll so i used it since, i had no problem with it but u can talk with the injector' creator gerasss from MPGH.net

**Comment by furioushell98** [comment]
@AbdallahMehiz i use Gerasss injector as well lol, undetected since a lot of time. I guess i never noticed the size cuz 20mb is definitely too big for a cheat tbh, sorry my bad. You should check the injector from Mpgh though, i trust Mpgh but not Votrix

**Comment by igre3zy** [comment]
Is tempoinjector safe?

**Comment by thomas0aotian** [comment]
i think i am the oldest fan of daniel

**Comment by thomas0aotian** [comment]
Haven't get VAC banned ever since then,I don't even get ow ban thay often.Maybe let's say 1 or 2 times a year. My injector is vac ud for every possible csgo cheat. Idk what has been built inside of the injector but i have never been vac banned for cheating in csgo ever since that I got this injector. i do not have to do any manual manipulation to the source. i can use this injector to easily avoid.gettomg vac banned. and yeah i am a well experienced csfo cheater/hvher

**Comment by agshaidun** [comment]
> @AbdallahMehiz i use Gerasss injector as well lol, undetected since a lot of time. I guess i never noticed the size cuz 20mb is definitely too big for a cheat or an injector or any cs hacking tool tbh, sorry my bad. You should check the injector from Mpgh though, i trust Mpgh but not Votrix
> @agshaidun do you get global cooldown in game main menu? If yes then fuck Randoinjector, use Gerass injector but get it from Mpgh

Yeah but not all acc . Sometimes VAC too

**Comment by AbdallahMehiz** [comment]
> @AbdallahMehiz i use Gerasss injector as well lol, undetected since a lot of time. I guess i never noticed the size cuz 20mb is definitely too big for a cheat or an injector or any cs hacking tool tbh, sorry my bad. You should check the injector from Mpgh though, i trust Mpgh but not Votrix
> @agshaidun do you get global cooldown in game main menu? If yes then fuck Randoinjector, use Gerass injector but get it from Mpgh

every time xd
i get GLOBAL COOLDOWN not account untrusted or any of that

**Comment by Laxybaxy** [comment]
Have been using the cheat for a long time on same acc(5+months), not banned yet.
I do not use the aimbot tho, also using randoinjector

**Comment by agshaidun** [comment]
> Have been using the cheat for a long time on same acc(5+months), not banned yet.
> I do not use the aimbot tho, also using randoinjector

Cpp edit? Did you use VMprotect?

**Comment by littlehurensohn** [comment]
> > Have been using the cheat for a long time on same acc(5+months), not banned yet.
> > I do not use the aimbot tho, also using randoinjector
> 
> Cpp edit? Did you use VMprotect?

Add too many junkcodes, disable optimalization > profit

TBh.. JOKE xd

**Comment by hyperxpro** [comment]
> > > Have been using the cheat for a long time on same acc(5+months), not banned yet.
> > > I do not use the aimbot tho, also using randoinjector
> > 
> > 
> > Cpp edit? Did you use VMprotect?
> 
> Add too many junkcodes, disable optimalization > profit
> 
> TBh.. JOKE xd

Editing source code, adding junk stuff, etc could be the most stupid suggestions I'd imagine.

**Comment by hyperxpro** [comment]
@agshaidun Your Injector is detected. I got 2 times "Your Account is Untrusted" error.

**Comment by hyperxpro** [comment]
I'd suggest using Source Code Obfuscate when compiling Osiris. It'll obfuscate the DLL file and make it impossible for VAC to detect it as any kinda hack because when VAC will look into Injected DLL, it'll find garbage inside DLL. 

Obfuscation is the way to go not adding junk code like blind noobs.

**Comment by hyperxpro** [comment]
I'd suggest using Source Code Obfuscator when compiling Osiris. It'll obfuscate the DLL file and make it impossible for VAC to detect it as any kinda hack because when VAC will look into Injected DLL, it'll find garbage inside DLL.

Obfuscation is the way to go not adding junk code like blind noobs.

**Comment by thomas0aotian** [comment]
@hyperxpro u r such a fucking noob,u dont know nothing about vac system,so why dont u just stfu and listen.
getting vac authentication error it's because u r using anti-aim fakelag or wide fov silent aim in any vac authenticated server. And mm is known as not vac authenticated server. So u can fucking spin however u want without getting vacae but def ow or vac. But u can't spin in casual wothout getting vacae,this system is different from mm vac,it detect unhumanized behavior in which mm could allow. 
UNDERSTAND? RETARD

**Comment by hyperxpro** [comment]
> @hyperxpro u r such a fucking noob,u dont know nothing about vac system,so why dont u just stfu and listen.
> getting vac authentication error it's because u r using anti-aim fakelag or wide fov silent aim in any vac authenticated server. And mm is known as not vac authenticated server. So u can fucking spin however u want without getting vacae but def ow or vac. But u can't spin in casual wothout getting vacae,this system is different from mm vac,it detect unhumanized behavior in which mm could allow.
> UNDERSTAND? RETARD

I'm really sorry to break your imagination but Rage Hack from Casual to War Games to Matchmaking and I never get any VAC Error. Why cry when you don't know anything?

P.S- Join English classes kid. It'll help.

**Comment by hyperxpro** [comment]
> @hyperxpro u r such a fucking noob,u dont know nothing about vac system,so why dont u just stfu and listen.
> getting vac authentication error it's because u r using anti-aim fakelag or wide fov silent aim in any vac authenticated server. And mm is known as not vac authenticated server. So u can fucking spin however u want without getting vacae but def ow or vac. But u can't spin in casual wothout getting vacae,this system is different from mm vac,it detect unhumanized behavior in which mm could allow.
> UNDERSTAND? RETARD

I'm really sorry to break your imagination but I Rage Hack from Casual to War Games to Matchmaking and I never get any VAC Error. Why cry when you don't know anything?

P.S- Join English classes kid. It'll help.

**Comment by agshaidun** [comment]
> @agshaidun Your Injector is detected. I got 2 times "Your Account is Untrusted" error.

Rip my injector

**Comment by hyperxpro** [comment]
> > @agshaidun Your Injector is detected. I got 2 times "Your Account is Untrusted" error.
> 
> Rip my injector

Try Rando-Injector or Daniel's MemJect. And look for source code obfuscation.

**Comment by agshaidun** [comment]
> > > @agshaidun Your Injector is detected. I got 2 times "Your Account is Untrusted" error.
> > 
> > 
> > Rip my injector
> 
> Try Rando-Injector or Daniel's MemJect. And look for source code obfuscation.

Can i try your injector?

**Comment by hyperxpro** [comment]
> > > > @agshaidun Your Injector is detected. I got 2 times "Your Account is Untrusted" error.
> > > 
> > > 
> > > Rip my injector
> > 
> > 
> > Try Rando-Injector or Daniel's MemJect. And look for source code obfuscation.
> 
> Can i try your injector?

Replying back on your Email.

**Comment by agshaidun** [comment]
> > > > > @agshaidun Your Injector is detected. I got 2 times "Your Account is Untrusted" error.
> > > > 
> > > > 
> > > > Rip my injector
> > > 
> > > 
> > > Try Rando-Injector or Daniel's MemJect. And look for source code obfuscation.
> > 
> > 
> > Can i try your injector?
> 
> Replying back on your Email.

ok

**Comment by hyperxpro** [comment]
@agshaidun Sent. Try it and let me know if you get Ban again on Legit settings.

**Comment by 0xE232FE** [comment]
> about Obfuscation

I am using compile time String encryption like most papa malware do. This changes .text area of the DLL on every compilation. Mostly VAC is able to look for static string patterns like Aimbot, Triggerbot, Wallhack etc. in this area.

For Obfuscation you go with [LLVM](https://llvm.org/)

For get rid of VAC Ban just by pass VAC.

**Comment by AbdallahMehiz** [comment]
guys, did anyo!ne get vac banned from my "gerassss" injector ?
i didn't yet

**Comment by 0xE232FE** [comment]
@AbdallahMehiz I didn't try yours. But my injector is still fine. Beside Manual-Map is detected, just use loadlibraryA!

**Comment by AbdallahMehiz** [comment]
> @AbdallahMehiz I didn't try yours. But my injector is still fine. Beside Manual-Map is detected, just use loadlibraryA!

still didn't xd

**Comment by 0xE232FE** [comment]
Dude 20 MByte .text area?
```
Name Virtual Address Virtual Size Raw Size Entropy MD5
.text 4096 18153922 18153984 5.85 ed9075cf948c11d3483dd8565cdfc9f3
.rdata 18161664 2974070 2974208 4.64 0d78b3e30437201ba641aaccdd18332b
.data 21139456 19696 12800 4.66 143d3f21773cad659aca94bf1b006588
.rsrc 21159936 480 512 4.73 21f1eced7745cc7f1ee93bd6a622d986
.reloc 21164032 780108 780288 6.82 2e11681cc184a2f8c3dd5e643e06f358
```

You do know how to code an injector?

1. Inject into legit Process like Teamviewer or Geforce Experience.
2. Load Encrypted dll into memory 
3. Attach from legit Process to csgo.exe
4. do shit LoadlibraryA from legit process.
5. profit.

This is how I inject into csgo.exe. Just impersonate a legit Program.

**Comment by hyperxpro** [comment]
> > about Obfuscation
> 
> I am using compile time String encryption like most papa malware do. This changes .text area of the DLL on every compilation. Mostly VAC is able to look for static string patterns like Aimbot, Triggerbot, Wallhack etc. in this area.
> 
> For Obfuscation you go with [LLVM](https://llvm.org/) and [clang](https://clang.llvm.org/)
> 
> For get rid of VAC Ban just by pass VAC.

String Obfuscation is to hide critical information stored in String. Let's say, a REST API Endpoint or some type of Secret Key. You need Source Code Obfuscation to hide it from VAC,, not String Obfuscation.

**Comment by hyperxpro** [comment]
> > about Obfuscation
> 
> I am using compile time String encryption like most papa malware do. This changes .text area of the DLL on every compilation. Mostly VAC is able to look for static string patterns like Aimbot, Triggerbot, Wallhack etc. in this area.
> 
> For Obfuscation you go with [LLVM](https://llvm.org/) and [clang](https://clang.llvm.org/)
> 
> For get rid of VAC Ban just by pass VAC.

String Obfuscation is to hide critical information stored in String. Let's say, a REST API Endpoint or some type of Secret Key. You need Source Code Obfuscation to hide it from VAC, not String Obfuscation.

**Comment by hyperxpro** [comment]
> Dude 20 MByte .text area?
> 
> ```
> Name Virtual Address Virtual Size Raw Size Entropy MD5
> .text 4096 18153922 18153984 5.85 ed9075cf948c11d3483dd8565cdfc9f3
> .rdata 18161664 2974070 2974208 4.64 0d78b3e30437201ba641aaccdd18332b
> .data 21139456 19696 12800 4.66 143d3f21773cad659aca94bf1b006588
> .rsrc 21159936 480 512 4.73 21f1eced7745cc7f1ee93bd6a622d986
> .reloc 21164032 780108 780288 6.82 2e11681cc184a2f8c3dd5e643e06f358
> ```
> 
> You do know how to code an injector?
> 
> 1. Inject into legit Process like Teamviewer or Geforce Experience.
> 2. Load Encrypted dll into memory
> 3. Attach from legit Process to csgo.exe
> 4. do shit LoadlibraryA from legit process.
> 5. profit.
> 
> This is how I inject into csgo.exe. Just impersonate a legit Program.
> 
> Why is your injector communicating with this Servers?
> 50.23.197.94 <- Payload
> 204.140.20.21 <- Payload
> 201.7.169.50 <- Communication with restapi? WTF
> xred.mooo.com <- Payload
> freedns.afraid.org <- Registering an Account there for dynamic dns updates.

How you so sure about this? How did you check? Send me that Injector too. Seems interesting.

**Comment by 0xE232FE** [comment]
He linked the executable everyone can download it. So becareful executing it on your own computer!

**Comment by hyperxpro** [comment]
> He linked the executable everyone can download it. So becareful executing it on your own computer!

No one can do shit to my Computer. It's like NSA Security. xD 

I will test and let you know.

**Comment by 0xE232FE** [comment]
I check for the domain **xred.mooo.com** it is used to serve several malware payloads. Over 8000 samples. XD

**Comment by Laxybaxy** [comment]
> > Have been using the cheat for a long time on same acc(5+months), not banned yet.
> > I do not use the aimbot tho, also using randoinjector
> 
> Cpp edit? Did you use VMprotect?

well, i added functions and my own gui to it so yeah, no vmprotect tho

**Comment by hyperxpro** [comment]
@agshaidun Did you got change to test my method which I sent over the Email?

**Comment by furioushell98** [comment]
@hyperxpro could you mention a github link/ a tool that obfuscates a cpp code (osiris) ?

**Comment by woah1337** [comment]
Lol I love this autism

**Comment by hyperxpro** [comment]
> @hyperxpro could you mention a github link/ a tool that obfuscates a cpp code (osiris) ?

Here you go: https://github.com/kgretzky/obfusion

**Comment by AbdallahMehiz** [comment]
can this thread be closed now ?
we know that the cheat isn't detected YET 
and we know that the vac bannes occured are because of detected injectors in combination with the cheat

**Comment by hyperxpro** [comment]
> can this thread be closed now ?
> we know that the cheat isn't detected YET
> and we know that the vac bannes occured are because of detected injectors in combination with the cheat

Waiting for @agshaidun response on my Injector.

**Comment by agshaidun** [comment]
> > can this thread be closed now ?
> > we know that the cheat isn't detected YET
> > and we know that the vac bannes occured are because of detected injectors in combination with the cheat
> 
> Waiting for @agshaidun response on my Injector.

No VAC bro so far.  Already tried on 3 acc

**Comment by hyperxpro** [comment]
> > > can this thread be closed now ?
> > > we know that the cheat isn't detected YET
> > > and we know that the vac bannes occured are because of detected injectors in combination with the cheat
> > 
> > 
> > Waiting for @agshaidun response on my Injector.
> 
> No VAC bro so far. Already tried on 3 acc

Cool. So my Injector works properly?

**Comment by agshaidun** [comment]
> > > > can this thread be closed now ?
> > > > we know that the cheat isn't detected YET
> > > > and we know that the vac bannes occured are because of detected injectors in combination with the cheat
> > > 
> > > 
> > > Waiting for @agshaidun response on my Injector.
> > 
> > 
> > No VAC bro so far. Already tried on 3 acc
> 
> Cool. So my Injector works properly?

Yeah. No glitch or crash . I hope it will not detected for a long time

**Comment by hyperxpro** [comment]
> > > > > can this thread be closed now ?
> > > > > we know that the cheat isn't detected YET
> > > > > and we know that the vac bannes occured are because of detected injectors in combination with the cheat
> > > > 
> > > > 
> > > > Waiting for @agshaidun response on my Injector.
> > > 
> > > 
> > > No VAC bro so far. Already tried on 3 acc
> > 
> > 
> > Cool. So my Injector works properly?
> 
> Yeah. No glitch or crash . I hope it will not detected for a long time

Cool. Get back to me on GitHub or over the Email if you need something.

You can close this issue now.

**Comment by agshaidun** [comment]
> > > > > > can this thread be closed now ?
> > > > > > we know that the cheat isn't detected YET
> > > > > > and we know that the vac bannes occured are because of detected injectors in combination with the cheat
> > > > > 
> > > > > 
> > > > > Waiting for @agshaidun response on my Injector.
> > > > 
> > > > 
> > > > No VAC bro so far. Already tried on 3 acc
> > > 
> > > 
> > > Cool. So my Injector works properly?
> > 
> > 
> > Yeah. No glitch or crash . I hope it will not detected for a long time
> 
> Cool. Get back to me on GitHub or over the Email if you need something.
> 
> You can close this issue now.

Alright
