### ISSUE TITLE
An Easy Request

### ISSUE THREAD

**Issue by AbdallahMehiz** [danielkrupinski/Osiris#656]
Like the rank revealer.. can you @danielkrupinski make money revealer?
jut like the esp one but the money of the enemies is shown in the scoreboard
it would be a good addition

**Comment by anonymouschicken111** [comment]
It's really easy just add Netvar to Entity.h and add text to esp and add option to gui and config(optional)

**Comment by hyperxpro** [comment]
> It's really easy just add Netvar to Entity.h and add text to esp and add option to gui and config(optional)
> m_iAccount

If it's really so easy for you, why not add code?

**Comment by AbdallahMehiz** [comment]
> > It's really easy just add Netvar to Entity.h and add text to esp and add option to gui and config(optional)
> > m_iAccount
> 
> If it's really so easy for you, why not add code?

i am new to coding and litrally only know the basics of c++

**Comment by sonicrules11** [comment]
> > It's really easy just add Netvar to Entity.h and add text to esp and add option to gui and config(optional)
> > m_iAccount
> 
> If it's really so easy for you, why not add code?

Because he isnt the one that requested it lmao

**Comment by 0xE232FE** [comment]
It's already in Entity.h
https://github.com/danielkrupinski/Osiris/blob/5d3f2ca38e3c1dce25b23999b8c8db3c6cf0c00b/Osiris/SDK/Entity.h#L266

You need to compare rank-revealer here which draws the ranks on scoreboard. Money should work same.

**Comment by anonymouschicken111** [comment]
Sorry I thought u meant to draw money in esp
but if u really want this I am post the code

**Comment by AbdallahMehiz** [comment]
> Sorry I thought u meant to draw money in esp
> but if u really want this I can post the code

xd please so i can predict what the other team has in term of equipements and weapons
also can you PLEASE add event log ?
like what the enemies bought and where is the bomb and how much damage have i done to someone and a lot of other stuff, and appears in console

**Comment by AbdallahMehiz** [comment]
I may close this

**Comment by danielkrupinski** [comment]
Added scoreboard money revealer. Unfortunately money updates only for non-dormant enemies.
