### ISSUE TITLE
Free XP

### ISSUE THREAD

**Issue by Kraken69** [danielkrupinski/Osiris#657]
Can i use name stealer + anti afk kick + console command +left in casual and just leave my game on to get easy xp? Will i get ow?

**Comment by anonymouschicken111** [comment]
It's casual dummy so no u won't get owned, and u won't get any exp with 0 kills

**Comment by Finndramere** [comment]
kinda useless and a waste of electricity tbh. I tried to turn on ragebot overnight with name stealer on. I didnt gain that much exp. But if ur looking to just boost ur hours played just use steam idle.

**Comment by Kraken69** [comment]
Yea just tried got no xp gon close this
