### ISSUE TITLE
Backtracking Issue

### ISSUE THREAD

**Issue by sundafused** [danielkrupinski/Osiris#658]
Hey, I noticed that backtracking isn't working at all for me, even when I have at least 1 choked packet. I'm not sure what the issue is. 
Thank you in advance!

**Comment by CallieOwO** [comment]
Send your config file or a screenshot of all tabs/windows

**Comment by sundafused** [comment]
[legit.txt](https://github.com/danielkrupinski/Osiris/files/3721334/legit.txt)

I changed it to a .txt file, so you can actually look at it.

**Comment by CallieOwO** [comment]
https://i.gyazo.com/b2a4479b92cf44727abf92a1ebe4d53e.mp4 it seems to work for me with that config? I just enabled backtrack chams and set choked packets to 0. It does seem overall a bit inaccurate but I think thats a cheat issue and not really a you issue in its self so either sprinkle a little pasta or hopefully the dev fixes it.
