### ISSUE TITLE
Suggestion: Add Bone ESP 

### ISSUE THREAD

**Issue by BobH233** [danielkrupinski/Osiris#665]
Can you add bone ESP at ESP.cpp please.
We can get enemy's status clearly by this.

**Comment by anonymouschicken111** [comment]
Dm me I can help u, but u need to understand a bit of programming

**Comment by BohanRen** [comment]
Sorry,Enemy's action

**Comment by BohanRen** [comment]
I've just tried to use offset to get Bone position.But the point is different models have different bone node ID

**Comment by anonymouschicken111** [comment]
I will try, when I succeed to will post source here

**Comment by Laxybaxy** [comment]
Just find parent bones

**Comment by CallieOwO** [comment]
If you're implying you can see when the enemy reloads, crouches, etc then you can use glow for that but I understand if you think bones is more stylish or easier to see in a way. +1 on the suggestion.

**Comment by anonymouschicken111** [comment]
Draw lines across parent bones
