### ISSUE TITLE
[Help] Get "m_iCompetitiveWins" and "m_iCompetitiveRanking" from <DT_CSPlayerResource>

### ISSUE THREAD

**Issue by Floraly** [danielkrupinski/Osiris#668]
Hello Everyone,

can someone help me to get the Rank and Wins from the DataTable CSPlayerResource?

I added this to entity.h

Edit: DT_CSPlayerResource to CCSPlayerResource
```
	NETVAR_OFFSET(CompetitiveRanking, "CCSPlayerResource", "m_iCompetitiveRanking", 4, int);
	NETVAR_OFFSET(CompetitiveWins, "CCSPlayerResource", "m_iCompetitiveWins", 4, int);
```

Now I can use **entity->CompetitiveWins()** and **entity->CompetitiveRanking()** what I know is that its a Table where I need entity->CompetitiveRanking() + entity->Index() so I should get the Address where the Rank or Win Count in Type int is stored.

How do I get the Integer from there?

My try was something like this:
```
renderPositionedText(config.font, (std::wostringstream{ } << std::fixed << std::showpoint << std::setprecision(2) << ( (int*)((uintptr_t)entity->CompetitiveWins() + entity->index() * 4)   )  << L'W').str().c_str(), config.distanceColor, { bbox.right + 5, drawPositionY });

renderPositionedText(config.font, (std::wostringstream{ } << std::fixed << std::showpoint << std::setprecision(2) << ( (int*)((uintptr_t)entity->CompetitiveRanking() + entity->index() * 4) )  << L'R').str().c_str(), config.distanceColor, { bbox.right + 5, drawPositionY });

```

**Comment by effex1337** [comment]
Edit that DT_ TO JUST C

**Comment by 0xE232FE** [comment]
I changed it to **CCSPlayerResource** I get the same Offsets O.o so it doesn't matter if I use DT_ or C. Nice help :-)

**Comment by 0xE232FE** [comment]
Additionally I think you need the PlayerResource Offset.
The actual Pattern is as follows.

PlayerResource = findPattern(L"client_panorama", "\x8B\x3D????\x85\xFF\x0F\x84????\x81\xC7", 2);

**Comment by steel4me** [comment]
Did it work? Would be nice to know. Is there a branch where it has already been implemented?
