### ISSUE TITLE
How can I change the rcs back to the old one

### ISSUE THREAD

**Issue by JayneFrack** [danielkrupinski/Osiris#67]
Hi I really liked the old rcs were the rcs worked perfect but the crosshair didn't move along with it. Is there a way to change the rcs back to the old one but make the crosshair follow the recoil control correctly.

**Comment by JayneFrack** [comment]
I don't like the new rcs because I have to set the smooth pretty low to make it work somewhat properly. And setting the smooth lower makes it kind of more obvious.

**Comment by didisko33** [comment]
Check the commits and paste the previous one.
https://github.com/danielkrupinski/Osiris/commits/master

**Comment by JayneFrack** [comment]
Yeah the new rcs is verry legit but it doesnt work that good because I need low smooth which makes it look less legit. And in the old rcs it works perfect just that on your screen it doesnt look as if you would recoil control, And after the shots the crosshair kind of jumps back to the enemy which looks weird do you know how to fix that?
