### ISSUE TITLE
how to see aa when activated 

### ISSUE THREAD

**Issue by xsincbt** [danielkrupinski/Osiris#670]
how to see aa when activated

**Comment by VuBrian22** [comment]
Go into third person mode. It depends on what you binded that key as. For my convenience, I mapped my third person as X in the cheat GUI.

**Comment by xsincbt** [comment]
But I turned it on with choked packet but still can't see it and I was in third person

**Comment by VuBrian22** [comment]
Hmm Interesting.......It should work perfectly fine. idk why it doesn't work for you.

**Comment by xsincbt** [comment]
Ok thanks I will give it a try I think my aa works but I don't see it
