### ISSUE TITLE
(Suggestions)world grenade prediction

### ISSUE THREAD

**Issue by xsincbt** [danielkrupinski/Osiris#671]
Does anyone know how to do this
To where you can see your teammates/enemys grenade

**Comment by anonymouschicken111** [comment]
Don't think that's possible

**Comment by hyperxpro** [comment]
> Does anyone know how to do this
> To where you can see your teammates/enemys grenade

You can predict yourself with Glow and little bit of Brain.

**Comment by Evilhelder** [comment]
> 
> 
> Don't think that's possible
My friend! This is perfectly possible.

![image](https://user-images.githubusercontent.com/33970481/66936002-5dc8db00-f013-11e9-8dc5-c32307a0adf8.png)

**Comment by Evilhelder** [comment]
![image](https://user-images.githubusercontent.com/33970481/66936147-99fc3b80-f013-11e9-852e-97bffa5e03a9.png)

**Comment by anonymouschicken111** [comment]
Welp my mistake good luck on this

**Comment by xsincbt** [comment]
Oh shit noice thanks for the insight

**Comment by xsincbt** [comment]
Isn't that flowhooks lmao

**Comment by VuBrian22** [comment]
@xsincbt Yeah it is.
