### ISSUE TITLE
(suggestion) for faceit 

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#673]
Hello, the aimbot is extremely good, but it's detected on faceit
if you could add these it would more or less stop faceit serverside detection. 
1. Randomized smoothness, basically there are 2 values you can set : a min, and a max
The aimbot would choose a random value each tick but it would only choose a value if you're holding mouse1(to prevent huge fps drops)
2. Randomized bunnyhop hitchance, this would be the same as aimbot 
That's pretty much it

**Comment by HowToMakeFaceitAB** [comment]
Tbh the cheat is 10/10 and definitely doesn't need those features but
I use 15 smooth in mm with 2 fov 
I literally destroy the f outta people

**Comment by RadicalRedemption** [comment]
I use 2.0 Smooth with 1.7 FOV, i literally destroy the f outta people.

**Comment by tirziz** [comment]
I use 180fov and 0 smooth. Absolutely destroy the frick outta ppl

**Comment by HowToMakeFaceitAB** [comment]
WoW i use like 0 smooth eith 360 fov
Destoys god
