### ISSUE TITLE
[Suggestion_WeaponEsp] Draw Overlapping items as lists

### ISSUE THREAD

**Issue by BobH233** [danielkrupinski/Osiris#674]
I have achieved this function.I suggest the author add this function as well.
It's easier to identify items.

Before Fixing:
![QQ图片20191017125802](https://user-images.githubusercontent.com/23572936/66978777-d300e280-f0dd-11e9-802b-e3a5436419ed.jpg)

After Fixing:
![QQ图片20191017125814](https://user-images.githubusercontent.com/23572936/66978784-d8f6c380-f0dd-11e9-8b1b-4c3bdd7f8346.png)
![QQ图片20191017125806](https://user-images.githubusercontent.com/23572936/66978786-dac08700-f0dd-11e9-8ec5-f3636baa627b.jpg)

**Comment by 0xE232FE** [comment]
Yes this is super clever! :-)

**Comment by 0xE232FE** [comment]
Yes this is super clever! :-)
@BohanRen may you do the pull request pls May you commit your changes to your Fork? So we can review your changes.

**Comment by BohanRen** [comment]
> Yes this is super clever! :-)
> @BohanRen may you do the pull request pls May you commit your changes to your Fork? So we can review your changes.

That's OK. But I updated UI language into Chinese so you can just pay attention to the changes about **ESP.cpp** and **Config.cpp**. By the way,my code is just like shit so you'd better rewrite it yourself.

I'll commit the changes a moment later in my fork.

**Comment by BohanRen** [comment]
> Yes this is super clever! :-)
> @BohanRen may you do the pull request pls May you commit your changes to your Fork? So we can review your changes.

https://github.com/BohanRen/Osiris/commit/659b7c2fbba4613663b6cb3a0e61aecba0ce01c1

My Commit @0xE232FE

**Comment by 0xE232FE** [comment]
thx for sharing I will look at it. :-)

**Comment by danielkrupinski** [comment]
You can also use "Max distance" to limit esp range.

**Comment by BohanRen** [comment]
> You can also use "Max distance" to limit esp range.

Yes,I have finished this function. In my changed commit, I limit the max esp distance.

https://github.com/BohanRen/Osiris/commit/659b7c2fbba4613663b6cb3a0e61aecba0ce01c1

**Comment by BohanRen** [comment]
And I also add an aimbot range circle in the center of the screen so that I can easily know in which range can aimbot attack.
![428a67a008d67677](https://user-images.githubusercontent.com/23572936/67017809-dec7c580-f12c-11e9-9745-733b22199742.jpg)

**Comment by xsincbt** [comment]
Can u open a pull request that would be amazing

**Comment by BohanRen** [comment]
> Can u open a pull request that would be amazing

Sorry, but because my code is so bad, you'd better just take it as a reference.

If you want to refer to my implementation, you can read my commit :

https://github.com/BohanRen/Osiris/commit/659b7c2fbba4613663b6cb3a0e61aecba0ce01c1

at ESP.cpp  renderWeaponDrawList function

**Comment by xsincbt** [comment]
Kk

**Comment by AbdallahMehiz** [comment]
CAN YOU PULL REQUEST THE AIMBOT FOV CIRCLE ?
@BohanRen

**Comment by xsincbt** [comment]
@abdallahMehiz you can check the implementation I was able to get it to work but I left it on default

**Comment by Mufinekkk** [comment]
Nice, lets check it.
