### ISSUE TITLE
[BUG REPORT]crashed after a map change after selecting CT or T side

### ISSUE THREAD

**Issue by Megalounge** [danielkrupinski/Osiris#675]
i guess the pointer is not initialized properly, can anyone find the problem?
i was playing in a community server btw

**Comment by tirziz** [comment]
Do you have glow on ? I found that glow sometime crash your game.

**Comment by Floraly** [comment]
attach debug and try to reproduce crash... otherwise we can not help.

**Comment by coron3hotdog** [comment]
i dont have reserve engineering experience, so maybe i'll post my config here so that anyone can test it out
[ttt.zip](https://github.com/danielkrupinski/Osiris/files/3742264/ttt.zip)

**Comment by coron3hotdog** [comment]
@tirziz actully it crashes my game every time after map change
