### ISSUE TITLE
aa bug

### ISSUE THREAD

**Issue by xsincbt** [danielkrupinski/Osiris#676]
the aa makes my gernade miss

**Comment by VuBrian22** [comment]
There has already been a fix here: https://github.com/danielkrupinski/Osiris/pull/432 however that pull request was never pushed to an update to the source. You can try pasting the fix to the source yourself.

**Comment by effex1337** [comment]
I posted it before having conflicts

**Comment by effex1337** [comment]
Idk why he doesn't pull it
