### ISSUE TITLE
Cheat set all my keys to alt, want choked packets to have no key

### ISSUE THREAD

**Issue by Hayden959** [danielkrupinski/Osiris#677]
dont know if this is supposed to happen but all my keys are alt, but i would like to have choked packets not have a key. how can i do this?

**Comment by Floraly** [comment]
If you lalt+tab out of the game. Sometimes lalt is locked and not release if you set then any key in the cheat menu it always show alt that's not a bug. Press alt again and it's released

**Comment by Hayden959** [comment]
> If you lalt+tab out of the game. Sometimes lalt is locked and not release if you set then any key in the cheat menu it always show alt that's not a bug. Press alt again and it's released

ok so how do i make it not use a key anymore

**Comment by VuBrian22** [comment]
You don't just make sure the fields don't say "alt" as a key bind.

**Comment by anonymouschicken111** [comment]
In Misc change choke packets to just if config.misc.chokePackets instead of getasynckeystate config.misc.chokePacketsKey, and in Gui change choke packets key to a checkbox and in configs change it to a boolean, and in configs.h change it to a bool, and initialize it to false

**Comment by danielkrupinski** [comment]
Hover key bind with mouse and press "ESC".
