### ISSUE TITLE
[Question] Where do I turn on recoil control?

### ISSUE THREAD

**Issue by robwes03** [danielkrupinski/Osiris#679]

**Comment by xsincbt** [comment]
The aimbot tab has recoil control

**Comment by xsincbt** [comment]
@robwes03

**Comment by robwes03** [comment]
can't get that to work for some reason

**Comment by effex1337** [comment]
The recoil control only works when the Aimbot is active.

**Comment by robwes03** [comment]
oh

**Comment by robwes03** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/13853713/67091891-22aedf00-f1ae-11e9-99bf-43a63bcb3fdc.png)
which one and hoiw do i

**Comment by effex1337** [comment]
I feel like you're trolling. It's literally named recoil control x and y.
Which controls your recoil in the x and y axis.

**Comment by robwes03** [comment]
I turned em both to 1, it didnt change anything, thats why im asking

**Comment by effex1337** [comment]
https://github.com/danielkrupinski/Osiris/issues/679#issuecomment-543693817

**Comment by robwes03** [comment]
didnt i turn it on tho? i checked the top box

**Comment by xsincbt** [comment]
Lmao

**Comment by xsincbt** [comment]
U a clown

**Comment by xsincbt** [comment]
Don't u see recoil control x and y

**Comment by robwes03** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/13853713/67092328-37d83d80-f1af-11e9-9064-dce4302dd2f3.png)
its legit like that and i still get max recoil

**Comment by HowToMakeFaceitAB** [comment]
Set the fov to 2
Idiot

**Comment by xsincbt** [comment]
Are u new

**Comment by robwes03** [comment]
ye im new

**Comment by effex1337** [comment]
Alright set the bone to head full fov and no recoil control at all. Then do the same except pit the recoil control to max. You'll feel the difference. Good luck😃

**Comment by anonymouschicken111** [comment]
It's not standalone RCS so it only works if your bullets are on the enemy, get the difference between aimbot RCS and standalone RCS.

**Comment by AbdallahMehiz** [comment]
after all, daniel should add the standalone rcs to the cheat because even i struggle to use this version xd. its not needed thou

**Comment by anonymouschicken111** [comment]
Hi, standalone RCS is hard to implement, I tried but I keep failing

**Comment by steel4me** [comment]
Done -> #769, wait for approval from @danielkrupinski
