### ISSUE TITLE
(Suggestion) Discord

### ISSUE THREAD

**Issue by xsincbt** [danielkrupinski/Osiris#680]
@danielkrupinski should create a discord for this cheat

**Comment by effex1337** [comment]
For what? 
If it's for support. 
He doesn't owe you anything.
Absolutely not needed!

**Comment by xsincbt** [comment]
Damn why TF u mad toxic just make one didn't even say it was for support lmao

**Comment by xsincbt** [comment]
Take that toxicity somewhere else

**Comment by sonicrules11** [comment]
effex isn't being toxic lmao

A Discord for Osiris isn't needed or required when there's an issue tracker. [Cheating Discord servers are against Discord TOS anyways so it would most likely get reported and taken down.](https://discordapp.com/terms)

![chrome_n2fuW7O3YP](https://user-images.githubusercontent.com/22671423/67143575-9c33e500-f221-11e9-8e29-20f6da7f971f.png)

**Comment by anonymouschicken111** [comment]
Hey u dumb cunt, u take ur toxicity some fucking where no one is fucking bothered to keep up with ur shit

**Comment by AbdallahMehiz** [comment]
close this issue

**Comment by CallieOwO** [comment]
> effex isn't being toxic lmao
> 
> A Discord for Osiris isn't needed or required when there's an issue tracker. [Cheating Discord servers are against Discord TOS anyways so it would most likely get reported and taken down.](https://discordapp.com/terms)
> 
> ![chrome_n2fuW7O3YP](https://user-images.githubusercontent.com/22671423/67143575-9c33e500-f221-11e9-8e29-20f6da7f971f.png)

omg matching pfps

**Comment by CallieOwO** [comment]
It'd be neat to have a Discord for general community purposes and not STRICTLY cheating related things but seems unlikely.
