### ISSUE TITLE
is it detected ?

### ISSUE THREAD

**Issue by AbdallahMehiz** [danielkrupinski/Osiris#681]
this week my friend got vac banned for using the cheat 
https://steamcommunity.com/profiles/76561198874060361/
he used it on friday - got banned on tuesday
is it detected ?

**Comment by effex1337** [comment]
Yes, gtf outta here if you can't read and do your own research.

**Comment by xsincbt** [comment]
Lmao

**Comment by xsincbt** [comment]
I been using and never got vac change some shit

**Comment by HowToMakeFaceitAB** [comment]
Effex fucking loser

**Comment by BohanRen** [comment]
You can use VMProtect to protect the compiled binary file,and also you can try some easy way to avoid detection such as remove the PE header or cut up the PEB link.
For more details,read this:
https://github.com/BohanRen/Osiris/blob/master/Osiris/AntiDetection.cpp

**Comment by 0xE232FE** [comment]
You used manual-map injection! ... This is the cause of your VAC Ban.

**Comment by effex1337** [comment]
Write your own injector i personally use mmap and never got a ban btw. My god why are these people so retarded.

**Comment by 0xE232FE** [comment]
@effex1337 interisting. When I use -Manual-Map on my own injector I get VAC ban between 3-7 Days. When I use the same injector but LoadLibrary I don't get VAC Ban.

**Comment by effex1337** [comment]
could be both.
(not my research but manual mapinging with the current hooking method is what makes it detected)
so you have 3 options
1. use a loadlib injector
2. change the hooking methods( which i did)
3. find a better mmap injector(yes theres an injector that mmaps osiris without detection but doesnt work with the latest windows 10 update)
@AbdallahMehiz @0xE232FE 
and also sorry for getting mad these retarded issues just make me cringe.
also for @HowToMakeFaceitAB use std::rand for your dynamic smoothing
https://en.cppreference.com/w/cpp/numeric/random/rand
good luck!
P.S. @HowToMakeFaceitAB you are a very big winner

**Comment by 0xE232FE** [comment]
The last thing VAC do is Hook detection. First they do signature detection, but atm they aren't do anything against Osiris.

**Comment by effex1337** [comment]
Yes there was a vacwave late 2018 ish where nearly every cheat got detected by the hooking methods.

**Comment by RadicalRedemption** [comment]
> 
> 
> You used manual-map injection! ... This is the cause of your VAC Ban.

I also have my own mmap injector, but with tons of other features. I never got banned?

**Comment by anonymouschicken111** [comment]
This fucking tab is where you fucking post issues and bugs with the fucking program, not some tech support fourm, people are here to lend a hand not fucking teach you how to fucking program before you post fucking cringy ass issues, fucking do your goddamn research, effex1337 isn't saying anything wrong, and HowToMakeFaceitAB there are plenty of threads and post on unknowncheats that explained how, before u fucking call someone a loser fucking think if u are one and you are so fucking kill yourself.

**Comment by BohanRen** [comment]
HaHaHa
![QQ图片20191019220041](https://user-images.githubusercontent.com/23572936/67146254-e669a480-f2bb-11e9-97aa-a1f0baaeb7f1.jpg)
I agree with u.

**Comment by AbdallahMehiz** [comment]
so...
after all the cheat is detected thats it ?
if i was to make a private injector, will it be undetected ?

**Comment by CallieOwO** [comment]
> Yes, gtf outta here if you can't read and do your own research.

be a bit nicer to people, no reason not to give people a little help if they're new to cheating/don't know much about it in general.

**Comment by hyperxpro** [comment]
Duplicate of https://github.com/danielkrupinski/Osiris/issues/653

**Comment by AbdallahMehiz** [comment]
ok
thanks for the help guys <3

**Comment by anonymouschicken111** [comment]
@Andallah u really don't know much about cheating do u? Well to answer ur question no, it won't help. Vac scans all process and all an injector does in inject it into csgo, the injector is like a middle man, it doesn't really matter

**Comment by hyperxpro** [comment]
> @Andallah u really don't know much about cheating do u? Well to answer ur question no, it won't help. Vac scans all process and all an injector does in inject it into csgo, the injector is like a middle man, it doesn't really matter


VAC Detected Injector can indeed get you VAC Banned. The injector does matter,

**Comment by anonymouschicken111** [comment]
@hyperxpro is right, in a nutshell since Vac scans all processes when u use a Vac detected injector Vac checks it compares it with its database of signature and bam ur Vacced
