### ISSUE TITLE
(Suggestion) NEW SKINS AND CLASSIC KNIFE

### ISSUE THREAD

**Issue by giangero1** [danielkrupinski/Osiris#683]
if we find the new skins ids maybe we can add the new skins in nSkinz source , should be easy :)

**Comment by Hayden959** [comment]
https://github.com/danielkrupinski/Osiris/pull/682

**Comment by igre3zy** [comment]
I added the classic knife, want my dll?

**Comment by giangero1** [comment]
@igre3zy sure , i'm trying to find where to paste that code that hayden send, my Giangero#3167 discord

**Comment by giangero1** [comment]
@Hayden959 actually thanks i found ur code on pull request thank u so much <3
