### ISSUE TITLE
Auto accept no longer working?

### ISSUE THREAD

**Issue by deprale** [danielkrupinski/Osiris#686]
Anyone can confirm?

**Comment by 0xE232FE** [comment]
Normaly its working.

**Comment by anonymouschicken111** [comment]
Not working for me

**Comment by AbdallahMehiz** [comment]
perfectly fine for me

**Comment by catke74** [comment]
same here auto-accept doesn't work

**Comment by 0xE232FE** [comment]
The only behavior I can tell where Auto Accept isn't propably working, is when the someone didn't accept and the next vote pops up. Sometimes the Auto Accept is confused and sometimes not. I tried to debug many times but can not find the issue. It always goes into the accept proceedure of the cheat and send the accept command. But the Interface of the csgo client didn't send the accept. This is not a Osiris issue. :/ I saw this behavior on P2C Cheats at my friends computer, he asked me the same question. It's a csgo issue like many other issues. XD

**Comment by 0xE232FE** [comment]
The only behavior I can tell where Auto Accept isn't propably working, is when someone didn't accept and the next vote pops up. Sometimes the Auto Accept is confused and sometimes not. I tried to debug many times but can not find the issue. Osiris always goes into the accept proceedure of the cheat and send the accept command. But the Interface of the csgo client didn't send the accept. This is not a Osiris issue. :/ I saw this behavior on P2C Cheats at my friends computer, he asked me the same question. It's a csgo issue like many other issues. XD

**Comment by littlehurensohn** [comment]
auto accept normally works 

//CLOSE

**Comment by RadicalRedemption** [comment]
Doesn't work for me either.

**Comment by danielkrupinski** [comment]
It works, but the 'Accept' button stays 'unpressed'.

**Comment by anonymouschicken1111** [comment]
@deprale Hey it's anonymouschicken111
My account recently got banned so all posts and comments I made are gone so I made anonymouschicken1111

On Sept11 you asked if I could help u with a legacy grenade prediction on a Grenade Prediction Post I made
If you're still up for it I can help
