### ISSUE TITLE
[SUGGESTION] Bypass sv_pure

### ISSUE THREAD

**Issue by Oly-UK** [danielkrupinski/Osiris#687]
Hey, i would love to see a bypass for sv_pure, to have some nostalgia on the old gun sounds. What do you guys think?

**Comment by AbdallahMehiz** [comment]
#569 it has been already thought of
soo... why don't you paste it from another cheat your self/code it youself

**Comment by anonymouschicken111** [comment]
First of all add ur own SendNetMsg hook

**Comment by hyperxpro** [comment]
Duplicate of https://github.com/danielkrupinski/Osiris/issues/569
