### ISSUE TITLE
Not Working!

### ISSUE THREAD

**Issue by AnonHackerr** [danielkrupinski/Osiris#688]
Guys hello... amm today i reinstall windows 10 on my laptop and when i tried to inject osiris.dll with CmR injector nothing happens... but its works perfectly on my pc... also i have tested with other injectors but nothing happen and can you help me ?

**Comment by AbdallahMehiz** [comment]
disable your anti-virus

**Comment by hyperxpro** [comment]
> Guys hello... amm today i reinstall windows 10 on my laptop and when i tried to inject osiris.dll with CmR injector nothing happens... but its works perfectly on my pc... also i have tested with other injectors but nothing happen and can you help me ?

Try installing Microsoft Visual C++ Packages.

**Comment by anonymouschicken111** [comment]
Kys dumass

**Comment by littlehurensohn** [comment]
Update c++, disable antivirus. 

//CLOSE

**Comment by VuBrian22** [comment]
@anonymouschicken111 He's using a dll from a hacking forum called cheater.fun

**Comment by 0xE232FE** [comment]
Is the DLL encrypted? Maybe you don't have the right key?

**Comment by anonymouschicken111** [comment]
@VuBrian22 ahh ok thanks for info

Try manually compiling it from source

**Comment by markito12** [comment]
could you fix it?

**Comment by thomas0aotian** [comment]
omg,just fucking launch ur injector as administrator. lmao
