### ISSUE TITLE
Crashing on match start

### ISSUE THREAD

**Issue by markito12** [danielkrupinski/Osiris#692]
is it caused by any old osiris cache / config files?

**Comment by 0xE232FE** [comment]
Without debug or error message we can not help here :(

**Comment by 0xE232FE** [comment]
For me it is working fine!
Without debug Log or specific error message we can not help you.

**Comment by markito12** [comment]
where can i find that? it was working fine idk what happened

**Comment by markito12** [comment]
i found out it only happens in online matchmaking with bots it does not crash

**Comment by 0xE232FE** [comment]
Delete config and join an Matchmaking without clear settings. Is it crashing for you?

**Comment by markito12** [comment]
now works, i verified csgo files and removed saved config for osiris and seems to be working :D thanks for the time!
