### ISSUE TITLE
Loading old configs crashes the game.

### ISSUE THREAD

**Issue by aska-monnnn** [danielkrupinski/Osiris#695]
As title, is anyone having the same problem though.
Link to config:
[0.zip](https://github.com/danielkrupinski/Osiris/files/3755059/0.zip)

**Comment by effex1337** [comment]
This problem has peen posted like 3 times in 2-3 days so you might wanna make a new one.

**Comment by aska-monnnn** [comment]
I don't see any but that's ok, ty.
