### ISSUE TITLE
(question) is there a way for me to edit the code to make backtrack 300 ms 

### ISSUE THREAD

**Issue by JayVer107** [danielkrupinski/Osiris#696]
hi I was wonder if it is possible for me to edit the code and make backtrack just a little longer
I know nothing about coding btw but I am trying to understand

**Comment by effex1337** [comment]
No huge backtracks are patched and how do you expect to drive if you never touched a vehicle?

**Comment by JayVer107** [comment]
okay thnx anyway and the internet helps me learn
