### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by h4x0reL** [danielkrupinski/Osiris#697]
Improve Legit/Fake AA
Add Fake chams
Add AA on key

**Comment by littlehurensohn** [comment]
up

**Comment by xsincbt** [comment]
Add it your self or at least try to

**Comment by h4x0reL** [comment]
it's not only for me but also for the author to improve aa, and cheat to be better than it is now and of course I respect every update.
it's simply a suggestion for the author to add it to the todo list and to take care of it in his spare time
(i can do it by myself but i dont want paste this awesome project ) peace

**Comment by AbdallahMehiz** [comment]
> it's not only for me but also for the author to improve aa, and cheat to be better than it is now and of course I respect every update.
> it's simply a suggestion for the author to add it to the todo list and to take care of it in his spare time
> (i can do it by myself but i dont want paste this awesome project ) peace

Pull Request

**Comment by anonymouschicken111** [comment]
Add it yourself, and fuck off
