### ISSUE TITLE
Crash game after load cfg

### ISSUE THREAD

**Issue by djborek** [danielkrupinski/Osiris#699]
Hi, what can crash configs made a month ago after csa update and crashes again.

**Comment by sonicrules11** [comment]
Make new config

**Comment by djborek** [comment]
That's all I know but I would like to know what caused that now it crashes again not to create the whole again but to change the given value in cfg to make it work again.

**Comment by danielkrupinski** [comment]
Colors are now objects, before they was float arrays. Crash is caused because JSON tries to read an object from config, but in old config it's an array. To fix old config remove Esp and Glow objects from config file.
