### ISSUE TITLE
Key for triggerbot

### ISSUE THREAD

**Issue by ahahaha0** [danielkrupinski/Osiris#7]
Hello,
Could you tell me how to change the triggerbot key (alt) in the code?
I would appreciate that,
Thanks.

**Comment by Takanaue** [comment]
Open your triggerbot.cpp and change the 13 line.

Change this:
`if (GetAsyncKeyState(VK_MENU)`
to:
`if (GetAsyncKeyState(anyKey_of_the_link)`

https://docs.microsoft.com/en-us/windows/desktop/inputdev/virtual-key-codes
