### ISSUE TITLE
[Bug] Load CFG button is crashing.

### ISSUE THREAD

**Issue by didisko33** [danielkrupinski/Osiris#70]
I'm using last build.

**Comment by danielkrupinski** [comment]
Remove configuration file from previous version and recreate it.

**Comment by didisko33** [comment]
@danielkrupinski thank you, it helped me.

**Comment by TheNotoriousAWP** [comment]
is there any way to fix this/ prevent it from happening? I wouldn't mind unencrypted configs but it's annoying when I have to recreate my config everytime there is a software update / new feature added. Thanks!
