### ISSUE TITLE
[SUGGESTION] Aimstep or "how to avoid vacauth"

### ISSUE THREAD

**Issue by 17BaZ** [danielkrupinski/Osiris#700]
When using Silent aim with max fov, you will become vac auth'd shortly after.
I'd love it if a feature like aimstep would be put in the cheat <3 .

**Comment by ZPDMiller** [comment]
That sounds like a good feature

**Comment by danielkrupinski** [comment]
Set "Max angle delta" in misc to 30.0

**Comment by furioushell98** [comment]
@danielrupinski 30 max angle delta can prevent being instantly sent to overwatch even with max fov?
