### ISSUE TITLE
Crashing on inject

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#702]
Cheat is crashing on injecting help me

**Comment by Syico** [comment]
Maybe windows defender or any other antivirus tool?

**Comment by HowToMakeFaceitAB** [comment]
Obviously not
I made many posts on the forum before 
I'm not new neither am i dumb
Don't want you to think i'm rude but it's clearly not for that reason

**Comment by littlehurensohn** [comment]
> Obviously not
> I made many posts on the forum before
> I'm not new neither am i dumb
> Don't want you to think i'm rude but it's clearly not for that reason

1. Do you have updated vc++ ? (Windows library) 
2. What windows are you using? Cause i think this cheat, not supports windows 7. 
3. What injector you using? 
4. Some hwid checks or something what u add into cheat? 
5. Windows defender? Cause can be running at the backgrounds (its shit antivirus) 
6. Do you have updates offsets, patterns? 

Answer me all question and I can in some way help you.

**Comment by anonymouschicken111** [comment]
Kill yourself, this isn't tech support

**Comment by MrSleekZ** [comment]
Most likely you anti-virus or injector

**Comment by thomas0aotian** [comment]
injector / hook issue

**Comment by thomas0aotian** [comment]
be aware that early injection may faill, inject it when u r at the lobby
