### ISSUE TITLE
[ suggestion]standalone rcs

### ISSUE THREAD

**Issue by thomas0aotian** [danielkrupinski/Osiris#704]
An always recoil control would be nice.

**Comment by AbdallahMehiz** [comment]
just find a paste man wtf

**Comment by VuBrian22** [comment]
Extremely hard to implement....

**Comment by HowToMakeFaceitAB** [comment]
oMg It'S sO hArD tO iMpLeMeNt

**Comment by anonymouschicken111** [comment]
FUCKING KILL YOURSELF SCROLL THRU THE FUCKING ISSUES TAB,
NIGGA THIS SHIT SO HARD TO IMPLEMENT I WANNA KILL MYSELF

**Comment by HowToMakeFaceitAB** [comment]
LoL
aRe YoU rEtArDeD
