### ISSUE TITLE
[Suggestion] Visible FOV aimbot circle

### ISSUE THREAD

**Issue by MrSleekZ** [danielkrupinski/Osiris#708]
Not sure what this is called but here is a pic: 
[-](https://media.discordapp.net/attachments/439027429307187200/637284682303537170/circle.PNG)

Didn't see this suggested before, sorry if it was.

**Comment by xsincbt** [comment]
#674 has a working one u can add

**Comment by Evilhelder** [comment]
up

**Comment by MrSleekZ** [comment]
Thanks
