### ISSUE TITLE
[glitch]

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#714]
Rcs stops controlling recoil
When out of fov
Another reason to add standalone rcs

**Comment by rosesware** [comment]
not a glitch lmao, thats the feature called "Recoil-based fov".

**Comment by anonymouschicken111** [comment]
No it's meant to do that, stops controlling recoil when the enemy is out of range

**Comment by HowToMakeFaceitAB** [comment]
I don't have that on

**Comment by HowToMakeFaceitAB** [comment]
> not a glitch lmao, thats the feature called "Recoil-based fov".

Why do you reply only once and never again

**Comment by rosesware** [comment]
idk what you talking about.

**Comment by Akianzax** [comment]
It still not working, as you said. When use low fov (like 1.5 or so) it stop the recoil control because after adjusting for recoil the cross-hair leaves the aimbot FOV.
I think it need a rcs fov diferent from the actual fov (so you can set fov like 1.5 and rcs fov 4).
