### ISSUE TITLE
[QUESTION] Aimstep

### ISSUE THREAD

**Issue by igre3zy** [danielkrupinski/Osiris#718]
On a scale of 1-10 how hard would it be to implement aimstep to osiris?

**Comment by effex1337** [comment]
-10 it's already there as max angle delta set it to 30 and you're gucci

**Comment by igre3zy** [comment]
> -10 it's already there as max angle delta set it to 30 and you're gucci

So I can use silent aim with a high fov in casual like this and I wont get a vac auth?

**Comment by ZPDMiller** [comment]
Yes
