### ISSUE TITLE
[QUESTION] AA chams

### ISSUE THREAD

**Issue by igre3zy** [danielkrupinski/Osiris#720]
How hard would it be to add chams for the fake angles on legit aa?

**Comment by effex1337** [comment]
100/10 from the way you're asking it.
But its like 2-3/10 if you have the knowledge.

**Comment by thomas0aotian** [comment]
@effex1337 bruh is this effex,ur xy0 repaste is op

**Comment by igre3zy** [comment]
@effex1337 do you have the knowledge?

**Comment by effex1337** [comment]
https://youtu.be/2K8zN8b585o
See it for yourself.
