### ISSUE TITLE
config.h issue

### ISSUE THREAD

**Issue by JustinLatiao** [danielkrupinski/Osiris#723]
After the update, I cannot set true or false for watermarker and other functions in config.h

**Comment by thomas0aotian** [comment]
No u can

**Comment by Bywnb** [comment]
`    struct ColorToggle : public Color {
        bool enabled{ false };
    };`

I tried changing false to true, but it was wrong

**Comment by thomas0aotian** [comment]
literally just do it again

**Comment by Bywnb** [comment]
@danielkrupinski
