### ISSUE TITLE
Introduce Versioning

### ISSUE THREAD

**Issue by hyperxpro** [danielkrupinski/Osiris#724]
It'd be great if Versioning is introduced. 

Osiris is an active project and gets updated daily and it becomes challenging to keep up with Stable version. So if we create Stable version release, It'd be really convenient for users and future feature planning.

**Comment by hyperxpro** [comment]
@danielkrupinski

**Comment by 0xE232FE** [comment]
Dude you always can step backwards if the current master isn't working. If you want releases pull a fork and make your own release channel. You are free to do so. ;-)

**Comment by hyperxpro** [comment]
> Dude you always can step backwards if the current master isn't working. If you want releases pull a fork and make your own release channel. You are free to do so. ;-)

Do you even understand what is Versioning?

**Comment by HowToMakeFaceitAB** [comment]
Versioning is basically giving each update a name or number
Ex: release osiris (latest) 1a, 1b ect.

**Comment by hyperxpro** [comment]
> Versioning is basically giving each update a name or number
> Ex: release osiris (latest) 1a, 1b ect.

If we make versions of Osiris such as Stable (Updated once every week), Nighty (Updated Daily). It'd be easy to create a roadmap of the feature.

Let's say: Stable v1.2.2 has ABC, DEF, features (25-October-2019 Release)
               Nighty v1.2.1.98 has GHI, JKL features (28-October-2019 Release)

Later once Nighty build meets standards and becomes bug-free, we'll push it into Stable release.

**Comment by hyperxpro** [comment]
> Versioning is basically giving each update a name or number
> Ex: release osiris (latest) 1a, 1b ect.

Just think of it like Windows Insider Preview Builds in Windows 10.

**Comment by thomas0aotian** [comment]
useless, Daniel is updating everyday. no ways to make a stable versioning

**Comment by hyperxpro** [comment]
> useless, Daniel is updating everyday. no ways to make a stable versioning

Every active project is updated daily (many hourly too). There can be a separate branch for the stable release.
