### ISSUE TITLE
[FIX] Skin changer request

### ISSUE THREAD

**Issue by igre3zy** [danielkrupinski/Osiris#725]
@danielkrupinski if you could, can you work on making it to where skins from the skin changer don't show when you switch to a bot? (knife & gloves too)

**Comment by ZPDMiller** [comment]
Also different knife and glove settings for each team

**Comment by igre3zy** [comment]
> Also different knife and glove settings for each team

@danielkrupinski ^^^

**Comment by hyperxpro** [comment]
> @danielkrupinski if you could, can you work on making it to where skins from the skin changer don't show when you switch to a bot? (knife & gloves too)

That's how the game is designed. And spending time on this is useless.

**Comment by thomas0aotian** [comment]
true^O^

**Comment by hyperxpro** [comment]
@igre3zy Close the issue.

**Comment by Oly-UK** [comment]
i +rep this idea
