### ISSUE TITLE
[QUESTION] Legit AA

### ISSUE THREAD

**Issue by igre3zy** [danielkrupinski/Osiris#726]
1.) When using legit aa on osiris with just yaw on, which angle does your real peek?
2.) When in third person with legit aa on, is the model your real angle?

**Comment by effex1337** [comment]
1. Legit aa doesnt work.
2. The thirdperson angles are incorrect. 
(prediction is needed

**Comment by igre3zy** [comment]
>1. Legit aa doesnt work. ...

@effex1337 when i put choked packets to 1 and turn on the legit aa with just jaw. the aa appears to work in third person 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by effex1337** [comment]
Have you tried it with someone? -> for testing if it actually works.
Have you asked someone to spec you? -> for testing if it is legit.

Do these researches for yourself.

**Comment by thomas0aotian** [comment]
# the aa is working but it ain't legit
# the yaw aa real is to ur right

**Comment by igre3zy** [comment]
>Have you tried it with someone? -> for testing if it actually works. ...

@effex1337 research kinda defeats the purpose of asking questions on these forums. chill out man

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by igre3zy** [comment]
># the aa is working but it ain't legit ...

@thomas0aotian would just yaw enabled on the aa appear legit to overwatch or no?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 0xE232FE** [comment]
It is not legit @igre3zy just make a server and record demo. You don't need someone to spectate you. Just record the demo on CSGO Server not on the client.

**Comment by thomas0aotian** [comment]
from what i've known,fake angles weren't fixed or weren't fixed completely, at least those premium cheat still has legit aa. But Osiris AA is sure not legit, it's faking angles in client but not the server. So when u fire,the real angle is actually flicking super hard no matter how many packages u r choking.
