### ISSUE TITLE
[IDEA] Skinchanger

### ISSUE THREAD

**Issue by AntonDoil** [danielkrupinski/Osiris#728]
Make a find skin in skinchanger menu? :) 

Does mean.. When u want Crimson Web.. (U type to the searchbar crimson web) 

I hope u know how i mean it.

**Comment by thomas0aotian** [comment]
searchbar in skinchanger

**Comment by Oly-UK** [comment]
i +rep this idea

**Comment by hyperxpro** [comment]
+1

**Comment by AbdallahMehiz** [comment]
+1 Good one
maybe he can just make the skins appear for the weapon you want
like when u want an ak skin on!ly aks skins appear
like i want an m4a1 the skins that will appear will be "Hot rod, GOLDEN COIL, Golden KOI..." and not the knifes and other weapons' skins

**Comment by ZPDMiller** [comment]
That is a good idea too, both of these ideas are great, +1

**Comment by xsincbt** [comment]
+1 me too so it's ezer

**Comment by rosesware** [comment]
_@AbdallahMehiz_

A lot of people use like M9 Bayonet with some random skin that doesn't exist in the game properly, ie this is, searchbar in skinchanger ideia is a pretty good ideia, but your ideia makes a lot people can't use this type of weapons with that type os skins.

**Comment by AbdallahMehiz** [comment]
> _@AbdallahMehiz_
> 
> A lot of people use like M9 Bayonet with some random skin that doesn't exist in the game properly, ie this is, searchbar in skinchanger ideia is a pretty good ideia, but your ideia makes a lot people can't use this type of weapons with that type os skins.

Maybe they can enable and disable an option that makes incompatible skins appear in the list.

**Comment by giangero1** [comment]
yes love this idea

**Comment by danielkrupinski** [comment]
Now you can search skins for certain weapon.
