### ISSUE TITLE
Cool idea, if anyone is down to help?

### ISSUE THREAD

**Issue by Oly-UK** [danielkrupinski/Osiris#729]
I want to make the backtrack chams cover all ticks, not just the last one for example, masterloosers x88 backtrack chams or spirthacks backtrack chams.

https://cdn.discordapp.com/attachments/629365117930438667/638325082917175297/unknown.png

**Comment by ZPDMiller** [comment]
I've been trying too but with no luck :( hopefully somebody can help us out

**Comment by thomas0aotian** [comment]
supported

**Comment by Scui1** [comment]
this is where backtrack chams are made:
https://github.com/danielkrupinski/Osiris/blob/master/Osiris/Hacks/Chams.cpp#L156-L166

all you need to do is create a loop and replace "record->back()" with the current record. Pretty easy if you know c++

**Comment by JDeu** [comment]
In backtrack change:
`hooks.modelRender.callOriginal<void, void*, void*, const ModelRenderInfo&, matrix3x4*>(21, ctx, state, info, record->at(x).matrix);`
to:
`						for (int x = 0; x < record->size(); x++) {
							hooks.modelRender.callOriginal<void, void*, void*, const ModelRenderInfo&, matrix3x4*>(21, ctx, state, info, record->at(x).matrix);
						}`

**Comment by xsincbt** [comment]
@JDeu you should would be amazing

**Comment by thomas0aotian** [comment]
lmao, it's actually ez af

**Comment by HowToMakeFaceitAB** [comment]
I have 0 experience with coding whatsoever

**Comment by igre3zy** [comment]
@JDeu your method works great for the masterlooser backtrack. Hopefully Daniel will fix the backtrack chams overlaying the enemy in the near future :)

**Comment by JDeu** [comment]
Made a pull request [#730](https://github.com/danielkrupinski/Osiris/pull/730)

Think some of the formatting is messed and the option should be stored in Chams really but I'm lazy.
