### ISSUE TITLE
[Suggestion] Name Stealer

### ISSUE THREAD

**Issue by CardealRusso** [danielkrupinski/Osiris#73]
Basic name stealer
if we can set the delay in minutes (steal another name in x minutes) can be great

**Comment by VitexHD** [comment]
Agreed, I was trying to figure that one out by myself, almost worked but it crashed because it was trying to read the wrong address, and I've not even went through each file reading line by line to understand how I could add to it from the base so I've gave up for now :3

**Comment by danielkrupinski** [comment]
Added.
