### ISSUE TITLE
Old Config is crashing Osiris, how to merge configs?

### ISSUE THREAD

**Issue by steel4me** [danielkrupinski/Osiris#732]
As title -> Old Config is crashing Osiris -> Tested Repos  with and without changes, so it doesnt apply to my modifications.

I know, on README.md this is described: Sometimes after updates configuration file needs to be deleted and recreated.

And i know that there are many issues open with workarounds. 

Does someone have a solution to merge old config to new ones? Or is redoing all settings / part of settings the only way?

**Comment by thomas0aotian** [comment]
reset part of the cfg that maybe updated

**Comment by steel4me** [comment]
okay, thanks, i found something after more searching that i will try....

[https://github.com/danielkrupinski/Osiris/issues/218#issuecomment-496924926](url)

**Comment by thomas0aotian** [comment]
uh,thats like ages ago before he even used the json system to store cfg
