### ISSUE TITLE
i want the most violent config

### ISSUE THREAD

**Issue by fissssssh** [danielkrupinski/Osiris#735]
i want the most violent config to play  in hvh

**Comment by effex1337** [comment]
ok

**Comment by AbdallahMehiz** [comment]
hvh with osiris???
autoshoot doesn't even work

**Comment by thomas0aotian** [comment]
@AbdallahMehiz false

**Comment by k1ngboo** [comment]
> @AbdallahMehiz false

no its true, autoshoot and autoscope are broken right now

**Comment by thomas0aotian** [comment]
autoshoot is never broken, just auto scope,and it needs a auto stop to make both work well

**Comment by NNiX1** [comment]
actually i was able to win against 2 spinners in mm ... of course they must had some pastes but still i wasa not  spinning using legit cheat soo :D

**Comment by AbdallahMehiz** [comment]
i tried hvh with it
activated it
everything is normal in the config
but still it doesn't autoshoot

**Comment by Mubi007** [comment]
> i tried hvh with it
> activated it
> everything is normal in the config
> but still it doesn't autoshoot

make a new cfg and be happy XD

**Comment by thomas0aotian** [comment]
@AbdallahMehiz yeah reset the aimbot/max angle delta set to 255/only enable all weapon/htc & min dmg set to 1/enable autoshoot. it has to be working
