### ISSUE TITLE
[Suggestion] Griefing

### ISSUE THREAD

**Issue by okureta** [danielkrupinski/Osiris#737]
Add a blockbot on key for trolling, would be extra epic. I already have seen this but it was ignored and that was back in July.

Just more griefing shit, troll votes is already epic
 
oh and an adaptive circle strafer would be nice, and airstuck

**Comment by xsincbt** [comment]
Just paste it in there boom ez

**Comment by thomas0aotian** [comment]
@xsincbt waiting r ur pull request,lmao

**Comment by k1ngboo** [comment]
> Just paste it in there boom ez

Send PR now

**Comment by Evilhelder** [comment]
please Run boost Helper.... :(

**Comment by okureta** [comment]
Bump?
