### ISSUE TITLE
C2039	'cold': is not a member of 'Entity'

### ISSUE THREAD

**Issue by NNiX1** [danielkrupinski/Osiris#738]
didnt changed anything :)

**Comment by effex1337** [comment]
Send a screenshot of where you get that

**Comment by NNiX1** [comment]
gui.cpp line 1011
http://prntscr.com/prbtnc

**Comment by effex1337** [comment]
Remove that line for the time being

**Comment by danielkrupinski** [comment]
Sorry, typo.
