### ISSUE TITLE
Recoil Control not working.

### ISSUE THREAD

**Issue by rivc** [danielkrupinski/Osiris#740]
It's keep straight up as normal weapon recoil do.

**Comment by thomas0aotian** [comment]
retard close it#679

**Comment by HowToMakeFaceitAB** [comment]
No
The aim rcs sucks

**Comment by thomas0aotian** [comment]
@HowToMakeFaceitAB noticed that this guy talked a lot a shit and never did any contribution and all he knows is how to act like a real mf.

**Comment by Finndramere** [comment]
wdym? its not standalone rcs. its just rcs. Its not our fault you suck ass at controlling recoil

**Comment by HowToMakeFaceitAB** [comment]
Ah, i suck ass st controlling recoil?
Ah it's obviously not the cheat
Look here moron, how the fuck am i supposed to control recoil when both fucking rcs and aimbot are battling each other
Holy fuck, retards

**Comment by HowToMakeFaceitAB** [comment]
Literally the aimbot is always active, cheat sucks ass.

**Comment by thomas0aotian** [comment]
Danial wouldn't mind some random retard who does not no a single shit about how the cheat works and does not like danial's work just get the fuck out of his issues tab.

**Comment by Oly-UK** [comment]
> Literally the aimbot
> Is active when the rcs is active
> So both things end up fucking with eachother, which doesn't fucking let me move mouse, badly coded.

it isnt badly coded, try setting recoil control x to 0.5 and recoil control y to 1.5
you can either change the limit of one from code or hold control and click it on the menu to edit it

**Comment by HowToMakeFaceitAB** [comment]
Ty oly-k
And fuck Thomas the retard

**Comment by rivc** [comment]
Thank you for replying & sorry for my retarded issues.

> > Literally the aimbot
> > Is active when the rcs is active
> > So both things end up fucking with eachother, which doesn't fucking let me move mouse, badly coded.
> 
> it isnt badly coded, try setting recoil control x to 0.5 and recoil control y to 1.5
> you can either change the limit of one from code or hold control and click it on the menu to edit it

Thank you @Oly-UK .

**Comment by steel4me** [comment]
Done -> #769, wait for approval from @danielkrupinski
