### ISSUE TITLE
[Suggestion] FAKE LATENCY FOR BETTER BACKTRACK ACCURACY 

### ISSUE THREAD

**Issue by Oly-UK** [danielkrupinski/Osiris#742]
as title says

**Comment by thomas0aotian** [comment]
idk fake ping has anything to do with backtrak

**Comment by Oly-UK** [comment]
it does @thomas0aotian i watch masterlooser regularly and he was talking about how he cant hit some of the ticks with his super legit enabled as it disables his fake latency

**Comment by thomas0aotian** [comment]
@Oly-UK really never heard of it

**Comment by xsincbt** [comment]
It basic extended by on ot

**Comment by ZPDMiller** [comment]
I thought it was patched and you can only backtrack 200ms on Valve servers?

**Comment by HowToMakeFaceitAB** [comment]
You can increase that with fake latency

**Comment by ZPDMiller** [comment]
That's pretty surprising, seeing as how most cheats don't have it

**Comment by thomas0aotian** [comment]
@ZPDMiller zapped.cc can bt ip to 400ms,and the extended bt that we are tlaking about here isn't increasing the bt length

**Comment by ZPDMiller** [comment]
Alright

**Comment by thomas0aotian** [comment]
yeah i am fking typing on my retarded phone and it doesn't have fking auto correction.

**Comment by 0xE232FE** [comment]
I talked many times to Masterlooser, sometimes he is trolling. Don't take not anything he says serious!

**Comment by ZPDMiller** [comment]
Whenever he's asked about coding stuff he's almost always serious, I don't think he'd joke around about stuff like this in the coding aspect

**Comment by littlehurensohn** [comment]
You cant backtrack more than 200ms, valve actually patched it.

And fake latency you can made with the region changer, is ez to paste it into this cheat from other sources, cause its works through cmd(console) ingame ofc.

**Comment by thomas0aotian** [comment]
。。。。

**Comment by thomas0aotian** [comment]
@littlehurensohn it would be real latency then

**Comment by xsincbt** [comment]
Bruh basic ot extended bt

**Comment by xsincbt** [comment]
So it's possible

**Comment by Oly-UK** [comment]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/227226-synced-fake-ping.html
for those who are saying it doent have anything to do with backtrack

**Comment by thomas0aotian** [comment]
@xsincbt from what i knew,op dont fake pings. so op's extended bt are not the fake latency method that we are talking about here.

**Comment by thomas0aotian** [comment]
@Oly-UK bruh since u have the code u wanna do the sdk translation?

**Comment by effex1337** [comment]
> https://www.unknowncheats.me/forum/counterstrike-global-offensive/227226-synced-fake-ping.html
> for those who are saying it doent have anything to do with backtrack

Nice 2017 post

**Comment by xAkiraMiura** [comment]
the backtrack window is 200ms max
the forwardtrack window is also 200ms max
using fake latency we can move the forwardtrack window into the past 
by doing this we remove the need to predict player movement
we have an extended backtrack window of 400ms without any engine prediction
you can move this window even farther back but the size will only ever be 400ms.
