### ISSUE TITLE
[Help] Trying to make the menu only One menu

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#745]
I didn't word the title very good. But im trying to make the menu style only one window and take the menubar completely out of the cheat. if anybody could help me with that it would be appreciated. but everytime i try to do it I just get the Debug menu in game with all the options.

**Comment by 0xE232FE** [comment]
There is already an option in "style".

Check Code here:
https://github.com/danielkrupinski/Osiris/blob/master/Osiris/GUI.cpp#L920

**Comment by Novalaki** [comment]
I know that lol. Im trying to take the "classic" style completely out of the cheat and have just the one window

**Comment by thomas0aotian** [comment]
？

**Comment by thomas0aotian** [comment]
Just check that 1 by default in config.h

**Comment by thomas0aotian** [comment]
Ez and fast

**Comment by Novalaki** [comment]
@thomas0aotian yeah I guess that works. really just wanted to take the menu bar completely out of the cheat.

**Comment by 0xE232FE** [comment]
Okay then you completly do not understand how it works. This is why you not able to remove it. I know it is hard to understand the code in this size. But I find it useful to have a switch for one windowed and menue bar. I love both styles. And so anybody can switch to the thing you like! It is awesome feature. I completly don't understand why people want to delete usefull code. O.o

**Comment by Novalaki** [comment]
Personal preference i guess. I just think the bar is really ugly and I never use it. so I wanna take it out.

**Comment by 0xE232FE** [comment]
Okay start in this function. It's simple to have only the One Window. You can leave the rest untouched until you understand the menue thing.

GUI::render()
https://github.com/danielkrupinski/Osiris/blob/bf1f3becd7db33c1bcd758e7c4cb15b32d9c9a5d/Osiris/GUI.cpp#L47
