### ISSUE TITLE
antiaim thirdperson

### ISSUE THREAD

**Issue by PostmanTap** [danielkrupinski/Osiris#746]
i was trying to add thirdperson antiaim angles like " NETVAR_OFFSET(thirdpersonAngles, "CBasePlayer", "deadflag", 4, Vector);" and setting it to cmd->viewangles cuz thats how i made it in my other base but its not working in this. any idea or any other way of doing it?

**Comment by thomas0aotian** [comment]
Do u mean desync cham or AA angle indicator

**Comment by PostmanTap** [comment]
aa angles like when i set cmd->viewangle = 180 and it still shows me looking forward in thirdperson

**Comment by PostmanTap** [comment]
fixed already 
here is fix : "	
if (stage == FrameStage::RENDER_START && memory.input->isCameraInThirdPerson && interfaces.engine->isInGame())
		*(Vector*)(((DWORD)localPlayer) + 0x31D4 + 0x4) = angle;"

**Comment by asraskmekaidasid** [comment]
where put this code?

**Comment by PostmanTap** [comment]
"stage == FrameStage::RENDER_START" no idea bro

**Comment by notgoodusename** [comment]
> "stage == FrameStage::RENDER_START" no idea bro

what do you mean?
framestagenotify hook has stage

**Comment by notgoodusename** [comment]
NETVAR(thirdpersonAngles, "CBasePlayer", "deadflag", Vector);
