### ISSUE TITLE
Add auto casual queue

### ISSUE THREAD

**Issue by matt1tk** [danielkrupinski/Osiris#747]
Some code on unknown cheats: 

void lobby_stuff::do_queue() {
  using handle_match_start_fn = bool(__thiscall*)(void*, const char*, char*, char*, char*);
  using create_session_fn = void*(__stdcall*)(void);
 
  static auto singleton = *(uint8_t**)(Utils::PatternScan("client_panorama.dll", "8B C8 89 0D ? ? ? ? 8D 41 08") + 4);
  static auto handle_match_start = (handle_match_start_fn)Utils::PatternScan("client_panorama.dll", "55 8B EC 51 53 56 57 8B F9 8B 0D ? ? ? ? 8B 01 FF 50 34");
  static auto create_session = (create_session_fn)Utils::PatternScanFromCall("client_panorama.dll", "E8 ? ? ? ? 83 EC 14 E8");
 
  static auto search_started = []() {
    if (!singleton)
      return false;
    if (auto ls = *(uint8_t**)singleton; ls) {
      return *(uint32_t*)(ls + 0x10) != 0;
    }
    return false;
  };
  
  if (auto match_session = g_match_framework->get_match_session()) {
    if (!search_started()) {
      auto session_settings = match_session->get_session_settings();
      session_settings->set_string("game/type", "classic");
      session_settings->set_string("game/mode", "casual");
      session_settings->set_string("game/mapgroupname", "mg_de_dust2");
      match_session->update_session_settings(session_settings);
      handle_match_start(*(uint8_t**)singleton, "", "", "", "");
    }
  }
  else {
    create_session();
  }
}

It would be nice if this was added to osiris. thanks. had some trouble adding it myself, can't figure it out.

**Comment by xAkiraMiura** [comment]
1: please stop pasting 
2: please put this in code tags
3: please close the issue its dead
