### ISSUE TITLE
GrenadeHelper

### ISSUE THREAD

**Issue by giangero1** [danielkrupinski/Osiris#752]
This Legit Cheat would be awesome to have a grenade helper that has an aim key and an action key, i just i found out this feature on another hack called CornerStone on uknowncheats and this would be a great feature to add on osiris.

**Comment by giangero1** [comment]
like it shows u the spots , u press the aim key aims for u and u press the action key and does the jump throw for you

**Comment by thomas0aotian** [comment]
I understand but show us the codes first

**Comment by thomas0aotian** [comment]
This feature needs a data base to store known spots

**Comment by thomas0aotian** [comment]
It's gonna be really hard

**Comment by giangero1** [comment]
@thomas0aotian @danielkrupinski i found code for it Guys!!!  
Here source files  :  https://github.com/martinjanas/Sensum
Here video of it : https://www.youtube.com/watch?v=JVGJKC9TMIY&feature=youtu.be

**Comment by xAkiraMiura** [comment]
why must you mention daniel in **EVERY COMMENT** you make? 
you are pasting. stop, make original code or dont make anything.
