### ISSUE TITLE
Osiris Discord.

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#754]
[other suggestions]
-it would be nice to have a discord regarding changelogs and a config section, that would be helpful as well.
[cheat suggestions]
-hitchance for the auto shoot
-extended backtrack
-fake latency ( I have heard from people that this increases backtrack accuracy, not a 100% sure)
-engine prediction ( this will be very helpful for people who are legit hacking since the aimbot can be inaccurate at times and can't keep up with the target because of the smooth, this only helps people who don't use backtrack)
Thank you for reading through, have a good day.

**Comment by HowToMakeFaceitAB** [comment]
also, how does recoil based fov work?

**Comment by ZPDMiller** [comment]
How about you set one up and let us all join?

- Yes for extended backtracking
- Fake latency was patched
- Yes for engine prediction

**Comment by HowToMakeFaceitAB** [comment]
> How about you set one up and let us all join?

me?

**Comment by ZPDMiller** [comment]
Well it would be best for Daniel to create one, seeing as how he's the cheat creator, if he even has Discord. Otherwise someone trustworthy would have to set one up, with trustworthy people as mods and shit

**Comment by HowToMakeFaceitAB** [comment]
yeah, I definitely agree.

**Comment by HowToMakeFaceitAB** [comment]
but could you reference an issue where they explain what recoil-based fov is?

**Comment by ZPDMiller** [comment]
Recoil-based fov - aimbot uses recoil as fov origin
Grabbed from the README.md file

**Comment by HowToMakeFaceitAB** [comment]
oh ok, do i enable it to fix the aimbot not working with rcs?

**Comment by HowToMakeFaceitAB** [comment]
i mean the rcs not working with aimbot

**Comment by ZPDMiller** [comment]
try setting recoil control x to 0.5 and recoil control y to 1.5
Or change the values around and toy around with it

**Comment by HowToMakeFaceitAB** [comment]
ok, thank you 👍

**Comment by xsincbt** [comment]
i could go ahead and make it but daniel should make one but if u guys want me to make one i could

**Comment by HowToMakeFaceitAB** [comment]
Please do.

**Comment by effex1337** [comment]
I remember someone making a discord for osiris with roles and shit.
The idea for a discord is just absurd.
This is an open source cheat, open source == you're supposed to debug it urself or post on issues.
He doesn't owe you stuff. hes literally been ignoring so many stuff, why would he wanna make a discord when hes ignoring even in a forum.

**Comment by xsincbt** [comment]
https://discord.gg/JQaEMjf here thee server just for now

**Comment by thomas0aotian** [comment]
@effex1337 true and btw what ever u wish to be on this cheat u r suggesting, don't argue about shit till u really figured it out. Daddy Daniel is already doing a good job on this cheat. Don't talk shit when u weren't contributing like some annoying retards.

**Comment by effex1337** [comment]
Figure out what?

**Comment by effex1337** [comment]
> weren't contributing like some annoying retards.

Lmao do your research before taking I've been helping here since there used to be like 100 ish stars. Also giving leechers and retards the answer they needed. 

> Daddy Daniel

I just died.

**Comment by HowToMakeFaceitAB** [comment]
> @effex1337 true and btw what ever u wish to be on this cheat u r suggesting, don't argue about shit till u really figured it out. Daddy Daniel is already doing a good job on this cheat. Don't talk shit when u weren't contributing like some annoying retards.

We might be retards, but you're just a toxic ass, please stop

**Comment by HowToMakeFaceitAB** [comment]
And not everyone knows how to code btw, don't forget that

**Comment by thomas0aotian** [comment]
@effex1337 chill out mu dude i am supporting u

**Comment by thomas0aotian** [comment]
@HowToMakeFaceitAB lmao I don't know.a single stuff of about coding half month ago

**Comment by effex1337** [comment]
> > @effex1337 true and btw what ever u wish to be on this cheat u r suggesting, don't argue about shit till u really figured it out. Daddy Daniel is already doing a good job on this cheat. Don't talk shit when u weren't contributing like some annoying retards.
> 
> We might be retards, but you're just a toxic ass, please stop

That's not called being toxic that's just giving appropriate answers where its needed.

**Comment by effex1337** [comment]
Don't think that can be called supporting. 
I'm just giving appropriate answers where required and some are just so retarded,  i just lose it.

**Comment by thomas0aotian** [comment]
@effex1337 i wasn't talking to you in that comment u see btw?
