### ISSUE TITLE
Fix old configs

### ISSUE THREAD

**Issue by Flaam** [danielkrupinski/Osiris#755]
Hi, how can i fix my old config, i don't want to lose them.

**Comment by ZPDMiller** [comment]
Note your old settings down, and then set them in your latest build.

**Comment by Flaam** [comment]
@ZPDMiller Yeah ok but i have a lot of skins on the config. Wait, do you have Discord? If you have some configs for legit hacking can u send them to me? Flaam#8135

**Comment by ZPDMiller** [comment]
I agree there should be some way to keep old configs, or at least create a skin configuration. You should create your own legit configs, as your play style is different to everyone else

**Comment by thomas0aotian** [comment]
ok boi heres how u are gonna do it
first u open the config in notepad++
u ctrl + f and then type in skinchanger
then you copy `"skinChanger" : 
	[......],` and then paste them inside the new config that u built.

You can create a txt and paste the skin settings in just that when next update is out u can replace the new cfg faster.
