### ISSUE TITLE
viewmodel aimbot

### ISSUE THREAD

**Issue by Oly-UK** [danielkrupinski/Osiris#756]
so i've seen flowhooks and masterlooser use a viewmodel aimbot and i believe it's avaliable on uc, i would love to see it in osiris

**Comment by notgoodusename** [comment]
what do you mean by "viewmodel aimbot"?

**Comment by Mufinekkk** [comment]
masterlooser is using viewmodel offset, not an "viewmodel aimbot".
https://github.com/danielkrupinski/Osiris/pull/584

**Comment by ZPDMiller** [comment]
I think he means that whenever aimbot is active and your player model is locked on to somebody, it will show that in first person (your arms pointing towards an enemy, but you still face whatever direction, like forward, backtwards, etc.)

**Comment by HowToMakeFaceitAB** [comment]
Do you mean viewangle aimbot? Or viewmodel

**Comment by Novalaki** [comment]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/336227-viewmodel-aimbot.html 
everything you need is here

**Comment by Oly-UK** [comment]
thanks! @Novalaki

**Comment by giangero1** [comment]
this is so cool

**Comment by thomas0aotian** [comment]
I can do a pr

**Comment by CantRememberMyself** [comment]
this would be cool

**Comment by Oly-UK** [comment]
seriously? that's be so cool! @thomas0aotian

**Comment by thomas0aotian** [comment]
k wait till i got home I'm in school now xD

**Comment by thomas0aotian** [comment]
k wait till i got home I'm in school now xD

**Comment by notgoodusename** [comment]
i wanna see that pr, idk if u can but try

**Comment by thomas0aotian** [comment]
Yeah I'm not sure

**Comment by appleman1232** [comment]
autism
