### ISSUE TITLE
Skin Changer [ Help ]

### ISSUE THREAD

**Issue by LegitCheater** [danielkrupinski/Osiris#757]
Can someone please me tell me more about the skin changer and how it works?
I also don't know how to use the stickers.
If there's FREE legit configs please msg me at discord : Jaxad#6702

**Comment by Mufinekkk** [comment]
You must have IQ upper than 80

**Comment by Shaxzy** [comment]
> You must have IQ upper than 80

**Comment by ZPDMiller** [comment]
There are plenty of yt videos that showcase skinchangers in cheats, watch one of them

**Comment by HowToMakeFaceitAB** [comment]
> You must have IQ upper than 80

An IQ*. Higher* than 80
Apparently you Don't have that, so take your toxicity elsewhere

**Comment by HyeN2018** [comment]
If u dont understand how its working , search on google , if u still dont understand , than leave cheating. One more thing , dont come here with an issue like this , thats not an cheat issue , your brain is the issue

**Comment by notgoodusename** [comment]
Dude, he just  asked how it works it maybe a retarded issue but he still needs help, telling that hes stupid doesnt help him in any point instead you are discouraging him to do what he wants.

**Comment by Mufinekkk** [comment]
> > You must have IQ upper than 80
> 
> An IQ*. Higher* than 80
> Apparently you Don't have that, so take your toxicity elsewhere

You wasn't understand what I mean posting comment like this.

**Comment by LegitCheater** [comment]
> There are plenty of yt videos that showcase skinchangers in cheats, watch one of them

I don't think there is. I looked before commenting btw. and If there's then they're prob in a different lang

**Comment by ZPDMiller** [comment]
Well it isn't too hard to use the skinchanger, you select the weapon you want to change skins for, you select the paint kit tab, and scroll down to find the skin you want. csgostash.com has all the skins with previews on display if you wanna browse all available skins. For stickers, you can apply up to five. You select any of the tabs on the right, the ones with numbers (#1, #2, #3, #4, and #5). Then you choose whatever sticker kit you wanna use. Stattrack and Seed are simple, you just select the number you wanna use. Once you're done, press update and enjoy. Be sure to save your config regularly, as re-doing skins all over again can be tedious.

Oh and make sure the skinchanger is enabled
