### ISSUE TITLE
[Question] Anyone know this feature?

### ISSUE THREAD

**Issue by agshaidun** [danielkrupinski/Osiris#758]
https://www.youtube.com/watch?v=GEV3jblzCtY&t=231

take a look at 3:53

he was following/mimic the player movement .

idk what is this feature call but it look so fun

**Comment by notgoodusename** [comment]
"Block bot" is a bot that blocks people, thats it

**Comment by rosesware** [comment]
https://github.com/danielkrupinski/Osiris/pull/739

**Comment by agshaidun** [comment]
Thank You!!
