### ISSUE TITLE
Head Dot & Csgo.exe CRASHED!

### ISSUE THREAD

**Issue by CemreKusdemir** [danielkrupinski/Osiris#759]
Hey, When I enabled HEAD DOT FOR ESP my game crashed.. I think it's little bug...

**Comment by thomas0aotian** [comment]
It's ID-10T / IBM error

**Comment by thomas0aotian** [comment]
I could also be PEBKAC

**Comment by thomas0aotian** [comment]
But anyway it's a PICNIC error

**Comment by 0xE232FE** [comment]
I am confused about the question?
Head Dot is working and do not have issues. Check the [prerequisites](https://github.com/danielkrupinski/Osiris#prerequisites)and compile again.
