### ISSUE TITLE
Hack crashes after inject

### ISSUE THREAD

**Issue by NexSqaud** [danielkrupinski/Osiris#76]
Code is not modified. The game does not crash.
Build: VS 2017 Community
Windows SDK: 10.0.17763.0
OS: Windows 10 x64
CSGO: 1.36.8.1, non-steam
An exception was thrown at the address 0x00F67267 (Osiris.dll) in csgo.exe: 0xC0000005: read access violation at 0x00000000.

**Comment by didisko33** [comment]
CSGO: 1.36.8.1, non-steam
The cheat working only on steam version
