### ISSUE TITLE
is it possible to draw backtrack on local?

### ISSUE THREAD

**Issue by CantRememberMyself** [danielkrupinski/Osiris#760]
So i tried putting the backtrack chams in local player, then i tried changing entity in backtrack.cpp to localplayer in a new void, ect but cant seem to get them to render on myself

**Comment by thomas0aotian** [comment]
Lmao that's not backtrak

**Comment by thomas0aotian** [comment]
It's the lag

**Comment by CantRememberMyself** [comment]
is it possible to render the backtrack chams that are in this source on local? yes or no?

**Comment by thomas0aotian** [comment]
No

**Comment by thomas0aotian** [comment]
It's nor backtrak, it's lag for local players. Backtraks are only for enermies.

**Comment by CantRememberMyself** [comment]
okay thanks, i didnt want it to render my lag, i was trying to do it as a retarded desync chams

**Comment by thomas0aotian** [comment]
U clearly don't know what lag is, when u r backtraking that means u r shooting their lag. And btw backtrak is a verb not a noun which most of u guys used it this way

**Comment by CantRememberMyself** [comment]
i know what lag is, i thought you were referring to rendering my fake lag sir
and also backtrack is both a verb and noun, i dont know why you brought your english knowledge into this however allow me prove you wrong; 
a verb = a word used to describe an action
a noun = a word used to indentify people. places or things

Backtrack is the name given to the feature of abusing the tickrate system to shoot at peoples previous ticks, thus meaning it's a noun and verb.

example for noun: Hey bro i'm going to add backtrack to my cheat today
example for verb: i'm going to backtrack this guy.

**Comment by notgoodusename** [comment]
hes asking for backtrack chams on localplayer it is possible

**Comment by CantRememberMyself** [comment]
any idea how i could do it, im bamboozled by my attempts

**Comment by notgoodusename** [comment]
idk,but dont create a full new function for this feature look at backtrack.cpp, chams.cpp

**Comment by thomas0aotian** [comment]
Backtrak is originally a verb, u guy just used it wrong. The noun that u guys r using should be lag instead of "backtrak". And if u wanna render lag in which enermies can backtrak just draw all record chams in the past 200ms

**Comment by thomas0aotian** [comment]
So shoot his backtrak should be backtrak him or shoot his lag. Say it right next time boi

**Comment by thomas0aotian** [comment]
And u can not draw ur own lags! Lag all depends on whoever is trying to backtrak u! Their ping to the server and ur ping to the server are directly related. So u can not draw ur exact own lag but u can draw ur lags in a certain amount of time let's say 200ms which is most cheat's maximum bt time. And btw if they wanted to bt u for 200ms they sure can hit the last tick but the hitchance for hitting between first and last ticks may vary due to server pings.

**Comment by thomas0aotian** [comment]
There's lot a thing u still need to learn about csgo cheats.

**Comment by effex1337** [comment]
Get fake matrix for localplayer on curtime.
Render it. (its fakelag chams also the closest thing to what he might have meant, since there's nothing like backtrack local chams anywhere)

**Comment by notgoodusename** [comment]
> Get fake matrix for localplayer on curtime.
> Render it. (its fakelag chams also the closest thing to what he might have meant, since there's nothing like backtrack local chams anywhere)

P anim fix

**Comment by thomas0aotian** [comment]
@effex1337 agreed

**Comment by xAkiraMiura** [comment]
backtrack works for every networkable entity. in my backtrack i specifically filter out teammates however i could store their previously locations as well. you can store the local player's past 14 ticks to visualize where you are backtrackable. there is no other real reason in doing that because you cant backtrack yourself.
