### ISSUE TITLE
ENGINE PREDICTION

### ISSUE THREAD

**Issue by thomas0aotian** [danielkrupinski/Osiris#761]
I was tryna do it but I failed cuz the codes from uc is too messed up plz just dont paste it in here. I did some research but I couldn't figue this out. Hopefully daddy Danial is gonna do it.:smiley:

**Comment by notgoodusename** [comment]
will work on it

**Comment by thomas0aotian** [comment]
Btw i checked the code on uc about forwardtrak, that shit won't work when target changed its initial angle

**Comment by notgoodusename** [comment]
why do you wanna forwardtrack?

**Comment by effex1337** [comment]
You need to add interfaces before you can add engine prediction.
It was actually pretty easy lmao.
P.S. edge jump requires engine prediction for those people asking for it.

**Comment by notgoodusename** [comment]
> You need to add interfaces before you can add engine prediction.
> It was actually pretty easy lmao.
> P.S. edge jump requires engine prediction for those people asking for it.

Lol

**Comment by thomas0aotian** [comment]
@notgoodusename ppl thought it would be enginepred

**Comment by thomas0aotian** [comment]
@effex1337 daddy down for help may be?

**Comment by anonymouschicken1111** [comment]
Can u link the uc thread?

**Comment by NNiX1** [comment]
engine prediction would rly make this cheat best :)
