### ISSUE TITLE
standalone rcs

### ISSUE THREAD

**Issue by gangbossman** [danielkrupinski/Osiris#762]
please add standalone rcs. thanks

**Comment by thomas0aotian** [comment]
@gangbossman it's much harder than it sounds bro

**Comment by thomas0aotian** [comment]
I think I have some ideas. About to get that idea accomplished tmr

**Comment by steel4me** [comment]
Done -> https://github.com/danielkrupinski/Osiris/pull/769, wait for approval from @danielkrupinski
