### ISSUE TITLE
Engine prediction

### ISSUE THREAD

**Issue by HowToMakeFaceitAB** [danielkrupinski/Osiris#765]
Tried to do forward tracking but that shit is useless when the enemy changes direction

**Comment by HowToMakeFaceitAB** [comment]
https://m.youtube.com/watch?v=WCFS4WM8L6Q

**Comment by HowToMakeFaceitAB** [comment]
I successfully did forward tracking but it ended up being useless so i just added it to my hvh paste

**Comment by HowToMakeFaceitAB** [comment]
Btw i don't understand other engine prediction, i only managed to understand forward tracking, bother explaining it for me?

**Comment by HowToMakeFaceitAB** [comment]
Wait, isn't the createmove 1 tick behind?? Doesn't that mean you just have to predict 1 tick after?

**Comment by HowToMakeFaceitAB** [comment]
Also engine prediction requires perfect movement fix as i heard not sure, dont judge me pls

**Comment by effex1337** [comment]
You need the movement Helper interface not rly a perfect movement fix.
