### ISSUE TITLE
Griffing bot + source

### ISSUE THREAD

**Issue by kvetinkavole** [danielkrupinski/Osiris#768]
add ?
https://www.unknowncheats.me/forum/cs-go-releases/361870-animesoftware-external-griefing-hack-runboostbot-blockbot-doorspammer.html

**Comment by tirziz** [comment]
ok, why you just cant do it yourself lol.
Ctrl + c then ctrl + v

**Comment by ZPDMiller** [comment]
Griefing**

**Comment by thomas0aotian** [comment]
Hella grigging bot

**Comment by thomas0aotian** [comment]
@notgoodusename Alright daddy

**Comment by thomas0aotian** [comment]
I think I had an idea of adding standalone rcs
