### ISSUE TITLE
Stupid question

### ISSUE THREAD

**Issue by caris1st** [danielkrupinski/Osiris#77]
I am new to cheating and just learnt some stuff about it. Can I get some answers for my question?
When I play on my prime legit account, will I never be detected if I just don't use cheats, or will it be the same since csgo.exe itself is injected? Also, I assume not a lot of people use this cheat, so is this pretty much a private paste that will unlikely get detected?

+Is cheat harder to use undetected in competitive than deathmatch and casual (I want to go blatant in deathmatch and casuals)?

**Comment by didisko33** [comment]
Do not use public cheats, you'll always have a risk to get banned, or just modify this source for yourself (change signature, remove/add features, etc).
