### ISSUE TITLE
New Csgo Update!!!!

### ISSUE THREAD

**Issue by giangero1** [danielkrupinski/Osiris#771]
http://counter-strike.net/shatteredweb 
![image](https://user-images.githubusercontent.com/56077913/69103052-f4eadd80-0a6c-11ea-81a8-15fb9611f3b3.png)

https://www.unknowncheats.me/forum/counterstrike-global-offensive/103220-counterstrike-global-offensive-reversal-structs-offsets-606.html

Halp

**Comment by itchy2019** [comment]
CS:GO UPDATED

https://blog.counter-strike.net/index.php/category/updates/

CRASH after inject

**Comment by giangero1** [comment]
Actually i can inject with xenos!!! so it's the injectors problem i used another one called DllEmbeddedInjectorMaker from uknown cheats so i will close this thread
