### ISSUE TITLE
add auto jumpbug?

### ISSUE THREAD

**Issue by mimphes** [danielkrupinski/Osiris#773]
please add auto jump bug to this awesome cheat
much appreciated

**Comment by thomas0aotian** [comment]
wdym

**Comment by mimphes** [comment]
> wdym

its when you crouch then let go of crouch 4 units above the ground then you keep your speed and gete greater height. look up csgo jumpbug for more info

**Comment by thomas0aotian** [comment]
U mean jump crouch?

**Comment by mimphes** [comment]
> U mean jump crouch?

i mean like its a bug that gives you no fall damage and also allows you to hit crazy jumps. look it up

**Comment by Novalaki** [comment]
This would be cool

**Comment by 0x1Eren** [comment]
This could get patched pretty quick so i myself dont see any point in seeing this in the main cheat.

**Comment by mimphes** [comment]
> This would be cool

ikr its awesome

**Comment by mimphes** [comment]
> This could get patched pretty quick so i myself dont see any point in seeing this in the main cheat.

this hasn't been patched since 1.6. its not getting patched. 
watch this video https://www.youtube.com/watch?v=MKSYLkpi7ZY see how it says JB above his speed? ( also a great feature) that means the cheat is doing a auto jumbug. thats how he is hitting all those jumps. those jumps are near impossible without auto jb.

**Comment by thomas0aotian** [comment]
Search for any codes(can even be the lua but then i need the full sdk explanations.) if u can then I might be able to increment it.

**Comment by mimphes** [comment]
> Search for any codes(can even be the lua but then i need the full sdk explanations.) if u can then I might be able to increment it.

oh sick fr ive got some right here. i think this is the whole code. if possible make it bindable to a key but if not its coded to mouse3 click.


 //    auto-jb
            if ( GetAsyncKeyState( VK_MBUTTON ) && m_vars.misc_jumpbug ) {

                if ( !( local_p->m_fFlags( ) & FL_ONGROUND ) ) {
                    if ( isground( ) ) {
                        cmd->buttons &= ~in_duck;
                    }
                }
            }

bool isground( ) {
    vec3_t origin = m_global.local_p->m_vecOrigin( );
    origin += m_global.local_p->m_vecVelocity( ) * m_interfaces.globalvars->interval_per_tick;

    Ray_t ray;
    ray.init( origin, origin - vec3_t( 0, 0, 4 ) );

    CTraceFilterSkipEntity fil( m_global.local_p );

    trace_t    tr;

    m_interfaces.enginetrace->TraceRay( ray, MASK_PLAYERSOLID, &fil, &tr );

    if ( tr.fraction == 1.0f )
        return false;

    return true;
}

**Comment by mimphes** [comment]
> Search for any codes(can even be the lua but then i need the full sdk explanations.) if u can then I might be able to increment it.

if its easier, go to this link. https://hatebin.com/iqoihvrdbn

**Comment by mimphes** [comment]
> Search for any codes(can even be the lua but then i need the full sdk explanations.) if u can then I might be able to increment it.

https://www.unknowncheats.me/forum/counterstrike-global-offensive/352766-auto-jumpbug-issue.html 
more code

**Comment by thomas0aotian** [comment]
@mimphes u r pasting codes from a thread that called the jump bug ISSUES, which means they had problem making the jump bugs work on higher level

**Comment by mimphes** [comment]
@thomas0aotion the first one (hatebin) works. I only linked the UC one because it had a prediction code. I wasn't sure if you needed that

**Comment by mimphes** [comment]
@thomas0aotion the first one (hatebin) works. I only linked the UC one because it had a prediction code. I wasn't sure if you needed that

**Comment by mimphes** [comment]
@thomas0aotian hatebin works I linked UC because it had prediction code

**Comment by thomas0aotian** [comment]
@mimphes nah bruh what i am saying id that the author from the codes that u provided needed help which means his codes are prob not working

**Comment by mimphes** [comment]
@thomas0aotian bruh surely at least try please 😘

**Comment by mimphes** [comment]
> @mimphes nah bruh what i am saying id that the author from the codes that u provided needed help which means his codes are prob not working

ok. so i finally found a completely working jumpbug source. please add it if you can or atleasy try
https://www.unknowncheats.me/forum/cs-go-releases/365274-jumpbug-source.html
