### ISSUE TITLE
Help ?

### ISSUE THREAD

**Issue by Anasx69** [danielkrupinski/Osiris#777]
Can someone refer me to a youtube tutorial or anything that tells me how should i compile this source ? Im new sorry for inconvenence

**Comment by ZPDMiller** [comment]
The instructions are in the readme

**Comment by 0xE232FE** [comment]
Before Compile getting Started with Visual Studio 2019
https://www.youtube.com/watch?v=1CgsMtUmVgs

**Comment by Anasx69** [comment]
Thanks
