### ISSUE TITLE
is osiris detected?????

### ISSUE THREAD

**Issue by jBZ8hwBS1QS** [danielkrupinski/Osiris#778]

**Comment by VuBrian22** [comment]
It shouldn't be.

**Comment by 0xE232FE** [comment]
It could be detected at any time. Why you asking?

**Comment by tirziz** [comment]
Atm hooking still undetected, you just need to worry about VAC scanning signature and PE I think

**Comment by giangero1** [comment]
i use vacbypass made by danielkrupinski and xenos native injection no vacs very happy 👍

**Comment by 0xE232FE** [comment]
Please close this issue. Question is answered.

**Comment by Kraken69** [comment]
> i use vacbypass made by danielkrupinski and xenos native injection no vacs very happy

Yo giangero, is that u?
What happened to ur yt channel?

**Comment by xAkiraMiura** [comment]
Why are you necroing a 3 month old closed issue.
