### ISSUE TITLE
HeadDot Performance issue

### ISSUE THREAD

**Issue by 0xE232FE** [danielkrupinski/Osiris#779]
Hello @danielkrupinski 

I would strictly recommend you to use this Function from the Valve SDK to draw the HeadDot circle. I see signifact Performance Issue on a low performance Computer with the DrawCircle function you use. On a High Performance Computer with 12 Cores there are no issues on a low Performance Computer with 2-4 Cores are significant performance problems and crashes.

https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/public/VGuiMatSurface/IMatSystemSurface.h#L81

`virtual void DrawColoredCircle( int centerx, int centery, float radius, int r, int g, int b, int a ) = 0;`

**Comment by 0xE232FE** [comment]
@danielkrupinski 
I implemented the Surface Functions **drawColoredCircle** it makes it possible to draw a colored circle with **drawFilledCircle**
https://github.com/0xE232FE/Osiris/blob/25c98138f45fcd197e994c10815c40d49e54f5bd/Osiris/SDK/Surface.h#L110
https://github.com/0xE232FE/Osiris/blob/25c98138f45fcd197e994c10815c40d49e54f5bd/Osiris/SDK/Surface.h#L120

**Comment by ZerGo0** [comment]
> @danielkrupinski
> I implemented the Surface Functions **drawColoredCircle** it makes it possible to draw a colored circle with **drawFilledCircle**
> https://github.com/0xE232FE/Osiris/blob/25c98138f45fcd197e994c10815c40d49e54f5bd/Osiris/SDK/Surface.h#L110
> https://github.com/0xE232FE/Osiris/blob/25c98138f45fcd197e994c10815c40d49e54f5bd/Osiris/SDK/Surface.h#L120

Is there any text outline function as well, I changed the watermark to display a bunch of debugging variables for me. The text is just flat and has no outline, it would be nice to have a outline for it. Any idea?

**Comment by thomas0aotian** [comment]
@ZerGo0 use different fonts the 17th is good
