### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by asraskmekaidasid** [danielkrupinski/Osiris#785]
static void __stdcall paintTraverse(unsigned int panel, bool forceRepaint, bool allowForce, UserCmd* cmd) noexcept
{
	if (interfaces.panel->getName(panel) == "MatSystemTopPanel") {
		Misc::lci(cmd);
		Misc::drawBombTimer();
		Misc::watermark();
		Misc::spectatorList();
		Esp::render();
	}
	hooks.panel.callOriginal<void, unsigned int, bool, bool>(41, panel, forceRepaint, allowForce, cmd);
}
my code it's good but i get crash, help me pls

**Comment by littlehurensohn** [comment]
Remove that code with (cmd)

**Comment by asraskmekaidasid** [comment]
but i must have with cmd

**Comment by effex1337** [comment]
Post the code for Misc::lci(cmd);
Or find a way to separate the code, So that you call the cmd stuff in createmove and drawing stuff in paint traverse.
