### ISSUE TITLE
Things about the config

### ISSUE THREAD

**Issue by thomas0aotian** [danielkrupinski/Osiris#787]
So I wanna store muiltiple config files within the dll and load them directly from the dll source. Is there any ways that i can accomplish this?

**Comment by danielkrupinski** [comment]
You can do this as follows (in **Config::load**()):
```cpp
Json::Value json;

const std::string myConfigEmbeddedInDLL{ R"({ "Misc" : { "Bunny hop" : true } })" };

if (std::unique_ptr<Json::CharReader> reader{ Json::CharReaderBuilder{ }.newCharReader() }; !reader->parse(myConfigEmbeddedInDLL.c_str(), myConfigEmbeddedInDLL.c_str() + myConfigEmbeddedInDLL.length(), &json, nullptr))
    return;
```

**Comment by thomas0aotian** [comment]
@danielkrupinski Thanks Daniel but how are u gonna do it with muiltiple config

**Comment by thomas0aotian** [comment]
> You can do this as follows (in **Config::load**()):
> 
> ```c++
> Json::Value json;
> 
> const std::string myConfigEmbeddedInDLL{ R"({ "Misc" : { "Bunny hop" : true } })" };
> 
> if (std::unique_ptr<Json::CharReader> reader{ Json::CharReaderBuilder{ }.newCharReader() }; !reader->parse(myConfigEmbeddedInDLL.c_str(), myConfigEmbeddedInDLL.c_str() + myConfigEmbeddedInDLL.length(), &json, nullptr))
>     return;
> ```

danial plz help I wanted to paste my entire cfg in but it wont work cuz the string is too long, how can I do this.

**Comment by thomas0aotian** [comment]
@danielkrupinski
