### ISSUE TITLE
[Suggestion] Aim Time

### ISSUE THREAD

**Issue by Finndramere** [danielkrupinski/Osiris#788]
Aim Time. Because pistols and other weapons arent aiming instantly. The current fov slider isnt very accurate so it just jumps to 1 fov. Using silent fov is very blatant. I have no idea how to reduce the slider or add a slider that is limited to only 15 fov or less for more accurate adjustment for pistols.

**Comment by 0x1Eren** [comment]
Same.

**Comment by steel4me** [comment]
> Aim Time. Because pistols and other weapons arent aiming instantly. The current fov slider isnt very accurate so it just jumps to 1 fov. Using silent fov is very blatant. I have no idea how to reduce the slider or add a slider that is limited to only 15 fov or less for more accurate adjustment for pistols.

AimTime is a complete other Feature then the adjustment of FOV. Im a bit confused what you need. For your own purposes i can answer at least your FOV adjustment. But this will be for any other weapon. But there is no need for more then a FOV a 5 when you play legit.

Edit file osiris\gui.cpp, search this line:
`ImGui::SliderFloat("Fov", &config.aimbot[currentWeapon].fov, 0.0f, 255.0f, "%.2f");`

Change it to:
`ImGui::SliderFloat("Fov", &config.aimbot[currentWeapon].fov, 0.0f, 15.0f, "%.5f");`

The slider now moves from 0 to 15 in 0.5 steps! Compile and test it.

**Comment by thomas0aotian** [comment]
U can do a first shot delay

**Comment by thomas0aotian** [comment]
I think that's what u mean by aim time

**Comment by steel4me** [comment]
i know aimtime as defined timespan where aimer is active, after that aimer stops...only with aimlock while pressing key useful

**Comment by Finndramere** [comment]
> > Aim Time. Because pistols and other weapons arent aiming instantly. The current fov slider isnt very accurate so it just jumps to 1 fov. Using silent fov is very blatant. I have no idea how to reduce the slider or add a slider that is limited to only 15 fov or less for more accurate adjustment for pistols.
> 
> AimTime is a complete other Feature then the adjustment of FOV. Im a bit confused what you need. For your own purposes i can answer at least your FOV adjustment. But this will be for any other weapon. But there is no need for more then a FOV a 5 when you play legit. I take your example with FOV 15.
> 
> Edit file osiris\gui.cpp, search this line:
> `ImGui::SliderFloat("Fov", &config.aimbot[currentWeapon].fov, 0.0f, 255.0f, "%.2f");`
> 
> Change it to:
> `ImGui::SliderFloat("Fov", &config.aimbot[currentWeapon].fov, 0.0f, 15.0f, "%.5f");`
> 
> The slider now moves from 0 to 15 in 0.5 steps! Another example, If you change %0.5f to %0.1f, the slider will get more and more inaccurate, cause 0.5 means 30 steps when you move silder, 0.1 means 150 steps if you move slider. FOV 255 means 1250 steps. Compile and test it, have fun!
> 
> **There is also another function based on ImGUI. But this is very dangerous if you type in wrong values, be careful. Just hold ctrl on keyboard and click into the slider, now you can type in the value you like.**
> 
> **If you type in to high or wrong values this can lead into untrust and this leads into permanently ban. This means your profile will show VAC Ban.**
> 
> @danielkrupinski i think, somehow, ctrl function of imgui should be disabled or every slider with float and int must be clamped. Just for your information.
> 
> EDIT12: Maybe my explanation is strictly argued, just give me advises. I just got untrusted on other meme's that i used with imgui integrated last years, cause i typed in wrong values ò_Ó

i knew i was right that slider adjustment is on gui.cpp but i was too scared to adjust it cuz as u said i might get untrusted because of wrong values. i suggested aim time because with silent aim off, smoothing a little above 1(1.44 and above) and between shots off it isnt too snappy and just shoots before it snaps on the head making you miss alot. Aim Time would benefit those who dont use silent aim because the aimbot has more time to adjust before it shoots. I saw this feature on that cheat that went free for 1 month i cant remember the name. Btw thank you for the help <3

**Comment by steel4me** [comment]
> i knew i was right that slider adjustment is on gui.cpp but i was too scared to adjust it cuz as u said i might get untrusted because of wrong values. i suggested aim time because with silent aim off, smoothing a little above 1(1.44 and above) and between shots off it isnt too snappy and just shoots before it snaps on the head making you miss alot. Aim Time would benefit those who dont use silent aim because the aimbot has more time to adjust before it shoots. I saw this feature on that cheat that went free for 1 month i cant remember the name. Btw thank you for the help <3

i explained too much, it won't geht you untrust when you change gui.cpp to:
`ImGui::SliderFloat("Fov", &config.aimbot[currentWeapon].fov, 0.0f, 15.0f, "%.5f");`

I meant another feature, without changing anything. load osiris, in main menu open osiris menu, go to aimbot, hold the key CTRL and click infot slider, now you can type in the value manually.
That **can** end in a untrust .

Example, you type in fov 5000 and it should not exceed 255 ;)

**Comment by Finndramere** [comment]
> o

for months i have been using cheats that have been using IMGUI. I never knew about the hold CTRL + Click function. I feel so dumb last night when you mentioned it.

**Comment by steel4me** [comment]
> for months i have been using cheats that have been using IMGUI. I never knew about the hold CTRL + Click function. I feel so dumb last night when you mentioned it.

no problem mate, you are not alone, i bet many users don't know it

**Comment by thomas0aotian** [comment]
@Finndramere u can tab too
