### ISSUE TITLE
[Suggestion] Mouse button support for Triggerbot

### ISSUE THREAD

**Issue by x4zm** [danielkrupinski/Osiris#79]
Any way to make the Triggerbot work when holding any of the mouse keys?
(VK_XBUTTON1, VK_XBUTTON2, VK_RBUTTON,)
The Triggerbot doesn't detect any of my mouse keys.
Still, this is probably the best cheat i used so far, amazing work

**Comment by danielkrupinski** [comment]
Implemented e49b69cd89ad83fa26e47c728844925e6c61ff2c
