### ISSUE TITLE
Watermark

### ISSUE THREAD

**Issue by Nexo848** [danielkrupinski/Osiris#791]
Hi, i want to draw filled rect in watermark funcion, of course im using interfaces.surface->drawFilledRect(), but nothing is showing up. Any idead what goes wrong?

**Comment by MinecraftGoodGame** [comment]
add your function to painttraverse hook

**Comment by Nexo848** [comment]
But watermark is already in, i placed drawFilledRect() in watermark function.

**Comment by MinecraftGoodGame** [comment]
Can you show me your code?

**Comment by danielkrupinski** [comment]
You probably forgot to set drawing color, example:
```cpp
interfaces.surface->setDrawColor(0, 127, 255, 50);
const auto [screenWidth, screenHeight] = interfaces.surface->getScreenSize();
interfaces.surface->drawFilledRect(0, 0, screenWidth, screenHeight);
```

**Comment by Nexo848** [comment]
No, i even set the color, i will try your code, maybe it will work

**Comment by Nexo848** [comment]
`interfaces.surface->setDrawColor(33, 35, 47, 1.0f);
interfaces.surface->drawFilledRect(screenWidth - 275, 4, 260, 20);`

**Comment by Nexo848** [comment]
My code is:
`interfaces.surface->setDrawColor(33, 35, 47, 1.0f);
		interfaces.surface->drawFilledRect(screenWidth - 275, 4, 260, 20);`

**Comment by Nexo848** [comment]
My code is:
`interfaces.surface->setDrawColor(33, 35, 47, 1.0f);`
`interfaces.surface->drawFilledRect(screenWidth - 275, 4, 260, 20);`

**Comment by Nexo848** [comment]
Wait, i think i know whats the problem, tell me wich number is rect height, which is rect width, which is x and which is y.

**Comment by danielkrupinski** [comment]
```cpp
template <typename T>
constexpr void drawFilledRect(T x0, T y0, T x1, T y1) noexcept
```
x0, y0 - screen coordinates of the top-left corner
x1, y1 - screen coordinates of the bottom-right corner

Therefore **x1 > x0** and **y1 > y0**

**Comment by Nexo848** [comment]
i still cant get it, why this sint frawing a small recatngle on top right of the screen? 
`interfaces.surface->drawFilledRect(screenWidth - 275, 15, 15, screenHeight - 4);`

**Comment by Nexo848** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/54820747/69485156-ce95bb00-0e3b-11ea-9e38-56db5c6ad124.png)
i want to draw something like this

**Comment by MinecraftGoodGame** [comment]
Well that's weird, I'm trying to figure out too

**Comment by danielkrupinski** [comment]
> Points on the screen are described by x- and y-coordinate pairs. The x-coordinates increase to the right; y-coordinates increase from top to bottom.

**Comment by MinecraftGoodGame** [comment]
It's positioning's fault but I'm too lazy to do that you for so that's your job

**Comment by Nexo848** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/54820747/69485353-7a400a80-0e3e-11ea-9d48-82da56644d46.png)
`interfaces.surface->setDrawColor(33, 35, 47, 255);`
`interfaces.surface->drawFilledRect(screenWidth - 275, 30, screenWidth - 15, 4);`
`interfaces.surface->setDrawColor(23, 25, 37, 255);`
`interfaces.surface->drawOutlinedRect(screenWidth - 275, 30, screenWidth - 15, 4);`
well, that makes more sense but still not looking like it should

**Comment by Nexo848** [comment]
well, i made my own function, it have same effect but its easier to use
![Screenshot_3](https://user-images.githubusercontent.com/54820747/69485638-9e9de600-0e42-11ea-9f74-2756906c833b.png)

**Comment by thomas0aotian** [comment]
bruh did u finish the water mark? really wanna learn how to

**Comment by Nexo848** [comment]
Yes, i finished it, you can add me on discord: Mecenas OwO#8888
