### ISSUE TITLE
Add Legit AA

### ISSUE THREAD

**Issue by csgocode** [danielkrupinski/Osiris#792]
Hello, I tried to add legit aa but it gives me errors and I don't know how to do it, could you help me to add it?

**Comment by notgoodusename** [comment]
check this #739

**Comment by rosesware** [comment]
@notgoodusename that's not legit aa.

**Comment by notgoodusename** [comment]
what do u think it is then?

**Comment by thomas0aotian** [comment]
@notgoodusename yeah bruh me and my friends tested out the AA and found out it's not legit. The slidemove desync is not desyncing even the fake and real angle thirdperson is wrong. The server head is still the real head. And also the yaw/pitch anti-aim is not even local desyncing which means when ur attack angle is not the view angle. Every bullets will go to wherrever it's set.

**Comment by notgoodusename** [comment]
> @notgoodusename yeah bruh me and my friends tested out the AA and found out it's not legit. The slidemove desync is not desyncing even the fake and real angle thirdperson is wrong. The server head is still the real head. 
i dont recomend using sidemove, lby is wayy better, thirdperson is not accurate but gives the idea for the real to work u need to choke, 
>And also the yaw/pitch anti-aim is not even local desyncing which means when ur attack angle is not the view angle. Every bullets will go to wherrever it's set.
its a bug actually idk why it happens but i looks normal for the server and hits people, i have tested with my friends lby breaker not sidemove will see if i can fix

**Comment by thomas0aotian** [comment]
> > @notgoodusename yeah bruh me and my friends tested out the AA and found out it's not legit. The slidemove desync is not desyncing even the fake and real angle thirdperson is wrong. The server head is still the real head.
> > i dont recomend using sidemove, lby is wayy better, thirdperson is not accurate but gives the idea ,for the real to work u need to choke,
> > And also the yaw/pitch anti-aim is not even local desyncing which means when ur attack angle is not the view angle. Every bullets will go to wherrever it's set.
> > its a bug actually idk why it happens but i looks normal for the server and hits people, i have tested with my friends lby breaker not sidemove will see if i can fix
> 
> i usually hvh with osiris and i see people shooting my fake so idk
> btw do u have discord?

No.5#4775
