### ISSUE TITLE
Regarding silent aim

### ISSUE THREAD

**Issue by Anasx69** [danielkrupinski/Osiris#793]
Is silent aim Perfect or just a normal silent aim ?

**Comment by MinecraftGoodGame** [comment]
Normal, perfect silent is patched

**Comment by Anasx69** [comment]
Somehow psilent is still fully functional in pphud ?.

**Comment by notgoodusename** [comment]
> Somehow psilent is still fully functional in pphud ?.

lol, thats simply normal silent
