### ISSUE TITLE
Question about detection

### ISSUE THREAD

**Issue by itchy2019** [danielkrupinski/Osiris#794]
I see in cheater.fun it is deactivated due to lack of updating. Here it was updated more than 20 hours ago. Is it detectable? Can we compile it and use it or how do we know it is oudated? Thank you

**Comment by tirziz** [comment]
I recommend change the source and compile it, like remove some function or add something to make it undetected . Also use an undetected injector too

**Comment by itchy2019** [comment]
I'm new and I'm learning, but I'm going to try. thank you

**Comment by thomas0aotian** [comment]
Use advanced ud injector

**Comment by AbdallahMehiz** [comment]
or add somejunk codes
these are really useful for making cheats undetected
maybe even in injectors
