### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by Nexo848** [danielkrupinski/Osiris#796]
Hi, how can i change watermark font?

**Comment by MinecraftGoodGame** [comment]
pretty sure it's interfaces.surface->setTextFont(insert hexadecimal number here)

**Comment by Nexo848** [comment]
well, how to get hex font number then?

**Comment by MinecraftGoodGame** [comment]
Try https://numbermonk.com

**Comment by danielkrupinski** [comment]
Command `vgui_spew_fonts` will show you available fonts.
