### ISSUE TITLE
Fakeban

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#797]
Hi, how fakeban works and how to use it?

**Comment by rosesware** [comment]
Fake ban is broken, but you enable and shot at your friends (only works on team kill server).

**Comment by thomas0aotian** [comment]
@rosesware not true. The correct way to use it is after u enable it u type disconnect in the console and everyone else will see u disconnect from the game b/c u got banned

**Comment by xAkiraMiura** [comment]
color is working, however only in competitive it seems.

**Comment by gosu821** [comment]
@xAkiraMiura for me, its white color, its doesnt change color

**Comment by thomas0aotian** [comment]
@gosu821 u can't see urself only others can see after u disconnect

**Comment by gosu821** [comment]
@thomas0aotian thx a lot

**Comment by xAkiraMiura** [comment]
@gosu821 what gamemode are you trying this in? in my testing gamemodes in which you dont actually do damage it shows up as white but if you can do damage (wingman, comp, dangerzone) it shows up in color.

**Comment by Evilhelder** [comment]
> 
> 
> Fake ban is broken (color's), but you enable and shot at your friends (only works with team kill enable).
I use the clan tag changer to make it work, I understand very well but it works perfectly when the clan tag is on.

**Comment by xAkiraMiura** [comment]
@Evilhelder Forgot to mention that fixes it, you can use unicode ZERO_WIDTH_SPACE to fix it without having a tag show up in chat.

**Comment by KernCS** [comment]
can confirm you don't need to have clan tag on to make it work https://i.imgur.com/PiPlsyA.png just did this in a wingman:)
