### ISSUE TITLE
Help with new bombTimer

### ISSUE THREAD

**Issue by KernCS** [danielkrupinski/Osiris#798]
So i have been trying to make a new bombtimer but the font only change to the right one when i press Mouse1 after a few seconds its going back to the " normal " font or a big font as show in this video: https://youtu.be/ElY-p4k6SIw how do i make so i dont need to press mouse1 to show the right font? my code: 
```ruby
void Misc::drawBombTimer2() noexcept
{
	if (config.misc.bombTimer2.enabled) 
	{
		for (int i = interfaces.engine->getMaxClients(); i <= interfaces.entityList->getHighestEntityIndex(); i++) 
		{
			Entity* entity = interfaces.entityList->getEntity(i);
			if (!entity || entity->isDormant() || entity->getClientClass()->classId != ClassId::PlantedC4 || !entity->c4Ticking())
				continue;
			
			constexpr unsigned bombfont{ 0x77 };
			interfaces.surface->setTextBombFont(bombfont);
			interfaces.surface->setTextColor(98, 209, 0); // default 255, 255, 255
			auto drawPositionY{ interfaces.surface->getScreenSize().second / 60 }; // hight // higher the nummer higher the text go
			auto bombText{ (std::wstringstream{ } << (!entity->c4BombSite() ?  'A' : 'B') << L" - " << std::fixed << std::showpoint << std::setprecision(1) << (std::max)(entity->c4BlowTime() - memory.globalVars->currenttime, 0.0f) << L" s").str() }; // "setprecision" how many sec its shows
			const auto bombTextX{ interfaces.surface->getScreenSize().first / 25 - static_cast<int>((interfaces.surface->getTextSize(bombfont, bombText.c_str())).first / 5) }; // 5 dose nothing?
			interfaces.surface->setTextPosition(bombTextX, drawPositionY);
			drawPositionY += interfaces.surface->getTextSize(bombfont, bombText.c_str()).second;
			interfaces.surface->printText(bombText.c_str());

			 
			if (config.misc.bombTimer2.rainbow)
				interfaces.surface->setDrawColor(rainbowColor(memory.globalVars->realtime, config.misc.bombTimer2.rainbowSpeed));
			else
				interfaces.surface->setDrawColor(config.misc.bombTimer2.color);

			static auto c4Timer = interfaces.cvar->findVar("mp_c4timer");

			break;
		}
	}
}
```

**Comment by rosesware** [comment]
I really don't know why, but bomb timer is clean and pretty, why change?

**Comment by KernCS** [comment]
> I really don't know why, but bomb timer is clean and pretty, why change?

Because I don't like the other one and I don't like the fact that there are things on my screen it seems better that it's in the side of my scare :)

**Comment by rosesware** [comment]
> Because I don't like the other one and I don't like the fact that there are things on my screen it seems better that it's in the side of my screen:)

Seems fair.

**Comment by 0xE232FE** [comment]
You have all information present in the source code. You just need to know how to use interfaces.surface->printText(...) then you can print it on any side you want.

**Comment by KernCS** [comment]
> You have all information present in the source code. You just need to know how to use interfaces.surface->printText(...) then you can print it on any side you want.
Yeah i know thats not the problem the problem is that it change between 3 drefren fonts here is a video were you can see it: https://youtu.be/ElY-p4k6SIw ( its only showing 2 fonts in the video tho)

**Comment by KernCS** [comment]
> You have all information present in the source code. You just need to know how to use interfaces.surface->printText(...) then you can print it on any side you want.

Yeah i know thats not the problem the problem is that it change between 3 drefren fonts here is a video were you can see it: https://youtu.be/ElY-p4k6SIw ( its only showing 2 fonts in the video tho)

**Comment by CerberusGame** [comment]
### void Misc::drawBombTimer() noexcept
{
    if (config.misc.bombTimer) {
        for (int i = interfaces.engine->getMaxClients(); i <= interfaces.entityList->getHighestEntityIndex(); i++) {
            Entity* entity = interfaces.entityList->getEntity(i);
            if (!entity || entity->isDormant() || entity->getClientClass()->classId != ClassId::PlantedC4 || !entity->c4Ticking())
                continue;

            static constexpr unsigned font{ 0xc1 };
            interfaces.surface->setTextFont(font);
            interfaces.surface->setTextColor(255.0f, 255.0f, 255.0f, 255.0f);
            auto drawPositionY{ interfaces.surface->getScreenSize().second / 8 };
            auto bombText{ (std::wstringstream{ } << L"Bomb on " << (!entity->c4BombSite() ? 'A' : 'B') << L" : " << std::showpoint << std::setprecision(3) << (std::max)(entity->c4BlowTime() - memory.globalVars->currenttime, 0.0f) << L" s").str() };
            const auto bombTextX{ interfaces.surface->getScreenSize().first / 2 - static_cast<int>((interfaces.surface->getTextSize(font, bombText.c_str())).first / 2) };
            interfaces.surface->setTextPosition(bombTextX, drawPositionY);
            drawPositionY += interfaces.surface->getTextSize(font, bombText.c_str()).second;
            interfaces.surface->printText(bombText.c_str());

            const auto progressBarX{ interfaces.surface->getScreenSize().first / 3 };
            const auto progressBarLength{ interfaces.surface->getScreenSize().first / 3 };
            constexpr auto progressBarHeight{ 5 };

            interfaces.surface->setDrawColor(50, 50, 50, 255);
            interfaces.surface->drawFilledRect(progressBarX - 3, drawPositionY + 2, progressBarX + progressBarLength + 3, drawPositionY + progressBarHeight + 8);
            interfaces.surface->setDrawColor(255, 140, 0, 255);
            interfaces.surface->drawFilledRect(progressBarX, drawPositionY + 5, static_cast<int>(progressBarX + progressBarLength * (std::max)(entity->c4BlowTime() - memory.globalVars->currenttime, 0.0f) / 40.0f), drawPositionY + progressBarHeight + 5);

            if (entity->c4Defuser() != -1) {
                static PlayerInfo playerInfo;
                if (interfaces.engine->getPlayerInfo(interfaces.entityList->getEntityFromHandle(entity->c4Defuser())->index(), playerInfo)) {
                    static wchar_t name[128];
                    if (MultiByteToWideChar(CP_UTF8, 0, playerInfo.name, -1, name, 128)) {
                        drawPositionY += interfaces.surface->getTextSize(font, L" ").second;
                        const auto defusingText{ (std::wstringstream{ } << name << L" is defusing: " << std::showpoint << std::setprecision(4) << (std::max)(entity->c4DefuseCountDown() - memory.globalVars->currenttime, 0.0f) << L" s").str() };

                        interfaces.surface->setTextPosition((interfaces.surface->getScreenSize().first - interfaces.surface->getTextSize(font, defusingText.c_str()).first) / 2, drawPositionY);
                        interfaces.surface->printText(defusingText.c_str());
                        drawPositionY += interfaces.surface->getTextSize(font, L" ").second;

                        interfaces.surface->setDrawColor(50, 50, 50, 255);
                        interfaces.surface->drawFilledRect(progressBarX - 3, drawPositionY + 2, progressBarX + progressBarLength + 3, drawPositionY + progressBarHeight + 8);
                        interfaces.surface->setDrawColor(0, 255, 0, 255);
                        interfaces.surface->drawFilledRect(progressBarX, drawPositionY + 5, progressBarX + static_cast<int>(progressBarLength * (std::max)(entity->c4DefuseCountDown() - memory.globalVars->currenttime, 0.0f) / (interfaces.entityList->getEntityFromHandle(entity->c4Defuser())->hasDefuser() ? 5.0f : 10.0f)), drawPositionY + progressBarHeight + 5);

                        drawPositionY += interfaces.surface->getTextSize(font, L" ").second;
                        const wchar_t* canDefuseText;

                        if (entity->c4BlowTime() >= entity->c4DefuseCountDown()) {
                            canDefuseText = L"Can Defuse";
                            interfaces.surface->setTextColor(0.0f, 255.0f, 0.0f, 255.0f);
                        } else {
                            canDefuseText = L"Cannot Defuse";
                            interfaces.surface->setTextColor(255.0f, 0.0f, 0.0f, 255.0f);
                        }

                        interfaces.surface->setTextPosition((interfaces.surface->getScreenSize().first - interfaces.surface->getTextSize(font, canDefuseText).first) / 2, drawPositionY);
                        interfaces.surface->printText(canDefuseText);
                    }
                }
            }
        }
    }
}

**Comment by KernCS** [comment]
> https://hastebin.com/axivekazob.php :)

That's just the default one?

**Comment by KernCS** [comment]
> https://hastebin.com/axivekazob.php :)

Well thanks i guess? managed to fix it with the code you sent:)
