### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Nexo848** [danielkrupinski/Osiris#799]
Hi, i want to show on watermark incoming and outgoing packets, this code crashes my game, any ideas what goes wrong?

![Screenshot_5](https://user-images.githubusercontent.com/54820747/69554059-7e386d80-0fa1-11ea-8255-46d89d0667a9.png)

**Comment by Nexo848** [comment]
well, i fixed it myself, closing

**Comment by Bywnb** [comment]
how do you fix it?

**Comment by Nexo848** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/54820747/69574265-06316e00-0fc8-11ea-82f3-4ccd702ebc7c.png)
And then drawed two rectangles and printed it to screen
