### ISSUE TITLE
Flashing Knife

### ISSUE THREAD

**Issue by ptzer** [danielkrupinski/Osiris#80]
yo danielkrupinski,

when you set the knife model you also need to sets its m_iItemDefinitionIndex to stop that annoying flickering you get when changing knife.

thanks!

**Comment by Havoccboi** [comment]
how do i fix the bug ptzer?

**Comment by danielkrupinski** [comment]
Fixed now.

**Comment by ptzer** [comment]
Sorry I didn't reply. Been busy.
