### ISSUE TITLE
[Bug?] Crashing.

### ISSUE THREAD

**Issue by rosesware** [danielkrupinski/Osiris#800]
**So, when I change resolution or graphics, game crash.**

### **Can I fix it?**

**Comment by 0xE232FE** [comment]
I never change Resolution with Cheat injected? O.o

**Comment by steel4me** [comment]
Same, never tried it. You may guess what I will try next! o_O

**Comment by anonymouschicken1111** [comment]
Then don't do it

**Comment by VuBrian22** [comment]
When the cheat is injected, it saves and remembers the current resolution. If you try to change the resolution now, the cheat is still stuck in the previous resolution and sometimes the game gets confused and crashes. I've tried it numerous times and it crashes every now and then, however most of the time, it's just GUI glitches and incorrectly scaled text and UI elements. Changing the resolution again, back to the previous one where the cheat remembers always will result in a crash. I haven't explored a fix for any of this yet. It is solely on the game itself and not on the cheat, I suppose. Please correct me, if I'm wrong.
