### ISSUE TITLE
More about the configs

### ISSUE THREAD

**Issue by thomas0aotian** [danielkrupinski/Osiris#801]
How can I encrypt the config and read it  from config::load?
or
How can I store the config into a temp file and hide it from the user

**Comment by 0xE232FE** [comment]
Here you go Xor is best.

I save encrypted cfg's in myconfig.crypt in cfg folder, read it as Binary and use xorBinary() function as is.
xor is encrypt and decrypt at the same time. :-) This makes it handy!

#if DECRYPT_CFG
VOID xorBinary(PCSTR key)
{
    SIZE_T keyLenth = strlen(key);
    for (int i = 0; i < sizeof(binary); i++)
        binary[i] ^= key[i % keyLenth];
}
#endif

**Comment by thomas0aotian** [comment]
> Here you go Xor is best.
> 
> I save encrypted cfg's in myconfig.crypt in cfg folder, read it as Binary and use xorBinary() function as is.
> xor is encrypt and decrypt at the same time. :-) This makes it handy!
> 
> ```
> // Code by Daniel Krupinski
> #if DECRYPT_CFG
> VOID xorBinary(PCSTR key)
> {
>     SIZE_T keyLenth = strlen(key);
>     for (int i = 0; i < sizeof(binary); i++)
>         binary[i] ^= key[i % keyLenth];
> }
> #endif
> ```

bruh can u help me with #787

**Comment by thomas0aotian** [comment]
> Here you go Xor is best.
> 
> I save encrypted cfg's in myconfig.crypt in cfg folder, read it as Binary and use xorBinary() function as is.
> xor is encrypt and decrypt at the same time. :-) This makes it handy!
> 
> ```
> // Code by Daniel Krupinski
> #if DECRYPT_CFG
> VOID xorBinary(PCSTR key)
> {
>     SIZE_T keyLenth = strlen(key);
>     for (int i = 0; i < sizeof(binary); i++)
>         binary[i] ^= key[i % keyLenth];
> }
> #endif
> ```

bruh how do u use this code?
