### ISSUE TITLE
FPS Boosting DLL (no cheats)

### ISSUE THREAD

**Issue by Briggoes** [danielkrupinski/Osiris#805]
So I tried removing every cheat and leaving disable PostProcess, no shadows and no 3dsky. Turns out that it works, but it also removes the player models from the game. So basically theres no players to shoot at xd.

I was wondering if anyone could help me achieve this...

**Comment by thomas0aotian** [comment]
lol

**Comment by anonymouschicken1111** [comment]
lol

**Comment by effex1337** [comment]
Can't say what to do unless i see the codes but you messed up dme stuff.
Unhooking it should fix the issue.

**Comment by Briggoes** [comment]
Im going to give you the .zip file but its probably the goofiest shit you'll ever see tbh.
https://www.mediafire.com/file/8buk0ztqzz9v9yp/Osiris-nocheats.zip/file

**Comment by effex1337** [comment]
I'm not gonna fix it for you bud 😂😂😂

**Comment by Briggoes** [comment]
Oh, my bad. I miss understood you then lol.

**Comment by anonymouschicken1111** [comment]
How tf is the source 500mb big

**Comment by thomas0aotian** [comment]
obj~

**Comment by anonymouschicken1111** [comment]
> obj~
ik the real question is why tf would u sent ur binaries when u only need to source code

**Comment by tirziz** [comment]
checkout drawModelExecute in hooks.cpp maybe you somehow mess it up.

**Comment by tirziz** [comment]
Or if you don't use Charm , just completely remove it. it will work.

**Comment by Briggoes** [comment]
Fixed it days ago, forgot to close. Ty either way

**Comment by Anasx69** [comment]
hey can you send me that ? discord Anas#8776 @Briggoes
