### ISSUE TITLE
Desync AA Code .?

### ISSUE THREAD

**Issue by Anasx69** [danielkrupinski/Osiris#807]
float Desync = g_LocalPlayer->GetDesyncDelta() / 100 * GetDesyncYaw() + 30.0f;
float MM = 1.10f;

if (m_bDesyncSide)
Desync = -Desync;

if (m_pCmd->buttons & IN_DUCK)
MM *= 3;

if (m_pCmd->tick_count % 2)
MM = -MM;

static float LBY = 0;

if (g_GlobalVars->curtime < LBY && m_pCmd->sidemove < 4 && m_pCmd->sidemove > -4)
m_pCmd->sidemove = MM;

if (!m_bSendPacket)
{
if (g_GlobalVars->curtime >= LBY && g_LocalPlayer->m_vecVelocity().Length() < 4)
{
m_pCmd->viewangles.yaw += 180.0f;
LBY = g_GlobalVars->curtime + 0.22f;
}
else
{
m_pCmd->viewangles.yaw += Desync;
}
}

m_flDesyncAmount = Desync / 2;

**Comment by VuBrian22** [comment]
Please write this up as a pull request and not an issue.

**Comment by Anasx69** [comment]
idk why but i cant push it into pull request

**Comment by VuBrian22** [comment]
> idk why but i cant push it into pull request

hmm alright.

**Comment by thomas0aotian** [comment]
Just fork it and upload ur own change and then request a pull request daddy

**Comment by thomas0aotian** [comment]
It's not even osiris sdk

**Comment by Anasx69** [comment]
Yes u i know it isnt osiris sdk its just a random desync code needs some adjustments and boom

**Comment by VuBrian22** [comment]
> Yes i know it isnt osiris sdk its just a random desync code needs some adjustments and boom

Then fork it, make the adjustments needed to fulfill the SDK, and then create a pull request.
