### ISSUE TITLE
Need contact with author

### ISSUE THREAD

**Issue by arthures11** [danielkrupinski/Osiris#808]
Please send me your skype or discord.

**Comment by GGPRO06Discord** [comment]
No

**Comment by arthures11** [comment]
i need private version of osiris or just few features, need to keep it undetected so i can play withotu vacs

**Comment by GGPRO06Discord** [comment]
there is no "private version" its a public source Xd

**Comment by GGPRO06Discord** [comment]
i can give you my dll with some added features
but i cant garentee undetection

**Comment by arthures11** [comment]
you aren't the author mate

**Comment by arthures11** [comment]
and i don't need more features just less

**Comment by arthures11** [comment]
i need aimbot+anti afk kick+autobh+spectator list

**Comment by HowToMakeFaceitAB** [comment]
> you aren't the author mate

Bruh, he won't give you no private version(that doesn't exist)
Stop being such an entitled brat

**Comment by arthures11** [comment]
i know, i just wanted to buy private few features to keep it undetected by vac :(

**Comment by HowToMakeFaceitAB** [comment]
> i know, i just wanted to buy private few features to keep it undetected by vac :(

Ok then, why ask daniel when you can ask the community

**Comment by arthures11** [comment]
i asked and now i ask somebody who is into coding

**Comment by arthures11** [comment]
you can make it? aimbot+few other miscs to keep it safe?

**Comment by GGPRO06Discord** [comment]
bro
less features dont make it more safe

**Comment by GGPRO06Discord** [comment]
you would have to remake hole parts of the entire cheat for example new hooks net methods and other crap and i dont think any1 would "give" you that "undetected version" for free man

**Comment by arthures11** [comment]
i don't want it for free lol

**Comment by arthures11** [comment]
i will pay

**Comment by Scui1** [comment]
if u pay anyway, why don't you just buy a public cheat like aimware?

**Comment by arthures11** [comment]
i wanted just few features and thought it would make it cheaper or something

**Comment by GGPRO06Discord** [comment]
yeah cheaper but not undetected

**Comment by arthures11** [comment]
any idea how to get it? i saw some cheats are 4+ years undetected?

**Comment by GGPRO06Discord** [comment]
yeah thats called skeet.cc

**Comment by arthures11** [comment]
give me invitation code

**Comment by GGPRO06Discord** [comment]
BROOO can some1 ban this kid for being "an fucking entitled spoiled brat"

**Comment by arthures11** [comment]
wdym mate, i need invitation code to register.

**Comment by GGPRO06Discord** [comment]
yeah you think some1 will just give you a 150 € invite code just out of the blue?

**Comment by GGPRO06Discord** [comment]
you must be taking a piss bruh

**Comment by arthures11** [comment]
oh lel thought it's some referral code, what's your problem mate?

**Comment by VuBrian22** [comment]
@arthures11 Also can't you just remove them yourself....It's rlly simple. Remove it in the both the source and the ImGui Library. And if you don't want it for free, donate to him using his paypal.me link; its the same deal here. All the protections in the free version are the same and protected as always as it is open source....

**Comment by GGPRO06Discord** [comment]
whats yours newfag

**Comment by VuBrian22** [comment]
@arthures11 His donations/sponsor link is: https://paypal.me/DanielK19

**Comment by arthures11** [comment]
> @arthures11 His donations/sponsor link is: https://paypal.me/DanielK19

i know.. makes no sense for me though. I need kinda undetected version(private or something) so i guess i won't find/buy anything liek that here. Am i right?

**Comment by VuBrian22** [comment]
Keep in mind that this cheat is open-source and will never be private.

**Comment by Straightplus** [comment]
No you can always "hire" a private dev to do the job but you cant expect to get any thing for free though

**Comment by VuBrian22** [comment]
> No you can always "hire" a private dev to do the job but you cant expect to get any thing for free though

But it won't be like Osiris unless it uses the Osiris Open-Source SDK and the Open-Source ImGui Interface Libraries.

**Comment by VuBrian22** [comment]
Then after all that, what's the point of making a private version where all the binary protections by VAC are the same and all the small features you want are the same as the free and open-sourced community version. Your mentality and intentions are just confusing now. Common sense is non-existent.

**Comment by VuBrian22** [comment]
@arthures11 Please close this redundant issue, Thank you.

**Comment by Straightplus** [comment]
i tried making that point :P

**Comment by thomas0aotian** [comment]
Ummm I can do the job, I already have a working modified-Osiris cheat. It's been ud for 5 months already and it has nearly 100 users. It has a full security system so it's def private. My discord is No.5#4775

**Comment by VuBrian22** [comment]
> Ummm I can do the job, I already have a working modified-Osiris cheat. It's been ud for 5 months already and it has nearly 100 users. It has a full security system so it's def private. My discord is No.5#4775

What's different in the protections from VAC in your version?

**Comment by Scui1** [comment]
just use the vac bypass, so you don't need to pay for a paste like the one from this guy 2 postes above.

**Comment by VuBrian22** [comment]
@Scui1 That's why I'm asking what he had changed or added to the binary protections.

**Comment by arthures11** [comment]
so i can use VAC bypass making it undetectable always? unless vac bypass stopped workign ofcourse

**Comment by VuBrian22** [comment]
> so i can use VAC bypass making it undetectable always? unless vac bypass stopped workign ofcourse

Yes.

**Comment by arthures11** [comment]
How much does it cost? And where can i find it?

**Comment by anarbmw** [comment]
Guys can u please help me? #809

**Comment by VuBrian22** [comment]
It costs nothing. https://github.com/danielkrupinski/VAC-Bypass https://github.com/danielkrupinski/VAC-Bypass-Loader

**Comment by arthures11** [comment]
So why isn't it popular? lol. It seems like perfect for public cheats, you will never get banned unless overwatch or something ofc.

**Comment by tirziz** [comment]
Osiris is a open source, it take time but surely the hooking will be detected at some point ( who know when lol) . Have fun while it still undetected. And don't fall for any kind of scam "fully undetected" or "undetectable".

**Comment by VuBrian22** [comment]
I honestly don't know why...lol

**Comment by VuBrian22** [comment]
> Osiris is a open source, it take time but surely the hooking will be detected at some point ( who know when lol) . Have fun while it still undetected. And don't fall for any kind of scam "fully undetected" or "undetectable".

Right, that's what I tried to explain.

**Comment by arthures11** [comment]
Thanks guys, vac bypass is obviously the thing i needed. Osiris is perfect for me but vac bans are insane and i wanted to use it with my main account,

**Comment by VuBrian22** [comment]
@arthures11 Glad to know you've fully understand.

**Comment by VuBrian22** [comment]
Please Close This Issue, Thank You!

**Comment by tirziz** [comment]
ayy don't use cheat on your main. create a free and cheat. not recommend to risk it

**Comment by VuBrian22** [comment]
> ayy don't use cheat on your main. create a free and cheat. not recommend to risk it

Yeah and that too, Thanks for the reminder for everyone here!

**Comment by arthures11** [comment]
i don't have any huge amount skins but i have some kinds of VIP on public server so i want to play there

**Comment by VuBrian22** [comment]
@arthures11 Alrighty, just be careful, that's all.

**Comment by arthures11** [comment]
i already got vac few times using osiris but with vac bypass shouldn't happen. am right?

**Comment by thomas0aotian** [comment]
No code-modifications, no anti-detection method, no private ring0 injector ofc u got detected. My main had 3k inventory value and I am still using it to rank up and now I am actually ge!

**Comment by VuBrian22** [comment]
@arthures11 It shouldn't happen by VAC. Only Overwatch from this point forward. Hopefully.

**Comment by VuBrian22** [comment]
> No code-modifications, no anti-detection method, no private ring0 injector ofc u got detected. My main had 3k inventory value and I am still using it to rank up and now I am actually ge!

What about your source and binary? It's never fully undetected just like the regular source that hasn't been modified.

**Comment by OBO-1** [comment]
This is fucking hilarious
