### ISSUE TITLE
Improved version of Osiris

### ISSUE THREAD

**Issue by anarbmw** [danielkrupinski/Osiris#809]
Hi. I would like to get an Osiris with all features from pull requests. I know it sounds dumb, but I don’t really understand all this stuff, how u add it in hack and etc.

**Comment by tirziz** [comment]
Just wait for Daniel merge these. He will make sure its compatible

**Comment by EGTLoneWolf** [comment]
ngl i dont rlly think he will merge it.

**Comment by effex1337** [comment]
Ye

**Comment by ZerGo0** [comment]
Literally takes a few seconds to copy and paste it yourself.

**Comment by anarbmw** [comment]
@ZerGo0 dude I dont understand how this works, how u open dlls files, write code and etc

**Comment by tirziz** [comment]
Look at the README.md it will tell you everything you need to compile this cheat. Also when you see a new pull request that interesting, just copy those change and paste in the right location and compile it agian., That is.

**Comment by anarbmw** [comment]
@tirziz can u explain me how u open dll files and then turn it back into dll?

**Comment by VuBrian22** [comment]
@anarbmw And remember that just copying and pasting code from UC or smth onto Osiris doesn't work  because it's not part of the Osiris SDK. You'll need to make some adjustments to fulfill the requirements of the SDK. Again, Read the README for that as well.

**Comment by ZerGo0** [comment]
> @ZerGo0 dude I dont understand how this works, how u open dlls files, write code and etc

There are a shit lot of tutorials about that shit online if you aren't capable of googling stuff like that, then I'm sorry, but there is no hope for you.
