### ISSUE TITLE
Name ESP + Weapon ESP

### ISSUE THREAD

**Issue by TheNotoriousAWP** [danielkrupinski/Osiris#81]
Hello, I am writing to ask you if you could add a name and weapon esp to the cheat as I believe it's less obnoxious compared to the glow esp. I have come up with a little bit of code that would work with the current source code of the cheat but I don't know if it is correct and how to implement it properly; it is written in the same style:
```
void Visuals::Name() noexcept
{
	if (config.esp.name && interfaces.engine->isInGame())
	{
		for (int i = 1; 1 <= interfaces.engine->getMaxClients(); i++)
		{
			auto entity = interfaces.entityList->getEntity(i);
			
			if (!entity || entity->isAlive() || entity->isDormant && entity->isEnemy)
				continue;

			static PlayerInfo playerInfo;

			auto info = interfaces.engine->getPlayerInfo(i, playerInfo);

			auto size = CalcTextSizeA(14.f, FLT_MAX, 0.0f, playerInfo.name);

		}
	}

}
```

**Comment by TheNotoriousAWP** [comment]
I am suggesting a feature? it isn't invalid..

**Comment by danielkrupinski** [comment]
Duplicate #61

**Comment by TheNotoriousAWP** [comment]
is my code at all useful?
