### ISSUE TITLE
Outdated "getObservertarget" index

### ISSUE THREAD

**Issue by Straightplus** [danielkrupinski/Osiris#810]
So i have the code for spec list but iam missing the getObservertarget because it broke right after the update `    constexpr Entity* getObserverTarget() noexcept
    {
        return callVirtualMethod<Entity*>(this, 293);
    }`
if anybody have the right number (instead of 293) please commend down below.

`void Misc::spectatorList() noexcept
{
    if (config.misc.spectatorList.enabled && interfaces.engine->isInGame()) {
        const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());

        if (!localPlayer->isAlive())
            return;

        interfaces.surface->setTextFont(Surface::font);

        if (config.misc.spectatorList.rainbow)
            interfaces.surface->setTextColor(rainbowColor(memory.globalVars->realtime, config.misc.spectatorList.rainbowSpeed));
        else
            interfaces.surface->setTextColor(config.misc.spectatorList.color);

        const auto [width, height] = interfaces.surface->getScreenSize();

        int textPositionY{ static_cast<int>(0.5f * height) };

        for (int i = 1; i <= interfaces.engine->getMaxClients(); i++) {
            auto entity = interfaces.entityList->getEntity(i);
            if (!entity || entity->isAlive() || entity->isDormant())
                continue;

            if (PlayerInfo playerInfo; interfaces.engine->getPlayerInfo(i, playerInfo) && entity->getObserverTarget() == localPlayer) {
                if (wchar_t name[128]; MultiByteToWideChar(CP_UTF8, 0, playerInfo.name, -1, name, 128)) {
                    const auto [textWidth, textHeight] = interfaces.surface->getTextSize(Surface::font, name);
                    interfaces.surface->setTextPosition(width - textWidth - 5, textPositionY);
                    textPositionY -= textHeight;
                    interfaces.surface->printText(name);
                }
            }
        }
    }
}`

**Comment by VuBrian22** [comment]
New Offsets? Wait did the game just update today?

**Comment by Anasx69** [comment]
try 294

**Comment by Straightplus** [comment]
no it did not it broke after the shattered web update sorry for not being specefic 

> New Offsets? Wait did the game just update today?

**Comment by Straightplus** [comment]
and thanks :D 

> try 294

**Comment by Straightplus** [comment]
ill see

**Comment by VuBrian22** [comment]
Ok

**Comment by Straightplus** [comment]
thanks man works like a charm :D

**Comment by Straightplus** [comment]
@Anasx69
