### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by asraskmekaidasid** [danielkrupinski/Osiris#811]
when i add more sound to hitsound i got crash?

**Comment by VuBrian22** [comment]
Did you import the sound, correctly?

**Comment by ZerGo0** [comment]
Attach a debugger and it will tell you where it crashed.

**Comment by Straightplus** [comment]
how do you even add new hitsounds ik the parths but??!?!

**Comment by VuBrian22** [comment]
@Straightplus  Yeah, same. But like, this person wants to add his own brand new sounds ig or smth like that and he'll need to import it in somehow. Otherwise the current hitsounds are in the game files, you just need the path for that.

**Comment by Straightplus** [comment]
Ik @VuBrian22 but what code do you need to change to get the new hitsounds?

**Comment by asraskmekaidasid** [comment]
https://gist.github.com/itotallyrock/e14c90fc948a0631e2bbda7bf79406d2 i use this list, and i when add anyway hitsound to my project i got crash or dosen't work

**Comment by ZerGo0** [comment]
> https://gist.github.com/itotallyrock/e14c90fc948a0631e2bbda7bf79406d2 i use this list, and i when add anyway hitsound to my project i got crash or dosen't work

You can literally attach a debugger and it will tell you why it crashes... There are thousands of tutorials for that kind of shit.
