### ISSUE TITLE
Ready osiris.dll

### ISSUE THREAD

**Issue by anarbmw** [danielkrupinski/Osiris#817]
Guys i really need all features from #739, can someone add them in the hack and send me ready dll? I tried to do it myself, but my visual studio keeps sending me errors and warnings.

**Comment by AbdallahMehiz** [comment]
you can use ZPDMiller's FORK
https://github.com/ZPDMiller/Osiris

**Comment by anarbmw** [comment]
@AbdallahMehiz yeah ill download it, but how to transform it into dll?

**Comment by ZPDMiller** [comment]
The instructions are on  the Readme Here: https://github.com/danielkrupinski/Osiris#getting-started

**Comment by anonymouschicken1111** [comment]
Can u close this issue?

**Comment by agshaidun** [comment]
https://gofile.io/?c=qxCKSZ

**Comment by 0xE232FE** [comment]
Do not trust anyone in the Hacker scene or you will be scammed!

Do not download or buy DLLs from script kiddies! Just follow the instruction in the README as pointed before!

**Comment by ZPDMiller** [comment]
Don't trust anybody, not even yourself

**Comment by anarbmw** [comment]
Just send me dll with all features from #739 and ill close this issue

**Comment by ZPDMiller** [comment]
If u really want it then here:
https://anonfile.com/h3X265D4nc/no_virus_rar
It has a few extra features from other pull requests, but everything that was in #739 is added

**Comment by anarbmw** [comment]
@ZPDMiller please tell me is there any virus there?

**Comment by ZPDMiller** [comment]
That file name is a joke, I promise you it is not a virus, you can scan it with virustotal.com, that filename is just a joke. I compiled it straight from my fork

**Comment by ZPDMiller** [comment]
Also you should scan any file you don't trust as a precaution. Scanning .rar files is a good measure if you wanna be sure the file is safe

**Comment by anarbmw** [comment]
@ZPDMiller thank u very much. also, could I get ur discord?

**Comment by ZPDMiller** [comment]
Sure, Zach#6392
