### ISSUE TITLE
Working on the following features in the future

### ISSUE THREAD

**Issue by ZerGo0** [danielkrupinski/Osiris#818]
Hey guys, 

I really like this cheat simply because the community behind it seems quite active. I want to contribute as well, but my C++ knowledge is not that good anymore and my game reverse engineering skills are not there. I will try my best tho, I currently plan on working on the following features:

- Hit Marker Damage indicator (a small floating number next to your crosshair when you hit someone with the damage number) - #835 DONE
- Dead ESP (Enable the ESP when you are dead) - #821 DONE
- Real-time Damage Log (both on-screen and potentially in the console)
- Global Health Overlay (Display the health (and armor I guess) of all enemies somewhere on the screen)
- Grenade Icon ESP (for each individual made I guess)

I will post everything as a pull request if any other dev wants to work or has already made one of these features then feel free to post them. I don't need to "waste" my time that way.

**Comment by ZPDMiller** [comment]
That's epic dude

**Comment by mendax47** [comment]
Can You Also Please Add Grenade Helper And Recoil Trace Cross-hair...?

**Comment by Anasx69** [comment]
If you may you can add a headshot level crosshair indicator 

@mendax47  recoil crosshair is already there

**Comment by ZerGo0** [comment]
> Can You Also Please Add Grenade Helper And Recoil Trace Cross-hair...?

There is already a grenade prediction, I'm not going to add pre defined spots for nades, sorry too cancer to maintain.

Recoil crosshair is already a thing as well.

> If you may you can add a headshot level crosshair indicator
> 
> @mendax47 recoil crosshair is already there

I might consider it, I wasn't planning on adding more than that for now.

**Comment by VuBrian22** [comment]
@ZerGo0 Could you also make a pull request on @ZPDMiller 's fork of Osiris because he's added most of the requested features so far. It would just be nice if you wouldn't mind cutting out most of the copying and pasting work for him. lol

**Comment by ZPDMiller** [comment]
There's no need for that, I can just copy whatever he puts in the pull request, I don't mind doing it, but if he really wants to, he can

**Comment by littlehurensohn** [comment]
> There's no need for that, I can just copy whatever he puts in the pull request, I don't mind doing it, but if he really wants to, he can

Are u possible to add edge jump? It can be very useful.

**Comment by VuBrian22** [comment]
Just trying to help a bit.....but alrighty!

**Comment by anonymouschicken1111** [comment]
For dead esp
if(!localPlayer->isAlive)
    config.esp.enable;

**Comment by ZerGo0** [comment]
> For dead esp
> 
> ```
> if(!localPlayer->isAlive)
>     config.esp.enable;
> ```

Appreciated, but dead esp is probably the easiest thing to code, I will probably add another tab in the GUI tho.

**Comment by anonymouschicken1111** [comment]
> > For dead esp
> > ```
> > if(!localPlayer->isAlive)
> >     config.esp.enable;
> > ```
> 
> Appreciated, but dead esp is probably the easiest thing to code, I will probably add another tab in the GUI tho.

Put that under Esp give the option to turn on dead esp under enable esp

**Comment by ZerGo0** [comment]
Dead ESP added - #821

**Comment by anonymouschicken1111** [comment]
Y don't u make a discord on this so we can share code together or something

**Comment by ZerGo0** [comment]
Hit Marker Damage indicator added - #835

**Comment by AbdallahMehiz** [comment]
i think displating the health would work perfectly on the scoreboard ._.

**Comment by giangero1** [comment]
@ZerGo0 grenade helper would be nice #752 check this out source and vid

**Comment by giangero1** [comment]
also #846

**Comment by ZerGo0** [comment]
> @ZerGo0 grenade helper would be nice #752 check this out source and vid @danielkrupinski

Not going to add that, don't have enough time for that.

> also #846 hitmarker sounds @danielkrupinski

The current system just uses the `play <soundfilepathhere>` command to play the hit sounds. As far as I know, there is no way to add local sounds to that.

**Comment by ZerGo0** [comment]
@danielkrupinski I'm currently trying to add an ESP option to show the C4 Carrier. I'm trying to get it via the following netvar: `NETVAR(c4CarrierIndex, "CCSPlayerResource", "m_iPlayerC4", int)`

I'm pretty sure that I need the `CSPlayerResource` as well, but I have no idea how I can get that, could you help me with that?

**Comment by danielkrupinski** [comment]
@ZerGo0 You can get `PlayerResource` entity from entity list or by pointer (from memory signature).

**Comment by ZerGo0** [comment]
> @ZerGo0 You can get `PlayerResource` entity from entity list or by pointer (from memory signature).

I'm definitely too retarded for this shit, I guess I will wait till someone else adds it. There is a bunch of nice stuff in that interface. ^^
