### ISSUE TITLE
About Virus

### ISSUE THREAD

**Issue by agshaidun** [danielkrupinski/Osiris#819]
When i scan my dll at virustotal it detect as virus . why ?

**Comment by ZPDMiller** [comment]
The cheat modifies game memory when it is injected into the game, it sees it as a virus. It is not a virus, it's just read as a false-positive

**Comment by agshaidun** [comment]
its sad cuz when i shared by dll to someone they told me i was trolling because sending them virus

**Comment by ZPDMiller** [comment]
People usually don't trust cheats sent to them from other people across the internet unless it's somebody they trust, it happens

**Comment by anonymouschicken1111** [comment]
> its sad cuz when i shared my dll to someone they told me i was trolling because sending them virus

Just send source code and tell them to compile it
