### ISSUE TITLE
add fakeduck

### ISSUE THREAD

**Issue by aixva** [danielkrupinski/Osiris#829]
idk for trolling :D

**Comment by rosesware** [comment]
You can't use fakeduck in matchmaking, fakeduck get untrusted.

**Comment by AbdallahMehiz** [comment]
._. can we close this ?

**Comment by CantRememberMyself** [comment]
@rosesware that isnt true, fakeduck simply doesnt work anymore in mm because they made the max packet choke 6 or 7 and fake duck requires like 15

**Comment by CantRememberMyself** [comment]
HOWEVER, some skeeters have said that gamesense has a working version but idk how it works and apparently it isnt as good
