### ISSUE TITLE
Removing the Grass causes crashing

### ISSUE THREAD

**Issue by VitexHD** [danielkrupinski/Osiris#83]
I went on a map with grass and disabled the grass, right after that, it crashed to desktop.

(Also, for people who have crashing with loading a config, it's becuase whenever an update comes, if you try to load your config, it'll try to load all of you settings in the old update, for an example, when I added my own functions and checkboxes and tried to load the config, it would always crash so I'd have to create a new config. But hopefully there is a way to get around this, like getting a version number and if that's != to the current version, it will simply just append to the config and loading a config. (I thought of that off my head (the solution). Maybe I can read through and see if that's possible, but I do know it uses an encryption and decryption method "cereal".)

**Comment by VitexHD** [comment]
And Daniel (That's weird because my name is Daniel too :3), where do you recommend learning game hacks? Or at least, internal because I know external but internal is so much easier, I'm just wondering how hooking works, what hooking is and the SDK (Probably read through it sometime). 

And this line of code: return hooks.clientMode.getOriginal<int(__thiscall*)(ClientMode*, int)>(44)(memory.clientMode, param);

What does the int 44 do? :3 Thanks for your help <3

**Comment by designeruc** [comment]
> And Daniel (That's weird because my name is Daniel too :3), where do you recommend learning game hacks? Or at least, internal because I know external but internal is so much easier, I'm just wondering how hooking works, what hooking is and the SDK (Probably read through it sometime).
> 
> And this line of code: return hooks.clientMode.getOriginal<int(__thiscall*)(ClientMode*, int)>(44)(memory.clientMode, param);
> 
> What does the int 44 do? :3 Thanks for your help <3

44 is index for DoPostScreenEffects.

**Comment by danielkrupinski** [comment]
Grass bug has been fixed.
