### ISSUE TITLE
Anti-untrusted

### ISSUE THREAD

**Issue by AbdallahMehiz** [danielkrupinski/Osiris#830]
soo...
i have been testing many things with the cheats the last few weeks
and i managed to make it undetected through the use of junk codes and shuffling the cheats' functions. i even managed to get LEM after 25 wins on a new account without getting VAC banned.
but i once created an account and toggled some blatant aimbot cuz i was bored.
and after 2 or 3 games of wingman i got banned for "Untrusted account".
even though the cheat is undected for me. i still got the ban on the new account.
so
i am asking some questions:
-How accounts get untrusted bans ?
-Why do accounts get untrusted bans ?
-How can we prevent untrusted bans ?
i am going to add an "Anti-untrusted" feature to the cheat once i know how it works. i need help.

**Comment by gosu821** [comment]
maybe ur injector is detected,

**Comment by gosu821** [comment]
and source is public, always have risk to get ban, and they need to fix backtrack, old backtrack, i try to fix new backtrack and its work very smooth

**Comment by Pedo1338** [comment]
yes backtrack need to get update is not accurate do you have a fix gosu821 ?

**Comment by gosu821** [comment]
Yea bro

**Comment by AbdallahMehiz** [comment]
> Yea bro

Pull request maybe?

**Comment by AbdallahMehiz** [comment]
what about anti untrusted

**Comment by gosu821** [comment]
> what about anti untrusted

Its about ur injector, if ur injector is detected, its will get untrusted ban,

**Comment by tirziz** [comment]
As far as I know, there is 2 ways of getting untrusted ban.
1. Detected injector.
2. Unhuman like behavior such as: impossible angle of some AA and some blatantly aimbot without aimstep,...

Base on those reasons, make you own solution.

**Comment by thomas0aotian** [comment]
Untrusted ban only happens in casual server. It detects AA, high fov aimbot and too many kills(in dm over 1k).

**Comment by AbdallahMehiz** [comment]
> Untrusted ban only happens in casual server. It detects AA, high fov aimbot and too many kills(in dm over 1k).

i once acheived 1.3k score in dm
and got no untrusted bans

**Comment by thomas0aotian** [comment]
> > Untrusted ban only happens in casual server. It detects AA, high fov aimbot and too many kills(in dm over 1k).
> 
> i once acheived 1.3k score in dm
> and got no untrusted bans

I meant 1k kills.

**Comment by furioushell98** [comment]
Use undetected injector and set your delta angle in misc to 30 or less.

**Comment by AbdallahMehiz** [comment]
Aight.
Thanks for the help boiis
