### ISSUE TITLE
what is reveal suspect

### ISSUE THREAD

**Issue by Bywnb** [danielkrupinski/Osiris#831]
i test many times and read the code , but i dont know how to use this , who could tell me?

**Comment by agshaidun** [comment]
Reveal Suspect name for Overwatch maybe?

**Comment by Bywnb** [comment]
i also think this，but i cant test...

**Comment by tirziz** [comment]
Its is, Daniel put that in for a long time, he just make a check box for it now.

**Comment by Bywnb** [comment]
thanks

**Comment by AbdallahMehiz** [comment]
why would you reveal a suspect's name in overwatch? ._.

**Comment by Finndramere** [comment]
> why would you reveal a suspect's name in overwatch? ._.

i think it shows animated clantag and name changers
