### ISSUE TITLE
snow effect

### ISSUE THREAD

**Issue by asraskmekaidasid** [danielkrupinski/Osiris#838]
how can i got snow effect with panorama to screenEffect?

**Comment by tirziz** [comment]
Check those effect, find what you need and edit in Visuals::applyScreenEffects
`effectname
effects/blood
effects/blood2
effects/blood_core
effects/blood_drop
effects/blood_gore
effects/blood_puff
effects/blueflare1
effects/bluespark
effects/bubble
effects/christmas_bulb.vmt
effects/combinemuzzle%d
effects/combinemuzzle%d_noz
effects/combinemuzzle1_nocull
effects/combinemuzzle2
effects/combinemuzzle2_nocull
effects/dangerzone_screen
effects/dronecam
effects/dronecam_closed
effects/dronecam_grab
effects/ember_swirling001
effects/energyball
effects/energysplash
effects/fire_cloud1
effects/fire_cloud2
effects/fire_embers1
effects/fire_embers2
effects/fire_embers3
effects/flashbang
effects/flashbang_white
effects/flashlight001
effects/flashlight_freezecam
effects/fleck_antlion1
effects/fleck_antlion2
effects/fleck_ash1
effects/fleck_ash2
effects/fleck_ash3
effects/fleck_cement1
effects/fleck_cement2
effects/fleck_glass1
effects/fleck_glass2
effects/fleck_tile1
effects/fleck_tile2
effects/fleck_wood1
effects/fleck_wood2
effects/gunshipmuzzle
effects/gunshiptracer
effects/healthboost
effects/huntertracer
effects/laser1
effects/muzzleflash%d
effects/muzzleflash%d_noz
effects/muzzleflash1
effects/muzzleflash1_noz
effects/muzzleflash2
effects/muzzleflash2_noz
effects/muzzleflash3
effects/muzzleflash3_noz
effects/muzzleflash4
effects/muzzleflash4_noz
effects/muzzleflashX
effects/nightvision
effects/overlaysmoke
effects/parachute
effects/screentear
effects/slime1
effects/spark
effects/splash1
effects/splash2
effects/splash3
effects/splash4
effects/splashwake1
effects/survival_zone_projection_distancefield
effects/survival_zone_projection_distancefield_inv
effects/underwater_overlay
effects/yellowflare
effects/yellowflare_noz`

**Comment by asraskmekaidasid** [comment]
ty
