### ISSUE TITLE
Scoreboard and buy menu issue

### ISSUE THREAD

**Issue by Matios210** [danielkrupinski/Osiris#839]
Everytime i inject cheat, i cant just open scoreboard and open buymenu.

Already tried to bind these things but it didnt worked and i must buy things via console xd

How can i fix this?

**Comment by agshaidun** [comment]
i think its ur cs problem . i don't have any problem using osiris

**Comment by Matios210** [comment]
Verified game files and this still happens, only when injecting cheat. When playing without it - everything works ;s

**Comment by thomas0aotian** [comment]
Alt+tab some more or put -disable_d3d9ex on launch option might fix it

**Comment by Matios210** [comment]
Tried this and still not working, ahh

**Comment by thomas0aotian** [comment]
...

**Comment by synvy** [comment]
This is an issue with the IsPlayingDemo hook.  Just return false at the end of the hook instead of returning the original.

**Comment by Matios210** [comment]
Oh man that worked! Thank you very much sir.
