### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by Eman6972** [danielkrupinski/Osiris#843]
-BlockBot. 
-Door spammer
-98 Nade

**Comment by ZPDMiller** [comment]
The blockbot and door spammer are in the pull request #739

**Comment by Eman6972** [comment]
> The blockbot and door spammer are in the pull request #739

sorry I'm pretty dumb all of that is very confusing 2 me

**Comment by Straightplus** [comment]
door spammer already added check pull requests

**Comment by AbdallahMehiz** [comment]
add them urself ._.

**Comment by Evilhelder** [comment]
Runboost helper please :(
