### ISSUE TITLE
Suggestion: Aimstep

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#844]
-Aimstep (allow rage, use silent aim without vac auth kick).

**Comment by ZPDMiller** [comment]
Set Max Angle Delta to around 30 in Misc, this will allow you to rage without getting a VAC Authentication error

**Comment by rosesware** [comment]
[VAC Bypass Loader](https://github.com/danielkrupinski/VAC-Bypass-Loader) (same as aimstep).
