### ISSUE TITLE
No recoil and No viewmodel bobbing

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#845]
- No recoil
- No viewmodel bobbing
- No spread
Im new cs go cheater guys. If i wrote wrong sorry.

**Comment by thomas0aotian** [comment]
？
？
？

**Comment by thomas0aotian** [comment]
# This sounds like:
## Feature Request:
- Player teleport
- Instant kill
- Respawn
- Noclip
- Crash the server

**Comment by nikita-tarasov3** [comment]
@thomas0aotian i meant 3 suggestions for cheat:
No recoil
No viewmodel bobbing
No spread

**Comment by xAkiraMiura** [comment]
no recoil is already implemented, just only for the aimbot, you probably mean an RCS (recoil control script). 

no spread is not possible because the server uses a cryptographically secure seed when calculating spread so we cannot calculate and compensate for it.
