### ISSUE TITLE
Hit marker sounds

### ISSUE THREAD

**Issue by CyborgPlatypus64** [danielkrupinski/Osiris#846]
adding custom hitsounds, such as the cod one or the oof sound. i tried to do it myself but integrating it was pretty difficult. would be a ice feature to have

**Comment by thomas0aotian** [comment]
and also the hitsound value

**Comment by giangero1** [comment]
how to add my own custom hitsound help please!

https://anonfile.com/14DcN3H5n6/ih_rar

here is the wav file and converted to C file. 
@thomas0aotian @danielkrupinski

**Comment by giangero1** [comment]
@danielkrupinski  https://www.unknowncheats.me/forum/counterstrike-global-offensive/180039-hitmarker-hitsound.html here code for it

**Comment by xAkiraMiura** [comment]
i think daniel is competent enough to understand how events work, after all he created a kernel injector and a vac disabler (extremely hard)

the code you linked uses singleton behaviour which is bad, we dont need a singleton for a hitmarker. it would add more dependencies.

**Comment by Oly-UK** [comment]
#1434
