### ISSUE TITLE
Add back alpha for chams?

### ISSUE THREAD

**Issue by drgn135** [danielkrupinski/Osiris#847]
The cheat used to have the ability to change the alpha of the chams but this was removed when rainbow colors were added. Anyone know how to add them back in into the current version?

**Comment by AbdallahMehiz** [comment]
use plastic models
they are pretty transparent

**Comment by MinecraftGoodGame** [comment]
Just add it to gui and then alpha modulate the cham material in chams render, alpha is in the config but just removed from the gui

**Comment by danielkrupinski** [comment]
Thanks for pointing that out, it was accidentally removed from GUI in e7422d92347bc4f71517d05708fda885cc11a318
