### ISSUE TITLE
About modifying the skin weapon classification

### ISSUE THREAD

**Issue by jackKiZhu** [danielkrupinski/Osiris#850]
I want to classify the unique skin of each weapon. Which aspect should I start from?

**Comment by Straightplus** [comment]
wat?

**Comment by Straightplus** [comment]
Try again but in english XD

**Comment by WolfOGG** [comment]
I think he is asking if there is any way to have skins be on their own section, such as all the AK skins be separated from the rest such as the AWP skins, when selecting skins under the AK drop box.

**Comment by Straightplus** [comment]
oh okay that makes alot more sense and yeah there is but you would have to add them each time there is a new update
