### ISSUE TITLE
Delay before the first shot

### ISSUE THREAD

**Issue by Chopard** [danielkrupinski/Osiris#853]
Does anyone have an implementation delay before the first shot for Osiris?

**Comment by Straightplus** [comment]
Why would you want that? (actual question?)

**Comment by Straightplus** [comment]
And yeah just put a if (mouse1.dodelay.config.aimbot.delay)
                                     mouse1.down
                                       not working code btw ^^

**Comment by Chopard** [comment]
cus if u use AWP or Scout aim doesnt worked

**Comment by Straightplus** [comment]
If you would like me to i can try and dp this?

**Comment by Chopard** [comment]
sure
