### ISSUE TITLE
question between shot

### ISSUE THREAD

**Issue by Chopard** [danielkrupinski/Osiris#854]
How does aim work if "between shot" disable

**Comment by Finndramere** [comment]
aimbot snaps or drags between shots. with it disabled. it only snaps for a very short amount of time then stops. you could test this out with a deagle with highest fov and lowest smooth with silent aim off. Its basically there for people who have silent aim off on pistol configs so it doesnt snap when holding mouse1 after a kill. But if you wait long enough and when the next bullet is ready, it will snap. Thats how i understand it.
