### ISSUE TITLE
fps drop 

### ISSUE THREAD

**Issue by TMCmaster420** [danielkrupinski/Osiris#855]
almost on ever map ik get just 60 fps normaly around 350.

i hope its fixed in the next update thanks :)

**Comment by danielkrupinski** [comment]
What features do you use? I've never had such issue.

**Comment by agshaidun** [comment]
Did you use this feature?
Fix animation LOD
Fix bone matrix

mine will drop to below 60 if i turn this

**Comment by AbdallahMehiz** [comment]
i use them and actually never had an issue
._.
i also got fps improvements from some of the cheat features

**Comment by thomas0aotian** [comment]
It's a game issue

**Comment by thomas0aotian** [comment]
U prob used all kinds of cheat which is messing up ur game file. I suggest u verify the integrity of the game or delete all .vpk files in csgo  dir and then verify the integrity

**Comment by ZerGo0** [comment]
> Did you use this feature?
> Fix animation LOD
> Fix bone matrix
> 
> mine will drop to below 60 if i turn this

This is correct, my friends and I all have lower FPS if we use them especially `Fix bone matrix`
