### ISSUE TITLE
Cheat update

### ISSUE THREAD

**Issue by yevg555** [danielkrupinski/Osiris#856]
how do I update my local files? I'm new in this Github game
got GitHub Desktop/ Git Bash

**Comment by ZPDMiller** [comment]
On the Code section of Osiris, click the Clone/Download button. Then click Open in Desktop, which will open up Github Desktop for you automatically. You can then choose where you want to have Osiris' source on your computer installed. Once you choose your location, click Clone and let it download the files onto your PC.  When a new update is pushed, Select the Osiris repository in the top left, then click Fetch Origin. Once that's done, click Pull Origin, which will download the latest changes to your install
