### ISSUE TITLE
Can't hook DispatchUserMessage

### ISSUE THREAD

**Issue by woah1337** [danielkrupinski/Osiris#860]
So I tried to hook dispatchusermessage but it throws an exception.
code for the hook:
`bool __fastcall DispatchUserMessage(int messageType, int arg, int arg1, void* data)
{
	utilities::ConsolePrint("DispatchUserMessage Hit!\n");
	return hooks.client.callOriginal<bool, int, int, int, void*>(38, messageType, arg, arg1, data);
}`
`    client.hookAt(38, DispatchUserMessage);
`
it looks like if i do nothing in the hook and just return false it still throws the exception :(
![image](https://user-images.githubusercontent.com/40292926/70851006-670ce180-1eb6-11ea-981a-917dbd2824b1.png)

**Comment by woah1337** [comment]
edit: nvm fixed i just realized what it was after reading my code in the issue LOL

**Comment by Straightplus** [comment]
yo man youve got discord?

**Comment by woah1337** [comment]
> yo man youve got discord?

だめ#1422 why tho niglet?

**Comment by Straightplus** [comment]
cause i wanted to use the hook for inventory changer :) ?
