### ISSUE TITLE
{QUESTION} AVX 512 Optimizations

### ISSUE THREAD

**Issue by VuBrian22** [danielkrupinski/Osiris#864]
Is the AVX 512 instruction set properly compatible with the Osiris Source? Or do we have to stick with AVX/AVX2 for optimization of the cheat?

**Comment by tirziz** [comment]
is AVX 512 significant different from AVX 2 ? My CPU only support AVX 2 :(

**Comment by VuBrian22** [comment]
@tirziz I mean I have a supported CPU. I'm just curious. I do now that if the code is not very AVX512-friendly (many non-vectorized pieces of code in between of vector code), then due to SKX "frequency throttling", AVX512VL could be sometimes more beneficial.

**Comment by VuBrian22** [comment]
UPDATE: I just tried compiling the source through AVX 512 and it crashes on inject. So I guess I answered my own question. I'll keep this open for discussion until I can find a fix submit a pull request or until I give up.

**Comment by 0xE232FE** [comment]
AVX-512 instructions are powerful. With great power comes great responsibility. It seems unwarranted to disable AVX-512 by default at this time. Instead, the usual engineering evaluations should proceed. Check your Mainboard Vendor and BIOS Settings.

**Comment by VuBrian22** [comment]
@0xE232FE Thank you for your input. I have decided to just stick with AVX 2 until compatibility has been confirmed. My CPU is capable of running AVX-512 instructions however the code isn't AVX 512 friendly so it crashes on injection. This issue has been closed.

**Comment by ClaudiuHKS** [comment]
If your CPU is Intel i7, i9, Xeon or Phi, you can try compiling with AVX512 and for sure it'll be much better optimized. If it won't load or crash then switch back to AVX2.
