### ISSUE TITLE
[HELP] new to all this

### ISSUE THREAD

**Issue by XenoxUSser** [danielkrupinski/Osiris#867]
Im new to all this and i have downloaded and made the osiris dll like told but idk how to update and neither add features from the pull request site so any help would be very apretiated!

**Comment by Nexo848** [comment]
At first learn basics of C++, osiris is very advanced thing, you will not understand it at all without any c++ knowledge.

**Comment by XenoxUSser** [comment]
> At first learn basics of C++, osiris is very advanced thing, you will not understand it at all without any c++ knowledge.

oh geez i dont think i have time for that is there an easier way i mean copy shit ya know

**Comment by xAkiraMiura** [comment]
im assuming you have vs2019, 
if you go on the right size you can change from `Solution Explorer` to `Team Explorer`.
if you used `git clone` then you will have the origin set, 
if you downloaded it you most like wont.
^ the command to fix this is `git init & git remote add origin https://github.com/danielkrupinski/Osiris.git`
whenever there is an update to osiris just do `Team Explorer -> Sync -> Pull (under Incoming Commits)`

**Comment by XenoxUSser** [comment]
> im assuming you have vs2019,
> if you go on the right size you can change from `Solution Explorer` to `Team Explorer`.
> if you used `git clone` then you will have the origin set,
> if you downloaded it you most like wont.
> ^ the command to fix this is `git init & git remote add origin https://github.com/danielkrupinski/Osiris.git`
> whenever there is an update to osiris just do `Team Explorer -> Sync -> Pull (under Incoming Commits)`

so what i do is type git init ? sorry im very new to this i never used c++ or anything and i only made an osiris dll one time

**Comment by xAkiraMiura** [comment]
do you have git for windows installed? install it if not
you need to open a command prompt and then move to your Osiris folder
^ example: `cd C:/Users/user/Downloads/Osiris`. the cd command moves you around
next run the git command `git init & git remote add origin https://github.com/danielkrupinski/Osiris.git`
your git should be working, now we can use `git pull` or just use vs2019 to do it for us

**Comment by XenoxUSser** [comment]
Users\Jack_Midnight>git init & git remote add origin https://github.com/danielkrupinski/Osiris.git
Initialized empty Git repository in C:/Users/Jack_Midnight/.git/

C:\Users\Jack_Midnight>
thats what i get when doing it

**Comment by XenoxUSser** [comment]
> do you have git for windows installed? install it if not
> you need to open a command prompt and then move to your Osiris folder
> ^ example: `cd C:/Users/user/Downloads/Osiris`. the cd command moves you around
> next run the git command `git init & git remote add origin https://github.com/danielkrupinski/Osiris.git`
> your git should be working, now we can use `git pull` or just use vs2019 to do it for us

ok its pulling the data now and how do i add pull requests to my osiris?

**Comment by xAkiraMiura** [comment]
if you contributed any code you will have to fork the project, commit it, then make a pull request. use a git tutorial for it because its a bit complicated. you should be able to run the .SLN file now and build it as `release x86`.

**Comment by XenoxUSser** [comment]
sorry but im very confused now i have the osiris file opened in visual studio what do i do now to add a pull request to it like hitmarker

> if you contributed any code you will have to fork the project, commit it, then make a pull request. use a git tutorial for it because its a bit complicated. you should be able to run the .SLN file now and build it as `release x86`.

i have it open now in visual studio the new osiris file how do i add the hitmarker for example?

**Comment by xAkiraMiura** [comment]
are you trying to get someone else's code or give us your code?

**Comment by xAkiraMiura** [comment]
if you want someone else's hitmarker then you can use `git clone https://github.com/...`, it will create the project with everything set up, ready for building. (the ... is whoever made the hitmarker's repo)

**Comment by XenoxUSser** [comment]
> if you want someone else's hitmarker then you can use `git clone https://github.com/...`, it will create the project with everything set up, ready for building. (the ... is whoever made the hitmarker's repo)

i want to get this implemented into osiris 
https://github.com/danielkrupinski/Osiris/pull/827
https://github.com/danielkrupinski/Osiris/pull/824

**Comment by XenoxUSser** [comment]
> if you want someone else's hitmarker then you can use `git clone https://github.com/...`, it will create the project with everything set up, ready for building. (the ... is whoever made the hitmarker's repo)

so how do i add these both?

**Comment by XenoxUSser** [comment]
> > if you want someone else's hitmarker then you can use `git clone https://github.com/...`, it will create the project with everything set up, ready for building. (the ... is whoever made the hitmarker's repo)
> 
> so how do i add these both?

https://github.com/danielkrupinski/Osiris/pull/739
forgot that one

**Comment by XenoxUSser** [comment]
> if you want someone else's hitmarker then you can use `git clone https://github.com/...`, it will create the project with everything set up, ready for building. (the ... is whoever made the hitmarker's repo)

hello?

**Comment by XenoxUSser** [comment]
agh fine i have to go to work tomorow then not
