### ISSUE TITLE
[HELP] pull requests

### ISSUE THREAD

**Issue by XenoxUSser** [danielkrupinski/Osiris#868]
i have seen multiple pull resuests i wanna add into my osiris so how do i do that?

**Comment by XenoxUSser** [comment]
I'm completely new to this I used git and got osiris now in visual studio what do I do now?

**Comment by rosesware** [comment]
go to commits, and copy paste all changes.

**Comment by VuBrian22** [comment]
Or download the raw code and just copy and replace the files from your osiris directory and compile.

**Comment by xAkiraMiura** [comment]
if you make your own branch you can probably use git merge.

**Comment by XenoxUSser** [comment]
can someone make me a quick totorial on how ?

**Comment by XenoxUSser** [comment]
> Or download the raw code and just copy and replace the files from your osiris directory and compile.

mind if chu make a step by step totorial maybe? sorry like i said im very new to this

**Comment by xAkiraMiura** [comment]
why waste time pasting code over.

fork osiris
clone your new repo
use git merge on both of the pulls you want
build it

you can look up all of the steps above on google

**Comment by XenoxUSser** [comment]
> why waste time pasting code over.
> 
> fork osiris
> clone your new repo
> use git merge on both of the pulls you want
> build it
> 
> you can look up all of the steps above on google

i know i am fucking stupid but could you please explain in steps all i find is on how to fucking make a pull request

**Comment by 0xE232FE** [comment]
**### Git Merge**
https://www.atlassian.com/git/tutorials/using-branches/git-merge

**### Git Branching - Mege**
https://learngitbranching.js.org/

Super Simple and easy to understand!
