### ISSUE TITLE
(SUGGESTION) Adding anti OBS and New menu

### ISSUE THREAD

**Issue by SmakHvh** [danielkrupinski/Osiris#870]
A great feature that is in majority of cheats is anti obs and it's not a overly useful thing but it would be a good feature to add aswell as others also a possible new menu I like the unique menu but it doesn't look good it's really spread out and having more compressed menu would look great with the same menu customisations

**Comment by xAkiraMiura** [comment]
osiris uses valve's ISurface and VGui Panels so i don't think it would be possible to add anti obs (for the esp, at least. imgui uses its own renderer.)
i agree that the menu looks too robotic. i dont think daniel will change the menu so adding another style is our only option. (i can't think of a gui that has auto positioning)

**Comment by anonymouschicken1111** [comment]
You could design your own Menu and share it in the pull requests I personally don't have time and I would be happy to see some new designs.

**Comment by danielkrupinski** [comment]
Check out recently released [GOESP](https://github.com/danielkrupinski/GOESP)!

**Comment by anonymouschicken1111** [comment]
Ma mind fking blown

**Comment by littlehurensohn** [comment]
Menu can create by urself, it isnt hard. 

noob != not new menu.

**Comment by xAkiraMiura** [comment]
I have created a menu, it is a bit hard for a c++ beginner that doesn't understand ISurface/D3D and InputSystem/GKSA. Creating a menu is a lot of optimization because you have to handle many things like key presses and buttons in an effecient way. Why should we accept a PR to a GUI that performs worse that ImGui?

**Comment by anonymouschicken1111** [comment]
> Menu can create by urself, it isnt hard.
> 
> noob != not new menu.

Chilllax, know it all ass
