### ISSUE TITLE
[Suggestion]Character's Skin Changer

### ISSUE THREAD

**Issue by anarbmw** [danielkrupinski/Osiris#871]
I'd like to know, is it possible to change character's skin, so it will show it to everyone, just like prime status thing?

**Comment by xAkiraMiura** [comment]
the player **SKINS** are **SKINS** and **SKINS** are server side. we could probably spoof it locally (already possible before OP SW) but you can't fake skins. valve actually cares about their skins because it makes them money.

**Comment by xAkiraMiura** [comment]
also this is a [Question] not a [Suggestion]. if you know its possible then do a suggestion, you were asking if its possible.

**Comment by Shaxzy** [comment]
Do you mean something like this?
https://streamable.com/mz1an

**Comment by xAkiraMiura** [comment]
yes they do, however they wanted a server side version which is impossible.
