### ISSUE TITLE
[Request] Remove head dot when first person spectating another player

### ISSUE THREAD

**Issue by pointydev** [danielkrupinski/Osiris#873]
Hey,

Currently while first person spectating a player that is a valid target for head dot, you can see a floating dot moving around which is rather distracting. Might be a good idea to remove it for the current spectate target. See below:

![](https://pointy.needs-to-s.top/92fr87f.png)

Thanks,
Pointy

**Comment by thomas0aotian** [comment]
@pointydev and fov/ viewmodel fov also

**Comment by linkupbiz** [comment]
I think this has been said before, but in case no one saw it, please replace the head dot with bone esp.

**Comment by pointydev** [comment]
> please replace the head dot with bone esp.

probably not replace, but add alongside perhaps

**Comment by xAkiraMiura** [comment]
Eye sights also have this issue. 
possible solution: loop over all players and get their observers, if we see the local player we stop and skip them when rendering the esp.

**Comment by woah1337** [comment]
if(!localPlayer->isAlive()) return: ?

**Comment by xAkiraMiura** [comment]
localplayer doesnt refer to the spectated player.

**Comment by danielkrupinski** [comment]
Fixed, thanks for reporting the issue.
