### ISSUE TITLE
How to add a pull request to Osiris

### ISSUE THREAD

**Issue by Ties113** [danielkrupinski/Osiris#874]
Hi ilm new and I don't know much about coding so how do I add a pull request to Osiris?

**Comment by xAkiraMiura** [comment]
Do you already have a fork with your own commits set up? please give more info on your current state.

**Comment by Ties113** [comment]
Well I don't know what you mean with fork and commits I just have Osiris and I wanted a fov circle cuz I don't know what fov is good for what situations

**Comment by xAkiraMiura** [comment]
ive put some information in #868 if you can use it. basically you need to fork the project and then merge the branches you want.

**Comment by Ties113** [comment]
> ive put some information in #868 if you can use it. basically you need to fork the project and then merge the branches you want.

Thanks 🙃

**Comment by tirziz** [comment]
Please close this issue if you got the answer.

**Comment by Ties113** [comment]
> Please close this issue if you got the answer.

Ok thanks for reminging
