### ISSUE TITLE
[Question] NadePredict

### ISSUE THREAD

**Issue by Straightplus** [danielkrupinski/Osiris#875]
Yeah hi i would like to ask if its possible to make another design for the nadepredict?
I have seen the flaming behavior lately so please dont be toxic thanks Straight+

**Comment by xAkiraMiura** [comment]
the current grenade prediction is the one built in with the game, it would take a lot more performance to trace a line than to just force a cvar, are you sure this is a good price to pay?

**Comment by linkupbiz** [comment]
> the current grenade prediction is the one built in with the game, it would take a lot more performance to trace a line than to just force a cvar, are you sure this is a good price to pay?

To be fair, I have heard this nade predict is off by a lot, and I've also see a couple videos on it, so in conclusion a new nade predict wouldn't be bad, but its up to the devs.

**Comment by ZerGo0** [comment]
> the current grenade prediction is the one built in with the game, it would take a lot more performance to trace a line than to just force a cvar, are you sure this is a good price to pay?

The performance of the current one isn't really good either, I lose like 20-40 FPS when I use it and through a nade. I would add a new one, but I don't have enough time, a lot of things would've to be changed.
