### ISSUE TITLE
Stream proofing

### ISSUE THREAD

**Issue by 4cc3s** [danielkrupinski/Osiris#876]
Hello Daniel, can you please add Stream Proofing in next update?

**Comment by xAkiraMiura** [comment]
#870, although the menu would work because it uses D3D, the visuals use ISurface which is not possible to make stream safe. (chams and world visuals are also not possible to make stream safe, they cant be remade with d3d)

**Comment by 4cc3s** [comment]
Ahhh

**Comment by anonymouschicken1111** [comment]
Close issue?

**Comment by danielkrupinski** [comment]
Stream Proof ESP has been added.
