### ISSUE TITLE
No work draw fow

### ISSUE THREAD

**Issue by DerLi1** [danielkrupinski/Osiris#878]
I use fov in pull request, and don't work, plz check https://github.com/DerLi1/Osiris why don't work

**Comment by xAkiraMiura** [comment]
please open an issue there, that code is not in this repo.

**Comment by ZerGo0** [comment]
> I use fov in pull request, and don't work, plz check https://github.com/DerLi1/Osiris why don't work

You literally have no idea what you are doing, you don't even call the function anywhere, no config addition for it and so on. You just copied the GUI and ESP file, you have to do more than that to make it work.

**Comment by DerLi1** [comment]
> > I use fov in pull request, and don't work, plz check https://github.com/DerLi1/Osiris why don't work
> 
> You literally have no idea what you are doing, you don't even call the function anywhere, no config addition for it and so on. You just copied the GUI and ESP file, you have to do more than that to make it work.

I think and I fix this 5 minutes ago
