### ISSUE TITLE
i m writing hack，who konw GetEyePosition how to write

### ISSUE THREAD

**Issue by maoxian123** [danielkrupinski/Osiris#879]
i m writing hack，who konw GetEyePosition how to write

**Comment by ifoverload** [comment]
`
const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
 auto eyepos = localPlayer->getEyePosition();
`
?

**Comment by maoxian123** [comment]
i  just want to judge the enemy isVisible，but i  cant understand how  the Osiris  get that

**Comment by maoxian123** [comment]
> `const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer()); auto eyepos = localPlayer->getEyePosition();`
> ?

i just want to judge the enemy isVisible，but i cant understand how the Osiris get that

**Comment by ifoverload** [comment]
> > `const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer()); auto eyepos = localPlayer->getEyePosition();`
> > ?
> 
> i just want to judge the enemy isVisible，but i cant understand how the Osiris get that

i don't get what you mean with that

**Comment by maoxian123** [comment]
> > > `const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer()); auto eyepos = localPlayer->getEyePosition();`
> > > ?
> > 
> > 
> > i just want to judge the enemy isVisible，but i cant understand how the Osiris get that
> 
> i don't get what you mean with that

i just want to judge the enemy is Visible or not

**Comment by ifoverload** [comment]
yeah but there is an esp for enemy with different visible & occluded config

**Comment by maoxian123** [comment]
> yeah but there is an esp for enemy with different visible & occluded config

can  you give me the code

**Comment by ifoverload** [comment]
https://prnt.sc/qdesnb
make sure that "All" option is disabled, when u want different config for visible & occluded

**Comment by ZerGo0** [comment]
> https://prnt.sc/qdesnb
> make sure that "All" option is disabled, when u want different config for visible & occluded

He is coding his "own" cheat and wants to know how to make a visibility check.



> > yeah but there is an esp for enemy with different visible & occluded config
> 
> can you give me the code

https://github.com/danielkrupinski/Osiris/blob/b84979d7eaadf67693f9e4ea3efd5d07f0332661/Osiris/SDK/Entity.h#L107

Should be self-explanatory.

**Comment by ifoverload** [comment]
kk sorry, eng not my native
