### ISSUE TITLE
[Question] Spinbot?

### ISSUE THREAD

**Issue by Adim2P** [danielkrupinski/Osiris#880]
Anyone know when Osiris is gonna get a spinbot with a full custom config feature? I don't know I wanna try HvH servers, can anyone recommend me a good rage cheat thats free with configurated options?

**Comment by rosesware** [comment]
https://github.com/danielkrupinski/Osiris/pull/739

**Comment by AbdallahMehiz** [comment]
> Anyone know when Osiris is gonna get a spinbot with a full custom config feature? I don't know I wanna try HvH servers, can anyone recommend me a good rage cheat thats free with configurated options?

bro cmon
dont beg people for free cheats 
but if u want one go to [cheater.fun](url)

**Comment by Adim2P** [comment]
> > Anyone know when Osiris is gonna get a spinbot with a full custom config feature? I don't know I wanna try HvH servers, can anyone recommend me a good rage cheat thats free with configurated options?
> 
> bro cmon
> dont beg people for free cheats
> but if u want one go to [cheater.fun](url)

I was asking for recommendations on a good cheat and not begging for one, there's a difference. And that site looks suspicious as fuck so thank you and no thank you.

**Comment by Adim2P** [comment]
> #739

Thanks btw.

**Comment by agshaidun** [comment]
#906

**Comment by DoomFishWasTaken** [comment]
#1546 my pull

**Comment by wirebruh** [comment]
imagine hvhing with a paste without a resolver

**Comment by DoomFishWasTaken** [comment]
@wirebruh bruh what kind of a nn u are when u need a resolver, resolvers are only bad (especially fatality (it dumps the fuck out of my pull))
