### ISSUE TITLE
VAC Bypass/Osiris

### ISSUE THREAD

**Issue by anarbmw** [danielkrupinski/Osiris#882]
Does VAC Bypass Loader still works?

Which Osiris features VAC can detect?

**Comment by ZPDMiller** [comment]
Yeah the VAC Bypass still works

**Comment by AbdallahMehiz** [comment]
Perfectly fine for me
It might be your injector

**Comment by anarbmw** [comment]
Im using VAC Bypass, but I was just making sure that it works. Also, I was asking about features which can be detected by VAC or Overwatch.

**Comment by rosesware** [comment]
> Im using VAC Bypass, but I was just making sure that it works. Also, I was asking about features which can be detected by VAC or Overwatch.

Any feature can be detected, you just have to put some junkcodes, use VAC Bypass and undetected injector.

**Comment by SmakHvh** [comment]
Is there and injection method called vac bypass

**Comment by tirziz** [comment]
Vac bypass work fine. 
And junk code just reduce you cheat performamce.
In my opinion if you want to make it safer, you can remove aimbot, aa, remove some tickbase features. And rework on hooking vmt. It will make you cheat last very long without being detected by vac.

**Comment by xAkiraMiura** [comment]
junk code is literally useless, hash detections are very rare.
polymorphic code workeds, vac uses signatures (based on asm code) and it changes the assembly.
removing code doesnt do much unless you know what has been sigged (which you dont)
i havent changed the source 1 bit and ive never been vac banned.
