### ISSUE TITLE
[Suggestion] Chat spammer (give me your thoughts :D)

### ISSUE THREAD

**Issue by Straightplus** [danielkrupinski/Osiris#883]
**As title says ^^**

**Comment by AbdallahMehiz** [comment]
Why would u need or use that?

**Comment by Straightplus** [comment]
Idk i just think its a kinda cool feature

**Comment by tirziz** [comment]
There is a kill spammer. You can edit it , it easy

**Comment by anonymouschicken1111** [comment]
`interfaces.engine->clientCmdUnrestricted(std::string{ "say " }.append(config.misc.SpamString).c_str());`

**Comment by Straightplus** [comment]
@anonymouschicken1111 you need a for loop XD
