### ISSUE TITLE
[Suggestion]Agent Changer

### ISSUE THREAD

**Issue by AbdallahMehiz** [danielkrupinski/Osiris#886]
we might use an agent changer in the skinchanger window the same as the knife changer and the glove changer.
i tried it. 
my game crashes everytime :(
help please

**Comment by woah1337** [comment]
dumbass post code

**Comment by JDeu** [comment]
This is what I use.

`	static constexpr const char* effects[]{
		"models/player/custom_player/legacy/ctm_fbi_variantb.mdl",
		"models/player/custom_player/legacy/ctm_fbi_variantf.mdl",
		"models/player/custom_player/legacy/ctm_fbi_variantg.mdl",
		"models/player/custom_player/legacy/ctm_fbi_varianth.mdl",
		"models/player/custom_player/legacy/ctm_sas_variantf.mdl",
		"models/player/custom_player/legacy/ctm_st6_variante.mdl",
		"models/player/custom_player/legacy/ctm_st6_variantg.mdl",
		"models/player/custom_player/legacy/ctm_st6_varianti.mdl",
		"models/player/custom_player/legacy/ctm_st6_variantk.mdl",
		"models/player/custom_player/legacy/ctm_st6_variantm.mdl",
		"models/player/custom_player/legacy/tm_balkan_variantf.mdl",
		"models/player/custom_player/legacy/tm_balkan_variantg.mdl",
		"models/player/custom_player/legacy/tm_balkan_varianth.mdl",
		"models/player/custom_player/legacy/tm_balkan_varianti.mdl",
		"models/player/custom_player/legacy/tm_balkan_variantj.mdl",
		"models/player/custom_player/legacy/tm_leet_variantf.mdl",
		"models/player/custom_player/legacy/tm_leet_variantg.mdl",
		"models/player/custom_player/legacy/tm_leet_varianth.mdl",
		"models/player/custom_player/legacy/tm_leet_varianti.mdl",
		"models/player/custom_player/legacy/tm_phoenix_variantf.mdl",
		"models/player/custom_player/legacy/tm_phoenix_variantg.mdl",
		"models/player/custom_player/legacy/tm_phoenix_varianth.mdl"
	};

	auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());

	if (stage == FrameStage::NET_UPDATE_POSTDATAUPDATE_START)
		localPlayer->setModelIndex(interfaces.modelInfo->getModelIndex(effects[config.visuals.playerModel]));`

**Comment by ZPDMiller** [comment]
Thanks for that JDeu, you should probably do a PR for those who don't know how to add that

**Comment by AbdallahMehiz** [comment]
> This is what I use.
> 
> `static constexpr const char* models[]{
> "models/player/custom_player/legacy/ctm_fbi_variantb.mdl",
> "models/player/custom_player/legacy/ctm_fbi_variantf.mdl",
> "models/player/custom_player/legacy/ctm_fbi_variantg.mdl",
> "models/player/custom_player/legacy/ctm_fbi_varianth.mdl",
> "models/player/custom_player/legacy/ctm_sas_variantf.mdl",
> "models/player/custom_player/legacy/ctm_st6_variante.mdl",
> "models/player/custom_player/legacy/ctm_st6_variantg.mdl",
> "models/player/custom_player/legacy/ctm_st6_varianti.mdl",
> "models/player/custom_player/legacy/ctm_st6_variantk.mdl",
> "models/player/custom_player/legacy/ctm_st6_variantm.mdl",
> "models/player/custom_player/legacy/tm_balkan_variantf.mdl",
> "models/player/custom_player/legacy/tm_balkan_variantg.mdl",
> "models/player/custom_player/legacy/tm_balkan_varianth.mdl",
> "models/player/custom_player/legacy/tm_balkan_varianti.mdl",
> "models/player/custom_player/legacy/tm_balkan_variantj.mdl",
> "models/player/custom_player/legacy/tm_leet_variantf.mdl",
> "models/player/custom_player/legacy/tm_leet_variantg.mdl",
> "models/player/custom_player/legacy/tm_leet_varianth.mdl",
> "models/player/custom_player/legacy/tm_leet_varianti.mdl",
> "models/player/custom_player/legacy/tm_phoenix_variantf.mdl",
> "models/player/custom_player/legacy/tm_phoenix_variantg.mdl",
> "models/player/custom_player/legacy/tm_phoenix_varianth.mdl"
> };
> 
> ```
> auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
> 
> if (stage == FrameStage::NET_UPDATE_POSTDATAUPDATE_START)
> 	localPlayer->setModelIndex(interfaces.modelInfo->getModelIndex(models[config.visuals.playerModel]));`
> ```

you should do a pull request man 
many people will love this addition
