### ISSUE TITLE
[Suggestion] Integrate ray based hitchance

### ISSUE THREAD

**Issue by streamshark** [danielkrupinski/Osiris#888]
After playing with Osiris for awhile on Danger Zone, I noticed it tends to shoot at players WAY farther than what is feasible with the max aim inaccuracy I had set.  The accuracy check seems to simply use the current inaccuracy for the player's weapon, but does not use anything that would discriminate based on the enemies position as long as the hitpoint is not occluded.  From what I have found, other cheats commonly estimate hitchance by running a pool of raytraces on the enemy randomly in the spread cone of the player's current inaccuracy value, then calculate how many rays hit out of how many were fired to better estimate real hitchance. Doing it this way or using a statistical estimation method would help ensure the cheat isn't shooting at what is wildly improbable to hit. Performance declines are the downside to this, but I imagine efficiency could be improved via some heuristics to reduce when hitchance is calculated on an enemy and how many rays are fired to calculate.

**Comment by SmakHvh** [comment]
This needs to be done

**Comment by xAkiraMiura** [comment]
i think raising your min damage could fix this. if it doesnt then there is a problem with the autowall where it doesnt factor in damage drop off (i doubt this problem exists).

**Comment by streamshark** [comment]
> i think raising your min damage could fix this. if it doesnt then there is a problem with the autowall where it doesnt factor in damage drop off (i doubt this problem exists).

This isn't the case, the issue is that it does not factor enemy position at all when determining inaccuracy. It only uses the local player inaccuracy, so if you have high accuracy value (crouched, stopped moving, etc) it will shoot at players at an infinite distance that are insanely statistically improbably to hit. The damage modifiers are fine as is, the issue is having an "inaccuracy" threshold rather than a true hitchance that factors enemy placement
