### ISSUE TITLE
(HELP) aimbot autostop movement / trigger the Auto shot only if accurate for sniper rifle

### ISSUE THREAD

**Issue by ifoverload** [danielkrupinski/Osiris#889]
as the title say, because as the current aimbot code i will surely miss the sniper shot if i'm not actually standing still
tried inside if bestTarget
```
cmd->forwardmove = 0;
cmd->sidemove = 0;
cmd->upmove = 0;
```
but it just don't work accurately
please give me any hint thanks!

**Comment by newcommerdontblame** [comment]
did u done:)?
