### ISSUE TITLE
[Yet another simple suggestion] Box ESP :)

### ISSUE THREAD

**Issue by TrackyBunny** [danielkrupinski/Osiris#89]
Hey! I think it will be cool for you to add a simple Box ESP since every other cheat has it.

I don't think it's that hard either as I've heard from other coders. 

Now I'm not sure but you might need World2Screen or some function like that I really don't know, as I wanna help but I'm not a good coder :D

**Comment by danielkrupinski** [comment]
Duplicate #61

**Comment by Fizz3** [comment]
I'm going to push this feature on a branch on my fork within the next day, once I clean up the code. I've only got 2D box (enemy and friendly toggles), name, health. Not sure if it will get merged with Daniel's repo, mines probably going to deviate quite a bit to suit my own wants.

**Comment by Fizz3** [comment]
@TrackyBunny It's available on my feature branch now. Added in one commit, so it should be easy to see what I've changed/added if you wanted to paste it into your copy of Daniels branch.
