### ISSUE TITLE
Hey, i really wanna help with this cuz i get on everysingle cheat and i dont even understand what it is

### ISSUE THREAD

**Issue by SorryX** [danielkrupinski/Osiris#890]
the problem is coming from std 
Filename = exempel chams.cpp
Problem:Filename is not a member of std
or something like that
and something else is sin and other stuff like that
so if someone could help me it would be awesome

**Comment by anonymouschicken1111** [comment]
Share source?

**Comment by woah1337** [comment]
it has std you need to disinfect it

**Comment by effex1337** [comment]
dude it actually has a std you need to disinfect it

**Comment by swegamegh** [comment]
i dont acctuly know what disinfect can you guys explain really sorry
