### ISSUE TITLE
Aimbot not working

### ISSUE THREAD

**Issue by Looopering** [danielkrupinski/Osiris#899]
Aimbot is not working for me at all, i've tried everything is this like a common issue?

**Comment by SmakHvh** [comment]
You have to enable it on each weapon

**Comment by Looopering** [comment]
You think, i'm stupid that's what i already did.

**Comment by SmakHvh** [comment]
Well yea I think your stupid it's working for everyone else

**Comment by AbdallahMehiz** [comment]
> You think, i'm stupid that's what i already did.

increase the fov maybe?

**Comment by anonymouschicken1111** [comment]
> You think, i'm stupid that's what i already did.

Brav you're the one asking for help, if you want help don't insult the guy trynna help.

**Comment by gustavogino** [comment]
You are probably leaving the aimbot error at 0, set it to 1.

**Comment by VuBrian22** [comment]
Un-check "On-Key".....

**Comment by xAkiraMiura** [comment]
make sure the recoil control scale is set to 100% for both x and y, 
enable is selected,
on key is disabled. 
fov should be 100% as well

**Comment by NNKTV28** [comment]
where can i change the recoil scale?
