### ISSUE TITLE
How to get back the old color picker

### ISSUE THREAD

**Issue by JayneFrack** [danielkrupinski/Osiris#90]
How could I get back the old color picker? The new one looks pretty good but I don't like the handling how would I get back the old color picker?

**Comment by effexcs** [comment]
change something like bool Imgui::color pickerr orr smthin
just find it somewhere lots of stuff imgui related are open source

**Comment by danielkrupinski** [comment]
I assume you mean [checkbox + color picker widget](https://github.com/danielkrupinski/Osiris/commit/4a6d7dddd4cdb1c62ac7fb29102dd56069cba91b)
