### ISSUE TITLE
Injection

### ISSUE THREAD

**Issue by Stage4000** [danielkrupinski/Osiris#900]
How can I make this work with manual map injection?

**Comment by AbdallahMehiz** [comment]
download an injector that supports MM or make one yourself
you can also use open source injectors like rando-injector, just add some junk code to it to make it temporarily undetected.

**Comment by Stage4000** [comment]
But the cheat crashes when i try to inject with man map

**Comment by ifoverload** [comment]
use GH Injector, manualmap is working for me

**Comment by MrSleekZ** [comment]
Link?

**Comment by Stage4000** [comment]
> use GH Injector, manualmap is working for me

@MrSleekZ is replying to you.

**Comment by ifoverload** [comment]
> Link?

its opensource
exeready: https://guidedhacking.com/resources/guided-hacking-dll-injector.4/
source: https://github.com/guided-hacking/GuidedHacking-Injector

**Comment by AbdallahMehiz** [comment]
> But the cheat crashes when i try to inject with man map

I use the cheat almost everyday, it never crashed my game even once for the last 7 days at least.

**Comment by effex1337** [comment]
1. If you want to make it work with your mmap injector you need to recode the whole cheat and make a proper entry point.

2. Else find a mmap injector that works with it.

Why?:imo this is cuz people dont have the knowledge to make their own stuff, they try to sell other's work, to prevent this some measures are applied leading to this kind of issue. 

Have a good day!

**Comment by AbdallahMehiz** [comment]
can this issue be closed?

**Comment by MrSleekZ** [comment]
@Stage4000
