### ISSUE TITLE
dark chams

### ISSUE THREAD

**Issue by Pateeesz** [danielkrupinski/Osiris#901]
https://i.gyazo.com/3a9259f2c290079c95bd94ab70adb556.jpg

Only normal, flat and glass working

**Comment by effex1337** [comment]
Video shaders->shader settings->very high
Else it wont work
This is cuz csgo uses envmap for reflections which is disabled when the shader settings arent on very high.

**Comment by Pateeesz** [comment]
oh, thanks bro
