### ISSUE TITLE
[SUGGESTION] Add max shot inaccuracy or hitchance to triggerbot

### ISSUE THREAD

**Issue by Finndramere** [danielkrupinski/Osiris#907]
Would be nice addition since triggerbot just shoots if you're moving and aiming at the target.

**Comment by rosesware** [comment]
You can do it by yourself easily. 👍

**Comment by Finndramere** [comment]
> You can do it by yourself easily. 👍

sorry i suck ass at coding csgo cheats atm. i only know python, java and a little bit of swift. Would be nice if could contribute to this community in the future.
