### ISSUE TITLE
Add skeleton esp, improve aimbot so you can use aimlock and silent at the same time, add fov slider for the silent if using both aimlock and silent, add streaming proof visuals, fix the stars not showing up on the knives and on stattrak.

### ISSUE THREAD

**Issue by SapphireCodenz** [danielkrupinski/Osiris#909]

**Comment by AbdallahMehiz** [comment]
do it yourself + fix your title

**Comment by KernCS** [comment]
you can get a star infront of your knife if you change the quality of the knife from "Default" to "Unusual"

**Comment by rosesware** [comment]
Btw, you know you have a TITLE and DESCRIPTION right?

**Comment by hyperxpro** [comment]
Wow Wow Wow Wow. Do you wear underwear on your head and T-shirt at Underwear place? 

I mean seriously, you can't understand difference between Title and Description?

**Comment by Sapphire1337420** [comment]
yo guys chill out I'm new to GitHub, i apologize.

**Comment by hyperxpro** [comment]
> yo guys chill out I'm new to GitHub, i apologize.

Ah, Now it makes sense! :D
