### ISSUE TITLE
[List] Most of the broken stuff 

### ISSUE THREAD

**Issue by woah1337** [danielkrupinski/Osiris#91]
[High Priority]
-RCS doesn't seem to work properly at low fov
[Moderate Priority]
-Knifechanger (small bug with icon not showing on bottom left)
[Low Priority]
-Sniper Crosshair (doesn't work at all)
-Recoil Crosshair (doesn't work at all)

**Comment by danielkrupinski** [comment]
Could you explain more in detail?

**Comment by Fizz3** [comment]
I believe the RCS bug is how at low FOV it wont RCS, because after adjusting for recoil the crosshair leaves the aimbot FOV. Maybe fix by compensating the dx,dy values caused by RCS, subtracting it from the actual viewangle.

**Comment by woah1337** [comment]
> Could you explain more in detail?

I just made a list of stuff that needs to be fixed to help you doing bugfixes, etc. Whenever I find a new bug I'll just post it here.


> I believe the RCS bug is how at low FOV it wont RCS, because after adjusting for recoil the crosshair leaves the aimbot FOV. Maybe fix by compensating the dx,dy values caused by RCS, subtracting it from the actual viewangle.

Idk cpp that much but thanks, I'll try

**Comment by Shaxzy** [comment]
Recoil and sniper crosshair works just fine for me

**Comment by kasem123** [comment]
Glow seems really buggy, at least for me. It only shows players about 10% of the time, even when they're really close.
