### ISSUE TITLE
[Help] Hitmarker

### ISSUE THREAD

**Issue by VeLocityYT** [danielkrupinski/Osiris#912]
![asd](https://user-images.githubusercontent.com/34091290/71467368-32bded00-27f5-11ea-9492-3cbeb91ca14f.png)

anyone know where is the location of that 4 files?
                "effects/dronecam",
                "effects/underwater_overlay",
                "effects/healthboost",
                "effects/dangerzone_screen"

**Comment by MinecraftGoodGame** [comment]
In game files, in pak files to be more exact. To access them open pak01_dir in GCFscape and search for folder "effects"

**Comment by VeLocityYT** [comment]
> 
> 
> In game files, in pak files to be more exact. To access them open pak01_dir in GCFscape and search for folder "effects"

thanks my friend.
