### ISSUE TITLE
Check if it's freezetime

### ISSUE THREAD

**Issue by MinecraftGoodGame** [danielkrupinski/Osiris#913]
Hi, I want to turn off antiaim on freezetime, but I cannot find a way to check if it's freezetime or not. I tried FL_FROZEN but it only works when camera cannot move, not player, and that's not what I want. Also i tried `NETVAR(freezetime, "DT_CSGameRulesProxy", "m_bFreezePeriod", bool)` but i don't really know where to put it. So... Any ideas?

**Comment by effex1337** [comment]
if (!strcmp(pEvent->GetName(), "round_freeze_end")) {
freezetime = false;
}

if (!strcmp(pEvent->GetName(), "round_prestart")) {
freezetime = true;
}
U might wanna add listeners
And also use fl_frozen for disabling aa when round ends.
