### ISSUE TITLE
[Issue] Player Models.

### ISSUE THREAD

**Issue by rosesware** [danielkrupinski/Osiris#914]
The issue is, **when we put some Player Model, fine, but when we put Default back the Player Model just don't return**, don't change to default.

Perhaps the fix is super easy, but I'm not a coder and paster as well.

**Comment by ifoverload** [comment]
yes because as the current code, the "Default" model option here is only define to not trigger the setModel function, maybe daniel need to backup "localPlayer->getModel()->name" before it actually changed it

**Comment by rosesware** [comment]
Humm...

**Comment by AbdallahMehiz** [comment]
> The issue is, **when we put some Player Model, fine, but when we put Default back the Player Model just don't return**, don't change to default.
> 
> Perhaps the fix is super easy, but I'm not a coder and paster as well.

you can apply the default player model by clicking on the apply button on the skinchanger tab

**Comment by rosesware** [comment]
> > The issue is, **when we put some Player Model, fine, but when we put Default back the Player Model just don't return**, don't change to default.
> > Perhaps the fix is super easy, but I'm not a coder and paster as well.
> 
> you can apply the default player model by clicking on the apply button on the skinchanger tab

Kinda boring. 😞

**Comment by AbdallahMehiz** [comment]
@rosesware can you close this issue?
