### ISSUE TITLE
[Suggestions] And a lot of em

### ISSUE THREAD

**Issue by Adim2P** [danielkrupinski/Osiris#915]
Well I had been on Osiris for almost 4 months and I have a lot of interesting suggestion at hands, I'm not expecting for this suggestion to appear soon nor I'm desperate for this. 

Moving on here are the list of suggestion I have in mind for this cheat.

1st is 'Flashbanged' Glow, similar to planting category, this will reveal to the user the location of the victims on the flashbang you threw, not really useful I know, but this feature will help some players who are unsure if there flashbangs hit or not. Then after the flashbang effect has subsided on the victims the see thru glows will be gone.

2nd is Relay Connectors similar to skeet, all it does is change where ur gonna matchmake, if I set it to America, I'll only join American only server regardless where the hell I'm.

3rd Movement Hacks this might be a bit difficult, but I've seen Millionware v3 has this. It currently has the feature to abuse Edge Bug when you turn it on and other fall damage bugs. I don't know this sounds hard to implement.

**Comment by tirziz** [comment]
For 2nd one, use this https://gamebanana.com/tools/5684
Also, the flashed glow is not legit , u may get ow ban.

**Comment by rosesware** [comment]
> For 2nd one, use this https://gamebanana.com/tools/5684
> Also, the flashed glow is not legit , u may get ow ban.

I think he means to added the "Flashed" option on "Chams", "Glow", "ESP".
