### ISSUE TITLE
nskinz

### ISSUE THREAD

**Issue by travispresk0** [danielkrupinski/Osiris#920]
How can I use/separate the nskinz code from here? Cause the main [nskinz code](https://github.com/namazso/nSkinz) is causing VAC kick

**Comment by rosesware** [comment]
Dude, use @danielkrupinski VAC Bypass Loader.

**Comment by SmakHvh** [comment]
Sorry but is the nskinz code the skinchanger in Osiris?

**Comment by hyperxpro** [comment]
Here you go: https://github.com/namazso/nSkinz

**Comment by travispresk0** [comment]
VAC bypass did the work

**Comment by flawnn** [comment]
> Dude, use @danielkrupinski VAC Bypass Loader.

Can I still play online tho?
