### ISSUE TITLE
[HELP] how to add Anti-aim chams ?

### ISSUE THREAD

**Issue by VeLocityYT** [danielkrupinski/Osiris#922]
the title said it.

**Comment by rosesware** [comment]
Coded. 😃

**Comment by VeLocityYT** [comment]
> 
> 
> Coding. smiley

"My Goodness Why Didn't I Think of That"

**Comment by Straightplus** [comment]
lul..........

**Comment by rosesware** [comment]
> > Coding. smiley
> 
> "My Goodness Why Didn't I Think of That"

What do you think people will said?

**Comment by Straightplus** [comment]
i agree ^
