### ISSUE TITLE
[HELP] Change Gui Default Color

### ISSUE THREAD

**Issue by sxckm** [danielkrupinski/Osiris#923]
Hey GitHub community, I'm pretty new to GitHub and i dont know that much about coding, so I would like to ask how I can change the Default Dark Theme that loads up automatically and change the colors.
Would be nice if someone could help :)

**Comment by Straightplus** [comment]
It is already dark theme from the start but if you want custom colors or a whole new them, you can just change these values to your liking :)
https://i.imgur.com/ZGG9QPZ.png

**Comment by Straightplus** [comment]
(Side note the values are in RGBA :))
