### ISSUE TITLE
Fast Stop (aka Auto Counter Strafe)

### ISSUE THREAD

**Issue by Deagle2k** [danielkrupinski/Osiris#926]
Can you please add a fast stop where you immediatly stop after letting go of a or d? would help thx!

**Comment by notgoodusename** [comment]
dont make 3 issues about 1 suggestion, you know u can edit them ?

**Comment by Deagle2k** [comment]
sry dude, I tried to comment it, didnt work, did it again, didnt work, then the last time i did it, it worked, but then all of them went through for some reason. IDK
