### ISSUE TITLE
[Enhancement] Fast Stop (aka Auto Counter Strafing)

### ISSUE THREAD

**Issue by Deagle2k** [danielkrupinski/Osiris#928]
Can you please add an automatic counter strafe? so like when you stop holding a or d, you stop immediately instead of sliding. THX!

**Comment by VeLocityYT** [comment]
you can use "Movement fix" in Misc Tab

**Comment by Deagle2k** [comment]
What does that do?

**Comment by tirziz** [comment]
> you can use "Movement fix" in Misc Tab
Its not fast stop , it is for anti aim

**Comment by Deagle2k** [comment]
yea thats what i thought

**Comment by linkupbiz** [comment]
void fastStop(CUserCmd* cmd)
    {
        Vector velocity = g::local_player->m_vecVelocity();
		QAngle direction;
		math::vector2angles(velocity, direction);
		float speed = velocity.Length2D();
 
		direction.yaw = cmd->viewangles.yaw - direction.yaw;
 
		Vector forward;
		math::angle2vectors(direction, forward);
 
		Vector right = (forward + 0.217812) * -speed;
		Vector left = (forward + -0.217812) * -speed;
 
		Vector move_forward = (forward + 0.217812) * -speed;
		Vector move_backward = (forward + -0.217812) * -speed;
 
		if (!(cmd->buttons & IN_MOVELEFT))
		{
			cmd->sidemove += +left.y;
		}
 
		if (!(cmd->buttons & IN_MOVERIGHT))
		{
			cmd->sidemove -= -right.y;
		} 
 
		if (!(cmd->buttons & IN_FORWARD))
		{
			if (cmd->buttons & IN_MOVELEFT || cmd->buttons & IN_MOVERIGHT || settings::misc::auto_strafe) //insert here your bool for auto strafe
				return;
 
			cmd->forwardmove += +move_forward.x;
		} 
 
		if (!(cmd->buttons & IN_BACK))
		{
			if (cmd->buttons & IN_MOVELEFT || cmd->buttons & IN_MOVERIGHT || settings::misc::auto_strafe) //insert here your bool for auto strafe
				return;
 
			cmd->forwardmove -= -move_backward.x;
		}
    }

**Comment by Deagle2k** [comment]
how do i put this into my game? sry if im stupid

**Comment by MinecraftGoodGame** [comment]
That's a copy paste, you will have to convert it for osiris

**Comment by Deagle2k** [comment]
I know that, but im too stupid to know how to do that D:

**Comment by linkupbiz** [comment]
I worked on it a bit this morning and fixed a couple of things on it, didn't have time to get m_vecVelocity, I got lots of college work to do and I don't think I'm going to be able to fix it completly but someone can deff pick up where I left ;) here is some of the code I fixed.

/*
{
    if (config.misc.fastStop) {
        const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());

        Vector velocity = g::local_player->m_vecVelocity();
		QAngle direction;
		math::vector2angles(velocity, direction);
		float speed = velocity.Length2D();

		direction.yaw = cmd->viewangles.yaw - direction.yaw;

		Vector forward;
		math::angle2vectors(direction, forward);

		Vector right = (forward + 0.217812) * -speed;
		Vector left = (forward + -0.217812) * -speed;

		Vector move_forward = (forward + 0.217812) * -speed;
		Vector move_backward = (forward + -0.217812) * -speed;

        if (config.misc.fastStop_mode == 1 || cconfig.misc.fastStop_mode == 3 && cconfig.misc.fastStop_mode != 2) // Only left & right or both
        {
            if (!(cmd->buttons & left))
            {
                cmd->sidemove += +left.y;
            }

            if (!(cmd->buttons & cmd-> IN_MOVERIGHT))
            {
                cmd->sidemove -= -right.y;
            }
        }

        if (config.misc.fastStop_mode == 2 || config.misc.fastStop_mode == 3 && config.misc.fastStop_mode != 1)  // Only forward & backward or both
        {
            if (!(cmd->buttons & cmd->IN_FORWARD))
            {
                if (cmd->buttons & cmd->IN_MOVELEFT || cmd->buttons & cmd->IN_MOVERIGHT || config.misc.autoStrafe)
                    return;

                cmd->forwardmove += +move_forward.x;
            }

            if (!(cmd->buttons & cmd->IN_BACK))
            {
                if (cmd->buttons & cmd->IN_MOVELEFT || cmd->buttons & cmd->IN_MOVERIGHT || config.misc.autoStrafe)
                    return;

                cmd->forwardmove -= -move_backward.x;
            }
        }
    }
}
*/

**Comment by xAkiraMiura** [comment]
osiris doesnt use qangles or the g namespace.

why are you pasting code and calling it your own?

**Comment by Deagle2k** [comment]
I dont know how to do that D:

**Comment by linkupbiz** [comment]
> osiris doesnt use qangles or the g namespace.
> 
> why are you pasting code and calling it your own?

Clearly didn't call it my own, as matter of fact this was pointed out up top by MinecraftGoodGame that it is a paste, and yes it has been noted that Osiris doesn't use qangles or g as a namespace and that's why I was working on it, so you made little to no sense my good friend, tragic, very tragic.

**Comment by Deagle2k** [comment]
I have no idea how to put this into my game, I know you need a 3rd party software right? But idk how to do any of that shit.

**Comment by thomas0aotian** [comment]
It's all pure skills u can do it on cheats.

**Comment by xAkiraMiura** [comment]
onetap v2 had it, can you stop spreading misinfomation? its gotten to a point where i cant say incompetence over malice.

**Comment by Deagle2k** [comment]
I have onetap v2, but i like osiris better, D:::
