### ISSUE TITLE
[BUGS & SUGGESTIONS]

### ISSUE THREAD

**Issue by effex1337** [danielkrupinski/Osiris#93]
Bugs :
RCS completely fked up[HIGH PRIORITY]
Knife changer issue flickering [medium]
Spec list/watermark font keeps changing size (flickering) [medium]

Suggestions :
BOX, Name, Health Esp [HIGH PRIORITY]
Nearest hitbox [HIGH PRIORITY]
Nade tracers [mid]
Add more skins(low)

**Comment by danielkrupinski** [comment]
Recoil control works inside an aimbot - it does not control your recoil when target is not found.

**Comment by effex1337** [comment]
Thanks it has been a great learning experience with this as a base. I am finally able to work comfortably with other bases as well.
