### ISSUE TITLE
Errors compiling new anti aim

### ISSUE THREAD

**Issue by Straightplus** [danielkrupinski/Osiris#930]
I get these errors if i try and compile the new antiaim??: 
https://i.imgur.com/hNarYDz.png
https://i.imgur.com/3rXZQDa.png

it works fine if i try and compile the old one.
Any help would be apreciated :)

AntiAim.cpp

`#include "AntiAim.h"
#include "../Interfaces.h"
#include "../SDK/Engine.h"
#include "../SDK/Entity.h"
#include "../SDK/EntityList.h"
#include "../SDK/NetworkChannel.h"
#include "../SDK/UserCmd.h"
#include "../Memory.h"
#include "../SDK/GlobalVars.h"
#include "Misc.h"
bool LbyBreaker()
{
	auto local_player = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
	static float NextUpdate = 0;
	float velocity = local_player->velocity().length();
	float time = memory.globalVars->serverTime();
	if (!(local_player->flags() & 1) || (!(local_player->isAlive()))) {
		return false;
	}
	if (velocity > 0.1f) {
		NextUpdate = time + 0.22f;
	}
	if (NextUpdate <= time)
	{
		NextUpdate = time + 1.1f;
		return true;
	}

	return false;
}
void AntiAim::run(UserCmd* cmd, const Vector& previousViewAngles, const Vector& currentViewAngles, bool& sendPacket) noexcept
{
	float desync = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer())->getMaxDesyncAngle();
	auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
	static float lastTime{ 0.0f };
	static bool invert;
	bool lby = LbyBreaker();
	int yaw = config.antiAim.yawangle;
	Vector oldangle = cmd->viewangles;
	if (config.antiAim.enabled) {
		if (GetAsyncKeyState(config.antiAim.invertkey) && memory.globalVars->realtime - lastTime > 0.5f) {
			invert = !invert;
			lastTime = memory.globalVars->realtime;
		}
		if (config.antiAim.pitch && cmd->viewangles.x == currentViewAngles.x) {
			cmd->viewangles.x = config.antiAim.pitchAngle;
		}
		if (config.antiAim.yaw) {
			if (lby) {
				sendPacket = false;
				invert ? cmd->viewangles.y += 118.f : cmd->viewangles.y -= 118.f;
				cmd->viewangles.y += 118.f;
			}
			else if (sendPacket) {
				cmd->viewangles.y += yaw;
			}
			else {
				invert ? cmd->viewangles.y += yaw + (desync * 2) : cmd->viewangles.y += yaw - (desync * 2);
			}
		}
	}
	cmd->viewangles.normalize();
	Misc::fixMovement(cmd, oldangle.y);

	cmd->viewangles.x = std::clamp(cmd->viewangles.x, -89.0f, 89.0f);
	cmd->viewangles.y = std::clamp(cmd->viewangles.y, -180.0f, 180.0f);
	cmd->viewangles.z = 0.0f;
}`

AntiAim.h

`#pragma once
#include "../SDK/Vector.h"
struct UserCmd;
struct Vector;

namespace AntiAim {
	void run(UserCmd* , const Vector& , const Vector& , bool& ) noexcept;
}

void CorrectMovement(Vector vOldAngles, UserCmd* pCmd, float fOldForward, float fOldSidemove);

Vector CalcAngle(Vector src, Vector dst);
void VectorAngles(const Vector& forward, QAngle& angles);
void AngleVectors(const QAngle& angles, Vector& forward);
void CorrectMovement(Vector vOldAngles, UserCmd* pCmd, float fOldForward, float fOldSidemove);
float VectorDistance(Vector v1, Vector v2);
int distance(Vector a, Vector b);`

**Comment by notgoodusename** [comment]
Thats the old one bro, check antiaim.cpp and antiaim.h from my repo

**Comment by Straightplus** [comment]
hmm still doesent seem to work?
https://www.dropbox.com/s/15zq84x7b8pozkh/G4lsCFH0Qa.mp4?dl=0

**Comment by notgoodusename** [comment]
check antiaim.h too

**Comment by Straightplus** [comment]
okay

**Comment by Straightplus** [comment]
nope just gives a load of errors https://i.imgur.com/0PiFOQM.png

**Comment by Straightplus** [comment]
the original error is from a fill called misc.obj?

**Comment by notgoodusename** [comment]
wait what other stuff do u have there

**Comment by Straightplus** [comment]
wdym

**Comment by notgoodusename** [comment]
like u cant get that many errors from 1 pull up request

**Comment by notgoodusename** [comment]
what did u add

**Comment by Straightplus** [comment]
can it be because of the vector.h file?

**Comment by notgoodusename** [comment]
did you pasted it from #739 ?

**Comment by Straightplus** [comment]
the vector.h?

**Comment by Straightplus** [comment]
or which file

**Comment by notgoodusename** [comment]
the whole project

**Comment by Straightplus** [comment]
yeah i think

**Comment by Straightplus** [comment]
the content of my antiaim.h is

#pragma once
#include "../SDK/Vector.h"
struct UserCmd;
struct Vector;

namespace AntiAim {
	void run(UserCmd* , const Vector& , const Vector& , bool& ) noexcept;
}

void CorrectMovement(Vector vOldAngles, UserCmd* pCmd, float fOldForward, float fOldSidemove);

Vector CalcAngle(Vector src, Vector dst);
void VectorAngles(const Vector& forward, QAngle& angles);
void AngleVectors(const QAngle& angles, Vector& forward);
void CorrectMovement(Vector vOldAngles, UserCmd* pCmd, float fOldForward, float fOldSidemove);
float VectorDistance(Vector v1, Vector v2);
int distance(Vector a, Vector b);

if that matters

**Comment by notgoodusename** [comment]
it TOTALLY MATTERS, you should have this
#pragma once

struct UserCmd;
struct Vector;

namespace AntiAim {
	void run(UserCmd*, const Vector&, const Vector&, bool&) noexcept;
}

**Comment by Straightplus** [comment]
works i think but now the autoblocker needs the Vector CalcAngle(Vector src, Vector dst); and int distance(Vector a, Vector b);

https://i.imgur.com/XhJrQJa.png

**Comment by Straightplus** [comment]
so do i just keep those?

**Comment by notgoodusename** [comment]
i will redo blockbot then
keep those if you want

**Comment by Straightplus** [comment]
these*

**Comment by notgoodusename** [comment]
paste it in misc as the same file as blockbot

**Comment by Straightplus** [comment]
okay nice :D 
thanks for the help man really appreciate it

**Comment by Straightplus** [comment]
does not work?
https://i.imgur.com/V4Pf9Ao.png

**Comment by notgoodusename** [comment]
just dont use it

**Comment by Straightplus** [comment]
okay

**Comment by Straightplus** [comment]
okay works like a charm now :DDDDD

**Comment by Straightplus** [comment]
thanks man really good help :D

**Comment by Straightplus** [comment]
<3333333
