### ISSUE TITLE
[Issue] Unsuccessful injection.

### ISSUE THREAD

**Issue by AbdallahMehiz** [danielkrupinski/Osiris#932]
Soo i use Randoinjector for now, i just was using the cheat for a while with no problem, it injects correctly and everything. i was on github and i downloaded the Vac-Bypass-Loader from daniel's repository wich worked for me, steam started correctly and i was able to play some csgo but i couldn't inject osiris while steam was opened with the vac-bypass-loader. i restarted steam and the cheat injectoed with no issues.
how can i fix this

**Comment by embern33** [comment]
Just use process hacker, RandoInjector doesn't work half the time.

**Comment by danielkrupinski** [comment]
Run injector as Administrator 😀
