### ISSUE TITLE
Name Font

### ISSUE THREAD

**Issue by time21** [danielkrupinski/Osiris#935]
how to change Name font with custom font , add anti aliasing and dropshadow.

**Comment by time21** [comment]
sad i dont even know how to tag label question

**Comment by Straightplus** [comment]
the fonts for esp etc is gotten from these lines of code i think
https://i.imgur.com/fmUEymo.png

**Comment by Straightplus** [comment]
works for me :)

**Comment by time21** [comment]
so how do i change it 
![image](https://user-images.githubusercontent.com/43808799/71638745-d5b1b380-2c9a-11ea-9c06-d433de04ed18.png)

**Comment by Straightplus** [comment]
fonts.[font from local pc] = io.Fonts->AddFontFromFileTTF((path / "insert font file path").string().c_str(), font bigness.decimal f, nullptr, ranges);

**Comment by Straightplus** [comment]
look through that line of code and set in the necesary info

**Comment by Straightplus** [comment]
:D And happy new years :D

**Comment by time21** [comment]
Thanks

**Comment by Straightplus** [comment]
sure :)
do you have discord?

**Comment by time21** [comment]
ihatetatchai#2489

**Comment by xAkiraMiura** [comment]
you could add a text box that takes a font name, appends ".ttf" to it and loads it
dont ask me on how to do it though.
