### ISSUE TITLE
[Help] Anyone know what is "killshot" in aimbot section ?

### ISSUE THREAD

**Issue by VeLocityYT** [danielkrupinski/Osiris#936]

**Comment by woah1337** [comment]
https://cdn.otaku.ooo/5klur.png

**Comment by anonymouschicken1111** [comment]
Literally so many damn duplicates

**Comment by AbdallahMehiz** [comment]
Kill shot if activated, the aimbot will only shoot if the next shot will 100% result in the enemy death

**Comment by Straightplus** [comment]
ahahhah changed the name LMAO

**Comment by rosesware** [comment]
Sorry buddy, I'm kinda rude but, did you even read the feature name?

**Comment by xAkiraMiura** [comment]
I don't know if its possible with ImGui but whenever you hover over something a description should pop up so issues like this stop. (probably wouldnt stop even with it implemented.)

**Comment by linkupbiz** [comment]
Kill shot would be better if it was a bind imo.

**Comment by Straightplus** [comment]
@rosesware who me?
