### ISSUE TITLE
CustomHitmarkerSoundsCode

### ISSUE THREAD

**Issue by giangero1** [danielkrupinski/Osiris#939]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/180039-hitmarker-hitsound.html

i know i already opened an issue for this but it's old so i made a new one and i found code for it maybe someone could help and do a pull request :)

**Comment by xAkiraMiura** [comment]
we have a hit marker on a different fork, it hasnt been merged yet.

**Comment by KernCS** [comment]
#824

**Comment by ZerGo0** [comment]
> https://www.unknowncheats.me/forum/counterstrike-global-offensive/180039-hitmarker-hitsound.html
> 
> i know i already opened an issue for this but it's old so i made a new one and i found code for it maybe someone could help and do a pull request :)

Current hit sounds use the ingame command play which doesn't allow you to play custom sounds. However seems like it is extremely easy to add custom ones, I will check it out tomorrow and add a pull if it works.

**Comment by xAkiraMiura** [comment]
-> **PlaySoundAsync** <-

**Comment by Oly-UK** [comment]
#1434
