### ISSUE TITLE
Watermark / spectator list font flickers

### ISSUE THREAD

**Issue by effexcs** [danielkrupinski/Osiris#94]
The watermark/spectator list's font size increases on shooting / mouse1.
Or maybe even the font changes

**Comment by danielkrupinski** [comment]
What locale do you use?

**Comment by effexcs** [comment]
I don't really know
It's just compiled as a default version.

**Comment by danielkrupinski** [comment]
I mean what language you have in game?

**Comment by effexcs** [comment]
Default english

**Comment by effexcs** [comment]
And while holding the bomb is horrible
When water mark isturned on in the start menu, some random unicode characters show up.

**Comment by Havoccboi** [comment]
Hi, just a question is this cheat still undetected?

**Comment by didisko33** [comment]
I have same issues here.

**Comment by danielkrupinski** [comment]
Should be fixed now. Please test again.

**Comment by effexcs** [comment]
It's working fine thanks.
