### ISSUE TITLE
[HELP] Severe fps drop on injection and afterward

### ISSUE THREAD

**Issue by Straightplus** [danielkrupinski/Osiris#940]
As stated above i have been getting massive fps drops on injection like injection alone, meaning i dont have any features on, and i still loose like 100 fps just from that, so my question is what causes this? (pls no tosic men) (normaly i run about 200)

Thanks, Straight :)

**Comment by Straightplus** [comment]
*gramma

**Comment by danielkrupinski** [comment]
Do you lose fps in main menu too?

**Comment by danielkrupinski** [comment]
You can try removing those two lines https://github.com/danielkrupinski/Osiris/blob/51217a04a137398bf28e282974a0430de2cf1128/Osiris/Hooks.cpp#L432-L433

**Comment by Straightplus** [comment]
not in main menu no

**Comment by Straightplus** [comment]
its rlly weird

**Comment by Straightplus** [comment]
cause i tried making a experiment on inferno casual

**Comment by Straightplus** [comment]
and when i was standing on highway in the houses when i turned to the outside i was getting fps drops but when i looked away it was gone

**Comment by Straightplus** [comment]
hmm doesent seem like it helped much?

**Comment by rosesware** [comment]
I think it's a CS problem, I see a lot of people saying the same thing (without cheats) and my fps is dropping to.

**Comment by thomas0aotian** [comment]
Try to do a full csgo reset. starting with deleting all .vpk files and do a game's integrity check. And then you will be just fine. Fps drops happens possibly because too many different cheats are being used in csgo and these might mess up ur game. Always do a  integrity check once a while

**Comment by Straightplus** [comment]
okay thanks :) ill try that

**Comment by xAkiraMiura** [comment]
none of that would help, the game doesnt just load paks for no reason. 
cheats cant mess up the game because modifying files is detected.
please, stop saying random shit if you dont know whats actually going on, it really is counter-productive to the actual problem.

what you could actually do:
* use the AX and AX2 instruction if your CPU supports it. (if your cpu doesnt then make sure they are off, it could hurt performance or cause crashes)
* find what the problem is (i.g, low ram, high gpu usage, high cpu usage.) it would help find what the issue is.

**Comment by Straightplus** [comment]
I just dont think its a pc problem because if  i play a high requirement game like the new mw or rainbow 6 siege its good both with discord and chrome open?

**Comment by Straightplus** [comment]
its only with cs this is going on so idk if its a problem with cs or with os

**Comment by Straightplus** [comment]
If you want me to show you the problem personaly add me on discord: B1g bruh#8336

**Comment by Straightplus** [comment]
and sorry i have tried researching what a AX instruction is but i couldent find anything what is it exactly?
@xAkiraMiura

**Comment by xAkiraMiura** [comment]
Project > Osiris Properties... > Configuration Properties > C/C++ > Code Generation > Enable Enhanced Instruction Set
default is /arch:SSE2 (Straming SIMD Extensions 2)
set it to /arch:AVX2 (Advanced Vector Extensions 2)

**Comment by Straightplus** [comment]
hmmm idfk know dude cause it seems like it gives me 10-20 fps more but still when i go out of a house my fps drops to 55-65 but thanks :)

**Comment by Straightplus** [comment]
@xAkiraMiura

**Comment by xAkiraMiura** [comment]
thats just how source does optimization
you only render whats in the connected visleaves to your current visleaf
also disabling the option called "Disable model occlusion" can help performance because you wont be rendering the models.
^ you will have to rely on ESP instead of chams though.

**Comment by Straightplus** [comment]
i dont rlly use chams so its fine ^^

**Comment by Straightplus** [comment]
and thanks ill try

**Comment by Straightplus** [comment]
didnt work sadly

**Comment by Straightplus** [comment]
solved

**Comment by danielkrupinski** [comment]
How did you solve it?

**Comment by Straightplus** [comment]
Optimized some of the code
