### ISSUE TITLE
Skinchanger animation failure 

### ISSUE THREAD

**Issue by thomas0aotian** [danielkrupinski/Osiris#941]
- So i had these problems when using os on my main acc with knives. When i inject os even if I didn't use skinchanger or anything else my knife-switch animation will definitely broke.
- Like if you switch between knife and weapons the animation will disappear.
- I think it's something inside the hook where it's default animation change is the default knife instead of my original knife.
- I wish we can have a check on that so it will auto detect the knife u r using rn instead of default knife as a constant.

**Comment by Straightplus** [comment]
i dont have this problem it might be because of the sequence of the knife

**Comment by Straightplus** [comment]
try find the matching code in netvars.cpp and paste this

static int get_new_animation(const uint32_t model, const int sequence) noexcept
{
    enum Sequence
    {
        SEQUENCE_DEFAULT_DRAW = 0,
        SEQUENCE_DEFAULT_IDLE1 = 1,
        SEQUENCE_DEFAULT_IDLE2 = 2,
        SEQUENCE_DEFAULT_LIGHT_MISS1 = 3,
        SEQUENCE_DEFAULT_LIGHT_MISS2 = 4,
        SEQUENCE_DEFAULT_HEAVY_MISS1 = 9,
        SEQUENCE_DEFAULT_HEAVY_HIT1 = 10,
        SEQUENCE_DEFAULT_HEAVY_BACKSTAB = 11,
        SEQUENCE_DEFAULT_LOOKAT01 = 12,

        SEQUENCE_BUTTERFLY_DRAW = 0,
        SEQUENCE_BUTTERFLY_DRAW2 = 1,
        SEQUENCE_BUTTERFLY_LOOKAT01 = 13,
        SEQUENCE_BUTTERFLY_LOOKAT03 = 15,

        SEQUENCE_FALCHION_IDLE1 = 1,
        SEQUENCE_FALCHION_HEAVY_MISS1 = 8,
        SEQUENCE_FALCHION_HEAVY_MISS1_NOFLIP = 9,
        SEQUENCE_FALCHION_LOOKAT01 = 12,
        SEQUENCE_FALCHION_LOOKAT02 = 13,

        SEQUENCE_DAGGERS_IDLE1 = 1,
        SEQUENCE_DAGGERS_LIGHT_MISS1 = 2,
        SEQUENCE_DAGGERS_LIGHT_MISS5 = 6,
        SEQUENCE_DAGGERS_HEAVY_MISS2 = 11,
        SEQUENCE_DAGGERS_HEAVY_MISS1 = 12,

        SEQUENCE_BOWIE_IDLE1 = 1,
    };

    // Hashes for best performance.
    switch (model) {
    case fnv::hash("models/weapons/v_knife_butterfly.mdl"):
    {
        switch (sequence)
        {
        case SEQUENCE_DEFAULT_DRAW:
            return random(SEQUENCE_BUTTERFLY_DRAW, SEQUENCE_BUTTERFLY_DRAW2);
        case SEQUENCE_DEFAULT_LOOKAT01:
            return random(SEQUENCE_BUTTERFLY_LOOKAT01, SEQUENCE_BUTTERFLY_LOOKAT03);
        default:
            return sequence + 1;
        }
    }

    case fnv::hash("models/weapons/v_knife_falchion_advanced.mdl"):
    {
        switch (sequence)
        {
        case SEQUENCE_DEFAULT_IDLE2:
            return SEQUENCE_FALCHION_IDLE1;
        case SEQUENCE_DEFAULT_HEAVY_MISS1:
            return random(SEQUENCE_FALCHION_HEAVY_MISS1, SEQUENCE_FALCHION_HEAVY_MISS1_NOFLIP);
        case SEQUENCE_DEFAULT_LOOKAT01:
            return random(SEQUENCE_FALCHION_LOOKAT01, SEQUENCE_FALCHION_LOOKAT02);
        case SEQUENCE_DEFAULT_DRAW:
        case SEQUENCE_DEFAULT_IDLE1:
            return sequence;
        default:
            return sequence - 1;
        }
    }

    case fnv::hash("models/weapons/v_knife_push.mdl"):
    {
        switch (sequence)
        {
        case SEQUENCE_DEFAULT_IDLE2:
            return SEQUENCE_DAGGERS_IDLE1;
        case SEQUENCE_DEFAULT_LIGHT_MISS1:
        case SEQUENCE_DEFAULT_LIGHT_MISS2:
            return random(SEQUENCE_DAGGERS_LIGHT_MISS1, SEQUENCE_DAGGERS_LIGHT_MISS5);
        case SEQUENCE_DEFAULT_HEAVY_MISS1:
            return random(SEQUENCE_DAGGERS_HEAVY_MISS2, SEQUENCE_DAGGERS_HEAVY_MISS1);
        case SEQUENCE_DEFAULT_HEAVY_HIT1:
        case SEQUENCE_DEFAULT_HEAVY_BACKSTAB:
        case SEQUENCE_DEFAULT_LOOKAT01:
            return sequence + 3;
        case SEQUENCE_DEFAULT_DRAW:
        case SEQUENCE_DEFAULT_IDLE1:
            return sequence;
        default:
            return sequence + 2;
        }
    }

    case fnv::hash("models/weapons/v_knife_survival_bowie.mdl"):
    {
        switch (sequence)
        {
        case SEQUENCE_DEFAULT_DRAW:
        case SEQUENCE_DEFAULT_IDLE1:
            return sequence;
        case SEQUENCE_DEFAULT_IDLE2:
            return SEQUENCE_BOWIE_IDLE1;
        default:
            return sequence - 1;
        }
    }

    case fnv::hash("models/weapons/v_knife_ursus.mdl"):
    case fnv::hash("models/weapons/v_knife_skeleton.mdl"):
    case fnv::hash("models/weapons/v_knife_cord.mdl"):
    case fnv::hash("models/weapons/v_knife_outdoor.mdl"):
    case fnv::hash("models/weapons/v_knife_canis.mdl"):
    {
        switch (sequence)
        {
        case SEQUENCE_DEFAULT_DRAW:
            return random(SEQUENCE_BUTTERFLY_DRAW, SEQUENCE_BUTTERFLY_DRAW2);
        case SEQUENCE_DEFAULT_LOOKAT01:
            return random(SEQUENCE_BUTTERFLY_LOOKAT01, 14);
        default:
            return sequence + 1;
        }
    }

    case fnv::hash("models/weapons/v_knife_stiletto.mdl"):
    {
        switch (sequence)
        {
        case SEQUENCE_DEFAULT_LOOKAT01:
            return random(12, 13);
        }
    }

    case fnv::hash("models/weapons/v_knife_widowmaker.mdl"):
    {
        switch (sequence)
        {
        case SEQUENCE_DEFAULT_LOOKAT01:
            return random(14, 15);
        }
    }
    default:
        return sequence;
    }
}

**Comment by xAkiraMiura** [comment]
@thomas0aotian you make no sense. 
also why is all of that inside of bullets, it is very clearly not a list?

@Straightplus why does only 80% of the code show up in the code block, the rest of it is normal text.

**Comment by Straightplus** [comment]
i dont rlly know tbh its kinda fucked (i only c+p the code lol)

**Comment by thomas0aotian** [comment]
> @thomas0aotian you make no sense.
> also why is all of that inside of bullets, it is very clearly not a list?
> 
> @Straightplus why does only 80% of the code show up in the code block, the rest of it is normal text.

sry my description is only readable to anyone that has IQ of 50 or above.
It's my bad of trying to let someone who has the IQ of 20 to understand what I said.

**Comment by thomas0aotian** [comment]
> try find the matching code in netvars.cpp and paste this
> 
> static int get_new_animation(const uint32_t model, const int sequence) noexcept
> {
> enum Sequence
> {
> SEQUENCE_DEFAULT_DRAW = 0,
> SEQUENCE_DEFAULT_IDLE1 = 1,
> SEQUENCE_DEFAULT_IDLE2 = 2,
> SEQUENCE_DEFAULT_LIGHT_MISS1 = 3,
> SEQUENCE_DEFAULT_LIGHT_MISS2 = 4,
> SEQUENCE_DEFAULT_HEAVY_MISS1 = 9,
> SEQUENCE_DEFAULT_HEAVY_HIT1 = 10,
> SEQUENCE_DEFAULT_HEAVY_BACKSTAB = 11,
> SEQUENCE_DEFAULT_LOOKAT01 = 12,
> 
> ```
>     SEQUENCE_BUTTERFLY_DRAW = 0,
>     SEQUENCE_BUTTERFLY_DRAW2 = 1,
>     SEQUENCE_BUTTERFLY_LOOKAT01 = 13,
>     SEQUENCE_BUTTERFLY_LOOKAT03 = 15,
> 
>     SEQUENCE_FALCHION_IDLE1 = 1,
>     SEQUENCE_FALCHION_HEAVY_MISS1 = 8,
>     SEQUENCE_FALCHION_HEAVY_MISS1_NOFLIP = 9,
>     SEQUENCE_FALCHION_LOOKAT01 = 12,
>     SEQUENCE_FALCHION_LOOKAT02 = 13,
> 
>     SEQUENCE_DAGGERS_IDLE1 = 1,
>     SEQUENCE_DAGGERS_LIGHT_MISS1 = 2,
>     SEQUENCE_DAGGERS_LIGHT_MISS5 = 6,
>     SEQUENCE_DAGGERS_HEAVY_MISS2 = 11,
>     SEQUENCE_DAGGERS_HEAVY_MISS1 = 12,
> 
>     SEQUENCE_BOWIE_IDLE1 = 1,
> };
> 
> // Hashes for best performance.
> switch (model) {
> case fnv::hash("models/weapons/v_knife_butterfly.mdl"):
> {
>     switch (sequence)
>     {
>     case SEQUENCE_DEFAULT_DRAW:
>         return random(SEQUENCE_BUTTERFLY_DRAW, SEQUENCE_BUTTERFLY_DRAW2);
>     case SEQUENCE_DEFAULT_LOOKAT01:
>         return random(SEQUENCE_BUTTERFLY_LOOKAT01, SEQUENCE_BUTTERFLY_LOOKAT03);
>     default:
>         return sequence + 1;
>     }
> }
> 
> case fnv::hash("models/weapons/v_knife_falchion_advanced.mdl"):
> {
>     switch (sequence)
>     {
>     case SEQUENCE_DEFAULT_IDLE2:
>         return SEQUENCE_FALCHION_IDLE1;
>     case SEQUENCE_DEFAULT_HEAVY_MISS1:
>         return random(SEQUENCE_FALCHION_HEAVY_MISS1, SEQUENCE_FALCHION_HEAVY_MISS1_NOFLIP);
>     case SEQUENCE_DEFAULT_LOOKAT01:
>         return random(SEQUENCE_FALCHION_LOOKAT01, SEQUENCE_FALCHION_LOOKAT02);
>     case SEQUENCE_DEFAULT_DRAW:
>     case SEQUENCE_DEFAULT_IDLE1:
>         return sequence;
>     default:
>         return sequence - 1;
>     }
> }
> 
> case fnv::hash("models/weapons/v_knife_push.mdl"):
> {
>     switch (sequence)
>     {
>     case SEQUENCE_DEFAULT_IDLE2:
>         return SEQUENCE_DAGGERS_IDLE1;
>     case SEQUENCE_DEFAULT_LIGHT_MISS1:
>     case SEQUENCE_DEFAULT_LIGHT_MISS2:
>         return random(SEQUENCE_DAGGERS_LIGHT_MISS1, SEQUENCE_DAGGERS_LIGHT_MISS5);
>     case SEQUENCE_DEFAULT_HEAVY_MISS1:
>         return random(SEQUENCE_DAGGERS_HEAVY_MISS2, SEQUENCE_DAGGERS_HEAVY_MISS1);
>     case SEQUENCE_DEFAULT_HEAVY_HIT1:
>     case SEQUENCE_DEFAULT_HEAVY_BACKSTAB:
>     case SEQUENCE_DEFAULT_LOOKAT01:
>         return sequence + 3;
>     case SEQUENCE_DEFAULT_DRAW:
>     case SEQUENCE_DEFAULT_IDLE1:
>         return sequence;
>     default:
>         return sequence + 2;
>     }
> }
> 
> case fnv::hash("models/weapons/v_knife_survival_bowie.mdl"):
> {
>     switch (sequence)
>     {
>     case SEQUENCE_DEFAULT_DRAW:
>     case SEQUENCE_DEFAULT_IDLE1:
>         return sequence;
>     case SEQUENCE_DEFAULT_IDLE2:
>         return SEQUENCE_BOWIE_IDLE1;
>     default:
>         return sequence - 1;
>     }
> }
> 
> case fnv::hash("models/weapons/v_knife_ursus.mdl"):
> case fnv::hash("models/weapons/v_knife_skeleton.mdl"):
> case fnv::hash("models/weapons/v_knife_cord.mdl"):
> case fnv::hash("models/weapons/v_knife_outdoor.mdl"):
> case fnv::hash("models/weapons/v_knife_canis.mdl"):
> {
>     switch (sequence)
>     {
>     case SEQUENCE_DEFAULT_DRAW:
>         return random(SEQUENCE_BUTTERFLY_DRAW, SEQUENCE_BUTTERFLY_DRAW2);
>     case SEQUENCE_DEFAULT_LOOKAT01:
>         return random(SEQUENCE_BUTTERFLY_LOOKAT01, 14);
>     default:
>         return sequence + 1;
>     }
> }
> 
> case fnv::hash("models/weapons/v_knife_stiletto.mdl"):
> {
>     switch (sequence)
>     {
>     case SEQUENCE_DEFAULT_LOOKAT01:
>         return random(12, 13);
>     }
> }
> 
> case fnv::hash("models/weapons/v_knife_widowmaker.mdl"):
> {
>     switch (sequence)
>     {
>     case SEQUENCE_DEFAULT_LOOKAT01:
>         return random(14, 15);
>     }
> }
> default:
>     return sequence;
> }
> ```
> 
> }

the code here is the same as the original codes. And I'm using butterfly knife from my inventory and sometime the knife-switching animation will disappear.

**Comment by Straightplus** [comment]
Oh okay so when you use a knife ingame insteqd of the skinchanger you need to turn off the skinchanger
Or am i not understanding you right?

**Comment by thomas0aotian** [comment]
@Straightplus even if I didn't have skinchanger on, my knife switching animation will still disappear. I think this happened as soon as the cheat has been hooked in the game.

**Comment by Straightplus** [comment]
hmm idk when i had the same problem it was just because my netvars/sequence for the specefic knife wasnt there.
