### ISSUE TITLE
[BUG] Default config doesn't load.

### ISSUE THREAD

**Issue by xAkiraMiura** [danielkrupinski/Osiris#942]
In Osiris.cpp, a config object is initiated with the value of "Osiris". 
This implies that any config named "Osiris" will be loaded by default.
However, the config is not loaded at injection.

**Comment by MinecraftGoodGame** [comment]
Doesn't that mean that configs are stored in a folder called "Osiris"?

**Comment by xAkiraMiura** [comment]
I checked the source and it does refer to the folder instead of a config.
