### ISSUE TITLE
Chams are black

### ISSUE THREAD

**Issue by igothxps** [danielkrupinski/Osiris#943]
I have the files and everything they just show up black (settings on high as well)

    std::ofstream("csgo\materials\skeetchams.vmt") << R"#("VertexLitGeneric"
      "$basetexture" "vgui/white_additive"
      "$ignorez" "0"
      "$additive" "0"
      "$envmap"  "models/effects/cube_white"
      "$normalmapalphaenvmapmask" "1"
      "$envmaptint" "[0 0.26 1]"
      "$envmapfresnel" "1"
      "$envmapfresnelminmaxexp" "[0 1 2]"

      "$envmapcontrast" "1"
      "$nofog" "1"
      "$model" "1"
      "$nocull" "0"
      "$selfillum" "1"
      "$halflambert" "1"
      "$znearer" "0"
      "$flat" "1" 
}
)#";

    std::ofstream("csgo\\materials\\regular_reflective.vmt") << R"#("VertexLitGeneric" {
      "$basetexture" "vgui/white_additive"
      "$ignorez" "0"
      "$envmap" "env_cubemap"
      "$normalmapalphaenvmapmask" "1"
      "$envmapcontrast"  "1"
      "$nofog" "1"
      "$model" "1"
      "$nocull" "0"
      "$selfillum" "1"
      "$halflambert" "1"
      "$znearer" "0"
      "$flat" "1";

**Comment by igothxps** [comment]
managed to fix the skeet one metallic is still black

**Comment by littlehurensohn** [comment]
Same problem. +up

**Comment by xAkiraMiura** [comment]
did you modify osiris in any way? try a fresh clone of the repo and rebuild it.

**Comment by danielkrupinski** [comment]
`csgo\materials\skeetchams.vmt` path is invalid, you should use either double backslashes ('\\\\') or single forward slashes ('/')
Another posibility is typo in your material file. In that case in-game console should output error.

**Comment by igothxps** [comment]
@danielkrupinski thnx it worked

**Comment by igothxps** [comment]
@danielkrupinski so it works for 1 at a time heres my updated code the reflective works but the skeet doesnt before when i only had the skeet they worked

    std::ofstream("csgo/materials/skeetchams.vmt") << R"#("VertexLitGeneric"
{
      "$basetexture" "vgui/white_additive"
      "$ignorez" "0"
      "$additive" "0"
      "$envmap"  "models/effects/cube_white"
      "$normalmapalphaenvmapmask" "1"
      "$envmaptint" "[0 0.26 1]"
      "$envmapfresnel" "1"
      "$envmapfresnelminmaxexp" "[0 1 2]"

      "$envmapcontrast" "1"
      "$nofog" "1"
      "$model" "1"
      "$nocull" "0"
      "$selfillum" "1"
      "$halflambert" "1"
      "$znearer" "0"
      "$flat" "1" 


)#";
    std::ofstream("csgo/materials/regular_reflective.vmt") << R"#("VertexLitGeneric" {
      "$basetexture" "vgui/white_additive"
      "$ignorez" "0"
      "$envmap" "env_cubemap"
      "$normalmapalphaenvmapmask" "1"
      "$envmapcontrast"  "1"
      "$nofog" "1"
      "$model" "1"
      "$nocull" "0"
      "$selfillum" "1"
      "$halflambert" "1"
      "$znearer" "0"
      "$flat" "1" 
}
)#";

**Comment by igothxps** [comment]
@danielkrupinski KeyValues Error: RecursiveLoadFromBuffer:  got NULL key in file materials/skeetchams.vmt line 21 thats what my game spits out

**Comment by igothxps** [comment]
@danielkrupinski nvm i fixed my issue for any one else having that make sure theres no space at the bottom creating extra lines in the vmt

**Comment by xAkiraMiura** [comment]
**could you not mention daniel in every single comment?**
after he adds a comment he gets automatically subscribed to the issue and sees everything so all you are doing is being annoying
