### ISSUE TITLE
[Suggestion] Ragdoll chams

### ISSUE THREAD

**Issue by Straightplus** [danielkrupinski/Osiris#944]
As title says^^

**Comment by giangero1** [comment]
@Straightplus i'v been using ragdoll glow if that's okay with you try it pretty cool when using reverse ragdoll gravity, not sure if there is ragdoll chams but if ur suggesting it u already checked.

**Comment by Straightplus** [comment]
Yeah

**Comment by olywxm** [comment]
yeah release dead glow that'd be epic

**Comment by rosesware** [comment]
> yeah release dead glow that'd be epic

Already have.

**Comment by suddenlybydl0** [comment]
> > yeah release dead glow that'd be epic
> 
> Already have.

In osiris there is only glow on the dead, not chams
