### ISSUE TITLE
What visuals are needed to run Osiris?

### ISSUE THREAD

**Issue by AuguxX** [danielkrupinski/Osiris#946]
So to compile the cheat i downloaded vs19 and every c++ package and it worked for me when injecting but a friend of mine installed the same packages but hes not able to inject the cheat...

**Comment by xAkiraMiura** [comment]
compile as release x86 mode, not debug mode. release mode makes it so you dont need all of the debug runtimes.
also how did you download every c++? do you mean every vc++ package or did you download a seperate compiler for no reason?

**Comment by AuguxX** [comment]
the ones that are listed on vsinstaller, thanks for helping!
