### ISSUE TITLE
[Improvement] Aspect ratio code

### ISSUE THREAD

**Issue by Straightplus** [danielkrupinski/Osiris#948]
just c+p

misc.cpp
void Misc::aspectratio() noexcept
{
    static auto aspectratio = interfaces.cvar->findVar("r_aspectratio");
    if (aspectratio)
    {
        aspectratio->setValue(config.misc.aspectratio);
    }
}

misc.h
    void aspectratio() noexcept;

hooks.cpp
    Misc::aspectratio();
![devenv_vjyvPycflU](https://user-images.githubusercontent.com/39915461/71785081-bf3d8c00-2ffb-11ea-994b-0a93d1722647.png)

config.cpp

if (miscJson.isMember("Aspect Ratio")) misc.aspectratio = miscJson["Aspect Ratio"].asFloat();
		miscJson["Aspect Ratio"] = misc.aspectratio;

config.h
		float aspectratio{ 0 };

gui.cpp
		ImGui::SliderFloat("Aspect Ratio", &config.misc.aspectratio, 0.0f, 5.0f, "%.2f");

works like a charm just use common sense and c+p

**Comment by CerberusGame** [comment]
Please share you left hand code :)

**Comment by xAkiraMiura** [comment]
please make a seperate fork and send a git clone command instead,
pasting code into files is prone to failure and takes much longer

template: `git clone https://github.com/USERNAME/REPO`
example: `git clone https://github.com/danielkrupinski/Osiris`

**Comment by Straightplus** [comment]
What are you on about mate?

**Comment by xAkiraMiura** [comment]
manually having to edit many files is very slow and error prone, just fork the project and commit the changes, that way we would be able to clone it and merge it with master.

**Comment by Straightplus** [comment]
did
