### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by tacticalNukes** [danielkrupinski/Osiris#95]
My csgo crashes when I try to inject the cheat? I haven't edited anything except that I had to change SDK version "10.0.17134.0" but don't think it would make a difference?

**Comment by effexcs** [comment]
That shouldnt make a difference

**Comment by danielkrupinski** [comment]
Could you please attach debugger and post output?

**Comment by danielkrupinski** [comment]
Remove configuration file if present.

**Comment by tacticalNukes** [comment]
I am validating files, this will make the config go away right? and if not where would I find it

**Comment by tacticalNukes** [comment]
Validating didn't work

**Comment by tacticalNukes** [comment]
Nevermind found the config

**Comment by gokdenizq** [comment]
I also had same issue but I can't find the config file can you give me the path to the config file?

**Comment by danielkrupinski** [comment]
@gokdenizq Documents/Osiris
