### ISSUE TITLE
Best dll injector?

### ISSUE THREAD

**Issue by 1-Xycro** [danielkrupinski/Osiris#950]
Can anyone recommend any dll injector for osiris which is undetected and doesnt require any coding?

**Comment by Kraken69** [comment]
Can I use xenia injector or process hacker?

**Comment by Kraken69** [comment]
Xenos*

**Comment by ifoverload** [comment]
@Kraken69 use GHInjector, Manualmap
close this please

**Comment by Kraken69** [comment]
Can I use process hacker?

**Comment by xAkiraMiura** [comment]
**This is not related to Osiris**

You can use daniel's injector, i don't think many people use it so its probably not detected
Xenos is most certainly detected, I always get VAC Authed when I try to use it.
Best solution: make your own injector. This is unrealistic unless you dedicate yourself to windows to learn injection methods (or you reverse malware for their injection methods).

**Comment by nucreac** [comment]
I agree with xAkiraMiura, making your injector is always been the best solution for injector. I've made my own and used it not only on CSGO but TF2 and L4D2 as well. And still, no VAC.
