### ISSUE TITLE
Problems with Drawmodel function

### ISSUE THREAD

**Issue by notgoodusename** [danielkrupinski/Osiris#952]
so i use this function
`    constexpr int DrawModel(int flags, int alpha) noexcept
    {
        return callVirtualMethod<int, int, int>(this + 4, 9, flags, alpha);
    }`
and it gives me a constant crash.
note: i hooked sceneend

**Comment by xAkiraMiura** [comment]
isnt it already hooked or is SceneEnd different from EndScene?

**Comment by notgoodusename** [comment]
> isnt it already hooked or is SceneEnd different from EndScene?

endscene is different from sceneend(sceneend is the 9th function of renderview)
