### ISSUE TITLE
Auto Edge Jump Feature.

### ISSUE THREAD

**Issue by EcoNyne** [danielkrupinski/Osiris#954]
Can you please add this? This would be a great feature especially for legit cheating. Thanks! (I tried to but I know nothing about coding so I just stopped doing it when I got a lot of errors) Hope you understand. Thanks!

**Comment by xAkiraMiura** [comment]
#938 #859 #773 #456

**Comment by woah1337** [comment]
ghetto af edgejump since there are like 5 issues asking for it:
`void Misc::edgeJump(UserCmd* cmd) noexcept
{
	if (GetAsyncKeyState('V')) {
		const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer());
		if (localPlayer->moveType() == MoveType::LADDER) return;
		Vector start, end;
		start = localPlayer->origin();
		end = start;
		end.z -= 32;
		Trace trace;
		Ray ray(start, end);
		TraceFilter filter(localPlayer);
		interfaces.engineTrace->traceRay(ray, MASK_PLAYERSOLID_BRUSHONLY, filter, trace);
		if (trace.fraction == 1.0f) cmd->buttons |= UserCmd::IN_JUMP;
	}
}`
note: this is not the proper way to do it. the reason im sharing it is because i don't use it anymore since im doing it properly with engine prediction now.
ready to c+p btw

**Comment by daisuki333** [comment]
> #938 #859 #773 #456

Auto Edge Jump and Auto Jump-Bug is different... just saying...

**Comment by agshaidun** [comment]
> 
> 
> Can you please add this? This would be a great feature especially for legit cheating. Thanks! (I tried to but I know nothing about coding so I just stopped doing it when I got a lot of errors) Hope you understand. Thanks!

#956

**Comment by xAkiraMiura** [comment]
> 
> 
> > #938 #859 #773 #456
> 
> Auto Edge Jump and Auto Jump-Bug is different... just saying...

i was specifically searching for jump bug, i saw like 3 edge jumps along the way but either way there are too many issues about jump bug and edge jump.
