### ISSUE TITLE
Fake Open Case

### ISSUE THREAD

**Issue by Chopard** [danielkrupinski/Osiris#955]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/272461-fake.html

Does anyone have a desire to deal with this? Great feature

**Comment by xAkiraMiura** [comment]
just type it into the fake ban area, set the color, disconnect, and reconnect to the server.
also why did you react to your own post

**Comment by VeLocityYT** [comment]
> just type it into the fake ban area, set the color, disconnect, and reconnect to the server.
> also why did you react to your own post

the problem is, if you open a case it show many different color per sentence

**Comment by Chopard** [comment]
> just type it into the fake ban area, set the color, disconnect, and reconnect to the server.
> also why did you react to your own post

[https://youtu.be/iAJlTpfLCCg](url)

**Comment by AbdallahMehiz** [comment]
You need to get an inventory changer,

**Comment by xAkiraMiura** [comment]
False. its literally just a message, stop spreading misinformation.

**Comment by tirziz** [comment]
I do need this in my life :-D
