### ISSUE TITLE
MemJect

### ISSUE THREAD

**Issue by travispresk0** [danielkrupinski/Osiris#958]
how do I use this with memject? im new to coding and all i can do now is compile and edit some lines. and now im stuck on converting this dll to array of bytes (i really dont know what im doing, i am also stuck in trying to know how to use daniel's python script ) so i can put it in memject.cpp as a binary i think

**Comment by ifoverload** [comment]
use HxD -> open your compiled dll -> ctrl+a(select all) -> Edit, Copy as, C
there go your aob this is also in the readme.
also what's wrong with another injector? personally only xenos seems like **"**detected**"**

**Comment by xAkiraMiura** [comment]
having to hex edit your dll into your injector **every single time** it updates is very annoying, why dont you just use a normal injector.

you could be a normal person and use a normal injector like https://github.com/danielkrupinski/Inflame

also why did you open the issue on osiris and not on MemJect's page? this isnt dll specific but is memject specific, so the issue should have been there.
