### ISSUE TITLE
[Code issue] "T" and "ConVar*".

### ISSUE THREAD

**Issue by rosesware** [danielkrupinski/Osiris#959]
```
void Misc::lefthandKnife() noexcept
{
	static auto lefthandKnife = interfaces.cvar->findVar("cl_righthand");

	bool lefthandKnife = static_cast<bool>(config.misc.lefthandKnife);
	if (const auto localPlayer = interfaces.entityList->getEntity(interfaces.engine->getLocalPlayer())) {
		if (const auto activeWeapon = localPlayer->getActiveWeapon(); activeWeapon && activeWeapon->getClientClass()->classId == ClassId::Knife)
			lefthandKnife->setValue(config.misc.lefthandKnife ? config.misc.lefthandKnife : 1);
	}
}
```

So this is the code, (I think it's to more easy to make this feature but anyways).
I'm getting the error [C2040](https://docs.microsoft.com/pt-pt/cpp/error-messages/compiler-errors-1/compiler-error-c2040?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DPT-BR%26k%3Dk(C2040)%26rd%3Dtrue&view=vs-2019), something like "'lefthandKnife': 'bool' differs in levels of 'T'".
If you know who to fix, thanks.

![Sem nome](https://user-images.githubusercontent.com/48736150/71941825-09b53900-31b3-11ea-94f5-087e9e32d219.png)

**And by the way, I'm not _paster_ and even a coder, I'm just trying to add this feature by my self.**

**Comment by xAkiraMiura** [comment]
findVar returns a ConVar pointer so try using `ConVar*` instead of `auto`, could be a problem with the compiler not knowing what the return type is due to this:

    class Cvar {
    public:
        constexpr auto findVar(const char* name) noexcept
        {
            return callVirtualMethod<ConVar*, const char*>(this, 15, name);
        }
    };

i think the vc++ compiler assumed it was a boolean function so your auto got set to a bool but then it changed its mind to a ConVar* apon seeing the vfunc call.

**Comment by rosesware** [comment]
Sorry, you are talking Chinese with me... 😞 
If you can be more exactly saying what I have to change, I appreciate.

**Comment by MinecraftGoodGame** [comment]
Replace "auto" with "ConVar*"

**Comment by woah1337** [comment]
You have 2 variables with the same name lol

**Comment by rosesware** [comment]
https://github.com/danielkrupinski/Osiris/pull/957/commits/2394e9aa0f450ec7106f0ac9daa938d3ccef975d

**Comment by xAkiraMiura** [comment]
ah, i didnt see the second declaration of it.
im pretty sure that intelisense complains about declaring something multiple times so how did you not get a warning for it?
