### ISSUE TITLE
FPS drop and game crashes.

### ISSUE THREAD

**Issue by rosesware** [danielkrupinski/Osiris#966]
I just need to know if you guys, are having FPS drop and crashes randomly?

**Comment by ZPDMiller** [comment]
No

**Comment by xAkiraMiura** [comment]
FPS will drop when using any cheat, crashes however are not normal. 
Are you able to reproduce what caused the crash?

**Comment by rosesware** [comment]
> Are you able to reproduce what could have caused the crash?

I really don't know, that is the reason why I posted this issue.
