### ISSUE TITLE
what is edge jump?

### ISSUE THREAD

**Issue by EJianZQ** [danielkrupinski/Osiris#967]
i test it for long time,but who can tell me what is edge jump??

**Comment by ZPDMiller** [comment]
Auto jumps whenever you're near an edge and about to fall off

**Comment by woah1337** [comment]
![Screenshot_20200112-041425_Chrome](https://user-images.githubusercontent.com/40292926/72211481-165ac980-34f2-11ea-866e-cf2077e85494.jpg)

**Comment by xAkiraMiura** [comment]
could we add tooltips to the menu so this stops? i think dear imgui supports it.

**Comment by ZPDMiller** [comment]
Quite funny you say that, I'm currently adding tooltips to my fork, someone should make a PR for it

**Comment by xAkiraMiura** [comment]
i think only the fork's owner can make a pr.
