### ISSUE TITLE
Wrong Build

### ISSUE THREAD

**Issue by ghost** [danielkrupinski/Osiris#968]
What if i build in Debug not in Release? i forgot to change it.

**Comment by ZPDMiller** [comment]
Then change it to Release and rebuild it

**Comment by rosesware** [comment]
> What if i build in Debug not in Release? i forgot to change it.

No problem I think, if you don't have errors when compiling, but it's recommended using "Release".

**Comment by xAkiraMiura** [comment]
building as debug makes includes debug symbols into your dll, super detectible but vac doesnt seem to notice them.
it also makes your dll much larger so a longer injection time and takes up more ram.
the code will be less optimized than release mode so it will take more cpu time.
