### ISSUE TITLE
[suggestion] Aimbot aim all parts

### ISSUE THREAD

**Issue by tacticalNukes** [danielkrupinski/Osiris#97]
Make a target for the aimbot were it aims at the seen part of the body for example if only the body is peeking then shoot the body and if the whole body is seen shoot the part that does most damage.

**Comment by effexcs** [comment]
That would be called nearest hitbox

**Comment by tacticalNukes** [comment]
Yeh thats what I meant thanks

**Comment by danielkrupinski** [comment]
It was added in 396de9f2f563b804ce8bdd0a4b480fd4fcc2e2e9.
