### ISSUE TITLE
How can you make the hitmarker crosshair the classic "X"?

### ISSUE THREAD

**Issue by fangshang132** [danielkrupinski/Osiris#974]
title

**Comment by Bywnb** [comment]
do yourself and pull requests

**Comment by fangshang132** [comment]
cant..

**Comment by xAkiraMiura** [comment]
i dont remember the hitmarker getting merged, i think this should be an issue on[ ZerGo0's fork](https://github.com/ZerGo0/Osiris/) so he can add it. (or you could comment on his pull request, #824)

**Comment by fangshang132** [comment]
@xAkiraMiura gave this a go and it wasnt doing anything but ill try again, its been like 3 weeks since i last tried.

**Comment by xAkiraMiura** [comment]
did you make sure to enable it? it's not on by default.

**Comment by fangshang132** [comment]
i get this error when i try adding it;
![https://i.imgur.com/noXIv3e.png]()

**Comment by MinecraftGoodGame** [comment]
change width to screenWidth and height to screenHeight

**Comment by fangshang132** [comment]
is there any way to add a fade out as it just dissapears

**Comment by anonymouschicken1111** [comment]
> is there any way to add a fade out as it just dissapears

You'd have to draw iterate thru the alpha function over the course of some time
