### ISSUE TITLE
Please add Tesla and bullet tracers !!

### ISSUE THREAD

**Issue by dispacc436** [danielkrupinski/Osiris#978]
please !

**Comment by notgoodusename** [comment]
what is tesla?

**Comment by Straightplus** [comment]
the "pasted bullet tracer from that noobdog scandale"

**Comment by notgoodusename** [comment]
> the "pasted bullet tracer from that noobdog scandale"

what noobdog scandale?

**Comment by agshaidun** [comment]
Zeus bullet glitch?

**Comment by Straightplus** [comment]
https://www.youtube.com/watch?v=U384cL8Mb0k&t=204s yeah

**Comment by Straightplus** [comment]
part 2 https://www.youtube.com/watch?v=97l9ejRE_UU

(great content)
