### ISSUE TITLE
Silent aimbot while walking/bhopping

### ISSUE THREAD

**Issue by Straightplus** [danielkrupinski/Osiris#981]
The whole body turns around when you use silent aimbot and then you watch one way and bhop/walk another its just very frustrating maybe add so it just does a quick flick? and then back to the cursor x/y

**Comment by danielkrupinski** [comment]
Enable "Fix movement" in "Misc".

**Comment by danielkrupinski** [comment]
Enable "Fix movement" in "Misc".

**Comment by Straightplus** [comment]
cool thanks

**Comment by Straightplus** [comment]
doesent seem to work?

**Comment by ZPDMiller** [comment]
I tried it and it works for me

**Comment by Straightplus** [comment]
what code do you have for it?

**Comment by ZPDMiller** [comment]
Same one as Daniel's

**Comment by Straightplus** [comment]
okay

**Comment by Straightplus** [comment]
hmmm
