### ISSUE TITLE
ADD Pls

### ISSUE THREAD

**Issue by ArchiiJoker** [danielkrupinski/Osiris#983]
Pls Add legith anti aim and fix normal anti aim to swipe and jairl

**Comment by notgoodusename** [comment]
jairl?what is that?

**Comment by ArchiiJoker** [comment]
jitler sr

**Comment by xAkiraMiura** [comment]
1. undescriptive title
2. what is legith
3. what is swipe
4. what is jairl sr

[please read this](https://stackoverflow.com/help/how-to-ask). tl;dr:
> Write a title that summarizes the specific problem
> * Pretend you're talking to a busy colleague and have to sum up your entire question in one sentence
> * Spelling, grammar and punctuation are important!
