### ISSUE TITLE
Legit AA

### ISSUE THREAD

**Issue by TMCmaster420** [danielkrupinski/Osiris#988]
can we focus on the legit aa please. I am a new comer to this so i can fix it my self yet.

**Comment by agshaidun** [comment]
You have source?

**Comment by xAkiraMiura** [comment]
source!??! source!?! source!?!?! source?!?!
stop pasting and write an original aa please.

**Comment by agshaidun** [comment]
> 
> 
> source!??! source!?! source!?!?! source?!?!
> stop pasting and write an original aa please.

I need idea nigga . Listen here WEABOO. You doesn't even make any improvement to this project. All you know is COMPLAIN COMPLAIN COMPLAIN COMPLAIN.

I wonder what do you look like in real life LOL

**Comment by agshaidun** [comment]
> 
> 
> source!??! source!?! source!?!?! source?!?!
> stop pasting and write an original aa please.

I need idea nigga . Listen here WEABOO. You doesn't even make any improvement to this project. All you know is COMPLAINT COMPLAINT COMPLAINT COMPLAINT.

I wonder what do you look like in real life LOL

**Comment by effex1337** [comment]
There totally aren't a 1000 links about legit desync.

**Comment by effex1337** [comment]
> > source!??! source!?! source!?!?! source?!?!
> > stop pasting and write an original aa please.
> 
> I need idea nigga . Listen here WEABOO. You doesn't even make any improvement to this project. All you know is COMPLAINT COMPLAINT COMPLAINT COMPLAINT.
> 
> I wonder what do you look like in real life LOL

There totally aren't a 1000 links about legit desync.

**Comment by effex1337** [comment]
> source!??! source!?! source!?!?! source?!?!
> stop pasting and write an original aa please.

How do you expect someone to write their own legit aa if they're here leeching here

**Comment by xAkiraMiura** [comment]
> 
> > ~snip
> 
> I need idea nigga . Listen here WEABOO. You doesn't even make any improvement to this project. All you know is COMPLAINT COMPLAINT COMPLAINT COMPLAINT.
> 
> I wonder what do you look like in real life LOL

"I need idea" is grammatically incorrect.
remove the space before period `nigga.`*
its `weeaboo`* with two E's 
bet, i've been helping people with bugs in the issues. (also #989)
"Doesn't" should be `Haven't`*
"Make" should be `Made`*
"improvement" should be `Improvements`*
"COMPLAINT" should be "COMPLAIN"* x4

Use your words next time buddy.

@effex1337 the project may be infested with skids but I still want to keep open source alive.

**Comment by tirziz** [comment]
Lol why so much hate , share love plz

**Comment by thomas0aotian** [comment]
@xAkiraMiura Looking the native English speaker is bragging about his native language skills again. Good thing is that we are basically all bi or muilti-langual here. And u only know English.

**Comment by agshaidun** [comment]
Creep

**Comment by xAkiraMiura** [comment]
ah yes all the skids mad that someone told them to be actual programmers and stop stealing code.

**Comment by chke24** [comment]
Sorry but i just wanted to ask how, so i can learn it. But that's wrong i guess.

**Comment by xAkiraMiura** [comment]
game hacking is an advanced subject that requires lots of experience (sometimes on the scale of years) to understand, for instance you need to know:
- Memory management
- Pointers
- DLL Injection
- Function hooking
and much more, game hacking isn't beginner friendly in the first place and trying to learn off of source isn't effective. 

If you actually want to learn instead of just cheat then I would recommend creating small projects to learn [the basics of C++](https://www.learncpp.com/) and how the NT kernal works.

I'm not against learning, I'm just against stealing code.

**Comment by thomas0aotian** [comment]
Wow, big wise man here. I thought the entire coding thing is all about copying and learnning programming techniques. Nobody knows everything when they start learning. And of course wise man Mr. Akira is not one of our normal people. You definitely didn't learn how to speak by imitating others, you just know everything when u r borned. Am I right. Wise man akira?

**Comment by xAkiraMiura** [comment]
I learned though experimenting with code and reading the documentation. I only got into game hacking once I had over a year of experience in regular programming. [Want proof?](https://gitlab.com/xAkiraMiura)
I gave methods on how to start learning to code. Of course nobody knows everything instantly, if that's what I thought then I wouldn't help people improve.

`u r borned`??? <- either learn grammar or stop trying to use slang (short language).

Please, don't listen to whatever thomas says, they spread misinformation and steal code. It's counter-productive to learning.

**Comment by woah1337** [comment]
WEABOO your opinion is automatically invalidated

**Comment by MAMAdzwoni** [comment]
> 
> 
> WEABOO your opinion is automatically invalidated

says the person with anime prof pic
