### ISSUE TITLE
Plastic Chams just making disappears

### ISSUE THREAD

**Issue by ifoverload** [danielkrupinski/Osiris#990]
as titled^^
ss: https://prnt.sc/qopvu1

**Comment by danielkrupinski** [comment]
#901

**Comment by ifoverload** [comment]
> #901

oh thankyou its working now
do you know what material to draw a chams like this: https://prnt.sc/qoq3yl ?
the plastic just not what i expected ;D

**Comment by xAkiraMiura** [comment]
thats flat chams with an inward glow or special cham effect.

**Comment by notgoodusename** [comment]
nah fam that the pearlesent effect

**Comment by Straightplus** [comment]
yeah i agree with @notgoodusename i think its just a static thing like the case hardened so you just plaster it around the player

**Comment by xAkiraMiura** [comment]
you can configure a glow to be similar with style 2 however it won't show up through walls. I don't know if override material allows a material like that or if they double rendered the model.

> yeah i agree with @notgoodusename i think its just a static thing like the case hardened so you just plaster it around the player

case hardened is a texture, it has nothing to do with materials or rendering.
