### ISSUE TITLE
Fix Bones

### ISSUE THREAD

**Issue by Lorekin** [danielkrupinski/Osiris#991]
![image](https://user-images.githubusercontent.com/26692817/72618755-da3dc380-394c-11ea-8e6a-ccaa92c72bb3.png)
![image](https://user-images.githubusercontent.com/26692817/72618786-efb2ed80-394c-11ea-9539-121bd2102db7.png)

**Comment by Straightplus** [comment]
am i the only one not seeing the difrecence?

**Comment by TheSolenOne** [comment]
> am i the only one not seeing the difrecence?

u stupid? or blind?

**Comment by notgoodusename** [comment]
> > am i the only one not seeing the difrecence?
> 
> u stupid? or blind?

idk what you mean i only see 2 bots one apart from each other

**Comment by notgoodusename** [comment]
and op hasnt said anything about an issue

**Comment by Lorekin** [comment]
I put the head he aims Sternum and vice versa

**Comment by TheSolenOne** [comment]
> and op hasnt said anything about an issue

what is the problem of looking at the specially allocated part of the cheat?
sternum - head
head - sternum

**Comment by notgoodusename** [comment]
oh, i see

**Comment by Lorekin** [comment]
And this seems to be a rare case, because my friend is fine, although I compiled both of us

**Comment by Straightplus** [comment]
Oh i see but you dont have to be rude about it.

**Comment by xAkiraMiura** [comment]
misc > fix bone matrix?
might be a purely aesthetic thing and only relates to the skeleton esp.

**Comment by danielkrupinski** [comment]
Please verify game files and launch local game on standard map (e.g. de_mirage) and check if the issue persists.

**Comment by danielkrupinski** [comment]
@Lorekin Have you fixed it?

**Comment by Lorekin** [comment]
@danielkrupinski yes
