### ISSUE TITLE
LBY Breaker

### ISSUE THREAD

**Issue by valveanticheat** [danielkrupinski/Osiris#992]
i am a newcomer to coding. so i don't now how to make a lBY breaker myself. if someone could explain a show me how to that would be nice.

**Comment by notgoodusename** [comment]
people wont give you a tutorial to make a lby breaker, thats pasting

**Comment by valveanticheat** [comment]
> people wont give you a tutorial to make a lby breaker, thats pasting

srry didn't now

**Comment by xAkiraMiura** [comment]
cheating isn't beginner friendly. it requires low level knowledge of how memory is managed in the system, how windows NT works, and lots of knowledge about C++ or a langauge that can access memory.

If you're going into programming just to cheat, it's not worth it and won't be for a long time. Try making some other projects in C++ first to get a grasp of how it all works in general.

Also if you only give a concept without actual code behind it then it's not pasting, only once you give them code can they paste.
