### ISSUE TITLE
Movement Check for Backtrack Chams

### ISSUE THREAD

**Issue by dctrlight** [danielkrupinski/Osiris#995]
Anyone know how to make it so the backtrack chams only draw if the enemy is moving?
thanks in advance

**Comment by notgoodusename** [comment]
u could just
auto vec = entity->velocity().lenght()
if(vec >0.1)
{
render
}

**Comment by PerezhoginViktor** [comment]
I haven't thought about this hahaha)

**Comment by PerezhoginViktor** [comment]
> Anyone know how to make it so the backtrack chams only draw if the enemy is moving?
> thanks in advance

`
if (config.chams[BACKTRACK].materials[i].enabled && config.backtrack.enabled) {
                auto record = &Backtrack::records[info.entityIndex];
                if (record && record->size() && Backtrack::valid(record->front().simulationTime))
				{
					if (applied && entity->velocity() > 0.0f)
					{
						hooks.modelRender.callOriginal<void, void*, void*, const ModelRenderInfo&, matrix3x4*>(21, ctx, state, info, customBoneToWorld);
						applyChams(config.chams[BACKTRACK].materials[i], false, entity->health());
						if (config.backtrack.drawAllTicks)
						{
							for (int x = 0; x < record->size(); x++) {
								hooks.modelRender.callOriginal<void, void*, void*, const ModelRenderInfo&, matrix3x4*>(21, ctx, state, info, record->at(x).matrix);
							}
						}
						else
						{
							hooks.modelRender.callOriginal<void, void*, void*, const ModelRenderInfo&, matrix3x4*>(21, ctx, state, info, record->back().matrix);
						}
						interfaces.modelRender->forceMaterialOverride(nullptr);
						applied = true;
					}
                }
            }
`

**Comment by PerezhoginViktor** [comment]
> Anyone know how to make it so the backtrack chams only draw if the enemy is moving?
> thanks in advance

**if (config.chams[BACKTRACK].materials[i].enabled && config.backtrack.enabled) {
                auto record = &Backtrack::records[info.entityIndex];
                if (record && record->size() && Backtrack::valid(record->front().simulationTime))
				{
					if (applied && entity->velocity() > 0.0f)
					{
						hooks.modelRender.callOriginal<void, void*, void*, const ModelRenderInfo&, matrix3x4*>(21, ctx, state, info, customBoneToWorld);
						applyChams(config.chams[BACKTRACK].materials[i], false, entity->health());
						if (config.backtrack.drawAllTicks)
						{
							for (int x = 0; x < record->size(); x++) {
								hooks.modelRender.callOriginal<void, void*, void*, const ModelRenderInfo&, matrix3x4*>(21, ctx, state, info, record->at(x).matrix);
							}
						}
						else
						{
							hooks.modelRender.callOriginal<void, void*, void*, const ModelRenderInfo&, matrix3x4*>(21, ctx, state, info, record->back().matrix);
						}
						interfaces.modelRender->forceMaterialOverride(nullptr);
						applied = true;
					}
                }
            }**

Replace with this in chams.cpp
