### ISSUE TITLE
Change deagle spinner to 100% chance on inspect instead of constantly spinning

### ISSUE THREAD

**Issue by pointydev** [danielkrupinski/Osiris#997]
Heya,

So the deagle spinner option in visuals is cool and all, but it'd be much better imo if it was user controlled instead of constantly spinning. No idea how to implement, so thought I'd suggest.

Thanks,
Pointy

**Comment by tirziz** [comment]
I think you can refer to this pull request #389 .

**Comment by ClaudiuHKS** [comment]
Yes, it would be nice to have two different **Deagle Spinner** options.

# 1. **Always Spin**
# 2. **User Controlled**

Unfortunately, I've no idea how to implement such thing.

**Comment by notgoodusename** [comment]
taking a look at this site
https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events#inspect_weapon
you can get if the client is inspecting the weapon and execute the command
`
        if (!strcmp(event->getName(), "inspect_weapon")) { //we get the if someone is inspecting
auto client = interfaces.engine->getPlayerForUserID(event->getInt("userid")); // the person that is inspecting the weapon
if(client == interfaces.engine->getLocalPlayer()){ // if its equal to localplayer(us)
//code goes here
}
        }
`

**Comment by effex1337** [comment]
U dont have to over complicate things its a 1-2 line fix with the current codes.

**Comment by effex1337** [comment]
https://github.com/danielkrupinski/Osiris/pull/1001
