### ISSUE TITLE
How to change all the TT/CT models?

### ISSUE THREAD

**Issue by arthures11** [danielkrupinski/Osiris#998]
Like i don't want only to change Visuals for myself but also WHOLE team. Is there any way to do that?

**Comment by danielkrupinski** [comment]
Just loop through player entities and apply model by their team.

**Comment by arthures11** [comment]
So i need to change source code and compile?

**Comment by ClaudiuHKS** [comment]
How else ..

**Comment by arthures11** [comment]
Not into coding so gotta learn stuff, probably will take some time. Anyways, thought it would be a cool feature to add, helpful on servers with different models so you can swap to deafult/any other model to actually make aimbot work propertly.

**Comment by arthures11** [comment]
ah nevermind, it just visuals so it obviously won't work like that, not sure why i thought like that
