### ISSUE TITLE
Filtering Fonts + ESP Flags

### ISSUE THREAD

**Issue by dctrlight** [danielkrupinski/Osiris#999]
Im pretty sure most people would prefer there be only a small amount of fonts or even just 1 font, most of the fonts right now are just either too big or just utter nonsense.

ESP Flags like flashed, defusing, armor etc would be really nice aswell

**Comment by ClaudiuHKS** [comment]
I agree about ESP.

**Comment by WolfOGG** [comment]
we need a bomb esp as well.

**Comment by dctrlight** [comment]
Still most fonts are either nothing, random symbols or way too big

**Comment by danielkrupinski** [comment]
Check out [GOESP](https://github.com/danielkrupinski/GOESP) and let me know if that font selection method satisfies you.

**Comment by NekoRem** [comment]
It would be nice to have a list of font names instead of a number
